### ISSUE TITLE
Install theano via conda

### ISSUE THREAD

**Issue by devcogcomp** [conda/conda#6102] opened 2017-10-07 18:11 UTC
I tried to install theano via conda:

devcogcomp@LinuxBox:~$ conda install -c conda-forge theano pygpu

and got this:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.23
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/devcogcomp/anaconda3  (writable)
    default environment : /home/devcogcomp/anaconda3
       envs directories : /home/devcogcomp/anaconda3/envs
                          /home/devcogcomp/.conda/envs
          package cache : /home/devcogcomp/anaconda3/pkgs
                          /home/devcogcomp/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Linux/4.10.0-35-generic debian/stretch/sid glibc/2.24    
                UID:GID : 1000:1000

`$ /home/devcogcomp/anaconda3/bin/conda install -c conda-forge theano pygpu`

    Traceback (most recent call last):
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/devcogcomp/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1505745053.518 for timestamp

**Comment by msarahan** [comment] 2017-10-08 15:52
Duplicate of #6096. closing to consolidate discussion.

**Closed by msarahan** 2017-10-08 15:52 UTC
