### ISSUE TITLE
Wrong version of dependency installed on linux

### ISSUE THREAD

**Issue by guyer** [conda/conda#7125] opened 2018-04-05 03:18 UTC
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

When I install our `fipy` package from my `guyer` channel, the version of one of the dependencies installed is , `gmsh-2.15.0-0`, even though version `gmsh-3.0.6-1` is available on the same channel.

When the prerequesites for `fipy` are installed directly, then `gmsh-3.0.6-1` *is* installed. 

I can discern no obvious reason for this difference in resolving the dependency tree, nor can I find any sign of a way to visualize conda's decision matrix.

    
### Steps to Reproduce

See [verbose output](https://gist.github.com/guyer/f5dd69677c9510db6ea3ee06e87e6600#file-conda-fipynomkl-txt) from
```
conda create --yes --quiet -vvv -n fipy10 --channel guyer --channel conda-forge fipy nomkl
```
vs [verbose output](https://gist.github.com/guyer/f5dd69677c9510db6ea3ee06e87e6600#file-conda-fipydependencies-txt) from
```
conda create --yes --quiet -vvv -n fipy12 --channel guyer --channel conda-forge python numpy scipy gmsh pysparse trilinos mpi4py matplotlib mayavi nomkl
```

## Expected Behavior

Install the newest version of the dependency, `gmsh`.

Barring (or in addition to) that, provide a mechanism for understanding why conda chooses what it chooses.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /users/guyer/.condarc
 populated config files : /users/guyer/.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 2.7.12.final.0
       base environment : /data/guyer/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /data/guyer/miniconda2/pkgs
                          /users/guyer/.conda/pkgs
       envs directories : /data/guyer/miniconda2/envs
                          /users/guyer/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/2.7.12 Linux/3.16.0-5-amd64 debian/8 glibc/2.19
                UID:GID : 17723:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /users/guyer/.condarc <==
changeps1: True
always_yes: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /data/guyer/miniconda2/envs/fipy10:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.1.18                     0    conda-forge
certifi                   2018.1.18                py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.22                       0    conda-forge
expat                     2.2.5                         0    conda-forge
fipy                      3.1.3            py36h265d7a0_4    guyer
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gmsh                      2.15.0                        0    guyer
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
icu                       58.2                          0    conda-forge
jpeg                      9b                            2    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libgfortran               3.0.0                         1    defaults
libgfortran-ng            7.2.0                hdf63c60_3    defaults
libiconv                  1.15                          0    conda-forge
libopenblas               0.2.20               h9ac9557_4    defaults
libpng                    1.6.34                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
ncurses                   5.9                          10    conda-forge
nomkl                     1.0                           0    defaults
numpy                     1.14.2          py36_nomklh2b20989_1  [nomkl]  defaults
openblas                  0.2.20                        7    conda-forge
openssl                   1.0.2n                        0    conda-forge
pcre                      8.41                          1    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
python                    3.6.5                         0    conda-forge
python-dateutil           2.7.2                      py_0    conda-forge
pytz                      2018.3                     py_0    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
scipy                     1.0.1           py36_nomklh9d22d0a_0  [nomkl]  defaults
setuptools                39.0.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.1                    py36_1    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```
</p></details>

**Comment by mbargull** [comment] 2018-04-05 08:44
I believe this is a duplicate of https://github.com/conda/conda/issues/7112. I still don't know what the reason for this is.
Thanks for raising this issue, it's good to have multiple data points.

**Closed by mbargull** 2018-04-05 08:44 UTC

**Comment by mbargull** [comment] 2018-04-05 08:51
Just to highlight the feature request part of the issue:
> I can discern no obvious reason for this difference in resolving the dependency tree, nor can I find any sign of a way to visualize conda's decision matrix.

> Barring (or in addition to) that, provide a mechanism for understanding why conda chooses what it chooses.
