### ISSUE TITLE
ImportError: cannot import name dist2quad

### ISSUE THREAD

**Issue by nullkatar** [conda/conda#5056] opened 2017-04-14 13:59 UTC
i gust wrote !conda install seaborn and this occured:

Traceback (most recent call last):
  File "C:\Users\Leon\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Leon\Anaconda2\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main)
  File "C:\Users\Leon\Anaconda2\lib\site-packages\conda\exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\Leon\Anaconda2\lib\site-packages\conda\exceptions.py", line 437, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\Leon\Anaconda2\lib\site-packages\conda\exceptions.py", line 396, in get_info
    from conda.cli import conda_argparse
  File "C:\Users\Leon\Anaconda2\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\Leon\Anaconda2\lib\site-packages\conda\cli\common.py", line 15, in <module>
    from ..install import dist2quad
ImportError: cannot import name dist2quad

**Comment by kalefranz** [comment] 2017-04-21 05:36
Interesting.  Unfortunately we're not seeing the real stack trace or cause of the error.  You're using python 2.7 as the conda python interpreter, which unfortunately doesn't chain exceptions.

For the purposes of this bug report, I think it will be fixed with https://github.com/conda/conda/pull/5090.  And in that case a duplicate of #5039.

**Closed by kalefranz** 2017-04-21 05:36 UTC
Labels: source:community, type:bug
