### ISSUE TITLE
ResolvePackageNotFound when creating env from exported environment.yml

### ISSUE THREAD

**Issue by maxwellmckinnon** [conda/conda#7311] opened 2018-05-19 00:59 UTC
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
Running `conda env create -f environment.yml`, many packages fail from ResolvePackageNotFound.
The environment.yml was exported from a machine where the environment was working fine.

### Steps to Reproduce

```
conda env create -f environment.yml

Solving environment: failed

ResolvePackageNotFound:
  - pyyaml==3.12=py27ha7932d0_1
  - msgpack-python==0.5.6=py27h04f5b5a_0
  - click==6.7=py27h2b86a94_0
  - libcxxabi==4.0.1=hebd6815_0
  - yaml==0.1.7=hc338f04_2
  - cytoolz==0.9.0.1=py27h1de35cc_0
  - partd==0.3.8=py27h7560dbf_0
  - psutil==5.4.5=py27h1de35cc_0
  - libcxx==4.0.1=h579ed51_0
  - locket==0.2.0=py27ha10513d_1
  - futures==3.2.0=py27h1b80678_0
  - zict==0.1.3=py27h5fff8b1_0
  - singledispatch==3.4.0.3=py27he22c18d_0
  - jinja2==2.10=py27h70b8dc5_0
  - libgfortran==3.0.1=h93005f0_2
  - tblib==1.3.2=py27ha684fc4_0
  - backports_abc==0.5=py27h6972548_0
  - bcolz==1.1.2=py27_0
```

## Expected Behavior
All packages installed correctly

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : base
    active env location : /root/anaconda2
            shell level : 1
       user config file : /root/.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.4.1
         python version : 2.7.14.final.0
       base environment : /root/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /root/anaconda2/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda2/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.14 Linux/4.8.0-58-generic ubuntu/14.04 glibc/2.19
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>
nothing for above*

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /root/anaconda2:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h08a7f0c_0    defaults
alabaster                 0.7.10           py27he5a193a_0    defaults
anaconda                  custom           py27h4a00acb_0    defaults
anaconda-client           1.6.9                    py27_0    defaults
anaconda-navigator        1.7.0                    py27_0    defaults
anaconda-project          0.8.2            py27h236b58a_0    defaults
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.1                    py27_0    defaults
astropy                   2.0.3            py27h14c3975_0    defaults
attrs                     17.4.0                   py27_0    defaults
babel                     2.5.3                    py27_0    defaults
backports                 1.0              py27h63c9359_1    defaults
backports.functools_lru_cache 1.4              py27he8db605_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2    defaults
backports_abc             0.5              py27h7b3c97b_0    defaults
beautifulsoup4            4.6.0            py27h3f86ba9_1    defaults
bitarray                  0.8.1            py27h14c3975_1    defaults
bkcharts                  0.2              py27h241ae91_0    defaults
blaze                     0.11.3           py27h5f341da_0    defaults
bleach                    2.1.2                    py27_0    defaults
bokeh                     0.12.13          py27h5233db4_0    defaults
boto                      2.48.0           py27h9556ac2_1    defaults
bottleneck                1.2.1            py27h21b16a3_0    defaults
bzip2                     1.0.6                h9a117a8_4    defaults
ca-certificates           2018.03.07                    0    defaults
cairo                     1.14.12              h77bcde2_0    defaults
cdecimal                  2.3              py27h14c3975_3    defaults
certifi                   2018.4.16                py27_0    defaults
cffi                      1.11.4           py27h9745a5d_0    defaults
chardet                   3.0.4            py27hfa10054_1    defaults
click                     6.7              py27h4225b90_0    defaults
cloudpickle               0.5.2                    py27_1    defaults
clyent                    1.2.2            py27h7276e6c_1    defaults
colorama                  0.3.9            py27h5cde069_0    defaults
conda                     4.5.4                    py27_0    defaults
conda-build               3.4.1                    py27_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py27hf052a9d_0    defaults
configparser              3.5.0            py27h5117587_0    defaults
contextlib2               0.5.5            py27hbf4c468_0    defaults
cryptography              2.1.4            py27h6697b16_0    defaults
curl                      7.58.0               h84994c4_0    defaults
cycler                    0.10.0           py27hc7354d3_0    defaults
cython                    0.27.3           py27hc56b35e_0    defaults
cytoolz                   0.9.0            py27h14c3975_0    defaults
dask                      0.16.1                   py27_0    defaults
dask-core                 0.16.1                   py27_0    defaults
datashape                 0.5.4            py27hf507385_0    defaults
dbus                      1.12.2               hc3f9b76_1    defaults
decorator                 4.2.1                    py27_0    defaults
distributed               1.20.2                   py27_0    defaults
docutils                  0.14             py27hae222c1_0    defaults
entrypoints               0.2.3            py27h502b47d_2    defaults
enum34                    1.1.6            py27h99a27e9_1    defaults
et_xmlfile                1.0.1            py27h75840f5_0    defaults
expat                     2.2.5                he0dffb1_0    defaults
fastcache                 1.0.2            py27h14c3975_2    defaults
filelock                  2.0.13           py27h61a9c69_0    defaults
flask                     0.12.2           py27h6d5c1cd_0    defaults
flask-cors                3.0.3            py27h1a8a27f_0    defaults
fontconfig                2.12.4               h88586e7_1    defaults
freetype                  2.8                  hab7d2ae_1    defaults
funcsigs                  1.0.2            py27h83f16ab_0    defaults
functools32               3.2.3.2          py27h4ead58f_1    defaults
futures                   3.2.0            py27h7b459c0_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.2.2            py27h475ea6a_0    defaults
glib                      2.53.6               h5d9569c_2    defaults
glob2                     0.6              py27hcea9cbd_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py27h4cf3fa8_2    defaults
graphite2                 1.3.10               hf63cedd_1    defaults
greenlet                  0.4.12           py27hac09c53_0    defaults
grin                      1.2.1                    py27_4    defaults
gst-plugins-base          1.12.4               h33fb286_0    defaults
gstreamer                 1.12.4               hb53b477_0    defaults
h5py                      2.7.1            py27h2697762_0    defaults
harfbuzz                  1.7.4                hc5b324e_0    defaults
hdf5                      1.10.1               h9caa474_1    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1            py27h5233db4_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.6              py27h5722d68_1    defaults
imageio                   2.2.0            py27hf108a7f_0    defaults
imagesize                 0.7.1            py27hd17bf80_0    defaults
intel-openmp              2018.0.0             hc7b2577_8    defaults
ipaddress                 1.0.19                   py27_0    defaults
ipykernel                 4.8.0                    py27_0    defaults
ipython                   5.4.1                    py27_2    defaults
ipython_genutils          0.2.0            py27h89fb69b_0    defaults
ipywidgets                7.1.1                    py27_0    defaults
isort                     4.2.15           py27hcfa4749_0    defaults
itsdangerous              0.24             py27hb8295c1_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py27h2cc5433_0    defaults
jedi                      0.11.1                   py27_0    defaults
jinja2                    2.10             py27h4114e70_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                2.6.0            py27h7ed5aa4_0    defaults
jupyter                   1.0.0                    py27_4    defaults
jupyter_client            5.2.2                    py27_0    defaults
jupyter_console           5.2.0            py27hc6bee7e_1    defaults
jupyter_core              4.4.0            py27h345911c_0    defaults
jupyterlab                0.31.5                   py27_0    defaults
jupyterlab_launcher       0.10.2                   py27_0    defaults
lazy-object-proxy         1.3.1            py27h682c727_0    defaults
libcurl                   7.58.0               h1ad7b7a_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libpng                    1.6.34               hb9fc6fc_0    defaults
libsodium                 1.0.15               hf101ebd_0    defaults
libssh2                   1.8.0                h9cfc8f7_4    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.9                h28f6b97_0    defaults
libtool                   2.4.6                h544aabb_3    defaults
libxcb                    1.12                 hcd93eb1_4    defaults
libxml2                   2.9.7                h26e45fe_0    defaults
libxslt                   1.1.32               h1312cb7_0    defaults
llvmlite                  0.21.0           py27h6dad3f9_0    defaults
locket                    0.2.0            py27h73929a2_1    defaults
lxml                      4.1.1            py27hf71bdeb_1    defaults
lzo                       2.10                 h49e0be7_2    defaults
markupsafe                1.0              py27h97b2822_1    defaults
matplotlib                2.1.2            py27h0e671d2_0    defaults
mccabe                    0.6.1            py27h0e7c7be_1    defaults
mistune                   0.8.3                    py27_0    defaults
mkl                       2018.0.1             h19d6760_4    defaults
mkl-service               1.1.2            py27hb2d42c5_4    defaults
mpc                       1.0.3                hec55b23_5    defaults
mpfr                      3.1.5                h11a74b3_2    defaults
mpmath                    1.0.0            py27h9669132_2    defaults
msgpack-python            0.5.1            py27h6bb024c_0    defaults
multipledispatch          0.4.9            py27h9b5f95a_0    defaults
navigator-updater         0.1.0            py27h0f9cd39_0    defaults
nbconvert                 5.3.1            py27he041f76_0    defaults
nbformat                  4.4.0            py27hed7f2b2_0    defaults
ncurses                   6.0                  h9df7e31_2    defaults
networkx                  2.1                      py27_0    defaults
nltk                      3.2.5            py27hec5f4de_0    defaults
nose                      1.3.7            py27heec2199_2    defaults
notebook                  5.4.0                    py27_0    defaults
numba                     0.36.2          np114py27he2868da_0    defaults
numexpr                   2.6.4            py27hd318778_0    defaults
numpy                     1.14.0           py27h3dfced4_1    defaults
numpydoc                  0.7.0            py27h9647a75_0    defaults
odo                       0.5.1            py27h9170de3_0    defaults
olefile                   0.45.1                   py27_0    defaults
openpyxl                  2.4.10                   py27_0    defaults
openssl                   1.0.2o               h20670df_0    defaults
packaging                 16.8             py27h5e07c7c_1    defaults
pandas                    0.22.0           py27hf484d3e_0    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py27h428e1e5_1    defaults
pango                     1.41.0               hd475d92_0    defaults
parso                     0.1.1            py27h718acc2_0    defaults
partd                     0.3.8            py27h4e55004_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.5             py27hefe4bee_0    defaults
pathlib2                  2.3.0            py27h6e9d198_0    defaults
patsy                     0.5.0                    py27_0    defaults
pcre                      8.41                 hc27e229_1    defaults
pep8                      1.7.1                    py27_0    defaults
pexpect                   4.3.1                    py27_0    defaults
pickleshare               0.7.4            py27h09770e1_0    defaults
pillow                    5.0.0            py27h3deb7b8_0    defaults
pip                       9.0.1            py27ha730c48_4    defaults
pip                       10.0.1                    <pip>
pixman                    0.34.0               hceecf20_3    defaults
pkginfo                   1.4.1            py27hee1a9ad_1    defaults
pluggy                    0.6.0            py27h1f4f128_0    defaults
ply                       3.10             py27hd6d9ae5_0    defaults
prompt_toolkit            1.0.15           py27h1b593e1_0    defaults
psutil                    5.4.3            py27h14c3975_0    defaults
ptyprocess                0.5.2            py27h4ccb14c_0    defaults
py                        1.5.2            py27h203d672_0    defaults
pycairo                   1.15.4           py27h1b9232e_1    defaults
pycodestyle               2.3.1            py27h904819d_0    defaults
pycosat                   0.6.3            py27ha4109ae_0    defaults
pycparser                 2.18             py27hefa08c5_1    defaults
pycrypto                  2.6.1            py27h14c3975_7    defaults
pycurl                    7.43.0.1         py27hb7f436b_0    defaults
pyflakes                  1.6.0            py27h904a57d_0    defaults
pygments                  2.2.0            py27h4a8b6f5_0    defaults
pylint                    1.8.2                    py27_0    defaults
pyodbc                    4.0.22           py27hf484d3e_0    defaults
pyopenssl                 17.5.0           py27hcee3be0_0    defaults
pyparsing                 2.2.0            py27hf1513f8_1    defaults
pyqt                      5.6.0            py27h4b1e83c_5    defaults
pysocks                   1.6.7            py27he2db6d2_1    defaults
pytables                  3.4.2            py27h1f7bffc_2    defaults
pytest                    3.3.2                    py27_0    defaults
python                    2.7.14              h1571d57_29    defaults
python-dateutil           2.6.1            py27h4ca5741_1    defaults
pytz                      2017.3           py27h001bace_0    defaults
pywavelets                0.5.2            py27hecda097_0    defaults
pyyaml                    3.12             py27h2d70dd7_1    defaults
pyzmq                     16.0.3           py27hc579512_0    defaults
qt                        5.6.2               h974d657_12    defaults
qtawesome                 0.4.4            py27hd7914c3_0    defaults
qtconsole                 4.3.1            py27hc444b0d_0    defaults
qtpy                      1.3.1            py27h63d3751_0    defaults
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py27hc5b0589_1    defaults
rope                      0.10.7           py27hfe459b0_0    defaults
ruamel_yaml               0.15.35          py27h14c3975_1    defaults
scandir                   1.6              py27hf7388dc_0    defaults
scikit-image              0.13.1           py27h14c3975_1    defaults
scikit-learn              0.19.1           py27h445a80a_0    defaults
scipy                     1.0.0            py27hf5f0f52_0    defaults
seaborn                   0.8.1            py27h633ea1e_0    defaults
send2trash                1.4.2                    py27_0    defaults
setuptools                38.4.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27h9bcb476_0    defaults
sip                       4.18.1           py27he9ba0ab_2    defaults
six                       1.11.0           py27h5f960f1_1    defaults
snowballstemmer           1.2.1            py27h44e2768_0    defaults
sortedcollections         0.5.3            py27h135218e_0    defaults
sortedcontainers          1.5.9                    py27_0    defaults
sphinx                    1.6.6                    py27_0    defaults
sphinxcontrib             1.0              py27h1512b58_1    defaults
sphinxcontrib-websupport  1.0.1            py27hf906f22_1    defaults
spyder                    3.2.6                    py27_0    defaults
sqlalchemy                1.2.1            py27h14c3975_0    defaults
sqlite                    3.22.0               h1bed415_0    defaults
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2    defaults
statsmodels               0.8.0            py27hc87d62d_0    defaults
subprocess32              3.2.7            py27h373dbce_0    defaults
sympy                     1.1.1            py27hc28188a_0    defaults
tblib                     1.3.2            py27h51fe5ba_0    defaults
terminado                 0.8.1                    py27_1    defaults
testpath                  0.3.1            py27hc38d2c4_0    defaults
tk                        8.6.7                hc745277_3    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   4.5.3                    py27_0    defaults
traitlets                 4.3.2            py27hd6ce930_0    defaults
typing                    3.6.2            py27h66f49e2_0    defaults
unicodecsv                0.14.1           py27h5062da9_0    defaults
unixodbc                  2.3.4                hc36303a_1    defaults
urllib3                   1.22             py27ha55213b_0    defaults
wcwidth                   0.1.7            py27h9e3e1ab_0    defaults
webencodings              0.5.1            py27hff10b21_1    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.30.0           py27h2bc6bb2_1    defaults
widgetsnbextension        3.1.0                    py27_0    defaults
wrapt                     1.10.11          py27h04f6869_0    defaults
xlrd                      1.1.0            py27ha77178f_1    defaults
xlsxwriter                1.0.2            py27h12cbc6b_0    defaults
xlwt                      1.3.0            py27h3d85d97_0    defaults
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.2                hbedb6e5_2    defaults
zict                      0.1.3            py27h12c336c_0    defaults
zlib                      1.2.11               ha838bed_2    defaults
```
</p></details>

<details><summary><code>from original computer: `conda info`</code></summary><p>

```
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : /Users/m/anaconda  (writable)
    default environment : /Users/m/anaconda/envs/m_py27
       envs directories : /Users/m/anaconda/envs
                          /Users/m/.conda/envs
          package cache : /Users/m/anaconda/pkgs
                          /Users/m/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/m/.condarc
             netrc file : /Users/m/.netrc
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.2 Darwin/17.6.0 OSX/10.13.5
                UID:GID : 501:20
```
</p></details>

<details><summary><code>environment.yml</code></summary><p>

```
name: m_py27
channels:
- conda-forge
- defaults
dependencies:
- bzip2=1.0.6=1
- ca-certificates=2018.4.16=0
- certifi=2016.2.28=py27_0
- cycler=0.10.0=py27_0
- decorator=4.1.2=py27_0
- ffmpeg=3.2.4=1
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- h5py=2.7.0=np112py27_0
- hdf5=1.8.17=2
- imageio=2.3.0=py27_0
- jbig=2.1=0
- libgpuarray=0.6.9=0
- libiconv=1.14=4
- mako=1.0.6=py27_0
- markupsafe=1.0=py27_0
- mock=2.0.0=py27_0
- networkx=1.11=py27_0
- nose=1.3.7=py27_1
- numexpr=2.6.5=py27_0
- openssl=1.0.2l=0
- pbr=1.10.0=py27_0
- pip=9.0.1=py27_1
- protobuf=3.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- pywavelets=0.5.2=np112py27_0
- scikit-image=0.13.0=np112py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- werkzeug=0.12.2=py27_0
- wheel=0.29.0=py27_0
- x264=20131217=3
- xz=5.2.3=0
- zlib=1.2.11=0
- backports_abc=0.5=py27h6972548_0
- bcolz=1.1.2=py27_0
- bokeh=0.12.16=py27_0
- click=6.7=py27h2b86a94_0
- cloudpickle=0.5.3=py27_0
- cytoolz=0.9.0.1=py27h1de35cc_0
- dask=0.17.5=py27_0
- dask-core=0.17.5=py27_0
- distributed=1.21.8=py27_0
- freetype=2.5.5=2
- futures=3.2.0=py27h1b80678_0
- heapdict=1.0.0=py27_2
- icu=54.1=0
- intel-openmp=2018.0.0=8
- jinja2=2.10=py27h70b8dc5_0
- jpeg=8d=2
- lcms=1.19=0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libgfortran=3.0.1=h93005f0_2
- libpng=1.6.30=1
- libprotobuf=3.2.0=0
- libtiff=4.0.6=2
- locket=0.2.0=py27ha10513d_1
- matplotlib=2.0.2=np112py27_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py27_3
- msgpack-python=0.5.6=py27h04f5b5a_0
- numpy=1.12.1=py27_0
- packaging=17.1=py27_0
- pandas=0.20.3=py27_0
- partd=0.3.8=py27h7560dbf_0
- pil=1.1.7=py27_2
- pillow=3.4.2=py27_0
- psutil=5.4.5=py27h1de35cc_0
- pygpu=0.6.9=py27_0
- pytables=3.4.2=np112py27_0
- pyyaml=3.12=py27ha7932d0_1
- qt=5.6.2=2
- readline=6.2=2
- scikit-learn=0.19.0=np112py27_0
- scipy=0.19.1=np112py27_0
- setuptools=36.4.0=py27_1
- singledispatch=3.4.0.3=py27he22c18d_0
- sortedcontainers=1.5.10=py27_0
- tblib=1.3.2=py27ha684fc4_0
- tensorflow=1.1.0=np112py27_0
- theano=0.9.0=py27_0
- tk=8.5.18=0
- toolz=0.9.0=py27_0
- tornado=5.0.2=py27_0
- yaml=0.1.7=hc338f04_2
- zict=0.1.3=py27h5fff8b1_0
- pip:
  - absl-py==0.1.13
  - appnope==0.1.0
  - asn1crypto==0.24.0
  - astor==0.6.2
  - audioread==2.1.5
  - aws==0.2.5
  - awscli==1.15.4
  - backports-abc==0.5
  - backports.functools-lru-cache==1.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.weakref==1.0.post1
  - bcrypt==3.1.4
  - beautifulsoup4==4.6.0
  - bleach==2.1.3
  - boto==2.48.0
  - botocore==1.10.4
  - cffi==1.11.5
  - chardet==3.0.4
  - cliff==2.11.0
  - cmd2==0.8.5
  - colorama==0.3.9
  - configparser==3.5.0
  - contextlib2==0.5.5
  - cryptography==2.2.2
  - cssselect==1.0.3
  - docutils==0.14
  - entrypoints==0.2.3
  - enum34==1.1.6
  - fabric==1.14.0
  - future==0.16.0
  - gast==0.2.0
  - grpcio==1.11.0
  - html5lib==1.0.1
  - idna==2.6
  - ipaddress==1.0.22
  - ipykernel==4.8.2
  - ipython==5.6.0
  - ipython-genutils==0.2.0
  - ipywidgets==7.2.1
  - jmespath==0.9.3
  - joblib==0.11
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - kaggle-cli==0.12.13
  - keras==2.1.5
  - librosa==0.6.0
  - llvmlite==0.22.0
  - lxml==4.2.1
  - markdown==2.6.11
  - mechanicalsoup==0.10.0
  - mistune==0.7.4
  - nbconvert==5.3.1
  - nbformat==4.4.0
  - notebook==5.4.1
  - np-utils==0.5.3.4
  - numba==0.37.0
  - pandocfilters==1.4.2
  - paramiko==2.3.1
  - pathlib2==2.3.0
  - pexpect==4.5.0
  - pickleshare==0.7.4
  - pip-review==1.0
  - prettytable==0.7.2
  - progressbar2==3.37.1
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - pyasn1==0.3.7
  - pycparser==2.18
  - pygments==2.2.0
  - pynacl==1.1.2
  - pyperclip==1.6.0
  - python-utils==2.3.0
  - pyzmq==17.0.0
  - qtconsole==4.3.1
  - requests==2.18.4
  - resampy==0.2.0
  - rsa==3.4.2
  - s3transfer==0.1.13
  - scandir==1.6
  - send2trash==1.5.0
  - simplegeneric==0.8.1
  - sklearn==0.0
  - soundfile==0.10.1
  - stevedore==1.28.0
  - tables==3.4.2
  - tensorboard==1.7.0
  - termcolor==1.1.0
  - terminado==0.8.1
  - testpath==0.3.1
  - traitlets==4.3.2
  - unicodecsv==0.14.1
  - urllib3==1.22
  - wcwidth==0.1.7
  - webencodings==0.5.1
  - widgetsnbextension==3.2.1
prefix: /Users/m/anaconda/envs/m_py27


```
</p></details>

**Comment by kalefranz** [comment] 2018-05-19 01:03
Can you provide `conda info` from the machine where the `environment.yml` file was working?

**Comment by kalefranz** [comment] 2018-05-19 01:04
Also might need the full contents of that `environment.yml` file.

**Comment by maxwellmckinnon** [comment] 2018-05-19 01:12
Appended above, thanks!

**Comment by semplea** [comment] 2018-11-27 14:54
Has a solution to this issue been found? I am facing a very similar looking problem... thanks!

**Comment by nehaljwani** [comment] 2018-11-28 04:59
This problem can happen if the environment was exported on a different platform than the target machine. For example, in the output above, the environment.yaml has the package: `pyyaml==3.12=py27ha7932d0_1`, and this is available only on osx-64, but the OP is trying to create the environment on a linux machine, and it won't find the package in the linux-64 subdir. There is nothing wrong in Conda here. Please explore the `--no-builds` option to `conda env export`, which would relax the constraint on the package build.

**Comment by nehaljwani** [comment] 2018-11-28 04:59
Closing as a non-issue. Feel free to re-open if you feel otherwise.

**Closed by nehaljwani** 2018-11-28 04:59 UTC

**Comment by mitchnegus** [comment] 2018-12-07 00:12
I mentioned this in #7836, but I'm still running into this problem now, and I'm wondering if this is a better place to have the discussion. Unfortunately the environment I'm looking at wasn't created by me, so I can't necessarily use the `--no-builds` option. I could (and likely will) go through and manually delete the build info off the end of each entry in the environment file, but that seems like it essentially destroys the elegance of the export/creation process. Would it be at all feasible to make the `--no-builds` option default, and maybe changing that flag to `--include-builds` or something similar? After some Google searching initially, I found that this seems to be a pretty common problem with people switching between OSs.  I don't know all the intricacies of conda (or have any enterprise dev experience) so maybe the build numbers are more essential, but in my personal developments I've resorted back to just writing the yml's by hand...

**Comment by mtxuser** [comment] 2020-02-07 23:36
> Closing as a non-issue. Feel free to re-open if you feel otherwise.

@nehaljwani @mitchnegus @maxwellmckinnon 

I want to make sure I understand this topic & its consequences: a `conda` user should thus **always** include the `--no-builds` option in a given project's README or documentation, unless one can be *absolutely sure* that any & all other project contributors are using the same native OS environment as the original creator of the environment file, right @nehaljwani ?

If so, shouldn't the `--no-builds` option be activated by default @conda-bot?

If this is true, then it severely undermines the very *purpose* of a virtual environment in the first place. I myself am running code for my employer on a MacOS laptop while working with a new individual who is unable to re-create the same **conda** virtual environment on a Windows machine, even within a "live-boot" Linux environment.

If I must specify to `conda`: 'do not consider the native machine's OS, merely install the packages listed', then A) why bother with a reqs/env file, given it doesn't fully express the necessary requirements or environment, and B) why necessitate an input file in the first place if doesn't require the very minimum of information (i.e. the freaking OS itself!)?!

**Comment by TCAllen07** [comment] 2020-02-07 23:37
> Closing as a non-issue. Feel free to re-open if you feel otherwise.

@nehaljwani @mitchnegus @maxwellmckinnon 

I want to make sure I understand this topic & its consequences: a `conda` user should thus **always** include the `--no-builds` option in a given project's README or documentation, unless one can be *absolutely sure* that any & all other project contributors are using the same native OS environment as the original creator of the environment file, right @nehaljwani ?

If so, shouldn't the `--no-builds` option be activated by default @conda-bot?

If this is true, then it severely undermines the very *purpose* of a virtual environment in the first place. I myself am running code for my employer on a MacOS laptop while working with a new individual who is unable to re-create the same **conda** virtual environment on a Windows machine, even within a "live-boot" Linux environment.

If I must specify to `conda`: 'do not consider the native machine's OS, merely install the packages listed', then A) why bother with a reqs/env file, given it doesn't fully express the necessary requirements or environment, and B) why necessitate an input file in the first place if doesn't require the very minimum of information (i.e. the freaking OS itself!)?!

**Comment by MosheVai** [comment] 2020-02-17 10:03
Adding to @TCAllen07  comment, even the --no-builds option doesn't work as it **includes the OS specific dependencies**  in the `.yml` file.

I tried using  --no-builds --from-history and still it added windows specific packages, for example:

running `conda env export --no-builds --from-history > environment.yaml`
resulted in the following packes in the `yml`:

`win_inet_pton==1.1.0=py37_0 `

Unless there is something that i don't understand, to me conda is an unusable venv manager.

to quote @EniasCailliau [comment](https://github.com/datitran/object_detector_app/issues/41#issuecomment-387648855)

> The whole concept of using yml files is to simplify environment installation on other computers. Why does the conda env export command generate a file that only works on the originating host?

**Comment by genecell** [comment] 2021-01-19 13:11
I have met the ResolvePackageNotFound errors many times and it is really bothering me. This time, I deleted the packages reported by ResolvePackageNotFound in the .yml file, and then Conda was able to install other packages and successfully created the environment.
My error is:
ResolvePackageNotFound: - binutils_impl_linux-64==2.34=h53a641e_0 - ld_impl_linux-64==2.34=h53a641e_0

**Comment by chenghlee** [comment] 2021-01-19 20:27
@genecell: are you trying to re-create the environment on the same platform (linux-64)? `environment.yml` files are not necessarily cross-platform, especially if they include packages that have specific host and/or CPU architecture requirements.

Further (assuming you originally got those packages from conda-forge), they've been marked "broken", so you will need to add `conda-forge/label/broken` to the `channels` list in the `environment.yml`.

**Comment by giacman** [comment] 2021-02-22 11:57
I am having the same issue even if I created the `environment.yml` file with ` --no-builds`. The environment file was originally created on OS and I'm trying to re-create it on Ubuntu. I get `ResolvePackageNotFound:  - libgfortran=5.0.0`

I delete that line manually and it worked. Is this the only solution? Not ideal.

**Comment by chloeh13q** [comment] 2021-02-23 19:12
> I am having the same issue even if I created the `environment.yml` file with ` --no-builds`. The environment file was originally created on OS and I'm trying to re-create it on Ubuntu. I get `ResolvePackageNotFound: - libgfortran=5.0.0`
> 
> I delete that line manually and it worked. Is this the only solution? Not ideal.

Same here!

**Comment by baggiponte** [comment] 2021-07-25 12:36
Hi! I'd like to add that sometimes adding the flag `--no-builds` is not enough. I have a macOS project I need to follow on Windows too and despite the ad-hoc environment there are still problems. In particular, the following packages cannot be found - I assume because they are not designed for Windows?

```
ResolvePackageNotFound:
  - ncurses=6.2
  - libgfortran5=9.3.0
  - libdap4=3.20.6
  - tzcode=2021a
  - libedit=3.1.20191231
  - libnghttp2=1.43.0
  - appnope=0.1.2
  - libcxx=12.0.1
  - libev=4.33
  - libgfortran=5.0.0
  - readline=8.1
```

**Comment by ashish-ram** [comment] 2021-11-15 06:49
This issue still exists. Has anyone found any workable solution? I am creating an yml file in Azure ML and then trying to recreate the env in the same VM (ubuntu) and it fails.

**Comment by jdwillard19** [comment] 2022-02-20 20:28
I am also experiencing this issue still, the --no-builds flag in the saving of the yml does not fix it.

**Comment by robjharrison** [comment] 2022-03-22 10:01
As per many above. Experiencing the same even though i'm moving to a pc with the SAME architecture. Expected the env porting feature to allow me to move the environment in this manner. But it fails on such as : 

ResolvePackageNotFound:
  - deepdiff
  - jupyter_contrib_nbextensions
  - jupyter-dash
  - pandasgui
  - chart-studio
  - geocoder
  
Obv non-standard ones, but now i'll have to pick through and do it manually. Would have at least like to have known before this point.

**Comment by baggiponte** [comment] 2022-03-23 08:31
(As a side note: I switched to [PDM](https://github.com/pdm-project/pdm) and solved all these issues that I had with conda/mamba. PDM basically is the next generation dependency manager, and is compatible with many new PEPs - unlike conda and poetry. It's also way faster than conda and you won't have reproducibility/build issues as it leverages the new `pyproject.toml` instead of requirements.txt/environment.yml)

**Comment by rickysugiarta** [comment] 2022-06-17 03:16
receive this error on docker, im using ARM laptop
so need to explicitly set `--platform=linux/amd64` on my conda container

difference behavior between ARM and amd64

**Comment by RaistlinD2x** [comment] 2022-12-30 02:40
Why is this topic closed with no resolution?

**Comment by CasperKristiansson** [comment] 2023-03-23 15:04
Was able to solve it for the specific packages:

- libgfortran=5.0.0
- libgfortran5=11.3.0

Compiled an environment file on MAC OSX for a linux compose. Could be solved by simply adding a - conda-forge channel for the environment.yml file
