### ISSUE TITLE
Conda Offline Package Install Issue

### ISSUE THREAD

**Issue by scarescrow** [conda/conda#3343] opened 2016-08-25 06:57 UTC
Hi, I faced an issue during offline install of packages. If space is present in path to a package, installing of package fails. 

Command was 

`conda install --offline -f win-64-gevent-1.1.1-py27_0.tar.bz2`
## Stack Trace

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 130, in args_func

    exit_code = args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 78, in ex
ecute
    install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 203, in instal
l
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\misc.py", line 140, in explicit
    execute_actions(actions, index=index, verbose=verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 599, in execute_actio
ns
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 136, in execu
te_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 78, in LINK_C
MD
    dist, lt = split_linkarg(arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 74, in split_
linkarg
    return (parts[0], int(LINK_HARD if len(parts) < 2 else parts[1]))
ValueError: invalid literal for int() with base 10: 'Files/Commvault/ContentStor
e/ContentAnalyzer/bin/::win-64-gevent-1.1.1-py27_0'
```

The issue was because the path to file is being split and typecast to int. So, if the path contains space, it will crash.
## Conda Info:

```
Warning: could not import binstar_client ('args' object has no attribute 'token'
)Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.3.5
       python version : 2.7.7.final.0
     requests version : 2.11.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by HugoTian** [comment] 2016-08-25 16:45
It happens before, and we may latter refactor the code into OO design. Now there are lots of attributes of package depends on parsing of a string, which is neither readable nor simple. We will have better design in the future

**Comment by ijstokes** [comment] 2016-11-05 16:28
I think this is a duplicate of #3059

**Comment by tyler-thetyrant** [comment] 2017-05-02 04:37
Closing outdated/duplicate.

**Closed by tyler-thetyrant** 2017-05-02 04:37 UTC
