### ISSUE TITLE
BUG: conda 4.0.4 fails to correctly resolve build numbers

### ISSUE THREAD

**Issue by cel4** [conda/conda#2297] opened 2016-03-22 05:51 UTC
Somewhere between `conda-4.0.2` and `conda-4.0.4` a bug has slipped in the dependency resolving logic.

One of my packages depends on gnuplot indirectly via a second dependency. There are multiple builds available in the bioconda channel:

```
gnuplot-5.0.3-0
gnuplot-5.0.3-1
gnuplot-5.0.3-2
gnuplot-5.0.3-3
```

conda-4.0.2 correctly identifies `gnuplot-5.0.3-3` as the package to pull in. For `>= conda-4.0.4`, conda erroneously thinks `gnuplot-5.0.3-0` is the correct dependency. 

`conda install gnuplot` correctly identifies `gnuplot-5.0.3-3` as the correct version for both versions.

**Comment by mcg1969** [comment] 2016-03-22 13:22
Can you offer your `conda info` output?

**Comment by mcg1969** [comment] 2016-03-22 13:23
Ahh, sorry, I missed the bioconda reference.

**Comment by mcg1969** [comment] 2016-03-22 13:24
Can you give us an example of a command that pulls in `gnuplot-5.0.3-0`?

**Comment by mcg1969** [comment] 2016-03-22 13:27
There is a difference in dependencies here. `gnuplot 5.0.3 0` depends on `libgcc` and `libgd`, and that's it. Later builds depend on `libgd *.bioconda`. The Bioconda package maintainers are going to have to chime in and explain what's going on here.

**Comment by msarahan** [comment] 2016-03-22 13:50
@cel4 what you might have missed is that the new versions of Conda are much better about not installing inconsistent collections of packages.  It's probably installing the older version either because some dependency is not available, or because some dependency conflicts in version with something else in your installation.

@mcg1969 is working on better output in these situations.  For now, though, you need to very carefully look at what dependencies (at what version) are getting pulled in.

**Comment by cel4** [comment] 2016-03-22 14:16
@mcg1969, it was me who introduced the change. The problem is that the `libgd` package in conda's default channels is broken and I did not see a way to ensure getting a non-broken package without fiddling with the version string. Confusingly, adding a string at the end of the version seemed to make the version number smaller instead of higher - so `1.0.0.bioconda < 1.0.0`. At this point I came up with the ugly hack I used there:

gnuplot got an explicit dependency on `libgd *.bioconda`, and bioconda's libgd version string got the `*.bioconda` suffix.

It seems that conda does not like this trick anymore. I am thinking about a different way to solve this, but cannot think of one right now.

**Comment by mcg1969** [comment] 2016-03-22 15:00
Got it. But again, can you offer an example of a specific `conda create` command that pulls down the "wrong" version of `gnuplot`?

**Comment by cel4** [comment] 2016-03-22 15:32
Consider this example:

meta.yaml
```yaml
package:
  name: foo
  version: 1.0

requirements:
  run:
    - gnuplot
```
If I build it and install it:

`conda install --use-local foo`

conda replies:
```
Package plan for installation in environment /Users/ch/miniconda/envs/sb35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    foo-1.0                    |                0          856 B

The following NEW packages will be INSTALLED:

    foo:     1.0-0
    gnuplot: 5.0.3-0

```

If I do:

`conda install gnuplot`

```
Package plan for installation in environment /Users/ch/miniconda/envs/sb35:

The following NEW packages will be INSTALLED:

    gnuplot: 5.0.3-3

The following packages will be DOWNGRADED:

    libgd:   2.1.1-0 --> 2.1.1.bioconda-0
```

So the dependency solver masks the gnuplot-5.0.3-3 version.

**Comment by mcg1969** [comment] 2016-03-22 15:47
This example seems to assume an existing environment; one, for instance, in which `libgd` is already installed. I'm afraid I just don't have the bandwidth to search for error cases or build custom packages. I need a self-contained way to reproduce the error Can you offer me a specific `conda create -n test -c bioconda` recipe that installs the wrong version of gnuplot?

**Comment by cel4** [comment] 2016-03-22 16:21
Here you go.

```bash
conda install conda==4.0.5
conda create -n test_foo python=3.5 fastx_toolkit -c bioconda -c defaults --override-channels
```

```
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/ch/miniconda/envs/test_foo:

The following NEW packages will be INSTALLED:

    cython:        0.23.4-py35_1
    fastx_toolkit: 0.0.14-1
    freetype:      2.5.5-0
    gnuplot:       5.0.3-0
    jbig:          2.1-0
    jpeg:          8d-1
    libgd:         2.1.1-0
    libgtextutils: 0.7-1
    libpng:        1.6.17-0
    libtiff:       4.0.6-1
    libwebp:       0.5.0-0
    nose:          1.3.7-py35_0
    openssl:       1.0.2g-0
    pip:           8.1.1-py35_0
    python:        3.5.1-0
    readline:      6.2-2
    setuptools:    20.3-py35_0
    sqlite:        3.9.2-0
    tk:            8.5.18-0
    wheel:         0.29.0-py35_0
    xz:            5.0.5-1
    zlib:          1.2.8-0

Proceed ([y]/n)?
```
---
```bash
conda install conda==4.0.2
conda create -n test_foo python=3.5 fastx_toolkit -c bioconda -c defaults --override-channels
```
```
Fetching package metadata: ......
Solving package specifications: ...........

Package plan for installation in environment /Users/ch/miniconda/envs/test_foo:

The following NEW packages will be INSTALLED:

    cython:        0.23.4-py35_1
    fastx_toolkit: 0.0.14-1
    freetype:      2.5.5-0
    gnuplot:       5.0.3-3
    jpeg:          8d-1
    libgd:         2.1.1.bioconda-1
    libgtextutils: 0.7-1
    libpng:        1.6.17-0
    libtiff:       4.0.6-0
    ncurses:       5.9-0
    nose:          1.3.7-py35_0
    openssl:       1.0.2g-0
    pip:           8.1.1-py35_0
    python:        3.5.1-0
    readline:      6.2-2
    setuptools:    20.3-py35_0
    sqlite:        3.9.2-0
    tk:            8.5.18-0
    wheel:         0.29.0-py35_0
    xz:            5.0.5-1
    zlib:          1.2.8-0

Proceed ([y]/n)?
```

**Comment by cel4** [comment] 2016-03-23 08:27
@mcg1969, would be interesting to know if you consider this a bug or expected behavior for the new dependency resolver. Would be helpful for me to know if my current recipes this will work again in the future or if I have to think of a new strategy to solve this.

**Comment by mcg1969** [comment] 2016-03-23 11:47
I'm sorry but we are not going to change the sorting order. I'm not sure exactly how the behavior changed in 4.0.2 but the plain understanding of the VersionOrder doc string shows that the ordering is intentional. And while you may consider `post` "impolite" it is nevertheless a documented and deliberate way to achieve what you are trying to accomplish.

Furthermore, _this isn't the real problem_. The problems are twofold: getting `libgd` fixed in default, if it is indeed broken, is one. The other is a proper handling of collisions between channels. Right now, when packages live in multiple channels, they are "merged together" as if they all live in the same channel. There is no way this is correct; build numbers cannot assume to interlace properly across channels. We are working on a solution to this problem, and when it arrives, your fix will be unnecessary.

**Closed** 2016-03-23 11:48 UTC

**Comment by cel4** [comment] 2016-03-23 12:22
I agree that a more sophisticated architecture may be needed here and I am looking forward to these changes. 

What is the correct way to handle my problem in the meantime? I have opened an issue for libgd a couple of days ago. I generally have the impression that continuumio's  focus shifts from maintaining packages to a more user centered approach.
Do you still fix these packages in the defaults channel? Or is it possible to remove your broken libgd version so I can get rid of the non-functional workaround?

Please also consider updating the documentation and making clear which wildcard expressions are understood by the new resolver and which are not. Silently ignoring potentially non-parsable dependencies is not a good strategy for people trying to debug :)

**Comment by mcg1969** [comment] 2016-03-23 13:12
I thought we gave you a functional workaround in the other issue. I'll certainly ask about the status of the libgd fix, by any chance is there an open issue you can point me to?

**Comment by mcg1969** [comment] 2016-03-23 13:15
I also don't know what you mean by "silently ignoring non-parsable expressions." We should not be doing that, and I don't believe we ever have intentionally. It's an expression doesn't parts we throw an exception. But if you can offer us a reproducible test case the demonstrates the behavior, please submit a new issue. If that simply is your interpretation of what's going on, then I'm going to need more evidence.

**Comment by cel4** [comment] 2016-03-23 13:25
Isn't the whole issue here a reproducible case for exactly that? I mean apart from the off-topic discussion about the style of the version numbers which I moved to a separate issue.

To me it seems obvious that the `libgd *.bioconda` dependency description I used (see the linked PR above) cannot be parsed anymore. Why else should conda choose the old 5.0.3-0 gnuplot version while ignoring higher `gnuplot-5.0.3-3`? It simply does not understand anymore what `libgd *.bioconda` is, but it does not warn me. Am I mistaken here?

This is the issue for libgd: https://github.com/conda/conda-recipes/issues/625

**Comment by msarahan** [comment] 2016-03-23 13:47
I agree that if the most recent version is not the one chosen to install (when no explicit version is specified), there should be some explanation of what made more up-to-date versions not installable.

I have added libgd as a package to transition to conda-forge.  We are moving recipes out of our private space, over to conda-forge, to better enable people to improve the content accessible with conda.  This transition won't happen immediately, but I'll be sure to ping you as it develops.

**Comment by cel4** [comment] 2016-03-23 13:54
Moreover, as I showed yesterday, directly using `conda install gnuplot` still correctly finds and installs `gnuplot-5.0.3-3`. This is at the very best inconsistent behavior that should be documented.

**Comment by mcg1969** [comment] 2016-03-23 15:56
> Isn't the whole issue here a reproducible case for exactly that? I mean apart from the off-topic discussion about the style of the version numbers which I moved to a separate issue.

I don't see it that way, no. `conda` has never been "silently ignoring" anything. And the issue is not because it's "non-parseable". You can verify for yourself that the `VersionOrder` code has not changed in a _long_ time (though it has been moved into its own module), and it has never had difficulty parsing your custom version numbers. I don't fully understand why your particular behavior changed between `4.0.2` and `4.0.4`, but `VersionOrder` itself is not to blame.

> To me it seems obvious that the libgd *.bioconda dependency description I used (see the linked PR above) cannot be parsed anymore.

If it could not parse it, it would throw an exception. But what we know is that it is interpreting your `bioconda` versions as *older* than the ones in `default`. If you want to restore functionality for now, you follow the advice offered in the other thread and add `post`.

**Comment by mcg1969** [comment] 2016-03-23 15:58
> Moreover, as I showed yesterday, directly using conda install gnuplot still correctly finds and installs gnuplot-5.0.3-3. This is at the very best inconsistent behavior that should be documented.

This is actually easy to explain. `conda`'s first priority is installing the latest versions of the packages that you specify on the command line; everything else is secondary. So of course this is going to get you the latest version of `gnuplot`.

But if gnuplot is just a *dependency* of another package, it has to balance installing the latest compatible versions of it versus all of the *other* dependencies it's pulling in. I'm going to hazard a guess that there is a tradeoff here between your "older" versions of `libgd` and the "older" versions of `gnuplot`, and `4.0.4` is making a different choice. Given the more clear-cut issues with version preferences we've had to fix in the last dot-0 release, I'm not surprised.

**Comment by cel4** [comment] 2016-03-23 21:23
>But if gnuplot is being pulled in as a dependency of another package, then conda is going to balance any downgrades across all packages it's pulling in. I'm going to hazard a guess that there is a tradeoff here between your "older" versions of libgd and the "older" versions of gnuplot, and 4.0.4 is making a different choice. Given the more clear-cut issues with version preferences we've had to fix in the last dot-0 release, I'm not surprised.

Okay, this makes sense. However the implementation seems very shaky then. Builds are basically bugfix versions, right? I don't see why it makes sense to choose a lower build number (maybe a buggy version) just to minimize downgrade dependencies.

**Comment by mcg1969** [comment] 2016-03-23 21:28
Remember, as far as the solver is concerned, it was deciding between downgrading `gnuplot` and downgrading `libgd`. Obviously, if it could have downgraded _neither_, that's what it would have done.

Also, it minimizes _version downgrades_ first, then it minimizes _build downgrades_ second, so it's not going to trade a build downgrade for a version downgrade or vice versa.

**Comment by mcg1969** [comment] 2016-03-23 21:29
BTW, I didn't realize this, but the `post` version convention is baked right into [PEP 440](https://www.python.org/dev/peps/pep-0440/). It wasn't just something that the designer of `VersionOrder` decided to do arbitrarily.
