### ISSUE TITLE
IPython Notebook's Windows shortcut's Start in folder sohuld be user's home

### ISSUE THREAD

**Issue by joonro** [conda/conda#1192] opened 2015-03-12 13:53 UTC
I'm not sure if this is the right place to report this, so please let me know if I should go to somewhere else.

Currently when I install ipython, the automatically generated shortcut for the notebook has `Start in` value `C:\Users\username\Documents\IPython Notebooks`. This forces the user to put notebooks inside that folder, since you cannot navigate outside of the folder where the kernel started at.

I'm currently teaching with Anaconda and this caused a lot of confusion to my students - they usually download a notebook to their Downloads folder and gets confused because when they open the IPython Notebook, they just get an empty window. It is not easy to explain the `Start in` folder thing to them since most of them are beginners and in my opinion it is unnecessary. The `Start in` folder should be the user's home, so they can navigate into whatever directory they want.

**Comment by asmeurer** [comment] 2015-03-12 16:01
This is a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/239. We plan to fix this for the next Anaconda release.

**Closed by asmeurer** 2015-03-12 16:01 UTC

**Comment by joonro** [comment] 2015-03-12 17:22
Sounds good - thanks!
