### ISSUE TITLE
Anaconda with Python 3 on Windows 7 error launching spyder

### ISSUE THREAD

**Issue by Andrew62** [conda/conda#1350] opened 2015-05-27 23:52 UTC
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

```python-traceback
Traceback (most recent call last):
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_run.py", line 77, in execute
    for pkg in get_package_versions(args.package):
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\api.py", line 168, in get_package_versions
    index = get_index()
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\utils.py", line 120, in __call__
    value = self.func(*args, **kw)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\fetch.py", line 250, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    verify=config.ssl_verify)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 234, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 135, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Users\andrew62\AppData\Local\Continuum\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in getPositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found
```

**Comment by ccordoba12** [comment] 2015-05-28 01:00
@Andrew62, the error you reported doesn't include a single line about Spyder.

Were you trying to start Spyder using the Anaconda Launcher?

**Comment by asmeurer** [comment] 2015-05-28 20:42
Try `conda update requests`

**Comment by asmeurer** [comment] 2015-05-28 20:44
Closing as duplicate of https://github.com/conda/conda/issues/1261

**Closed by asmeurer** 2015-05-28 20:44 UTC

**Comment by Andrew62** [comment] 2015-05-31 19:22
Yes, I was using the launcher tool with a python 3 environment
