### ISSUE TITLE
conda update conda error

### ISSUE THREAD

**Issue by cyberbod** [conda/conda#6099] opened 2017-10-07 15:39 UTC
Hi Sorry if this is my fault. I cant tell, nut the error message said post info here.

Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.  <—— Bottom of page

Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "//anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 239, in install
    offline=args.offline)
  File "//anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "//anaconda/lib/python3.5/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "//anaconda/lib/python3.5/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "//anaconda/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "//anaconda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "//anaconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "//anaconda/lib/python3.5/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "//anaconda/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "//anaconda/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "//anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "//anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "//anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "//anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "//anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "//anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

/////////////// info ////////

Current conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.12.1
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment] 2017-10-10 20:56
duplicate of #4022

**Comment by kalefranz** [comment] 2017-10-10 20:58
It seems you've been using pip in this environment, and it's left you in a corrupt state.  The solution will probably be `pip install -U cryptography`.

**Comment by kalefranz** [comment] 2017-10-10 20:58
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-10-10 20:58 UTC
