### ISSUE TITLE
jupyter post-link script failure

### ISSUE THREAD

**Issue by Aleti1** [conda/conda#6493] opened 2017-12-19 22:01 UTC
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 0+unknown
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\Users\aleti\AppData\Local\conda\conda\envs\dlnd
       envs directories : C:\Users\aleti\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\aleti\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\aleti\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False

`$ C:\ProgramData\Anaconda3\Scripts\conda install jupyter notebook -v`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\Windows\\system32\\cmd.exe', '/d', '/c', 'C:\\Users\\aleti\\AppData\\Local\\conda\\conda\\envs\\dlnd\\Scripts\\.ipykernel-post-link.bat']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package defaults::ipykernel-4.7.0-py36h2f9c1c0_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Users\aleti\AppData\Local\conda\conda\envs\dlnd\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 281, in execute
        pkg_data, actions)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.7.0-py36h2f9c1c0_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Users\aleti\AppData\Local\conda\conda\envs\dlnd\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.7.0-py36h2f9c1c0_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Users\aleti\AppData\Local\conda\conda\envs\dlnd\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

**Comment by TAdeJong** [comment] 2018-01-12 12:23
Also occuring for me upon updating Anaconda3 from a fresh install of 5.0.1, with precisely the same errors. Contrary to what the output suggests, `-v` will not yield more information than this. 
So it seems the post-link script for `ipykernel-4.7.0-py36h2f9c1c0_0` is just broken in its current release?

I in addition tried to install on a fresh install in administrator mode,, this also yields the same error.

**Comment by mingwandroid** [comment] 2018-01-12 16:20
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/8087

Closing as this isn't the right place to report issues with packages. @TAdeJong please try my suggestion in https://github.com/ContinuumIO/anaconda-issues/issues/8087#issuecomment-357190830

**Closed** 2018-01-17 20:01 UTC
