### ISSUE TITLE
Fix ValueError: invalid literal for int() with base 10: '' in tqdm/utils.py

### ISSUE THREAD

**Issue by erastogi** [conda/conda#10673] opened 2021-05-18 21:03 UTC
Valid for conda version > 4.8.3
At line-336 in `_vendors/tqdm/utils.py` (https://github.com/conda/conda/commit/db380cc9a1fbeedb5efab84750d4437f1ab72d45#diff-a2e083f5ce1f74db5268f51073df0c2cdb07b7e2d64f65be3e65f5964e023417), `os.environ` is called which returns an empty string and thus fails with value error when `int()` is called on it. In the previous code, a default value of `1` was used (line-204 in `_vendors/tqdm/_utils.py` ).  I suggest that the line-336 in `_vendors/tqdm/utils.py`  should be changed to `return [int(os.environ.get(i, 1)) - 1 for i in ("COLUMNS", "LINES")]`

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by jezdez** [comment] 2021-05-31 19:57
@erastogi I've seen your PR #10674 but I'm not sure how to reproduce this issue, can you share more about the run environment where you saw this issue?

**Comment by jezdez** [comment] 2021-06-01 09:54
@chenghlee My PR was merged upstream and is likely going to be part of the next tqdm release. Can we pair program the update of the vendored copy once that happens so I understand what the process is?

**Comment by erastogi** [comment] 2021-06-01 17:30
> @erastogi I've seen your PR #10674 but I'm not sure how to reproduce this issue, can you share more about the run environment where you saw this issue?

I don't have all the information as I don't have full access to the system where this issue occurred but few things that might help :
- I am using `conda` Python library to run `conda env` command in Python 
- The Python code is run by compiling and exec-ing  (using `compile()` and `exec()` commands)
- The Python code is running on a Linux system. (This code works on Mac Os)

Hope this helps. I don't have a full error stacktrace to post here.

**Comment by jezdez** [comment] 2021-06-07 15:11
That's actually a great overview @erastogi, thank you for sharing! I'm pretty sure it's because exec is used that it fails to get correct env vars from the shell it's running in.

I think it's fine to simply handle the situation better like in the pull request you sent and is now fixed in the upstream tqdm change. I think @casperdcl will do a release with that soon which we'll be able to pull in in our vendored version.

**Closed** 2021-06-15 08:02 UTC
Labels: type-bug, waiting-OP_response
