### ISSUE TITLE
Running using `conda run` inside already activated environment should be the same as running it outside

### ISSUE THREAD

**Issue by karrtikr** [conda/conda#11305] opened 2022-03-08 14:53 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Hi Python extension VSCode dev here 👋 Consider the following scenario:

1. Create conda environment:

```
conda create -n hello python
```
2. Activate the environment using `conda activate hello`.
3. Install a module say `black`:
```
python -m pip install black
```
4. Use the following to check if module is installed. Notice it is detected.
```
python -m black -h
```
5. Prefix the command with `conda run` and check again:
```
conda run -n hello python -m black -h
```
Output:
```
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '-m', 'black', '-h']' command failed.  (See above for error)
~\Miniconda3\python.exe: No module named black
```

6. Now deactivate the environment.
```
conda deactivate
```
7.  Run command mentioned in step `5.` again. Notice black module is now detected.

We would've expected step `4.` and `5.` to have the same behavior, but it seems using `conda run` on top of `conda activate` maybe kind of double activates the environment so installed modules can't be accessed.

### Additional Context

We have switched to using `conda run` in our extension for running files or installing modules, this is being problematic as we also send a command to activate the environment when a terminal is opened. (See https://github.com/microsoft/vscode-python/issues/18639, https://github.com/microsoft/vscode-python/issues/18634, https://github.com/microsoft/vscode-python/issues/18638)

^ I don't believe above template information is relevant here but let me know if you still need it.

**Comment by robertodawid** [comment] 2022-03-08 15:17
Hi, I discovered the same issue today; VSC was working perfectly last week. I downgraded the Python interpreter to the previous version-v2022.0.1814523869 around three weeks ago. It seems the problem has been solved.

**Comment by bilderbuchi** [comment] 2022-03-09 07:44
@karrtikr duplicate of #9587?

**Comment by karrtikr** [comment] 2022-03-09 10:41
@bilderbuchi Yep that could be the cause. Although that issue is about incorrect `sys.executable` whereas this issue is related to incorrect `sys.path`, which I think is used to detect installed modules. I'll leave it up to the conda team to decide.

**Comment by kenodegard** [comment] 2022-03-09 21:29
Marking and closing as a duplicate of https://github.com/conda/conda/issues/11174 for now.

**Closed by kenodegard** 2022-03-09 21:29 UTC
Labels: type::bug, source::community, severity::3, plugins::run, duplicate

**Comment by karrtikr** [comment] 2022-03-10 05:55
@kenodegard Can you please explain how this one is a duplicate of that? I believe it's potentially a separate issue, and we should keep this open so we don't loose track.

**Comment by kenodegard** [comment] 2022-03-10 17:55
@karrtikr You specified that you got the following error:

> ```
> ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '-m', 'black', '-h']' command failed.  (See above for error)
> ~\Miniconda3\python.exe: No module named black
> ```

The issue here is that the subprocess `conda run` invokes to run the command `python -m black -h` is exposing the wrong Python. It exposes the Python from your `base` environment (`~\Miniconda3\python.exe`) not the Python in your `hello` environment (`~\Miniconda3\envs\hello\python.exe`).

It is very likely this is the same issue identified in #11174 where the current environment (usually `base`) is injected onto the `$PATH` and causing `conda run` to use the wrong executables.

**Comment by imatiach-msft** [comment] 2022-10-28 21:40
I was able to work around this by calling conda deactivate first, like this (and then passing to subprocess.check_call in my case):

        command = [
            "conda",
            "deactivate",
            "&&",
            "conda",
            "run",
            "-n",
            self.inference_conda_env,
            "python",
            get_wrapmodel_filepath(),
            "--model_path",
            self.model_path,
            "--wrapped_model_path",
            self.wrapped_model_path,
        ]
