### ISSUE TITLE
conda 4.0.2 does not select latest build

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda#2219] opened 2016-03-09 18:00 UTC
It appears that conda version 4.0.2 does not select the latest build of a package when solving for dependencies.  For example:

```
~$ conda --version
conda 4.0.2
~$ conda create -n flower python=2.7 gdal
Fetching package metadata: ..
Solving package specifications: ...........

Package plan for installation in environment /home/jhelmus/anaconda/envs/flower:

The following NEW packages will be INSTALLED:

    curl:       7.45.0-0     
    gdal:       2.0.0-py27_1 
    hdf5:       1.8.15.1-2   
    libgdal:    2.0.0-0      
    libnetcdf:  4.3.3.1-3    
    mkl:        11.3.1-0     
    numpy:      1.10.4-py27_1
    openssl:    1.0.2g-0     
    pip:        8.1.0-py27_0 
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 20.2.2-py27_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-0      

Proceed ([y]/n)? 
```

Notice that libgdal 2.0.0-0 is selected for install and not the more recent 2.0.0-2 build.

Using conda version 3.19.3 selects the latest build of libgdal which pull in additional packages:

```
~$ conda --version 
conda 3.19.3
~$ conda create -n flower python=2.7 gdal
Fetching package metadata: ..
Solving package specifications: ...............
Package plan for installation in environment /home/jhelmus/anaconda/envs/flower:

The following NEW packages will be INSTALLED:

    curl:       7.45.0-0     
    gdal:       2.0.0-py27_1 
    geos:       3.4.2-0      
    hdf4:       4.2.11-0     
    hdf5:       1.8.15.1-2   
    jpeg:       8d-0         
    kealib:     1.4.5-0      
    libgdal:    2.0.0-2      
    libnetcdf:  4.3.3.1-3    
    mkl:        11.3.1-0     
    numpy:      1.10.4-py27_1
    openssl:    1.0.2g-0     
    pip:        8.1.0-py27_0 
    proj4:      4.9.1-0      
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 20.2.2-py27_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    xerces-c:   3.1.2-0      
    zlib:       1.2.8-0      

Proceed ([y]/n)? 
```

**Comment by mcg1969** [comment] 2016-03-09 19:02
Checking it out now!

**Comment by mcg1969** [comment] 2016-03-09 19:07
I'm able to reproduce this in 4.0.2. The good news is that I'm not able to reproduce this in master :-) I'm going to try and diagnose it anyway to make sure I understand the cause, but I did some refactoring of version ordering for other reasons that may have caught the error.

**Comment by kalefranz** [comment] 2016-03-09 19:15
We'll release 4.0.3 today from master.

**Comment by mcg1969** [comment] 2016-03-09 19:25
OK, but this is weird, because I can only reproduce it intermittently. @jjhelmus, can you send the output of `conda --debug` on this recipe? You're running Linux 64, right?

**Comment by kalefranz** [comment] 2016-03-09 19:32
@mcg1969 `4.0.3` can wait until you get this figured out if you want.  Happy to push it off until tomorrow too.

**Comment by mcg1969** [comment] 2016-03-09 19:34
Nevermind, I've got it. The fix in 4.0.3 takes care of this.

**Comment by mcg1969** [comment] 2016-03-09 19:36
@jjhelmus, I'm getting the following package list with 4.0.3. Does this look sane?
```
curl-7.45.0-0.tar.bz2
gdal-2.0.0-py27_1.tar.bz2
hdf5-1.8.15.1-2.tar.bz2
libgdal-2.0.0-0.tar.bz2
libnetcdf-4.3.3.1-3.tar.bz2
mkl-11.3.1-0.tar.bz2
numpy-1.10.4-py27_1.tar.bz2
openssl-1.0.2g-0.tar.bz2
pip-8.1.0-py27_0.tar.bz2
python-2.7.11-0.tar.bz2
readline-6.2-2.tar.bz2
setuptools-20.2.2-py27_0.tar.bz2
sqlite-3.9.2-0.tar.bz2
tk-8.5.18-0.tar.bz2
wheel-0.29.0-py27_0.tar.bz2
zlib-1.2.8-0.tar.bz2
```
Not sure why 3.19.3 is bringing in extra packages.

**Comment by jjhelmus** [comment] 2016-03-09 19:59
That list is still not including the more recent libgdal-2.0.0-2 build which is important as it fixes some big issues.

**Comment by kalefranz** [comment] 2016-03-09 20:19
I don't see `libgdal-2.0.0-2` in my repos on `osx-64`.  Only `libgdal-2.0.0-0`.

**Comment by kalefranz** [comment] 2016-03-09 20:21
@jjhelmus I think @mcg1969 was testing on `osx-64`, which is the reason libgdal-2 is at build 0 in his output.

**Comment by kalefranz** [comment] 2016-03-09 20:21
Closing the issue because it will be resolved with `4.0.3`.

**Comment by jjhelmus** [comment] 2016-03-09 21:20
Sorry, missed that we were using different platforms.  I was seeing the issue on `linux-64`.

**Comment by mcg1969** [comment] 2016-03-09 21:23
Oh

**Comment by mcg1969** [comment] 2016-03-09 22:16
Oh, no, I'm looking at linux-64. 

I'm re-opening this because I think we should talk about the problem---I'm not convinced conda is wrong here---or at least, there are reasonable interpretations. 

The problem is that `gdal`'s dependency lists are all over the map. Conda tries to differentiate between "strong" and "weak" dependencies: "strong" dependencies are shared across _all_ versions of a package, while "weak" dependencies are version-specific. In the case of "gdal", it's quite crazy:

- The earliest versions depended only on `python`
- Later versions brought in `numpy`
- Later versions brought in `libnetcdf` and `hdf5`
- Somewhere in the _middle of version 1.11.2_, `libgdal` was brought in. That's right, `libgdal` isn't even a consistent dependency in a minor version of `gdal`.
- _For build 1 of version 2.0.0_, a bunch of the dependencies are _dropped_, and _all_ that is left is `libgdal`, `numpy`, and `python`. Furthermore, the version requirement in `libgdal` is _dropped_: according to the metadata, any version of `libgdal` will do. (Surely that's not right.)

This is crazymaking for a solver that is trying to take an algorithmic approach to determining which packages should be brought in and which should not be. Currently, the solver maximizes versions in this order: 1) requested packages, 2) strong dependencies, and 3) weak dependencies. Furthermore, when maximizing weak dependency versions, it favors _no package at all_ whenever possible. So the solver likes the idea of not having to bring in a few extra packages.

So my view is this: if a particular build of `libgdal` is critical here, then it needs to be _explicitly requested in the dependencies_. If you're not doing that, then you're giving the solver the discretion to do things you might not like.

**Comment by mcg1969** [comment] 2016-03-09 22:18
I would definitely say that the fact build 1 of `gdal` has _completely_ relaxed the version requirements on `libgdal` is a bug. But that's a bug in the metadata, not in conda, and we should file an issue over on the anaconda side.

**Comment by mcg1969** [comment] 2016-03-09 22:22
I've commented over on your [Anaconda issue](https://github.com/ContinuumIO/anaconda-issues/issues/584) about this. I think once the metadata is right, we're good. The good news is that metadata fixes don't necessarily need to wait for a new build to come online.

**Comment by jjhelmus** [comment] 2016-03-09 22:23
@mcg1969 I agree with your analysis, gdal's dependencies are a mess.

In my opinion any package that is not the latest build should be completely ignored by conda.  The entire reason to put out a new build is to correct an issue with the previous build.  Selecting a non-latest build for install basically guarantees that you are shipping a broken package to the user.

**Closed by mcg1969** 2016-03-09 22:22 UTC

**Comment by mcg1969** [comment] 2016-03-09 22:27
I get that, @jjhelmus, but your recipe *doesn't ask for libgdal*. It only asks for `gdal`, and leaves it to the solver to figure out which version of libgdal to pick up. 

There are multiple conflicting concerns here when designing the dependency solver's goals. In the case of `libgdal` for instance, you're not just picking up an older version of `libgdal`, but also older versions of other packages as well. The "downgrade" score for build 0 of `libgdal` is actually lower: by downgrading `libgdal` only 2 builds, I'm downgrading other packages less.

At some point you have to throw up your hands and say _the metadata just has to be right_. In this case I would argue the best solution is a version bump for `libgdal` and stronger version specs for `gdal`.

**Comment by jjhelmus** [comment] 2016-03-09 22:30
So if you screw up the metadata in the build of a package there is no way of ever correcting that mistake without rolling the version number?

**Comment by jjhelmus** [comment] 2016-03-09 22:32
For example, if I make a build of pyyaml that does not depend on yaml, release the error and make a new release that does include the dependency on yaml, that build will never be resolved and installed because the original build has fewer dependencies.

**Comment by mcg1969** [comment] 2016-03-09 22:32
Oh no, we can often fix the metadata live. _In this case_, with the dependencies for `gdal` being all over the map, I'm recommending a version bump. Build number bumps should be reserved for much smaller corrections than the ones I'm seeing in `gdal` and `libgdal`, IMO. 

In fact, I would suggest a good rule of thumb is this: if the metadata fix you're considering for one build would not work if applied to the other builds, then we need a new version.

**Comment by jjhelmus** [comment] 2016-03-09 22:33
But recipe makes cannot bump version number, those are controlled by the package itself.

**Comment by mcg1969** [comment] 2016-03-09 22:34
The Anaconda repo can do metadata fixes without recompilation. Actually, anyone can manually edit their own metadata if they're in charge of the web site :-) It would be good to expose that capability to all channel providers on Anaconda, IMO.

**Comment by mcg1969** [comment] 2016-03-09 22:35
I'm experimenting as we speak with relaxing the preference that `conda` has towards minimizing the number of weak dependencies installed. The problem is that if I just _remove_ that bias I actually get ambiguous solutions (that is, multiple package sets that satisfy all of the objectives). If there is an alternative that can avoid that ambiguity I will drop it in.

**Comment by jjhelmus** [comment] 2016-03-09 22:36
Can the dependencies in the packages `info/index.json` file and those reported elsewhere differ?

**Comment by mcg1969** [comment] 2016-03-09 22:36
Yes, and when they differ, the `repodata.json` file is preferred, for this very reason.

**Comment by jjhelmus** [comment] 2016-03-09 22:38
Did not know that.  I still think all but the last build of a package should be excluded from consideration but if the metadata can be changed post-build then at least there is a way to solve this.

**Comment by mcg1969** [comment] 2016-03-09 22:39
We can't do what you're suggesting (exclude the last build) because some packages do actually hardcode build numbers.

**Comment by jjhelmus** [comment] 2016-03-09 22:40
Yes, in those cases I agree the build number should come into play, the user or package is specifically requesting that build.

**Comment by mcg1969** [comment] 2016-03-09 22:42
I've commented on your Anaconda issue: I definitely think a metadata fix is warranted. It just doesn't make sense to suddenly drop the version requirements for `libgdal`!

**Comment by jjhelmus** [comment] 2016-03-09 22:44
I'm sure the `gdal` issue can be resolved, more I'm a bit worried about packages I release myself.  I have no way of marking a particular build as "bad" without removing it completely.

**Comment by mcg1969** [comment] 2016-03-09 22:46
I'm not sure we should be leaving truly "bad" builds of a package in the repo. I mean, it's one thing to leave builds in that people might be depending on. But if a build is broken, and should not be depended on in any way, why take the chance? We've actually pulled bad packages before.

Still, keep in mind, I think we should expose multiple solutions to this challenge.

**Comment by jjhelmus** [comment] 2016-03-09 22:50
Removing software which someone may have installed from the original location makes future debugging really hard.  This is the reason packages cannot be removed from PyPI without a lot of work.  On PyPI post-released are the recommended way to deal with these type of issues.  I always equated the build number with post-release where only the latest is "valid".  If this is not the case then I'll need to keep this in mind.

**Comment by mcg1969** [comment] 2016-03-09 22:51
Heh heh, thanks for sticking with me in this discussion. In fact, I was multitasking---and might have a fix to entertain for the next tagged release. :-) By removing the slight bias against weak dependencies from the version optimizer, and adding _one more pass_ to remove any packages that are strictly unnecessary, I seem to be able to eliminate ambiguity.

**Comment by jjhelmus** [comment] 2016-03-09 22:53
I should also mention that an easy solution to the original issue is to explicitly specify libgdal on the recipe line:

```
$ conda create -n flower python=2.7 gdal libgdal
Fetching package metadata: ..
Solving package specifications: ...........

Package plan for installation in environment /home/jhelmus/anaconda/envs/flower:

The following NEW packages will be INSTALLED:

    curl:       7.45.0-0     
    gdal:       2.0.0-py27_1 
    geos:       3.4.2-0      
    hdf4:       4.2.11-0     
    hdf5:       1.8.15.1-2   
    jpeg:       8d-0         
    kealib:     1.4.5-0      
    libgdal:    2.0.0-2      
    libnetcdf:  4.3.3.1-3    
    mkl:        11.3.1-0     
    numpy:      1.10.4-py27_1
    openssl:    1.0.2g-0     
    pip:        8.1.0-py27_0 
    proj4:      4.9.1-0      
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 20.2.2-py27_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    xerces-c:   3.1.2-0      
    zlib:       1.2.8-0      

Proceed ([y]/n)? 
```

It seem a bit odd to me that gdal+libgdal should resolve differently that gdal which depends on libgdal but I can see how difficult the resolution can be.

**Comment by mcg1969** [comment] 2016-03-09 22:54
Yes, the nice thing about this approach is that maximizing the version and build of explicitly requested packages is a very high priority.

**Comment by mcg1969** [comment] 2016-03-09 22:57
You might be interested in this: if I remove all bias against removing unnecessary packages, I get the solution you've asked for above, plus versions with the following additional packages:
```
  - krb5-1.13.2-0.tar.bz2, libgfortran-3.0-0.tar.bz2
  - krb5-1.13.2-0.tar.bz2
  - libgfortran-3.0-0.tar.bz2
```

**Comment by jjhelmus** [comment] 2016-03-09 23:03
That seems reasonable, I know krb5 needs to be installed for gdal to work properly.

**Comment by mcg1969** [comment] 2016-03-10 01:59
Well, apparently it is not a dependency for the lates builds...
