### ISSUE TITLE
Disable .netrc authentication

### ISSUE THREAD

**Issue by dsludwig** [conda/conda#2161] opened 2016-03-03 02:17 UTC
Anaconda-Server/support#23

When a user has a `~/.netrc` file present, `requests` will use that file to populate the `Authorization` header (using HTTP Basic auth). When authorization fails, conda falls into an infinite loop retrying.

To fix this problem in `anaconda-client`, I disabled `.netrc` authorization by adding a `NullAuth` to the `requests.Session`.

https://github.com/Anaconda-Server/anaconda-client/pull/298

**Comment by flub** [comment] 2016-09-21 13:36
The .netrc authentication has been accidentally disabled again by the use of `BinstarAuth` in `CondaSession` in the current versions.

I'd hope to see this fixed again, we rely on .netrc to get credentials for basic auth used without having to put them in the URLs.  If there's an authentication loop going on I'd hope that can be solved differently.

**Comment by kalefranz** [comment] 2016-09-21 14:40
:facepalm:

Didn't write regression tests for that because I don't have a proxy server set up to test against. I'll definitely re-enable all of that. Disabling it wasn't intentional. 

Hopefully I can just subclass a different class or call super or something.

**Comment by kalefranz** [comment] 2016-09-21 14:41
@dsludwig I want to leave .netrc enabled. People know we use requests, and it's built comes built in and enabled by default.

**Comment by dsludwig** [comment] 2016-09-21 17:02
> @dsludwig I want to leave .netrc enabled

That's fine with me.

> conda falls into an infinite loop retrying

This is the main thing I'd like us to fix. The other issue is making it clear that it is picking up `.netrc` for authentication - that would have helped [this user](https://github.com/Anaconda-Platform/support/issues/23) to diagnose their problem.

**Comment by kalefranz** [comment] 2016-09-21 19:04
Yeah working on exactly that now.

**Comment by kalefranz** [comment] 2017-05-04 18:58
I'm going to close this issue.  There is discussion about this thread throughout the issue tracker.  After much back and forth and input, conda will continue to support .netrc through request's support of it.

Other proxy issues are now being tracked with https://github.com/conda/conda/issues/5220

**Closed by kalefranz** 2017-05-04 18:58 UTC
Labels: 2 - Needs Discussion
