### ISSUE TITLE
Error cloning a conda environment

### ISSUE THREAD

**Issue by ltransom** [conda/conda#2112] opened 2016-02-21 00:59 UTC
conda create --name test --clone quant
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
src_prefix: '/Users/lransom/anaconda3/envs/quant'
dst_prefix: '/Users/lransom/anaconda3/envs/test'
Packages: 153
Files: 93
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/lransom/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/lransom/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/Users/lransom/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/lransom/anaconda3/lib/python3.4/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/lransom/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/lransom/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/lransom/anaconda3/lib/python3.4/site-packages/conda/misc.py", line 238, in clone_env
    shutil.copystat(src, dst)
  File "/Users/lransom/anaconda3/lib/python3.4/shutil.py", line 206, in copystat
    lookup("chflags")(dst, st.st_flags, follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted: '/Users/lransom/anaconda3/envs/test/lib/libgcc_s.10.5.dylib'

             platform : osx-64
        conda version : 3.19.3
  conda-build version : 1.19.0
       python version : 3.4.4.final.0
     requests version : 2.5.1
     root environment : /Users/lransom/anaconda3  (writable)
  default environment : /Users/lransom/anaconda3
     envs directories : /Users/lransom/anaconda3/envs
        package cache : /Users/lransom/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ThompkWT** [comment] 2016-02-22 23:22
having same problem with python 2.7 environment
urrent conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/Tilt/anaconda  (writable)
  default environment : /Users/Tilt/anaconda
     envs directories : /Users/Tilt/anaconda/envs
        package cache : /Users/Tilt/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment] 2016-02-26 16:57
@ltransom let me look at your computer later today if this is still happening.  Looks like a permissions issue somewhere.  Curious what the exact problem is so that we can do better with hints on how to fix it.

**Comment by mcg1969** [comment] 2016-03-04 01:38
I just reproduced this error myself.

**Comment by mcg1969** [comment] 2016-03-04 01:39
Duplicate of #1998

**Comment by mcg1969** [comment] 2016-03-04 01:39
And #1930

**Comment by ltransom** [comment] 2016-03-04 01:43
@mcg1969 I was playing around with this problem tonight.  It is interesting because it only happens on one of my environments.  I seem to be able to clone the others.

**Comment by ltransom** [comment] 2016-03-04 02:01
@mcg1969 and @kalefranz I tried a series of experiments.

*  I can install python 2 or 3 just fine with anaconda
*  I can clone my environment that do NOT have anaconda
*  I cannot clone an environment with anaconda, even with a clean install
  -  `conda create -n test python=2 anaconda` installs fine but the clone fails

**Comment by mcg1969** [comment] 2016-03-08 00:01
@kalefranz the problem here is that `misc.clone_env` doesn't handle symbolic links properly. If the environment has a symbolic link, it copies the file into the new environment instead of creating a duplicate symbolic link. So then when attempting to do `shutil.copystat(src, dst)`, it's trying to copy the flags from a symbolic link onto an actual file.

In this case, `libgcc_s` is an absolute symbolic link to a system library, so we might as well duplicate the link.

**Comment by mcg1969** [comment] 2016-03-08 00:04
Fix in preparation. But here's what I want to know: why is `clone_env` using low-level file operations to copy a file? Why is it not using `shutil.copy`?

**Comment by mcg1969** [comment] 2016-03-08 00:14
https://github.com/conda/conda/pull/2194

**Comment by kalefranz** [comment] 2016-03-10 06:16
Also see comments in #2120.

**Closed by kalefranz** 2016-03-10 06:16 UTC
