### ISSUE TITLE
conda update fails on macOS

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#7297] opened 2018-05-16 19:13 UTC
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

`conda update conda` fails both while `base` is active and in any other env.
It warns about an existing update, but then return the update attempt with `All requested packages already installed`.

### Steps to Reproduce

```
(stable) └─❱❱❱ conda update -n base conda                                           +9702 13:06 ❰─┘
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.3
  latest version: 4.5.4

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed.


┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(stable) └─❱❱❱ conda --version                                                      +9703 13:06 ❰─┘
conda 4.5.3

┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
└─❱❱❱ conda activate base                                                           +9706 13:08 ❰─┘

┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(base) └─❱❱❱ conda update conda                                                     +9707 13:08 ❰─┘
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.3
  latest version: 4.5.4

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed.
```

## Expected Behavior

Updates are being performed with the advised commands.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : base
    active env location : /Users/klay6683/miniconda3
            shell level : 1
       user config file : /Users/klay6683/.condarc
 populated config files : /Users/klay6683/miniconda3/.condarc
                          /Users/klay6683/.condarc
          conda version : 4.5.3
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /Users/klay6683/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/NSIDC/osx-64
                          https://conda.anaconda.org/NSIDC/noarch
          package cache : /Users/klay6683/miniconda3/pkgs
                          /Users/klay6683/.conda/pkgs
       envs directories : /Users/klay6683/miniconda3/envs
                          /Users/klay6683/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.3 requests/2.18.4 CPython/3.6.3 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 273771:2260
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/klay6683/miniconda3/.condarc <==
pinned_packages:
  - conda-forge::gdal

==> /Users/klay6683/.condarc <==
auto_update_conda: True
channels:
  - conda-forge
  - defaults
  - NSIDC
report_errors: True

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/klay6683/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.23.0           py36h782d450_0    defaults
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.2           py36hd3e6348_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
conda                     4.5.3                    py36_0    conda-forge
conda-env                 2.6.0                h36134e3_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.0                  hd04f020_2    defaults
openssl                   1.0.2o                        0    conda-forge
pip                       9.0.1            py36h1555ced_4    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
python                    3.6.3                h47c878a_7    defaults
python.app                2                py36h54569d5_7    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
setuptools                36.5.0           py36h2134326_0    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
sqlite                    3.20.1               h7e4c145_2    defaults
tk                        8.6.7                h35a86e2_3    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

**Comment by mbargull** [comment] 2018-05-16 22:01
duplicate of gh-7165

https://github.com/conda/conda/issues/7165#issuecomment-389320976:
> Resolved with #7289 to be released in 4.5.5.

**Closed by mbargull** 2018-05-16 22:01 UTC
