### ISSUE TITLE
GIT_BUILD_STR doesn't uniquely identify a build if the package supports different versions of python and numpy

### ISSUE THREAD

**Issue by chdoig** [conda/conda#1179] opened 2015-03-04 06:59 UTC
I was having an issue where binstar build was overwriting the previous builds (combinations of python and numpy versions) in into, just leaving one available version (python=3.4 and numpy=1.9). You can read the full issue and discussion here: https://github.com/ContinuumIO/into/issues/113.

While going through the issue, I found out that the problem was that the package build string used in the meta.yaml file was not uniquely identifiable across combinations of python and numpy versions, since GIT_BUILD_STR just identifies a commit, not a build. 

The conda.recipe was written following the only example in the docs that is not `abc`.
http://conda.pydata.org/docs/build.html#git-environment-variables

```
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}
```

Although the docs mention that  "it will override the default build string with the Python and Numpy versions", it is not clear that the example will cause the built package to not be uniquely identifiable across different combinations of python and numpy versions (when many packages offer support for a combination of them), and it is prone to cause problems.

I know there are workarounds to solve it, like what conda-env does:
https://github.com/conda/conda-env/blob/44fe0c2471bc505529134003de42d78754fbaddc/conda.recipe/meta.yaml

```
{% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
```

but I believe that conda recipes should be simpler than having to write that every time and we could easily provide an environment variable that contains for example CONDA_PY, CONDA_NPY and GIT_DESCRIBE_HASH.

I also think that examples in the docs should provide a simple standard, and from the aforementioned reasons, GIT_BUILD_STR is not a good one.

cc: @asmeurer, @tswicegood

**Comment by asmeurer** [comment] 2015-03-04 21:44
I thought I had already fixed this. I guess not.

**Comment by asmeurer** [comment] 2015-03-04 21:47
Ohhh, I remember now. The actual Python version and build number is not known at templating time.  See https://github.com/conda/conda-build/pull/223.

**Comment by asmeurer** [comment] 2015-03-04 21:47
Also https://github.com/conda/conda-build/issues/191. I want to close this as a dupe of those (and it's in the wrong repo anyway).

**Closed by asmeurer** 2015-03-04 21:47 UTC
