### ISSUE TITLE
Mini/Ana Conda installation error and CondaHTTPError: HTTP 000 CONNECTION FAILED

### ISSUE THREAD

**Issue by chayanroyc** [conda/conda#10987] opened 2021-10-12 23:54 UTC
### What happened?

Hi, so I have anaconda installed in an HPC with Linux and whenever I try to use conda to install anything or do some update, it shows this error,

```
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/linux-64'
```

Even when I try to download the latest version of Anaconda and Miniconda it shows me the following:

```
Miniconda3 will now be installed into this location:
/home/croychoudhury/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/croychoudhury/miniconda3] >>> 
PREFIX=/home/croychoudhury/miniconda3
Unpacking payload ...
Collecting package metadata (current_repodata.json): done                                                
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                   

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package readline conflicts for:
certifi==2021.5.30=py37h06a4308_0 -> python[version='>=3.7,<3.8.0a0'] -> readline[version='>=8.0,<9.0a0']
urllib3==1.26.6=pyhd3eb1b0_1 -> python[version='>=3.6,<4.0'] -> readline[version='>=8.0,<9.0a0']
pip==21.1.3=py37h06a4308_0 -> python[version='>=3.7,<3.8.0a0'] -> readline[version='>=8.0,<9.0a0']
chardet==4.0.0=py37h06a4308_1003 -> python[version='>=3.7,<3.8.0a0'] -> readline[version='>=8.0,<9.0a0']
brotlipy==0.7.0=py37h27cfd23_1003 -> python[version='>=3.7,<3.8.0a0'] -> readline[version='>=8.0,<9.0a0']
six==1.16.0=pyhd3eb1b0_0 -> python -> readline[version='>=8.0,<9.0a0']
```

I tried all the solutions found online for the HTTP 000 error but none of them worked.
I don't why there are so many issues popping up these days. I would gladly appreciate any help Thanks.

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /usr/local/anaconda3
            shell level : 1
       user config file : /home/croychoudhury/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __linux=2.6.32=0
                          __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/anaconda3  (read only)
      conda av data dir : /usr/local/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /home/croychoudhury/.conda/pkgs
       envs directories : /home/croychoudhury/.conda/envs
                          /usr/local/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.5 Linux/2.6.32-754.33.1.el6.x86_64 centos/6.10 glibc/2.12
                UID:GID : 1878341100:1878341100
             netrc file : /home/croychoudhury/.netrc
           offline mode : False
```

</details>

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /usr/local/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaults
_libgcc_mutex             0.1                        main    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
anaconda                  custom                   py38_1    defaults
anaconda-client           1.8.0            py38h06a4308_0    defaults
anaconda-navigator        1.10.0                   py38_0    defaults
anaconda-project          0.10.1             pyhd3eb1b0_0    defaults
anyio                     2.2.0            py38h06a4308_1    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
argh                      0.26.2                   py38_0    defaults
argon2-cffi               20.1.0           py38h27cfd23_1    defaults
asn1crypto                1.4.0                      py_0    defaults
astroid                   2.6.6            py38h06a4308_0    defaults
astropy                   4.3.1            py38h09021b7_0    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
autopep8                  1.5.4                      py_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.0                pyhd3eb1b0_2    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.10.0             pyh06a4308_0    defaults
bitarray                  2.3.0            py38h7f8727e_1    defaults
bkcharts                  0.2                      py38_0    defaults
black                     19.10b0                    py_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.0.0              pyhd3eb1b0_0    defaults
blosc                     1.21.0               h8c45485_0    defaults
bokeh                     2.3.3            py38h06a4308_0    defaults
boto                      2.49.0                   py38_0    defaults
bottleneck                1.3.2            py38heb32a55_1    defaults
brotlipy                  0.7.0           py38h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.17.1               h27cfd23_0    defaults
ca-certificates           2021.7.5             h06a4308_1    defaults
cairo                     1.16.0               hf32fb01_1    defaults
certifi                   2021.5.30        py38h06a4308_0    defaults
cffi                      1.14.6           py38h400218f_0    defaults
chardet                   4.0.0           py38h06a4308_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.1              pyhd3eb1b0_0    defaults
cloudpickle               1.6.0              pyhd3eb1b0_0    defaults
clyent                    1.2.2                    py38_1    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
conda                     4.10.3           py38h06a4308_0    defaults
conda-build               3.20.5                   py38_1    defaults
conda-env                 2.6.0                         1    defaults
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    1.7.3            py38h27cfd23_1    defaults
conda-verify              3.4.2                      py_1    defaults
contextlib2               0.6.0.post1        pyhd3eb1b0_0    defaults
cryptography              3.4.7            py38hd23ed53_0    defaults
curl                      7.78.0               h1ccaba5_0    defaults
cycler                    0.10.0                   py38_0    defaults
cython                    0.29.24          py38h295c915_0    defaults
cytoolz                   0.11.0           py38h7b6447c_0    defaults
dask                      2021.8.1           pyhd3eb1b0_0    defaults
dask-core                 2021.8.1           pyhd3eb1b0_0    defaults
dataclasses               0.8                pyh6d0b6a4_7    defaults
dbus                      1.13.18              hb2f20db_0    defaults
debugpy                   1.4.1            py38h295c915_0    defaults
decorator                 5.0.9              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713           pyhd3eb1b0_0    defaults
distributed               2021.8.1         py38h06a4308_0    defaults
docutils                  0.17.1           py38h06a4308_1    defaults
entrypoints               0.3                      py38_0    defaults
et_xmlfile                1.1.0            py38h06a4308_0    defaults
expat                     2.4.1                h2531618_2    defaults
fastcache                 1.1.0            py38h7b6447c_0    defaults
filelock                  3.0.12             pyhd3eb1b0_1    defaults
flake8                    3.8.4                      py_0    defaults
flask                     1.1.2              pyhd3eb1b0_0    defaults
fontconfig                2.13.1               h6c09931_0    defaults
freetype                  2.10.4               h5ab3b9f_0    defaults
fribidi                   1.0.10               h7b6447c_0    defaults
fsspec                    2021.8.1           pyhd3eb1b0_0    defaults
future                    0.18.2                   py38_1    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    21.8.0           py38h7f8727e_1    defaults
glib                      2.69.1               h5202010_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
gmp                       6.2.1                h2531618_2    defaults
gmpy2                     2.0.8            py38hd5f6e3b_3    defaults
graphite2                 1.3.14               h23475e2_0    defaults
greenlet                  1.1.1            py38h295c915_0    defaults
gst-plugins-base          1.14.0               h8213a91_2    defaults
gstreamer                 1.14.0               h28cd5cc_2    defaults
h5py                      2.10.0           py38h7918eee_0    defaults
harfbuzz                  2.8.1                h6f93f22_0    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
heapdict                  1.0.1              pyhd3eb1b0_0    defaults
html5lib                  1.1                pyhd3eb1b0_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.2                pyhd3eb1b0_0    defaults
imageio                   2.9.0              pyhd3eb1b0_0    defaults
imagesize                 1.2.0              pyhd3eb1b0_0    defaults
importlib-metadata        4.8.1            py38h06a4308_0    defaults
importlib_metadata        4.8.1                hd3eb1b0_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
intel-openmp              2021.3.0          h06a4308_3350    defaults
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.2.0            py38h06a4308_1    defaults
ipython                   7.27.0           py38hb070fc8_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.3              pyhd3eb1b0_1    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
itsdangerous              2.0.1              pyhd3eb1b0_0    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4.1              pyhd3eb1b0_0    defaults
jedi                      0.17.2           py38h06a4308_1    defaults
jeepney                   0.7.1              pyhd3eb1b0_0    defaults
jinja2                    3.0.1              pyhd3eb1b0_0    defaults
joblib                    1.0.1              pyhd3eb1b0_0    defaults
jpeg                      9d                   h7f8727e_0    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter                   1.0.0                    py38_7    defaults
jupyter_client            7.0.1              pyhd3eb1b0_0    defaults
jupyter_console           6.4.0              pyhd3eb1b0_0    defaults
jupyter_core              4.7.1            py38h06a4308_0    defaults
jupyter_server            1.4.1            py38h06a4308_0    defaults
jupyterlab                3.1.7              pyhd3eb1b0_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.8.1              pyhd3eb1b0_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
keyring                   23.1.0           py38h06a4308_0    defaults
kiwisolver                1.3.1            py38h2531618_0    defaults
krb5                      1.19.2               hac12032_0    defaults
lazy-object-proxy         1.6.0            py38h27cfd23_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libarchive                3.4.2                h62408e4_0    defaults
libcurl                   7.78.0               h0b77cf5_0    defaults
libedit                   3.1.20210714         h7f8727e_0    defaults
libev                     4.33                 h7b6447c_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblief                   0.10.1               he6710b0_0    defaults
libllvm10                 10.0.1               hbcb73fb_5    defaults
libllvm9                  9.0.1                h4a3c616_1    defaults
libnghttp2                1.41.0               hf8bcb03_2    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libspatialindex           1.9.3                h2531618_0    defaults
libssh2                   1.9.0                h1ba5d50_1    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libtool                   2.4.6             h7b6447c_1005    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libuv                     1.40.0               h7b6447c_0    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.10               hb55368b_3    defaults
libxslt                   1.1.34               hc22bd24_0    defaults
llvmlite                  0.36.0           py38h612dafd_4    defaults
locket                    0.2.1            py38h06a4308_1    defaults
lxml                      4.6.3            py38h9120a33_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
lzo                       2.10                 h7b6447c_2    defaults
markupsafe                2.0.1            py38h27cfd23_0    defaults
matplotlib                3.3.4            py38h06a4308_0    defaults
matplotlib-base           3.3.4            py38h62a2d02_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mccabe                    0.6.1                    py38_1    defaults
mistune                   0.8.4           py38h7b6447c_1000    defaults
mkl                       2021.3.0           h06a4308_520    defaults
mkl-service               2.4.0            py38h7f8727e_0    defaults
mkl_fft                   1.3.0            py38h42c9631_2    defaults
mkl_random                1.2.2            py38h51133e4_0    defaults
mock                      4.0.3              pyhd3eb1b0_0    defaults
more-itertools            8.8.0              pyhd3eb1b0_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.2                hb69a4c5_1    defaults
mpmath                    1.2.1            py38h06a4308_0    defaults
msgpack-python            1.0.2            py38hff7bd54_1    defaults
multipledispatch          0.6.0                    py38_0    defaults
mypy_extensions           0.4.3                    py38_0    defaults
navigator-updater         0.2.1                    py38_0    defaults
nbclassic                 0.2.6              pyhd3eb1b0_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.1.0            py38h06a4308_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
networkx                  2.6.2              pyhd3eb1b0_0    defaults
nltk                      3.6.2              pyhd3eb1b0_0    defaults
nose                      1.3.7           pyhd3eb1b0_1006    defaults
notebook                  6.4.3            py38h06a4308_0    defaults
numba                     0.53.1           py38ha9443f7_0    defaults
numexpr                   2.7.3            py38h22e1b3c_1    defaults
numpy                     1.20.3           py38hf144106_0    defaults
numpy-base                1.20.3           py38h74d4b33_0    defaults
numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
openjpeg                  2.4.0                h3ad879b_0    defaults
openpyxl                  3.0.7              pyhd3eb1b0_0    defaults
openssl                   1.1.1l               h7f8727e_0    defaults
packaging                 21.0               pyhd3eb1b0_0    defaults
pandas                    1.3.2            py38h8c16a72_0    defaults
pandoc                    2.12                 h06a4308_0    defaults
pandocfilters             1.4.3            py38h06a4308_1    defaults
pango                     1.45.3               hd140c19_0    defaults
parso                     0.7.0                      py_0    defaults
partd                     1.2.0              pyhd3eb1b0_0    defaults
patchelf                  0.13                 h295c915_0    defaults
path                      16.0.0           py38h06a4308_0    defaults
path.py                   12.5.0               hd3eb1b0_0    defaults
pathlib2                  2.3.6            py38h06a4308_2    defaults
pathspec                  0.7.0                      py_0    defaults
pathtools                 0.1.2              pyhd3eb1b0_1    defaults
patsy                     0.5.1                    py38_0    defaults
pcre                      8.45                 h295c915_0    defaults
pep8                      1.7.1                    py38_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.3.1            py38h2c7a002_0    defaults
pip                       21.0.1           py38h06a4308_0    defaults
pixman                    0.40.0               h7f8727e_0    defaults
pkginfo                   1.7.1            py38h06a4308_0    defaults
pluggy                    0.13.1           py38h06a4308_0    defaults
ply                       3.11                     py38_0    defaults
prometheus_client         0.11.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.17             pyhca03da5_0    defaults
prompt_toolkit            3.0.17               hd3eb1b0_0    defaults
psutil                    5.8.0            py38h27cfd23_1    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
py                        1.10.0             pyhd3eb1b0_0    defaults
py-lief                   0.10.1           py38h403a769_0    defaults
pycodestyle               2.6.0              pyhd3eb1b0_0    defaults
pycosat                   0.6.3            py38h7b6447c_1    defaults
pycparser                 2.20                       py_2    defaults
pycurl                    7.43.0.6         py38h1ba5d50_0    defaults
pydocstyle                6.1.1              pyhd3eb1b0_0    defaults
pyerfa                    2.0.0            py38h27cfd23_0    defaults
pyflakes                  2.2.0              pyhd3eb1b0_0    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pylint                    2.9.6            py38h06a4308_1    defaults
pyls-black                0.4.6                hd3eb1b0_0    defaults
pyls-spyder               0.3.2              pyhd3eb1b0_0    defaults
pyodbc                    4.0.31           py38h295c915_0    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py38h05f1152_4    defaults
pyrsistent                0.17.3           py38h7b6447c_0    defaults
pysocks                   1.7.1            py38h06a4308_0    defaults
pytables                  3.6.1            py38h9fd0a39_0    defaults
pytest                    6.2.4            py38h06a4308_2    defaults
python                    3.8.5                h7579374_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-jsonrpc-server     0.4.0                      py_0    defaults
python-language-server    0.36.2             pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
pywavelets                1.1.1            py38h7b6447c_2    defaults
pyxdg                     0.27               pyhd3eb1b0_0    defaults
pyyaml                    5.4.1            py38h27cfd23_1    defaults
pyzmq                     22.2.1           py38h295c915_1    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtawesome                 1.0.2              pyhd3eb1b0_0    defaults
qtconsole                 5.1.0              pyhd3eb1b0_0    defaults
qtpy                      1.10.0             pyhd3eb1b0_0    defaults
readline                  8.1                  h27cfd23_0    defaults
regex                     2021.8.3         py38h7f8727e_0    defaults
requests                  2.26.0             pyhd3eb1b0_0    defaults
ripgrep                   12.1.1                        0    defaults
rope                      0.19.0             pyhd3eb1b0_0    defaults
rtree                     0.9.7            py38h06a4308_1    defaults
ruamel_yaml               0.15.100         py38h27cfd23_0    defaults
scikit-image              0.18.1           py38ha9443f7_0    defaults
scikit-learn              0.24.2           py38ha9443f7_0    defaults
scipy                     1.6.2            py38had2a1c9_1    defaults
seaborn                   0.11.2             pyhd3eb1b0_0    defaults
secretstorage             3.3.1            py38h06a4308_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                58.0.4           py38h06a4308_0    defaults
simplegeneric             0.8.1                    py38_2    defaults
singledispatch            3.7.0           pyhd3eb1b0_1001    defaults
sip                       4.19.13          py38he6710b0_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
snappy                    1.1.8                he6710b0_0    defaults
sniffio                   1.2.0            py38h06a4308_1    defaults
snowballstemmer           2.1.0              pyhd3eb1b0_0    defaults
sortedcollections         2.1.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.2.1              pyhd3eb1b0_0    defaults
sphinx                    4.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib             1.0                      py38_1    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
sphinxcontrib-websupport  1.2.4                      py_0    defaults
spyder                    4.2.5            py38h06a4308_0    defaults
spyder-kernels            1.10.2           py38h06a4308_0    defaults
sqlalchemy                1.4.22           py38h7f8727e_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
statsmodels               0.12.2           py38h27cfd23_0    defaults
sympy                     1.8              py38h06a4308_0    defaults
tbb                       2020.3               hfd86e86_0    defaults
tblib                     1.7.0              pyhd3eb1b0_0    defaults
terminado                 0.9.4            py38h06a4308_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
threadpoolctl             2.2.0              pyh0d69192_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tifffile                  2020.10.1        py38hdd07704_2    defaults
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.11.1             pyhd3eb1b0_0    defaults
tornado                   6.1              py38h27cfd23_0    defaults
tqdm                      4.62.2             pyhd3eb1b0_1    defaults
traitlets                 5.0.5              pyhd3eb1b0_0    defaults
typed-ast                 1.4.3            py38h7f8727e_1    defaults
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
ujson                     4.0.2            py38h2531618_0    defaults
unicodecsv                0.14.1                   py38_0    defaults
unixodbc                  2.3.9                h7b6447c_0    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
watchdog                  1.0.2            py38h06a4308_1    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py38_1    defaults
werkzeug                  2.0.1              pyhd3eb1b0_0    defaults
wheel                     0.37.0             pyhd3eb1b0_1    defaults
widgetsnbextension        3.5.1                    py38_0    defaults
wrapt                     1.12.1           py38h7b6447c_1    defaults
wurlitzer                 2.1.1            py38h06a4308_0    defaults
xlrd                      2.0.1              pyhd3eb1b0_0    defaults
xlsxwriter                3.0.1              pyhd3eb1b0_0    defaults
xlwt                      1.3.0                    py38_0    defaults
xmltodict                 0.12.0             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yapf                      0.31.0             pyhd3eb1b0_0    defaults
zeromq                    4.3.4                h2531618_0    defaults
zict                      2.0.0              pyhd3eb1b0_0    defaults
zipp                      3.5.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zope                      1.0                      py38_1    defaults
zope.event                4.5.0                    py38_0    defaults
zope.interface            5.4.0            py38h7f8727e_0    defaults
zstd                      1.4.9                haebb681_0    defaults
```

</details>

**Comment by stevenrjanssens** [comment] 2021-10-16 09:35
Hit the same issue on the HPC environment that I use. It too is still on CentOS 6.10 (sadly this is out of my control).

`curl -L --head https://repo.anaconda.com/pkgs/main/linux-64/repodata.json` spits out `200 OK`.

I believe the issue is the system version of GLIBC is old (2.12) and packages in the latest conda are looking for much newer versions.

I encountered similar conflicts when reinstalling conda using the newest Miniconda installer. However, at the end is the GLIBC conflict:

```
Package chardet conflicts for:
chardet==4.0.0=py39h06a4308_1003
requests==2.25.1=pyhd3eb1b0_0 -> chardet[version='>=3.0.2,<5']
conda==4.10.3=py39h06a4308_0 -> requests[version='>=2.18.4,<3'] -> chardet[version='>=3.0.2,<5']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.12=0
  - feature:|@/linux-64::__glibc==2.12=0
  - brotlipy==0.7.0=py39h27cfd23_1003 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - cffi==1.14.6=py39h400218f_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-package-handling==1.7.3=py39h27cfd23_1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - cryptography==3.4.7=py39hd23ed53_0 -> libgcc-ng -> __glibc[version='>=2.17']
  - libgcc-ng==9.3.0=h5101ec6_17 -> __glibc[version='>=2.17']
  - libstdcxx-ng==9.3.0=hd4cf53a_17 -> __glibc[version='>=2.17']
  - ncurses==6.2=he6710b0_1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - openssl==1.1.1k=h27cfd23_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pycosat==0.6.3=py39h27cfd23_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - python==3.9.5=h12debd9_4 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - readline==8.1=h27cfd23_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - ruamel_yaml==0.15.100=py39h27cfd23_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - sqlite==3.36.0=hc218d9a_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - tk==8.6.10=hbc83047_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - xz==5.2.5=h7b6447c_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - yaml==0.2.5=h7b6447c_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zlib==1.2.11=h7b6447c_3 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.12
```

I grabbed an installer from a year ago and it installed fine. However, upon completing a `conda update --all`, conda python then fails complaining that a recent version of GLIBC (2.14, 2.15, 2.17) isn't found.

```
$ conda
/home/janssens/miniconda3/bin/python: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/janssens/miniconda3/bin/python)
/home/janssens/miniconda3/bin/python: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/janssens/miniconda3/bin/python)
/home/janssens/miniconda3/bin/python: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/janssens/miniconda3/bin/python)
```

**Comment by ntraut** [comment] 2021-11-08 17:36
Same problem for me. Solved by compiling a newer version of glibc in linuxbrew and then i can run python with ssl support with `$HOME/.linuxbrew/lib/ld-2.23.so --library-path $HOME/.linuxbrew/lib $HOME/miniconda3/bin/python`.

**Comment by kenodegard** [comment] 2022-03-25 17:29
Closing since this issue is ultimately caused by running `conda` on an incompatible OS with an outdated GLIBC.

**Closed as completed by kenodegard** 2022-03-25 17:29 UTC
Labels: type::support, source::community, locked
