### ISSUE TITLE
conda list <package_name> failing. 

### ISSUE THREAD

**Issue by weinbe58** [conda/conda#6123] opened 2017-10-09 12:26 UTC
I don't know what I did to make this happen, but now every time I try to use conda list I get an error. Here is the message it gives me:

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /usr/share/anaconda2  (writable)
    default environment : /usr/share/anaconda2
       envs directories : /usr/share/anaconda2/envs
                          /home/phillip/.conda/envs
          package cache : /usr/share/anaconda2/pkgs
                          /home/phillip/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/phillip/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-96-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /usr/share/anaconda2/bin/conda list matplotlib`

    Traceback (most recent call last):
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 242, in execute
        show_channel_urls=context.show_channel_urls)
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 172, in print_packages
        installed = linked(prefix)
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/usr/share/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Invalid value 1506017697.64 for timestamp

**Comment by msarahan** [comment] 2017-10-09 13:11
closing as duplicate of #6096

**Closed by msarahan** 2017-10-09 13:11 UTC
