### ISSUE TITLE
bad order of paths in sys.path for pip in python 2.7

### ISSUE THREAD

**Issue by michalsustr** [conda/conda#3839] opened 2016-11-08 12:59 UTC
I've installed anaconda3 from the official site, with conda version 

```
$ conda -V
conda 4.2.9
```

Then I created two environments, one for py2.7.12 and for py3.5.2:
```
$ conda create --name py27 python=2.7
$ conda create --name py35 python=3.5
```

```
(py27) $ which pip
/home/michal/Bin/anaconda3/envs/py27/bin/pip
(py27) $ pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
(py27) $ which python
/home/michal/Bin/anaconda3/envs/py27/bin/python
(py27) $ python -V
Python 2.7.12 :: Continuum Analytics, Inc.

(py35) $ which pip
/home/michal/Bin/anaconda3/envs/py35/bin/pip
(py35) $ pip -V
pip 9.0.1 from /home/michal/Bin/anaconda3/envs/py35/lib/python3.5/site-packages (python 3.5)
(py35) $ which python
/home/michal/Bin/anaconda3/envs/py35/bin/python
(py35) $ python -V
Python 3.5.2 :: Continuum Analytics, Inc.
```

When I install a package via pip in 35 it works fine, but in 27 I got a problem with paths, trying to run system python's pip. After some investigation which took me almost two days I found that `/usr/lib/python2.7` have been prepended instead of appended into `sys.path`.

By editing `/home/michal/Bin/anaconda3/envs/py27/bin/pip` 

```
    import sys
    sys.path = ['', 
        '/home/michal/Code/BSS/raptor', 
        '/home/michal/Code/BSS/fairalgo/src', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python27.zip', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python2.7', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python2.7/plat-linux2', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python2.7/lib-tk', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python2.7/lib-old', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python2.7/lib-dynload', 
        '/home/michal/.local/lib/python2.7/site-pckages', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python2.7/site-packages', 
        '/home/michal/Bin/anaconda3/envs/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg',
        '/usr/lib/python2.7', 
        '/usr/lib/python2.7/dist-packages', 
    ]
    import pip
```

After fix:
```
(py27) $ pip -V
pip 9.0.1 from /home/michal/Bin/anaconda3/envs/py27/lib/python2.7/site-packages (python 2.7)
```

I got it to work. I don't know where these paths are added into `sys.path`, my `~/.bashrc` is clean (no additions to `$PYTHONPATH`)

Any idea how to solve this without "hacking" pip file?

Thanks!

**Comment by michalsustr** [comment] 2016-11-08 13:24
The problem seems to still remain:
```
(py27) $ pip install cryptography==1.5
Collecting cryptography==1.5
  Using cached cryptography-1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-O5JPo5/cryptography/setup.py", line 50, in <module>
        if platform.python_implementation() == "PyPy":
      File "/usr/lib/python2.7/platform.py", line 1521, in python_implementation
        return _sys_version()[0]
      File "/usr/lib/python2.7/platform.py", line 1486, in _sys_version
        repr(sys_version))
    ValueError: failed to parse CPython sys.version: '2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-O5JPo5/cryptography/
```

**Comment by kalefranz** [comment] 2017-05-05 00:23
Duplicate of #3606

**Closed by kalefranz** 2017-05-05 00:23 UTC
