### ISSUE TITLE
conda run -n MY-ENV python FILE.py uses the base interpreter instead of environment interpreter.

### ISSUE THREAD

**Issue by Parskatt** [conda/conda#9587] opened 2020-01-10 12:42 UTC
**I'm submitting a...**
  - bug report
  - [ ] feature request

## Current Behavior

Using conda run -n for environments, when shell is in specified environment, leads to default conda interpreter being used instead of environment interpreter. This leads to python not finding packages e.g. numpy.

### Steps to Reproduce
On w10 with miniconda + at least 1 environment.

Running:

```¨
conda activate MY-ENV
conda run -n MY-ENV python .\test.py
```
In PS or cmd on the python file
 ```python
import sys
print(sys.executable)
```
Prints: "conda path"\python.exe (in my case: C:\Users\parsk\Miniconda3\python.exe i.e. the base conda environment)

## Expected Behavior

The environment python interpreter should be called, e.g. C:\Users\parsk\Miniconda3\envs\MY-ENV\python.exe

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : MY-ENV
    active env location : C:\Users\parsk\Miniconda3\envs\MY-ENV
            shell level : 2
       user config file : C:\Users\parsk\.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\parsk\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\parsk\Miniconda3\pkgs
                          C:\Users\parsk\.conda\pkgs
                          C:\Users\parsk\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\parsk\Miniconda3\envs
                          C:\Users\parsk\.conda\envs
                          C:\Users\parsk\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(empty)
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\parsk\Miniconda3:
#
# Name                    Version                   Build  Channel
altgraph                  0.16.1                   pypi_0    pypi
asn1crypto                1.2.0                    py37_0    defaults
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.13.0           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
conda                     4.7.12                   py37_0    defaults
conda-package-handling    1.6.0            py37h62dcd97_0    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
future                    0.18.2                   pypi_0    pypi
idna                      2.8                      py37_0    defaults
menuinst                  1.4.16           py37he774522_0    defaults
openssl                   1.1.1d               he774522_3    defaults
pefile                    2019.4.18                pypi_0    pypi
pip                       19.3.1                   py37_0    defaults
powershell_shortcut       0.0.1                         2    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyinstaller               3.5                      pypi_0    pypi
pyopenssl                 19.0.0                   py37_0    defaults
pyqt5                     5.13.2                   pypi_0    pypi
pyqt5-sip                 12.7.0                   pypi_0    pypi
pyqtchart                 5.13.1                   pypi_0    pypi
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.4                h5263a28_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywin32-ctypes            0.2.0                    pypi_0    pypi
requests                  2.22.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                41.4.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.30.0               he774522_0    defaults
tqdm                      4.36.1                     py_0    defaults
urllib3                   1.24.2                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wheel                     0.33.6                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
```
</p></details>

**Comment by Parskatt** [comment] 2020-01-10 12:46
Some further info: Reason that this is a problem for me is because vscode's default "Run Python file in terminal" uses this command. I'm temporarily using the debugger instead since that calls the correct interpreter.

**Comment by nfearnley** [comment] 2020-01-10 21:27
I'm having the same issue. The python linter tries to run the following command, and fails to find the flake8 linter.

```
conda run -n myenv python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\path\to\file.py
```

If I activate my environment, then run flake8 by hand, it runs successfully
```
> (myenv) C:\path\to>flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows
```

This only seems to be an issue when I already have an enviroment loaded (other than base), and I am trying to call is with `python -m`. It seems to find the wrong instance of python. If I try to call flake8 directly instead of as a module, it seems to work fine.
```
> C:\path\to>conda run -n myenv flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows

> C:\path\to>conda run -n myenv python -m flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows

> (base) C:\path\to>conda run -n myenv flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows

> (base) C:\path\to>conda run -n myenv python -m flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows

> (myenv) C:\path\to>conda run -n myenv flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows

> (myenv) C:\path\to>conda run -n myenv python -m flake8 --version
C:\ProgramData\Miniconda3\python.exe: No module named flake8

> (otherenv) C:\path\to>conda run -n myenv flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.1 on Windows

> (otherenv) C:\path\to>conda run -n myenv python -m flake8 --version
C:\ProgramData\Miniconda3\python.exe: No module named flake8
```

Here's which python `conda run` is finding:
```
> C:\path\to>conda run -n myenv python -c "import sys; print(sys.executable)"
C:\ProgramData\Miniconda3\envs\myenv\python.exe

> (base) C:\path\to>conda run -n myenv python -c "import sys; print(sys.executable)"
C:\ProgramData\Miniconda3\envs\myenv\python.exe

> (myenv) C:\path\to>conda run -n myenv python -c "import sys; print(sys.executable)"
C:\ProgramData\Miniconda3\python.exe

> (otherenv) C:\path\to>conda run -n myenv python -c "import sys; print(sys.executable)"
C:\ProgramData\Miniconda3\python.exe
```

**Comment by Parskatt** [comment] 2020-01-10 21:30
>This only seems to be an issue when I already have an enviroment loaded (other than base), and I >am trying to call is with python -m. It seems to find the wrong instance of python. If I try to call >flake8 directly instead of as a module, it seems to work fine.

Tested this. Same issue for me, works when called from base environment. Will update the original question.

**Comment by nfearnley** [comment] 2020-01-10 21:44
Actually, I just realized that, while it manages to find flake8, running `conda run -n myenv flake8 --version` (without `python -m`) from inside of an activated environment is still running the base interpreter (python 3.7) not the environment interpreter (python 3.8).

**Comment by nfearnley** [comment] 2020-01-10 21:49
Also, it seems this is a separate bug from the one causing problems with vscode. It like the percentages  are being mangled in the command before it reaches flake8:
```
conda run -n myenv python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\path\to\file.py
```
```
> conda run -n myenv echo python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\path\to\file.py
python -m flake8 --format=(col)d,(code)s:\path\to\file.py

> conda run -n myenv echo python -m flake8 --format=%%(row)d,%%(col)d,%(code).1s,%%(code)s:%%(text)s c:\path\to\file.py
python -m flake8 --format=(col)d,(code)s:\path\to\file.py
```

**Comment by Parskatt** [comment] 2020-01-10 21:53
@nfearnley https://github.com/conda/conda/issues/9579 , maybe this is related?

**Comment by nfearnley** [comment] 2020-01-10 23:26
I've figured out what caused this bug to first appear in VS Code.

It seems to be related to the vscode [python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python).

In version 2019.11.50794 of the extension, it calls flake8 by running the interpreter directly:
```
> C:\ProgramData\Miniconda3\envs\myenv\python.exe -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\path\to\file.py
5,1,F,F401:'itertools.zip_longest' imported but unused
```

In version 2020.1.57204, it calls flake8 using conda run:
```
> conda run -n myenv python -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\path\to\file.py
(col)d,(code)s:\path\to\file.py
```

Downgrading the vs code python extension to version 2019.11.50794 seems to work as a temporary fix

**Comment by beeb** [comment] 2020-01-13 06:17
@nfearnley The VSCode team is working on it, should be reverted back soon https://github.com/microsoft/vscode-python/issues/9481

**Comment by bilderbuchi** [comment] 2022-03-07 09:44
I am still seeing this as reported on Windows 10, conda 4.11.0

In the activated `myenv` (or **another non-base**, as I found out!) environment , running `conda run -n myenv python -c "import sys;print(sys.executable)"` points to the **base environment** interpreter, not the one of the environment. 
Only when in the `base` environment, does this correctly use `myenv`'s python interpreter.

**Comment by Parskatt** [comment] 2022-03-07 12:22
@bilderbuchi yes, same for me, luckily i'm just running the base environment anyway :p.
Probably introduced by a recent vscode patch.

**Comment by bilderbuchi** [comment] 2022-03-09 07:28
I'm using VS Code too, which surfaced this bug for me, but I don't see how the bug itself could be introduced by VS Code.

**Comment by bilderbuchi** [comment] 2022-03-09 07:47
#11305 is probably the same issue, #11174 sound related to this.

**Comment by Parskatt** [comment] 2022-03-09 08:16
@bilderbuchi I don't mean that vscode causes it, I just mean that depending on what vscode uses to run by default will surface the bug. In some versions of vscode they don't use conda run.

**Comment by kenodegard** [comment] 2022-03-09 21:30
Duplicate of https://github.com/conda/conda/issues/11174

**Closed by kenodegard** 2022-03-09 21:30 UTC
Labels: type::bug, source::community, plugins::run, duplicate

**Comment by ogindes** [comment] 2022-03-22 10:36
Was able to fix the issue by changing conda default environment in anaconda-navigator settings. It's not a fix but a workaround. hope it'll help someone <3
