### ISSUE TITLE
Error moving to old revision

### ISSUE THREAD

**Issue by evanburgess** [conda/conda#3158] opened 2016-07-26 18:03 UTC
Hi Conda folks,

I just tried to revert to an old revision and got the following.  First are just the results of a conda list --revisions.  And then an attempt to move to rev 5 and the traceback.  

Thanks,
Evan 

2016-07-15 16:23:52  (rev 4)
     anaconda  {4.0.0 -> custom}
     cloudpickle  {0.1.1 -> 0.2.1}
     conda  {4.1.5 -> 4.1.8}
     conda-env  {2.5.0 -> 2.5.2}
     dask  {0.8.1 -> 0.10.1}
     partd  {0.3.2 -> 0.3.4}

2016-07-25 13:43:22  (rev 5)
     astropy  {1.1.2 -> 1.2.1}
     bottleneck  {1.0.0 -> 1.1.0}
     conda  {4.1.8 -> 4.1.10}
     curl  {7.45.0 -> 7.49.0}
     geos  {3.4.2 -> 3.5.0}
     h5py  {2.5.0 -> 2.6.0}
     hdf4  {4.2.11 -> 4.2.12}
     hdf5  {1.8.15.1 -> 1.8.17}
     kealib  {1.4.5 -> 1.4.6}
     libgdal  {2.0.0 -> 2.1.0}
     libnetcdf  {4.3.3.1 -> 4.4.1}
     llvmlite  {0.9.0 -> 0.12.1}
     matplotlib  {1.5.1 -> 1.5.1}
     numba  {0.24.0 -> 0.27.0}
     numexpr  {2.5 -> 2.5.2}
     numpy  {1.10.4 -> 1.11.0}
     pandas  {0.18.0 -> 0.18.1}
     patsy  {0.4.0 -> 0.4.1}
     proj4  {4.9.1 -> 4.9.2}
     pycurl  {7.19.5.3 -> 7.43.0}
     pytables  {3.2.2 -> 3.2.3.1}
     scikit-image  {0.12.3 -> 0.12.3}
     scikit-learn  {0.17.1 -> 0.17.1}
     scipy  {0.17.0 -> 0.17.0}
     shapely  {1.5.13 -> 1.5.16}
     statsmodels  {0.6.1 -> 0.6.1}
     xerces-c  {3.1.2 -> 3.1.4}
    +click-6.6
    +click-plugins-1.0.3
    +cligj-0.4.0
    +fiona-1.7.0
    +geotiff-1.4.1
    +munch-2.0.4

2016-07-26 10:09:59  (rev 6)
     astropy  {1.2.1 -> 1.1.2}
     bottleneck  {1.1.0 -> 1.0.0}
     conda  {4.1.10 -> 4.1.8}
     curl  {7.49.0 -> 7.45.0}
     geos  {3.5.0 -> 3.4.2}
     h5py  {2.6.0 -> 2.5.0}
     hdf4  {4.2.12 -> 4.2.11}
     hdf5  {1.8.17 -> 1.8.15.1}
     kealib  {1.4.6 -> 1.4.5}
     libgdal  {2.1.0 -> 2.0.0}
     libnetcdf  {4.4.1 -> 4.3.3.1}
     llvmlite  {0.12.1 -> 0.9.0}
     matplotlib  {1.5.1 -> 1.5.1}
     numba  {0.27.0 -> 0.24.0}
     numexpr  {2.5.2 -> 2.5}
     numpy  {1.11.0 -> 1.10.4}
     pandas  {0.18.1 -> 0.18.0}
     patsy  {0.4.1 -> 0.4.0}
     proj4  {4.9.2 -> 4.9.1}
     pycurl  {7.43.0 -> 7.19.5.3}
     pytables  {3.2.3.1 -> 3.2.2}
     scikit-image  {0.12.3 -> 0.12.3}
     scikit-learn  {0.17.1 -> 0.17.1}
     scipy  {0.17.0 -> 0.17.0}
     shapely  {1.5.16 -> 1.5.13}
     statsmodels  {0.6.1 -> 0.6.1}
     xerces-c  {3.1.4 -> 3.1.2}
    -click-6.6
    -click-plugins-1.0.3
    -cligj-0.4.0
    -fiona-1.7.0
    -geotiff-1.4.1
    -munch-2.0.4

conda install --revision 5

Traceback (most recent call last):
  File "/home/eburgess/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/eburgess/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/eburgess/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/eburgess/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/home/eburgess/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 394, in install
    display_actions(actions, index, show_channel_urls=args.show_channel_urls)
  File "/home/eburgess/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 97, in display_actions
    rec = index[fkey]
KeyError: 'conda-4.1.10-py27_0.tar.bz2'

**Comment by HugoTian** [comment] 2016-07-27 17:49
I think there is something wrong with index which comes from repodata,  and could you please show the output of "conda info" as well as "conda --debug install --revision 5"

Thanks

**Comment by HugoTian** [comment] 2016-07-27 18:17
@evanburgess, the problem is that, when we want to roll back to an old state, some packages are not available on repodata.

So, an easy fix will be throw an exception, and say "this rev is not ok, please revert to an more recent version". May I know your opinion on this ?

Thanks

**Comment by HugoTian** [comment] 2016-07-28 14:26
@evanburgess , please  refer to PR #3181, and if you have any advice, please @ me under that PR.

I will close this issue, and feel free to reopen it. 

Thanks

**Closed by HugoTian** 2016-07-28 14:26 UTC
Labels: bug
