### ISSUE TITLE
Creating new environment silently crashes

### ISSUE THREAD

**Issue by alanhdu** [conda/conda#5004] opened 2017-04-05 21:46 UTC
I'm using a memory-constrained VM (DigitalOcean 512 MB droplet, although ~300 MB are used by other processes). When I run `conda env create` with the following `environment.yml` file:

```yaml
name: test
channels:
- conda-forge
dependencies:
- python
```

`conda env create` will silently fail with an exit code of 247 (e.g. no user-facing errors or stacktraces):

```bash
$ conda env create --name test
Fetching package metadata ..... $ echo $?
247
$ source activate test
CondaEnvironmentNotFoundError: Could not find environment: test .
You can list all discoverable environments with `conda info --envs`.

$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/2.7.13 Linux/3.13.0-32-generic debian/8.5 glibc/2.19
                UID:GID : 0:0
```

On the server, I can replicate this with the following `Dockerfile` and `environment.yml`:

```bash
$ cat Dockerfile 
FROM continuumio/miniconda

RUN conda update --all --yes
RUN conda info -a
COPY environment.yml /environment.yml
RUN conda env create --name test --file /environment.yml

$ cat environment.yml 
name: test
channels:
- conda-forge
dependencies:
- python

$ docker build .
Sending build context to Docker daemon 28.67 kB
Step 1/3 : FROM continuumio/miniconda
 ---> 8803dca81524
Step 2/3 : COPY environment.yml /environment.yml
 ---> Using cache
 ---> f86ee3406057
Step 3/3 : RUN conda env create --name test --file /environment.yml
 ---> Using cache
 ---> f406b9a6f6d1
Successfully built f406b9a6f6d1
root@adi-website:~/tmp# docker build .
Sending build context to Docker daemon 28.67 kB
Step 1/3 : FROM continuumio/miniconda
 ---> 8803dca81524
Step 2/3 : COPY environment.yml /environment.yml
 ---> Using cache
 ---> f86ee3406057
Step 3/3 : RUN conda env create --name test --file /environment.yml
 ---> Running in 8902825d5973
Fetching package metadata ...The command '/bin/sh -c conda env create --name test --file /environment.yml' returned a non-zero code: 247
```

If, however, I free up enough RAM (or use my laptop which has 8 GB of RAM), then this bug goes away (so I strong suspect this is related to #5003).

**Comment by kalefranz** [comment] 2017-05-10 04:07
I'd say this is a duplicate of #5003.

**Closed by kalefranz** 2017-05-10 04:07 UTC
