### ISSUE TITLE
Reopen 8565

### ISSUE THREAD

**Issue by steventartakovsky-vungle** [conda/conda#10287] opened 2020-10-14 17:08 UTC
Please reopen https://github.com/conda/conda/issues/8565 as it has not been resolved.

**Comment by harry-fuyu** [comment] 2021-02-22 03:27
I had the same problem and fixed it by deleting all exported paths and adding the following line to my .bashrc:
``` export PATH=/root/anaconda3/bin```
As suggested [here](https://stackoverflow.com/questions/59510865/unable-to-activate-existing-conda-environments), this error might be caused by repeatedly specifying the same path, which was what's happening in my original error-throwing .bashrc file.

**Comment by TitusCornelius** [comment] 2021-11-24 16:46
great, thanks for that input @harry-fuyu: That totally solved it.

I had both modified the path to include the binaries and then a `conda activate base` that I added later. Removing the manual (redundant) PATH modification got rid of the bug for me. Strange thing is that an `echo $PATH` before removing it didn't actually show any duplication. Weird. Either way, this solved it.

I think the issue should be closed. #

**Comment by beeankha** [comment] 2022-08-30 20:34
Closing this issue, as no further comments have been made on it (please re-open if this problem is persisting!)

**Closed by beeankha** 2022-08-30 20:34 UTC
