### ISSUE TITLE
unknown key conda-build

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7192] opened 2018-04-20 15:29 UTC
Saw this in a recent build log. Based on consensus, we thought it was coming from `conda`. That said, this is a `conda-build` key so....

In general would figure other build tools using `conda` could register keys they use from the config, but IDK if that is a thing we can do with `conda` currently. Also avoiding conflicts can get tricky.

Perhaps for now it is ok if `conda` learns the `conda-build` key is ok (even if it is a poor separation of concerns). Long term some sort of config discussion would be good.

ref: https://circleci.com/gh/conda-forge/conda-smithy-feedstock/220

cc @isuruf @msarahan

**Comment by kalefranz** [comment] 2018-04-20 16:06
That looks wrong.  `conda-build` shouldn't be an unknown key I don't think.  It's a map-type key that conda's configuration is supposed to read for conda-build.  I'll look into it.

**Comment by msarahan** [comment] 2018-04-20 16:07
Conda should definitely know this key.  It is well-documented: https://conda.io/docs/user-guide/configuration/use-condarc.html#conda-build-configuration

Thanks @kalefranz for looking into it, and thanks @jakirkham for pointing it out.

**Comment by kalefranz** [comment] 2018-04-20 16:10
I see.  This is coming from `conda config --get`.  The message is benign.  The issue is that `conda config --get` doesn't work well with map-type keys.  So the message is a little misleading.  It also has basically no effect.

**Comment by kalefranz** [comment] 2018-04-20 16:12
I'm inclined not to worry about this for now and just close it.  I'm not a fan of the `conda config --get` pattern.  In conda-forge's CI setup, I'd recommend using `conda config --show` and/or `conda config --show-sources` there instead.

**Closed by kalefranz** 2018-04-20 16:12 UTC
Labels: source:community, type:bug

**Comment by kalefranz** [comment] 2018-04-20 16:14
> I'm not a fan of the `conda config --get` pattern.

I think the idea was that you could somehow pipe the output of `conda config --get` into `conda config` and then basically recreate your config.  It wasn't ever fully implemented.

**Comment by jakirkham** [comment] 2018-04-20 16:43
Thanks for the info. I think `conda config --show-sources` is what we are looking for. We are just interested in verifying/providing the contents of `.condarc` in the log. Will update accordingly.
