### ISSUE TITLE
conda fail

### ISSUE THREAD

**Issue by ypc8272805** [conda/conda#6253] opened 2017-11-02 08:27 UTC
(F:\Anaconda3) C:\Users\ypc8272805>conda install numpy
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : F:\Anaconda3  (writable)
    default environment : F:\Anaconda3
       envs directories : F:\Anaconda3\envs
                          C:\Users\ypc8272805\AppData\Local\conda\conda\envs
                          C:\Users\ypc8272805\.conda\envs
          package cache : F:\Anaconda3\pkgs
                          C:\Users\ypc8272805\AppData\Local\conda\conda\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\ypc8272805\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063

`$ F:\Anaconda3\Scripts\conda-script.py install numpy`

    Traceback (most recent call last):
      File "F:\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "F:\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "F:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "F:\Anaconda3\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "F:\Anaconda3\lib\site-packages\conda\core\index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "F:\Anaconda3\lib\site-packages\conda\core\index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "F:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "F:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "F:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 463, in <listcomp>
        for url, schan, pri in tasks]
      File "F:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "F:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "F:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "F:\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "F:\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "F:\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "F:\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "F:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 588, in urlopen
        self._prepare_proxy(conn)
      File "F:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 801, in _prepare_proxy
        conn.connect()
      File "F:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 281, in connect
        conn = self._new_conn()
      File "F:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 138, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "F:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 66, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kalefranz** [comment] 2017-11-07 20:59
This is a duplicate of #3962.  You have a proxy configuration error somewhere on your system.  There's nothing conda can do to resolve this for you.  You'll have to track down and fix the proxy configuration error yourself.

Once requests has https://github.com/requests/requests/pull/4356 merged, we'll be able to hand back better error messages in conda too.

**Closed by kalefranz** 2017-11-07 20:59 UTC
