### ISSUE TITLE
Spaces in prefix fix breaks passing the `$PS1` environment variable

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11893] opened 2022-09-27 20:59 UTC
### What happened?

After releasing conda 22.9.0, users (predominantly Linux) identified an issue (https://github.com/conda/conda/issues/11885) where the prompt would no longer update correctly on posix. After some digging, the issue appears because of the spaces in prefix fix (#11676).

How to replicate:

1. Update conda:
    
    ```
    conda update conda
    ```

2. At this point, depending on your system, the issue may already be present. If not, you'll need to continue to mock the issue users are encountering.

3. Modify `$CONDA_PREFIX/bin/conda`'s shebang to use the long prefix/space in prefix trick:
 
    So from this:
    ```
    #!/Users/kodegard/.conda/4.12.0/3.9/bin/python
    # -*- coding: utf-8 -*-
    ...
    ```

    To this:
    ```
    #!/bin/sh
    '''exec' "/Users/kodegard/.conda/4.12.0/3.9/bin/python" "$0" "$@"
    ' '''
    # -*- coding: utf-8 -*-
    ...
    ```

4. Running `conda activate` will now break your prompt.

This has to do with how environment variables are passed to the sub-shell. Only exported environment variables are passed along and since `$PS1` is not an exported value it gets lost with the `exec` call (this is why the bash shell interface for activate/deactivate calls conda as `eval "$(PS1=${PS1:-} conda shell.posix activate ...)"` to correctly pass along the `$PS1` value). Now that our entry points are invoking another sub-shell that PS1 isn't being passed along to the exec's sub-shell, conda isn't able to identify the presence of a prompt.

A fix is needed as this issue likely propagates to all entry points & scripts that conda installs, i.e., I would be unable to pass environment variables to executables:

```
LIFE=42 $CONDA_PREFIX/bin/executable
```

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : None
            shell level : 0
       user config file : /Users/kodegard/.condarc
 populated config files : /Users/kodegard/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.12.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/kodegard/.conda/4.12.0/3.9  (writable)
      conda av data dir : /Users/kodegard/.conda/4.12.0/3.9/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pytorch/osx-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/kodegard/.conda/4.12.0/3.9/pkgs
                          /Users/kodegard/.conda/pkgs
       envs directories : /Users/kodegard/.conda/4.12.0/3.9/envs
                          /Users/kodegard/.conda/envs
               platform : osx-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.12 Darwin/21.6.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

</details>
<details>
<summary><code>conda config</code></summary>

```shell
==> /Users/kodegard/.condarc <==
auto_update_conda: False
auto_activate_base: False
channels:
  - defaults
```

</details>
<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/kodegard/.conda/4.12.0/3.9:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.11.1           py39hecd8cb5_0    defaults
brotlipy                  0.7.0           py39h9ed2024_1003    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
ca-certificates           2022.07.19           hecd8cb5_0    defaults
cctools                   949.0.1             h9abeeb2_23    defaults
cctools_osx-64            949.0.1             hc7db93f_23    defaults
certifi                   2022.9.14        py39hecd8cb5_0    defaults
cffi                      1.15.1           py39hc55c11b_0    defaults
chardet                   4.0.0           py39hecd8cb5_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     22.9.0           py39hecd8cb5_0    defaults
conda-build               3.22.0           py39hecd8cb5_0    defaults
conda-package-handling    1.9.0            py39hca72f7f_0    defaults
cryptography              37.0.1           py39hf6deb26_0    defaults
filelock                  3.6.0              pyhd3eb1b0_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 h0a44026_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
ld64                      530                 h20443b4_23    defaults
ld64_osx-64               530                 h70f3046_23    defaults
ldid                      2.1.2                h2d21305_2    defaults
libarchive                3.6.1                he336d3b_0    defaults
libcxx                    14.0.6               h9765a3e_0    defaults
libffi                    3.3                  hb1e8313_2    defaults
libiconv                  1.16                 hca72f7f_2    defaults
liblief                   0.11.5               he9d5cce_1    defaults
libllvm12                 12.0.0               h9b2ccf5_3    defaults
libxml2                   2.9.14               hbf8cd5e_0    defaults
lz4-c                     1.9.3                h23ab428_1    defaults
markupsafe                2.0.1            py39h9ed2024_0    defaults
ncurses                   6.3                  hca72f7f_3    defaults
openssl                   1.1.1q               hca72f7f_0    defaults
patch                     2.7.6             h1de35cc_1001    defaults
pip                       22.1.2           py39hecd8cb5_0    defaults
pkginfo                   1.8.2              pyhd3eb1b0_0    defaults
psutil                    5.9.0            py39hca72f7f_0    defaults
py-lief                   0.11.5           py39he9d5cce_1    defaults
pycosat                   0.6.3            py39h9ed2024_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py39hecd8cb5_0    defaults
python                    3.9.12               hdfd78df_1    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python.app                3                py39hca72f7f_0    defaults
pytz                      2022.1           py39hecd8cb5_0    defaults
pyyaml                    6.0              py39hca72f7f_1    defaults
readline                  8.1.2                hca72f7f_1    defaults
requests                  2.28.1           py39hecd8cb5_0    defaults
ripgrep                   13.0.0               hc2228c6_0    defaults
ruamel_yaml               0.15.100         py39h9ed2024_0    defaults
setuptools                63.4.1           py39hecd8cb5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
sqlite                    3.39.2               h707629a_0    defaults
tapi                      1000.10.8            ha1b3eb9_0    defaults
tk                        8.6.12               h5d9f67b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.11.2             pyhd3eb1b0_0    defaults
tqdm                      4.64.0           py39hecd8cb5_0    defaults
tzdata                    2022c                h04d1e81_0    defaults
urllib3                   1.26.11          py39hecd8cb5_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.6                hca72f7f_0    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
zlib                      1.2.12               h4dc903c_3    defaults
zstd                      1.5.2                hcb37349_0    defaults
```

</details>

**Comment by jaimergp** [comment] 2022-09-27 21:34
We are using the same technique `setuptools` and `pip` have been using for their entry points for _years_ so I am surprised this hasn't showed up before. Also, this shouldn't break existing installations because previous installations could not use spaces at all so I wonder how the new entry point got there? Just because of the long path? I am also surprised (so many surpises!) `exec` does not inherit the local, inline env vars.

I'll see what I can come up with.

**Comment by kenodegard** [comment] 2022-09-27 21:37
If we unpack the linux and macos tarballs for the conda 22.9.0 package and inspect the bin/conda scripts we see that the linux one already has the split shebang:

```
#!/bin/sh
'''exec' "/opt/conda/conda-bld/conda_1664201055870/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python" "$0" "$@"
' '''
```

and macos does not:

```
#!/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_3c3zclpfj3/croots/recipe/conda_1664201064130/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
```

this explains (unsurprisingly) why we cannot replicate this on our development machines (macOS) without manually hacking the scripts

this also turns out to be dependent on the bash version, the `exec` command in newer versions will pass along all environment variables, older versions do not

| OS | Bash | Has Issue with Split Shebang? |
|---|---|---|
| macOS 12.6 | GNU 3.2.57 | yes |
| Ubuntu 18 | GNU 4.4.20 | no |

Also, note that the author of https://github.com/conda/conda/issues/11885#issue-1387443291 is on CentOS 7

**Comment by jaimergp** [comment] 2022-09-27 21:49
The Linux split must come from the conda-build pre-processing. `$PREFIX` there is intentionally long, and IIRC the `conda` entry points are created at packaging time, not at install time (as it happens with `noarch` packages).

We might need to:
* Special case `conda`? But this doesn't solve issues with other packages.
* Check `bash` version? But this doesn't solve issues introduced at build time.
* Shrug and just use the `#!/usr/bin/env` approach, that however requires environment activation to work.

**Comment by jaimergp** [comment] 2022-09-27 21:56
Also, maybe I don't understand it fully but I can't reproduce the case where `exec` ignores local variables :/

Let's say we have this script, name `test_exec_vars.sh`:

```bash
#!/bin/sh
exec bash -c "env | grep VAR="
```

Once marked as executable, I run it with:

```bash
$ ./test_exec_vars.sh  # no output
$ VAR=hello ./test_exec_vars.sh
VAR=hello
```

My bash version on Mac:

```bash
$ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

---

Same behaviour for this "closer to reality" reproducer, so I don't know if `exec` is really the one to blame here.

```
#!/bin/sh
'''exec' "/Users/jrodriguez/.local/anaconda/envs/conda-dev/bin/python" "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import os
print("VAR =", os.environ.get('VAR', '<not set>'))
```

**Comment by jaimergp** [comment] 2022-09-28 14:08
Ok, wrap up, @jezdez and I have been debugging this during the morning and we have results.

First the facts:

* We were both right. The new entry point does not drop environment variables. It DOES drop `PS1`, even if exported previously. This has todo with the invocation mode of `/bin/sh`. Changing the shebang to `#!/bin/sh -i` so it's _interactive_ ✨ fixes it! However, we don't want every entry point loading `~/.bashrc` by default.

* We can indeed use the shell part of the entry point to set a `PS1` of our choice. We cannot access the parent shell `PS1`, though, because it has been dropped, but this is ok:

```bash
#!/bin/sh
'''exec' /usr/bin/env PS1="<custom-prompt>: " /opt/conda/bin/python" "$0" "$@"
' '''
... # python parts below
```

This was key to understand that (A) the Python parts that generate the shell activation logic are not dropping PS1. It just never made it there due to `#!/bin/sh` filtering it out!

How can we fix this without forcing people to re-initialize their installation? Several steps:

* The idea is to change how the [`conda` shell function](https://github.com/conda/conda/blob/6918d6f667c55a95e762c68cb6f95842fe1e9e74/conda/shell/etc/profile.d/conda.sh#L38-L52) calls `conda` Python layer itself. This is defined (for Posix shells) in [this part of the script](https://github.com/conda/conda/blob/6918d6f667c55a95e762c68cb6f95842fe1e9e74/conda/shell/etc/profile.d/conda.sh#L4-L6). The variables there are defined by the ["hook preamble"](https://github.com/conda/conda/blob/6918d6f667c55a95e762c68cb6f95842fe1e9e74/conda/activate.py#L829-L843), which simply renders [these env vars](https://github.com/conda/conda/blob/6918d6f667c55a95e762c68cb6f95842fe1e9e74/conda/base/context.py#L654-L684) in the adequate shell dialect.
* In development mode, `__conda_exe()` uses `$CONDA_PREFIX/bin/python -m conda`. In normal mode, it uses `$CONDA_PREFIX/bin/conda` (the faulty entry point!). 
* **The solution** - I propose we always make `__conda_exe()` use the `python -m conda` approach. This bypasses the entry point totally, since we are now calling `python` directly, which correctly inherits and sees `PS1`.

However, the entry point is still dropping `PS1`. This is an edge case, but some users might not expect this behaviour, so we should provide PS1 if possible. My suggestion is to expose `PS1` through a proxy variable (e.g. `_PS1_FOR_CONDA_ENTRY_POINTS`) that is defined in the shell hook template (for example, [here at the top](https://github.com/conda/conda/blob/6918d6f667c55a95e762c68cb6f95842fe1e9e74/conda/shell/etc/profile.d/conda.sh#L3-L6)) and then inject it in the entry point with:

```bash
#!/bin/sh
'''exec' /usr/bin/env PS1="${_PS1_FOR_CONDA_ENTRY_POINTS:-}" /opt/conda/bin/python" "$0" "$@"
' '''
... # python parts below
```

This should fix all our problems, as far as I am concerned. The only difference I can anticipate has to do with `sys.path`:

* The entry point mechanism is essentially equivalent to doing `$CONDA_PREFIX/bin/python $CONDA_PREFIX/bin/<entry_point.py>`. In other words, it's Python running a file.
* The `python -m conda` uses the `-m` flag, which needs to find the module (or `package.__main__`).
* These two modes differ in how `sys.path` is initialized (if the current working directory is included or not).

```
(base) [root@9b97ef056010 ~]# python package/__init__.py 
['/root/package', '/opt/conda/lib/python39.zip', '/opt/conda/lib/python3.9', '/opt/conda/lib/python3.9/lib-dynload', '/opt/conda/lib/python3.9/site-packages']
(base) [root@9b97ef056010 ~]# python -m package
['/root', '/opt/conda/lib/python39.zip', '/opt/conda/lib/python3.9', '/opt/conda/lib/python3.9/lib-dynload', '/opt/conda/lib/python3.9/site-packages']
```

Note the entry point has a workaround to cover for this. We'd need to investigate whether we need to port this over to `conda.__main__`.

Phew, that was quite a bit. Hope it's clear, but let me know if more details are needed.

**Comment by kenodegard** [comment] 2022-09-28 14:29
Ah, so if we could do:

```
conda shell.posix activate --prompt ${PS1:-}
```

we should be fine?

**Closed** 2022-11-17 13:17 UTC
Labels: type::bug, source::anaconda, severity::3, cli::posix, os::linux, sprint
