### ISSUE TITLE
conda messes up path on Windows and mingw64-git after any command

### ISSUE THREAD

**Issue by ispmarin** [conda/conda#5036] opened 2017-04-11 14:05 UTC
Using [mingw64-git ](https://git-scm.com/download/win) and Anaconda 

  `conda info
Current conda install:

               platform : win-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : C:\Users\user\bin\anaconda3  (writable)
    default environment : C:\users\user\bin\envs\hcbda
       envs directories : C:\users\user\bin\envs
                          C:\Users\user\bin\anaconda3\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
                          C:\Users\user\.conda\envs
          package cache : C:\Users\user\bin\anaconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\user\.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.6.0 Windows/10 Windows/10.0.10586
`
after issuing any command (conda update, conda install, any command), no other command works, including commands from the shell (wget, etc), with "file not found" error.

**Comment by kalefranz** [comment] 2017-04-21 06:33
Can you give us the exact command line session from when this happens.  And then after the error occurs, show us the output of `env | sort`.

**Comment by ispmarin** [comment] 2017-04-24 11:14
Sure thing:

```
    conda create -n test
    Fetching package metadata ...........
    Solving package specifications:
    Package plan for installation in environment C:\users\310277940\bin\envs\test:

    Proceed ([y]/n)? y

#

# To activate this environment, use:
# > activate test
#
# To deactivate this environment, use:
# > deactivate test
#
# * for power-users using bash, you must source
#
```
Next, activating it:

```
    source activate test
```

Installing a package:

```
$ conda install pandas
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\users\310277940\bin\envs\test:

The following NEW packages will be INSTALLED:

    mkl:             2017.0.1-0         defaults
    numpy:           1.12.1-py36_0      defaults
    pandas:          0.19.2-np112py36_1 defaults
    pip:             9.0.1-py36_1       defaults
    python:          3.6.1-0            defaults
    python-dateutil: 2.6.0-py36_0       defaults
    pytz:            2017.2-py36_0      defaults
    setuptools:      27.2.0-py36_1      defaults
    six:             1.10.0-py36_0      defaults
    vs2015_runtime:  14.0.25123-0       defaults
    wheel:           0.29.0-py36_0      defaults

Proceed ([y]/n)? y

```

Everything working so far. Now, trying to install second package:

```
$ conda install ipython
bash: /C/users/310277940/bin/envs/test/Scripts/conda: No such file or directory
(test)

```

Failure. Result of `env | sort`:

```
$ env | sort
!::=::\
_=/usr/bin/env
ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\myuser\AppData\Roaming
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMFILES=C:\Program Files\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=mycomputer
COMSPEC=C:\WINDOWS\system32\cmd.exe
CONDA_DEFAULT_ENV=test
CONDA_PATH_BACKUP=/c/Users/myuser/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/myuser/bin:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/PuTTY:/cmd:/c/Program Files (x86)/GNU/GnuPG/pub:/c/Program Files/OpenVPN/bin:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Users/myuser/bin/anaconda3:/c/Users/myuser/bin/anaconda3/Scripts:/c/Users/myuser/bin/anaconda3/Library/bin:/c/Users/myuser/AppData/Local/Programs/MiKTeX 2.9/miktex/bin/x64:/c/Users/myuser/bin/SublimeText:/c/Users/myuser/bin/R-3.3.2/bin/x64:/c/Users/myuser/bin/pandoc:/usr/bin/vendor_perl:/usr/bin/core_perl
CONDA_PREFIX=/C/users/myuser/bin/envs/test
CONDA_PS1_BACKUP=\[\033]0;$TITLEPREFIX:${PWD//[^[:ascii:]]/?}\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
CONFIG_SITE=/mingw64/etc/config.site
DEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
DISPLAY=needs-to-be-defined
EXEPATH=C:\Program Files\Git
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOME=/c/Users/myuser
HOMEDRIVE=C:
HOMEPATH=\Users\myuser
HOSTNAME=mycomputer
INFOPATH=/usr/local/info:/usr/share/info:/usr/info:/share/info
JUPYTER_CONFIG_DIR=C:\Users\myuser\.jupyter
JUPYTER_PATH=C:\Users\myuser\.jupyter
LANG=pt_BR.UTF-8
LOCALAPPDATA=C:\Users\myuser\AppData\Local
MANPATH=/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man
MINGW_CHOST=x86_64-w64-mingw32
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
MINGW_PREFIX=/mingw64
MSYS2_ENV_CONV_EXCL=CONDA_PATH
MSYSTEM_CARCH=x86_64
MSYSTEM_CHOST=x86_64-w64-mingw32
MSYSTEM_PREFIX=/mingw64
MSYSTEM=MINGW64
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\myuser\OneDrive - Business
ORIGINAL_PATH=/mingw64/bin:/usr/bin:/c/Users/myuser/bin:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/PuTTY:/cmd:/c/Program Files (x86)/GNU/GnuPG/pub:/c/Program Files/OpenVPN/bin:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Users/myuser/bin/anaconda3:/c/Users/myuser/bin/anaconda3/Scripts:/c/Users/myuser/bin/anaconda3/Library/bin:/c/Users/myuser/AppData/Local/Programs/MiKTeX 2.9/miktex/bin/x64:/c/Users/myuser/bin/SublimeText:/c/Users/myuser/bin/R-3.3.2/bin/x64:/c/Users/myuser/bin/pandoc
ORIGINAL_TEMP=/tmp
ORIGINAL_TMP=/tmp
OS=Windows_NT
PATH=/C/users/myuser/bin/envs/test:/C/users/myuser/bin/envs/test/Library/mingw-w64/bin:/C/users/myuser/bin/envs/test/Library/usr/bin:/C/users/myuser/bin/envs/test/Library/bin:/C/users/myuser/bin/envs/test/Scripts:/c/Users/myuser/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/myuser/bin:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/PuTTY:/cmd:/c/Program Files (x86)/GNU/GnuPG/pub:/c/Program Files/OpenVPN/bin:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Users/myuser/bin/anaconda3:/c/Users/myuser/bin/anaconda3/Scripts:/c/Users/myuser/bin/anaconda3/Library/bin:/c/Users/myuser/AppData/Local/Programs/MiKTeX 2.9/miktex/bin/x64:/c/Users/myuser/bin/SublimeText:/c/Users/myuser/bin/R-3.3.2/bin/x64:/c/Users/myuser/bin/pandoc:/usr/bin/vendor_perl:/usr/bin/core_perl
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
PLINK_PROTOCOL=ssh
PRINTER=Microsoft Print to PDF
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3d04
ProgramData=C:\ProgramData
ProgramFiles(x86)=C:\Program Files (x86)
PROGRAMFILES=C:\Program Files
ProgramW6432=C:\Program Files
PS1=(test) \[\033]0;$TITLEPREFIX:${PWD//[^[:ascii:]]/?}\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PWD=/c/Users/myuser
SESSIONNAME=Console
SHELL=/usr/bin/bash
SHLVL=1
SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=/tmp
TERM=xterm-256color
TMP=/tmp
TMPDIR=/tmp
USERDNSDOMAIN=domain.Business.COM
USERDOMAIN=domain
USERNAME=myuser
USERPROFILE=C:\Users\myuser
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSEDEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
WINDIR=C:\WINDOWS
(test)

```

**Comment by kalefranz** [comment] 2017-05-02 19:54
This is a problem with activate and mingw64-git.  We should be able to address it pretty easily now that we have #5044 merged.

**Comment by brechtm** [comment] 2017-05-08 11:54
I have noticed that conda rebuilds the PATH environment variable using a semicolon `;` (Windows style) instead of the colon `:` (POSIX style), completely breaking the search path in msys2.

**Comment by ispmarin** [comment] 2017-05-16 11:30
@brechtm could this be the cause of the failure on mingw64-git?

**Comment by brechtm** [comment] 2017-05-17 09:39
@ispmarin Yes. I'm running conda 4.3.11 BTW.

**Comment by autodrive** [comment] 2017-06-18 20:34
Is someone working on this issue ?  Or is it already resolved ?

**Comment by zwn** [comment] 2017-06-20 15:25
Which version of conda is the last one before the `deactivate` part got broken for msys by rebuilding the path "windows style" with semicolons? I've just updated conda only to find myself unable to deactivate :worried:

**Comment by zwn** [comment] 2017-06-20 15:57
Versions 4.3.13 and 4.3.11 have semicolons bug.

Version 4.2.12 works with msys (git environment).

**Comment by brechtm** [comment] 2017-06-27 08:59
With 4.3.22:

```
$ source activate testenv
(testenv)
$ which python
/C/Users/bmachie/AppData/Local/Continuum/Miniconda3/envs/testenv/python
(testenv)
$ source deactivate

$ source activate testenv
-bash: activate: No such file or directory
```

**Comment by autodrive** [comment] 2017-06-29 16:24
> Which version of conda is the last one before the deactivate part got broken for msys by rebuilding the path "windows style" with semicolons? I've just updated conda only to find myself unable to deactivate 😟

@zwn @brechtm IMHO could you try 4.3.4?

**Comment by brechtm** [comment] 2017-07-10 07:35
@autodrive I can't install 4.3.4 since I'm using Python 3 Miniconda.

**Comment by zwn** [comment] 2017-07-10 08:40
@autodrive 4.3.4 works with python 2.7 and it is my newly pinned version now :+1:

**Comment by brechtm** [comment] 2017-07-10 10:16
I believe the root cause is that conda (`..deactivate.path` in `cli/activate.py`) gets the `PATH` environment variable using `os.environ['PATH']`, which is different from the `PATH` in bash (`echo $PATH`).

One solution could be to pass the contents of `PATH` to `conda ..deactivate.path`.

**Comment by autodrive** [comment] 2017-07-10 12:31
@brechtm I am currently using Anaconda 4.2 + Python 3.5 on Windows and this version works fine, IMHO.

**Comment by brechtm** [comment] 2017-07-10 14:06
@autodrive I'm using "Miniconda3-latest-Windows-x86_64.exe" with "Product version" 4.3.11, Python 3.6.0 and conda 4.3.22.

Which conda version do you have installed?

**Comment by autodrive** [comment] 2017-07-13 06:47
@brechtm @zwn I am currently using Anaconda 4.2 (conda 4.3.22) + Python 3.5 +
  on Windows and this version works fine, IMHO.

**Comment by kalefranz** [comment] 2018-01-24 18:22
> This is a problem with activate and mingw64-git.

All flavors of bash on Windows should work pretty well as of conda 4.4.7.  If there are any specific new problems, please file a new issue.

**Closed by kalefranz** 2018-01-24 18:22 UTC
Labels: source:community, type:bug

**Comment by brechtm** [comment] 2018-01-25 12:42
Thanks! So far, I'm not seeing these issues anymore with conda 4.4.7 on MSYS2.
