### ISSUE TITLE
activate with zsh on linux not working due to PS1 prompt

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2744] opened 2016-06-17 15:30 UTC
I've adapted a bug reported on the Conda ML by Alan Wilter from EMBL:

Before updating Conda:

```
conda:       4.0.8-py27_0 --> 4.1.1-py27_0 
conda-env:   2.4.5-py27_0 --> 2.5.0-py27_0 
```

The command:

```
source activate py35
```

was working fine in my Z shell.  Now with Conda 4.1.1 I get this error:

```
prepending /homes/trembl/miniconda2/envs/py35/bin to PATH
/homes/trembl/miniconda2/bin/activate:export:59: not valid in this context: $PR_CYAN$PR_ULCORNER$PR_HBAR$PR_GREY(\
```

---

ISR: I have tested this with Conda 4.1.1 and zsh on OS X 10.11.5 (using Homebrew-installed zsh) and it sort of works OK for me (I am not keen on the double round brackets, nor on the fact that Conda has made its own decision regarding what my prompt should look like:

```
➜  ~ source activate ana40py35
prepending /Users/ijstokes/anaconda/envs/ana40py35/bin to PATH
((ana40py35)) ijstokes@petawawa:~% 
```

**Comment by msarahan** [comment] 2016-06-17 15:34
Duplicate of #2743  - but there are some potentially helpful details there.  Leaving it open.

Please suggest anything other than the double round brackets.  Those are there from a regex that isn't there any more.  They can be anything.

As for changing your prompt, that's a bug.  Conda should just be reading the value of $PROMPT$ and prepending the environment to it.

**Comment by kalefranz** [comment] 2016-06-17 17:03
I've got to say I'm not fond of the double either. Or the extra added space.  Prompts should be as short as possible for the screen real estate, and we've added three extra characters that probably aren't necessary.

I *would* like to disambiguate from virtualenv, because someday conda envs and virtualenv **will** play nice together.

How about angle brackets?  `<ana40py35>ijstokes@petawawa:~%`

**Comment by kalefranz** [comment] 2016-06-17 17:04
I'd want to wait for 4.2.0 to change this though.  Also, we should add code the the prompt setting logic to let people customize this more.  Similar to `config.changeps1`, but giving even more control.

**Comment by kalefranz** [comment] 2016-06-17 17:06
So now this ticket has morphed from a bug report to a bug report and a feature request.  I'll fork a new ticket.

**Comment by leebenson** [comment] 2017-02-28 12:10
I'm not sure if this is related (I was advised to post here from the Anaconda group), but when I try to activate a new environment via Anaconda Navigator, I get:

> ➜  ~ /Users/leebenson/.anaconda/navigator/a.tool
/Users/leebenson/.anaconda/navigator/a.tool: line 1: syntax error near unexpected token `('
/Users/leebenson/.anaconda/navigator/a.tool: line 1: `bash --init-file <(echo "source activate /Users/leebenson/anaconda/envs/Dev;")'

I assume a `#!/bin/bash` would fix it, but I'm brand new to this stack and I didn't want to go poking around...

**Comment by leebenson** [comment] 2017-02-28 12:10
And to be clear, I'm using zsh.

**Comment by kalefranz** [comment] 2017-05-13 01:11
Is this still a problem in recent versions of conda?  Latest is conda 4.3.17.

**Closed** 2017-05-15 17:21 UTC
Labels: source:cio, type:bug
