### ISSUE TITLE
conda clean -iltp causes unexpected error (linux-64)

### ISSUE THREAD

**Issue by j9ac9k** [conda/conda#1663] opened 2015-09-30 04:35 UTC
Ran conda clean -iltp and got an unexpected error.  Was able to run conda clean -i, conda clean -l, conda clean -t, conda clean -p independently with no issues.  Ran it again to grab the traceback:

```
ogi@ubuntu:~$ conda clean -iltp
Cache location:
There are no tarballs to remove
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/ogi/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main_clean.py", line 340, in execute
    pkgs_dirs, warnings, totalsize, pkgsizes = find_pkgs()
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main_clean.py", line 166, in find_pkgs
    pkgs = [i for i in listdir(pkgs_dir) if isdir(join(pkgs_dir, i)) and
FileNotFoundError: [Errno 2] No such file or directory: '/home/ogi/miniconda3/conda-bld'
ogi@ubuntu:~$
```

For reference my conda info output is:

```
ogi@ubuntu:~$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.1
  conda-build version : 1.17.0
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/ogi/miniconda3  (writable)
  default environment : /home/ogi/miniconda3
     envs directories : /home/ogi/miniconda3/envs
        package cache : /home/ogi/miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/salford_systems/linux-64/
                        https://conda.anaconda.org/salford_systems/noarch/
                        https://conda.anaconda.org/minrk/linux-64/
                        https://conda.anaconda.org/minrk/noarch/
                        https://conda.anaconda.org/IOOS/linux-64/
                        https://conda.anaconda.org/IOOS/noarch/
                        https://conda.anaconda.org/gpoulin/linux-64/
                        https://conda.anaconda.org/gpoulin/noarch/
                        https://conda.anaconda.org/auto/linux-64/
                        https://conda.anaconda.org/auto/noarch/
                        https://conda.anaconda.org/asmeurer/linux-64/
                        https://conda.anaconda.org/asmeurer/noarch/
                        https://conda.anaconda.org/meloncholy/linux-64/
                        https://conda.anaconda.org/meloncholy/noarch/
                        https://conda.anaconda.org/ostrokach/linux-64/
                        https://conda.anaconda.org/ostrokach/noarch/
                        https://conda.anaconda.org/pydy/linux-64/
                        https://conda.anaconda.org/pydy/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/ogi/.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment] 2015-09-30 16:52
I can't reproduce this but I have a guess as to what might be causing it, which I've pushed.

**Comment by j9ac9k** [comment] 2015-09-30 16:58
So I suppose I should report back after testing with the next version of conda?

**Comment by asmeurer** [comment] 2015-09-30 16:59
Yes, unless you want to test the git version (clone the repo and run `PYTHONPATH=. conda clean -iltp` in the conda directory).

**Comment by j9ac9k** [comment] 2015-09-30 17:04
On one hand this isn't a show-stopper, but since you've gotten me out of a number of jams before, I'll be happy to test.  I'll try and report back later today.

**Comment by j9ac9k** [comment] 2015-10-01 02:54
I'm afraid I'm still getting this error:

```
ogi@ubuntu:~$ echo $PYTHONPATH

ogi@ubuntu:~$ mkdir test-conda
ogi@ubuntu:~$ cd test-conda/
ogi@ubuntu:~/test-conda$ git clone https://github.com/conda/conda.git
Cloning into 'conda'...
remote: Counting objects: 20816, done.
remote: Total 20816 (delta 0), reused 0 (delta 0), pack-reused 20816
Receiving objects: 100% (20816/20816), 5.58 MiB | 3.38 MiB/s, done.
Resolving deltas: 100% (13696/13696), done.
Checking connectivity... done.
ogi@ubuntu:~/test-conda$ PYTHONPATH=.
ogi@ubuntu:~/test-conda$ conda clean -iltp
Cache location:
There are no tarballs to remove
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/ogi/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main_clean.py", line 340, in execute
    pkgs_dirs, warnings, totalsize, pkgsizes = find_pkgs()
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/conda/cli/main_clean.py", line 166, in find_pkgs
    pkgs = [i for i in listdir(pkgs_dir) if isdir(join(pkgs_dir, i)) and
FileNotFoundError: [Errno 2] No such file or directory: '/home/ogi/miniconda3/conda-bld'
ogi@ubuntu:~/test-conda$ echo $PYTHONPATH
.
ogi@ubuntu:~/test-conda$
```

**Comment by kalefranz** [comment] 2017-05-02 01:20
Report is for conda 3.18.1.  Closing this issue, as outdated.  If you have a similar stack trace in a recent version of conda, please file a new issue.

**Closed by kalefranz** 2017-05-02 01:20 UTC
