### ISSUE TITLE
endlocal statement in activate.bat prevents environment variables being propogated

### ISSUE THREAD

**Issue by gillins** [conda/conda#1916] opened 2015-12-17 23:41 UTC
Just testing the latest gdal build on Windows. There is a gdal-activate.bat that gets properly called to set %GDAL_DATA% but this does not get returned to the user's environment. I think this is due to the endlocal statement preventing set variables getting returned to the caller.

This is easy to test by trying to activate an environment with gdal in it and testing the value to %GDAL_DATA%.

Also, %GDAL_DATA% is quoted by gdal-activate.bat which causes GDAL to fail to find its coordinate files.

Sorry, originally posted to the wrong place as https://github.com/Anaconda-Server/support/issues/4.

**Comment by msarahan** [comment] 2015-12-18 02:04
Can you clarify for me that the problem is solely in gdal-activate.bat and not activate.bat?

@groutr - see activate.bat for examples of how to use endlocal to set global variables.  I'm happy to chat if you need help.

**Comment by gillins** [comment] 2015-12-18 02:15
There is a problem in both. The main problem is that activate.bat does not allow environment variables to get set permanently by gdal-activate.bat.

gdal-activate.bat needs to set %GDAL_DATA% so GDAL can find its data files.

Second, less serious problem is that gdal-activate.bat isn't quite right, should read:
set "GDAL_DATA=%~dp0\..\..\..\Library\share\gdal"
The current syntax ends up with %GDAL_DATA% being quoted which confuses GDAL.

My apologies for the confusion.

**Comment by kalefranz** [comment] 2017-05-09 07:27
Closing.  All of the activate.bat code was rewritten since this ticket was filed with #1727 and part of conda 4.1.

**Closed by kalefranz** 2017-05-09 07:27 UTC
