### ISSUE TITLE
Error when running conda update conda on Windows

### ISSUE THREAD

**Issue by bidhya** [conda/conda#6169] opened 2017-10-15 03:47 UTC
conda update conda

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : C:\Users\bny\Anaconda2  (writable)
    default environment : C:\Users\bny\Anaconda2
       envs directories : C:\Users\bny\Anaconda2\envs
                          C:\Users\bny\AppData\Local\conda\conda\envs
                          C:\Users\bny\.conda\envs
          package cache : C:\Users\bny\Anaconda2\pkgs
                          C:\Users\bny\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\bny\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Windows/10 Windows/10.0.15063
          administrator : False

**Comment by SajidSalim** [comment] 2017-10-15 04:51
_Facing the same issue._

`An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Users\rpa\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\rpa\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\rpa\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\rpa\AppData\Local\conda\conda\envs
                          C:\Users\rpa\.conda\envs
          package cache : C:\Users\rpa\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\rpa\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\rpa\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : False

$ C:\Users\rpa\AppData\Local\Continuum\Anaconda3\Scripts\conda update --all




    Traceback (most recent call last):
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506081103.986 for timestamp`

**Comment by moonshoes87** [comment] 2017-10-15 19:34
I have the same error on OS X.  It appeared to start after a `conda install` command that was interrupted, but that may be incidental.

    Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/nebula/anaconda  (writable)
    default environment : /Users/nebula/anaconda
       envs directories : /Users/nebula/anaconda/envs
                          /Users/nebula/.conda/envs
          package cache : /Users/nebula/anaconda/pkgs
                          /Users/nebula/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : /Users/nebula/.netrc
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/3.6.1 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /Users/nebula/anaconda/bin/conda upgrade conda`




    Traceback (most recent call last):
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/nebula/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080276.026 for timestamp

**Comment by kalefranz** [comment] 2017-10-17 22:11
Duplicate of https://github.com/conda/conda/issues/6096.  See that issue for solutions.

**Closed by kalefranz** 2017-10-17 22:11 UTC
