### ISSUE TITLE
errors with conda env create 

### ISSUE THREAD

**Issue by rimhur** [conda/conda#6358] opened 2017-11-29 08:19 UTC
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /anaconda3  (writable)
    default environment : /anaconda3
       envs directories : /anaconda3/envs
                          /Users/rhur/.conda/envs
          package cache : /anaconda3/pkgs
                          /Users/rhur/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/rhur/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Darwin/14.5.0 OSX/10.10.5    
                UID:GID : 502:20

`$ /anaconda3/bin/conda-env create`

    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/anaconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 32, in install
        channel_priority_map=_channel_priority_map)
      File "/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 473, in install_actions_list
        linked_in_root = linked_data(context.root_prefix)
      File "/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080276.026 for timestamp

**Comment by kalefranz** [comment] 2017-11-30 22:26
Duplicate of https://github.com/conda/conda/issues/6096.  See that issue for solutions.

**Closed by kalefranz** 2017-11-30 22:26 UTC
Labels: reso:already-fixed, source:community, type:bug
