### ISSUE TITLE
Can't update anaconda

### ISSUE THREAD

**Issue by coramdeonyc** [conda/conda#4123] opened 2016-12-21 19:12 UTC
Upon doing the usual "conda update anaconda", i got the following error message, was told to post it here.

Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/johnkim/anaconda  (writable)
    default environment : /Users/johnkim/anaconda
       envs directories : /Users/johnkim/anaconda/envs
          package cache : /Users/johnkim/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/johnkim/anaconda/bin/conda update anaconda`

    Traceback (most recent call last):
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
        for url in urls]
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/johnkim/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by Woodstonelee** [comment] 2016-12-22 21:53
echo the same issue here but I got different output about the error

Fetching package metadata ..........An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.12
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /share/pkg/anaconda2/4.2.0/install  (read only)
    default environment : /usr3/graduate/zhanli86/anaconda_envs/zhanli_py27
       envs directories : /usr3/graduate/zhanli86/anaconda_envs
                          /share/pkg/anaconda2/4.2.0/install/envs
                          /usr3/graduate/zhanli86/.conda/envs
                          /share/pkg/anaconda2/4.2.0/install/envs
          package cache : /usr3/graduate/zhanli86/anaconda_envs/.pkgs
                          /share/pkg/anaconda2/4.2.0/install/pkgs
                          /usr3/graduate/zhanli86/.conda/envs/.pkgs
                          /share/pkg/anaconda2/4.2.0/install/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          file:///usr3/graduate/zhanli86/conda-bld/linux-64
                          file:///usr3/graduate/zhanli86/conda-bld/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /usr3/graduate/zhanli86/.condarc
           offline mode : False



`$ /share/pkg/anaconda2/4.2.0/install/bin/conda.real update anaconda`




    Traceback (most recent call last):
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
        r.content
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/requests/models.py", line 781, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/share/pkg/anaconda2/4.2.0/install/lib/python2.7/site-packages/requests/models.py", line 714, in generate
        chunk = self.raw.read(chunk_size)
    AttributeError: 'exceptions.OSError' object has no attribute 'read'

**Comment by coramdeonyc** [comment] 2016-12-22 22:01
I just did a uninstall/reinstall.  Seems to have fixed things.  

Things went awry for me because i was trying to update to scikit-learn .18 from .17.  After un/reinstall, able to do so without any problems.

**Comment by kalefranz** [comment] 2017-05-01 19:55
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:55 UTC
