### ISSUE TITLE
when installing tensorflow-gpu tensorflow (cpu version) also installs. gpu becomes unaccessible.

### ISSUE THREAD

**Issue by jbisgrove** [conda/conda#7970] opened 2018-11-19 03:42 UTC
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment] 2018-11-19 03:47
Please provide info requested in issue template. Closing as insufficient info. Will reopen it new info provided.

**Closed by msarahan** 2018-11-19 03:47 UTC

**Comment by jbisgrove** [comment] 2018-11-19 04:00
GPU was active on the previous install using pip.
after switching from pip install to conda-forge tensorflow shows tf.test.is_gpu_available()  as 'False'

**Comment by nehaljwani** [comment] 2018-11-24 08:47
@jbisgrove The following is the cause for your troubles:
```
tensorflow                1.10.0                   py36_0    conda-forge
tensorflow-gpu            1.10.0               hf154084_0    defaults
```

Please avoid mixing conda-forge and defaults unless absolutely necessary.
