### ISSUE TITLE
Issue with conda create -n py35 python=3.5 anaconda

### ISSUE THREAD

**Issue by MPardemann** [conda/conda#1787] opened 2015-11-06 14:34 UTC
The following conda create did not work.

C:\Anaconda>conda create -n py35 python=3.5 anaconda
Fetching package metadata: ....
Solving package specifications: ....................................................
.............................................................................An unex
nsider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 333, in install
    update_deps=args.update_deps)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 1057, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 819, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 624, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: ipython-notebook-4.0.4-py35_3.tar.bz2 MatchSpec(u'menuinst 1.2.0')

This is my current conda info result:

Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\marco.pardemann\.condarc
    is foreign system : False

**Comment by marscher** [comment] 2015-11-06 15:05
Same here with python 2.7 x86 win

**Comment by mcg1969** [comment] 2015-11-06 22:38
I believe this is a duplicate of, or similar to, https://github.com/conda/conda/issues/1778

If so, a fix is in place and will appear in 3.18.4. Downgrading conda to 3.18.2 and installing should get you by in the meanwhile.

**Comment by mcg1969** [comment] 2015-11-06 22:41
I'm sorry, I was mistaken; I do *not* think downgrading will fix this.

**Comment by mcg1969** [comment] 2015-11-10 02:19
This is solved by 3.18.4, which was just released.

**Closed** 2015-11-10 02:37 UTC
