### ISSUE TITLE
Error in using "conda install ipython-notebook"

### ISSUE THREAD

**Issue by dawandehuoshaoyun** [conda/conda#1457] opened 2015-07-24 07:02 UTC
![traceback](https://cloud.githubusercontent.com/assets/13182067/8869185/9b194a70-3213-11e5-83fd-ccb1edbe427f.png)

I have successfully installed python34 and anaconda (Anaconda-2.3.0-Windows-x86_64.exe).
Moreover, ipython works as well. What makes me so frustrated is the installation of ipython-notebook.  I have tried many approaches to install it, using different python versions, python27 and python34, and pip install vs easy_install. But I have not figured it out. At last, I find this way, "conda install ipython-notebook". The error still be there. I really do not know I should I do now. Please help me. Thank you all, sincerely!

**Comment by asmeurer** [comment] 2015-07-27 18:57
When you say you've tried python34, do you mean you created a Python 3.4 environment, or used Anaconda3? I think the only way to fix this is to use Anaconda3, so that conda itself runs in Python 3. See https://github.com/conda/conda/issues/1180.

**Comment by asmeurer** [comment] 2015-07-27 18:58
I am going to close this as a duplicate of https://github.com/conda/conda/issues/1180. if you have any further questions, please comment there.

**Closed by asmeurer** 2015-07-27 18:58 UTC

**Comment by Jhih-Jie** [comment] 2015-07-29 07:13
Thanks for your comment. I finally created another account on my PC, in order to abandon Chinese as my username. And it worked well now. I was outside these days and late for check. Thanks.

**Comment by asmeurer** [comment] 2015-07-29 17:00
That's probably the smartest idea. No doubt other software would have issues with the non-ASCII characters as well.

**Comment by dawandehuoshaoyun** [comment] 2015-07-30 01:52
Anyway, thanks so much.

**Comment by Coolfunkygirl** [comment] 2020-09-07 07:29
The installation of ipython-notebook command doesn't work...
So
Try 
conda install -c free ipython-notebook 
instead of conda install ipython-notebook
