### ISSUE TITLE
conda run crashes when targeted to an env on a read-only filesystem/path.

### ISSUE THREAD

**Issue by erykoff** [conda/conda#11208] opened 2022-02-11 04:14 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

If you try to do `conda run` into a read-only filesystem/env (as is sometimes used in shared environments) it crashes because it can't write a temporary file to the env location.

For example ...

This runs fine:
```
conda create -n testpy python=3.9
conda run -n testpy python
```
Then make it read-only:
```
chmod -w $CONDA_PREFIX/envs/testpy
conda run -n testpy python
```
And you get:
```
% conda run -n testpy python        

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/erykoff/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/erykoff/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/erykoff/miniforge3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/erykoff/miniforge3/lib/python3.9/site-packages/conda/cli/main_run.py", line 25, in execute
        script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
      File "/Users/erykoff/miniforge3/lib/python3.9/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/Users/erykoff/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/Users/erykoff/miniforge3/lib/python3.9/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/Users/erykoff/miniforge3/lib/python3.9/tempfile.py", line 251, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/Users/erykoff/miniforge3/envs/testpy/.tmpog17cbzk'

`$ /Users/erykoff/miniforge3/bin/conda run -n testpy python`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/erykoff/miniforge3/bin/conda
             CONDA_PREFIX=/Users/erykoff/miniforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/erykoff/miniforge3/bin/python
               CONDA_ROOT=/Users/erykoff/miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/erykoff/miniforge3/bin:/Users/erykoff/miniforge3/bin:/Users/ery
                          koff/miniforge3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:
                          /Library/Apple/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/erykoff/miniforge3
            shell level : 1
       user config file : /Users/erykoff/.condarc
 populated config files : /Users/erykoff/miniforge3/.condarc
                          /Users/erykoff/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __osx=11.6.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/erykoff/miniforge3  (writable)
      conda av data dir : /Users/erykoff/miniforge3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/erykoff/miniforge3/pkgs
                          /Users/erykoff/.conda/pkgs
       envs directories : /Users/erykoff/miniforge3/envs
                          /Users/erykoff/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.9.2 Darwin/20.6.0 OSX/11.6.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

### Conda info

```shell
active environment : base
    active env location : /Users/erykoff/miniforge3
            shell level : 1
       user config file : /Users/erykoff/.condarc
 populated config files : /Users/erykoff/miniforge3/.condarc
                          /Users/erykoff/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __osx=11.6.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/erykoff/miniforge3  (writable)
      conda av data dir : /Users/erykoff/miniforge3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/erykoff/miniforge3/pkgs
                          /Users/erykoff/.conda/pkgs
       envs directories : /Users/erykoff/miniforge3/envs
                          /Users/erykoff/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.9.2 Darwin/20.6.0 OSX/11.6.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda config

```shell
channels:
  - conda-forge

==> /Users/erykoff/.condarc <==
auto_activate_base: False
```

### Conda list

```shell
# packages in environment at /Users/erykoff/miniforge3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py39h46acfd9_1001    conda-forge
bzip2                     1.0.8                h27ca646_4    conda-forge
c-ares                    1.17.1               h27ca646_1    conda-forge
ca-certificates           2020.12.5            h4653dfc_0    conda-forge
cairo                     1.16.0            he69dfd1_1008    conda-forge
certifi                   2020.12.5        py39h2804cbe_1    conda-forge
cffi                      1.14.5           py39h702c04f_0    conda-forge
chardet                   4.0.0            py39h2804cbe_1    conda-forge
conda                     4.10.0           py39h2804cbe_1    conda-forge
conda-package-handling    1.7.3            py39h5161555_0    conda-forge
cryptography              3.4.7            py39h73257c9_0    conda-forge
dbus                      1.13.6               h7e028eb_2    conda-forge
emacs                     27.1                 h1d6f1cd_4    conda-forge
expat                     2.3.0                h9f76cd9_0    conda-forge
fontconfig                2.13.1            heb65262_1005    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
gdk-pixbuf                2.42.6               hff60771_0    conda-forge
gettext                   0.19.8.1          hea66d9f_1005    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
glib                      2.68.1               hbdafb3b_0    conda-forge
glib-tools                2.68.1               hbdafb3b_0    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.6.13               h706517b_1    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
harfbuzz                  2.8.0                h2a75196_1    conda-forge
icu                       68.1                 h17758a7_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
krb5                      1.17.2               h17618d6_0    conda-forge
libarchive                3.5.1                h2abb879_1    conda-forge
libcurl                   7.76.0               h0ebd9f5_0    conda-forge
libcxx                    11.1.0               h168391b_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libglib                   2.68.1               h6c200e4_0    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
libnghttp2                1.43.0               hf3018f0_0    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
librsvg                   2.50.4               h957afdb_0    conda-forge
libsolv                   0.7.18               habe5f53_0    conda-forge
libssh2                   1.9.0                hb80f160_6    conda-forge
libtiff                   4.2.0                h70663a0_0    conda-forge
libwebp-base              1.2.0                h27ca646_2    conda-forge
libxml2                   2.9.10               h538f51a_4    conda-forge
lz4-c                     1.9.3                h9f76cd9_0    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
mamba                     0.8.2            py39h7f98bdb_0    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
nettle                    3.6                  hc6a1b29_0    conda-forge
openssl                   1.1.1k               h27ca646_0    conda-forge
pango                     1.48.4               h1fe82c0_0    conda-forge
pcre                      8.44                 hb904e53_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
pycosat                   0.6.3           py39h46acfd9_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_3    conda-forge
python                    3.9.2           hcbd9b3a_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  hfbdcbf2_0    conda-forge
reproc                    14.2.1               h27ca646_0    conda-forge
reproc-cpp                14.2.1               h9f76cd9_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py39h46acfd9_1004    conda-forge
setuptools                49.6.0           py39h2804cbe_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.35.4               hc49ca36_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
zstd                      1.4.9                h5b28eab_0    conda-forge
```

**Comment by erykoff** [comment] 2022-02-13 17:20
Ah, I see this is a dupe of #10690

**Comment by kenodegard** [comment] 2022-02-13 19:15
@erykoff thanks for looking into this, since this is a duplicate we'll close this one in favor of #10690

**Closed** 2022-02-13 19:15 UTC
Labels: type::bug, source::community, severity::2, duplicate

**Comment by hjoliver** [comment] 2022-02-22 22:17
> @erykoff thanks for looking into this, since this is a duplicate we'll close this one in favor of #10690

And that was a duplicate of #10098 :grin:

**Comment by jezdez** [comment] 2022-02-25 22:56
And it was related to #9574, too.
