### ISSUE TITLE
conda info should accept a -c option

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1813] opened 2015-11-12 18:03 UTC
I hope the following is reasonably self explanatory for why `conda info` should accept a `-c` option, but if not, please let me know and I'll clarify.

``` bash
$ conda build --python 3.4 -c ijstokes -c memex conda.recipe
Removing old build environment
Removing old work directory
BUILD START: gensim-0.12.3-py34_1
Fetching package metadata: ..........
Solving package specifications: ............
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|#############################################################################################################################| 100%

Hint: the following packages conflict with each other:
  - pyro4 >=4.27
  - smart_open >=1.2.1

Use 'conda info pyro4' etc. to see the dependencies for each package.

ijstokes@petawawa gensim (conda_recipe) $ conda info -c ijstokes pyro4
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: -c

ijstokes@petawawa gensim (conda_recipe) $ conda info  pyro4
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: pyro4

ijstokes@petawawa gensim (conda_recipe) $ conda info ijstokes/pyro4
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: ijstokes/pyro4
```

**Comment by kalefranz** [comment] 2017-05-10 10:19
duplicate of #1390

**Closed by kalefranz** 2017-05-10 10:19 UTC
