### ISSUE TITLE
conda 4.7.5 removes packages for no apparent reason

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#8860] opened 2019-07-03 00:47 UTC
## Current Behavior

I did `conda update --all` and it proceeded to remove jupyterlab and jupyterlab-server, apparently for no reason, because a subsequent reinstall did not uncover any dependency issues.

### Steps to Reproduce

Sorry, not sure how to reproduce that. 
I guess it depends on the precious previous state?
But here's the log of what happened:
```
$ conda update --all                                                                            (py37)
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/klay6683/miniconda3/envs/py37


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipywidgets-7.5.0           |             py_0         100 KB  conda-forge
    libpq-11.4                 |       h756f0eb_1         2.4 MB  conda-forge
    postgresql-11.4            |       h25afefd_1         4.3 MB  conda-forge
    python-3.7.3               |       h93065d6_1        20.8 MB  conda-forge
    readline-8.0               |       hcfe32e1_0         415 KB  conda-forge
    sqlite-3.28.0              |       hb7d70f7_1         2.4 MB  conda-forge
    widgetsnbextension-3.5.0   |           py37_0         1.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        32.2 MB

The following packages will be REMOVED:

  json5-0.8.4-py_0
  jupyterlab-1.0.0-py37_0
  jupyterlab_server-1.0.0-py_0

The following packages will be UPDATED:

  ipywidgets                                     7.4.2-py_0 --> 7.5.0-py_0
  libpq                                     11.3-h56406e1_0 --> 11.4-h756f0eb_1
  postgresql                                11.3-hf10c77c_0 --> 11.4-h25afefd_1
  python                                   3.7.3-h0d93f26_0 --> 3.7.3-h93065d6_1
  readline                                7.0-hcfe32e1_1001 --> 8.0-hcfe32e1_0
  sqlite                                  3.28.0-h9721f7c_0 --> 3.28.0-hb7d70f7_1
  widgetsnbextension                        3.4.2-py37_1000 --> 3.5.0-py37_0


Proceed ([y]/n)?


Downloading and Extracting Packages
readline-8.0         | 415 KB    | ############################################################ | 100%
libpq-11.4           | 2.4 MB    | ############################################################ | 100%
ipywidgets-7.5.0     | 100 KB    | ############################################################ | 100%
widgetsnbextension-3 | 1.8 MB    | ############################################################ | 100%
postgresql-11.4      | 4.3 MB    | ############################################################ | 100%
python-3.7.3         | 20.8 MB   | ############################################################ | 100%
sqlite-3.28.0        | 2.4 MB    | ############################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ b'Uninstalling jupyter-js-widgets jupyter-js-widgets/extension\nRemoving: /Users/klay6683/miniconda3/envs/py37/share/jupyter/nbextensions/jupyter-js-widgets\n'
| b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: \x1b[32mOK\x1b[0m\n'
done
klay6683@macl3886|~/D/src
$ conda list jupyterlab                                                                         (py37)
# packages in environment at /Users/klay6683/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
jupyterlab-git            0.6.1                    pypi_0    pypi
jupyterlab-github         0.7.0                    pypi_0    pypi
jupyterlab-latex          0.4.1                    pypi_0    pypi
klay6683@macl3886|~/D/src
$ conda install jupyterlab                                                                      (py37)
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/klay6683/miniconda3/envs/py37

  added / updated specs:
    - jupyterlab


The following NEW packages will be INSTALLED:

  json5              conda-forge/noarch::json5-0.8.4-py_0
  jupyterlab         conda-forge/osx-64::jupyterlab-1.0.0-py37_0
  jupyterlab_server  conda-forge/noarch::jupyterlab_server-1.0.0-py_0


Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

## Expected Behavior

conda should do the update, either
1. without removing packages when there isn't a dependency issue
2. suggest removal but don't do it automatically.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : py37
    active env location : /Users/klay6683/miniconda3/envs/py37
            shell level : 1
       user config file : /Users/klay6683/.condarc
 populated config files : /Users/klay6683/.condarc
                          /Users/klay6683/miniconda3/envs/py37/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/klay6683/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/michaelaye/osx-64
                          https://conda.anaconda.org/michaelaye/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/klay6683/miniconda3/pkgs
                          /Users/klay6683/.conda/pkgs
       envs directories : /Users/klay6683/miniconda3/envs
                          /Users/klay6683/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 273771:2260
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/klay6683/.condarc <==
pinned_packages: []
report_errors: True
anaconda_upload: True

==> /Users/klay6683/miniconda3/envs/py37/.condarc <==
pinned_packages:
  - conda-forge::opencv
  - conda-forge::gdal
  - conda-forge::numpy
channels:
  - michaelaye
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/klay6683/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
advbumpversion            1.2.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
apipkg                    1.5                        py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0                 py37_1000    conda-forge
argcomplete               1.10.0                   pypi_0    pypi
arrow                     0.14.2                   py37_0    conda-forge
arrow-cpp                 0.13.0           py37h43d7656_7    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
astroid                   2.2.5                    py37_0    conda-forge
astropy                   3.2.1            py37h01d97ff_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
autopep8                  1.4.4                      py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.7.1                 py37_1001    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     19.3b0                     py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.16.3               h6de7cb9_1    conda-forge
bokeh                     1.2.0                    py37_0    conda-forge
boost-cpp                 1.70.0               hd59e818_0    conda-forge
brotli                    1.0.7             h6de7cb9_1000    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.16.0            h0ab9d94_1001    conda-forge
cartopy                   0.17.0          py37h929c6f0_1004    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cffi                      1.12.3           py37hccf1714_0    conda-forge
cftime                    1.0.3.4         py37h1e5eb4f_1001    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.1                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
cmarkgfm                  0.4.2            py37h1de35cc_2    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
conda                     4.7.5                    py37_0    conda-forge
conda-build               3.18.6                   py37_0    conda-forge
conda-package-handling    1.3.10                   py37_0    conda-forge
conda-verify              3.1.1                 py37_1000    conda-forge
cookiecutter              1.6.0                 py37_1000    conda-forge
coverage                  4.5.3            py37h1de35cc_0    conda-forge
cryptography              2.7              py37h212c5bf_0    conda-forge
cspice                    66                h01d97ff_1005    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.11          py37h6de7cb9_0    conda-forge
cytoolz                   0.9.0.1          py37h470a237_1    conda-forge
dask                      2.0.0                      py_0    conda-forge
dask-core                 2.0.0                      py_0    conda-forge
dask-labextension         0.3.3                    pypi_0    pypi
datashader                0.7.0                      py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
deprecated                1.2.5                      py_0    conda-forge
descartes                 1.1.0                      py_3    conda-forge
distributed               2.0.1                      py_0    conda-forge
docutils                  0.14                  py37_1001    conda-forge
double-conversion         3.1.5                h6de7cb9_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
execnet                   1.6.0                      py_0    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
fastparquet               0.3.1            py37h01d97ff_1    conda-forge
filelock                  3.0.10                     py_0    conda-forge
fiona                     1.8.6            py37h7eb7563_3    conda-forge
flake8                    3.7.7                    py37_0    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
future                    0.17.1                py37_1000    conda-forge
gdal                      2.4.1            py37h7eb7563_0    conda-forge
geopandas                 0.5.0                      py_2    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.4.2                h5e233db_0    defaults
geoviews                  1.6.2                      py_0    conda-forge
geoviews-core             1.6.2                      py_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gflags                    2.2.2             h6de7cb9_1001    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h9d45998_1001    conda-forge
glob2                     0.7                        py_0    conda-forge
glog                      0.4.0                h6de7cb9_1    conda-forge
graphviz                  2.40.1               ha626266_0    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
holoviews                 1.12.3                     py_2    conda-forge
hvplot                    0.4.0                      py_1    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.5.0                    py37_0    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib-resources       1.0.2                    pypi_0    pypi
importlib_metadata        0.18                     py37_0    conda-forge
intake                    0.5.1                      py_0    conda-forge
ipykernel                 5.1.1            py37h24bf2e0_0    conda-forge
ipympl                    0.2.1                 py37_1002    conda-forge
ipyparallel               6.2.4                    py37_0    conda-forge
ipython                   7.6.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.0                      py_0    conda-forge
isort                     4.3.21                   py37_0    conda-forge
jedi                      0.14.0                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
joblib                    0.13.2                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
json5                     0.8.4                      py_0    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterlab                1.0.0                    py37_0    conda-forge
jupyterlab-git            0.6.1                    pypi_0    pypi
jupyterlab-github         0.7.0                    pypi_0    pypi
jupyterlab-latex          0.4.1                    pypi_0    pypi
jupyterlab_server         1.0.0                      py_0    conda-forge
kealib                    1.4.10            hecf890f_1003    conda-forge
kiwisolver                1.1.0            py37h770b8ee_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
latexcodec                1.0.7                      py_0    conda-forge
lazy-object-proxy         1.4.1            py37h01d97ff_0    conda-forge
libarchive                3.3.3             h5c473cc_1005    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         4    conda-forge
libcxxabi                 8.0.0                         4    conda-forge
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libevent                  2.1.10               h212c5bf_0    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.1                h16bfee5_0    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
liblief                   0.9.0                h2a1bed3_1    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.4                 h756f0eb_1    conda-forge
libprotobuf               3.8.0                hfbae3c0_0    conda-forge
libsodium                 1.0.16            h1de35cc_1001    conda-forge
libspatialindex           1.9.0                h6de7cb9_1    conda-forge
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                hd80cff7_0    conda-forge
libxslt                   1.1.32            h1e79283_1003    conda-forge
llvm-openmp               8.0.0                h770b8ee_0    conda-forge
llvmlite                  0.29.0           py37h3fea490_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.4            py37h08abf6f_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
mapclassify               2.1.1                      py_0    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
matplotlib                3.1.1                    py37_0    conda-forge
matplotlib-base           3.1.1            py37h3a684a6_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h1de35cc_1000    conda-forge
mock                      3.0.5                    py37_0    conda-forge
more-itertools            4.3.0                 py37_1000    conda-forge
msgpack-numpy             0.4.4.3                    py_0    conda-forge
msgpack-python            0.6.1            py37h04f5b5a_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nb-black                  1.0.5                    pypi_0    pypi
nb_conda_kernels          2.2.2                    py37_0    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nbresuse                  0.3.2                    pypi_0    pypi
nbsphinx                  0.4.2                      py_0    conda-forge
nbstripout                0.3.5                      py_0    conda-forge
nbval                     0.9.1                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf4                   1.5.1.2          py37h58b02fa_0    conda-forge
networkx                  2.3                        py_0    conda-forge
nodejs                    11.14.0              h6de7cb9_1    conda-forge
notebook                  5.7.8                    py37_1    conda-forge
numba                     0.44.1           py37h86efe34_0    conda-forge
numexpr                   2.6.9           py37h1702cab_1000    conda-forge
numpy                     1.16.4           py37h6b0580a_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
oset                      0.1.3                      py_1    conda-forge
owslib                    0.18.0                     py_0    conda-forge
p4tools                   0.6.0                     dev_0    <develop>
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py37h86efe34_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
param                     1.9.1                      py_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.5.0                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
phantomjs                 2.1.1                         1    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.0.0            py37h7095ceb_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
planetfour-catalog        1.2.2                         0    michaelaye
planetpy                  0.4.6                    pypi_0    pypi
planets                   0.1.0                     dev_0    <develop>
pluggy                    0.12.0                     py_0    conda-forge
poppler                   0.67.0               hb974355_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.4                 h25afefd_1    conda-forge
poyo                      0.4.2                      py_0    conda-forge
proj4                     5.2.0             h6de7cb9_1003    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.3            py37h01d97ff_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pvl                       0.3.0                      py_1    conda-forge
py                        1.8.0                      py_0    conda-forge
py-lief                   0.9.0            py37h6d6d4d2_1    conda-forge
pyaml                     19.4.1                     py_0    conda-forge
pyarrow                   0.13.0           py37he1943e6_2    conda-forge
pybtex                    0.22.2                   py37_0    conda-forge
pybtex-docutils           0.2.1                 py37_1000    conda-forge
pyciss                    0.12.6                   pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py37h1de35cc_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pykdtree                  1.3.1           py37h917ab60_1002    conda-forge
pylint                    2.3.1                    py37_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py37h01d97ff_1002    conda-forge
pyqt                      5.9.2            py37h2a560b1_0    conda-forge
pyrsistent                0.15.2           py37h01d97ff_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysis                     0.6.0                    pypi_0    pypi
pysocks                   1.7.0                    py37_0    conda-forge
pytables                  3.5.2            py37hc2baff1_0    conda-forge
pytest                    5.0.0                    py37_0    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.5.0                      py_0    conda-forge
pytest-cache              1.0                      py37_1    defaults
pytest-cov                2.7.1                      py_0    conda-forge
pytest-doctestplus        0.3.0                      py_0    conda-forge
pytest-openfiles          0.3.1                      py_0    conda-forge
pytest-pep8               1.0.6                      py_1    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-graphviz           0.11                       py_1    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
python-pptx               0.6.18                     py_0    conda-forge
python-snappy             0.5.4            py37h1e06ddd_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyviz_comms               0.7.2                      py_0    conda-forge
pywavelets                1.0.3            py37h1e5eb4f_1    conda-forge
pyyaml                    5.1.1            py37h01d97ff_0    conda-forge
pyzmq                     18.0.2           py37h2d07e9b_0    conda-forge
qt                        5.9.7                h93ee506_2    conda-forge
qtconsole                 4.5.1                      py_0    conda-forge
re2                       2019.07.01           h6de7cb9_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
readme_renderer           24.0                       py_0    conda-forge
requests                  2.22.0                   py37_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
requirements-parser       0.2.0                      py_0    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
ruamel                    1.0                      py37_0    conda-forge
ruamel.yaml               0.15.96          py37h01d97ff_0    conda-forge
ruamel_yaml               0.15.71         py37h1de35cc_1000    conda-forge
scikit-image              0.15.0           py37h6de7cb9_0    conda-forge
scikit-learn              0.21.2           py37hd4ffd6c_1    conda-forge
scipy                     1.3.0            py37hab3da7d_0    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
selenium                  3.141.0         py37h1de35cc_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
shapely                   1.6.4           py37h79c6f3e_1005    conda-forge
sip                       4.19.8          py37h0a44026_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             h6de7cb9_1002    conda-forge
snowballstemmer           1.9.0                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.2                    py37_0    conda-forge
sphinx                    2.1.2                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-bibtex      0.4.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
spicer                    0.2b0                     dev_0    <develop>
spiceypy                  2.2.0                      py_1    conda-forge
sqlite                    3.28.0               hb7d70f7_1    conda-forge
statsmodels               0.10.0           py37heacc8b8_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
thrift                    0.11.0          py37h0a44026_1001    conda-forge
thrift-cpp                0.12.0            h874095a_1004    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
toml                      0.10.0                     py_0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.3            py37h01d97ff_0    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
twine                     1.13.0                     py_1    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
tzlocal                   1.5.1                    pypi_0    pypi
urllib3                   1.24.3                   py37_0    conda-forge
utt                       1.12                     pypi_0    pypi
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
whichcraft                0.5.2                      py_1    conda-forge
widgetsnbextension        3.5.0                    py37_0    conda-forge
wrapt                     1.11.2           py37h01d97ff_0    conda-forge
xarray                    0.12.2                     py_0    conda-forge
xerces-c                  3.2.2             h44e365a_1001    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.1.8                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
yapf                      0.27.0                     py_0    conda-forge
zeromq                    4.3.1             h0a44026_1000    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.5.1                      py_0    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```
</p></details>

**Comment by msarahan** [comment] 2019-07-03 20:47
Duplicate of #8842 

Please see that issue for more info.

**Closed by msarahan** 2019-07-03 20:47 UTC
