### ISSUE TITLE
conda list/update/remove fail (Python works)

### ISSUE THREAD

**Issue by sumoka** [conda/conda#6258] opened 2017-11-03 21:13 UTC
I am pasting the o/p of the command `conda update conda` :

`Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.12.4
       root environment : /Users/<myid>/anaconda  (writable)
    default environment : /Users/<myid>/anaconda
       envs directories : /Users/<myid>/anaconda/envs
                          /Users/<myid>/.conda/envs
          package cache : /Users/<myid>/anaconda/pkgs
                          /Users/<myid>/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /Users/<myid>/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.12.4 CPython/3.6.3 Darwin/16.7.0 OSX/10.12.6
                UID:GID : <>`

I have two installs of R one through standard R download and another through anaconda env. which I would like to get rid of, however, I am unable to perform any operation using conda commands. 

My Python and Jupyter notebooks works fine.

**Comment by kalefranz** [comment] 2017-11-03 22:16
Can you provide the error messages or stack traces you’re receiving?

**Comment by sumoka** [comment] 2017-11-03 22:20
I should have shared it in my initial post - 

`   Traceback (most recent call last):
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/<myid>/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080276.026 for timestamp`

**Comment by kalefranz** [comment] 2017-11-03 22:22
Duplicate of #6096. See that issue for solutions.

**Closed by kalefranz** 2017-11-03 22:22 UTC

**Comment by sumoka** [comment] 2017-11-03 23:45
@kalefranz - The first fix did not work. I'll go through the post and and try to fix it.
