### ISSUE TITLE
conda 4.5.1 create environment fails with TypeError: 'NoneType' in conda/core/subdir_data.py

### ISSUE THREAD

**Issue by Tagar** [conda/conda#7892] opened 2018-10-22 20:38 UTC
```bash 
$ conda create -n py36_test python==3.6.6
```
Solving environment: failed

#### >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

> 
> 
>     Traceback (most recent call last):
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
>         return func(*args, **kwargs)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
>         exit_code = do_call(args, p)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
>         exit_code = getattr(module, func_name)(args, parser)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 11, in execute
>         install(args, parser, 'create')
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 235, in install
>         force_reinstall=context.force,
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
>         force_remove, force_reinstall)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
>         final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
>         index, r = self._prepare(prepared_specs)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
>         self.subdirs, prepared_specs)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
>         new_records = query_all(spec)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
>         return tuple(concat(future.result() for future in as_completed(futures)))
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
>         self.load()
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
>         _internal_state = self._load()
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 218, in _load
>         mod_etag_headers.get('_mod'))
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 280, in _read_local_repdata
>         _internal_state = self._process_raw_repodata_str(raw_repodata_str)
>       File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
>         info['fn'] = fn
>     TypeError: 'NoneType' object does not support item assignment
> 
> `$ /opt/cloudera/parcels/Anaconda3/bin/conda create -n py36_test python==3.6.6`
> 
>   environment variables:
>                  CIO_TEST=<not set>
>          CONDA_BUILD_NAME=Anaconda3
>          CONDA_BUILD_ROOT=/opt/cloudera/parcels/Anaconda3
>                CONDA_ROOT=/opt/cloudera/parcels/Anaconda3
>               CONDA_SHLVL=0
>                   MANPATH=/opt/quest/man::/usr/share/man:/usr/share/man
>                      PATH=/vol/devel1/ruslan/miniconda3/bin:/vol/devel1/ruslan/miniconda2/bin:/u
>                           sr/java/latest/bin:/usr/java/latest/bin:/opt/cloudera/parcels/Anaconda
>                           /bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/rdautkha/
>                           bin:/usr/openv/netbackup/bin:/home/rdautkha/bin:/usr/openv/netbackup/b
>                           in
>        REQUESTS_CA_BUNDLE=<not set>
>             SSL_CERT_FILE=<not set>
> 
>      active environment : None
>             shell level : 0
>        user config file : /home/rdautkha/.condarc
>  populated config files : /home/rdautkha/.condarc
>           conda version : 4.5.11
>     conda-build version : 3.16.1
>          python version : 3.6.6.final.0
>        base environment : /opt/cloudera/parcels/Anaconda3  (read only)
>            channel URLs : https://conda.anaconda.org/anaconda/linux-64
>                           https://conda.anaconda.org/anaconda/noarch
>                           https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/linux-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/pro/linux-64
>                           https://repo.anaconda.com/pkgs/pro/noarch
>           package cache : /vol/devel1/ruslan/conda/pkgs
>        envs directories : /vol/devel1/ruslan/conda/envs
>                           /opt/cloudera/parcels/Anaconda/envs
>                           /home/rdautkha/.conda/envs
>                           /opt/cloudera/parcels/Anaconda3/envs
>                platform : linux-64
>              user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Linux/3.10.0-862.6.3.el7.x86_64 rhel/7.5 glibc/2.17
>                 UID:GID : 2074918846:30
>              netrc file : None
>            offline mode : False
> 
> 
> An unexpected error has occurred. Conda has prepared the above report.
> If submitted, this report will be used by core maintainers to improve
> future releases of conda.
> Would you like conda to send this report to the core maintainers?
> [y/N]: y
> Upload successful.
> 
> Thank you for helping to improve conda.
> Opt-in to always sending reports (and not see this message again)
> by running
> 
>     $ conda config --set report_errors true
> 
> 
>

**Comment by Tagar** [comment] 2018-10-22 20:41
Did some debugging .. 

> 
> DEBUG conda.core.subdir_data:_load(230): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/free/linux-64'. Updating mtime and loading from disk
> DEBUG conda.core.subdir_data:_read_pickled(293): found pickle file /vol/devel1/ruslan/conda/pkgs/cache/98cb6fa3.q
> DEBUG conda.core.subdir_data:_load(216): Using cached repodata for https://conda.anaconda.org/anaconda/linux-64 at /vol/devel1/ruslan/conda/pkgs/cache/c484148c.json. Timeout in 850 sec
> DEBUG conda.core.subdir_data:_read_local_repdata(266): Loading raw json for https://conda.anaconda.org/anaconda/linux-64 at /vol/devel1/ruslan/conda/pkgs/cache/c484148c.json
> failed
> DEBUG conda.base.context:root_writable(370): [Errno 13] Permission denied: '/opt/cloudera/parcels/Anaconda3/conda-meta/history'
> DEBUG conda.base.context:root_writable(370): [Errno 13] Permission denied: '/opt/cloudera/parcels/Anaconda3/conda-meta/history'
> 
> 

We have conda root environment /opt/cloudera/parcels/Anaconda3/ that's not writable to normal users.. 

Is this a known issue? 

Didn't have this problem in conda 4.3. 

We recently upgraded to conda 4.5.

**Comment by Tagar** [comment] 2018-10-22 20:56
I guess the main problem is 

> DEBUG conda.core.subdir_data:_load(230): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/main/linux-64'. Updating mtime and loading from disk
> DEBUG conda.core.subdir_data:_read_pickled(293): found pickle file /vol/devel1/ruslan/conda/pkgs/cache/47929eba.q
> DEBUG conda.core.subdir_data:_load(216): Using cached repodata for https://conda.anaconda.org/anaconda/linux-64 at /vol/devel1/ruslan/conda/pkgs/cache/c484148c.json. Timeout in 993 sec
> DEBUG conda.core.subdir_data:_read_local_repdata(266): Loading raw json for https://conda.anaconda.org/anaconda/linux-64 at /vol/devel1/ruslan/conda/pkgs/cache/c484148c.json
> failed
> 

Notice that `/vol/devel1/ruslan/conda/pkgs/cache/` is an NFS share, so it might be an issues with updating that file's metadata someway?

```python
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 218, in _load
    mod_etag_headers.get('_mod'))
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 280, in _read_local_repdata
    _internal_state = self._process_raw_repodata_str(raw_repodata_str)
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
    info['fn'] = fn
TypeError: 'NoneType' object does not support item assignment

```

**Comment by Tagar** [comment] 2018-10-22 20:59
This is where this assignment fails - `info['fn']` is not defined here:
https://github.com/conda/conda/blob/master/conda/core/subdir_data.py#L357

Any ideas how to fix this?
Thanks.

**Comment by Tagar** [comment] 2018-10-22 21:13
I guess this issue is duplicate of https://github.com/conda/conda/issues/7892 that was already reported

**Comment by skanwal** [comment] 2018-10-24 05:30
Hi,

We had also come across similar-ish issue recently.  Removing `anaconda` from the `channels` solved it.
Sharing the experience - in case this would help you as well.

Cheers,
Sehrish

**Comment by msarahan** [comment] 2018-10-26 12:53
duplicate of #7870, closing

**Closed by msarahan** 2018-10-26 12:53 UTC
