### ISSUE TITLE
Is there a way to disappear the (base) entry in the command prompt, but to keep that string for any other environment?

### ISSUE THREAD

**Issue by ZaidaEMtzMo** [conda/conda#9137] opened 2019-08-25 01:21 UTC
I have been trying to get the "(base)" string gone from my terminal every time that I open it. I have conda activated all the time, and I am ok with that, but I wish there would be away to omit the appearance of that string only. I would like it to appear when I activate any other environment, but not the main one I am in all the time. I tried by modifying the activate.d and activate.bat, but it didn't work. I then tried to add this string: `PS1="$(echo $PS1 | sed 's/(base) //') "` to them, but didn't work. Then, I finally decided to add it to the .condarc file. It work in the way that the "(base)" string didn't appear anymore but now I cannot activate conda. This error appears when I try:
```
conda create --name testing

ConfigurationLoadError: Unable to load configuration file.
  path: /home/$USER/.condarc
  reason: invalid yaml at line 3, column 0
```

Please let me know if there is any way of changing it.
Thank you.

**Comment by jjhelmus** [comment] 2019-08-29 16:18
The `changeps1` and `env_prompt` configuration control if and how conda changes to prompt when environment are activated.  Adding `changeps1: 1` to the .condarc file in your home directory will turn off the `(base)` indicator.  More information on these configuration options can be found by running `conda config --describe`.

The error you are seeing is likely cause by invalid formatting in your .condarc file.  Try removing portions of it to see if that fixes the issue.

**Comment by msarahan** [comment] 2019-12-30 21:24
closing as likely duplicate of #8169

**Closed by msarahan** 2019-12-30 21:24 UTC
