### ISSUE TITLE
Installation of a `noarch_python` package from Anaconda.org fails with 404

### ISSUE THREAD

**Issue by frol** [conda/conda#1552] opened 2015-08-27 14:41 UTC
I have successfully built and uploaded a conda package with `noarch_python` build option (https://github.com/conda/conda-build/issues/317). The package went into `noarch` subfolder on Anaconda.org, but when I try to install the given package, conda tries to reach wrong location (`linux-64` instead of `noarch`):

```
$ conda install -c salford_systems invoke
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /home/jenkins/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    invoke-0.10.1              |           py_228         160 KB

The following NEW packages will be INSTALLED:

    invoke: 0.10.1-py_228

Proceed ([y]/n)?

Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/t/sa-288608ab-8c64-4fed-99e2-ec9480ec0105/salford_systems/linux-64/invoke-0.10.1-py_228.tar.bz2
```

This issue is related to #1391

**Comment by csoja** [comment] 2015-10-26 15:25
I was not able to reproduce this problem for the example you provided.  Are you still experiencing this problem?

**Comment by frol** [comment] 2015-10-27 00:56
@csoja It is because of the fact that I have removed `noarch` package for `invoke` and uploaded converted packages for each platform.

**Comment by csoja** [comment] 2016-02-12 18:06
Tested installing https://anaconda.org/ilan/foo/files  (a noarch package) on Linux, MacOSX & Windows 64-bit machines.  Was not able to reproduce this issue.  Closing for now.  Please reopen with additional details (include conda recipe) if you believe this is still an issue.

**Closed by csoja** 2016-02-12 18:06 UTC

**Comment by frol** [comment] 2016-02-13 14:27
Indeed, it works now.
