### ISSUE TITLE
`conda info` has no support for `-c` option

### ISSUE THREAD

**Issue by stefanseefeld** [conda/conda#2174] opened 2016-03-04 21:37 UTC
`conda install -c <channel> <package>` sometimes informs me about conflicting dependencies, suggesting to use `conda info <package>` to find out the details of those conflicts. However, if <package> comes from a default channel <channel>, I'd need a way to specify the above `-c <channel>` option with the `conda info` command. Unfortunately that option isn't supported.

**Comment by kalefranz** [comment] 2017-05-10 10:22
duplicate of #1390

**Closed by kalefranz** 2017-05-10 10:22 UTC
Labels: type:feature
