### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment during conda installation

### ISSUE THREAD

**Issue by liyuaned** [conda/conda#7888] opened 2018-10-22 06:18 UTC
**I'm submitting a...**
  - [ X] bug report
  - [ ] feature request

### Steps to Reproduce

RUN if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.0; then conda install conda==4.4.11 -c anaconda; fi
 ---> Running in 996b69fba65e
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/mmlspark/lib/conda  (writable)
    default environment : /home/mmlspark/lib/conda
       envs directories : /home/mmlspark/lib/conda/envs
                          /home/mmlspark/.conda/envs
          package cache : /home/mmlspark/lib/conda/pkgs
                          /home/mmlspark/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-101-generic debian/stretch/sid glibc/2.23    
                UID:GID : 0:0

`$ /home/mmlspark/bin/conda install conda==4.4.11 -c anaconda`

    Traceback (most recent call last):
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/common/io.py", line 174, in decorated
        return f(*args, **kwds)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/index.py", line 103, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/index.py", line 122, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 476, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "/home/mmlspark/lib/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 412, in process_repodata
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

Docker image build failed
Removing any dangling images
The command '/bin/sh -c if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.0; then conda install conda==4.4.11 -c anaconda; fi' returned a non-zero code: 1
```


## Expected Behavior
<!-- What do you think should happen? -->


## Environment Information
<details open><summary><code>`conda info`</code></summary><p>
<!-- between the ticks below, paste the output of 'conda info' -->

```

```
</p></details>


<details open><summary><code>`conda config --show-sources`</code></summary><p>
<!-- between the ticks below, paste the output of 'conda config --show-sources' -->

```

```
</p></details>


<details><summary><code>`conda list --show-channel-urls`</code></summary><p>
<!-- between the ticks below, paste the output of 'conda list --show-channel-urls' -->

`

```
</p></details>

**Comment by scalavision** [comment] 2018-10-22 14:54
I get something similar building within Docker, I think?

My conda info outputs:

```
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /miniconda  (writable)
  default environment : /miniconda
     envs directories : /miniconda/envs
        package cache : /miniconda/pkgs
         channel URLs : https://conda.anaconda.org/anaconda/linux-64/
                        https://conda.anaconda.org/anaconda/noarch/
                        https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /root/.condarc
    is foreign system : False
```
The traceback is like this:
```
Fetching package metadata: ............An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 240, in install
    prefix=prefix)
  File "/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "/miniconda/lib/python2.7/site-packages/conda/api.py", line 43, in get_index
    unknown=unknown)
  File "/miniconda/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 271, in fetch_index
    info['channel'] = url
TypeError: 'NoneType' object does not support item assignment
The command '/bin/sh -c conda install -c bioconda samtools' returned a non-zero code: 1
```

**Comment by scalavision** [comment] 2018-10-23 08:44
Seems this is related to this:

https://bioconda.github.io/#set-up-channels

**Comment by msarahan** [comment] 2018-10-26 12:57
duplicate of #7870, closing

**Closed by msarahan** 2018-10-26 12:57 UTC
