### ISSUE TITLE
version number comparison issue in 4.6.x when resolving requirements

### ISSUE THREAD

**Issue by alaniwi** [conda/conda#8309] opened 2019-02-19 21:38 UTC
## Current Behavior

Trying to do install from a yml file containing:
```
  - cdms2=3.1.0
  - esmf=7.1.0r
```
where the `cdms2` package requires `esmf >= 7.1.*`

works fine in conda 4.5.x (tested in 4.5.1 and 4.5.13), but in conda 4.6.x (tested in 4.6.1 and 4.6.4) it gives:
```
ResolvePackageNotFound: 
  - cdms2=3.1.0 -> esmf[version='>=7.1.*']
```

### Steps to Reproduce

```
$ conda install conda=4.6.1
$ conda env create -p /path/to/envs/testenv -f /path/to/test.yml 
```
where `test.yml` contains:
```
name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cdms2=3.1.0=py27h6091dcd_0
  - esmf=7.1.0r=hdfb41a0_1003
  - esmpy=7.1.0r=py27h24bf2e0_2
prefix: /tmp/miniconda2/envs/testenv
```
(Note this is not the full environment but it is sufficent to reproduce the error.)

This gives:
```
ResolvePackageNotFound: 
  - cdms2==3.1.0=py27h6091dcd_0 -> esmf[version='>=7.1.*']
  - cdms2==3.1.0=py27h6091dcd_0 -> esmpy[version='>=7.1.*']
```

The dependency is as follows:
```
$ conda search cdms2=3.1.0=py27h6091dcd_0 --info
...
dependencies:
...
  - esmf >=7.1.*
  - esmpy >=7.1.*
```

## Expected Behavior

I *believe* that it ought to accept the dependency and create the environment, as it does e.g. in 4.5.13:

```
Solving environment: done
... etc ...
```

If this is *not* the case (i.e. if `7.1.0r` is not a valid version number to satisfy `>= 7.1.*`) then please say, so that I can advise the maintainers of `cdms2` accordingly.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

(home directory path munged)

```
     active environment : None
            shell level : 0
       user config file : /path/to/.condarc
 populated config files : /path/to/.condarc
          conda version : 4.6.4
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /tmp/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp/miniconda2/pkgs
                          /path/to/.conda/pkgs
       envs directories : /tmp/miniconda2/envs
                          /path/to/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/2.7.15 Linux/2.6.32-754.6.3.el6.x86_64 rhel/6.10 glibc/2.12
                UID:GID : 25168:26210
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /path/to/.condarc <==
channels:
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /tmp/miniconda2:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0    defaults
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.11.5           py27he75722e_1    defaults
chardet                   3.0.4                    py27_1    defaults
conda                     4.6.4                    py27_0    conda-forge
conda-env                 2.6.0                         1    defaults
cryptography              2.4.2            py27h1ba5d50_0    defaults
enum34                    1.1.6                    py27_1    defaults
futures                   3.2.0                    py27_0    defaults
idna                      2.8                      py27_0    defaults
ipaddress                 1.0.22                   py27_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1a            h14c3975_1000    conda-forge
pip                       18.1                     py27_0    defaults
pycosat                   0.6.3            py27h14c3975_0    defaults
pycparser                 2.19                     py27_0    defaults
pyopenssl                 18.0.0                   py27_0    defaults
pysocks                   1.6.8                    py27_0    defaults
python                    2.7.15               h9bab390_6    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py27_0    defaults
ruamel_yaml               0.15.46          py27h14c3975_0    defaults
setuptools                40.6.3                   py27_0    defaults
six                       1.12.0                   py27_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
urllib3                   1.24.1                   py27_0    defaults
wheel                     0.32.3                   py27_0    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by xylar** [comment] 2019-02-20 01:45
I'm also seeing this problem (for this same package: `esmf`).

**Comment by xylar** [comment] 2019-02-20 02:10
Seems to be a repeat of https://github.com/conda/conda/issues/8158

**Comment by msarahan** [comment] 2019-02-20 02:29
closing as duplicate of #8158

**Closed by msarahan** 2019-02-20 02:29 UTC
