### ISSUE TITLE
activate in 4.1-4.2.3 clobbers non-conda PATH changes

### ISSUE THREAD

**Issue by timsnyder** [conda/conda#3287] opened 2016-08-12 14:01 UTC
When doing the following:

``` bash
# start with very basic path
export PATH=/usr/local/bin:/usr/bin:/bin;
echo PATH=$PATH;

# Add conda to path
source $MINICONDA_PREFIX/bin/activate root;
echo PATH=$PATH;

# Customize PATH some more
run export PATH=/foo/bin:$PATH;
echo PATH=$PATH;

# Switch to a different conda environment
run source activate bokeh-dev-py34;
echo PATH=$PATH;
```

With any version of conda newer than 4.1, using both bash and zsh I see `/foo/bin` dropped from PATH in the last echo statement.  

Before 4.1, `activate` would reorder PATH, putting the latest activated environment at the beginning of PATH but any modifications between the first and second activate would at least still be there.  I was willing to live with that behavior because the help for activate clearly documented that it put the new environment first.

Is this new(er) behavior intentional?

**Comment by kalefranz** [comment] 2016-08-12 14:24
No, it's not. And thanks for the report.  It's something we'll be sure is fixed with https://github.com/conda/conda/pull/3175

CC @njalerikson

**Comment by njalerikson** [comment] 2016-08-12 14:51
the current activate/deactivate handling of the path and other variables is inline with how a subshell would work

so we instead want to be injecting/removing conda while leaving any root conda on the path as discussed yesterday

**Comment by njalerikson** [comment] 2016-08-12 20:10
just updated #3175 to address this

**Comment by timsnyder** [comment] 2016-08-12 23:46
Glad to see the support for other shells in progress.  Let me know if there's any way I can help.

**Comment by timsnyder** [comment] 2016-11-16 13:12
I'm excited to see #3175 coming along and hopefully being included in 4.3.  I'll try to keep an eye on the conda-canary channel for an initial version to try out.  If you ping me, and @groutr here when it's available, we'll be happy to test and confirm our ability to upgrade.

**Comment by kalefranz** [comment] 2016-11-17 02:47
#3175 merged today. Canary coming as soon as possible. Need to wrap up the other issues marked with the blocking tag, then we're set.

**Comment by groutr** [comment] 2017-01-05 00:07
Testing conda-canary 4.3.1 and it still fails the case given in the OP.

```
% export PATH=/usr/local/bin:/usr/bin:/bin;
% echo $PATH
/usr/local/bin:/usr/bin:/bin
% source ~/miniconda2/bin/activate test1
% echo $PATH
****/miniconda2/envs/test1/bin:/usr/local/bin:/usr/bin:/bin
% export PATH=/foo/bin:$PATH;
% echo $PATH
/foo/bin:****/miniconda2/envs/test1/bin:/usr/local/bin:/usr/bin:/bin
% source ~/miniconda2/bin/activate test2
% echo $PATH
****/miniconda2/envs/test2/bin:/usr/local/bin:/usr/bin:/bin
```

**Comment by mingwandroid** [comment] 2017-01-05 01:08
@groutr, the discussion about the need for reversion starts at https://github.com/conda/conda/pull/3175#issuecomment-261205963

**Comment by groutr** [comment] 2017-01-05 18:10
Thanks @mingwandroid.  Somehow I missed the mental connection between that and the reason for reverting.  Makes sense now.  Would it be possible to address this regression in a much smaller PR?

I think #1727 may be responsible for this change in behavior.

**Closed** 2017-01-07 06:31 UTC
Labels: bug, ent, ¡blocking!

**Comment by kalefranz** [comment] 2017-01-07 06:38
This will be released with `4.2.14` (probably on Monday), and it will also be in any future `4.1.x` release if we cut another one.

**Comment by timsnyder** [comment] 2017-01-09 16:28
Thanks @kalefranz .   We'll be on the lookout for 4.2.14 and give it a try once it's available.

**Comment by groutr** [comment] 2017-01-09 16:59
Just tested 4.2.14 and AFAICT, the issue is fixed in that version.  Thanks @kalefranz for addressing this.

**Comment by kalefranz** [comment] 2017-01-09 17:35
Hey guys `4.2.14` should be live in defaults now.

**Comment by groutr** [comment] 2017-01-10 17:41
@kalefranz Could there be another canary release of 4.3 with this fix in it?  I believe our setup requires the lockless, multi-user features in 4.3.
