### ISSUE TITLE
AttributeError: 'exceptions.OSError' object has no attribute 'read'

### ISSUE THREAD

**Issue by jsiverskog** [conda/conda#3985] opened 2016-12-01 16:06 UTC
I got this when running conda search:

```
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.11
         python version : 2.7.12.final.0
       requests version : 2.12.3
       root environment : /home/jacob/.miniconda2  (writable)
    default environment : /home/jacob/.miniconda2
       envs directories : /home/jacob/.miniconda2/envs
          package cache : /home/jacob/.miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /home/jacob/.miniconda2/bin/conda search -c file://conda-chan/ --override-channels`




    Traceback (most recent call last):
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/cli/main_search.py", line 126, in execute
        execute_search(args, parser)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/cli/main_search.py", line 174, in execute_search
        unknown=args.unknown)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
        for url in urls]
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
        r.content
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/requests/models.py", line 781, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/home/jacob/.miniconda2/lib/python2.7/site-packages/requests/models.py", line 714, in generate
        chunk = self.raw.read(chunk_size)
    AttributeError: 'exceptions.OSError' object has no attribute 'read'
```

**Comment by immerrr** [comment] 2016-12-08 18:18
Same here, fails for me because  
```
u'file:///home/immerrr/.conda/conda-bld/noarch/repodata.json.bz2'
```
is missing

**Comment by immerrr** [comment] 2016-12-08 18:37
The problem is in `LocalFSAdapter` that for some reason assigns an exception to `request.raw` that's meant to be file-like on line 289 of `/home/immerrr/.conda/lib/python2.7/site-packages/conda/connection.py`.

It seems to be fixed in master, but conda update --all doesn't seem to fetch the fix for me, so a really quick fix would be to replace
```
            resp.raw = exc
```
with
```
            resp.raw = StringIO(str(exc))
```

**Comment by jsiverskog** [comment] 2016-12-08 21:31
Another possible workaround is to call it like this:
conda search -c ./conda-chan/ --override-channels

**Comment by jakirkham** [comment] 2017-01-05 20:15
Also seeing this problem.

**Comment by jakirkham** [comment] 2017-01-05 20:19
Should add that I can all reproduce it with calls to use the local package index (e.g. `conda install --use-local ...`).

**Comment by jakirkham** [comment] 2017-01-05 20:20
Should add that I can also reproduce it with calls to use the local package index (e.g. `conda install --use-local ...`).

**Comment by kalefranz** [comment] 2017-05-01 20:04
fixed.

**Closed by kalefranz** 2017-05-01 20:04 UTC
