### ISSUE TITLE
Conda run show output line by line

### ISSUE THREAD

**Issue by technic** [conda/conda#9373] opened 2019-10-25 21:33 UTC
Hi,
when I do `conda run -n NAME foobar` the stdout/stderr is read completely and then printed to the user
https://github.com/conda/conda/blob/8174f5f85d63d49cf741cd4ad2e384b942d73831/conda/cli/main_run.py#L27

This is not what I expect if I like to run a lengthy script, and want to watch it in real time.

The possible fix would be to run `stdout.readline()` while loop, but this doesn't solve the problem with stderr. We can redirect stderr to stdout if we I fine by not distinguishing this.

The proper solutions also exist, but I am not aware on how much it is portable between platforms and python versions. For example the `poll()` call is AFAIK unix only, and `await` features are only for recent python.

**Comment by gilescope** [comment] 2019-10-27 20:47
Dupe of #8386, definitely needs fixing.

**Comment by jamfly** [comment] 2021-01-04 06:18
Does anyone has solution? I encounter this issue, and cannot fix it.

**Comment by kenodegard** [comment] 2022-03-10 19:36
This is possible with the `--no-capture-output` argument.

Duplicate of https://github.com/conda/conda/issues/9412.

**Closed by kenodegard** 2022-03-10 19:36 UTC
Labels: type::bug, source::community, plugins::run, duplicate
