### ISSUE TITLE
conda update --all failed on Windows 7 Pro, 64-Bit

### ISSUE THREAD

**Issue by ReddyKilowatt** [conda/conda#6905] opened 2018-02-21 03:43 UTC
**I'm submitting a...**
  - [X ] bug report
  - [ ] feature request

## Current Behavior

Most/all packages are downloaded and installed. .ipykernel-post-link.bat fails

### Steps to Reproduce

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

`$ C:\ProgramData\Anaconda2\Scripts\conda update --all -v`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\link.py", line 297, in execute
        rollback_excs,
    CondaMultiError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProgramData\Anaconda2\envs\py36dev\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

```

## Expected Behavior

all packages should install cleanly

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(py36dev) C:\Users\MyUSerName>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2\envs\py36dev
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\z48176zz\AppData\Local\conda\conda\envs
                          C:\Users\Z48176ZZ\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\z48176zz\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/7 Windows/6.1.7601
          administrator : True
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Nothing was displayed

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(py36dev) C:\Users\Z48176ZZ>conda **list --show-channel-urls**
# packages in environment at C:\ProgramData\Anaconda2\envs\py36dev:
#
_license                  1.1                      py36_1    defaults
alabaster                 0.7.10           py36hedafc74_0    defaults
anaconda                  custom           py36h8b40cde_0    defaults
anaconda-client           1.6.5            py36hb3b9584_0    defaults
anaconda-navigator        1.6.8            py36h480f867_0    defaults
anaconda-project          0.8.0            py36h88395f3_0    defaults
appJar                    0.90.0                    <pip>
arcgis                    1.0.1                    py36_1    esri
asn1crypto                0.22.0           py36hee29ec9_1    defaults
astroid                   1.5.3            py36h3217d1f_0    defaults
astropy                   2.0.2            py36h5dd925f_4    defaults
attrs                     17.2.0                    <pip>
babel                     2.5.0            py36h9773feb_0    defaults
backports                 1.0              py36hf8a4c8f_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36h567543b_2    defaults
beautifulsoup4            4.6.0            py36h4361f19_1    defaults
bitarray                  0.8.1            py36hfa6e2cd_1    defaults
bkcharts                  0.2              py36h41dda5e_0    defaults
blaze                     0.11.3           py36h70bead1_0    defaults
bleach                    2.0.0            py36h2453164_0    defaults
bokeh                     0.12.7           py36h515f05b_1    defaults
boto                      2.48.0           py36h2dece20_1    defaults
bottleneck                1.2.1            py36hd155fb5_0    defaults
bzip2                     1.0.6            vc14h31cfb99_1  [vc14]  defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cachecontrol              0.12.3           py36h922bf65_0    defaults
certifi                   2017.7.27.1      py36h8287e07_0    defaults
cffi                      1.10.0           py36h935798a_1    defaults
chardet                   3.0.4            py36hf2a9688_1    defaults
click                     6.7              py36hfb6b3c4_0    defaults
cloudpickle               0.4.0            py36h859eb6c_0    defaults
clyent                    1.2.2            py36h4dd741a_1    defaults
colorama                  0.3.9            py36he9a059a_0    defaults
comtypes                  1.1.2            py36h9d81d3a_0    defaults
console_shortcut          0.1.1                haa4cab3_2    defaults
contextlib2               0.5.5            py36h19a5d9b_0    defaults
coverage                  4.4.1                     <pip>
cryptography              2.0.3            py36h011be45_1    defaults
curl                      7.55.1           vc14h8488bd0_3  [vc14]  defaults
cycler                    0.10.0           py36hd299a41_0    defaults
cython                    0.26.1           py36h9e8b7db_0    defaults
cytoolz                   0.8.2            py36hdaace5b_0    defaults
dask                      0.15.2           py36hb47af22_0    defaults
dask-core                 0.15.2           py36he76c447_0    defaults
datashape                 0.5.4            py36h801e743_0    defaults
decorator                 4.1.2            py36hac4cfca_0    defaults
distlib                   0.2.5            py36hada7309_0    defaults
distributed               1.18.3           py36h0bcddad_0    defaults
docutils                  0.14             py36h4cf9f97_0    defaults
entrypoints               0.2.3            py36hd26a89c_2    defaults
et_xmlfile                1.0.1            py36ha14dd7c_0    defaults
fastcache                 1.0.2            py36h41c7961_0    defaults
filelock                  2.0.12           py36h38d8215_0    defaults
flake8                    3.3.0                    py36_0    defaults
flask                     0.12.2           py36h7a02084_0    defaults
flask-cors                3.0.3            py36h499a37b_0    defaults
freetype                  2.8              vc14hfa46bb4_0  [vc14]  defaults
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                h4b36c58_0    defaults
gevent                    1.2.2            py36h35b58af_0    defaults
glob2                     0.5              py36h850fbe3_1    defaults
Gooey                     1.0.0                     <pip>
greenlet                  0.4.12           py36hdfd23a0_0    defaults
h5py                      2.7.0            py36h2a75726_1    defaults
hdf5                      1.10.1           vc14h7c25517_0  [vc14]  defaults
heapdict                  1.0.0            py36hbd458ba_0    defaults
html5lib                  0.999999999      py36h3e19504_0    defaults
hypothesis                3.33.0                    <pip>
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2             vc14hbe8e9fa_0  [vc14]  defaults
idna                      2.6              py36h787667b_1    defaults
imageio                   2.2.0            py36h74fbb4f_0    defaults
imagesize                 0.7.1            py36h8cc6c1c_0    defaults
intel-openmp              2018.0.0             hda8db3e_7    defaults
ipykernel                 4.6.1            py36h9617649_0    defaults
ipython                   6.1.0            py36h25a49e7_1    defaults
ipython_genutils          0.2.0            py36h011d6f9_0    defaults
ipywidgets                7.0.0            py36he7427df_0    defaults
isort                     4.2.15           py36h9892446_0    defaults
itsdangerous              0.24             py36h0eb04fb_1    defaults
jdcal                     1.3              py36hdee49d3_0    defaults
jedi                      0.10.2           py36he9c8e28_0    defaults
jinja2                    2.9.6            py36hcda7f41_1    defaults
jpeg                      9b               vc14h39a59fb_1  [vc14]  defaults
jsonschema                2.6.0            py36hc586ae5_0    defaults
jupyter                   1.0.0            py36h16e480c_2    defaults
jupyter_client            5.1.0            py36h1f9acbd_0    defaults
jupyter_console           5.2.0            py36hb66b1b8_1    defaults
jupyter_core              4.3.0            py36h576004c_0    defaults
jupyterlab                0.27.0           py36h65ec9ff_2    defaults
jupyterlab_launcher       0.4.0            py36h4890406_0    defaults
kerberos-sspi             0.2                      py36_0    defaults
lazy-object-proxy         1.3.1            py36hfebf436_0    defaults
libiconv                  1.15             vc14h61b1384_5  [vc14]  defaults
libpng                    1.6.32           vc14hf2380a1_2  [vc14]  defaults
libssh2                   1.8.0            vc14h91c0462_2  [vc14]  defaults
libtiff                   4.0.8           vc14h38eb8c7_10  [vc14]  defaults
libxml2                   2.9.4            vc14h3c340fd_5  [vc14]  defaults
libxslt                   1.1.29           vc14h4217bde_5  [vc14]  defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36h3eabf40_1    defaults
lockfile                  0.12.2           py36hbbd9834_0    defaults
lxml                      3.8.0            py36hdf3c5c2_0    defaults
markupsafe                1.0              py36h3b07c4d_1    defaults
matplotlib                2.0.2            py36hcac705d_1    defaults
mccabe                    0.6.1            py36ha34857b_1    defaults
menuinst                  1.4.8            py36hc3e3049_0    defaults
mistune                   0.7.4            py36hd7f275d_0    defaults
mkl                       2018.0.0             hd024497_4    defaults
mkl-service               1.1.2            py36h10c1010_4    defaults
mpmath                    0.19             py36h16eb394_2    defaults
msgpack-python            0.4.8            py36h1581075_0    defaults
multipledispatch          0.4.9            py36hd8bd89d_0    defaults
navigator-updater         0.1.0            py36he13d301_0    defaults
nbconvert                 5.3.1            py36h5066f46_0    defaults
nbformat                  4.4.0            py36hfe36a2e_0    defaults
networkx                  1.11             py36ha8b2ae0_0    defaults
nltk                      3.2.4            py36h4f806ae_0    defaults
nose                      1.3.7            py36h732162c_2    defaults
notebook                  5.0.0            py36hb30061a_1    defaults
numba                     0.35.0             np113py36_10    defaults
numexpr                   2.6.2            py36h686ca0e_1    defaults
numpy                     1.13.1           py36h730a520_2    defaults
numpydoc                  0.7.0            py36he021ee4_0    defaults
odo                       0.5.1            py36h3d61389_0    defaults
olefile                   0.44             py36hb56be0d_0    defaults
openpyxl                  2.4.8            py36hc89560d_1    defaults
openssl                   1.0.2l           vc14h7709ba0_2  [vc14]  defaults
packaging                 16.8             py36h7c26a67_1    defaults
pandas                    0.20.3           py36h93e7217_2    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py36hbaae778_1    defaults
partd                     0.3.8            py36h9032c1e_0    defaults
path.py                   10.3.1           py36hecbadf8_0    defaults
pathlib2                  2.3.0            py36hebc6caf_0    defaults
patsy                     0.4.1            py36h8a8f1ce_0    defaults
pep8                      1.7.0            py36h68eb8c5_0    defaults
pickleshare               0.7.4            py36he181f7f_0    defaults
pillow                    4.2.1            py36hc1b3d4a_0    defaults
Pillow                    4.3.0                     <pip>
pip                       9.0.1            py36h09019dc_3    defaults
pkginfo                   1.4.1            py36h6186838_1    defaults
ply                       3.10             py36h9282218_0    defaults
progress                  1.3              py36h646ed32_0    defaults
prompt_toolkit            1.0.15           py36ha226939_0    defaults
psutil                    5.2.2            py36h8b9e7f1_0    defaults
psutil                    5.4.2                     <pip>
py                        1.4.34           py36h5d7abe8_1    defaults
pycodestyle               2.3.1            py36h265b76b_0    defaults
pycosat                   0.6.2            py36h06ed0df_1    defaults
pycparser                 2.18             py36h315bf61_1    defaults
pycrypto                  2.6.1            py36h08e4588_1    defaults
pycurl                    7.43.0           py36he5719a0_3    defaults
pyflakes                  1.5.0            py36h2baec01_1    defaults
pygame                    1.9.3                     <pip>
pygments                  2.2.0            py36h1a04f08_0    defaults
PyInstaller               3.2.1                     <pip>
pylint                    1.7.2            py36he4ca981_0    defaults
pyodbc                    4.0.17           py36h458d450_0    defaults
pyopenssl                 17.2.0           py36h2105193_0    defaults
pyparsing                 2.2.0            py36h9ef7486_1    defaults
PyPDF2                    1.26.0                    <pip>
pyqt                      5.6.0            py36h13ac1a8_5    defaults
pysocks                   1.6.7            py36hbb234f4_1    defaults
pytables                  3.4.2            py36h5791413_1    defaults
pytest                    3.2.1            py36h842b08d_1    defaults
python                    3.6.2               h21b614c_11    defaults
python-dateutil           2.6.1            py36h507c767_1    defaults
pytz                      2017.2           py36h6ca8096_1    defaults
pywavelets                0.5.2            py36hf262123_0    defaults
pywin32                   221              py36heebab90_0    defaults
pyyaml                    3.12             py36h624d9f2_1    defaults
pyzmq                     16.0.2           py36h450087d_2    defaults
qt                        5.6.2           vc14h6f76a7e_12  [vc14]  defaults
qtawesome                 0.4.4            py36h6b33ce7_0    defaults
qtconsole                 4.3.1            py36h86495bc_0    defaults
qtpy                      1.3.1            py36hc5ff042_0    defaults
requests                  2.18.4           py36h964142b_1    defaults
rope                      0.10.5           py36h3c8b003_0    defaults
ruamel_yaml               0.11.14          py36h1a6402c_2    defaults
scikit-image              0.13.0           py36h32d7ed4_1    defaults
scikit-learn              0.19.0           py36he1ad879_2    defaults
scipy                     0.19.1           py36hfc7e94f_3    defaults
seaborn                   0.8.0            py36h5f15cc2_0    defaults
setuptools                36.5.0           py36h7f22f53_0    defaults
setuptools                36.2.0                    <pip>
simplegeneric             0.8.1            py36h295c9ac_0    defaults
singledispatch            3.4.0.3          py36h2687f66_0    defaults
sip                       4.18.1           py36h0e39f04_2    defaults
six                       1.10.0           py36hcdf3386_1    defaults
snowballstemmer           1.2.1            py36h5e2b779_0    defaults
sortedcollections         0.5.3            py36hd1c3950_0    defaults
sortedcontainers          1.5.7            py36h4eaf07f_0    defaults
sphinx                    1.6.3            py36h9a8bd83_0    defaults
sphinxcontrib             1.0              py36h3cc09c9_1    defaults
sphinxcontrib-websupport  1.0.1            py36h10e879d_1    defaults
spyder                    3.2.3            py36h5e42050_0    defaults
sqlalchemy                1.1.13           py36h5c218a5_0    defaults
sqlite                    3.20.1           vc14hf772eac_1  [vc14]  defaults
statsmodels               0.8.0            py36h2172a75_0    defaults
sympy                     1.1.1            py36hba5725f_0    defaults
tabulate                  0.8.2                     <pip>
tblib                     1.3.2            py36h96aaa60_0    defaults
testpath                  0.3.1            py36ha9283f1_0    defaults
tk                        8.6.7            vc14h051b162_1  [vc14]  defaults
toolz                     0.8.2            py36he12a8a7_0    defaults
tornado                   4.5.2            py36hfd51417_0    defaults
traitlets                 4.3.2            py36h0dbcc04_0    defaults
typing                    3.6.2            py36h9649c0b_0    defaults
unicodecsv                0.14.1           py36h238903e_0    defaults
urllib3                   1.22             py36hf0c4117_0    defaults
vc                        14                   h2379b0c_1    defaults
vs2015_runtime            14.0.25123           h98fd7d1_1    defaults
wcwidth                   0.1.7            py36hc8ec93f_0    defaults
webencodings              0.5.1            py36hf0a7dc3_1    defaults
werkzeug                  0.12.2           py36h5b09e35_0    defaults
wheel                     0.29.0           py36h442dda1_1    defaults
widgetsnbextension        3.0.2            py36h98546b4_1    defaults
win_inet_pton             1.0.1            py36h6b5aef5_1    defaults
win_unicode_console       0.5              py36ha08cfaa_0    defaults
wincertstore              0.2              py36hcdd9a18_0    defaults
wrapt                     1.10.11          py36h084cbfa_0    defaults
wxPython                  4.0.0b1                   <pip>
xlrd                      1.1.0            py36he7b893d_1    defaults
xlsxwriter                0.9.8            py36h5b0eb8e_0    defaults
xlwings                   0.11.4           py36h89f095e_0    defaults
xlwt                      1.3.0            py36hb79324b_0    defaults
yaml                      0.1.7            vc14h188b4a1_1  [vc14]  defaults
zict                      0.1.2            py36hf5af582_0    defaults
zlib                      1.2.11           vc14h902601c_1  [vc14]  defaults


```
</p></details>

**Comment by kalefranz** [comment] 2018-02-21 17:42
This is a duplicate of ContinuumIO/anaconda-issues#8087. Please see that issue for further discussion.

**Closed by kalefranz** 2018-02-21 17:42 UTC
