### ISSUE TITLE
unexpected error while installing opencv3 through anaconda prompt

### ISSUE THREAD

**Issue by alijawad07** [conda/conda#6112] opened 2017-10-08 20:37 UTC
(C:\Users\Ali Jawad\Anaconda3) C:\Users\Ali Jawad>conda install -c menpo opencv3
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\Ali Jawad\Anaconda3  (writable)
    default environment : C:\Users\Ali Jawad\Anaconda3
       envs directories : C:\Users\Ali Jawad\Anaconda3\envs
                          C:\Users\Ali Jawad\AppData\Local\conda\conda\envs
                          C:\Users\Ali Jawad\.conda\envs
          package cache : C:\Users\Ali Jawad\Anaconda3\pkgs
                          C:\Users\Ali Jawad\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/menpo/win-64
                          https://conda.anaconda.org/menpo/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Ali Jawad\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Users\Ali Jawad\Anaconda3\Scripts\conda install -c menpo opencv3`

    Traceback (most recent call last):
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\cli\install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "C:\Users\Ali Jawad\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506084313.778 for timestamp

**Comment by nehaljwani** [comment] 2017-10-08 21:18
Closing as duplicate of #6096 (Please read all comments there before attempting the solution)

**Closed by nehaljwani** 2017-10-08 21:18 UTC
