### ISSUE TITLE
ImportError: No module named 'pycosat'

### ISSUE THREAD

**Issue by jamesengleback** [conda/conda#7728] opened 2018-09-03 14:31 UTC
## Current Behavior

I couldn't start any of my text editors, and conda itself couldn't do any tasks without giving an error message about pycosat. Here's what I put in the command line:
C:\Users\MFBX3JE3>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\MFBX3JE3\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 44, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\zmq\__init__.py", line 34, in <module>
    from zmq import backend
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\zmq\backend\select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'

C:\Users\MFBX3JE3>conda install -c auto constants
Traceback (most recent call last):
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\MFBX3JE3\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 6, in <module>
    from .install import install
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\install.py", line 20, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\index.py", line 7, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 34, in <module>
    from ..history import History
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\history.py", line 26, in <module>
    from .resolve import MatchSpec
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ImportError: No module named 'pycosat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MFBX3JE3\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main.py", line 113, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 1108, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 822, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 862, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 873, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 943, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>
    from ..core.subdir_data import SubdirData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 28, in <module>
    from ..core.package_cache_data import PackageCacheData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 34, in <module>
    from ..history import History
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\history.py", line 26, in <module>
    from .resolve import MatchSpec
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ImportError: No module named 'pycosat'

C:\Users\MFBX3JE3>conda update
Traceback (most recent call last):
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\MFBX3JE3\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 9, in <module>
    from .install import install
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\install.py", line 20, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\index.py", line 7, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 34, in <module>
    from ..history import History
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\history.py", line 26, in <module>
    from .resolve import MatchSpec
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ImportError: No module named 'pycosat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MFBX3JE3\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main.py", line 113, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 1108, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 822, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 862, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 873, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 943, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>
    from ..core.subdir_data import SubdirData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 28, in <module>
    from ..core.package_cache_data import PackageCacheData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 34, in <module>
    from ..history import History
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\history.py", line 26, in <module>
    from .resolve import MatchSpec
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ImportError: No module named 'pycosat'

C:\Users\MFBX3JE3>conda -V
conda 4.5.11

### Steps to Reproduce

```

```

## Expected Behavior

I looked at issue #862 and it mine seems similar to theirs.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
C:\Users\MFBX3JE3>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\MFBX3JE3\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>
        from ..core.subdir_data import SubdirData
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 28, in <module>
        from ..core.package_cache_data import PackageCacheData
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 34, in <module>
        from ..history import History
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\history.py", line 26, in <module>
        from .resolve import MatchSpec
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
        from .common.logic import Clauses, minimal_unsatisfiable_subset
      File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
        import pycosat
    ImportError: No module named 'pycosat'

`$ C:\Users\MFBX3JE3\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
C:\Users\MFBX3JE3>conda config --show-sources
==> C:\Users\MFBX3JE3\.condarc <==
ssl_verify: True
channels:
  - defaults
  - BjornFJohansson


C:\Users\MFBX3JE3>
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
C:\Users\MFBX3JE3>conda list --show-channel-urls
Traceback (most recent call last):
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\MFBX3JE3\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 15, in <module>
    from ..egg_info import get_egg_info
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\misc.py", line 17, in <module>
    from .core.index import get_index
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\index.py", line 7, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 34, in <module>
    from ..history import History
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\history.py", line 26, in <module>
    from .resolve import MatchSpec
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ImportError: No module named 'pycosat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MFBX3JE3\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main.py", line 113, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 1108, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 822, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 862, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 873, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\exceptions.py", line 943, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>
    from ..core.subdir_data import SubdirData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 28, in <module>
    from ..core.package_cache_data import PackageCacheData
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 34, in <module>
    from ..history import History
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\history.py", line 26, in <module>
    from .resolve import MatchSpec
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\resolve.py", line 11, in <module>
    from .common.logic import Clauses, minimal_unsatisfiable_subset
  File "C:\Users\MFBX3JE3\Anaconda3\lib\site-packages\conda\common\logic.py", line 32, in <module>
    import pycosat
ImportError: No module named 'pycosat'

C:\Users\MFBX3JE3>
```
</p></details>

**Comment by kalefranz** [comment] 2018-09-04 02:35
This is a duplicate of https://github.com/conda/conda/issues/7714. Please see that issue for details and solutions.

**Closed by kalefranz** 2018-09-04 02:35 UTC

**Comment by jamesengleback** [comment] 2018-09-05 10:10
Thank you,

That solved the pycosat issue, I updated all packages though now I can not import pandas into a notebook without seeing an attribute error:


in:

import numpy as np
import pandas as pd


out:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-68532d870e0c> in <module>()
      1 import numpy as np
----> 2 import pandas as pd
      3
      4 NewRecipes = pd.DataFrame(pd.concat([
      5                       pd.Series(np.random.randint(7,9, size = size),name =  'No. of cycles'),# pH

~\Anaconda3\lib\site-packages\pandas\__init__.py in <module>()
     38
     39 # let init-time option registration happen
---> 40 import pandas.core.config_init
     41
     42 from pandas.core.api import *

~\Anaconda3\lib\site-packages\pandas\core\config_init.py in <module>()
     10
     11 """
---> 12 import pandas.core.config as cf
     13 from pandas.core.config import (is_int, is_bool, is_text, is_instance_factory,
     14                                 is_one_of_factory, is_callable)

~\Anaconda3\lib\site-packages\pandas\core\config.py in <module>()
     55 import warnings
     56 from pandas.compat import map, lmap, u
---> 57 import pandas.compat as compat
     58
     59 DeprecatedOption = namedtuple('DeprecatedOption', 'key msg rkey removal_ver')

AttributeError: module 'pandas' has no attribute 'compat'


Is this related?


Best wishes
James

________________________________
