### ISSUE TITLE
Conda --explicit: could not parse explicit url

### ISSUE THREAD

**Issue by evanseitz** [conda/conda#9272] opened 2019-09-23 16:31 UTC
I'm trying to streamline a conda environment for a large public release where users will be downloading from different operating systems.

The environment I'm using had to be installed very carefully: first installing an older version of vtk, then mayavi and pyqt4, then finally upgrading vtk to current and adding numerous other modules. Due to this, .yml files have performed erratically across numerous OS; for example, the attached .yml (needed to change from .yml to .txt to attach) works great on CentOS but has an error "numpy not found" in Ubuntu.

Given this, I've been instructed on another repo (while trying to do a conda-lock) to instead do `conda list --explicit > spec-file.txt` which I'm attaching here as well.

However, upon giving this to someone to test on their machine, they immediately got an error after using `conda create --name myenv --file spec-file.txt`:
`ParseError: Could not parse explicit URL: https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.2.1-hd88cf55_4.conda`

I've noted that they are running Anaconda 2 while I created my file on Anaconda 3... could this be an issue? If not, do you see any room for improvements elsewhere?

Thank you so much for your time.

[YML.txt](https://github.com/conda/conda/files/3643136/YML.txt)
[spec-file.txt](https://github.com/conda/conda/files/3643118/spec-file.txt)

**Comment by kalefranz** [comment] 2019-09-23 22:51
> different operating systems

Explicit won’t work across what we would consider “different operating systems.” If instead your target is just different flavors of Linux, then yeah, you’re fine.

Also, this error indeed looks like a bug with parsing the `.conda` filenames. Probably related to all the old `Dist` stuff.

Until the bug is fixed, and for now while there’s still perfect parity, you should probably be able to work around the issue by manually (or with sed or something like that) changing the `.conda` extension to `.tar.bz2`.

**Comment by evanseitz** [comment] 2019-09-25 15:19
@kalefranz this strategy worked for my user; thank you so so much!

**Comment by soapy1** [comment] 2019-09-27 20:10
@evanseitz I'm trying to reproduce your issue but everything seems to work fine on the latest conda. What version of conda where you using when you ran into the error?

**Comment by evanseitz** [comment] 2019-09-30 14:59
@soapy1 I think both of my users (one on mac and one on linux) were using conda 2. Changing all `.conda` extensions to `.tar.bz2` fixed the error on both systems.

**Comment by evanseitz** [comment] 2019-09-30 14:59
I should note that I made unique files for mac and linux, not the same

**Comment by soapy1** [comment] 2019-09-30 19:47
could you provide the output of `conda info`

**Comment by evanseitz** [comment] 2019-09-30 20:01
Do you want that for the system that created the `explicit` files (which contained the .conda extensions) or for the system that couldn't use the `explicit` file?

For the linux user that got the error, his info is:
```
conda version = 4.6.14
conda build version =  3.15.1
python version = 2.7.15.final.0
```

**Comment by soapy1** [comment] 2019-09-30 20:15
Yup, I meant for the system that couldn't use the explicit file. Confirmed that this does not work with conda 4.6.14, since it's already fixed in the latest release of conda I'll close this issue.

**Closed by soapy1** 2019-09-30 20:15 UTC
