### ISSUE TITLE
Running py_compile on each file makes for really long install times for some packages

### ISSUE THREAD

**Issue by moorepants** [conda/conda#7778] opened 2018-09-18 03:51 UTC
**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request
  - [x] performance report

## Current Behavior

There are about 7000 python files in the plotly 3.2.1 package available on conda forge. Conda runs this py_compile command on each one:

```
DEBUG conda.gateways.subprocess:subprocess_call(46): executing>> "/home/moorepants/miniconda3/envs/skijumpdesign-dev-bin/bin/python3.6" -Wi -m py_compile "/home/moorepants/miniconda3/envs/skijumpdesign-dev-bin/lib/python3.6/site-packages/dash_html_components/version.py"
```

It took somewhere between 10 (real time) minutes to install the package on my laptop. This seems a bit excessive. It used to install quickly but there must have been a change in plotly or conda to slow this down.

```
moorepants@garuda:paper_row(master)$ time conda create -n plotly-install-test plotly
Solving environment: done

## Package Plan ##

  environment location: /home/moorepants/miniconda3/envs/plotly-install-test

  added / updated specs: 
    - plotly


The following NEW packages will be INSTALLED:

    asn1crypto:           0.24.0-py36_3         conda-forge
    bzip2:                1.0.6-h470a237_2      conda-forge
    ca-certificates:      2018.8.24-ha4d7672_0  conda-forge
    certifi:              2018.8.24-py36_1      conda-forge
    cffi:                 1.11.5-py36h5e8e0c9_1 conda-forge
    chardet:              3.0.4-py36_3          conda-forge
    cryptography:         2.3.1-py36hdffb7b8_0  conda-forge
    cryptography-vectors: 2.3.1-py36_0          conda-forge
    decorator:            4.3.0-py_0            conda-forge
    idna:                 2.7-py36_2            conda-forge
    ipython_genutils:     0.2.0-py_1            conda-forge
    jsonschema:           2.6.0-py36_2          conda-forge
    jupyter_core:         4.4.0-py_0            conda-forge
    libffi:               3.2.1-hfc679d8_5      conda-forge
    libgcc-ng:            7.2.0-hdf63c60_3      conda-forge
    libstdcxx-ng:         7.2.0-hdf63c60_3      conda-forge
    nbformat:             4.4.0-py_1            conda-forge
    ncurses:              6.1-hfc679d8_1        conda-forge
    openssl:              1.0.2p-h470a237_0     conda-forge
    pip:                  18.0-py36_1           conda-forge
    plotly:               3.2.1-py_0            conda-forge
    pycparser:            2.18-py_1             conda-forge
    pyopenssl:            18.0.0-py36_0         conda-forge
    pysocks:              1.6.8-py36_2          conda-forge
    python:               3.6.6-h5001a0f_0      conda-forge
    pytz:                 2018.5-py_0           conda-forge
    readline:             7.0-haf1bffa_1        conda-forge
    requests:             2.19.1-py36_1         conda-forge
    retrying:             1.3.3-py_2            conda-forge
    setuptools:           40.2.0-py36_0         conda-forge
    six:                  1.11.0-py36_1         conda-forge
    sqlite:               3.24.0-h2f33b56_1     conda-forge
    tk:                   8.6.8-ha92aebf_0      conda-forge
    traitlets:            4.3.2-py36_0          conda-forge
    urllib3:              1.23-py36_1           conda-forge
    wheel:                0.31.1-py36_1         conda-forge
    xz:                   5.2.4-h470a237_1      conda-forge
    zlib:                 1.2.11-h470a237_3     conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > source activate plotly-install-test
#
# To deactivate an active environment, use:
# > source deactivate
#


real	10m22.535s
user	6m51.235s
sys	3m21.938s
```

Reference issue on plotly feedstock https://github.com/conda-forge/plotly-feedstock/issues/44

### Steps to Reproduce

```
time conda create -c conda-forge -n plotly-install-test plotly

```

You can add the verbose flag to watch all the compilation happen.

## Expected Behavior

I think that plotly from conda-forge should install faster.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
moorepants@garuda:paper_row(master)$ conda info

     active environment : None
       user config file : /home/moorepants/.condarc
 populated config files : /home/moorepants/.condarc
          conda version : 4.5.11
    conda-build version : 3.11.0
         python version : 3.5.5.final.0
       base environment : /home/moorepants/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          http://repo.continuum.io/pkgs/free/linux-64
                          http://repo.continuum.io/pkgs/free/noarch
                          https://conda.anaconda.org/pydy/linux-64
                          https://conda.anaconda.org/pydy/noarch
                          https://conda.anaconda.org/moorepants/linux-64
                          https://conda.anaconda.org/moorepants/noarch
          package cache : /home/moorepants/miniconda3/pkgs
                          /home/moorepants/.conda/pkgs
       envs directories : /home/moorepants/miniconda3/envs
                          /home/moorepants/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.5.5 Linux/4.15.0-34-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/moorepants/.netrc
           offline mode : False


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
moorepants@garuda:paper_row(master)$ conda config --show-sources
==> /home/moorepants/.condarc <==
conda-build:
  root-dir: /tmp/conda-builds
channels:
  - conda-forge
  - http://repo.continuum.io/pkgs/free
  - pydy
  - moorepants
ssl_verify: True
always_yes: True

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
moorepants@garuda:paper_row(master)$ conda list --show-channel-urls
# packages in environment at /home/moorepants/miniconda3:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.4.0                    py35_1    defaults
alabaster                 0.7.11                     py_3    conda-forge
altair                    2.2.2                    py35_1    conda-forge
ampl-mp                   3.1.0                h26a2512_1    conda-forge
anaconda-client           1.7.1                      py_0    conda-forge
anaconda-navigator        1.6.4                    py35_0    defaults
anaconda-project          0.8.2                      py_1    conda-forge
antlr-python-runtime      4.7.1                    py35_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
apptools                  4.4.0                    py35_2    conda-forge
argcomplete               1.9.4                    py35_0    conda-forge
args                      0.1.0                    py35_0    conda-forge
asn1crypto                0.24.0                   py35_3    conda-forge
astroid                   2.0.2                    py35_0    conda-forge
asttokens                 1.1.11                     py_0    conda-forge
asv                       0.3              py35hfc679d8_0    conda-forge
atomicwrites              1.1.5                    py35_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
automat                   0.7.0                      py_1    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
beautifulsoup4            4.6.3                    py35_0    conda-forge
bicycleparameters         1.0.0                      py_1    conda-forge
bkcharts                  0.2                      py35_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.4                      py_1    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.14.4               hfc679d8_0    conda-forge
bokeh                     0.13.0                   py35_0    conda-forge
bqplot                    0.11.1                   py35_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
cairo                     1.14.12              he56eebe_3    conda-forge
certifi                   2018.8.24                py35_1    conda-forge
cffi                      1.11.5           py35h5e8e0c9_1    conda-forge
chardet                   3.0.4                    py35_3    conda-forge
chest                     0.2.3                    py35_0    conda-forge
chrpath                   0.16                 h470a237_1    conda-forge
click                     6.7                        py_1    conda-forge
clint                     0.5.1                      py_1    conda-forge
cloog                     0.18.0                        0    defaults
cloudpickle               0.5.6                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.3.9                      py_1    conda-forge
conda                     4.5.11                   py35_0    conda-forge
conda-build               3.11.0                   py35_0    conda-forge
conda-build-all           1.1.3                      py_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-forge-pinning       2018.09.17                    0    conda-forge
conda-manager             0.4.0                    py35_0    defaults
conda-smithy              3.1.12                     py_0    conda-forge
conda-verify              2.0.0                    py35_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
coverage                  4.5.1            py35h470a237_1    conda-forge
cryptography              2.3.1            py35hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                    py35_0    conda-forge
curl                      7.61.0               h93b3f91_2    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cyipopt                   0.1.7            py35h7eb728f_2    conda-forge
cython                    0.28.5           py35hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py35h470a237_0    conda-forge
dash                      0.26.5                     py_0    conda-forge
dash-core-components      0.28.3                     py_0    conda-forge
dash-html-components      0.12.0                     py_0    conda-forge
dash-renderer             0.13.2                     py_0    conda-forge
dask                      0.19.2                     py_0    conda-forge
dask-core                 0.19.2                     py_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
depfinder                 2.1.1                      py_0    conda-forge
dill                      0.2.8.2                  py35_0    conda-forge
distributed               1.23.2                   py35_0    conda-forge
doctr                     1.7.3                    py35_0    conda-forge
docutils                  0.14                     py35_1    conda-forge
dynamicisttoolkit         0.5.3                      py_1    conda-forge
entrypoints               0.2.3                    py35_2    conda-forge
envisage                  4.7.0                      py_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fastcache                 1.0.2            py35h470a237_1    conda-forge
feedgenerator             1.9                        py_1    conda-forge
filelock                  3.0.4                      py_1    conda-forge
filterpy                  1.4.4                      py_0    conda-forge
flake8                    3.5.0                    py35_0    conda-forge
flake8-import-order       0.18                       py_0    conda-forge
flake8-polyfill           1.0.2                      py_0    conda-forge
flask                     1.0.2                      py_1    conda-forge
flask-compress            1.4.0                      py_0    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freeglut                  3.0.0                hfc679d8_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
future                    0.16.0                   py35_2    conda-forge
gcc                       4.8.5                         7    defaults
get_terminal_size         1.0.0                    py35_0    defaults
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
ghp-import                0.5.5                      py_1    conda-forge
gitdb                     0.6.4                    py35_2    conda-forge
gitdb2                    2.0.4                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gmpy2                     2.0.8                    py35_1    conda-forge
graphite2                 1.3.12               hfc679d8_1    conda-forge
graphviz                  2.38.0                        7    conda-forge
gsl                       2.4             blas_openblash47a8a8e_1  [blas_openblas]  conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
harfbuzz                  1.8.5                h2bb21d5_0    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.1                        2    conda-forge
heapdict                  1.0.0                    py35_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py35_2    conda-forge
imageio                   2.3.0                      py_1    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
incremental               17.5.0                     py_0    conda-forge
invoke                    1.2.0                    py35_0    conda-forge
ipopt                     3.12.11         blas_openblash1727795_0  [blas_openblas]  conda-forge
ipydatawidgets            3.2.0                      py_0    conda-forge
ipykernel                 4.9.0                    py35_0    conda-forge
ipympl                    0.2.1                    py35_0    conda-forge
ipyscales                 0.2.2                      py_0    conda-forge
ipython                   6.5.0                    py35_0    conda-forge
ipython-notebook          4.0.4                    py35_0    defaults
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isl                       0.12.2                        0    defaults
isort                     4.3.4                    py35_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jbig                      2.1               h470a237_1001    conda-forge
jedi                      0.12.1                   py35_0    conda-forge
jeepney                   0.3.1                      py_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsoncpp                   1.8.4                h2d50403_0    conda-forge
jsonschema                2.6.0                    py35_2    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py35_1    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                    py35_0    conda-forge
jupyter_latex_envs        1.4.4                    py35_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py35_0    conda-forge
jupyterlab                0.34.10                  py35_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
keyring                   13.2.1                   py35_0    conda-forge
kiwisolver                1.0.1            py35h2d50403_2    conda-forge
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1            py35h470a237_0    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libglu                    9.0.0                         0    conda-forge
libgpuarray               0.7.6                h470a237_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libnetcdf                 4.6.1                         2    conda-forge
libogg                    1.3.2                h470a237_1    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtheora                 1.1.1                h470a237_1    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libtool                   2.4.6                h470a237_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libvorbis                 1.3.5                         0    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h88dbc4e_2    conda-forge
llvm                      3.3                           0    defaults
llvmlite                  0.23.0                   py35_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.5            py35hc9114bc_0    conda-forge
lz4-c                     1.8.3                hfc679d8_0    conda-forge
lzo                       2.10                          0    conda-forge
mako                      1.0.7                      py_1    conda-forge
markupsafe                1.0              py35h470a237_1    conda-forge
mathjax                   2.2                      py35_0    defaults
matplotlib                2.2.2                    py35_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mesa                      10.5.4                        0    defaults
metakernel                0.20.14                    py_0    conda-forge
metis                     5.1.0                h470a237_3    conda-forge
mistune                   0.8.3            py35h470a237_2    conda-forge
mkl                       2017.0.3                      0    defaults
mkl-service               1.1.2                    py35_3    defaults
mock                      2.0.0                    py35_0    conda-forge
more-itertools            4.3.0                    py35_0    conda-forge
mpc                       1.1.0                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                h26a2512_4    conda-forge
mpld3                     0.3                        py_1    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.5.6            py35h2d50403_2    conda-forge
mumps                     5.0.2           blas_openblash613969f_210  [blas_openblas]  conda-forge
nb_anacondacloud          1.4.0                    py35_0    conda-forge
nb_conda                  2.2.1                    py35_0    conda-forge
nb_conda_kernels          2.1.1                    py35_1    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbdime                    1.0.2                    py35_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nbpresent                 3.0.2                    py35_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
networkx                  2.1                        py_1    conda-forge
nose                      1.3.7                    py35_2    conda-forge
notebook                  5.6.0                    py35_1    conda-forge
numba                     0.38.1                   py35_0    conda-forge
numexpr                   2.6.6                    py35_0    conda-forge
numpy                     1.15.1          py35_blas_openblashd3ea46f_1  [blas_openblas]  conda-forge
numpydoc                  0.8.0                      py_1    conda-forge
oct2py                    4.0.6                      py_1    conda-forge
octave_kernel             0.28.4                     py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.4           py35hf8a1672_0    conda-forge
pandoc                    2.2.2                         1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              h9105a7a_2    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.8                      py_1    conda-forge
patchelf                  0.9                  hfc679d8_2    conda-forge
path.py                   11.0.1                     py_0    conda-forge
pathlib2                  2.3.2                    py35_0    conda-forge
patsy                     0.5.0                      py_1    conda-forge
pbr                       4.2.0                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pelican                   3.7.1                      py_1    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pep8-naming               0.7.0                      py_0    conda-forge
pexpect                   4.6.0                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
pillow                    5.2.0            py35h2dc6135_1    conda-forge
pint                      0.8.1                      py_1    conda-forge
pip                       18.0                     py35_1    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
plotly                    3.2.1                      py_0    conda-forge
pluggy                    0.7.1                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
proj4                     5.2.0                h470a237_0    conda-forge
prometheus_client         0.3.1                      py_1    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
psutil                    5.4.7            py35h470a237_1    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptscotch                  6.0.5                ha5050ec_0    conda-forge
ptyprocess                0.6.0                    py35_0    conda-forge
py                        1.6.0                      py_0    conda-forge
pyasn1                    0.4.4                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycodestyle               2.3.1                      py_1    conda-forge
pycosat                   0.6.3            py35h470a237_1    conda-forge
pycparser                 2.18                       py_1    conda-forge
pycrypto                  2.6.1                    py35_1    conda-forge
pydy                      0.4.0                    py35_0    conda-forge
pyface                    6.0.0                      py_1    conda-forge
pyflakes                  1.6.0                      py_1    conda-forge
pygithub                  1.39                     py35_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pygpu                     0.7.6            py35h7eb728f_0    conda-forge
pygraphviz                1.4rc1           py35h470a237_0    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyinstrument              0.13.1                    <pip>
pyinstrument              2.2.1                      py_0    conda-forge
pyinstrument_cext         0.2.0            py35h470a237_0    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pylint                    2.1.1                    py35_0    conda-forge
pyopenssl                 18.0.0                   py35_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyproj                    1.9.5.1                  py35_0    conda-forge
pyqt                      5.6.0            py35h8210e8a_7    conda-forge
pyserial                  3.4                      py35_0    conda-forge
pysocks                   1.6.8                    py35_2    conda-forge
pytables                  3.4.4                    py35_8    conda-forge
pytest                    3.8.0                    py35_0    conda-forge
python                    3.5.5                h5001a0f_2    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python-symengine          0.3.0            py35h1c59948_2    conda-forge
pythreejs                 1.1.0                    py35_3    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywavelets                1.0.0            py35h7eb728f_0    conda-forge
pyyaml                    3.13             py35h470a237_1    conda-forge
pyzmq                     17.1.2           py35hae99301_0    conda-forge
qt                        5.6.2                h50c60fd_8    conda-forge
qtawesome                 0.4.4              pyh8a2030e_1    conda-forge
qtconsole                 4.4.1                    py35_1    conda-forge
qtpy                      1.5.0              pyh8a2030e_0    conda-forge
quantities                0.12.2             pyh24bf2e0_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.19.1                   py35_1    conda-forge
requests-toolbelt         0.8.0                      py_1    conda-forge
resonance                 0.19.1                   py35_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rope                      0.10.7                     py_1    conda-forge
ruamel.yaml               0.15.66          py35h470a237_0    conda-forge
ruamel_yaml               0.15.63          py35h470a237_0    conda-forge
ruby                      2.4.4                h0825b16_1    conda-forge
scalapack                 2.0.2                h186ce0b_3    conda-forge
scikit-image              0.14.0           py35hfc679d8_1    conda-forge
scikit-learn              0.19.2          py35_blas_openblasha84fab4_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py35_blas_openblash7943236_201  [blas_openblas]  conda-forge
scotch                    6.0.5                h9c0d707_1    conda-forge
seaborn                   0.9.0                      py_0    conda-forge
secretstorage             3.1.0                    py35_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setproctitle              1.1.10           py35h470a237_1    conda-forge
setuptools                40.2.0                   py35_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1           py35hfc679d8_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
skijumpdesign             1.3.0                      py_0    conda-forge
slycot                    0.3.3           py35_blas_openblash8cac196_0  [blas_openblas]  conda-forge
smmap                     0.9.0                      py_2    conda-forge
smmap2                    2.0.4                      py_0    conda-forge
snakeviz                  0.4.1                    py35_0    defaults
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcontainers          2.0.4                      py_1    conda-forge
sphinx                    1.8.0                    py35_0    conda-forge
sphinx-issues             1.0.0                      py_0    conda-forge
sphinx_rtd_theme          0.4.1                      py_0    conda-forge
sphinxcontrib             1.0                      py35_0    defaults
sphinxcontrib-autoprogram 0.1.5                      py_1    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.2.8                    py35_0    conda-forge
spyder-kernels            1.1.0                      py_0    conda-forge
spyder-notebook           0.1.3                      py_1    conda-forge
sqlite                    3.24.0               h2f33b56_1    conda-forge
statsmodels               0.9.0                    py35_0    conda-forge
stdlib-list               0.4.0                    py35_0    conda-forge
symengine                 0.3.0                         1    conda-forge
sympy                     1.3                      py35_0    conda-forge
system                    5.8                           2    defaults
tbb                       2018_20171205                 0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                    py35_1    conda-forge
testpath                  0.3.1                    py35_1    conda-forge
theano                    1.0.2                    py35_0    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.1.1            py35h470a237_0    conda-forge
tqdm                      4.26.0                     py_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
traits                    4.6.0            py35h470a237_2    conda-forge
traitsui                  6.0.0                      py_1    conda-forge
traittypes                0.2.1                      py_1    conda-forge
twine                     1.11.0                     py_1    conda-forge
twisted                   18.7.0           py35h470a237_1    conda-forge
typed-ast                 1.1.0                    py35_0    conda-forge
typing                    3.6.6                    py35_0    conda-forge
uncertainties             3.0.2                    py35_1    conda-forge
unidecode                 1.0.22                     py_1    conda-forge
urllib3                   1.23                     py35_1    conda-forge
vega                      2.0.0                    py35_0    conda-forge
vtk                       8.1.0           py35h3f2a929_203    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.1                   py35_1    conda-forge
widgetsnbextension        3.4.2                    py35_0    conda-forge
wrapt                     1.10.11                  py35_0    conda-forge
wxpython                  4.0.3            py35h15c1503_0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xonsh                     0.7.8                    py35_0    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.2                h8c8a85c_6    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
yeadon                    1.3.0                    py35_1    conda-forge
youtube-dl                2016.10.26                <pip>
zeromq                    4.2.5                hfc679d8_5    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope                      1.0                      py35_0    defaults
zope.interface            4.5.0            py35h470a237_1    conda-forge
```
</p></details>

**Comment by moorepants** [comment] 2018-09-18 03:58
As a comparison, even with download times, pip is much faster (35s):

```
moorepants@garuda:paper_row(master)$ act plotly-pip
(plotly-pip) moorepants@garuda:paper_row(master)$ time pip install plotly
Collecting plotly
  Downloading https://files.pythonhosted.org/packages/25/e6/716d30f51604daedaf12b1064e1d1e48d1c0a224ac41a83496b39862124d/plotly-3.2.1-py2.py3-none-any.whl (37.0MB)
    100% |████████████████████████████████| 37.0MB 472kB/s 
Collecting requests (from plotly)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 1.9MB/s 
Collecting decorator>=4.0.6 (from plotly)
  Downloading https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting six (from plotly)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pytz (from plotly)
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 2.3MB/s 
Collecting retrying>=1.3.3 (from plotly)
  Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
Collecting nbformat>=4.2 (from plotly)
  Downloading https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl (155kB)
    100% |████████████████████████████████| 163kB 2.2MB/s 
Requirement already satisfied: certifi>=2017.4.17 in /home/moorepants/miniconda3/envs/plotly-pip/lib/python3.6/site-packages (from requests->plotly) (2018.8.24)
Collecting urllib3<1.24,>=1.21.1 (from requests->plotly)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.6MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->plotly)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.3MB/s 
Collecting idna<2.8,>=2.5 (from requests->plotly)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 2.9MB/s 
Collecting jupyter-core (from nbformat>=4.2->plotly)
  Downloading https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 2.2MB/s 
Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2->plotly)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting traitlets>=4.1 (from nbformat>=4.2->plotly)
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 2.6MB/s 
Collecting ipython-genutils (from nbformat>=4.2->plotly)
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Building wheels for collected packages: retrying
  Running setup.py bdist_wheel for retrying ... done
  Stored in directory: /home/moorepants/.cache/pip/wheels/d7/a9/33/acc7b709e2a35caa7d4cae442f6fe6fbf2c43f80823d46460c
Successfully built retrying
Installing collected packages: urllib3, chardet, idna, requests, decorator, six, pytz, retrying, ipython-genutils, traitlets, jupyter-core, jsonschema, nbformat, plotly
Successfully installed chardet-3.0.4 decorator-4.3.0 idna-2.7 ipython-genutils-0.2.0 jsonschema-2.6.0 jupyter-core-4.4.0 nbformat-4.4.0 plotly-3.2.1 pytz-2018.5 requests-2.19.1 retrying-1.3.3 six-1.11.0 traitlets-4.3.2 urllib3-1.23

real	0m35.381s
user	0m12.835s
sys	0m4.623s
```

**Comment by kalefranz** [comment] 2018-09-19 03:31
Duplicate of https://github.com/conda/conda/issues/7621. Please direct comments and upvotes to that issue :)

**Closed by kalefranz** 2018-09-19 03:31 UTC
