### ISSUE TITLE
Should conda do some check when adding channels?

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#2884] opened 2016-06-27 18:19 UTC
When doing
`conda config --add channels asdakjalsdk`

It would be nice if **conda** warn the user that channel `https://<conda-api-url>/asdakjalsdk, does not exist, and ask if he wants to add it to the config still?

**Comment by kalefranz** [comment] 2017-05-10 20:56
duplicate of #4934

**Closed by kalefranz** 2017-05-10 20:56 UTC
Labels: type:feature
