### ISSUE TITLE
Encoding error with print() in display_actions()

### ISSUE THREAD

**Issue by rpratt20** [conda/conda#5938] opened 2017-09-08 01:27 UTC
[obspy1.0.2] C:\Anaconda>conda install basemap
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment C:\Anaconda\envs\obspy1.0.2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
[obspy1.0.2] C:\Anaconda>conda info
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_info.py", line 255, in exec
ute
    """ % info_dict)
LookupError: unknown encoding: cp65001
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 400, in instal
l
    plan.display_actions(actions, index)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 57, in display_action
s
    print_dists(disp_lst)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 42, in print_dists
    print(line)
LookupError: unknown encoding: cp65001

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 400, in instal
l
    plan.display_actions(actions, index)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 57, in display_action
s
    print_dists(disp_lst)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 42, in print_dists
    print(line)
LookupError: unknown encoding: cp65001

**Comment by goanpeca** [comment] 2018-06-05 21:28
Closing as duplicate of https://github.com/conda/conda/issues/5448

**Closed by goanpeca** 2018-06-05 21:28 UTC
Labels: easy, good_first_issue, s-3, source-community, type-bug
