### ISSUE TITLE
Cannot do updates in conda

### ISSUE THREAD

**Issue by OrbitalMechanic** [conda/conda#9087] opened 2019-08-11 08:37 UTC
I'm running the Anaconda distribution for Python 3.7.3 on an iMacPro under Mac OS X version 10.14.6. All of sudden I find that I can no update conda as dispected in the attached file. The problem appears to caused by dlopen(/Users/user/anaconda3/bin/../lib/libarchive.dylib, 6) cannot find -libiconv:

OSError: dlopen(/Users/user/anaconda3/bin/../lib/libarchive.dylib, 6): Symbol not found: _libiconv
      Referenced from: /Users/user/anaconda3/bin/../lib/libarchive.dylib
      Expected in: /usr/lib/libiconv.2.dylib
     in /Users/user/anaconda3/bin/../lib/libarchive.dylib

Besides doing a clean install of my Python setup, how can I fix this?

Please advise.
[cant-update-conda.txt](https://github.com/conda/conda-build/files/3489708/cant-update-conda.txt)

**Comment by msarahan** [comment] 2019-08-12 12:49
Duplicate of #8867

**Closed by msarahan** 2019-08-12 12:49 UTC
