### ISSUE TITLE
open conda prompt in window10

### ISSUE THREAD

**Issue by sharh** [conda/conda#5805] opened 2017-08-12 04:56 UTC
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "D:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "D:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "D:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "D:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "D:\ProgramData\Anaconda2\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "D:\ProgramData\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "D:\ProgramData\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "D:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "D:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "D:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "D:\ProgramData\Anaconda2\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "D:\ProgramData\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 1: ordinal not in range(128)

**Comment by mingwandroid** [comment] 2017-08-12 12:53
This is a duplicate of https://github.com/conda/conda/issues/5788

Please follow the investigative steps I outlined there and close this issue if it fixes it for you.

The tl;dr is you cannot use Python2 a Windows system if `PATH` contains *any* characters that fall outside of the ASCII codeset.

**Comment by MigoJ** [comment] 2017-08-30 14:12
Hello ,could you helpy me the same issue, this is follow your instruction,but cannot find root cause

**Comment by MigoJ** [comment] 2017-08-30 14:12
C:\Users\a56c>path
PATH=C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Calibre2\;D:\软件\Scripts\;D:\软件\

C:\Users\a56c>echo %PATH%
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;

reopen conda results as below:

D:\Anacoda2\Library\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Calibre2\
D:\软件\Scripts\
D:\软件\
D:\Anacoda2\Library\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Calibre2\
D:\软件\Scripts\
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

**Comment by mingwandroid** [comment] 2017-08-30 14:25
You cannot have any entires in your PATH with non-ascii. You have several starting with "D:\软件" they must all be removed.

**Closed** 2017-10-10 21:41 UTC
Labels: source:community, type:support
