### ISSUE TITLE
Conda init tcsh does install the right script

### ISSUE THREAD

**Issue by petrosb** [conda/conda#8584] opened 2019-04-22 17:34 UTC
## Current Behavior

When I type conda init tcsh (or conda init --all) conda mentions it updates my .tcshrc file. However, when I open a tcsh shell, I get an "Illegal variable name" error, and the path is not updated. I believe the issue is that the .tcshrc created is not actually tcsh compatible. For example, it includes a redirect to /dev/null/ of the form "2>" which might not be an acceptable tcsh command (see here, https://unix.stackexchange.com/questions/197878/inconsistency-of-stderr-redirection-between-tcsh-and-other-shells/197880). Also uses the $(...) syntax, which also seems to be an illegal tcsh command (see here, https://stackoverflow.com/questions/43725152/illegal-variable-name-tcsh-shell-linux). Also see below for a dump of the .tcshrc that is created. Another explanation is that for some reason the command installs an incorrect .tcshrc, intended for some other shell.
Current solution is to delete the .tcshrc, but then "conda activate base" does not work.

### Steps to Reproduce

```
On a Mac:

>>conda init tcsh
no change     /Users/petrosb/anaconda3/condabin/conda
no change     /Users/petrosb/anaconda3/bin/conda
no change     /Users/petrosb/anaconda3/bin/conda-env
no change     /Users/petrosb/anaconda3/bin/activate
no change     /Users/petrosb/anaconda3/bin/deactivate
no change     /Users/petrosb/anaconda3/etc/profile.d/conda.sh
no change     /Users/petrosb/anaconda3/etc/fish/conf.d/conda.fish
no change     /Users/petrosb/anaconda3/shell/condabin/Conda.psm1
no change     /Users/petrosb/anaconda3/shell/condabin/conda-hook.ps1
no change     /Users/petrosb/anaconda3/lib/python3.6/site-packages/xonsh/conda.xsh
no change     /Users/petrosb/anaconda3/etc/profile.d/conda.csh
modified      /Users/petrosb/.tcshrc

==> For changes to take effect, close and re-open your current shell. <==

>> reopening a new shell:
Last login: Mon Apr 22 12:42:13 on ttys005
Illegal variable name.
[ap8w39:~] petrosb% which conda
conda: Command not found.
[ap8w39:~] petrosb% which python
/usr/local/bin/python
[ap8w39:~] petrosb% more .tcshrc                                                
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/petrosb/anaconda3/bin/conda' 'shell.tcsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/petrosb/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/petrosb/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/petrosb/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

[ap8w39:~] petrosb% __conda_setup="$('/Users/petrosb/anaconda3/bin/conda' 'shell.tcsh' 'hook' 2> /dev/null)"
Illegal variable name.

```

## Expected Behavior

Have the new shell open without an error and have anaconda in the path, so I can run conda activate, python, etc. there.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /Users/petrosb/.condarc
 populated config files : /Users/petrosb/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : /Users/petrosb/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/petrosb/anaconda3/pkgs
                          /Users/petrosb/.conda/pkgs
       envs directories : /Users/petrosb/anaconda3/envs
                          /Users/petrosb/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 1585:500
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/petrosb/.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/petrosb/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0    defaults
alabaster                 0.7.12                   py36_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-navigator        1.9.6                    py36_0    defaults
anaconda-project          0.8.2                    py36_0    defaults
appdirs                   1.4.3            py36h28b3542_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.1.0            py36h1de35cc_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   2.2.5                    py36_0    defaults
astropy                   3.1.2            py36h1de35cc_0    defaults
atomicwrites              1.3.0                    py36_1    defaults
attrs                     19.1.0                   py36_1    defaults
automat                   0.7.0                    py36_0    defaults
autopep8                  1.4.3                    py36_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                      py36_1    defaults
backports.os              0.1.1                    py36_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
beautifulsoup4            4.7.1                    py36_1    defaults
bitarray                  0.8.3            py36h1de35cc_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
black                     19.3b0                     py_0    conda-forge
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py36_0    defaults
bleach                    3.1.0                    py36_0    defaults
blosc                     1.15.0               hd9629dc_0    defaults
bokeh                     1.0.4                    py36_0    defaults
boost                     1.67.0                   py36_4    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py36h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py36_0    defaults
cffi                      1.12.2           py36hb5b8e2f_1    defaults
chardet                   3.0.4                    py36_1    defaults
click                     7.0                      py36_0    defaults
cloudpickle               0.8.0                    py36_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.4.1                    py36_0    defaults
conda                     4.6.14                   py36_0    defaults
conda-build               3.17.8                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
constantly                15.1.0           py36h28b3542_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.6.1            py36ha12b0ac_0    defaults
curl                      7.64.0               ha441bb4_2    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.29.6           py36h0a44026_0    defaults
cytoolz                   0.9.0.1          py36h1de35cc_1    defaults
dask                      1.1.4                    py36_1    defaults
dask-core                 1.1.4                    py36_1    defaults
datashape                 0.5.4                    py36_1    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py36_1    defaults
defusedxml                0.5.0                    py36_1    defaults
distributed               1.26.0                   py36_1    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.3                      py36_0    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py36h1de35cc_2    defaults
filelock                  3.0.10                   py36_0    defaults
flake8                    3.7.7                    py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.7                    py36_0    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.4.0            py36h1de35cc_0    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py36_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36h6ef4df4_2    defaults
greenlet                  0.4.15           py36h1de35cc_0    defaults
h5py                      2.9.0            py36h3134771_0    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1                    py36_0    defaults
hyperlink                 18.0.0                   py36_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py36_0    defaults
imageio                   2.5.0                    py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
importlib_metadata        0.8                      py36_0    defaults
incremental               17.5.0                   py36_0    defaults
intel-openmp              2019.3                      199    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   7.4.0            py36h39e3cac_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.4.2                    py36_0    defaults
isort                     4.3.16                   py36_0    defaults
itsdangerous              1.1.0                    py36_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.13.3                   py36_0    defaults
jinja2                    2.10                     py36_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                3.0.1                    py36_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.2.4                    py36_0    defaults
jupyter_console           6.0.0                    py36_0    defaults
jupyter_core              4.4.0                    py36_0    defaults
jupyterlab                0.35.4           py36hf63ae98_0    defaults
jupyterlab_launcher       0.13.1                   py36_0    defaults
jupyterlab_server         0.2.0                    py36_0    defaults
keyring                   18.0.0                   py36_0    defaults
kiwisolver                1.0.1            py36h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py36h1de35cc_2    defaults
libarchive                3.3.3                h786848e_5    defaults
libboost                  1.67.0               hebc422b_4    defaults
libcurl                   7.64.0               h051b688_2    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_2    defaults
libpng                    1.6.36               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.10               hcb84e12_2    defaults
libxml2                   2.9.9                hab757c2_0    defaults
libxslt                   1.1.33               h33a18ac_0    defaults
llvmlite                  0.28.0           py36h8c7ce04_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.3.2            py36hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.1.1            py36h1de35cc_0    defaults
matplotlib                3.0.3            py36h54f8f79_0    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.4            py36h1de35cc_0    defaults
mkl                       2019.3                      199    defaults
mkl-service               1.1.2            py36hfbe908c_5    defaults
mkl_fft                   1.0.10           py36h5e564d8_0    defaults
mkl_random                1.0.2            py36h27c97d8_0    defaults
more-itertools            6.0.0                    py36_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py36_0    defaults
msgpack-python            0.6.1            py36h04f5b5a_1    defaults
multipledispatch          0.6.0                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.4.1                    py36_3    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
networkx                  2.2                      py36_1    defaults
nltk                      3.4                      py36_1    defaults
nose                      1.3.7                    py36_2    defaults
notebook                  5.7.8                    py36_0    defaults
numba                     0.43.1           py36h6440ff4_0    defaults
numexpr                   2.6.9            py36h7413580_0    defaults
numpy                     1.16.2           py36hacdab7b_0    defaults
numpy-base                1.16.2           py36h6575580_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.46                     py36_0    defaults
openpyxl                  2.6.1                    py36_1    defaults
openssl                   1.1.1b               h1de35cc_1    defaults
packaging                 19.0                     py36_0    defaults
pandas                    0.24.2           py36h0a44026_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
parso                     0.3.4                    py36_0    defaults
partd                     0.3.10                   py36_1    defaults
path.py                   11.5.0                   py36_0    defaults
pathlib2                  2.3.3                    py36_0    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.6.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    5.4.1            py36hb68e598_0    defaults
pip                       19.0.3                   py36_0    defaults
pkginfo                   1.5.0.1                  py36_0    defaults
pluggy                    0.9.0                    py36_0    defaults
ply                       3.11                     py36_0    defaults
prometheus_client         0.6.0                    py36_0    defaults
prompt_toolkit            2.0.9                    py36_0    defaults
psutil                    5.6.1            py36h1de35cc_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
py                        1.8.0                    py36_0    defaults
py-boost                  1.67.0           py36h6440ff4_4    defaults
py-lief                   0.9.0            py36h1413db1_2    defaults
pyasn1                    0.4.5                      py_0    defaults
pyasn1-modules            0.2.4                    py36_0    defaults
pycodestyle               2.5.0                    py36_0    defaults
pycosat                   0.6.3            py36h1de35cc_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36h1de35cc_9    defaults
pycurl                    7.43.0.2         py36ha12b0ac_0    defaults
pyflakes                  2.1.1                    py36_0    defaults
pygments                  2.3.1                    py36_0    defaults
pylint                    2.3.1                    py36_0    defaults
pyodbc                    4.0.26           py36h0a44026_0    defaults
pyopenssl                 19.0.0                   py36_0    defaults
pyparsing                 2.3.1                    py36_0    defaults
pyqt                      5.9.2            py36h655552a_2    defaults
pyrsistent                0.14.11          py36h1de35cc_0    defaults
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.5.1            py36h5bccee9_0    defaults
pytest                    4.3.1                    py36_0    defaults
pytest-arraydiff          0.3              py36h39e3cac_0    defaults
pytest-astropy            0.5.0                    py36_0    defaults
pytest-doctestplus        0.3.0                    py36_0    defaults
pytest-openfiles          0.3.2                    py36_0    defaults
pytest-remotedata         0.3.1                    py36_0    defaults
python                    3.6.8                haf84260_0    defaults
python-dateutil           2.8.0                    py36_0    defaults
python-libarchive-c       2.8                      py36_6    defaults
python.app                2                        py36_9    defaults
pytz                      2018.9                   py36_0    defaults
pywavelets                1.0.2            py36h1d22016_0    defaults
pyyaml                    5.1              py36h1de35cc_0    defaults
pyzmq                     18.0.0           py36h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.7                    py36_1    defaults
qtconsole                 4.4.3                    py36_0    defaults
qtpy                      1.7.0                    py36_1    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                   py36_0    defaults
rope                      0.12.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36h1de35cc_0    defaults
scikit-image              0.14.2           py36h0a44026_0    defaults
scikit-learn              0.20.3           py36h27c97d8_0    defaults
scipy                     1.2.1            py36h1410ff5_0    defaults
seaborn                   0.9.0                    py36_0    defaults
send2trash                1.5.0                    py36_0    defaults
service_identity          18.1.0           py36h28b3542_0    defaults
setuptools                40.8.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.19.8           py36h0a44026_0    defaults
six                       1.12.0                   py36_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         1.1.2                    py36_0    defaults
sortedcontainers          2.1.0                    py36_0    defaults
soupsieve                 1.8                      py36_0    defaults
sphinx                    1.8.5                    py36_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.3.3                    py36_0    defaults
spyder-kernels            0.4.2                    py36_0    defaults
sqlalchemy                1.3.1            py36h1de35cc_0    defaults
sqlite                    3.27.2               ha441bb4_0    defaults
statsmodels               0.9.0            py36h1d22016_0    defaults
sympy                     1.3                      py36_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.4.2                    py36_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toml                      0.10.0                     py_0    conda-forge
toolz                     0.9.0                    py36_0    defaults
tornado                   6.0.2            py36h1de35cc_0    defaults
tqdm                      4.31.1                   py36_1    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
twisted                   17.5.0                   py36_0    defaults
typed-ast                 1.3.1            py36h1de35cc_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.1                   py36_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.33.1                   py36_0    defaults
widgetsnbextension        3.4.2                    py36_0    defaults
wrapt                     1.11.1           py36h1de35cc_0    defaults
wurlitzer                 1.0.2                    py36_0    defaults
xlrd                      1.2.0                    py36_0    defaults
xlsxwriter                1.1.5                    py36_0    defaults
xlwings                   0.15.4                   py36_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
yapf                      0.26.0                   py36_0    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zict                      0.1.4                    py36_0    defaults
zipp                      0.3.3                    py36_1    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zope                      1.0                      py36_1    defaults
zope.interface            4.6.0            py36h1de35cc_0    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```
</p></details>

**Comment by soapy1** [comment] 2019-04-25 22:04
This is fixed in master. Will be in the next release of conda

**Comment by pmassey** [comment] 2019-06-02 22:39
I am having the identical problem even after a conda update conda.  I am wondering you could make the correct script available so i can fix my .tcshrc.

**Comment by robertlugg** [comment] 2019-06-11 00:37
Has anyone confirmed that the change in master works?  It does not seem to, but admittedly, I copy-and-pasted as best I could to try it out.  First, I would suggest converting from 'export' to 'setenv' as in:
`setenv PATH "%(conda_bin)s:$PATH"`

Also, it appears that you are referencing `"%(conda_prefix)s/etc/profile.d/conda.sh"` for csh and tcsh.  Shouldn't this be the csh version?

Finally, I can't see __conda_setup being set correctly.  Maybe I'm doing something incorrectly?  The only way I could do it is to source a temporary file:

    set temp_file="`mktemp`"
    ${conda_exe} shell.${user_shell} hook > ${temp_file}

**Comment by soapy1** [comment] 2019-06-17 15:16
@robertlugg @pmassey what versions of conda are you on?

**Comment by pmassey** [comment] 2019-06-17 15:21
conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0

**Comment by soapy1** [comment] 2019-06-17 15:30
The fix is not in 4.6.14, it's in 4.7.x. This is available in canary. You can install it by running `conda install -c conda-canary conda`. Note that canary releases might not be entirely stable

**Comment by pmassey** [comment] 2019-06-17 15:36
Thanks.

However, after I’ve installed it, and resourced .tcshrc, I still get the same error message if I try conda activate:

conda init tcsh
no change     /Users/massey/anaconda3/condabin/conda
no change     /Users/massey/anaconda3/bin/conda
no change     /Users/massey/anaconda3/bin/conda-env
no change     /Users/massey/anaconda3/bin/activate
no change     /Users/massey/anaconda3/bin/deactivate
no change     /Users/massey/anaconda3/etc/profile.d/conda.sh
no change     /Users/massey/anaconda3/etc/fish/conf.d/conda.fish
no change     /Users/massey/anaconda3/shell/condabin/Conda.psm1
no change     /Users/massey/anaconda3/shell/condabin/conda-hook.ps1
no change     /Users/massey/anaconda3/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /Users/massey/anaconda3/etc/profile.d/conda.csh
modified      /Users/massey/.tcshrc

==> For changes to take effect, close and re-open your current shell. <==

[thetardis:~] massey% source .tcshrc
[thetardis:~] massey% conda activate

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Here are the modifications that conda init tcsh made to my .tcshrc:

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
set __conda_setup="`/Users/massey/anaconda3/bin/conda shell.tcsh hook >& /dev/null`"
if ( $? == 0 ) then
    eval "$__conda_setup"
else
    if ( -f "/Users/massey/anaconda3/etc/profile.d/conda.sh" ) then
        . "/Users/massey/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/massey/anaconda3/bin:$PATH"
    endif
endif
unset __conda_setup
# <<< conda initialize <<<

**Comment by soapy1** [comment] 2019-06-17 19:59
Right, I think I have a fix for this. Please see https://github.com/conda/conda/pull/8792

**Comment by soapy1** [comment] 2019-06-19 22:12
New conda has been released, looks like it works as intended now

```
[0311:~] scastellarin% conda info

     active environment : base
    active env location : /Users/scastellarin/miniconda3
            shell level : 1
       user config file : /Users/scastellarin/.condarc
 populated config files : /Users/scastellarin/.condarc
          conda version : 4.7.4
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       virtual packages :
       base environment : /Users/scastellarin/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/scastellarin/miniconda3/pkgs
                          /Users/scastellarin/.conda/pkgs
       envs directories : /Users/scastellarin/miniconda3/envs
                          /Users/scastellarin/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.4 requests/2.22.0 CPython/3.7.2 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False

[0311:~] scastellarin% conda init tcsh
no change     /Users/scastellarin/miniconda3/condabin/conda
no change     /Users/scastellarin/miniconda3/bin/conda
no change     /Users/scastellarin/miniconda3/bin/conda-env
no change     /Users/scastellarin/miniconda3/bin/activate
no change     /Users/scastellarin/miniconda3/bin/deactivate
no change     /Users/scastellarin/miniconda3/etc/profile.d/conda.sh
no change     /Users/scastellarin/miniconda3/etc/fish/conf.d/conda.fish
no change     /Users/scastellarin/miniconda3/shell/condabin/Conda.psm1
no change     /Users/scastellarin/miniconda3/shell/condabin/conda-hook.ps1
no change     /Users/scastellarin/miniconda3/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /Users/scastellarin/miniconda3/etc/profile.d/conda.csh
modified      /Users/scastellarin/.tcshrc

==> For changes to take effect, close and re-open your current shell. <==

[0311:~] scastellarin% source ~/.tcshrc
[0311:~] scastellarin% conda activate
(base) [0311:~] scastellarin%
```

**Closed by soapy1** 2019-06-19 22:12 UTC

**Comment by pmassey** [comment] 2019-06-20 00:48
Works for me too!  Thanks very much!
