### ISSUE TITLE
Install fails with meaningless error when AWS S3 is down

### ISSUE THREAD

**Issue by moble** [conda/conda#4765] opened 2017-02-28 18:47 UTC
I'm trying to install [a package of my own](https://github.com/moble/quaternion).  I've successfully installed this package previously on numerous systems, including several flavors of linux (some times on VMs) and OS X, as have numerous other users of this package.  I'm trying to install it on one system right now that I *successfully installed on* three days ago.  In both cases, I created an entirely new anaconda installation, being careful to get the `PATH` right, ran `conda update --all`, and then tried installing my package, with no intermediate steps.  I don't think anything has changed about the system.  I'm avoiding python3 for the moment because the update to 3.6 opens up another can of worms.

How can I debug this error?

    > conda install -c moble quaternion
    Fetching package metadata ...........
    Solving package specifications: .

    Package plan for installation in environment /share/storage/moble/anaconda2:

    The following NEW packages will be INSTALLED:

        quaternion: 2017.01.08.dev232822920-py27_0 moble

    Proceed ([y]/n)? 

    An unexpected error has occurred.
    Please consider posting the following information to the
    conda GitHub issue tracker at:

        https://github.com/conda/conda/issues

    Current conda install:

                   platform : linux-64
              conda version : 4.3.13
           conda is private : False
          conda-env version : 4.3.13
        conda-build version : not installed
             python version : 2.7.13.final.0
           requests version : 2.13.0
           root environment : /share/storage/moble/anaconda2  (writable)
        default environment : /share/storage/moble/anaconda2
           envs directories : /share/storage/moble/anaconda2/envs
                              /home/moble/.conda/envs
              package cache : /share/storage/moble/anaconda2/pkgs
                              /home/moble/.conda/pkgs
               channel URLs : https://conda.anaconda.org/moble/linux-64
                              https://conda.anaconda.org/moble/noarch
                              https://repo.continuum.io/pkgs/free/linux-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/r/linux-64
                              https://repo.continuum.io/pkgs/r/noarch
                              https://repo.continuum.io/pkgs/pro/linux-64
                              https://repo.continuum.io/pkgs/pro/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.13 Linux/2.6.32-279.el6.x86_64 Red Hat Enterprise Linux Server/6.3 glibc/2.12
                    UID:GID : 524:527

    `$ /share/storage/moble/anaconda2/bin/conda install -c moble quaternion`

        Traceback (most recent call last):
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
            return_value = func(*args, **kwargs)
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
            exit_code = args.func(args, p)
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
            install(args, parser, 'install')
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
            execute_actions(actions, index, verbose=not context.quiet)
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
            execute_instructions(plan, index, verbose)
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
            cmd(state, arg)
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
            progressive_fetch_extract.execute()
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 474, in execute
            self._execute_action(action)
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 490, in _execute_action
            exceptions.append(CondaError(repr(e)))
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
            return '%s: %s\n' % (self.__class__.__name__, text_type(self))
          File "/share/storage/moble/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 46, in __str__
            return text_type(self.message % self._kwargs)
        TypeError: not enough arguments for format string

**Comment by bbakernoaa** [comment] 2017-02-28 19:04
this is the same I'm having in #4766

**Comment by nsoranzo** [comment] 2017-02-28 19:07
AWS S3 is down, which means that anaconda.conda.org is too.

**Comment by moble** [comment] 2017-02-28 19:09
Thanks for pointing that out @nsoranzo.  (I thought it was just me, because I've been having weird internet issues today, but maybe the ubiquity of S3 usage explains why!)  I guess we both just need to wait until it's back up.  But I would also suggest that `conda` needs to be able to deal with issues like this in a more sensible way, so I'll leave this issue open.

**Comment by kalefranz** [comment] 2017-02-28 19:18
The root cause is that Amazon S3 is down, and so anaconda.org is down (along with half the internet). This will be resolved when S3 is back online.

**Comment by dcsoft4** [comment] 2017-02-28 19:42
Still, the exception could be improved.  While doing a similar
 conda install -c kristvanneste jsonpickle

I got the same error
  TypeError: not enough arguments for format string

But when I then tried
  pip install -i https://pypi.anaconda.org/pypi/simple jsonpickle

  It at least returned an error starting with:

      Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003AF1278>, 'Connection to binstar-cio-packages-prod.s3.amazonaws.com timed out. (connect timeout=15)')'

**Comment by kalefranz** [comment] 2017-02-28 19:48
Yeah exception definitely has a problem that we're fixing :)

**Comment by kalefranz** [comment] 2017-02-28 20:02
There's actually a really helpful error message already there, if we didn't have that stack trace in forming it.  Would have saved me having to respond to a dozen or so github issues, so I feel the pain :)

**Comment by moble** [comment] 2017-02-28 20:07
@kalefranz "There's actually a really helpful error message already there, if we didn't have that stack trace in forming it."  Already where?  Even knowing what the problem is, I'm not seeing anything that would indicate a failure to get data from the internet.

**Comment by kalefranz** [comment] 2017-02-28 20:10
@moble That's because you're running conda with a python2 interpreter, and python2 doesn't chain stack traces.  [Here](https://github.com/conda/conda/issues/4764#issuecomment-283133253)'s what the stack trace looks like in python3.

**Comment by moble** [comment] 2017-02-28 20:31
@kalefranz  I appreciate the nice work you and the other `conda` folks do, but I just want to point out that I searched for the error before I opened this issue, and didn't find anything.  Now I realize that I only searched open issues, so it may have been a better idea to leave one of those older issues open until this actually was resolved one way or another.  Also, saying that it "will be resolved when S3 is back online" does not inspire confidence that `conda` will get better at detecting and explaining this or similar problems.  I only bring these points up because I'm constantly encouraging people to adopt `conda` as an excellent solution to all things python, and it makes things harder for me when they run into silly problems like these.  Thanks for your help.

**Comment by kalefranz** [comment] 2017-02-28 21:24
Sure that's all fair.  Especially closing the issue too soon.

There's been some fairly extensive error messages for HTTP errors for a while now.  Although most of the time we've always ran into problems with downloading repodata, and so that's where most of the error message work is focused.  Check this out:
https://github.com/conda/conda/blob/4.3.x/conda/core/repodata.py#L169-L296

We have a more limited error message for HTTP errors triggered when downloading packages.  It's still rather descriptive:
https://github.com/conda/conda/blob/4.3.x/conda/gateways/download.py#L120-L131
plus
https://github.com/conda/conda/blob/4.3.x/conda/exceptions.py#L323-L346

The ugly stack trace here was happening because the anaconda.org download url--actually an s3 bucket url--had `%` signs in it.  We needed to `unquote` the url, which is already fixed in the 4.3.x stable working branch.

**Comment by moble** [comment] 2017-02-28 22:40
Ah, tricky bug!  Thanks for the explanation.

**Comment by kalefranz** [comment] 2017-03-01 16:23
The failure to present a proper error message here should be fixed in https://github.com/conda/conda/pull/4769.

**Closed by kalefranz** 2017-03-01 16:23 UTC

**Comment by moble** [comment] 2017-03-01 16:46
Thanks!

**Comment by cdeil** [comment] 2017-05-19 19:59
@kalefranz - I'm seeing a similar error just now with conda `4.3.6`
https://travis-ci.org/gammapy/gammapy/jobs/234116327#L541

```
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string
```

A TypeError form an error handler is still a bug in conda, no?
Should I open a new issue? (or do you not consider this a bug, or am I running on an old version?)

**Comment by kalefranz** [comment] 2017-05-19 20:32
4.3.6?  Try `conda update conda`.

**Comment by kalefranz** [comment] 2017-05-19 20:34
Before opening a new issue, please make sure the behavior you want to report is present in the latest version of conda.

**Comment by cdeil** [comment] 2017-05-19 20:43
I don't have a way to reproduce that issue locally (at least not easily). Let's forget about it then.

**Comment by kalefranz** [comment] 2017-05-19 20:51
Pretty certain it's already been fixed :)
