### ISSUE TITLE
Regression in 4.3.27: mkl is installed even if nomkl is passed in the conda create arguments

### ISSUE THREAD

**Issue by lesteve** [conda/conda#6071] opened 2017-10-04 14:25 UTC
Maybe there is another way to switch between MKL and not using MKL in the most recent conda version? I had a look in the [release notes](https://github.com/conda/conda/blob/master/CHANGELOG.md) and I could see things related to features in the upcoming 4.4 release but nothing in 4.3.27.

#### To reproduce:
This snippet downloads miniconda 4.3.21 and then shows the output of `conda create -n test numpy nomkl` with conda 4.3.25 and 4.3.27:
```bash
export PATH=/tmp/miniconda3/bin:$PATH

wget https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh 2> /dev/null
bash Miniconda3-4.3.21-Linux-x86_64.sh -b -p /tmp/miniconda3 > /dev/null
conda install conda=4.3.25 -y
conda --version
conda create --dry-run -n test python numpy nomkl

conda update conda -y
conda --version
conda create --dry-run -n test python numpy nomkl
rm -rf /tmp/miniconda3 /tmp/Miniconda3*
```

#### Output:
From the output you can see that with 4.3.25 mkl is not installed in the test conda env. With 4.3.27, mkl is installed in the test conda env.
```
Python 3.6.1 :: Continuum Analytics, Inc.
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /tmp/miniconda3:

The following packages will be UPDATED:

    conda: 4.3.21-py36_0 --> 4.3.25-py36_0

conda-4.3.25-p 100% |#####################################################################################| Time: 0:00:00   3.04 MB/s
conda 4.3.25
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /tmp/miniconda3/envs/test:

The following NEW packages will be INSTALLED:

    certifi:     2016.2.28-py36_0   
    libgfortran: 3.0.0-1            
    nomkl:       1.0-0              
    numpy:       1.13.1-py36_nomkl_0 [nomkl]
    openblas:    0.2.19-0           
    openssl:     1.0.2l-0           
    pip:         9.0.1-py36_1       
    python:      3.6.2-0            
    readline:    6.2-2              
    setuptools:  36.4.0-py36_1      
    sqlite:      3.13.0-0           
    tk:          8.5.18-0           
    wheel:       0.29.0-py36_0      
    xz:          5.2.3-0            
    zlib:        1.2.11-0           

Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /tmp/miniconda3:

The following packages will be UPDATED:

    conda: 4.3.25-py36_0 --> 4.3.27-py36h2866c0b_0

conda-4.3.27-p 100% |#####################################################################################| Time: 0:00:00   5.54 MB/s
conda 4.3.27
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /tmp/miniconda3/envs/test:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0     
    certifi:         2017.7.27.1-py36h8b7b77e_0
    intel-openmp:    2018.0.0-h15fc484_7       
    libedit:         3.1-heed3624_0            
    libffi:          3.2.1-h4deb6c0_3          
    libgcc-ng:       7.2.0-hcbc56d2_1          
    libgfortran-ng:  7.2.0-h6fcbd8e_1          
    libstdcxx-ng:    7.2.0-h24385c6_1          
    mkl:             2018.0.0-hb491cac_4       
    ncurses:         6.0-h06874d7_1            
    nomkl:           1.0-0                     
    numpy:           1.13.1-py36h5bc529a_2     
    openssl:         1.0.2l-h9d1a558_3         
    pip:             9.0.1-py36h8ec8b28_3      
    python:          3.6.2-hdfe5801_15         
    readline:        7.0-hac23ff0_3            
    setuptools:      36.5.0-py36he42e2e1_0     
    sqlite:          3.20.1-h6d8b0f3_1         
    tk:              8.6.7-h5979e9b_1          
    wheel:           0.29.0-py36he7f4e38_1     
    xz:              5.2.3-h2bcbf08_1          
    zlib:            1.2.11-hfbfcf68_1         
```

**Comment by kalefranz** [comment] 2017-10-04 14:40
I can verify this is Indeed a bug. I saw it yesterday.

**Comment by lesteve** [comment] 2017-10-04 14:48
OK thanks for confirming. Is there a work-around with conda 4.3.27 to do the equivalent of nomkl or is it better to downgrade to 4.3.25 until the bug is fixed?

**Comment by kalefranz** [comment] 2017-10-04 21:30
For an immediate fix, you can either downgrade to conda 4.3.25 or upgrade to conda 4.4.0rc1.  For the latter,

    conda config --add channels conda-canary
    conda update conda

**Comment by mcg1969** [comment] 2017-10-05 22:32
cc: @msharahan @jjhelmus  @csoja 

In my view, this is most accurately characterized as an Anaconda problem, not a conda problem. The problem is caused by:

- Giving `pkgs/main` a higher channel priority than `pkgs/free`
- Not building any `nomkl` packages in `pkgs/main`

To understand why, consider what would happen if NumPy 1.14 came out and you built _only_ an MKL version of the package; and suppose someone runs `conda install numpy nomkl`. The _first thing_ conda tries to do is maximize the version of NumPy; that will be 1.14 in this case. The _second_ thing it will try to do is maximize the number of `nomkl` packages it can install. But since there are no `nomkl` versions of NumPy 1.14, it has to fall back to the `mkl` version.

That's what is happening here, only it's caused by channel priority instead of version number. The _first_ thing conda tries to do is maximize the channel priority for NumPy. Since it can find NumPy in `pkgs/main`, that's the one it's going to prefer. The _second_ thing conda tries to do is maximize the number of `nomkl` features. But there is no `nomkl` version of the package in `pkgs/main`, so it can't do anything with that.

This can be solved in several ways:
- Revert the channel priority change that gives each subdir its own channel priority.
- Build new `nomkl` equivalents for all packages like NumPy that have `mkl`/`nomkl`.
- Copy the `nomkl` versions of NumPy et. al. from `pkgs/free` into `pkgs/main`.

**Comment by kalefranz** [comment] 2017-10-05 22:52
@lesteve Until we get this squared away, for environments where you don't want mkl, you can add a `.condarc` file in the root directory of that environment, with:

```
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
```

which effectively removes `https://repo.continuum.io/pkgs/main` from `defaults`.

**Comment by jjhelmus** [comment] 2017-10-06 16:25
@mcg1969 I agree with you assessment, conda is properly solving the specifications given.  

That said, I think many users expect `nomkl` to behave in a different manner, specifically including `nomkl` means that the `mkl` package will never be installed in the environment.  In many cases this was true by maximizing the packages with a `nomkl` feature but it was never guaranteed.

I don't believe a requirement of "forbid the mkl package in this environment" can be accomplished with conda's current features.  A package exclusion list, #2410, or something similar might allow this to be done.

**Comment by mcg1969** [comment] 2017-10-06 16:29
That's a fair assessment, @jjhelmus, but I'm afraid desired behavior really isn't compatible with conda's solver structure right now. Fortunately one of the solutions described above will restore the previous behavior, that as you say works in most environments.

**Comment by lschr** [comment] 2017-10-07 11:39
It looks like only `pkgs/main` contains the latest packages, so removing it from the channel list seems like a temporary solution at best… Are there plans to add `nomkl` packages to `pkgs/main`?

**Comment by mingwandroid** [comment] 2017-10-07 11:43
Conda 4.4 has a new key/value variants feature that's a lot nicer than the binary and negative old features implementation.

I am really hoping to make a clean break from that stuff if we can in the new main channel but it requires conda 4.4.

It's there something about mkl that we can investigate fixing for you in the meantime or is it a licencing issue that you have with it?

**Comment by lschr** [comment] 2017-10-07 12:09
@mingwandroid For me this is about licensing and not wanting to depend on non-free software. If a proper solution is possible/planned for the future, I will stick to the free channel for now. Thanks for your quick reply!

**Comment by mingwandroid** [comment] 2017-10-07 12:12
We do plan to add support for people who do not want mkl to the main channel, hopefully soon-ish.

**Comment by lesteve** [comment] 2017-10-08 17:51
In the scikit-learn case, we were using the nomkl argument to test scikit-learn with a numpy using OpenBLAS.

**Comment by lschr** [comment] 2017-10-09 09:26
I tried to use build variants
```yaml
use_mkl:
    - mkl
    - nomkl  # [not win]
```
and then depend on `{{ use_mkl }}`, but that does not seem strong enough to keep nomkl numpy from the `free` channel.

**Comment by mcg1969** [comment] 2017-10-16 03:23
In my view we must support mkl and non-mkl in the main channel, or we must remove prioritizatiin of main. There is no third choice.

**Comment by mcg1969** [comment] 2017-10-16 03:26
Cc: @csoja this is an anaconda issue, so making sure proper attention is given.

**Comment by mingwandroid** [comment] 2017-10-16 08:13
We were hoping to use conda 4.4's key/value variants for the `nomkl` packages.

**Comment by kalefranz** [comment] 2018-02-24 00:12
This issue has been resolved.

**Comment by solomonik** [comment] 2018-06-11 20:19
@kalefranz I have attempted to follow the instructions you give in two comments in this thread (and some alternative instructions from elsewhere), but my miniconda always attempts to install mkl alongside numpy.

I am trying to get a build of numpy on python 3.4 without mkl. I've update my conda version via

```
The following packages will be UPDATED:

    conda: 4.3.31-py36_0 --> 4.6.0a2-py36_0 conda-canary
```

but subsequently trying to `conda install numpy nomkl` still proposes to install mkl. I also added a .condarc file with

```
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
```

which prevented me from installing openblas (so I must've put it in the right place), but after removing it, installing openblas, adding it back and trying to `conda install numpy nomkl`, its still trying to install MKL

```
Solving environment: done

## Package Plan ##

  environment location: /home/edgar/miniconda3/envs/mypy2

  added / updated specs: 
    - nomkl
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nomkl-1.0                  |                0          402 B
    mkl-2017.0.3               |                0       129.5 MB
    numpy-1.13.0               |           py34_0         7.3 MB
    ------------------------------------------------------------
                                           Total:       136.8 MB

The following NEW packages will be INSTALLED:

    mkl:   2017.0.3-0   
    nomkl: 1.0-0        
    numpy: 1.13.0-py34_0
```

Would you please update on the status of this issue? From the discussion above its not clear to me if/how its been resolved or possibly if the problem has been reintroduced.

**Comment by msarahan** [comment] 2018-06-11 20:41
Similar symptoms have come from a different problem.  We are working on moving towards a different, more dependable way of expressing mutual exclusivity, and we're having growing pains.  I'll be uploading a new numpy version soon that should fix this issue.  In the meantime, be sure to update nomkl, and if that still isn't working, add in a "blas=*=openblas" dependency

**Comment by solomonik** [comment] 2018-06-11 21:19
@msarahan thanks for the information. 

Updating mkl and adding the blas=*=openblas to conda install numpy is unfortunately still requesting to install mkl. I look forward to the updated numpy version, other suggestions in the meanwhile are very welcome. Installing MKL is not an issue for me, but I'd like to import numpy without it trying to use MKL symbols (need to pick up reference BLAS and not MKL symbols elsewhere for debugging purposes), so a workaround that fixes that would also help.

**Comment by msarahan** [comment] 2018-06-12 20:11
numpy 1.14.4 packages are uploaded and fix this problem for me.  Make sure that nomkl is version 3.0, not 1.0.  I note that you don't have the "main" channel in your default channels.  Usually, you get that by just updating conda.  If you have manually set up your channels, though, that may not work.  You definitely want 

https://repo.continuum.io/pkgs/main

as your highest priority channel.  The free channel is not actively maintained anymore.  The main channel has all of our newest stuff since around September.

**Comment by solomonik** [comment] 2018-06-13 19:10
@msarahan thank you, the new version of conda with numpy 1.14.4 packages has enabled me to install numpy via conda without MKL in Python 2.7, 3.5, 3.6, **but not 3.4**, which still tries to install numpy 1.13.3 as well as mkl (even with nomkl and openblas specified).

Likely unrelated to conda issues, but the numpy update to conda has actually introduced the bug I am seeing into later conda python versions (to unambiguously reproduce this, I reran a 2-week old repeatedly successful travis-CI run, and it now fails). Previously this problem was only occurring with python 3.4 via conda.

The nature of the bug is a segfault when calling a complex BLAS routine from a C++ code called via cython from a python numpy code. The complex BLAS test runs successfully via C++, on some versions of numpy with mkl, and without mkl. The real (non-complex) version of the test never has problems. The same error happens when calling either the QR or SVD routine of ScaLAPACK (which calls LAPACK). The valgrind trace for the error looks like,
```
==10281==  Bad permissions for mapped region at address 0x17685D38
==10281==    at 0xF5B7C3E: mkl_lapack_cladiv (in /home/edgar/miniconda3/envs/mypy3.5/lib/libmkl_core.so)
==10281==    by 0xC36AEFD: CLADIV (in /home/edgar/miniconda3/envs/mypy3.5/lib/libmkl_intel_lp64.so)
```
Possibly numpy use of MKL is causing it to access python protected memory when called from C++. At this point cannot yet say whether this has anything to do with the specifics of the conda build or is a general numpy+MKL problem, but thought I would mention it here anyway since its feasibly a misconfiguration of the MKL/numpy install.

**Comment by msarahan** [comment] 2018-06-13 19:15
Sorry, 3.4 hasn't been officially supported for quite a while.  We only support the two most recent 3.x releases and 2.7.

Regarding your MKL question, that's something I'd ask the Intel guys.  @oleksandr-pavlyk is usually a good person to ask.

**Comment by solomonik** [comment] 2018-06-13 19:21
Ah, that makes sense, thanks for your help!

**Closed** 2018-09-04 03:03 UTC
Labels: source-community, tag-solver, type-discussion

**Comment by bsipocz** [comment] 2018-09-13 04:29
I'm sorry to comment on an old issue like this. 

The conda installs became quite slow recently for our CIs, and I'm trying to gain some speed in [ci-helpers](https://github.com/astropy/ci-helpers) by making sure mkl isn't downloaded unless it was explicitly asked for. But I'm running into this same issue that `nomkl` is specified, yet mkl is downloaded as well. E.g. here for numpy 1.15/python 3.6:
https://ci.appveyor.com/project/Astropy/ci-helpers/build/1.0.1012/job/jj53j58ecd9fed56#L536

**Comment by msarahan** [comment] 2018-09-13 13:06
Thanks for reraising this. It's because ofa problem with our package dependency metadata. We'll address it soon this morning.

**Comment by msarahan** [comment] 2018-09-13 13:39
@bsipocz this is a misunderstanding.  There are no openblas packages that we provide on Windows right now.  There's only MKL.  The nomkl package exists, but does not do anything.  I'm not sure what its purpose is, and I'm hesitant to remove it, but it really does not make sense to use it.

**Comment by bsipocz** [comment] 2018-09-13 18:56
@msarahan - Thank you for clearing it up. I read in other issues that MKL is the only way to go on Windows, but then `nomkl` appeared, so I assumed that might have changed since those comments.
