### ISSUE TITLE
Source activation for anaconda python environments no longer working (Mac)

### ISSUE THREAD

**Issue by kristiewirth** [conda/conda#6667] opened 2018-01-05 19:06 UTC
The source activate command in conda is suddenly no longer working for me. When I type `source activate py3` in my Mac terminal, I get this error `-bash: _conda_activate: command not found`.

I recently created a new conda environment for TabPy (Tableau python server); I'm not sure if that changed anything. I have checked that the conda environments I'm trying to activate exist by using `conda info --envs`, here is that output:

```
# conda environments:
#
base                  *  /Users/applemacbook/anaconda
Tableau-Python-Server     /Users/applemacbook/anaconda/envs/Tableau-Python 
Server
py3                      /Users/applemacbook/anaconda/envs/py3
```

I already have the following in my bash profile from my initial installation of anaconda awhile ago `export PATH="/Users/applemacbook/anaconda/bin:$PATH"`.

Here is some additional information: The output of `which conda` is `/Users/applemacbook/anaconda/bin/conda`. The output of `type source` is `source is a shell builtin`. The output of `which activate` is `/Users/applemacbook/anaconda/bin/activate`. My conda version is conda 4.4.6

**Comment by kalefranz** [comment] 2018-01-05 19:41
Guessing this is a duplicate of https://github.com/conda/conda/issues/6639?

**Comment by kalefranz** [comment] 2018-01-05 19:55
Maybe not.  Could you open a new terminal, and then give me the output of

    env | sort
    set -x
    source activate py3

**Comment by kalefranz** [comment] 2018-01-05 20:08
You'll want to close the terminal down after you do the above.  Or

    set +x

to get things back to normal.

Also, can you give me the output of 

    cat /Users/applemacbook/anaconda/bin/activate

**Comment by kristiewirth** [comment] 2018-01-05 20:42
Alright, I think I've got all the outputs you asked for below:

$ env | sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.XLbN3qRfIV/Render
CDPATH=.:/Users/applemacbook:/Users/applemacbook/Documents/Galvanize:/Users/applemacbook/Documents/Galvanize/immersive:/Users/applemacbook/Documents:
COLORFGBG=7;0
COLORTERM=truecolor
EDITOR=emacs
HADOOP_HOME=/usr/local/hadoop
HOME=/Users/applemacbook
ITERM_PROFILE=Default
ITERM_SESSION_ID=w0t3p0:1061674E-3BF3-4203-A297-44BAC655F9A4
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
LANG=en_US.UTF-8
LOGNAME=applemacbook
PATH=/usr/local/spark/bin:/Users/applemacbook/anaconda/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PS1=$
PWD=/Users/applemacbook
PYTHONPATH=/usr/local/spark/python:
SHELL=/bin/bash
SHLVL=1
SPARK_HOME=/usr/local/spark
SPARK_LOCAL_IP=localhost
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.FwpsT72RUz/Listeners
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.1.5
TERM_SESSION_ID=w0t3p0:1061674E-3BF3-4203-A297-44BAC655F9A4
TMPDIR=/var/folders/yp/3f96txfd1rj8m8k28xxbvpkh0000gn/T/
USER=applemacbook
VISUAL=emacs
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x0:0:0

$ set -x
+ set -x

$ source activate py3
+ source activate py3
++ _CONDA_ROOT=/Users/applemacbook/anaconda
++ _conda_script_is_sourced
++ sourced=0
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n x ']'
++ '[' /Users/applemacbook/anaconda/bin/activate = -bash ']'
++ return 0
++ _conda_set_vars
++ '[' -n x ']'
++ _CONDA_SHELL_FLAVOR=bash
++ local script_dir
++ case "$_CONDA_SHELL_FLAVOR" in
+++ dirname /Users/applemacbook/anaconda/bin/activate
++ script_dir=/Users/applemacbook/anaconda/bin
++ '[' -z x ']'
++ cd .. /Users/applemacbook/anaconda/etc/profile.d/conda.sh
++ _conda_activate py3
-bash: _conda_activate: command not found

$ cat /Users/applemacbook/anaconda/bin/activate
+ cat /Users/applemacbook/anaconda/bin/activate
#!/bin/sh
_CONDA_ROOT="/Users/applemacbook/anaconda"
#!/bin/sh

_conda_set_vars() {
    # set _CONDA_SHELL_FLAVOR
    if [ -n "${BASH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=bash
    elif [ -n "${ZSH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=zsh
    elif [ -n "${KSH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=ksh
    elif [ -n "${POSH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=posh
    else
        # https://unix.stackexchange.com/a/120138/92065
        local _q="$(ps -p$$ -o cmd="",comm="",fname="" 2>/dev/null | sed
's/^-//' | grep -oE '\w+' | head -n1)"
        if [ "$_q" = dash ]; then
            _CONDA_SHELL_FLAVOR=dash
        else
            (>&2 echo "Unrecognized shell.")
            return 1
        fi
    fi

    #
https://unix.stackexchange.com/questions/4650/determining-path-to-sourced-shell-script/
    local script_dir
    case "$_CONDA_SHELL_FLAVOR" in
        bash) script_dir="$(dirname "${BASH_SOURCE[0]}")";;
        zsh) script_dir="$(dirname "${(%):-%x}")";;  #
http://stackoverflow.com/a/28336473/2127762
        dash) x=$(lsof -p $$ -Fn0 | tail -1); script_dir="$(dirname
"${x#n}")";;
        *) script_dir="$(cd "$(dirname "$_")" && echo "$PWD")";;
    esac

    if [ -z "${_CONDA_ROOT+x}" ]; then
        _CONDA_ROOT="$(dirname "$script_dir")"
    fi

}

_conda_script_is_sourced() {
    # http://stackoverflow.com/a/28776166/2127762
    sourced=0
    if [ -n "${ZSH_EVAL_CONTEXT:+x}" ]; then
      case $ZSH_EVAL_CONTEXT in *:file) sourced=1;; esac
    elif [ -n "${KSH_VERSION:+x}" ]; then
      [ "$(cd $(dirname -- $0) && pwd -P)/$(basename -- $0)" != "$(cd
$(dirname -- ${.sh.file}) && pwd -P)/$(basename -- ${.sh.file})" ] &&
sourced=1
    elif [ -n "${BASH_VERSION:+x}" ]; then
      [ "${BASH_SOURCE[0]}" = "$0" ] && sourced=1
    else # All other shells: examine $0 for known shell binary filenames
      # Detects `sh` and `dash`; add additional shell filenames as needed.
      case ${0##*/} in sh|dash) sourced=0;; *) sourced=1;; esac
    fi
    return $sourced
}

if ! _conda_script_is_sourced; then
    (
      >&2 echo "Error: activate must be sourced. Run 'source activate
envname'"
      >&2 echo "instead of 'activate envname'."
    )
    exit 1
fi

_conda_set_vars
. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
_conda_activate "$@"

**Comment by kalefranz** [comment] 2018-01-05 20:51
```
$ env | sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.XLbN3qRfIV/Render
CDPATH=.:/Users/applemacbook:/Users/applemacbook/Documents/Galvanize:/Users/applemacbook/Documents/Galvanize/immersive:/Users/applemacbook/Documents:
COLORFGBG=7;0
COLORTERM=truecolor
EDITOR=emacs
HADOOP_HOME=/usr/local/hadoop
HOME=/Users/applemacbook
ITERM_PROFILE=Default
ITERM_SESSION_ID=w0t3p0:1061674E-3BF3-4203-A297-44BAC655F9A4
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
LANG=en_US.UTF-8
LOGNAME=applemacbook
PATH=/usr/local/spark/bin:/Users/applemacbook/anaconda/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PS1=$
PWD=/Users/applemacbook
PYTHONPATH=/usr/local/spark/python:
SHELL=/bin/bash
SHLVL=1
SPARK_HOME=/usr/local/spark
SPARK_LOCAL_IP=localhost
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.FwpsT72RUz/Listeners
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.1.5
TERM_SESSION_ID=w0t3p0:1061674E-3BF3-4203-A297-44BAC655F9A4
TMPDIR=/var/folders/yp/3f96txfd1rj8m8k28xxbvpkh0000gn/T/
USER=applemacbook
VISUAL=emacs
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x0:0:0

$ set -x
+ set -x

$ source activate py3
+ source activate py3
++ _CONDA_ROOT=/Users/applemacbook/anaconda
++ _conda_script_is_sourced
++ sourced=0
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n x ']'
++ '[' /Users/applemacbook/anaconda/bin/activate = -bash ']'
++ return 0
++ _conda_set_vars
++ '[' -n x ']'
++ _CONDA_SHELL_FLAVOR=bash
++ local script_dir
++ case "$_CONDA_SHELL_FLAVOR" in
+++ dirname /Users/applemacbook/anaconda/bin/activate
++ script_dir=/Users/applemacbook/anaconda/bin
++ '[' -z x ']'
++ cd .. /Users/applemacbook/anaconda/etc/profile.d/conda.sh
++ _conda_activate py3
-bash: _conda_activate: command not found

$ cat /Users/applemacbook/anaconda/bin/activate
+ cat /Users/applemacbook/anaconda/bin/activate
#!/bin/sh
_CONDA_ROOT="/Users/applemacbook/anaconda"
#!/bin/sh

_conda_set_vars() {
    # set _CONDA_SHELL_FLAVOR
    if [ -n "${BASH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=bash
    elif [ -n "${ZSH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=zsh
    elif [ -n "${KSH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=ksh
    elif [ -n "${POSH_VERSION:+x}" ]; then
        _CONDA_SHELL_FLAVOR=posh
    else
        # https://unix.stackexchange.com/a/120138/92065
        local _q="$(ps -p$$ -o cmd="",comm="",fname="" 2>/dev/null | sed
's/^-//' | grep -oE '\w+' | head -n1)"
        if [ "$_q" = dash ]; then
            _CONDA_SHELL_FLAVOR=dash
        else
            (>&2 echo "Unrecognized shell.")
            return 1
        fi
    fi

    #
https://unix.stackexchange.com/questions/4650/determining-path-to-sourced-shell-script/
    local script_dir
    case "$_CONDA_SHELL_FLAVOR" in
        bash) script_dir="$(dirname "${BASH_SOURCE[0]}")";;
        zsh) script_dir="$(dirname "${(%):-%x}")";;  #
http://stackoverflow.com/a/28336473/2127762
        dash) x=$(lsof -p $$ -Fn0 | tail -1); script_dir="$(dirname
"${x#n}")";;
        *) script_dir="$(cd "$(dirname "$_")" && echo "$PWD")";;
    esac

    if [ -z "${_CONDA_ROOT+x}" ]; then
        _CONDA_ROOT="$(dirname "$script_dir")"
    fi

}

_conda_script_is_sourced() {
    # http://stackoverflow.com/a/28776166/2127762
    sourced=0
    if [ -n "${ZSH_EVAL_CONTEXT:+x}" ]; then
      case $ZSH_EVAL_CONTEXT in *:file) sourced=1;; esac
    elif [ -n "${KSH_VERSION:+x}" ]; then
      [ "$(cd $(dirname -- $0) && pwd -P)/$(basename -- $0)" != "$(cd
$(dirname -- ${.sh.file}) && pwd -P)/$(basename -- ${.sh.file})" ] &&
sourced=1
    elif [ -n "${BASH_VERSION:+x}" ]; then
      [ "${BASH_SOURCE[0]}" = "$0" ] && sourced=1
    else # All other shells: examine $0 for known shell binary filenames
      # Detects `sh` and `dash`; add additional shell filenames as needed.
      case ${0##*/} in sh|dash) sourced=0;; *) sourced=1;; esac
    fi
    return $sourced
}

if ! _conda_script_is_sourced; then
    (
      >&2 echo "Error: activate must be sourced. Run 'source activate
envname'"
      >&2 echo "instead of 'activate envname'."
    )
    exit 1
fi

_conda_set_vars
. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
_conda_activate "$@"

```

**Comment by kalefranz** [comment] 2018-01-05 20:53
Comparing from above

```
++ script_dir=/Users/applemacbook/anaconda/bin
++ '[' -z x ']'
++ cd .. /Users/applemacbook/anaconda/etc/profile.d/conda.sh
++ _conda_activate py3
-bash: _conda_activate: command not found
```

to what I get myself

```
++ script_dir=/Users/kfranz/miniconda/bin
++ '[' -z x ']'
++ . /Users/kfranz/miniconda/etc/profile.d/conda.sh
+++ _CONDA_EXE=/Users/kfranz/miniconda/bin/conda
+++ _CONDA_ROOT=/Users/kfranz/miniconda
```

**Comment by kalefranz** [comment] 2018-01-05 21:01
@mbargull If you have a free moment, can you look at some of this here and see if you understand what's going on?  I don't really understand what we're seeing as output from @kristiewirth, and also not able to reproduce it myself.

Regardless, #6669 will probably fix it, I think.  Still curious if you can spot what's going on here...

**Comment by mbargull** [comment] 2018-01-05 21:58
Possibly some ancient `bash` version provided by OSX?
The output for
```bash
_conda_script_is_sourced() {
...
    elif [ -n "${BASH_VERSION:+x}" ]; then
      [ "${BASH_SOURCE[0]}" = "$0" ] && sourced=1
...
    return $sourced
}

if ! _conda_script_is_sourced; then
...
    exit 1
fi

_conda_set_vars
```
looks fishy:
```
++ '[' -n x ']'
++ '[' /Users/applemacbook/anaconda/bin/activate = -bash ']'
++ return 0
++ _conda_set_vars
```
. It shows that `[ "${BASH_SOURCE[0]}" = "$0" ]` didn't recognize the script was sourced and `return 0` didn't evaluate to false for `! _conda_script_is_sourced`.
Since `"${BASH_VERSION:+x}"` is non-empty, I suppose we have `bash` but maybe an older one that behaves differently?

**Comment by kalefranz** [comment] 2018-01-05 22:35
@kristiewirth can you give us output of `conda info` and `which -a bash` ?

**Comment by kalefranz** [comment] 2018-01-05 22:37
@kristiewirth Looking more closely at your environment variables, you have set

    PYTHONPATH=/usr/local/spark/python:

that's going to cause you all sorts of grief.

**Comment by kalefranz** [comment] 2018-01-05 22:41
Also, you just taught me something.  Had no idea what `CDPATH` was.

**Comment by mbargull** [comment] 2018-01-05 22:41
`echo $BASH_VERSION` would be interesting, too.

**Comment by kristiewirth** [comment] 2018-01-06 20:31
I've had the following in my bash profile for quite awhile for Spark
without issue, but happy to alter if that's screwing things up somehow.
export PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH

And CDPATH is great for quick navigation. =)

Requested output:

$ conda info
     active environment : None
       user config file : /Users/applemacbook/.condarc
 populated config files : /Users/applemacbook/.condarc
          conda version : 4.4.6
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /Users/applemacbook/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/applemacbook/anaconda/pkgs
                          /Users/applemacbook/.conda/pkgs
       envs directories : /Users/applemacbook/anaconda/envs
                          /Users/applemacbook/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.6 requests/2.18.4 CPython/2.7.14
Darwin/17.3.0 OSX/10.13.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False

$ which -a bash
/bin/bash

$ echo $BASH_VERSION
3.2.57(1)-release

**Comment by mbargull** [comment] 2018-01-06 22:12
Thanks for the output -- I'm still confused though. But my previous comment can be disregarded -- I was thinking not in terms of exit codes but Boolean variables, which was foolish...

I still can't figure out how
```bash
. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
```
turned into
```bash
++ cd .. /Users/applemacbook/anaconda/etc/profile.d/conda.sh
```
 @kristiewirth, can you show what `type .` outputs? Can you also try `CDPATH=0 source activate py3`?

@kalefranz, I knew of `CDPATH` but I never thought about its [implications inside scripts](https://bosker.wordpress.com/2012/02/12/bash-scripters-beware-of-the-cdpath/)... 
If the user uses `CDPATH` but doesn't have `.` as its first value, then even simple things like `"$(cd $(dirname -- $0)"` can fail 😨 -- thus you would always have to make sure to somehow force absolute paths or relative ones starting with `.` (if you'd want to support such exotic cases that is -- which might be questionable). Since we `source` scripts, it wouldn't even help to tell the users to not `export CDPATH` since the script is executed inside the same shell process. And an `unset CDPATH` inside a sourced script without a proper `trap` that restores `CDPATH` on exit would also be upsetting to the user... What a mess!

**Comment by kristiewirth** [comment] 2018-01-07 00:23
I've had those CDPATH commands in my bash profile for awhile. They
shouldn't have had any recent changes to mess anything up! I'm happy to
comment out more optional things in my bash profile if that would make this
easier.

$ type .
. is aliased to `cd ..'

$ CDPATH=0 source activate py3
-bash: _conda_activate: command not found

**Comment by mbargull** [comment] 2018-01-07 00:40
Aha, another thing I didn't thought about before: `source`d scripts run the aliased commands (same shell process and all...)!
So the problem here is the alias for `.`. It is a bug in `conda`'s scripts that they use user-defined aliases.
@kristiewirth: A temporary workaround for you would be to `unalias .` before running the `activate`/`deactivate` scripts. 
@kalefranz: I don't know what the most portable solution is, but there are a couple of those, e.g., given in https://unix.stackexchange.com/questions/39291/run-a-command-that-is-shadowed-by-an-alias

**Comment by kristiewirth** [comment] 2018-01-07 02:11
That works! Thanks all.

**Comment by kalefranz** [comment] 2018-01-10 13:55
Oh wow just catching up on this issue.  

Was recently reviewing https://github.com/kennethreitz/autoenv/blob/master/activate.sh, and didn't understand what the backslashes were for.  Also got sidetracked (likely because reviewing that itself was a sidetrack) and didn't pursue the backslash thing further.

Makes sense now though.

**Comment by kalefranz** [comment] 2018-01-10 13:58
The backslash method seems to work for dash and zsh.

**Comment by kalefranz** [comment] 2018-01-10 14:03
Solution here is to modify the posix portion of `conda/activate.py` from

```python
self.unset_var_tmpl = 'unset %s'
self.export_var_tmpl = "export %s='%s'"
self.set_var_tmpl = "%s='%s'"
self.run_script_tmpl = '. "%s"'
```

to

```python
self.unset_var_tmpl = '\\unset %s'
self.export_var_tmpl = "\\export %s='%s'"
self.set_var_tmpl = "%s='%s'"
self.run_script_tmpl = '\\. "%s"'
```

and modify associated tests.

**Comment by mbargull** [comment] 2018-01-12 00:43
In addition to `conda/activate.py`, the shell scripts need to be changed as well (including all those inline/sub-shell `dirname`/`pwd`/... calls).

**Comment by norok2** [comment] 2018-01-22 07:58
I had the same issue on Debian and `unalias .` restores `source activate` funcionality (using anaconda2 conda version 4.4.7)

**Comment by kalefranz** [comment] 2018-02-02 20:05
Yeah the PR is https://github.com/conda/conda/pull/6669.  Hopefully we have some bandwidth to review and merge it soon.  CC @nehaljwani @jjhelmus

**Closed** 2018-02-15 20:26 UTC
Labels: easy, good first issue, source:community, type:enhancement

**Comment by durack1** [comment] 2018-02-15 20:42
@kalefranz what version of conda/anaconda should I look out for to test the fix? BTW, my issue was on linux not mac

**Comment by kalefranz** [comment] 2018-02-15 20:55
conda 4.4.11

**Comment by durack1** [comment] 2018-02-23 01:12
@kalefranz thanks, I've been watching for `4.4.11` are you anticipating a release soon?
