### ISSUE TITLE
conda search --reverse-dependency stopped working

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#7298] opened 2018-05-16 20:31 UTC
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

`conda search --reverse-dependency pkgname` used to provide a list of packages that have `pkgname` as a dependency.
 It currently simply returns the exact same result as `conda search pkgname`.

### Steps to Reproduce

```
(TEST) └─❱❱❱ conda search intel-openmp                                              +9747 14:29 ❰─┘
Loading channels: done
# Name                  Version           Build  Channel
intel-openmp           2017.0.4      h6509f9f_0  pkgs/main
intel-openmp           2018.0.0               8  pkgs/main
intel-openmp           2018.0.0      h68bdfb3_7  pkgs/main
intel-openmp           2018.0.0      h8158457_8  pkgs/main
intel-openmp           2018.0.0      hdd0ccc9_7  pkgs/main

┌─( ~/D/src )───────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(TEST) └─❱❱❱ conda search --reverse-dependency intel-openmp --full-name             +9748 14:30 ❰─┘
Loading channels: done
# Name                  Version           Build  Channel
intel-openmp           2017.0.4      h6509f9f_0  pkgs/main
intel-openmp           2018.0.0               8  pkgs/main
intel-openmp           2018.0.0      h68bdfb3_7  pkgs/main
intel-openmp           2018.0.0      h8158457_8  pkgs/main
intel-openmp           2018.0.0      hdd0ccc9_7  pkgs/main
```

## Expected Behavior

A list of package names that have `pkgname` as dependency.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : TEST
    active env location : /Users/klay6683/miniconda3/envs/TEST
            shell level : 2
       user config file : /Users/klay6683/.condarc
 populated config files : /Users/klay6683/miniconda3/.condarc
                          /Users/klay6683/.condarc
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /Users/klay6683/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/NSIDC/osx-64
                          https://conda.anaconda.org/NSIDC/noarch
          package cache : /Users/klay6683/miniconda3/pkgs
                          /Users/klay6683/.conda/pkgs
       envs directories : /Users/klay6683/miniconda3/envs
                          /Users/klay6683/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 273771:2260
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/klay6683/miniconda3/.condarc <==
pinned_packages:
  - conda-forge::gdal

==> /Users/klay6683/.condarc <==
auto_update_conda: True
channels:
  - conda-forge
  - defaults
  - NSIDC
report_errors: True

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/klay6683/miniconda3/envs/TEST:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
openssl                   1.0.2o                        0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
python                    3.6.5                         1    conda-forge
readline                  7.0                           0    conda-forge
setuptools                39.1.0                   py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```
</p></details>

**Comment by mbargull** [comment] 2018-05-16 21:58
duplicate of gh-6670.

**Closed by mbargull** 2018-05-16 21:58 UTC
