### ISSUE TITLE
 Unsatisfiable package specifications are actually satisfiable

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#1912] opened 2015-12-16 09:01 UTC
If I specify the exact version of matplotlib I want installed conda throws an *unsatisfiable package specifications* error
```
c:\temp>conda create -n test --alt-hint --dry-run matplotlib=1.4.3=np19py27_3 numpy=1.9.3
Fetching package metadata: ............
Solving package specifications: ............
Error: Unsatisfiable package specifications.
Generating minimal hint:
[      COMPLETE      ]|##################################################| 100%

The following set of clauses is unsatisfiable:

not tk-8.5.18-vc10_0
not tk-8.5.18-vc9_0
not tk-8.5.18-vc14_0
matplotlib-1.4.3-np19py27_3
matplotlib-1.4.3-np19py27_3 => tk-8.5.18-vc10_0 or tk-8.5.18-vc9_0 or tk-8.5.18-vc14_0
```

However if I don't specify the build string it happily creates the environment with the exact same version I originally specified!
```
c:\temp>conda create -n test --alt-hint --dry-run matplotlib=1.4.3 numpy=1.9.3
Fetching package metadata: ..........
Solving package specifications: ..........................
Package plan for installation in environment C:\dev\bin\Anaconda\envs\test:

The following NEW packages will be INSTALLED:

    jpeg:            8d-vc9_0         [vc9]
    libpng:          1.6.17-vc9_1     [vc9]
    libtiff:         4.0.6-vc9_1      [vc9]
    matplotlib:      1.4.3-np19py27_3
    msvc_runtime:    1.0.1-vc9_0      [vc9]
    numpy:           1.9.3-py27_0
    openssl:         1.0.2d-vc9_0     [vc9]
    pip:             7.1.2-py27_0
    pyparsing:       2.0.3-py27_0
    pyqt:            4.11.4-py27_4
    python:          2.7.11-0
    python-dateutil: 2.4.2-py27_0
    pytz:            2015.7-py27_0
    qt:              4.8.7-vc9_5      [vc9]
    setuptools:      18.8.1-py27_0
    sip:             4.16.9-py27_2
    six:             1.10.0-py27_0
    tk:              8.5.18-vc9_0     [vc9]
    wheel:           0.24.0-py27_0
    zlib:            1.2.8-vc9_2      [vc9]

Dry run: exiting
```

**Comment by dhirschfeld** [comment] 2015-12-16 09:29
I came across the above example when I was trying to debug an issue with one of our internal packages. In that case we have the main package `mypackage` which depends on a `mypackage-deps` meta-package which specifies exact versions and build-strings for ~60 packages.

Installing `mypackage` fails, but installing `mypackage-deps` on its own works fine. If **both** `mypackage` and `mypackage-deps` are specified in the conda create command it works so the package specifications are obviously satisfiable.

```
c:\temp>conda create -n test --alt-hint --dry-run mypackage==1.8.1.dev107
Fetching package metadata: ..........
Solving package specifications: .......................................................................................................................................
Error: Unsatisfiable package specifications.
Generating minimal hint:
[      COMPLETE      ]|##################################################| 100%

The following set of clauses is unsatisfiable:

mypackage-1.8.1.dev107-0 => mypackage-deps-1.8.1.dev107-np19py27_0
pyqt-4.11.4-py27_4 => qt-4.8.7-vc9_5
not qt-4.8.7-vc9_5
mypackage-deps-1.8.1.dev107-np19py27_0 => pyqt-4.11.4-py27_4
mypackage-1.8.1.dev107-0

c:\temp>conda create -n test --alt-hint --dry-run mypackage-deps==1.8.1.dev107
Fetching package metadata: ..........
Solving package specifications: ........................................................................................................................................
Package plan for installation in environment C:\dev\bin\Anaconda\envs\test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mypackage-deps-1.8.1.dev107|       np19py27_0         1.4 MB

The following NEW packages will be INSTALLED:

<snip>

Dry run: exiting

c:\temp>conda create -n test --alt-hint --dry-run mypackage==1.8.1.dev107 mypackage-deps==1.8.1.dev107
Fetching package metadata: ..........
Solving package specifications: ............................................................................................................................................
Package plan for installation in environment C:\dev\bin\Anaconda\envs\test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mypackage-1.8.1.dev107|                0        43.7 MB
   mypackage-deps-1.8.1.dev107|       np19py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:        45.1 MB

The following NEW packages will be INSTALLED:

<snip>

Dry run: exiting
```

**Comment by dhirschfeld** [comment] 2015-12-16 09:31
```
c:\temp>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.9
  conda-build version : 1.18.1
       python version : 2.7.11.final.0
     requests version : 2.9.0
     root environment : C:\dev\bin\Anaconda  (writable)
  default environment : C:\dev\bin\Anaconda
     envs directories : C:\dev\bin\Anaconda\envs
        package cache : C:\dev\bin\Anaconda\pkgs
         channel URLs : http://conda:82/CI/win-64/
                        http://conda:82/CI/noarch/
                        https://conda.anaconda.org/dhirschfeld/win-64/
                        https://conda.anaconda.org/dhirschfeld/noarch/
                        http://repo.continuum.io/pkgs/dev/win-64/
                        http://repo.continuum.io/pkgs/dev/noarch/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/gpl/win-64/
                        http://repo.continuum.io/pkgs/gpl/noarch/
          config file : C:\Users\dhirschfeld\.condarc
    is foreign system : False
```

**Comment by dhirschfeld** [comment] 2015-12-16 11:21
**Note:** After removing `msvc_runtime` and all packages with `[vc9]` features I can now install our internal package so it seems the problem is related to #1779.

Since the latest matplotlib package uses features I suspect the first issue is also related to #1779 so hopefully that minimal example will be helpful debugging the underlying problem

**Comment by groutr** [comment] 2015-12-17 17:06
I tried reproducing this on my machine, and specifying the exact build string doesn't result in unsatisfied dependencies.
```
❯ conda create -n test --alt-hint --dry-run matplotlib=1.4.3=np19py27_3 numpy=1.9.3
Fetching package metadata: ......
Solving package specifications: ......................
Package plan for installation in environment /Users/rgrout/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.9.3                |           py27_0         2.9 MB  defaults
    pyparsing-2.0.3            |           py27_0          63 KB  defaults
    matplotlib-1.4.3           |       np19py27_3        40.8 MB  defaults
    ------------------------------------------------------------
                                           Total:        43.8 MB

The following NEW packages will be INSTALLED:

    freetype:        2.5.5-0          defaults
    libpng:          1.6.17-0         defaults
    matplotlib:      1.4.3-np19py27_3 defaults
    numpy:           1.9.3-py27_0     defaults
    openssl:         1.0.2d-0         defaults
    pip:             7.1.2-py27_0     defaults
    pyparsing:       2.0.3-py27_0     defaults
    pyqt:            4.11.4-py27_1    defaults
    python:          2.7.11-0         defaults
    python-dateutil: 2.4.2-py27_0     defaults
    pytz:            2015.7-py27_0    defaults
    qt:              4.8.7-1          defaults
    readline:        6.2-2            defaults
    setuptools:      18.8.1-py27_0    defaults
    sip:             4.16.9-py27_0    defaults
    six:             1.10.0-py27_0    defaults
    sqlite:          3.8.4.1-1        defaults
    tk:              8.5.18-0         defaults
    wheel:           0.26.0-py27_1    defaults
    zlib:            1.2.8-0          defaults

Dry run: exiting
```

**Comment by groutr** [comment] 2015-12-17 20:07
The only thing I can think of is there is a conflict between your conda channels.  Also note that the `dev` and `gpl` channels of repo.continuum.io are no longer active.

**Comment by dhirschfeld** [comment] 2015-12-20 23:38
@groutr - I don't think that can be right as I get exactly the same results on a different PC, also when I explicitly set `--override-channels` and specify the Continuum defaults:
```
C:\Users\Dave
λ conda create -n test --alt-hint --override-channels --channel defaults --dry-run matplotlib=1.4.3=np19py27_3 numpy=1.9.3
Fetching package metadata: ....
Solving package specifications: .........
Error: Unsatisfiable package specifications.
Generating minimal hint:
[      COMPLETE      ]|##################################################| 100%

The following set of clauses is unsatisfiable:

matplotlib-1.4.3-np19py27_3 => tk-8.5.18-vc10_0 or tk-8.5.18-vc14_0 or tk-8.5.18-vc9_0
not tk-8.5.18-vc9_0
not tk-8.5.18-vc14_0
not tk-8.5.18-vc10_0
matplotlib-1.4.3-np19py27_3
C:\Users\Dave
λ conda create -n test --alt-hint --override-channels --channel https://repo.continuum.io/pkgs/free --dry-run matplotlib=1.4.3=np19py27_3 numpy=1.9.3
Fetching package metadata: ..
Solving package specifications: .........
Error: Unsatisfiable package specifications.
Generating minimal hint:
[      COMPLETE      ]|##################################################| 100%

The following set of clauses is unsatisfiable:

not tk-8.5.18-vc9_0
matplotlib-1.4.3-np19py27_3 => tk-8.5.18-vc14_0 or tk-8.5.18-vc9_0 or tk-8.5.18-vc10_0
not tk-8.5.18-vc14_0
not tk-8.5.18-vc10_0
matplotlib-1.4.3-np19py27_3
C:\Users\Dave
λ
```
```
C:\Users\Dave
λ conda info
Current conda install:

             platform : win-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.0
     root environment : C:\bin\Anaconda3  (writable)
  default environment : C:\bin\Anaconda3
     envs directories : C:\bin\Anaconda3\envs
        package cache : C:\bin\Anaconda3\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/dhirschfeld/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/dhirschfeld/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Dave\.condarc
    is foreign system : False
```

**Comment by dhirschfeld** [comment] 2015-12-20 23:42
@grout - looks like you're trying on linux where you don't have the whole `[vc9]`/`[vc14]`... features mess.

As mentioned above I suspect that this `unsatisfiable specifications` error is related to a bug in the "features" feature and probably related to #1779

**Comment by kalefranz** [comment] 2016-01-12 03:17
@dhirschfeld New conda tech lead here.  Still trying to catch up on a deep backlog, but fixing issues with the solver is a high priority.  Working with several people to figure out what the best path forward is here.

**Comment by dhirschfeld** [comment] 2016-01-12 12:02
@kalefranz,welcome aboard! Thanks for touching base - it's good to know someone is having a look. I imagine it's not a simple one to track down but hopefully this issue can provide a useful repro...

**Comment by dhirschfeld** [comment] 2016-02-06 00:52
With the latest conda dev build ` 3.19.1.44.g05366e9-dev_py35` I'm still seeing some unusual behaviour:

Trying to install a fully specified matplotlib gives an *Unsatisfiable package specifications* error but only lists matplotlib in the conflicting packages - what is matplotlib conflicting with?!?
```
λ conda create -n test --dry-run matplotlib=1.4.3=np19py27_3 numpy=1.9.3
Fetching package metadata: ......
Solving package specifications: .
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


The following specifications were found to be in conflict:
  - matplotlib 1.4.3 np19py27_3
Use "conda info <package>" to see the dependencies for each package.
```

If I simply specify `python=2.7*` in the install list conda is able to to create an installation plan:
```
λ conda create -n test --dry-run python=2.7* matplotlib=1.4.3=np19py27_3 numpy=1.9.3
Fetching package metadata: ......
Solving package specifications: .......

Package plan for installation in environment C:\bin\Anaconda3\envs\test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2f             |            vc9_0         4.4 MB
    tk-8.5.18                  |            vc9_0         2.2 MB
    python-2.7.11              |                2        23.2 MB
    numpy-1.9.3                |           py27_0        23.5 MB
    pyparsing-2.0.3            |           py27_0          63 KB
    pytz-2015.7                |           py27_0         169 KB
    setuptools-19.6.2          |           py27_0         671 KB
    pip-8.0.2                  |           py27_0         1.5 MB
    python-dateutil-2.4.2      |           py27_0         219 KB
    matplotlib-1.4.3           |       np19py27_3        40.8 MB
    ------------------------------------------------------------
                                           Total:        96.7 MB

The following NEW packages will be INSTALLED:

    jpeg:            8d-vc9_0         [vc9]
    libpng:          1.6.17-vc9_1     [vc9]
    libtiff:         4.0.6-vc9_1      [vc9]
    matplotlib:      1.4.3-np19py27_3
    msvc_runtime:    1.0.1-vc9_0      [vc9]
    numpy:           1.9.3-py27_0
    openssl:         1.0.2f-vc9_0     [vc9]
    pip:             8.0.2-py27_0
    pyparsing:       2.0.3-py27_0
    pyqt:            4.11.4-py27_4
    python:          2.7.11-2
    python-dateutil: 2.4.2-py27_0
    pytz:            2015.7-py27_0
    qt:              4.8.7-vc9_5      [vc9]
    setuptools:      19.6.2-py27_0
    sip:             4.16.9-py27_2
    six:             1.10.0-py27_0
    tk:              8.5.18-vc9_0     [vc9]
    wheel:           0.26.0-py27_1
    zlib:            1.2.8-vc9_2      [vc9]

Dry run: exiting
```

**Comment by mcg1969** [comment] 2016-02-06 02:02
I've seen stuff like this. I'd bet money it is a genuine conflict, buried somewhere. The bug is in the lousy hint.

**Comment by mcg1969** [comment] 2016-02-06 20:01
Hmm, I'm having trouble reproducing this:
```
0203-mgrant:~ mgrant$ conda create -n test --dry-run matplotlib=1.4.3=np19py27_3 numpy=1.9.3
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .......

Package plan for installation in environment /Users/mgrant/miniconda2/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.9.3                |           py27_0         2.9 MB
    matplotlib-1.4.3           |       np19py27_3        40.8 MB
    ------------------------------------------------------------
                                           Total:        43.7 MB

The following NEW packages will be INSTALLED:

    freetype:        2.5.5-0         
    libpng:          1.6.17-0        
    matplotlib:      1.4.3-np19py27_3
    numpy:           1.9.3-py27_0    
    openssl:         1.0.2f-0        
    pip:             8.0.2-py27_0    
    pyparsing:       2.0.3-py27_0    
    pyqt:            4.11.4-py27_1   
    python:          2.7.11-0        
    python-dateutil: 2.4.2-py27_0    
    pytz:            2015.7-py27_0   
    qt:              4.8.7-1         
    readline:        6.2-2           
    setuptools:      19.6.2-py27_0   
    sip:             4.16.9-py27_0   
    six:             1.10.0-py27_0   
    sqlite:          3.9.2-0         
    tk:              8.5.18-0        
    wheel:           0.26.0-py27_1   
    zlib:            1.2.8-0         

Dry run: exiting
```
What channels do you have in your default list?

**Comment by mcg1969** [comment] 2016-02-06 23:39
Actually it looks like this may be Windows specific.

**Comment by mcg1969** [comment] 2016-02-07 20:19
This is now fixed in our internal version. I'll let you know when we post a new conda package with an update. cc: @groutr

**Comment by dhirschfeld** [comment] 2016-02-11 11:18
I can confirm that this works with conda `3.19.1.44.g05366e9-dev_py35` so happy for it to be closed...

**Comment by mcg1969** [comment] 2016-02-11 20:31
Great. We've identified a couple of issues that need fixing before we tag the new solver for release. For instance, now that it's more strict about not allowing inconsistencies, we're finding that the mistakes previous versions of conda have left behind are causing problems :-) But I will indeed close this! Thanks!

**Closed by mcg1969** 2016-02-11 20:31 UTC
Labels: bug, Solver
