### ISSUE TITLE
keras installation on anaconda 

### ISSUE THREAD

**Issue by sharmadp** [conda/conda#4177] opened 2017-01-04 17:49 UTC
step followed
http://stackoverflow.com/questions/34097988/how-do-i-install-keras-and-theano-in-anaconda-python-2-7-on-windows

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.2
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\user\Anaconda2  (writable)
    default environment : C:\Users\user\Anaconda2
       envs directories : C:\Users\user\Anaconda2\envs
          package cache : C:\Users\user\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\user\Anaconda2\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\exceptions.py", line
 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\cli\main.py", line 1
45, in _main
        exit_code = args.func(args, p)
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\cli\main_update.py",
 line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\cli\install.py", lin
e 238, in install
        prefix=prefix)
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\api.py", line 24, in
 get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\fetch.py", line 295,
 in fetch_index
        for url in urls]
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\fetch.py", line 75,
in func
        res = f(*args, **kwargs)
      File "C:\Users\user\Anaconda2\lib\site-packages\conda\fetch.py", line 117,
 in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\sessions.py", lin
e 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\sessions.py", lin
e 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\sessions.py", lin
e 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\adapters.py", lin
e 423, in send
        timeout=timeout
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\packages\urllib3\
connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\packages\urllib3\
connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\packages\urllib3\
connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\packages\urllib3\
connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\packages\urllib3\
contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Users\user\Anaconda2\lib\site-packages\requests\packages\urllib3\
contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_clas
s'

(C:\Users\user\Anaconda2) C:\Windows\system32>

**Comment by kalefranz** [comment] 2017-05-01 20:00
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 20:00 UTC
