### ISSUE TITLE
Conda doesn't work after failed update.

### ISSUE THREAD

**Issue by scholer** [conda/conda#3437] opened 2016-09-15 15:56 UTC
I did a routine ```conda update --all``` just now, but the update failed with a CondaOSError:

    Extracting packages ...
    [      COMPLETE      ]|#########################################################################################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|#########################################################################################################################| 100%
    Linking packages ...
    CondaOSError: OS error: failed to link (src='/Users/rasmus/anaconda3/pkgs/hdf5-1.8.17-1/lib/libhdf5_cpp.dylib', dst='/Users/rasmus/anaconda3/lib/libhdf5_cpp.dylib', type=3, error=FileExistsError(17, 'File exists'))
    
After this, whenever I run any ```conda``` command or ```source```, it fails with this error:

    -bash: /Users/rasmus/anaconda3/bin/conda: /Users/rasmus/anaconda3/bin/python: bad interpreter: No such file or directory

When I run ```which python```, I get only the system python—as though Anaconda isn't even installed.

    /usr/bin/python

How do I recover my conda installation? I have quite a lot of environments customized for separate applications, and I would hate to have to wipe everything.

**Comment by kalefranz** [comment] 2016-09-15 16:02
This is a duplicate of #3433 which will have a patch out today or early tomorrow.  Thanks for the report!

**Closed by kalefranz** 2016-09-15 16:02 UTC

**Comment by scholer** [comment] 2016-09-15 16:16
So... I assume the patch will just prevent this from happening, which is nice. But how do I recover my Anaconda installation, @kalefranz ?

**Comment by kalefranz** [comment] 2016-09-16 03:11
Try rolling back a step or two with `condo list --revisions` and `condo install --revision REVISION_NUMBER`.

**Comment by scholer** [comment] 2016-09-16 18:05
Thanks for the suggestion, @kalefranz , but again, the ```conda``` command was completely broken. I installed Anaconda again by downloading the "Anaconda3-4.1.1 graphical installer", thinking it would fix my installation. But it just installed Anaconda in ```~/anaconda``` rather than ```~/anaconda3```, where my original installation was located. 

I think I have requrements.txt files for most of my old environments, so I will probably just try to re-create each environment when I need it.

**Comment by kalefranz** [comment] 2016-09-16 18:10
You shouldn't have to recreate each environment.  One way to always fix conda is to

1. Download the installer you want from http://repo.continuum.io/miniconda/.  Probably one of those called `Miniconda3-latest-*`.  Let's say you've saved it locally at `~/miniconda.sh`.
2. Run `bash ~/miniconda.sh -bfp ~/anaconda3`.

Conda should be healed at that point.

**Comment by dartdog** [comment] 2016-11-07 16:33
FWIW just had this same thing happen when I was trying to update On Linux 16.04 Spyder from 3.0 to 3.01 I ran  conda update qt pyqt
and got:
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/tom/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    icu-56.1                   |                4        21.9 MB  conda-forge
    jpeg-9b                    |                0         918 KB  conda-forge
    libiconv-1.14              |                3         2.0 MB  conda-forge
    libpng-1.6.26              |                0         297 KB  conda-forge
    libtiff-4.0.6              |                7         507 KB  conda-forge
    libxml2-2.9.4              |                3         4.9 MB  conda-forge
    conda-env-2.5.2            |           py35_0          27 KB  conda-forge
    freetype-2.6.3             |                1         2.8 MB  conda-forge
    conda-4.1.12               |           py35_0         205 KB  conda-forge
    fontconfig-2.11.1          |                3         874 KB  conda-forge
    cairo-1.12.18              |                8         1.1 MB  conda-forge
    pango-1.40.1               |                0         912 KB  conda-forge
    qt-4.8.7                   |                3        31.3 MB  conda-forge
    pyqt-4.11.4                |           py35_1         3.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        71.1 MB

The following NEW packages will be INSTALLED:

    conda-env:  2.5.2-py35_0 conda-forge
    libiconv:   1.14-3       conda-forge
    pango:      1.40.1-0     conda-forge

The following packages will be UPDATED:

    cairo:      1.12.18-6                --> 1.12.18-8     conda-forge
    freetype:   2.5.5-1                  --> 2.6.3-1       conda-forge
    icu:        54.1-0                   --> 56.1-4        conda-forge
    jpeg:       8d-2                     --> 9b-0          conda-forge
    libpng:     1.6.22-0                 --> 1.6.26-0      conda-forge
    libtiff:    4.0.6-2                  --> 4.0.6-7       conda-forge
    libxml2:    2.9.2-0                  --> 2.9.4-3       conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:      4.2.9-py35_0             --> 4.1.12-py35_0 conda-forge
    fontconfig: 2.11.1-6                 --> 2.11.1-3      conda-forge
    pyqt:       5.6.0-py35_0             --> 4.11.4-py35_1 conda-forge
    qt:         5.6.0-0                  --> 4.8.7-3       conda-forge

Proceed ([y]/n)? y

Fetching packages ...
icu-56.1-4.tar 100% |################################| Time: 0:00:08   2.62 MB/s
jpeg-9b-0.tar. 100% |################################| Time: 0:00:00   2.12 MB/s
libiconv-1.14- 100% |################################| Time: 0:00:00   2.63 MB/s
libpng-1.6.26- 100% |################################| Time: 0:00:00 818.28 kB/s
libtiff-4.0.6- 100% |################################| Time: 0:00:00   1.36 MB/s
libxml2-2.9.4- 100% |################################| Time: 0:00:01   4.01 MB/s
conda-env-2.5. 100% |################################| Time: 0:00:00 291.79 kB/s
freetype-2.6.3 100% |################################| Time: 0:00:08 326.57 kB/s
conda-4.1.12-p 100% |################################| Time: 0:00:00 891.85 kB/s
fontconfig-2.1 100% |################################| Time: 0:00:00   1.56 MB/s
cairo-1.12.18- 100% |################################| Time: 0:00:00   1.77 MB/s
pango-1.40.1-0 100% |################################| Time: 0:00:00   1.72 MB/s
qt-4.8.7-3.tar 100% |################################| Time: 0:00:13   2.42 MB/s
pyqt-4.11.4-py 100% |################################| Time: 0:00:01   2.76 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
CondaOSError: OS error: failed to link (src='/home/tom/anaconda3/pkgs/icu-56.1-4/lib/icu/current', dst='/home/tom/anaconda3/lib/icu/current', type=3, error=FileExistsError(17, 'File exists'))
 
So I'll try to reinstall via the miniconda suggestion above..

**Comment by dartdog** [comment] 2016-11-07 16:59
And that did not work out so well see new issue opened here https://github.com/conda/conda/issues/3827

**Comment by albert748** [comment] 2016-12-03 13:52
hi,, the issue still exists on linux installation tarball.

which I've downloaded from anaconda, the version is Anaconda3-4.2.0-Linux-x86_64.sh.

**Comment by uduwage** [comment] 2016-12-07 19:42
I am on el capitan and just did `$conda update --all` ended up with the same error: 

`ondaOSError: OS error: failed to link (src=u'/Users/a/anaconda2/pkgs/futures-3.0.5-py27_0/lib/python2.7/site-packages/concurrent/__init__.py', dst='/Users/a/anaconda2/lib/python2.7/site-packages/concurrent/__init__.py', type=1, error=OSError(17, 'File exists'))`

**Comment by joshpeng** [comment] 2016-12-23 08:02
Just ran into the same error trying to install matplotlib2.0.0rc2 on Windows Subsystem Linux.
```
conda install -c conda-forge/label/rc -c conda-forge matplotlib
```
Result
```
CondaOSError: OS error: failed to link (src=u'/home/josh/anaconda2/pkgs/icu-56.1-4/lib/icu/current', dst='/home/josh/anaconda2/lib/icu/current', type=3, error=OSError(17, 'File exists'))
```
