### ISSUE TITLE
Confused about upgrade vs downgrade?

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3356] opened 2016-08-30 15:44 UTC
Conda sees this as an upgrade:

```
    r-zoo:          1.7_12-r3.2.2_1a    r --> 1.7_13-r3.3.1_0    r
```

but then sees this as a downgrade:

```
    r-assertthat:   0.1-r3.2.2_2a       r --> 0.1-r3.3.1_2       r
```

That seems surprising.  This is with Conda 4.1.11.

**Comment by mcg1969** [comment] 2016-08-30 16:30
I can see why this might be confusing. Build strings like `r3.2.2_2a` and `r3.3.1_2` have absolutely no bearing on whether conda considers a package to be an upgrade or a downgrade. Only the build _number_ matters. The question I would have for @mingwandroid is: what are the underlying build numbers here?

**Comment by mcg1969** [comment] 2016-08-30 16:32
Those are funky dist strings. In the `r_zoo` case, I'm assuming that the version string is `1.7_12` and 1.7_13`, respectively, which normalizes internally to `(1,7,12)` and `(1,7,13)`. So that is indeed an upgrade, no matter what the build strings are.

On the other hand, in the `r-assertthat` case, the version is `0.1` in both cases, so it gets down to the build number.

**Comment by mcg1969** [comment] 2016-08-30 16:37
Answering my own question, on Mac OS at least:
`r-assertthat-0.1-r3.2.2_2a.tar.bz2` has build number 3.
`r-assertthat-0.1-r3.3.1_2.tar.bz2` has build number 2.

**Comment by mingwandroid** [comment] 2016-08-30 16:41
Ouch, that's my fault!

**Comment by mingwandroid** [comment] 2016-08-30 16:42
I will expedite some new builds ..

**Comment by mcg1969** [comment] 2016-08-30 16:45
As a more general issue, perhaps conda's plan output ought to separate build strings and build numbers. 

On one hand, it might also be good for conda to consider that when a build string changes, that it needn't compare the build numbers. The problem is that there really is no current standard for combining the build number and the build string. In theory, the build string can be _anything_, and it need not include the build number at all. In _practice_, the build string is either the build number itself or something like `'%s_%d' % (build_prefix, build_number)`. We could perhaps detect if that's the case and parse appropriately. That is: if the build prefix changes, the build number is not considered when deciding if it's an upgrade/downgrade.

**Comment by mingwandroid** [comment] 2016-08-30 16:50
Is there a way to get build numbers from the conda cli for a list of packages at once?

**Comment by mcg1969** [comment] 2016-08-30 16:50
I don't think so.

**Comment by mingwandroid** [comment] 2016-08-30 16:51
OK. Would be very useful right now! I'll take a quick look at the code.

**Comment by mingwandroid** [comment] 2016-08-30 16:56
`conda search -c r r-assertthat --json` kind of gives me it, but not in a nice single line I can pass through `sort`.

**Comment by mingwandroid** [comment] 2016-08-30 17:14
OK, this is pretty horrible, for some reason, meta.yaml for the recipe was at 2, but the metadata was hotfixed, for osx-64 only. Causing me further head scratching was:

https://github.com/conda/conda/issues/3357

I'm just going to bump it to 4 on all platforms I reckon!

**Comment by ijstokes** [comment] 2017-04-28 19:56
@mcg1969 and @mingwandroid would you say that this issue is now resolved as far as conda interpretation of build numbers goes?

**Comment by mcg1969** [comment] 2017-04-29 17:45
In this particular case conda was not at fault---it was properly interpreting the information it was given. So yes I think we should close this.

**Comment by mcg1969** [comment] 2017-04-29 17:45
I'll do so---please reopen if you disagree!

**Closed by mcg1969** 2017-04-29 17:45 UTC
