### ISSUE TITLE
conda create -n course_py36 python=3.6 --An unexpected error has occurred

### ISSUE THREAD

**Issue by NewKimberly** [conda/conda#5869] opened 2017-08-23 09:57 UTC
(C:\Users\Kim-book\Anaconda3) C:\Users\Kim-book>conda create -n course_py36 python=3.6
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\Kim-book\Anaconda3  (writable)
    default environment : C:\Users\Kim-book\Anaconda3
       envs directories : C:\Users\Kim-book\Anaconda3\envs
                          C:\Users\Kim-book\AppData\Local\conda\conda\envs
                          C:\Users\Kim-book\.conda\envs
          package cache : C:\Users\Kim-book\Anaconda3\pkgs
                          C:\Users\Kim-book\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Users\Kim-book\Anaconda3\Scripts\conda-script.py create -n course_py36 python=3.6`

    Traceback (most recent call last):
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
        timeout=timeout
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\Kim-book\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by iranmatlab** [comment] 2017-09-23 19:16
Hello Friends
I have solved the problem.

This error cause because of different version of python in anaconda and installed python on your system.

when you upgrade anaconda to new version, It has been written in newest version on pyhton (3.6 for me) but i have installed lower version (3.5 for me) of python in my system, so it cause fail in run.

so download newest version of python and install it, then 
**rename** folder of last python to a different name such as "pythoonn"

then conda command will works.

**Comment by kalefranz** [comment] 2017-10-03 02:46
@NewKimberly Can you provide the output of

    conda config --show-sources

and

    set

**Comment by NewKimberly** [comment] 2017-10-05 04:52
thanks @kalefranz
here is the output:
(C:\Users\Kim-book\Anaconda3) C:\Users\Kim-book>conda config --show-sources
==> C:\Users\Kim-book\.condarc <==
ssl_verify: True
channels:
  - defaults

 (C:\Users\Kim-book\Anaconda3) C:\Users\Kim-book>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Kim-book\AppData\Roaming
asl.log=Destination=file
CCHZPATH=C:\CTEX\CTeX\cct\fonts
CCPKPATH=C:\CTEX\CTeX\fonts\pk\modeless\cct\dpi$d
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=LAPTOP-OOV5IG06
ComSpec=C:\WINDOWS\system32\cmd.exe
CONDA_DEFAULT_ENV=C:\Users\Kim-book\Anaconda3
CONDA_PREFIX=C:\Users\Kim-book\Anaconda3
CONDA_PS1_BACKUP=$P$G
configsetroot=C:\WINDOWS\ConfigSetRoot
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\Kim-book
LOCALAPPDATA=C:\Users\Kim-book\AppData\Local
LOGONSERVER=\\LAPTOP-OOV5IG06
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\Kim-book\OneDrive
OS=Windows_NT
Path=C:\Users\Kim-book\Anaconda3;C:\Users\Kim-book\Anaconda3\Library\mingw-w64\bin;C:\Users\Kim-book\Anaconda3\Library\usr\bin;C:\Users\Kim-book\Anaconda3\Library\bin;C:\Users\Kim-book\Anaconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\CTEX\UserData\miktex\bin;C:\CTEX\MiKTeX\miktex\bin;C:\CTEX\CTeX\ctex\bin;C:\CTEX\CTeX\cct\bin;C:\CTEX\CTeX\ty\bin;C:\CTEX\Ghostscript\gs9.05\bin;C:\CTEX\GSview\gsview;C:\CTEX\WinEdt;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Kim-book\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4e03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=(C:\Users\Kim-book\Anaconda3) $P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\Kim-book\AppData\Local\Temp
TMP=C:\Users\Kim-book\AppData\Local\Temp
USERDOMAIN=LAPTOP-OOV5IG06
USERDOMAIN_ROAMINGPROFILE=LAPTOP-OOV5IG06
USERNAME=Kim-book
USERPROFILE=C:\Users\Kim-book
windir=C:\WINDOWS

**Comment by NewKimberly** [comment] 2017-10-05 05:12
thanks @kalefranz 
here is the output:

(C:\Users\Kim-book\Anaconda3) C:\Users\Kim-book>conda config --show-sources
==> C:\Users\Kim-book\.condarc <==
ssl_verify: True
channels:
  - defaults


(C:\Users\Kim-book\Anaconda3) C:\Users\Kim-book>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Kim-book\AppData\Roaming
asl.log=Destination=file
CCHZPATH=C:\CTEX\CTeX\cct\fonts
CCPKPATH=C:\CTEX\CTeX\fonts\pk\modeless\cct\dpi$d
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=LAPTOP-OOV5IG06
ComSpec=C:\WINDOWS\system32\cmd.exe
CONDA_DEFAULT_ENV=C:\Users\Kim-book\Anaconda3
CONDA_PREFIX=C:\Users\Kim-book\Anaconda3
CONDA_PS1_BACKUP=$P$G
configsetroot=C:\WINDOWS\ConfigSetRoot
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\Kim-book
LOCALAPPDATA=C:\Users\Kim-book\AppData\Local
LOGONSERVER=\\LAPTOP-OOV5IG06
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\Kim-book\OneDrive
OS=Windows_NT
Path=C:\Users\Kim-book\Anaconda3;C:\Users\Kim-book\Anaconda3\Library\mingw-w64\bin;C:\Users\Kim-book\Anaconda3\Library\usr\bin;C:\Users\Kim-book\Anaconda3\Library\bin;C:\Users\Kim-book\Anaconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\CTEX\UserData\miktex\bin;C:\CTEX\MiKTeX\miktex\bin;C:\CTEX\CTeX\ctex\bin;C:\CTEX\CTeX\cct\bin;C:\CTEX\CTeX\ty\bin;C:\CTEX\Ghostscript\gs9.05\bin;C:\CTEX\GSview\gsview;C:\CTEX\WinEdt;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Kim-book\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4e03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=(C:\Users\Kim-book\Anaconda3) $P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\Kim-book\AppData\Local\Temp
TMP=C:\Users\Kim-book\AppData\Local\Temp
USERDOMAIN=LAPTOP-OOV5IG06
USERDOMAIN_ROAMINGPROFILE=LAPTOP-OOV5IG06
USERNAME=Kim-book
USERPROFILE=C:\Users\Kim-book
windir=C:\WINDOWS

**Comment by NewKimberly** [comment] 2017-10-05 05:29
@iranmatlab 
thank you for comment.
I have reinstalled the system (only reformed the system hard drive) and installed the newest version of anaconda, but it still fails in run.

**Comment by kalefranz** [comment] 2017-10-05 18:23
Related to or duplicate of #3962.

**Comment by kalefranz** [comment] 2017-10-05 18:24
In the past this error has related to incorrect proxy configuration. Can you explore that as a possibility and report back?

**Comment by kalefranz** [comment] 2017-10-05 18:28
Please move future discussion to #3962.

**Closed by kalefranz** 2017-10-05 18:28 UTC
