### ISSUE TITLE
Invalid value 1502156801.236 for timestamp   ----$conda update --all --yes

### ISSUE THREAD

**Issue by lukemckinstry** [conda/conda#6103] opened 2017-10-08 01:57 UTC
$conda update --all --yes

An unexpected error has occurred.
Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/lukemckinstry/miniconda3  (writable)
    default environment : /Users/lukemckinstry/miniconda3
       envs directories : /Users/lukemckinstry/miniconda3/envs
                          /Users/lukemckinstry/.conda/envs
          package cache : /Users/lukemckinstry/miniconda3/pkgs
                          /Users/lukemckinstry/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/lukemckinstry/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20

`$ /Users/lukemckinstry/miniconda3/bin/conda update --all --yes`

    Traceback (most recent call last):
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/lukemckinstry/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1502156801.236 for timestamp

**Comment by nehaljwani** [comment] 2017-10-08 07:02
Closing as duplicate of https://github.com/conda/conda/issues/6096

**Closed by nehaljwani** 2017-10-08 07:02 UTC
Labels: reso:duplicate
