### ISSUE TITLE
Noarch(type='python') is not a valid NoarchType error importing from Artifactory channel

### ISSUE THREAD

**Issue by analog-cbarber** [conda/conda#8311] opened 2019-02-20 18:17 UTC
## Current Behavior

Using conda 4.6.2 through current version (4.6.4) I get the following error when I try to install a package from a conda channel on our local artifactory server. This error does not occur when using 4.5:

```
kadenz-0.1.4.dev1    | 11 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'https://artifactory.analog.com/artifactory/garage-conda::kadenz-0.1.4.dev1-py_0'.
ValidationError(ValueError("Noarch(type='python') is not a valid NoarchType",),)
Attempting to roll back.

Rolling back transaction: done
```

The entry for the this package from the `repodata.json` on the Artifactory server is:

```
"kadenz-0.1.4.dev1-py_0.tar.bz2" : {
      "build" : "py_0",
      "build_number" : 0,
      "depends" : [ "python >=3.5.*" ],
      "license" : "Apache 2",
      "md5" : "928b777a9aa557e74ba6c139562ce1b0",
      "name" : "kadenz",
      "sha256" : "42145ebce75a6f8b8ec175bad547ba6a73886ed809bdafea7fab1587fe155250",
      "size" : 11228,
      "subdir" : "noarch",
      "timestamp" : 1549393159581,
      "version" : "0.1.4.dev1"
    },
```
Installing the same package from my local `conda-bld` cache using `--use-local` does not fail.
The corresponding entry from my `repodata.json` in my local `conda-bld` is:

```
"kadenz-0.1.4.dev1-py_0.tar.bz2": {
      "build": "py_0",
      "build_number": 0,
      "depends": [
        "python >=3.5.*"
      ],
      "license": "Apache 2",
      "md5": "928b777a9aa557e74ba6c139562ce1b0",
      "name": "kadenz",
      "noarch": "python",
      "sha256": "42145ebce75a6f8b8ec175bad547ba6a73886ed809bdafea7fab1587fe155250",
      "size": 11228,
      "subdir": "noarch",
      "timestamp": 1549393159581,
      "version": "0.1.4.dev1"
    },
```

## Environment Information

<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : foo
    active env location : /Users/cbarber/miniconda3/envs/foo
            shell level : 1
       user config file : /Users/cbarber/.condarc
 populated config files : /Users/cbarber/.condarc
          conda version : 4.6.4
    conda-build version : 3.8.1
         python version : 3.6.7.final.0
       base environment : /Users/cbarber/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cbarber/miniconda3/pkgs
                          /Users/cbarber/.conda/pkgs
       envs directories : /Users/cbarber/miniconda3/envs
                          /Users/cbarber/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.4 requests/2.18.4 CPython/3.6.7 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 102236026:1785187213
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/cbarber/.condarc <==
allow_conda_downgrades: True
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by ivan-gomes** [comment] 2019-02-21 22:46
I am experiencing the issue as well, also with Artifactory and Conda 4.6.[2-4]. Downgrading to Conda 4.5.13 mitigated the issue, although we would like to be using the latest Conda.

**Comment by msarahan** [comment] 2019-02-21 22:48
Aritfactory seems to be presenting information that is not valid.  Artifactory is a 3rd party index, and while conda doesn't intentionally break it, we also make no effort to ensure that it will not break, nor do we "fix" conda when it breaks.

**Comment by anschweitzer** [comment] 2019-02-21 22:55
Can you elaborate on what you in the output for an Artifactory ticket? Also, do you have speculation as to what behavior change between conda 4.5 and 4.6 could be related to this issue? 

Thanks, 

Andy

**Comment by ivan-gomes** [comment] 2019-02-21 22:55
Thank you for responding! Could you please point me to the specification for a valid `repodata.json`? I found mention of it in https://docs.conda.io/projects/conda-build/en/latest/source/resources/package-spec.html, but there is no row for `noarch`.

**Comment by ivan-gomes** [comment] 2019-02-21 22:59
I'm assuming the invalidity you are referring to is the missing `"noarch": "python"` line.

**Comment by analog-cbarber** [comment] 2019-02-22 02:40
Why specifically is that invalid? Why does this work with 4.5? Is this an undocumented change to the repodata.json specification? Where is the documentation for repodata.json for that matter?

I have no idea how Artifactory implements its indexing, but it does not seem unlikely that they are simply using `conda index` from some older version of conda (probably no earlier than 4.3, since that is the version they mention [here](https://www.jfrog.com/confluence/display/RTF/Conda+Repositories#CondaRepositories-ReindexingaCondaRepository).

**Comment by analog-cbarber** [comment] 2019-02-22 04:20
This seems like a strange error to get if the cause is the lack of a "noarch" line in the repodata. If that is the cause, where is the `Noarch(type='python')` entity coming from? It seems like conda is correctly finding the noarch information (possibly from the package itself?) but is barfing when it tries to coerce it to `NoarchType`. 

Does this just require adding support to `NoarchType.coerce` to convert from `Noarch`?

**Comment by analog-cbarber** [comment] 2019-02-25 22:30
The error appears to be coming from `EnumField.box`. I made it dump out the stack from a local conda dev environment (using master branch) and got this:

~~~
 13, in <module>
    sys.exit(main())
  File "/Users/cbarber/ws/conda/conda/cli/main.py", line 117, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/Users/cbarber/ws/conda/conda/exceptions.py", line 1290, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Users/cbarber/ws/conda/conda/exceptions.py", line 1002, in __call__
    return func(*args, **kwargs)
  File "/Users/cbarber/ws/conda/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/cbarber/ws/conda/conda/cli/conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/cbarber/ws/conda/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/Users/cbarber/ws/conda/conda/cli/install.py", line 271, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/Users/cbarber/ws/conda/conda/cli/install.py", line 300, in handle_txn
    unlink_link_transaction.execute()
  File "/Users/cbarber/ws/conda/conda/core/link.py", line 241, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/Users/cbarber/ws/conda/conda/core/link.py", line 534, in _execute
    cls._execute_actions(pkg_idx, axngroup)
  File "/Users/cbarber/ws/conda/conda/core/link.py", line 597, in _execute_actions
    action.execute()
  File "/Users/cbarber/ws/conda/conda/core/path_actions.py", line 863, in execute
    package_tarball_full_path=package_tarball_full_path,
  File "/Users/cbarber/ws/conda/conda/_vendor/auxlib/entity.py", line 771, in from_objects
    return cls(**init_vars)
  File "/Users/cbarber/ws/conda/conda/_vendor/auxlib/entity.py", line 724, in __call__
    instance = super(EntityType, cls).__call__(*args, **kwargs)
  File "/Users/cbarber/ws/conda/conda/_vendor/auxlib/entity.py", line 741, in __init__
    setattr(self, key, kwargs[key])
  File "/Users/cbarber/ws/conda/conda/_vendor/auxlib/entity.py", line 430, in __set__
    instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
  File "/Users/cbarber/ws/conda/conda/models/records.py", line 43, in box
    return super(NoarchField, self).box(instance, instance_type, NoarchType.coerce(val))
  File "/Users/cbarber/ws/conda/conda/_vendor/auxlib/entity.py", line 570, in box
    traceback.print_stack()
failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'https://artifactory.analog.com/artifactory/garage-conda::kadenz-0.1.4.dev1-py_0'.
ValidationError(ValueError("Noarch(type='python') is not a valid NoarchType"))
~~~

**Comment by analog-cbarber** [comment] 2019-02-25 22:45
It appears that the value of `self.package_info.package_metadata` in the `CreatePrefixRecordAction` has the bad value: `PackageMetadata(package_metadata_version=1, noarch=Noarch(type='python'))`. I presume this should have been `PackageMetadata(package_metadata_version=1, noarch='python')`

**Comment by analog-cbarber** [comment] 2019-02-26 00:02
Or perhaps this code is expecting a simple dict parsed from the json file. It looks like the PackageMetadata object is exactly what you get when you use the `read_package_metadata` function on the expanded package directory.

**Comment by analog-cbarber** [comment] 2019-02-26 18:16
I have verified that manually adding `"noarch" : "python"` to the corresponding entry in the `repodata.json` file on the Artifactory server does prevent this error from happening in this case.

Still, it does not seem that it should be failing in this manner. At the very least, you would expect an error stating that the `repodata.json` file is incorrect.

**Comment by analog-cbarber** [comment] 2019-02-27 17:04
Looking at `CreatePrefixRecordAction.execute` where it calls `PrefixRecord.from_objects` there is a commented out line referring to `self.package_info.index_json_record`:
 https://github.com/conda/conda/blob/3bffc380c98decec2d436e45ad274c4b97329722/conda/core/path_actions.py#L853-L857

So it appears that this function expects to get a JSON object (i.e a dict) containing the metadata but is actually being passed a `PackageMetaData` instance. 

If I replace `self.package_info.package_metadata` with `self.package_info.package_metadata.json()` then the conda install completes, but the package does not get installed in the environment's `site-packages/`, so there is something else wrong.

**Comment by analog-cbarber** [comment] 2019-02-27 17:11
Actually, with the above change the package is installed in `<env>/site-packages` but not `<env>/lib/python3.7/site-packages`.

**Comment by analog-cbarber** [comment] 2019-02-27 18:26
I guess the noarch info used to be parsed from `self.package_info.index_json_record`, which comes from the expanded package, but is now parsed from the record that came from `repodata.json`, thus it does not do the necessary noarch path direction in `LinkPathAction.make_file_link_action`.

# Potential fix

I find that if I remove `self.package_info.package_metadata` from the `PrefixRecord.from_objects` call in `CreatePrefixRecordAction.execute`:

~~~python
        self.prefix_record = PrefixRecord.from_objects(
            self.package_info.repodata_record,
            # self.package_info.index_json_record,
            # self.package_info.package_metadata,
            requested_spec=text_type(self.requested_spec),
            paths_data=paths_data,
            files=files,
            link=link,
            url=self.package_info.url,
            extracted_package_dir=extracted_package_dir,
            package_tarball_full_path=package_tarball_full_path,
        )
~~~

and use `package_info.package_metadata` to obtain the noarch info in `LinkPathAction.create_file_link_actions`:

~~~python
        def make_file_link_action(source_path_data):
            # TODO: this inner function is still kind of a mess
            # noarch = package_info.repodata_record.noarch
            noarch = package_info.package_metadata.noarch
            if noarch:
                noarch = noarch.type
            if noarch == NoarchType.python:
                sp_dir = transaction_context['target_site_packages_short_path']
                if sp_dir is None:
                    raise CondaError("Unable to determine python site-packages "
                                     "dir in target_prefix!\nPlease make sure "
                                     "python is installed in %s" % target_prefix)
                target_short_path = get_python_noarch_target_path(source_path_data.path, sp_dir)
~~~

I can successfully install the package.

Is this a correct fix? I don't know if the intention with using the repodata record was to avoid having to extract the information from the package, but it seems that at least in this case the information has already been extracted.

**Comment by analog-cbarber** [comment] 2019-02-27 19:56
My proposed change is breaking tests, so clearly is not correct...

**Comment by analog-cbarber** [comment] 2019-02-27 20:19
Appears to be working better with this:

~~~python
        def make_file_link_action(source_path_data):
            # TODO: this inner function is still kind of a mess
            # noarch = package_info.repodata_record.noarch
            if package_info.package_metadata is not None:
                noarch = package_info.package_metadata.noarch
                if noarch:
                    noarch = noarch.type
            else:
                noarch = package_info.repodata_record.noarch
~~~

**Comment by analog-cbarber** [comment] 2019-02-28 15:06
I don't fully understand what is going on with the PackageMetadata parsing, but I think the right thing to do is to leave the `package_info.package_metadata` in the `PrefixRecord.from_objects` call in place, but hack the `NoarchType.coerce` method to handle `Noarch` instances. It seems like this code should not be importing the `package_info` module, so something like this works but seems overly hacky:

~~~python
    @staticmethod
    def coerce(val):
        # what a mess
        if isinstance(val, NoarchType):
            return val
        if val.__class__.__name__ == 'Noarch':
            tmpval = getattr(val, 'type')
            if isinstance(tmpval, NoarchType):
                return tmpval
~~~

You could just skip the classname check and be satisfied if val supplies an appropriate type attribute and leave it at that.

The fact is that any failure of this coerce method leads to an error that likely won't make much sense to an end user.

**Comment by analog-cbarber** [comment] 2019-03-01 15:16
I don't think Artifactory is in any rush to fix their buggy implementation. So those of using Artifactory are kind of stuck with conda 4.5 for now.

Is there any chance that my fix would be accepted if I were to submit a pull request?

**Comment by ivan-gomes** [comment] 2019-03-04 06:04
> 
> 
> I don't think Artifactory is in any rush to fix their buggy implementation. So those of using Artifactory are kind of stuck with conda 4.5 for now.
> 
> Is there any chance that my fix would be accepted if I were to submit a pull request?

Can't hurt to try @analog-cbarber.

**Comment by kylekeppler** [comment] 2019-03-13 15:07
@analog-cbarber, I am seeing a very similar problem with a package I have hosted on our internal Artifactory that specifies noarch:generic. If I download the package manually and `conda install mypkg.tar.bz2` it works. If I install from Artifactory via `conda install mypkg` (with Artifactory as a channel in .condarc) I get:

```
ERROR conda.core.link:_execute(568): An error occurred while installing package 'myArtifacory::mypkg-0.3-1'.
ValidationError(ValueError("Noarch(type='generic') is not a valid NoarchType"))
Attempting to roll back.

Rolling back transaction: done

ValidationError(ValueError("Noarch(type='generic') is not a valid NoarchType"))
```

This problem is manifest by a third party repo, but the error conda gives makes me think conda has a bug (also?):

```
"Noarch(type='generic') is not a valid NoarchType"
```

**Comment by analog-cbarber** [comment] 2019-03-14 01:33
Yes, I would consider this failure mode to be a conda bug, but clearly Artifactory is not correctly updating the repodata indexes. They have admitted it is a bug, but it remains to be seen how fast they fix it. You would think that given this is a relatively new feature, they would be more sensitive to bug reports.

My proposed conda change does work around this problem, but I have been too busy to get around to signing the developer agreement and submitting a merge request (that might simply be ignored).

The easiest workaround is to downgrade to conda 4.5.

**Comment by kylekeppler** [comment] 2019-03-15 02:54
Downgrading to 4.5 did not solve the problem for me.

@analog-cbarber do you have a link to where this was reported to Artifactory?

**Comment by analog-cbarber** [comment] 2019-03-15 03:12
Downgrading should work. I have upgraded and downgraded several times now. I am using 4.5.13. Are you sure the downgrade worked? 

I had to add this to my `.condarc` file:

~~~
allow_conda_downgrades: true
~~~

**Comment by kylekeppler** [comment] 2019-03-15 15:03
Tried again with 4.5 and it is working. Had to get over some hurdles caused by the downgrade, but the noarch pkg installs correctly now. Thanks!

**Comment by analog-cbarber** [comment] 2019-03-21 12:59
Artifactory has reported back that they don't expect to fix this until the fourth quarter of this year. That's a long time to wait!

**Comment by analog-cbarber** [comment] 2019-04-18 14:43
The workaround is in 4.6.12 so this can probably be closed.

**Comment by jjhelmus** [comment] 2019-04-18 14:46
Thanks @analog-cbarber for the update, closing this issue.

**Closed by jjhelmus** 2019-04-18 14:46 UTC
