### ISSUE TITLE
conda has channels not specified in .condarc file

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2457] opened 2016-05-10 12:28 UTC
`conda info` reports some channels from a localhost installation of Anaconda Repository including tokens (see below, token strings removed by me):

```
$ sudo -u guest /opt/wakari/anaconda/bin/conda info 
Using Anaconda Cloud api site http://localhost:8080/api
Current conda install:

             platform : linux-64
        conda version : 3.19.3
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /opt/wakari/anaconda  (read only)
  default environment : /opt/wakari/anaconda
     envs directories : /home/guest/.conda/envs
                        /home/guest/envs
                        /opt/wakari/anaconda/envs
        package cache : /home/guest/.conda/envs/.pkgs
                        /home/guest/envs/.pkgs
                        /opt/wakari/anaconda/pkgs
         channel URLs : http://localhost:8080/conda/anaconda/linux-64/
                        http://localhost:8080/conda/anaconda/noarch/
                        https://conda.anaconda.org/wakari/linux-64/
                        https://conda.anaconda.org/wakari/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        http://localhost:8080/conda/t/SOME_TOKEN/r/linux-64/
                        http://localhost:8080/conda/t/SOME_TOKEN/r/noarch/
          config file : /opt/wakari/anaconda/.condarc
    is foreign system : False
```

Those last two channel entries are a mystery to me, since here is the config file that `conda info` says is being used, and you can see that it comments out the lines with any tokens involved (and in any case they are to Anaconda Cloud, not to local host, and the 

```
$ cat /opt/wakari/anaconda/.condarc

channels:
  - http://localhost:8080/conda/anaconda
  - https://conda.anaconda.org/wakari
#  - https://conda.anaconda.org/t/DIFFERENT_TOKEN/anaconda-nb-extensions
  - defaults
  - r

create_default_packages:
  - anaconda-client
  - python
  - ipython-we
  - pip
  - r-essentials
```

Where else does conda get channel configuration information from?  If it gets it from anywhere else, why isn't that listed in the output of `conda info`?

**Comment by ijstokes** [comment] 2016-05-10 12:36
OK, I'm going back and forth with this issue being tied to conda or Anaconda Repository.  I think it is a bit of both.  I originally reported it here https://github.com/Anaconda-Platform/anaconda-server/issues/2159 (Anaconda Repository).

I had a brain wave that it could be tied to `anaconda login`, and sure enough once I do `anaconda logout` then those two mystery entries:

```
                        http://localhost:8080/conda/t/SOME_TOKEN/r/linux-64/
                        http://localhost:8080/conda/t/SOME_TOKEN/r/noarch/
```

disappear -- so they are there thanks to some `anaconda login` token.  News to me!

However they are now **replaced** with token-less versions of those same channels:

```
root@anaconda-enterprise / $ sudo -u guest /opt/wakari/anaconda/bin/anaconda logout
Using Anaconda Cloud api site http://localhost:8080/api
logout successful
root@anaconda-enterprise / $ sudo -u guest /opt/wakari/anaconda/bin/conda info 
Using Anaconda Cloud api site http://localhost:8080/api
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /opt/wakari/anaconda  (read only)
  default environment : /opt/wakari/anaconda
     envs directories : /home/guest/.conda/envs
                        /home/guest/envs
                        /opt/wakari/anaconda/envs
        package cache : /home/guest/.conda/envs/.pkgs
                        /home/guest/envs/.pkgs
                        /opt/wakari/anaconda/pkgs
         channel URLs : http://localhost:8080/conda/anaconda/linux-64/
                        http://localhost:8080/conda/anaconda/noarch/
                        https://conda.anaconda.org/wakari/linux-64/
                        https://conda.anaconda.org/wakari/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        http://localhost:8080/conda/r/linux-64/
                        http://localhost:8080/conda/r/noarch/
          config file : /opt/wakari/anaconda/.condarc
    is foreign system : False
```

And even these token-less channels cause problems:

```
$ sudo -u guest /opt/wakari/anaconda/bin/conda create -p /projects/guest/TestProject3/envs/default --clone root
Using Anaconda Cloud api site http://localhost:8080/api
Fetching package metadata: .........Error: Could not find URL: http://localhost:8080/conda/r/linux-64/
```

Please can someone clarify:

1. Hints on how to rectify this situation
2. Which repo I should be reporting this issue against: Anaconda Repository, Conda, or Anaconda Client.

**Comment by kalefranz** [comment] 2016-05-10 14:05
This has been a mystery to me too, and one I haven't dug into yet.  Guess it's time.

@ijstokes Can you `conda uninstall anaconda-client` and see if it changes the output of `conda info`?  After you uninstall anaconda-client, run `hash -r && which anaconda` to make sure it isn't on path anymore.  I want to make sure the behavior is just isolated to conda and that anaconda client isn't somewhere hooking into the conda code.

**Comment by ijstokes** [comment] 2016-05-10 14:30
@kalefranz that removes those channels:

```
root@anaconda-enterprise / $ sudo -u wakari /opt/wakari/anaconda/bin/conda uninstall anaconda-client
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..........
Solving package specifications: .
Package plan for package removal in environment /opt/wakari/anaconda:

The following packages will be REMOVED:

    anaconda-client: 1.2.2-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|############################################################################################| 100%

root@anaconda-enterprise / $ sudo -u guest /opt/wakari/anaconda/bin/conda info 
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /opt/wakari/anaconda  (read only)
  default environment : /opt/wakari/anaconda
     envs directories : /home/guest/.conda/envs
                        /home/guest/envs
                        /opt/wakari/anaconda/envs
        package cache : /home/guest/.conda/envs/.pkgs
                        /home/guest/envs/.pkgs
                        /opt/wakari/anaconda/pkgs
         channel URLs : http://localhost:8080/conda/anaconda/linux-64/
                        http://localhost:8080/conda/anaconda/noarch/
                        https://conda.anaconda.org/wakari/linux-64/
                        https://conda.anaconda.org/wakari/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
          config file : /opt/wakari/anaconda/.condarc
    is foreign system : False
```

But I have to have `anaconda-client` installed, so this may be "informative" but it is not, for me, a "solution" -- I don't think you were suggesting that it should be, but just so we're on the same page.

**Comment by ijstokes** [comment] 2016-05-10 15:42
So the channels are no longer a mystery: they come from anaconda-client.  But:

1. it is unclear to me why there are also channels listed even when a user has logged out; and
2. the error listed in https://github.com/Anaconda-Platform/anaconda-server/issues/2159 (about channel not found) still happens even without the token in the channel URL;
3. Looking at it more carefully it is bizzare that having an anaconda login token would result in conda setting up a channel specifically for R packages.  It looks for:
    * (logged in): http://localhost:8080/conda/t/<TOKEN>/r/linux-64/
    * (logged out): http://localhost:8080/conda/r/linux-64/

Could that be a result of having the `- r` channel listed last in the `.condarc` (see above)?

**Comment by kalefranz** [comment] 2016-05-13 22:02
Discussed on video chat. Closing because this is expected behavior.

**Closed by kalefranz** 2016-05-13 22:02 UTC
