### ISSUE TITLE
conda 4.7 throws various version constraint issues on install

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#8828] opened 2019-06-26 15:43 UTC
AFAICT none of the version constraints listed shows why the install could not proceed. However there are a lot of them. So it is completely possible I've overlooked something here.

Note: This is happening in staged-recipes when converting recipes to feedstocks. We had to rollback to conda 4.6 for now to bypass this issue.

## Current Behavior

```
$ conda install --yes --quiet 'conda-forge-ci-setup=2.*' 'conda-smithy=3.*' conda-forge-pinning git=2.12.2 conda-build

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - certifi -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-build -> beautifulsoup4 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-forge-ci-setup=2 -> anaconda-client -> requests[version='>=2.9.1'] -> urllib3[version='>=1.21.1,<1.25'] -> cryptography[version='>=1.3.4'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-forge/linux-64::conda-package-handling==1.3.9=py37_0 -> libarchive[version='>=3.3.3'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-forge/linux-64::conda==4.7.4=py37_0 -> conda-package-handling[version='>=1.3.0'] -> libarchive[version='>=3.3.3'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-forge/linux-64::python-libarchive-c==2.8=py37_1004 -> libarchive -> openssl[version='>=1.1.1a,<1.1.2a']
  - conda-smithy=3 -> conda[version='>=4.2'] -> conda-package-handling[version='>=1.3.0'] -> libarchive[version='>=3.3.3'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - cryptography -> cffi[version='>=1.7'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - git=2.12.2 -> curl -> krb5[version='>=1.16.3,<1.17.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - libarchive -> openssl[version='>=1.1.1a,<1.1.2a']
  - openssl
  - pkgs/main/linux-64::asn1crypto==0.24.0=py37_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::cffi==1.12.2=py37h2e261b9_1 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::chardet==3.0.4=py37_1 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::idna==2.8=py37_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::pip==19.0.3=py37_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::pycosat==0.6.3=py37h14c3975_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::pycparser==2.19=py37_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::pyopenssl==19.0.0=py37_0 -> cryptography[version='>=2.2.1'] -> cffi[version='>=1.7'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::pysocks==1.6.8=py37_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::python==3.7.3=h0371630_0 -> openssl[version='>=1.1.1b,<1.1.2a']
  - pkgs/main/linux-64::requests==2.21.0=py37_0 -> certifi[version='>=2017.4.17'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::ruamel_yaml==0.15.46=py37h14c3975_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::setuptools==41.0.0=py37_0 -> certifi[version='>=2016.09'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::six==1.12.0=py37_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::urllib3==1.24.1=py37_0 -> certifi -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pkgs/main/linux-64::wheel==0.33.1=py37_0 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
```

https://travis-ci.org/conda-forge/staged-recipes/builds/549908215#L823

### Steps to Reproduce

```
# Install Miniconda.
echo ""
echo "Installing a fresh version of Miniconda."
curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > ~/miniconda.sh
bash ~/miniconda.sh -b -p ~/miniconda
(
    source ~/miniconda/bin/activate root

    # Configure conda.
    echo ""
    echo "Configuring conda."
    conda config --set show_channel_urls true
    conda config --set auto_update_conda false
    conda config --set add_pip_as_python_dependency false
    conda config --add channels conda-forge

    unset conda
    conda update -n root --yes --quiet conda
)
source ~/miniconda/bin/activate root

conda install --yes --quiet conda-forge-ci-setup=2.* conda-smithy=3.* conda-forge-pinning git=2.12.2 conda-build>=3.16
```

ref: https://github.com/conda-forge/staged-recipes/blob/4334174c35fd0052955e0ad94ecb4558516dd990/.travis_scripts/create_feedstocks#L17-L38

## Expected Behavior

The installation occurs without errors.

## Environment Information

Unfortunately this is run on the following line. So we don't get that far.

However as we starting from a fresh Miniconda install. This should be irrelevant for reproducing. Note this is Miniconda 4.6.14 with Python 3 for 64-bit Linux.

**Comment by tkelman** [comment] 2019-06-26 19:36
I think https://github.com/regro/cf-scripts/issues/526 is a near-duplicate of this, with simpler triggering conditions. In that case it was a single package (frozendict) that at the time didn't have a build available for python 3.7, but the conda 4.7 error message was mentioning pip which didn't make sense. I went looking for some other not-recently-updated package as a test case, and `conda config --prepend channels conda-forge && conda update -y --all && conda install -y pywps` also errors in a way that mentions pip inside a pristine docker container of `continuumio/miniconda3:latest`

Don't mind moving this comment to a separate issue if it's a different underlying cause.

**Comment by msarahan** [comment] 2019-06-27 01:35
@tkelman I think you're right.  I'm trying to improve the error messaging.

**Comment by msarahan** [comment] 2019-06-27 01:48
I can't reproduce this with the script above, unfortunately.  I'm not sure if something about the available packages has changed.  I have some tests on improving the messaging, but I'm not sure if it will affect this issue at all.

**Comment by jakirkham** [comment] 2019-06-27 04:32
@msarahan, it's worth noting the problem was sporadic, but did occur more often than not. So running it once unfortunately may not be sufficient. Sorry I don't have better news. 😞

**Comment by jorisvandenbossche** [comment] 2019-06-28 03:23
I am also running in a case where I have an environment that no longer can be created with conda 4.7 and shows a huge list of the packages, without a clear idea which ones are now in conflict: https://travis-ci.org/geopandas/geopandas/jobs/551100679

output:
<details>
```
$ conda env create --file="${ENV_FILE}"
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:
  - descartes -> matplotlib -> freetype[version='>=2.9.1,<3.0a0'] -> libgcc-ng[version='>=7.3.0']
  - descartes -> matplotlib -> freetype[version='>=2.9.1,<3.0a0'] -> libpng[version='>=1.6.34,<1.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - descartes -> matplotlib -> icu[version='>=58.2,<59.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - descartes -> matplotlib -> numpy -> blas==1.0=mkl
  - descartes -> matplotlib -> numpy -> libgfortran-ng[version='>=7,<8.0a0']
  - descartes -> matplotlib -> numpy -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> libffi[version='>=3.2.1,<4.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<6.0a0']
  - descartes -> matplotlib -> pyparsing
  - descartes -> matplotlib -> pyqt=5.9 -> dbus[version='>=1.13.2,<2.0a0'] -> expat[version='>=2.2.6,<3.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> dbus[version='>=1.13.2,<2.0a0'] -> glib[version='>=2.56.2,<2.57.0a0'] -> pcre[version='>=8.42,<9.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libuuid[version='>=1.0.3,<2.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> gstreamer[version='>=1.14.0,<2.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> libxcb[version='>=1.13,<2.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> jpeg[version='>=9b,<10a']
  - descartes -> matplotlib -> pyqt=5.9 -> sip[version='>=4.19.4,<=4.19.8']
  - descartes -> matplotlib -> python-dateutil -> six[version='>=1.5']
  - descartes -> matplotlib -> pytz
  - descartes -> matplotlib -> setuptools -> certifi[version='>=2016.09']
  - descartes -> matplotlib -> subprocess32
  - descartes -> matplotlib -> tornado -> backports_abc[version='>=0.4']
  - descartes -> matplotlib -> tornado -> futures
  - descartes -> matplotlib -> tornado -> singledispatch
  - descartes -> matplotlib -> tornado -> ssl_match_hostname -> backports
  - fiona=1.7 -> click-plugins -> python -> libffi[version='>=3.2.1,<4.0a0'] -> libgcc-ng[version='>=7.2.0']
  - fiona=1.7 -> click-plugins -> python -> libffi[version='>=3.2.1,<4.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - fiona=1.7 -> click-plugins -> python -> ncurses[version='>=6.1,<7.0a0']
  - fiona=1.7 -> click-plugins -> python -> openssl[version='>=1.1.1b,<1.1.2a'] -> ca-certificates
  - fiona=1.7 -> click-plugins -> python -> pip -> setuptools -> certifi[version='>=2016.09']
  - fiona=1.7 -> click-plugins -> python -> pip -> wheel
  - fiona=1.7 -> click-plugins -> python -> readline[version='>=7.0,<8.0a0']
  - fiona=1.7 -> click-plugins -> python -> sqlite[version='>=3.27.2,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - fiona=1.7 -> click-plugins -> python -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - fiona=1.7 -> click-plugins -> python -> xz[version='>=5.2.4,<6.0a0']
  - fiona=1.7 -> cligj
  - fiona=1.7 -> enum34
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> expat[version='>=2.2.5,<3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> freexl[version='>=1.0.5,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> geos[version='>=3.6.2,<3.6.3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> giflib[version='>=5.1.4,<5.2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> hdf4[version='>=4.2.13,<4.2.14.0a0'] -> jpeg[version='>=9b,<10a']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> hdf5[version='>=1.8.18,<1.8.19.0a0'] -> libgfortran-ng[version='>=7.2.0,<8.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> icu[version='>=58.2,<59.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> json-c[version='>=0.13.1,<0.14.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> kealib[version='>=1.4.7,<1.5.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libcurl[version='>=7.60.0,<8.0a0'] -> krb5[version='>=1.16.1,<1.17.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libcurl[version='>=7.60.0,<8.0a0'] -> libssh2[version='>=1.8.2,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> curl
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> libuuid[version='>=1.0.3,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> util-linux
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libkml[version='>=1.3.0,<1.4.0a0'] -> libboost[version='>=1.67.0,<1.67.1.0a0'] -> bzip2[version='>=1.0.6,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libnetcdf[version='>=4.6.1,<5.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libpng[version='>=1.6.34,<1.7.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libpq[version='>=10.3,<11.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libspatialite[version='>=4.3.0a,<4.4.0a0'] -> proj4[version='>=5.2.0,<5.2.1.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libtiff[version='>=4.0.9,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> openjpeg[version='>=2.3.0,<3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> pcre[version='>=8.42,<9.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> freetype[version='>=2.9.1,<3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> glib[version='>=2.56.1,<2.57.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> libxcb[version='>=1.13,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> pixman[version='>=0.34.0,<1.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> poppler-data[version='>=0.4.9']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> xerces-c[version='>=3.2.1,<3.3.0a0']
  - fiona=1.7 -> gdal=2.2 -> numpy[version='>=1.11.3,<2.0a0'] -> blas==1.0=mkl
  - fiona=1.7 -> gdal=2.2 -> numpy[version='>=1.11.3,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - fiona=1.7 -> munch -> six
  - fiona=1.7 -> shapely
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> libffi[version='>=3.2.1,<4.0a0'] -> libgcc-ng[version='>=7.2.0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> libffi[version='>=3.2.1,<4.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1b,<1.1.2a'] -> ca-certificates
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.27.2,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> xz[version='>=5.2.4,<6.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> six
  - matplotlib==2.0.2 -> freetype[version='>=2.8,<2.9.0a0'] -> libpng[version='>=1.6.32,<1.7.0a0']
  - matplotlib==2.0.2 -> functools32
  - matplotlib==2.0.2 -> icu[version='>=58.2,<59.0a0']
  - matplotlib==2.0.2 -> numpy -> blas==1.0=mkl
  - matplotlib==2.0.2 -> numpy -> libgfortran-ng[version='>=7,<8.0a0']
  - matplotlib==2.0.2 -> numpy -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - matplotlib==2.0.2 -> pyparsing
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> dbus[version='>=1.13.2,<2.0a0'] -> expat[version='>=2.2.6,<3.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> dbus[version='>=1.13.2,<2.0a0'] -> glib[version='>=2.56.2,<2.57.0a0'] -> pcre[version='>=8.42,<9.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libuuid[version='>=1.0.3,<2.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> gstreamer[version='>=1.14.0,<2.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> libxcb[version='>=1.13,<2.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> jpeg[version='>=9b,<10a']
  - matplotlib==2.0.2 -> pyqt=5.6 -> sip=4.18
  - matplotlib==2.0.2 -> python-dateutil
  - matplotlib==2.0.2 -> pytz
  - matplotlib==2.0.2 -> setuptools -> certifi[version='>=2016.09']
  - matplotlib==2.0.2 -> subprocess32
  - matplotlib==2.0.2 -> tornado -> backports_abc[version='>=0.4']
  - matplotlib==2.0.2 -> tornado -> futures
  - matplotlib==2.0.2 -> tornado -> singledispatch
  - matplotlib==2.0.2 -> tornado -> ssl_match_hostname -> backports
  - pandas=0.24 -> libgcc-ng[version='>=7.3.0']
  - pandas=0.24 -> libstdcxx-ng[version='>=7.3.0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> blas==1.0=mkl
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0'] -> libopenblas[version='>=0.3.3,<1.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0']
  - pandas=0.24 -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5']
  - pandas=0.24 -> pytz
  - pyproj -> libgcc-ng[version='>=7.3.0']
  - pyproj -> numpy -> blas==1.0=mkl
  - pyproj -> numpy -> libgfortran-ng[version='>=7,<8.0a0']
  - pyproj -> numpy -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> libffi[version='>=3.2.1,<4.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> readline[version='>=7.0,<8.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<6.0a0']
  - pyproj -> proj4[version='>=5.2.0,<5.2.1.0a0']
  - shapely -> geos[version='>=3.7.1,<3.7.2.0a0'] -> libgcc-ng[version='>=7.3.0']
  - shapely -> geos[version='>=3.7.1,<3.7.2.0a0'] -> libstdcxx-ng[version='>=7.3.0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> blas==1.0=mkl
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> libffi[version='>=3.2.1,<4.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> readline[version='>=7.0,<8.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<6.0a0']
```

</details>

The yaml environment file is this one: https://github.com/geopandas/geopandas/blob/master/ci/travis/36-pd024.yaml (but also happens for https://github.com/geopandas/geopandas/blob/master/ci/travis/35-minimal.yaml)

One strange part that I noticed is:

```
...
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> blas==1.0=mkl
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0'] -> libopenblas[version='>=0.3.3,<1.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0']
...
```

where ``mkl_fft`` requires Python 2.7, while this is a Python 3.6 environment that is being created.

**Closed** 2019-06-28 23:56 UTC
