### ISSUE TITLE
unable to build complex packages after migration : absolute installation path hardcoded during install

### ISSUE THREAD

**Issue by xuancong84** [conda/conda#6962] opened 2018-03-01 02:00 UTC
It seems that both Anaconda and Miniconda has hard-coded the absolute installation path into many places during install. After I copy the entire Anaconda/Miniconda folder into a new location, existing packages can still run, but new complex packages will encounter compilation error, i.e., a lot of "path not found".

Steps to reproduce the bug:
1. Use a freshly installed copy of Anaconda/Miniconda to install https://github.com/facebookresearch/fairseq ,  everything goes successfully.
2. Install a freshly installed copy of Anaconda/Miniconda, copy the entire folder into a different location, then use the conda in that new location (must set PATH, LD_LIBRARY_PATH, etc. correctly) to install https://github.com/facebookresearch/fairseq , the compilation fails with many "library not found" errors.

I hope the developer can improve the relocation flexibility of the software. Thanks!

**Comment by kalefranz** [comment] 2018-03-01 02:23
> LD_LIBRARY_PATH

We also highly discourage any use of `LD_LIBRARY_PATH`.  There are *rare* occasions where it must be used during package building.  They are exceedingly rare though.

**Comment by xuancong84** [comment] 2018-03-01 02:24
Thanks! Let me try it first.

**Comment by mingwandroid** [comment] 2018-03-01 05:35
Closing as not a bug. We do not support relocating Anaconda or Miniconda.

**Closed by mingwandroid** 2018-03-01 05:35 UTC
