### ISSUE TITLE
ValueError: failed to parse CPython sys.version: '2.7.11 |Anaconda 2.5.0 (64-bit )| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]'

### ISSUE THREAD

**Issue by SogandKa** [conda/conda#5431] opened 2017-05-25 21:54 UTC
C:\Users\skarba1>conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Users\skarba1\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.
py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\skarba1\AppData\Local\Continuum\Anaconda2\lib\site-packages\con
da\cli\main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\skarba1\AppData\Local\Continuum\Anaconda2\lib\site-packages\con
da\exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "C:\Users\skarba1\AppData\Local\Continuum\Anaconda2\lib\site-packages\con
da\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\skarba1\AppData\Local\Continuum\Anaconda2\lib\site-packages\con
da\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\skarba1\AppData\Local\Continuum\Anaconda2\lib\site-packages\con
da\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\skarba1\AppData\Local\Continuum\Anaconda2\lib\site-packages\con
da\connection.py", line 55, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1498, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1463, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.11 |Anaconda 2.5.0 (64-bit
)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]'

**Comment by kalefranz** [comment] 2017-06-02 07:15
duplicate of 

* https://github.com/conda/conda/issues/4901
* #3606
* #5413
* https://github.com/ContinuumIO/anaconda-issues/issues/1736
* https://github.com/ContinuumIO/anaconda-issues/issues/1667

**Comment by kalefranz** [comment] 2017-06-02 07:15
From https://github.com/conda/conda/issues/4901#issuecomment-287868746

> Here you have two different Python installations and they are stepping on each other's toes.
> 
> I am guessing you elected to allow the installer to add itself to your system `PATH` but already had 'normal' Python 2.7 installed to the default location and also present in your `PATH`?
> 
> Unfortunately our installer adds its entries to the end of `PATH` so DLLs for other software frequently get loaded instead of ours (Python itself consists of many DLLs).
>
> I think, if the Anaconda Installer is going to add to `PATH` it should add its entries to the front of `PATH` like nearly all other installers do, but I more strongly think that software should not add itself to `PATH` by default (or recommend that to users).
>
> If you use the `Anaconda Prompt` to launch your command prompt then that will add the correct entries to the front of your `PATH` temporarily (i.e. for that command prompt instance only).

**Closed by kalefranz** 2017-06-02 07:15 UTC
