### ISSUE TITLE
Update miniconda installers (Python 3.10 & Miniconda 4.13+)

### ISSUE THREAD

**Issue by joelostblom** [conda/conda#11728] opened 2022-08-11 07:56 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

A Miniconda installer with Python 3.10 would be convenient for teaching since novice students would have access to the improved Python error message without updating their Python version first. Are there plans to release this soon together with the new conda version 4.13 or 4.14?

Ref https://github.com/conda/conda-docs/issues/775

**Comment by tarrade** [comment] 2022-09-13 09:51
As now we have conda 4.14 package available on the defaults channel. Any update when will be released miniconda installer new with the new conda version 4.14 and Python 3.10 ? Maybe having a tentative roadmap somewhere on Github could help us to see what are the actual plan. Anaconda is too big for us and since we need to have a reproducible work bench on many machine, we need to use the miniconda installed.  Thanks for providing such great tools

**Comment by EwoutH** [comment] 2022-09-27 10:35
I would really love to see a miniconda installer with Python 3.11. Maybe we can leapfrog to Conda [22.9.0](https://github.com/conda/conda/releases/tag/22.9.0), but please do whatever is faster. Hope we can make it before the Python 3.11 release.

**Comment by EwoutH** [comment] 2022-10-10 17:10
Any update on this?

(@skalburgi @csoja @chenghlee)

**Comment by EwoutH** [comment] 2022-10-18 09:29
@skalburgi @csoja @chenghlee @jezdez Anything to share? Even a quick message that you're still working on it would be fine, or even that the issue is rejected and Python 3.10 miniconda won't be released.

Please just share anything :)

**Comment by csoja** [comment] 2022-10-18 15:18
There are plans to build a Python 3.10 Miniconda installer (and new Miniconda installers with the latest released version of conda).  Unfortunately, we do not yet have line of sight for exactly when it will be built and available.

**Comment by EwoutH** [comment] 2022-10-18 15:27
Thanks for the update! Great to hear, please keep us in the loop :)

**Comment by EwoutH** [comment] 2022-10-27 22:44
Hey @csoja! Do you have anything to share as of this moment?

**Comment by csoja** [comment] 2022-10-28 14:37
Nothing new to share yet...

**Comment by EwoutH** [comment] 2022-11-16 05:18
We're a few weeks further, how is it going?

**Comment by zhangxiaoxing** [comment] 2022-11-28 00:36
Just wanted to let you know that we would greatly benefit from an up-to-date mini-conda release, and we really appreciate all of your hard work.

**Comment by EwoutH** [comment] 2022-12-12 15:39
Thanks for working on this, do you have any news to share?

**Comment by tarrade** [comment] 2022-12-23 13:07
The updated installer was released yesterday. Great
"Latest - Conda 22.11.1 Python 3.10.8 released December 22, 2022"

**Comment by EwoutH** [comment] 2022-12-23 21:37
Awesome! Thanks a lot for updating Miniconda!

Maybe it is useful to document the proces, so it will be easier for future Python and Conda releases.

**Closed** 2023-01-05 17:14 UTC
Labels: source::community, type::task, duplicate::primary, sprint
