### ISSUE TITLE
Conda clean issue

### ISSUE THREAD

**Issue by bwlee** [conda/conda#749] opened 2014-05-29 14:00 UTC
conda failed when do clean --packages.  WinXP, with python program running.

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Develop\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Develop\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in m
ain
    args.func(args, p)
  File "C:\Develop\Anaconda\lib\site-packages\conda\cli\main_clean.py", line 200
, in execute
    rm_pkgs(args)
  File "C:\Develop\Anaconda\lib\site-packages\conda\cli\main_clean.py", line 180
, in rm_pkgs
    rm_rf(join(pkgs_dir, pkg))
  File "C:\Develop\Anaconda\lib\site-packages\conda\install.py", line 143, in rm
_rf
    shutil.rmtree(path)
  File "C:\Develop\Anaconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Develop\Anaconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Develop\Anaconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Develop\Anaconda\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Develop\Anaconda\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] : 'C:\\Develop\\Anaconda\\pkgs\\matplotlib-1.3.1-np18py2
7_2\\Lib\\site-packages\\matplotlib\\_path.pyd'

**Comment by soapy1** [comment] 2016-10-11 22:12
Cannot reproduce this on the newest version of conda. Closing this issue

**Closed by soapy1** 2016-10-11 22:12 UTC
