### ISSUE TITLE
After update to high priority channel, new conda version failed to update packages

### ISSUE THREAD

**Issue by duytrung** [conda/conda#6120] opened 2017-10-09 10:55 UTC
Hi all, I have the following error after updating conda:

```

C:\Users\310 G1
λ conda update --all
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\MyPrograms\Anaconda3:

The following packages will be SUPERSEDED by a higher-priority channel:

    conda: 4.3.28-py36h9daa44c_0 --> 4.3.27-py36hcbae3bd_0

Proceed ([y]/n)? y

conda-4.3.27-p 100% |###############################| Time: 0:00:00 584.15 kB/s

C:\Users\310 G1
λ conda update --all
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\MyPrograms\Anaconda3  (writable)
    default environment : C:\MyPrograms\Anaconda3
       envs directories : C:\MyPrograms\Anaconda3\envs
                          C:\Users\310 G1\AppData\Local\conda\conda\envs
                          C:\Users\310 G1\.conda\envs
          package cache : C:\MyPrograms\Anaconda3\pkgs
                          C:\Users\310 G1\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\310 G1\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.14393
          administrator : False

`$ C:\MyPrograms\Anaconda3\Scripts\conda update --all`




    Traceback (most recent call last):
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\cli\install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506621463.269 for timestamp

```
Please advice. Thanks

TN

**Comment by mchapman87501** [comment] 2017-10-09 11:23
I have the same problem on macOS 10.12.6:
Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /Users/mitchchapman/anaconda3  (writable)
    default environment : /Users/mitchchapman/anaconda3
       envs directories : /Users/mitchchapman/anaconda3/envs
                          /Users/mitchchapman/.conda/envs
          package cache : /Users/mitchchapman/anaconda3/pkgs
                          /Users/mitchchapman/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 503:20

`$ /Users/mitchchapman/anaconda3/bin/conda update --all`




    Traceback (most recent call last):
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/mitchchapman/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080276.026 for timestamp

**Comment by msarahan** [comment] 2017-10-09 13:11
closing as duplicate of #6096

**Closed by msarahan** 2017-10-09 13:11 UTC
