### ISSUE TITLE
conda can't install a specific `ipython`  version 7.19.0

### ISSUE THREAD

**Issue by tipanverella** [conda/conda#10460] opened 2021-01-15 15:30 UTC
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### Steps to Reproduce

1. create a `just_ipython.yml` conda env specification with essentially just:
```
name: just_ipython
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=7.19.0=py38h81c977d_0
```
2.
```bash
conda env create -f just_ipython.yml
```
==> ERROR MSG:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ipython==7.19.0=py38h81c977d_0
```
## Expected Behavior

Just install `ipython` version `7.19.0`

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : base
    active env location :~/miniconda3
            shell level : 1
       user config file : ~/.condarc
 populated config files : ~/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : ~/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : ~/miniconda3/pkgs
                          ~/.conda/pkgs
       envs directories : ~/miniconda3/envs
                          ~/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Linux/2.6.32-754.35.1.el6.x86_64 rhel/6.10 glibc/2.12
                UID:GID : 293049219:293000513
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> ~/.condarc <==
ssl_verify: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at ~/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
awscli                    1.18.209         py38h578d9bd_0    conda-forge
bat                       0.17.1               h48fdc8c_0    conda-forge
botocore                  1.19.49            pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.8            h06a4308_0    defaults
certifi                   2020.12.5        py38h578d9bd_0    conda-forge
cffi                      1.14.4           py38ha65f79e_1    conda-forge
chardet                   4.0.0            py38h578d9bd_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
conda                     4.9.2            py38h578d9bd_0    conda-forge
conda-package-handling    1.7.2            py38h8df0ef7_0    conda-forge
cryptography              3.3.1            py38h2b97feb_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
docutils                  0.15.2           py38h578d9bd_1    conda-forge
expat                     2.2.10               he6710b0_2    defaults
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
git                       2.30.0          pl5320h014a29a_0    conda-forge
htop                      3.0.4                h46c0cb4_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_1    conda-forge
libarchive                3.3.3             hddc7a2b_1008    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libnl                     3.2.25               h516909a_0    conda-forge
libsolv                   0.7.16               h8b12597_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.7.6            py38h4c9354d_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.32.0               h36c2ea0_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.5                h7579374_1    defaults
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
reproc                    14.2.1               h36c2ea0_0    conda-forge
reproc-cpp                14.2.1               h58526e2_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rsa                       4.4.1              pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.87          py38h7b6447c_1    defaults
s3transfer                0.3.3            py38h32f6830_2    conda-forge
setuptools                51.0.0           py38h06a4308_2    defaults
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tqdm                      4.55.1             pyhd8ed1ab_0    conda-forge
tree                      1.8.0                h516909a_1    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
vim                       8.2.2305         py38h526f742_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                hdf46e1d_0    conda-forge

```
</p></details>

**Comment by tipanverella** [comment] 2021-01-25 16:09
Hey,  could someone please look into this?

**Comment by FrugoFruit90** [comment] 2021-02-01 08:29
Just had the same problem.

**Comment by chenghlee** [comment] 2021-02-01 18:02
Due to a [jedi dependency problem](https://github.com/conda-forge/ipython-feedstock/issues/125), conda-forge has marked this specific build of ipython as broken:
```
$ conda search -c conda-forge/label/broken --platform=linux-64 ipython=7.19.0=py38h81c977d_0
Loading channels: done
# Name                       Version           Build  Channel             
ipython                       7.19.0  py38h81c977d_0  conda-forge/label/broken
```

To resolve this, you can change the package build string from `py38h81c977d_0` to either `py38h81c977d_1` or `py38h81c977d_2`. (I would _not_ recommend adding `conda-forge/label/broken` as a channel, as that makes it highly likely that your environment will be in a non-usable state.)

Closing this issue as it's not a bug in conda.

**Closed by chenghlee** 2021-02-01 18:02 UTC

**Comment by tipanverella** [comment] 2021-02-04 15:06
Thank you
