### ISSUE TITLE
"Error: MD5 sums mismatch for download" with conda 4.0.3 [FIXED]

### ISSUE THREAD

**Issue by lyndb** [conda/conda#2232] opened 2016-03-10 21:26 UTC
After updating conda for both Anaconda and Anaconda 3, I get errors like the above for any package I try to update. 

conda 4.0.3

Ubuntu 14.04 64 bit.

**Comment by MarkCWirt** [comment] 2016-03-10 21:38
I'm on the same platform and have been having this issue for the past few hours (fresh install) on a variety of packages (e.g., libsodium).

The issue seems to be somewhat intermittent.

**Comment by kalefranz** [comment] 2016-03-10 21:41
ack. Working on it.

**Comment by jjhelmus** [comment] 2016-03-10 21:45
Can confirm this bug, the hash is always reported as d41d8cd98f00b204e9800998ecf8427e if that helps.

```
Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/linux-64/patchelf-0.8-0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != 66d5849a6e2cfb103162540589e87c64)
```

**Comment by jenisys** [comment] 2016-03-10 21:49
Same problem exists on OSX after update to conda 4.0.3 (and pip-8.1.0).
Other packages seem to have the checksum-mismatch problem.

```
Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/osx-64/jupyter_core-4.1.0-py35_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != 48d7d3f0bb04b28d41082e80589623ec)
```

Problem exist in different conda environments (with python2.7 and python3.5). It seems also to be not possible to create a new conda environment.

**Comment by jjhelmus** [comment] 2016-03-10 21:52
If anyone gets stuck trying to downgrade to conda 4.0.2 you can still install conda package from a file to bypass the md5 check:

```
$ conda --version
conda 4.0.3
$ conda install conda=4.0.2
...
Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/linux-64/conda-4.0.2-py35_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != 6dc7d788a7e2fde2dcdcb39b2a6f8824)
$ wget https://repo.continuum.io/pkgs/free/linux-64/conda-4.0.2-py35_0.tar.bz2
$ conda install conda-4.0.2-py35_0.tar.bz2
$ conda --version
conda 4.0.2

**Comment by MarkCWirt** [comment] 2016-03-10 21:57
Yea, I know they're working on it (and have perhaps pushed a fix, so this could be spurious), but conda 4.0.2 seems to be working for me.

**Comment by kalefranz** [comment] 2016-03-10 21:58
We pulled `4.0.3` (forbidden?) from the repo.  Anything automated should revert back to `4.0.2` now.

**Comment by kalefranz** [comment] 2016-03-10 22:06
git bisect shows #2217 as the cause

**Comment by mcg1969** [comment] 2016-03-10 22:10
<red faced>

**Comment by kalefranz** [comment] 2016-03-10 22:36
Hey @mcg1969, just as much my fault.  I merged the PR with the line of code not having coverage.  Lesson learned.

**Comment by jenisys** [comment] 2016-03-10 23:02
conda-4.0.4 seems to be OK.

**Comment by thomco** [comment] 2016-03-11 00:02
How do I install / update to 4.0.4.
If conda 4.0.3 is installed, `conda update conda` fails with MD5 sums mismatch.
I can download the 4.0.4 from here:
https://repo.continuum.io/pkgs/free/win-64/conda-4.0.4-py35_0.tar.bz2

But, not sure how to install correctly into my Anaconda root environment.

**Comment by mcg1969** [comment] 2016-03-11 00:06
This should do it:

`conda install -f conda==4.0.2`
`conda update conda`

**Comment by thomco** [comment] 2016-03-11 00:09
Thanks.   Unfortunately, does not work.  
I get MD5 error when downgrading to 4.0.2, even with the force flag on:
```
> conda install -f conda==4.0.2
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Thomas\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.0.2                |           py35_0         231 KB

The following packages will be DOWNGRADED:

    conda: 4.0.3-py35_0 --> 4.0.2-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-4.0.2-py 100% |###############################| Time: 0:00:00   0.00  B/s
conda-4.0.2-py 100% |###############################| Time: 0:00:00   0.00  B/s
conda-4.0.2-py 100% |###############################| Time: 0:00:00  15.21 MB/s
conda-4.0.2-py 100% |###############################| Time: 0:00:00   0.00  B/s
Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/win-64/conda-4.0.2-py35_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != c8361872771e934944aea18992dcdaac)
```

**Comment by thomco** [comment] 2016-03-11 00:14
```
Following the instructions from jjhelmus in previous comment worked:
> conda install conda-4.0.4-py35_0.tar.bz2
[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

> conda --version
conda 4.0.4
```

**Comment by mcg1969** [comment] 2016-03-11 00:20
Ah, good stuff. I guess I got lucky.

**Comment by kalefranz** [comment] 2016-03-11 01:09
For anyone coming to this thread now, it unfortunately turns out that backing out of this isn't all that easy. You actually need to back up to your previous version of conda, and then you can update to conda latest (right now `4.0.4`).

The output of

    ls $(/conda/bin/conda info | grep cache | cut -d: -f2) | grep -E "^conda-\d"

should show you the version numbers available in your cache. Then from there, for example if `3.19.3` was the version number indicated

    conda install conda=3.19.3

Sorry for the trouble.

**Comment by talumbau** [comment] 2016-03-11 04:17
I don't think I understand the underlying cause of this issue enough to resolve my situation. I am trying to deploy a Heroku application using a version of the [conda-buildpack](https://github.com/kennethreitz/conda-buildpack). I thought that hardcoding my conda version to an earlier version would fix the issue, as I assumed it was some problem with a particular version of conda. However, I continue to specify older and older versions of conda and keep getting the MD5 error. When deploying to Heroku, the buildpack essentially installs on a clean box. Do you have a suggestion on how to work around this issue so I can deploy to Heroku?

**Comment by jakevdp** [comment] 2016-03-11 04:30
@talumbau – The root of the problem is that **conda 4.0.3 cannot download new packages**. You can, however, install packages you've already downloaded and cached. So even if you do ``conda install conda=4.0.2``, if your current installed version is 4.0.3 and you don't have 4.0.2 cached, you will get an error.

What you need to do is to find an older version of conda cached on your system (see @kalefranz's comment above), switch to this first, and then do ``conda update conda`` from there.

**Comment by talumbau** [comment] 2016-03-11 04:36
Ah @jakevdp I see thanks. In this case, since my issue is a deployment on Heroku, I am essentially starting from scratch each time I deploy. Therefore, I have to try to get a version of miniconda that has as its root environment a conda before 4.0.3, and then, when I install packages with that conda, make sure  I don't get a version of conda that is 4.0.3. If I have misunderstood, or if what I am saying is not making sense, the best answer for me would be instructions on what to do in the case that you have no existing version of conda installed on your system (since that is my case in a Heroku deployment).

**Comment by flybonzai** [comment] 2016-03-11 05:08
I can see with the ls command that 4.0.2 is in my cache:

conda-4.0.2-py35_0.tar.bz2.part
conda-4.0.3-py35_0
conda-4.0.4-py35_0.tar.bz2.part

But when I run conda install -f conda=4.0.2 I get the same md5 error:

Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/osx-64/conda-4.0.2-py35_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != 36c89aacc29e84de28b8e8a0e5807f1f)

**Comment by talumbau** [comment] 2016-03-11 05:21
@flybonzai yes I have same problem. For example, using Miniconda2-3.19, conda 3.19.0 is included in the download, or at least, that is what it looks like when examining the non-binary portions of the file .sh file. But then when I specify a `conda install -f conda=3.19.0` it tries to download conda v.3.19.0 and then fails because it tries to do this download with conda v.4.0.3. I am doing this with Heroku buildpacks, so there is an additional level of indirection for me, but I appear to have trouble switching the root environment conda to be something other than version 4.0.3, so therefore my deployment fails.

**Comment by flybonzai** [comment] 2016-03-11 05:26
I just uninstalled and reinstalled ( on Mac).  Upgraded to 4.0.4, so hopefully I'm good.

**Comment by jakevdp** [comment] 2016-03-11 06:04
You could manually download the file you need, and put it in the cache. Then the conda command should work.

**Comment by talumbau** [comment] 2016-03-11 06:23
I was mistaken about the environment and it appears that conda version 4.0.1 was in my miniconda install, so I was able to proceed. @kalefranz's suggestion above did it for me. The issue is that the buildpack environment is ephemeral until a build succeeds, then it stays around. It was difficult to get the miniconda environment printed out while the buildpack executes, but for others who may hit this problem, I would suggest adding something like:

```
conda install conda=4.0.1
```
Just above this line:

https://github.com/kennethreitz/conda-buildpack/blob/master/bin/steps/conda_compile#L13

If your application has been around for a while, it's likely you have that version of conda in your cache.

**Comment by mcg1969** [comment] 2016-03-11 15:27
We need to keep this issue open for awhile until any remaining problems are cleared out.

**Comment by kalefranz** [comment] 2016-03-11 16:23
Alternate solution:

    conda list --revisions

Figure out which rev number you want to roll back to...

    conda install --revision NUMBER

**Comment by diego898** [comment] 2016-03-11 17:51
Hello, just documenting what worked for me, as trying to install `4.0.2` didn't work for me either.

```
➜  ~ ls $(~/anaconda/bin/conda info | grep cache | cut -d: -f2) | grep -E "^conda-\d"
Using Anaconda Cloud api site https://api.anaconda.org
conda-3.18.8-py35_0/
conda-3.18.9-py35_0/
conda-3.18.9-py35_0.tar.bz2
conda-3.19.0-py35_0/
conda-3.19.0-py35_0.tar.bz2
conda-3.19.1-py35_0/
conda-3.19.1-py35_0.tar.bz2
conda-3.19.3-py35_0/
conda-3.19.3-py35_0.tar.bz2
conda-4.0.0-py35_0/
conda-4.0.0-py35_0.tar.bz2
conda-4.0.2-py35_0.tar.bz2.part
conda-4.0.3-py35_0/
conda-4.0.3-py35_0.tar.bz2
conda-4.0.4-py35_0/
conda-4.0.4-py35_0.tar.bz2

➜  ~ conda install -f conda=3.19.3
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ..........

Package plan for installation in environment /Users/diego/anaconda:

The following packages will be DOWNGRADED:

    conda: 4.0.3-py35_0 --> 3.19.3-py35_0

Proceed ([y]/n)? y

[      COMPLETE      ]|###################################################| 100%
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%

➜  ~ conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ....................
Package plan for installation in environment /Users/diego/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-20.2.2          |           py35_0         458 KB
    conda-4.0.4                |           py35_0         188 KB
    pip-8.1.0                  |           py35_0         1.6 MB
    ------------------------------------------------------------
                                           Total:         2.2 MB

The following packages will be UPDATED:

    conda:      3.19.3-py35_0 --> 4.0.4-py35_0
    openssl:    1.0.2d-0      --> 1.0.2g-0
    pip:        8.0.3-py35_0  --> 8.1.0-py35_0
    setuptools: 20.1.1-py35_0 --> 20.2.2-py35_0

Proceed ([y]/n)? y

Fetching packages ...
setuptools-20. 100% |################################| Time: 0:00:00   1.00 MB/s
conda-4.0.4-py 100% |################################| Time: 0:00:00 612.05 kB/s
pip-8.1.0-py35 100% |################################| Time: 0:00:00   1.97 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
```

**Comment by timlincool** [comment] 2016-03-15 01:26
Hi,My conda version was 4.0.4 and CentOS release 6.4, 
I try "conda install -c r r-essentials",Error message was
 "MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/r-bh-1.58.0_1-r3.2.2_0.tar.bz2 (34907a572898a623c98e80e8e72e9cf6 != 90915873ed8920f10b40d66229595686)`"

So I try to downgrading to 4.0.2,it works.but when I try "conda install -c r r-essentials" again,
it's shows,

`   
   r-xtable:       1.8_0-r3.2.2_0    
    r-xts:          0.9_7-r3.2.2_0    
    r-yaml:         2.1.13-r3.2.2_1   
    r-zoo:          1.7_12-r3.2.2_1   

The following packages will be UPDATED:

    conda:          4.0.2-py27_0 --> 4.0.4-py27_0      

Proceed ([y]/n)? y

Fetching packages ...
r-bh-1.58.0_1- 100% |############################################################################################################################################################
Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/r-bh-1.58.0_1-r3.2.2_0.tar.bz2 (34907a572898a623c98e80e8e72e9cf6 != 90915873ed8920f10b40d66229595686)`

It still not working, can anyone  help me?

**Comment by lpantano** [comment] 2016-03-15 18:40
Same here. Same issue. Got conda 4.0.4, only packages related to r are not working for me.

**Comment by kalefranz** [comment] 2016-03-16 19:37
The r packages issue was with anaconda.org.  Verified that it's now fixed for https://conda.anaconda.org/r/linux-64/r-bh-1.58.0_1-r3.2.2_0.tar.bz2

**Closed by kalefranz** 2016-03-16 19:37 UTC
Labels: bug, high priority

**Comment by cwhits** [comment] 2016-04-13 16:43
I'm having this happen going `conda: 4.0.3-py27_0 --> 4.0.5-py27_0` on OS X. Should I open a new issue? 

`Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/osx-64/conda-4.0.5-py27_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != 7954569e1a09d0a20348a6950144a478)`

**Comment by kalefranz** [comment] 2016-04-19 03:19
@cwhits See the solution above, here: https://github.com/conda/conda/issues/2232#issuecomment-195437845
