### ISSUE TITLE
conda-env 2.6.0 for Linux can't import yaml

### ISSUE THREAD

**Issue by ifosch** [conda/conda#3775] opened 2016-10-31 19:30 UTC
Hi!

I'm preparing a presentation on Conda for the Barcelona sysadmin community, and I found that latest conda-env=2.6.0 on Linux is broken. I can't export or use it in any way, since it can't import yaml, even when it should be there installed by conda setup.

I managed to workaround this using Miniconda, 3 and 2, 4.1.11, but when I get to install conda-build, it upgrades to the latest conda-env, no matter what I do, so I can't use it anymore. I have other issues with conda-build, but I'll create another issue there.

I've tried this on Ubuntu Trusty 64 and Xenial 64 vagrant boxes on VirtualBox.

Example conda info:
```
vagrant@vagrant-ubuntu-trusty-64:~$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/vagrant/miniconda2  (writable)
    default environment : /home/vagrant/miniconda2
       envs directories : /home/vagrant/miniconda2/envs
          package cache : /home/vagrant/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
```

Error I get using conda env export:
```
vagrant@vagrant-ubuntu-trusty-64:~$ conda env export -n my-env > my-env.yml
Traceback (most recent call last):
  File "/home/vagrant/miniconda2/bin/conda-env", line 4, in <module>
    import conda_env.cli.main
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 35, in <module>
    from . import main_attach
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_env/env.py", line 17, in <module>
    from . import yaml
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda_env/yaml.py", line 8, in <module>
    import yaml
ImportError: No module named yaml
```

**Comment by rscohn2** [comment] 2016-11-01 11:25
The latest miniconda has the problem. With this script:
```
#! /bin/bash -x
rm -rf testconda
wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod +x Miniconda3-latest-Linux-x86_64.sh
cksum ./Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh -b -p testconda
testconda/bin/conda create -y -n test2 xz
testconda/bin/conda env remove -n test2
```

I see this output:

```
rscohn1@fxsatlin01$ ./x.sh
+ rm -rf testconda
+ wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
+ chmod +x Miniconda3-latest-Linux-x86_64.sh
+ cksum ./Miniconda3-latest-Linux-x86_64.sh
709979015 33905474 ./Miniconda3-latest-Linux-x86_64.sh
+ ./Miniconda3-latest-Linux-x86_64.sh -b -p testconda
PREFIX=/nfs/site/home/rscohn1/local/tmp/testconda
installing: python-3.5.2-0 ...
installing: conda-env-2.6.0-0 ...
installing: openssl-1.0.2j-0 ...
installing: pycosat-0.6.1-py35_1 ...
installing: readline-6.2-2 ...
installing: requests-2.11.1-py35_0 ...
installing: ruamel_yaml-0.11.14-py35_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: xz-5.2.2-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.2.11-py35_0 ...
installing: pycrypto-2.6.1-py35_4 ...
installing: pip-8.1.2-py35_0 ...
installing: wheel-0.29.0-py35_0 ...
installing: setuptools-27.2.0-py35_0 ...
Python 3.5.2 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
+ testconda/bin/conda create -y -n test2 xz
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /nfs/site/home/rscohn1/local/tmp/testconda/envs/test2:

The following NEW packages will be INSTALLED:

    xz: 5.2.2-0

Linking packages ...
[      COMPLETE      ]|| 100%
#
# To activate this environment, use:
# > source activate test2
#
# To deactivate this environment, use:
# > source deactivate test2
#

+ testconda/bin/conda env remove -n test2
Traceback (most recent call last):
  File "/nfs/site/home/rscohn1/local/tmp/testconda/bin/conda-env", line 4, in <module>
    import conda_env.cli.main
  File "/nfs/site/home/rscohn1/local/tmp/testconda/lib/python3.5/site-packages/conda_env/cli/main.py", line 35, in <module>
    from . import main_attach
  File "/nfs/site/home/rscohn1/local/tmp/testconda/lib/python3.5/site-packages/conda_env/cli/main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "/nfs/site/home/rscohn1/local/tmp/testconda/lib/python3.5/site-packages/conda_env/env.py", line 17, in <module>
    from . import yaml
  File "/nfs/site/home/rscohn1/local/tmp/testconda/lib/python3.5/site-packages/conda_env/yaml.py", line 8, in <module>
    import yaml
ImportError: No module named 'yaml'
rscohn1@fxsatlin01$
```

**Comment by justincely** [comment] 2016-11-01 16:59
I get this same traceback when trying to use some of the built-in conda commands with a fresh install of miniconda on osx.  e.g. `conda env list` spits out this traceback.

I got around it by `conda install pyyaml` but it seems like the miniconda install should come bundled with this.

**Comment by ifosch** [comment] 2016-11-01 18:08
@justincely it's funny, I'm using conda on osx myself, latest version although not a fresh install, and I haven't found this problem ...:
```
❯ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 2.0.7
         python version : 3.4.5.final.0
       requests version : 2.9.1
       root environment : /Users/ifosch/.miniconda3  (writable)
    default environment : /Users/ifosch/.miniconda3/envs/conda-intro
       envs directories : /Users/ifosch/.miniconda3/envs
          package cache : /Users/ifosch/.miniconda3/pkgs
           channel URLs : https://conda.binstar.org/natx/osx-64
                          https://conda.binstar.org/natx/noarch
                          https://conda.anaconda.org/binstar/osx-64
                          https://conda.anaconda.org/binstar/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ifosch/.condarc
           offline mode : False
```

I also used the Miniconda3 4.2.11 (fresh install) on raspbian on a RPi, and it works ok.

**Comment by dopplershift** [comment] 2016-11-01 18:34
Duplicate of #3756.

**Comment by ssolari** [comment] 2016-11-01 18:53
+1 our entire continuous integration is broken on Circle CI due to this. 
#3756 was closed, but the following commands are raising errors.  Again this is on CircleCI linux. 
```python
conda update --yes --quiet conda conda-env
conda env create -n my_env -f environment.yml
```

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-env", line 4, in <module>
    import conda_env.cli.main
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_env/cli/main.py", line 35, in <module>
    from . import main_attach
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_env/cli/main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_env/env.py", line 17, in <module>
    from . import yaml
  File "/home/ubuntu/miniconda/lib/python3.5/site-packages/conda_env/yaml.py", line 8, in <module>
    import yaml
ImportError: No module named 'yaml'
```
Conda_env needs the yaml package by default.  Please fix!

**Comment by dopplershift** [comment] 2016-11-01 18:55
There's hasn't been a new release of conda or miniconda yet; the bug is closed since the fix has been committed to master.

**Comment by ssolari** [comment] 2016-11-01 18:58
Got it. Thanks!

**Comment by kalefranz** [comment] 2016-11-02 16:15
fixed in https://github.com/conda/conda/pull/3740

**Closed by kalefranz** 2016-11-02 16:15 UTC
