### ISSUE TITLE
Allow changeps1 excluding base environment

### ISSUE THREAD

**Issue by ATXMJ** [conda/conda#9553] opened 2019-12-30 21:13 UTC
I like having both `auto_activate_base` and `changeps1` set to **true**, but would prefer the PS1 value to be unmodified for the base environment.

My recommendation would be to add a `changeps1_for_base` that defaults to **true**, and has no effect if `changeps1` is set to **false**, but determines whether or not to modify the PS1 value for the base environment if `changeps1` is set to **true**.

**Comment by msarahan** [comment] 2019-12-30 21:24
duplicate of 

https://github.com/conda/conda/issues/9137
https://github.com/conda/conda/issues/8169
https://github.com/conda/conda/issues/8535

As mentioned in https://github.com/conda/conda/issues/8169#issuecomment-492767377, this issue is something we'd love help with, but we can't dedicate our time to fixing it.

**Closed by msarahan** 2019-12-30 21:24 UTC
