### ISSUE TITLE
Conda "install" removes existing packages without any reason

### ISSUE THREAD

**Issue by krestjaninoff** [conda/conda#3603] opened 2016-10-11 12:15 UTC
For some reason "conda install" command tries to remove existing packages without any reason. Below you can see the way to reproduce the problem:

_Install Anaconda_:

``` bash
wget -O anaconda.sh https://repo.continuum.io/archive/Anaconda3-4.1.1-Linux-x86_64.sh
./anaconda.sh -b -p /opt/anaconda3
export PATH=/opt/anaconda3/bin:$PATH
```

_Install the latest Conda version_:

``` bash
conda update conda

Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /opt/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    anaconda-custom            |           py35_0           3 KB
    ruamel_yaml-0.11.14        |           py35_0         377 KB
    conda-4.2.9                |           py35_0         374 KB
    ------------------------------------------------------------
                                           Total:         755 KB

The following packages will be UPDATED:

    anaconda:    4.1.1-np111py35_0 --> custom-py35_0
    conda:       4.1.6-py35_0      --> 4.2.9-py35_0
    conda-env:   2.5.1-py35_0      --> 2.6.0-0
    ruamel_yaml: 0.11.7-py35_0     --> 0.11.14-py35_0
```

_Provision conda environment from a config file_:

``` bash
cat environment.yml

dependencies:
- matplotlib == 1.5.3
- numpy == 1.11.1
- pandas == 0.18.1
- pytest == 2.9.2
- pytz == 2016.6.1
- PyYAML == 3.12
- scikit-learn == 0.18
- pip:
  - python-logstash == 0.4.6
  - usaddress == 0.5.7

conda env update -n root -f environment.yml
```

_Install a new package_:

``` bash
conda install twisted

Fetching package metadata .......
Solving package specifications: ...........
Warning: >10 possible package resolutions (only showing differing packages):
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  ... and others

Package plan for installation in environment /opt/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    zope-1.0                   |           py35_0          912 B
    zope.interface-4.3.2       |           py35_0         216 KB
    twisted-16.4.1             |           py35_0         3.5 MB
    ------------------------------------------------------------
                                           Total:         3.7 MB

The following NEW packages will be INSTALLED:

    twisted:        16.4.1-py35_0
    zope:           1.0-py35_0
    zope.interface: 4.3.2-py35_0

The following packages will be REMOVED:

    jpeg:           8d-2
    matplotlib:     1.5.3-np111py35_0
    openssl:        1.0.2j-0
    pyqt:           4.11.4-py35_3
    pytz:           2016.6.1-py35_0
    pyyaml:         3.12-py35_0
    qt:             4.8.7-3
    requests:       2.11.1-py35_0
    scikit-learn:   0.17.1-np111py35_2
    scipy:          0.18.1-np111py35_0
    setuptools:     27.2.0-py35_0
    sip:            4.18-py35_0
```

_"Twisted" doesn't have any tricky dependencies_:

```
conda info twisted

twisted 16.4.1 py35_0
---------------------
file name   : twisted-16.4.1-py35_0.tar.bz2
name        : twisted
version     : 16.4.1
build number: 0
build string: py35_0
channel     : defaults
size        : 3.5 MB
date        : 2016-09-16
fn          : twisted-16.4.1-py35_0.tar.bz2
license     : MIT
md5         : 34dafe3beea70c45288c422f8c8e20d9
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/linux-64/twisted-16.4.1-py35_0.tar.bz2
dependencies:
    python 3.5*
    zope.interface >=4.0.2
```

So, **why does Conda want to remove a half of previously installed packages?** (even setuptools and requests)

The same happens when I try to install any other package:

``` bash
conda install requests
Fetching package metadata .......
Solving package specifications: ..........
Warning: 8 possible package resolutions (only showing differing packages):
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, pyyaml-3.11-py35_4.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, pyyaml-3.12-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2

Package plan for installation in environment /opt/anaconda3:

The following packages will be REMOVED:

    jpeg:         8d-1
    matplotlib:   1.5.1-np111py35_0
    openssl:      1.0.2j-0
    pyqt:         5.6.0-py35_0
    pytz:         2016.6.1-py35_0
    pyyaml:       3.12-py35_0
    qt:           5.6.0-1
    requests:     2.10.0-py35_0
    scikit-learn: 0.18-np111py35_0
    scipy:        0.17.1-np111py35_1
    setuptools:   27.2.0-py35_0
    sip:          4.18-py35_0
```

**Comment by krestjaninoff** [comment] 2016-10-17 15:49
Is anyone here? )

**Comment by ma-ba** [comment] 2016-10-25 17:52
Should be a duplicate of #3478.

**Closed** 2017-05-02 04:47 UTC

**Comment by ArthurAttout** [comment] 2019-05-12 12:36
So .. Is there still no reason why Conda removes those packages ? ..

**Comment by sk-sahu** [comment] 2019-06-10 07:29
Same here also. I am trying to install a package and without any reason some other necessary packages are being removed.

**Comment by tex** [comment] 2019-12-29 15:13
Yep. I have same problem.

**Comment by Dammi87** [comment] 2020-01-13 10:33
Same here, although I haven't tried it with an updated conda yet.

```
==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\Users\Adam.Fjelsted\AppData\Local\Continuum\miniconda3\envs\vaktin

  added / updated specs:
    - py2exe


The following NEW packages will be INSTALLED:

  py2exe             kieranharding/win-64::py2exe-0.9.2.0-py34_0

The following packages will be REMOVED:

  dash-bootstrap-components-0.8.1-py36_0
  soupsieve-1.9.4-py36_0```

**Comment by AdamMiltonBarker** [comment] 2020-09-04 07:12
Same here:


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    hdf5-1.10.2                |       hba1933b_1         5.2 MB
    libtiff-4.1.0              |       h2733197_1         607 KB
    lz4-c-1.9.2                |       he6710b0_1         253 KB
    zstd-1.4.5                 |       h9ceee32_0         716 KB
    ------------------------------------------------------------
                                           Total:         6.7 MB

The following NEW packages will be INSTALLED:

  _tflow_select      pkgs/main/linux-64::_tflow_select-2.3.0-mkl
  astor              pkgs/main/linux-64::astor-0.8.1-py37_0
  cairo              pkgs/main/linux-64::cairo-1.14.12-h8948797_3
  ffmpeg             pkgs/main/linux-64::ffmpeg-4.0-hcdf2ecd_0
  fontconfig         pkgs/main/linux-64::fontconfig-2.13.0-h9420a91_0
  freeglut           pkgs/main/linux-64::freeglut-3.0.0-hf484d3e_5
  glib               pkgs/main/linux-64::glib-2.65.0-h3eb4bd4_0
  graphite2          pkgs/main/linux-64::graphite2-1.3.14-h23475e2_0
  harfbuzz           pkgs/main/linux-64::harfbuzz-1.8.8-hffaf4a1_0
  icu                pkgs/main/linux-64::icu-58.2-he6710b0_3
  jasper             pkgs/main/linux-64::jasper-2.0.14-h07fcdf6_1
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  keras-applications pkgs/main/noarch::keras-applications-1.0.8-py_1
  libglu             pkgs/main/linux-64::libglu-9.0.0-hf484d3e_1
  libopencv          pkgs/main/linux-64::libopencv-3.4.2-hb342d67_1
  libopus            pkgs/main/linux-64::libopus-1.3.1-h7b6447c_0
  libtiff            pkgs/main/linux-64::libtiff-4.1.0-h2733197_1
  libuuid            pkgs/main/linux-64::libuuid-1.0.3-h1bed415_2
  libvpx             pkgs/main/linux-64::libvpx-1.7.0-h439df22_0
  libxcb             pkgs/main/linux-64::libxcb-1.14-h7b6447c_0
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.2-he6710b0_1
  opencv             pkgs/main/linux-64::opencv-3.4.2-py37h6fd60c2_1
  pcre               pkgs/main/linux-64::pcre-8.44-he6710b0_0
  pixman             pkgs/main/linux-64::pixman-0.40.0-h7b6447c_0
  py-opencv          pkgs/main/linux-64::py-opencv-3.4.2-py37hb342d67_1
  zstd               pkgs/main/linux-64::zstd-1.4.5-h9ceee32_0

The following packages will be REMOVED:

  intelpython3_full-2020.2-0

The following packages will be UPDATED:

  certifi                  intel::certifi-2020.4.5.2-py37_0 --> pkgs/main::certifi-2020.6.20-py37_0

The following packages will be SUPERSEDED by a higher-priority channel:

  gast                    pkgs/main/noarch::gast-0.3.3-py_0 --> pkgs/main/linux-64::gast-0.2.2-py37_0
  tensorflow                 intel::tensorflow-2.2.0-py37_0 --> pkgs/main::tensorflow-2.1.0-mkl_py37h80a91df_0
  tensorflow-base            intel::tensorflow-base-2.2.0-0 --> pkgs/main::tensorflow-base-2.1.0-mkl_py37h6d63fb7_0

The following packages will be DOWNGRADED:

  h5py                                2.10.0-py37hd6299e0_1 --> 2.8.0-py37h989c5e5_3
  hdf5                                    1.10.6-hb1b8bf9_0 --> 1.10.2-hba1933b_1
  tensorflow-estima~                     2.2.0-pyh208ff02_0 --> 2.1.0-pyhd54b08b_0
