### ISSUE TITLE
"Solving environment: failed" when I try installing packages

### ISSUE THREAD

**Issue by sethun** [conda/conda#6998] opened 2018-03-07 13:38 UTC
**I'm submitting a...**
  -  bug report
  - [ ] feature request

## Current Behavior

"Solving environment: failed" error occurs when I try installing packages with the command conda install.
Issue occurs for both existing and new packages.

### Steps to Reproduce

```
conda install tensorflow
conda install skimage
conda upgrade conda
```

## Expected Behavior

Installation of packages without Solving environment failure and generation of error report.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

(base) C:\Users\Sethu>conda info

     active environment : base
    active env location : C:\Users\Sethu\Anaconda3
            shell level : 1
       user config file : C:\Users\Sethu\.condarc
 populated config files : C:\Users\Sethu\.condarc
          conda version : 4.4.6
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : C:\Users\Sethu\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Sethu\Anaconda3\pkgs
                          C:\Users\Sethu\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Sethu\Anaconda3\envs
                          C:\Users\Sethu\AppData\Local\conda\conda\envs
                          C:\Users\Sethu\.conda\envs
               platform : win-64
             user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.3 Windows/7 Wi
ndows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False


(base) C:\Users\Sethu>
```
</p></details>

<details><summary><code>Generated Error Report</code></summary><p>

```

(base) C:\Users\Sethu>conda install tensorflow
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 724, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\cli\main.py", line
78, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\cli\conda_argparse.
py", line 76, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\cli\main_install.py
", line 11, in execute
        install(args, parser, 'install')
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 236, in install
        force_reinstall=context.force,
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\core\solve.py", lin
e 504, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\core\solve.py", lin
e 437, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned
, force_remove)
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\core\solve.py", lin
e 145, in solve_final_state
        solution = tuple(Dist(d) for d in prefix_data.iter_records())
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\core\linked_data.py
", line 90, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\core\linked_data.py
", line 103, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\core\linked_data.py
", line 48, in load
        self._load_single_record(meta_file)
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\core\linked_data.py
", line 108, in _load_single_record
        json_data = json_load(fh.read())
      File "C:\Users\Sethu\Anaconda3\lib\site-packages\conda\common\serialize.py
", line 85, in json_load
        return json.loads(string)
      File "C:\Users\Sethu\Anaconda3\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "C:\Users\Sethu\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\Sethu\Anaconda3\lib\json\decoder.py", line 357, in raw_deco
de
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ C:\Users\Sethu\Anaconda3\Scripts\conda install tensorflow`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
             CONDA_PREFIX=C:\Users\Sethu\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Sethu\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\Sethu\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.
1
                 HOMEPATH=\Users\Sethu
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\Sethu\Anaconda3;C:\Users\Sethu\Anaconda3\Libr
ary\mingw-w64\bi
                          n;C:\Users\Sethu\Anaconda3\Library\usr\bin;C:\Users\Se
thu\Anaconda3\Li
                          brary\bin;C:\Users\Sethu\Anaconda3\Scripts;C:\Users\Se
thu\Anaconda3\bi
                          n;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Comp
uting Toolkit\CU
                          DA\v9.1\libnvvp;C:\ProgramData\Oracle\Java\javapath;;C
:\Program
                          Files\Dell\DW WLAN Card;;C:\Windows\system32;C:\Window
s;C:\Windows\Sys
                          tem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
;C:\Program
                          Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WID
COMM\Bluetooth
                          Software\syswow64;C:\Program Files\NVIDIA GPU Computin
g
                          Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Comp
uting
                          Toolkit\CUDA\v9.1\libnvvp;C:\Program Files\NVIDIA GPU
Computing
                          Toolkit\CUDA\v9.1\extras\CUPTI\libx64;C:\Program Files
 (x86)\NVIDIA
                          Corporation\PhysX\Common;;C:\Users\Sethu\AppData\Local
\Google\Cloud
                          SDK\google-cloud-sdk\bin
             PSMODULEPATH=;C:\Users\Sethu\AppData\Local\Google\Cloud SDK\google-
cloud-
                          sdk\platform\PowerShell
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Sethu\Anaconda3
            shell level : 1
       user config file : C:\Users\Sethu\.condarc
 populated config files : C:\Users\Sethu\.condarc
          conda version : 4.4.6
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : C:\Users\Sethu\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Sethu\Anaconda3\pkgs
                          C:\Users\Sethu\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Sethu\Anaconda3\envs
                          C:\Users\Sethu\AppData\Local\conda\conda\envs
                          C:\Users\Sethu\.conda\envs
               platform : win-64
             user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.3 Windows/7 Wi
ndows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

```
</p></details>

**Comment by sethun** [comment] 2018-03-08 12:13
```
Additional Info1:
```
Encountered the same error when tried the command "Conda list"

```
Additional Info2(Might be related to existing error):
```
After tensorflow import, when tried the command "tf.python_io.TFRecordWriter('path'), encountered following error:
_"UnknownError: Failed to create a NewWriteableFile: path : Access is denied.
; Input/output error"_

**Comment by kalefranz** [comment] 2018-03-08 20:42
Duplicate of https://github.com/conda/conda/issues/6390.  The error message provided in https://github.com/conda/conda/pull/6778 gives the explanation.

**Closed by kalefranz** 2018-03-08 20:42 UTC

**Comment by sethun** [comment] 2018-03-09 06:32
Thanks for looking into the issue. I tried copying both files listed in fix #[6390](https://github.com/conda/conda/pull/6778) to corresponding conda directories in my local machine. But the error - conda crashes for install/upgrade and list commands - persists.
Wondering if I have to take some other action to fix the issue?

**Comment by yjc765** [comment] 2018-04-19 16:02
Have you solved your problem? Can you tell me how?

**Comment by vasiliy249** [comment] 2018-05-02 13:16
Have you solved your problem? Can you tell me how?

**Comment by ivan-marroquin** [comment] 2018-05-03 18:08
I am having the same issue with conda 3.4

**Comment by galaxyyouyouyouzi** [comment] 2018-09-14 08:52
-1.use     **conda config --show channels **  to see which channels you have
![image](https://user-images.githubusercontent.com/26134021/45540140-35821200-b83e-11e8-9ff0-fe90f9b58561.png)
-2.use     **conda config --remove channels ###**  (eg:   conda config --remove channels conda-config)  to delete channels except defalut
![image](https://user-images.githubusercontent.com/26134021/45540158-4763b500-b83e-11e8-9dab-e46c9b837750.png)
-3. try to use   **conda install** again
