### ISSUE TITLE
conda environment activation is not possible

### ISSUE THREAD

**Issue by akshaybabloo** [conda/conda#5529] opened 2017-06-14 23:53 UTC
I am not able to activate the environment after updating `conda` to `4.3.21`, all I get when activating the environment is 

```
C:\Users\aksha>activate root35
'activate' is not recognized as an internal or external command,
operable program or batch file.
```

My `conda info` is:

```
C:\Users\aksha>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : C:\Users\aksha\Anaconda3  (writable)
    default environment : C:\Users\aksha\Anaconda3
       envs directories : C:\Users\aksha\Anaconda3\envs
                          C:\Users\aksha\AppData\Local\conda\conda\envs
                          C:\Users\aksha\.conda\envs
          package cache : C:\Users\aksha\Anaconda3\pkgs
                          C:\Users\aksha\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/menpo/win-64
                          https://conda.anaconda.org/menpo/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\aksha\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.13.0 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False
```

**Update**

Looking at #1519, I can't even use `activate.bat`, system can't seem to find it.

**Update 2**

`activate.exe` or `activate.bat` is not there in the `scripts` folder.

**Update 3**

I had to copy the `activate` and `deactivate` code from other system to make it work as a quick fix. The following files are not found:

```
activate
activate.bat
activate-global-python-argcomplete.exe
activate-global-python-argcomplete-script.py
deactivate
deactivate.bat
```

**Comment by alexpawlowski** [comment] 2017-06-15 14:29
I am also experiencing this issue with the recent update to `4.3.21` on `Windows`.
`conda-info`

```
Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\[user]\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\[user]\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\[user]\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\[user]\AppData\Local\conda\conda\envs
                          C:\Users\[user]\.conda\envs
          package cache : C:\Users\[user]\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\[user]\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\[user]\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393
          administrator : False
```

**Comment by MCBama** [comment] 2017-06-15 16:55
Also experiencing this error. Attempting to install any packages that require conda to update (such as Shapely) also causes error.

Workaround currently for me is copying the activate/deactivate scripts from `Anaconda3/Scripts` into another folder, installing packages, and then moving the scripts back where they belong in `Anaconda3/Scripts`

**Comment by mbargull** [comment] 2017-06-15 22:20
This is most likely a `conda-forge` packaging issue on Windows, see https://github.com/conda-forge/conda-feedstock/issues/24. I suppose this should be fixed after a `conda update conda` once the fixed package is built for Windows and made available on `conda.anaconda.org/conda-forge` (in a couple of hours or so).

**Comment by vmuriart** [comment] 2017-06-16 01:09
Just had this issue and running `conda update conda` fixed it.

**Comment by alexpawlowski** [comment] 2017-06-16 19:19
@mbargull 's suggestion worked for me to resolve my issue, thanks.

**Comment by MartinPri** [comment] 2017-06-17 09:14
suggestion creates same error for me:(
Problem cannot be solved

**Comment by wlievens** [comment] 2017-10-06 12:01
Same issue here, I don't see activate.bat in the Scripts folder.

Is there an older version that does work?

**Comment by kalefranz** [comment] 2017-10-11 21:16
Closing per mbargull's explanation.

**Closed by kalefranz** 2017-10-11 21:16 UTC

**Comment by fastlater** [comment] 2017-11-07 08:15
I got a similar error. I fresh installed the latest version without problem.
Then prompt worked fine till I installed tensorflow-gpu. Then, it cannot find the activate.bat EVEN when the file activate,bat exists in the Scripts folder.
The activate.bat is as below:
@echo off
call "C:\Anaconda2\Scripts\activate" %*

I reinstalled all and prompt worked only the first time and then it cannot find the activate.bat again.

**Comment by AdityaSoni19031997** [comment] 2017-11-07 09:16
It's still exists..
Just now when I was trying to install Pytorch from the tar itself..
activate.bat went missing..

**Comment by mbargull** [comment] 2017-11-08 03:50
@fastlater, @AdityaSoni19031997: Your issues with `activate.bat` have different causes (which I don't know). This issue is an old and resolved one.

**Comment by fastlater** [comment] 2017-11-08 05:41
@mbargull  do you recommend us to open a new issue?

**Comment by mbargull** [comment] 2017-11-08 08:41
I'd recommend to look at
https://github.com/continuumio/anaconda-issues/issues?q=activate+sort%3Aupdated-desc
and
https://github.com/conda/conda/issues?q=activate+sort%3Aupdated-desc
to see if there is a more recent issue which seems to be identical to yours and add a comment on that one. If you cannot find such an issue, you should open a new one (maybe preferably on https://github.com/continuumio/anaconda-issues/issues).

In either case please provide more information about your installation and steps to reproduce your problem, i.e., output of `conda info` and, in your own case `conda install --dry-run tensorflow-gpu` and/or `conda create --dry-run -n new-env tensorflow-gpu` if the `tensorflow-gpu` install caused that behavior. `conda` should be callable by `installation-path\Scripts\conda.exe` even if you didn't `activate` before.

**Comment by somanadi** [comment] 2017-12-04 21:43
I also had the same issue with the latest the latest version. But got resolved by installing the previous version (Anaconda3-5.0.0) from https://repo.continuum.io/archive/,

why don't you try that? @AdityaSoni19031997

**Comment by compie** [comment] 2017-12-11 22:58
I had the same issue, see https://github.com/ContinuumIO/anaconda-issues/issues/2533#issuecomment-350885435 for a working workaround.
