### ISSUE TITLE
Bad Conda env name results in "unexpected error" and stack trace

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4342] opened 2017-01-17 19:09 UTC
I think the trace below tells the story.  I would instead expect the result to be something like "Conda environment not found - please check the channel and environment name.  If the environment is private please ensure that you are logged in from the command line with an account that can access that asset".  But not "an unexpected error" and stack trace.

```
$ conda env create ijstokes/dspyr
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/3.5.2 Darwin/16.3.0 OSX/10.12.2
                UID:GID : 502:20



`$ /Users/ijstokes/anaconda/bin/conda-env create ijstokes/dspyr`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 82, in execute
        directory=os.getcwd())
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: ijstokes/dspyr was not found on anaconda.org.
    You may need to be logged in. Try running:
        anaconda login
    ijstokes/dspyr does not exist or can't be accessed
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt
```

**Comment by ijstokes** [comment] 2017-01-17 19:10
FWIW this is the command I **meant** to execute (and which works):

```
conda env create datasciencepythonr/dspyr
```

**Comment by kalefranz** [comment] 2017-01-17 21:50
For historic reasons I think you're aware of, the conda-env code is pretty much completely separate from the conda code, even though they finally  at least live in the same repo.  In 2017 I'll get more time to work on it hopefully.

**Comment by kalefranz** [comment] 2017-05-09 03:58
Duplicate of #3689

**Closed by kalefranz** 2017-05-09 03:58 UTC
