### ISSUE TITLE
pyasn1.error.PyAsn1Error: Duplicate type TagSet

### ISSUE THREAD

**Issue by wanglongqi** [conda/conda#1280] opened 2015-04-15 04:18 UTC
>conda search scikit-learn

Fetching package metadata: ...An unexpected error has occurred, please consider
sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Python\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Python\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Python\lib\site-packages\conda\cli\main_search.py", line 101, in exec
ute
    execute_search(args, parser)
  File "C:\Python\lib\site-packages\conda\cli\main_search.py", line 166, in exec
ute_search
    unknown=args.unknown, json=args.json, offline=args.offline)
  File "C:\Python\lib\site-packages\conda\cli\common.py", line 531, in get_index
_trap
    return get_index(*args, **kwargs)
  File "C:\Python\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Python\lib\site-packages\conda\utils.py", line 86, in __call__
    value = self.func(*args, **kw)
  File "C:\Python\lib\site-packages\conda\fetch.py", line 250, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Python\lib\site-packages\concurrent\futures\_base.py", line 397, in r
esult
    return self.__get_result()
  File "C:\Python\lib\site-packages\concurrent\futures\_base.py", line 356, in _
_get_result
    raise self._exception
pyasn1.error.PyAsn1Error: Duplicate type TagSet(Tag(tagClass=128, tagFormat=0, t
agId=8))

>conda info

Current conda install:

             platform : win-64
        conda version : 3.10.1
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.6.0
     root environment : C:\Python  (writable)
  default environment : C:\Python
     envs directories : C:\Python\envs
        package cache : C:\Python\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

>conda update scikit-learn

Fetching package metadata: ...An unexpected error has occurred, please consider
sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Python\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Python\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Python\lib\site-packages\conda\cli\main_update.py", line 40, in execu
te
    install.install(args, parser, 'update')
  File "C:\Python\lib\site-packages\conda\cli\install.py", line 253, in install
    offline=args.offline)
  File "C:\Python\lib\site-packages\conda\cli\common.py", line 531, in get_index
_trap
    return get_index(*args, **kwargs)
  File "C:\Python\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Python\lib\site-packages\conda\utils.py", line 86, in __call__
    value = self.func(*args, **kw)
  File "C:\Python\lib\site-packages\conda\fetch.py", line 250, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Python\lib\site-packages\concurrent\futures\_base.py", line 404, in r
esult
    return self.__get_result()
  File "C:\Python\lib\site-packages\concurrent\futures\_base.py", line 356, in _
_get_result
    raise self._exception
pyasn1.error.PyAsn1Error: Duplicate type TagSet(Tag(tagClass=128, tagFormat=0, t
agId=8))

**Comment by ymost** [comment] 2015-04-21 14:09
+1

**Comment by asmeurer** [comment] 2015-05-28 20:42
Try `conda update requests`

**Comment by asmeurer** [comment] 2015-05-28 20:44
Closing as duplicate of https://github.com/conda/conda/issues/1261

**Closed by asmeurer** 2015-05-28 20:44 UTC
