### ISSUE TITLE
(base) C:\Users\krish>conda create -n myenv python=3.6 Collecting package metadata (current_repodata.json): failed  CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json> Elapsed: -  An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way. 'https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64'  I am running anaconda new version in windows. But I am facing this problem. Can some able to help me struggling from last 24 hours. Searched every where but didnt found solution. Thanks  in advacne 

### ISSUE THREAD

**Issue by nnk-maker** [conda/conda#10360] opened 2020-11-14 17:39 UTC
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by ifrh** [comment] 2020-11-14 19:50
Well perhaps the server admin can help you:

```
 curl -H 'Cache-Control: no-cache' https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json
 curl: (52) Empty reply from server

```
```
Firefox output is
Fehler: Gesicherte Verbindung fehlgeschlagen
Beim Verbinden mit www.lfd.uci.edu trat ein Fehler auf. PR_CONNECT_RESET_ERROR
    Die Website kann nicht angezeigt werden, da die Authentizität der erhaltenen Daten nicht verifiziert werden konnte.
    Kontaktieren Sie bitte den Inhaber der Website, um ihn über dieses Problem zu informieren.

```

**Comment by nnk-maker** [comment] 2020-11-15 10:12
(base) C:\Users\krish>conda info

     active environment : base
    active env location : C:\Users\krish\anaconda3
            shell level : 1
       user config file : C:\Users\krish\.condarc
 populated config files : C:\Users\krish\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages :
       base environment : C:\Users\krish\anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
                          https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64
                          https://www.lfd.uci.edu/~gohlke/pythonlibs/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\krish\anaconda3\pkgs
                          C:\Users\krish\.conda\pkgs
                          C:\Users\krish\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\krish\anaconda3\envs
                          C:\Users\krish\.conda\envs
                          C:\Users\krish\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


(base) C:\Users\krish>conda config --show-sources
==> C:\Users\krish\.condarc <==
ssl_verify: True
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame
  - defaults
show_channel_urls: True


(base) C:\Users\krish>conda list --show-channel-urls
# packages in environment at C:\Users\krish\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaults
alabaster                 0.7.12                     py_0    defaults
anaconda                  2020.07                  py38_0    defaults
anaconda-client           1.7.2                    py38_0    defaults
anaconda-navigator        1.9.12                   py38_0    defaults
anaconda-project          0.8.4                      py_0    defaults
argh                      0.26.2                   py38_0    defaults
asn1crypto                1.3.0                    py38_0    defaults
astroid                   2.4.2                    py38_0    defaults
astropy                   4.0.1.post1      py38he774522_1    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     19.3.0                     py_0    defaults
autopep8                  1.5.3                      py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.2.0                      py_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.6.1                      py_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py38_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
bcrypt                    3.1.7            py38he774522_1    defaults
beautifulsoup4            4.9.1                    py38_0    defaults
bitarray                  1.4.0            py38he774522_0    defaults
bkcharts                  0.2                      py38_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.5                      py_0    defaults
blosc                     1.19.0               h7bd577a_0    defaults
bokeh                     2.1.1                    py38_0    defaults
boto                      2.49.0                   py38_0    defaults
bottleneck                1.3.2            py38h2a96729_1    defaults
brotlipy                  0.7.0           py38he774522_1000    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2020.6.24                     0    defaults
certifi                   2020.6.20                py38_0    defaults
cffi                      1.14.0           py38h7a1dbc1_0    defaults
chardet                   3.0.4                 py38_1003    defaults
click                     7.1.2                      py_0    defaults
cloudpickle               1.5.0                      py_0    defaults
clyent                    1.2.2                    py38_1    defaults
colorama                  0.4.3                      py_0    defaults
comtypes                  1.1.7                 py38_1001    defaults
conda                     4.8.3                    py38_0    defaults
conda-build               3.18.11                  py38_1    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.1            py38h62dcd97_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
contextlib2               0.6.0.post1                py_0    defaults
cryptography              2.9.2            py38h7a1dbc1_0    defaults
curl                      7.71.1               h2a8f88b_1    defaults
cycler                    0.10.0                   py38_0    defaults
cython                    0.29.21          py38ha925a31_0    defaults
cytoolz                   0.10.1           py38he774522_0    defaults
dask                      2.20.0                     py_0    defaults
dask-core                 2.20.0                     py_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
diff-match-patch          20200713                   py_0    defaults
distributed               2.20.0                   py38_0    defaults
docutils                  0.16                     py38_1    defaults
entrypoints               0.3                      py38_0    defaults
et_xmlfile                1.0.1                   py_1001    defaults
fastcache                 1.1.0            py38he774522_0    defaults
filelock                  3.0.12                     py_0    defaults
flake8                    3.8.3                      py_0    defaults
flask                     1.1.2                      py_0    defaults
freetype                  2.10.2               hd328e21_0    defaults
fsspec                    0.7.4                      py_0    defaults
future                    0.18.2                   py38_1    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    20.6.2           py38he774522_0    defaults
glob2                     0.7                        py_0    defaults
gmpy2                     2.0.8            py38h7edee0f_3    defaults
greenlet                  0.4.16           py38he774522_0    defaults
h5py                      2.10.0           py38h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
heapdict                  1.0.1                      py_0    defaults
html5lib                  1.1                        py_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      2.10                       py_0    defaults
imageio                   2.9.0                      py_0    defaults
imagesize                 1.2.0                      py_0    defaults
importlib-metadata        1.7.0                    py38_0    defaults
importlib_metadata        1.7.0                         0    defaults
intel-openmp              2020.1                      216    defaults
intervaltree              3.0.2                      py_1    defaults
ipykernel                 5.3.2            py38h5ca1d4c_0    defaults
ipython                   7.16.1           py38h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py38_0    defaults
ipywidgets                7.5.1                      py_0    defaults
isort                     4.3.21                   py38_0    defaults
itsdangerous              1.1.0                      py_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.17.1                   py38_0    defaults
jinja2                    2.11.2                     py_0    defaults
joblib                    0.16.0                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.9.5                      py_0    defaults
jsonschema                3.2.0                    py38_0    defaults
jupyter                   1.0.0                    py38_7    defaults
jupyter_client            6.1.6                      py_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.3                    py38_0    defaults
jupyterlab                2.1.5                      py_0    defaults
jupyterlab_server         1.2.0                      py_0    defaults
keyring                   21.2.1                   py38_0    defaults
kiwisolver                1.2.0            py38h74a9793_0    defaults
krb5                      1.18.2               hc04afaa_0    defaults
lazy-object-proxy         1.4.3            py38he774522_0    defaults
libarchive                3.4.2                h5e25573_0    defaults
libcurl                   7.71.1               h2a8f88b_1    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.10.1               ha925a31_0    defaults
libllvm9                  9.0.1                h21ff451_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libspatialindex           1.9.3                h33f27b4_0    defaults
libssh2                   1.9.0                h7a1dbc1_1    defaults
libtiff                   4.1.0                h56a325e_1    defaults
libxml2                   2.9.10               h464c3ec_1    defaults
libxslt                   1.1.34               he774522_0    defaults
llvmlite                  0.33.0           py38ha925a31_0    defaults
locket                    0.2.0                    py38_1    defaults
lxml                      4.5.2            py38h1350720_0    defaults
lz4-c                     1.9.2                h62dcd97_0    defaults
lzo                       2.10                 he774522_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py38he774522_0    defaults
matplotlib                3.2.2                         0    defaults
matplotlib-base           3.2.2            py38h64f37c6_0    defaults
mccabe                    0.6.1                    py38_1    defaults
menuinst                  1.4.16           py38he774522_1    defaults
mistune                   0.8.4           py38he774522_1000    defaults
mkl                       2020.1                      216    defaults
mkl-service               2.3.0            py38hb782905_0    defaults
mkl_fft                   1.1.0            py38h45dec08_0    defaults
mkl_random                1.1.1            py38h47e9c7a_0    defaults
mock                      4.0.2                      py_0    defaults
more-itertools            8.4.0                      py_0    defaults
mpc                       1.1.0                h7edee0f_1    defaults
mpfr                      4.0.2                h62dcd97_1    defaults
mpir                      3.0.0                hec2e145_1    defaults
mpmath                    1.1.0                    py38_0    defaults
msgpack-python            1.0.0            py38h74a9793_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py38_0    defaults
navigator-updater         0.2.1                    py38_0    defaults
nbconvert                 5.6.1                    py38_0    defaults
nbformat                  5.0.7                      py_0    defaults
networkx                  2.4                        py_1    defaults
nltk                      3.5                        py_0    defaults
nose                      1.3.7                    py38_2    defaults
notebook                  6.0.3                    py38_0    defaults
numba                     0.50.1           py38h47e9c7a_0    defaults
numexpr                   2.7.1            py38h25d0782_0    defaults
numpy                     1.18.5           py38h6530119_0    defaults
numpy-base                1.18.5           py38hc3f5095_0    defaults
numpydoc                  1.1.0                      py_0    defaults
olefile                   0.46                       py_0    defaults
openpyxl                  3.0.4                      py_0    defaults
openssl                   1.1.1g               he774522_0    defaults
packaging                 20.4                       py_0    defaults
pandas                    1.0.5            py38h47e9c7a_0    defaults
pandoc                    2.10                          0    defaults
pandocfilters             1.4.2                    py38_1    defaults
paramiko                  2.7.1                      py_0    defaults
parso                     0.7.0                      py_0    defaults
partd                     1.1.0                      py_0    defaults
path                      13.1.0                   py38_0    defaults
path.py                   12.4.0                        0    defaults
pathlib2                  2.3.5                    py38_0    defaults
pathtools                 0.1.2                      py_1    defaults
patsy                     0.5.1                    py38_0    defaults
pep8                      1.7.1                    py38_0    defaults
pexpect                   4.8.0                    py38_0    defaults
pickleshare               0.7.5                 py38_1000    defaults
pillow                    7.2.0            py38hcc1f983_0    defaults
pip                       20.1.1                   py38_1    defaults
pkginfo                   1.5.0.1                  py38_0    defaults
pluggy                    0.13.1                   py38_0    defaults
ply                       3.11                     py38_0    defaults
powershell_shortcut       0.0.1                         3    defaults
prometheus_client         0.8.0                      py_0    defaults
prompt-toolkit            3.0.5                      py_0    defaults
prompt_toolkit            3.0.5                         0    defaults
psutil                    5.7.0            py38he774522_0    defaults
py                        1.9.0                      py_0    defaults
py-lief                   0.10.1           py38ha925a31_0    defaults
pycodestyle               2.6.0                      py_0    defaults
pycosat                   0.6.3            py38he774522_0    defaults
pycparser                 2.20                       py_2    defaults
pycurl                    7.43.0.5         py38h7a1dbc1_0    defaults
pydocstyle                5.0.2                      py_0    defaults
pyflakes                  2.2.0                      py_0    defaults
pygments                  2.6.1                      py_0    defaults
pylint                    2.5.3                    py38_0    defaults
pynacl                    1.4.0            py38h62dcd97_1    defaults
pyodbc                    4.0.30           py38ha925a31_0    defaults
pyopenssl                 19.1.0                     py_1    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py38ha925a31_4    defaults
pyreadline                2.1                      py38_1    defaults
pyrsistent                0.16.0           py38he774522_0    defaults
pysocks                   1.7.1                    py38_0    defaults
pytables                  3.6.1            py38ha5be198_0    defaults
pytest                    5.4.3                    py38_0    defaults
python                    3.8.3                he1778fa_2    defaults
python-dateutil           2.8.1                      py_0    defaults
python-jsonrpc-server     0.3.4                      py_1    defaults
python-language-server    0.34.1                   py38_0    defaults
python-libarchive-c       2.9                        py_0    defaults
pytz                      2020.1                     py_0    defaults
pywavelets                1.1.1            py38he774522_0    defaults
pywin32                   227              py38he774522_1    defaults
pywin32-ctypes            0.2.0                 py38_1000    defaults
pywinpty                  0.5.7                    py38_0    defaults
pyyaml                    5.3.1            py38he774522_1    defaults
pyzmq                     19.0.1           py38ha925a31_1    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.7.2                      py_0    defaults
qtconsole                 4.7.5                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
regex                     2020.6.8         py38he774522_0    defaults
requests                  2.24.0                     py_0    defaults
rope                      0.17.0                     py_0    defaults
rtree                     0.9.4            py38h21ff451_1    defaults
ruamel_yaml               0.15.87          py38he774522_1    defaults
scikit-image              0.16.2           py38h47e9c7a_0    defaults
scikit-learn              0.23.1           py38h25d0782_0    defaults
scipy                     1.5.0            py38h9439919_0    defaults
seaborn                   0.10.1                     py_0    defaults
send2trash                1.5.0                    py38_0    defaults
setuptools                49.2.0                   py38_0    defaults
simplegeneric             0.8.1                    py38_2    defaults
singledispatch            3.4.0.3                  py38_0    defaults
sip                       4.19.13          py38ha925a31_0    defaults
six                       1.15.0                     py_0    defaults
snappy                    1.1.8                h33f27b4_0    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcollections         1.2.1                      py_0    defaults
sortedcontainers          2.2.2                      py_0    defaults
soupsieve                 2.0.1                      py_0    defaults
sphinx                    3.1.2                      py_0    defaults
sphinxcontrib             1.0                      py38_1    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    defaults
sphinxcontrib-devhelp     1.0.2                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.3                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.3                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.4                      py_0    defaults
sphinxcontrib-websupport  1.2.3                      py_0    defaults
spyder                    4.1.4                    py38_0    defaults
spyder-kernels            1.9.2                    py38_0    defaults
sqlalchemy                1.3.18           py38he774522_0    defaults
sqlite                    3.32.3               h2a8f88b_0    defaults
statsmodels               0.11.1           py38he774522_0    defaults
sympy                     1.6.1                    py38_0    defaults
tbb                       2020.0               h74a9793_0    defaults
tblib                     1.6.0                      py_0    defaults
terminado                 0.8.3                    py38_0    defaults
testpath                  0.4.4                      py_0    defaults
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.10               he774522_0    defaults
toml                      0.10.1                     py_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   6.0.4            py38he774522_1    defaults
tqdm                      4.47.0                     py_0    defaults
traitlets                 4.3.3                    py38_0    defaults
typing_extensions         3.7.4.2                    py_0    defaults
ujson                     1.35             py38he774522_0    defaults
unicodecsv                0.14.1                   py38_0    defaults
urllib3                   1.25.9                     py_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_3    defaults
watchdog                  0.10.3                   py38_0    defaults
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py38_1    defaults
werkzeug                  1.0.1                      py_0    defaults
wheel                     0.34.2                   py38_0    defaults
widgetsnbextension        3.5.1                    py38_0    defaults
win_inet_pton             1.1.0                    py38_0    defaults
win_unicode_console       0.5                      py38_0    defaults
wincertstore              0.2                      py38_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.11.2           py38he774522_0    defaults
xlrd                      1.2.0                      py_0    defaults
xlsxwriter                1.2.9                      py_0    defaults
xlwings                   0.19.5                   py38_0    defaults
xlwt                      1.3.0                    py38_0    defaults
xmltodict                 0.12.0                     py_0    defaults
xz                        5.2.5                h62dcd97_0    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.30.0                     py_0    defaults
zeromq                    4.3.2                ha925a31_2    defaults
zict                      2.0.0                      py_0    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults
zope                      1.0                      py38_1    defaults
zope.event                4.4                      py38_0    defaults
zope.interface            4.7.1            py38he774522_0    defaults
zstd                      1.4.5                ha9fde0e_0    defaults

I tried that , But still the problem is not resolved can some one help me ?

**Comment by nnk-maker** [comment] 2020-11-15 10:14
(base) C:\Users\krish>curl -H 'Cache-Control: no-cache' https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json
curl: (6) Could not resolve host: no-cache'
curl: (56) Send failure: Connection was reset

I tried this too its too fail. So, no one in the world able to help me?

**Comment by ifrh** [comment] 2020-11-16 05:47
You have two options:
a) remove        https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64  from your conda channels
b) get in contact with that server user gohlke [from his webpage: Christoph Gohlke, Laboratory for Fluorescence Dynamics, University of California, Irvine] an tell him your problem. Maybe he or his server admin can help you.

**Comment by chenghlee** [comment] 2020-11-24 14:13
Closing, as this appears to be a configuration issue with the UCI server, rather than with conda.

**Closed by chenghlee** 2020-11-24 14:13 UTC

**Comment by nnk-maker** [comment] 2020-11-27 12:59
Not closed.
No one is helping me

**Comment by nnk-maker** [comment] 2020-11-27 14:33
> Well perhaps the server admin can help you:
> 
> ```
>  curl -H 'Cache-Control: no-cache' https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json
>  curl: (52) Empty reply from server
> ```
> 
> ```
> Firefox output is
> Fehler: Gesicherte Verbindung fehlgeschlagen
> Beim Verbinden mit www.lfd.uci.edu trat ein Fehler auf. PR_CONNECT_RESET_ERROR
>     Die Website kann nicht angezeigt werden, da die Authentizität der erhaltenen Daten nicht verifiziert werden konnte.
>     Kontaktieren Sie bitte den Inhaber der Website, um ihn über dieses Problem zu informieren.
> ```
(base) C:\WINDOWS\system32> curl -H 'Cache-Control: no-cache' https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json
curl: (6) Could not resolve host: no-cache'
curl: (56) Send failure: Connection was reset

**Comment by ifrh** [comment] 2020-11-27 17:55
I want to try helping you.

The problem is, that the resource you want to "catch" is not online on that server.
If you try to "download" the json-file with some program, than you can see error messages independent of conda.
That is why I had used CURL and (German localized) Firefox. 
I don't know where you find information to that json URL, maybe there is a writing mistake or the information is to old and the resource has moved to an other place.

> > > Well perhaps the server admin can help you:
> > ```
> >  curl -H 'Cache-Control: no-cache' https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json
> >  curl: (52) Empty reply from server
> > ```
> > 
> > 
> > ```
> > Firefox output is
> > Fehler: Gesicherte Verbindung fehlgeschlagen
> > Beim Verbinden mit www.lfd.uci.edu trat ein Fehler auf. PR_CONNECT_RESET_ERROR
> >     Die Website kann nicht angezeigt werden, da die Authentizität der erhaltenen Daten nicht verifiziert werden konnte.
> >     Kontaktieren Sie bitte den Inhaber der Website, um ihn über dieses Problem zu informieren.
> > ```
> 
> (base) C:\WINDOWS\system32> curl -H 'Cache-Control: no-cache' https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json
> curl: (6) Could not resolve host: no-cache'
> curl: (56) Send failure: Connection was reset

Okay , you are running curl on windows, so you should use double quotes to ensure, that the space inside the Cache-Control option is not interpreted as begin of new commandline parameter.
Try this in Windows:
`curl -H "Cache-Control: no-cache" https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json`

**Comment by ifrh** [comment] 2020-11-27 18:09
IF there is a public available `win-64/current_repodata.json` inside the user space of `~gohlke`, than you can ask him ([https://www.lfd.uci.edu/~gohlke](https://www.lfd.uci.edu/~gohlke)) what the current URL is.
IF the URL to that JSON is correct, and you are allowed (perhaps VPN) to have access to that repository, than you should
get in contact with their server-admin. 
Realy no one else (except former named) can help you, iff the URL is correct and is a public repository.

IF you decide just to query an other channel having the same "resources", than you should ask a new question.
(I search for resource having xyz. How I can exchange queried channels in conda?)

**Comment by cgohlke** [comment] 2020-11-28 09:39
`https://www.lfd.uci.edu/~gohlke/pythonlibs` is not a conda repo/channel. Remove it from the channel list.

**Comment by nnk-maker** [comment] 2020-11-28 12:20
> `https://www.lfd.uci.edu/~gohlke/pythonlibs` is not a conda repo/channel. Remove it from the channel list.

cgohlke- Can you tell me how to remove it from the channel list: https://www.lfd.uci.edu/~gohlke/pythonlibs.
Can you share the process to remove the channel

**Comment by nnk-maker** [comment] 2020-11-28 12:37
> `https://www.lfd.uci.edu/~gohlke/pythonlibs` is not a conda repo/channel. Remove it from the channel list.

Can some share. How to remove this link from the channel list https://www.lfd.uci.edu/~gohlke/pythonlibs

**Comment by nnk-maker** [comment] 2020-11-28 13:09
> `https://www.lfd.uci.edu/~gohlke/pythonlibs` is not a conda repo/channel. Remove it from the channel list.

Hi sir,

I try to remove the link from the channel. But it's not working. I am sharing my output and screenshot below.


(base) C:\Users\krish>conda create -n procimg python=3.8.5
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64'

(base) C:\Users\krish>conda config --remove channels https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json
CondaKeyError: 'channels': 'https://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/current_repodata.json' is not in the 'channels' key of the config file.

**Comment by nnk-maker** [comment] 2020-11-28 13:11
# 
![image](https://user-images.githubusercontent.com/72618531/100516337-86faeb00-3183-11eb-87a3-7d47233a0b30.png)

**Comment by nnk-maker** [comment] 2020-11-28 13:20
![image](https://user-images.githubusercontent.com/72618531/100516524-d1c93280-3184-11eb-988f-4445e49338a1.png)

**Comment by nnk-maker** [comment] 2020-11-28 13:46
![image](https://user-images.githubusercontent.com/72618531/100517074-7ef17a00-3188-11eb-9a94-b741a60fa9e9.png)

**Comment by ifrh** [comment] 2020-11-28 18:28
here is your answer:
 [https://stackoverflow.com/questions/39558316/how-can-i-remove-a-url-channel-from-anaconda](https://stackoverflow.com/questions/39558316/how-can-i-remove-a-url-channel-from-anaconda)

`conda config --remove channels 'URL-to-Repository-to-remove'`

**Comment by nnk-maker** [comment] 2020-11-29 08:37
> here is your answer:
> https://stackoverflow.com/questions/39558316/how-can-i-remove-a-url-channel-from-anaconda
> 
> `conda config --remove channels 'Repository-to-remove'`
> 
> In your case, because you told that the `conda config --remove` didn't work for you, you can edit `.condarc` with a text editor like it is mentioned here https://stackoverflow.com/a/39596897

thanks , this works for me
