### ISSUE TITLE
Conda env install (4.6.7 on Win64) seems to use wrong pip (maybe from base env?) for pip section

### ISSUE THREAD

**Issue by chkothe** [conda/conda#8358] opened 2019-02-28 18:31 UTC
## Current Behavior
I'm trying to install a minimal python=3.6.6 environment .yml that has a pip section which installs a matching cp3.6 .whl (from an https source). Doing that using `conda env create` works fine with with the 4.5.12 version, but after `conda update -n base -c defaults conda`, re-running the same command (using a new -n name) no longer works, and fails with a "... is not a supported wheel on this platform" error. It looks like to me like conda might try to use the wrong pip, perhaps from the base env, which is 3.7.

This is on Windows 10, using a freshly-installed Miniconda3 4.5.12 (Py3.7 amd64) that was then upgraded with said command to 4.6.7.

## Expected Behavior
Using this bare-bones conda .yml file:
```
name: test-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.6
  - pip:
    - https://github.com/intheon/vispy/releases/download/v0.6.0.dev0/vispy-0.6.0.dev0-cp36-cp36m-win_amd64.whl
```
... the install succeeds (as it should), with a vanilla just-downloaded and installed Miniconda3 4.5.12:

```
(base) D:\DEVEL\Qusp\cpe\requirements>conda env create -f test-conda.yml
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.7

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
pip-19.0.3           | 1.9 MB    | ############################################################################ | 100%
setuptools-40.8.0    | 633 KB    | ############################################################################ | 100%
wheel-0.33.1         | 52 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting vispy==0.6.0.dev0 from https://github.com/intheon/vispy/releases/download/v0.6.0.dev0/vispy-0.6.0.dev0-cp36-cp36m-win_amd64.whl (from -r D:\DEVEL\Qusp\cpe\requirements\condaenv.cf311h7_.requirements.txt (line 1))
  Downloading https://github.com/intheon/vispy/releases/download/v0.6.0.dev0/vispy-0.6.0.dev0-cp36-cp36m-win_amd64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 3.2MB/s
Requirement already satisfied: numpy in c:\users\chris\appdata\roaming\python\python36\site-packages\numpy-1.16.0-py3.6-win-amd64.egg (from vispy==0.6.0.dev0->-r D:\DEVEL\Qusp\cpe\requirements\condaenv.cf311h7_.requirements.txt (line 1)) (1.16.0)
Installing collected packages: vispy
Successfully installed vispy-0.6.0.dev0
#
# To activate this environment, use
#
#     $ conda activate test-conda
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

### Steps to Reproduce
But when we now upgrade to 4.6.7, ...
```
(base) D:\DEVEL\Qusp\cpe\requirements>conda update -n base -c defaults conda
Solving environment: done

## Package Plan ##

  environment location: C:\Users\chris\Miniconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.1.23  |                0         158 KB
    openssl-1.1.1b             |       he774522_0         5.8 MB
    conda-4.6.7                |           py37_0         1.7 MB
    ------------------------------------------------------------
                                           Total:         7.6 MB

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0      --> 2019.1.23-0
    conda:           4.5.12-py37_0     --> 4.6.7-py37_0
    openssl:         1.1.1a-he774522_0 --> 1.1.1b-he774522_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
ca-certificates-2019 | 158 KB    | ############################################################################ | 100%
openssl-1.1.1b       | 5.8 MB    | ############################################################################ | 100%
conda-4.6.7          | 1.7 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

... and then we re-run the same command (with a new -n), it fails:

```
(base) D:\DEVEL\Qusp\cpe\requirements>conda env create -f test-conda.yml -n test-conda2
Collecting package metadata: done
Solving environment: \ WARNING conda.common.logic:get_sat_solver_cls(278): Could not run SAT solver through interface 'pycryptosat'.
done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

CondaEnvException: Pip subcommand failed with
output:
error: The system cannot find the path specified.
vispy-0.6.0.dev0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

... and it says the wheel is not supported on this platform (even though it's cp36, and it installed just fine with an earlier version of conda).

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : base
    active env location : C:\Users\chris\Miniconda3
            shell level : 1
       user config file : C:\Users\chris\.condarc
 populated config files : C:\Users\chris\.condarc
          conda version : 4.6.7
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Users\chris\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\chris\Miniconda3\pkgs
                          C:\Users\chris\.conda\pkgs
                          C:\Users\chris\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\chris\Miniconda3\envs
                          C:\Users\chris\.conda\envs
                          C:\Users\chris\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(base) D:\DEVEL\Qusp\cpe\requirements>conda config --show-sources
==> C:\Users\chris\.condarc <==
pip_interop_enabled: True
channels:
  - conda-forge
  - defaults
sat_solver: pycryptosat

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\chris\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.7                    py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.4.2            py37h7a1dbc1_0    defaults
idna                      2.8                      py37_0    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
openssl                   1.1.1b               he774522_0    defaults
pip                       18.1                     py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.1                h8c8aaf0_6    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults

```
</p></details>

**Comment by chkothe** [comment] 2019-02-28 18:43
Some more notes that might be helpful: 
- note that there's an unspecific "The system cannot find the path specified" error just before the "not a supported wheel on this platform" error
- if I activate the half-created env, and then run `pip install <url-of-wheel> inside of it, pip also manages to install the whl file.

**Comment by chnldw** [comment] 2019-02-28 22:23
I met same issue on windows. install conda 4.6.4 will work.
But "The system cannot find the path specified" error still there in 4.6.4

**Comment by sobayed** [comment] 2019-03-01 14:55
I came across the same issue when trying to install ``pybuilder`` (whose latest release requires Python 3.6) using an "environment.yml" like this:

```
name: pybuilder
channels:
  - defaults
dependencies:
  - python=3.6
  - pip:
    - pybuilder
```

When trying to create the environment using a Python 3.7 installation for the "base" environment, I get the following error message:

  ```
  Collecting package metadata: done
  Solving environment: done
  Preparing transaction: done
  Verifying transaction: done
  Executing transaction: done

  CondaEnvException: Pip subcommand failed with
  output: 
  pybuilder requires Python '!=3.0,!=3.1,!=3.2,<3.7,>=2.6' but the running Python is 3.7.2
  ```

So it looks like the ``pip.exe`` from the "base" environment is used instead of the newly created one.

# Environment info

```
     active environment : base
    active env location : C:\Users\...\anaconda3
            shell level : 1
       user config file : C:\Users\...\.condarc
 populated config files : C:\Users\...\.condarc
          conda version : 4.6.7
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : C:\Users\...\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\...\anaconda3\pkgs
                          C:\Users\...\.conda\pkgs
                          C:\Users\...\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\...\anaconda3\envs
                          C:\Users\...\.conda\envs
                          C:\Users\...\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment] 2019-03-01 15:03
Thanks for the reports.  Recent versions of conda try to activate the environment prior to running pip in that environment.  If anything, this should be less confused, not more confused, but clearly something is going wrong.  We will look into it.

**Comment by chkothe** [comment] 2019-03-01 16:46
Great, thx!

**Comment by soapy1** [comment] 2019-03-01 20:53
So, I'm able to reproduce this issue, but not with conda installed from master. I built that version of conda and installed it and that also seems fine. I've attached the build I made to test this out. @chkothe when you have a second could you test it out. You should be able to unzip it and do a `conda install <path to file>.tar.bz2` to get this version of conda.

[conda-4.6.7+master-py37_0.tar.bz2.zip](https://github.com/conda/conda/files/2921020/conda-4.6.7%2Bmaster-py37_0.tar.bz2.zip)

**Comment by DancingQuanta** [comment] 2019-03-05 18:27
I have the same issues with trying to install my python packages as editable packages via PIP for development. I find that the packages were not installed in the development environment as expected.
My environment.yml
```
name: writecal_dev
channels:
  - defaults
dependencies:
  - pandas
  - pip:
    # local package
    - xlsxwriter
    - -e .
```
Activating the environment then running `conda env update -f environment.yml` does not resolve the issue. So then I will have to manually execute `pip install -e .` to get around this issue.

**Comment by ramseydsilva** [comment] 2019-03-06 00:18
Currently, my appveyor configuration uses `conda update -q conda` as is recommended, however because of this bug, i would like to pin the conda version to `4.5.12`. Anybody have any ideas how to basically tell conda to not update to the latest version, but a specific version?

**Comment by ramseydsilva** [comment] 2019-03-06 13:42
nvm, i'm just changing  `conda update -q conda` to `conda install conda==4.5.12` until this bug is fixed.

**Comment by chinmayrane** [comment] 2019-03-08 20:38
Is it fixed in https://github.com/conda/conda/releases/tag/4.6.8 ? Release Notes doesn't mention anything addressing this issue. 
Looks like this will be a major issue with production processes having reverse dependency on conda updates.

**Comment by msarahan** [comment] 2019-03-08 20:41
I think it is in the release notes:

> quote path to temporary requirements files generated by conda env. Fixes issues with spaces. (#8352)

**Comment by chinmayrane** [comment] 2019-03-08 20:46
@msarahan Thanks! I see [#8358](https://github.com/conda/conda/pull/8352) being referenced in [#8352] (https://github.com/conda/conda/pull/8352) now. Will install and check.

**Comment by msarahan** [comment] 2019-03-11 21:13
4.6.8 is available on defaults.  Closing.  If you still have problems, please open a new issue with all of the requested information.

**Closed by msarahan** 2019-03-11 21:13 UTC
