### ISSUE TITLE
Issue with "conda update --all" in a Win10 64bits box

### ISSUE THREAD

**Issue by pxcandeias** [conda/conda#1658] opened 2015-09-28 21:27 UTC
Hi,

I found the following issue when running a "conda update --all" in a Win10 64bits box:

C:\Users\Paulo\Anaconda>conda update --all
Fetching package metadata: ....
Solving package specifications: ................................An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Paulo\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Paulo\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Users\Paulo\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Users\Paulo\Anaconda\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Users\Paulo\Anaconda\lib\site-packages\conda\cli\install.py", line 337, in install
    update_deps=args.update_deps)
  File "C:\Users\Paulo\Anaconda\lib\site-packages\conda\plan.py", line 421, in install_actions
    for name in install.win_ignore_root:
AttributeError: 'module' object has no attribute 'win_ignore_root'

C:\Users\Paulo\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.0
  conda-build version : 1.17.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : C:\Users\Paulo\Anaconda  (writable)
  default environment : C:\Users\Paulo\Anaconda
     envs directories : C:\Users\Paulo\Anaconda\envs
        package cache : C:\Users\Paulo\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment] 2015-09-28 21:39
I've pushed a fix.

**Closed by asmeurer** 2015-09-28 21:39 UTC

**Comment by asmeurer** [comment] 2015-09-28 21:41
Once we push a fixed version (in a few minutes), `conda install -f conda` should fix this.

**Comment by sean-violante-lendico** [comment] 2015-09-28 21:53
same issue on windows 7.. could you maybe edit isue name

**Comment by asmeurer** [comment] 2015-09-28 21:56
@sean-violante-lendico @pxcandeias can you verify if `conda install -f conda` fixes the problem?

**Comment by sean-violante-lendico** [comment] 2015-09-28 21:59
Does not seem to fix it.

**Comment by asmeurer** [comment] 2015-09-28 22:16
Sorry. I think the only way to fix this is to either reinstall Anaconda/Miniconda, or, download the correct file for your installation below. 

[64-bit Python 2.7](http://repo.continuum.io/pkgs/free/win-64/conda-3.18.1-py27_0.tar.bz2)
[64-bit Python 3.3](http://repo.continuum.io/pkgs/free/win-64/conda-3.18.1-py33_0.tar.bz2)
[64-bit Python 3.4](http://repo.continuum.io/pkgs/free/win-64/conda-3.18.1-py34_0.tar.bz2)
[32-bit Python 2.7](http://repo.continuum.io/pkgs/free/win-32/conda-3.18.1-py27_0.tar.bz2)
[32-bit Python 3.3](http://repo.continuum.io/pkgs/free/win-32/conda-3.18.1-py33_0.tar.bz2)
[32-bit Python 3.4](http://repo.continuum.io/pkgs/free/win-32/conda-3.18.1-py34_0.tar.bz2)

Then cd to your Downloads directory and run

````
conda install <filename>
```

(replace `<filename>` with the name of the file you downloaded, like `conda-3.18.1-py27_0.tar.bz2`).

This will give the same error, but conda should work after that.

**Comment by pxcandeias** [comment] 2015-09-28 22:20
Same error here, now I can not even "conda install -f conda".

**Comment by asmeurer** [comment] 2015-09-28 22:23
Sorry. I think the only way to fix this is to either reinstall Anaconda/Miniconda, or, download the correct file for your installation below. 

[64-bit Python 2.7](http://repo.continuum.io/pkgs/free/win-64/conda-3.18.1-py27_0.tar.bz2)
[64-bit Python 3.3](http://repo.continuum.io/pkgs/free/win-64/conda-3.18.1-py33_0.tar.bz2)
[64-bit Python 3.4](http://repo.continuum.io/pkgs/free/win-64/conda-3.18.1-py34_0.tar.bz2)
[32-bit Python 2.7](http://repo.continuum.io/pkgs/free/win-32/conda-3.18.1-py27_0.tar.bz2)
[32-bit Python 3.3](http://repo.continuum.io/pkgs/free/win-32/conda-3.18.1-py33_0.tar.bz2)
[32-bit Python 3.4](http://repo.continuum.io/pkgs/free/win-32/conda-3.18.1-py34_0.tar.bz2)

You can see what your platform and Python version are by running `conda info` (should work even if conda is broken).

Then cd to your Downloads directory and run

````
conda install <filename>
conda install -f conda
```

(replace `<filename>` with the name of the file you downloaded, like `conda-3.18.1-py27_0.tar.bz2`).

This will give the same error, but conda should work after that.  The second line, `conda install -f conda` is very important. Do not skip it!

**Comment by pxcandeias** [comment] 2015-09-28 22:33
Nope, it does not work. The "conda install conda-3.18.1-py27_0.tar.bz2" command line gives the same error message.

**Comment by asmeurer** [comment] 2015-09-28 22:35
It will give the same error message, but as long as you run `conda install -f conda` immediately afterwards, it should fix it.

**Comment by pxcandeias** [comment] 2015-09-28 22:38
You are right, I was hasty. The "conda info" already gave me the new conda version (3.18.1) and the second command line finally solved it. Thanks!

**Comment by pxcandeias** [comment] 2015-09-28 22:56
Neat! You found a way of updating the core python package in Windows? I did "conda update --all" again and I am now downloading python-2.7.10 build 1. I launched Spyder and there it was, a build date of Sep 15 2015. Great work, many thanks!

**Comment by dhirschfeld** [comment] 2015-09-28 23:59
Managed to install 3.18.0 before the fix and managed to bork my conda installation before making it here :frowning: 
```
'conda' is not recognized as an internal or external command,
operable program or batch file.
```
Managed to "manually" reinstall but I might suggest that 3.18.0 be removed from the repos to prevent others falling into this trap.

**Comment by sean-violante-lendico** [comment] 2015-09-29 06:25
So I guess the problem is that my conda is broken because of this bug? so do I have to reinstall anaconda (I cannot fix a broken conda using a broken conda)

**Comment by pxcandeias** [comment] 2015-09-29 08:26
Hi,

I was also caught in the conda 3.18.0/3.18.1 loop but Aaron's instructions
to download the correct file for installation solved the problem for me.

Paulo


2015-09-29 7:25 GMT+01:00 sean-violante-lendico <notifications@github.com>:

> So I guess the problem is that my conda is broken because of this bug? so
> do I have to reinstall anaconda (I cannot fix a broken conda using a broken
> conda)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1658#issuecomment-143957719>.
>



-- 
Paulo Xavier Candeias
