### ISSUE TITLE
Unexpected error when trying to run conda update anaconda from ubuntu command line 

### ISSUE THREAD

**Issue by schrezraoeder** [conda/conda#3491] opened 2016-09-21 23:57 UTC
$ conda update anaconda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

Traceback (most recent call last):
  File "/home/ezra/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/ezra/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/home/ezra/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 488, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/ezra/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 436, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/ezra/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 406, in get_info
    args.func(args, p)
  File "/home/ezra/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 155, in execute
    from conda.api import get_index
  File "/home/ezra/anaconda2/lib/python2.7/site-packages/conda/api.py", line 7, in <module>
    from .fetch import fetch_index
  File "/home/ezra/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 20, in <module>
    from requests.packages.urllib3.connectionpool import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning

**Comment by schrezraoeder** [comment] 2016-09-21 23:58
Sorry if I'm not doing this right.

**Comment by McNees287** [comment] 2016-09-29 16:01
I've got the same problem.

**Comment by kalefranz** [comment] 2017-05-01 21:52
Duplicate of #4803

**Closed by kalefranz** 2017-05-01 21:52 UTC
