### ISSUE TITLE
upgrading to conda 4.1.8 brakes all conda commands - Exception

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3104] opened 2016-07-18 17:08 UTC
I just did

    conda update conda

to upgrade from conda 4.1.6-py27_0 to conda 4.1.8-py27_0. With conda 4.1.8, I now can't do anything, every conda command produces a NameError - that the BINSTAR_TOKEN_PATH is not defined. Worse, I can't downgrade to 4.1.6:
```
(psreldev) psel701: /reg/g/psdm/sw/conda/manage/recipes/psana $ conda list
Traceback (most recent call last):
  File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main.py", line 61, in main
    from conda.cli import conda_argparse
  File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/common.py", line 12, in <module>
    from ..config import (envs_dirs, default_prefix, platform, update_dependencies,
  File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/config.py", line 472, in <module>
    load_condarc(rc_path)
  File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/config.py", line 430, in load_condarc
    channel_alias = remove_binstar_tokens(channel_alias.rstrip('/') + '/')
  File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/config.py", line 276, in remove_binstar_tokens
    return BINSTAR_TOKEN_PAT.sub(r'\1', url)
NameError: global name 'BINSTAR_TOKEN_PAT' is not defined

```

**Comment by HugoTian** [comment] 2016-07-18 20:34
could you please run conda config --get , and show the output,

I think there is something wrong with the condarc file.

Thanks in advance

**Comment by ilanschnell** [comment] 2016-07-19 07:07
Even if `~/.condarc` is misconfigured, conda should never break in such an irrecoverable way.
CC @kalefranz

**Comment by HugoTian** [comment] 2016-07-19 14:45
@ilanschnell I agree with your idea. When I trace the bug, I find that the error happens because remove_binstar_tokens is called before init_binstar. And I think that happens since,   rc.get('channel_alias', None) is not None. So I want to check condarc file, and see how to fix it

**Comment by ilanschnell** [comment] 2016-07-19 14:50
@HugoTian you could also try to reproduce the problem

**Comment by davidslac** [comment] 2016-07-19 14:59
Sorry, for some reason I missed @HugoTian's first comment, did you still need more information? I did start from scratch, i.e, just install miniconda, then install conda-build, let it upgrade conda, I think I was able to do one thing, but then conda list had the same error - I don't think I had my custom .condarc in place yet. I've since torn down that miniconda. 

Right now, as the administer of the central install, where I had the problem, I see

    (psreldev) psel701: /reg/g/psdm/sw/conda $ conda config --get
    (psreldev) psel701: /reg/g/psdm/sw/conda $ 

that is nothing, which is a little surprising, I do have a .condarc in place per the central install - is that an issue? conda config --get is only getting your local user configuration?

**Comment by HugoTian** [comment] 2016-07-19 15:03
@davidslac Thanks for your information, and @ilanschnell I already reproduce the error

**Comment by HugoTian** [comment] 2016-07-19 15:36
@davidslac , I create a PR for this bug, hope it will woks, Pull Request #3108

**Comment by HugoTian** [comment] 2016-07-20 14:22
I will close this issue, and please refer to PR #3108. If you have any questions, feel free to reopen it

**Closed by HugoTian** 2016-07-20 14:22 UTC
Labels: bug

**Comment by davidslac** [comment] 2016-07-20 15:49
Thanks for addressing the issue so quickly! 

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by HugoTian** [comment] 2016-07-20 15:56
@davidslac , In conda 4.0.x the BINSTAR_TOKENS_PAT is always a global variable, but in 4.1.x, it's still a global variable but defined in init_binstar() function. When the remove_binstar_tokens is called before init_binstar, you will get this issue. It will definitely fixed in future.

Thanks
