### ISSUE TITLE
MD5 Error installing r-essentials (Linux and Windows)

### ISSUE THREAD

**Issue by diegocgaona** [conda/conda#1955] opened 2016-01-13 18:35 UTC
Hi, 

I had a error installing r-essentials: (in linux and windows)

```
Error: MD5 sums mismatch for download: 
http://conda.anaconda.org/r/linux-64/ncurses-5.9-4.tar.bz2 (e0ad9554f7d062cadab00b66de726f6a != 9271fc4904a6395e3221ea8ed02240a4)
```
I'm using Anaconda3 (Python 3.5.1 :: Anaconda 2.4.1 (64-bit))
Somebody can help-me?

**Comment by kalefranz** [comment] 2016-01-13 18:55
I pinged our anaconda server devs (anaconda.org).  Will let you know when something changes.

**Comment by kalefranz** [comment] 2016-01-13 19:05
Yeah so this is a problem with anaconda.org and is a dupe of #1952.  

@yosuah gave this hack, which is as good as any for now until the anaconda-server guys get this fixed

    wget https://anaconda.org/r/ncurses/5.9/download/linux-64/ncurses-5.9-4.tar.bz2 \
        https://anaconda.org/r/nlopt/2.4.2/download/linux-64/nlopt-2.4.2-1.tar.bz2 \
        https://anaconda.org/r/glib/2.43.0/download/linux-64/glib-2.43.0-2.tar.bz2 \
    && conda install --yes ncurses-5.9-4.tar.bz2 nlopt-2.4.2-1.tar.bz2 glib-2.43.0-2.tar.bz2

https://github.com/ContinuumIO/anaconda-issues/issues/621#issuecomment-171393237

**Comment by kalefranz** [comment] 2016-01-13 19:09
Going to close this ticket since the issue is being tracked in ContinuumIO/anaconda-issues#621 and #1952

**Closed** 2016-01-13 19:09 UTC

**Comment by diegocgaona** [comment] 2016-01-13 23:22
Thanks @kalefranz !!! Worked fine.

**Comment by kalefranz** [comment] 2016-01-15 18:33
I think this has now been fixed on anaconda.org.  Please update if you encounter issues again.
