### ISSUE TITLE
conda create Error when create into a dockerfile 

### ISSUE THREAD

**Issue by Christianivh** [conda/conda#7877] opened 2018-10-20 01:35 UTC
## Current Behavior
I created a new environment and installed a bunch of packages, but this error has been presented just a few days ago.

### Dockerfile 
```
FROM phusion/baseimage:latest
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update --fix-missing \
     && apt-get install --no-install-recommends -y wget bzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh

ENV PATH /opt/conda/bin:$PATH

WORKDIR /usr/src/app
COPY . .

RUN conda env create -qf environment.yml
```

### environment.yml file
```
name: test
channels:
 - anaconda
 - conda-forge
dependencies:
 - boto3==1.6.1
```

### Error 

```

Step 8/8 : RUN conda env create -qf environment.yml
 ---> Running in a4a7c99f609b
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Linux/4.9.93-linuxkit-aufs debian/stretch/sid glibc/2.23    
                UID:GID : 0:0

`$ /opt/conda/bin/conda-env create -qf environment.yml`




    Traceback (most recent call last):
      File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 29, in install
        prefix=prefix)
      File "/opt/conda/lib/python2.7/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/conda/lib/python2.7/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/opt/conda/lib/python2.7/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/conda/lib/python2.7/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/conda/lib/python2.7/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/opt/conda/lib/python2.7/site-packages/conda/core/repodata.py", line 476, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "/opt/conda/lib/python2.7/site-packages/conda/core/repodata.py", line 412, in process_repodata
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment


```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Linux/4.9.93-linuxkit-aufs debian/stretch/sid glibc/2.23    
                UID:GID : 0:0
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
channels:
 - anaconda
 - conda-forge

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda:
#
asn1crypto                0.22.0           py27h94ebe91_1    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2017.7.27.1      py27h9ceb091_0    defaults
cffi                      1.10.0           py27hf1aaaf4_1    defaults
chardet                   3.0.4            py27hfa10054_1    defaults
conda                     4.3.27           py27hff99c7a_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.0.3            py27hea39389_1    defaults
enum34                    1.1.6            py27h99a27e9_1    defaults
idna                      2.6              py27h5722d68_1    defaults
ipaddress                 1.0.18           py27h337fd85_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc-ng                 7.2.0                hcbc56d2_1    defaults
libstdcxx-ng              7.2.0                h24385c6_1    defaults
ncurses                   6.0                  h06874d7_1    defaults
openssl                   1.0.2l               h9d1a558_3    defaults
pip                       9.0.1            py27h4c18a59_2    defaults
pycosat                   0.6.2            py27h1cf261c_1    defaults
pycparser                 2.18             py27hefa08c5_1    defaults
pyopenssl                 17.2.0           py27h189ff3b_0    defaults
pysocks                   1.6.7            py27he2db6d2_1    defaults
python                    2.7.13              hfff3488_13    defaults
readline                  7.0                  hac23ff0_3    defaults
requests                  2.18.4           py27hc5b0589_1    defaults
ruamel_yaml               0.11.14          py27h672d447_2    defaults
setuptools                36.5.0           py27h68b189e_0    defaults
six                       1.10.0           py27hdcd7534_1    defaults
sqlite                    3.20.1               h6d8b0f3_1    defaults
tk                        8.6.7                h5979e9b_1    defaults
urllib3                   1.22             py27ha55213b_0    defaults
wheel                     0.29.0           py27h411dd7b_1    defaults
yaml                      0.1.7                h96e3832_1    defaults
zlib                      1.2.11               hfbfcf68_1    defaults
```
</p></details>

**Comment by Christianivh** [comment] 2018-10-20 02:14
I tried, changed my repo 

```
FROM continuumio/miniconda2:latest
WORKDIR /usr/src/app
COPY . .
RUN conda env create -qf environment.yml
```
i got the same error 😞

**Comment by mrakitin** [comment] 2018-10-20 05:37
I am struggling with the same issue while running this Docker image build: https://github.com/mrakitin/debian-with-miniconda/blob/make_image_uptodate/Dockerfile.

#7870 seems to be relevant.

**Comment by Christianivh** [comment] 2018-10-20 23:09
Solve!! the problem was the _enviroment.yaml_ file, i consider **anaconda** channels, and now i think it's terms was change, to **default** channel.  😕

**Comment by mingwandroid** [comment] 2018-10-20 23:14
No it's always been defaults since the start.

**Comment by msarahan** [comment] 2018-10-26 12:55
duplicate of #7870, closing

**Closed by msarahan** 2018-10-26 12:55 UTC
