### ISSUE TITLE
"conda update conda" fails on windows 7 (TypeError: list expected in sat)

### ISSUE THREAD

**Issue by dmfilippov** [conda/conda#2229] opened 2016-03-10 11:53 UTC
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 146, in args_func 
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 413, in install_actions
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 858, in install
    specs, preserve = self.install_specs(specs, installed or [], update_deps)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 839, in install_specs
    limit, preserve = self.bad_installed(installed, specs)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 807, in bad_installed
    solution = C.sat(constraints)
  File "C:\Anaconda\lib\site-packages\conda\logic.py", line 422, in sat
    solution = pycosat.solve(clauses, vars=self.m, prop_limit=limit)
TypeError: list expected

C:\Windows\system32>conda info
Current conda install:
             platform : win-32
        conda version : 4.0.0
  conda-build version : not installed
       python version : 2.7.5.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by mcg1969** [comment] 2016-03-10 13:34
As a workaround can you try `conda install -f conda=4.0.2`

But before you do, can you do `conda --debug update conda` and paste the (long) output here?

**Comment by dmfilippov** [comment] 2016-03-10 13:55
Thanks a lot for your prompt reply.
The output of `conda --debug update conda` pasted below.
Suggested workaround with `conda install -f conda=4.0.2` didn't help - got exactly the same (as in the starting post) error message ((

C:\Windows\system32>conda --debug update conda
DEBUG:conda.fetch:channel_urls=('https://repo.continuum.io/pkgs/free/win-32/', '
https://repo.continuum.io/pkgs/free/noarch/', 'https://repo.continuum.io/pkgs/pr
o/win-32/', 'https://repo.continuum.io/pkgs/pro/noarch/')
Fetching package metadata: INFO:stdoutlog:Fetching package metadata:
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(t
otal=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1):
 repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2):
 repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3):
 repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4):
 repo.continuum.io
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:315: SNIMis
singWarning: An HTTPS request has been made, but the SNI (Subject Name Indicatio
n) extension to TLS is not available on this platform. This may cause the server
 to present an incorrect TLS certificate, which can cause validation failures. F
or more information, see https://urllib3.readthedocs.org/en/latest/security.html
#snimissingwarning.
  SNIMissingWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:120: Insecu
rePlatformWarning: A true SSLContext object is not available. This prevents urll
ib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/securi
ty.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:120: Insecu
rePlatformWarning: A true SSLContext object is not available. This prevents urll
ib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/securi
ty.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:120: Insecu
rePlatformWarning: A true SSLContext object is not available. This prevents urll
ib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/securi
ty.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:120: Insecu
rePlatformWarning: A true SSLContext object is not available. This prevents urll
ib3 from configuring SSL appropriately and may cause certain SSL connections to
fail. For more information, see https://urllib3.readthedocs.org/en/latest/securi
ty.html#insecureplatformwarning.
  InsecurePlatformWarning
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/win-32/repodata.j
son.bz2 HTTP/1.1" 304 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/noarch/repodata.js
on.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/no
arch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession o
bject at 0x02F29950>}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/win-32/repodata.js
on.bz2 HTTP/1.1" 304 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/noarch/repodata.j
son.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/n
oarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession
object at 0x02F29950>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/wi
n-32/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession o
bject at 0x02F29950>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/w
in-32/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession
object at 0x02F29950>}

INFO:stdoutlog:

DEBUG:conda.plan:Pinned specs=[]
.DEBUG:dotupdate:explicit([MatchSpec('conda'), MatchSpec('conda')]) finished
DEBUG:conda.plan:H0 specs=['conda', 'conda']
DEBUG:conda.plan:H2 python True
DEBUG:conda.plan:H3 python
DEBUG:conda.plan:H2 lua False
DEBUG:conda.plan:H2A lua
DEBUG:conda.plan:HF specs=['conda', 'conda', 'python 2.7*']
DEBUG:conda.resolve:Checking satisfiability of current install
DEBUG:conda.resolve:Checking if the current environment is consistent
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 146, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 48, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 334, in instal
l
    update_deps=args.update_deps)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 413, in install_actio
ns
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update
_deps)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 858, in install
    specs, preserve = self.install_specs(specs, installed or [], update_deps)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 839, in install_sp
ecs
    limit, preserve = self.bad_installed(installed, specs)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 807, in bad_instal
led
    solution = C.sat(constraints)
  File "C:\Anaconda\lib\site-packages\conda\logic.py", line 422, in sat
    solution = pycosat.solve(clauses, vars=self.m, prop_limit=limit)
TypeError: list expected

**Comment by mcg1969** [comment] 2016-03-10 15:49
Hmm, this one's challenging. Would you please do me a favor and give me the output of "conda list" as well?

**Comment by dmfilippov** [comment] 2016-03-10 16:05
Yes, of course! Please find the output cited below:

```
C:\Windows\system32>conda list
# packages in environment at C:\Anaconda:
#
Could not extract name and version from: 'Warning: cannot find svn location for joblib==0.8.3-r1'
_license                  1.1                      py27_0    <unknown>
amqp                      1.4.5                     <pip>
anaconda                  2.1.0                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/anaconda-2.1.0-np19py27_0.tar.bz2
anyjson                   0.3.3                     <pip>
apptools                  4.2.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/apptools-4.2.1-py27_0.tar.bz2
argcomplete               0.8.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/argcomplete-0.8.1-py27_0.tar.bz2
astropy                   0.4.2                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/astropy-0.4.2-np19py27_0.tar.bz2
atom                      0.3.9                    py27_0    http://repo.continuum.io/pkgs/free/win-32/atom-0.3.9-py27_0.tar.bz2
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.7.1                np18py27_0    http://repo.continuum.io/pkgs/free/win-32/bcolz-0.7.1-np18py27_0.tar.bz2
beautiful-soup            4.3.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/beautiful-soup-4.3.2-py27_0.tar.bz2
beautifulsoup4            4.3.2                     <pip>
billiard                  3.3.0.18                  <pip>
binstar                   0.7.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/binstar-0.7.1-py27_0.tar.bz2
biopython                 1.63                 np18py27_0    http://repo.continuum.io/pkgs/free/win-32/biopython-1.63-np18py27_0.tar.bz2
bitarray                  0.8.1                    py27_1    http://repo.continuum.io/pkgs/free/win-32/bitarray-0.8.1-py27_1.tar.bz2
blaze                     0.6.3                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/blaze-0.6.3-np19py27_0.tar.bz2
blz                       0.6.2                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/blz-0.6.2-np19py27_0.tar.bz2
bokeh                     0.6.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/bokeh-0.6.1-np19py27_0.tar.bz2
boto                      2.32.1                   py27_0    http://repo.continuum.io/pkgs/free/win-32/boto-2.32.1-py27_0.tar.bz2
brewer2mpl                1.3.2                     <pip>
casuarius                 1.1                      py27_0    <unknown>
cdecimal                  2.3                      py27_1    http://repo.continuum.io/pkgs/free/win-32/cdecimal-2.3-py27_1.tar.bz2
celery                    3.1.13                    <pip>
cffi                      0.8.6                    py27_0    http://repo.continuum.io/pkgs/free/win-32/cffi-0.8.6-py27_0.tar.bz2
chaco                     4.4.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/chaco-4.4.1-np19py27_0.tar.bz2
colorama                  0.3.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/colorama-0.3.1-py27_0.tar.bz2
conda                     4.0.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/conda-4.0.0-py27_0.tar.bz2
conda-env                 2.4.5                    py27_0    http://repo.continuum.io/pkgs/free/win-32/conda-env-2.4.5-py27_0.tar.bz2
configobj                 5.0.6                    py27_0    http://repo.continuum.io/pkgs/free/win-32/configobj-5.0.6-py27_0.tar.bz2
cryptography              0.5.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/cryptography-0.5.4-py27_0.tar.bz2
cubes                     0.10.2                   py27_4    http://repo.continuum.io/pkgs/free/win-32/cubes-0.10.2-py27_4.tar.bz2
cython                    0.21                     py27_0    http://repo.continuum.io/pkgs/free/win-32/cython-0.21-py27_0.tar.bz2
cytoolz                   0.7.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/cytoolz-0.7.0-py27_0.tar.bz2
datashape                 0.3.0                np19py27_1    http://repo.continuum.io/pkgs/free/win-32/datashape-0.3.0-np19py27_1.tar.bz2
dateutil                  2.1                      py27_2    <unknown>
decorator                 3.4.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/decorator-3.4.0-py27_0.tar.bz2
distribute                0.6.45                   py27_0    <unknown>
docopt                    0.6.2                     <pip>
docutils                  0.12                     py27_0    http://repo.continuum.io/pkgs/free/win-32/docutils-0.12-py27_0.tar.bz2
dynd-python               0.6.5                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/dynd-python-0.6.5-np19py27_0.tar.bz2
enable                    4.3.0                np19py27_2    http://repo.continuum.io/pkgs/free/win-32/enable-4.3.0-np19py27_2.tar.bz2
enaml                     0.9.8                    py27_0    http://repo.continuum.io/pkgs/free/win-32/enaml-0.9.8-py27_0.tar.bz2
envisage                  4.4.0                    py27_1    http://repo.continuum.io/pkgs/free/win-32/envisage-4.4.0-py27_1.tar.bz2
fdb                       1.5                       <pip>
feedparser                5.1.3                    py27_1    http://repo.continuum.io/pkgs/free/win-32/feedparser-5.1.3-py27_1.tar.bz2
flask                     0.10.1                   py27_1    <unknown>
future                    0.13.1                   py27_0    http://repo.continuum.io/pkgs/free/win-32/future-0.13.1-py27_0.tar.bz2
futures                   2.1.6                    py27_0    http://repo.continuum.io/pkgs/free/win-32/futures-2.1.6-py27_0.tar.bz2
gdbn                      0.1                       <pip>
gevent                    1.0.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/gevent-1.0.1-py27_0.tar.bz2
gevent-websocket          0.9.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/gevent-websocket-0.9.3-py27_0.tar.bz2
gevent-zeromq             0.2.2                     <pip>
gevent_zeromq             0.2.5                    py27_3    http://repo.continuum.io/pkgs/free/win-32/gevent_zeromq-0.2.5-py27_3.tar.bz2
gnumpy                    0.2                       <pip>
greenlet                  0.4.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/greenlet-0.4.4-py27_0.tar.bz2
grin                      1.2.1                    py27_2    <unknown>
h5py                      2.3.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/h5py-2.3.1-np19py27_0.tar.bz2
imaging                   1.1.7                    py27_2    <unknown>
ipython                   2.3.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/ipython-2.3.1-py27_0.tar.bz2
ipython-notebook          2.2.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/ipython-notebook-2.2.0-py27_0.tar.bz2
ipython-qtconsole         2.2.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/ipython-qtconsole-2.2.0-py27_0.tar.bz2
itsdangerous              0.24                     py27_0    http://repo.continuum.io/pkgs/free/win-32/itsdangerous-0.24-py27_0.tar.bz2
jdcal                     1.0                      py27_0    http://repo.continuum.io/pkgs/free/win-32/jdcal-1.0-py27_0.tar.bz2
jinja2                    2.7.3                    py27_1    http://repo.continuum.io/pkgs/free/win-32/jinja2-2.7.3-py27_1.tar.bz2
joblib-0.8.3              r1                        <pip>
keyring                   3.3                      py27_0    http://repo.continuum.io/pkgs/free/win-32/keyring-3.3-py27_0.tar.bz2
kiwisolver                0.1.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/kiwisolver-0.1.3-py27_0.tar.bz2
kombu                     3.0.21                    <pip>
launcher                  1.0.0                         1    http://repo.continuum.io/pkgs/free/win-32/launcher-1.0.0-1.tar.bz2
libpython                 1.0                      py27_1    http://repo.continuum.io/pkgs/free/win-32/libpython-1.0-py27_1.tar.bz2
llvmmath                  0.1.1                np17py27_2    <unknown>
llvmpy                    0.12.7                   py27_0    http://repo.continuum.io/pkgs/free/win-32/llvmpy-0.12.7-py27_0.tar.bz2
lxml                      3.4.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/lxml-3.4.0-py27_0.tar.bz2
markupsafe                0.23                     py27_0    http://repo.continuum.io/pkgs/free/win-32/markupsafe-0.23-py27_0.tar.bz2
matplotlib                1.4.2                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/matplotlib-1.4.2-np19py27_0.tar.bz2
mayavi                    4.3.1                np18py27_0    http://repo.continuum.io/pkgs/free/win-32/mayavi-4.3.1-np18py27_0.tar.bz2
mdp                       3.3                  np18py27_0    http://repo.continuum.io/pkgs/free/win-32/mdp-3.3-np18py27_0.tar.bz2
menuinst                  1.3.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/menuinst-1.3.2-py27_0.tar.bz2
meta                      0.4.2.dev                py27_0    <unknown>
mingw                     4.7                           1    <unknown>
mock                      1.0.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/mock-1.0.1-py27_0.tar.bz2
msvc_runtime              1.0.1                     vc9_0  [vc9]  http://repo.continuum.io/pkgs/free/win-32/msvc_runtime-1.0.1-vc9_0.tar.bz2
multipledispatch          0.4.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/multipledispatch-0.4.7-py27_0.tar.bz2
netcdf4                   1.0.8                np18py27_0    http://repo.continuum.io/pkgs/free/win-32/netcdf4-1.0.8-np18py27_0.tar.bz2
networkx                  1.9.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/networkx-1.9.1-py27_0.tar.bz2
nltk                      3.0.0                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/nltk-3.0.0-np19py27_0.tar.bz2
node-webkit               0.10.1                        0    http://repo.continuum.io/pkgs/free/win-32/node-webkit-0.10.1-0.tar.bz2
nolearn                   0.4                       <pip>
nose                      1.3.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/nose-1.3.4-py27_0.tar.bz2
numba                     0.14.0               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/numba-0.14.0-np19py27_0.tar.bz2
numexpr                   2.3.1                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/numexpr-2.3.1-np19py27_0.tar.bz2
numpy                     1.9.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/numpy-1.9.1-py27_0.tar.bz2
opengraph                 0.5                       <pip>
openpyxl                  1.8.5                    py27_0    http://repo.continuum.io/pkgs/free/win-32/openpyxl-1.8.5-py27_0.tar.bz2
pandas                    0.15.1               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/pandas-0.15.1-np19py27_0.tar.bz2
patsy                     0.3.0                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/patsy-0.3.0-np19py27_0.tar.bz2
pep8                      1.5.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pep8-1.5.7-py27_0.tar.bz2
pil                       1.1.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pil-1.1.7-py27_0.tar.bz2
pip                       1.5.6                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pip-1.5.6-py27_0.tar.bz2
ply                       3.4                      py27_0    <unknown>
psutil                    1.1.2                    py27_0    <unknown>
py                        1.4.25                   py27_0    http://repo.continuum.io/pkgs/free/win-32/py-1.4.25-py27_0.tar.bz2
pycosat                   0.6.0                    py27_0    <unknown>
pycparser                 2.10                     py27_0    http://repo.continuum.io/pkgs/free/win-32/pycparser-2.10-py27_0.tar.bz2
pycrypto                  2.6.1                    py27_2    http://repo.continuum.io/pkgs/free/win-32/pycrypto-2.6.1-py27_2.tar.bz2
pyface                    4.4.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pyface-4.4.0-py27_0.tar.bz2
pyflakes                  0.8.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pyflakes-0.8.1-py27_0.tar.bz2
pygments                  1.6                      py27_0    <unknown>
pykit                     0.2.0                np18py27_0    http://repo.continuum.io/pkgs/free/win-32/pykit-0.2.0-np18py27_0.tar.bz2
pymongo                   2.6.3                     <pip>
pymssql                   2.1.1                     <pip>
pyodbc                    3.0.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pyodbc-3.0.7-py27_0.tar.bz2
pyopenssl                 0.14                     py27_0    http://repo.continuum.io/pkgs/free/win-32/pyopenssl-0.14-py27_0.tar.bz2
pyparsing                 2.0.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pyparsing-2.0.1-py27_0.tar.bz2
pyqt                      4.10.4                   py27_0    http://repo.continuum.io/pkgs/free/win-32/pyqt-4.10.4-py27_0.tar.bz2
pyreadline                2.0                      py27_0    http://repo.continuum.io/pkgs/free/win-32/pyreadline-2.0-py27_0.tar.bz2
pysal                     1.6.0                np18py27_1    http://repo.continuum.io/pkgs/free/win-32/pysal-1.6.0-np18py27_1.tar.bz2
pyside                    1.2.1                    py27_0    <unknown>
pysimplesoap              1.05a                     <pip>
pytables                  3.1.1                np19py27_1    http://repo.continuum.io/pkgs/free/win-32/pytables-3.1.1-np19py27_1.tar.bz2
pytest                    2.6.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/pytest-2.6.3-py27_0.tar.bz2
python                    2.7.5                         2    <unknown>
python-dateutil           1.5                       <pip>
pytz                      2014.9                   py27_0    http://repo.continuum.io/pkgs/free/win-32/pytz-2014.9-py27_0.tar.bz2
pywin32                   219                      py27_0    http://repo.continuum.io/pkgs/free/win-32/pywin32-219-py27_0.tar.bz2
pyyaml                    3.11                     py27_3    http://repo.continuum.io/pkgs/free/win-32/pyyaml-3.11-py27_3.tar.bz2
pyzmq                     14.3.1                   py27_0    http://repo.continuum.io/pkgs/free/win-32/pyzmq-14.3.1-py27_0.tar.bz2
requests                  2.9.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/requests-2.9.1-py27_0.tar.bz2
rope                      0.9.4                    py27_1    http://repo.continuum.io/pkgs/free/win-32/rope-0.9.4-py27_1.tar.bz2
runipy                    0.1.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/runipy-0.1.1-py27_0.tar.bz2
scikit-image              0.10.1               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/scikit-image-0.10.1-np19py27_0.tar.bz2
scikit-learn              0.15.2               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/scikit-learn-0.15.2-np19py27_0.tar.bz2
scipy                     0.14.0               np19py27_0    http://repo.continuum.io/pkgs/free/win-32/scipy-0.14.0-np19py27_0.tar.bz2
seaborn                   0.5.0                np19py27_0    http://repo.continuum.io/pkgs/free/win-32/seaborn-0.5.0-np19py27_0.tar.bz2
setuptools                7.0                      py27_0    http://repo.continuum.io/pkgs/free/win-32/setuptools-7.0-py27_0.tar.bz2
six                       1.8.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/six-1.8.0-py27_0.tar.bz2
sockjs-tornado            1.0.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sockjs-tornado-1.0.1-py27_0.tar.bz2
sphinx                    1.2.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sphinx-1.2.3-py27_0.tar.bz2
spyder                    2.3.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/spyder-2.3.1-py27_0.tar.bz2
spyder-app                2.3.1                    py27_0    http://repo.continuum.io/pkgs/free/win-32/spyder-app-2.3.1-py27_0.tar.bz2
sqlalchemy                0.9.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sqlalchemy-0.9.7-py27_0.tar.bz2
ssl_match_hostname        3.4.0.2                  py27_0    http://repo.continuum.io/pkgs/free/win-32/ssl_match_hostname-3.4.0.2-py27_0.tar.bz2
statsmodels               0.5.0                np19py27_2    http://repo.continuum.io/pkgs/free/win-32/statsmodels-0.5.0-np19py27_2.tar.bz2
sympy                     0.7.5                    py27_0    http://repo.continuum.io/pkgs/free/win-32/sympy-0.7.5-py27_0.tar.bz2
tables                    3.1.1                     <pip>
toolz                     0.7.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/toolz-0.7.0-py27_0.tar.bz2
tornado                   4.0.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/tornado-4.0.2-py27_0.tar.bz2
traits                    4.4.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/traits-4.4.0-py27_0.tar.bz2
traitsui                  4.4.0                    py27_0    http://repo.continuum.io/pkgs/free/win-32/traitsui-4.4.0-py27_0.tar.bz2
twitter                   1.15.0                    <pip>
ujson                     1.33                     py27_0    http://repo.continuum.io/pkgs/free/win-32/ujson-1.33-py27_0.tar.bz2
unicodecsv                0.9.4                    py27_0    http://repo.continuum.io/pkgs/free/win-32/unicodecsv-0.9.4-py27_0.tar.bz2
vtk                       5.10.1                   py27_0    <unknown>
werkzeug                  0.9.6                    py27_1    http://repo.continuum.io/pkgs/free/win-32/werkzeug-0.9.6-py27_1.tar.bz2
wsgiref                   0.1.2                     <pip>
xlrd                      0.9.3                    py27_0    http://repo.continuum.io/pkgs/free/win-32/xlrd-0.9.3-py27_0.tar.bz2
xlsxwriter                0.5.7                    py27_0    http://repo.continuum.io/pkgs/free/win-32/xlsxwriter-0.5.7-py27_0.tar.bz2
xlwings                   0.2.2                    py27_0    http://repo.continuum.io/pkgs/free/win-32/xlwings-0.2.2-py27_0.tar.bz2
xlwt                      0.7.5                    py27_0    <unknown>
```

**Comment by mcg1969** [comment] 2016-03-10 18:27
Great, thank you! I'll try and figure this out, but I'm a bit concerned that you may be in a situation where you can't update your way out of this.

**Comment by mcg1969** [comment] 2016-03-10 19:12
Whoa, why is this here?
> python                    2.7.5                         2    <unknown>

It doesn't seem to know where you got your python installation from?

**Comment by dmfilippov** [comment] 2016-03-10 20:03
Actually I've got several python installations:
1. Anaconda (C:\Anaconda) v 2.7.5
2. "Vanilla" Python (C:\Python27) v 2.7.3
3. pypy (C:\pypy) v 2.7.3
4. 64 bit "vanilla" Python (D:\Python27) v 2.7.6

so I kinda lost - how comes that conda detects 2 installations of 2.7.5 and, more interestingly, it wasn't an issue earlier, during previous updates with `conda update conda`. 

Or maybe I'm interpreting your remark concerning python installation wrong? 

BTW, I found  a file `C:\Anaconda\conda-meta\python-2.7.5-2.json` - named suspiciously similar to the line that caught your attention in your previous message. Maybe I'm barking on a wrong tree, though.

**Comment by mcg1969** [comment] 2016-03-10 20:27
Oh, sorry, I wasn't clear above. What I was looking for with `conda list` is a list of the filenames for your conda packages. Sure enough, I see every single one above... _except Python itself_. I think that `json` file you've found fills in that missing info. I'll keep digging.

**Comment by dmfilippov** [comment] 2016-03-10 20:48
Thank you very much for the clarification. 
Just in case - the (abridged) contents of the  aforementioned file:

```
C:\Anaconda\conda-meta\python-2.7.5-2.json
{
  "arch": "x86", 
  "build": "2", 
  "build_number": 2, 
  "files": [
    "DLLs/_bsddb.pyd", 
    "DLLs/_ctypes.pyd",
    ...
    _<skipped about 3700 filenames>_
    ...
    "tcl/tkstub85.lib", 
    "w9xpopen.exe"
  ], 
  "name": "python", 
  "platform": "win", 
  "requires": [], 
  "version": "2.7.5"
}
```

**Comment by mcg1969** [comment] 2016-03-12 22:09
@mathursomyak, can you please offer up two things:

- the full output of `conda list`
- the full output of `conda info`
- the full output of `conda --debug update anaconda`

Thanks!

**Comment by mcg1969** [comment] 2016-03-12 22:10
This bug is occurring in the code that checks if the installed set of packages is valid. Something is failing in this section in an unexpected manner. I worked on this code so I'd definitely like to get this figured out.

**Comment by mcg1969** [comment] 2016-03-12 22:11
For my reference this is @mathursomyak's `conda info`:
```
Current conda install:

             platform : win-64
        conda version : 4.0.4
  conda-build version : 1.2.0
       python version : 2.7.6.final.0
     requests version : 2.9.1
     root environment : C:\Users\skmathur\Anaconda  (writable)
  default environment : C:\Users\skmathur\Anaconda
     envs directories : C:\Users\skmathur\Anaconda\envs
        package cache : C:\Users\skmathur\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by mcg1969** [comment] 2016-03-12 22:22
Once we get the solution figured out, we're going to have to help you both to "force" install this update so that you can once again start using conda. I do apologize for this! What's happening is this: because of bugs in _previous_ versions of conda, your installations have some dependency conflicts. The new version of conda no longer allows this; but because your installations are already in this state, it needs to figure out how to respond gracefully. Clearly it is failing to do that!

**Comment by dmfilippov** [comment] 2016-03-15 07:42
Michael, thanks a lot for helping with the issue! Will wait for your suggestions. 

P.S. Sorry for not replying earlier, was offline.

**Comment by JamesRamm** [comment] 2016-03-15 10:29
Hallo! I have the same problem; Is there a workaround available?
I'm tempted to just uninstall and start afresh...

**Comment by msarahan** [comment] 2016-03-15 11:59
If uninstalling and reinstalling is easy for you, go for it. That should work to fix the inconsistent state that causes this problem.

**Comment by kalefranz** [comment] 2016-03-16 14:52
Hopefully fixed in #2251.  Please comment here (and re-open) if not.

**Closed by kalefranz** 2016-03-16 14:52 UTC
Labels: bug

**Comment by dmfilippov** [comment] 2016-03-18 07:03
Had to reinstall anaconda from scratch. Everything works fine now ) Thanks for your efforts, suggestions and help!

**Comment by mcg1969** [comment] 2016-04-06 17:08
For those who happen upon this issue: it turns out that the problem was caused by the presence of `pycosat 0.6.0` in your environment, installed by `pip`. In fact, `conda` requires 0.6.1. Normally, that is the version that would be installed when updating to `conda 4.x`, but for some reason that was not happening, possibly because `pycosat` was pip installed. We're going to add a fix to `conda` so that it still operates even with `pycosat 0.6.0`.
