### ISSUE TITLE
Newest compiler_compat changes seem to break python setup.py scripts

### ISSUE THREAD

**Issue by ezyang** [conda/conda#6132] opened 2017-10-09 22:18 UTC
Here is an attempt to build a trivial C extension via Python setup.py on an essentially new miniconda install, with 'defaults' gcc installed:

```
$ conda install gcc
Fetching package metadata ...........
Solving package specifications: .

The following NEW packages will be INSTALLED:

    cloog: 0.18.0-0        
    gcc:   4.8.5-7         
    gmp:   6.1.2-hb3b607b_0
    isl:   0.12.2-0        
    mpc:   1.0.3-hf803216_4
    mpfr:  3.1.5-h12ff648_1
$ python setup.py build
running build
running build_ext
building 'foo' extension
creating build
creating build/temp.linux-x86_64-3.6
gcc -pthread -B /private/home/ezyang/pytorch/env/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/private/home/ezyang/pytorch/env/include/python3.6m -c foo.c -o build/temp.linux-x86_64-3.6/foo.o
creating build/lib.linux-x86_64-3.6
gcc -pthread -shared -B /private/home/ezyang/pytorch/env/compiler_compat -L/private/home/ezyang/pytorch/env/lib -Wl,-rpath=/private/home/ezyang/pytorch/env/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/foo.o -L/private/home/ezyang/pytorch/env/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/foo.cpython-36m-x86_64-linux-gnu.so
/private/home/ezyang/pytorch/env/compiler_compat/ld: cannot find -lpthread
/private/home/ezyang/pytorch/env/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
$ cat setup.py
from distutils.core import setup, Extension
setup(name='foo',
      version='1.0',
      ext_modules=[Extension('foo', ['foo.c'])],
      )
$ cat foo.c
$ 
```

You can see that there is some business with `-B /private/home/ezyang/pytorch/env/compiler_compat`; this particular line is breaking the build when used with 'defaults' gcc. Using my system gcc there is no problem (i.e., omit the `conda install gcc`)

**Comment by mingwandroid** [comment] 2017-10-09 22:27
We no longer support the defaults gcc. Please use `gcc_linux-64` or `gcc_linux-64`

**Comment by ezyang** [comment] 2017-10-10 02:42
Is there some way we can get conda to report an error in this case? It is very confusing for this to silently not work! Also, where was this change advertised?

**Comment by mingwandroid** [comment] 2017-10-10 15:49
Conda used to report such 'clobbering' and took steps to prevent it, disallowing it to happen. The problem is it is impossible to prevent it when you have independent endeavours creating packages with overlapping files.

We *could* make a new 'gcc' metapackage and put it in the new 'main' channel so that it gets selected in preference to the old one (we do this for 'libgcc'). 'gcc' was never meant as a user-facing package anyway, it was always just a stop-gap compiler so we could compile things that needed C++11 so there was never *any* advertising around it.

**Comment by kalefranz** [comment] 2017-10-10 19:28
> Is there some way we can get conda to report an error in this case?

Yes.

    conda config --set path_conflict warn

or 

    conda config --set path_conflict prevent

The default in conda 4.3 is

    conda config --set path_conflict clobber

**Comment by kalefranz** [comment] 2017-10-12 20:11
I'm going to close this issue.  Really not related to the code contained within this repo.

**Closed by kalefranz** 2017-10-12 20:11 UTC
Labels: source:community, type:support

**Comment by rcasero** [comment] 2018-01-08 11:45
This error has driven me crazy for a couple of days. Very useful finding this issue.
