### ISSUE TITLE
conda create --dry-run throws an exception traceback

### ISSUE THREAD

**Issue by mwiebe** [conda/conda#3490] opened 2016-09-21 20:54 UTC
```
C:\>conda create -n testing --dry-run python=2.7

Package plan for installation in environment C:\Anaconda3\envs\testing:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vs2008_runtime-9.00.30729.1|                2         1.0 MB
    python-2.7.12              |                0        23.5 MB
    ------------------------------------------------------------
                                           Total:        24.5 MB

The following NEW packages will be INSTALLED:

    python:         2.7.12-0
    vs2008_runtime: 9.00.30729.1-2

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 2.0.1
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\mwiebe\.condarc
           offline mode : False



`$ C:\Anaconda3\Scripts\conda-script.py create -n testing --dry-run python=2.7`




    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 398, in install
        common.confirm_yn(args)
      File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 433, in confirm_yn
        raise DryRunExit
    TypeError: __init__() missing 1 required positional argument: 'message'
```

**Comment by murison** [comment] 2016-09-23 16:23
I, too, have encountered this just today:

\> conda create --dry-run -n test python=3 numpy astropy

Package plan for installation in environment /scr/bin/anaconda3/envs/test:

The following NEW packages will be INSTALLED:

    astropy:    1.2.1-np111py35_0
    mkl:        11.3.3-0         
    numpy:      1.11.1-py35_0    
    openssl:    1.0.2i-0         
    pip:        8.1.2-py35_0     
    python:     3.5.2-0          
    readline:   6.2-2            
    setuptools: 27.2.0-py35_0    
    sqlite:     3.13.0-0         
    tk:         8.5.18-0         
    wheel:      0.29.0-py35_0    
    xz:         5.2.2-0          
    zlib:       1.2.8-3          

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /scr/bin/anaconda3  (writable)
    default environment : /scr/bin/anaconda3
       envs directories : /scr/bin/anaconda3/envs
          package cache : /scr/bin/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /scr/bin/anaconda3/bin/conda create --dry-run -n test python=3 numpy astropy`




    Traceback (most recent call last):
      File "/scr/bin/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/scr/bin/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/scr/bin/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/scr/bin/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 398, in install
        common.confirm_yn(args)
      File "/scr/bin/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 433, in confirm_yn
        raise DryRunExit
    TypeError: __init__() missing 1 required positional argument: 'message'

**Comment by ddraayer** [comment] 2016-09-27 03:50
It looks like the `message` argument to `DryRunExit.__init__` became a required one early in August. But the places that raise `DryRunExit` were not updated to supply it. So either they need to be remedied or (simple fix) a default message should be provided, making the `message` argument optional.

**Comment by kalefranz** [comment] 2017-05-05 19:09
Duplicate of #3485.  Also fixed.

**Closed by kalefranz** 2017-05-05 19:09 UTC
