### ISSUE TITLE
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

### ISSUE THREAD

**Issue by giselachen** [conda/conda#3996] opened 2016-12-03 05:19 UTC
Hi,

I was trying to download seaborn using condo install seaborn and got this error message. Would appreciate if someone can trouble shoot this for me. Thank you~

Current conda install:

               platform : osx-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 1.14.1
         python version : 2.7.10.final.0
       requests version : 2.12.1
       root environment : /Users/CodeGisela/anaconda  (writable)
    default environment : /Users/CodeGisela/anaconda
       envs directories : /Users/CodeGisela/anaconda/envs
          package cache : /Users/CodeGisela/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/CodeGisela/anaconda/bin/conda install seaborn`

    Traceback (most recent call last):
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 282, in fetch_index
        for url in urls]
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/CodeGisela/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by 0bserver07** [comment] 2016-12-11 09:36
I'm getting same error after trying to install:
` conda install opencv`

**Comment by kalefranz** [comment] 2017-05-01 19:55
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:55 UTC
