### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by marswatson** [conda/conda#3980] opened 2016-12-01 04:16 UTC
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.19.0
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : F:\Anaconda2  (writable)
    default environment : F:\Anaconda2
       envs directories : F:\Anaconda2\envs
          package cache : F:\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ F:\Anaconda2\Scripts\conda-script.py install plotly`

    Traceback (most recent call last):
      File "F:\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "F:\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "F:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "F:\Anaconda2\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "F:\Anaconda2\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "F:\Anaconda2\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "F:\Anaconda2\lib\site-packages\concurrent\futures\_base.py", line 403, in result
        return self.__get_result()
      File "F:\Anaconda2\lib\site-packages\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "F:\Anaconda2\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "F:\Anaconda2\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "F:\Anaconda2\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "F:\Anaconda2\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "F:\Anaconda2\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "F:\Anaconda2\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "F:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "F:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "F:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "F:\Anaconda2\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "F:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "F:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by hasStephen** [comment] 2017-02-07 14:55
I'm getting the same error and have no idea why

**Comment by kalefranz** [comment] 2017-05-01 19:56
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:56 UTC
