### ISSUE TITLE
anaconda.asc is not supported on RHEL9/CentOS9Stream

### ISSUE THREAD

**Issue by BennyItkin** [conda/conda#12175] opened 2022-12-13 13:32 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When trying to install conda from the rpm repo on RHEL9/CentOS9Stream (my guess that latest fedora and rocky Linux will suffer the same but I didn't tested it), the anaconda.asc key cannot be imported by rpm:
`server # rpm --import https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
error: https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc: key 1 import failed.`

from a short google search I found that RHEL removed support for SHA1 based signing keys:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/considerations_in_adopting_rhel_9/index#assembly_software-management_considerations-in-adopting-RHEL-9:~:text=xml%20output_directory.-,10.2.%20Crypto%2Dpolicies%2C%20RHEL%20core%20cryptographic%20components%2C%20and%20protocols,-Continuing%20SHA%2D1

a WA listed in the RHEL release notes is to reduce the security crypto policy of the server and after that the import works.
`# update-crypto-policies --set DEFAULT:SHA1`

### Conda Info

```shell
N/A never installed.
```

### Conda Config

```shell
N/A never installed.
```

### Conda list

```shell
N/A never installed.
```

### Additional Context

```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.0 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.0 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"

```

**Comment by BennyItkin** [comment] 2023-01-08 12:42
Hi, any update ?

**Comment by travishathaway** [comment] 2023-01-24 13:35
Hi @BennyItkin,

Thanks for filing this issue. I am currently trying to track down exactly who is responsible for maintaining conda releases on RHEL. There's a slight chance that this simply isn't supported there though.

Please keep an eye this issue for updates.

**Comment by travishathaway** [comment] 2023-01-24 15:07
Hi @BennyItkin,

I've spoken with those responsible for maintaining this and they have confirmed that this has been resolved.

Can you please confirm whether or not you are still having this issue? If not, I kindly ask that you close out this issue.

**Comment by BennyItkin** [comment] 2023-03-08 11:49
Hi @travishathaway 

thanks for the response, sorry i was away for a while and didnt had the chance to check until now, seems like it still has the sha1 signature and it cannot be imported into rpm on rhel9/Centos Stream9 systems:

rpm --import https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc: key 1 import failed.

**Comment by travishathaway** [comment] 2023-03-24 15:22
Hi @BennyItkin,

I just want to let you know that this is something that is still being worked on. I can't say exactly when it will be fixed, but sometime in the next month seems to be a fair estimate at this point.

Because this issue is related specifically to anaconda.org, I will be closing this issue now. It is not directly related to the conda package manager and therefore considered off topic.

**Closed by travishathaway** 2023-03-24 15:22 UTC
Labels: type::bug, source::community, pending::support

**Comment by pseudoyim** [comment] 2023-04-10 20:38
Hi @BennyItkin. Thank you for your patience. We've finished making several updates for our RPM and Debian repos, and you should now be able to run the steps documented [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html). Please let us know if you continue to run into any issues.

**Comment by vndroid** [comment] 2024-01-17 06:51
Now, It still can not work.

```
## AlmaLinux-9
$ sudo rpm --import https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc: key 1 import failed.
```

From [RPM and Debian Repositories for Miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html)
