### ISSUE TITLE
'C:\Users\PKumar\Continuum\anaconda3\Scripts\activate.bat' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ItsPavan** [conda/conda#6053] opened 2017-10-02 11:33 UTC
'C:\Users\PKumar\Continuum\anaconda3\Scripts\activate.bat' is not recognized as an internal or external command, operable program or batch file.
Encountered above error in anaconda prompt,i tried pasting activate.bat file into scripts directory,but the dependancies for other files are missing.

**Comment by kalefranz** [comment] 2017-10-02 21:15
Does the file `C:\Users\PKumar\Continuum\anaconda3\Scripts\activate.bat` exist on your system?

**Comment by ItsPavan** [comment] 2017-10-03 03:10
activate.bat file exists in the
path C:\Users\PKumar\Anaconda\pkgs\conda-4.3.27-py36hcbae3bd_0\Scripts.
Not sure if this activate.bat is same as C:\Users\PKumar\Con
tinuum\anaconda3\Scripts\activate.bat.
I tried pasting
C:\Users\PKumar\Anaconda\pkgs\conda-4.3.27-py36hcbae3bd_0\Scripts\activate.bat
to C:\Users\PKumar\Continuum\anaconda3\Scripts,but it was throwing error
for other dependancies.

**Comment by neelpython** [comment] 2017-10-28 18:41
i am having the same problem after installing anaconda3

**Comment by ccscroggin** [comment] 2017-11-08 01:47
I am having the same issue - any help would be appreciated. For me, activate.bat does not exist in the scripts directory, but does exist in the same location noted by ItsPavan, as well as a few others. I am on my work laptop, so don't have admin privileges and a anti-virus software may be causing installation issues. Also, I previously installed and uninstalled the 32bit version. I don't see the Anaconda navigator as an option in my start menu following installation.

**Comment by Aslizy** [comment] 2017-11-14 11:08
Hi, @ccscroggin. I have the same issue as you. activate.bat is not in the anaconda3\scripts directory, but in the C:\Users\Wei\Anaconda3\pkgs\conda-4.3.30-py36h7e176b0_0\Scripts. I do not know if they are the same activate file. And I do not see the Anaconda navigator as an option after installation. Did you solve this issue, and can anybody help? 

I used to install and uninstalled the 64bit version, because after installing opencv3, navigator and spyder both did not work any more.....

**Comment by Aslizy** [comment] 2017-11-14 11:54
Just now, I uninstalled the Anaconda, and restarted my laptop, and reinstalled Anaconda again. Anaconda navigator works and activate. bat also works. :) Maybe it is a good idea to restart your laptop between uninstall and reinstall. 

Adding path in the environment variable or shutting down anti-virus software does not really help me. But maybe it works for other situations.

**Comment by ccscroggin** [comment] 2017-12-02 16:13
Thanks, @Aslizy . I am still having this issue, and on a different computer now - so don't think it was due to antivirus software. Going to try your suggestion.

**Comment by neelpython** [comment] 2017-12-02 16:23
Hi Mr kumar When I had the similar problem all I did was uninstalled any
python installation from my laptop and then installed anaconda continuum.

**Comment by compie** [comment] 2017-12-11 22:59
I had the same issue, see https://github.com/ContinuumIO/anaconda-issues/issues/2533#issuecomment-350885435 for a workaround.

**Comment by johnty05** [comment] 2017-12-29 05:31
Well guys!! I need a bit help here. I have installed Anaconda. Anaconda Prompt is there but no navigator. Even conda is not recognized. I have already changed the path.Please guide me.

**Comment by mingwandroid** [comment] 2017-12-29 17:11
I have fixed the underlying bug here but we will not release new Anaconda installers for a while.

The fix is in the latest Miniconda installers:

64-bit:
https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86_64.exe

32-bit:
https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe
https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe

Install those, then run the `Anaconda Prompt` and install whatever packages you need. If you want the latest full `Anaconda` release then use:

`conda install anaconda=5.0.1`

**Comment by johnty05** [comment] 2017-12-30 06:21
Thanks a lot @mingwandroid . The above mentioned instructions really worked.

**Comment by mingwandroid** [comment] 2017-12-30 10:40
Great. Thanks for the feedback.

**Comment by zzwATdhu** [comment] 2018-01-12 08:43
Thanks  @mingwandroid

**Comment by louisjuliendo** [comment] 2018-01-12 16:18
This is all I need. Thanks for the solution.

**Comment by anajubl** [comment] 2018-01-19 16:29
Thaks a lot mingwandroid. It works

**Closed** 2018-01-25 15:34 UTC

**Comment by princehn** [comment] 2018-01-26 07:17
Thanks a lot.. @mingwandroid

**Comment by hvpandya** [comment] 2018-02-19 02:40
Installed Miniconda and tried upgrading to full Anaconda, getting the same error as others

```
ERROR conda.core.link:_execute(481): An error occurred while installing package 'defaults::ipykernel-4.8.0-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\harsh\Miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\harsh\Miniconda3\Scripts\.ipykernel-post-link.bat
```

**Comment by mingwandroid** [comment] 2018-02-19 07:42
> Installed Miniconda and tried upgrading to full Anaconda

You shouldn't need to do this now, just install Anaconda 5.1

**Comment by maverik-akagami** [comment] 2018-02-21 10:16
seems like this problem persists on Anaconda 5.1 too. activate.bat file is missing

**Comment by maverik-akagami** [comment] 2018-02-21 18:53
@mingwandroid your December answer on installing miniconda and then installing anaconda still works. Anaconda standalone doesn't work as of today

**Comment by mingwandroid** [comment] 2018-02-21 18:57
That's weird because the bug-fix I made for `Miniconda` is now also in `Anaconda`. @nehaljwani any ideas about this? Could that patch have got dropped somehow?

**Comment by Palwin97** [comment] 2018-02-28 04:25
Hey, I'm having the same problem here!

I'm tried downloading both Miniconda and Anaconda and the same problem has been occurring :-/ 

I'm not sure what to do now. Anaconda Prompt is the only thing that has been downloading with a "activate.bat" error.

**Comment by maverik-akagami** [comment] 2018-03-01 04:15
loading miniconda and then using `conda install anaconda=5.1` worked for me. please check.

**Comment by serek2023** [comment] 2018-03-11 04:03
I had the same issue, and the file C:\Users\......\anaconda3\Scripts\activate.bat not exist on my system,
how to install the file and from where ? I had uninstall conda3 and reinstall ,but still not found activate.bat file

**Comment by serek2023** [comment] 2018-03-11 04:04
I had the same issue, and the file C:\Users......\anaconda3\Scripts\activate.bat not exist on my system,
how to install the file and from where ? I had uninstall conda3 and reinstall ,but still not found activate.bat file @kalefranz

**Comment by hamulya** [comment] 2018-03-16 06:41
loading miniconda i mean i dont see miniconda anywhere in start options please help

**Comment by gabboshow** [comment] 2018-04-03 18:54
Hi,

same problem here... after installing anconda3 and runnig the anconda prompt I got the message 'activate.bat' is not recognized as an internal or external command... unistalled, installed miniconda, but didnt work as well... any news about this?

**Comment by mingwandroid** [comment] 2018-04-03 19:03
You probably need to turn off your virus scanner during installation. There's nothing we can do about this.

**Comment by fireattack** [comment] 2018-04-03 19:07
@mingwandroid I tried to install anaconda on two different machines (Win 7 and Win 10 respectively, with no AV software) and both resulted in activate.bat being not there at all. 

I'm using miniconda now, which has no such problem.

Did you test on Windows machine with fresh installation that it works for you?

**Comment by mingwandroid** [comment] 2018-04-03 19:08
Of course. We test each release on fresh machines and non-fresh machines. Exactly which versions did you try?

**Comment by gabboshow** [comment] 2018-04-03 20:59
I am using AD 5.1.0 an an brand new machine running windows 8.1. I can't uninstall the antivirus since it is a company laptop...

**Comment by mingwandroid** [comment] 2018-04-03 21:01
Can you ask your IT people to disable it while you install AD?

**Comment by spno77** [comment] 2018-04-10 09:15
I had the same problem on windows 8 ! I uninstalled all python versions i had on my pc, anaconda and disabled my anti-virus. After re-installing anaconda and restarting my pc , it works fine !

**Comment by TheHippiez** [comment] 2018-04-11 12:32
I have uninstalled Python, re installed anaconda en restarted multiple times. The .bat is still not recognized. Is there a solution in the works?

**Comment by Sandidfares** [comment] 2018-04-19 18:55
thnx a lot @mingwandroid

**Comment by mingwandroid** [comment] 2018-04-19 19:11
> Is there a solution in the works

It is very difficult for us to fix local problems that we cannot diagnose (and clearly we managed to figure workarounds for most of the people having issues here). If you can identify exactly what goes wrong we can think about developing mitigations and if you are willing to confirm they work for you then we can consider making our install process apply them. However disabling 3rd party anti-virus software is probably not something that we can do programmatically (as otherwise viruses would just do that!).

Some ideas you can try from this thread and others to work around the most common Windows installation problems (namely misbehaving and over-zealous Antivirus software and DLL-hell) in order of most likely to yield a positive result are:

1. Ensure that from a fresh cmd.exe prompt (non-Anaconda Prompt) `where zlib.dll` does *not* show `C:\Windows\System32`, do the same checks for `where python2.dll` if you use Python 2. If it does rename them to see if this fixes it. It could break some badly packaged software you use though. Please report this to the developers of this software. Tell them to put their DLLs beside their exes or to statically link to the libraries instead.
2. Disable your antivirus software temporarily or ask you IT dept to do that for you.
3. Install Miniconda then install the Anaconda Metapackage as per: https://github.com/conda/conda/issues/6053#issuecomment-354473217 (though this *should* not be necessary provided you use AD 5.1.0 installers).
4. Clean up your PATH so it doesn't contain a load of potentially problematic entries as per https://github.com/ContinuumIO/anaconda-issues/issues/2533#issuecomment-350885435
5. Repeat all of these steps but from `Safe Mode`.

**Comment by gabboshow** [comment] 2018-04-19 20:19
Hi,

what worked for me was
Downloaded **Anaconda3-5.0.1-Windows-x86_64** (not 5.1.0...at least I didn't try with this after that 5.0.1 worked)
Right clicked on the installation file and selected Run as administrator to install
Selected option to 'Install for:' 'All Users (requires admin privilege)'
Specified Destination folder 'C:\ProgramData\Anaconda3' (maybe location is important, the suggested path of the installation was C:\Users\...\AppData)

**Comment by xinjici** [comment] 2018-05-22 09:08
@kk13579 
Following your method, I successfully installed the miniconda and finally can use the Anaconda Prompt. But the problem is when I use the code:'conda install anaconda=5.0.1' to install the full Anaconda, the Anaconda Prompt came to the error: 
ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::ipykernel-4.8.0-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
How can I fix this? 
I have installed the same version of Anaconda successfully before I reinstalled my Windows two days ago, whitout any changes on my hardware...So the bug is caused by the different version of windows? 
The problem is really troublesome, I spant my whole day but haven't solving it!!

**Comment by eshalev4** [comment] 2018-06-13 16:01
I am having the same issue here. I tried everything here and got to the 
`Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::ipykernel-4.6.1-py27h30cef79_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.6.1-py27h30cef79_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda2\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-4.6.1-py27h30cef79_0
running your command again with `-v` will provide additional information
location of failed script: C:\ProgramData\Miniconda2\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>`

the file `.ipykernel-post-link.bat` is simply not there, even though I have completely installed Miniconda from the link @mingwandroid gave for Miniconda2 64 bit. I have no path issues  as well. there was no issue when I first installed Anaconda3 but than I have uninstalled it because I need python 2.7 version. Any more suggestions?

**Comment by alextorex0** [comment] 2018-09-13 19:57
Make sure  to remove any old python path in environment variables in order for anaconda to install without issues

**Comment by kasiperumal** [comment] 2018-10-02 07:32
> Hi,
> 
> what worked for me was
> Downloaded **Anaconda3-5.0.1-Windows-x86_64** (not 5.1.0...at least I didn't try with 5.1.0 after that 5.0.1 worked)
> Right clicked on the installation file and selected Run as administrator to install
> Selected option to 'Install for:' 'All Users (requires admin privilege)'
> Specified Destination folder 'C:\ProgramData\Anaconda3' (maybe location is important, the suggested path of the installation was C:\Users...\AppData)
> 
> Didn't need to do anything of the above such disable antivirus etc. (I discovered that I didn't even have an antivirus :) )

this one worked..Thanks

**Comment by ArunWSU** [comment] 2018-10-04 00:50
I had previously installed Python 3.7.0, which I accidentally deleted the folde rinstead of uninstalling it using control panel. It left residual files (keys), which I tried to delete in by going to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall. `
But, it was too tedious to delete each key. So, I ended up using IObitUninstaller, which removed all residual files of previous python 3.7 version. Then, I tried reinstalling individually anaconda and miniconda. But, I still faced the activate.bat problem. 
Then, I looked into system environment variable, which still had path to previous installation. On removing the previous path variable, restarting and reinstalling the anaconda normally, fixed the issue for me.

**Comment by arifzain74** [comment] 2018-10-16 07:59
Same issue for me. Tried installing and reinstalling but nothing changed. installed miniconda but now i want to upgrade miniconda to anaconda with "conda install anaconda " command, but got some certificate problem (see image). Anyone know any solution ?
![condacertifi](https://user-images.githubusercontent.com/30549020/47001098-51334d80-d147-11e8-8a8e-c13e36dbd6a5.PNG)

**Comment by HengyangLin** [comment] 2018-12-13 23:47
Hey guys, I have met exact the same problem when I was using anaconda 5.3.1 on windows10.
Well, the solution is to uninstall your anaconda and re-install  it. And when you install anaconda, you can't close the exe command window manually. You should let it run and exit by itself. Only by this way your anaconda would be installed correctly.

**Comment by HengyangLin** [comment] 2018-12-14 20:43
> > ```
> >       Hey guys, I have met exactly the same problem when I was using anaconda 5.3.1 on windows10.
> > ```
> > Well, the solution is to uninstall your anaconda and re-install  it. And when you install anaconda, you can't close the exe command window manually which would show up at the end of installing. You should let it run and exit by itself. Only by this way your anaconda would be installed correctly.
> 
> I'm still having this trouble, I've reinstalled numerous times - you can't let the .exe finish itself - you have to select buttons to close the dialog box so I'm not sure what you mean above.

During installing there would be a long lasting black window to show up. (The black window is similar to cmd window.)
I mean, don't close it. Only click those buttons which you are asked to.

**Comment by geoelisha** [comment] 2018-12-14 20:46
> Hey guys, I have met exactly the same problem when I was using anaconda 5.3.1 on windows10.
> 
> Well, the solution is to uninstall your anaconda and re-install  it. And when you install anaconda, you can't close the exe command window manually which would show up at the end of installing. You should let it run and exit by itself. Only by this way your anaconda would be installed correctly.
> 
> I'm still having this trouble, I've reinstalled numerous times - you can't let the .exe finish itself - you have to select buttons to close the dialog box so I'm not sure what you mean above.
> 
> During installing there would be a long lasting black window to show up. (The black window is similar to cmd window.)
> I mean, don't close it. Only click those buttons which you are asked to.

yeah - that's what I did. Still no dice for me. :-/

**Comment by bsmadhuri1412** [comment] 2019-02-09 19:32
> I have fixed the underlying bug here but we will not release new Anaconda installers for a while.
> 
> The fix is in the latest Miniconda installers:
> 
> 64-bit:
> https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
> https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86_64.exe
> 
> 32-bit:
> https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe
> https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe
> 
> Install those, then run the `Anaconda Prompt` and install whatever packages you need. If you want the latest full `Anaconda` release then use:
> 
> `conda install anaconda=5.0.1`

Hi,
I installed as you mentioned. But I am getting path not find error.
I am attaching the screenshots of anaconda prompt and environmental variables.
![image](https://user-images.githubusercontent.com/45907340/52525413-b6bfc280-2c7f-11e9-85aa-d688e5569f38.png)

![image](https://user-images.githubusercontent.com/45907340/52525420-dbb43580-2c7f-11e9-864a-f5218b3cba86.png)

And in Miniconda I found activate.bat in Scripts.
Please kindly consider my issue.

**Comment by olisteadman** [comment] 2019-02-27 14:29
Still no luck for me either. I've followed the installation instructions through exactly, 3 times over, trying both Anaconda and Miniconda (latest versions in each case, on a fresh Win10 environment), and at no stage has the `anaconda-navigator` command yielded any results (trying in VSCode Terminal, in Command Prompt, and in Anaconda Prompt); nor does anything containing 'anaconda' show up in my programs list or with a search (except 'Anaconda Prompt'). There are directories though, at `C:\Users\<username>\AppData\Local\Continuum\anaconda3` and `C:\Users\<username>\AppData\Local\Continuum\miniconda3`. On opening Anaconda Prompt I see this message:
`'C:\Users\<username>\AppData\Local\Continuum\anaconda3\Scripts\activate.bat' is not recognized as an internal or external command`

**Comment by geoangelotti** [comment] 2019-03-18 00:05
>... meanwhile the `anaconda-navigator` command yielded no results (trying in VSCode Terminal, in Command Prompt, and in Anaconda Prompt):
> 
>     * Terminal says `bash: anaconda-navigator: command not found`
> 
>     * Both the Command Prompt and anaconda Prompt say `'anaconda-navigator' is not recognized as an internal or external command, operable program or batch file.`

When installing anaconda through `conda install anaconda` the anaconda-navigator is not installed. 

You need to manually install anaconda-navigator though `conda install anaconda-navigator`.
