### ISSUE TITLE
IOError: invalid data stream

### ISSUE THREAD

**Issue by srossross** [conda/conda#1189] opened 2015-03-11 19:49 UTC
```
$ conda search --override -c sean/channel --platform linux-64 conda_gc_test
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/sean/anaconda/envs/binstar/bin/conda", line 7, in <module>
    execfile(__file__)
  File "/Users/sean/Documents/workspace/conda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/sean/Documents/workspace/conda/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/Users/sean/Documents/workspace/conda/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/Users/sean/Documents/workspace/conda/conda/cli/main_search.py", line 93, in execute
    execute_search(args, parser)
  File "/Users/sean/Documents/workspace/conda/conda/cli/main_search.py", line 158, in execute_search
    unknown=args.unknown, json=args.json)
  File "/Users/sean/Documents/workspace/conda/conda/cli/common.py", line 447, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/sean/Documents/workspace/conda/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/sean/Documents/workspace/conda/conda/utils.py", line 79, in __call__
    value = self.func(*args, **kw)
  File "/Users/sean/Documents/workspace/conda/conda/fetch.py", line 210, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/sean/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 397, in result
    return self.__get_result()
  File "/Users/sean/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
IOError: invalid data stream
```

**Comment by srossross** [comment] 2015-03-11 19:51
The issue is that `-c sean/channel` does not point to a valid channel. I'm not sure what is going on with conda.

**Comment by srossross** [comment] 2015-03-11 19:58
Because of the flexibility named channels in anaconda-server https://conda.binstar.org/sean/channel/linux-64/repodata.json matches a html page, not a `repodata.json` file.

There are a few things that conda can do to report better error messages. 

 1. Check `Content-Type` header to make sure that the file is json/bz2 

    ```
curl -I https://conda.binstar.org/sean/channel/repodata.json 
HTTP/1.1 200 OK
Content-Length: 11316
Content-Type: text/html; charset=utf-8
Date: Wed, 11 Mar 2015 19:55:38 GMT
Server: nginx/1.4.3
Set-Cookie: session=eyJjc3JmIjp7IiBiIjoiTURVMlpXWTFabVJpWmpVNE9UaGlPV0V5T1RWbE1UZzRaVE13WWpjNE9EWXpaakZpTm1VNE1RPT0ifX0.B-IvOg.ToAGZf5X7sfFvDD7Q1Js-XciVIs; Domain=.binstar.org; HttpOnly; Path=/
Strict-Transport-Security: max-age=31536000
Connection: keep-alive
    ```
 1. Validate the input from `-c` better before the request is made.

**Comment by ilanschnell** [comment] 2015-03-13 01:58
The problem is that this is a user error, but conda make it seems like an internal error.

**Comment by kalefranz** [comment] 2016-10-24 02:58
I think we can close this issue given discussion in #1233.

**Closed by kalefranz** 2016-10-24 02:58 UTC
