### ISSUE TITLE
Setting proxy configuration from command line

### ISSUE THREAD

**Issue by nirvana-msu** [conda/conda#5677] opened 2017-07-11 10:07 UTC
Is it possible to set proxy configuration from command line? `conda config` only seems to support setting primitive (via `--set`) or sequence (via `--add`/`--append`/`--prepend`) parameters, but `proxy_servers` parameter is a map, so attemping to use `--set` or `--add` just throws an error.

As a result it just doesn't seem possible to update the config programmatically. Writing or appending to the `.condarc` file directly is not really an option because it may conflict with existing user's configuration.

I want something like the following to work:

```bash
$ conda config --add proxy_servers.http http://proxy.tld
$ conda config --add proxy_servers.https https://proxy.tld
```

**Comment by goanpeca** [comment] 2017-07-11 16:20
This has been already implemented on https://github.com/conda/conda/pull/5310  (conda 4.4)

Closing as a duplicate of https://github.com/conda/conda/issues/4302

**Closed by goanpeca** 2017-07-11 16:20 UTC

**Comment by kalefranz** [comment] 2018-08-20 18:28
Passwords in plain text configuration files are a completely different issue.

**Comment by samolito** [comment] 2020-03-25 08:12
> Is it possible to set proxy configuration from command line? `conda config` only seems to support setting primitive (via `--set`) or sequence (via `--add`/`--append`/`--prepend`) parameters, but `proxy_servers` parameter is a map, so attemping to use `--set` or `--add` just throws an error.
> 
> As a result it just doesn't seem possible to update the config programmatically. Writing or appending to the `.condarc` file directly is not really an option because it may conflict with existing user's configuration.
> 
> I want something like the following to work:
> 
> ```shell
> $ conda config --add proxy_servers.http http://proxy.tld
> $ conda config --add proxy_servers.https https://proxy.tld
> ```

it works for me.
great
