### ISSUE TITLE
Conda env export 4.6 does not export pip packages

### ISSUE THREAD

**Issue by quartox** [conda/conda#8190] opened 2019-01-30 19:22 UTC
## Current Behavior

From previous versions `conda env export` includes a pip section, this pip section is missing from 4.6.1.

### Steps to Reproduce

```
conda create --name test-pip python=3.7
conda activate test-pip
pip install pytest
conda env export
```

yields

```
name: test-pip
channels:
  - defaults
dependencies:
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1a=h1de35cc_0
  - pip=18.1=py37_0
  - python=3.7.2=haf84260_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.6.3=py37_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/quartox/local/anaconda3/envs/test-pip
```

## Expected Behavior

```
name: test-pip
channels:
  - defaults
dependencies:
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1a=h1de35cc_0
  - pip=18.1=py37_0
  - python=3.7.2=haf84260_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.6.3=py37_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - more-itertools==5.0.0
    - pluggy==0.8.1
    - py==1.7.0
    - pytest==4.1.1
    - six==1.12.0
prefix: /Users/quartox/local/anaconda3/envs/test-pip
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : test-pip
    active env location : /Users/quartox/local/anaconda3/envs/test-pip
            shell level : 4
       user config file : /Users/quartox/.condarc
 populated config files : /Users/quartox/.condarc
          conda version : 4.6.1
    conda-build version : 3.17.7
         python version : 3.7.2.final.0
       base environment : /Users/quartox/local/anaconda3  (writable)
           channel URLs : <internal corporate mirrors of defaults>
          package cache : /Users/quartox/local/anaconda3/pkgs
                          /Users/quartox/.conda/pkgs
       envs directories : /Users/quartox/local/anaconda3/envs
                          /Users/quartox/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.1 requests/2.21.0 CPython/3.7.2 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 807788005:81860857
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/jlord/.condarc <==
ssl_verify: False
channels:
  - <internal corporate mirrors of defaults>
sat_solver: pycryptosat
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/jlord/local/anaconda3/envs/test-pip:
#
# Name                    Version                   Build  Channel
atomicwrites              1.2.1                    pypi_0    pypi
attrs                     18.2.0                   pypi_0    pypi
ca-certificates           2018.12.5                     0    defaults
certifi                   2018.11.29               py37_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
more-itertools            5.0.0                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.1.1a               h1de35cc_0    defaults
pip                       18.1                     py37_0    defaults
pluggy                    0.8.1                    pypi_0    pypi
py                        1.7.0                    pypi_0    pypi
pytest                    4.1.1                    pypi_0    pypi
python                    3.7.2                haf84260_0    defaults
readline                  7.0                  h1de35cc_5    defaults
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                   pypi_0    pypi
sqlite                    3.26.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
wheel                     0.32.3                   py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```
</p></details>

**Comment by msarahan** [comment] 2019-01-30 19:24
duplicate of https://github.com/conda/conda/issues/8136; fixed in 4.6.2 (on conda-canary channel right now)

**Closed by msarahan** 2019-01-30 19:24 UTC
