### ISSUE TITLE
Creating a new environment fails with conda 4.3.11

### ISSUE THREAD

**Issue by davidfokkema** [conda/conda#4593] opened 2017-02-10 14:11 UTC
Building my VM suddenly fails. I think I tracked it down to the new version of conda. Using conda 4.3.9 everything works, but no longer. I issued as a regular user:
```
$ yes | /opt/miniconda/bin/conda create -p /srv/publicdb/publicdb_env python --yes
```
which now fails with a permission error. It tries to write to the root-owned package cache, although it says in the dump below that there is a package cache in the users home directory.

```
Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/miniconda  (read only)
    default environment : /opt/miniconda
       envs directories : /opt/miniconda/envs
                          /home/hisparc/.conda/envs
          package cache : /opt/miniconda/pkgs
                          /home/hisparc/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/2.6.
32-642.13.1.el6.x86_64 CentOS/6.8 glibc/2.12
                UID:GID : 500:500



`$ /opt/miniconda/bin/conda create -p /srv/publicdb/publicdb_env python --yes`




    Traceback (most recent call last):
      File "/opt/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/opt/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'/opt/miniconda/pkgs/cache/db552c1e.json'
```

**Comment by swails** [comment] 2017-02-12 02:57
Also looks like a dupe of #4584

**Comment by davidfokkema** [comment] 2017-02-12 11:57
@swails I tried, but #4584 uses conda 4.3.8, and that works without problems for me. In my VM, conda 3.7.3 is installed, and that works. If I upgrade to 4.3.8, that works too. If I upgrade to 4.3.9, that works as well. However, upgrading to 4.3.11 and then creating an environment fails.

**Comment by kalefranz** [comment] 2017-02-14 05:21
@davidfokkema thanks for the report and sorry for the trouble.  What do you get for

    ls -al /opt/miniconda/pkgs/cache

and for

    id

?

**Comment by kalefranz** [comment] 2017-02-14 05:47
@davidfokkema never mind the above.  I tracked down the issue and don't need any additional information.

I'll have a fix out asap.  See #4621 for more details.

**Comment by davidfokkema** [comment] 2017-02-14 06:25
@kalefranz wonderful, thanks!

**Comment by kalefranz** [comment] 2017-02-15 04:36
Conda 4.3.12 that includes a patch for this issue has been released to conda canary.  Feel free to test.

    conda config --add channels conda-canary
    conda update conda

**Closed by kalefranz** 2017-02-15 04:36 UTC
Labels: bug, high priority
