### ISSUE TITLE
conda env update failing with `ImportError: cannot import name 'install' from 'conda.cli'`

### ISSUE THREAD

**Issue by romulorosa** [conda/conda#13560] opened 2024-02-02 16:40 UTC
### What happened?

An exception is thrown while running `conda env update -n base -q -f environment.yml` within my docker container. The exception sown is the following one:
```
#0 329.9 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
#0 329.9 
#0 329.9     Traceback (most recent call last):
#0 329.9       File "/conda/lib/python3.8/site-packages/conda/exception_handler.py", line 17, in __call__
#0 329.9       File "/conda/lib/python3.8/site-packages/conda/cli/main.py", line 83, in main_subshell
#0 329.9       File "/conda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
#0 329.9       File "/conda/lib/python3.8/site-packages/conda/notices/core.py", line 124, in wrapper
#0 329.9       File "/conda/lib/python3.8/site-packages/conda/cli/main_env_update.py", line 161, in execute
#0 329.9       File "/conda/lib/python3.8/site-packages/conda/env/env.py", line 279, in print_result
#0 329.9     ImportError: cannot import name 'install' from 'conda.cli' (/conda/lib/python3.8/site-packages/conda/cli/__init__.py)
#0 329.9 
#0 329.9 `$ /usr/local/bin/conda env update -n base -q -f environment.yml --solver=classic`
#0 329.9 
#0 329.9   environment variables:
#0 329.9                  CIO_TEST=<not set>
#0 329.9                CONDA_ROOT=/conda
#0 329.9             CONDA_VERSION=4.12.0
#0 329.9            CURL_CA_BUNDLE=<not set>
#0 329.9                LD_PRELOAD=<not set>
#0 329.9                      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bi
#0 329.9                           n
#0 329.9        REQUESTS_CA_BUNDLE=<not set>
#0 329.9             SSL_CERT_FILE=<not set>
#0 329.9 
#0 329.9      active environment : None
#0 329.9        user config file : /root/.condarc
#0 329.9  populated config files : 
#0 329.9           conda version : 24.1.0
#0 329.9     conda-build version : not installed
#0 329.9          python version : 3.8.18.final.0
#0 329.9                  solver : libmamba (default)
#0 329.9        virtual packages : __archspec=1=x86_64
#0 329.9                           __conda=24.1.0=0
#0 329.9                           __glibc=2.36=0
#0 329.9                           __linux=5.15.49=0
#0 329.9                           __unix=0=0
#0 329.9        base environment : /conda  (writable)
#0 329.9       conda av data dir : /conda/etc/conda
#0 329.9   conda av metadata url : None
#0 329.9            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
#0 329.9                           https://repo.anaconda.com/pkgs/main/noarch
#0 329.9                           https://repo.anaconda.com/pkgs/r/linux-64
#0 329.9                           https://repo.anaconda.com/pkgs/r/noarch
#0 329.9           package cache : /conda/pkgs
#0 329.9                           /root/.conda/pkgs
#0 329.9        envs directories : /conda/envs
#0 329.9                           /root/.conda/envs
#0 329.9                platform : linux-64
#0 329.9              user-agent : conda/24.1.0 requests/2.31.0 CPython/3.8.18 Linux/5.15.49-linuxkit debian/12.4 glibc/2.36 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
#0 329.9                 UID:GID : 0:0
#0 329.9              netrc file : None
#0 329.9            offline mode : False
#0 329.9 
#0 329.9 
#0 329.9 An unexpected error has occurred. Conda has prepared the above report.
#0 329.9 If you suspect this error is being caused by a malfunctioning plugin,
#0 329.9 consider using the --no-plugins option to turn off plugins.
#0 329.9 
#0 329.9 Example: conda --no-plugins install <package>
#0 329.9 
#0 329.9 Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
#0 329.9 the command line to run the command without plugins enabled.
#0 329.9 
#0 329.9 Example: CONDA_NO_PLUGINS=true conda install <package>
#0 329.9 

```

### Conda Info

```shell
    active environment : None
      user config file : /root/.condarc
populated config files :
         conda version : 24.1.0
   conda-build version : not installed
        python version : 3.8.18.final.0
                solver : libmamba (default)
      virtual packages : __archspec=1=x86_64 __conda=24.1.0=0 __glibc=2.36=0 __linux=5.15.49=0 __unix=0=0
      base environment : /conda (writable)
     conda av data dir : /conda/etc/conda
 conda av metadata url : None
          channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                         https://repo.anaconda.com/pkgs/main/noarch
                         https://repo.anaconda.com/pkgs/r/linux-64
                         https://repo.anaconda.com/pkgs/r/noarch
         package cache : /conda/pkgs
                         /root/.conda/pkgs
      envs directories : /conda/envs
                         /root/.conda/envs
              platform : linux-64
            user-agent : conda/24.1.0 requests/2.31.0 CPython/3.8.18 Linux/5.15.49-linuxkit debian/12.4 glibc/2.36 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
               UID:GID : 0:0
            netrc file : None
          offline mode : False
```

### Conda Config

```shell
root@5b2de479d2c3:/# conda config --show-sources
+ conda config --show-sources
```

### Conda list

```shell
packages in environment at /conda: # # Name Version Build Channel _libgcc_mutex 0.1 conda_forge conda-forge _openmp_mutex 4.5 2_gnu conda-forge appdirs 1.4.4 pyhd3eb1b0_0 defaults archspec 0.2.1 pyhd3eb1b0_0 defaults boltons 23.0.0 py38h06a4308_0 defaults brotli-python 1.0.9 py38h6a678d5_7 defaults bzip2 1.0.8 h7b6447c_0 defaults c-ares 1.19.1 h5eee18b_0 defaults ca-certificates 2023.12.12 h06a4308_0 defaults cachecontrol 0.12.11 py38h06a4308_1 defaults cachecontrol-with-filecache 0.12.11 py38h06a4308_1 defaults cachy 0.3.0 pyhd3eb1b0_0 defaults certifi 2023.11.17 py38h06a4308_0 defaults cffi 1.16.0 py38h5eee18b_0 defaults charset-normalizer 2.0.4 pyhd3eb1b0_0 defaults click 8.1.7 py38h06a4308_0 defaults click-default-group 1.2.2 py38h06a4308_0 defaults clikit 0.6.2 py_0 defaults conda 24.1.0 py38h06a4308_0 defaults conda-content-trust 0.2.0 py38h06a4308_0 defaults conda-libmamba-solver 24.1.0 pyhd3eb1b0_0 defaults conda-lock 2.5.2 pyhd8ed1ab_0 conda-forge conda-package-handling 2.2.0 py38h06a4308_0 defaults conda-package-streaming 0.9.0 py38h06a4308_0 defaults conda-token 0.4.0 pyhd3eb1b0_0 defaults crashtest 0.3.1 pyhd3eb1b0_1 defaults cryptography 41.0.7 py38hdda0065_0 defaults dbus 1.13.18 hb2f20db_0 defaults distlib 0.3.8 pyhd8ed1ab_0 conda-forge distro 1.8.0 py38h06a4308_0 defaults ensureconda 1.4.3 py38h06a4308_0 defaults expat 2.5.0 h6a678d5_0 defaults filelock 3.13.1 py38h06a4308_0 defaults fmt 9.1.0 hdb19cb5_0 defaults gitdb 4.0.7 pyhd3eb1b0_0 defaults gitpython 3.1.37 py38h06a4308_0 defaults glib 2.69.1 he621ea3_2 defaults html5lib 1.1 pyhd3eb1b0_0 defaults icu 73.1 h6a678d5_0 defaults idna 3.4 py38h06a4308_0 defaults importlib-metadata 7.0.1 py38h06a4308_0 defaults importlib_metadata 7.0.1 hd3eb1b0_0 defaults importlib_resources 6.1.1 py38h06a4308_1 defaults jaraco.classes 3.2.1 pyhd3eb1b0_0 defaults jeepney 0.7.1 pyhd3eb1b0_0 defaults jinja2 3.1.3 py38h06a4308_0 defaults jsonpatch 1.32 pyhd3eb1b0_0 defaults jsonpointer 2.1 pyhd3eb1b0_0 defaults keyring 23.13.1 py38h06a4308_0 defaults krb5 1.20.1 h143b758_1 defaults ld_impl_linux-64 2.38 h1181459_1 defaults libarchive 3.6.2 h6ac8c49_2 defaults libcurl 8.5.0 h251f7ec_0 defaults libedit 3.1.20230828 h5eee18b_0 defaults libev 4.33 h7f8727e_1 defaults libffi 3.4.4 h6a678d5_0 defaults libgcc-ng 13.2.0 h807b86a_5 conda-forge libgomp 13.2.0 h807b86a_5 conda-forge libmamba 1.5.6 haf1ee3a_0 defaults libmambapy 1.5.6 py38h2dafd23_0 defaults libnghttp2 1.57.0 h2d74bed_0 defaults libsolv 0.7.24 he621ea3_0 defaults libssh2 1.10.0 hdbd6064_2 defaults libstdcxx-ng 11.2.0 h1234567_1 defaults libxml2 2.10.4 hf1b16e4_1 defaults lockfile 0.12.2 py38h06a4308_0 defaults lz4-c 1.9.4 h6a678d5_0 defaults markupsafe 2.1.3 py38h5eee18b_0 defaults menuinst 2.0.2 py38h06a4308_0 defaults more-itertools 10.1.0 py38h06a4308_0 defaults msgpack-python 1.0.3 py38hd09550d_0 defaults ncurses 6.4 h6a678d5_0 defaults openssl 3.0.12 h7f8727e_0 defaults packaging 23.1 py38h06a4308_0 defaults pastel 0.2.1 py_0 defaults pcre 8.45 h295c915_0 defaults pcre2 10.42 hebb0a14_0 defaults pip 23.3.1 py38h06a4308_0 defaults pkginfo 1.9.6 py38h06a4308_0 defaults platformdirs 3.10.0 py38h06a4308_0 defaults pluggy 1.0.0 py38h06a4308_1 defaults pybind11-abi 4 hd3eb1b0_1 defaults pycosat 0.6.6 py38h5eee18b_0 defaults pycparser 2.21 pyhd3eb1b0_0 defaults pydantic 1.10.12 py38h5eee18b_1 defaults pylev 1.3.0 py_0 defaults pyopenssl 23.2.0 py38h06a4308_0 defaults pysocks 1.7.1 py38h06a4308_0 defaults python 3.8.18 h955ad1f_0 defaults python_abi 3.8 2_cp38 conda-forge pyyaml 6.0.1 py38h5eee18b_0 defaults readline 8.2 h5eee18b_0 defaults reproc 14.2.4 h295c915_1 defaults reproc-cpp 14.2.4 h295c915_1 defaults requests 2.31.0 py38h06a4308_0 defaults ruamel.yaml 0.17.21 py38h5eee18b_0 defaults ruamel.yaml.clib 0.2.7 py38h01eb140_2 conda-forge secretstorage 3.3.1 py38h06a4308_1 defaults setuptools 68.2.2 py38h06a4308_0 defaults six 1.16.0 pyhd3eb1b0_1 defaults smmap 4.0.0 pyhd3eb1b0_0 defaults sqlite 3.41.2 h5eee18b_0 defaults tk 8.6.12 h1ccaba5_0 defaults tomli 2.0.1 py38h06a4308_0 defaults tomlkit 0.11.1 py38h06a4308_0 defaults toolz 0.12.0 py38h06a4308_0 defaults tqdm 4.65.0 py38hb070fc8_0 defaults typing-extensions 4.9.0 py38h06a4308_1 defaults typing_extensions 4.9.0 py38h06a4308_1 defaults urllib3 1.26.18 py38h06a4308_0 defaults virtualenv 20.25.0 pyhd8ed1ab_0 conda-forge webencodings 0.5.1 py38_1 defaults wheel 0.41.2 py38h06a4308_0 defaults xz 5.4.5 h5eee18b_0 defaults yaml 0.2.5 h7b6447c_0 defaults yaml-cpp 0.8.0 h6a678d5_0 defaults zipp 3.17.0 py38h06a4308_0 defaults zlib 1.2.13 h5eee18b_0 defaults zstandard 0.19.0 py38h5eee18b_0 defaults zstd 1.5.5 hc292b87_0 defaults
```

### Additional Context

The relevant content of my Dockerfile is:
```
RUN set -ex \
    && apt-get -qq update \
    && apt-get -qq -y install curl bzip2 \
    && curl -sSL --fail https://repo.anaconda.com/miniconda/Miniconda3-py38_${CONDA_VERSION}-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /miniconda \
    && /miniconda/bin/conda create -yq -p /conda python=3.8 conda conda-forge::conda-lock conda-token \
    && ln -sf /conda/bin/conda /usr/local/bin/conda \
    && rm -rf /tmp/miniconda.sh /miniconda
  ```

**Comment by Javier-Jimenez99** [comment] 2024-03-08 09:31
Same error, some update on this?

**Comment by mescarra** [comment] 2024-03-08 13:58
Same error, what's going on?

**Comment by napulen** [comment] 2024-03-09 02:25
Same here. No changes to the `environment.yml` I am using in Github actions.

**Comment by EthanJamesLew** [comment] 2024-03-09 20:37
Same here

**Comment by EthanJamesLew** [comment] 2024-03-11 05:59
Update: for me, this was solved just by updating my environment.yml (environment description) to something that can be resolved by python 3.12 on ubuntu 22.04. I did not need to change the github actions workflow.

**Comment by napulen** [comment] 2024-03-12 23:09
Update on my end. Some of my dependencies are not compatible with `python=3.12`. Although the right python setup is defined in my `environment.yaml` (including `python=3.11`), for some reason, it doesn't just work when I try to update the environment with the default routine in github actions

```yaml
    - name: Install dependencies
      run: |
        conda env update --file environment.yaml --name base
```

However, it works if I first force a downgrade to `python=3.11`, and then do the update, like this:

```yaml
    - name: Install dependencies
      run: |
        conda install -y python=3.11
        conda env update --file environment.yaml --name base
```

I imagine the change that happened on gh-actions was that the interpreter version changed and that's what is breaking some of us?

**Comment by astromark** [comment] 2024-03-13 12:03
I've been having this problem too and I noticed that the action was using conda from `/usr/share/miniconda/lib/python3.12` even though the python version had been set to 3.10 elsewhere in the action. Thanks a lot for your solution @napulen. That helped, although in my case I also needed to add `echo $CONDA/bin >> $GITHUB_PATH` after the `conda install` line in order to ensure other parts of the action worked as intended.

**Comment by adrian-valente** [comment] 2024-03-21 11:30
@napulen thanks for this solution, indeed it solves the issue with gh-actions! It appears that python 3.12.1 was installed by default despite the python-version variable being set to 3.11 in the rule actions/setup-python@v3. Any insights on why this happens and who should be aware of the issue, maybe the maintainers of github actions?

**Comment by jjhelmus** [comment] 2024-03-26 20:10
A small reproducer of this issue uses this Dockerfile:

``` Dockerfile
FROM --platform=linux/amd64 continuumio/miniconda3:24.1.2-0
RUN echo "dependencies:\n- python=3.9" > env.yml
RUN conda env update -n base -f env.yml
```

Attempting to build this produces the error from the OP:
```
❯ docker build .
...
#6 7.747 Executing transaction: ...working... done
#6 11.81
#6 11.81 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
#6 11.81
#6 11.81     Traceback (most recent call last):
#6 11.81       File "/opt/conda/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
#6 11.81       File "/opt/conda/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
#6 11.81       File "/opt/conda/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
#6 11.81       File "/opt/conda/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
#6 11.81       File "/opt/conda/lib/python3.11/site-packages/conda/cli/main_env_update.py", line 161, in execute
#6 11.81       File "/opt/conda/lib/python3.11/site-packages/conda/env/env.py", line 279, in print_result
#6 11.81     ImportError: cannot import name 'install' from 'conda.cli' (/opt/conda/lib/python3.11/site-packages/conda/cli/__init__.py)
#6 11.81
#6 11.81 `$ /opt/conda/bin/conda env update -n base -f env.yml`
...
```

Switching the base image to the previous miniconda3 tag on Dockehub `FROM --platform=linux/amd64 continuumio/miniconda3:23.10.0-1` results in a working build. 

Note that this is not just a different in the Python version between these two tags as both use Python 3.11 (3.11.7 vs 3.11.5).

**Comment by jjhelmus** [comment] 2024-03-26 21:05
I was able to bisect this to 33a75a98f04cf9b09b4fa32d28855c9b2bbaecbd which was added in #13168. Prior to this commit the Python version in the base environment could be changed using `conda env update ...`.

**Comment by jezdez** [comment] 2024-03-26 21:38
> I was able to bisect this to [33a75a9](https://github.com/conda/conda/commit/33a75a98f04cf9b09b4fa32d28855c9b2bbaecbd) which was added in #13168. Prior to this commit the Python version in the base environment could be changed using `conda env update ...`.

Nice sleuthing, what an unfortunate side effect! We plan to do a 24.3.1 release with #13685 anyways next week, might as well fix this.

**Closed** 2024-04-16 13:05 UTC
Labels: type::bug, source::anaconda

**Comment by zndr27** [comment] 2024-05-06 03:32
Not working for me
