### ISSUE TITLE
conda update --file complains about missing package name of --file

### ISSUE THREAD

**Issue by ssbarnea** [conda/conda#3207] opened 2016-08-02 12:47 UTC
When run from inside an activated conda virtual environment this line gives an unexpected error:
```
conda update --prefix /tmp/myconda --file compiled.txt
Error: too few arguments, must supply command line package specs or --file
```
This environment was successfully created using
```
conda create --prefix /tmp/myconda --file compiled.txt
```

During the build process,  I do expect to be able to installed eventually modified requirement files but my impression is that `update` does not follow the `install` behaviour.

The workaround is to always remove the entire environment in order to recreate it from scratch each time, something that slows down the builds considerably.

Note: If I add a package name as a parameter, conda will try to update only this and fully ignore the --file parameter.

**Comment by HugoTian** [comment] 2016-08-02 14:19
Can you show the output of "conda info", I tried on OS X, and I cannot reproduce the error

Thanks

**Comment by ssbarnea** [comment] 2016-08-02 15:15
```
Current conda install:

             platform : osx-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /Users/sorins/anaconda3  (writable)
  default environment : /Users/sorins/anaconda3
     envs directories : /Users/sorins/anaconda3/envs
        package cache : /Users/sorins/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by HugoTian** [comment] 2016-08-02 15:25
I just try the command on my machine, and I cannot reproduce the error. Both install and update works fine.

Would you mind show me the content of compiled.txt ? Maybe it will help.

Thanks

**Comment by ssbarnea** [comment] 2016-08-02 15:45
```
# put here any python requirements that are precompiled as conda packages in order to speed-up the build and deployment
lxml
numpy>=1.11
pandas
psycopg2
pytables
scipy
```

**Comment by HugoTian** [comment] 2016-08-02 15:59
Actually, I did not run into the "Error: too few arguments, must supply command line package specs or --file" error, and it seems your command line is correct.

However, I run into a bug that the env is not actually updated according to the txt file, and I will try to find a solution

**Comment by ssbarnea** [comment] 2016-08-02 16:19
Thank you @HugoTian! I am trying to migrate our build environment to conda and this would clearly be an important step. Let me know if there is anything I can do to help with this.

I hope that I will not encounter the same issue while trying to deploy on linux (this happened on my own machine)

**Comment by HugoTian** [comment] 2016-08-02 16:25
@ssbarnea , Sure, and I will try to fix this , and provide a stable version in conda4.2

**Comment by HugoTian** [comment] 2016-08-02 17:18
@ssbarnea. The bug I found is clear, and I already create a PR #3209 for this. That will fix the behavior when you try to update from  a file.

However, for the command line issue you have, I really have no idea, since I cannot reproduce the error. I copy and paste your command, and everything works fine. It is wired, and please keep me updated if you figure out why, or it works on Linux.

I am about to close this issue, and let's move the discussion under that PR.

Feel free to reopen this issue and @ me

Thanks

**Comment by HugoTian** [comment] 2016-08-03 17:52
@ssbarnea , Sorry about the previous message, and I think --file is not an option for "conda update"

Please try conda install --file, and I think that will work as expected.

We already revert that PR, and we will have better -h message soon

**Comment by kalefranz** [comment] 2016-08-03 20:09
As @HugoTian said, updating from a file is incorrect, and the real bug here is that `conda update --help` showed `--file` as an option.

Correct usage for `--file` is with `conda create` or `conda install`.

**Closed** 2016-08-05 14:13 UTC
