### ISSUE TITLE
circular dependencies for awscli?

### ISSUE THREAD

**Issue by jseabold** [conda/conda#1503] opened 2015-08-06 22:48 UTC
There appears to be some kind of circular dependency in installing awscli using Miniconda on 64-bit linux with Python 3.4.

```
$ conda --version
conda 3.15.1
```

Then

```
conda skeleton pypi awscli
conda build awscli
```

Just keeps trying to install the rsa dependency AFAICT.

**Comment by jseabold** [comment] 2015-08-06 22:59
A little more information. I did this first.

```
conda skeleton pypi rsa
conda build rsa

conda skeleton pypi botocore
conda build botocore
```

**Comment by asmeurer** [comment] 2015-08-11 16:26
This probably means the awscli recipe has a version restriction on rsa that doesn't match the rsa recipe.

**Comment by jseabold** [comment] 2015-08-11 16:32
That looks like it.

**Comment by asmeurer** [comment] 2015-08-11 16:37
Dupe of https://github.com/conda/conda-build/issues/393

**Closed by asmeurer** 2015-08-11 16:37 UTC
