### ISSUE TITLE
Tried to update ipython notebook and this error appeared

### ISSUE THREAD

**Issue by franink** [conda/conda#3898] opened 2016-11-16 21:32 UTC
An unexpected error has occurred, please consider sending the             |  66%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/frankanayet/anaconda/bin/conda", line 5, in <module>
    
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    p = sub_parsers.add_parser(
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    add_unlink(actions, dist)
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    PREFIX: PREFIX_CMD,
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    symlink_conda(state['prefix'], arg)
  File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/install.py", line 616, in link
    dist = dist[:-8]
  File "/Users/frankanayet/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/frankanayet/anaconda/lib/python2.7/site-packages/pip/_vendor/html5lib/_trie'

then tried to do conda update conda and the got the following message:
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.18.1
         python version : 2.7.12.final.0
       requests version : 2.12.0
       root environment : /Users/frankanayet/anaconda  (writable)
    default environment : /Users/frankanayet/anaconda
       envs directories : /Users/frankanayet/anaconda/envs
          package cache : /Users/frankanayet/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/frankanayet/anaconda/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 403, in result
        return self.__get_result()
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by kalefranz** [comment] 2016-11-22 23:05
Duplicate of #3918, #3929, #3934, and #3935.  Honestly not sure where this came from all the sudden.  We definitely need to limit dependencies somewhere.

In general `pyopenssl` and `cryptography` are out of sync.

    CONDA_VERIFY_SSL=false conda update pyopenssl

should fix your problem

**Closed by kalefranz** 2016-11-22 23:05 UTC

**Comment by franink** [comment] 2016-11-28 21:11
Thanks for the reply!

I still get error after running the command you suggested:

CONDA_VERIFY_SSL=false conda update pyopenssl
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.18.1
         python version : 2.7.12.final.0
       requests version : 2.12.0
       root environment : /Users/frankanayet/anaconda  (writable)
    default environment : /Users/frankanayet/anaconda
       envs directories : /Users/frankanayet/anaconda/envs
          package cache : /Users/frankanayet/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /Users/frankanayet/anaconda/bin/conda update pyopenssl`




    Traceback (most recent call last):
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 403, in result
        return self.__get_result()
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/frankanayet/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

Thanks

**Comment by kalefranz** [comment] 2016-11-30 01:31
I had previously given something that was incorrect.  Please try

    CONDA_SSL_VERIFY=false conda update pyopenssl

**Comment by PAGWatson** [comment] 2016-11-30 16:56
I would like to report that the command "CONDA_SSL_VERIFY=false conda update pyopenssl" does not fix the problem for me. I ran that command, then tried installing the pymc module with "conda install pymc", and got similar output to the above error:

Fetching package metadata .../network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.binstar.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.anaconda.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
..An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.2
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /network/home/aopp/watson/anaconda2  (writable)
    default environment : /network/home/aopp/watson/anaconda2/envs/main
       envs directories : /network/home/aopp/watson/anaconda2/envs
          package cache : /network/home/aopp/watson/anaconda2/pkgs
           channel URLs : https://conda.binstar.org/rsignell/linux-64
                          https://conda.binstar.org/rsignell/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /network/home/aopp/watson/.condarc
           offline mode : False



`$ /network/home/aopp/watson/anaconda2/envs/main/bin/conda install pymc`




    Traceback (most recent call last):
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
        for url in urls]
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/network/home/aopp/watson/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by franink** [comment] 2016-11-30 23:10
Hi kalefranz thanks for the help. Although I do think that it fixed the underlying issue I still have some troubles as part of the original error pip got uninstalled and it seems that it can't reinstall it so the update froze:

Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/frankanayet/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.9.1                 |           py27_0         193 KB
    conda-4.2.13               |           py27_0         375 KB
    cryptography-1.6           |           py27_0         461 KB
    pyopenssl-16.2.0           |           py27_0          68 KB
    ------------------------------------------------------------
                                           Total:         1.1 MB

The following NEW packages will be INSTALLED:

    pip:          9.0.1-py27_0 

The following packages will be UPDATED:

    cffi:         1.2.1-py27_0  --> 1.9.1-py27_0 
    conda:        4.2.12-py27_0 --> 4.2.13-py27_0
    cryptography: 1.0.2-py27_0  --> 1.6-py27_0   
    pyopenssl:    0.15.1-py27_1 --> 16.2.0-py27_0

Proceed ([y]/n)? y

Fetching packages ...
cffi-1.9.1-py2 100% |#################################| Time: 0:00:00  16.76 MB/s
conda-4.2.13-p 100% |#################################| Time: 0:00:00  19.79 MB/s
cryptography-1 100% |#################################| Time: 0:00:00  12.27 MB/s
pyopenssl-16.2 100% |#################################| Time: 0:00:00  11.88 MB/s
Extracting packages ...
[      COMPLETE      ]|####################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|####################################################| 100%
Linking packages ...


CondaOSError: OS error: failed to link (src=u'/Users/frankanayet/anaconda/pkgs/pip-9.0.1-py27_0/lib/python2.7/site-packages/pip/__init__.py', dst='/Users/frankanayet/anaconda/lib/python2.7/site-packages/pip/__init__.py', type=1, error=OSError(17, 'File exists'))


sr14-107f98ff53:~ frankanayet$ ############                                              |       40%

**Comment by franink** [comment] 2016-12-02 08:45
I fixed it by removing /Users/frankanayet/anaconda/lib/python2.7/site-packages/pip/init.py' from my computer and then reinstalling pip. After that everything worked

**Comment by ags-wsu** [comment] 2016-12-15 14:59
Using pip, I upgraded the following which has fixed the same problem for me:

`Successfully installed cffi-1.9.1 cryptography-1.7.1 idna-2.1 ipaddress-1.0.17 pycparser-2.17 setuptools-32.0.0`

**Comment by modqhx** [comment] 2017-01-04 02:10
@kalefranz Hey, i followed your command on my terminal `CONDA_SSL_VERIFY=false conda update pyopenssl`. It installed fine. After that suddenly, it seems I broke ipython I am not able to launch ipython in the terminal? Any idea why? I get error:
```
command not found: ipython
```
And if I do `conda install ipython`, I get:
```
CondaOSError: OS error: failed to link (src=u'//anaconda/pkgs/wcwidth-0.1.7-py27_0/lib/python2.7/site-packages/wcwidth/__init__.py', dst='//anaconda/lib/python2.7/site-packages/wcwidth/__init__.py', type=1, error=OSError(17, 'File exists'))
```
