### ISSUE TITLE
update anaconda explodes ... 

### ISSUE THREAD

**Issue by terminsen** [conda/conda#6971] opened 2018-03-01 21:26 UTC
Hi - 

I am trying to update anaconda, running the command conda update --all on my Win 7. 
The system explodes and returns with the error below. 

Anybody who knows Anacondan ? 

Thank you very much.

Regards, Jesper. 

The following packages will be UPDATED:

    anaconda-client:           1.6.5-py36hd36550c_0       --> 1.6.11-py36_0

    anaconda-project:          0.8.0-py36h8b3bf89_0       --> 0.8.2-py36hfad2e28
_0
    asn1crypto:                0.22.0-py36h8e79faa_1      --> 0.24.0-py36_0

    astroid:                   1.5.3-py36h9d85297_0       --> 1.6.1-py36_0

    astropy:                   2.0.2-py36h06391c4_4       --> 3.0-py36h452e1ab_1

    babel:                     2.5.0-py36h35444c1_0       --> 2.5.3-py36_0

    bitarray:                  0.8.1-py36h6af124b_0       --> 0.8.1-py36hfa6e2cd
_1
    bleach:                    2.0.0-py36h0a7e3d6_0       --> 2.1.2-py36_0

    bokeh:                     0.12.10-py36h0be3b39_0     --> 0.12.14-py36_0

    bzip2:                     1.0.6-vc14hdec8e7a_1       --> 1.0.6-hbe05fcf_4

    cachecontrol:              0.12.3-py36hfe50d7b_0      --> 0.12.4-py36_0

    cffi:                      1.10.0-py36hae3d1b5_1      --> 1.11.4-py36hfa6e2c
d_0
    cloudpickle:               0.4.0-py36h639d8dc_0       --> 0.5.2-py36_1

    comtypes:                  1.1.2-py36heb9b3d1_0       --> 1.1.4-py36_0

    cryptography:              2.0.3-py36h123decb_1       --> 2.1.4-py36he1d7878
_0
    curl:                      7.55.1-vc14hdaba4a4_3      --> 7.58.0-h7602738_0

    cython:                    0.26.1-py36h18049ac_0      --> 0.27.3-py36h22f4c8
4_0
    cytoolz:                   0.8.2-py36h547e66e_0       --> 0.9.0-py36hfa6e2cd
_0
    dask:                      0.15.3-py36h396fcb9_0      --> 0.17.1-py36_0

    dask-core:                 0.15.3-py36hd651449_0      --> 0.17.1-py36_0

    decorator:                 4.1.2-py36he63a57b_0       --> 4.2.1-py36_0

    distlib:                   0.2.5-py36h51371be_0       --> 0.2.6-py36_0

    distributed:               1.19.1-py36h8504682_0      --> 1.21.1-py36_0

    fastcache:                 1.0.2-py36hffdae1b_0       --> 1.0.2-py36hfa6e2cd
_2
    filelock:                  2.0.12-py36hd7ddd41_0      --> 3.0.4-py36_0

    font-ttf-dejavu-sans-mono: 2.37-0                     --> 2.37-h6964260_0

    font-ttf-inconsolata:      2.000-0                    --> 2.001-hcb22688_0

    font-ttf-source-code-pro:  2.030-0                    --> 2.030-h7457263_0

    font-ttf-ubuntu:           0.83-0                     --> 0.83-h8b1ccd4_0

    freetype:                  2.8-vc14h17c9bdf_0         --> 2.8-h51f8f2c_1

    glob2:                     0.5-py36h11cc1bd_1         --> 0.6-py36hdf76b57_0

    greenlet:                  0.4.12-py36ha00ad21_0      --> 0.4.13-py36hfa6e2c
d_0
    h5py:                      2.7.0-py36hfbe0a52_1       --> 2.7.1-py36he54a1c3
_0
    hdf5:                      1.10.1-vc14hb361328_0      --> 1.10.1-h98b8871_1

    heapdict:                  1.0.0-py36h21fa5f4_0       --> 1.0.0-py36_2

    html5lib:                  0.999999999-py36ha09b1f3_0 --> 1.0.1-py36h047fa9f
_0
    icu:                       58.2-vc14hc45fdbb_0        --> 58.2-ha66f8fd_1

    imagesize:                 0.7.1-py36he29f638_0       --> 1.0.0-py36_0

    intel-openmp:              2018.0.0-hcd89f80_7        --> 2018.0.0-hd92c6cd_
8
    ipykernel:                 4.6.1-py36hbb77b34_0       --> 4.8.2-py36_0

    ipython:                   6.1.0-py36h236ecc8_1       --> 6.2.1-py36h9cf0123
_1
    ipywidgets:                7.0.0-py36h2e74ada_0       --> 7.1.2-py36_0

    isort:                     4.2.15-py36h6198cc5_0      --> 4.3.4-py36_0

    jedi:                      0.10.2-py36hed927a0_0      --> 0.11.1-py36_0

    jinja2:                    2.9.6-py36h10aa3a0_1       --> 2.10-py36h292fed1_
0
    jpeg:                      9b-vc14h4d7706e_1          --> 9b-hb83a4c4_2

    jupyter_client:            5.1.0-py36h9902a9a_0       --> 5.2.2-py36_0

    jupyterlab:                0.27.0-py36h34cc53b_2      --> 0.31.10-py36_0

    jupyterlab_launcher:       0.4.0-py36h22c3ccf_0       --> 0.10.5-py36_0

    libiconv:                  1.15-vc14h29686d3_5        --> 1.15-h1df5818_7

    libpng:                    1.6.32-vc14h5163883_3      --> 1.6.34-h79bbb47_0

    libssh2:                   1.8.0-vc14hcf584a9_2       --> 1.8.0-hd619d38_4

    libtiff:                   4.0.8-vc14h04e2a1e_10      --> 4.0.9-h0f13578_0

    libxml2:                   2.9.4-vc14h8fd0f11_5       --> 2.9.7-h79bbb47_0

    libxslt:                   1.1.29-vc14hf85b8d4_5      --> 1.1.32-hf6f1972_0

    llvmlite:                  0.20.0-py36_0              --> 0.22.0-py36ha794a7
c_0
    lxml:                      4.1.0-py36h0dcd83c_0       --> 4.1.1-py36hef2cd61
_1
    lzo:                       2.10-vc14h0a64fa6_1        --> 2.10-h6df0209_2

    matplotlib:                2.1.0-py36h11b4b9c_0       --> 2.1.2-py36h016c42a
_0
    menuinst:                  1.4.10-py36h42196fb_0      --> 1.4.11-py36hfa6e2c
d_0
    mistune:                   0.7.4-py36h4874169_0       --> 0.8.3-py36_0

    mkl:                       2018.0.0-h36b65af_4        --> 2018.0.1-h2108138_
4
    mpmath:                    0.19-py36he326802_2        --> 1.0.0-py36hacc8adf
_2
    msgpack-python:            0.4.8-py36h58b1e9d_0       --> 0.5.5-py36he980bc4
_0
    networkx:                  2.0-py36hff991e3_0         --> 2.1-py36_0

    nltk:                      3.2.4-py36hd0e0a39_0       --> 3.2.5-py36h76d52bb
_0
    notebook:                  5.3.1-py36_0               --> 5.4.0-py36_0

    numba:                     0.35.0-np113py36_10        --> 0.37.0-np114py36he
a3a760_0
    numexpr:                   2.6.2-py36h7ca04dc_1       --> 2.6.4-py36h30784b8
_0
    numpy:                     1.13.3-py36ha320f96_0      --> 1.14.1-py36h4a9962
6_1
    olefile:                   0.44-py36h0a7bdd2_0        --> 0.45.1-py36_0

    openpyxl:                  2.4.8-py36hf3b77f6_1       --> 2.5.0-py36_0

    pandas:                    0.20.3-py36hce827b7_2      --> 0.22.0-py36h653833
5_0
    path.py:                   10.3.1-py36h3dd8b46_0      --> 11.0-py36_0

    patsy:                     0.4.1-py36h42cefec_0       --> 0.5.0-py36_0

    pep8:                      1.7.0-py36h0f3d67a_0       --> 1.7.1-py36_0

    pillow:                    4.2.1-py36hdb25ab2_0       --> 5.0.0-py36h0738816
_0
    pip:                       9.0.1-py36hadba87b_3       --> 9.0.1-py36_5

    ply:                       3.10-py36h1211beb_0        --> 3.11-py36_0

    psutil:                    5.4.0-py36h4e662fb_0       --> 5.4.3-py36hfa6e2cd
_0
    py:                        1.4.34-py36ha4aca3a_1      --> 1.5.2-py36hbcfbabc
_0
    pycrypto:                  2.6.1-py36he68e6e2_1       --> 2.6.1-py36hfa6e2cd
_7
    pycurl:                    7.43.0-py36h086bf4c_3      --> 7.43.0.1-py36h74b6
da3_0
    pylint:                    1.7.4-py36ha4e6ded_0       --> 1.8.2-py36_0

    pyodbc:                    4.0.17-py36h0006bc2_0      --> 4.0.22-py36h653833
5_0
    pyopenssl:                 17.2.0-py36h15ca2fc_0      --> 17.5.0-py36h5b7d81
7_0
    pysocks:                   1.6.7-py36h698d350_1       --> 1.6.8-py36_0

    pytest:                    3.2.1-py36h753b05e_1       --> 3.4.1-py36_0

    python:                    3.6.3-h3b118a2_4           --> 3.6.4-h6538335_1

    pytz:                      2017.2-py36h05d413f_1      --> 2018.3-py36_0

    pywin32:                   221-py36h9c10281_0         --> 222-py36hfa6e2cd_0

    pyzmq:                     16.0.2-py36h38c27d9_2      --> 16.0.3-py36he714bf
5_0
    rope:                      0.10.5-py36hcaf5641_0      --> 0.10.7-py36had63a6
9_0
    ruamel_yaml:               0.11.14-py36h9b16331_2     --> 0.15.35-py36hfa6e2
cd_1
    scikit-image:              0.13.0-py36h6dffa3f_1      --> 0.13.1-py36hfa6e2c
d_1
    scipy:                     0.19.1-py36h7565378_3      --> 1.0.0-py36h1260518
_0
    seaborn:                   0.8.0-py36h62cb67c_0       --> 0.8.1-py36h9b69545
_0
    setuptools:                36.5.0-py36h65f9e6e_0      --> 38.5.1-py36_0

    simplegeneric:             0.8.1-py36heab741f_0       --> 0.8.1-py36_2

    sortedcontainers:          1.5.7-py36ha90ac20_0       --> 1.5.9-py36_0

    sphinx:                    1.6.3-py36h9bb690b_0       --> 1.7.1-py36_0

    spyder:                    3.2.6-py36_0               --> 3.2.7-py36_0

    sqlalchemy:                1.1.13-py36h5948d12_0      --> 1.2.4-py36hfa6e2cd
_0
    sqlite:                    3.20.1-vc14h7ce8c62_1      --> 3.22.0-h9d3ae62_0

    tk:                        8.6.7-vc14hb68737d_1       --> 8.6.7-hcb92d03_3

    toolz:                     0.8.2-py36he152a52_0       --> 0.9.0-py36_0

    tornado:                   4.5.2-py36h57f6048_0       --> 4.5.3-py36_0

    typing:                    3.6.2-py36hb035bda_0       --> 3.6.4-py36_0

    vc:                        14-h2379b0c_2              --> 14-h0510ff6_3

    vs2015_runtime:            14.0.25123-hd4c4e62_2      --> 14.0.25123-3

    werkzeug:                  0.12.2-py36h866a736_0      --> 0.14.1-py36_0

    wheel:                     0.29.0-py36h6ce6cde_1      --> 0.30.0-py36h6c3ec1
4_1
    widgetsnbextension:        3.0.2-py36h364476f_1       --> 3.1.4-py36_0

    xlwings:                   0.11.4-py36hd3cf94d_0      --> 0.11.7-py36_0

    yaml:                      0.1.7-vc14hb31d195_1       --> 0.1.7-hc54c509_2

    zlib:                      1.2.11-vc14h1cdd9ab_1      --> 1.2.11-h8395fce_2

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: / DEBUG menuinst_win32:__init__(185): Menu: name: 'Anacon
da${PY_VER} ${PLATFORM}', prefix: 'C:\Users\jet\Anaconda3', env_name: 'None', mo
de: 'None', used_mode: 'system'
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\jet\Anaconda3\pythonw
.exe, args are ['C:\\Users\\jet\\Anaconda3\\cwp.py', 'C:\\Users\\jet\\Anaconda3'
, 'C:\\Users\\jet\\Anaconda3\\pythonw.exe', 'C:\\Users\\jet\\Anaconda3\\Scripts\
\spyder-script.py']
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\jet\Anaconda3\python.
exe, args are ['C:\\Users\\jet\\Anaconda3\\cwp.py', 'C:\\Users\\jet\\Anaconda3',
 'C:\\Users\\jet\\Anaconda3\\python.exe', 'C:\\Users\\jet\\Anaconda3\\Scripts\\s
pyder-script.py', '--reset']
- DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}
', prefix: 'C:\Users\jet\Anaconda3', env_name: 'None', mode: 'None', used_mode:
'system'
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\jet\Anaconda3\python.
exe, args are ['C:\\Users\\jet\\Anaconda3\\cwp.py', 'C:\\Users\\jet\\Anaconda3',
 'C:\\Users\\jet\\Anaconda3\\python.exe', 'C:\\Users\\jet\\Anaconda3\\Scripts\\j
upyter-notebook-script.py', '%USERPROFILE%']
failed
ERROR conda.core.link:_execute(481): An error occurred while installing package
'defaults::ipykernel-4.8.2-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\jet\Anaconda3\Scripts\.ipykernel-post-link.b
at
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: - DEBUG menuinst_win32:__init__(185): Menu: name: 'Ana
conda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\jet\Anaconda3', env_name: 'None',
 mode: 'None', used_mode: 'system'
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\jet\Anaconda3\python.
exe, args are ['C:\\Users\\jet\\Anaconda3\\cwp.py', 'C:\\Users\\jet\\Anaconda3',
 'C:\\Users\\jet\\Anaconda3\\python.exe', 'C:\\Users\\jet\\Anaconda3\\Scripts\\j
upyter-notebook-script.py', '%USERPROFILE%']
| DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}
', prefix: 'C:\Users\jet\Anaconda3', env_name: 'None', mode: 'None', used_mode:
'system'
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\jet\Anaconda3\pythonw
.exe, args are ['C:\\Users\\jet\\Anaconda3\\cwp.py', 'C:\\Users\\jet\\Anaconda3'
, 'C:\\Users\\jet\\Anaconda3\\pythonw.exe', 'C:\\Users\\jet\\Anaconda3\\Scripts\
\spyder-script.py']
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Users\jet\Anaconda3\python.
exe, args are ['C:\\Users\\jet\\Anaconda3\\cwp.py', 'C:\\Users\\jet\\Anaconda3',
 'C:\\Users\\jet\\Anaconda3\\python.exe', 'C:\\Users\\jet\\Anaconda3\\Scripts\\s
pyder-script.py', '--reset']
done

LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\jet\Anaconda3\Scripts\.ipykernel-post-link.b
at
==> script messages <==
<None>

(base) C:\Users\jet>

**Comment by kalefranz** [comment] 2018-03-01 21:44
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/8087

**Closed by kalefranz** 2018-03-01 21:44 UTC
