### ISSUE TITLE
Deprecation warnings about conda.compat give no advice as to how to remove the warning

### ISSUE THREAD

**Issue by bgoodr** [conda/conda#8512] opened 2019-04-06 03:08 UTC
## Current Behavior

Running conda env command emits a deprecation warning on stderr, with no obvious way to get rid of the warning, or to otherwise comply with its intended advice.  Although I don't consider myself to be a "new player" to Python or to conda, the introduction of warnings like this, without advice as to how to rectify it, is problematic for the newcomer. I have scripts that call conda info to get information on available env's, but this warning coming out on stderr causes problems for many invocations of conda in my scripts, and so I seek to irradiate this warning or somehow adjust my scripts to avoid using the features thus deprecated.  But the "bug" (if there is a bug) here is that there is no advice in the warning at all.

### Steps to Reproduce

```
$ conda info --envs >/dev/null
WARNING: The conda.compat module is deprecated and will be removed in a future release.
```

## Expected Behavior

There was no advice given in that message about how to make that warning disappear.  Is the user doing something incorrect here?   How do I make the error go away? Is there something I need to uninstall or stop using?  If there is something I should do differently, then the message should state as such and not leave the user to guess.
 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/brentg/.condarc
 populated config files : 
          conda version : 4.6.11
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/brentg/conda/Ubuntu.18.04.miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/brentg/conda/Ubuntu.18.04.miniconda3/pkgs
                          /home/brentg/.conda/pkgs
       envs directories : /home/brentg/conda/Ubuntu.18.04.miniconda3/envs
                          /home/brentg/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.1 Linux/4.18.0-17-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/brentg/conda/Ubuntu.18.04.miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
attrs                     19.1.0                   py37_1    defaults
backcall                  0.1.0                    py37_0    defaults
bleach                    3.1.0                    py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.11.5           py37he75722e_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.11                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.4.2            py37h1ba5d50_0    defaults
dbus                      1.13.6               h746ee38_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.5.0                    py37_1    defaults
entrypoints               0.3                      py37_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
glib                      2.56.2               hd408876_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      py37_0    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.4.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libpng                    1.6.36               hbc83047_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                he19cac6_0    defaults
markupsafe                1.1.1            py37h7b6447c_0    defaults
mistune                   0.8.4            py37h7b6447c_0    defaults
nbconvert                 5.4.1                    py37_3    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
notebook                  5.7.8                    py37_0    defaults
openssl                   1.1.1b               h7b6447c_1    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.4                    py37_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pexpect                   4.6.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       18.1                     py37_0    defaults
prometheus_client         0.6.0                    py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.14.11          py37h7b6447c_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.1                h0371630_7    defaults
python-dateutil           2.8.0                    py37_0    defaults
pyzmq                     18.0.0           py37he6710b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.4.3                    py37_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                40.6.3                   py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tornado                   6.0.2            py37h7b6447c_0    defaults
traitlets                 4.3.2                    py37_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.32.3                   py37_0    defaults
widgetsnbextension        3.4.2                    py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.3.1                he6710b0_3    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by msarahan** [comment] 2019-04-06 16:17
Yep, it's a bug. We'll have a fix out early this week. Please ignore it for now. Fix is in https://github.com/conda/conda/pull/8507 if you'd like to hack it in to your installation yourself.

**Comment by bgoodr** [comment] 2019-04-06 18:55
Thank you for addressing this!

**Comment by henryiii** [comment] 2019-04-06 19:35
Does this cause the return code to be non-zero? I have an appveyor build failing with 
```

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
conda : WARNING: The conda.compat module is deprecated and will be removed in a future release.
At line:20 char:3
+   conda install -y -q pytest numpy scipy
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: The co...future release.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: WARNING: The conda.compat module is deprecated and will be removed in a future release.
```

**Comment by carlosgino** [comment] 2019-04-08 16:31
> repl_python() # reticulate in R
Error: lexical error: invalid char in json text.
                                       WARNING: The conda.compat modul
                     (right here) ------^

**Comment by PaolaGhione** [comment] 2019-04-08 17:42
Hi,
I had the same trouble while installing Keras package in Rstudio (windows10) using Anaconda3.6 and I got the following error:
keras::install_keras()
Error: lexical error: invalid char in json text.
WARNING: The conda.compat modul
(right here) ------^

**Comment by dougmet** [comment] 2019-04-09 12:51
@PaolaGhione if you pull the latest reticulate using `remotes::install_github("rstudio/reticulate")` that gets around this by ignoring the warning. See rstudio/reticulate#477 (although mine is still falling over on something else).

**Comment by PaolaGhione** [comment] 2019-04-09 21:01
Hi Douglas, thanks for your suggestion, but yesterday, after many attempts, I got this solution:
1.) installation of R 3.5.2 (independent from directory (standard or any other)
2.) installation of RStudio (independent from directory)
3.) RStudio -> Tools -> Global Options -> Packages -> Disable both "Use secure download method for HTTP" and "Use Internet Explorer library/proxy for HTTP"
4.) installation of Miniconda3 (-> has to be the standard directory!) Version 4.5.11 (it did not work with the newest version)
5.) Use RStudio ->
install.packages("tensorflow")
install.packages("keras")
library("keras")
install_keras()
This worked for me and I am now able to use Keras in R!

**Comment by MuqadderIqbal** [comment] 2019-07-07 02:43
Hi guys, is there an estimated timeline for this to be merged to master? I just downloaded the latest version of anaconda and encountered this warning right away (trying to list out conda environments). Appreciate all the help getting this resolved!

**Comment by msarahan** [comment] 2019-07-07 02:55
This has been fixed for many conda releases, but we haven't had an Anaconda release since then. You can update conda by running

``conda update conda``

**Closed by msarahan** 2019-07-07 02:55 UTC

**Comment by MuqadderIqbal** [comment] 2019-07-07 03:08
Confirmed that after updating conda (and all other packages), this issue has been resolved. Thanks for the quick turnaround!
