### ISSUE TITLE
Trying to run conda install virtualenv

### ISSUE THREAD

**Issue by mctopherganesh** [conda/conda#5672] opened 2017-07-10 21:43 UTC
`user$conda install virtualenv`

`Traceback (most recent call last):
  File "/Users/user/anaconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 231, in install
    index = common.get_index_trap(**index_args)
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 622, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/api.py", line 26, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 292, in fetch_index
    session=CondaSession()) for url in urls)
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 292, in <genexpr>
    session=CondaSession()) for url in urls)
  File "/Users/user/anaconda3/lib/python3.5/site-packages/conda/connection.py", line 96, in __init__
    http_adapter = requests.adapters.HTTPAdapter(max_retries=retries)
TypeError: __init__() got an unexpected keyword argument 'max_retries'`

`Users-Computer:learning-flask user$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 1.1.0
     root environment : /Users/user/anaconda3  (writable)
  default environment : /Users/user/anaconda3
     envs directories : /Users/user/anaconda3/envs
        package cache : /Users/user/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
`

**Comment by tyler-thetyrant** [comment] 2017-07-11 14:15
Your conda version is extremely old. Please uninstall and reinstall the most recent version of conda (4.3.22) and try again. Closing this as I was not able to reproduce the issue in conda 4.3.23.

```
root@7890c18faaa6:/# conda install virtualenv
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /usr/local:

The following NEW packages will be INSTALLED:

    virtualenv: 15.1.0-py36_0

Proceed ([y]/n)? y

virtualenv-15. 100% |################################################################| Time: 0:00:00   5.29 MB/s
root@7890c18faaa6:/#
```

**Closed by tyler-thetyrant** 2017-07-11 14:15 UTC
