### ISSUE TITLE
Installing with --no-deps shouldn't result in an error if deps aren't present

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1599] opened 2015-09-11 06:53 UTC
If I use the `--no-deps` option to install something it seems weird to get an error when the dependencies aren't there:

```bash
# sudo -u wakari /opt/wakari/anaconda/bin/conda install  --no-deps --offline -p /opt/wak
ari/anaconda  r-base-3.2.1-0.tar.bz2
[      COMPLETE      ]|#############################################################################################| 100%
Extracting packages ...
[      COMPLETE      ]|#############################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#############################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################################################| 100%
Fetching package metadata: 
Error: No packages found in current linux-64 channels matching: pcre

You can search for this package on anaconda.org with

    anaconda search -t conda pcre

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

I know the dependencies aren't satisfied.  That is part of why I'm using `--no-deps`.

This is with latest conda:

```bash
# sudo -u wakari /opt/wakari/anaconda/bin/conda info
Current conda install:

             platform : linux-64
        conda version : 3.16.0
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /opt/wakari/anaconda  (writable)
  default environment : /opt/wakari/anaconda
     envs directories : /opt/wakari/anaconda/envs
        package cache : /opt/wakari/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/wakari/linux-64/
                        https://conda.anaconda.org/wakari/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /opt/wakari/anaconda/.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment] 2015-09-14 17:31
Dupe of https://github.com/conda/conda/issues/1118

**Closed by asmeurer** 2015-09-14 17:31 UTC
