### ISSUE TITLE
Attribute error during install

### ISSUE THREAD

**Issue by finwitz** [conda/conda#4083] opened 2016-12-16 09:56 UTC
>             platform : win-64
>           conda version : 4.2.13
>        conda is private : False
>       conda-env version : 4.2.13
>     conda-build version : 1.19.0
>          python version : 3.5.2.final.0
>        requests version : 2.12.4
>        root environment : C:\Users\Anaconda3  (writable)
>     default environment : C:\Users\Anaconda3
>        envs directories : C:\Users\Anaconda3\envs
>           package cache : C:\Users\Anaconda3\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False

>     Traceback (most recent call last):
>       File "C:\Users\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\Users\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
>         exit_code = args.func(args, p)
>       File "C:\Users\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
>         install(args, parser, 'install')
>       File "C:\Users\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
>         prefix=prefix)
>       File "C:\Users\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
>         index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
>       File "C:\Users\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
>         repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
>       File "C:\Users\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
>         repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
>       File "C:\Users\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
>         return self.__get_result()
>       File "C:\Users\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
>         raise self._exception
>       File "C:\Users\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
>         result = self.fn(*self.args, **self.kwargs)
>       File "C:\Users\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
>         res = f(*args, **kwargs)
>       File "C:\Users\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
>         timeout=(6.1, 60))
>       File "C:\Users\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
>         return self.request('GET', url, **kwargs)
>       File "C:\Users\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
>         resp = self.send(prep, **send_kwargs)
>       File "C:\Users\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
>         r = adapter.send(request, **kwargs)
>       File "C:\Users\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
>         timeout=timeout
>       File "C:\Users\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
>         chunked=chunked)
>       File "C:\Users\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
>         self._validate_conn(conn)
>       File "C:\Users\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
>         conn.connect()
>       File "C:\Users\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in connect
>         cert = self.sock.getpeercert()
>       File "C:\Users\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
>         'subjectAltName': get_subj_alt_name(x509)
>       File "C:\Users\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
>         ext = cert.extensions.get_extension_for_class(
>     AttributeError: 'Extensions' object has no attribute 'get_extension_for_class

`

**Comment by goretkin** [comment] 2016-12-18 15:00
This happened to me yesterday. The following install/upgrades succeeded. But then any conda install afterwards appeared to fail.

```
(root) $ conda install networkx
Fetching package metadata: ....
Solving package specifications: ...................
Package plan for installation in environment /Users/goretkin/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B  defaults
    decorator-4.0.10           |           py27_1          13 KB  defaults
    pycosat-0.6.1              |           py27_1          89 KB  defaults
    requests-2.12.4            |           py27_0         752 KB  defaults
    ruamel_yaml-0.11.14        |           py27_0         184 KB  defaults
    conda-4.2.13               |           py27_0         375 KB  defaults
    networkx-1.11              |           py27_0         1.1 MB  defaults
    pip-9.0.1                  |           py27_1         1.6 MB  defaults
    ------------------------------------------------------------
                                           Total:         4.0 MB

The following NEW packages will be INSTALLED:

    ruamel_yaml: 0.11.14-py27_0 defaults

The following packages will be UPDATED:

    conda:       3.18.8-py27_0 defaults --> 4.2.13-py27_0  defaults
    conda-env:   2.4.5-py27_0  defaults --> 2.6.0-0        defaults
    decorator:   4.0.4-py27_0  defaults --> 4.0.10-py27_1  defaults
    enum34:      1.0.4-py27_0  defaults --> 1.1.6-py27_0   defaults
    networkx:    1.10-py27_0   defaults --> 1.11-py27_0    defaults
    openssl:     1.0.2d-0      defaults --> 1.0.2j-0       defaults
    pip:         7.1.2-py27_0  defaults --> 9.0.1-py27_1   defaults
    pycosat:     0.6.1-py27_0  defaults --> 0.6.1-py27_1   defaults
    python:      2.7.11-0      defaults --> 2.7.12-1       defaults
    requests:    2.8.1-py27_0  defaults --> 2.12.4-py27_0  defaults
    setuptools:  18.5-py27_0   defaults --> 27.2.0-py27_0  defaults
    sqlite:      3.8.4.1-1     defaults --> 3.13.0-0       defaults
    wheel:       0.26.0-py27_1 defaults --> 0.29.0-py27_0  defaults
    zlib:        1.2.8-0       defaults --> 1.2.8-3        defaults
```

**Comment by kalefranz** [comment] 2017-05-01 19:55
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:55 UTC
