### ISSUE TITLE
windows 7 - failed "conda update conda"

### ISSUE THREAD

**Issue by OrnaBregman** [conda/conda#1215] opened 2015-03-23 15:50 UTC
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\Lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\Lib\site-packages\conda\cli\main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\Lib\site-packages\conda\cli\install.py", line 184, in install
    unknown=args.unknown)
  File "C:\Anaconda\Lib\site-packages\conda\api.py", line 40, in get_index
    unknown=unknown)
  File "C:\Anaconda\Lib\site-packages\conda\utils.py", line 77, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\Lib\site-packages\conda\fetch.py", line 152, in fetch_index
    session = CondaSession()
  File "C:\Anaconda\Lib\site-packages\conda\connection.py", line 58, in __init__
    super(CondaSession, self).__init__(*args, **kwargs)
  File "C:\Anaconda\Lib\site-packages\requests\sessions.py", line 273, in __init__
    self.headers = default_headers()
  File "C:\Anaconda\Lib\site-packages\requests\utils.py", line 555, in default_headers
    'User-Agent': default_user_agent(),
  File "C:\Anaconda\Lib\site-packages\requests\utils.py", line 524, in default_user_agent
    _implementation = platform.python_implementation()
  File "C:\Python27\Lib\platform.py", line 1498, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1463, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.7 |Anaconda 2.0.1 (64-bit)| (default, Jun 11 2014, 10:40:02) [MSC v.1500 64 bit (AMD64)]'

**Comment by asmeurer** [comment] 2015-03-23 16:20
Dupe of https://github.com/ContinuumIO/anaconda-issues/issues/33.

**Closed by asmeurer** 2015-03-23 16:20 UTC
