### ISSUE TITLE
Bad packages cause mysterious error

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5455] opened 2017-05-30 19:56 UTC
This seems like it is probably a bugged package in my collection causing this, perhaps from development on conda-build.  I'm posting it here before I attempt to clean up, just in case someone else might be affected by this error.

```
__________________________________ test_recipe_builds[always_include_files_glob] ___________________________________
Traceback (most recent call last):
  File "/Users/msarahan/code/conda-build/tests/test_api_build.py", line 87, in test_recipe_builds
    api.build(recipe, config=testing_config)
  File "/Users/msarahan/code/conda-build/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/msarahan/code/conda-build/conda_build/build.py", line 1499, in build_tree
    built_packages=built_packages,
  File "/Users/msarahan/code/conda-build/conda_build/build.py", line 895, in build
    subdir=m.config.build_subdir, is_cross=m.is_cross)
  File "/Users/msarahan/code/conda-build/conda_build/environ.py", line 747, in create_env
    execute_actions(actions, index, verbose=config.debug)
  File "/Users/msarahan/code/conda/conda/plan.py", line 611, in execute_actions
    plan = plan_from_actions(actions, index)
  File "/Users/msarahan/code/conda/conda/plan.py", line 352, in plan_from_actions
    plan = inject_UNLINKLINKTRANSACTION(plan, index, prefix, axn, specs)
  File "/Users/msarahan/code/conda/conda/plan.py", line 301, in inject_UNLINKLINKTRANSACTION
    pfe.prepare()
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 425, in prepare
    for dist in self.link_dists)
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 425, in <genexpr>
    for dist in self.link_dists)
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 345, in make_actions_for_dist
    key=lambda pce: pce and pce.is_extracted and pce.tarball_matches_md5_if(md5)
  File "/Users/msarahan/code/conda/conda/_vendor/auxlib/collection.py", line 88, in first
    return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
  File "/Users/msarahan/code/conda/conda/_vendor/auxlib/collection.py", line 88, in <genexpr>
    return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 344, in <genexpr>
    (PackageCache(pkgs_dir).get(record, None) for pkgs_dir in context.pkgs_dirs),
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 88, in get
    return self._package_cache_records[package_ref]
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 195, in _package_cache_records
    return self.__package_cache_records or self.load() or self.__package_cache_records
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 82, in load
    package_cache_record = self._make_single_record(base_name)
  File "/Users/msarahan/code/conda/conda/core/package_cache.py", line 250, in _make_single_record
    repodata_record = read_repodata_json(extracted_package_dir)
  File "/Users/msarahan/code/conda/conda/gateways/disk/read.py", line 116, in read_repodata_json
    record = IndexRecord(**json.load(fi))
  File "/Users/msarahan/code/conda/conda/_vendor/auxlib/entity.py", line 714, in __call__
    instance = super(EntityType, cls).__call__(*args, **kwargs)
  File "/Users/msarahan/code/conda/conda/_vendor/auxlib/entity.py", line 731, in __init__
    setattr(self, key, kwargs[key])
  File "/Users/msarahan/code/conda/conda/_vendor/auxlib/entity.py", line 425, in __set__
    instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
  File "/Users/msarahan/code/conda/conda/_vendor/auxlib/entity.py", line 601, in validate
    raise ValidationError(self.name, val)
conda._vendor.auxlib.exceptions.ValidationError: Value for constrains cannot be None.
```

**Comment by msarahan** [comment] 2017-05-30 20:03
Not sure about this.  I cleaned out my caches with:

``conda build purge-all``
and
``conda clean -ptiy``

and this error stays exactly the same.  Let me know if I can provide further info.  I need to keep pushing forward on conda-build with conda 4.3.x for now.

**Comment by kalefranz** [comment] 2017-05-31 23:46
This happened when working with conda 4.4.x, correct?  There are/were a couple problems switching back and forth between 4.3.x and 4.4.x.  Some of them are solved; some might not be yet.

The way I had been having to fix this is look at where the pkg cache directories are as reported by `conda info`, then `rm -rf <PKG_DIR>/*`.

Going to leave this issue open as a reminder to check and make sure all of these cases have been cleaned up for 4.4.

**Comment by msarahan** [comment] 2017-06-01 02:14
How should I switch to avoid these problems?  I generally have a development install of conda, and just checkout various git branches to switch versions.

Thanks for the tip on conda info.  I had only been clearing out the pkgs dir by doing ```conda clean -ptiy```.  I don't think it's a good idea to tell customers to do that rm -rf, though.  Let me know if I can help in diagnosing the issue or testing fixes.

**Comment by kalefranz** [comment] 2017-06-02 02:55
I agree.  I don't think the 4.4.x branch writes files to disk any longer that create this sticky problem.  But leaving this ticket open to track and confirm before we have a real public release.

**Comment by stefanseefeld** [comment] 2017-06-05 19:59
I'm observing this issue running `conda`'s own test suite. Wouldn't that rule out a "bad" package to be the cause ?

**Comment by kalefranz** [comment] 2017-06-22 16:21
I haven't seen this recently. This is probably solved.

**Comment by kalefranz** [comment] 2017-08-17 09:06
Dated issue that I believe to now be solved.  Closing.

**Closed by kalefranz** 2017-08-17 09:06 UTC
Labels: source:core, type:bug
