### ISSUE TITLE
Improve repodata / subdir_data interface

### ISSUE THREAD

**Issue by dholth** [conda/conda#12521] opened 2023-03-22 15:49 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

An improved repodata interface is needed generally and for libmamba-solver which wants to download without parsing.

This is about adding a "fetch to path" interface for libmamba-solver and about further separating network access from SubdirData's repodata parsing. e.g. https://github.com/conda/conda/pull/12475/files#diff-813ca3bd61f56355fb3ea7c560d18b892d42d62a07fa0e78666dcfa50c5fda13R761

Test by enabling jlap, running `CONDA_DEBUG=1 conda (search or install) ...`, and then try again in an hour or so once the remote repository has updated -- check that jlap is used to get a small diff instead of re-fetching the entire remote data.

Test that things still work without jlap as well, but not in the middle of the jlap test -- remember that switching between jlap and not-jlap will invalidate the cache.

**Comment by dholth** [comment] 2023-03-22 16:05
Related to https://github.com/conda/conda-libmamba-solver/issues/114

**Comment by travishathaway** [comment] 2023-05-08 09:27
@dholth, do you have a plan for improving this interface already? Is this related to your work in:

- https://github.com/conda/conda/pull/12475

**Comment by jezdez** [comment] 2023-05-10 07:04
Is this a duplicate of #12572?

**Comment by dholth** [comment] 2023-05-10 12:02
No but they might be addressed in the same PR.

**Closed** 2023-05-17 18:28 UTC
Labels: type::feature, source::anaconda, in-progress
