### ISSUE TITLE
should_bypass_proxies_patched() error

### ISSUE THREAD

**Issue by tedtoal** [conda/conda#7518] opened 2018-07-09 22:11 UTC
**I'm submitting a...**
  - [X] bug report

## Current Behavior
Any "conda install" or "conda update" produces a long report of error information, inside of which is invariably buried the following error:

`
TypeError: should_bypass_proxies_patched() missing 1 required positional argument: 'no_proxy'
`

This began happening after I did:
```
conda upgrade python
```

which succeeded and before doing it told me to do this, which I did after the above succeeded:

```
conda upgrade -n base conda
```

(or something close to that).  That succeeded, and it was after that that I started having the error.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : R_pipeline
    active env location : /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/R_pipeline
            shell level : 2
       user config file : /home/twtoal/.condarc
 populated config files : /home/twtoal/.condarc
          conda version : 4.5.6
    conda-build version : not installed
         python version : 3.5.3.final.0
       base environment : /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl  (writable)
           channel URLs : https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/pkgs
                          /home/twtoal/.conda/pkgs
       envs directories : /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs
                          /home/twtoal/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.6 requests/2.13.0 CPython/3.5.3 Linux/4.4.0-127-generic ubuntu/14.04 glibc/2.19
                UID:GID : 20494:20494
             netrc file : /home/twtoal/.netrc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/twtoal/.condarc <==
channels:
  - intel
  - conda-forge
  - r
  - bioconda
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/R_pipeline:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6                  intel_14  [intel]  intel
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.8                  intel_1  [intel]  intel
curl                      7.52.1                        0    conda-forge
distribute                0.6.45                   py27_1    defaults
fontconfig                2.12.1                  intel_0  [intel]  intel
freetype                  2.5.5                   intel_9  [intel]  intel
glib                      2.50.2                        1    defaults
gmp                       6.1.2                         0    conda-forge
gsl                       2.2.1                         1    conda-forge
harfbuzz                  0.9.39                        2    defaults
icu                       58.2                          0    conda-forge
intelpython               2018.0.3                      0    intel
jpeg                      9c                      intel_0  [intel]  intel
libffi                    3.2.1                   intel_8  [intel]  intel
libgcc                    5.2.0                         0    defaults
libiconv                  1.14                          4    conda-forge
libpng                    1.6.34                  intel_1  [intel]  intel
libsodium                 1.0.16                  intel_1  [intel]  intel
libtiff                   4.0.9                   intel_2  [intel]  intel
libxml2                   2.9.5                   intel_0  [intel]  intel
mysql-connector-c         6.1.6                         2    bioconda
mysql-python              1.2.5                    py27_0    defaults
mysqlclient               1.3.10                   py27_0    bioconda
ncurses                   5.9                          10    conda-forge
numpy                     1.14.1                    <pip>
openjdk                   8.0.121                       1    defaults
openssl                   1.0.2o                  intel_0  [intel]  intel
pandoc                    2.0.0.1                       1    conda-forge
pango                     1.40.3                        1    defaults
pcre                      8.39                          0    conda-forge
pip                       9.0.1              py27_intel_0  [intel]  intel
pixman                    0.34.0                  intel_0  [intel]  intel
python                    2.7.14                  intel_6  [intel]  intel
r                         3.4.1                  r3.4.1_0    r
r-ape                     4.1                    r3.3.2_0    conda-forge
r-assertthat              0.1                    r3.3.2_0    conda-forge
r-backports               1.0.5                  r3.3.2_0    conda-forge
r-base                    3.4.1                         4    conda-forge
r-base64enc               0.1_3                  r3.3.2_0    conda-forge
r-bh                      1.62.0_1               r3.3.2_0    conda-forge
r-bit                     1.1_12                 r3.3.2_0    conda-forge
r-bit64                   0.9_5                  r3.3.2_0    conda-forge
r-bitops                  1.0_6                  r3.3.2_0    conda-forge
r-blob                    1.1.0                  r3.3.2_0    conda-forge
r-boot                    1.3_19                 r3.4.1_0    r
r-broom                   0.4.2                  r3.3.2_0    conda-forge
r-car                     2.1_4                  r3.3.2_0    conda-forge
r-caret                   6.0_76                 r3.3.2_0    conda-forge
r-catools                 1.17.1                 r3.3.2_0    conda-forge
r-cellranger              1.1.0                  r3.3.2_0    conda-forge
r-class                   7.3_14                 r3.4.1_0    r
r-cluster                 2.0.6                  r3.4.1_0    r
r-codetools               0.2_15                 r3.4.1_0    r
r-colorspace              1.3_2                  r3.3.2_0    conda-forge
r-crayon                  1.3.2                  r3.3.2_0    conda-forge
r-curl                    2.6                    r3.4.1_0    r
r-data.table              1.10.4                 r3.3.2_0    conda-forge
r-dbi                     0.6_1                  r3.3.2_0    conda-forge
r-devtools                1.13.5                 r3.3.2_0    conda-forge
r-dichromat               2.0_0                  r3.3.2_0    conda-forge
r-digest                  0.6.12                 r3.3.2_0    conda-forge
r-dotcall64               0.9_04                 r3.3.2_0    conda-forge
r-dplyr                   0.5.0                  r3.3.2_0    conda-forge
r-evaluate                0.10                   r3.3.2_0    conda-forge
r-feather                 0.3.1                  r3.3.2_0    conda-forge
r-forcats                 0.2.0                  r3.3.2_0    conda-forge
r-foreach                 1.4.3                  r3.4.1_0    r
r-foreign                 0.8_68                 r3.4.1_0    r
r-formatr                 1.4                    r3.3.2_0    conda-forge
r-futile.logger           1.4.3                  r3.3.2_0    conda-forge
r-futile.options          1.0.0                  r3.3.2_0    conda-forge
r-getopt                  1.20.0                 r3.4.1_0    conda-forge
r-ggplot2                 2.2.1                  r3.3.2_0    conda-forge
r-gistr                   0.4.0                  r3.3.2_0    conda-forge
r-git2r                   0.19.0                 r3.3.2_0    conda-forge
r-glmnet                  2.0_5                  r3.3.2_0    conda-forge
r-gsalib                  2.1                    r3.3.2_0    conda-forge
r-gtable                  0.2.0                  r3.3.2_0    conda-forge
r-haven                   1.0.0                  r3.3.2_0    conda-forge
r-hexbin                  1.27.1                 r3.3.2_0    conda-forge
r-highr                   0.6                    r3.3.2_0    conda-forge
r-hms                     0.3                    r3.3.2_0    conda-forge
r-htmltools               0.3.6                  r3.3.2_0    conda-forge
r-htmlwidgets             0.9                    r3.3.2_0    conda-forge
r-httpuv                  1.3.3                  r3.3.2_0    conda-forge
r-httr                    1.2.1                  r3.3.2_0    conda-forge
r-irdisplay               0.4.4                  r3.3.2_0    conda-forge
r-iterators               1.0.8                  r3.4.1_0    r
r-jpeg                    0.1_8                  r3.3.2_0    conda-forge
r-jsonlite                1.5                    r3.4.1_0    r
r-kernsmooth              2.23_15                r3.4.1_0    r
r-knitr                   1.16                   r3.3.2_0    conda-forge
r-labeling                0.3                    r3.3.2_0    conda-forge
r-lambda.r                1.1.9                  r3.3.2_0    conda-forge
r-lattice                 0.20_35                r3.4.1_0    r
r-lazyeval                0.2.0                  r3.3.2_0    conda-forge
r-lme4                    1.1_13                 r3.3.2_0    conda-forge
r-lubridate               1.6.0                  r3.3.2_0    conda-forge
r-magrittr                1.5                    r3.3.2_0    conda-forge
r-maps                    3.2.0                  r3.3.2_0    conda-forge
r-markdown                0.8                    r3.3.2_0    conda-forge
r-mass                    7.3_47                 r3.4.1_0    r
r-matrix                  1.2_10                 r3.4.1_0    r
r-matrixmodels            0.4_1                  r3.3.2_0    conda-forge
r-memoise                 1.1.0                  r3.3.2_0    conda-forge
r-mgcv                    1.8_17                 r3.4.1_0    r
r-mime                    0.5                    r3.3.2_0    conda-forge
r-minqa                   1.2.4                  r3.3.2_0    conda-forge
r-mnormt                  1.5_5                  r3.3.2_0    conda-forge
r-modelmetrics            1.1.0                  r3.3.2_0    conda-forge
r-modelr                  0.1.0                  r3.3.2_0    conda-forge
r-munsell                 0.4.3                  r3.3.2_0    conda-forge
r-nlme                    3.1_131                r3.4.1_0    r
r-nloptr                  1.0.4                  r3.3.2_2    r
r-nnet                    7.3_12                 r3.4.1_0    r
r-openssl                 0.9.7                  r3.3.2_0    conda-forge
r-optparse                1.4.4                  r3.4.1_0    conda-forge
r-pbdzmq                  0.2_4                  r3.3.2_0    conda-forge
r-pbkrtest                0.4_7                  r3.3.2_0    conda-forge
r-permute                 0.9_4                         0    conda-forge
r-pkgconfig               2.0.1                  r3.3.2_0    conda-forge
r-plogr                   0.1_1                  r3.3.2_0    conda-forge
r-plyr                    1.8.4                  r3.3.2_0    conda-forge
r-png                     0.1_7                  r3.4.1_3    r
r-pryr                    0.1.2                  r3.3.2_0    conda-forge
r-psych                   1.7.3.21               r3.3.2_0    conda-forge
r-purrr                   0.2.2                  r3.3.2_0    conda-forge
r-quantmod                0.4_8                  r3.3.2_0    conda-forge
r-quantreg                5.33                   r3.3.2_0    conda-forge
r-r.methodss3             1.7.1                  r3.3.2_0    conda-forge
r-r.oo                    1.21.0                 r3.3.2_0    conda-forge
r-r.utils                 2.5.0                  r3.3.2_0    conda-forge
r-r6                      2.2.1                  r3.4.1_0    r
r-randomforest            4.6_12                 r3.3.2_0    conda-forge
r-rbokeh                  0.5.0                  r3.3.2_0    conda-forge
r-rcolorbrewer            1.1_2                  r3.3.2_0    conda-forge
r-rcpp                    0.12.13                r3.3.2_0    conda-forge
r-rcpparmadillo           0.7.800.2.0            r3.3.2_0    conda-forge
r-rcppeigen               0.3.2.9.1              r3.3.2_0    conda-forge
r-rcurl                   1.95_4.8               r3.3.2_0    conda-forge
r-readr                   1.1.0                  r3.3.2_0    conda-forge
r-readxl                  1.0.0                  r3.3.2_0    conda-forge
r-recommended             3.4.1                  r3.4.1_0    r
r-rematch                 1.0.1                  r3.3.2_0    conda-forge
r-repr                    0.10                   r3.3.2_0    conda-forge
r-reshape2                1.4.2                  r3.3.2_0    conda-forge
r-rjava                   0.9_8                  r3.3.2_0    r
r-rlang                   0.1.2                  r3.3.2_0    conda-forge
r-rmarkdown               1.6                    r3.3.2_2    conda-forge
r-rpart                   4.1_11                 r3.4.1_0    r
r-rprojroot               1.2                    r3.3.2_0    conda-forge
r-rsqlite                 2.0                    r3.3.2_0    conda-forge
r-rstudioapi              0.7                    r3.3.2_0    conda-forge
r-rvest                   0.3.2                  r3.3.2_0    conda-forge
r-scales                  0.4.1                  r3.3.2_0    conda-forge
r-selectr                 0.3_1                  r3.3.2_0    conda-forge
r-shiny                   1.0.3                  r3.3.2_0    conda-forge
r-snow                    0.4_2                  r3.3.2_0    conda-forge
r-sourcetools             0.1.6                  r3.3.2_0    conda-forge
r-sp                      1.2_4                  r3.3.2_0    conda-forge
r-spam                    2.1_1                  r3.3.2_0    conda-forge
r-sparsem                 1.76                   r3.3.2_0    conda-forge
r-spatial                 7.3_11                 r3.4.1_0    r
r-splancs                 2.01_40                r3.3.2_0    conda-forge
r-stringi                 1.1.2                  r3.3.2_0    conda-forge
r-stringr                 1.2.0                  r3.3.2_0    conda-forge
r-survival                2.41_3                 r3.4.1_0    r
r-tibble                  1.3.3                  r3.3.2_0    conda-forge
r-tidyr                   0.6.1                  r3.3.2_0    conda-forge
r-tidyverse               1.1.1                  r3.3.2_0    conda-forge
r-ttr                     0.23_1                 r3.3.2_0    conda-forge
r-uuid                    0.1_2                  r3.3.2_0    conda-forge
r-vegan                   2.4_3                  r3.3.2_0    conda-forge
r-vgam                    1.0_3                  r3.4.1_0    r
r-viridislite             0.2.0                  r3.3.2_0    conda-forge
r-whisker                 0.3_2                  r3.3.2_0    conda-forge
r-withr                   2.1.1                  r3.3.2_0    conda-forge
r-xml                     3.98_1.6               r3.3.2_0    conda-forge
r-xml2                    1.1.1                  r3.3.2_0    conda-forge
r-xtable                  1.8_2                  r3.3.2_0    conda-forge
r-xts                     0.9_7                  r3.3.2_0    conda-forge
r-yaml                    2.1.14                 r3.3.2_0    conda-forge
r-zoo                     1.7_14                 r3.3.2_0    conda-forge
readline                  7.0                           0    conda-forge
setuptools                27.2.0             py27_intel_0  [intel]  intel
sqlite                    3.23.1                  intel_0  [intel]  intel
tcl                       8.6.4                  intel_19  [intel]  intel
tk                        8.6.4                  intel_26  [intel]  intel
util-linux                2.21                          0    defaults
wheel                     0.31.0             py27_intel_0  [intel]  intel
xz                        5.2.3                   intel_0  [intel]  intel
zeromq                    4.2.3                   intel_0  [intel]  intel
zlib                      1.2.11                  intel_3  [intel]  intel
```
</p></details>

**Comment by kalefranz** [comment] 2018-07-09 22:47
Duplicate of https://github.com/conda/conda/issues/7506.  The `requests` version conda is depending on has gotten out of sync somehow.  I very rarely recommend this, but in this case, `/share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/bin/pip install -U requests` should unwind the problem for you.

**Closed by kalefranz** 2018-07-09 22:47 UTC
