### ISSUE TITLE
`conda install --file` reports Python 3.5* conflict for everything

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2791] opened 2016-06-21 15:00 UTC
I have a file with a bunch of packages listed in it (attached, below).  No versions.  I want to install them into my current Python 3.5-based Conda environment using the command:

```
$ conda install --file pkgs_only.txt
```

[pkgs_only.txt](https://github.com/conda/conda/files/325862/pkgs_only.txt)

However I get this kind of output:

```
$ conda install --file pkgs_only.txt
Fetching package metadata .......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - astropy
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

I don't understand how `astropy` can be in conflict with `python 3.5`.  The environment already has `astropy` and `python` 3.5 installed.  Is that the problem?  Is this a variation on the problem I reported in #2598?

```
$ conda list | grep -e astropy -e numpy -e ^python
astropy                   1.1.2               np110py35_0  
numpy                     1.10.4                   py35_0  
python                    3.5.1                         0  
```

In case it helps, here are my `conda info` and `conda list` details:

```
             platform : osx-64
        conda version : 4.1.2
  conda-build version : 1.20.3
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/ijstokes/anaconda  (writable)
  default environment : /Users/ijstokes/anaconda/envs/ana40py35b
     envs directories : /Users/ijstokes/anaconda/envs
        package cache : /Users/ijstokes/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ijstokes/.condarc
    is foreign system : False
```

```
alabaster=0.7.7=py35_0
anaconda=4.0.0=np110py35_0
anaconda-client=1.4.0=py35_0
anaconda-navigator=1.1.0=py35_0
appnope=0.1.0=py35_0
appscript=1.0.1=py35_0
argcomplete=1.0.0=py35_1
astropy=1.1.2=np110py35_0
babel=2.2.0=py35_0
beautifulsoup4=4.4.1=py35_0
bitarray=0.8.1=py35_0
blaze=0.9.1=py35_0
bokeh=0.11.1=py35_0
boto=2.39.0=py35_0
bottleneck=1.0.0=np110py35_0
cffi=1.5.2=py35_0
chest=0.2.3=py35_0
cloudpickle=0.1.1=py35_0
clyent=1.2.1=py35_0
colorama=0.3.7=py35_0
conda-manager=0.3.1=py35_0
configobj=5.0.6=py35_0
cryptography=1.3=py35_0
curl=7.45.0=0
cycler=0.10.0=py35_0
cython=0.23.4=py35_1
cytoolz=0.7.5=py35_0
dask=0.8.1=py35_0
datashape=0.5.1=py35_0
decorator=4.0.9=py35_0
dill=0.2.4=py35_0
docutils=0.12=py35_0
dynd-python=0.7.2=py35_0
et_xmlfile=1.0.1=py35_0
fastcache=1.0.2=py35_0
flask=0.10.1=py35_1
flask-cors=2.1.2=py35_0
freetype=2.5.5=0
gevent=1.1.0=py35_0
greenlet=0.4.9=py35_0
h5py=2.5.0=np110py35_4
hdf5=1.8.15.1=2
heapdict=1.0.0=py35_0
idna=2.0=py35_0
ipykernel=4.3.1=py35_0
ipython=4.1.2=py35_1
ipython_genutils=0.1.0=py35_0
ipywidgets=4.1.1=py35_0
itsdangerous=0.24=py35_0
jbig=2.1=0
jdcal=1.2=py35_0
jedi=0.9.0=py35_0
jinja2=2.8=py35_0
jpeg=8d=1
jsonschema=2.4.0=py35_0
jupyter=1.0.0=py35_2
jupyter_client=4.2.2=py35_0
jupyter_console=4.1.1=py35_0
jupyter_core=4.1.0=py35_0
libdynd=0.7.2=0
libpng=1.6.17=0
libtiff=4.0.6=1
libxml2=2.9.2=0
libxslt=1.1.28=2
llvmlite=0.9.0=py35_0
locket=0.2.0=py35_0
lxml=3.6.0=py35_0
markupsafe=0.23=py35_0
matplotlib=1.5.1=np110py35_0
mistune=0.7.2=py35_1
mkl=11.3.1=0
mkl-service=1.1.2=py35_0
mpmath=0.19=py35_0
multipledispatch=0.4.8=py35_0
nbconvert=4.1.0=py35_0
nbformat=4.0.1=py35_0
networkx=1.11=py35_0
nltk=3.2=py35_0
nose=1.3.7=py35_0
notebook=4.1.0=py35_2
numba=0.24.0=np110py35_0
numexpr=2.5=np110py35_0
numpy=1.10.4=py35_0
odo=0.4.2=py35_0
openpyxl=2.3.2=py35_0
openssl=1.0.2g=0
pandas=0.18.0=np110py35_0
partd=0.3.2=py35_1
path.py=8.1.2=py35_1
patsy=0.4.0=np110py35_0
pep8=1.7.0=py35_0
pexpect=4.0.1=py35_0
pickleshare=0.5=py35_0
pillow=3.1.1=py35_0
pip=8.1.1=py35_1
ply=3.8=py35_0
psutil=4.1.0=py35_1
ptyprocess=0.5=py35_0
py=1.4.31=py35_0
pyasn1=0.1.9=py35_0
pycosat=0.6.1=py35_0
pycparser=2.14=py35_0
pycrypto=2.6.1=py35_0
pycurl=7.19.5.3=py35_0
pyflakes=1.1.0=py35_0
pygments=2.1.1=py35_0
pyopenssl=0.15.1=py35_2
pyparsing=2.0.3=py35_0
pyqt=4.11.4=py35_1
pytables=3.2.2=np110py35_1
pytest=2.8.5=py35_0
python=3.5.1=0
python-dateutil=2.5.1=py35_0
python.app=1.2=py35_4
pytz=2016.2=py35_0
pyyaml=3.11=py35_1
pyzmq=15.2.0=py35_0
qt=4.8.7=1
qtawesome=0.3.2=py35_0
qtconsole=4.2.0=py35_0
qtpy=1.0=py35_0
readline=6.2=2
redis=2.6.9=0
redis-py=2.10.3=py35_0
requests=2.9.1=py35_0
rope=0.9.4=py35_1
scikit-image=0.12.3=np110py35_0
scikit-learn=0.17.1=np110py35_0
scipy=0.17.0=np110py35_0
setuptools=20.3=py35_0
simplegeneric=0.8.1=py35_0
singledispatch=3.4.0.3=py35_0
sip=4.16.9=py35_0
six=1.10.0=py35_0
snowballstemmer=1.2.1=py35_0
sockjs-tornado=1.0.1=py35_0
sphinx=1.3.5=py35_0
sphinx_rtd_theme=0.1.9=py35_0
spyder=2.3.8=py35_1
sqlalchemy=1.0.12=py35_0
sqlite=3.9.2=0
statsmodels=0.6.1=np110py35_0
sympy=1.0=py35_0
terminado=0.5=py35_1
tk=8.5.18=0
toolz=0.7.4=py35_0
tornado=4.3=py35_0
traitlets=4.2.1=py35_0
unicodecsv=0.14.1=py35_0
werkzeug=0.11.4=py35_0
wheel=0.29.0=py35_0
xlrd=0.9.4=py35_0
xlsxwriter=0.8.4=py35_0
xlwings=0.7.0=py35_0
xlwt=1.0.0=py35_0
xz=5.0.5=1
yaml=0.1.6=0
zeromq=4.1.3=0
zlib=1.2.8=0
```

**Comment by mcg1969** [comment] 2016-06-22 01:22
I'm afraid the problem is that the conflict hints are broken. I have _yet_ to see a case where `conda` reports a conflict when there isn't one. But the hints are definitely broken and lead people on wild goose chases. I have a WIP PR that addresses this but it's a it dated and I don't know the priority.

**Comment by kalefranz** [comment] 2016-06-22 23:33
> and I don't know the priority

I *really* need you to do ecosystem namespaces @mcg1969 :-/

**Comment by mcg1969** [comment] 2016-06-22 23:57
Well yes, that I know. :-)

**Comment by scienceopen** [comment] 2016-08-23 19:46
There is a very long-standing "bug" that if "dateutil" is in your requirements.txt, you will get conflict with python3.5* on the first line in requirements.txt, no matter what that line is.

Switch to python-dateutil and this weird bug disappears. Happens with Python 3.4 and 3.5 for over a year at least.

**Comment by scivision** [comment] 2017-05-08 18:36
@kalefranz was this fixed in a particular conda version?

**Comment by kalefranz** [comment] 2017-05-08 18:40
This should be fixed in recent versions of conda 4.3. Latest is 4.3.17.

**Comment by scivision** [comment] 2017-05-08 18:42
Thank you that will be very helpful to those reaching this page by search engine!

**Comment by kalefranz** [comment] 2017-05-09 02:04
Looking back again at this issue... I'm going to re-open it (sorry).  We fixed another issue that had to do with python-dateutil vs. datutil in conda-env environment.yml files.  I thought this ticket was a duplicate of that issue.  Reading back over it again, I don't think that's the case.

**Comment by kalefranz** [comment] 2017-05-09 02:06
@scivision is there a reason you use `dateutil` instead of `python-dateutil`?  There isn't a `dateutil` package even listed on PyPI https://pypi.python.org/pypi/dateutil/.  There probably used to be.  I'm guessing the PyPA folks just nixed it though.  It's all the same package at this point, and the official name is `python-dateutil`.

**Comment by scivision** [comment] 2017-05-09 02:08
Oops thanks @kalefranz I didn't recheck this. A couple years ago was probably the last time I used `pip install dateutil` so I was using outdated package name!

**Comment by kalefranz** [comment] 2017-05-09 02:08
For history, repo.continuum.io started packaging `python-dateutil` just as `dateutil`.  At some point, we migrated the name to be consistent with the PyPI name.  However, I think we left the old `dateutil` packages in the repo so we didn't break people who were already using them.

That said, I almost want to close this issue again, now that there's a record and it's googlable.

The correct fix is to use `python-dateutil` instead of `dateutil`.

**Comment by scivision** [comment] 2017-05-09 02:09
Perfect sleuthing work @kalefranz thanks!!

**Closed** 2017-05-09 02:30 UTC
