### ISSUE TITLE
conda install fails after cloning the root env (conda-env leaks into the new env)

### ISSUE THREAD

**Issue by mahmoud** [conda/conda#4076] opened 2016-12-15 01:49 UTC
Two in a day! :)

On a fresh install of Linux x64 Anaconda, I cloned the root env like so:

`$ ~/anaconda2/bin/conda create --name sk1 --clone root`

Then I went to install a package, and I saw:

```
$ conda install -c conda-forge pylibmc==1.5.1
Fetching package metadata .........
Solving package specifications: ..........


InstallError: Install error: Error: one or more of the packages already installed depend on 'conda'
and should only be installed in the root environment: conda-env
These packages need to be removed before conda can proceed.
```

Maybe there should be a special case to not clone over `conda-env`?

**Comment by mahmoud** [comment] 2016-12-15 01:50
(note that I can `conda uninstall conda-env` and proceed as normal)

**Comment by kalefranz** [comment] 2016-12-15 02:10
Ugg. At least conda-env is tested and versioned along with conda at this point. 

I feel like the second time around I have the option to ask if it's fixed in 4.3.0. 

    conda config --add channels conda-canary
    conda update conda

Just don't want to chase bugs that have already been fixed. But also now that 4.3 is in canary, I have some bandwidth to tackle some outstanding issues that need attention.

**Comment by mahmoud** [comment] 2016-12-15 19:24
Ah! Yes, this does seem to be address:

```
$ ~/anaconda2/bin/conda create --name test1 --clone root
Source:      /Users/mahmoud/anaconda2
Destination: /Users/mahmoud/anaconda2/envs/test1
The following packages cannot be cloned out of the root environment:
 - conda-4.3.0-py27_1
 - conda-build-2.0.2-py27_0
 - conda-env-2.6.0-0
Packages: 192
Files: 5
Fetching package metadata ...........
(...)
```

However, the install that worked (once I removed conda-env) last time, ran into a strange (unrelated?) error with 4.3.0:

```
$ source activate test1
(test1) mahmoud:~ $ conda install -c conda-forge pylibmc
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/mahmoud/anaconda2/envs/test1:

The following NEW packages will be INSTALLED:

    libmemcached: 1.0.18-0     conda-forge
    pylibmc:      1.5.1-py27_0 conda-forge

Proceed ([y]/n)? y

mahmoud 100% |############################################################| Time: 0:00:00   1.16 MB/s
mahmoud 100% |############################################################| Time: 0:00:00  17.10 MB/s
ERROR conda.core.link:_execute_actions(223): Something bad happened, but it's okay because I'm going to roll back now.


ClobberError: Conda no longer clobbers existing files without the use of the --force option.
  source path:      /Users/mahmoud/anaconda2/pkgs/libmemcached-1.0.18-0/bin/activate
  destination path: /Users/mahmoud/anaconda2/envs/test1/bin/activate
```

Should the libmemcached activate really be overwriting my env activate? If so, should it be generating this error? If it is as unrelated as it seems to be, I can create another issue :)

**Comment by mahmoud** [comment] 2016-12-15 19:25
(Also, congrats on 1000 🌟s!)

**Comment by kalefranz** [comment] 2016-12-17 06:08
Ok so the ClobberError looks like expected behavior, and looks like it's working exactly as it should.  That's because that conda-forge libmemcached package is jacked.

```
kfranz@0283:~/continuum/conda *more-link-pre ❯ head /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/pkgs/libmemcached-1.0.18-0/info/files
bin/activate
bin/conda
bin/deactivate
bin/memcapable
bin/memcat
...
```

and 

```
kfranz@0283:~/continuum/conda *more-link-pre ❯ ls -al  /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/pkgs/libmemcached-1.0.18-0/bin
total 928
drwxr-xr-x  18 kfranz  admin   612B Dec 17 00:01 ./
drwxr-xr-x   7 kfranz  admin   238B Dec 17 00:01 ../
lrwxr-xr-x   1 kfranz  admin    37B Dec 17 00:01 activate@ -> /Users/travis/miniconda3/bin/activate
lrwxr-xr-x   1 kfranz  admin    34B Dec 17 00:01 conda@ -> /Users/travis/miniconda3/bin/conda
lrwxr-xr-x   1 kfranz  admin    39B Dec 17 00:01 deactivate@ -> /Users/travis/miniconda3/bin/deactivate
-rwxr-xr-x   1 kfranz  admin    94K Jun 21 09:25 memcapable*
-rwxr-xr-x   1 kfranz  admin    28K Jun 21 09:25 memcat*
-rwxr-xr-x   1 kfranz  admin    32K Jun 21 09:25 memcp*
```

It should absolutely not have those files listed in the manifest, or those symlinks in the conda package tarball.

Actually.... If this were to succeed, it would be a case where conda appears to uninstall itself.  Looks like I'm getting some validation that we're fixing this several-year-old issue finally.

I'm going to file an issue on the conda-forge feedstock for you.

**Comment by kalefranz** [comment] 2016-12-17 06:12
(Yes, I use homebrew python when I'm developing on conda. Feel like it's generally best not to cross streams.  Not to have conda development depend on and roll back over on itself.)

**Closed** 2016-12-17 06:12 UTC

**Comment by mahmoud** [comment] 2016-12-17 06:34
Excellent! Just what I was hoping to hear. Thanks for all the great work!
