### ISSUE TITLE
conda 4.7.10 cannot install packages, make new envs, or update since update and removal of env 

### ISSUE THREAD

**Issue by mikeWShef** [conda/conda#9003] opened 2019-07-26 11:34 UTC
## Current Behavior

trying to update, etc. the environment is solved, but when the packages are getting downloaded I get a popup windows error:
python.exe - Entry Point Not Found
The procedure entry point OPENSSL_sk_new_reserve could not be located in the dynamic link library XXXXX\Anaconda3\Library\bin\libssl-1_1-x64.dll

### Steps to Reproduce

I don't know if this is minimal as my conda distribution is unusable. The only thing I did with conda was deleting an envrionment using the command:
conda remove --name myenv --all
As suggested in the help page here:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment
I have not been digging into any program files etc. and installed a package yesterday with no issues. 
```
(base) C:\Users\XXXXX>conda create -n slippy python=3.7
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\XXXXX\.conda\envs\slippy

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-19.1.1                 |           py37_0         1.8 MB
    python-3.7.3               |       h8c8aaf0_1        17.8 MB
    setuptools-41.0.1          |           py37_0         680 KB
    vs2015_runtime-14.15.26706 |       h3a45250_4         2.4 MB
    wheel-0.33.4               |           py37_0          57 KB
    ------------------------------------------------------------
                                           Total:        22.7 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2019.5.15-0
  certifi            pkgs/main/win-64::certifi-2019.6.16-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1c-he774522_1
  pip                pkgs/main/win-64::pip-19.1.1-py37_0
  python             pkgs/main/win-64::python-3.7.3-h8c8aaf0_1
  setuptools         pkgs/main/win-64::setuptools-41.0.1-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.29.0-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.15.26706-h3a45250_4
  wheel              pkgs/main/win-64::wheel-0.33.4-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
wheel-0.33.4         | 57 KB     |                                                                              |   0%
python-3.7.3         | 17.8 MB   |                                                                              |   0%
vs2015_runtime-14.15 | 2.4 MB    |                                                                              |   0%
pip-19.1.1           | 1.8 MB    |                                                                              |   0%
setuptools-41.0.1    | 680 KB    |                                                                              |   0%

[WinError 127] The specified procedure could not be found
[WinError 127] The specified procedure could not be found
[WinError 127] The specified procedure could not be found
[WinError 127] The specified procedure could not be found
[WinError 127] The specified procedure could not be found


(base) C:\Users\XXXXX>
```

## Expected Behavior

Commands should execute without pop up errors

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\44779\.condarc
 populated config files : C:\Users\44779\.condarc
          conda version : 4.7.10
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       virtual packages : __cuda=10.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\44779\.conda\pkgs
                          C:\Users\44779\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\44779\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\44779\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\44779\.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
alabaster                 0.7.11                   py37_0    defaults
anaconda                  5.3.0                    py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.2                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
appdirs                   1.4.3            py37h28b3542_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.0.4                    py37_0    defaults
astropy                   3.0.4            py37hfa6e2cd_0    defaults
atomicwrites              1.2.1                    py37_0    defaults
attrs                     18.2.0           py37h28b3542_0    defaults
automat                   0.7.0                    py37_0    defaults
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
beautifulsoup4            4.6.3                    py37_0    defaults
bitarray                  0.8.3            py37hfa6e2cd_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py37_0    defaults
bleach                    2.1.4                    py37_0    defaults
blosc                     1.14.4               he51fdeb_0    defaults
bokeh                     0.13.0                   py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h452e1ab_1    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2019.5.15                     0    defaults
certifi                   2019.6.16                py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     6.7                      py37_0    defaults
cloudpickle               0.5.5                    py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.3.9                    py37_0    defaults
comtypes                  1.1.7                    py37_0    defaults
conda                     4.7.10                   py37_0    defaults
conda-build               3.15.1                   py37_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-package-handling    1.3.11                   py37_0    defaults
console_shortcut          0.1.1                         3    defaults
constantly                15.1.0           py37h28b3542_0    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.7              py37h7a1dbc1_0    defaults
curl                      7.65.2               h2a8f88b_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.28.5           py37h6538335_0    defaults
cytoolz                   0.9.0.1          py37hfa6e2cd_1    defaults
dask                      0.19.1                   py37_0    defaults
dask-core                 0.19.1                   py37_0    defaults
datashape                 0.5.4                    py37_1    defaults
decorator                 4.3.0                    py37_0    defaults
defusedxml                0.5.0                    py37_1    defaults
distributed               1.23.1                   py37_0    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.2.3                    py37_2    defaults
et_xmlfile                1.0.1                    py37_0    defaults
fastcache                 1.0.2            py37hfa6e2cd_2    defaults
filelock                  3.0.8                    py37_0    defaults
flask                     1.0.2                    py37_1    defaults
flask-cors                3.0.6                    py37_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.3.6            py37hfa6e2cd_0    defaults
glob2                     0.6                      py37_0    defaults
greenlet                  0.4.15           py37hfa6e2cd_0    defaults
h5py                      2.8.0            py37h3bdd7fb_2    defaults
hdf5                      1.10.2               hac2f561_1    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
hyperlink                 18.0.0                   py37_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.7                      py37_0    defaults
imageio                   2.4.1                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
incremental               17.5.0                   py37_0    defaults
intel-openmp              2019.0                      118    defaults
ipykernel                 4.10.0                   py37_0    defaults
ipython                   6.5.0                    py37_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.1                    py37_0    defaults
isort                     4.3.4                    py37_0    defaults
itsdangerous              0.24                     py37_1    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.12.1                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.3                    py37_0    defaults
jupyter_console           5.2.0                    py37_1    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.34.9                   py37_0    defaults
jupyterlab_launcher       0.13.1                   py37_0    defaults
keyring                   13.2.1                   py37_0    defaults
kiwisolver                1.0.1            py37h6538335_0    defaults
krb5                      1.16.1               hc04afaa_7    defaults
lazy-object-proxy         1.3.1            py37hfa6e2cd_2    defaults
libarchive                3.3.3                h0643e63_5    defaults
libcurl                   7.65.2               h2a8f88b_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.2                h7a1dbc1_0    defaults
libtiff                   4.0.9                h36446d0_2    defaults
libxml2                   2.9.8                hadb2253_1    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.24.0           py37h6538335_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.2.5            py37hef2cd61_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0              py37hfa6e2cd_1    defaults
matplotlib                2.2.3            py37hd159220_0    defaults
mccabe                    0.6.1                    py37_1    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
mistune                   0.8.3            py37hfa6e2cd_1    defaults
mkl                       2019.0                      118    defaults
mkl-service               1.1.2            py37hb217b18_5    defaults
mkl_fft                   1.0.4            py37h1e22a9b_1    defaults
mkl_random                1.0.1            py37h77b88f5_1    defaults
more-itertools            4.3.0                    py37_0    defaults
mpmath                    1.0.0                    py37_2    defaults
msgpack-python            0.5.6            py37he980bc4_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.4.0                    py37_1    defaults
nbformat                  4.4.0                    py37_0    defaults
networkx                  2.1                      py37_0    defaults
nltk                      3.3.0                    py37_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.6.0                    py37_0    defaults
numba                     0.39.0           py37h830ac7b_0    defaults
numexpr                   2.6.8            py37h9ef55f4_0    defaults
numpy                     1.15.1           py37ha559c80_0    defaults
numpy-base                1.15.1           py37h8128ebf_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
odo                       0.5.1                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.5.6                    py37_0    defaults
openssl                   1.1.1c               he774522_1    defaults
packaging                 17.1                     py37_0    defaults
pandas                    0.23.4           py37h830ac7b_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.1                    py37_0    defaults
partd                     0.3.8                    py37_0    defaults
path.py                   11.1.0                   py37_0    defaults
pathlib2                  2.3.2                    py37_0    defaults
patsy                     0.5.0                    py37_0    defaults
pep8                      1.7.1                    py37_0    defaults
pickleshare               0.7.4                    py37_0    defaults
pillow                    5.2.0            py37h08bbbbd_0    defaults
pip                       10.0.1                   py37_0    defaults
pkginfo                   1.4.2                    py37_1    defaults
pluggy                    0.7.1            py37h28b3542_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.3.1            py37h28b3542_0    defaults
prompt_toolkit            1.0.15                   py37_0    defaults
psutil                    5.4.7            py37hfa6e2cd_0    defaults
py                        1.6.0                    py37_0    defaults
pyasn1                    0.4.4            py37h28b3542_0    defaults
pyasn1-modules            0.2.2                    py37_0    defaults
pycodestyle               2.4.0                    py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.18                     py37_1    defaults
pycrypto                  2.6.1            py37hfa6e2cd_9    defaults
pycurl                    7.43.0.3         py37h7a1dbc1_0    defaults
pyflakes                  2.0.0                    py37_0    defaults
pygments                  2.2.0                    py37_0    defaults
pylint                    2.1.1                    py37_0    defaults
pyodbc                    4.0.24           py37h6538335_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pyparsing                 2.2.0                    py37_1    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pysocks                   1.6.8                    py37_0    defaults
pytables                  3.4.4            py37he6f6034_0    defaults
pytest                    3.8.0                    py37_0    defaults
pytest-arraydiff          0.2              py37h39e3cac_0    defaults
pytest-astropy            0.4.0                    py37_0    defaults
pytest-doctestplus        0.1.3                    py37_0    defaults
pytest-openfiles          0.3.0                    py37_0    defaults
pytest-remotedata         0.3.0                    py37_0    defaults
python                    3.7.0                hea74fb7_0    defaults
python-dateutil           2.7.3                    py37_0    defaults
python-libarchive-c       2.8                     py37_11    defaults
pytz                      2018.5                   py37_0    defaults
pywavelets                1.0.0            py37h452e1ab_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.4                    py37_0    defaults
pyyaml                    3.13             py37hfa6e2cd_0    defaults
pyzmq                     17.1.2           py37hfa6e2cd_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.4.4                    py37_0    defaults
qtconsole                 4.4.1                    py37_0    defaults
qtpy                      1.5.0                    py37_0    defaults
requests                  2.19.1                   py37_0    defaults
rope                      0.11.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
scikit-image              0.14.0           py37h6538335_1    defaults
scikit-learn              0.19.2           py37heebcf9a_0    defaults
scipy                     1.1.0            py37h4f6bf74_1    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
service_identity          17.0.0           py37h28b3542_0    defaults
setuptools                40.2.0                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.11.0                   py37_1    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.0.1                    py37_0    defaults
sortedcontainers          2.0.5                    py37_0    defaults
sphinx                    1.7.9                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.1                    py37_1    defaults
spyder-kernels            0.2.6                    py37_0    defaults
sqlalchemy                1.2.11           py37hfa6e2cd_0    defaults
sqlite                    3.29.0               he774522_0    defaults
statsmodels               0.9.0            py37h452e1ab_0    defaults
sympy                     1.1.1                    py37_0    defaults
tblib                     1.3.2                    py37_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.3.1                    py37_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   5.1              py37hfa6e2cd_0    defaults
tqdm                      4.26.0           py37h28b3542_0    defaults
traitlets                 4.3.2                    py37_0    defaults
twisted                   18.7.0           py37hfa6e2cd_1    defaults
unicodecsv                0.14.1                   py37_0    defaults
urllib3                   1.23                     py37_0    defaults
vboxapi                   1.0                      pypi_0    pypi
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.31.1                   py37_0    defaults
widgetsnbextension        3.4.1                    py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
win_unicode_console       0.5                      py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py37hfa6e2cd_2    defaults
xlrd                      1.1.0                    py37_1    defaults
xlsxwriter                1.1.0                    py37_0    defaults
xlwings                   0.11.8                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.2.5                he025d50_1    defaults
zict                      0.1.3                    py37_0    defaults
zlib                      1.2.11               h8395fce_2    defaults
zope                      1.0                      py37_1    defaults
zope.interface            4.5.0            py37hfa6e2cd_0    defaults
zstd                      1.3.7                h508b16e_0    defaults
```
</p></details>

**Comment by nernst** [comment] 2019-07-30 14:24
I'm running into the same issue. Started just this morning after I updated conda to 4.7.10 from 4.5.x. My conda info shows largely the same as above, excepting I don't appear to have conda-build installed and, of course, user paths.

**Comment by mikeWShef** [comment] 2019-07-30 14:55
It's pretty inconvenient hey, I managed to 'fix' it by uninstalling and reinstalling anaconda but pycharm didn't keep up and now my envs are all over the place.

**Comment by msarahan** [comment] 2019-07-30 15:20
I'm not sure what is causing the issue, but you may be able to recover using the standalone conda executables at https://repo.anaconda.com/pkgs/misc/conda-execs/

These use pyinstaller to create a self-contained conda.  It's not fully functional - no `conda init` - but it can be useful to repair broken environments.

For example, to force reinstallation of openssl:

``conda-latest-win-64.exe install -f -p <path to broken env> openssl``

We'll try to reproduce the issue, but unfortunately these are often very dependent on your system state and hard to reproduce.

**Comment by SimonCarozza** [comment] 2019-07-30 16:44
I had the same issue. I found libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.

**Comment by atapano** [comment] 2019-07-30 21:53
SimonCarozza, that worked perfectly for me and I'm finally able to run conda update. Thank you!

**Comment by nernst** [comment] 2019-08-01 03:16
For me, I think the corruption occurred when I uninstalled the matplotlib
package. I dont have the list on hand, but it wanted to remove around 20
"unused" packages. I think I remember some ssl packages being mentioned.

When I was recreating our environment from a fresh install today, I noticed
a number of packages fighting over which version of openssl to use (why
Python packages dont use the ssl lib is beyond me).  I'm not familiar with
the modules installed. I'm just trying to get everything to work together
for our quant team.

I will try and reproduce tomorrow when I'm in the office, but I suspect its
removing a package dependent upon ssl that wanted a different version than
the stock as I supplied by Python. Also, PATH precedence seems to play a
role as well.

**Comment by SimoneGenta** [comment] 2019-08-01 08:43
I updated conda inside an environment and had the same behaviour. 
SimonCarozza solution works great.

**Comment by ceg-gha** [comment] 2019-08-01 13:44
SimonCarozza solution worked for me too, thanks!

**Comment by xuemind** [comment] 2019-08-02 05:09
SimonCarozza solution worked for me too, thanks!

**Comment by jhliu17** [comment] 2019-08-03 10:06
Thanks, SimonCarozza! Your solution worked for me too!

**Comment by guoanby** [comment] 2019-08-04 10:29
> I had the same issue.
> 
> I found out libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.
> 
> Hope it helps.

awesome！ How do you find this?

**Comment by subhroisback** [comment] 2019-08-05 10:10
Thanks, SimonCarozza! It worked for me too!

**Comment by iboates** [comment] 2019-08-05 14:55
SimonCarozza's fix did not help me, the environment was correctly installed, but now it can no longer download any packages:

`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")'`

**Comment by msarahan** [comment] 2019-08-06 14:50
moving libssl dlls around like that is really not advisable.  Those DLLs are duplicated because you have something fishy going on in your packages.  There should not be any openssl DLLs in the DLLs folder.  They should be in Library/bin.  The fact that you have them there means that the package for python that you've installed is inconsistent with the openssl package that you have installed.  Maybe you got python from conda-forge or somewhere else?

When you copy DLLs around yourself, you might luck into the right (newest) files being put where they are needed.  If you have bad luck, you break things by replacing the newer file with the older one, like @iboates is seeing.

The fundamental problem here is that the python package you're using should not vendor openssl DLLs.

**Comment by rwhitt2049** [comment] 2019-08-08 20:30
FWIW, I got the same error as OP immediately after I upgraded conda from 4.7.5 to 4.7.10. The workaround from @SimonCarozza fixed my issue and I deleted my miniconda/DLLs/libssl-1_1-x64.dll as per the comment from @msarahan  above.

I was trying to do a conda install into a known good environment when I got the error.

My environment information is identical to what I documented in a previous issue: https://github.com/conda/conda/issues/9060

**Comment by vidartf** [comment] 2019-08-09 14:14
Had the same issue. No idea how this got so broken. Following @SimonCarozza solution solved it. No idea which package was the source.

**Comment by richdevboston** [comment] 2019-08-10 21:08
I have the same issue with Matplotlib update.  The solution from @SimonCarozza solution solved the blocking error ```![image](https://user-images.githubusercontent.com/9345711/62826831-d2554880-bb90-11e9-9676-570774d6f950.png)```, so now I can update my environment.  But I still have the problem with Matplotlib.  

I introduced the inconsistency by using PIP sometimes and CONDA at other times.  PIP and conda need to be merged.  Pip doesn't do consistency checking, which is a HUGE problem.  I try to stay away from pip but there are many packages that don't have conda packages.  

The problem is that it is not SIMPLE to convert a pip package to a conda package.  I don't know enough about the two package formats to be able to create a converter, but a converter is badly needed.  

The community needs to agree to merge the functions of pip and conda or provide a simple and automatic solution to convert between the two.

**Comment by fjprobos** [comment] 2019-08-12 16:20
> I had the same issue.
> 
> I found out libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.
> 
> Hope it helps.

This worked perfect for me.

**Comment by drafter250** [comment] 2019-08-14 14:59
> moving libssl dlls around like that is really not advisable. Those DLLs are duplicated because you have something fishy going on in your packages. There should not be any openssl DLLs in the DLLs folder. They should be in Library/bin. The fact that you have them there means that the package for python that you've installed is inconsistent with the openssl package that you have installed. Maybe you got python from conda-forge or somewhere else?
> 
> When you copy DLLs around yourself, you might luck into the right (newest) files being put where they are needed. If you have bad luck, you break things by replacing the newer file with the older one, like @iboates is seeing.
> 
> The fundamental problem here is that the python package you're using should not vendor openssl DLLs.

So i just cut the libssl-1_1-x64.dll from the DLLs folder since you said it shouldn't be in there and expected everything to work. however conda instead told me it couldnt find the ssl module instead.

>
>
>

Therefore it seems on the surface to me, conda is instead looking for the ssl module in the wrong location.

**Comment by drafter250** [comment] 2019-08-14 15:58
I bet this PR caused it https://github.com/conda/conda/pull/8949

**Comment by YK-NY** [comment] 2019-08-22 21:51
I did what drafter250 did (removed the libssl-1_1-x64.dll from under DLLs and copied to a temp location) and conda install gives an SSL error.

**Comment by sennendoko** [comment] 2019-09-03 16:48
I just found a solution to this, more or less by accident; I don't libssl-1_1-x64.dll in my DLLs directory for some reason, so couldn't use Simon's solution. So instead:

1) conda install git
2) in C:\ProgramData\Anaconda3 or wherever you installed it, copy pkgs\git-2.20.1-h6bb4b03_0\Library\mingw64\bin\libssl-1_1-x64.dll across to Library\bin\libssl-1_1-x64.dll
3) start a new Anaconda Prompt, and everything works OK (for me)

**Comment by tolga-balci** [comment] 2019-09-20 19:42
Same issue here.
While Simon's workaround is brilliant and worked for some people, I would not do this on my laptop. Dll files should be where they are and should not be copied around. You may never know when/where the application look for the newer dlls, when the dlls become obsolete etc.
I believe this should be fixed with the next release. If this issue happened now and is not resolved, it will carry on to the next releases and we will be left with a conda installation that is not updating.

**Comment by jenniferchiang** [comment] 2019-09-26 05:56
SimonCarozza, It's amazing! The conda finally works! thanks a lot!

**Comment by Saderius** [comment] 2019-10-01 00:17
> I had the same issue.
> 
> I found out libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.
> 
> Hope it helps.

You are true hero we all need!

**Comment by jamessong** [comment] 2019-10-05 23:58
Now I followed the same trick as last time, but the problem comes back again ... This is sick

**Comment by raqui23** [comment] 2019-10-08 05:59
> I had the same issue.
> 
> I found out libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.
> 
> Hope it helps.

This really worked for me. I advice others to follow the same steps as above

**Comment by LingrenKong** [comment] 2019-10-12 10:46
> I had the same issue.
> 
> I found out libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.
> 
> Hope it helps.

Thanks. It really worked.

**Comment by Aicha28** [comment] 2019-10-18 16:48
Thanks, SimonCarozza! Your solution worked perfectly !!

**Comment by jamessong** [comment] 2019-10-18 17:59
it doesn't matter, the problem will come back again when you update other packages. That is what I said, the conda or anaconda is hindering python adoption

**Comment by AdityaJakkam** [comment] 2019-10-18 20:22
> I had the same issue.
> 
> I found out libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.
> 
> Hope it helps.

Thank you! It worked like charm

**Comment by elikapati** [comment] 2019-10-22 10:04
Thank you, SimonCarozza. Your solution worked for me.

**Comment by KingDarBoja** [comment] 2019-10-30 19:32
I do find the same error after updating/installing new packages, of course, the provided solution works but it is pretty annoying to keep copying the same file over and over without taking into account the possible side-effects of doing it (which I haven't faced yet).

**Comment by digitalstephen** [comment] 2019-11-01 06:06
I have miniconda installed on Windows 10, and not Anaconda.  The libssl-1_1 file is not found anywhere on my machine.  Even if I had it, I'm not sure I'd want to move it, seeing that some people are continually having this problem and having to copy the file repeatedly.

Is there any other recommended solution?  I can't use conda update and I can't install other packages.  The miniconda installer page says not to use it if you have an older version of miniconda installed already, but to use conda update instead.  There does not seem to be a clean way to uninstall and reinstall miniconda.  I'm at a bit of a loss.

**Comment by KingDarBoja** [comment] 2019-11-01 23:45
What I did on Windows 10:
- Uninstall Anaconda.
- Uninstall any other Python version.
- Uninstall PyCharm (It isn't needed but just wanted to make a fresh install too).
- Remove any Python/Anaconda folder on Program Data.
- Remove any Enviroment Variable inside PATH.
- Restart PC.
- Install Anaconda (or Miniconda if you want). At this point, **DO NOT** add it to the PATH variable. Use anaconda prompt (and miniconda equivalent) for handling virtual enviroment and running scripts.
- Create new virtual enviroments.

So be sure to activate the virtual enviroment for the desired project in order to install packages and don't mess with the base one.

It is better to make fresh install

Cheers!

**Comment by shubhamsaininnl** [comment] 2019-11-08 06:03
Thank you Simon Carozza. Your solution is best.

**Comment by Krogsager** [comment] 2019-11-12 10:12
> 
> 
> I'm not sure what is causing the issue, but you may be able to recover using the standalone conda executables at https://repo.anaconda.com/pkgs/misc/conda-execs/
> 
> These use pyinstaller to create a self-contained conda. It's not fully functional - no `conda init` - but it can be useful to repair broken environments.
> 
> For example, to force reinstallation of openssl:
> 
> `conda-latest-win-64.exe install -f -p <path to broken env> openssl`
> 

I tried the command to reinstal openssl but an error occurs and a report is prepared.
```
"site-packages\libarchive\ffi.py", line 53, in <module> 
ImportError: Failed to find libarchive library
```

**Comment by AbishekAnbarasan** [comment] 2019-11-13 01:17
> 
> 
> I had the same issue.
> 
> I found out libssl-1_1-x64 dlls in Anaconda/DLLS and Anaconda/Library/bin being installed at different dates, so, as an experiment, I copied the one in Anaconda/DLLS and replaced that in Anaconda/Library/bin and conda started working again, at least for now - I could install new packages again.
> 
> Hope it helps.

Amazing, thanks simon carroza

**Comment by ckcampbell248** [comment] 2019-11-13 17:52
Confirming that replacing the libssl dll in the Anaconda/Library/bin folder with the one from Anaconda/DLLs resolved the issue. The original in Library/bin was dated 10/16/2019. The one I replaced it with is dated 6/28/2018. I'm running conda version 4.7.12 on Windows 10 Enterprise.

**Comment by msarahan** [comment] 2019-11-13 18:05
As stated before:

moving libssl dlls around like that is really not advisable. Those DLLs are duplicated because you have something fishy going on in your packages. There should not be any openssl DLLs in the DLLs folder. They should be in Library/bin. The fact that you have them there means that the package for python that you've installed is inconsistent with the openssl package that you have installed. Maybe you got python from conda-forge or somewhere else?

When you copy DLLs around yourself, you might luck into the right (newest) files being put where they are needed. If you have bad luck, you break things by replacing the newer file with the older one.  Regardless, as time goes on, you're almost certain to break, as newer software requires newer libraries than the one you've manually copied.

The fundamental problem here is that the python package you're using should not vendor openssl DLLs, and that you need to be activating your environments.  There's info here: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment

If you really can't activate your env (by using Anaconda Prompt or otherwise), try setting this env var:

CONDA_DLL_SEARCH_MODIFICATION_ENABLE

With a value of 1. Our python interpreter adds more paths when you enable that. We call it "hacktivation". It might help with finding openssl.

https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

Locking this issue to prevent bottom-posting making this information harder to find.

**Closed by msarahan** 2019-11-13 18:05 UTC
