### ISSUE TITLE
Unexpected downgrade when updating

### ISSUE THREAD

**Issue by pitrou** [conda/conda#2052] opened 2016-02-10 11:30 UTC
I get the following on one of my environments:
```
$ conda update --all
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ............................................................................
Package plan for installation in environment /home/antoine/35:

The following NEW packages will be INSTALLED:

    mkl-rt:       11.1-p0            

The following packages will be DOWNGRADED:

    numexpr:      2.5-np110py35_0    --> 2.4.4-np110py35_p0  [mkl]
    numpy:        1.10.4-py35_0      --> 1.10.2-py35_p0      [mkl]
    scikit-learn: 0.17-np110py35_2   --> 0.17-np110py35_p1   [mkl]
    scipy:        0.17.0-np110py35_1 --> 0.16.1-np110py35_p0 [mkl]

Proceed ([y]/n)? n
```

**Comment by MSeifert04** [comment] 2016-02-12 19:23
I have the same problem. OS: Windows10 64-bit, Python:3.5, Anaconda: 2.5.

**Comment by alanhdu** [comment] 2016-02-16 17:00
I can also reproduce, but with Linux and Python 3.4 (so not Python 3.5 only).

**Comment by jhoblitt** [comment] 2016-02-19 21:15
I think I've seen the same issue occur when no changes should happen at all.

```
$ conda --version
conda 3.19.3
$ conda install -y 'conda-build!=1.18.2'
Fetching package metadata: ....
Solving package specifications: ...................
Package plan for installation in environment /home/conda/conda-lsst/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.10              |                2        12.0 MB

The following packages will be DOWNGRADED:

    python: 2.7.11-0 --> 2.7.10-2

```

**Comment by kalefranz** [comment] 2016-02-19 21:33
The github.com/conda/conda master branch is slated for a 4.0 release.  We
are working through a full revamp of our solver to fix issues just like
this.

On Fri, Feb 19, 2016 at 3:15 PM, Joshua Hoblitt <notifications@github.com>
wrote:

> I think I've seen the same issue occur when no changes should happen at
> all.
>
> $ conda --version
> conda 3.19.3
> $ conda install -y 'conda-build!=1.18.2'
> Fetching package metadata: ....
> Solving package specifications: ...................
> Package plan for installation in environment /home/conda/conda-lsst/miniconda:
>
> The following packages will be downloaded:
>
>     package                    |            build
>     ---------------------------|-----------------
>     python-2.7.10              |                2        12.0 MB
>
> The following packages will be DOWNGRADED:
>
>     python: 2.7.11-0 --> 2.7.10-2
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/2052#issuecomment-186410172>.
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Comment by MSeifert04** [comment] 2016-03-05 12:10
With conda 4.0 it still wants to downgrade ``numexpr`` (though it doesn't want to downgrade the other mentioned packages anymore).

Since ``numexpr 2.4.6`` and ``numexpr 2.5`` do work with my ``mkl`` version it is very strange my environment always wants to downgrade it:

```
The following packages will be DOWNGRADED:

    numexpr:   2.5-np110py27_0    --> 2.4.6-np110py27_1
```

(Windows 10, conda 4.0, python 2.7 and python 3.5)

**Comment by mcg1969** [comment] 2016-03-05 16:33
Can you give us the exact starting environment (`conda list`), the exact update command (`conda update` perhaps?) and the full output of `conda`?

This is curious indeed, since those two particular builds of `numexpr` have the same dependencies. The only thing I can think of is that something else in your environment is depending on the older version of `numexpr`. 

It's certainly an area of future development to attach to each undesirable event like a downgrade some sort of explanation about the underlying  _cause_. In my efforts to revamp the solver I've found conda _often_ does non-intuitive things---and it's often the fault of the metadata, not the solver. That said, this is a major solver revamp, so it's possible there are bugs.

**Comment by MSeifert04** [comment] 2016-03-06 22:26
@mcg1969 - I've tried to replicate the error in a fresh environment but it worked fine there so it's probably a problem with a manually installed package. Is there a way to find out which package might be the problem or should I just post all my installed packages?

**Comment by mcg1969** [comment] 2016-03-06 23:15
I think it would be most helpful to post the full outputs as I have suggested previously. Clean environments are frankly the easy case :-) Now that conda is trying to be strict about preserving consistency in environments, our greatest challenges are gracefully handling broken environments and providing helpful hints and explanations about what is going on.

I should also point out that issue #2179 has proven to cause some of the problems others are seeing, so that may be the case here too. If so, we have a fix ready to go for 4.0.1, which will likely be pushed out tomorrow.

**Comment by MSeifert04** [comment] 2016-03-06 23:48
Sorry I just wanted to ask again because I have a lot of packages installed over the time:

```
[Anaconda] C:\Users\Admin>conda list
# packages in environment at C:\Programming\Anaconda:
#
alabaster                 0.7.7                    py35_0    defaults
anaconda-client           1.2.2                    py35_0    defaults
aplpy                     1.0                      py35_0    astropy
argcomplete               1.0.0                    py35_1    <unknown>
astropy                   1.1.dev14686              <pip>
astropy-helpers           1.1.1                    py35_0    astropy
astroquery                0.3.1                    py35_0    astropy
astroscrappy              1.0.3               np110py35_0    astropy
babel                     2.2.0                    py35_0    defaults
beautifulsoup4            4.4.1                    py35_0    <unknown>
bitarray                  0.8.1                    py35_1    <unknown>
blaze                     0.9.0                     <pip>
blaze-core                0.9.0                    py35_0    defaults
bokeh                     0.11.1                   py35_0    defaults
boto                      2.39.0                   py35_0    defaults
bottleneck                1.0.0               np110py35_0    defaults
bzip2                     1.0.6                    vc14_2  [vc14]  <unknown>
ccdproc                   0.3.3                    py35_0    astropy
cffi                      1.2.1                    py35_0    <unknown>
chest                     0.2.3                    py35_0    defaults
cloudpickle               0.1.1                    py35_0    defaults
clyent                    1.2.1                    py35_0    defaults
colorama                  0.3.6                    py35_0    defaults
comtypes                  1.1.2                    py35_0    <unknown>
conda                     4.0.0                    py35_0    defaults
conda-build               1.19.0                   py35_0    defaults
conda-env                 2.4.5                    py35_0    defaults
configobj                 5.0.6                    py35_0    <unknown>
console_shortcut          0.1.1                    py35_1    <unknown>
coverage                  4.0.3                    py35_0    defaults
cryptography              1.0.2                    py35_0    <unknown>
curl                      7.45.0                   vc14_1  [vc14]  defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.23.4                   py35_0    <unknown>
cytoolz                   0.7.5                    py35_0    defaults
dask                      0.8.0                    py35_0    defaults
datashape                 0.5.1                    py35_0    defaults
decorator                 4.0.9                    py35_0    defaults
dill                      0.2.4                    py35_0    defaults
docutils                  0.12                     py35_1    <unknown>
dynd                      f641248                   <pip>
dynd-python               0.7.1                    py35_0    defaults
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py35_0    defaults
execnet                   1.3.0                    py35_1    defaults
fastcache                 1.0.2                    py35_0    <unknown>
flask                     0.10.1                   py35_1    <unknown>
freetype                  2.5.5                    vc14_0  [vc14]  <unknown>
ginga                     2.5.20151230025145          py35_0    astropy
greenlet                  0.4.9                    py35_0    <unknown>
h5py                      2.5.0               np110py35_4    <unknown>
hdf5                      1.8.15.1                 vc14_4  [vc14]  defaults
heapdict                  1.0.0                    py35_0    defaults
html5lib                  0.999                    py35_0    defaults
idna                      2.0                      py35_0    <unknown>
iminuit                   1.2                      py35_0    astropy
ipykernel                 4.3.1                    py35_0    defaults
ipyparallel               5.0.1                    py35_0    defaults
ipython                   4.1.2                    py35_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_3    defaults
ipython-qtconsole         4.0.1                    py35_4    defaults
ipython_genutils          0.1.0                    py35_0    <unknown>
ipywidgets                4.1.1                    py35_0    defaults
itsdangerous              0.24                     py35_0    <unknown>
jdcal                     1.2                      py35_0    defaults
jedi                      0.9.0                    py35_0    <unknown>
jinja2                    2.8                      py35_0    <unknown>
jpeg                      8d                       vc14_0  [vc14]  <unknown>
jsonschema                2.4.0                    py35_0    <unknown>
jupyter                   1.0.0                    py35_1    defaults
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0    <unknown>
jupyter_console           4.1.0                    py35_0    defaults
jupyter_core              4.0.6                    py35_0    <unknown>
keyring                   5.3                      py35_0    astropy
launcher                  1.0.0                         4    <unknown>
libdynd                   0.7.1                         0    defaults
libpng                    1.6.17                   vc14_1  [vc14]  <unknown>
libsodium                 1.0.3                         0    <unknown>
libtiff                   4.0.6                    vc14_1  [vc14]  defaults
line-profiler             1.0                       <pip>
line_profiler             1.0                      py35_0    defaults
llvmlite                  0.9.0                    py35_0    defaults
locket                    0.2.0                    py35_0    defaults
lxml                      3.5.0                    py35_0    defaults
markupsafe                0.23                     py35_0    <unknown>
matplotlib                1.5.1               np110py35_0    defaults
menuinst                  1.3.2                    py35_0    defaults
mingw                     4.7                           1    defaults
mistune                   0.7.1                    py35_0    <unknown>
mkl                       11.3.1                        0    defaults
mkl-rt                    11.1                         p0    defaults
mkl-service               1.1.2                    py35_0    defaults
msvc_runtime              1.0.1                         0    defaults
multipledispatch          0.4.8                    py35_0    <unknown>
nbconvert                 4.1.0                    py35_0    defaults
nbformat                  4.0.1                    py35_0    <unknown>
netcdf4                   1.2.2               np110py35_0    defaults
networkx                  1.11                     py35_0    defaults
nltk                      3.2                      py35_0    defaults
node-webkit               0.10.1                        0    <unknown>
nose                      1.3.7                    py35_0    <unknown>
notebook                  4.1.0                    py35_0    defaults
numba                     0.24.0              np110py35_0    defaults
numexpr                   2.5                 np110py35_0    defaults
numpy                     1.10.4                   py35_0    defaults
odo                       0.4.2                    py35_0    defaults
openpyxl                  2.3.2                    py35_0    defaults
openssl                   1.0.2g                   vc14_0  [vc14]  defaults
pandas                    0.17.1              np110py35_0    defaults
partd                     0.3.2                    py35_1    defaults
patch                     2.5.9                         1    defaults
path.py                   7.6.1                    py35_0    defaults
patsy                     0.4.0               np110py35_0    <unknown>
pep8                      1.7.0                    py35_0    defaults
photutils                 0.2.1                    py35_0    astropy
pickleshare               0.5                      py35_0    <unknown>
pillow                    3.1.1                    py35_0    defaults
pip                       8.0.3                    py35_0    defaults
ply                       3.8                      py35_0    <unknown>
psutil                    4.0.0                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    <unknown>
pycosat                   0.6.1                    py35_0    <unknown>
pycparser                 2.14                     py35_0    <unknown>
pycrypto                  2.6.1                    py35_3    <unknown>
pycurl                    7.19.5.3                 py35_1    defaults
pyephem                   3.7.6.0                  py35_0    astropy
pyflakes                  1.1.0                    py35_0    defaults
pygments                  2.1.1                    py35_0    defaults
pyopenssl                 0.15.1                   py35_1    <unknown>
pyparsing                 2.0.3                    py35_0    <unknown>
pyqt                      4.11.4                   py35_5    defaults
pyreadline                2.1                      py35_0    <unknown>
pyregion                  1.1.4               np110py35_0    astropy
pytables                  3.2.2               np110py35_1    <unknown>
pytest                    2.8.5                    py35_0    defaults
pytest-cache              1.0                      py35_0    defaults
pytest-cov                2.2.1                     <pip>
pytest-pep8               1.0.6                    py35_0    defaults
python                    3.5.1                         2    defaults
python-dateutil           2.4.2                    py35_0    <unknown>
pytz                      2015.7                   py35_0    defaults
pywin32                   220                      py35_1    defaults
pyyaml                    3.11                     py35_3    defaults
pyzmq                     15.2.0                   py35_0    defaults
qt                        4.8.7                    vc14_6  [vc14]  defaults
qtconsole                 4.1.1                    py35_0    defaults
reproject                 0.2                 np110py35_0    astropy
requests                  2.9.1                    py35_0    defaults
rope                      0.9.4                    py35_1    <unknown>
rope-py3k                 0.9.4.post1               <pip>
scikit-image              0.11.3              np110py35_0    <unknown>
scikit-learn              0.17.1              np110py35_0    defaults
scipy                     0.17.0              np110py35_0    defaults
setuptools                20.1.1                   py35_0    defaults
simplegeneric             0.8.1                    py35_0    <unknown>
sip                       4.16.9                   py35_2    defaults
six                       1.10.0                   py35_0    <unknown>
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.1                    py35_0    <unknown>
specutils                 0.1                      py35_0    astropy
sphinx                    1.3.5                    py35_0    defaults
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py35_0    defaults
spyder                    2.3.8                    py35_0    defaults
spyder-app                2.3.8                    py35_0    defaults
sqlalchemy                1.0.12                   py35_0    defaults
statsmodels               0.6.1               np110py35_0    <unknown>
sympy                     0.7.6.1                  py35_0    <unknown>
tables                    3.2.2                     <pip>
tk                        8.5.18                   vc14_0  [vc14]  <unknown>
toolz                     0.7.4                    py35_0    <unknown>
tornado                   4.3                      py35_0    defaults
traitlets                 4.1.0                    py35_0    defaults
ujson                     1.35                     py35_0    defaults
unicodecsv                0.14.1                   py35_0    <unknown>
unxutils                  14.04.03                      0    defaults
wcsaxes                   0.6                      py35_0    astropy
werkzeug                  0.11.4                   py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
xarray                    0.7.1                    py35_0    defaults
xlrd                      0.9.4                    py35_0    <unknown>
xlsxwriter                0.8.4                    py35_0    defaults
xlwings                   0.6.4                    py35_1    defaults
xlwt                      1.0.0                    py35_0    <unknown>
zeromq                    4.1.3                    vc14_1  [vc14]  <unknown>
zlib                      1.2.8                    vc14_2  [vc14]  <unknown>
```

and the update:

```
[Anaconda] C:\Users\Admin>conda update -c astropy --all
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ...........

Package plan for installation in environment C:\Programming\Anaconda:

The following NEW packages will be INSTALLED:

    astropy:      1.1.1-np110py35_0  # This is only because I deleted the original before installing the dev version

The following packages will be UPDATED:

    msvc_runtime: 1.0.1-0         --> 1.0.1-vc14_0      [vc14]

The following packages will be DOWNGRADED:

    numexpr:      2.5-np110py35_0 --> 2.4.6-np110py35_1
```

**Comment by mcg1969** [comment] 2016-03-07 14:31
Thanks Michael! My suggestion is this: if possible, wait until conda 4.0.1 drops, which should be very soon (likely today). If `numexpr` is still downgraded after that, then there's either a dependency conflict there, or an issue with `update --all`. I *do* think that `update --all` is not perfect yet.

So another thing you can try is to do `conda update -c astropy --all` followed by `conda update numexpr` and see what happens.

**Comment by mcg1969** [comment] 2016-03-07 14:32
@MSeifert04, I figured it out: `pytables 3.2.2` requires `numexpr 2.4*`.

**Comment by MSeifert04** [comment] 2016-03-07 15:13
@mcg1969 - Thank you!

I just wasn't sure if it was a lingering problem with the new conda or some conflict. After removing ``pytables`` everything seems ok again. :+1:

**Comment by kalefranz** [comment] 2016-03-07 20:08
@MSeifert04 I'm going to close this issue for now.  `4.0.1` should be available with `conda update conda` very soon.  If something comes up again, reopen this issue if it's related, or just create a new one :)

**Closed by kalefranz** 2016-03-07 20:08 UTC
