### ISSUE TITLE
Error printing messages inside .messages.txt file for python3.7+

### ISSUE THREAD

**Issue by jhonderson** [conda/conda#8809] opened 2019-06-20 23:36 UTC
## Current Behavior
If you have a post-link.sh script in your conda recipe, and you put output messages to the $PREFIX/.messages.txt file, they are not printed with the right format. This happens on python 3.7, seems to work on python 2.7.

### Steps to Reproduce
Create a dummy conda recipe with a post-link.sh script with the following content:
```
cat <<EOF >> ${PREFIX}/.messages.txt
line 1
line 2
EOF
```

Build the conda package:
```
conda build .
```

Create a new environment with the above package:
```
conda create -n test-env test-package
```

At the end of the package installation, you will get this output message:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: / b'\nline 1\nline 2\n\n'
done
```

## Expected Behavior
You should get this output message:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction:
line 1
line 2

done
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /anaconda2
            shell level : 1
       user config file : /Users/jhon/.condarc
 populated config files : /Users/jhon/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          file:///anaconda2/conda-bld/noarch
          package cache : /anaconda2/pkgs
                          /Users/jhon/.conda/pkgs
       envs directories : /anaconda2/envs
                          /Users/jhon/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/3.7.3 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 735871630:1493692218
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/jhon/.condarc <==
ssl_verify: True
channel_priority: strict
channels:
  - defaults
  - conda-forge
  - file:///anaconda2/conda-bld/noarch/
```
</p></details>

**Comment by jhonderson** [comment] 2019-06-20 23:41
The issue seems to be on [link.py messages](https://github.com/conda/conda/blob/2ae1abc83521e6f908b9f25dd1606d8fa44ce863/conda/core/link.py#L1166) function.

Something like this could work:
```
def messages(prefix):
    path = join(prefix, '.messages.txt')
    try:
        if isfile(path):
            with open(path) as fi:
                m = fi.read()
                if hasattr(m, "decode"):
                    m = m.decode('utf-8')
                    print(m.encode('utf-8'), file=sys.stderr if context.json else sys.stdout)
                else:
                    print(m, file=sys.stderr if context.json else sys.stdout)
                return m
    finally:
        rm_rf(path)
```

But I don't know if that change could have bad implications for other python versions.

**Comment by duboism** [comment] 2019-08-30 20:05
I have observed the same problem with python 2.7.

**Comment by notestaff** [comment] 2019-11-15 18:13
Just to confirm that I'm seeing the same problem.  I'm trying to use the .messages.txt file to notify users of potential breaking changes in recent versions of a package, but the multi-line message is getting garbled.

**Comment by phil-blain** [comment] 2020-06-01 18:06
@jhonderson your patch to link.py does solve this issue (I tried in conda 4.8.3, with Python 3.7.6 in the base environment.)

To try it, I modifed `link.py` located at:
`/path/to/miniconda3/lib/python3.7/site-packages/conda/core/link.py`.

Would you be willing to submit a PR? If not do I have your permission to open a PR myself and use your patch ?

**Comment by jhonderson** [comment] 2020-06-01 18:10
> @jhonderson your patch to link.py does solve this issue (I tried in conda 4.8.3, with Python 3.7.6 in the base environment.)
> 
> To try it, I modifed `link.py` located at:
> `/path/to/miniconda3/lib/python3.7/site-packages/conda/core/link.py`.
> 
> Would you be willing to submit a PR? If not do I have your permission to open a PR myself and use your patch ?

Hello @phil-blain 

Nice to hear that. Please feel free to open a PR with this patch.

**Comment by phil-blain** [comment] 2020-06-03 22:38
this is actually a duplicate of https://github.com/conda/conda/issues/9819 (see also https://github.com/conda/conda-build/issues/3883), and it is has already been fixed: https://github.com/conda/conda/pull/9841

It should be in conda 4.8.4.

**Comment by phil-blain** [comment] 2020-06-14 01:07
@jhonderson you could close this one if you want :)

**Closed** 2020-06-14 01:12 UTC
