### ISSUE TITLE
conda.CondaMultiError: [Errno 2] No such file or directory: '/opt/python/bin/python3.7': '/opt/python/bin/python3.7'

### ISSUE THREAD

**Issue by lilihongjava** [conda/conda#9769] opened 2020-03-18 01:55 UTC
## Current Behavior

During handling of the above exception, another exception occurred:

I exec "conda install -c rapidsai -c nvidia -c numba -c conda-forge -c anaconda dask-cuda"

error info " No such file or directory: '/opt/python/bin/python3.7"

but root@c53aace09164:/opt/python/bin# ll /opt/python/bin/python3.7 
-rwxrwxrwx 1 root root 12788080 Mar 17 07:28 /opt/python/bin/python3.7*
I have this file

Traceback (most recent call last):
  File "/opt/python/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "/opt/python/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/opt/python/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/opt/python/lib/python3.7/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/opt/python/lib/python3.7/site-packages/conda/cli/install.py", line 253, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/opt/python/lib/python3.7/site-packages/conda/cli/install.py", line 282, in handle_txn
    unlink_link_transaction.execute()
  File "/opt/python/lib/python3.7/site-packages/conda/core/link.py", line 228, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/opt/python/lib/python3.7/site-packages/conda/core/link.py", line 526, in _execute
    rollback_excs,
conda.CondaMultiError: [Errno 2] No such file or directory: '/opt/python/bin/python3.7': '/opt/python/bin/python3.7'

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /opt/python  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/python/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/python/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-957.el7.x86_64 ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /root/.condarc <==
proxy_servers:
  http: http://127.0.0.1:8118
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
show_channel_urls: True


```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/python:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
attrs                     19.3.0                    <pip>
bokeh                     2.0.0                     <pip>
ca-certificates           2018.03.07                    0    defaults
cachetools                4.0.0                     <pip>
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37he75722e_1    defaults
chardet                   3.0.4                    py37_1    defaults
cloudpickle               1.3.0                     <pip>
conda                     4.5.12                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.4.2            py37h1ba5d50_0    defaults
cycler                    0.10.0                    <pip>
dask                      2.12.0                    <pip>
distributed               2.12.0                    <pip>
fsspec                    0.6.2                     <pip>
google-auth               1.11.3                    <pip>
graphviz                  0.13.2                    <pip>
HeapDict                  1.0.1                     <pip>
idna                      2.8                      py37_0    defaults
importlib-metadata        1.5.0                     <pip>
Jinja2                    2.11.1                    <pip>
joblib                    0.14.1                    <pip>
kiwisolver                1.1.0                     <pip>
kubernetes                11.0.0                    <pip>
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
locket                    0.2.0                     <pip>
MarkupSafe                1.1.1                     <pip>
matplotlib                3.2.0                     <pip>
more-itertools            8.2.0                     <pip>
msgpack                   1.0.0                     <pip>
ncurses                   6.1                  he6710b0_1    defaults
numpy                     1.18.1                    <pip>
oauthlib                  3.1.0                     <pip>
openssl                   1.1.1a               h7b6447c_0    defaults
packaging                 20.3                      <pip>
pandas                    1.0.2                     <pip>
partd                     1.1.0                     <pip>
Pillow                    7.0.0                     <pip>
pip                       18.1                     py37_0    defaults
pluggy                    0.13.1                    <pip>
psutil                    5.7.0                     <pip>
py                        1.8.1                     <pip>
pyasn1                    0.4.8                     <pip>
pyasn1-modules            0.2.8                     <pip>
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pyparsing                 2.4.6                     <pip>
pysocks                   1.6.8                    py37_0    defaults
pytest                    5.4.1                     <pip>
python                    3.7.1                h0371630_7    defaults
python-dateutil           2.8.1                     <pip>
pytz                      2019.3                    <pip>
PyYAML                    5.3                       <pip>
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py37_0    defaults
requests-oauthlib         1.3.0                     <pip>
rsa                       4.0                       <pip>
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
scikit-learn              0.22.2.post1              <pip>
scipy                     1.4.1                     <pip>
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sortedcontainers          2.1.0                     <pip>
sqlite                    3.26.0               h7b6447c_0    defaults
tblib                     1.6.0                     <pip>
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.10.0                    <pip>
tornado                   6.0.4                     <pip>
typing-extensions         3.7.4.1                   <pip>
urllib3                   1.24.1                   py37_0    defaults
wcwidth                   0.1.8                     <pip>
websocket-client          0.57.0                    <pip>
wheel                     0.32.3                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zict                      2.0.0                     <pip>
zipp                      3.1.0                     <pip>
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by forrestwaters** [comment] 2020-03-18 16:43
Duplicate of https://github.com/conda/conda/issues/9761 . 
I recommend using the latest version of conda if possible.

**Closed by forrestwaters** 2020-03-18 16:43 UTC
