### ISSUE TITLE
unable to load shared object R_X11.so

### ISSUE THREAD

**Issue by ruoyu0088** [conda/conda#2020] opened 2016-02-03 10:56 UTC
I installed R and irkernel by conda and then run following code with R kernel:

```
hist(rnorm(100))
```

I got following error message:

```
1: In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/usr/local/anaconda/envs/py35/lib/R/modules//R_X11.so':
  libSM.so.6: cannot open shared object file: No such file or directory
2: In png(tf, width, height, "in", pointsize, bg, res, antialias = antialias) :
  unable to load shared object '/usr/local/anaconda/envs/py35/lib/R/library/grDevices/libs//cairo.so':
  libXrender.so.1: cannot open shared object file: No such file or directory
3: In png(tf, width, height, "in", pointsize, bg, res, antialias = antialias) :
  failed to load cairo DLL
4: In file(con, "rb") :
  cannot open file '/tmp/Rtmpb0Osrt/file1f7d36acdcdd.png': No such file or directory
5: In svg(tf, width, height, pointsize, FALSE, family, bg, antialias) :
  failed to load cairo DLL
6: In file(con, "rb") :
  cannot open file '/tmp/Rtmpb0Osrt/file1f7d6e357c82.svg': No such file or directory
```

I am running anaconda on a ChromeOS PC with dev-mode enabled.

**Comment by vsnreddy2006** [comment] 2016-05-12 20:16
I am seeing same issue on Linux environment with R version 2.11.1

**Comment by jsignell** [comment] 2016-09-01 18:45
I am having the same issue in Linux with R version 3.2.2

**Comment by mingwandroid** [comment] 2016-09-02 16:42
The latest r version is 3.3.1, can you test with, and use that or must you use 3.2.2 for some reason?

**Comment by jsignell** [comment] 2016-09-02 19:24
I uninstalled R and installed 3.3.1 instead and I still have this issue. I installed cairo, jpeg, and png, but this is what I get when I do `capabilities()`. This is on a linux machine. 

Warning message:
In doTryCatch(return(expr), name, parentenv, handler): unable to load shared object '/miniconda/envs/lightning/lib/R/modules//R_X11.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory

jpeg
    FALSE
png
    FALSE
tiff
    FALSE
tcltk
    TRUE
X11
    FALSE
aqua
    FALSE
http/ftp
    TRUE
sockets
    TRUE
libxml
    TRUE
fifo
    TRUE
cledit
    FALSE
iconv
    TRUE
NLS
    TRUE
profmem
    TRUE
cairo
    FALSE
ICU
    TRUE
long.double
    TRUE
libcurl
    TRUE

**Comment by leipzig** [comment] 2016-10-05 14:52
https://github.com/ContinuumIO/anaconda-issues/issues/1063
https://github.com/jupyter/docker-stacks/issues/210

**Comment by abalter** [comment] 2017-01-27 20:05
I tried going back to v3.1.3 and still having the X11 problem:

```
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double
       TRUE       FALSE        TRUE       FALSE        TRUE
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/home/.../Applications/miniconda3/envs/r311/lib/R/modules//R_X11.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory
> plot(1:10,1:10)
Error in (function (display = "", width, height, pointsize, gamma, bg,  :
  X11 module cannot be loaded
```

I've ssh'd in with X. `xclock` opens and I can plot in python.

Furthermore: 

```
(r311) balter@exalab3:~$ ls -l /home/.../Applications/miniconda3/envs/r311/lib/R/modules/
total 13
-rwxr-xr-x 2 balter BioCoders  89840 Jun  2  2015 internet.so
-rwxr-xr-x 2 balter BioCoders  45779 Jun  2  2015 lapack.so
-rwxr-xr-x 2 balter BioCoders  69296 Jun  2  2015 R_de.so
-rwxr-xr-x 2 balter BioCoders 169562 Jun  2  2015 R_X11.so
-rwxr-xr-x 2 balter BioCoders 616020 Jun  2  2015 vfonts.so
```

So, why can't it load `R_X11.so`? Is the double slash `//` the problem?

**Comment by kalefranz** [comment] 2017-01-27 20:35
I guess maybe a duplicate of ContinuumIO/anaconda-issues#1063.  Either way, you should file your issue on github.com/ContinuumIO/anaconda-issues.  That's where you'll get the help you need :)

**Closed by kalefranz** 2017-01-27 20:35 UTC

**Comment by vujkovicm** [comment] 2017-08-24 19:12
I had the same error, and for me installing graphite2 fixed the problem.

`> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.4 (Santiago)

Matrix products: default
BLAS: /group/research/snakemake/.venv/lib/R/lib/libRblas.so
LAPACK: /group/research/snakemake/.venv/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1


# packages in environment at /group/research/mvp001/snakemake/.venv:
#
cairo                     1.12.18                       5    
cffi                      1.10.0                   py35_0    
curl                      7.54.1                        0    
entrypoints               0.2.3                    py35_1    
font-ttf-dejavu-sans-mono 2.37                          0    
fontconfig                2.12.1                        4    
freetype                  2.7                           1    
glib                      2.51.4                        0    
gmp                       6.1.2                         0    
graphite2                 1.3.9                         0    
graphviz                  2.38.0                        4    
harfbuzz                  1.4.3                         0    
jupyter_client            5.1.0                    py35_0    
jupyter_contrib_core      0.3.1                    py35_0    
jupyter_core              4.3.0                    py35_0    
latexcodec                1.0.1                    py35_0    
libffi                    3.2.1                         3    
libgcc                    4.8.5                         2    
libiconv                  1.14                          4    
libpng                    1.6.28                        1    
libpq                     9.6.3                         0    
libsodium                 1.0.10                        0    
libtiff                   4.0.6                         7    
libtool                   2.4.6                         0    
libx11                    1.6.3                         0    
libxml2                   2.9.4                         4    
libxslt                   1.1.29                        5    
modern-xorg-stack         2016.03                       1    
pandoc                    1.19.2                        0    
pandocfilters             1.4.1                    py35_0    
pango                     1.40.4                        0    
pillow                    4.2.1                    py35_1    
r                         3.3.2                  r3.3.2_0    
r-assertthat              0.1                    r3.3.2_4    
r-backports               1.0.4                  r3.3.2_0    
r-base                    3.4.1                         0    
r-bh                      1.62.0_1               r3.3.2_0    
r-bitops                  1.0_6                  r3.3.2_2    
r-cairo                   1.5_9                  r3.4.1_1    
r-curl                    2.3                    r3.3.2_0    
r-essentials              1.6.0                  r3.4.1_0    
r-xtable                  1.8_2                  r3.3.2_0    
r-xts                     0.9_7                  r3.3.2_2    
r-yaml                    2.1.14                 r3.3.2_0    
r-zoo                     1.7_13                 r3.3.2_0    
simplegeneric             0.8.1                    py35_0    
six                       1.10.0                   py35_1    
sqlite                    3.15.0                        0    
terminado                 0.6                      py35_0    
tk                        8.5.19                        2    
tornado                   4.5.1                    py35_0    
traitlets                 4.3.2                    py35_0    
wcwidth                   0.1.7                    py35_0    
xorg-libx11               1.6.4                         6    
xz                        5.2.2                         0    
`
