### ISSUE TITLE
Enable setting mappings keys (e.g. proxy_servers) via config set

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#5257] opened 2017-05-09 04:18 UTC
It should be possible to do

`conda config --set proxy_servers.http 1.2.3.4:4004`

and

`conda config --get proxy_servers.http`

**Comment by kalefranz** [comment] 2017-05-09 04:20
duplicate of https://github.com/conda/conda/issues/4302

**Closed** 2017-05-09 04:26 UTC
Labels: reso:duplicate, sev:4-low, source:cio, tag:config, type:enhancement
