### ISSUE TITLE
ValidationError: Value for sha256 cannot be None

### ISSUE THREAD

**Issue by snegirigens** [conda/conda#7634] opened 2018-08-09 18:52 UTC
## Current Behavior

Got "ValidationError: Value for sha256 cannot be None" while setting up conda virtual environment

### Steps to Reproduce

```
conda env update -f environment-cpu.yml
Fetching package metadata ...................
Solving package specifications: .
Warning: >10 possible package resolutions (only showing differing packages):
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36hfc679d8_0, conda-forge::icu-58.2-0, conda-forge::scipy-1.1.0-py36_blas_openblashd3ea46f_201
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36hfc679d8_0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::scipy-1.1.0-py36_blas_openblashd3ea46f_201
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36_0, conda-forge::icu-58.2-0, conda-forge::scipy-1.1.0-py36_blas_openblashd3ea46f_201
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36_0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::scipy-1.1.0-py36_blas_openblashd3ea46f_201
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36_0, conda-forge::icu-58.2-0, conda-forge::scipy-1.1.0-py36_blas_openblash7943236_201
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36_0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::scipy-1.1.0-py36_blas_openblash7943236_201
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36hfc679d8_0, conda-forge::icu-58.2-0, conda-forge::scipy-1.1.0-py36_blas_openblash7943236_201
  - conda-forge::bcolz-1.2.1-py36hf8a1672_1, conda-forge::cymem-1.31.2-py36hfc679d8_0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::scipy-1.1.0-py36_blas_openblash7943236_201
  - conda-forge::bcolz-1.2.1-py36_1, conda-forge::cymem-1.31.2-py36hfc679d8_0, conda-forge::icu-58.2-0, conda-forge::scipy-1.1.0-py36_blas_openblash7943236_201
  - conda-forge::bcolz-1.2.1-py36_1, conda-forge::cymem-1.31.2-py36hfc679d8_0, conda-forge::icu-58.2-0, conda-forge::scipy-1.1.0-py36_blas_openblashd3ea46f_201
  ... and others
blosc-1.14.4-h 100% |############################################################################################################| Time: 0:00:01 411.62 kB/s
bzip2-1.0.6-1. 100% |############################################################################################################| Time: 0:00:00 289.75 kB/s
ca-certificate 100% |############################################################################################################| Time: 0:00:00 260.43 kB/s
expat-2.2.5-hf 100% |############################################################################################################| Time: 0:00:00 192.68 kB/s
icu-58.2-0.tar 100% |############################################################################################################| Time: 0:00:22   1.07 MB/s
intel-openmp-2 100% |############################################################################################################| Time: 0:00:01 943.70 kB/s
jpeg-9c-h470a2 100% |############################################################################################################| Time: 0:00:00 320.35 kB/s
libffi-3.2.1-3 100% |############################################################################################################| Time: 0:00:00 158.15 kB/s
libiconv-1.15- 100% |############################################################################################################| Time: 0:00:01 842.32 kB/s
libsodium-1.0. 100% |############################################################################################################| Time: 0:00:00   1.17 MB/s
ncurses-6.1-hf 100% |############################################################################################################| Time: 0:00:01 676.29 kB/s
pandoc-2.2.2-h 100% |############################################################################################################| Time: 0:00:12   1.20 MB/s
pcre-8.41-h470 100% |############################################################################################################| Time: 0:00:00 532.43 kB/s
tk-8.6.8-0.tar 100% |############################################################################################################| Time: 0:00:01   1.87 MB/s
xz-5.2.4-h470a 100% |############################################################################################################| Time: 0:00:00 565.15 kB/s
yaml-0.1.7-h47 100% |############################################################################################################| Time: 0:00:00 671.96 kB/s
zlib-1.2.11-h4 100% |############################################################################################################| Time: 0:00:00 248.71 kB/s
hdf5-1.10.2-hc 100% |############################################################################################################| Time: 0:00:01   3.05 MB/s
libpng-1.6.34- 100% |############################################################################################################| Time: 0:00:00 511.80 kB/s
libtiff-4.0.9- 100% |############################################################################################################| Time: 0:00:00 720.13 kB/s
libxml2-2.9.8- 100% |############################################################################################################| Time: 0:00:01   1.36 MB/s
mkl-2018.0.3-1 100% |############################################################################################################| Time: 0:00:24   6.50 MB/s
openblas-0.2.2 100% |############################################################################################################| Time: 0:00:03   5.38 MB/s
openssl-1.0.2o 100% |############################################################################################################| Time: 0:00:01   2.99 MB/s
readline-7.0-h 100% |############################################################################################################| Time: 0:00:00 771.42 kB/s
zeromq-4.2.5-h 100% |############################################################################################################| Time: 0:00:00   1.53 MB/s
blas-1.1-openb 100% |############################################################################################################| Time: 0:00:00   1.15 MB/s
freetype-2.8.1 100% |############################################################################################################| Time: 0:00:00   1.03 MB/s
libxslt-1.1.32 100% |############################################################################################################| Time: 0:00:00 849.57 kB/s
sqlite-3.24.0- 100% |############################################################################################################| Time: 0:00:00   1.76 MB/s
python-3.6.6-h 100% |############################################################################################################| Time: 0:00:02   4.92 MB/s
qt-5.6.2-hd4c9 100% |############################################################################################################| Time: 0:00:06   5.59 MB/s
appdirs-1.4.3- 100% |############################################################################################################| Time: 0:00:00   6.32 MB/s
appnope-0.1.0- 100% |############################################################################################################| Time: 0:00:00   1.81 MB/s
asn1crypto-0.2 100% |############################################################################################################| Time: 0:00:00 571.64 kB/s
atomicwrites-1 100% |############################################################################################################| Time: 0:00:00   5.17 MB/s
attrs-18.1.0-p 100% |############################################################################################################| Time: 0:00:00   5.91 MB/s
backcall-0.1.0 100% |############################################################################################################| Time: 0:00:00   9.93 MB/s
certifi-2018.4 100% |############################################################################################################| Time: 0:00:00 546.40 kB/s
click-6.7-py_1 100% |############################################################################################################| Time: 0:00:00   4.58 MB/s
cloudpickle-0. 100% |############################################################################################################| Time: 0:00:00  10.45 MB/s
constantly-15. 100% |############################################################################################################| Time: 0:00:00   7.18 MB/s
cryptography-v 100% |############################################################################################################| Time: 0:00:05   5.86 MB/s
cymem-1.31.2-p 100% |############################################################################################################| Time: 0:00:00   7.26 MB/s
dask-core-0.18 100% |############################################################################################################| Time: 0:00:00   1.12 MB/s
decorator-4.3. 100% |############################################################################################################| Time: 0:00:00   7.35 MB/s
dill-0.2.8.2-p 100% |############################################################################################################| Time: 0:00:00 731.73 kB/s
entrypoints-0. 100% |############################################################################################################| Time: 0:00:00   6.86 MB/s
heapdict-1.0.0 100% |############################################################################################################| Time: 0:00:00   4.59 MB/s
hyperlink-17.3 100% |############################################################################################################| Time: 0:00:00   2.42 MB/s
idna-2.7-py36_ 100% |############################################################################################################| Time: 0:00:00 501.36 kB/s
incremental-17 100% |############################################################################################################| Time: 0:00:00   6.69 MB/s
ipython_genuti 100% |############################################################################################################| Time: 0:00:00   5.73 MB/s
jsonschema-2.6 100% |############################################################################################################| Time: 0:00:00 470.27 kB/s
kiwisolver-1.0 100% |############################################################################################################| Time: 0:00:00 503.26 kB/s
locket-0.2.0-p 100% |############################################################################################################| Time: 0:00:00   4.64 MB/s
lxml-4.2.4-py3 100% |############################################################################################################| Time: 0:00:01   1.57 MB/s
markupsafe-1.0 100% |############################################################################################################| Time: 0:00:00   5.29 MB/s
mistune-0.8.3- 100% |############################################################################################################| Time: 0:00:00 689.81 kB/s
msgpack-python 100% |############################################################################################################| Time: 0:00:00 620.60 kB/s
murmurhash-0.2 100% |############################################################################################################| Time: 0:00:00  11.18 MB/s
numpy-1.15.0-p 100% |############################################################################################################| Time: 0:00:01   2.75 MB/s
olefile-0.45.1 100% |############################################################################################################| Time: 0:00:00  12.03 MB/s
pandocfilters- 100% |############################################################################################################| Time: 0:00:00   7.32 MB/s
parso-0.3.1-py 100% |############################################################################################################| Time: 0:00:00 453.28 kB/s
path.py-11.0.1 100% |############################################################################################################| Time: 0:00:00  15.25 MB/s
pickleshare-0. 100% |############################################################################################################| Time: 0:00:00   8.63 MB/s
plac-0.9.6-py_ 100% |############################################################################################################| Time: 0:00:00   7.11 MB/s
pluggy-0.7.1-p 100% |############################################################################################################| Time: 0:00:00  11.40 MB/s
psutil-5.4.6-p 100% |############################################################################################################| Time: 0:00:00 727.28 kB/s
ptyprocess-0.6 100% |############################################################################################################| Time: 0:00:00   6.69 MB/s
py-1.5.4-py_0. 100% |############################################################################################################| Time: 0:00:00 457.83 kB/s
pyasn1-0.4.4-p 100% |############################################################################################################| Time: 0:00:00 388.66 kB/s
pycparser-2.18 100% |############################################################################################################| Time: 0:00:00 629.10 kB/s
pyparsing-2.2. 100% |############################################################################################################| Time: 0:00:00 378.46 kB/s
pytz-2018.5-py 100% |############################################################################################################| Time: 0:00:00 733.97 kB/s
pyzmq-17.1.0-p 100% |############################################################################################################| Time: 0:00:00 809.38 kB/s
regex-2017.11. 100% |############################################################################################################| Time: 0:00:00 903.91 kB/s
send2trash-1.5 100% |############################################################################################################| Time: 0:00:00   9.68 MB/s
simplegeneric- 100% |############################################################################################################| Time: 0:00:00   2.08 MB/s
sip-4.18-py36_ 100% |############################################################################################################| Time: 0:00:00 634.52 kB/s
six-1.11.0-py3 100% |############################################################################################################| Time: 0:00:00   6.78 MB/s
sortedcontaine 100% |############################################################################################################| Time: 0:00:00   1.77 MB/s
tblib-1.3.2-py 100% |############################################################################################################| Time: 0:00:00   8.06 MB/s
termcolor-1.1. 100% |############################################################################################################| Time: 0:00:00   4.74 MB/s
testpath-0.3.1 100% |############################################################################################################| Time: 0:00:00 711.12 kB/s
toolz-0.9.0-py 100% |############################################################################################################| Time: 0:00:00   3.80 MB/s
tornado-4.5.3- 100% |############################################################################################################| Time: 0:00:00 933.25 kB/s
tqdm-4.24.0-py 100% |############################################################################################################| Time: 0:00:00 266.57 kB/s
ujson-1.35-py3 100% |############################################################################################################| Time: 0:00:00  10.11 MB/s
wcwidth-0.1.7- 100% |############################################################################################################| Time: 0:00:00   5.56 MB/s
webencodings-0 100% |############################################################################################################| Time: 0:00:00  11.66 MB/s
wrapt-1.10.11- 100% |############################################################################################################| Time: 0:00:00 309.13 kB/s
zope.interface 100% |############################################################################################################| Time: 0:00:00 740.13 kB/s
automat-0.7.0- 100% |############################################################################################################| Time: 0:00:00   7.44 MB/s
cffi-1.11.5-py 100% |############################################################################################################| Time: 0:00:00 536.63 kB/s
cycler-0.10.0- 100% |############################################################################################################| Time: 0:00:00   6.92 MB/s
cytoolz-0.8.2- 100% |############################################################################################################| Time: 0:00:00 857.27 kB/s
html5lib-1.0.1 100% |############################################################################################################| Time: 0:00:00 592.73 kB/s
jedi-0.12.1-py 100% |############################################################################################################| Time: 0:00:00 553.72 kB/s
more-itertools 100% |############################################################################################################| Time: 0:00:00 188.28 kB/s
msgpack-numpy- 100% |############################################################################################################| Time: 0:00:00   8.30 MB/s
packaging-17.1 100% |############################################################################################################| Time: 0:00:00 155.38 kB/s
partd-0.3.8-py 100% |############################################################################################################| Time: 0:00:00  10.88 MB/s
pexpect-4.6.0- 100% |############################################################################################################| Time: 0:00:00 281.92 kB/s
pillow-5.2.0-p 100% |############################################################################################################| Time: 0:00:01 440.37 kB/s
preshed-1.0.1- 100% |############################################################################################################| Time: 0:00:00 131.94 kB/s
pyasn1-modules 100% |############################################################################################################| Time: 0:00:00  79.10 kB/s
pyhamcrest-1.9 100% |############################################################################################################| Time: 0:00:00  93.20 kB/s
pyqt-5.6.0-py3 100% |############################################################################################################| Time: 0:00:08 508.53 kB/s
python-dateuti 100% |############################################################################################################| Time: 0:00:00 222.21 kB/s
scipy-1.1.0-py 100% |############################################################################################################| Time: 0:00:16   1.02 MB/s
setuptools-40. 100% |############################################################################################################| Time: 0:00:00 973.18 kB/s
terminado-0.8. 100% |############################################################################################################| Time: 0:00:00   1.68 MB/s
traitlets-4.3. 100% |############################################################################################################| Time: 0:00:00 427.87 kB/s
zict-0.1.3-py_ 100% |############################################################################################################| Time: 0:00:00   8.11 MB/s
bleach-2.1.3-p 100% |############################################################################################################| Time: 0:00:00  87.24 kB/s
cryptography-2 100% |############################################################################################################| Time: 0:00:00 603.46 kB/s
distributed-1. 100% |############################################################################################################| Time: 0:00:00   1.44 MB/s
jinja2-2.10-py 100% |############################################################################################################| Time: 0:00:00 126.46 kB/s
jupyter_core-4 100% |############################################################################################################| Time: 0:00:00 318.72 kB/s
matplotlib-2.2 100% |############################################################################################################| Time: 0:00:05   1.20 MB/s
numexpr-2.6.6- 100% |############################################################################################################| Time: 0:00:00 232.33 kB/s
pandas-0.23.4- 100% |############################################################################################################| Time: 0:00:08   1.23 MB/s
patsy-0.5.0-py 100% |############################################################################################################| Time: 0:00:00 356.00 kB/s
pygments-2.2.0 100% |############################################################################################################| Time: 0:00:01 521.78 kB/s
pytest-3.7.1-p 100% |############################################################################################################| Time: 0:00:00   1.21 MB/s
pytorch-0.3.1- 100% |############################################################################################################| Time: 0:00:02   2.20 MB/s
thinc-6.10.2-p 100% |############################################################################################################| Time: 0:00:01 861.31 kB/s
wheel-0.31.1-p 100% |############################################################################################################| Time: 0:00:00   4.55 MB/s
bokeh-0.13.0-p 100% |############################################################################################################| Time: 0:00:04   1.15 MB/s
jupyter_client 100% |############################################################################################################| Time: 0:00:00 221.75 kB/s
nbformat-4.4.0 100% |############################################################################################################| Time: 0:00:00 194.18 kB/s
pip-18.0-py36_ 100% |############################################################################################################| Time: 0:00:04 419.20 kB/s
prompt_toolkit 100% |############################################################################################################| Time: 0:00:01 308.89 kB/s
pyopenssl-18.0 100% |############################################################################################################| Time: 0:00:00 518.77 kB/s
pytables-3.4.4 100% |############################################################################################################| Time: 0:00:05 494.01 kB/s
spacy-2.0.11-p 100% |############################################################################################################| Time: 0:00:35   1.02 MB/s
statsmodels-0. 100% |############################################################################################################| Time: 0:00:04   2.06 MB/s
dask-0.18.2-py 100% |############################################################################################################| Time: 0:00:00   2.16 MB/s
ipython-6.5.0- 100% |############################################################################################################| Time: 0:00:00   1.38 MB/s
nbconvert-5.3. 100% |############################################################################################################| Time: 0:00:00   1.19 MB/s
seaborn-0.9.0- 100% |############################################################################################################| Time: 0:00:00 366.59 kB/s
service_identi 100% |############################################################################################################| Time: 0:00:00   4.19 MB/s
bcolz-1.2.1-py 100% |############################################################################################################| Time: 0:00:00 855.49 kB/s
ipykernel-4.8. 100% |############################################################################################################| Time: 0:00:00   1.07 MB/s
twisted-18.7.0 100% |############################################################################################################| Time: 0:00:02   2.27 MB/s
jupyter_consol 100% |############################################################################################################| Time: 0:00:00 275.41 kB/s
prometheus_cli 100% |############################################################################################################| Time: 0:00:00 207.45 kB/s
qtconsole-4.3. 100% |############################################################################################################| Time: 0:00:00 350.81 kB/s
notebook-5.6.0 100% |############################################################################################################| Time: 0:00:03   2.16 MB/s
jupyter_contri 100% |############################################################################################################| Time: 0:00:00  11.71 MB/s
widgetsnbexten 100% |############################################################################################################| Time: 0:00:01   1.39 MB/s
ipywidgets-7.4 100% |############################################################################################################| Time: 0:00:00 328.09 kB/s
jupyter_highli 100% |############################################################################################################| Time: 0:00:00   5.39 MB/s
jupyter_latex_ 100% |############################################################################################################| Time: 0:00:00   1.37 MB/s
jupyter-1.0.0- 100% |############################################################################################################| Time: 0:00:00   4.27 MB/s
jupyter_contri 100% |############################################################################################################| Time: 0:00:08   2.49 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/sneg/tools/miniconda2  (writable)
    default environment : /Users/sneg/tools/miniconda2
       envs directories : /Users/sneg/tools/miniconda2/envs
          package cache : /Users/sneg/tools/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.12 Darwin/15.0.0 OSX/10.11.1
                UID:GID : 501:20

`$ /Users/sneg/tools/miniconda2/bin/conda-env update -f environment-cpu.yml`

    Traceback (most recent call last):
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 113, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda_env/installers/conda.py", line 37, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 122, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 122, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 75, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 141, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 141, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/sneg/tools/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/sneg/tools/miniconda2  (writable)
    default environment : /Users/sneg/tools/miniconda2/envs/fastai-cpu
       envs directories : /Users/sneg/tools/miniconda2/envs
          package cache : /Users/sneg/tools/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.12 Darwin/15.0.0 OSX/10.11.1
                UID:GID : 501:20
```
</p></details>

<details><summary><code>`cat environment-cpu.yml`</code></summary><p>
```
name: fastai-cpu
channels:
- fastai
- pytorch
- defaults
- peterjc123
- anaconda
dependencies:
- scipy
- numpy
- pillow
- jpeg
- spacy
- zlib
- freetype
- libtiff
- bleach
- certifi
- cffi
- cycler
- decorator
- entrypoints
- expat
- html5lib
- icu
- defaults::intel-openmp
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jedi
- jinja2
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- conda-forge::jupyter_contrib_nbextensions  
- libiconv
- libpng
- libsodium
- libxml2
- markupsafe
- matplotlib
- mistune
- mkl
- nbconvert
- nbformat
- notebook
- numpy
- olefile
- openssl
- pandas
- pandocfilters
- path.py
- patsy
- pcre
- pexpect
- pickleshare
- pillow
- pip
- prompt_toolkit
- pycparser
- pygments
- pyparsing
- pyqt
- python>=3.6.0
- python-dateutil
- pytz
- pyzmq
- qt
- qtconsole
- scipy
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- statsmodels
- testpath
- tk
- tornado<5
- tqdm
- traitlets
- wcwidth
- wheel
- widgetsnbextension
- xz
- zeromq
- pytorch<0.4
- bcolz
- prompt_toolkit
- pytest
- pip:
  - torchvision>=0.1.9
  - opencv-python
  - isoweek
  - pandas_summary
  - torchtext
  - graphviz
  - sklearn_pandas
  - feather-format
  - plotnine
  - kaggle-cli
  - ipywidgets
```
</p></details>

**Comment by kalefranz** [comment] 2018-08-13 16:14
Duplicate of https://github.com/conda/conda/issues/5278. Fixed in 4.3.14. `conda update conda`

**Closed by kalefranz** 2018-08-13 16:14 UTC
