### ISSUE TITLE
Cannot remove environment, returns empty PackagesNotFoundError

### ISSUE THREAD

**Issue by jarmitage** [conda/conda#8351] opened 2019-02-27 11:28 UTC
## Current Behavior

```
Remove all packages in environment /anaconda3/envs/cling37:


PackagesNotFoundError: The following packages are missing from the target environment:
- 

```

### Steps to Reproduce

```
> conda remove --name cling37 --all
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : cling37
    active env location : /anaconda3/envs/cling37
            shell level : 1
       user config file : /Users/jarm/.condarc
 populated config files : /Users/jarm/.condarc
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /anaconda3/pkgs
                          /Users/jarm/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/jarm/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/jarm/.condarc <==
ssl_verify: True
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /anaconda3/envs/cling37:
#
# Name                    Version                   Build  Channel
```
</p></details>

**Comment by jjhelmus** [comment] 2019-03-02 22:17
Are there any files in the `/anaconda3/envs/cling37/conda-meta` directory?  If this environment is not need it is safe to remote it using `rm -rf /anaconda3/envs/cling37`.

**Comment by jarmitage** [comment] 2019-03-03 22:48
Sorry, I had to reinstall Anaconda after having tonnes of issues with `conda update --all` and upgrading to Python 3.7, so I can't give any more information on this. Feel free to close.

**Comment by jjhelmus** [comment] 2019-03-07 13:15
Thanks for the update @jarmitage.  I'm going to close this.  If you run into issue like this again feel free to open a new issue.

**Closed by jjhelmus** 2019-03-07 13:15 UTC

**Comment by rtmatx** [comment] 2019-03-18 18:57
I faced similar issue and followed your instruction @jjhelmus . It worked out. I had `history` folder in the `envs\env_name` folder and I had to remove to remove the environment

**Comment by instantname** [comment] 2019-06-17 13:05
This happened to me after creating an environment without specifying the python version:

    conda create -n test_env
    conda remove -n test_env --all

**Comment by jjhelmus** [comment] 2019-06-17 15:29
`conda remove` removes a package from an environment.  To remove the environment you need to use `conda env remove -n test_env`.

**Comment by P450** [comment] 2019-06-25 14:15
> `conda remove` removes a package from an environment. To remove the environment you need to use `conda env remove -n test_env`.

Well that's just confusing since their [doc](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment) suggests using `conda remove` to remove an environment, not a package from an environment.

**Comment by sktomar** [comment] 2019-06-25 18:44
> This happened to me after creating an environment without specifying the python version:
> 
> ```
> conda create -n test_env
> conda remove -n test_env --all
> ```

I can also confirm this. I created an environment without specifying Python version, and when I wanted to delete it, I ended up facing this problem, that is, if I try to use < conda remove -n my_env --all >, it gives the warning "PackagesNotFoundError".

I solved it by using the following command
< conda env remove -n my_env >

This first removes all the packages, and then removes the environment itself (checked by < conda info --envs >.

**Comment by sktomar** [comment] 2019-06-25 18:49
> > `conda remove` removes a package from an environment. To remove the environment you need to use `conda env remove -n test_env`.
> 
> Well that's just confusing since their [doc](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment) suggests using `conda remove` to remove an environment, not a package from an environment.
> 
> Edit:
> @jjhelmus - can you please confirm if this is expected behaviour (#8147)? It seems like `conda remove --name myenv --all` should remove all the packages as well as the environment from the docs. But it does not remove the environment without any package installed.

I can confirm that if I create an env without any packages installed, then < conda remove -n my_end --all > does not remove the environment. For that case, as I explained in https://github.com/conda/conda/issues/8351#issuecomment-505572025
we can use < conda env remove -n my_env >, which first removes all the packages (actually nothing is there), and then removes the environment.

If there are some packages installed at the time of creation, then < conda remove -n my_env --all > removes the complete environment.

Hope this helps.

**Comment by gar1t** [comment] 2019-09-14 17:58
This issue should be reopened - as pointed out the docs are wrong. Those should be fixed before closing.

**Comment by Riponcs** [comment] 2019-10-22 02:12
> `conda remove` removes a package from an environment. To remove the environment you need to use `conda env remove -n test_env`.

This command worked for me when I face same issue:- PackagesNotFoundError

**Comment by bobloki** [comment] 2019-10-22 16:24
1.  conda remove --yes --name myenv --all
    a. PackagesNotFoundError: The following packages are missing from the target environment: 

2. conda env remove --name myenv
    a.  Works.

@gar1t  This documentation needs updating still https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by JohannesWiesner** [comment] 2019-11-29 09:32
> 1. conda remove --yes --name myenv --all
>    a. PackagesNotFoundError: The following packages are missing from the target environment:
> 2. conda env remove --name myenv
>    a.  Works.
> 
> @gar1t @jjhelmus This documentation needs updating still https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

Same here when using a specified subdirectory:

1. `conda remove --all --prefix "absolute\path\to\env"` threw the PackagesNotFoundError.
2. `conda env remove --prefix "absolute\path\to\env"` worked.

**Comment by comperem** [comment] 2019-12-31 05:56
`conda env remove --name myenv` is fine, but the [conda-cheatsheet.pdf](https://docs.conda.io/projects/conda/en/latest/user-guide/cheatsheet.html) says just `conda remove`. A documentation update as @P450  indicated above

**Comment by aa25desh** [comment] 2020-01-24 11:31
form `(base)`   `conda env remove --name` 
worked

**Comment by Doev** [comment] 2020-05-11 14:15
Same happend to me. It was a "empty" environemnt, that means no additional package installed. I installed a random package, after that There was no error and I was able to delete the environment.
