### ISSUE TITLE
Installing xopen 1.1.0 breaks conda

### ISSUE THREAD

**Issue by mboratko** [conda/conda#10907] opened 2021-09-10 15:14 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

```
conda create -n xopen-breaks-conda python=3.8
conda activate xopen-breaks-conda
pip install xopen==1.1.0
conda list
```
results in `SyntaxError: unknown variable: python_implementation`.

Full output:[xopen-breaks-conda-output.txt](https://github.com/conda/conda/files/7144727/xopen-breaks-conda-output.txt)

### Conda info

```shell
active environment : xopen-breaks-conda
    active env location : /Users/username/.miniconda3/envs/xopen-breaks-conda
            shell level : 1
       user config file : /Users/username/.condarc
 populated config files : /Users/username/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/username/.miniconda3  (writable)
      conda av data dir : /Users/username/.miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pytorch/osx-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/username/.miniconda3/pkgs
                          /Users/username/.conda/pkgs
       envs directories : /Users/username/.miniconda3/envs
                          /Users/username/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.10 Darwin/20.6.0 OSX/10.16
                UID:GID : 503:20
             netrc file : /Users/username/.netrc
           offline mode : False
```

### Conda config

```shell
==> /Users/username/.condarc <==
channels:
  - pytorch
  - defaults
```

### Conda list

```shell
SyntaxError: unknown variable: python_implementation

(same as above)
```

**Comment by jezdez** [comment] 2021-09-17 17:12
Duplicate of #10768

**Closed by jezdez** 2021-09-17 17:12 UTC
Labels: type-bug

**Comment by jezdez** [comment] 2021-09-17 18:51
@mboratko For the record, I've opened https://github.com/pycompression/xopen/issues/70 to fix the issue that is causing the environment parsing error in Conda, but this'll need to be better handled in conda as well, which is why #10768 is still worthwhile to keep an eye on. Basically `conda list` needs to better report back what environment marker failed.
