### ISSUE TITLE
SafetyError?

### ISSUE THREAD

**Issue by dEvasEnApati** [conda/conda#6689] opened 2018-01-09 13:44 UTC
Hello all

I get this warning with conda:

> SafetyError: The package for subprocess32 located at /home/aj/Installations/anaconda3/pkgs/subprocess32-3.2.7-py27h373dbce_0 appears to be corrupted. The path 'lib/python2.7/site-packages/_posixsubprocess.so' has a sha256 mismatch.   reported sha256: e3df799e317d2796d064e1b384e0acfeee81f03399465ad87a78c91e39ea9c32   actual sha256: 1b75cfe2ca991b4984c62f0b30162603c58fdefe8214efd74a190ae70cb94ebb

Researching about this told me that the sha256 mismatch might have happened when the same package was installed from different channels into different environments. How do I get rid of this warning?

Edit: I get this with conda v4.4.6 on Ubuntu 16.04

**Comment by kalefranz** [comment] 2018-01-09 14:33
It's probably a bad package.  What is the origin URL for the package?

**Comment by dEvasEnApati** [comment] 2018-01-09 15:14
>conda info subprocess32 

showed the following url for the package `subprocess32 3.2.7 py27h373dbce_0` above

> https://repo.continuum.io/pkgs/main/linux-64/subprocess32-3.2.7-py27h373dbce_0.tar.bz2

**Comment by kalefranz** [comment] 2018-01-09 15:33
Package looks fine actually.

```
$ shasum -a 256 lib/python2.7/site-packages/_posixsubprocess.so
e3df799e317d2796d064e1b384e0acfeee81f03399465ad87a78c91e39ea9c32  lib/python2.7/site-packages/_posixsubprocess.so
```

Try

    conda clean --packages --tarballs

and see if that helps.

**Comment by dEvasEnApati** [comment] 2018-01-09 15:52
I tried `conda clean --packages --tarball` which removed ~250MB of data. Then when I try
```
conda create --name dummy python=2.7 subprocess32
```

I get the same SafetyError Warning. Any idea whats happening?

**Comment by nicain** [comment] 2018-01-18 21:59
Me too:

conda 4.4.7

conda create --name test python=3.6

```SafetyError: The package for certifi located at /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0
appears to be corrupted. The path 'lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc'
has a sha256 mismatch.
  reported sha256: 8b56c5594309e44c9f5058bdde343e5e62bf0ab92d048a059ce17736d3401257
  actual sha256: ad2edf25b55f10556acc7010d7354f2c1246475fbfb0b5e5252252b876730361

SafetyError: The package for certifi located at /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0
appears to be corrupted. The path 'lib/python3.6/site-packages/certifi/__pycache__/__main__.cpython-36.pyc'
has a sha256 mismatch.
  reported sha256: c9a6c77ce469f80cf327424500e96d3808c708a75a45f40d89aa25a6b9a4e03c
  actual sha256: 7a2a59764be4ce9febc2e46d1192bef777539f8cfaf60c09649df414fdee3aed

SafetyError: The package for certifi located at /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0
appears to be corrupted. The path 'lib/python3.6/site-packages/certifi/__pycache__/core.cpython-36.pyc'
has a sha256 mismatch.
  reported sha256: d85767e7fff4a54f77d58a2c2451c9507e95e59d0dd3210dbdf0d7bc3dd3b26d
  actual sha256: db9dfa0fcf84bba4fea01a1b2084e950e444c6ef6c509b895565f78dc20c186d
```

**Comment by kalefranz** [comment] 2018-01-18 22:03
@nicain Can you give me output of `conda info`?

**Comment by nicain** [comment] 2018-01-18 22:11
```
active environment : None
       user config file : /home/nicholasc/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /home/nicholasc/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/nicholasc/anaconda2/pkgs
                          /home/nicholasc/.conda/pkgs
       envs directories : /home/nicholasc/anaconda2/envs
                          /home/nicholasc/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/2.7.14 Linux/4.10.0-38-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1095:1000
             netrc file : None
           offline mode : False
```

**Comment by nicain** [comment] 2018-01-18 22:45
```
 [nicholasc@nicholasc-ubuntu]~/projects/$sha256sum /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
ad2edf25b55f10556acc7010d7354f2c1246475fbfb0b5e5252252b876730361  /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
➜ [nicholasc@nicholasc-ubuntu]~/projects/$sha256sum /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__main__.cpython-36.pyc
7a2a59764be4ce9febc2e46d1192bef777539f8cfaf60c09649df414fdee3aed  /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__main__.cpython-36.pyc
➜ [nicholasc@nicholasc-ubuntu]~/projects/$sha256sum /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/core.cpython-36.pyc
db9dfa0fcf84bba4fea01a1b2084e950e444c6ef6c509b895565f78dc20c186d  /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/core.cpython-36.pyc
```

**Comment by kalefranz** [comment] 2018-01-18 23:15
Downloaded the package myself from https://repo.continuum.io/pkgs/main/linux-64/certifi-2017.11.5-py36hf29ccca_0.tar.bz2

The hash I get when I download the package directly matches what's in `info/paths.json`.

```
kfranz@0283:~/Downloads/certifi-2017.11.5-py36hf29ccca_0 ❯ shasum -a 256 lib/python3.6/site-packages/certifi/__pycache__/__main__.cpython-36.pyc
c9a6c77ce469f80cf327424500e96d3808c708a75a45f40d89aa25a6b9a4e03c  lib/python3.6/site-packages/certifi/__pycache__/__main__.cpython-36.pyc
```

I'm guessing that 

    ls -al /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc

will show hard-link count `> 1`, meaning the inode is being used in a conda environment somewhere.  And that's why `conda clean --packages` isn't working.  Perhaps we need to add a `conda clean --packages --force-remove`, which will basically just be `rm -rf`.

I can think of two different ways the hashes wouldn't match.  One is if conda (i.e. python) extracted the package tarball incorrectly.  The second is if pip operated on a conda environment that the package was linked into and modified those paths.

**Comment by kalefranz** [comment] 2018-01-18 23:19
And for the record, downgrading to conda 4.3 will appear to "fix" the problem for you.  It's actually not fixed though; the problem is still there.  Conda 4.3 just isn't smart enough to see it.  Whether you use 4.3 or 4.4, no doubt there's a discrepancy in your environment that should be understood.

If you want to allow conda 4.4 to move forward,

    conda config --set safety_checks warn

or

    conda config --set safety_checks disabled

after we get https://github.com/conda/conda/pull/6619 merged.  Until that gets in though, you'll have to manually edit a condarc file with those config parameters.

**Comment by nicain** [comment] 2018-01-19 18:43
Thanks!

**Comment by kalefranz** [comment] 2018-01-19 18:51
I'm going to close this issue.  I think my analysis was complete with

>  I can think of two different ways the hashes wouldn't match. One is if conda (i.e. python) extracted the package tarball incorrectly. The second is if pip operated on a conda environment that the package was linked into and modified those paths.

and my *guess* is that it's the pip situation.

**Closed by kalefranz** 2018-01-19 18:51 UTC

**Comment by nicain** [comment] 2018-01-19 18:57
You were right about hard-link count, but maybe for a trivial reason?  

> meaning the inode is being used in a conda environment somewhere. 

It looks like the inode is being used, but by conda?  the ./anaconda2/pkgs hardlink usage of the file is intended, right?

```
➜ git:(master) [nicholasc@nicholasc-ubuntu]~/projects/mtrain/$ls -al /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
-rw-rw-r-- 2 nicholasc nicholasc 219 Jan 16 13:24 /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
➜ git:(master) [nicholasc@nicholasc-ubuntu]~/projects/mtrain/$cd ~
➜ [nicholasc@nicholasc-ubuntu]~/$find . -samefile /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
./anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
./anaconda2/envs/allensdk_internal_test/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
➜ [nicholasc@nicholasc-ubuntu]~/$conda env remove --name allensdk_internal_test       

Remove all packages in environment /home/nicholasc/anaconda2/envs/allensdk_internal_test:

Proceed ([y]/n)? y

➜ [nicholasc@nicholasc-ubuntu]~/$ls -al /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
-rw-rw-r-- 1 nicholasc nicholasc 219 Jan 16 13:24 /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0/lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc
➜ [nicholasc@nicholasc-ubuntu]~/$conda create --name allensdk_internal_test python=3.6
Solving environment: done

## Package Plan ##

  environment location: /home/nicholasc/anaconda2/envs/allensdk_internal_test

  added / updated specs: 
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0   
    certifi:         2017.11.5-py36hf29ccca_0
    libedit:         3.1-heed3624_0          
    libffi:          3.2.1-hd88cf55_4        
    libgcc-ng:       7.2.0-h7cc24e2_2        
    libstdcxx-ng:    7.2.0-h7a57d05_2        
    ncurses:         6.0-h9df7e31_2          
    openssl:         1.0.2n-hb7f436b_0       
    pip:             9.0.1-py36h6c6f9ce_4    
    python:          3.6.4-hc3d631a_1        
    readline:        7.0-ha6073c6_4          
    setuptools:      38.4.0-py36_0           
    sqlite:          3.20.1-hb898158_2       
    tk:              8.6.7-hc745277_3        
    wheel:           0.30.0-py36hfd4bba0_1   
    xz:              5.2.3-h55aa19d_2        
    zlib:            1.2.11-ha838bed_2       

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: | 
SafetyError: The package for certifi located at /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0
appears to be corrupted. The path 'lib/python3.6/site-packages/certifi/__pycache__/__init__.cpython-36.pyc'
has a sha256 mismatch.
  reported sha256: 8b56c5594309e44c9f5058bdde343e5e62bf0ab92d048a059ce17736d3401257
  actual sha256: ad2edf25b55f10556acc7010d7354f2c1246475fbfb0b5e5252252b876730361

SafetyError: The package for certifi located at /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0
appears to be corrupted. The path 'lib/python3.6/site-packages/certifi/__pycache__/__main__.cpython-36.pyc'
has a sha256 mismatch.
  reported sha256: c9a6c77ce469f80cf327424500e96d3808c708a75a45f40d89aa25a6b9a4e03c
  actual sha256: 7a2a59764be4ce9febc2e46d1192bef777539f8cfaf60c09649df414fdee3aed

SafetyError: The package for certifi located at /home/nicholasc/anaconda2/pkgs/certifi-2017.11.5-py36hf29ccca_0
appears to be corrupted. The path 'lib/python3.6/site-packages/certifi/__pycache__/core.cpython-36.pyc'
has a sha256 mismatch.
  reported sha256: d85767e7fff4a54f77d58a2c2451c9507e95e59d0dd3210dbdf0d7bc3dd3b26d
  actual sha256: db9dfa0fcf84bba4fea01a1b2084e950e444c6ef6c509b895565f78dc20c186d


/ 
done
Executing transaction: done
#
# To activate this environment, use:
# > source activate allensdk_internal_test
#
# To deactivate an active environment, use:
# > source deactivate
#

➜ [nicholasc@nicholasc-ubuntu]~/
```

**Comment by nicain** [comment] 2018-01-19 18:59
FIXED!

**Comment by kalefranz** [comment] 2018-01-19 19:04
Cool!  Sounds like conda 4.4 is working as designed then!  (Not that the design can't use additional UI tweaks to help explain and untangle a situation like this.)

**Comment by dEvasEnApati** [comment] 2018-01-22 11:54
>  The second is if pip operated on a conda environment that the package was linked into and modified those paths.

I think my problem was caused by this, as I did install the same package using pip into a conda environment. The above suggestion, namely, `conda remove -n <env name>` followed by `conda clean --packages --tarballs` did not make the warnings go away.

Based on the following,
> Perhaps we need to add a conda clean --packages --force-remove, which will basically just be rm -rf

I removed the problematic package from anaconda cache and now I don't have this warning anymore. I hope deleting packages from the cache does not affect conda, would it?

**Comment by kalefranz** [comment] 2018-01-22 18:35
> I hope deleting packages from the cache does not affect conda, would it?

No.  The only thing you disrupt by deleting packages from the cache is the disk space conservation you get from being able to link the same package into multiple conda environments.

**Comment by kalefranz** [comment] 2018-02-12 15:41
I'm guessing this issue has the same root-cause dynamics as https://github.com/conda/conda/issues/6859

**Comment by sebma** [comment] 2018-07-09 15:03
@kalefranz Hi, I have the same pb. Do you have an alternative other than `conda remove -n <env name>` to help me fix the pb. ?

**Comment by karenachiketc** [comment] 2018-08-29 09:40
Hi @kalefranz 
I also had a similar problem(also referring to #6861 ) with my conda environment.
I went through both the issue discussion and this is my conclusion(put in very simple words):
Whenever inside a conda environment, if you need a package to be installed avoid using pip and use conda. pip will mess with the way conda organizes the environment(s). So do a conda install instead of a pip installed.
Please let me know if that is correct
I ask this because this has been my question every since I've started using conda: the correct way of installing packages inside a conda environment. I've tried searching for a solution and on most of the links I've read that both the ways are correct; that was until I ran into this issue. Some sort of conclusion will be really helpful. Thanks!

**Comment by gmgitx** [comment] 2019-01-08 11:44
> Package looks fine actually.
> 
> ```
> $ shasum -a 256 lib/python2.7/site-packages/_posixsubprocess.so
> e3df799e317d2796d064e1b384e0acfeee81f03399465ad87a78c91e39ea9c32  lib/python2.7/site-packages/_posixsubprocess.so
> ```
> Try
> 
> ```
> conda clean --packages --tarballs
> ```
> and see if that helps.

Could I ask for this step, `conda clean --packages --tarballs`, it will also clean other dependency packages(like a, b, c)? If yes, think other package d need b,c, then d can't work well after clean. If not, so this environment will keep a but useless. When installing package, also update some packages at same time. Above all, clean one package should after a rethink? These are what I not clear and worried about now, how about your view? Many thanks!!!

**Comment by omry** [comment] 2020-08-17 18:13
I had this just creating an env with python 3.8 (without any other dependencies).
`conda clean --packages --tarballs` did not do the job for some reason.

Turns out nuking (or renaming) the pkgs directory (e.g ~/miniconda/pkgs) is safe and conda will restore it.
