### ISSUE TITLE
conda --help incomplete

### ISSUE THREAD

**Issue by Reissner** [conda/conda#9817] opened 2020-04-07 10:38 UTC
The command `conda --help` fails to mention both activate and deactivate. 

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kenodegard** [comment] 2022-03-09 17:15
Duplicate of https://github.com/conda/conda/issues/6353

**Closed by kenodegard** 2022-03-09 17:15 UTC
Labels: type::feature, source::community, duplicate
