### ISSUE TITLE
feature request: "conda download package" 

### ISSUE THREAD

**Issue by hainm** [conda/conda#5704] opened 2017-07-21 04:13 UTC
What do you think? 
This should be similar to `pip download package`

PS: I searched ""conda download" in issues but getting > 280 restuls, not sure if this post is duplicated.

**Comment by kalefranz** [comment] 2017-10-11 20:41
Implemented via #5988 in conda 4.4 with a `--download-only` flag.  Duplicate of #5983.

**Closed by kalefranz** 2017-10-11 20:41 UTC

**Comment by hainm** [comment] 2017-10-11 20:55
thanks. 

> Duplicate of #5983.

actually this issue is opened before that issue.
