### ISSUE TITLE
Different basic environment activate the same environment but lead to different places

### ISSUE THREAD

**Issue by hnljq** [conda/conda#10786] opened 2021-07-12 16:09 UTC
I am using conda 4.8.3.
Now I found when I am in two different environments to activate a same environment , Gunicorn is in different places.

![image](https://user-images.githubusercontent.com/31721142/125320045-e94cd880-e36d-11eb-84ed-e967e08fe43b.png)

As the picture above, when I am  in the "base" environment, I activated the env "ocsr", and my "gunicorn" is in "/home/lijinqiang/.local/bin/gunicorn", but when I am not in any conda environment and activate the env "ocsr", my "gunicorn" is in the right place "/home/lijinqiang/.conda/envs/ocsr/bin/gunicorn". I am so confused.

**Comment by kenodegard** [comment] 2022-03-09 21:32
Not entirely sure what's going on but this seems to potentially be a duplicate of https://github.com/conda/conda/issues/11174, closing this for now.

**Closed by kenodegard** 2022-03-09 21:32 UTC
Labels: duplicate
