### ISSUE TITLE
Unable to update conda

### ISSUE THREAD

**Issue by Sanjeev2487** [conda/conda#3577] opened 2016-10-04 10:09 UTC
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : linux-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : /home/sanjeev/anaconda2  (writable)
default environment : /home/sanjeev/anaconda2
   envs directories : /home/sanjeev/anaconda2/envs
      package cache : /home/sanjeev/anaconda2/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /home/sanjeev/anaconda2/bin/conda update conda`

```
Traceback (most recent call last):
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
    prefix=prefix)
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
    for url in urls]
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
    res = f(*args, **kwargs)
  File "/home/sanjeev/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 137, in fetch_repodata
    .format(url, filename, e))
CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Missing dependencies for SOCKS support.
```

(root) sanjeev@sanjeev-pc:~/OpenBLAS$ python --version
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)

**Comment by soapy1** [comment] 2016-10-04 14:16
Duplicate of https://github.com/conda/conda/issues/3505

**Closed** 2017-05-01 20:03 UTC
