### ISSUE TITLE
UnavailableInvalidChannel bioconda

### ISSUE THREAD

**Issue by mdeea** [conda/conda#11031] opened 2021-11-09 08:12 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

This was working. Then I tried to make a new environment and suddenly it didn't work anymore.

conda create -n myENV
Collecting package metadata (current_repodata.json): done
Solving environment: done

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: bioconda
  channel url: https://conda.anaconda.org/bioconda
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

Tried it on a completely different server and it gave the same result.
I can see other people have had issues with this in the past.
I can see the url in a browser so what is the problem??

### Conda info

```shell
active environment : base
    active env location : /home/mdeea/miniconda3
            shell level : 1
       user config file : /home/mdeea/.condarc
 populated config files : /home/mdeea/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __cuda=11.2=0
                          __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/mdeea/miniconda3  (writable)
      conda av data dir : /home/mdeea/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mdeea/miniconda3/pkgs
                          /home/mdeea/.conda/pkgs
       envs directories : /home/mdeea/miniconda3/envs
                          /home/mdeea/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.1 Linux/4.15.0-161-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> /home/mdeea/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults
```

### Conda list

```shell
# packages in environment at /home/mdeea/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2021.10.26           h06a4308_2    defaults
certifi                   2021.10.8        py39h06a4308_0    defaults
cffi                      1.14.6           py39h400218f_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     4.10.3           py39h06a4308_0    defaults
conda-package-handling    1.7.3            py39h27cfd23_1    defaults
cryptography              35.0.0           py39hd23ed53_0    defaults
idna                      3.2                pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1l               h7f8727e_0    defaults
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 21.0.0             pyhd3eb1b0_1    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.1                hdb3f193_2    defaults
readline                  8.1                  h27cfd23_0    defaults
requests                  2.26.0             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
setuptools                58.0.4           py39h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tk                        8.6.11               h1ccaba5_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
tzdata                    2021e                hda174b7_0    defaults
urllib3                   1.26.7             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

**Comment by kenodegard** [comment] 2021-11-09 15:15
This appears to be a duplicate of #11032 and appears to have already been resolved.

**Closed by kenodegard** 2021-11-09 15:15 UTC
Labels: type::bug, source::community, duplicate
