### ISSUE TITLE
conda update bokeh --> unexpected error (IOError)

### ISSUE THREAD

**Issue by KjonVALIS** [conda/conda#1039] opened 2014-12-08 22:48 UTC
I've been looking forward to the new Bokeh release, but when I tried to update through conda, I received the traceback below. Any experience in resolving this would be helpful.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 397, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 563, in execute_plan
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 434, in extract
    t.extractall(path=path)
  File "C:\Anaconda\lib\tarfile.py", line 2047, in extractall
    self.extract(tarinfo, path)
  File "C:\Anaconda\lib\tarfile.py", line 2084, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Anaconda\lib\tarfile.py", line 2160, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Anaconda\lib\tarfile.py", line 2200, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Anaconda\\pkgs\\scipy-0.14.0-np19py27_0\\Lib\\site-packages\\scipy\\integrate\\_dop.pyd'

Current conda install:
             platform : win-64
        conda version : 3.7.3
  conda-build version : not installed
       python version : 2.7.5.final.0
     requests version : 2.5.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment] 2016-10-13 19:49
I can't reproduce this issue on the newest version of conda. Closing the issue; if this is still a problem for you after updating conda, please reopen the issue.

**Closed by soapy1** 2016-10-13 19:49 UTC
