### ISSUE TITLE
Permission error in conda when trying to install basemap

### ISSUE THREAD

**Issue by debrasaxton** [conda/conda#3019] opened 2016-07-08 18:38 UTC
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\dlsax_000>conda install -c conda-forge basemap
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\dlsax_000\Anaconda3:

The following NEW packages will be INSTALLED:

    basemap: 1.0.8.dev0-np111py35_1 conda-forge
    geos:    3.4.2-vc14_2           conda-forge [vc14]
    pyproj:  1.9.5.1-py35_0         conda-forge
    pyshp:   1.2.3-py35_0           conda-forge

The following packages will be UPDATED:

    conda:   4.1.4-py35_0                       --> 4.1.6-py35_0

Proceed ([y]/n)? y

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\dlsax_000\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\dlsax_000\Anaconda3\lib\site-packages\conda\install.py", line 236, in exp_backoff_fn
    result = fn(*args)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\dlsax_000\\Anaconda3\\pkgs\\conda-4.1.6-py35_0.tmp' -> 'C:\\Users\\dlsax_000\\Anaconda3\\pkgs\\conda-4.1.6-py35_0'

C:\Users\dlsax_000>

C:\Users\dlsax_000>

C:\Users\dlsax_000>

**Comment by jakirkham** [comment] 2016-07-12 22:00
As a redux, the issue is trying to upgrade `conda` to 4.1.6. Could you please generate a traceback just with upgrading `conda` and without any other channels or packages to verify this is the case?

**Comment by HugoTian** [comment] 2016-07-20 21:31
Please update conda, if "conda update conda" not working, please reinstall miniconda or anaconda.

I think this issue is fixed in new version of conda.

I will close this issue, and if there is still problem, feel free to reopen it and @ me

**Closed by HugoTian** 2016-07-20 21:31 UTC
