### ISSUE TITLE
conda update conda fail

### ISSUE THREAD

**Issue by H3zi** [conda/conda#7870] opened 2018-10-18 07:17 UTC
~ conda update conda
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/subdir_data.py", line 218, in _load
        mod_etag_headers.get('_mod'))
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/subdir_data.py", line 280, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/heziz/miniconda/lib/python2.7/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /home/heziz/miniconda/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
          COMPIZ_BIN_PATH=/usr/bin/
               CONDA_ROOT=/home/heziz/miniconda
              CONDA_SHLVL=0
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/heziz/miniconda/bin:/home/heziz/miniconda/envs/garage/bin:/home/
                          heziz/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:
                          /sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin
               PYTHONPATH=:/home/heziz/dev/theGarage
       REQUESTS_CA_BUNDLE=<not set>
        SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : None
            shell level : 0
       user config file : /home/heziz/.condarc
 populated config files : /home/heziz/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       base environment : /home/heziz/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/trax/linux-64
                          https://conda.anaconda.org/trax/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/heziz/miniconda/pkgs
                          /home/heziz/.conda/pkgs
       envs directories : /home/heziz/miniconda/envs
                          /home/heziz/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.12.4 CPython/2.7.13 Linux/4.15.0-36-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.

**Comment by ssidorenko** [comment] 2018-10-18 07:46
I don't really know conda's internals, but looking at the traceback and the verbose output here, I suspect null entries in https://conda.anaconda.org/anaconda/linux-64/repodata.json to be the culprit.

For example the entry `biopython-1.67-np111py27_0.tar.bz2` in the `packages` list is null.

**Comment by H3zi** [comment] 2018-10-18 08:34
This issue also effect `conda env update`...
I confirmed that altering the repodata.json cached file to not include entries with null value resolved this issue...
Any ETA from conda guys to fix this issue?

**Comment by cristi-zz** [comment] 2018-10-18 10:07
@randolf-scholz, thank you, it works. (at least now it is downloading packages)
Side question:
I removed the miniconda env and reinstalled older versions (4.5.4, 4.5.1, 4.4.10 and originally I had 4.3.x). All of them were crashing with roughly the same error. So I guess the problem is at anaconda's repodata.json file?

So, if one waits a while, the local conda instalation would start working, right?

Thnaks!

**Comment by family-guy** [comment] 2018-10-18 10:12
also tried this fix and it worked
any idea how to make a travis ci build that does `conda env create ..` pass?

**Comment by jeremyjliu** [comment] 2018-10-18 21:03
The problematic packages are:
```
    "bazel-0.11.1-hf484d3e_0.tar.bz2": null,
    "bazel-0.12.0-hf484d3e_0.tar.bz2": null,
    "bazel-0.14.0-hf484d3e_0.tar.bz2": null,
    "bazel-0.5.4-hf484d3e_1.tar.bz2": null,
    "biopython-1.66-np111py35_0.tar.bz2": null,
    "biopython-1.67-np110py34_0.tar.bz2": null,
    "biopython-1.67-np110py35_0.tar.bz2": null,
    "biopython-1.67-np111py27_0.tar.bz2": null,
```

Interestingly, these packages/versions exist with proper values in the upstream repodata.json, https://repo.continuum.io/pkgs/main (bazel) and https://repo.continuum.io/pkgs/free (biopython) so something may be up with the aggregation in the anaconda mirror. So you could work around by using those channels instead.

**Comment by jwindhager** [comment] 2018-10-19 09:17
I can confirm this issue for the latest miniconda release from the downloads page (conda 4.5.11). Note that for miniconda, one would need to rebuild for the quick (now: not so quick) fix mentioned above.

**Comment by wavemaster90** [comment] 2018-10-19 10:06
I came across the same error. The fix for me was to remove the anaconda channel from all of my environments and let conda-forge handle the packages.

It looks like the json response from the conda channel can't be parsed correctly, possibly because 'packages' is missing. Therefore the default value {} is being used, which causes the NoneType Error.

Is there currently a problem with this channel? Would it be possible to add a more specific error message for the future?

**Comment by itamarst** [comment] 2018-10-19 13:21
Happening to us too.

**Comment by mingwandroid** [comment] 2018-10-19 22:41
No one should use the `anaconda` channel. It is an internal channel only. Use `defaults` instead please.

**Comment by yuvval** [comment] 2018-10-20 10:50
FYI: Also happens when installing tensorflow-gpu package.
The workaround by @randolf-scholz solved the issue

**Comment by joosterman** [comment] 2018-10-22 09:03
> No one should use the `anaconda` channel. It is an internal channel only. Use `defaults` instead please.

This solved the issue for us.

**Comment by joosterman** [comment] 2018-10-22 09:16
> No one should use the `anaconda` channel. It is an internal channel only. Use `defaults` instead please.

This solved the issue for us.

**Comment by randolf-scholz** [comment] 2018-10-22 10:01
> No one should use the `anaconda` channel. It is an internal channel only. Use `defaults` instead please.

If this is the case, the conda team is not communicating it very well. Many official sources ask you to install packages directly from the anaconda channel, for example 

https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide

**Comment by randolf-scholz** [comment] 2018-10-22 10:08
> No one should use the `anaconda` channel. It is an internal channel only. Use `defaults` instead please.

Is there a source on this? Many 3rd parties ask users to use the anaconda channel, for example:

https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide

It seems to me that not using the anaconda channel is not really very well communicated guideline.

**Comment by LCAR979** [comment] 2018-10-23 03:06
> I came across the same error. The fix for me was to remove the anaconda channel from all of my environments and let conda-forge handle the packages.
> 
> It looks like the json response from the conda channel can't be parsed correctly, possibly because 'packages' is missing. Therefore the default value {} is being used, which causes the NoneType Error.
> 
> Is there currently a problem with this channel? Would it be possible to add a more specific error message for the future?

Same error here when try to install h5py module using `conda install -c anaconda h5py`.   
And thanks for your post, I turned to `conda install -c conda-forge/label/gcc7 h5py`, then successfully installed.

**Comment by yamacgulfidan** [comment] 2018-10-23 12:28
Hi I have the similar issue, I'm using azure batch-AI and working with docker, so doing the fix from conda libraries is not an option for me, any ideas ?

**Comment by cristi-zz** [comment] 2018-10-24 13:48
I did a fresh install of miniconda-latest yesterday and the issue seem to be gone (i DID NOT touch the conda source code or played with channels [except add whatever I was needing] ) The conda version reported by ```conda list conda``` is 4.5.11 py37_0. Hmmmm...

**Comment by bgreen-litl** [comment] 2018-10-26 19:28
> No one should use the `anaconda` channel. It is an internal channel only. Use `defaults` instead please.

The anaconda channel seems to have some packages that default does not though.

I added the channel to my environment.yml a while back because it contains the version of redis I need.  This has been working fine and now suddenly does not work.  Suggestions?

`NoPackagesFoundError: Package missing in current linux-64 channels: 
  - redis 4.0.11*`

**Comment by Jamie725** [comment] 2018-10-29 06:34
I tried: 
conda install python=3.6 tensorflow-gpu.
and it works

**Comment by nehaljwani** [comment] 2018-11-03 10:55
@bgreen-litl redis 4.0.11 for linux-64 is indeed available in defaults.
```
(base) bash-4.1# conda search redis=4.0.11
Loading channels: done
# Name                  Version           Build  Channel
redis                    4.0.11      h14c3975_0  pkgs/main
```

@Jamie725 You had to restrict python to 3.6 because tensorflow doesn't support 3.7 officially yet.

**Comment by nehaljwani** [comment] 2018-11-03 10:56
The original issue was due to bad metadata in https://conda.anaconda.org/anaconda/linux-64/repodata.json , as correctly pointed out by @ssidorenko , which has been fixed. Closing.

**Closed by nehaljwani** 2018-11-03 10:56 UTC
