### ISSUE TITLE
can you help me？ I don't know why have this problem

### ISSUE THREAD

**Issue by YSZYCF** [conda/conda#6124] opened 2017-10-09 14:02 UTC
C:\Users\Mowar>conda uninstall seaborn
Fetching package metadata .............
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : G:\Anaconda2  (writable)
    default environment : G:\Anaconda2
       envs directories : G:\Anaconda2\envs
                          C:\Users\Mowar\AppData\Local\conda\conda\envs
                          C:\Users\Mowar\.conda\envs
          package cache : G:\Anaconda2\pkgs
                          C:\Users\Mowar\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.12.4 CPython/2.7.13 Windows/7 Windows/6.1.7601
          administrator : False

`$ G:\Anaconda2\Scripts\conda uninstall seaborn`

    Traceback (most recent call last):
      File "G:\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "G:\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "G:\Anaconda2\lib\site-packages\conda\cli\main_remove.py", line 141, in execute
        prefix=prefix)
      File "G:\Anaconda2\lib\site-packages\conda\core\index.py", line 106, in get_index
        _supplement_index_with_prefix(index, prefix, known_channels)
      File "G:\Anaconda2\lib\site-packages\conda\core\index.py", line 32, in _supplement_index_with_prefix
        for dist, info in iteritems(linked_data(prefix)):
      File "G:\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "G:\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "G:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "G:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "G:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "G:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Invalid value 1506081004.8 for timestamp

**Comment by nehaljwani** [comment] 2017-10-09 14:24
Closing as duplicate of #6096 

Solution for you is to delete all files with the timestamp value in decimal. You can use the following to find out those files, and then use `del` to delete them:
```
findstr /s /m /i /r /c:"timestamp\": [0-9]*\." G:\Anaconda2\conda-meta\*.json
```

**Closed by nehaljwani** 2017-10-09 14:24 UTC
