### ISSUE TITLE
Conda skeleton uwsgi error

### ISSUE THREAD

**Issue by maruina** [conda/conda#1042] opened 2014-12-11 12:14 UTC
Hi!
After reading here
https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/JVxrCz9TZlI/s3rwBxzXIQ0J
I'm trying to build my uwsgi package. I can't use Travis' version because I'm on CentOS 6.5 and I have a different LIBC version.

When I try to build the skeleton, I have this error
```
conda skeleton pypi uWSGI
Using url https://pypi.python.org/packages/source/u/uWSGI/uwsgi-2.0.8.tar.gz (758 KB) for uWSGI.
Downloading uWSGI (use --no-download to skip this step)
Using cached download
Unpacking uWSGI...
done
working in /tmp/tmp1BQ3f1conda_skeleton_uwsgi-2.0.8.tar.gz
Fetching package metadata: ...
Solving package specifications: .
Applying patch: '/tmp/tmp1BQ3f1conda_skeleton_uwsgi-2.0.8.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/miniconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 131, in main
    args_func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 142, in execute
    pypi.main(args, parser)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/pypi.py", line 372, in main
    get_package_metadata(args, package, d, data)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_build/pypi.py", line 563, in get_package_metadata
    d['homeurl'] = data['homeurl']
KeyError: 'homeurl'
```

This is my conda info
```
conda info
Current conda install:

             platform : linux-64
        conda version : 3.7.3
  conda-build version : 1.9.1
       python version : 2.7.8.final.0
     requests version : 2.5.0
     root environment : /opt/miniconda  (writable)
  default environment : /opt/miniconda
     envs directories : /opt/miniconda/envs
        package cache : /opt/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
```

**Comment by soapy1** [comment] 2016-10-13 19:44
I can't reproduce this issue on the newest version of conda. Closing the issue; if this is still a problem for you after updating conda, please reopen the issue.

**Closed by soapy1** 2016-10-13 19:44 UTC
