### ISSUE TITLE
miniconda2 installs Python 3.5.2 when creating new env

### ISSUE THREAD

**Issue by geramirez** [conda/conda#3192] opened 2016-07-29 14:24 UTC
# How to recreate the issue:

```bash
### Run the cflinuxfs2 Docker image
docker run -it cloudfoundry/cflinuxfs2 bash
### Install miniconda
wget https://repo.continuum.io/miniconda/Miniconda2-4.1.11-Linux-x86_64.sh
chmod +x Miniconda2-4.1.11-Linux-x86_64.sh
./Miniconda2-4.1.11-Linux-x86_64.sh 
### Download environment.yaml file
wget https://raw.githubusercontent.com/cloudfoundry/python-buildpack/develop/cf_spec/fixtures/miniconda_simple_app_python_2/environment.yml
### Create env 
conda env update -n dep_env -f environment.yml
### Activate env
source activate dep_env
### Check Python version
python --version
```

The python version appears as `Python 3.5.2 :: Continuum Analytics, Inc.` when we expect 2.7.11. We expect Python version 2 because we downloaded and installed miniconda 2. 

Note: we are not sure if this is a bug or a new feature. 

-- @RochesterinNYC

**Comment by HugoTian** [comment] 2016-07-29 14:30
please show your "conda info" and environment.yml, so that we can reproduce the case.

Thanks in advance

**Comment by geramirez** [comment] 2016-07-29 17:38
Here is the info you requested:

## Conda Info
```
(dep_env) root@39a2ce8d523c:/# conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : not installed
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /root/miniconda2  (writable)
  default environment : /root/miniconda2/envs/dep_env
     envs directories : /root/miniconda2/envs
        package cache : /root/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

## conda list -n dep_env
```
(dep_env) root@39a2ce8d523c:/# conda list -n dep_env
# packages in environment at /root/miniconda2/envs/dep_env:
#
click                     6.6                      py35_0
flask                     0.11.1                   py35_0
itsdangerous              0.24                     py35_0
jinja2                    2.8                      py35_1
libgfortran               3.0.0                         1
markupsafe                0.23                     py35_2
mkl                       11.3.3                        0
nose                      1.3.7                    py35_1
numpy                     1.10.4                   py35_2
openssl                   1.0.2h                        1
pandas                    0.18.0              np110py35_0
pip                       8.1.2                    py35_0
py                        1.4.31                   py35_0
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.6.1                 py35_0
readline                  6.2                           2
scikit-learn              0.17.1              np110py35_2
scipy                     0.17.0              np110py35_4
setuptools                23.0.0                   py35_0
six                       1.10.0                   py35_0
sqlite                    3.13.0                        0
tk                        8.5.18                        0
werkzeug                  0.11.10                  py35_0
wheel                     0.29.0                   py35_0
xz                        5.2.2                         0
zlib                      1.2.8                         3
```

Also, we did not specify the version of python in the environment.yml. Below is the environment.yml we used:

```
name: pydata_test
dependencies:
- pip
- pytest
- flask
- nose
- numpy=1.10.4
- scipy=0.17.0
- scikit-learn=0.17.1
- pandas=0.18.0
```

**Comment by HugoTian** [comment] 2016-07-29 17:59
The python update comes from the resolve module, which I am not quite familiar with. However, the resolver tells me that 

    'python-3.5.2-0.tar.bz2',

will be installed in your environment, and I guess in your package list, there is some packages depends on py35, and that's the reason for this update.

I will go deep into the code, see whether I can give your a more detailed answer. And I do not think this is a bug for conda.

Thanks

**Comment by geramirez** [comment] 2016-07-29 21:54
Thanks for looking into this. We opened the issue because the behavior above wasn't present in miniconda 4.0.5. It appeared with 4.1.11.

**Comment by HugoTian** [comment] 2016-07-29 21:56
@geramirez , I believe @mcg1969  can give you a better answer, and I will also learn more about resolver from him.

Thanks

**Comment by mcg1969** [comment] 2016-07-29 22:17
I frankly doubt this is a solver issue. Rather, my guess is that it has something to do with the way `environment.yml` is handled versus standard command-line specs. The function `add_defaults_to_specs` is the one that adds a `python=2.7` spec to your spec list, to ensure that it doesn't update to Python 3.5.

One thing that would be very helpful is if you could do `conda --debug env update -n dep_env -f environment.yml` and paste the output here. We don't need the output where it starts installing the files, just everything before that.

**Comment by HugoTian** [comment] 2016-08-01 13:58
@geramirez, thanks for hint from mcg1969, I think I find a solution for your problem, 

You update the envronment through conda-env, and there is no add_defaults_to_specs in condo-env. However you can update your environment through conda, try

    conda update -n your_env --file your.yml

In this command, it will add the default python(with target tar file) to the action, and I think you will get the correct update

**Comment by HugoTian** [comment] 2016-08-02 18:02
I double checked the conda update behavior and I think use conda update will avoid this issue that caused by conda env update.

I will close this issue and feel free to reopen it and @ me

**Closed by HugoTian** 2016-08-02 18:02 UTC

**Comment by geramirez** [comment] 2016-08-03 02:31
Thanks for looking into this. On our end, we were able to partially fix the issue by locking down the Python version, but we'll try out the recommended fix.
