### ISSUE TITLE
Uncaught backoff error upon module update

### ISSUE THREAD

**Issue by chiffa** [conda/conda#6814] opened 2018-01-29 21:05 UTC
**I'm submitting a...**
bug report

## Current Behavior
Failure to update the scikit-image module due to an uncaught backoff error

### Steps to Reproduce
On the current system state, a `conda update scikits-image` leads to this behavior

## Expected Behavior
Just update to the latest version

## Environment Information
WARNING conda.gateways.disk:exp_backoff_fn(47): Uncaught backoff with errno EEXIST 17
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.21.2
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda2  (writable)
    default environment : C:\Anaconda2
       envs directories : C:\Anaconda2\envs
                          C:\Users\Andrei\AppData\Local\conda\conda\envs
                          C:\Users\Andrei\.conda\envs
          package cache : C:\Anaconda2\pkgs
                          C:\Users\Andrei\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.17074
          administrator : False

`$ C:\Anaconda2\Scripts\conda update scikit-image`

    Traceback (most recent call last):
      File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "C:\Anaconda2\lib\site-packages\conda\core\package_cache.py", line 492, in execute
        self._execute_action(action)
      File "C:\Anaconda2\lib\site-packages\conda\core\package_cache.py", line 506, in _execute_action
        action.reverse()
      File "C:\Anaconda2\lib\site-packages\conda\core\path_actions.py", line 838, in reverse
        backoff_rename(self.hold_path, self.target_full_path)
      File "C:\Anaconda2\lib\site-packages\conda\gateways\disk\update.py", line 53, in backoff_rename
        exp_backoff_fn(rename, source_path, destination_path, force)
      File "C:\Anaconda2\lib\site-packages\conda\gateways\disk\__init__.py", line 28, in exp_backoff_fn
        result = fn(*args, **kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\gateways\disk\update.py", line 47, in rename
        os_rename(source_path, destination_path)
    WindowsError: [Error 183] Cannot create a file when that file already exists

**Comment by kalefranz** [comment] 2018-01-31 19:53
I think probably related to https://github.com/conda/conda/issues/6631

**Comment by kalefranz** [comment] 2018-02-24 10:19
I do believe this is pretty much a duplicate of #6631.  That's turning out to be a particularly hard issue to solve, but the severity attached to it ensures that it won't get lost.

**Closed by kalefranz** 2018-02-24 10:19 UTC
Labels: source:community, type:bug
