### ISSUE TITLE
'conda update --all' failed.

### ISSUE THREAD

**Issue by koyano** [conda/conda#6212] opened 2017-10-22 19:16 UTC
Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.5.0.final.0
       requests version : 2.18.4
       root environment : /home/username/.pyenv/versions/anaconda3-4.4.0  (writabl                                                           e)
    default environment : /home/username/.pyenv/versions/anaconda3-4.4.0
       envs directories : /home/username/.pyenv/versions/anaconda3-4.4.0/envs
                          /home/username/.conda/envs
          package cache : /home/username/.pyenv/versions/anaconda3-4.4.0/pkgs
                          /home/username/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.5.0 Linux/4.4.0                                                           -96-generic debian/stretch/sid glibc/2.23
                UID:GID : 1003:1003

`$ /home/username/.pyenv/versions/anaconda3-4.4.0/bin/conda update --all`

    Traceback (most recent call last):
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance                                                           , val))
      File "/home/username/.pyenv/versions/anaconda3-4.4.0/lib/python3.5/site-pack                                                           ages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1505693395.20                                                           6 for timestamp

**Comment by kalefranz** [comment] 2017-10-23 15:56
Duplicate of https://github.com/conda/conda/issues/6096.  See that issue for solutions.

**Closed by kalefranz** 2017-10-23 15:56 UTC
