### ISSUE TITLE
Assertion error when use 'conda list' , conda==4.6.2 but bug also appears in 4.6.1

### ISSUE THREAD

**Issue by DingXiangYuanZhiXing** [conda/conda#8196] opened 2019-01-31 13:37 UTC
## Current Behavior
```
(base) PS C:\Users\Sevenpure> conda list

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 116, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 145, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 69, in load
        self._load_site_packages()
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 258, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 245, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 78, in init
        return PythonInstalledDistribution(prefix_path, anchor_file, python_version)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 382, in __init__
        super(PythonInstalledDistribution, self).__init__(anchor_full_path, python_version)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 106, in __init__
        self._check_files()
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 116, in _check_files
        assert isfile(fpath)
    AssertionError

`$ C:\Users\Sevenpure\Anaconda3\Scripts\conda-script.py list`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=C:\Program Files\APPLICATION\Xpress\lib\xprm.jar;C:\Program
                          Files\APPLICATION\Xpress\lib\xprs.jar;C:\Program
                          Files\APPLICATION\Xpress\lib\xprb.jar;C:\Program Files\APPLICATION\Mos
                          ek\8\tools\platform\win64x86\bin\mosek.jar;C:\Program Files\APPLICATIO
                          N\Mosek\8\tools\platform\win64x86\bin\fusion.jar;C:\Program
                          Files\APPLICATION\Mosek\9.0\tools\platform\win64x86\bin\mosek.jar
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Sevenpure\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\Sevenpure\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Sevenpure\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\Sevenpure\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
                 HOMEPATH=\Users\Sevenpure
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\Sevenpure\Anaconda3\Library\bin;C:\Users\Sevenpure\Anaconda3;C:\U
                          sers\Sevenpure\Anaconda3/Library/mingw-w64/bin;C:\Users\Sevenpure\Anaconda
                          3/Library/usr/bin;C:\Users\Sevenpure\Anaconda3/Library/bin;C:\Users\Shan
                          wen\Anaconda3/Scripts;C:\Users\Sevenpure\Anaconda3/bin;C:\Users\Sevenpure\
                          Anaconda3\condabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\
                          Wbem;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\iCLS\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Windows\System32\WindowsPowerShell
                          \v1.0\;C:\Users\Sevenpure\Anaconda3;C:\Users\Sevenpure\Anaconda3\Library\m
                          ingw-w64\bin;C:\Users\Sevenpure\Anaconda3\Library\usr\bin;C:\Users\Shanw
                          en\Anaconda3\Library\bin;C:\Users\Sevenpure\Anaconda3\Scripts;C:\Program
                          Files\APPLICATION\Matlab\runtime\win64;C:\Program
                          Files\APPLICATION\Matlab\bin;C:\Program
                          Files\APPLICATION\Mosek\9.0\tools\platform\win64x86\bin;C:\Program
                          Files\APPLICATION\Mosek\8\tools\platform\win64x86\bin;C:\Program
                          Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;C:\texlive\2018\bin\win32;C:\Program
                          Files\APPLICATION\Xpress\bin;C:\Program
                          Files\APPLICATION\Xpress\workbench;C:\Program
                          Files\APPLICATION\Gurobi\win64\bin;C:\Program
                          Files\APPLICATION\CPLEX\opl\bin\x64_win64;C:\Program
                          Files\APPLICATION\CPLEX\opl\oplide\;C:\Program
                          Files\APPLICATION\CPLEX\cplex\bin\x64_win64;C:\Program Files\APPLICATI
                          ON\CPLEX\cpoptimizer\bin\x64_win64;C:\Windows\System32\OpenSSH\;C:\Pro
                          gram Files\dotnet\;C:\Program Files (x86)\Wolfram
                          Research\WolframScript\;C:\Program Files\APPLICATION\Git\cmd;C:\Users\
                          Sevenpure\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\APPLICATION\PyCharm\bin;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\Users\Sevenpure\AppData\Local\GitHubDesktop\bin;C:\Users\Sevenpure\
                          Anaconda3\lib\site-
                          packages\pywin32_system32;C:\Users\Sevenpure\Anaconda3\lib\site-
                          packages\pywin32_system32
             PSMODULEPATH=C:\Users\Sevenpure\Documents\WindowsPowerShell\Modules;C:\Program Files\
                          WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\M
                          odules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Sevenpure\Anaconda3
            shell level : 1
       user config file : C:\Users\Sevenpure\.condarc
 populated config files : C:\Users\Sevenpure\.condarc
          conda version : 4.6.2
    conda-build version : 3.16.3
         python version : 3.6.6.final.0
       base environment : C:\Users\Sevenpure\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://conda.anaconda.org/gurobi/win-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Sevenpure\Anaconda3\pkgs
                          C:\Users\Sevenpure\.conda\pkgs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Sevenpure\Anaconda3\envs
                          C:\Users\Sevenpure\.conda\envs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

## Steps to Reproduce
In my pc, just type in :
conda list

## Expected Behavior
display the list of my conda packages.

## Environment Information

```
(base) PS C:\Users\Sevenpure> conda info
     active environment : base
    active env location : C:\Users\Sevenpure\Anaconda3
            shell level : 1
       user config file : C:\Users\Sevenpure\.condarc
 populated config files : C:\Users\Sevenpure\.condarc
          conda version : 4.6.2
    conda-build version : 3.16.3
         python version : 3.6.6.final.0
       base environment : C:\Users\Sevenpure\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://conda.anaconda.org/gurobi/win-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Sevenpure\Anaconda3\pkgs
                          C:\Users\Sevenpure\.conda\pkgs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Sevenpure\Anaconda3\envs
                          C:\Users\Sevenpure\.conda\envs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by kalefranz** [comment] 2019-01-31 14:48
Duplicate of #8178 fixed with #8184.

**Closed by kalefranz** 2019-01-31 14:48 UTC

**Comment by DingXiangYuanZhiXing** [comment] 2019-01-31 16:04
# Problem with 'conda install' instead of 'conda list'

I have updated my numpy=1.15.4 and somehow the bug solved itself.
But when I want to install scipy=1.2.0 , another bug shows up.

## Current Behavior
```
(base) PS C:\Users\Sevenpure> conda install scipy=1.2.0
Collecting package metadata: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 294, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1814, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1614, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 294, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1814, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1614, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 294, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1814, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1614, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 294, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1814, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1614, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 294, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1814, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1631, in _raise_ssl_error
        raise SysCallError(errno, errorcode.get(errno))
    OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\response.py", line 360, in _error_catcher
        yield
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\response.py", line 669, in read_chunked
        chunk = self._handle_chunk(amt)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\response.py", line 615, in _handle_chunk
        value = self._fp._safe_read(amt)
      File "C:\Users\Sevenpure\Anaconda3\lib\http\client.py", line 612, in _safe_read
        chunk = self.fp.read(min(amt, MAXAMOUNT))
      File "C:\Users\Sevenpure\Anaconda3\lib\socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 309, in recv_into
        return self.recv_into(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 309, in recv_into
        return self.recv_into(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 309, in recv_into
        return self.recv_into(*args, **kwargs)
      [Previous line repeated 1 more time]
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 299, in recv_into
        raise SocketError(str(e))
    OSError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\requests\models.py", line 750, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\response.py", line 490, in stream
        for line in self.read_chunked(amt, decode_content=decode_content):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\response.py", line 694, in read_chunked
        self._original_response.close()
      File "C:\Users\Sevenpure\Anaconda3\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\urllib3\response.py", line 378, in _error_catcher
        raise ProtocolError('Connection broken: %r' % e, e)
    urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\cli\install.py", line 253, in install
        force_reinstall=context.force_reinstall or context.force,
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\solve.py", line 107, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\solve.py", line 145, in solve_for_diff
        force_remove)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\solve.py", line 235, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\solve.py", line 285, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\solve.py", line 675, in _prepare
        self.subdirs, prepared_specs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\index.py", line 213, in get_reduced_index
        new_records = query_all(spec)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\index.py", line 176, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 93, in query
        self.load()
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 147, in load
        _internal_state = self._load()
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 218, in _load
        mod_etag_headers.get('_mod'))
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 429, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\requests\sessions.py", line 686, in send
        r.content
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\requests\models.py", line 828, in content
        self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
      File "C:\Users\Sevenpure\Anaconda3\lib\site-packages\requests\models.py", line 753, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))

`$ C:\Users\Sevenpure\Anaconda3\Scripts\conda-script.py install scipy=1.2.0`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=C:\Program Files\APPLICATION\Xpress\lib\xprm.jar;C:\Program
                          Files\APPLICATION\Xpress\lib\xprs.jar;C:\Program
                          Files\APPLICATION\Xpress\lib\xprb.jar;C:\Program Files\APPLICATION\Mos
                          ek\8\tools\platform\win64x86\bin\mosek.jar;C:\Program Files\APPLICATIO
                          N\Mosek\8\tools\platform\win64x86\bin\fusion.jar;C:\Program
                          Files\APPLICATION\Mosek\9.0\tools\platform\win64x86\bin\mosek.jar
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Sevenpure\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\Sevenpure\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Sevenpure\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\Sevenpure\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
                 HOMEPATH=\Users\Sevenpure
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\Sevenpure\Anaconda3;C:\Users\Sevenpure\Anaconda3/Library/mingw-w6
                          4/bin;C:\Users\Sevenpure\Anaconda3/Library/usr/bin;C:\Users\Sevenpure\Anac
                          onda3/Library/bin;C:\Users\Sevenpure\Anaconda3/Scripts;C:\Users\Sevenpure\
                          Anaconda3/bin;C:\Users\Sevenpure\Anaconda3\condabin;C:\Windows\system32;
                          C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\iCLS\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Windows\System32\WindowsPowerShell
                          \v1.0\;C:\Users\Sevenpure\Anaconda3;C:\Users\Sevenpure\Anaconda3\Library\m
                          ingw-w64\bin;C:\Users\Sevenpure\Anaconda3\Library\usr\bin;C:\Users\Shanw
                          en\Anaconda3\Library\bin;C:\Users\Sevenpure\Anaconda3\Scripts;C:\Program
                          Files\APPLICATION\Matlab\runtime\win64;C:\Program
                          Files\APPLICATION\Matlab\bin;C:\Program
                          Files\APPLICATION\Mosek\9.0\tools\platform\win64x86\bin;C:\Program
                          Files\APPLICATION\Mosek\8\tools\platform\win64x86\bin;C:\Program
                          Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;C:\texlive\2018\bin\win32;C:\Program
                          Files\APPLICATION\Xpress\bin;C:\Program
                          Files\APPLICATION\Xpress\workbench;C:\Program
                          Files\APPLICATION\Gurobi\win64\bin;C:\Program
                          Files\APPLICATION\CPLEX\opl\bin\x64_win64;C:\Program
                          Files\APPLICATION\CPLEX\opl\oplide\;C:\Program
                          Files\APPLICATION\CPLEX\cplex\bin\x64_win64;C:\Program Files\APPLICATI
                          ON\CPLEX\cpoptimizer\bin\x64_win64;C:\Windows\System32\OpenSSH\;C:\Pro
                          gram Files\dotnet\;C:\Program Files (x86)\Wolfram
                          Research\WolframScript\;C:\Program Files\APPLICATION\Git\cmd;C:\Users\
                          Sevenpure\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\APPLICATION\PyCharm\bin;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\Users\Sevenpure\AppData\Local\GitHubDesktop\bin;C:\Users\Sevenpure\
                          Anaconda3\lib\site-
                          packages\pywin32_system32;C:\Users\Sevenpure\Anaconda3\lib\site-
                          packages\pywin32_system32
             PSMODULEPATH=C:\Users\Sevenpure\Documents\WindowsPowerShell\Modules;C:\Program Files\
                          WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\M
                          odules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Sevenpure\Anaconda3
            shell level : 1
       user config file : C:\Users\Sevenpure\.condarc
 populated config files : C:\Users\Sevenpure\.condarc
          conda version : 4.6.2
    conda-build version : 3.16.3
         python version : 3.6.8.final.0
       base environment : C:\Users\Sevenpure\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://conda.anaconda.org/gurobi/win-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Sevenpure\Anaconda3\pkgs
                          C:\Users\Sevenpure\.conda\pkgs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Sevenpure\Anaconda3\envs
                          C:\Users\Sevenpure\.conda\envs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

## Steps to Reproduce
In my pc, just type in :
conda install any packages

## Expected Behavior
install the specific package I want to install.


## Environment Information

```
(base) PS C:\Users\Sevenpure> conda info

     active environment : base
    active env location : C:\Users\Sevenpure\Anaconda3
            shell level : 1
       user config file : C:\Users\Sevenpure\.condarc
 populated config files : C:\Users\Sevenpure\.condarc
          conda version : 4.6.2
    conda-build version : 3.16.3
         python version : 3.6.8.final.0
       base environment : C:\Users\Sevenpure\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://conda.anaconda.org/gurobi/win-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Sevenpure\Anaconda3\pkgs
                          C:\Users\Sevenpure\.conda\pkgs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Sevenpure\Anaconda3\envs
                          C:\Users\Sevenpure\.conda\envs
                          C:\Users\Sevenpure\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by DingXiangYuanZhiXing** [comment] 2019-01-31 16:08
sorry , I don't know if it's the same bug as  #8178.

**Comment by DingXiangYuanZhiXing** [comment] 2019-01-31 16:13
I downgrade my python to 3.6.6 and the 'conda install scipy=1.2.0' bug fixed.
