### ISSUE TITLE
Switching python 3.6 -> 3.5 with conda env breaks conda

### ISSUE THREAD

**Issue by pvanderlinden** [conda/conda#4902] opened 2017-03-20 16:14 UTC
Easiest to reproduce this, is to use the latest miniconda3 docker image, and then make an environment.yml file with the following contents:
```
name: root
dependencies:
- python=3.5
- pip:
  - bson
```
When running `conda env update` you will get the following error:
```
Unable to install package for pip.

Please double check and ensure you dependencies file has
the correct spelling.  You might also try installing the
conda-env-pip package to see if provides the required
installer.
```
The combination of changing python 3.6 to 3.5 and also installing a pip package with the same environment file breaks the installer.

**Comment by kalefranz** [comment] 2017-05-16 03:04
duplicate of #4985

**Closed by kalefranz** 2017-05-16 03:04 UTC
Labels: source:community, tag:conda-env, type:bug
