### ISSUE TITLE
Getting unexpected error when an update is being done from anaconda-notebook

### ISSUE THREAD

**Issue by Sanojkumar** [conda/conda#2272] opened 2016-03-16 17:44 UTC
Traceback (most recent call last):
conda info

  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    try:
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
    plan = plan_from_actions(actions)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    def UNLINK_CMD(state, arg):
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 689, in unlink
    'type': link_name_map.get(linktype)}
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Anaconda3\conda-meta\conda-3.18.5-py34_0.json'

**Comment by kalefranz** [comment] 2017-05-09 05:10
Example of conda "uninstalling" itself after a failed update.  Root cause fixed in conda 4.3.

**Closed by kalefranz** 2017-05-09 05:10 UTC
