### ISSUE TITLE
Fail to install any modules in anaconda 5.0

### ISSUE THREAD

**Issue by LouieLIUJ** [conda/conda#6056] opened 2017-10-02 15:00 UTC
I have spent hours to install tensorflow in anaconda 5.0. I used "anaconda search -t conda tensorflow" and cmd returned :

Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\L\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\L\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\L\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\L\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\ProgramData\Anaconda3\Scripts\conda install numpy`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 144, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
        timeout=timeout
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
        self._prepare_proxy(conn)
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
        conn.connect()
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kalefranz** [comment] 2017-10-02 21:04
Please provide the output of `conda instal -vv numpy`

**Comment by LouieLIUJ** [comment] 2017-10-02 23:57
The output of conda install -vv numpy is:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 144, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
        timeout=timeout
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
        self._prepare_proxy(conn)
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
        conn.connect()
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kalefranz** [comment] 2017-10-03 00:28
What is the output of

    python -c "import requests; print(requests.__version__)"

and

    python -c "import urllib3; print(urllib3.__version__)"

**Comment by LouieLIUJ** [comment] 2017-10-03 00:31
The output of 
python -c "import requests; print(requests.__version__)" 
is
2.18.4

The output of 
python -c "import urllib3; print(urllib3.__version__)"
is
1.22

**Comment by LouieLIUJ** [comment] 2017-10-03 00:31
The output of
`python -c "import requests; print(requests.version)"`
is
`2.18.4`

The output of
`python -c "import urllib3; print(urllib3.version)"`
is
`1.22`

**Comment by kalefranz** [comment] 2017-10-03 02:30
Still not seeing what's going on exactly...

Can you provide the output of

    conda config --show-sources

and 

    env | sort

**Comment by NeoNeuron** [comment] 2017-10-04 07:42
I am facing exact the same issue, and cannot figure it out yet.

**Comment by LouieLIUJ** [comment] 2017-10-04 07:56
I feel desperate now! However, I install tensorflow in Linux successfully.

**Comment by kalefranz** [comment] 2017-10-04 14:44
Please provide more information, as requested above.

**Comment by LouieLIUJ** [comment] 2017-10-04 15:02
The return of conda config --show-sources is
`==> C:\Users\L\.condarc <==
channels:
  - defaults
show_channel_urls: True`

the return of set is
`ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\L\AppData\Roaming
asl.log=Destination=file
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=MI-AIR-13
ComSpec=C:\Windows\system32\cmd.exe
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\L
LOCALAPPDATA=C:\Users\L\AppData\Local
LOGONSERVER=\\MI-AIR-13
MOZ_PLUGIN_PATH=C:\Program Files (x86)\Nuance\PDF Professional 8\Bin\
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\L\OneDrive
OS=Windows_NT
Path=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\MATLAB\MATLAB Production Server\R2015a\runtime\win64;C:\Program Files\MATLAB\MATLAB Production Server\R2015a\bin;C:\Program Files\MATLAB\MATLAB Production Server\R2015a\polyspace\bin;C:\Users\L\AppData\Local\Microsoft\WindowsApps;C:\texlive\2016\bin\win32
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\L\AppData\Local\Temp
TMP=C:\Users\L\AppData\Local\Temp
USERDOMAIN=MI-AIR-13
USERDOMAIN_ROAMINGPROFILE=MI-AIR-13
USERNAME=L
USERPROFILE=C:\Users\L
windir=C:\Windows`

**Comment by foxl-studio** [comment] 2017-10-05 04:13
I faced same issue in Win 10 Enterprise.
And dug into source codes, tried adding some output, then found at urllib3.connectionpool:_prepare_proxy function, the self._proxy_host is none, but in _new_conn function, it had data.  That's why the first exception ['NoneType' object has no attribute 'startswith'], since the host is [None].
I'm not familiar with python, so cannot debug for more. But looks like something wrong in net work proxy for HTTPS.
Hope someone can find the exact cause.

**Comment by kalefranz** [comment] 2017-10-05 18:17
@LouieLIUJ  In the past this error has related to incorrect proxy configuration.  Can you explore that as a possibility and report back?

**Comment by kalefranz** [comment] 2017-10-05 18:25
Related to or duplicate of #3962.

**Comment by kalefranz** [comment] 2017-10-05 18:28
Please move future discussion to #3962.

**Closed by kalefranz** 2017-10-05 18:28 UTC

**Comment by LouieLIUJ** [comment] 2017-10-05 23:48
I guess that the problem is relating to VPN software. I have checked the file .condarc and think this file is normal. I am trying to fix this problem now.
