### ISSUE TITLE
Conda (4.6.9 and 4.6.11) broken in (git) Bash on windows, No command "conda conda"

### ISSUE THREAD

**Issue by jenshnielsen** [conda/conda#8506] opened 2019-04-05 07:48 UTC
Running any conda command in bash on windows with conda versions 4.6.9 and 4.6.11 results in an error. 

## Current Behavior
Running conda or any subcommand in bash on windows result in. 

```bash
$ conda

CommandNotFoundError: No command 'conda conda'.
```

### Steps to Reproduce
This is reproduced using any conda command on in bash window
```
conda
```
The error is also printed during the sourcing of .bashrc that contains 
```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval "$('/c/Users/jenielse/AppData/Local/Continuum/miniconda3/Scripts/conda.exe' 'shell.bash' 'hook')"
# <<< conda initialize <<<
```

Conda does seem to work correctly in `cmd.exe`
## Expected Behavior

Conda should work normally in bash too

## Environment Information
As Conda does not work at all in bash the information below is grabbed from conda in `cmd.exe`

<details open><summary><code>`conda info`</code></summary><p>

```
C:\Users\jenielse>conda info

     active environment : None
            shell level : 0
       user config file : C:\Users\jenielse\.condarc
 populated config files : C:\Users\jenielse\.condarc
          conda version : 4.6.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : C:\Users\jenielse\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\jenielse\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\jenielse\.conda\pkgs
                          C:\Users\jenielse\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\jenielse\.conda\envs
                          C:\Users\jenielse\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\jenielse\.condarc <==
pip_interop_enabled: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
C:\Users\jenielse>conda list --show-channel-urls
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at C:\Users\jenielse\AppData\Local\Continuum\miniconda3:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3            py37h28b3542_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
attrs                     19.1.0                   py37_1    defaults
automat                   0.7.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.12.2           py37h7a1dbc1_1    defaults
chardet                   3.0.4                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
conda                     4.6.11                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
constantly                15.1.0           py37h28b3542_0    defaults
cryptography              2.6.1            py37h7a1dbc1_0    defaults
cryptography-vectors      2.6.1                      py_0    defaults
cycler                    0.10.0                   py37_0    defaults
decorator                 4.4.0                    py37_1    defaults
entrypoints               0.3                      py37_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
html5lib                  1.0.1                    py37_0    defaults
hyperlink                 18.0.0                   py37_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.8                      py37_0    defaults
incremental               17.5.0                   py37_0    defaults
intel-openmp              2019.3                      203    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.4.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
isort                     4.3.16                   py37_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
kiwisolver                1.0.1            py37h6538335_0    defaults
lazy-object-proxy         1.3.1            py37hfa6e2cd_2    defaults
libpng                    1.6.36               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py37he774522_0    defaults
matplotlib                3.0.3            py37hc8f65d3_0    defaults
mccabe                    0.6.1                    py37_1    defaults
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2019.3                      203    defaults
mkl_fft                   1.0.10           py37h14836fe_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
msys2-conda-epoch         20160418                      1    defaults
nbformat                  4.4.0                    py37_0    defaults
numpy                     1.16.2           py37h19fb1c0_0    defaults
numpy-base                1.16.2           py37hc3f5095_0    defaults
openssl                   1.1.1b               he774522_1    defaults
pandas                    0.24.2           py37ha925a31_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.4                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       19.0.3                   py37_0    defaults
prometheus_client         0.6.0                    py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
pyasn1                    0.4.5                      py_0    defaults
pyasn1-modules            0.2.4                    py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pyhamcrest                1.9.0                    py37_2    defaults
pylint                    2.3.1                    py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.3.1                    py37_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyrsistent                0.14.11          py37he774522_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.3                h8c8aaf0_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
pytz                      2018.9                   py37_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.5                 py37_1000    defaults
pyzmq                     18.0.0           py37ha925a31_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtconsole                 4.4.3                    py37_0    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
send2trash                1.5.0                    py37_0    defaults
service_identity          18.1.0           py37h28b3542_0    defaults
setuptools                40.8.0                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.27.2               he774522_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tornado                   6.0.2            py37he774522_0    defaults
traitlets                 4.3.2                    py37_0    defaults
twisted                   18.9.0           py37he774522_0    defaults
typed-ast                 1.3.1            py37he774522_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h21ff451_3    defaults
vs2015_runtime            15.5.2                        3    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.33.1                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.11.1           py37he774522_0    defaults
xarray                    0.11.3                   py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zope                      1.0                      py37_1    defaults
zope.interface            4.6.0            py37he774522_0    defaults
```
</p></details>

**Comment by gary-cotton-tech-collaborator** [comment] 2019-04-08 03:45
Thank You, Git Hub, Miniconda, Anaconda, Conda, For Having This Forum.
Date: Sun, 7 Apr 2019 21:36:36 -0500
Subject: Please, Please, Read This Message To Your Corporation And Forward It To Whoever Can Benefit From It -- Thank You & God Bless All
{Message}
===>  Work-Around & Corporation Encouragement -- Here <===
Dear Miniconda, Anaconda, Conda, (Others?):
Granted, I could have, myself, introduced, or caused the following Conda
Non-Functionality:
"CommandNotFoundError: No command 'conda conda'."
Regardless, please accept my sharing with you as an Encouragement, - Not -
a complaint: I Guarantee You And Conda And its Associated Corporations
That:
This Problem Is - Not - Some peripheral minor mishap, But, Rather, is
appearing to be widespread across Many, If Not Every Operating System:
Windows 7, Windows 10, Mac OsX, Linux, Etc.
 ... Please Note: These Operating Systems Are Not "Remote". By God's grace,
persons joined in to share their wisdom for a "Solution". Yes, Downgrading
Conda, Back to one's previous Rev, -- Does -- Seem To Bring Conda
Functionality Back. But, Is This Really A Full Resolution? No. The
Following Command - Did - "Resolve" the dilemma caused by the Conda
"Warning", (during a Git Conda flask env install) suggesting -- implying
Necessity -- of an install-embedded upgrade to "Conda 4.6.1", Resulting in
the Loss of All Conda Functionality.
But, though I and many Others, are grateful, for the following Command - It
- Is - Simply - A 'Downgrade-To-Your-Original-Conda-Version--Work-Around',
which is - Not - the Real Solution. That Command Is:
"$ python -m conda install conda==4.5.12"
===>>> (The "4.5.12" should be replaced by -Your- original previous Conda
Rev Level: You can find it out by journeying to:
"C:\ProgramData\Miniconda3" {Windows 7}, selecting the "Packages" folder,
and seeking the folders named: "conda-4.5.12-p737_0", or some names
similar. The "4.5.12" or whatever it is - Is - the conda version number you
are needing to Downgrade to, to get your Functionality back. the
corresponding creation dates or modification dates, of the folders - Should
- guide you to the right previous conda Rev Level..
===>>> Therefore, Conda Corporation:
Please "Update" Your "Warning" message, programmed to emerge, for the User,
when They are running:
"$ conda create -n flask-env", {etc.} to "Warn" The User That: "Conda
Non-Functionality May Result, If You Upgrade Now. Here Is The Work-Around
Recovery Command, Should You Lose Conda Functioinality, Due To Upgrading
During This Environment Creation:
--->
"$ python -m conda install conda==4.5.12" (The "4.5.12" should be replaced
by -Your- original previous Conda Rev Level: You can find it out by
journeying to:
"C:\ProgramData\Miniconda3" {Windows 7}, selecting the "Packages" folder,
and seeking the folders named: "conda-4.5.12-p737_0", or some name similar.
The "4.5.12" or whatever it is - Is - the conda version number you are
needing to Downgrade to, to get your Functionality back. the corresponding
creation dates or modification dates - Should - guide you to the right
previous conda Rev Level..
---<
===>>> Here Is Why:
I Am An Experienced IT Learner & Professional, A Software-Programming
Student, Working Full-Time, and Gratefully In School. It Cost Me 5 hours of
my Own Time, To Resolve This Unnecessary Problem. I have a Key Assignment,
Due on Monday-April-08-2019, Which I, may Not be able to complete, by the
time I have to leave for work at 06:00am Monday morning. I ask -You, Conda
Corporation, - Who - Is - It - That:
 ===>>> Should Be Investing The Time For Excellent: Pre- Public Product
Release <<<=== ???
Why Should I, And Countless Others, Unknowingly Be Forced Into Resolving
Some Corporation's Pre-Mature Software Roll-Out?  Why? These Lost 5 Hours,
==> Should <== Have Been Invested By Your Corporation, And - Not - By The
Unknowing, Unsuspecting User And Corporate And Educational Communities!
Please, Put The Following "Proven Production Profit Principle" To Better
Oversight In Your Corporation:
The "7-E's Principle" Of: "Excellence, Even Empathy, Equals Extending
Expanding Existence"
Possibly, by God's Grace, You Will Take Better Hold Of This True Principle,
And Endeavor To More Extensively User-Level Pre-Test  & Pre-Resolve, Any And All Public Production Releases - Or - You may choose to Ignore such shared information, and maybe even Snicker at my Experience here today. I urge You to Consider: AOL, MySpace, Yahoo, Internet Explorer, Bing, Geeves, K-Mart, Sears, And Many Other Corporations: 
==>>> Abandoned By The World. <<<===
Do You, Conda Corporation, Wish To Be There With Them?  
I can Guarantee You, that, Anything Less, Than A Full-Hearted Understanding And A Fuller Implementation Of The "7-E's Principle" Of: "Excellence, Even Empathy, Equals Extending Expanding Existence", {without this Principle} Will Result, "Eventually" in Your Corporation's Public Profitability "Ending".
===>>> Please, Do This! -- Thank You And God Bless You, Each And All. <<<===
Gary Cotton (IT Professional & Coding-Programming Student) 
gary.cotton.tech.collaborator@gmail.com

**Comment by Banus** [comment] 2019-04-08 10:26
The last version running correctly on my configuration (Windows 10, GIT bash) is `4.6.7`.
The issue seems related to this change in `4.6.8`:

    fix the post-creation helper message from "source activate" to "conda activate"

Downgrading Conda (in Windows CMD) with `conda install -n base conda==4.6.7` seems to solve the issue. Remember to regenerate the scripts with `conda init` before trying again on a new bash terminal.

**Comment by mfansler** [comment] 2019-04-08 14:37
@Banus [Others have reported that 4.6.8 is fine](https://stackoverflow.com/q/55477806/570918), rather that the error was introduced with 4.6.9.

**Closed** 2019-04-08 19:49 UTC

**Comment by MHouse** [comment] 2019-04-10 17:41
> The last version running correctly on my configuration (Windows 10, GIT bash) is `4.6.7`.
> The issue seems related to this change in `4.6.8`:
> 
> ```
> fix the post-creation helper message from "source activate" to "conda activate"
> ```
> Downgrading Conda (in Windows CMD) with `conda install -n base conda==4.6.7` seems to solve the issue. Remember to regenerate the scripts with `conda init` before trying again on a new bash terminal.

As @mfansler pointed out, 4.6.8 seems to work.  Besides running a `conda init` don't forget to also do a `conda init bash` since we're on Windows.  By default, `conda init` will only configure cmd and PowerShell.

Also, if you have a new installation of Anaconda and a `.bashrc` file doesn't exist, 4.6.8 experiences this error:  #8244 

Simple solution is to create an empty file with `touch .bashrc` and re-run `conda init bash`

**Comment by tobsecret** [comment] 2019-04-12 18:41
Having this issue again with 4.6.11 on Windows 7. Can run the conda command upon initialization of the shell but running activate gives the error and subsequently I get the error every time I run the conda command. This is resolved by restarting the shell but I cannot use activate, so it seems like running `conda init bash` changed activate.

**Comment by mfansler** [comment] 2019-04-13 14:19
@tobsecret yeah, the fix is merged master, so should be in release 4.6.12.

**Comment by pattyjula** [comment] 2019-04-29 17:18
> ```shell
> CommandNotFoundError: No command 'conda conda'.
> ```

I had this issue too. Posted the solution for me over [here](https://superuser.com/questions/1424489/conda-activate-is-not-working-in-git-bash-shelll-but-it-looks-well-on-cmd-exe/1431014#1431014) .

**Comment by CSP197** [comment] 2019-05-17 04:01
Can confirm-- updating to conda v 4.6.14 should solve this issue 👍 
`conda update conda`

**Comment by neozenith** [comment] 2019-05-28 00:00
In git bash (2.21.0) Win10:
```bash
λ env | grep CONDA
CONDA_SHLVL=0
CONDA_EXE=/c/Users/me/AppData/Local/Continuum/anaconda3/Scripts/conda.exe
CONDA_BAT=C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\conda.bat
_CE_CONDA=conda

λ $CONDA_EXE update conda
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: ...working...
.....

λ $CONDA_EXE init
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts\conda.exe
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts\conda-env.exe
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts\conda-script.py
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts\conda-env-script.py
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\conda.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\Library\bin\conda.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\_conda_activate.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\rename_tmp.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\conda_auto_activate.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\conda_hook.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts\activate.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\activate.bat
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\condabin\deactivate.bat
modified      C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts\activate
modified      C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts\deactivate
modified      C:\Users\me\AppData\Local\Continuum\anaconda3\etc\profile.d\conda.sh
modified      C:\Users\me\AppData\Local\Continuum\anaconda3\etc\fish\conf.d\conda.fish
no change     C:\Users\me\AppData\Local\Continuum\anaconda3\shell\condabin\Conda.psm1
modified      C:\Users\me\AppData\Local\Continuum\anaconda3\shell\condabin\conda-hook.ps1
modified      C:\Users\me\AppData\Local\Continuum\anaconda3\Lib\site-packages\xonsh\conda.xsh
modified      C:\Users\me\AppData\Local\Continuum\anaconda3\etc\profile.d\conda.csh
modified      C:\Users\me\Documents\WindowsPowerShell\profile.ps1
modified      HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun

==> For changes to take effect, close and re-open your current shell. <==


```

**Comment by s2t2** [comment] 2019-05-30 03:52
We needed to run `conda init bash` and then (sometimes maybe?) run `conda update conda` before restarting Git Bash.
