### ISSUE TITLE
 AssertionError: C:\Users\anaconda\.tmp.index.json

### ISSUE THREAD

**Issue by sameen94** [conda/conda#6207] opened 2017-10-21 21:34 UTC
Hi, I'm facing this issue while installing textblob. Please help.

(C:\Users\anaconda) C:\Users\anaconda>conda install -c nbsantos textblob
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\anaconda:

The following NEW packages will be INSTALLED:

    asn1crypto:     0.22.0-py36_0
    certifi:        2016.2.28-py36_0
    cffi:           1.10.0-py36_0
    conda:          4.3.27-py36hcbae3bd_0
    conda-env:      2.6.0-0
    cryptography:   1.8.1-py36_0
    idna:           2.6-py36_0
    menuinst:       1.4.7-py36_0
    nltk:           3.2.4-py36_0
    openssl:        1.0.2l-vc14_0                  [vc14]
    packaging:      16.8-py36_0
    pip:            9.0.1-py36_1
    pycosat:        0.6.2-py36_0
    pycparser:      2.18-py36_0
    pyopenssl:      17.0.0-py36_0
    pyparsing:      2.2.0-py36_0
    pywin32:        220-py36_2
    requests:       2.14.2-py36_0
    ruamel_yaml:    0.11.14-py36_1
    setuptools:     36.4.0-py36_1
    six:            1.10.0-py36_0
    textblob:       0.12.0-py36hb7c39c7_0 nbsantos
    vs2015_runtime: 14.0.25420-0
    wheel:          0.29.0-py36_0
    wincertstore:   0.2-py36_0

Proceed ([y]/n)?

nltk-3.2.4-py3 100% |###############################| Time: 0:00:04 432.26 kB/s
textblob-0.12. 100% |###############################| Time: 0:00:03 181.21 kB/s
conda-4.3.27-p 100% |###############################| Time: 0:00:01 495.26 kB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\anaconda  (writable)
    default environment : C:\Users\anaconda
       envs directories : C:\Users\anaconda\envs
                          C:\Users\Sameen Fatima\AppData\Local\conda\conda\envs
                          C:\Users\Sameen Fatima\.conda\envs
          package cache : C:\Users\anaconda\pkgs
                          C:\Users\Sameen Fatima\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/nbsantos/win-64
                          https://conda.anaconda.org/nbsantos/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Sameen Fatima\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.14393
          administrator : False

`$ C:\Users\anaconda\Scripts\conda-script.py install -c nbsantos textblob`

    Traceback (most recent call last):
      File "C:\Users\anaconda\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\anaconda\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\anaconda\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\anaconda\lib\site-packages\conda\cli\install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\anaconda\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\anaconda\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\anaconda\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\Users\anaconda\lib\site-packages\conda\core\link.py", line 263, in execute
        self.verify()
      File "C:\Users\anaconda\lib\site-packages\conda\core\link.py", line 242, in verify
        self.prepare()
      File "C:\Users\anaconda\lib\site-packages\conda\core\link.py", line 149, in prepare
        for pkg_info in self.packages_info_to_link)
      File "C:\Users\anaconda\lib\site-packages\conda\core\link.py", line 149, in <genexpr>
        for pkg_info in self.packages_info_to_link)
      File "C:\Users\anaconda\lib\site-packages\conda\core\link.py", line 54, in determine_link_type
        if hardlink_supported(source_test_file, target_prefix):
      File "C:\Users\anaconda\lib\site-packages\conda\_vendor\auxlib\decorators.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
      File "C:\Users\anaconda\lib\site-packages\conda\gateways\disk\test.py", line 84, in hardlink_supported
        assert not lexists(test_file), test_file
    AssertionError: C:\Users\anaconda\.tmp.index.json

**Comment by nehaljwani** [comment] 2017-10-23 08:05
Closing as duplicate of https://github.com/conda/conda/issues/6023

**Closed by nehaljwani** 2017-10-23 08:05 UTC
