### ISSUE TITLE
Conda modifying fish prompt even with changeps1: false

### ISSUE THREAD

**Issue by UtkuBirkan** [conda/conda#9245] opened 2019-09-16 09:18 UTC
## Current Behavior

Activating conda in fish shell changes prompt even with `changeps1: false` set on the .condarc file.

### Steps to Reproduce

Laucnhing an interactive fish shell instance and activating an environment 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /Users/birk0/miniconda3
            shell level : 1
       user config file : /Users/birk0/.condarc
 populated config files : /Users/birk0/.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.1.final.0
       virtual packages :
       base environment : /Users/birk0/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/birk0/miniconda3/pkgs
                          /Users/birk0/.conda/pkgs
       envs directories : /Users/birk0/miniconda3/envs
                          /Users/birk0/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.1 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

</p></details>

**Comment by sealcoms1111** [comment] 2019-09-24 15:52
100 keep it pushing

**Comment by lewisacidic** [comment] 2019-10-15 15:20
Duplicate of #6996, fixed by #7000 if it ever gets accepted...

**Comment by sdaitzman** [comment] 2019-12-23 22:45
Additional not-ideal but functional workaround: add this to your `~/.config/fish/config.fish`, after the modifications by conda:

```fish
# kill the right prompt __conda_add_prompt 😠
function __conda_add_prompt; end
```

It overwrites the function Conda uses to print the right prompt. This has the benefit of persisting across runs of `$ conda init` and is persistent when conda is updated, moved or reinstalled.

**Comment by soapy1** [comment] 2019-12-24 00:31
pr https://github.com/conda/conda/pull/7000 merged. Thank you @teake for the fix!

**Closed by soapy1** 2019-12-24 00:31 UTC
Labels: good_first_issue
