### ISSUE TITLE
Unable to remove files for package: pyyaml

### ISSUE THREAD

**Issue by H0R5E** [conda/conda#1725] opened 2015-10-21 18:50 UTC
```
C:\Users\Winston>conda update pyyaml
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following NEW packages will be INSTALLED:

    wheel:      0.26.0-py27_1

The following packages will be UPDATED:

    conda:      3.11.0-py27_0 --> 3.18.3-py27_0
    conda-env:  2.1.4-py27_0  --> 2.4.3-py27_1
    pip:        6.1.1-py27_0  --> 7.1.2-py27_0
    pyyaml:     3.11-py27_0   --> 3.11-py27_2
    requests:   2.7.0-py27_0  --> 2.8.1-py27_0
    setuptools: 16.0-py27_0   --> 18.4-py27_0

Proceed ([y]/n)? y

Error: Unable to remove files for package: pyyaml

Please close all processes running code from pyyaml and try again.


C:\Users\Winston>conda info
Current conda install:

             platform : win-64
        conda version : 3.11.0
  conda-build version : 1.13.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://conda.binstar.org/t/<TOKEN>/topper/win-64/
                        https://conda.binstar.org/t/<TOKEN>/topper/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Winston\.condarc
    is foreign system : False


C:\Users\Winston>
```

But I am running no python based applications.

**Comment by msarahan** [comment] 2015-10-21 21:23
Have you tried restarting your computer, or at least logging out and back in?  Sometimes things are still held onto by some annoying ghost.

**Comment by H0R5E** [comment] 2015-10-21 22:02
No, no joy I'm afraid. Can I provide any more info?

**Comment by msarahan** [comment] 2015-10-21 22:04
Not right now.  I'll try to reproduce.  My only thought is that the conda process itself is using pyyaml, and I don't understand how that works.  That's not a great argument, though, because surely updating things like Conda itself would never have worked?

**Comment by H0R5E** [comment] 2015-10-21 22:18
Well, here is some snake oil for you...

```
[C:\Users\Winston]conda update anaconda
Fetching package metadata: ......
Solving package specifications: ..................................
Package plan for installation in environment C:\Anaconda:

The following packages will be UPDATED:

    conda:      3.11.0-py27_0 --> 3.18.3-py27_0
    conda-env:  2.1.4-py27_0  --> 2.4.2-py27_0

The following packages will be DOWNGRADED:

    pip:        6.1.1-py27_0  --> 6.0.8-py27_0
    requests:   2.7.0-py27_0  --> 2.6.0-py27_0
    setuptools: 16.0-py27_0   --> 14.3-py27_0

Proceed ([y]/n)? y

Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

[C:\Users\Winston]conda update pyyaml
Fetching package metadata: ......
Solving package specifications: ..............
Package plan for installation in environment C:\Anaconda:

The following NEW packages will be INSTALLED:

    wheel:      0.26.0-py27_1

The following packages will be UPDATED:

    pip:        6.0.8-py27_0 --> 7.1.2-py27_0
    python:     2.7.9-1      --> 2.7.10-1
    pyyaml:     3.11-py27_0  --> 3.11-py27_2
    requests:   2.6.0-py27_0 --> 2.8.1-py27_0
    setuptools: 14.3-py27_0  --> 18.4-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
```

Shall I close it?

**Comment by msarahan** [comment] 2015-10-22 12:31
Closing.  I hope anyone in the future finds this helpful.  I will add it to our bug investigation, but low priority, since you were able to easily work around it.

**Closed by msarahan** 2015-10-22 12:31 UTC
