### ISSUE TITLE
IsADirectoryError

### ISSUE THREAD

**Issue by pvanderlinden** [conda/conda#6811] opened 2018-01-29 11:55 UTC
**I'm submitting a...**
  - [X] bug report

## Current Behavior
When installing certain packages it will break with IsADirectoryError
```
<<HTTPS 200 OK
< Accept-Ranges: bytes
< Content-Disposition: attachment; filename="six-1.11.0-py35h423b573_1.tar.bz2"; filename*=UTF-8''six-1.11.0-py35h423b573_1.tar.bz2
< Content-Type: application/x-tar
< Date: Mon, 29 Jan 2018 11:43:42 GMT
< ETag: "576d38abfcb7ceb3b323b802b1fec665"
< Last-Modified: Sat, 21 Oct 2017 18:55:29 GMT
< Server: AmazonS3
< x-amz-id-2: IGiKj9lk7QKmYRYyZCVaUEM4Ax19T3slC8e1+ZVXTR3gT5Hg9UNd/8CxoS9yDWZt5PdfORpg9mo=
< x-amz-request-id: 8A668C11FD79A607
< Content-Length: 21870
< Elapsed: 00:00.106578

TRACE conda.core.path_actions:execute(1238): extracting /opt/conda/pkgs/six-1.11.0-py35h423b573_1.tar.bz2 => /opt/conda/pkgs/six-1.11.0-py35h423b573_1
TRACE conda.gateways.disk.update:rename(60): renaming /opt/conda/pkgs/six-1.11.0-py35h423b573_1 => /opt/conda/pkgs/six-1.11.0-py35h423b573_1.c~
DEBUG conda.gateways.disk.create:extract_tarball(132): extracting /opt/conda/pkgs/six-1.11.0-py35h423b573_1.tar.bz2
  to /opt/conda/pkgs/six-1.11.0-py35h423b573_1
TRACE conda.gateways.disk.create:write_as_json_to_file(61): writing json to file /opt/conda/pkgs/six-1.11.0-py35h423b573_1/info/repodata_record.json
TRACE conda.gateways.disk.create:write_as_json_to_file(61): writing json to file /opt/conda/pkgs/six-1.11.0-py35h423b573_1/info/repodata_record.json
TRACE conda.gateways.disk.delete:rm_rf(29): rm_rf /opt/conda/pkgs/six-1.11.0-py35h423b573_1.tar.bz2.c~
TRACE conda.gateways.disk.delete:rm_rf(29): rm_rf /opt/conda/pkgs/six-1.11.0-py35h423b573_1.c~
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGIOT
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGINT
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGTERM
DEBUG conda.common.signals:signal_handler(56): de-registering handler for Signals.SIGQUIT
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 772, in __call__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/conda_env/cli/main.py", line 74, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/opt/conda/lib/python3.5/site-packages/conda_env/cli/main_update.py", line 107, in execute
    installer.install(prefix, specs, args, env)
  File "/opt/conda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 38, in install
    pfe.execute()
  File "/opt/conda/lib/python3.5/site-packages/conda/core/package_cache.py", line 590, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: [Errno 21] Is a directory: '/opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0'
[Errno 21] Is a directory: '/opt/conda/pkgs/libedit-3.1-heed3624_0'
```

### Steps to Reproduce
- run the continuumio/miniconda3 docker image
- run `conda update conda`
- create a file test.yaml with the following contents:
```
name: test
dependencies:
- lxml==3.7.2
- anaconda::redis-py==2.10.5
- beautifulsoup4==4.5.3
- feedparser==5.2.1
- html5lib==0.999
- w3lib==1.16.0
- clinicalgraphics::libgcrypt11=1
- python=3.5
```
- run `conda env update -f test.yaml`

## Expected Behavior
It should install without problems

## Environment Information
```
     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.4.8
    conda-build version : not installed
         python version : 3.6.2.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.8 requests/2.18.4 CPython/3.6.2 Linux/4.4.0-112-generic debian/8 glibc/2.19
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.22.0           py36h265ca7c_1    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2017.7.27.1      py36h8b7b77e_0    defaults
cffi                      1.10.0           py36had8d393_1    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
conda                     4.4.8                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.0.3            py36ha225213_1    defaults
idna                      2.6              py36h82fb2a8_1    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc-ng                 7.2.0                hcbc56d2_1    defaults
libstdcxx-ng              7.2.0                h24385c6_1    defaults
ncurses                   6.0                  h06874d7_1    defaults
openssl                   1.0.2l               h9d1a558_3    defaults
pip                       9.0.1            py36h30f8307_2    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pyopenssl                 17.2.0           py36h5cc804b_0    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
python                    3.6.2               h02fb82a_12    defaults
readline                  7.0                  hac23ff0_3    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
setuptools                36.5.0           py36he42e2e1_0    defaults
six                       1.10.0           py36hcac75e4_1    defaults
sqlite                    3.20.1               h6d8b0f3_1    defaults
tk                        8.6.7                h5979e9b_1    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
wheel                     0.29.0           py36he7f4e38_1    defaults
xz                        5.2.3                h2bcbf08_1    defaults
yaml                      0.1.7                h96e3832_1    defaults
zlib                      1.2.11               hfbfcf68_1    defaults

```
</p></details>

**Comment by msarahan** [comment] 2018-01-29 15:26
I am also seeing this with conda-build.

**Comment by msarahan** [comment] 2018-01-31 16:23
For context, with conda-build, it happens very frequently with the cross-platform build.  So, on our linux-64 docker image, when we run with CONDA_SUBDIR=linux-32 and ``linux32 conda-build``, we can get this error right away.  I'm less sure about how to reproduce with the OP's report.  I know that @nehaljwani has tried, and it's tough to get to happen reliably.  I think that's because it depends on the state of the package cache.  You must have the correct initial state (something already existing there) to get this problem to happen.

**Comment by pvanderlinden** [comment] 2018-01-31 16:42
This seems to be the same problem in my case, if run the command again, it seems to work. We have frozen conda to an old version as this was crashing our CI pipelines.

**Comment by kalefranz** [comment] 2018-01-31 19:51
Do you think this is related to https://github.com/conda/conda/issues/6631?  That issue isn't new; it was present in conda 4.3, and probably 4.2.  But something in conda 4.4 could be helping to exacerbate it.

**Comment by pvanderlinden** [comment] 2018-02-01 11:14
It seems to be unrelated, also this bug doesn't exist in 4.4.7.

**Comment by nehaljwani** [comment] 2018-02-12 11:19
To reproduce this, exact steps:
```
# Spawn the container
sudo docker run --rm -it continuumio/miniconda3:4.3.27 /bin/bash

# Inside the container
cat <<EOF > ~/test.yaml 
name: test
dependencies:
- anaconda::ca-certificates==2017.08.26
EOF

# Update conda to 4.4.9
conda install -y conda=4.4.9

# Trigger the problem
conda env update -f ~/test.yaml 
Solving environment: done

Downloading and Extracting Packages
ca-certificates 2017.08.26: ############################5                   |  75% 

IsADirectoryError(21, 'Is a directory')
```

**Comment by nehaljwani** [comment] 2018-02-12 11:50
However, if I switch my docker daemon configuration from (overlay2/aufs):
```
{
  "storage-driver": "overlay2"
}
```
To:
```
{
  "storage-driver": "devicemapper"
}
```

Then the problem goes away. 
Logs:
[log_overlay2.txt](https://github.com/conda/conda/files/1716159/log_overlay2.txt)
[log_devicemapper.txt](https://github.com/conda/conda/files/1716160/log_devicemapper.txt)

But, that doesn't mean that this is not a bug in Conda. Because, if I switch the update from conda 4.4.9 to 4.4.7 (as @pvanderlinden has pointed out), the problem doesn't occur, even in the case of overlay2.

The difference in verbose logs is:
4.4.7:
```
TRACE conda.core.path_actions:execute(1238): extracting /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0
TRACE conda.gateways.disk.update:rename(50): renaming /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
DEBUG conda.core.path_actions:execute(1251): Invalid cross-device link on rename /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
TRACE conda.gateways.disk.delete:rm_rf(29): rm_rf /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0
DEBUG conda.gateways.disk.create:extract_tarball(131): extracting /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2
  to /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0/info/repodata_record.json
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0/info/repodata_record.json
TRACE conda.gateways.disk.delete:rm_rf(29): rm_rf /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2.c~
TRACE conda.gateways.disk.delete:rm_rf(29): rm_rf /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
TRACE conda.gateways.disk.delete:rm_rf(49): rm_rf failed. Not a link, file, or directory: /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
```
>4.4.7:
```
TRACE conda.core.path_actions:execute(1238): extracting /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0
TRACE conda.gateways.disk.update:rename(60): renaming /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
TRACE conda.gateways.disk.update:rename(67): Could not rename do to errno [18]. Falling back to copy/remove.
TRACE conda.gateways.disk.create:create_hard_link_or_copy(201): creating hard link /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
INFO conda.gateways.disk.create:create_hard_link_or_copy(204): hard link failed, so copying /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
TRACE conda.gateways.disk.create:_do_copy(251): copying /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0 => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.c~
TRACE conda.gateways.disk.delete:rm_rf(29): rm_rf /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0
TRACE conda.core.path_actions:reverse(1206): moving /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2.c~ => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2
TRACE conda.gateways.disk.delete:rm_rf(29): rm_rf /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2
TRACE conda.gateways.disk.update:rename(60): renaming /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2.c~ => /opt/conda/pkgs/ca-certificates-2017.08.26-h1d4fec5_0.tar.bz2
DEBUG conda.core.package_cache:execute(586): IsADirectoryError(21, 'Is a directory')
NoneType: None
```

**Comment by nehaljwani** [comment] 2018-02-12 12:23
If I revert this commit: 0b57e1ea4ff49b82df3bcd02408368cf182a3aba , then the problem mentioned in this issue goes away, however, that's not the right fix, of course.

**Comment by nehaljwani** [comment] 2018-02-12 12:48
Okay, seems like the [function in that commit ](https://github.com/conda/conda/blob/4.4.9/conda/gateways/disk/update.py#L47-L53)was written keeping files in mind, not directories!

**Comment by nehaljwani** [comment] 2018-02-12 12:51
So, the IsADirectoryError exception is coming from https://github.com/conda/conda/blob/4.4.9/conda/gateways/disk/create.py#L259

**Comment by kalefranz** [comment] 2018-02-13 18:59
I think Hunt just ran into this issue.

**Comment by travigd** [comment] 2018-02-15 22:08
Currently using Conda via Julia and trying to install things broke (within the last couple of days) for me.  Also running in a Docker container using overlayfs. Running `4.4.10-py27_0`. Barfs here:

```
DEBUG conda.gateways.disk.create:extract_tarball(132): extracting /home/nbuser/.julia/v0.6/Conda/deps/usr/pkgs/openblas-0.2.19-2.tar.bz2
  to /home/nbuser/.julia/v0.6/Conda/deps/usr/pkgs/openblas-0.2.19-2
DEBUG conda.common.signals:signal_handler(56): de-registering handler for 6
DEBUG conda.common.signals:signal_handler(56): de-registering handler for 2
DEBUG conda.common.signals:signal_handler(56): de-registering handler for 15
DEBUG conda.common.signals:signal_handler(56): de-registering handler for 3
Traceback (most recent call last):
  File "/home/nbuser/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/exceptions.py", line 789, in __call__
    return func(*args, **kwargs)
  File "/home/nbuser/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/home/nbuser/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/nbuser/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/home/nbuser/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "/home/nbuser/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 281, in handle_txn
    progressive_fetch_extract.execute()
  File "/home/nbuser/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/package_cache.py", line 590, in execute
    raise CondaMultiError(exceptions)
CondaMultiError: [Errno 21] Is a directory: u'/home/nbuser/.julia/v0.6/Conda/deps/usr/pkgs/certifi-2018.1.18-py27_0'
```

Was able to work around via downgrading to 4.4.7.

**Comment by kalefranz** [comment] 2018-02-15 22:52
#6867 will be in the next conda 4.4 release (4.4.11), which should resolve this issue.

**Closed** 2018-02-23 00:30 UTC
Labels: s:2, source:community, type:bug

**Comment by jakirkham** [comment] 2018-02-27 00:11
Ran into this recently with a routine Miniconda install. Any chance we can bump the included `conda` version in Miniconda to 4.4.11?

**Comment by mbargull** [comment] 2018-02-28 22:30
We also ran into this at Bioconda since a part of the build process uses `continuumio/miniconda3:latest`.
https://github.com/bioconda/bioconda-recipes/pull/8044

**Comment by ZelphirKaltstahl** [comment] 2018-04-16 11:57
This still seems to be happening with Anaconda 5.1.0 in some cases. Usually I was doing:

```
ENV CONDA_DIR="/home/${NON_PRIVILEGED_USER}/anaconda"

ENV ANACONDA_VERSION="5.1.0"
ENV ANACONDA_SHA256SUM="7e6785caad25e33930bc03fac4994a434a21bc8401817b7efa28f53619fa9c29"
ENV ANACONDA_DOWNLOAD_URL="https://repo.continuum.io/archive/Anaconda3-${ANACONDA_VERSION}-Linux-x86_64.sh"
ENV ANACONDA_DOWNLOAD_FILENAME="Anaconda3-${ANACONDA_VERSION}-Linux-x86_64.sh"
ENV CONDA_DIR /home/$NON_PRIVILEGED_USER/anaconda
ENV PATH $CONDA_DIR/bin:$PATH

WORKDIR /home/$NON_PRIVILEGED_USER
RUN mkdir --parents $CONDA_DIR \
 && wget --quiet $ANACONDA_DOWNLOAD_URL \
 && echo "${ANACONDA_SHA256SUM} ${ANACONDA_DOWNLOAD_FILENAME}" | sha256sum -c - \
 && /bin/bash $ANACONDA_DOWNLOAD_FILENAME -f -b -p $CONDA_DIR \
 && rm $ANACONDA_DOWNLOAD_FILENAME \
 && $CONDA_DIR/bin/conda config --system --add channels conda-forge \
 && $CONDA_DIR/bin/conda config --system --set auto_update_conda false \
 && conda clean -tips --yes
```

(dockerfile)

and the following fixed the issue:

```
ENV CONDA_DIR="/home/${NON_PRIVILEGED_USER}/anaconda"

ENV ANACONDA_VERSION="5.1.0"
ENV ANACONDA_SHA256SUM="7e6785caad25e33930bc03fac4994a434a21bc8401817b7efa28f53619fa9c29"
ENV ANACONDA_DOWNLOAD_URL="https://repo.continuum.io/archive/Anaconda3-${ANACONDA_VERSION}-Linux-x86_64.sh"
ENV ANACONDA_DOWNLOAD_FILENAME="Anaconda3-${ANACONDA_VERSION}-Linux-x86_64.sh"

ENV CONDA_DIR /home/$NON_PRIVILEGED_USER/anaconda

ENV PATH $CONDA_DIR/bin:$PATH

WORKDIR /home/$NON_PRIVILEGED_USER
RUN mkdir --parents $CONDA_DIR \
 && wget --quiet $ANACONDA_DOWNLOAD_URL \
 && echo "${ANACONDA_SHA256SUM} ${ANACONDA_DOWNLOAD_FILENAME}" | sha256sum -c - \
 && /bin/bash $ANACONDA_DOWNLOAD_FILENAME -f -b -p $CONDA_DIR \
 && rm $ANACONDA_DOWNLOAD_FILENAME \
 && conda update -n base conda \
 && $CONDA_DIR/bin/conda config --system --add channels conda-forge \
 && $CONDA_DIR/bin/conda config --system --set auto_update_conda false \
 && conda clean -tips --yes
```

(only added ` && conda update -n base conda \`)

**Comment by bootrider** [comment] 2018-04-18 20:01
Having Conda 4.4.10 and trying to update to  4.5.1:

```
/opt/conda/bin/conda upgrade -y conda
 ---> Running in 702de5c21d41
Solving environment: ...working... done
ca-certificates 2018.03.07: ########## | 100%
openssl 1.0.2o: ########## | 100%
conda 4.5.0: ########## | 100%
certifi 2018.1.18: #######5   |  75%

IsADirectoryError(21, 'Is a directory')
```

it also happens if I try to update/install just certifi package

**Comment by jakirkham** [comment] 2018-04-18 20:12
Generally a new installer with `conda` 4.4+ would be good. Also had to side step some `conda` 4.4.10 issues recently.

**Comment by bootrider** [comment] 2018-04-18 21:20
should I uninstall conda and installed again?

**Comment by bootrider** [comment] 2018-04-19 21:05
As @ZelphirKaltstahl states.....this happens in the Docker containers, in my case it happens all the time :(

**Comment by bootrider** [comment] 2018-04-20 17:29
> If you just upgrade conda  first
it keeps happening

**Comment by imad3v** [comment] 2018-04-25 12:44
@bootrider updating conda with this line worked for me:

`conda install -n base conda`
