### ISSUE TITLE
recursion bug attempting to install r-irkernel

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1777] opened 2015-11-04 04:50 UTC
See output of `conda install r-irkernel` in this file, as well as output of `conda info -a` (at the end).

[conda_recursion_bug.txt](https://github.com/conda/conda/files/26788/conda_recursion_bug.txt)

**Comment by ahmadia** [comment] 2015-11-04 05:38
@ijstokes - didn't this get resolved in the latest version of conda?

**Comment by ahmadia** [comment] 2015-11-04 05:39
Can you check this isn't a dupe of https://github.com/conda/conda/issues/1748 and resolved by https://github.com/conda/conda/pull/1749

**Comment by ijstokes** [comment] 2015-11-04 17:45
@ahmadia and @mcg1969 looks like the bug might still be there.  The above `conda_recursion_bug.txt` file has the output of `conda info-a` at the end and I'm using `conda version : 3.18.3`

**Comment by mcg1969** [comment] 2015-11-04 17:49
It definitely looks like it, and yet I can't reproduce it on mac for some reason (even if I include `-c wakari` `-c r`). Will investigate further.

**Comment by mcg1969** [comment] 2015-11-04 17:50
Ah, I got it. Had to create a new environment, not just install `r-irkernel`

**Comment by mcg1969** [comment] 2015-11-04 17:51
Actually, it looks like my fix was reverted in 3.18.3 somehow.

**Comment by mcg1969** [comment] 2015-11-04 17:54
It hasn't been reverted; the new version hasn't been pushed out. Definitely a duplicate then.

**Comment by ijstokes** [comment] 2015-11-04 19:26
FWIW, 3.17.0 works OK.

**Comment by mcg1969** [comment] 2015-11-04 19:31
Yes, that's to be expected.

**Comment by mcg1969** [comment] 2015-11-10 02:19
This is solved by 3.18.4, which was just released.

**Closed** 2015-11-10 02:37 UTC
