### ISSUE TITLE
Strange behaviour with conda 4.3.27, downgrading python inexplicably (to me).

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#6164] opened 2017-10-13 21:13 UTC
```
move %UserProfile%\.condarc %UserProfile%\.condarc.bak
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Windows-x86_64.exe', 'mc3.exe') }"
start /wait "" mc3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%TEMP%\mc3
%TEMP%\mc3\Scripts\activate.bat
conda update -y conda
conda update -y --all
conda install -y m2-file
```

When installing `m2-file` python gets downgraded to 3.5:

```
The following NEW packages will be INSTALLED:

    m2-file:           5.25-2
    m2-gcc-libs:       5.3.0-4
    m2-msys2-runtime:  2.5.0.17080.65c939c-3
    m2-zlib:           1.2.8-4
    msys2-conda-epoch: 20160418-1

The following packages will be UPDATED:

    asn1crypto:        0.22.0-py36h8e79faa_1      --> 0.22.0-py35he3634b9_1
    cachecontrol:      0.12.3-py36hfe50d7b_0      --> 0.12.3-py35h3f82863_0
    certifi:           2017.7.27.1-py36h043bc9e_0 --> 2017.7.27.1-py35hbab57cd_0
    cffi:              1.10.0-py36hae3d1b5_1      --> 1.10.0-py35h4132a7f_1
    chardet:           3.0.4-py36h420ce6e_1       --> 3.0.4-py35h177e1b7_1
    colorama:          0.3.9-py36h029ae33_0       --> 0.3.9-py35h32a752f_0
    conda:             4.3.29-py36h7c1b203_0      --> 4.3.29-py35hc07314a_0
    cryptography:      2.0.3-py36h123decb_1       --> 2.0.3-py35h67a4558_1
    distlib:           0.2.5-py36h51371be_0       --> 0.2.5-py35h12c42d7_0
    html5lib:          0.999999999-py36ha09b1f3_0 --> 0.999999999-py35h79d4e7f_0
    idna:              2.6-py36h148d497_1         --> 2.6-py35h8dcb9ae_1
    lockfile:          0.12.2-py36h0468280_0      --> 0.12.2-py35h667c6d9_0
    menuinst:          1.4.8-py36h870ab7d_0       --> 1.4.8-py35h7787ee1_0
    msgpack-python:    0.4.8-py36h58b1e9d_0       --> 0.4.8-py35hdef45cb_0
    packaging:         16.8-py36ha0986f6_1        --> 16.8-py35h5fb721f_1
    pip:               9.0.1-py36hadba87b_3       --> 9.0.1-py35h69293b5_3
    progress:          1.3-py36hbeca8d3_0         --> 1.3-py35ha84af61_0
    pycosat:           0.6.2-py36hf17546d_1       --> 0.6.2-py35h396ce21_1
    pycparser:         2.18-py36hd053e01_1        --> 2.18-py35h15a15da_1
    pyopenssl:         17.2.0-py36h15ca2fc_0      --> 17.2.0-py35hea705d1_0
    pyparsing:         2.2.0-py36h785a196_1       --> 2.2.0-py35hcabcaab_1
    pysocks:           1.6.7-py36h698d350_1       --> 1.6.7-py35hb30ac0d_1
    pywin32:           221-py36h9c10281_0         --> 221-py35h14ddfd5_0
    requests:          2.18.4-py36h4371aae_1      --> 2.18.4-py35h54a615f_1
    ruamel_yaml:       0.11.14-py36h9b16331_2     --> 0.11.14-py35h7ef29f8_2
    setuptools:        36.5.0-py36h65f9e6e_0      --> 36.5.0-py35h21a22e4_0
    six:               1.10.0-py36h2c0fdd8_1      --> 1.10.0-py35h06cf344_1
    urllib3:           1.22-py36h276f60a_0        --> 1.22-py35h8cc84eb_0
    webencodings:      0.5.1-py36h67c50ae_1       --> 0.5.1-py35h5d527fb_1
    wheel:             0.29.0-py36h6ce6cde_1      --> 0.29.0-py35hdbcb6e6_1
    win_inet_pton:     1.0.1-py36he67d7fd_1       --> 1.0.1-py35hbef1270_1
    wincertstore:      0.2-py36h7fe50ca_0         --> 0.2-py35hfebbdb8_0

The following packages will be DOWNGRADED:

    python:            3.6.3-h3389d20_0           --> 3.5.4-hedc2606_15
```

Any clues why @kalefranz?

**Comment by kalefranz** [comment] 2017-10-14 00:13
Looking.  But I'm not seeing it...  Not seeing why I mean.

**Comment by kalefranz** [comment] 2017-10-14 00:15
Man I'm stumped.  Might need to call in the big guns @mcg1969

**Comment by kalefranz** [comment] 2017-10-14 00:46
For the record, the flow showed in the original post is using conda 4.3.29, not 4.3.27.  The behavior is probably the same on 4.3.27 though.

When I stepped conda on windows back to 4.3.25, and then added pkgs/main to `defaults`, I got identical behavior.

What this means is that we can rule out the solver channel pass optimization and also the sub-channel prioritization as causes for this problem.

It seems to point to something in particular going on in metadata for the pkgs/main channel, I think.

**Comment by mcg1969** [comment] 2017-10-14 01:42
why not do `conda install m2-file python-3.6` and see what it says?

**Comment by kalefranz** [comment] 2017-10-14 01:58
Another datapoint, I tried conda 4.4.0rc1, manually adding pkgs/main to `defaults` (it's not merged up yet for 4.4.0rc1, it will be included in 4.4.0rc2).  It segfaulted on me twice, and then proceeded as expected, *without* changing the python version.  Interesting.

I'm going to try `conda install m2-file python=3.6` with conda 4.3 now.

**Comment by kalefranz** [comment] 2017-10-14 02:07
`conda install m2-file python=3.6` with conda 4.3.x gives the correct result.

Also, both

    conda config --add channels conda-canary
    conda install m2-file --dry-run

and

    conda config --remove channels conda-canary
    conda config --set auto_update_conda false
    conda install m2-file --dry-run

give the correct result I think

**Comment by mcg1969** [comment] 2017-10-14 02:31
Can you post the full output of the ‘correct’ result?

**Comment by kalefranz** [comment] 2017-10-14 02:36
Here's some of the flow

```
(root) C:\Users\builder>conda install conda=4.3.27
Solving environment: done

## Package Plan ##

  environment location: C:\Users\builder\AppData\Local\Temp\mc3

  added / updated specs:
    - conda=4.3.27


The following packages will be DOWNGRADED:

    conda: 4.4.0rc1-py36_0 conda-canary --> 4.3.27-py36hcbae3bd_0

Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
The batch file cannot be found.

(root) C:\Users\builder>conda install m2-file --dry-run
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\builder\AppData\Local\Temp\mc3:

The following NEW packages will be INSTALLED:

    m2-file:           5.25-2
    m2-gcc-libs:       5.3.0-4
    m2-msys2-runtime:  2.5.0.17080.65c939c-3
    m2-zlib:           1.2.8-4
    msys2-conda-epoch: 20160418-1

The following packages will be UPDATED:

    asn1crypto:        0.22.0-py36h8e79faa_1      --> 0.22.0-py35he3634b9_1
    cachecontrol:      0.12.3-py36hfe50d7b_0      --> 0.12.3-py35h3f82863_0
    certifi:           2017.7.27.1-py36h043bc9e_0 --> 2017.7.27.1-py35hbab57cd_0
    cffi:              1.10.0-py36hae3d1b5_1      --> 1.10.0-py35h4132a7f_1
    chardet:           3.0.4-py36h420ce6e_1       --> 3.0.4-py35h177e1b7_1
    colorama:          0.3.9-py36h029ae33_0       --> 0.3.9-py35h32a752f_0
    conda:             4.3.27-py36hcbae3bd_0      --> 4.3.29-py35hc07314a_0
    cryptography:      2.0.3-py36h123decb_1       --> 2.0.3-py35h67a4558_1
    distlib:           0.2.5-py36h51371be_0       --> 0.2.5-py35h12c42d7_0
    html5lib:          0.999999999-py36ha09b1f3_0 --> 0.999999999-py35h79d4e7f_0
    idna:              2.6-py36h148d497_1         --> 2.6-py35h8dcb9ae_1
    lockfile:          0.12.2-py36h0468280_0      --> 0.12.2-py35h667c6d9_0
    menuinst:          1.4.8-py36h870ab7d_0       --> 1.4.8-py35h7787ee1_0
    msgpack-python:    0.4.8-py36h58b1e9d_0       --> 0.4.8-py35hdef45cb_0
    packaging:         16.8-py36ha0986f6_1        --> 16.8-py35h5fb721f_1
    pip:               9.0.1-py36hadba87b_3       --> 9.0.1-py35h69293b5_3
    progress:          1.3-py36hbeca8d3_0         --> 1.3-py35ha84af61_0
    pycosat:           0.6.2-py36hf17546d_1       --> 0.6.2-py35h396ce21_1
    pycparser:         2.18-py36hd053e01_1        --> 2.18-py35h15a15da_1
    pyopenssl:         17.2.0-py36h15ca2fc_0      --> 17.2.0-py35hea705d1_0
    pyparsing:         2.2.0-py36h785a196_1       --> 2.2.0-py35hcabcaab_1
    pysocks:           1.6.7-py36h698d350_1       --> 1.6.7-py35hb30ac0d_1
    pywin32:           221-py36h9c10281_0         --> 221-py35h14ddfd5_0
    requests:          2.14.2-py36_0              --> 2.18.4-py35h54a615f_1
    ruamel_yaml:       0.11.14-py36h9b16331_2     --> 0.11.14-py35h7ef29f8_2
    setuptools:        36.5.0-py36h65f9e6e_0      --> 36.5.0-py35h21a22e4_0
    six:               1.10.0-py36h2c0fdd8_1      --> 1.10.0-py35h06cf344_1
    urllib3:           1.22-py36h276f60a_0        --> 1.22-py35h8cc84eb_0
    webencodings:      0.5.1-py36h67c50ae_1       --> 0.5.1-py35h5d527fb_1
    wheel:             0.29.0-py36h6ce6cde_1      --> 0.29.0-py35hdbcb6e6_1
    win_inet_pton:     1.0.1-py36he67d7fd_1       --> 1.0.1-py35hbef1270_1
    wincertstore:      0.2-py36h7fe50ca_0         --> 0.2-py35hfebbdb8_0

The following packages will be DOWNGRADED:

    python:            3.6.3-h3389d20_0           --> 3.5.4-hedc2606_15


(root) C:\Users\builder>conda config --set auto_update_conda false

(root) C:\Users\builder>conda install m2-file --dry-run
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\builder\AppData\Local\Temp\mc3:

The following NEW packages will be INSTALLED:

    m2-file:           5.25-2
    m2-gcc-libs:       5.3.0-4
    m2-msys2-runtime:  2.5.0.17080.65c939c-3
    m2-zlib:           1.2.8-4
    msys2-conda-epoch: 20160418-1

```

**Comment by mcg1969** [comment] 2017-10-14 02:40
Is 4.3.29 available for Python 3.6 yet?

**Comment by mcg1969** [comment] 2017-10-14 02:43
I would want to see the exact specs passed to the solver in every instance. I am guessing that the specs that are _added_ to the command line specs, through add_defaults_to_specs, auto_update_conda, or the new auto-pinning are involved here.

**Comment by kalefranz** [comment] 2017-10-14 02:44
> Is 4.3.29 available for Python 3.6 yet?

Gosh, I would have been so embarrassed, but yes.  From https://repo.continuum.io/pkgs/main/win-64/repodata.json

```
    "conda-4.3.29-py36h7c1b203_0.tar.bz2": {
      "build": "py36h7c1b203_0",
      "build_number": 0,
      "depends": [
        "conda-env >=2.6",
        "menuinst",
        "pycosat >=0.6.1",
        "pyopenssl >=16.2.0",
        "python >=3.6,<3.7.0a0",
        "requests >=2.12.4",
        "ruamel_yaml >=0.11.14"
      ],
      "license": "BSD 3-Clause",
      "md5": "fb73509cc25d0ab93e3a3fb0da7e6887",
      "name": "conda",
      "sha256": "5257fc0174e63d74c7e7c0af972d522925e215c2bdc9ce1fe444bfd7b26b407d",
      "sig": null,
      "size": 547817,
      "subdir": "win-64",
      "timestamp": 1507581140427,
      "version": "4.3.29"
    },
```

**Comment by kalefranz** [comment] 2017-10-14 02:45
Yeah I'm definitely going to have to spend more time with this later.  I'm moving on tonight I think :)

**Comment by mcg1969** [comment] 2017-10-14 02:58
sounds good. Next step is to see the input to the solver.

**Comment by mcg1969** [comment] 2017-10-14 03:13
Actually 4.3.27 has the sub channel weighting business, doesn’t it. Probably related to that

**Comment by mcg1969** [comment] 2017-10-14 19:18
I'm playing with this now. @mingwandroid, thanks for always doing such a good job giving us a straightforward way to reproduce an issue.

**Comment by mingwandroid** [comment] 2017-10-14 19:24
No problem! Actually @nehaljwani pointed this problem out to me originally, thanks Nehal!

**Comment by mcg1969** [comment] 2017-10-14 19:27
@mingwandroid @kalefranz I'm confused about something. When I do `conda update conda` initially, I go from 4.3.21 to 4.3.27. But if I do it _again_, I go to 4.3.29.

I'm guessing this has to do with the introduction of `pkgs/main`?

Regardless of the explanation, this isn't a good pattern. We need to make sure that users of `conda` who do not yet "see" `pkgs/main` can update to the latest version of conda in one shot. This may mean making an exception for conda itself, and including its latest packages in `pkgs/free`.

**Comment by mcg1969** [comment] 2017-10-14 19:39
OK, here's what I'm observing: the following combinations all do what is expected.
```
conda update conda # gets me to 4.3.27
conda config --set auto_update_conda false
conda install m2-file
```
```
conda update conda # gets me to 4.3.27
conda config --set auto_update_conda false
conda update conda # gets me to 4.3.29
conda install m2-file
```
```
conda update conda # gets me to 4.3.27
conda config --set auto_update_conda false
conda update conda # gets me to 4.3.29
conda update --all
conda install m2-file
```
However, this causes the downgrade behavior:
```
conda update conda # gets me to 4.3.27
conda config --set auto_update_conda false
conda update conda # gets me to 4.3.29
conda update --all
conda config --set auto_update_conda true
conda install m2-file
```

**Comment by mcg1969** [comment] 2017-10-14 19:57
OK, here's something interesting. I'm still not sure why the downgrade is happening, but I can explain why things differ depending on the value of `auto_update_conda`. 

The short answer is that the addition of the `conda` specs comes _after_ `add_defaults_to_specs`, and this needs to be reversed here. Here's why. If I type
```
conda install m2-file conda conda-env
```
then `add_defaults_to_specs` sees that `conda` and `conda-env` depend on Python, and it adds `python 3.6*` as an additional spec. However, if I do
```
conda install m2-file
```
then `add_defaults_to_specs`  sees that `m2-file` does _not_ depend on Python, so it doesn't think it needs to add anything to the specs. The problem with that is that then, somewhere _later_ in the process, you're adding `conda` and `conda-env` to the specs. So it _should_ have the exact same behavior as
```
conda install m2-file conda conda-env
```
The reason this bug usually doesn't come up is that frankly, most of the time, people are installing python-dependent packages with `conda install`. The behavior inconsistency is showing up only because `m2-file` is not a Python package.

So that's the explanation for the behavior difference. I consider this a bug that needs to be fixed, _independently_ of the mysterious downgrade behavior, which I am now going to investigate.

**Comment by mcg1969** [comment] 2017-10-14 20:17
OK, I've got it. It's the damn timestamps. (Sort of)

The relevant optimization passes here are, in order:

1. Maximize the version numbers of the requested packages (in this case, m2-file, conda, conda-env)
2. Maximize the build number (and now, _timestamp_) of the requested packages
3. Minimize the number of installed packages that need updating.

Before the advent of timestamps, `conda-4.3.29-py35hc07314a_0` and `conda-4.3.29-py36h7c1b203_0` would have equal consideration after Step 1 and 2, but the `py35` package would be eliminated from consideration by Step 3.

Now that timestamps are considered, `conda-4.3.29-py35hc07314a_0` is actually the _only_ survivor of Step 2. So now, Step 3 _has_ to schedule downgrades to Python 3.5 in order to install it.

Clearly, this is not the behavior we want. I think there are two choices here.

_Fix A:_ Swap the order of steps 2 and 3. <br/>
_Fix B:_ _Break apart_ Step 2 into Step 2a (build number) and Step 2b (timestamp), and put Step 2b after Step 3.

The simplest fix is clearly Fix A. But I think that's not the correct one overall. If someone issues a new build of a package `foo` with a dependency change, then someone doing `conda update foo` is not going to get that latest build, because conda will prefer to keep all of their dependencies the same. So I think we _need_ to do Fix B.

**Comment by mcg1969** [comment] 2017-10-14 20:27
I'm not fully convinced even Fix B is right. I'm concerned these timestamps have opened a Pandora's Box here. I know why y'all wanted them, but builds are builds are builds. Distinguishing between builds that merit a build number bump, and those that need _only_ a timestamp bump, seems problematic. We shouldn't be _keeping_ multiple builds of the same package, with identical build numbers, around for conda to even consider.

**Comment by mcg1969** [comment] 2017-10-15 19:00
Moving `add_defaults_to_specs` after `augment_specs` will prevent this particular case from occurring. Conda 4.4 might not need this because it's likely to have soft pins for Python in any environment that contains it.

**Comment by mcg1969** [comment] 2017-10-15 19:00
(Ah, given the output you're showing me from `4.4.0rc1`, maybe it doesn't have that soft pin. It needs it.)

**Comment by rainwoodman** [comment] 2017-10-17 18:47
Sorry but why is timestamp considered before the version of the package (or used at all)?

In RPM they had an epoch prefix to manually override version: https://utcc.utoronto.ca/~cks/space/blog/python/ExampleSortComparison

Epoch number seemed to be more reliable than timestamp, since the fact a package is built later has no correlation with the content of a package at all.

**Comment by mcg1969** [comment] 2017-10-17 18:49
> Sorry but why is timestamp considered before the version of the package (or used at all)?

It's not. Timestamp is considered _after_ versions and build numbers, and then only to break ties.

**Comment by rainwoodman** [comment] 2017-10-17 19:30
Thanks. Now I see.  I strongly agree with you on your previous comment https://github.com/conda/conda/issues/6164#issuecomment-336664971

maybe timestamp shall be used only if everything else, including the pin string are identical? It means your fix B:
- step 2 do not consider timestamp;
- the optimizer will spit out package-specs up to the timestamp degeneracy;
- then there is a step 4 to resolve the degeneracy by finding the latest timestamp for the package-spec;

soft-pinning may have fixed this for Python, but what about other packages?

**Comment by kalefranz** [comment] 2018-01-26 07:26
I think we got this resolved when we patched the vc metadata stuff.

**Closed by kalefranz** 2018-01-26 07:26 UTC
Labels: tag:solver
