### ISSUE TITLE
package/channel clash?

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#2773] opened 2016-06-20 04:20 UTC
Trying to do a `conda update --all` gives me a `FileExistsError` because (IIUC) it wants to install `python-simplegeneric` which comes from conda-forge when I already have `simplegeneric` from anaconda installed.

I thought conda-forge was suppose to be a semi-official repository for conda packages? It's not much good though if anyone can post duplicate packages which break conda!

```
λ conda search simplegeneric
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
python-simplegeneric         0.8.1                    py27_0  conda-forge
                             0.8.1                    py34_0  conda-forge
                          .  0.8.1                    py35_0  conda-forge
simplegeneric                0.8.1                    py27_0  defaults
                          .  0.8.1                    py34_0  defaults
                             0.8.1                    py35_0  defaults
                             0.8.1                    py27_1  defaults
                          .  0.8.1                    py34_1  defaults
                          *  0.8.1                    py35_1  defaults
```
```
λ conda install -f python-simplegeneric
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment C:\Python\envs\py-dev:

The following NEW packages will be INSTALLED:

    python-simplegeneric: 0.8.1-py35_0

Proceed ([y]/n)? y

[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Python\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Python\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Python\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Python\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Python\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Python\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Python\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Python\lib\site-packages\conda\instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Python\lib\site-packages\conda\instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Python\lib\site-packages\conda\install.py", line 634, in link
    os.makedirs(dst_dir)
  File "C:\Python\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Python\\envs\\py-dev\\Lib/site-packages/simplegeneric-0.8.1-py3.5.egg-info'

[py-dev] c:\Temp
λ conda list simplegeneric
# packages in environment at C:\Python\envs\py-dev:
#
simplegeneric             0.8.1                    py35_1
```

**Comment by kalefranz** [comment] 2016-06-20 04:48
Good additional info possibly to a problem we're trying to isolate.

https://github.com/conda/conda/issues/2773
https://github.com/conda/conda/issues/2722
https://github.com/conda/conda/issues/2714

**Comment by kalefranz** [comment] 2016-06-20 04:49
@mingwandroid, I know you were looking into this, but were having trouble reproducing it.  Maybe with this additional info, it falls more in @mcg1969's ballpark?

**Comment by mingwandroid** [comment] 2016-06-20 06:52
There were 3 different file/permissions bugs, two of which I could reproduce and fixed with `exp_backoff_fn`. Unfortunately this is the third bug.

It sounds like a useful hint was provided here and if channel change is the cause then it's something for @mcg1969.

Otherwise, we could wrap the call to `os.makedirs` with `exp_backoff_fn` but there's a good chance that it was the unlink operation that didn't complete successfully (`move _to_trash` may have failed).

I will continue to try to reproduce it though.

**Comment by mcg1969** [comment] 2016-06-21 00:50
There is nothing the conda solver can do if `conda-forge` insists on using a different package name than we do. That is to say: conda cannot prevent `simplegeneric` and `python-simplegeneric` from being installed one on top of the other.

**Comment by mcg1969** [comment] 2016-06-21 00:56
@dhirschfeld thanks for filing this issue: https://github.com/conda-forge/python-simplegeneric-feedstock/issues/1

**Comment by kalefranz** [comment] 2016-06-21 01:00
I'm satisfied and concur with @mcg1969's explanation.  This bug was also a duplicate of https://github.com/conda/conda/issues/2673

**Closed by kalefranz** 2016-06-21 01:00 UTC
Labels: bug
