### ISSUE TITLE
Why new version of conda hide machine name of linux console

### ISSUE THREAD

**Issue by showkeyjar** [conda/conda#12109] opened 2022-11-16 02:24 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I found machine name and file dir is missing when update new conda version on centos7

before update:

(rapids) [root@m-11-10 ~]$

after update:

(rapids) 

is there a proper reason to hide machine name and file dir?

if not, please don't do that.

now I can't know what machine I'm logging on and where dir I was.

### Conda Info

```shell
active environment : rapids
    active env location : /home/meteo/anaconda3/envs/rapids
            shell level : 2
       user config file : /home/meteo/.condarc
 populated config files :
          conda version : 22.9.0
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=11.0=0
                          __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/meteo/anaconda3  (writable)
      conda av data dir : /home/meteo/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/meteo/anaconda3/pkgs
                          /home/meteo/.conda/pkgs
       envs directories : /home/meteo/anaconda3/envs
                          /home/meteo/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.24.0 CPython/3.8.3 Linux/3.10.0-1160.11.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 5101:5101
             netrc file : None
           offline mode : False
```

**Comment by kenodegard** [comment] 2022-11-16 03:59
This is a duplicate of #11885

**Closed by kenodegard** 2022-11-16 03:59 UTC
Labels: type::bug
