### ISSUE TITLE
Failure to install r-base=3.3.1 

### ISSUE THREAD

**Issue by aflatto** [conda/conda#6117] opened 2017-10-09 07:09 UTC
Current conda install:
10:07:47 
10:07:47                platform : linux-64
10:07:47           conda version : 4.3.27
10:07:47        conda is private : False
10:07:47       conda-env version : 4.3.27
10:07:47     conda-build version : not installed
10:07:47          python version : 2.7.13.final.0
10:07:47        requests version : 2.12.4
10:07:47        root environment : /usr/local/miniconda  (writable)
10:07:47     default environment : /usr/local/miniconda
10:07:47        envs directories : /usr/local/miniconda/envs
10:07:47                           /root/.conda/envs
10:07:47           package cache : /usr/local/miniconda/pkgs
10:07:47                           /root/.conda/pkgs
10:07:47            channel URLs : https://conda.anaconda.org/r/linux-64
10:07:47                           https://conda.anaconda.org/r/noarch
10:07:47                           https://repo.continuum.io/pkgs/main/linux-64
10:07:47                           https://repo.continuum.io/pkgs/main/noarch
10:07:47                           https://repo.continuum.io/pkgs/free/linux-64
10:07:47                           https://repo.continuum.io/pkgs/free/noarch
10:07:47                           https://repo.continuum.io/pkgs/r/linux-64
10:07:47                           https://repo.continuum.io/pkgs/r/noarch
10:07:47                           https://repo.continuum.io/pkgs/pro/linux-64
10:07:47                           https://repo.continuum.io/pkgs/pro/noarch
10:07:47             config file : None
10:07:47              netrc file : None
10:07:47            offline mode : False
10:07:47              user-agent : conda/4.3.27 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-327.10.1.el7.x86_64 CentOS Linux/7.2.1511 glibc/2.17    
10:07:47                 UID:GID : 0:0
10:07:47 
10:07:47 `$ /usr/local/miniconda/bin/conda install -c r r-base=3.3.1 --file /usr/local/miniconda/lib/R/library/conda-r-list -qy`
10:07:47 
10:07:47 
10:07:47 
10:07:47 
10:07:47     Traceback (most recent call last):
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
10:07:47         return_value = func(*args, **kwargs)
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
10:07:47         exit_code = args.func(args, p)
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
10:07:47         install(args, parser, 'install')
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 160, in install
10:07:47         linked_dists = install_linked(prefix)
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 123, in linked
10:07:47         return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 115, in linked_data
10:07:47         load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
10:07:47         linked_data_[prefix][dist] = rec = IndexRecord(**rec)
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
10:07:47         instance = super(EntityType, cls).__call__(*args, **kwargs)
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
10:07:47         setattr(self, key, kwargs[key])
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
10:07:47         instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
10:07:47       File "/usr/local/miniconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
10:07:47         raise ValidationError(getattr(self, 'name', 'undefined name'), val)
10:07:47     ValidationError: Invalid value 1506080072.32 for timestamp

**Comment by nehaljwani** [comment] 2017-10-09 07:32
Closing as duplicate of https://github.com/conda/conda/issues/6096

For your scenario, the solution is to find out the files with timestamp in decimals and delete them:
```
grep -l '"timestamp": [0-9]\+\.'  /usr/local/miniconda/conda-meta/*.json | xargs rm -f
```

**Closed by nehaljwani** 2017-10-09 07:32 UTC
