### ISSUE TITLE
conda env export fails with InvalidVersionSpec:

### ISSUE THREAD

**Issue by sorenwacker** [conda/conda#10879] opened 2021-08-23 18:14 UTC
conda env export
    > InvalidVersionSpec: Invalid version '1.20pandas>=1': invalid character(s)

I installed pandas with conda. Does anybody know how to fix this?

I tired

    conda install pandas --force-reinstall

conda 4.10.3

**Comment by jezdez** [comment] 2021-08-23 20:09
Hi there, please open the ticket in the panda issue tracker, this issue tracker is for the development of the Conda package manager.

**Comment by soerendip** [comment] 2021-08-23 22:21
To me this looks more like a `conda` issue. That's why I posted it here.

**Comment by jezdez** [comment] 2021-08-23 22:44
Thanks for the pointers, could you please provide more information how to reproduce this issue? The [issue template](https://github.com/conda/conda/issues/new?assignees=&labels=&template=Bug_report.md) has a number of fields that wold help us to better understand your environment and able to find a solution. Thanks for your help!

**Comment by DiptoChakrabarty** [comment] 2021-08-28 10:47
I am also facing this issue in my case its like this

`conda env export > base.yml

InvalidVersionSpec: Invalid version '7.0.0cloudpickle>=0.2.2': invalid character(s)
`

I have tried uninstalling , reinstalling nothing works the same error is repeated

**Comment by jezdez** [comment] 2021-09-17 20:06
Okay, to clarify, the error in question happens because Conda can't correctly parse an environment spec (read: "the version specified in the metadata") of one of the packages you have installed.

@sorenwacker Without the list of packages you have installed, I can't help you. One of the packages you installed has used "1.20pandas>=1" instead of "...1.20;pandas>=1". The missing semicolon is invalid.

@DiptoChakrabarty The same applies to you, one of the packages you use is missing a delimiter in the version spec.

I'm gonna close this as a duplicate of #9624 since there is enough information already there.

**Closed by jezdez** 2021-09-17 20:06 UTC

**Comment by sorenwacker** [comment] 2021-09-17 21:08
I know what the error is. 

It comes from a wrongly format specification in a `setup.py` file!

**Comment by Ayenem** [comment] 2022-06-29 21:57
> 

Where do you find this `setup.py` file?
