### ISSUE TITLE
Unexpected error when trying to install KlustaViewa

### ISSUE THREAD

**Issue by bs10reh** [conda/conda#5059] opened 2017-04-15 15:10 UTC
(C:\Users\Rachel\Miniconda3) C:\Users\Rachel>conda env create -n klusta -f environment.yml
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : C:\Users\Rachel\Miniconda3  (writable)
    default environment : C:\Users\Rachel\Miniconda3
       envs directories : C:\Users\Rachel\Miniconda3\envs
                          C:\Users\Rachel\AppData\Local\conda\conda\envs
                          C:\Users\Rachel\.conda\envs
          package cache : C:\Users\Rachel\Miniconda3\pkgs
                          C:\Users\Rachel\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.3 Windows/10 Windows/10.0.14393

`$ C:\Users\Rachel\Miniconda3\Scripts\conda-env-script.py create -n klusta -f environment.yml`

    Traceback (most recent call last):
      File "C:\Users\Rachel\Miniconda3\lib\site-packages\conda\exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Rachel\Miniconda3\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Users\Rachel\Miniconda3\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Invalid name, try the format: user/package
    klusta does not exist or can't be accessed
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

**Comment by nehaljwani** [comment] 2017-04-19 19:15
Duplicate of #4328

**Closed** 2017-04-19 19:25 UTC
