### ISSUE TITLE
source deactivate leaves miniconda's bin directory in the PATH

### ISSUE THREAD

**Issue by certik** [conda/conda#813] opened 2014-07-15 17:55 UTC
Here is how to reproduce:

```
ondrej@kittiwake:~$ echo $PATH
/nh/nest/u/ondrej/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/nh/nest/vendor/Linux/ParaView-3.14.1-Linux-64bit/bin
ondrej@kittiwake:~$ cd /tmp/
ondrej@kittiwake:/tmp$ source activate xx
discarding /scratch/miniconda/bin from PATH
prepending /scratch/miniconda/envs/xx/bin to PATH
(xx)ondrej@kittiwake:/tmp$ echo $PATH
/scratch/miniconda/envs/xx/bin:/nh/nest/u/ondrej/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/nh/nest/vendor/Linux/ParaView-3.14.1-Linux-64bit/bin
(xx)ondrej@kittiwake:/tmp$ source deactivate
discarding /scratch/miniconda/envs/xx/bin from PATH
ondrej@kittiwake:/tmp$ echo $PATH
/scratch/miniconda/bin:/nh/nest/u/ondrej/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/nh/nest/vendor/Linux/ParaView-3.14.1-Linux-64bit/bin
```

As you can see, I have no `bin` directory in the PATH at the beginning, but after calling `deactivate`, the `/scratch/miniconda/bin` path is left in PATH.

I have linked the `activate`, `deactivate` and `conda` into `~/usr/bin` and put `~/usr/bin` into my PATH:

```
ondrej@kittiwake:~$ which conda
/nh/nest/u/ondrej/usr/bin/conda
ondrej@kittiwake:~$ which activate
/nh/nest/u/ondrej/usr/bin/activate
ondrej@kittiwake:~$ which deactivate
/nh/nest/u/ondrej/usr/bin/deactivate
ondrej@kittiwake:~$ ll /nh/nest/u/ondrej/usr/bin/conda
lrwxrwxrwx 1 ondrej cnls 28 Jul 15 11:41 /nh/nest/u/ondrej/usr/bin/conda -> /scratch/miniconda/bin/conda*
```

**Comment by jbpoline** [comment] 2015-08-07 20:36
It looks like this issue has last been discussed in 2014.  @asmeurer, did you come to any conclusion on how to handle it?  We are still running into the situation where the conda directory is still on the path, leading to use of the root conda python by default, even after deactivation.

**Comment by msarahan** [comment] 2015-10-25 20:46
This should be fixed with https://github.com/conda/conda/pull/1727.  It adds and removes paths as a block of strings from the front of PATH.  It only removes the first set of such a block.

Please review and let me know if it does not fix the issue.

**Comment by QuLogic** [comment] 2016-03-31 22:51
Does that mean I can finally remove `conda/bin` from `PATH`? The problem is not conda, it's the Python interpreter. I _don't_ want to use conda's Python at all when not in an environment. Especially annoying is that miniconda3 installs a `python` symlink to `python3`, going against PEP394.

**Comment by msarahan** [comment] 2016-04-01 01:16
Yes, that's the plan, anyway.  The installers will be modified to give you 3 options instead of 2:

1. add conda/bin to PATH (old way)
2. add conda/exec to PATH (new folder, contains only activate and conda as symlinks to those in the bin folder)
3. Do not change PATH

This will be released as conda 4.1, and installers for miniconda should come some time after that.  Anaconda installers will get it later - we just had a release, so the next one will be in about 3 months.

Sorry about the symlink - I can see the other side, though.  I haven't been successful at training myself to add the 3 on the end, and it annoys me to have that overhead (just to remember to add the 3, not typing the one extra character).

**Comment by QuLogic** [comment] 2016-07-18 06:54
So #1727 was milestoned 4.0 and current conda is 4.1.8, but after updating, I don't see a `conda/exec`. Do I need to re-install from scratch?

**Comment by kalefranz** [comment] 2017-05-09 08:03
closing per #1727

**Closed by kalefranz** 2017-05-09 08:03 UTC
Labels: type:feature

**Comment by asmeurer** [comment] 2017-05-09 17:48
So is the `deactivate` behavior changing to restore the old PATH instead of removing the activated environment?

**Comment by kalefranz** [comment] 2017-05-09 18:44
conda 4.1 through 4.3 is closer to "restore old PATH."  #5044 going into conda 4.4 is closer to "removing activated environment."

**Comment by jbpoline** [comment] 2017-05-09 21:55
Sorry - I had a look at #5044 but couldnt see if indeed the PATH before "activate"  is fully restored after a "deactivate" (it's a long PR:)  : is that the case ?

**Comment by kalefranz** [comment] 2017-05-09 22:10
Yes, it is. And extensively unit tested.

**Comment by jbpoline** [comment] 2017-05-09 22:15
Great, thanks a lot
