### ISSUE TITLE
Can not launch update of conda

### ISSUE THREAD

**Issue by Yaochieh** [conda/conda#6245] opened 2017-11-01 09:54 UTC
Here below is the error message:

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 3.5.4.final.0
       requests version : 2.18.4
       root environment : /home/tony/anaconda3  (writable)
    default environment : /home/tony/anaconda3
       envs directories : /home/tony/anaconda3/envs
                          /home/tony/.conda/envs
          package cache : /home/tony/anaconda3/pkgs
                          /home/tony/.conda/pkgs
           channel URLs : https://conda.anaconda.org/obspyck/linux-64
                          https://conda.anaconda.org/obspyck/noarch
                          https://conda.anaconda.org/obspy/linux-64
                          https://conda.anaconda.org/obspy/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/tony/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.5.4 Linux/4.4.0-98-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/tony/anaconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/tony/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080093.174 for timestamp

Thanks!

**Comment by kalefranz** [comment] 2017-11-01 16:16
This is a duplicate of https://github.com/conda/conda/issues/6096.  Please see that issue for solutions.

**Closed by kalefranz** 2017-11-01 16:16 UTC
