### ISSUE TITLE
`conda create` from yaml will not read env name from file

### ISSUE THREAD

**Issue by Adamtaranto** [conda/conda#13676] opened 2024-03-10 00:37 UTC
### What happened?

Using minconda I am trying to create a new env from environment.yml

environment.yml
```
name: newenv
channels:
    - conda-forge
    - bioconda
dependencies:
  - python=3.11
  - nbgrader==0.8.5
```

`conda create` has the option `--file` to take a env YAML. 

However, running `conda create --file environment.yml` gives this error:

`conda create: error: one of the arguments -n/--name -p/--prefix is required`

Providing an env name in addition to the yml gives a different error:

```
conda create -n testnew --file environment.yml 
>>> CondaValueError: could not parse 'name: newenv' in: environment.yml
```

I only get the expected behaviour by running `conda enve create --file environment.yml` which creates an env called "newenv".

Note: This error does not exist in micromamba which creates the env "newenv" as expected using either "conda create -f env.yml` or `conda env create -f env.yml `.

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /home/gitpod/miniconda
            shell level : 1
       user config file : /home/gitpod/.condarc
 populated config files : /home/gitpod/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=23.11.0=0
                          __glibc=2.35=0
                          __linux=6.1.75=0
                          __unix=0=0
       base environment : /home/gitpod/miniconda  (writable)
      conda av data dir : /home/gitpod/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/gitpod/miniconda/pkgs
                          /home/gitpod/.conda/pkgs
       envs directories : /home/gitpod/miniconda/envs
                          /home/gitpod/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Linux/6.1.75-060175-generic ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 33333:33333
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> /home/gitpod/.condarc <==
channel_priority: strict
channels:
  - bioconda
  - conda-forge
  - defaults
solver: libmamba
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /home/gitpod/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
archspec                  0.2.1              pyhd3eb1b0_0    defaults
boltons                   23.0.0          py311h06a4308_0    defaults
brotli-python             1.0.9           py311h6a678d5_7    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.12.12           h06a4308_0    defaults
certifi                   2023.11.17      py311h06a4308_0    defaults
cffi                      1.16.0          py311h5eee18b_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.11.0         py311h06a4308_0    defaults
conda-content-trust       0.2.0           py311h06a4308_0    defaults
conda-libmamba-solver     23.12.0            pyhd3eb1b0_1    defaults
conda-package-handling    2.2.0           py311h06a4308_0    defaults
conda-package-streaming   0.9.0           py311h06a4308_0    defaults
cryptography              41.0.7          py311hdda0065_0    defaults
distro                    1.8.0           py311h06a4308_0    defaults
fmt                       9.1.0                hdb19cb5_0    defaults
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4             py311h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libcurl                   8.4.0                h251f7ec_1    defaults
libedit                   3.1.20230828         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.5.3                haf1ee3a_0    defaults
libmambapy                1.5.3           py311h2dafd23_0    defaults
libnghttp2                1.57.0               h2d74bed_0    defaults
libsolv                   0.7.24               he621ea3_0    defaults
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.10.4               hf1b16e4_1    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
menuinst                  2.0.1           py311h06a4308_1    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.12               h7f8727e_0    defaults
packaging                 23.1            py311h06a4308_0    defaults
pcre2                     10.42                hebb0a14_0    defaults
pip                       23.3.1          py311h06a4308_0    defaults
platformdirs              3.10.0          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.5               h955ad1f_0    defaults
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.31.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                68.2.2          py311h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
truststore                0.8.0           py311h06a4308_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18         py311h06a4308_0    defaults
wheel                     0.41.2          py311h06a4308_0    defaults
xz                        5.4.5                h5eee18b_0    defaults
yaml-cpp                  0.8.0                h6a678d5_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

</details>

**Comment by kenodegard** [comment] 2024-03-10 01:09
Yup we are aware of the inconsistencies between `conda create` and `conda env create` (the former only accepts `requirements.txt` style files, the latter accepts both `requirements.txt` and `environment.yaml` styles). We are working to align these two commands (and the others offered via `conda env`).

Added to https://github.com/conda/conda/issues/11321

**Comment by kenodegard** [comment] 2024-03-10 01:20
This is a duplicate of https://github.com/conda/conda/issues/13015

**Closed by kenodegard** 2024-03-10 01:20 UTC
Labels: source::community, type::tech-debt, backlog
