### ISSUE TITLE
conda 4.4 incorrect activate message

### ISSUE THREAD

**Issue by csoja** [conda/conda#5790] opened 2017-08-08 14:44 UTC
I updated to conda 4.4.0b2 from conda v4.3. I created a new environment and it recommended the following - which I ran and got an error:

To activate this environment, use

    $ conda activate anaconda2

To deactivate an active environment, use

    $ conda deactivate

0288-csoja:scripts csoja$ conda activate anaconda2
Traceback (most recent call last):
  File "/Users/csoja/Desktop/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 176, in main
    raise CommandNotFoundError(argv1)
conda.exceptions.CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/csoja/Desktop/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/csoja/Desktop/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 178, in main
    from ..exceptions import handle_exception
ImportError: cannot import name 'handle_exception'

**Comment by tyler-thetyrant** [comment] 2017-08-08 18:32
Duplicate of #5738

**Closed** 2017-08-16 20:51 UTC
Labels: source:cio, type:bug
