### ISSUE TITLE
conda randomly not recognized in windows terminal (PowerShell and Bash)

### ISSUE THREAD

**Issue by tpackard1** [conda/conda#12734] opened 2023-05-31 16:39 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I open PowerShell, I am immediately given:
```
usage: sqlformat  [OPTIONS] FILE, ...
sqlformat: error: unrecognized arguments: hook
Invoke-Expression: C:\Users\Taylor\Documents\PowerShell\profile.ps1:4
Line |
   4 |  … onda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
     |                                                        ~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Command' because it is an empty string.
```

I have not changed the profile file that it references in the error message. But here is what is in the profile.ps file:
```

#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& "C:\Users\Taylor\miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
#endregion
```

And in Bash, I try to run the following command and get the error:

```
$ conda activate venv
usage: sqlformat  [OPTIONS] FILE, ...
sqlformat: error: unrecognized arguments: activate venv
```

Earlier today conda was working fine. It was only after closing vscode and the terminal then later coming back and opening a new terminal that it suddenly was not working. If  you need anymore information to diagnosis the issue please let me know what and how to provide it.

### Conda Info

```shell
[ERROR] Failed to read info: [Errno 2] No such file or directory: 'info'
```

### Conda Config

```shell
usage: sqlformat  [OPTIONS] FILE, ...
sqlformat: error: unrecognized arguments: --show sources
```

### Conda list

```shell
usage: sqlformat  [OPTIONS] FILE, ...
sqlformat: error: unrecognized arguments: --show-channel-urls
```

**Comment by tpackard1** [comment] 2023-05-31 18:13
I uninstalled miniconda3 and re-installed it and when I ran the `conda init powershell` command in Anaconda Powershell Prompt i received the following error report:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Taylor\miniconda3\lib\site-packages\conda\exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Taylor\miniconda3\lib\site-packages\conda\cli\main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "C:\Users\Taylor\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\Taylor\miniconda3\lib\site-packages\conda\cli\main_init.py", line 33, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "C:\Users\Taylor\miniconda3\lib\site-packages\conda\core\initialize.py", line 111, in initialize
        run_plan(plan2)
      File "C:\Users\Taylor\miniconda3\lib\site-packages\conda\core\initialize.py", line 659, in run_plan
        result = globals()[step['function']](*step.get('args', ()), **step.get('kwargs', {}))
      File "C:\Users\Taylor\miniconda3\lib\site-packages\conda\core\initialize.py", line 1551, in init_powershell_user
        profile_content = fp.read()
      File "C:\Users\Taylor\miniconda3\lib\codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

`$ C:\Users\Taylor\miniconda3\Scripts\conda-script.py init powershell`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Taylor\miniconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\Taylor\miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Taylor\miniconda3\python.exe
               CONDA_ROOT=C:\Users\Taylor\miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                   GOPATH=C:\Users\Taylor\go
                 HOMEPATH=\Users\Taylor
               LD_PRELOAD=<not set>
                     PATH=C:\Users\Taylor\miniconda3;C:\Users\Taylor\miniconda3\Library\mingw-
                          w64\bin;C:\Users\Taylor\miniconda3\Library\usr\bin;C:\Users\Taylor\min
                          iconda3\Library\bin;C:\Users\Taylor\miniconda3\Scripts;C:\Users\Taylor
                          \miniconda3\bin;C:\Users\Taylor\miniconda3\condabin;C:\Windows\system3
                          2;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPower
                          Shell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\Amazon\AWSCLIV2;C:\WINDOWS\system32;C:\WINDOW
                          S;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;
                          C:\WINDOWS\System32\OpenSSH;C:\Program Files\dotnet;C:\Program
                          Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program
                          Files (x86)\Microsoft SQL Server\150\Tools\Binn;C:\Program
                          Files\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Microsoft
                          SQL Server\150\DTS\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\150\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\140\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\140\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\140\DTS\Binn;C:\Program Files
                          (x86)\Java\jre1.8.0_201\bin;C:\Program
                          Files\Docker\Docker\resources\bin;C:\Program Files\Go\bin;C:\Program
                          Files\Git\cmd;C:\Users\Taylor\AppData\Roaming\nvm;C:\Program
                          Files\nodejs;C:\Program Files\PowerShell\7;C:\Users\Taylor\AppData\Roa
                          ming\Python\Scripts;C:\Users\Taylor\.cargo\bin;C:\Users\Taylor\AppData
                          \Local\Microsoft\WindowsApps;C:\Users\Taylor\AppData\Local\Programs\Mi
                          crosoft VS Code\bin;C:\Users\Taylor\miniconda3;C:\Users\Taylor\minicon
                          da3\Scripts;C:\Program Files\Azure Data
                          Studio\bin;C:\Users\Taylor\go\bin;C:\Users\Taylor\mingw64\bin
             PSMODULEPATH=C:\Users\Taylor\Documents\WindowsPowerShell\Modules;C:\Program Files\W
                          indowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mo
                          dules;C:\Program Files (x86)\Microsoft SQL
                          Server\150\Tools\PowerShell\Modules\;C:\Program Files (x86)\Microsoft
                          SQL Server\140\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Taylor\miniconda3
            shell level : 1
       user config file : C:\Users\Taylor\.condarc
 populated config files :
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\Users\Taylor\miniconda3  (writable)
      conda av data dir : C:\Users\Taylor\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Taylor\miniconda3\pkgs
                          C:\Users\Taylor\.conda\pkgs
                          C:\Users\Taylor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Taylor\miniconda3\envs
                          C:\Users\Taylor\.conda\envs
                          C:\Users\Taylor\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.10 Windows/10 Windows/10.0.22621
          administrator : True
             netrc file : None
           offline mode : False
```

I went ahead and sent the report to the core maintainers via the command line but thought I would add it here as well.

**Comment by travishathaway** [comment] 2023-06-01 16:20
Hi @tpackard1,

Thanks for filing this issue. It is really weird that you are seeing this `sqlformat` usage message. Was this a package you installed? I know you can't list the contents of the environment, but do you remember what you installed to it before you started seeing these errors?

Perhaps the error is being caused by it. Packages are allowed to run their own scripts during activation and deactivation. This is commonly used to set and unset environment variables.

**Comment by tpackard1** [comment] 2023-06-02 16:57
Hi @travishathaway ,

This was not a package that I installed. I had installed Poetry a couple of days prior and was doing some testing with Poetry but the testing went fine and nothing unusual. I was testing an application I am developing and created a new virtual environment and used poetry to install all the dependencies for that environment and it all worked smoothly. The testing virtual environment was deactivated then I activated the my dev environment for the application then made a push to the project repository, then closed everything out. Only once I came back to powershell did I start receiving the error.

In the end, I went ahead and did a full uninstall and re-install. Now everything is working smoothly again.

**Comment by travishathaway** [comment] 2023-06-05 11:05
Hi @tpackard1,

Thanks for giving me a little more information about this. I'm guessing something must have screwed up the command line configuration, and I think this came from outside of conda. Therefore, I think it makes sense to close this issue now.

I am happy you eventually got everything working again though. We appreciate the time you took to report this issue.

**Closed by travishathaway** 2023-06-05 11:05 UTC
Labels: type::bug, source::community, pending::support
