### ISSUE TITLE
html5Lib and beautifulsoup4 conda install error in python 3

### ISSUE THREAD

**Issue by jhgeorgi** [conda/conda#1683] opened 2015-10-06 20:15 UTC
when trying to install the above 2 packages, I get the following (identical error for both packages):

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Jacqui\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Jacqui\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Users\Jacqui\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Users\Jacqui\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\Jacqui\Anaconda3\lib\site-packages\conda\cli\install.py", line 337, in install
    update_deps=args.update_deps)
  File "C:\Users\Jacqui\Anaconda3\lib\site-packages\conda\plan.py", line 421, in install_actions
    for name in install.win_ignore_root:
AttributeError: 'module' object has no attribute 'win_ignore_root'

**Comment by soapy1** [comment] 2016-11-07 20:16
@jhgeorgi I can't reproduce this issue on the newest version of conda, so I'm going to close this issue. If this is still a problem after updating conda please reopen the issue 😸

**Closed by soapy1** 2016-11-07 20:16 UTC
