### ISSUE TITLE
Conda 4.7 breaks geospatial env: requires python 2.7 in python 3.6 environment

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda/conda#8849] opened 2019-06-29 21:42 UTC
## Current behaviou" 

I also mentioned this in https://github.com/conda/conda/issues/8828, and possibly similar as https://github.com/conda/conda/issues/8844. 
I am running in a case where I have an environment that no longer can be created with conda 4.7 and shows a huge list of the packages, without a clear idea at first sight which ones are now in conflict: https://travis-ci.org/geopandas/geopandas/jobs/551100679

output:
<details>
```
$ conda env create --file="${ENV_FILE}"
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:
  - descartes -> matplotlib -> freetype[version='>=2.9.1,<3.0a0'] -> libgcc-ng[version='>=7.3.0']
  - descartes -> matplotlib -> freetype[version='>=2.9.1,<3.0a0'] -> libpng[version='>=1.6.34,<1.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - descartes -> matplotlib -> icu[version='>=58.2,<59.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - descartes -> matplotlib -> numpy -> blas==1.0=mkl
  - descartes -> matplotlib -> numpy -> libgfortran-ng[version='>=7,<8.0a0']
  - descartes -> matplotlib -> numpy -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> libffi[version='>=3.2.1,<4.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0']
  - descartes -> matplotlib -> numpy -> python[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<6.0a0']
  - descartes -> matplotlib -> pyparsing
  - descartes -> matplotlib -> pyqt=5.9 -> dbus[version='>=1.13.2,<2.0a0'] -> expat[version='>=2.2.6,<3.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> dbus[version='>=1.13.2,<2.0a0'] -> glib[version='>=2.56.2,<2.57.0a0'] -> pcre[version='>=8.42,<9.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libuuid[version='>=1.0.3,<2.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> gstreamer[version='>=1.14.0,<2.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> libxcb[version='>=1.13,<2.0a0']
  - descartes -> matplotlib -> pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0'] -> jpeg[version='>=9b,<10a']
  - descartes -> matplotlib -> pyqt=5.9 -> sip[version='>=4.19.4,<=4.19.8']
  - descartes -> matplotlib -> python-dateutil -> six[version='>=1.5']
  - descartes -> matplotlib -> pytz
  - descartes -> matplotlib -> setuptools -> certifi[version='>=2016.09']
  - descartes -> matplotlib -> subprocess32
  - descartes -> matplotlib -> tornado -> backports_abc[version='>=0.4']
  - descartes -> matplotlib -> tornado -> futures
  - descartes -> matplotlib -> tornado -> singledispatch
  - descartes -> matplotlib -> tornado -> ssl_match_hostname -> backports
  - fiona=1.7 -> click-plugins -> python -> libffi[version='>=3.2.1,<4.0a0'] -> libgcc-ng[version='>=7.2.0']
  - fiona=1.7 -> click-plugins -> python -> libffi[version='>=3.2.1,<4.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - fiona=1.7 -> click-plugins -> python -> ncurses[version='>=6.1,<7.0a0']
  - fiona=1.7 -> click-plugins -> python -> openssl[version='>=1.1.1b,<1.1.2a'] -> ca-certificates
  - fiona=1.7 -> click-plugins -> python -> pip -> setuptools -> certifi[version='>=2016.09']
  - fiona=1.7 -> click-plugins -> python -> pip -> wheel
  - fiona=1.7 -> click-plugins -> python -> readline[version='>=7.0,<8.0a0']
  - fiona=1.7 -> click-plugins -> python -> sqlite[version='>=3.27.2,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - fiona=1.7 -> click-plugins -> python -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - fiona=1.7 -> click-plugins -> python -> xz[version='>=5.2.4,<6.0a0']
  - fiona=1.7 -> cligj
  - fiona=1.7 -> enum34
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> expat[version='>=2.2.5,<3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> freexl[version='>=1.0.5,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> geos[version='>=3.6.2,<3.6.3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> giflib[version='>=5.1.4,<5.2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> hdf4[version='>=4.2.13,<4.2.14.0a0'] -> jpeg[version='>=9b,<10a']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> hdf5[version='>=1.8.18,<1.8.19.0a0'] -> libgfortran-ng[version='>=7.2.0,<8.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> icu[version='>=58.2,<59.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> json-c[version='>=0.13.1,<0.14.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> kealib[version='>=1.4.7,<1.5.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libcurl[version='>=7.60.0,<8.0a0'] -> krb5[version='>=1.16.1,<1.17.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libcurl[version='>=7.60.0,<8.0a0'] -> libssh2[version='>=1.8.2,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> curl
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> libuuid[version='>=1.0.3,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libdap4[version='>=3.19.0,<3.20.0a0'] -> util-linux
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libkml[version='>=1.3.0,<1.4.0a0'] -> libboost[version='>=1.67.0,<1.67.1.0a0'] -> bzip2[version='>=1.0.6,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libnetcdf[version='>=4.6.1,<5.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libpng[version='>=1.6.34,<1.7.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libpq[version='>=10.3,<11.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libspatialite[version='>=4.3.0a,<4.4.0a0'] -> proj4[version='>=5.2.0,<5.2.1.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> libtiff[version='>=4.0.9,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> openjpeg[version='>=2.3.0,<3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> pcre[version='>=8.42,<9.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> freetype[version='>=2.9.1,<3.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> glib[version='>=2.56.1,<2.57.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> libxcb[version='>=1.13,<2.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> cairo[version='>=1.14.12,<2.0a0'] -> pixman[version='>=0.34.0,<1.0a0']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> poppler[version='>=0.65.0,<1.0a0'] -> poppler-data[version='>=0.4.9']
  - fiona=1.7 -> gdal=2.2 -> libgdal==2.2.4=heea9cce_1 -> xerces-c[version='>=3.2.1,<3.3.0a0']
  - fiona=1.7 -> gdal=2.2 -> numpy[version='>=1.11.3,<2.0a0'] -> blas==1.0=mkl
  - fiona=1.7 -> gdal=2.2 -> numpy[version='>=1.11.3,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - fiona=1.7 -> munch -> six
  - fiona=1.7 -> shapely
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> libffi[version='>=3.2.1,<4.0a0'] -> libgcc-ng[version='>=7.2.0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> libffi[version='>=3.2.1,<4.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1b,<1.1.2a'] -> ca-certificates
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.27.2,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> python[version='>=3.7,<3.8.0a0'] -> xz[version='>=5.2.4,<6.0a0']
  - matplotlib==2.0.2 -> cycler[version='>=0.10'] -> six
  - matplotlib==2.0.2 -> freetype[version='>=2.8,<2.9.0a0'] -> libpng[version='>=1.6.32,<1.7.0a0']
  - matplotlib==2.0.2 -> functools32
  - matplotlib==2.0.2 -> icu[version='>=58.2,<59.0a0']
  - matplotlib==2.0.2 -> numpy -> blas==1.0=mkl
  - matplotlib==2.0.2 -> numpy -> libgfortran-ng[version='>=7,<8.0a0']
  - matplotlib==2.0.2 -> numpy -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - matplotlib==2.0.2 -> pyparsing
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> dbus[version='>=1.13.2,<2.0a0'] -> expat[version='>=2.2.6,<3.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> dbus[version='>=1.13.2,<2.0a0'] -> glib[version='>=2.56.2,<2.57.0a0'] -> pcre[version='>=8.42,<9.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libuuid[version='>=1.0.3,<2.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> fontconfig[version='>=2.13.0,<3.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> gstreamer[version='>=1.14.0,<2.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> gst-plugins-base[version='>=1.14.0,<1.15.0a0'] -> libxcb[version='>=1.13,<2.0a0']
  - matplotlib==2.0.2 -> pyqt=5.6 -> qt[version='5.6.*,>=5.6.3,<5.7.0a0'] -> jpeg[version='>=9b,<10a']
  - matplotlib==2.0.2 -> pyqt=5.6 -> sip=4.18
  - matplotlib==2.0.2 -> python-dateutil
  - matplotlib==2.0.2 -> pytz
  - matplotlib==2.0.2 -> setuptools -> certifi[version='>=2016.09']
  - matplotlib==2.0.2 -> subprocess32
  - matplotlib==2.0.2 -> tornado -> backports_abc[version='>=0.4']
  - matplotlib==2.0.2 -> tornado -> futures
  - matplotlib==2.0.2 -> tornado -> singledispatch
  - matplotlib==2.0.2 -> tornado -> ssl_match_hostname -> backports
  - pandas=0.24 -> libgcc-ng[version='>=7.3.0']
  - pandas=0.24 -> libstdcxx-ng[version='>=7.3.0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> blas==1.0=mkl
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0'] -> libopenblas[version='>=0.3.3,<1.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0']
  - pandas=0.24 -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5']
  - pandas=0.24 -> pytz
  - pyproj -> libgcc-ng[version='>=7.3.0']
  - pyproj -> numpy -> blas==1.0=mkl
  - pyproj -> numpy -> libgfortran-ng[version='>=7,<8.0a0']
  - pyproj -> numpy -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> libffi[version='>=3.2.1,<4.0a0'] -> libstdcxx-ng[version='>=7.2.0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> readline[version='>=7.0,<8.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - pyproj -> numpy -> python[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<6.0a0']
  - pyproj -> proj4[version='>=5.2.0,<5.2.1.0a0']
  - shapely -> geos[version='>=3.7.1,<3.7.2.0a0'] -> libgcc-ng[version='>=7.3.0']
  - shapely -> geos[version='>=3.7.1,<3.7.2.0a0'] -> libstdcxx-ng[version='>=7.3.0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> blas==1.0=mkl
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> libffi[version='>=3.2.1,<4.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<7.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> readline[version='>=7.0,<8.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - shapely -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<6.0a0']
```

</details>

One strange part that I noticed is:

```
...
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> blas==1.0=mkl
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl[version='>=2019.3,<2020.0a0'] -> intel-openmp
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0'] -> libopenblas[version='>=0.3.3,<1.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0']
  - pandas=0.24 -> numpy[version='>=1.12.1,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0']
...
```

where pandas->numpy requires ``mkl_fft`` requires Python 2.7, while this is a Python 3.6 environment that is being created. 

## Steps to Reproduce

The yaml environment file is this one: https://github.com/geopandas/geopandas/blob/master/ci/travis/36-pd024.yaml (but also happens for https://github.com/geopandas/geopandas/blob/master/ci/travis/35-minimal.yaml)

The environment is created with `conda env create --file=36-pd024.yaml`

## Environment information

From https://travis-ci.org/geopandas/geopandas/jobs/551100679:

```
$ conda info
     active environment : None
       user config file : /home/travis/.condarc
 populated config files : /home/travis/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/travis/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/travis/miniconda/pkgs
                          /home/travis/.conda/pkgs
       envs directories : /home/travis/miniconda/envs
                          /home/travis/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-1028-gcp ubuntu/16.04.5 glibc/2.23
                UID:GID : 2000:2000
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment] 2019-06-29 21:50
Yes, closing as duplicate of #8844 - there is one or more packages in the stack that depend on the free channel.

As I mention in https://github.com/conda/conda/issues/8844#issuecomment-506910071, you can work around this with:

```
conda config --set restore_free_channel true
```
or equivalently, setting the ``CONDA_RESTORE_FREE_CHANNEL`` environment variable to true.

**Closed by msarahan** 2019-06-29 21:50 UTC

**Comment by jorisvandenbossche** [comment] 2019-06-29 21:54
Yes, a test with restoring the free channel is already running.

But is that a long term solution though? Is there a way to see which package is depending on the free channel?

**Comment by jorisvandenbossche** [comment] 2019-06-29 21:56
Restoring the free channel works.

Is the pandas=0.24->numpy->mpl_ftt requiring python 2.7 in a python 3.6 environment not a bit strange?

**Comment by msarahan** [comment] 2019-06-29 21:58
Work is ongoing for improving solver messaging.  What you are confused by is certainly misleading.

#8834 will help some, but there will be more work to do.  Since this removal of free is kind of a special case, if we can isolate the unavailable packages better and match them up with what exists only in ``free``, maybe we can put up a better message.  As you can see, that isolation is the tricky part.
