### ISSUE TITLE
Conda update conda-build produces Error 183 on windows

### ISSUE THREAD

**Issue by r-jain1** [conda/conda#2881] opened 2016-06-27 16:28 UTC
conda update conda-build on windows produces: 

<img width="1280" alt="screen shot 2016-06-27 at 11 26 56 am" src="https://cloud.githubusercontent.com/assets/17412057/16387360/24fe1616-3c5a-11e6-94cb-667998f0972f.png">

The same error is also given when running conda-build pycosat, conda-build pyyaml, and conda-build pip on windows

**Comment by mcg1969** [comment] 2016-06-28 21:56
I believe this is a duplicate of #2876 and is fixed by #2882. @kalefranz

**Closed** 2017-05-04 18:28 UTC
