### ISSUE TITLE
Creating Python 2.7 environment leads to unexpected error

### ISSUE THREAD

**Issue by tomnewport** [conda/conda#1078] opened 2015-01-06 11:19 UTC
conda fails when creating new environment:
    
    $ conda create -n python2 python=2.7 anaconda --yes
    
    An unexpected error has occurred, please consider sending the             |  51%
    following traceback to the conda GitHub issue tracker at:
    
        https://github.com/conda/conda/issues
    
    Include the output of the command 'conda info' in your report.
    
    
    Traceback (most recent call last):
      File "/****/****/*****/anaconda3/bin/conda", line 5, in <module>
        sys.exit(main())
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
        args_func(args, p)
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 206, in args_func
        args.func(args, p)
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/cli/main_create.py", line 50, in execute
        install.install(args, parser, 'create')
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 397, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 587, in execute_actions
        execute_plan(plan, index, verbose)
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 569, in execute_plan
        link(prefix, arg, index=index)
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 525, in link
        install.link(pkgs_dir, prefix, dist, lt, index=index)
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/install.py", line 531, in link
        update_prefix(join(prefix, f), prefix, placeholder, mode)
      File "/****/****/*****/anaconda3/lib/python3.4/site-packages/conda/install.py", line 252, in update_prefix
        with open(path, 'rb') as fi:
    FileNotFoundError: [Errno 2] No such file or directory: '/****/****/*****/anaconda3/envs/python2/lib/python2.7/site-packages/numpy/distutils/site.cfg'
    
    
    
    $ conda info
    Current conda install:
    
                 platform : linux-64
            conda version : 3.7.3
      conda-build version : 1.8.2
           python version : 3.4.2.final.0
         requests version : 2.5.0
         root environment : /****/****/*****/anaconda3  (writable)
      default environment : /****/****/*****/anaconda3
         envs directories : /****/****/*****/anaconda3/envs
            package cache : /****/****/*****/anaconda3/pkgs
             channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                            http://repo.continuum.io/pkgs/pro/linux-64/
              config file : None
        is foreign system : False

**Comment by soapy1** [comment] 2016-10-13 18:57
I can't reproduce this issue on the newest version of conda. Closing the issue; if this is still a problem for you after updating conda, please reopen the issue.

**Closed by soapy1** 2016-10-13 18:57 UTC
