### ISSUE TITLE
Doc: CLI help does not mention how to remove environment with `conda remove`

### ISSUE THREAD

**Issue by corneliusroemer** [conda/conda#12396] opened 2023-02-24 18:21 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I would like to remove/delete a conda environment.

Using `conda -h` is not helpful, there seems to be no command for it. The closest is `conda remove` which is described as:

```console
$ conda remove -h
Remove a list of packages from a specified conda environment.

This command will also remove any package that depends on any of the
specified packages as well---unless a replacement can be found without
that dependency. If you wish to skip this dependency checking and remove
just the requested packages, add the '--force' option. Note however that
this may result in a broken environment, so use this with caution.
```

Notably, this does not mention the use case of deleting a whole environment _at all_.

Yet, according to the documentation, it _is_ used for removing a whole environment via `--all`:

> To remove an environment, in your terminal window or an Anaconda Prompt, run:
> ```
> conda remove --name myenv --all
> ```
> You may instead use conda env remove --name myenv.
> 
> To verify that the environment was removed, in your terminal window or an Anaconda Prompt, run:
> ```
> conda info --envs
> ```
> The environments list that displays should not show the removed environment.
> https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment

The CLI help should mention this more explicitly, rather than just within one of many options but in top level `conda -h`

### Conda Info

```shell
version conda 22.11.1
```

**Comment by kenodegard** [comment] 2023-03-06 15:35
This is a duplicate of https://github.com/conda/conda/issues/12358

**Closed by kenodegard** 2023-03-06 15:35 UTC
Labels: source::community, type::documentation, duplicate
