### ISSUE TITLE
Nightly releases of master

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#929] opened 2014-09-30 18:03 UTC
Create a channel that contains nightly, automated builds of conda.  This way people could follow `master` without having to build from source.

Better yet, create a channel that builds any commit to master so someone can follow that by adding a `conda/dev` channel or some such.

**Comment by damianavila** [comment] 2015-02-03 17:09
FYI, I am doing something like this on https://github.com/bokeh/bokeh/pull/1800, triggering the build on tags pushes, but it could be done for every commit too if you want...

**Comment by tswicegood** [comment] 2015-02-07 01:16
@damianavila I'm hoping to use binstar-build for this.  @ilanschnell has done some work this past week to make it possible to build conda with conda-build, so that should make it pretty easy for us to drop in to there.

**Comment by damianavila** [comment] 2015-02-07 01:32
yep... this is what I have in mind too... but I wanted to have something working ASAP, so I invested some time with the conda-convert and TravisCI pair, at the end, eas a nice exercise to learn new things :wink:

**Comment by kalefranz** [comment] 2017-05-10 02:18
duplicate of #2085

**Closed by kalefranz** 2017-05-10 02:18 UTC
