### ISSUE TITLE
conda list error: ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by loeljem** [conda/conda#956] opened 2014-10-14 23:11 UTC
# packages in environment at /build/local/anaconda3:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/build/local/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/build/local/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/build/local/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/build/local/anaconda3/lib/python3.4/site-packages/conda/cli/main_list.py", line 227, in execute
    print_packages(prefix, args.regex, format, piplist=args.pip, json=args.json)
  File "/build/local/anaconda3/lib/python3.4/site-packages/conda/cli/main_list.py", line 189, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/build/local/anaconda3/lib/python3.4/site-packages/conda/cli/main_list.py", line 123, in add_pip_installed
    version, path = version.split(', ')
ValueError: too many values to unpack (expected 2)
joela@tmp131=>conda info
Current conda install:

             platform : linux-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.4.1
     root environment : /build/local/anaconda3  (writable)
  default environment : /build/local/anaconda3
     envs directories : /build/local/anaconda3/envs
        package cache : /build/local/anaconda3/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment] 2016-10-13 18:18
I can't reproduce this error on the newest version of conda. Closing this issue; if this is still a problem for you on the newest version of conda please reopen the issue.

**Closed by soapy1** 2016-10-13 18:18 UTC
