### ISSUE TITLE
Navigator not launching on Mac

### ISSUE THREAD

**Issue by mgjkdotnabla** [conda/conda#6987] opened 2018-03-05 16:15 UTC
Hi 

i'm getting the following error message when I launch Navigator on the Mac. I've updated anaconda and navigator and still the same error message. Manually removed offending file and still no joy.

Any advice?

Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/markkeane/Library/Application Support/binstar/config.yaml", line 1, column 1****

**Comment by goanpeca** [comment] 2018-03-05 16:31
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.11
```

**Closed by goanpeca** 2018-03-05 16:31 UTC

**Comment by mgjkdotnabla** [comment] 2018-03-05 16:38
thanks
