### ISSUE TITLE
Pylint fails to install `pylint-script.py`

### ISSUE THREAD

**Issue by sam-s** [conda/conda#14103] opened 2024-07-31 15:55 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`conda install --force-reinstall pylint` removes `Scripts\pylint-script.py` which is required by `Scripts\pylint.exe`

### Conda Info

```shell
active environment : c312
    active env location : ${localappdata}\miniconda3\envs\c312
            shell level : 2
       user config file : ${HOME}\.condarc
 populated config files : ${HOME}\.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.11.9.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.7.1=0
                          __cuda=11.4=0
                          __win=0=0
       base environment : ${localappdata}\miniconda3  (writable)
      conda av data dir : ${localappdata}\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda/win-64
                          https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda/noarch
                          https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/win-64
                          https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/noarch
                          https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo/win-64
                          https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo/noarch
                          https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev/win-64
                          https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : ${localappdata}\miniconda3\pkgs
                          ${HOME}\.conda\pkgs
                          ${localappdata}\conda\conda\pkgs
       envs directories : ${localappdata}\miniconda3\envs
                          ${HOME}\.conda\envs
                          ${localappdata}\conda\conda\envs
               platform : win-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.11.9 Windows/10 Windows/10.0.19045
solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
ssl_verify: False
channel_priority: flexible
channels:
  - https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
  - https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
  - https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo
  - https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev
  - conda-forge
  - defaults
report_errors: False
```

### Conda list

```shell
# packages in environment at ${localappdata}\miniconda3\envs\c312:
#
# Name                    Version                   Build  Channel
anyio                     4.4.0              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312he70551f_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
astroid                   3.2.4           py312h2e8e312_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
bbq-tools                 1.30.0a0               g966fb6b    https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
bloomberg.cis.sdk         1.1.16.2                      0    https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
blpapi                    3.24.4          py312hd5eb7cc_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
bqapi                     0.34.0                 g05b8b63    https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
bqclient                  0.11.0a0               g6540660    https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
bqevents                  1.5.0a0                 py312_0    https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev
bqlmetadata               0.99.0a0               g21df3e5    https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
bqlogger                  0.31.0                 ge1c3661    https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py312h53d5487_1    conda-forge
bzip2                     1.0.8                h2466b09_7    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
ca-certificates           2024.7.4             h56e8100_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
cffi                      1.16.0          py312he70551f_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
ciso8601                  2.3.1           py312he70551f_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h0d7def4_0    conda-forge
coverage                  7.4.1                    pypi_0    pypi
cryptography              43.0.0          py312h9500af3_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.2           py312h275cf98_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.8              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et-xmlfile                1.1.0                    pypi_0    pypi
exceptiongroup            1.2.2              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
exchange-calendars        4.5.5              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.53.1          py312h4389bb4_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
fsspec                    2024.6.1           pyhff2d567_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
fx                        0.0.0                    pypi_0    pypi
gettext                   0.22.5               h5728263_2    conda-forge
gettext-tools             0.22.5               h7d00a51_2    conda-forge
glib                      2.80.3               h7025463_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
glib-tools                2.80.3               h4394cf3_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
gst-plugins-base          1.24.6               hb0a98b8_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
gstreamer                 1.24.6               h5006eae_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
holidays                  0.53               pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
importlib_metadata        8.2.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.2.0           h57928b3_980    conda-forge
ipykernel                 6.29.5             pyh4bbf305_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
ipympl                    0.9.4              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
ipython                   8.26.0             pyh7428d3b_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
ipython_genutils          0.2.0              pyhd8ed1ab_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
ipywidgets                8.1.3              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
isort                     5.13.2             pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpickle                3.2.2              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
jsonpointer               3.0.0           py312h2e8e312_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
jupyter                   1.0.0             pyhd8ed1ab_10    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.4.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_nbextensions 0.7.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312h2e8e312_0    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_highlight_selected_word 0.2.0           pyhd8ed1ab_1006    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.6.1              pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.4              pyhd8ed1ab_0    conda-forge
jupyterlab_execute_time   3.1.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.11             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
kiwisolver                1.4.5           py312h0d7def4_1    conda-forge
korean_lunar_calendar     0.3.1              pyhd8ed1ab_0    conda-forge
krb5                      1.21.3               hdf4eb48_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libasprintf               0.22.5               h5728263_2    conda-forge
libasprintf-devel         0.22.5               h5728263_2    conda-forge
libblas                   3.9.0              23_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              23_win64_mkl    conda-forge
libclang                  18.1.8          default_hec7ea82_1    conda-forge
libclang13                18.1.8          default_ha5278ca_1    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.4                hd77b12b_1    defaults
libgettextpo              0.22.5               h5728263_2    conda-forge
libgettextpo-devel        0.22.5               h5728263_2    conda-forge
libglib                   2.80.3               h7025463_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
libhwloc                  2.11.1          default_h8125262_1000    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libintl-devel             0.22.5               h5728263_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              23_win64_mkl    conda-forge
libogg                    1.3.5                h2466b09_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libpq                     16.3                 hab9416b_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.46.0               h2466b09_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 hcd874cb_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzlib                   1.3.1                h2466b09_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
lxml                      5.2.2           py312h56c7e3b_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.5           py312he70551f_0    conda-forge
matplotlib                3.9.1           py312h2e8e312_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
matplotlib-base           3.9.1           py312h90004f6_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkl                       2024.1.0           h66d3029_694    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclassic                 1.1.0              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.4               hd8ed1ab_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
nbconvert-pandoc          7.16.4               hd8ed1ab_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
notebook                  6.5.7              pyha770c72_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numpy                     2.0.1           py312h49bc9c5_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.3.1                h2466b09_2    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
pandas                    2.2.2           py312h72972c8_1    conda-forge
pandas_market_calendars   4.4.0              pyha770c72_0    conda-forge
pandoc                    3.3                  h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h3d7b363_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py312h381445a_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
pip                       24.1.2             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
prompt_toolkit            3.0.47               hd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
psutil                    6.0.0           py312h4389bb4_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyapp                     36                       pypi_0    pypi
pyarrow                   15.0.0                   pypi_0    pypi
pyasn1                    0.6.0              pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
pybql                     0.127.0a0              ga1af868    https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
pylint                    3.2.6              pyhd8ed1ab_0    conda-forge
pyluach                   2.2.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.10         py312hd77b12b_0    defaults
pyqt5-sip                 12.13.0         py312h2bbff1b_0    defaults
pyrefdata                 0.4.0                      py_0    https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.12.3          h2628c8c_0_cpython    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
python-dateutil           2.9.0post0      py312haa95532_0    defaults
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.14                     pypi_0    pypi
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywin32                   306             py312h53d5487_2    conda-forge
pywinpty                  2.0.13          py312h53d5487_0    conda-forge
pyyaml                    6.0.1           py312he70551f_1    conda-forge
pyzmq                     24.0.1          py312h2bbff1b_0    defaults
qhull                     2020.2               hc790b64_5    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
qt-main                   5.15.8              h06adc49_23    conda-forge
qtconsole                 5.5.2              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.5.2              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.19.1          py312h2615798_0    conda-forge
ruff                      0.5.5           py312h7a6832a_0    conda-forge
scikit-learn              1.5.1           py312h816cc57_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
scipy                     1.14.0          py312h1f4e10d_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
send2trash                1.8.3              pyh5737063_0    conda-forge
setuptools                71.0.4             pyhd8ed1ab_0    conda-forge
sip                       6.7.12          py312h53d5487_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sklearn-pandas            2.2.0                    pypi_0    pypi
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sqlite                    3.46.0               h2466b09_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.2          py312h1a27103_0    conda-forge
tbb                       2021.12.0            hc790b64_3    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
terminado                 0.18.1             pyh5737063_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.13.0             pyha770c72_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h4389bb4_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
typing_extensions         4.12.2             pyha770c72_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
vc                        14.3                h8a93ad2_20    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.6.0             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        4.0.11             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.4.6                h8cc25b3_1    defaults
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.5                he1f189c_4    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
zlib                      1.3.1                h2466b09_1    https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
zstandard                 0.23.0          py312h7606c53_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

**Comment by travishathaway** [comment] 2024-08-01 10:43
@sam-s,

Thanks for reporting this. I'm pretty sure this is a problem with the `pytlint` package on conda-forge. You will want to report that here:

- https://github.com/conda-forge/pylint-feedstock

I can confirm that I also get this error though. Here's the commands I ran:

Create a new environment with pylint at its latest version:
```bash
conda create -n pylint -c conda-forge -y pylint
```

Activate and try to run the `pylint` command:
```bash
conda activate pylint
pylint --help
# command not found error
```

When I instead use the `defaults` channel everything works as expected:

```bash
conda create -n pylint -c defaults -y pylint
conda activate pylint
pylint --help
# command is found and help prints
```

Because there is not much we can do on this project to resolve this issue, I will now be closing this issue. Thanks for understanding.

**Closed by travishathaway** 2024-08-01 10:43 UTC
Labels: type::bug
