### ISSUE TITLE
Misleading error when trying to create environment from missing file

### ISSUE THREAD

**Issue by drdavella** [conda/conda#6781] opened 2018-01-24 18:25 UTC
### Steps to Reproduce
When running the following command with a non-existant environment file:

```
$ conda env create -f nonexistant.yml

SpecNotFound: Can't process without a name
```

This doesn't make sense. The environment file can contain the name of the environment to be created, so the `-n` option is not required in this case.

## Expected Behavior

Instead, I should get an error for a missing file, maybe something like the following:
```
$ conda env create -f nonexistant.yml

Given environment file path 'nonexistant.yml' does not exist
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/ddavella/miniconda3  (writable)
    default environment : /Users/ddavella/miniconda3/envs/cubeviz
       envs directories : /Users/ddavella/miniconda3/envs
                          /Users/ddavella/.conda/envs
          package cache : /Users/ddavella/miniconda3/pkgs
                          /Users/ddavella/.conda/pkgs
           channel URLs : http://ssb.stsci.edu/astroconda/osx-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ddavella/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 1187:1031
```

**Comment by kalefranz** [comment] 2018-01-25 00:11
Duplicate of https://github.com/conda/conda/issues/5681

**Closed by kalefranz** 2018-01-25 00:11 UTC
Labels: source:community, tag:environment-spec, type:techdebt
