### ISSUE TITLE
#cookiecutter + python 2.7 (win-32 bit) package combination = Error  message (Install with Anaconda) 

### ISSUE THREAD

**Issue by JeffreyJackovich** [conda/conda#1151] opened 2015-02-13 17:37 UTC
Hi There,

This might be an isolated Win-32 issue, however, installing "#cookiecutter" resulted in an, "unjustifiable package specification."  After, I installed, "urllib3", and was prompted with the following error:
-"pyasn1.error.PyAsn1"

Before installing, #cookiecutter, I installed "beautifulsoup4-4.3.2" and "urllib3" (urllib3 - downloaded : pyasn1-0.1.7, ngb-httpsclient-0.3.2, and urllib3-1.9).  Thus, not sure if I can isolate the issue, but I only received an error after downloading #cookiecutter.  From the site, cookiecutter looks like a great/well supported package, so it was probably the installs prior, but want to make this aware in case a known work-around is available to resolve or avoid this issue.

Thanks!

Error 1.  "-conda install -c https://conda.binstar.org/pydanny cookiecutter
Fetching package metadata: ........
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ] |#################################################| 100%

Hint: the following combinations of packages create a conflict with the
remaining packages:
  - python 2.7*
  - cookiecutter

Error 2. C:\Users\jjackovich\AppData\Local\Continuum\Anaconda>conda install -c https://conda.binstar.org/dhirschfeld requests-ntlm
Fetching package metadata: .....An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker "

"
  File "C:\Users\jjackovich\AppData\Local\Continuum\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 356, in __get_result
    raise self._exception
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

C:\Users\jjackovich\AppData\Local\Continuum\Anaconda>conda install -c https://conda.binstar.org/anaconda requests
Fetching package metadata: .......An unexpected error has occurred, please consider sending the"

**Comment by asmeurer** [comment] 2015-02-16 18:02
The cookiecutter thing looks unrelated (the issue there is that it's not been built for Python 2.7). 

I've never seen this pyasn1 error before.

**Comment by asmeurer** [comment] 2015-05-28 20:43
Try `conda update requests`

**Comment by asmeurer** [comment] 2015-05-28 20:45
Closing as duplicate of https://github.com/conda/conda/issues/1261

**Closed by asmeurer** 2015-05-28 20:45 UTC
