### ISSUE TITLE
cannot update conda

### ISSUE THREAD

**Issue by johndanskin** [conda/conda#4207] opened 2017-01-06 15:02 UTC
"conda update conda" seemed to work once, then I couldn't update anaconda, then I tried to update conda again to see if it was OK, and I got this. Probably I'll see if I can do a clean install. I'm posting this in case it's somehow helpful. "conda update anaconda" died on the same line.

Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.19.0
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Applications/Anaconda/anaconda  (writable)
    default environment : /Applications/Anaconda/anaconda
       envs directories : /Applications/Anaconda/anaconda/envs
          package cache : /Applications/Anaconda/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Applications/Anaconda/anaconda/bin/conda update conda`

    Traceback (most recent call last):
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Applications/Anaconda/anaconda/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/Applications/Anaconda/anaconda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/Applications/Anaconda/anaconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Applications/Anaconda/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by andershellberg** [comment] 2017-01-06 19:11
I encountered this same error today. I could run "conda update conda" once, then both that and "conda update anaconda" produce the same set of errors:

`Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.3.5
         python version : 3.4.1.final.0
       requests version : 2.12.4
       root environment : C:\Users\Anders\Anaconda3  (writable)
    default environment : C:\Users\Anders\Anaconda3
       envs directories : C:\Users\Anders\Anaconda3\envs
          package cache : C:\Users\Anders\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False






    Traceback (most recent call last):
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Anders\Anaconda3\lib\concurrent\futures\_base.py", line 402, in result
        return self.__get_result()
      File "C:\Users\Anders\Anaconda3\lib\concurrent\futures\_base.py", line 354, in __get_result
        raise self._exception
      File "C:\Users\Anders\Anaconda3\lib\concurrent\futures\thread.py", line 54, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Users\Anders\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'`

**Comment by kimmotikka** [comment] 2017-01-06 19:16
Got a similar problem while trying to update conda:

" AttributeError: 'unicode' object has no attribute 'iteritems'"

??
regards, Kimmo
------
user:anaconda user$ conda update qtpy
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /Users/user/anaconda  (writable)
    default environment : /Users/user/anaconda
       envs directories : /Users/user/anaconda/envs
          package cache : /Users/user/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/user/.condarc
           offline mode : False



`$ /Users/user/anaconda/bin/conda update qtpy`




    Traceback (most recent call last):
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 139, in install
        context.validate_all()
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/common/configuration.py", line 752, in validate_all
        for source in self.raw_data))
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/common/configuration.py", line 752, in <genexpr>
        for source in self.raw_data))
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/common/configuration.py", line 739, in check_source
        collected_errors = parameter.collect_errors(self, typed_value, match.source)
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/common/configuration.py", line 642, in collect_errors
        for key, val in iteritems(value) if not isinstance(val, element_type))
      File "/Users/user/anaconda/lib/python2.7/site-packages/conda/compat.py", line 135, in iteritems
        return iter(getattr(d, _iteritems)())
    AttributeError: 'unicode' object has no attribute 'iteritems'

tikkak:anaconda user$ conda list
# packages in environment at /Users/user/anaconda:
#
_license                  1.1                      py27_1
abstract-rendering        0.5.1               np110py27_0
alabaster                 0.7.6                    py27_0
anaconda                  2.4.1               np110py27_0
anaconda-client           1.2.1                    py27_0
appnope                   0.1.0                    py27_0
appscript                 1.0.1                    py27_0
apptools                  4.2.1                    py27_0    <unknown>
argcomplete               1.0.0                    py27_1
astropy                   1.0.6               np110py27_0
atom                      0.3.9                    py27_0
babel                     2.1.1                    py27_0
backports_abc             0.4                      py27_0
bcolz                     0.9.0                np19py27_0
beautiful-soup            4.3.2                    py27_0
beautifulsoup4            4.4.1                    py27_0
binstar                   0.11.0                   py27_0
biopython                 1.63                 np18py27_0    <unknown>
bitarray                  0.8.1                    py27_0    <unknown>
blaze                     0.6.3                np19py27_0
blaze-core                0.8.3                    py27_0
blz                       0.6.2                np19py27_1
bokeh                     0.10.0                   py27_0
boto                      2.38.0                   py27_0
bottleneck                1.0.0               np110py27_0
bugs                      0.5.1                     <pip>
casuarius                 1.1                      py27_0    <unknown>
cdecimal                  2.3                      py27_0    <unknown>
certifi                   14.05.14                 py27_0
cffi                      1.2.1                    py27_0
chaco                     4.4.1                np19py27_0
clyent                    1.2.0                    py27_0
colorama                  0.3.3                    py27_0
conda                     4.2.7                    py27_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py27_0
cryptography              1.0.2                    py27_0
cubes                     0.10.2                   py27_4    <unknown>
curl                      7.45.0                        0
cycler                    0.9.0                    py27_0
cython                    0.23.4                   py27_1
cytoolz                   0.7.4                    py27_0
datashape                 0.4.7               np110py27_1
dateutil                  2.1                      py27_2    <unknown>
dbdreader                 0.3.7                     <pip>
decorator                 4.0.4                    py27_0
distribute                0.6.45                   py27_0    <unknown>
dockserver-talk           0.2.2                     <pip>
docutils                  0.12                     py27_0
dynd-python               0.7.0                    py27_0
enable                    4.3.0                np19py27_2
enaml                     0.9.8                    py27_0
enum34                    1.0.4                    py27_0
envisage                  4.4.0                    py27_1    <unknown>
fastcache                 1.0.2                    py27_0
fastkml                   0.11                      <pip>
flask                     0.10.1                   py27_1    <unknown>
freetype                  2.5.5                         0
funcsigs                  0.4                      py27_0
future                    0.13.1                   py27_0
futures                   2.1.6                    py27_0
geojson                   1.0.9                     <pip>
geos                      3.3.3                         0
gevent                    1.0.1                    py27_0
gevent-websocket          0.9.3                    py27_0
gevent_zeromq             0.2.5                    py27_3    <unknown>
greenlet                  0.4.9                    py27_0
grin                      1.2.1                    py27_1    <unknown>
h5py                      2.5.0               np110py27_4
hdf5                      1.8.15.1                      2
idna                      2.0                      py27_0
imaging                   1.1.7                    py27_2    <unknown>
ipaddress                 1.0.14                   py27_0
ipykernel                 4.1.1                    py27_0
ipython                   4.0.1                    py27_0
ipython-notebook          4.0.4                    py27_0
ipython-qtconsole         4.0.1                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.0                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jdcal                     1.0                      py27_0
jedi                      0.9.0                    py27_0
jinja2                    2.8                      py27_0
jpeg                      8d                            1    <unknown>
jsonschema                2.4.0                    py27_0
jupyter                   1.0.0                    py27_1
jupyter_client            4.1.1                    py27_0
jupyter_console           4.0.3                    py27_0
jupyter_core              4.0.6                    py27_0
keyring                   3.3                      py27_0    <unknown>
kiwisolver                0.1.3                    py27_0
launcher                  1.0.0                         3
lcms                      1.19                          0
libdynd                   0.7.0                         0
libevent                  2.0.20                        1    <unknown>
libnetcdf                 4.3.2                         0
libpng                    1.6.17                        0
libsodium                 0.4.5                         0
libtiff                   4.0.6                         1
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2    <unknown>
llvm                      3.3                           0    <unknown>
llvmlite                  0.8.0                    py27_0
llvmmath                  0.1.1                np17py27_2    <unknown>
llvmpy                    0.12.7                   py27_0
lxml                      3.4.4                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.5.0               np110py27_0
mayavi                    4.3.1                np18py27_0    <unknown>
mdp                       3.3                  np18py27_0    <unknown>
meta                      0.4.2.dev                py27_0    <unknown>
mistune                   0.7.1                    py27_0
mock                      1.0.1                    py27_0    <unknown>
multipledispatch          0.4.8                    py27_0
MySQL-python              1.2.4b4                   <pip>
nbconvert                 4.0.0                    py27_0
nbformat                  4.0.1                    py27_0
netcdf4                   1.1.1                np19py27_0
networkx                  1.10                     py27_0
nltk                      3.1                      py27_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py27_0
notebook                  4.0.6                    py27_0
numba                     0.22.1              np110py27_0
numexpr                   2.4.4               np110py27_0
numpy                     1.10.1                   py27_0
odo                       0.3.4                    py27_0
openpyxl                  2.2.6                    py27_0
openssl                   1.0.2g                        0
pandas                    0.17.1              np110py27_0
path.py                   8.1.2                    py27_1
patsy                     0.4.0               np110py27_0
pep8                      1.6.2                    py27_0
pexpect                   3.3                      py27_0
pickleshare               0.5                      py27_0
pil                       1.1.7                    py27_1
pillow                    3.0.0                    py27_1
pip                       8.1.0                    py27_0
pip                       9.0.1                     <pip>
ply                       3.8                      py27_0
psutil                    3.3.0                    py27_0
ptyprocess                0.5                      py27_0
py                        1.4.30                   py27_0
pyasn1                    0.1.9                    py27_0
pyaudio                   0.2.7                    py27_0    <unknown>
pycosat                   0.6.1                    py27_0    <unknown>
pycparser                 2.14                     py27_0
pycrypto                  2.6.1                    py27_0    <unknown>
pycurl                    7.19.5.1                 py27_3
pyface                    4.4.0                    py27_0    <unknown>
pyflakes                  1.0.0                    py27_0
pygeoif                   0.6                       <pip>
pygments                  2.0.2                    py27_0
pykit                     0.2.0                np18py27_0    <unknown>
pymongo                   3.3.0                    py27_0
PyMySQL                   0.6.1                     <pip>
pymysql                   0.7.6                    py27_0
pyopenssl                 0.15.1                   py27_1
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.4                   py27_1
pysal                     1.11.0                   py27_0
pysam                     0.6                      py27_0    <unknown>
pyside                    1.1.2                    py27_1    <unknown>
pytables                  3.2.2               np110py27_0
pytest                    2.8.1                    py27_0
python                    2.7.12                        1
python-dateutil           2.4.2                    py27_0
python-nvd3               0.11.0                    <pip>
python.app                1.2                      py27_4
pytz                      2015.7                   py27_0
pyyaml                    3.11                     py27_1
pyzmq                     14.7.0                   py27_1
qt                        4.8.7                         1
qtconsole                 4.1.1                    py27_0
readline                  6.2                           2    <unknown>
redis                     2.6.9                         0    <unknown>
redis-py                  2.10.3                   py27_0
requests                  2.9.1                    py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_0
runipy                    0.1.3                    py27_0
scikit-image              0.11.3              np110py27_0
scikit-learn              0.17                np110py27_1
scipy                     0.16.0              np110py27_1
serial2rudics             0.0.1                     <pip>
setuptools                20.2.2                   py27_0
shapely                   1.5.7                    py27_0
shiboken                  1.1.2                    py27_0    <unknown>
simpleais                 0.6.5                     <pip>
simplegeneric             0.8.1                    py27_0
simplekml                 1.3.0                     <pip>
simpy                     3.0.9                     <pip>
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.0                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.3.1                    py27_0
sphinx_rtd_theme          0.1.7                    py27_0
spyder                    2.3.8                    py27_0
spyder-app                2.3.8                    py27_0
sqlalchemy                1.0.9                    py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
statsmodels               0.6.1               np110py27_0
surfalarm                 0.1                       <pip>
sympy                     0.7.6.1                  py27_0
terminado                 0.5                      py27_1
tk                        8.5.18                        0
toolz                     0.7.4                    py27_0
tornado                   4.3                      py27_0
traitlets                 4.0.0                    py27_0
traits                    4.4.0                    py27_0    <unknown>
traitsui                  4.4.0                    py27_0    <unknown>
ujson                     1.33                     py27_0    <unknown>
unicodecsv                0.14.1                   py27_0
vtk                       5.10.1                   py27_0    <unknown>
werkzeug                  0.11.2                   py27_0
wheel                     0.29.0                   py27_0
xlrd                      0.9.4                    py27_0
xlsxwriter                0.7.7                    py27_0
xlwings                   0.5.0                    py27_0
xlwt                      1.0.0                    py27_0
xz                        5.0.5                         0
yaml                      0.1.6                         0
zeromq                    4.1.3                         0
zlib                      1.2.8                         0

**Comment by kalefranz** [comment] 2017-05-01 19:54
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:54 UTC
