### ISSUE TITLE
IOError(11, 'Resource temporarily unavailable') when downloading mkl on Travis

### ISSUE THREAD

**Issue by ssanderson** [conda/conda#6473] opened 2017-12-15 20:59 UTC
Over on [zipline](https://github.com/quantopian/zipline) we've suddenly started seeing all of our travis builds reliably failing during a call to `conda create` while installing `mkl`.  Adding `--debug` to our conda invocation shows the following traceback during the download:

```bash
`$ /home/travis/miniconda/bin/conda create -n testenv --debug --use-local --yes -c quantopian pip python=2.7 numpy=1.11.1 scipy=0.17.1 libgfortran=3.0 ta-lib=0.4.9`
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 492, in execute
        self._execute_action(action)
      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 513, in _execute_action
        raise CondaMultiError(exceptions)
    CondaMultiError: IOError(11, 'Resource temporarily unavailable')
    IOError(11, 'Resource temporarily unavailable')
    IOError(11, 'Resource temporarily unavailable')
```

Based on just the traceback it's not clear where the actual `IOError` is being raised. 

We're not seeing this issue in our windows builds on AppVeyor, nor have we been able to reproduce the failure locally so far, so it seems to be somehow related to the environment on travis.

**Comment by lheagy** [comment] 2017-12-16 20:35
We are encountering the same issue in multiple libraries (eg. https://travis-ci.org/simpeg/discretize/builds/317459170) . Appveyor is fine, but travis is erroring on the install.

Thanks for your help!

**Comment by kalefranz** [comment] 2017-12-16 20:59
It’s occurring during downloading and extracting packages. No idea what’s going on with the file system here. It’s clearly something going on with the OS though. Guess you could google for details of Travis-CI and IOError(11, 'Resource temporarily unavailable')

**Comment by lheagy** [comment] 2017-12-18 21:32
travis-ci/travis-ci#8934 is related. 

We updated the install to include the `--quiet` flag, and now the tests seem to be running fine on travis.

**Comment by ssanderson** [comment] 2017-12-18 21:41
FWIW, we appear to have fixed this in zipline by ensuring that the stdout of the travis build is in blocking mode (per this comment https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959).

**Comment by CJ-Wright** [comment] 2018-01-04 19:38
I'm having a similar problem (`--quiet` fixed it but I don't think that's a good long term fix)

**Comment by CJ-Wright** [comment] 2018-01-05 17:00
Also got with [`icu`](https://travis-ci.org/xpdAcq/xpdSim/builds/325512353#L1873)

**Comment by kalefranz** [comment] 2018-01-05 17:18
The exceptions appear a little differently between python2 and python 3.  They're both errno `11`.  The python3 exception is something like

    BlockingIOError: [Errno 11] write could not complete without blocking

**Comment by kalefranz** [comment] 2018-01-05 17:21
Travis-CI is the only infrastructure this has been reported for so far.  I'm open to solutions for Conda if anyone wants to make suggestions, but I don't know exactly what they would be.

For now I think `--quiet` is the best solution.

**Comment by kalefranz** [comment] 2018-01-05 17:24
The comment linked from above (https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959) is pretty useful.  I'm not sure if this is something conda should take on itself to configure though.  Seems like if we did, we could end up doing something that another group of people wouldn't like.

**Comment by kalefranz** [comment] 2018-01-05 17:28
Do want to note that the first reports here (in #6468 I believe) were with conda 4.3 and before 4.4 was released.  So the new progressbar and spinner UI elements in 4.4 shouldn't be isolated as the cause.

**Comment by kalefranz** [comment] 2018-01-24 00:02
Seems like this issue has quieted down. Not really something conda has control of I don't think.  Going to go ahead and close it.

**Closed by kalefranz** 2018-01-24 00:02 UTC
