### ISSUE TITLE
conda canary installation resets or ignores ```conda config --set always-yes yes```

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3342] opened 2016-08-24 16:47 UTC
Original discussion on flowdock:

Ben
@Kale, i may be seeing some odd behavior in the canary setup:
conda config --set always_yes yes --set changeps1 no
The following packages will be UPDATED:
conda:     4.1.11-py35_0 --> 4.2.4-py35_0 conda-canary
conda-env: 2.5.2-py35_0  --> 2.6.0-0      conda-canary

Fetching packages ...
conda-env-2.6. 100% |################################| Time: 0:00:00 227.04 kB/s
conda-4.2.4-py 100% |################################| Time: 0:00:00   1.13 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
+conda --version
conda 4.2.4
+conda install conda-env
Fetching package metadata .........
Solving package specifications: ..........
# All requested packages already installed.
# packages in environment at /home/travis/miniconda:
#
conda-env                 2.6.0                         0    conda-canary
+conda create -n adam python=3.5
Fetching package metadata .........
Solving package specifications: ..........
Package plan for installation in environment /home/travis/miniconda/envs/adam:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    setuptools-25.1.6          |           py35_0         478 KB
The following NEW packages will be INSTALLED:
    openssl:    1.0.2h-1     
    pip:        8.1.2-py35_0 
    python:     3.5.2-0      
    readline:   6.2-2        
    setuptools: 25.1.6-py35_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py35_0
    xz:         5.2.2-0      
    zlib:       1.2.8-3      
Proceed ([y]/n)? 
#always_yes
The above hangs and it looks like conda config --set always_yes yes doesn’t set things to always yes
Does installing conda_canary overwrite condarc file ?
@Kale, testing this locally i see the same behavior; enable always_yes and conda install … hangs waiting for input

CC @quasiben @kalefranz

**Comment by quasiben** [comment] 2016-08-24 18:26
👍

**Comment by quasiben** [comment] 2016-08-25 14:34
I did a bit of debugging to see if it was an easy fix and I was unsuccessful.  Still, I'll post some notes to help the next person.

- from the looks of things `always_yes` should be of type: `PrimitiveParameter(False, parameter_type=(bool, NoneType), aliases=('yes',))` ?https://github.com/conda/conda/blob/master/conda/base/context.py#L81

- I don't know what `_cache` is in the `Configuration` object but the variable is populated with the below just before it's overwritten by an empty `dict()`: https://github.com/conda/conda/blob/master/conda/common/configuration.py#L693 :

> {'always_yes': True, '_envs_dirs': (), 'channel_alias': 'https://conda.anaconda.org/', '_root_dir': '/Users/quasiben/anaconda', 'channel_priority': True, 'show_channel_urls': True, 'update_dependencies': True, 'binstar_upload': None, 'bld_path': '', 'offline': False}

**Comment by quasiben** [comment] 2016-08-25 14:46
Hmm, actually it seems like the problem is around `aliases`.  When this is removed everything runs smoothly

**Comment by csoja** [comment] 2016-09-06 17:23
fixed with PR3374

**Closed by csoja** 2016-09-06 17:23 UTC
Labels: cio, ¡blocking!

**Comment by quasiben** [comment] 2016-09-06 17:47
@kalefranz let me know when a new package is pushed `conda-canary` channel
