### ISSUE TITLE
`source activate` is broken in 4.4 for zsh

### ISSUE THREAD

**Issue by drorata** [conda/conda#6639] opened 2018-01-03 10:09 UTC
After updating to 4.4.6 I can no longer activate environments. Trying `source activate my_env` returns:

```
/Users/drorata/anaconda3/bin/activate:pwd:66: too many arguments
```

`conda info` returns:

```
     active environment : None
       user config file : /Users/drorata/.condarc
 populated config files : /Users/drorata/.condarc
          conda version : 4.4.6
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /Users/drorata/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/drorata/anaconda3/pkgs
                          /Users/drorata/.conda/pkgs
       envs directories : /Users/drorata/anaconda3/envs
                          /Users/drorata/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.4 Darwin/17.3.0 OSX/10.13.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

The environment variables are:

```
COLORFGBG=7;0
ITERM_PROFILE=Default
XPC_FLAGS=0x0
LANG=en_US.UTF-8
PWD=/Users/drorata
SHELL=/opt/local/bin/zsh
TERM_PROGRAM_VERSION=3.1.5
TERM_PROGRAM=iTerm.app
PATH=/Users/drorata/Applications/google-cloud-sdk/bin:/Users/drorata/anaconda3/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet
COLORTERM=truecolor
TERM=xterm-256color
HOME=/Users/drorata
TMPDIR=/var/folders/6z/h5jqtwss0m13gg40vv06gs_40000gn/T/
ZSH=/Users/drorata/.oh-my-zsh-drorata
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LANGUAGE=en_US.UTF-8
EDITOR=vim
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
_=/usr/bin/env
```

If I use `bash`, the behavior seems to be correct.

What have you done in this update???? How can I solve the problem.

**Comment by drorata** [comment] 2018-01-03 10:26
As per the recommendations [here](https://github.com/conda/conda/blob/a4c4feae404b2b378e106bd25f62cc8be15c768f/CHANGELOG.md#440-2017-12-20), I removed the `PATH` change and added 

```
.  ~/anaconda3/etc/profile.d/conda.sh
conda activate base
```

to my `.zshrc`. Now, with `conda activate my_env` I can activate an environment.

**LESSON**: The change introduced was *not* backwards compatible in my case.

**Comment by kalefranz** [comment] 2018-01-04 22:01
It should have been backward compatible.  Apparently not for zsh.  We're targeting at least eight different shells, each with their own individual quirks.  The most tested shells are going to be `bash` on unix and `cmd.exe` on Windows.  Doing our best on the others.  Definitely have room to improve though.  The improvements we've made in 4.4 should eventually help us get there.

**Comment by drorata** [comment] 2018-01-05 07:06
The move from `source (de)activate` to `conda (de)activate` is great. But due to the fact it is so critical, I would have hoped to see at least some notice during the update process. Glitches in backward compatibility are always to be expected when something that fundamental is overhauled.

**Comment by kalefranz** [comment] 2018-01-05 20:05
I'd like to fix whatever you ran into, but I'm having trouble reproducing it.  Can you help me understand where I'm going wrong?

```
docker run --rm -it ubuntu /bin/bash
apt-get update
apt-get install -y bzip2 wget vim zsh

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -bfp $HOME/miniconda
$HOME/miniconda/bin/conda update -y conda

echo "export PATH=$HOME/miniconda/bin:$PATH" >> $HOME/.zshrc
zsh

conda create -n my_env -y
source activate my_env
```

**Comment by drorata** [comment] 2018-01-05 21:46
I will try to provide more detailed reproducing procedure later. I can however confirm that he problem occurs on another machine. I suspect the cause is somehow https://github.com/robbyrussell/oh-my-zsh 

As soon as I find the time I will get back and elaborate this issue.

**Comment by drorata** [comment] 2018-01-06 07:07
I indeed can reproduce the problem on another machine. However not as a minimal example. In `.zshrc` I had to:

```
# export PATH="/Users/drorata/anaconda3/bin:$PATH"
source /Users/drorata/anaconda3/etc/profile.d/conda.sh
conda activate
```

Note that merely `. /Users/drorata/anaconda3/etc/profile.d/conda.sh` doesn't work and yields:

```
Users/drorata/.zshrc:pwd:101: too many arguments
/Users/drorata/.zshrc:102: command not found: conda
```

**Comment by mbargull** [comment] 2018-01-12 12:48
This might be not `zsh`-specific, but a duplicate of https://github.com/conda/conda/issues/6667#issuecomment-355789782, I think.
@drorata, do you maybe have `alias .=pwd` defined somewhere? If so, try to `unalias .` before running `conda.sh` for now.

**Comment by drorata** [comment] 2018-01-12 12:55
Now I understand why sourcing `conda.sh` using `.` didn't work and I had to revert to `source`. I indeed have `alias .=pwd`... I will keep it; 

Anyways I switched now to `conda (de)actiavte`...

**Comment by mbargull** [comment] 2018-01-12 13:23
Right, if you `source` and then only use the `conda` shell function, you avoid running another `.` as you don't execute the de-/activate scripts -- so, correct, no further conflicts for your `alias .` 👍
Since #6667 tracks the issue's cause, you may close this one.

**Closed** 2018-01-12 15:14 UTC

**Comment by marcusjwhelan** [comment] 2018-06-14 21:09
@mbargull  what if source activate my_env does not bring up the new shell or conda activate my_env but conda info shows its active?
