### ISSUE TITLE
conda local install falls over

### ISSUE THREAD

**Issue by tfeb** [conda/conda#3917] opened 2016-11-19 09:56 UTC
I 've written a trivial recipe to wrap up a fairly crufty C library so I can install it in a conda environment.  `conda build` builds it happily, but then `conda install --use-local libmo_unpack` falls over.  It may be that the package is bogus (I think it's OK actually), but even so it should not die like this I think.

    Current conda install:

                   platform : linux-64
              conda version : 4.2.12
           conda is private : False
          conda-env version : 4.2.12
        conda-build version : 2.0.10
             python version : 2.7.12.final.0
           requests version : 2.12.1
           root environment : /local/tfb/packages/portability  (writable)
        default environment : /local/tfb/packages/portability
           envs directories : /local/tfb/packages/portability/envs
              package cache : /local/tfb/packages/portability/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/pro/linux-64
                              https://repo.continuum.io/pkgs/pro/noarch
                config file : None
               offline mode : False

    `$ /local/tfb/packages/portability/bin/conda install --use-local libmo_unpack`

        Traceback (most recent call last):
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
            return_value = func(*args, **kwargs)
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
            exit_code = args.func(args, p)
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
            install(args, parser, 'install')
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
            prefix=prefix)
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
            index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
            for url in urls]
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
            res = f(*args, **kwargs)
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/conda/fetch.py", line 116, in fetch_repodata
            timeout=(3.05, 60))
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
            return self.request('GET', url, **kwargs)
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
            resp = self.send(prep, **send_kwargs)
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
            r.content
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/requests/models.py", line 772, in content
            self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
          File "/local/tfb/packages/portability/lib/python2.7/site-packages/requests/models.py", line 705, in generate
            chunk = self.raw.read(chunk_size)
        AttributeError: 'exceptions.OSError' object has no attribute 'read'

**Comment by sscherfke** [comment] 2016-11-21 08:52
This issue occurs when you upgrade `requests` from `2.11.1` to `2.12.*`.

**Comment by mparry** [comment] 2016-11-21 10:12
Indeed; I also see this after updating `requests`, when trying to install from a local channel via file URL. (There is a win-64 subdirectory but not a noarch one. Not sure if that's valid as such, but it was fine previously.)

The issue seems to be that `connection.LocalFSAdapter` stores the exception in `resp.raw` and this greatly upsets `requests` when it attempts to process it. Changing that line to do the following instead seems to fix it:

`resp.raw = StringIO(str(exc))`

**Comment by mparry** [comment] 2016-11-21 10:54
Ah, I see 640e308a9dfe already fixed this in master / 4.3

**Comment by sscherfke** [comment] 2016-11-21 11:21
Will there be a backport to fix 4.2.* or is the 4.3 release not too far away?

**Comment by tfeb** [comment] 2016-11-21 11:43
As a dumb user of the released version, is there anything I can easily do (nuking caches?) which will make things work for me while waiting for a new release?  I'm happy to do anything which won't perturb `conda upgrade --all` (or which I know how to undo in due course so I can upgrade) as I'd like not to have to rebuild my environment from cold.

**Comment by mparry** [comment] 2016-11-21 11:58
As a temporary workaround you can just replace L289 of connection.py, in your local install of conda in the root env, with the fix I gave above. Certainly worked for me.

Either that, or downgrade `requests` to 2.11.1 (and possibly pin it).

**Comment by tfeb** [comment] 2016-11-21 17:39
@mparry: thanks: that works fine for me

**Comment by kalefranz** [comment] 2016-11-22 22:48
@sscherfke 

> Will there be a backport to fix 4.2.* or is the 4.3 release not too far away?

No, not planned.  We could.  You could even cherry-pick and create a PR if you wanted pointed at 4.2.x.  We updated the metadata for all conda packages < 4.3 to cap requests at 2.11.1

**Comment by kalefranz** [comment] 2016-11-22 22:49
duplicate of https://github.com/conda/conda/issues/3928 btw

**Comment by kalefranz** [comment] 2016-11-22 22:51
In general, a couple things that should always get you out of trouble if a conda installation gets corrupted somehow.

## Option 1

Try `conda list --revisions`.  Find the latest working `rev`.  Then `conda install --rev REVNUM`.

## Option 2

Do something similar to

    wget  http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
    bash Miniconda2-latest-Linux-x86_64.sh -bfp PATH_TO_CONDA_ROOT

**Closed by kalefranz** 2016-11-22 22:51 UTC
