### ISSUE TITLE
"conda update" fails after upgrading to conda 4.5.6 from 4.5.5

### ISSUE THREAD

**Issue by bounlu** [conda/conda#7520] opened 2018-07-10 06:25 UTC
**I'm submitting a...**
  - bug report

## Current Behavior

After upgrading conda from 4.5.5 to 4.5.6, updating command for any package fails with the below error:

$ conda update bwa
Solving environment: failed

ERROR REPORT

    Traceback (most recent call last):
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/solve.py", line 506, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/solve.py", line 439, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/solve.py", line 580, in _prepare
        self.subdirs, prepared_specs)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 94, in query
        self.load()
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 148, in load
        _internal_state = self._load()
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 216, in _load
        mod_etag_headers.get('_mod'))
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 416, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 479, in request
        prep.url, proxies, stream, verify, cert
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 654, in merge_environment_settings
        env_proxies = get_environ_proxies(url) or {}
      File "/home/users/nus/csioan/software/anaconda2/lib/python2.7/site-packages/requests/utils.py", line 617, in get_environ_proxies
        if should_bypass_proxies(url):
    TypeError: should_bypass_proxies_patched() takes exactly 3 arguments (2 given)

`$ /home/users/nus/csioan/software/anaconda2/bin/conda update bwa`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/users/nus/csioan/software/anaconda2
          LD_LIBRARY_PATH=/home/users/nus/csioan/library:/cm/local/apps/gcc/5.1.0/lib:/cm/local/
                          apps/gcc/5.1.0/lib64
                  MANPATH=/usr/local/share/man:/usr/share/man/overrides:/usr/share/man/en:/usr/s
                          hare/man:/cm/local/apps/environment-
                          modules/current/share/man:/opt/pbs/share/man
               MODULEPATH=/app/modules/tools:/app/modules/interpreters:/app/modules/bio:/app/mod
                          ules/chem:/app/modules/earth:/app/modules/engineering:/app/modules
                          /dev-intel:/app/modules/dev-gnu:/app/modules/dev-
                          gpu:/app/modules/dev:/app/modules/sys:/app/modules/dev-java
                     PATH=/home/users/nus/csioan/software:/home/users/nus/csioan/software/cellra
                          nger-2.1.1:/home/users/nus/csioan/software/anaconda2/bin:/cm/local/app
                          s/gcc/5.1.0/bin:/app/pbs/bin:/app/pbs/bin:/usr/lib64/qt-3.3/bin:/usr/l
                          ocal/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bi
                          n:/sbin:/usr/sbin:/opt/pbs/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/users/nus/csioan/.condarc
 populated config files : /home/users/nus/csioan/.condarc
          conda version : 4.5.6
    conda-build version : 3.10.6
         python version : 2.7.15.final.0
       base environment : /home/users/nus/csioan/software/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/users/nus/csioan/software/anaconda2/pkgs
                          /home/users/nus/csioan/.conda/pkgs
       envs directories : /home/users/nus/csioan/software/anaconda2/envs
                          /home/users/nus/csioan/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.6 requests/2.13.0 CPython/2.7.15 Linux/2.6.32-696.30.1.el6.x86_64 rhel/6.9 glibc/2.12
                UID:GID : 20838:1002
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

### Steps to Reproduce

```
conda --version
```
conda 4.5.5
```
conda update conda
conda --version
```
conda 4.5.6
```
conda update bwa
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/users/nus/csioan/.condarc
 populated config files : /home/users/nus/csioan/.condarc
          conda version : 4.5.6
    conda-build version : 3.10.6
         python version : 2.7.15.final.0
       base environment : /home/users/nus/csioan/software/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/users/nus/csioan/software/anaconda2/pkgs
                          /home/users/nus/csioan/.conda/pkgs
       envs directories : /home/users/nus/csioan/software/anaconda2/envs
                          /home/users/nus/csioan/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.6 requests/2.13.0 CPython/2.7.15 Linux/2.6.32-696.30.1.el6.x86_64 rhel/6.9 glibc/2.12
                UID:GID : 20838:1002
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/users/nus/csioan/.condarc <==
ssl_verify: False
report_errors: True
auto_update_conda: False
channels:
  - bioconda
  - r
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
_ipyw_jlab_nb_ext_conf    0.1.0            py27h08a7f0c_0    defaults
_r-mutex                  1.0.0                     mro_2    r
alabaster                 0.7.11                     py_3    conda-forge
anaconda                  custom           py27h4a00acb_0    defaults
anaconda-client           1.6.5                      py_0    conda-forge
anaconda-navigator        1.8.4                    py27_0    defaults
anaconda-project          0.8.2                    py27_0    conda-forge
asn1crypto                0.24.0                     py_1    conda-forge
astroid                   1.6.5                    py27_0    conda-forge
astropy                   2.0.7                    py27_1    conda-forge
atomicwrites              1.1.5                    py27_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
babel                     2.6.0                      py_1    conda-forge
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.5                      py27_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                      py27_0    conda-forge
beautifulsoup4            4.6.0                    py27_0    conda-forge
bedtools                  2.27.1               he941832_2    bioconda
binutils_impl_linux-64    2.28.1               had2808c_3    defaults
binutils_linux-64         7.2.0               had2808c_27    defaults
bitarray                  0.8.1            py27h470a237_0    conda-forge
bkcharts                  0.2                      py27_0    conda-forge
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3                   py27_0    conda-forge
bleach                    1.4.2                    py27_0    bioconda
blinker                   1.4                        py_1    conda-forge
blosc                     1.14.0                        1    conda-forge
bokeh                     0.12.16                  py27_0    conda-forge
boto                      2.48.0           py27h9556ac2_1    defaults
boto3                     1.7.52                     py_0    conda-forge
botocore                  1.10.52                    py_0    conda-forge
bottleneck                1.2.1            py27h7eb728f_1    conda-forge
bwa                       0.7.17               ha92aebf_3    bioconda
bwidget                   1.9.11                        0    defaults
bz2file                   0.98                     py27_0    defaults
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
cdecimal                  2.3                      py27_0    conda-forge
certifi                   2018.4.16                py27_0    conda-forge
cffi                      1.11.5                   py27_0    conda-forge
chardet                   3.0.4                      py_1    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.3.9                      py_1    conda-forge
conda                     4.5.6                    py27_0    conda-forge
conda-build               3.10.6                   py27_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py27_0    conda-forge
configparser              3.5.0                    py27_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.2.1            py27hdffb7b8_1    conda-forge
curl                      7.60.0                        0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.28.4           py27hfc679d8_0    conda-forge
cytoolz                   0.9.0.1                  py27_0    conda-forge
dask                      0.18.1                     py_0    conda-forge
dask-core                 0.18.1                     py_0    conda-forge
datashape                 0.5.4                    py27_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.22.0                   py27_0    conda-forge
docutils                  0.14                     py27_0    conda-forge
entrypoints               0.2.3                    py27_1    conda-forge
enum34                    1.1.6                    py27_1    conda-forge
et_xmlfile                1.0.1                    py27_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fastcache                 1.0.2                    py27_0    conda-forge
fastqc                    0.11.7                        4    bioconda
filelock                  3.0.4                    py27_0    conda-forge
flask                     1.0.2                      py_1    conda-forge
flask-cors                3.0.4                      py_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
funcsigs                  1.0.2                      py_2    conda-forge
functools32               3.2.3.2                  py27_2    conda-forge
futures                   3.2.0                    py27_0    conda-forge
gcc_impl_linux-64         7.2.0                habb00fd_3    defaults
gcc_linux-64              7.2.0               h550dcbe_27    defaults
gensim                    3.5.0                    py27_0    conda-forge
get_terminal_size         1.0.0                haa9412d_0    defaults
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.0.2                    py27_0    bioconda
gfortran_impl_linux-64    7.2.0                hdf63c60_3    defaults
gfortran_linux-64         7.2.0               h550dcbe_27    defaults
glib                      2.55.0                        0    conda-forge
glob2                     0.4.1                    py27_0    bioconda
gmp                       6.1.2                hfc679d8_0    conda-forge
gmpy2                     2.0.8                    py27_0    conda-forge
graphite2                 1.3.11               hfc679d8_0    conda-forge
greenlet                  0.4.13                   py27_0    conda-forge
grin                      1.2.1                    py27_1    conda-forge
gsl                       2.4             blas_openblas_0  [blas_openblas]  conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
gxx_impl_linux-64         7.2.0                hdf63c60_3    defaults
gxx_linux-64              7.2.0               h550dcbe_27    defaults
h5py                      2.8.0            py27h470a237_0    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
hdf5                      1.10.1                        2    conda-forge
heapdict                  1.0.0                    py27_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                        py_1    conda-forge
imageio                   2.3.0                    py27_0    conda-forge
imagesize                 1.0.0                      py_1    conda-forge
intel-openmp              2018.0.3                      0    defaults
ipaddress                 1.0.22                     py_1    conda-forge
ipykernel                 4.8.2                    py27_0    conda-forge
ipython                   5.7.0                    py27_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.2.1                    py27_1    conda-forge
isort                     4.3.4                    py27_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jbig                      2.1                           0    conda-forge
jdcal                     1.4                      py27_0    conda-forge
jedi                      0.12.0                   py27_0    conda-forge
jinja2                    2.10                     py27_0    conda-forge
jmespath                  0.9.3                    py27_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
jsonschema                2.6.0                    py27_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py27_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.32.1                   py27_0    conda-forge
jupyterlab_launcher       0.10.5                   py27_0    conda-forge
keyring                   13.2.1                   py27_0    conda-forge
kiwisolver                1.0.1                    py27_1    conda-forge
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1                    py27_0    conda-forge
libcurl                   7.60.0               h1ad7b7a_0    defaults
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libgfortran               3.0.0                         1    defaults
libgfortran-ng            7.2.0                hdf63c60_3    defaults
libiconv                  1.15                 h470a237_1    conda-forge
libopenblas               0.2.20               h9ac9557_7    defaults
libpng                    1.6.34               ha92aebf_1    conda-forge
libsodium                 1.0.16                        0    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
libtiff                   4.0.9                he6b73bb_1    conda-forge
libtool                   2.4.6                         0    conda-forge
libxcb                    1.13                 h470a237_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
libxslt                   1.1.32               h88dbc4e_1    conda-forge
linecache2                1.0.0                    py27_0    conda-forge
llvmlite                  0.23.0                   py27_1    conda-forge
locket                    0.2.0                    py27_1    conda-forge
lxml                      4.2.3            py27hc9114bc_0    conda-forge
lzo                       2.10                          0    conda-forge
markupsafe                1.0                      py27_0    conda-forge
matplotlib                2.2.2                    py27_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.3                    py27_1    conda-forge
mkl                       2018.0.3                      1    defaults
mkl-service               1.1.2            py27hb2d42c5_4    defaults
mkl_fft                   1.0.2                    py27_0    conda-forge
mkl_random                1.0.1                    py27_0    conda-forge
more-itertools            4.2.0                      py_0    conda-forge
mpc                       1.1.0                hb705a9b_6    conda-forge
mpfr                      4.0.1                h16a7912_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.0              py27_mpich_2    conda-forge
mpich                     3.2.1                h26a2512_4    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.5.6            py27h2d50403_2    conda-forge
multipledispatch          0.5.0                    py27_0    conda-forge
navigator-updater         0.2.1                    py27_0    defaults
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py27_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  2.1                        py_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py27_2    conda-forge
notebook                  5.5.0                    py27_0    conda-forge
numba                     0.38.1                   py27_0    conda-forge
numexpr                   2.6.5                    py27_0    conda-forge
numpy                     1.14.5          py27_blas_openblashd3ea46f_201  [blas_openblas]  conda-forge
numpy-base                1.14.3           py27h0ea5e3f_1    defaults
numpydoc                  0.8.0                    py27_0    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
odo                       0.5.1                    py27_0    conda-forge
olefile                   0.45.1                     py_1    conda-forge
openblas                  0.2.20                        8    conda-forge
openjdk                   8.0.144          zulu8.23.0.3_1    conda-forge
openmpi                   2.1.2                         0    conda-forge
openpyxl                  2.4.0                    py27_0    bioconda
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.0                   py27_0    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                    py27_0    conda-forge
pango                     1.40.14                       0    conda-forge
parallel                  20160622                      1    bioconda
parso                     0.3.0                      py_0    conda-forge
partd                     0.3.8                      py_1    conda-forge
patchelf                  0.9                           2    conda-forge
path.py                   11.0.1                     py_0    conda-forge
pathlib2                  2.3.2                    py27_0    conda-forge
patsy                     0.5.0                    py27_0    conda-forge
pcre                      8.39                          0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
perl                      5.26.2               h470a237_0    conda-forge
perl-parallel-forkmanager 1.17                    pl526_1    bioconda
perl-threaded             5.22.0                       10    bioconda
pexpect                   4.6.0                    py27_0    conda-forge
pickleshare               0.7.4                    py27_0    conda-forge
pillow                    5.2.0                    py27_0    conda-forge
pip                       9.0.3                    py27_0    conda-forge
pixman                    0.34.0                        2    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prompt_toolkit            1.0.15                   py27_0    conda-forge
psutil                    5.4.6                    py27_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                    py27_0    conda-forge
py                        1.5.4                      py_0    conda-forge
pycairo                   1.16.3           py27h4d1f301_0    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3                    py27_0    conda-forge
pycparser                 2.18                     py27_0    conda-forge
pycrypto                  2.6.1                    py27_1    conda-forge
pycurl                    7.43.0.2         py27hb7f436b_0    defaults
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pylint                    1.9.2                    py27_0    conda-forge
pyodbc                    4.0.17                   py27_0    conda-forge
pyopenssl                 18.0.0                   py27_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      5.6.0            py27h8210e8a_6    conda-forge
pysocks                   1.6.8                    py27_1    conda-forge
pytables                  3.4.4                    py27_8    conda-forge
pytest                    3.6.2                    py27_0    conda-forge
python                    2.7.15                        0    conda-forge
python-crfsuite           0.9.5            py27h470a237_0    conda-forge
python-dateutil           2.3                      py27_0    bioconda
pytz                      2018.5                     py_0    conda-forge
pywavelets                0.5.2                    py27_1    conda-forge
pyyaml                    3.12                     py27_1    conda-forge
pyzmq                     17.0.0                   py27_4    conda-forge
qt                        5.6.2                         7    conda-forge
qtawesome                 0.4.4              pyh8a2030e_1    conda-forge
qtconsole                 4.3.1                    py27_0    conda-forge
qtpy                      1.4.2              pyh8a2030e_1    conda-forge
r                         3.4.1                  r3.4.1_0    r
r-assertthat              0.2.0                  r3.4.1_0    r
r-base                    3.4.1                         4    conda-forge
r-bh                      1.62.0_1               r3.4.1_0    r
r-bindr                   0.1                    r3.4.1_0    r
r-bindrcpp                0.2                    r3.4.1_0    r
r-boot                    1.3_19                 r3.4.1_0    r
r-class                   7.3_14                 r3.4.1_0    r
r-cli                     1.0.0                  r3.4.1_0    conda-forge
r-cluster                 2.0.6                  r3.4.1_0    r
r-codetools               0.2_15                 r3.4.1_0    r
r-colorspace              1.3_2                  r3.4.1_0    r
r-crayon                  1.3.4                  r3.4.1_0    conda-forge
r-dichromat               2.0_0                  r3.4.1_2    r
r-digest                  0.6.12                 r3.4.1_0    r
r-dplyr                   0.7.0                  r3.4.1_0    r
r-foreign                 0.8_68                 r3.4.1_0    r
r-ggally                  1.3.0                  r3.3.2_0    bioconda
r-ggplot2                 2.2.1                  r3.4.1_0    r
r-glue                    1.1.1                  r3.4.1_0    r
r-gridextra               2.2.1                  r3.4.1_0    r
r-gtable                  0.2.0                  r3.4.1_0    r
r-kernsmooth              2.23_15                r3.4.1_0    r
r-labeling                0.3                    r3.4.1_2    r
r-lattice                 0.20_35                r3.4.1_0    r
r-lazyeval                0.2.0                  r3.4.1_0    r
r-magrittr                1.5                    r3.4.1_2    r
r-mass                    7.3_47                 r3.4.1_0    r
r-matrix                  1.2_10                 r3.4.1_0    r
r-mgcv                    1.8_17                 r3.4.1_0    r
r-munsell                 0.4.3                  r3.4.1_0    r
r-nlme                    3.1_131                r3.4.1_0    r
r-nnet                    7.3_12                 r3.4.1_0    r
r-pillar                  1.2.2                    r341_0    conda-forge
r-pkgconfig               2.0.1                  r3.4.1_0    r
r-plogr                   0.1_1                  r3.4.1_0    r
r-plyr                    1.8.4                  r3.4.1_0    r
r-purrr                   0.2.2                         1    bioconda
r-r6                      2.2.1                  r3.4.1_0    r
r-rcolorbrewer            1.1_2                  r3.4.1_3    r
r-rcpp                    0.12.11                r3.4.1_0    r
r-recommended             3.4.1                  r3.4.1_0    r
r-reshape                 0.8.6                  r3.3.2_0    bioconda
r-reshape2                1.4.2                  r3.4.1_0    r
r-rlang                   0.1.1                  r3.4.1_0    r
r-rpart                   4.1_11                 r3.4.1_0    r
r-scales                  0.4.1                  r3.4.1_0    r
r-spatial                 7.3_11                 r3.4.1_0    r
r-stringi                 1.1.5                  r3.4.1_0    r
r-stringr                 1.2.0                  r3.4.1_0    r
r-survival                2.41_3                 r3.4.1_0    r
r-tibble                  1.3.3                  r3.4.1_0    r
r-tidyr                   0.6.3                  r3.4.1_0    r
r-tidyselect              0.2.3                  r3.4.1_0    conda-forge
r-utf8                    1.1.3                  r3.4.1_0    conda-forge
r-viridislite             0.2.0                  r3.4.1_0    r
readline                  7.0                           0    conda-forge
requests                  2.13.0                   py27_0    conda-forge
requests-oauthlib         1.0.0                    py27_0    conda-forge
rope                      0.10.7                   py27_0    conda-forge
ruamel_yaml               0.15.42          py27h470a237_0    conda-forge
s3transfer                0.1.13                   py27_0    conda-forge
samtools                  1.8                  h46bd0b3_5    bioconda
scandir                   1.7                      py27_0    conda-forge
scikit-image              0.14.0           py27hfc679d8_1    conda-forge
scikit-learn              0.19.1          py27_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py27_blas_openblas_200  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py27_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.0.0                   py27_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3                  py27_0    conda-forge
sip                       4.18                     py27_1    conda-forge
six                       1.11.0                   py27_1    conda-forge
smart_open                1.6.0                      py_1    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.0.1                      py_1    conda-forge
sortedcontainers          2.0.4                    py27_0    conda-forge
sphinx                    1.7.5                    py27_0    conda-forge
sphinxcontrib             1.0              py27h1512b58_1    defaults
sphinxcontrib-websupport  1.0.1                    py27_0    conda-forge
spyder                    3.3.0                    py27_1    conda-forge
spyder-kernels            0.2.4                    py27_0    conda-forge
sqlalchemy                1.2.9                    py27_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
sra-tools                 2.9.1_1              h470a237_0    bioconda
ssl_match_hostname        3.5.0.1                  py27_1    conda-forge
star                      2.6.0c                        1    bioconda
statsmodels               0.9.0                    py27_0    conda-forge
subprocess32              3.5.2                    py27_0    conda-forge
sympy                     1.1.1                    py27_0    conda-forge
tblib                     1.3.2                    py27_0    conda-forge
terminado                 0.8.1                    py27_0    conda-forge
testpath                  0.3.1                    py27_0    conda-forge
tk                        8.6.7                         0    conda-forge
tktable                   2.10                 h14c3975_0    defaults
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.0.2                    py27_0    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
traitlets                 4.3.2                    py27_0    conda-forge
twython                   3.7.0                      py_0    conda-forge
typing                    3.5.2.2                  py27_0    bioconda
unicodecsv                0.14.1                   py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
unixodbc                  2.3.4                         1    conda-forge
urllib3                   1.12                     py27_0    bioconda
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5                      py27_0    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.1                   py27_0    conda-forge
widgetsnbextension        3.2.1                    py27_0    conda-forge
wrapt                     1.10.11                  py27_0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xlsxwriter                1.0.5                      py_0    conda-forge
xlwt                      1.3.0                    py27_0    conda-forge
xorg-libxau               1.0.8                h470a237_5    conda-forge
xorg-libxdmcp             1.1.2                h470a237_6    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.5                hfc679d8_3    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</p></details>

**Comment by Scheibs** [comment] 2018-07-10 15:11
I have the same issue.

**Comment by mbargull** [comment] 2018-07-13 02:18
duplicate of https://github.com/conda/conda/issues/7506

**Closed by mbargull** 2018-07-13 02:18 UTC
