### ISSUE TITLE
pip attempts to install to incorrect directory /lib/python2.7

### ISSUE THREAD

**Issue by mindriot101** [conda/conda#1170] opened 2015-02-25 21:10 UTC
When I try to install a package using pip (e.g. the [emcee](http://dan.iel.fm/emcee/current/) package), pip tries to install to the wrong directory. Instead of installing to `/home/astro/phsnag/anaconda/lib/python2.7` it tries to install to `/lib/python2.7` which is apparently missing the prefix related to my anaconda installation.

I've tried with a fresh copy of bash (`sudo -u phsnag bash`) i.e. with no custom environment variables set and the same error occurs. It also occurs with conda environments. I can get packages to install with the `--root ~/anaconda` command line argument, but it is not as clean. I have tested with a new installation, and other shells; all fail in the same way.

Error log:

```
Collecting emcee
  Using cached emcee-2.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in ./anaconda/lib/python2.7/site-packages (from emcee)
Installing collected packages: emcee
  Running setup.py install for emcee
    error: could not create '/lib/python2.7': Permission denied
    Complete output from command /home/astro/phsnag/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hfnnWw/emcee/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JgXGMS-record/install-record.txt --single-version-externally-managed --compile:
    running install

    running build

    running build_py

    creating build

    creating build/lib

    creating build/lib/emcee

    copying emcee/__init__.py -> build/lib/emcee

    copying emcee/autocorr.py -> build/lib/emcee

    copying emcee/ensemble.py -> build/lib/emcee

    copying emcee/interruptible_pool.py -> build/lib/emcee

    copying emcee/mh.py -> build/lib/emcee

    copying emcee/mpi_pool.py -> build/lib/emcee

    copying emcee/ptsampler.py -> build/lib/emcee

    copying emcee/sampler.py -> build/lib/emcee

    copying emcee/tests.py -> build/lib/emcee

    copying emcee/utils.py -> build/lib/emcee

    running egg_info

    writing requirements to emcee.egg-info/requires.txt

    writing emcee.egg-info/PKG-INFO

    writing top-level names to emcee.egg-info/top_level.txt

    writing dependency_links to emcee.egg-info/dependency_links.txt

    warning: manifest_maker: standard file '-c' not found



    reading manifest file 'emcee.egg-info/SOURCES.txt'

    reading manifest template 'MANIFEST.in'

    writing manifest file 'emcee.egg-info/SOURCES.txt'

    running install_lib

    creating /lib/python2.7

    error: could not create '/lib/python2.7': Permission denied

    ----------------------------------------
    Command "/home/astro/phsnag/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hfnnWw/emcee/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JgXGMS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hfnnWw/emcee
```

**Comment by asmeurer** [comment] 2015-02-25 21:23
What is the output of `conda info -a`?

**Comment by mindriot101** [comment] 2015-02-25 21:25
```
Current conda install:

             platform : linux-64
        conda version : 3.9.1
  conda-build version : 1.8.2
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : /home/astro/phsnag/anaconda  (writable)
  default environment : /home/astro/phsnag/anaconda
     envs directories : /home/astro/phsnag/anaconda/envs
        package cache : /home/astro/phsnag/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
                        http://conda.binstar.org/srwalker101/linux-64/
                        http://conda.binstar.org/srwalker101/noarch/
                        https://conda.binstar.org/binstar/linux-64/
                        https://conda.binstar.org/binstar/noarch/
          config file : /home/astro/phsnag/.condarc
    is foreign system : False

# conda environments:
#
cluster                  /home/astro/phsnag/anaconda/envs/cluster
root                  *  /home/astro/phsnag/anaconda

sys.version: 2.7.9 |Anaconda 2.1.0 (64-bit)| (default...
sys.prefix: /home/astro/phsnag/anaconda
sys.executable: /home/astro/phsnag/anaconda/bin/python
conda location: /home/astro/phsnag/anaconda/lib/python2.7/site-packages/conda
conda-build: /home/astro/phsnag/anaconda/bin/conda-build
conda-convert: /home/astro/phsnag/anaconda/bin/conda-convert
conda-develop: /home/astro/phsnag/anaconda/bin/conda-develop
conda-env: /home/astro/phsnag/anaconda/bin/conda-env
conda-index: /home/astro/phsnag/anaconda/bin/conda-index
conda-metapackage: /home/astro/phsnag/anaconda/bin/conda-metapackage
conda-pipbuild: /home/astro/phsnag/anaconda/bin/conda-pipbuild
conda-skeleton: /home/astro/phsnag/anaconda/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: /home/astro/phsnag/.local/lib:/home/astro/phsnag/.local/lib:/usr/local/mdsplus/lib:/home/astro/phsgan/Software/Terapix/lib
PATH: /home/astro/phsnag/.cabal/bin:/home/astro/phsnag/anaconda/bin:/home/astro/phsnag/.local/bin:/home/astro/phsnag/.gem/ruby/1.8/bin:/home/astro/phsnag/.bin:/home/astro/phsnag/.cabal/bin:/usr/local/bin:/home/astro/phsnag/.local/bin:/warwick/moab/default/bin:/home/astro/phsnag/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/kde3/bin:/opt/cross/bin:/warwick/iraf/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/local/mdsplus/bin:/usr/NX/bin:/usr/lib/qt3/bin:/warwick/scilab/4.1/bin:/warwick/visit/linux-x86_64/bin:/home/astro/phsnag/bin:/home/astro/phsgan/Software/Terapix/bin:/home/astro/phsnag/.local/go/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /home/astro/phsnag/.continuum
    /home/astro/phsnag/anaconda/licenses
License files (license*.txt):
    /home/astro/phsnag/.continuum/license_academic_20140918074445.txt
               Reading license file : 1
                    Signature valid : 1
                       Vendor match : 1
                            product : u'Academic'
                           packages : u'numbapro mkl iopro'
                           end_date : u'2015-09-18'
                               type : None
Package/feature end dates:
    numbapro        : 2015-09-18
    iopro           : 2015-09-18
    mkl             : 2015-09-18
```

**Comment by asmeurer** [comment] 2015-02-25 21:51
I've not seen this issue before. My only suggestion is to force reinstall pip and setuptools (`conda install -f pip setuptools`).

**Comment by mindriot101** [comment] 2015-02-26 10:40
I'm afraid your suggestion didn't work.

I understand you haven't seen this behaviour before. I am a user of two machines, both of which are SLES, with very similar kernels etc., the same version of zsh (though I've determined it's not shell specific), and one shows this error and the other doesn't. All of my dotfiles are the same (under version control etc.) and I cannot find out what the source of the error is.

**Comment by asmeurer** [comment] 2015-02-26 16:53
If you create a new conda environment (`conda create -n test python pip`) can you reproduce it there?

**Comment by mindriot101** [comment] 2015-02-26 17:58
Yes, it is the same:

```
$ conda create -n test python pip                                                
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /home/astro/phsnag/anaconda/envs/test:

The following NEW packages will be INSTALLED:

    ipython:    2.4.1-py27_0
    openssl:    1.0.1k-0
    pip:        6.0.8-py27_0
    python:     2.7.9-1
    readline:   6.2-2
    setuptools: 12.2-py27_0
    sqlite:     3.8.4.1-0
    system:     5.8-1
    tk:         8.5.15-0
    zlib:       1.2.8-0

Linking packages ...
[      COMPLETE      ] |############################################################| 100%
#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#

$ source activate test                                                           
discarding /home/astro/phsnag/anaconda/bin from PATH
prepending /home/astro/phsnag/anaconda/envs/test/bin to PATH
(test)
$ pip install pep8                                                               
Collecting pep8
  Using cached pep8-1.6.2-py2.py3-none-any.whl
Installing collected packages: pep8

  Exception:
  Traceback (most recent call last):
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/site-packages/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/site-packages/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/site-packages/pip/req/req_install.py", line 963, in move_wheel_files
      isolated=self.isolated,
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/site-packages/pip/wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/site-packages/pip/wheel.py", line 176, in clobber
      os.makedirs(dest)
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/os.py", line 150, in makedirs
      makedirs(head, mode)
    File "/home/astro/phsnag/anaconda/envs/test/lib/python2.7/os.py", line 157, in makedirs
      mkdir(name, mode)
  OSError: [Errno 13] Permission denied: '/lib/python2.7'
```

I've used pep8 for this example as it's pure python and has no dependencies.

**Comment by ilanschnell** [comment] 2015-02-28 16:43
I'm wondering if there are environment variables which change the default behavior of where pip installs packages into.  To me this seems to be more of a pip than a conda issue.

**Comment by mindriot101** [comment] 2015-02-28 17:03
I did consider environment variables. I have tried running `sudo -u phsnag zsh` to get a fresh environment, along with other shells e.g. `sudo -u phsnag bash`. I have also tried running zsh with the `--no-rcs` option preventing the sourcing of my zshrc files. I get the same error.

I agree it *probably* isn't a conda issue.

**Comment by dckc** [comment] 2016-04-21 15:11
I'm seeing the same symptoms. I'm also on SLES.

```
> cat /etc/SuSE-release 
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
```

**Comment by dckc** [comment] 2016-04-21 15:14
Ah...

> If you have a very restrictive umask (such as 077), you will see “permission denied” errors.
-- [Issue: permission denied errors during install](http://conda.pydata.org/docs/troubleshooting.html#issue-permission-denied-errors-during-install)

**Comment by dckc** [comment] 2016-04-21 15:16
even with `umask 007`, I lose.

**Comment by dckc** [comment] 2016-04-21 15:20
I think I found a work-around: `pip install --prefix ~/miniconda2/envs/hetlog pathlib`.

**Comment by mindriot101** [comment] 2016-05-13 14:48
I think I found the cause of the problem. I had a file `$HOME/.pydistutils.cfg` which was the following:

```cfg
[install]
prefix=
```

This file sets defaults when installing with pip. It now makes sense that I had the line `error: could not create '/lib/python2.7': Permission denied` in my error log, which with variables should be `<prefix>/lib/python2.7`. Also command line options have priority which is how your work-around "solves" the problem.

Once I removed this file, I could install with `pip` again. @dckc do you have a similar file? It might be a `setup.cfg` in the current directory

**Comment by dckc** [comment] 2016-05-16 19:55
Yes, I have a similar file.

The only difference is a comment pointing to [Combine --user with --prefix error with setup.py install](http://stackoverflow.com/a/4495175/846824) on stackoverflow.

**Comment by JoseAlban** [comment] 2016-06-23 10:03
@mindriot101 good spot! I had exactly the same issue.
+1

**Comment by bofinbabu** [comment] 2016-10-08 06:41
Try this:
`pip install <lib_name> --user`

**Comment by mindriot101** [comment] 2016-10-31 10:26
This issue is solved for me, @dckc is it solved for you? I'm happy to close this issue if everyone else is?

**Comment by dckc** [comment] 2016-10-31 14:56
It's not bothering me since Apr 21 when I found a work-around.

I don't know if it's really fixed for SLES, but I don't mind if you close it.

**Closed** 2017-05-01 21:18 UTC
