### ISSUE TITLE
Update using Anaconda Navigator

### ISSUE THREAD

**Issue by Chimsom** [conda/conda#6637] opened 2018-01-02 17:03 UTC
Hello...
I am been trying to update packages using Anaconda Navigator, but this error keeps coming...
**Unsatisfiable Error: The following specifications were found to be in conflict:
  - anaconda-client==1.6.6
  - anaconda==5.0.1 -> anaconda-client==1.6.5=py27h9642776_0
Use "conda info <package>" to see the dependencies for each package.**
Please I need help with this.
Thanks

**Comment by kalefranz** [comment] 2018-01-04 23:42
@goanpeca What's the best way to get out of this currently?

Hopefully we'll have https://github.com/ContinuumIO/anaconda-issues/issues/4298 implemented for Anaconda 5.1.

**Comment by goanpeca** [comment] 2018-01-04 23:43
Hmmm not sure, I am working on a new release soon so I will tackle this tomorrow  (moving to navi repo)

**Comment by goanpeca** [comment] 2018-01-08 22:41
@kalefranz I don't understand why this is an issue, why is conda not complying, should not it change to anaconda-custom thinguie and move on ?

**Comment by kalefranz** [comment] 2018-01-09 17:40
What is the equivalent conda command that Navi is issuing here?  Also, might have just been an issue for very early versions of conda 4.4?  Not sure what version of conda we're dealing with here.

**Comment by goanpeca** [comment] 2018-01-09 17:50
`<path-to-python> <path-to-conda> install --yes --json --force-pscheck --prefix <prefix> anaconda-client==1.6.6`

**Comment by kalefranz** [comment] 2018-01-10 21:27
That's what I suspect too.  Closing, and we can reopen if there's information indicating the issue is still ongoing.

**Closed by kalefranz** 2018-01-10 21:27 UTC
