### ISSUE TITLE
Error "Access Denied" when trying to install basemap on Windows 10

### ISSUE THREAD

**Issue by libbywiz** [conda/conda#2739] opened 2016-06-17 13:10 UTC
Hi, when I try to install basemap I get the following errors:
Traceback (most recent call last):
  File "C:\Users\Libby\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\Libby\Anaconda2\lib\site-packages\conda\install.py", line 828, in extract
    os.rename(temp_path, path)
WindowsError: [Error 5] Access is denied

Here's my conda info:
           platform : win-64
        conda version : 4.1.1
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\Libby\Anaconda2  (writable)
  default environment : C:\Users\Libby\Anaconda2
     envs directories : C:\Users\Libby\Anaconda2\envs
        package cache : C:\Users\Libby\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

ETA: I have already tried running as an administrator and still get the same error.

**Comment by kalefranz** [comment] 2016-06-17 16:32
Thanks for the report.  This is a duplicate of #2687 and #2697, with a fix coming with 4.1.2 in a few hours.

**Closed by kalefranz** 2016-06-17 16:32 UTC
