### ISSUE TITLE
Conda install fails: AttributeError: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by hippwndon** [conda/conda#11759] opened 2022-08-25 05:17 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I recently upgraded my Ubuntu version from impish to jammy and haven't opened Conda in the past few months (since May), for context, so I'm not really sure when Conda broke. Running conda in my command line didn't instantiate anything, so I ran rm -rf ~/anaconda3 and rm -rf ~/.condarc ~/.conda ~/.continuum as per suggestion of a stackoverflow answer. I then downloaded the newest version of Anaconda from the downloads page and ran the .sh script. Running it resulted in a variety of errors after selectin yes at this prompt: Do you wish the installer to initialize Anaconda3
by running conda init? [yes|no] and unfortunately I don't happen to have the output on me. I ran the rm -rf commands again, then tried reinstalling, but with the newest miniconda release also to no avail. I reinstalled pip as well after this and tried reinstalling anaconda, with another row of errors after the same prompt. Conda was not recognized in the command line a single time, even after setting PATHs. Here is the most recent output:
```
done
installation finished.
Do you wish the installer to initialize Anaconda3
by running conda init? [yes|no]
[no] >>> yes
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/whitenoiz/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whitenoiz/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/whitenoiz/.local/lib/python3.9/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false

Thank you for installing Anaconda3!

===========================================================================

Working with Python and Jupyter is a breeze in DataSpell. It is an IDE
designed for exploratory data analysis and ML. Get better data insights
with DataSpell.

DataSpell for Anaconda is available at: https://www.anaconda.com/dataspell
```

### Conda Info

```shell
Traceback (most recent call last):
  File "/home/whitenoiz/.local/bin/conda", line 5, in <module>
    from conda.cli.pip_warning import main
ModuleNotFoundError: No module named 'conda'
```

### Additional Context

`Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
`
`>>> print(sys.version)
3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
`

**Comment by hippwndon** [comment] 2022-08-25 06:08
Looks like adding sudo to the install command and installing python3.9 fixed the list of errors, but conda still is unusable. 
I still keep receiving `  File "/home/whitenoiz/.local/bin/conda", line 5, in <module>
    from conda.cli.pip_warning import main
ModuleNotFoundError: No module named 'conda'
`
but conda isn't listed in my pip packages.

**Comment by kenodegard** [comment] 2022-08-26 00:02
@hippwndon This is a duplicate of https://github.com/conda/conda/issues/11279, please refer to the suggested solutions there.

**Closed by kenodegard** 2022-08-26 00:02 UTC
Labels: type::bug
