### ISSUE TITLE
conda update broken after 'conda update conda'

### ISSUE THREAD

**Issue by ian-wat** [conda/conda#6130] opened 2017-10-09 17:41 UTC
I ran the following:

```
> conda update conda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/ian/miniconda3:

The following packages will be SUPERSEDED by a higher-priority channel:

    conda: 4.3.28-py36h620ea6e_0 --> 4.3.27-py36h2866c0b_0

Proceed ([y]/n)? y

>
```

but there was no further output. Now, I get errors:

```
> conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/ian/miniconda3  (writable)
    default environment : /home/ian/miniconda3
       envs directories : /home/ian/miniconda3/envs
                          /home/ian/.conda/envs
          package cache : /home/ian/miniconda3/pkgs
                          /home/ian/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Linux/4.9.0-3-amd64 debian/9.2 glibc/2.24
                UID:GID : 1000:1000

`$ /home/ian/miniconda3/bin/conda update conda`




    Traceback (most recent call last):
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/ian/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506357774.387 for timestamp
```

Please help! Thanks.

**Comment by nehaljwani** [comment] 2017-10-09 18:01
Closing as duplicate of https://github.com/conda/conda/issues/6096

Basically, you need to delete the files which have timestamp in floating point. You can try running:
```
grep -l '"timestamp": [0-9]\+\.'  /home/ian/miniconda3/conda-meta/*.json | xargs rm -f
```

**Closed by nehaljwani** 2017-10-09 18:01 UTC
