### ISSUE TITLE
option to check integrity of a conda environment

### ISSUE THREAD

**Issue by csoja** [conda/conda#4208] opened 2017-01-06 19:32 UTC
add an option/tool to conda that will check the integrity/health of a conda environment

**Comment by groutr** [comment] 2017-01-06 20:25
A few possible sanity checks:
1. Are the packages satisifed (according to the solver).  IIRC, this happens anytime there are package changes in an environment.
2. Are all the files present in the environment? This would verify that all files that are claimed to be in the environment, are actually present.  Mapping os.path.exists on the files list in the conda-meta json files accomplishes this.  Are files that are supposed to be hardlinked/symlinked actually hardlinks/symlinks?
3. Check file permissions.

What other checks would determine the health of an environment?

**Comment by kalefranz** [comment] 2018-02-24 00:30
Duplicate of https://github.com/conda/conda/issues/474

**Closed by kalefranz** 2018-02-24 00:30 UTC
Labels: source:cio, type:feature
