### ISSUE TITLE
conda list error in other activated env 

### ISSUE THREAD

**Issue by kkkdesu** [conda/conda#10791] opened 2021-07-15 05:41 UTC
Hello!
       I'm using conda 4.10.3 on CentOS8. When I used conda list in the base environment, it seemed to be normal. While I changed environment into another env named rnaseq, conda list gave me an error report below. But it worked before and I did not changed the rnaseq env recently.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/cli/main_list.py", line 140, in execute
        exitcode = print_packages(prefix, regex, format, piplist=args.pip,
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/cli/main_list.py", line 79, in print_packages
        exitcode, output = list_packages(prefix, regex, format=format,
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/cli/main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 140, in iter_records
        return itervalues(self._prefix_records)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 169, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 79, in load
        self._load_site_packages()
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 284, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/gateways/disk/read.py", line 240, in read_python_record
        depends, constrains = pydist.get_conda_dependencies()
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 337, in get_conda_dependencies
        depends.update(
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 339, in <genexpr>
        if interpret(pyspec.marker, execution_context)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 1195, in interpret
        return evaluator.evaluate(expr, context)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 1110, in evaluate
        rhs = self.evaluate(erhs, context)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 1109, in evaluate
        lhs = self.evaluate(elhs, context)
      File "/home/software/anaconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 1097, in evaluate
        raise SyntaxError('unknown variable: %s' % expr)
    SyntaxError: unknown variable: python_implementation

`$ /home/software/anaconda3/bin/conda list`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=/home/software/anaconda3/envs/rnaseq:/home/software/anaconda3/envs/rna
                          seq/x86_64-conda-linux-gnu/sysroot/usr
   CONDA_BACKUP_JAVA_HOME=
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=
      CONDA_BUILD_SYSROOT=/home/software/anaconda3/envs/rnaseq/x86_64-conda-linux-gnu/sysroot
        CONDA_DEFAULT_ENV=rnaseq
                CONDA_EXE=/home/software/anaconda3/bin/conda
             CONDA_PREFIX=/home/software/anaconda3/envs/rnaseq
           CONDA_PREFIX_1=/home/software/anaconda3
           CONDA_PREFIX_2=/home/software/anaconda3/envs/test
    CONDA_PROMPT_MODIFIER=(rnaseq)
         CONDA_PYTHON_EXE=/home/software/anaconda3/bin/python
               CONDA_ROOT=/home/software/anaconda3
              CONDA_SHLVL=3
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/home/software/anaconda3/envs/rnaseq/jre/lib/amd64/server
                     PATH=/home/software/anaconda3/bin:/home/software/anaconda3/envs/rnaseq/bin:
                          /home/software/anaconda3/condabin:/home/rnaseq/.local/bin:/home/rnaseq
                          /bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/software/
                          RSEM-1.3.3:/home/software/subread-2.0.2/bin:/home/software/preseq-3.1.
                          2/bin:/home/software/TrimGalore-0.6.6
               PYTHONPATH=:/home/software/kobas-3.0/src
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : rnaseq
    active env location : /home/software/anaconda3/envs/rnaseq
            shell level : 3
       user config file : /home/rnaseq/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.10.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/software/anaconda3  (writable)
      conda av data dir : /home/software/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/software/anaconda3/pkgs
                          /home/rnaseq/.conda/pkgs
       envs directories : /home/software/anaconda3/envs
                          /home/rnaseq/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.10 Linux/4.18.0-240.el8.x86_64 centos/8.4.2105 glibc/2.28
                UID:GID : 1001:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:

If I created a new environment, conda list gave proper blank result in it for I did not install anything.
I'm wondering if I made mistakes for something recently.
Thank you for your applies!

**Comment by jezdez** [comment] 2021-09-17 17:15
Duplicate of #10768

**Closed by jezdez** 2021-09-17 17:15 UTC
