### ISSUE TITLE
Error report installing libraries

### ISSUE THREAD

**Issue by OnlyHigh** [conda/conda#7907] opened 2018-10-24 23:01 UTC
Hi

I runned this command line in this command line, it worked. 
```
conda install -c conda-forge bcolz tensorflow matplotlib keras keras-applications
```

When I runned this commmand line:
```
conda install -c anaconda bcolz numpy pandas seaborn

```
it crashed hardcore, and even now I can't install anything, 

```
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 246, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/bio/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /home/bio/anaconda3/bin/conda install -c anaconda bcolz numpy pandas seaborn`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/bio/anaconda3
                     PATH=/home/bio/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/
                          bin:/sbin:/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             SUDO_COMMAND=/bin/bash
                 SUDO_GID=1000
                 SUDO_UID=1000
                SUDO_USER=bio

     active environment : None
       user config file : /home/bio/.condarc
 populated config files : /home/bio/.condarc
          conda version : 4.5.11
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/bio/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /home/bio/anaconda3/pkgs
                          /home/bio/.conda/pkgs
       envs directories : /home/bio/anaconda3/envs
                          /home/bio/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.15.0-36-generic ubuntu/18.04 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
Can anyone tell me what's happening and how can I fix it?
Thanks in advance, 
Luis Alfonso.

**Comment by nehaljwani** [comment] 2018-10-25 05:17
@OnlyHigh Try removing `-c anaconda` in the second command.

**Comment by msarahan** [comment] 2018-10-26 12:58
duplicate of #7870, closing

**Closed by msarahan** 2018-10-26 12:58 UTC
