### ISSUE TITLE
problem installing 'anaconda' and 'gdal'

### ISSUE THREAD

**Issue by flamingbear** [conda/conda#1915] opened 2015-12-17 18:07 UTC
So I was just helped with my netcdf4 problem, maybe you can help me again. 

Starting on a fresh vm of ubuntu 14.04 and installing miniconda2.  if I try to `conda install -n root 'anaconda' 'gdal'` I get a non-functional gdal. 

```
   11  python
   12  wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
   13  bash Miniconda-latest-Linux-x86_64.sh
   14  . bashrc
   15  . .bashrc
   16  which python
   17  python --version
   18  python -c "import osgeo"
   19  conda install -n root 'anaconda' 'gdal'
   20  python -c "import osgeo"
```

This is the result after command #19

```
vagrant@vyak:~$ python -c "import osgeo"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libgdal.so.20: cannot open shared object file: No such file or directory
```

if i do a `conda install gdal`  It says there are lots of specs to change:

```
vagrant@vyak:~$ conda install gdal
Fetching package metadata: ....
Solving package specifications: ...................
Package plan for installation in environment /home/vagrant/miniconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geos-3.4.2                 |                0        15.4 MB
    krb5-1.13.2                |                0         3.5 MB
    openssl-1.0.1k             |                1         2.6 MB
    proj4-4.9.1                |                0         517 KB
    xerces-c-3.1.2             |                0         7.5 MB
    curl-7.43.0                |                1         550 KB
    hdf4-4.2.11                |                0         3.3 MB
    python-2.7.10              |                1        12.0 MB
    kealib-1.4.5               |                0         204 KB
    libnetcdf-4.3.3.1          |                1         900 KB
    numpy-1.10.2               |           py27_0         5.9 MB
    requests-2.9.0             |           py27_0         604 KB
    setuptools-18.8.1          |           py27_0         345 KB
    libgdal-2.0.0              |                2        47.0 MB
    ------------------------------------------------------------
                                           Total:       100.3 MB

The following NEW packages will be INSTALLED:

    geos:       3.4.2-0
    hdf4:       4.2.11-0
    kealib:     1.4.5-0
    krb5:       1.13.2-0
    libnetcdf:  4.3.3.1-1
    proj4:      4.9.1-0
    xerces-c:   3.1.2-0

The following packages will be UPDATED:

    libgdal:    1.11.2-0      --> 2.0.0-2
    numpy:      1.10.1-py27_0 --> 1.10.2-py27_0
    requests:   2.8.1-py27_0  --> 2.9.0-py27_0
    setuptools: 18.5-py27_0   --> 18.8.1-py27_0

The following packages will be DOWNGRADED:

    curl:       7.45.0-0      --> 7.43.0-1
    openssl:    1.0.2d-0      --> 1.0.1k-1
    python:     2.7.11-0      --> 2.7.10-1
```

And proceeding, it installs a number of packages.

and `python -c "import osgeo"` now works without issues.

As a note:

Installing them sequentially seems to work without issue.

```
conda install -n root 'anaconda'
conda install -n root 'gdal'
"python -c "import osgeo"
```

My machines are generally being created via puppet, and the module we use doesn't allow for sequential installs.  It just gathers the packages into a list and does a 
`conda install -n root 'package1' 'package2' ....`

So maybe you can tell me what I'm doing wrong again.  

Thanks
Matt

**Comment by groutr** [comment] 2015-12-17 19:10
Ok.  This might be a little more subtle.  One thing to be aware of is that the anaconda package forces very specific versions of packages to be installed.  I would not recommend installing anaconda in combination with any other packages.

**Comment by flamingbear** [comment] 2015-12-17 19:16
My suggested workaround was to find out what exactly was being used in anaconda and just install those things along with gdal.

**Comment by groutr** [comment] 2015-12-17 19:34
That would likely be closer to what you want.

**Comment by godber** [comment] 2016-02-05 12:17
@groutr can I read your following statement:

"Ok. This might be a little more subtle. One thing to be aware of is that the anaconda package forces very specific versions of packages to be installed. I would not recommend installing combinations of packages that include the anaconda package."

As: "Do not add additional packages to an environment that includes the anaconda package"?

**Comment by piprrr** [comment] 2016-02-08 18:22
I'm getting the same error:

`$ python -c 'import gdal'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/may/anaconda2/envs/gdal/lib/python2.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/may/anaconda2/envs/gdal/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/may/anaconda2/envs/gdal/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libgdal.so.20: cannot open shared object file: No such file or directory`

I've even gone so far as to create a "gdal specific" environment to no avail.  And I'll be damned if I can find what is trying to load `libgdal.so.20` since, as far as I can tell, that dynamic library does not exist anywhere on my system.

**Comment by piprrr** [comment] 2016-02-08 18:49
And here's a potential clue as to why this might be happening:

` conda search gdal
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
gdal                         1.10.1                   py33_0  defaults        
                             1.10.1                   py27_0  defaults        
                             1.10.1                   py26_0  defaults        
                             1.10.1               np18py34_2  defaults        
                             1.10.1               np18py33_2  defaults        
                             1.10.1               np18py27_2  defaults        
                             1.10.1               np18py26_2  defaults        
                             1.11.0               np19py34_0  defaults        
                             1.11.0               np19py33_0  defaults        
                             1.11.0               np19py27_0  defaults        
                             1.11.0               np19py26_0  defaults        
                             1.11.1               np19py34_0  defaults        
                             1.11.1               np19py33_0  defaults        
                             1.11.1               np19py27_0  defaults        
                             1.11.1               np19py26_0  defaults        
                             1.11.1               np19py34_1  defaults        
                             1.11.1               np19py33_1  defaults        
                             1.11.1               np19py27_1  defaults        
                             1.11.1               np19py26_1  defaults        
                             1.11.2               np19py34_0  defaults        
                             1.11.2               np19py33_0  defaults        
                             1.11.2               np19py27_0  defaults        
                             1.11.2               np19py26_0  defaults        
                             1.11.2               np19py34_1  defaults        
                             1.11.2               np19py33_1  defaults        
                             1.11.2               np19py27_1  defaults        
                             1.11.2               np19py26_1  defaults        
                             1.11.2               np19py34_2  defaults        
                             1.11.2               np19py33_2  defaults        
                             1.11.2               np19py27_2  defaults        
                             1.11.2               np19py26_2  defaults        
                             1.11.2               np19py34_3  defaults        
                             1.11.2               np19py33_3  defaults        
                             1.11.2               np19py27_3  defaults        
                             1.11.2               np19py26_3  defaults        
                             2.0.0                np19py35_0  defaults        
                             2.0.0                np19py34_0  defaults        
                             2.0.0                np19py33_0  defaults        
                             2.0.0                np19py27_0  defaults        
                             2.0.0                np19py26_0  defaults        
                             2.0.0               np110py35_0  defaults        
                             2.0.0               np110py34_0  defaults        
                             2.0.0               np110py27_0  defaults        
                             2.0.0                    py35_1  defaults        
                             2.0.0                    py34_1  defaults        
                          *  2.0.0                    py27_1  defaults        
libgdal                   *  1.11.2                        0  defaults        
                             1.11.2                        1  defaults        
                             1.11.2                        2  defaults        
                             2.0.0                         0  defaults        
                             2.0.0                         1  defaults        
                             2.0.0                         2  defaults `

Note that the `gdal` uses 2.0.0 by default, whereas libgdal refers to 1.112.  gdal underwent a significant API change from 1.x to 2.x that is *not* backwardly compatible.

I'll see if I can bend conda to install an older version of gdal to match the library version.

**Comment by piprrr** [comment] 2016-02-08 19:04
I resolved the problem by manually downgrading gdal to match the corresponding libgdal:

```
$ conda install -n gdal gdal=1.10.1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ................
Package plan for installation in environment /home/may/anaconda2/envs/gdal:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.8.2                |           py27_1         7.9 MB
    gdal-1.10.1                |       np18py27_2        33.8 MB
    ------------------------------------------------------------
                                           Total:        41.6 MB

The following NEW packages will be INSTALLED:

    libgfortran: 1.0-0            

The following packages will be DOWNGRADED:

    gdal:        2.0.0-py27_1  --> 1.10.1-np18py27_2
    numpy:       1.10.4-py27_0 --> 1.8.2-py27_1     

Proceed ([y]/n)? 

Fetching packages ...
numpy-1.8.2-py 100% |####################################################################################| Time: 0:00:01   4.27 MB/s
gdal-1.10.1-np 100% |####################################################################################| Time: 0:00:04   8.03 MB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
```

And now to test out the fix:
```
(gdal)[may@gist-smapper2 ~]$ python -c 'import gdal'
```

No whining, so import worked.

Therefore the fix for this is for whomever manages the official package default to ensure that the gdal and libgdal are both 2.x or 1.x -- *never* mix the two!

**Comment by piprrr** [comment] 2016-02-08 20:25
Addendum:

`python3` does *not* support `gdal` 1.x; you *must* use 2.0. The following will get `libgdal` in sync with the default version of `gdal`:

`conda install -n gdal3 libgdal=2.0.0`

So, again __you must ensure that `gdal` and `libgdal` are both either 1.x or 2.x__ or you will get the aforementioned error.

**Comment by michaelaye** [comment] 2016-03-08 00:56
I have 2.0 version on both and it still fails:
```bash
$ python -c 'import gdal'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/klay6683/miniconda3/envs/py35/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/klay6683/miniconda3/envs/py35/lib/python3.5/site-packages/osgeo/_gdal.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/./libgssapi_krb5.2.2.dylib
  Referenced from: /Users/klay6683/miniconda3/envs/py35/lib/libgdal.20.dylib
  Reason: image not found
```

The library file is definitely there:
```bash
$ ls -la /Users/klay6683/miniconda3/envs/py35/lib/libgdal.20.dylib
-rwxrwxr-x  3 klay6683  LASP\Domain Users    25M Jul 23  2015 /Users/klay6683/miniconda3/envs/py35/lib/libgdal.20.dylib
(py35)
```

**Comment by michaelaye** [comment] 2016-03-17 19:18
My problem above was caused by a broken and unrequired dependency to krb5 (it works fine on Py2 without it). So I installed krb5 and then things work. Here https://goo.gl/QKh01l this solution was described first. Also, apparently linux already has the updates, but OSX is still missing updated packages for it. :(

**Comment by neothemachine** [comment] 2016-06-09 09:31
I have the same problem with gdal 2 on Windows 64 bit:
```sh
$ conda create --name test gdal

Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment C:\Users\...

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.3                 |                1       110.0 MB
    vs2010_runtime-10.00.40219.1|                1         1.2 MB
    geos-3.4.2                 |           vc10_0         3.6 MB
    jpeg-8d                    |           vc10_0         177 KB
    proj4-4.9.1                |           vc10_0         499 KB
    python-3.4.4               |                4        31.7 MB
    xerces-c-3.1.2             |           vc10_0         1.3 MB
    zlib-1.2.8                 |           vc10_3         108 KB
    curl-7.49.0                |           vc10_0         300 KB
    hdf4-4.2.11                |                0         534 KB
    hdf5-1.8.16                |           vc10_0        11.7 MB
    numpy-1.11.0               |           py34_1         2.7 MB
    setuptools-22.0.5          |           py34_0         769 KB
    wheel-0.29.0               |           py34_0         123 KB
    kealib-1.4.5               |           vc10_0         172 KB
    libnetcdf-4.3.3.1          |           vc10_4         425 KB
    pip-8.1.2                  |           py34_0         1.6 MB
    libgdal-2.0.0              |           vc10_1         5.1 MB
    gdal-2.0.0                 |           py34_1         478 KB
    ------------------------------------------------------------
                                           Total:       172.6 MB
```
On import I get `ImportError: DLL load failed`.

Installing gdal==1.11.2 instead works as expected (it also installs libgdal 1.11.2 along with it).

**Comment by davidh-ssec** [comment] 2016-08-18 02:54
I've had this same problem and was solving it by manually installing `krb5`, but have now run in to it again (after not using anaconda for a while). My project requires gdal 1.11.2, but I think that might have only been limited because of this bug which I now experience on OSX even with gdal 1.11.2. I see this issue has had no traffic for a long time even though this seems like a simple fix, right?

Would this be a better issue/PR for the anaconda repos (https://github.com/ContinuumIO/anaconda-recipes)?

**Comment by ilanschnell** [comment] 2016-08-18 15:44
Hi @davidh-ssec, we just updated gdal to 2.1.0.  Is it possible for you to switch to this version?

**Comment by davidh-ssec** [comment] 2016-08-18 16:03
@ilanschnell I just tried updating to 2.1.0 on my mac (after uninstalling krb5) and got the following error:
```
  File "/Users/davidh/repos/git/CSPOV/py/cspov/model/shapes.py", line 31, in <module>
    from rasterio.features import rasterize
  File "/Users/davidh/anaconda/envs/cspov/lib/python3.4/site-packages/rasterio/__init__.py", line 8, in <module>
    from rasterio._base import eval_window, window_shape, window_index
ImportError: dlopen(/Users/davidh/anaconda/envs/cspov/lib/python3.4/site-packages/rasterio/_base.so, 2): Library not loaded: @loader_path/../../../libgdal.1.dylib
  Referenced from: /Users/davidh/anaconda/envs/cspov/lib/python3.4/site-packages/rasterio/_base.so
  Reason: image not found
```

However, I then updated rasterio and now it seems to work. I'll have to test on my Windows VM still, but this looks good.

**Comment by davidh-ssec** [comment] 2016-08-19 01:07
@ilanschnell I tried updating gdal on my Windows VM and it fails. My application and `import gdal` work when `gdal=1.11.4` (newest version I see) and `libgdal=1.11.2`. If I do `conda update gdal` it only suggest updating `libgdal` to `2.1.0` which then causes a DLL load fail. Here is what works:

```
(sift_dev) C:\Users\User>conda list gdal
# packages in environment at C:\Anaconda3\envs\sift_dev:
#
gdal                      1.11.4          np110py34_vc10_7  [vc10]  ioos
libgdal                   1.11.2                        2
```

Here is what fails:
```
(sift_dev) C:\Users\User>conda update gdal
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda3\envs\sift_dev:

The following packages will be UPDATED:

    libgdal: 1.11.2-2 --> 2.1.0-vc10_0 [vc10]

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

(sift_dev) C:\Users\User>conda list gdal
# packages in environment at C:\Anaconda3\envs\sift_dev:
#
gdal                      1.11.4          np110py34_vc10_7  [vc10]  ioos
libgdal                   2.1.0                    vc10_0  [vc10]

(sift_dev) C:\Users\User>python -c "import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\sift_dev\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\Anaconda3\envs\sift_dev\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Anaconda3\envs\sift_dev\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "C:\Anaconda3\envs\sift_dev\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by Tobin9130** [comment] 2017-03-23 16:32
Famingbear, 'python -c "import osgeo"' has saved me. I am an newb and couldn't figure out for the life of me what was going on for two weeks. 

Thank you!

**Comment by kalefranz** [comment] 2017-05-06 04:02
This issue was moved to ContinuumIO/anaconda-issues#1687

**Closed by kalefranz** 2017-05-06 04:02 UTC
