### ISSUE TITLE
Unable to remove Conda Environment

### ISSUE THREAD

**Issue by wpm** [conda/conda#2698] opened 2016-06-15 23:05 UTC
The tensorflow Conda environment exists. It was created with the command `conda create -n tensorflow python=3.5`. I cannot remove it.

```
> conda env remove --name tensorflow
Fetching package metadata .......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "//anaconda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "//anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: 'module' object has no attribute 'PREFIX'
williammcneill:~/Documents/DeepLearning/scratch
> conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.0
  conda-build version : 1.18.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by mjuric** [comment] 2016-06-16 01:08
I'm seeing the same problem (also osx-64).

**Comment by kalefranz** [comment] 2016-06-16 02:08
Duplicate of #2679. Until the conda-env source is patched, which unfortunately lives in a different repo, you can use the conda code directly to remove the environment.  The equivalent command is

    conda remove -n ENVIRONMENT_NAME --all

**Closed by kalefranz** 2016-06-16 02:08 UTC

**Comment by soerendip** [comment] 2019-02-01 23:32
Access is denied also with that code.
