### ISSUE TITLE
Posting error message - "conda update conda" Fails

### ISSUE THREAD

**Issue by bn-sandbox** [conda/conda#4003] opened 2016-12-05 02:28 UTC
Below is the error message I received when I tried to update - for context, I had just previously removed the launcher in response to suggestions from this board.  New to Python but not to programming - though I'm pretty rusty - but can't figure out the error from the text returned.

Any help would be much appreciated.  Thx.

bnm1:anaconda bn$ conda update conda
Fetching package metadata ...**An unexpected error has occurred**.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.11.0
         python version : 3.4.5.final.0
       requests version : 2.12.1
       root environment : /Users/bn/anaconda  (writable)
    default environment : /Users/bn/anaconda
       envs directories : /Users/bn/anaconda/envs
          package cache : /Users/bn/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/bn/.condarc
           offline mode : False

`$ /Users/bn/anaconda/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/bn/anaconda/lib/python3.4/concurrent/futures/_base.py", line 402, in result
        return self.__get_result()
      File "/Users/bn/anaconda/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
        raise self._exception
      File "/Users/bn/anaconda/lib/python3.4/concurrent/futures/thread.py", line 54, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/bn/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by senis000** [comment] 2016-12-06 18:33
Same attributeError here:

$ conda update anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.1
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : C:\Python\Anaconda  (writable)
    default environment : C:\Python\Anaconda
       envs directories : C:\Python\Anaconda\envs
          package cache : C:\Python\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False



`$ C:\Python\Anaconda\Scripts\conda-script.py update anaconda`




    Traceback (most recent call last):
      File "C:\Python\Anaconda\lib\site-packages\conda\exceptions.py", line 479,
 in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Python\Anaconda\lib\site-packages\conda\cli\main.py", line 145, i
n _main
        exit_code = args.func(args, p)
      File "C:\Python\Anaconda\lib\site-packages\conda\cli\main_update.py", line
 65, in execute
        install(args, parser, 'update')
      File "C:\Python\Anaconda\lib\site-packages\conda\cli\install.py", line 238
, in install
        prefix=prefix)
      File "C:\Python\Anaconda\lib\site-packages\conda\api.py", line 24, in get_
index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Python\Anaconda\lib\site-packages\conda\fetch.py", line 300, in f
etch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Python\Anaconda\lib\site-packages\conda\fetch.py", line 300, in <
listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Python\Anaconda\lib\concurrent\futures\_base.py", line 405, in re
sult
        return self.__get_result()
      File "C:\Python\Anaconda\lib\concurrent\futures\_base.py", line 357, in __
get_result
        raise self._exception
      File "C:\Python\Anaconda\lib\concurrent\futures\thread.py", line 55, in ru
n
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Python\Anaconda\lib\site-packages\conda\fetch.py", line 75, in fu
nc
        res = f(*args, **kwargs)
      File "C:\Python\Anaconda\lib\site-packages\conda\fetch.py", line 117, in f
etch_repodata
        timeout=(6.1, 60))
      File "C:\Python\Anaconda\lib\site-packages\requests\sessions.py", line 501
, in get
        return self.request('GET', url, **kwargs)
      File "C:\Python\Anaconda\lib\site-packages\requests\sessions.py", line 488
, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Python\Anaconda\lib\site-packages\requests\sessions.py", line 609
, in send
        r = adapter.send(request, **kwargs)
      File "C:\Python\Anaconda\lib\site-packages\requests\adapters.py", line 423
, in send
        timeout=timeout
      File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\conne
ctionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\conne
ctionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\conne
ctionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\conne
ction.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\contr
ib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\contr
ib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_clas
s'

**Comment by dwaynepaschall** [comment] 2016-12-30 04:30
I have the same error on a Win10 box. Similar to here, I uninstalled python 3.5 and installed a new python 3.4 with a previous Anaconda x86_64 installer. (short version: I only want to install/run py34, not multiple versions and have to change the default environment, etc. I have some critical packages that don't yet d/l with py35). The same error as posted above emerges after I: 1) install py34 using the last Anaconda installer that used 3.4; 2) run the update command: conda update conda which installed some new packages and updates some others. 

Any insight would be helpful. As it stands, I cant intall that critical library, as well as some other common packages like ggplot.

**Comment by roshni-b** [comment] 2017-03-04 05:54
Same problem here:
**conda update anaconda**

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Users\Roshni\Anaconda3  (writable)
    default environment : C:\Users\Roshni\Anaconda3
       envs directories : C:\Users\Roshni\Anaconda3\envs
                          C:\Users\Roshni\AppData\Local\conda\conda\envs
                          C:\Users\Roshni\.conda\envs
          package cache : C:\Users\Roshni\Anaconda3\pkgs
                          C:\Users\Roshni\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.14393



`$ C:\Users\Roshni\Anaconda3\Scripts\conda-script.py update anaconda`




    Traceback (most recent call last):
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\core\link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\core\link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Roshni\\Anaconda3\\pkgs\\notebook-4.3.1-py35_1\\info\\index.json'

**Comment by kalefranz** [comment] 2017-05-01 19:55
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:55 UTC
