### ISSUE TITLE
conda env create and conda create are not the same

### ISSUE THREAD

**Issue by mousey92** [conda/conda#14110] opened 2024-08-01 13:42 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

There is quite a difference between how **conda create** and **conda env create** should be used, even though both are used to create a new environment.

For example, conda env create can use options **-f** and **--file** to refer to a definition file, but conda create can only use --file, using -f throws an error.

It would make more sense if both commands had the same functionality/were an alias of each other

### Conda Info

```shell
active environment : base
    active env location : C:\Users\Matthijs.Kramer\mambaforge
            shell level : 1
       user config file : C:\Users\Matthijs.Kramer\.condarc
 populated config files : C:\Users\Matthijs.Kramer\mambaforge\.condarc
                          C:\Users\Matthijs.Kramer\.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.5.0=0
                          __win=0=0
       base environment : C:\Users\Matthijs.Kramer\mambaforge  (writable)
      conda av data dir : C:\Users\Matthijs.Kramer\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Matthijs.Kramer\mambaforge\pkgs
                          C:\Users\Matthijs.Kramer\.conda\pkgs
                          C:\Users\Matthijs.Kramer\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Matthijs.Kramer\mambaforge\envs
                          C:\Users\Matthijs.Kramer\.conda\envs
                          C:\Users\Matthijs.Kramer\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.12.4 Windows/11 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\Matthijs.Kramer\mambaforge\.condarc <==
channels:
  - conda-forge

==> C:\Users\Matthijs.Kramer\.condarc <==
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
# packages in environment at C:\Users\Matthijs.Kramer\mambaforge:
#
# Name                    Version                   Build  Channel
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.16               hec1de76_6    conda-forge
aws-c-cal                 0.6.10               hd481e46_1    conda-forge
aws-c-common              0.9.13               hcfcfb64_0    conda-forge
aws-c-compression         0.2.18               hd481e46_1    conda-forge
aws-c-event-stream        0.4.2                h0f06f08_4    conda-forge
aws-c-http                0.8.1                hdb5aac5_5    conda-forge
aws-c-io                  0.14.5               h08270f9_1    conda-forge
aws-c-mqtt                0.10.2               hfea8755_4    conda-forge
aws-c-s3                  0.5.2                h4b2095a_0    conda-forge
aws-c-sdkutils            0.1.15               hd481e46_1    conda-forge
aws-checksums             0.1.18               hd481e46_1    conda-forge
aws-crt-cpp               0.26.2               h8492d2a_7    conda-forge
aws-sdk-cpp               1.11.267             h93f5800_1    conda-forge
azure-core-cpp            1.10.3               h249a519_1    conda-forge
azure-storage-blobs-cpp   12.10.0              h91493d7_0    conda-forge
azure-storage-common-cpp  12.5.0               h91493d7_2    conda-forge
blosc                     1.21.6               h85f69ea_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py312h53d5487_1    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-ares                    1.27.0               hcfcfb64_0    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cairo                     1.18.0               h91e5215_2    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312he70551f_0    conda-forge
cfitsio                   4.4.0                h9b0cee5_1    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     24.5.0          py312h2e8e312_0    conda-forge
conda-libmamba-solver     24.7.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.7          py312he4c2ea2_1    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
fiona                     1.9.6           py312h95cbb4d_0    conda-forge
fmt                       10.2.1               h181d51b_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
frozendict                2.4.4           py312h4389bb4_0    conda-forge
gdal                      3.8.4           py312h36e25a9_3    conda-forge
geos                      3.12.1               h1537add_0    conda-forge
geotiff                   1.7.1               hbf5ca3a_15    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.80.2               h0df6a38_0    conda-forge
glib-tools                2.80.2               h2f9d560_0    conda-forge
gst-plugins-base          1.22.7               h001b923_0    conda-forge
gstreamer                 1.22.7               hb4038d2_0    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.3          nompi_h2b43c12_105    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
intel-openmp              2024.0.0         h57928b3_49841    conda-forge
jigsawpy                  1.0.0                    pypi_0    pypi
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
kealib                    1.5.3                hd248416_0    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20230802.1      cxx17_h63175ca_0    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libarchive                3.7.4                haf234dc_0    conda-forge
libblas                   3.9.0              21_win64_mkl    conda-forge
libboost-headers          1.84.0               h57928b3_1    conda-forge
libcblas                  3.9.0              21_win64_mkl    conda-forge
libclang                  15.0.7          default_h3a3e6c3_5    conda-forge
libclang13                15.0.7          default_hf64faad_5    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.8.0                hd5e4a3a_0    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.8.4                h8e1932a_3    conda-forge
libglib                   2.80.2               h0df6a38_0    conda-forge
libgoogle-cloud           2.21.0               h7ece6b4_1    conda-forge
libgoogle-cloud-storage   2.21.0               hb581fae_1    conda-forge
libgrpc                   1.60.1               h0bf0bfa_0    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libintl-devel             0.22.5               h5728263_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             h538826c_1020    conda-forge
liblapack                 3.9.0              21_win64_mkl    conda-forge
libmamba                  1.5.8                h3f09ed1_0    conda-forge
libmambapy                1.5.8           py312h66cf91f_0    conda-forge
libnetcdf                 4.9.2           nompi_h92078aa_114    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libpq                     16.2                 hdb24f17_0    conda-forge
libprotobuf               4.25.1               hb8276f3_2    conda-forge
libre2-11                 2023.09.01           h8c5ae5e_1    conda-forge
librttopo                 1.1.0               h94c4f80_15    conda-forge
libsolv                   0.7.30               hbb528cf_0    conda-forge
libspatialite             5.1.0                hf2f0abc_4    conda-forge
libsqlite                 3.46.0               h2466b09_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
lxml                      5.2.2           py312h56c7e3b_0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
mamba                     1.5.8           py312h5494d5c_0    conda-forge
menuinst                  2.1.1           py312h275cf98_0    conda-forge
miniforge_console_shortcut 1.0                  h57928b3_0    conda-forge
minizip                   4.0.6                hb638d1e_0    conda-forge
mkl                       2024.0.0         h66d3029_49657    conda-forge
munch                     4.0.0              pyhd8ed1ab_0    conda-forge
mypy                      1.10.1          py312h4389bb4_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
numpy                     1.26.4          py312h8753938_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openpyxl                  3.1.4           py312he70551f_0    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h72972c8_1    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pipreqs                   0.4.13             pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   24.03.0              hc2f3c52_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.2                 h1beaf6b_0    conda-forge
proj                      9.3.1                he13c7e8_0    conda-forge
psutil                    6.0.0           py312h4389bb4_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py312he70551f_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyogrio                   0.7.2           py312he3b4e22_1    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyqt                      5.15.9          py312he09f080_5    conda-forge
pyqt5-sip                 12.12.2         py312h53d5487_5    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.12.4          h889d299_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qt                        5.15.8               h91493d7_0    conda-forge
qt-main                   5.15.8              h9e85ed6_17    conda-forge
qt-webengine              5.15.8               h4bf5c4e_4    conda-forge
re2                       2023.09.01           hd3b24a8_1    conda-forge
reproc                    14.2.4               hcfcfb64_0    conda-forge
reproc-cpp                14.2.4               h63175ca_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.6          py312he70551f_0    conda-forge
ruamel.yaml.clib          0.2.8           py312he70551f_0    conda-forge
scipy                     1.14.0                   pypi_0    pypi
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.4           py312h91267bd_1    conda-forge
sip                       6.7.12          py312h53d5487_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                h23299a8_0    conda-forge
sqlite                    3.46.0               h2466b09_0    conda-forge
tbb                       2021.11.0            h91493d7_1    conda-forge
tiledb                    2.20.1               hde99414_1    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
uriparser                 0.9.8                h5a68840_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xerces-c                  3.2.5                h63175ca_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml-cpp                  0.8.0                h63175ca_0    conda-forge
yarg                      0.1.9                      py_1    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h2466b09_1    conda-forge
zstandard                 0.23.0          py312h7606c53_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

**Comment by kenodegard** [comment] 2024-08-01 15:02
Duplicate of https://github.com/conda/conda/issues/13015

**Closed by kenodegard** 2024-08-01 15:02 UTC
Labels: type::feature, source::community, duplicate
