### ISSUE TITLE
conda-canary ignores CIO_TEST

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#3382] opened 2016-09-06 01:46 UTC
Using the current `4.2.x` branch, it seems like the `CIO_TEST` environment variable is being ignored.  Also `conda info` still displays `channel URLs : defaults` (instead of the actual URLs).

**Comment by kalefranz** [comment] 2016-09-06 23:54
duplicate of #3203

**Closed by kalefranz** 2016-09-06 23:54 UTC
