### ISSUE TITLE
conda broken after installing XQuartz mistakenly and again uninstalled.

### ISSUE THREAD

**Issue by vikrantsanghvi** [conda/conda#3599] opened 2016-10-10 08:00 UTC
<img width="1014" alt="screen shot 2016-10-10 at 3 56 06 am" src="https://cloud.githubusercontent.com/assets/7551589/19229701/867c0124-8e9d-11e6-9a56-a6d8e8e49b9f.png">

So i was working on igraph library which asked me to install Cairo for plotting and somehow i landed up in getting pop up tp install XQuartz. I somehow uninstalled it but anaconda still not working. On giving any command of conda it gives this error.
I really need to get this run as soon as possible as its very critical to me.

**Comment by kalefranz** [comment] 2017-05-05 19:02
duplicate of #3621

**Closed by kalefranz** 2017-05-05 19:02 UTC
