### ISSUE TITLE
Error while executing update command "conda update --all" after the most recent update

### ISSUE THREAD

**Issue by raghavmenon** [conda/conda#6125] opened 2017-10-09 16:02 UTC
I had updated using 'conda update --all' this morning and since then none of the conda commands are working (conda list, conda install <pkg>, conda update --all etc). I am receiving the following error. Would be grateful if a solution is provided to get around this problem. Would I have to delete the anaconda folder and reinstall everything from scratch along with all the python packages? Thanks in advance!!

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 3.5.4.final.0
       requests version : 2.18.4
       root environment : /home/raghav/anaconda3  (writable)
    default environment : /home/raghav/anaconda3
       envs directories : /home/raghav/anaconda3/envs
                          /home/raghav/.conda/envs
          package cache : /home/raghav/anaconda3/pkgs
                          /home/raghav/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.5.4 Linux/4.4.0-97-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/raghav/anaconda3/bin/conda update --all`

    Traceback (most recent call last):
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/raghav/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080093.174 for timestamp

**Comment by nehaljwani** [comment] 2017-10-09 16:15
Closing as duplicate of https://github.com/conda/conda/issues/6096

Basically, you need to delete the files which have timestamp in decimals. You can try running:
```
grep -l '"timestamp": [0-9]\+\.'  /home/raghav/anaconda3/conda-meta/*.json | xargs rm -f
```

**Closed by nehaljwani** 2017-10-09 16:15 UTC
