### ISSUE TITLE
conda list gave an error

### ISSUE THREAD

**Issue by hjstein** [conda/conda#8223] opened 2019-02-05 16:51 UTC
## Current Behavior
I ran "conda list" and got an error report.

### Steps to Reproduce
```
conda list
```

## Expected Behavior
I thought I'd get a list of packages.  Instead, I got:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 116, in iter_records
        return itervalues(self._prefix_records)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 145, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 69, in load
        self._load_site_packages()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 258, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 245, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 90, in init
        return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 400, in __init__
        super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 104, in __init__
        raise RuntimeError("Path not found: %s" % anchor_full_path)
    RuntimeError: Path not found: C:\ProgramData\Anaconda3\Lib\site-packages\Sphinx-1.5.1-py3.6.egg\EGG-INFO

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py list`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                 HOMEPATH=\
               HTTP_PROXY=<set>
                 INFOPATH=/usr/local/info:/usr/share/info:/usr/info
            ORIGINAL_PATH=/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/S
                          ystem32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygd
                          rive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program
                          Files/nodejs:/cygdrive/c/Users/hstein/.dnx/bin:/cygdrive/c/Program
                          Files/Microsoft DNX/Dnvm:/cygdrive/c/Program Files/Microsoft SQL
                          Server/120/Tools/Binn:/cygdrive/c/Program Files
                          (x86)/Citrix/ICAService:/cygdrive/c/Program Files (x86)/Citrix/System3
                          2:/cygdrive/c/ProgramData/Anaconda3:/cygdrive/c/ProgramData/Anaconda3/
                          Scripts:/cygdrive/c/ProgramData/Anaconda3/Library/bin:/usr/bin:/usr/bi
                          n:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance
                          Toolkit:/cygdrive/c/Program
                          Files/MATLAB/R2017a/bin:/cygdrive/c/Program Files (x86)/Pandoc:/cygdri
                          ve/c/Users/hstein/AppData/Local/instantclient_12_1:/cygdrive/c/Program
                          Files (x86)/Wolfram
                          Research/WolframScript:/cygdrive/c/blp/DAPI:/cygdrive/c/blp/DAPI/DDE
                     PATH=C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\WINDOWS\system32;C:\WINDO
                          WS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0
                          ;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program
                          Files\nodejs;C:\Users\hstein\.dnx\bin;C:\Program Files\Microsoft
                          DNX\Dnvm;C:\Program Files\Microsoft SQL
                          Server\120\Tools\Binn;C:\Program Files
                          (x86)\Citrix\ICAService;C:\Program Files (x86)\Citrix\System32;C:\Prog
                          ramData\Anaconda3;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anac
                          onda3\Library\bin;C:\cygwin64\bin;C:\cygwin64\bin;C:\Program Files
                          (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program
                          Files\MATLAB\R2017a\bin;C:\Program Files (x86)\Pandoc;C:\Users\hstein\
                          AppData\Local\instantclient_12_1;C:\Program Files (x86)\Wolfram Resear
                          ch\WolframScript;C:\blp\DAPI;C:\blp\DAPI\DDE;C:\cygwin64\lib\lapack;C:
                          \cygwin64\home\hstein\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\cygwin64\home\hstein\.condarc
 populated config files : C:\cygwin64\home\hstein\.condarc
          conda version : 4.6.2
    conda-build version : 3.17.6
         python version : 3.6.7.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\cygwin64\home\hstein\.conda\pkgs
                          C:\Users\hstein\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\cygwin64\home\hstein\.conda\envs
                          C:\Users\hstein\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.6.7 Windows/7 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload did not complete.
Thank you for helping to improve conda.

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> C:\cygwin64\home\hstein\.condarc <==
ssl_verify: False
proxy_servers:
  http: http://proxy.bloomberg.com:81
  https: https://proxy.bloomberg.com:81
```
</p></details>

**Comment by msarahan** [comment] 2019-02-05 17:11
I think this is a duplicate of https://github.com/conda/conda/issues/8185.  It was fixed by https://github.com/conda/conda/pull/8198 which will be present in conda 4.6.3.  That's close to release, and may be out for early release on the conda-canary channel later today.

**Closed** 2019-02-05 17:11 UTC

**Comment by dstanner** [comment] 2019-02-28 22:46
@msarahan I have the same error. I am running conda 4.6.7. Did something change in a subsequent release that caused the error to occur again?

 Here is my error report:

---

(base) C:\Users\datanner>conda list                                                                                                                                                                                                                                                                                                                 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<                                                                                                                                                                                                                                                                                            Traceback (most recent call last):                                                                                                                                          File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 1002, in __call__                                                    return func(*args, **kwargs)                                                                                                                                            File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main                                                           exit_code = do_call(args, p)                                                                                                                                            File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call                                               exit_code = getattr(module, func_name)(args, parser)                                                                                                                    File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute                                                   show_channel_urls=context.show_channel_urls)                                                                                                                            File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages                                             show_channel_urls=show_channel_urls)                                                                                                                                    File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages                                              installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),                                                                                         File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 117, in iter_records                                           return itervalues(self._prefix_records)                                                                                                                                 File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 146, in _prefix_records                                        return self.__prefix_records or self.load() or self.__prefix_records                                                                                                    File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 70, in load                                                    self._load_site_packages()                                                                                                                                              File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 261, in _load_site_packages                                    python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)                                                                                     File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 245, in read_python_record                                   pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)                                                                                              File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 90, in init                                           return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)                                                                                        File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 401, in __init__                                      super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)                                                                                       File "C:\Users\datanner\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 104, in __init__                                      raise RuntimeError("Path not found: %s" % anchor_full_path)                                                                                                           RuntimeError: Path not found: C:\Users\datanner\AppData\Local\Continuum\Anaconda3\Lib\site-packages\Sphinx-1.5.1-py3.6.egg\EGG-INFO                                                                                                                                                                                                             `$ C:\Users\datanner\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py list`                                                                                                                                                                                                                                                                  environment variables:                                                                                                                                                                   CIO_TEST=<not set>                                                                                                                                                       CONDA_BAT=C:\Users\datanner\AppData\Local\Continuum\Anaconda3\condabin\conda.bat                                                                                  CONDA_DEFAULT_ENV=base                                                                                                                                                            CONDA_EXE=C:\Users\datanner\AppData\Local\Continuum\Anaconda3\Scripts\conda.exe                                                                                        CONDA_PREFIX=C:\Users\datanner\AppData\Local\Continuum\Anaconda3                                                                                                 CONDA_PROMPT_MODIFIER=(base)                                                                                                                                                   CONDA_PYTHON_EXE=C:\Users\datanner\AppData\Local\Continuum\Anaconda3\python.exe                                                                                                 CONDA_ROOT=C:\Users\datanner\AppData\Local\Continuum\Anaconda3                                                                                                           CONDA_SHLVL=1                                                                                                                                                               CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0                                                                                                         HOMEPATH=\Users\datanner                                                                                                                                           NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\                                                                                                                      PATH=C:\Users\datanner\AppData\Local\Continuum\Anaconda3\;C:\Users\datanner                                                                                                    \AppData\Local\Continuum\Anaconda3\Library\mingw-w64\bin;C:\Users\data                                                                                                    nner\AppData\Local\Continuum\Anaconda3\Library\usr\bin;C:\Users\datann                                                                                                    er\AppData\Local\Continuum\Anaconda3\Library\bin;C:\Users\datanner\App                                                                                                    Data\Local\Continuum\Anaconda3\Scripts;C:\Users\datanner\AppData\Local                                                                                                    \Continuum\Anaconda3\bin;C:\Users\datanner\AppData\Local\Continuum\Ana                                                                                                    conda3;C:\Users\datanner\AppData\Local\Continuum\Anaconda3\Library\min                                                                                                    gw-w64\bin;C:\Users\datanner\AppData\Local\Continuum\Anaconda3\Library                                                                                                    \usr\bin;C:\Users\datanner\AppData\Local\Continuum\Anaconda3\Library\b                                                                                                    in;C:\Users\datanner\AppData\Local\Continuum\Anaconda3\Scripts;C:\User                                                                                                    s\datanner\AppData\Local\Continuum\Anaconda3\bin;C:\Users\datanner\App                                                                                                    Data\Local\Continuum\Anaconda3\condabin;C:\Users\datanner\AppData\Loca                                                                                                    l\Continuum\Anaconda3\condabin\;C:\ProgramData\Anaconda3;C:\ProgramDat                                                                                                    a\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr                                                                                                    \bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scr                                                                                                    ipts;C:\Program Files\NVIDIA GPU Computing                                                                                                                                Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing                                                                                                              Toolkit\CUDA\v10.0\libnvvp;C:\Program Files\Common Files\Microsoft                                                                                                        Shared\Microsoft Online Services;C:\Program Files (x86)\Common                                                                                                            Files\Microsoft Shared\Microsoft Online Services;C:\windows\system32;C                                                                                                    :\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShe                                                                                                    ll\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL                                                                                                      Server\130\Tools\Binn\;C:\Program Files (x86)\NVIDIA                                                                                                                      Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Users\datanner\Ap                                                                                                    pData\Local\Continuum\anaconda3\;C:\Users\datanner\AppData\Local\Conti                                                                                                    nuum\anaconda3\Scripts\;C:\Program Files (x86)\Microsoft SQL                                                                                                              Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files                                                                                                                   (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files                                                                                                               (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files                                                                                                                 (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program                                                                                                    Files\Git\cmd;C:\Users\datanner\AppData\Local\Continuum\Anaconda3;C:\U                                                                                                    sers\datanner\AppData\Local\Continuum\Anaconda3\Scripts;C:\Users\datan                                                                                                    ner\AppData\Local\Continuum\Anaconda3\Library\bin;C:\Users\datanner\Ap                                                                                                    pData\Local\Microsoft\WindowsApps;C:\Users\datanner\AppData\Local\Prog                                                                                                    rams\Microsoft VS Code\bin;C:\Users\datanner\AppData\Local\atom\bin                                                                                          PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\Windows                                                                                                    PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft Azure                                                                                                            Information Protection\Powershell                                                                                                                        PYTHONIOENCODING=1252                                                                                                                                                   REQUESTS_CA_BUNDLE=<not set>                                                                                                                                                   SSL_CERT_FILE=<not set>                                                                                                                                                                                                                                                                                                                      active environment : base                                                                                                                                                active env location : C:\Users\datanner\AppData\Local\Continuum\Anaconda3                                                                                                         shell level : 1                                                                                                                                                      user config file : C:\Users\datanner\.condarc                                                                                                                       populated config files : C:\Users\datanner\.condarc                                                                                                                                conda version : 4.6.7                                                                                                                                               conda-build version : not installed                                                                                                                                            python version : 3.6.8.final.0                                                                                                                                          base environment : C:\Users\datanner\AppData\Local\Continuum\Anaconda3  (writable)                                                                                            channel URLs : https://repo.anaconda.com/pkgs/main/win-64                                                                                                                                https://repo.anaconda.com/pkgs/main/noarch                                                                                                                                https://repo.anaconda.com/pkgs/free/win-64                                                                                                                                https://repo.anaconda.com/pkgs/free/noarch                                                                                                                                https://repo.anaconda.com/pkgs/r/win-64                                                                                                                                   https://repo.anaconda.com/pkgs/r/noarch                                                                                                                                   https://repo.anaconda.com/pkgs/msys2/win-64                                                                                                                               https://repo.anaconda.com/pkgs/msys2/noarch                                                                                                               package cache : C:\Users\datanner\AppData\Local\Continuum\Anaconda3\pkgs                                                                                                                  C:\Users\datanner\.conda\pkgs                                                                                                                                             C:\Users\datanner\AppData\Local\conda\conda\pkgs                                                                                                       envs directories : C:\Users\datanner\AppData\Local\Continuum\Anaconda3\envs                                                                                                                  C:\Users\datanner\.conda\envs                                                                                                                                             C:\Users\datanner\AppData\Local\conda\conda\envs                                                                                                               platform : win-64                                                                                                                                                       user-agent : conda/4.6.7 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.17763                                                                                   administrator : False                                                                                                                                                        netrc file : None                                                                                                                                                       offline mode : False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               An unexpected error has occurred. Conda has prepared the above report.

**Comment by akapocsi** [comment] 2019-03-12 17:55
> I think this is a duplicate of #8185. It was fixed by #8198 which will be present in conda 4.6.3. That's close to release, and may be out for early release on the conda-canary channel later today.

@msarahan This issue is not fixed. I received the same error with conda 4.6.8.

C:\Users\akapocsi\Desktop>conda list

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1002, in __call__
        return func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 117, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 146, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 70, in load
        self._load_site_packages()
      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 261, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 245, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "C:\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 90, in init
        return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)
      File "C:\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 401, in __init__
        super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)
      File "C:\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 104, in __init__
        raise RuntimeError("Path not found: %s" % anchor_full_path)
    RuntimeError: Path not found: C:\Anaconda3\Lib\site-packages\Sphinx-1.5.1-py3.6.egg\EGG-INFO
```

**Comment by apacifico** [comment] 2019-03-28 20:35
To solve this issue copy the directory 'Sphinx-1.8.5-py3.7.egg-info' or the version you have installed recently and rename it EGG-INFO.  It seems the last install of sphinx broke this directory.
This manipulation has solved the 'conda list' issue I had.

**Comment by SebastianoCurreli** [comment] 2019-04-17 16:53
apacifico answer fixed my issue. 
Conda v4.6.12 py36_0 Windows 10 Pro 64bit

**Comment by JasonMDSI** [comment] 2019-07-22 04:51
> To solve this issue copy the directory 'Sphinx-1.8.5-py3.7.egg-info' or the version you have installed recently in the directory Sphinx-1.5.1-py3.6.egg and rename it EGG-INFO. It seems the last install of sphinx broke this directory.
> This manipulation has solved the 'conda list' issue I had.
Hi, apacifico. Was the 'Sphinx-1.8.5-py3.7.egg-info' you referred to a folder or a file? I can only see in my directory anaconda3\Lib\site-packages\Sphinx-1.6.3-py3.6.egg an EGG-INFO folder (please see attached). and there is no other Sphinx folder like you have (Sphinx-1.8.5-py3.7 and Sphinx-1.5.1-py3.6). Also, what did you mean by copy the directory 'Sphinx-1.8.5-py3.7.egg-info' or the version you have installed recently in the directory Sphinx-1.5.1-py3.6.egg and rename it EGG-INFO"? Thanks
![image](https://user-images.githubusercontent.com/11934573/61606982-20f97c00-ac90-11e9-8e2f-619593241e4b.png)

**Comment by BrenBarn** [comment] 2019-08-10 21:39
In my case the exact EGG-INFO directory it was looking for existed under a different path.  It wanted it in `...\Anaconda3\Lib\site-packages\Sphinx-1.5.1-py3.6.egg` but I found it in `...\Anaconda3\pkgs\sphinx-1.5.1-py36_0\Lib\site-packages\Sphinx-1.5.1-py3.6.egg`.  This is the same version of Sphinx so it feels a bit more safe.  But I still don't understand why conda ever deleted the one that was in the first location, or, if it didn't delete it, why it was looking for it there.

**Comment by lucubrator** [comment] 2020-01-30 08:20
@jaseuts The error from the `conda list` command ended with: 
`RuntimeError: Path not found: C:\Anaconda3\Lib\site-packages\Sphinx-1.5.1-py3.6.egg\EGG-INFO` 

Going to the directory of the supposed `EGG-INFO`-folder one can see that the `EGG-INFO`-folder is indeed missing. To fix this problem, apacifico copied the `EGG-INFO` folder from somewhere else to this directory. 

As @BrenBarn said (and which was also my case), the `EGG-INFO`-folder of the same version of Sphinx could be found by looking for Sphinx in the pkgs directory, `...\Anaconda3\pkgs\...`. When you've found `EGG-INFO`, just copy it to the directory named in the RuntimeError message (`C:\Anaconda3\Lib\site-packages\Sphinx-1.5.1-py3.6.egg\EGG-INFO`).
