### ISSUE TITLE
Unable to install Python 3.4

### ISSUE THREAD

**Issue by mrbean-bremen** [conda/conda#8859] opened 2019-07-02 19:15 UTC
## Current Behavior

In [Travis.CI builds](https://travis-ci.org/pydicom/pydicom/builds/553068425) the Python 3.4 builds fail if upgrading to conda 4.7.5, but succeed if using the pre-installed 4.6.14 version.

### Steps to Reproduce

Conda is installed using miniconda,
```
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
        -O miniconda.sh
    MINICONDA_PATH=/home/travis/miniconda
    chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
    export PATH=$MINICONDA_PATH/bin:$PATH
    conda --version  # 4.6.14
    conda update --yes conda  # updates to 4.7.5
    conda create -n testenv --yes python=$PYTHON_VERSION pip
```
With PYTHON_VERSION 2.7, 3.5 - 3.7 this works as expected.
With PYTHON_VERSION=3.4, this fails with the following output:
```
PackagesNotFoundError: The following packages are not available from current channels:
  - python=3.4
Current channels:
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```
The full output can be seen [here](https://travis-ci.org/pydicom/pydicom/jobs/553068436).
## Expected Behavior

Will fill out the info below later (waiting for Travis.CI build).
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment] 2019-07-02 22:11
This is a duplicate of #8844

Draft blog post explaining things at https://docs.google.com/document/d/1F5KqQgC21Lj5eCODQQLQavnzNkVSdDSyFqR4xUICUvI/edit?usp=sharing

**Closed by msarahan** 2019-07-02 22:11 UTC

**Comment by mrbean-bremen** [comment] 2019-07-02 23:53
Thanks!
