### ISSUE TITLE
`vs2015_runtime` platform-dependent universal C-runtime version 

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda#2268] opened 2016-03-15 19:26 UTC
As of the version 14 of Visual Studio (2015), the C-runtime dlls were separated into two parts.

- the *Universal C-Runtime* libraries `api-ms-win-*`, which are dependent on the version of windows, but should not depend on the version of Visual Studio from MSVC 14 onward (future versions).
    These `api-ms-win-*` dll are present by default in windows 10, and available as an update for earlier versions of windows. (see [here](https://support.microsoft.com/en-us/kb/2999226).)

- the compiler version-dependent part of the msvc runtime that is provided with the redistributable package.

Since anaconda must be installable without admin rights, it cannot require the universal C runtime system update for earlier versions of windows than windows 10. What is done instead is that the `vs2015_runtime` package comes bundled with *a* version of those dlls, apparently the windows 7 versions.

It is not going to be a problem on windows 10 because the system libraries are searched *before* the `Library` subdirectory the of Anaconda install.

However, on other versions of windows (earlier than windows 10, different from windows 7), this version of the C-runtime is probably not compatible with the system.

**Comment by SylvainCorlay** [comment] 2016-03-15 19:27
As per discussion on gitter, cc @jmabille @jasongrout @msarahan @groutr.

**Comment by SylvainCorlay** [comment] 2016-03-16 14:07
A solution for that would be to
- remove the universal C runtime dlls from the `vs2015_runtime` package
- make the `vs2015_runtime` have runtime dependencies on different `ucr` (universal c runtime) packages depending on the version of windows (none for windows 10, this version for windows 7, and the ad hoc ones for win 8, win server, vista)

**Comment by msarahan** [comment] 2016-03-16 14:12
Yes, that's a good solution.  I don't think we really currently have a way of splitting up package destinations based on Windows version.  Maybe it would be OK to bundle them all into one, but have a post-link script actually do the copying of the correct files.

At any rate, this is a low priority issue until someone has a broken system because of it.  Please let me know if you encounter breakage in the field, and ideally any steps to reproduce (e.g. Win8.1 base install, no updates = barf)

**Comment by SylvainCorlay** [comment] 2016-03-16 14:19
Yes, you would need to extend the `# [win]`, `# [unix]` syntax to versions of windows.

**Comment by SylvainCorlay** [comment] 2016-03-16 14:22
> At any rate, this is a low priority issue until someone has a broken system because of it. Please let me know if you encounter breakage in the field, and ideally any steps to reproduce (e.g. Win8.1 base install, no updates = barf)

I guess we can come up with a case that breaks - there must be a good reason why they made the UCR platform dependent. It sounds like a really serious issue if anaconda3 is incompatible with windows 8...

**Comment by mcg1969** [comment] 2016-03-16 17:24
I use Anaconda3 with Windows 8 all the time. In what way is it incompatible?

**Comment by SylvainCorlay** [comment] 2016-03-16 17:26
@mcg1969 that would be because your windows 8 is up to date, and includes this update: https://support.microsoft.com/en-us/kb/2999226. If so, these version of the universal c runtime is going to be picked up before the one shipped with anaconda.

The problem would only occur on versions of windows 8/vista/server that don't have that update installed.

**Comment by mcg1969** [comment] 2016-03-16 17:29
OK, but is it unreasonable for us to ask our users to apply that update?

**Comment by SylvainCorlay** [comment] 2016-03-16 17:30
In managed corporate environments, this update might not be installed.

Besides, Anaconda must be installable without admin rights and can probably not require that update.

**Comment by mcg1969** [comment] 2016-03-16 21:40
I think of large numbers of our Windows users were having difficulty with this issue, we would already know about it. That's why I remain skeptical

**Comment by msarahan** [comment] 2016-03-16 22:29
I think this is a real issue, but unfortunately I don't have time to prioritize and investigate the fix right now.  I'm going to leave this open and assign it to myself.

Thanks for bringing it to our attention.

**Comment by jmabille** [comment] 2016-03-16 22:51
Maybe the issue can be confirmed (or infirmed) with the following steps on Windows 8 (or any Windows that is not Windows 7 or Windows 10):

- If the update mentioned by @SylvainCorlay is installed, rename the api-ms-win-*.dll in the WinSxS folder (adding an underscore in front of the name for instance) to be sure the assembly loader won't find them.
- If these DLLs are present in any subfolder of System32 or Visual Studio, rename them too (that should not change anything, but let's be sure the assembly loader can only find the DLLs that come with Anaconda)
- Be sure the api-ms-win-*.dll of the vs2015_runtime package are present in Anaconda folder, at the same level as Python.exe (that should be the root folder of Anaconda 
- Run a python script doing specific OS operations (such as I/O or a lot of memory allocation / deallocation) to see what happens.

If everything is ok, a debugger should be attached to Python.exe to check which C runtime DLLs are loaded.

Not sure about this procedure, but I think it's worth giving a try

**Comment by msarahan** [comment] 2016-03-16 23:31
I created a fresh VM of Windows 8.1.  Visual studio was not installed.  I searched the C:\Windows folder (which includes the WinSxS folder) for api-ms-win* and came up with nothing.

I installed Miniconda 3.19.0, which is Python 3.5.1.  Searching for api-ms-win* turns up the many DLLs that we ship.

Python starts fine.  I can create files, and I created a large list, then allowed it to be reclaimed.

If you have a specific problem you can show, I'll revisit this problem.

<img width="428" alt="screen shot 2016-03-16 at 18 28 16" src="https://cloud.githubusercontent.com/assets/38393/13831898/09ecdd54-eba5-11e5-953b-72dc78fadedb.png">
<img width="468" alt="screen shot 2016-03-16 at 18 28 28" src="https://cloud.githubusercontent.com/assets/38393/13831899/09eef3b4-eba5-11e5-8b17-6a81d7aedeb8.png">

**Comment by SylvainCorlay** [comment] 2016-03-16 23:44
Can you try launching spyder?

I created a fresh VM of Windows 8.1. Visual studio was not installed. I
searched the C:\Windows folder (which includes the WinSxS folder) for
api-ms-win* and came up with nothing.

I installed Miniconda 3.19.0, which is Python 3.5.1. Searching for
api-ms-win* turns up the many DLLs that we ship.

Python starts fine. I can create files, and I created a large list, then
allowed it to be reclaimed.

If you have a specific problem you can show, I'll revisit this problem.

[image: screen shot 2016-03-16 at 18 28 16]
<https://cloud.githubusercontent.com/assets/38393/13831898/09ecdd54-eba5-11e5-953b-72dc78fadedb.png>
[image: screen shot 2016-03-16 at 18 28 28]
<https://cloud.githubusercontent.com/assets/38393/13831899/09eef3b4-eba5-11e5-8b17-6a81d7aedeb8.png>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/conda/conda/issues/2268#issuecomment-197604164>

**Comment by msarahan** [comment] 2016-03-16 23:57
Sorry, that also works fine.

**Comment by jasongrout** [comment] 2016-03-17 15:12
By the way, I think you can check which dlls are being loaded by using http://www.dependencywalker.com/. That would make sure that you really are loading the DLLs from the vs 2015 conda package.

**Comment by SylvainCorlay** [comment] 2016-03-17 16:42
So looking at the blog entry by Microsoft VC++ team on the universal C runtime, they say:

*Updated September 11, 2015:  App-local deployment of the Universal CRT is supported.  To obtain the binaries for app-local deployment, install the Windows Software Development Kit (SDK) for Windows 10.  The binaries will be installed to C:\Program Files (x86)\Windows Kits\10\Redist\ucrt.  You will need to copy all of the DLLs with your app (* **note that the set of DLLs are necessary is different on different versions of Windows, so you must include all of the DLLs in order for your program to run on all supported versions of Windows)** *.*

However, a lot of the dll have exactly the same size between the win8 and win7 redistributables, but not all.

**Comment by SylvainCorlay** [comment] 2016-03-17 16:43
So looking at the blog entry by Microsoft VC++ team on the universal C runtime, they say:

*Updated September 11, 2015:  App-local deployment of the Universal CRT is supported.  To obtain the binaries for app-local deployment, install the Windows Software Development Kit (SDK) for Windows 10.  The binaries will be installed to C:\Program Files (x86)\Windows Kits\10\Redist\ucrt.  You will need to copy all of the DLLs with your app (* **note that the set of DLLs are necessary is different on different versions of Windows, so you must include all of the DLLs in order for your program to run on all supported versions of Windows)** *.*

However, a lot of the dll have exactly the same size between the win8 and win7 redistributables, but not all.

**Comment by msarahan** [comment] 2016-03-17 18:44
Thanks, Jason.  That did show dll's in C:\Windows\System32.  It turns out they're hidden - that's why I didn't see them before.  Cute.

I looked for KB2999226 in the Installed updates, but came up with nothing.  I can't delete the DLLs.  From an elevated admin command prompt, windows says

    C:\Windows\system32>del api-ms-win-appmodel-identity-l1-1-0.dll
    Could Not Find C:\Windows\system32\api-ms-win-appmodel-identity-l1-1-0.dll

I tried to make the files not hidden, but can't elevate permissions to do that.  MS has really protected these things.

I manually (one-by-one) uninstalled 88 windows updates.  A few remain that I can't uninstall (the option to uninstall simply isn't there).  After that, the DLLs are still there.

<img width="1324" alt="screen shot 2016-03-17 at 13 40 29" src="https://cloud.githubusercontent.com/assets/38393/13857017/ef2cbc18-ec45-11e5-86a5-176909d60b14.png">

The DLLs that we copy are:

robocopy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\%VC_PATH%"  "%PREFIX%" *.dll /E
robocopy "C:\Program Files (x86)\Microsoft Visual Studio %MSC_VER%.0\VC\redist\%VC_PATH%\Microsoft.VC%MSC_VER%0.CRT" "%PREFIX%" *.dll /E

I think we're following the instructions you quote.

I'm sorry, but until there is a report of an actual problem caused by this, I need to move on.

**Comment by SylvainCorlay** [comment] 2016-03-17 19:06
> So looking at the blog entry by Microsoft VC++ team on the universal C runtime, they say:

> *Updated September 11, 2015:  App-local deployment of the Universal CRT is supported.  To obtain the binaries for app-local deployment, install the Windows Software Development Kit (SDK) for Windows 10.  The binaries will be installed to C:\Program Files (x86)\Windows Kits\10\Redist\ucrt.  You will need to copy all of the DLLs with your app (* **note that the set of DLLs are necessary is different on different versions of Windows, so you must include all of the DLLs in order for your program to run on all supported versions of Windows)** *.*

We got some info from the MSVC guys. It happens that if you want to do app-local deployment of the universal C runtime, you can use the dlls from the Win10 SDK redist on any earlier version of windows.

**Closed** 2016-04-07 23:25 UTC

**Comment by jasongrout** [comment] 2016-04-07 23:29
Why did you close this?
