### ISSUE TITLE
Trying to create an environment and getting the error CondaError: Run 'conda init' before 'conda activate'

### ISSUE THREAD

**Issue by Iris-ai12** [conda/conda#14147] opened 2024-08-13 00:55 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have an open source code with some methods suppored by old versions of python and torch. So I try to create an environment with anacoda:

```
!pip install -q condacolab
import condacolab
condacolab.install()
!conda create -n my_env python=3.6.5
!conda activate my_env
```

An error occured: `CondaError: Run conda init before conda activate`

### Conda Info

```shell
active environment : None
       user config file : /root/.condarc
 populated config files : /usr/local/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=broadwell
                          __conda=23.11.0=0
                          __glibc=2.35=0
                          __linux=6.1.85=0
                          __unix=0=0
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Linux/6.1.85+ ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /usr/local/.condarc <==
channels:
  - conda-forge
always_yes: True
```

### Conda list

```shell
# packages in environment at /usr/local:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
boltons                   23.1.1             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.24.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h2fee648_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.11.0         py310hff52083_1    conda-forge
conda-libmamba-solver     23.12.0            pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
condacolab                0.1.9                    pypi_0    pypi
distro                    1.8.0              pyhd8ed1ab_0    conda-forge
filelock                  3.15.4                   pypi_0    pypi
fmt                       10.1.1               h00ab1b0_1    conda-forge
fsspec                    2024.6.1                 pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4                    pypi_0    pypi
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py310hff52083_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libarchive                3.7.2                h2aa1ff5_1    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libmamba                  1.5.5                had39da4_0    conda-forge
libmambapy                1.5.5           py310h39ff949_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsolv                   0.7.27               hfc55251_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.12.3               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.5.5           py310h51d5547_0    conda-forge
markupsafe                2.1.5                    pypi_0    pypi
menuinst                  2.0.1           py310hff52083_0    conda-forge
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  3.3                      pypi_0    pypi
numpy                     2.0.1                    pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.20                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pillow                    10.4.0                   pypi_0    pypi
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py310h2372a71_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.13         hd12c33a_0_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.5          py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h2372a71_2    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
sympy                     1.13.2                   pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torch                     1.12.1                   pypi_0    pypi
torchaudio                2.4.0                    pypi_0    pypi
torchvision               0.13.1                   pypi_0    pypi
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
triton                    3.0.0                    pypi_0    pypi
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zstandard                 0.22.0          py310h1275a96_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by travishathaway** [comment] 2024-08-13 07:28
@Iris-ai12,

Please see this comment:

- https://github.com/conda/conda/issues/13998#issuecomment-2239306638

Creating new environments with different Python versions is not possible using condacolab.

**Comment by travishathaway** [comment] 2024-08-13 07:29
Duplicate of: https://github.com/conda/conda/issues/13998

**Comment by Iris-ai12** [comment] 2024-08-13 08:28
> @Iris-ai12,
> 
> Please see this comment:
> 
> * [The error report "CondaError: Run 'conda init' before 'conda activate'" is misleading, solution proposed #13998 (comment)](https://github.com/conda/conda/issues/13998#issuecomment-2239306638)
> 
> Creating new environments with different Python versions is not possible using condacolab.

Ok. Is there a solusion to excecute the code  ? I use Colab

**Comment by Iris-ai12** [comment] 2024-08-13 08:32
> Duplicate of: #13998

"conda init" doesn't work also.

I use Colab. It is the same thing ?

**Comment by travishathaway** [comment] 2024-08-15 13:52
@Iris-ai12,

You cannot execute those conda commands and expect them to work in Colab using condacolab. The condacolab library does not support creating additional environments.

**Comment by Iris-ai12** [comment] 2024-08-15 23:43
> @Iris-ai12,
> 
> You cannot execute those conda commands and expect them to work in Colab using condacolab. The condacolab library does not support creating additional environments.

Could you please tell me how can I use environments in Colab ?

**Closed** 2024-08-16 07:23 UTC
Labels: source::community, duplicate
