### ISSUE TITLE
condo-build 3.10.9 fails on python 2.7

### ISSUE THREAD

**Issue by bp-kelley** [conda/conda#7448] opened 2018-06-19 16:26 UTC
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior
conda build fails on python 2.7

I checked the issue log for a duplicate but was unable to find one, so here goes:

```
$ conda build .
Traceback (most recent call last):
  File "/Users/kellebr5/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 2155, in build_tree
    bypass_env_check=True)
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 705, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 835, in __init__
    self.parse_again(permit_undefined_jinja=True, allow_no_other_outputs=True)
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 908, in parse_again
    bypass_env_check=bypass_env_check),
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 1449, in _get_contents
    env.globals.update(environ.get_dict(m=self))
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/environ.py", line 252, in get_dict
    d.update(python_vars(m, prefix))
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/environ.py", line 310, in python_vars
    'STDLIB_DIR': utils.get_stdlib_dir(prefix, py_ver),
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 815, in get_stdlib_dir
    python_folder = glob(os.path.join(lib_dir, 'python?.*'))
  File "/Users/kellebr5/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 59, in glob
    return glob2_glob(pathname, recursive=recursive)
TypeError: glob() got an unexpected keyword argument 'recursive'
```

### Steps to Reproduce

Update to conda build 3.10.9 on python 2.7
```
conda update conda-build
Solving environment: done

## Package Plan ##

  environment location: /Users/kellebr5/anaconda

  added / updated specs: 
    - conda-build


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-build-3.10.9         |           py27_0         429 KB

The following packages will be UPDATED:

    conda-build: 3.7.1-py27_0 --> 3.10.9-py27_0
```

## Expected Behavior

The build would complete.

The following change resolved the issue in conda_build/utils.py line 58
The recursive keyword is only support in python 3.5 forward I believe:

https://docs.python.org/3/library/glob.html

```
    def glob(pathname, recursive=True):
        return glob2_glob(pathname)#, recursive=recursive)
```
n.b. this is in the non PY3 branch, but I think the minor version might need to be checked as well as the 'if PY3' check.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
                          /Users/me/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.13.0 CPython/2.7.14 Darwin/17.5.0 OSX/10.13.4
                UID:GID : 1506476385:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment] 2018-06-19 16:55
This is a conda-build issue, not a conda issue.  It is also a duplicate of https://github.com/conda/conda-build/issues/2976

**Closed by msarahan** 2018-06-19 16:55 UTC
