### ISSUE TITLE
Miniconda3-latest-Linux-x86_64.sh: 494: [[: not found

### ISSUE THREAD

**Issue by samuel-hunter** [conda/conda#10431] opened 2020-12-25 23:36 UTC
## Current Behavior

After being prompted to run `conda init`, The miniconda installer exits with the error `[[: not found`, and then continues installing:

```
Preparing transaction: done
Executing transaction: done
installation finished.
Do you wish the installer to initialize Miniconda3
by running conda init? [yes|no]
[no] >>> yes
Miniconda3-latest-Linux-x86_64.sh: 494: [[: not found
```

### Steps to Reproduce

1. Use a Linux distribution that links `/bin/sh` to a shell outside `bash` -- Debian, for example. links it to `dash`.
1. Download Miniconda3-latest-Linux-x86_64.sh from https://docs.conda.io/en/latest/miniconda.html
1. Run it either with `chmod +x Miniconda3-latest-Linux-x86_64.sh && ./Miniconda3-latest-Linux-x86_64.sh` or `sh Miniconda3-latest-Linux-x86_64.sh`
1. After being prompted to run `conda init`, answer `yes`.

## Steps to Fix

It looks like the issue with the command is in the Installer:

```sh
# lines 494-499
        if [[ $SHELL = *zsh ]]
        then
            $PREFIX/bin/conda init zsh
        else
            $PREFIX/bin/conda init
        fi
```

`[[`, as a bash extension, is not necessarily available for all POSIX shells (as the hashbang `#!/bin/sh` implies). There are two solutions here:

### (Preferred) Replace `[[` with a `case`
```sh
# replace lines 494-499 with:
        case $SHELL in
            *zsh)
                $PREFIX/bin/conda init zsh
                ;;
            *)
                $PREFIX/bin/conda init
                ;;
        esac
```

### Explicitly mark the installer as a bash script:
Replace the hashbang on line 1:

```diff
-#!/bin/sh
+#!/bin/bash
```

- - -
In theory this solution is easy enough for me to make a pull request instead, but I couldn't for the life of me figure out how the installer is built. `ack`ing for the code snippet in this repo shows nothing for me, and being completely new to conda, I don't know which repo out of the 37 in this GitHub organization contains the script that builds the installer. If I could find a pointer to where it is, I'd be happy to set up the pull request.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-329)

**Comment by aoliong** [comment] 2021-07-22 11:54
Hi, when I fixed the Installer, and change the md5 in Installer, then I got this:

```
[/project/miniconda3] >>> 
PREFIX=/project/miniconda3
Unpacking payload ...
./Miniconda3-py39_4.9.2-Linux-x86_64.sh: line 412: /project/miniconda3/conda.exe: cannot execute binary file: Exec format error
./Miniconda3-py39_4.9.2-Linux-x86_64.sh: line 414: /project/miniconda3/conda.exe: cannot execute binary file: Exec format error`
```

How can I fix this ?

**Comment by samuel-hunter** [comment] 2021-07-22 14:08
Hi @aoliong, it looks like the errors are within lines 412-414. Can you show me a snippet that has those line numbers?

**Comment by jezdez** [comment] 2021-12-16 18:09
This seems to be an issue in the constructor version that Anaconda uses to build miniconda, which was already fixed in the main repo in https://github.com/conda/constructor/blob/a7ad3d2807129b2cdc596337b5081df1967002d5/constructor/header.sh#L591-L594

**Comment by jezdez** [comment] 2021-12-16 18:12
I've opened an internal ticket to track the fix.

**Comment by stmlange** [comment] 2022-12-23 07:32
Any updates on this? This still seems to be a problem with the latest installer:

{code}
$ curl -sSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o Miniconda3-latest-Linux-x86_64.sh
$ sha256sum *
00938c3534750a0e4069499baf8f4e6dc1c2e471c86a59caa0dd03f4a9269db6  Miniconda3-latest-Linux-x86_64.sh
$ chmod +x Miniconda3-latest-Linux-x86_64.sh
$ ./Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3
{code}
fails with
{code}
./Miniconda3-latest-Linux-x86_64.sh: 438: [[: not found
./Miniconda3-latest-Linux-x86_64.sh: 444: [[: not found
{code}
Thanks!

**Comment by AnkushMalaker** [comment] 2022-12-23 08:40
I'm facing the same issue with the py39 installer as-well. 
I get the following logs:
```
PREFIX=/home/ubuntu/miniconda3
Unpacking payload ...
                                                                                                         
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
Miniconda3-latest-Linux-x86_64.sh: 438: [[: not found

Installing * environment...

Miniconda3-latest-Linux-x86_64.sh: 444: [[: not found

CondaFileIOError: '/home/ubuntu/miniconda3/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '/home/ubuntu/miniconda3/pkgs/envs/*/env.txt'
```
This is a fresh install of ubuntu 22.10.

**Comment by stmlange** [comment] 2022-12-23 08:59
Thanks for the hint! I was initially trying the `source activate` which was suggested in one of the [previous comments](https://github.com/conda/conda/issues/10431#issuecomment-884854215) which didn't work. Using `bash Miniconda3-latest-Linux-x86_64.sh` to install works fine on ubuntu jammy (22.04.1 LTS).

**Comment by jonhermansen** [comment] 2022-12-23 17:36
I ran into this issue today as well, thank you all for the suggestion of running under `bash`

Perhaps the shebang at the top of the script, should be changed?

**Comment by dbast** [comment] 2022-12-23 19:51
related https://github.com/conda/constructor/issues/596

**Comment by ezyang** [comment] 2022-12-24 07:07
This is more pressing now that focal is shipping a sh that doesn't understand this bash-ism

**Comment by pat-s** [comment] 2022-12-25 08:56
I also just hit this in `focal` latest. Quite unfortunate from an outside perspective.

Invoking the `.sh` script with `./` should really work as one rarely calls `bash <script>.sh` in an automation workflow. A working shebang definition should solve this.

**Comment by jaimergp** [comment] 2022-12-28 15:44
Sorry about this!

The `constructor` test suite was using `bash` to run the installers in CI, so this regression wasn't caught. Fix has been submitted https://github.com/conda/constructor/pull/599.

In the meantime, please use `bash <your-installer.sh>` to run the installation.

**Comment by stmlange** [comment] 2022-12-28 15:53
Thanks for your quick reaction and fix despite the fact that I have re-used an old issue in the wrong repo (for me it wasn't clear where to report it and this one was still open) :-)

**Comment by sbrozell** [comment] 2022-12-29 22:38
Thanks.  When will the fix go live ?

**Closed** 2023-01-02 08:09 UTC
Labels: source::community, severity::2, type::installer, backlog

**Comment by sbrozell** [comment] 2023-01-04 21:33
Is it expected that this will ultimately be fixed in release distribution ?

**Comment by donaldafeith** [comment] 2023-01-17 01:57
Remember to restart. (I'm running WSL 2 and was able to install it by)

- curl -sSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o Miniconda3-latest-Linux-x86_64.sh
- chmod +x Miniconda3-latest-Linux-x86_64.sh
-  ./Miniconda3-latest-Linux-x86_64.sh -b -p /home/user/miniconda3a **because I have windows python installed with miniconda /user/miniconda3
-  conda config --set auto_activate_base false
- exited out of WSL2 
- Restarted WSL2
- conda --version

**Comment by divinity76** [comment] 2023-01-20 02:31
seems to still be unfixed as of 2023-01-20, and the `bash -c` workaround does NOT work, i can reproduce it with this Dockerfile:
```
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt-get update -y
RUN apt-get install -y wget
RUN wget --no-verbose 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh';
RUN chmod +x ./Miniconda3-latest-Linux-x86_64.sh;
RUN bash -c './Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda;'
```
yields
```
$ docker build -f Dockerfile .;
Sending build context to Docker daemon  92.34MB
Step 1/28 : FROM ubuntu:22.04
 ---> 6b7dfa7e8fdb
Step 2/28 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 9fcfd668e8a3
Step 3/28 : RUN apt-get update -y
 ---> Using cache
 ---> 76449545c502
Step 4/28 : RUN apt-get install -y wget
 ---> Using cache
 ---> 5c0ab313726e
Step 5/28 : RUN wget --no-verbose 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh';
 ---> Running in 763122d8236d
2023-01-20 02:29:04 URL:https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh [72402405/72402405] -> "Miniconda3-latest-Linux-x86_64.sh" [1]
Removing intermediate container 763122d8236d
 ---> aa1dcca06d6f
Step 6/28 : RUN chmod +x ./Miniconda3-latest-Linux-x86_64.sh;
 ---> Running in 06dec8f155ac
Removing intermediate container 06dec8f155ac
 ---> 333dd872b5e3
Step 7/28 : RUN bash -c './Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda;'
 ---> Running in 85b760c4cf22
PREFIX=/miniconda
Unpacking payload ...
                                                                                                               
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: ...working... done
Executing transaction: ...working... done
./Miniconda3-latest-Linux-x86_64.sh: 438: [[: not found

Installing * environment...

./Miniconda3-latest-Linux-x86_64.sh: 444: [[: not found

CondaFileIOError: '/miniconda/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '/miniconda/pkgs/envs/*/env.txt'

The command '/bin/sh -c bash -c './Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda;'' returned a non-zero code: 1
```

**Comment by dbast** [comment] 2023-01-20 08:00
you have to call `bash Miniconda3-latest-Linux-x86_64.sh` ... without `-c` ... and also no need for the `chmod` call!

**Comment by divinity76** [comment] 2023-01-21 00:17
@dbast that actually worked! thanks! btw i'm positive there is a bug in the current Miniconda3-latest-Linux-x86_64.sh where it uses `#!/bin/bash`-exclusive syntax with the shebang `#!/bin/sh` , causing normal invocation to crash, but when the file is invoked with `bash Miniconda...sh` , the shebang will be ignored, and it will be parsed with bash-rules regardless of shebang~

**Comment by Aemon-Algiz** [comment] 2023-05-22 00:45
@divinity76 You are a hero.
