### ISSUE TITLE
`ERROR conda.core.link:_execute(952)`

### ISSUE THREAD

**Issue by ZeWLi** [conda/conda#12728] opened 2023-05-29 06:38 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I tried to create a conda environment with yml file on a server, but it turned out to report error info.  But I can download this package on my PC and update to the server, so I wonder how I can fix that. Thanks!

`ERROR conda.core.link:_execute(952): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'.`

### Conda Info

```shell
active environment : base
    active env location : /home/lizw/anaconda3
            shell level : 1
       user config file : /home/lizw/.condarc
 populated config files : /home/lizw/.condarc
          conda version : 23.5.0
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /home/lizw/anaconda3  (writable)
      conda av data dir : /home/lizw/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : file:///home/lizw/conda/linux-64
                          file:///home/lizw/conda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/lizw/anaconda3/pkgs
                          /home/lizw/.conda/pkgs
       envs directories : /home/lizw/anaconda3/envs
                          /home/lizw/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.0 requests/2.29.0 CPython/3.10.9 Linux/3.10.0-1160.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1007:1008
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/lizw/.condarc <==
channels:
  - /home/lizw/conda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
```

### Conda list

```shell
# packages in environment at /home/lizw/anaconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
anaconda-client           1.11.2          py310h06a4308_0    defaults
anaconda-navigator        2.4.0           py310h06a4308_0    defaults
anaconda-project          0.11.1          py310h06a4308_0    defaults
attrs                     22.1.0          py310h06a4308_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.12.2          py310h06a4308_0    defaults
boltons                   23.0.0          py310h06a4308_0    defaults
brotlipy                  0.7.0           py310h7f8727e_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2023.5.7        py310h06a4308_0    defaults
cffi                      1.15.1          py310h5eee18b_3    defaults
chardet                   4.0.0           py310h06a4308_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py310h06a4308_0    defaults
clyent                    1.2.2           py310h06a4308_1    defaults
conda                     23.5.0          py310h06a4308_0    defaults
conda-build               3.24.0          py310h06a4308_0    defaults
conda-content-trust       0.1.3           py310h06a4308_0    defaults
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    2.0.2           py310h06a4308_0    defaults
conda-package-streaming   0.7.0           py310h06a4308_0    defaults
conda-repo-cli            1.0.41          py310h06a4308_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
cryptography              39.0.1          py310h9ce1e76_0    defaults
dbus                      1.13.18              hb2f20db_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
expat                     2.4.9                h6a678d5_0    defaults
filelock                  3.9.0           py310h06a4308_0    defaults
fontconfig                2.14.1               h52c9d5c_1    defaults
freetype                  2.12.1               h4a9f257_0    defaults
future                    0.18.3          py310h06a4308_0    defaults
giflib                    5.2.1                h5eee18b_3    defaults
glib                      2.69.1               he621ea3_2    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
gst-plugins-base          1.14.1               h6a678d5_1    defaults
gstreamer                 1.14.1               h5eee18b_1    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.4             py310h06a4308_0    defaults
jinja2                    3.1.2           py310h06a4308_0    defaults
jpeg                      9e                   h5eee18b_1    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.17.3          py310h06a4308_0    defaults
jupyter_core              5.3.0           py310h06a4308_0    defaults
krb5                      1.19.4               h568e23c_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libarchive                3.5.2                h5de8990_0    defaults
libclang                  10.0.1          default_hb85057a_2    defaults
libdeflate                1.17                 h5eee18b_0    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libevent                  2.1.12               h8f2d780_0    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
liblief                   0.12.3               h6a678d5_0    defaults
libllvm10                 10.0.1               hbcb73fb_5    defaults
libpng                    1.6.39               h5eee18b_0    defaults
libpq                     12.9                 h16c4e8d_3    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtiff                   4.5.0                h6a678d5_2    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libwebp                   1.2.4                h11a3e52_1    defaults
libwebp-base              1.2.4                h5eee18b_1    defaults
libxcb                    1.15                 h7f8727e_0    defaults
libxkbcommon              1.0.1                hfa300c1_0    defaults
libxml2                   2.9.14               h74e7548_0    defaults
libxslt                   1.1.35               h4e12654_0    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
markupsafe                2.1.1           py310h7f8727e_0    defaults
navigator-updater         0.3.0           py310h06a4308_0    defaults
nbformat                  5.7.0           py310h06a4308_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
nspr                      4.33                 h295c915_0    defaults
nss                       3.74                 h0370c37_0    defaults
openssl                   1.1.1t               h7f8727e_0    defaults
packaging                 23.0            py310h06a4308_0    defaults
patch                     2.7.6             h7b6447c_1001    defaults
patchelf                  0.17.2               h6a678d5_0    defaults
pathlib                   1.0.1              pyhd3eb1b0_1    defaults
pcre                      8.45                 h295c915_0    defaults
pillow                    9.4.0           py310h6a678d5_0    defaults
pip                       22.3.1          py310h06a4308_0    defaults
pkginfo                   1.9.6           py310h06a4308_0    defaults
platformdirs              2.5.2           py310h06a4308_0    defaults
pluggy                    1.0.0           py310h06a4308_1    defaults
ply                       3.11            py310h06a4308_0    defaults
psutil                    5.9.0           py310h5eee18b_0    defaults
py-lief                   0.12.3          py310h6a678d5_0    defaults
pycosat                   0.6.4           py310h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyjwt                     2.4.0           py310h06a4308_0    defaults
pyopenssl                 23.0.0          py310h06a4308_0    defaults
pyqt                      5.15.7          py310h6a678d5_1    defaults
pyqt5-sip                 12.11.0                  pypi_0    pypi
pyrsistent                0.18.0          py310h7f8727e_0    defaults
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.9               h7a1cb2a_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2          py310h06a4308_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2022.7          py310h06a4308_0    defaults
pyyaml                    6.0             py310h5eee18b_1    defaults
qt-main                   5.15.2               h327a75a_7    defaults
qt-webengine              5.15.9               hd2b0992_4    defaults
qtpy                      2.2.0           py310h06a4308_0    defaults
qtwebkit                  5.212                h4eab89a_4    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.29.0          py310h06a4308_0    defaults
requests-toolbelt         0.9.1              pyhd3eb1b0_0    defaults
ripgrep                   13.0.0               hbdeaff8_0    defaults
ruamel.yaml               0.17.21         py310h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6           py310h5eee18b_1    defaults
ruamel_yaml               0.17.21         py310h5eee18b_0    defaults
setuptools                65.6.3          py310h06a4308_0    defaults
sip                       6.6.2           py310h6a678d5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.4             py310h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1           py310h06a4308_0    defaults
toolz                     0.12.0          py310h06a4308_0    defaults
tornado                   6.2             py310h5eee18b_0    defaults
tqdm                      4.65.0          py310h2f386ee_0    defaults
traitlets                 5.7.1           py310h06a4308_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
ujson                     5.4.0           py310h6a678d5_0    defaults
urllib3                   1.26.15         py310h06a4308_0    defaults
wheel                     0.38.4          py310h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py310h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

**Comment by travishathaway** [comment] 2023-05-30 07:36
Hi @ZeWLi,

Thanks for filing this issue. Can you please share that particular environment file (please paste the contents in a comment). Once we see this file, we can get a better idea of exactly why you are seeing this error.

Thanks,

**Comment by cqmuhj** [comment] 2023-06-08 16:48
I also encountered this error code when trying to install the 'fastqc' package using conda on the win64 platform. I have tried many methods, but I still failed. It seems that this error code is not commonly found online, and now I'm at a loss on how to solve this problem.

**Comment by cqmuhj** [comment] 2023-06-08 17:01
[upstream.tar.gz](https://github.com/conda/conda/files/11691124/upstream.tar.gz)

This is my environment file. I encountered the aforementioned error when installing the 'fastqc' package, but it seems that other packages are not affected for now.

**Comment by cqmuhj** [comment] 2023-06-08 17:07
Here is the relevant information.

**conda info**
`
     active environment : upstream
    active env location : C:\Users\hj\miniconda3\envs\upstream
            shell level : 4
       user config file : C:\Users\hj\.condarc
 populated config files : C:\Users\hj\.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : C:\Users\hj\miniconda3  (writable)
      conda av data dir : C:\Users\hj\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
          package cache : C:\Users\hj\miniconda3\pkgs
                          C:\Users\hj\.conda\pkgs
                          C:\Users\hj\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\hj\miniconda3\envs
                          C:\Users\hj\.conda\envs
                          C:\Users\hj\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.5.0 requests/2.29.0 CPython/3.10.11 Windows/10 Windows/10.0.22000
          administrator : True
             netrc file : None
           offline mode : False
`

conda config
`channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
show_channel_urls: true
ssl_verify: false`

**Comment by travishathaway** [comment] 2023-06-12 07:14
@cqmuhj,

If you want us to see the environment file, please copy and paste the contents of the file into a comment.

**Comment by cqmuhj** [comment] 2023-06-12 13:33
> [upstream.tar.gz](https://github.com/conda/conda/files/11691124/upstream.tar.gz)
> 
> This is my environment file. I encountered the aforementioned error when installing the 'fastqc' package, but it seems that other packages are not affected for now.


Yes, I have packaged my environment using the pack tool and attached it to this reply. If you encounter any issues while downloading it, please let me know promptly. I am highly invested in finding a solution to this problem.

**Comment by cqmuhj** [comment] 2023-06-12 13:40
I'm sorry, it seems like I misunderstood your request. Here are the file and contents of the environment that I exported using the "export" command:




name: upstream
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
prefix: C:\Users\hj\miniconda3\envs\upstream

**Comment by cqmuhj** [comment] 2023-06-12 13:56
This is my environment file. I can install biopython here, but I encountered an error (Error 952) while trying to install fastqc:


name: upstream
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - biopython=1.69=np113py27_0
  - blas=1.0=mkl
  - certifi=2016.2.28=py27_0
  - mkl=2017.0.3=0
  - numpy=1.13.1=py27_0
  - pip=9.0.1=py27_1
  - python=2.7.13=1
  - setuptools=36.4.0=py27_1
  - vc=9=h2eaa2aa_6
  - vs2008_runtime=9.00.30729.5054=0
  - wheel=0.29.0=py27_0
  - wincertstore=0.2=py27_0
prefix: C:\Users\hj\miniconda3\envs\upstream



and this is the error content:
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\hj\miniconda3\envs\upstream

  added / updated specs:
    - fastqc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fastqc-0.11.7              |       hdfd78af_7         9.6 MB  http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
    openjdk-17.0.3             |       h57928b3_1       165.5 MB  http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    vs2015_runtime-14.0.25420  |                0         2.0 MB  http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    ------------------------------------------------------------
                                           Total:       177.0 MB

The following NEW packages will be INSTALLED:

  fastqc             anaconda/cloud/bioconda/noarch::fastqc-0.11.7-hdfd78af_7
  openjdk            anaconda/cloud/conda-forge/win-64::openjdk-17.0.3-h57928b3_1
  perl               anaconda/pkgs/free/win-64::perl-5.20.3.1-1
  vs2015_runtime     anaconda/pkgs/free/win-64::vs2015_runtime-14.0.25420-0


Proceed ([y]/n)?


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(952): An error occurred while installing package 'http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::fastqc-0.11.7-hdfd78af_7'.
Rolling back transaction: done

[Errno 22] Invalid argument: 'C:\\Users\\hj\\miniconda3\\pkgs\\fastqc-0.11.7-hdfd78af_7\\bin\\fastqc'
()

**Comment by cqmuhj** [comment] 2023-06-12 14:00
This is my environment file. I can install biopython here, but I encountered an error (Error 952) while trying to install fastqc:


```
name: upstream
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - biopython=1.69=np113py27_0
  - blas=1.0=mkl
  - certifi=2016.2.28=py27_0
  - mkl=2017.0.3=0
  - numpy=1.13.1=py27_0
  - pip=9.0.1=py27_1
  - python=2.7.13=1
  - setuptools=36.4.0=py27_1
  - vc=9=h2eaa2aa_6
  - vs2008_runtime=9.00.30729.5054=0
  - wheel=0.29.0=py27_0
  - wincertstore=0.2=py27_0
prefix: C:\Users\hj\miniconda3\envs\upstream
```


and this is the error content:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\hj\miniconda3\envs\upstream

  added / updated specs:
    - fastqc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fastqc-0.11.7              |       hdfd78af_7         9.6 MB  http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
    openjdk-17.0.3             |       h57928b3_1       165.5 MB  http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    vs2015_runtime-14.0.25420  |                0         2.0 MB  http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    ------------------------------------------------------------
                                           Total:       177.0 MB

The following NEW packages will be INSTALLED:

  fastqc             anaconda/cloud/bioconda/noarch::fastqc-0.11.7-hdfd78af_7
  openjdk            anaconda/cloud/conda-forge/win-64::openjdk-17.0.3-h57928b3_1
  perl               anaconda/pkgs/free/win-64::perl-5.20.3.1-1
  vs2015_runtime     anaconda/pkgs/free/win-64::vs2015_runtime-14.0.25420-0


Proceed ([y]/n)?


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(952): An error occurred while installing package 'http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::fastqc-0.11.7-hdfd78af_7'.
Rolling back transaction: done

[Errno 22] Invalid argument: 'C:\\Users\\hj\\miniconda3\\pkgs\\fastqc-0.11.7-hdfd78af_7\\bin\\fastqc'
()
```

**Comment by travishathaway** [comment] 2023-06-14 11:48
Hi @cqmuhj,

For your case, the answer is that Bioconda packages are not supported on Windows. Even though that package says `noarch` there migth be some sort of unix shell script running during the transaction.

**Comment by cqmuhj** [comment] 2023-06-14 17:21
Thank you @travishathaway 
Thank you very much for your patient assistance and responses. I am grateful for your professionalism and enthusiasm, which align with my initial assumptions. The fastq software originally had a Windows version, and Conda is also labeled as "noarch," so I thought it should have been well-adapted within Conda. However, this error occurred. Nevertheless, Conda is a very convenient software to use, and I hope it continues to improve. Once again, thank you for your help!

**Comment by LZXstal** [comment] 2023-06-25 03:56
I tried to install the R package on the server using the “conda install -c conda-forge r-wgcna”, but I got the following error:
`ERROR conda.core.link:_execute(952): An error occurred while installing package 'bioconda::bioco                                                  nductor-genomeinfodbdata-1.2.9-r42hdfd78af_0'.                                              
Rolling back transaction: done          
      
class: LinkError                                                                                                        
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78af_0
location of failed script: /data/lizhixian/Installation/miniconda3/envs/R_4.2/bin/.bioconductor-                                                    genomeinfodbdata-post-link.sh`


My conda info:
active environment : R_4.2
    active env location : /data/lizhixian/Installation/miniconda3/envs/R_4.2
            shell level : 2
       user config file : /home/lizhixian/.condarc
 populated config files : /home/lizhixian/.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.27=0
                          __linux=5.4.0=0
                          __unix=0=0
       base environment : /data/lizhixian/Installation/miniconda3  (writable)
      conda av data dir : /data/lizhixian/Installation/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /data/lizhixian/Installation/miniconda3/pkgs
                          /home/lizhixian/.conda/pkgs
       envs directories : /data/lizhixian/Installation/miniconda3/envs
                          /home/lizhixian/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.0 requests/2.31.0 CPython/3.9.16 Linux/5.4.0-148-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False

I have successfully installed this R package in my own windows computer, but whatever cannot install it on Linux server, how can I solve this  problem?

**Comment by travishathaway** [comment] 2023-07-14 12:32
Hi @LZXstal,

I am not sure how to solve this particular problem, but I can at least point you to the script that's failing so you can get more information:

The post-link script in the recipe:

- https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-genomeinfodbdata/post-link.sh

And the link to the actual script being run (I 99% sure that's the right one):

- https://github.com/dfornika/bioconda-recipes/blob/f8332d1cfd026a0cf1ae40678ff6be586ab93bc4/recipes/bioconductor-data-packages/installBiocDataPackage.sh#L4

Unfortunately, it doesn't look like there was a lot of error output reported, but perhaps if you run that script manually, you can get a little more insight?

Additionally, there's not much more I can do as a conda maintainer to help here. This is something that you will have to bring up with that specific package maintainer.

Hope this helps.

**Comment by carlosalvarezh** [comment] 2023-07-14 13:57
Hello, I have a similar error when trying to install different packages through Anaconda. In this particular case, it's with Rise:

ERROR conda.core.link:_execute(952): An error occurred while installing package 'conda-forge::rise-5.7.1-py311h1ea47a8_2'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::rise-5.7.1-py311h1ea47a8_2
location of failed script: C:\Users\USER\anaconda3\Scripts\.rise-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\jupyter_core\application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)

Just to share a few lines of the error. My operating system is W10, and the Python kernel I'm using is

Python 3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]

I have been searching forums, but nowhere can I find a solution to this issue. I have already tried running the console as an administrator, completely uninstalling Anaconda and reinstalling it, but nothing works.

I also have a computer with Linux Mint, and there I have been able to install packages without any issues. Could there be any inconsistency between the latest versions of the packages and W10?

**Comment by travishathaway** [comment] 2023-07-18 13:58
@carlosalvarezh,

This error is a result of the package failing to install correctly, specifically the post-link script. It's not happening within conda itself. Therefore, you should contact the authors of the package. I believe this is the correct repository for that project: https://github.com/conda-forge/rise-feedstock (rise?)

For anyone else coming to this issue with similar problems, please attempt to reach out to the package maintainers if the problem is stemming from a post-link script.

Thanks! ✌️

**Comment by travishathaway** [comment] 2023-09-13 12:14
@ShuyiF,

It looks like you don't have enough space on your drive to support the download.

I'm going to go ahead and close this issue as I believe it has been discussed adequately and the solutions to many of these problems do not fall the within scope of bugs directly related to conda (i.e. problems within conda's source code).

**Closed by travishathaway** 2023-09-13 12:14 UTC
Labels: type::bug, source::community
