### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by sutwili** [conda/conda#5918] opened 2017-09-05 05:24 UTC
D:\software\Anaconda3\Scripts>conda install -c conda-forge tensorflow
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : D:\software\Anaconda3  (writable)
    default environment : D:\software\Anaconda3
       envs directories : D:\software\Anaconda3\envs
          package cache : D:\software\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ D:\software\Anaconda3\Scripts\conda-script.py install -c conda-forge tensorflow`

    Traceback (most recent call last):
      File "D:\software\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\software\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "D:\software\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "D:\software\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "D:\software\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "D:\software\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "D:\software\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "D:\software\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "D:\software\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "D:\software\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\software\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "D:\software\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "D:\software\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "D:\software\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "D:\software\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "D:\software\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "D:\software\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
        self._prepare_proxy(conn)
      File "D:\software\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
        conn.connect()
      File "D:\software\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "D:\software\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "D:\software\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 66, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kalefranz** [comment] 2017-10-05 18:25
Related to or duplicate of #3962.

**Comment by kalefranz** [comment] 2017-10-05 18:28
Please move future discussion to #3962.

**Closed by kalefranz** 2017-10-05 18:28 UTC

**Comment by andreamarto** [comment] 2018-03-26 14:39
this is my error 
can you help me?


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "offwhite.py", line 55, in run
    self.re = self.s.post(url, data=self.data, proxies=self.proxy)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/util/connection.py", line 51, in create_connection
    if host.startswith('['):
AttributeError: 'NoneType' object has no attribute 'startswith'
