### ISSUE TITLE
Cannot set config to an empty list

### ISSUE THREAD

**Issue by minrk** [conda/conda#13642] opened 2024-03-01 08:55 UTC
### What happened?

In answer to a question about avoiding upgrades to ca-certificates, etc., governed by `aggressive_update_packages`, I wanted to suggest a `conda config --set` command to set it to an empty list.

But it appears that `conda config` doesn't have a way to set config values to empty lists, because e.g. attempts to `conda config --set aggressive_update_packages` fail with:

```
CondaValueError: Key 'aggressive_update_packages' is not a known primitive parameter.
```

An empty list _can_ be created by adding and then removing a single key:

```
conda config --add aggressive_update_packages x
conda config --remove aggressive_update_packages x
```

or writing directly to the file:

```bash
echo 'aggressive_update_packages: []' >> ~/.condarc
```

but both of these assume that there is no config set previously. There is no way that I can find to explicitly set any config value to an empty list, regardless of the initial config state.

I realize this is an uncommon situation, since it only really makes sense for list config values where the default is not empty that also make sense to _be_ empty, which is a rather small set.

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
mamba version : 1.5.6
     active environment : None
            shell level : 0
       user config file : /Users/minrk/.condarc
 populated config files : /Users/minrk/conda/.condarc
                          /Users/minrk/.condarc
          conda version : 23.11.0
    conda-build version : 3.28.4
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=23.11.0=0
                          __osx=14.3.1=0
                          __unix=0=0
       base environment : /Users/minrk/conda  (writable)
      conda av data dir : /Users/minrk/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/minrk/conda/pkgs
                          /Users/minrk/.conda/pkgs
       envs directories : /Users/minrk/conda/envs
                          /Users/minrk/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Darwin/23.3.0 OSX/14.3.1 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.6
                UID:GID : 501:20
             netrc file : /Users/minrk/.netrc
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> /Users/minrk/conda/.condarc <==
channels:
  - conda-forge

==> /Users/minrk/.condarc <==
safety_checks: enabled
local_repodata_ttl: 86400
channels:
  - conda-forge
show_channel_urls: True
report_errors: False
solver: libmamba
```

</details>

**Comment by travishathaway** [comment] 2024-03-01 11:19
Hi @minrk,

Thanks for filing this. I have switched this to being a feature request because I think it's better suited as such. Please let me know if you disagree.

I think the best way to implement this via the CLI API would be by adding a `--set-default` option to the `conda config` command. If the parameter in question has a default, it would use that, otherwise it would choose an empty value. In the case of a sequence parameter, that would be an empty list.

I am curious to hear other's thoughts about how best to implement this.

**Comment by kenodegard** [comment] 2024-03-04 14:58
`--set-default` is interesting but I worry it would be too confusing. Is the default what we have hardcoded within conda? Or is the default what sys admins have set as the value in, e.g., `/etc/conda/condarc`? And what if the default is a non-empty list?

I'd say what we actually want is `conda config --clear` so this would be a duplicate of https://github.com/conda/conda/issues/7617.

**Closed as not planned by kenodegard** 2024-03-04 14:58 UTC
Labels: type::feature, source::community, plugins::config, locked, duplicate
