### ISSUE TITLE
`conda create` fails on network drive

### ISSUE THREAD

**Issue by arnold-jr** [conda/conda#5251] opened 2017-05-08 15:12 UTC
Trying to create a new environment on a GPFS mounted drive, and I run into 13 Permission Denied. Works as expected when installing to a local drive. 

```
Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /opt/easybuild/software/Core/Anaconda3/4.3.1  (writable)
    default environment : /opt/easybuild/software/Core/Anaconda3/4.3.1
       envs directories : /opt/easybuild/software/Core/Anaconda3/4.3.1/envs
                          /home/fido/.conda/envs
          package cache : /opt/easybuild/software/Core/Anaconda3/4.3.1/pkgs
                          /home/fido/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Linux/2.6.32-642.6.2.el6.x86_64 CentOS/6.8 glibc/2.12
                UID:GID : 30100:36014



`$ /opt/easybuild/software/Core/Anaconda3/4.3.1/bin/conda create -v -p /gpfs22/home/fido/.conda/envs/baz python=3.6`




    Traceback (most recent call last):
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/core/link.py", line 324, in _execute_actions
        action.execute()
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/core/path_actions.py", line 270, in execute
        super(PrefixReplaceLinkAction, self).execute()
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/core/path_actions.py", line 225, in execute
        force=context.force)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 233, in create_link
        _do_copy(src, dst)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 207, in _do_copy
        shutil.copy2(src, dst)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/shutil.py", line 252, in copy2
        copystat(src, dst, follow_symlinks=follow_symlinks)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/shutil.py", line 219, in copystat
        _copyxattr(src, dst, follow_symlinks=follow)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/shutil.py", line 159, in _copyxattr
        os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
    PermissionError: [Errno 13] Permission denied: '/gpfs22/home/fido/.conda/envs/baz/bin/c_rehash'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/core/link.py", line 279, in execute
        pkg_data, actions)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/core/link.py", line 342, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/gpfs22/home/fido/.conda/envs/baz/bin/c_rehash'
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/plan.py", line 800, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/opt/easybuild/software/Core/Anaconda3/4.3.1/lib/python3.6/site-packages/conda/core/link.py", line 295, in execute
        rollback_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/gpfs22/home/fido/.conda/envs/baz/bin/c_rehash'
```

**Comment by kalefranz** [comment] 2017-05-08 15:25
duplicate of #4911

**Closed by kalefranz** 2017-05-08 15:25 UTC
