### ISSUE TITLE
Unicode error with qt 4.8 package install from default repos

### ISSUE THREAD

**Issue by matmel** [conda/conda#4612] opened 2017-02-13 00:30 UTC
Hello, on windows 10, I had a problem installing qt package.

I installed the latest miniconda followed by `conda update conda`. Now my conda is:

    > conda info
    Current conda install:

                   platform : win-64
              conda version : 4.3.11
           conda is private : False
          conda-env version : 4.3.11
        conda-build version : not installed
             python version : 3.5.2.final.0
           requests version : 2.12.4
           root environment : C:\Users\Matthieu\Miniconda3  (writable)
        default environment : C:\Users\Matthieu\Miniconda3
           envs directories : C:\Users\Matthieu\Miniconda3\envs
                              C:\Users\Matthieu\AppData\Local\conda\conda\envs
                              C:\Users\Matthieu\.conda\envs
              package cache : C:\Users\Matthieu\Miniconda3\pkgs
                              C:\Users\Matthieu\AppData\Local\conda\conda\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/r/win-64
                              https://repo.continuum.io/pkgs/r/noarch
                              https://repo.continuum.io/pkgs/pro/win-64
                              https://repo.continuum.io/pkgs/pro/noarch
                              https://repo.continuum.io/pkgs/msys2/win-64
                              https://repo.continuum.io/pkgs/msys2/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.11 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

Here is the error I get if I try to install pyqt 4:

    >conda create -n testqt pyqt=4*
    Fetching package metadata ...........
    Solving package specifications: .
    
    Package plan for installation in environment C:\Users\Matthieu\Miniconda3\envs\testqt:
    
    The following NEW packages will be INSTALLED:
    
        jpeg:           8d-vc14_2     [vc14]
        libpng:         1.6.27-vc14_0 [vc14]
        libtiff:        4.0.6-vc14_2  [vc14]
        openssl:        1.0.2k-vc14_0 [vc14]
        pip:            9.0.1-py35_1
        pyqt:           4.11.4-py35_7
        python:         3.5.2-0
        qt:             4.8.7-vc14_9  [vc14]
        setuptools:     27.2.0-py35_1
        sip:            4.18-py35_0
        vs2015_runtime: 14.0.25123-0
        wheel:          0.29.0-py35_0
        zlib:           1.2.8-vc14_3  [vc14]
    
    Proceed ([y]/n)? y
    
    ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'defaults::qt-4.8.7-vc14_9'.
    UnicodeDecodeError('utf-8', b'        1 fichier(s) copi\x82(s).\r\n', 25, 26, 'invalid start byte')
    Attempting to roll back.
    
    UnicodeDecodeError('utf-8', b'        1 fichier(s) copi\x82(s).\r\n', 25, 26, 'invalid start byte')

Here is the content of my root environment:

    >conda list
    # packages in environment at C:\Users\Matthieu\Miniconda3:
    #
    cffi                      1.9.1                    py35_0
    conda                     4.3.11                   py35_0
    conda-env                 2.6.0                         0
    console_shortcut          0.1.1                    py35_1
    cryptography              1.7.1                    py35_0
    idna                      2.2                      py35_0
    menuinst                  1.4.2                    py35_1
    openssl                   1.0.2k                   vc14_0  [vc14]
    pip                       8.1.2                    py35_0
    pyasn1                    0.1.9                    py35_0
    pycosat                   0.6.1                    py35_1
    pycparser                 2.17                     py35_0
    pycrypto                  2.6.1                    py35_4
    pyopenssl                 16.2.0                   py35_0
    python                    3.5.2                         0
    pywin32                   220                      py35_1
    requests                  2.12.4                   py35_0
    ruamel_yaml               0.11.14                  py35_0
    setuptools                27.2.0                   py35_1
    six                       1.10.0                   py35_0
    vs2015_runtime            14.0.25123                    0
    wheel                     0.29.0                   py35_0

The workaround I found is to go back to conda 4.2.* and now it works:

    >conda env remove -n testqt
    
    Remove all packages in environment C:\Users\Matthieu\Miniconda3\envs\testqt:
    
    Proceed ([y]/n)? y

    >conda install conda=4.2*
    Fetching package metadata ...........
    Solving package specifications: .
    
    Package plan for installation in environment C:\Users\Matthieu\Miniconda3:
    
    The following packages will be DOWNGRADED due to dependency conflicts:
    
        conda: 4.3.11-py35_0 --> 4.2.16-py35_0
    
    Proceed ([y]/n)? y
    
    >conda create -n testqt pyqt=4*
    Fetching package metadata .........
    Solving package specifications: ..........
    
    Package plan for installation in environment C:\Users\Matthieu\Miniconda3\envs\testqt:
    
    The following NEW packages will be INSTALLED:
    
        jpeg:           8d-vc14_2     [vc14]
        libpng:         1.6.27-vc14_0 [vc14]
        libtiff:        4.0.6-vc14_2  [vc14]
        openssl:        1.0.2k-vc14_0 [vc14]
        pip:            9.0.1-py35_1
        pyqt:           4.11.4-py35_7
        python:         3.5.2-0
        qt:             4.8.7-vc14_9  [vc14]
        setuptools:     27.2.0-py35_1
        sip:            4.18-py35_0
        vs2015_runtime: 14.0.25123-0
        wheel:          0.29.0-py35_0
        zlib:           1.2.8-vc14_3  [vc14]
    
    Proceed ([y]/n)? y
    
    Linking packages ...
            1 fichier(s) copié(s).###################################        |  84%
    [      COMPLETE      ]|##################################################| 100%
    #
    # To activate this environment, use:
    # > activate testqt
    #
    # To deactivate this environment, use:
    # > deactivate testqt
    #
    # * for power-users using bash, you must source
    #

**Comment by matmel** [comment] 2017-02-13 00:42
Probably a duplicate of #4567 actually which has already a fix in development version.

Feel free to close the issue, sorry for the noise.

**Comment by kalefranz** [comment] 2017-02-14 05:57
Yes, I believe this is a duplicate of #4567.  The fix will be in the next patch release coming this week.

**Comment by kalefranz** [comment] 2017-02-15 04:35
Conda 4.3.12 that includes a patch for this issue has been released to conda canary.  Feel free to test.

    conda config --add channels conda-canary
    conda update conda

**Closed by kalefranz** 2017-02-15 04:35 UTC
