### ISSUE TITLE
Installing a package with conda-forge last in channels list, forces reinstall and downgrade of already installed packages

### ISSUE THREAD

**Issue by garu57** [conda/conda#7261] opened 2018-05-06 14:31 UTC
```
     active environment : base
    active env location : C:\Programs\Anaconda3
            shell level : 1
       user config file : C:\Users\ggaru\.condarc
 populated config files : C:\Users\ggaru\.condarc
          conda version : 4.5.2
    conda-build version : 3.10.1
         python version : 3.6.5.final.0
       base environment : C:\Programs\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Programs\Anaconda3\pkgs
                          C:\Users\ggaru\AppData\Local\conda\conda\pkgs
       envs directories : C:\Programs\Anaconda3\envs
                          C:\Users\ggaru\AppData\Local\conda\conda\envs
                          C:\Users\ggaru\.conda\envs
               platform : win-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```
`.condarc`
```
channels:
  - defaults
  - conda-forge
```

Doc tells:

> By default, conda now prefers packages from a higher priority channel over any version from a lower priority channel. Therefore, you can now safely put channels at the bottom of your channel list to provide additional packages that are not in the default channels, and still be confident that these channels will not override the core package set.

but trying to install `doc8` from `conda-forge`, `conda` wants to reinstall a number of already installed packages and downgrade a number of others.
```
(base) C:\Users\ggaru>conda install --dry-run  doc8
Solving environment: done

## Package Plan ##

  environment location: C:\Programs\Anaconda3

  added / updated specs:
    - doc8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libxslt-1.1.32             |           vc14_0         456 KB  conda-forge
    libtiff-4.0.9              |           vc14_0         616 KB  conda-forge
    restructuredtext_lint-1.1.3|             py_0          13 KB  conda-forge
    curl-7.59.0                |           vc14_1         362 KB  conda-forge
    libpng-1.6.34              |           vc14_0         547 KB  conda-forge
    libiconv-1.14              |           vc14_4         670 KB  conda-forge
    lzo-2.10                   |           vc14_0         154 KB  conda-forge
    pbr-4.0.2                  |           py36_0         132 KB
    bzip2-1.0.6                |           vc14_1         144 KB  conda-forge
    zlib-1.2.11                |           vc14_0         119 KB  conda-forge
    freetype-2.8.1             |           vc14_0         469 KB  conda-forge
    tk-8.6.7                   |           vc14_0         3.5 MB  conda-forge
    proj4-4.9.3                |           vc14_5         3.2 MB  conda-forge
    winpty-0.4.3               |           vc14_2         126 KB  conda-forge
    lxml-4.1.1                 |   py36he0adb16_0         1.1 MB
    stevedore-1.28.0           |             py_0          23 KB  conda-forge
    pyqt-5.6.0                 |           py36_2         4.5 MB
    libxml2-2.9.5              |           vc14_1         3.2 MB  conda-forge
    geos-3.6.2                 |           vc14_1         4.1 MB  conda-forge
    zeromq-4.2.5               |           vc14_1         9.6 MB  conda-forge
    krb5-1.14.6                |           vc14_0         767 KB  conda-forge
    libsodium-1.0.16           |           vc14_0         582 KB  conda-forge
    jpeg-9b                    |           vc14_2         314 KB  conda-forge
    snappy-1.1.7               |           vc14_1          80 KB  conda-forge
    qt-5.6.2                   |           vc14_1        55.6 MB  conda-forge
    yaml-0.1.7                 |           vc14_0         103 KB  conda-forge
    sqlite-3.22.0              |           vc14_0         907 KB  conda-forge
    doc8-0.8.0                 |           py36_0          70 KB  conda-forge
    libssh2-1.8.0              |           vc14_2         184 KB  conda-forge
    icu-58.2                   |           vc14_0        21.8 MB  conda-forge
    hdf5-1.10.1                |           vc14_2        17.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       131.1 MB

The following NEW packages will be INSTALLED:

    doc8:                  0.8.0-py36_0         conda-forge
    krb5:                  1.14.6-vc14_0        conda-forge [vc14]
    pbr:                   4.0.2-py36_0
    restructuredtext_lint: 1.1.3-py_0           conda-forge
    stevedore:             1.28.0-py_0          conda-forge

The following packages will be UPDATED:

    curl:                  7.59.0-h7602738_0                --> 7.59.0-vc14_1        conda-forge [vc14]
    freetype:              2.8-h51f8f2c_1                   --> 2.8.1-vc14_0         conda-forge [vc14]
    hdf5:                  1.10.1-h98b8871_1                --> 1.10.1-vc14_2        conda-forge [vc14]
    jpeg:                  9b-hb83a4c4_2                    --> 9b-vc14_2            conda-forge [vc14]
    libpng:                1.6.34-h79bbb47_0                --> 1.6.34-vc14_0        conda-forge [vc14]
    libsodium:             1.0.16-h9d3ae62_0                --> 1.0.16-vc14_0        conda-forge [vc14]
    libtiff:               4.0.9-h0f13578_0                 --> 4.0.9-vc14_0         conda-forge [vc14]
    libxslt:               1.1.32-hf6f1972_0                --> 1.1.32-vc14_0        conda-forge [vc14]
    zeromq:                4.2.5-hc6251cf_0                 --> 4.2.5-vc14_1         conda-forge [vc14]

The following packages will be DOWNGRADED:

    bzip2:                 1.0.6-hbe05fcf_4                 --> 1.0.6-vc14_1         conda-forge [vc14]
    geos:                  3.6.2-h9ef7328_2                 --> 3.6.2-vc14_1         conda-forge [vc14]
    icu:                   58.2-ha66f8fd_1                  --> 58.2-vc14_0          conda-forge [vc14]
    libiconv:              1.15-h1df5818_7                  --> 1.14-vc14_4          conda-forge [vc14]
    libssh2:               1.8.0-hd619d38_4                 --> 1.8.0-vc14_2         conda-forge [vc14]
    libxml2:               2.9.8-hc33b523_0                 --> 2.9.5-vc14_1         conda-forge [vc14]
    lxml:                  4.2.1-py36heafd4d3_0             --> 4.1.1-py36he0adb16_0
    lzo:                   2.10-h6df0209_2                  --> 2.10-vc14_0          conda-forge [vc14]
    matplotlib:            2.2.2-py36h153e9ff_1             --> 2.2.2-py36h153e9ff_0
    proj4:                 4.9.3-hcf24537_7                 --> 4.9.3-vc14_5         conda-forge [vc14]
    pyqt:                  5.9.2-py36h1aa27d4_0             --> 5.6.0-py36_2
    qt:                    5.9.5-vc14he4a7d60_0             --> 5.6.2-vc14_1         conda-forge [vc14]
    snappy:                1.1.7-h777316e_3                 --> 1.1.7-vc14_1         conda-forge [vc14]
    sqlite:                3.23.1-h35aae40_0                --> 3.22.0-vc14_0        conda-forge [vc14]
    tk:                    8.6.7-hcb92d03_3                 --> 8.6.7-vc14_0         conda-forge [vc14]
    winpty:                0.4.3-4                          --> 0.4.3-vc14_2         conda-forge [vc14]
    yaml:                  0.1.7-hc54c509_2                 --> 0.1.7-vc14_0         conda-forge [vc14]
    zlib:                  1.2.11-h8395fce_2                --> 1.2.11-vc14_0        conda-forge [vc14]
```

I verified that this is not specifically linked to `doc8` package. Whenever i append `conda-forge` to the channels list, whichever package i try to install, even if it's from `pkgs/main`, `conda` wants to screw up my installation with the previous list of packages from `conda-forge`.

**Comment by garu57** [comment] 2018-05-07 08:54
I verified also the following.
Doc tells

> Conda attempts to install the newest versions of  the  requested packages.  To  accomplish this, it may update some packages that are already installed, or install additional packages.  To  prevent  existing packages from updating, use the --no-update-deps option.

and

> --no-update-dependencies, --no-update-deps
              Don't  update  dependencies. Overrides the value given by `conda config --show update_deps`.

But `conda config --show update_deps`  returns
```
ArgumentError: Invalid configuration parameters:
  - update_deps
```
and both `--no-update-dependencies` and `--no-update-deps` are accepted (i mean no error is returned), but happily ignored.

As a matter of fact, i need to install a couple of packages from `conda-forge` but i can't without resorting to one of these options

- let `conda` overwrite and downgrade system packages, but i have no idea of the consequences for future updates
- use  `pip`, but again, being rather new to `conda`, it's not clear to me if mixing `conda` packages and `pip` could become a problem for future installation mainenance.

Could please someone give any hint on how to exit from this impasse?
Thanks.

**Comment by kalefranz** [comment] 2018-05-07 17:40
There's a feature interaction here, with conda-forge still using the vc14 feature, while defaults doesn't.  I think that's the root cause of what's going on.

Oh looks like @mbargull also already identified this as a feature issue.

**Comment by kalefranz** [comment] 2018-05-07 17:43
I agree this is suboptimal behavior.  I don't know if we want conda-forge to fix it at the packaging level, or if we want to fix it at the conda code level.  If the first, presumably conda-forge would NOT be rebuilding all of these packages.  Seems completely infeasible.  So the project there is to give conda-forge and anaconda.org users in general a way to update metadata.  That work is ongoing.

**Comment by garu57** [comment] 2018-05-08 11:42
Not sure to follow completely your reasoning about features and metadata. I'm not yet so in depth with conda.
However from your tone I guess it won't be neither an easy solution nor a near one, so in the meanwhile I'm thinking to install what i need in user site using `pip --user` so that i can have the packages i need without corrupting Anaconda installation. Do you see any problem with this?
Thanks

**Comment by kalefranz** [comment] 2018-05-08 17:02
Yeah `pip install --user` might be a good option for now.  Note that we're discussing disabling (by default) a conda-installed python interpreter digging into `~/.local`.  https://github.com/conda/conda/issues/7173

Fine for now though.

**Comment by michaelaye** [comment] 2018-05-15 05:35
This issue has wide-ranging and subtle implications.
Installing a package from conda-forge that depends on an already installed package from conda-forge suddenly wants to convert these dependencies back to the defaults channel, and this with conda-forge having the higher priority in .condarc (conda version 4.5.3).
How can I fix this mess? I just want to install another package from conda-forge like I have been doing successfully for over a year now, with conda-forge having the higher priority. :/

**Comment by trenst** [comment] 2018-06-12 16:22
I'm not sure this error is due to conda-forge features as @kalefranz states.   I just filed issue [7410](https://github.com/conda/conda/issues/7410).   I'm getting this same behavior when running <code>conda update conda</code> even though no conda-forge packages are installed.  It seems like a bug in channel priority to me.

**Comment by mbargull** [comment] 2018-07-04 15:05
>  I'm getting this same behavior when running `conda update conda` even though no conda-forge packages are installed. It seems like a bug in channel priority to me.

The problem is still `features`: The packages `vc` is installed and has `track_features: vc14`. Since packages from `defaults` do not have `features: vc14` anymore, the packages from `conda-forge` with `features: vc14` will be preferred.
@msarahan: Given we have the saner dependency-based `vc` scheme by now, are there any reasons to have `track_features: vc*` in the `vc` (and corresponding compiler) packages (added in https://github.com/AnacondaRecipes/aggregate/pull/4) anymore?

**Comment by sdmcclure** [comment] 2018-07-10 21:18
Hi All, I encountered this issue but unfortunately proceeded with the updates. Now many of my packages have been assigned to the conda-forge channel. When I try to update conda, or update these packages with conda, I get an error.

What is the best way to repair this situation?

**Comment by mbargull** [comment] 2018-07-13 02:20
@sdmcclure, maybe remove `conda-forge` from the channel list and then try `conda update --all`? But please open up another issue for this and provide all the information asked for in the issue template. Without that information we can't really help you any further.

**Comment by sdmcclure** [comment] 2018-07-13 15:01
@mbargull I appologize, Github is new to me so I'm still learning basic ins and outs of issue logging.

I was able to fix the conda error. There were two things that happened: 
1. Starting with default channels, I installed a package from conda-forge using `conda install -c conda-forge Miktex`. This caused upgrades or downgrades of several packages from the conda-forge channel, which I believe is similar the original issue posted, including upgrading conda to version 4.5.6.
2. The errors I was getting with conda was an issue with conda 4.5.6 and I was able to fix it and downgrade to conda in the default channel using the advice found here: [https://github.com/conda/conda/issues/7524](url)

I'm not sure if this is additional info is helpfull or redundant clutter. Please advise whether it would be more helpful to keep, delete, or log a seperate issue.

Here's the info on my environment:
```
C:\>conda info

     active environment : None
       user config file : C:\Users\smcclure\.condarc
 populated config files : C:\Users\smcclure\.condarc
          conda version : 4.5.5
    conda-build version : 1.20.0
         python version : 3.5.1.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\smcclure\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\smcclure\AppData\Local\conda\conda\envs
                          C:\Users\smcclure\.conda\envs
               platform : win-64
             user-agent : conda/4.5.5 requests/2.12.4 CPython/3.5.1 Windows/7 Wi
ndows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by mbargull** [comment] 2018-07-13 15:50
> please open up another issue for this and provide all the information asked for in the issue template. 

> I apologize, Github is new to me so I'm still learning basic ins and outs of issue logging.

Just go to https://github.com/conda/conda/issues and click on the big green "New issue" button and follow the instructions provided in the template that comes up.

> Please advise whether it would be more helpful to keep these posts, delete, or log a separate issue.

A separate issue would be most helpful.

**Comment by sdmcclure** [comment] 2018-07-13 16:48
@mbargull Thanks, I've deleted my previous comments and logged a separate issue.

**Comment by BrenBarn** [comment] 2018-12-27 00:50
What is the status of this?  I find myself running into this issue virtually every time I try to install anything from conda-forge.  Just today, to test it, I created a fresh environment with `conda create -n testdeps python=3.6`.  I then installed one package and its dependencies using `conda install jupyter`.

I then tried `conda install -c conda-forge jupyter_contrib_nbextensions` and I get this:

```
Solving environment: done

## Package Plan ##

  environment location: C:\FakeProgs\Anaconda3\envs\testdeps

  added / updated specs:
    - jupyter_contrib_nbextensions


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libsodium-1.0.16           |           vc14_0         582 KB  conda-forge
    sqlite-3.22.0              |           vc14_0         907 KB  conda-forge
    libxml2-2.9.5              |           vc14_1         3.2 MB  conda-forge
    ca-certificates-2018.11.29 |       ha4d7672_0         179 KB  conda-forge
    pyyaml-3.13                |py36hfa6e2cd_1001         147 KB  conda-forge
    jupyter_highlight_selected_word-0.2.0|        py36_1000          13 KB  conda-forge
    jupyter_contrib_core-0.3.3 |             py_2          15 KB  conda-forge
    qt-5.6.2                   |           vc14_1        55.6 MB  conda-forge
    lxml-4.2.3                 |   py36heafd4d3_0         1.2 MB  conda-forge
    libxslt-1.1.32             |           vc14_0         456 KB  conda-forge
    jupyter_latex_envs-1.4.4   |        py36_1000         752 KB  conda-forge
    jupyter_nbextensions_configurator-0.4.0|        py36_1000         487 KB  conda-forge
    python-3.6.6               |       he025d50_0        21.4 MB  conda-forge
    markupsafe-1.1.0           |py36hfa6e2cd_1000          27 KB  conda-forge
    jupyter_contrib_nbextensions-0.5.0|        py36_1000        19.4 MB  conda-forge
    mistune-0.8.4              |py36hfa6e2cd_1000          53 KB  conda-forge
    certifi-2018.11.29         |        py36_1000         145 KB  conda-forge
    openssl-1.0.2p             |    hfa6e2cd_1001         5.4 MB  conda-forge
    zeromq-4.2.5               |           vc14_2         9.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       119.4 MB

The following NEW packages will be INSTALLED:

    jupyter_contrib_core:              0.3.3-py_2             conda-forge
    jupyter_contrib_nbextensions:      0.5.0-py36_1000        conda-forge
    jupyter_highlight_selected_word:   0.2.0-py36_1000        conda-forge
    jupyter_latex_envs:                1.4.4-py36_1000        conda-forge
    jupyter_nbextensions_configurator: 0.4.0-py36_1000        conda-forge
    libiconv:                          1.14-vc14_4            conda-forge [vc14]
    libxml2:                           2.9.5-vc14_1           conda-forge [vc14]
    libxslt:                           1.1.32-vc14_0          conda-forge [vc14]
    lxml:                              4.2.3-py36heafd4d3_0   conda-forge
    pyyaml:                            3.13-py36hfa6e2cd_1001 conda-forge
    yaml:                              0.1.7-vc14_0           conda-forge [vc14]

The following packages will be UPDATED:

    ca-certificates:                   2018.03.07-0                       --> 2018.11.29-ha4d7672_0   conda-forge
    certifi:                           2018.11.29-py36_0                  --> 2018.11.29-py36_1000    conda-forge
    jpeg:                              9b-hb83a4c4_2                      --> 9b-vc14_2               conda-forge [vc14]
    libsodium:                         1.0.16-h9d3ae62_0                  --> 1.0.16-vc14_0           conda-forge [vc14]
    markupsafe:                        1.1.0-py36he774522_0               --> 1.1.0-py36hfa6e2cd_1000 conda-forge
    mistune:                           0.8.4-py36he774522_0               --> 0.8.4-py36hfa6e2cd_1000 conda-forge
    zeromq:                            4.2.5-he025d50_1                   --> 4.2.5-vc14_2            conda-forge [vc14]

The following packages will be DOWNGRADED:

    icu:                               58.2-ha66f8fd_1                    --> 58.2-vc14_0             conda-forge [vc14]
    libpng:                            1.6.35-h2a8f88b_0                  --> 1.6.34-vc14_0           conda-forge [vc14]
    openssl:                           1.1.1a-he774522_0                  --> 1.0.2p-hfa6e2cd_1001    conda-forge
    pyqt:                              5.9.2-py36h6538335_2               --> 5.6.0-py36_2
    python:                            3.6.7-h9f7ef89_2                   --> 3.6.6-he025d50_0        conda-forge
    qt:                                5.9.7-vc14h73c81de_0               --> 5.6.2-vc14_1            conda-forge [vc14]
    sqlite:                            3.26.0-he774522_0                  --> 3.22.0-vc14_0           conda-forge [vc14]
    vc:                                14.1-h0510ff6_4                    --> 14-0                    conda-forge
    zlib:                              1.2.11-h62dcd97_3                  --> 1.2.11-vc14_0           conda-forge [vc14]
```

Notice that all of the "upgrades" (except `ca-certificates`) are not actually upgrades at all; all the "new" versions have the same version number, but now they're different builds coming from conda-forge instead of defaults.  The same is true of some of the downgrades, and the rest appear to be miniscule changes (e.g., downgrading libpng from 1.6.35 to 1.6.34) which I suspect are not really necessary for all packages to actually work.

Is there any solution in sight for this?

**Comment by michaelaye** [comment] 2018-12-27 02:07
@BrenBarn First, I wouldn't recommend mixing conda-forge and packages, at least I am trying to avoid it using best efforts, sometimes a math library is only available on the `defaults` channel, but that's about it, otherwise I'm exclusively using conda-forge.

When you execute `conda create -n testdeps python=3.6` you will create a new env based on the `defaults` channel, unless you have added `conda-forge` to your ~/.condarc as the top priority.
This command shows you all configured sources:

`conda config --show-sources`

mine has this:

```bash
==> /Users/klay6683/miniconda3/.condarc <==
pinned_packages: []
channels:
  - defaults

==> /Users/klay6683/.condarc <==
auto_update_conda: True
pinned_packages:
  - notebook=5.6
channels:
  - defaults
report_errors: True
anaconda_upload: True

==> /Users/klay6683/miniconda3/envs/py37/.condarc <==
pinned_packages:
  - conda-forge::opencv
  - conda-forge::gdal
  - conda-forge::numpy
channels:
  - conda-forge
  - defaults
```

Now, you can either exclusively work on conda-forge by doing:

`conda config --add channels conda-forge`
but I dislike that for my base environment, being scared that the conda application itself uses that for its functionality, so I leave the `base` env untouched and define my channels per environment. The way to do that is like so:

```bash
conda create -n testdeps python=3.6 -c conda-forge
conda activate testdeps
conda config --env --add channels conda-forge
```

This solves half of the problems you have described above.
Now, because of the dysfunctional (or inconsistently working --- between different channels ---) feature of conda called 'feature tracking', conda likes to mess up things by starting to mix default and conda-forge packages. The trick to avoid this is to pin the packages that cause these mixings to conda-forge like so in my example, where I pin numpy, gdal and opencv to conda-forge:

```bash
conda config --env --add pinned_packages conda-forge::numpy
conda config --env --add pinned_packages conda-forge::opencv
conda config --env --add pinned_packages conda-forge::gdal
```

The advantage of doing this by environment is obviously, that I can have different channel priorities for different environments; a highly under-advertised feature of conda.

Note that I am currently pinning globally (i.e. for all my envs) notebook to version 5.6 b/c of an incompatibility for notebook extensions, but the fix is about to be pushed to conda, I believe, so won't be necessary anymore, shortly.

**Comment by BrenBarn** [comment] 2018-12-27 06:59
@michaelaye That just seems strange.  What is the use of the defaults channel (and why is it the default) if the best solution is to never use it at all?

I thought the way it was supposed to work is that you install stuff from defaults, and then if you want some experimental or third-party thing that's only available in conda-forge, you can install that from conda-forge.  And yeah, sure, if that experimental thing requires newer versions of stuff that's not available in defaults, it can install newer versions of those dependencies from conda-forge.  But I don't get why installing one package from conda-forge requires everything to switch to conda-forge, or to do these kinds of fiddly tiny downgrades.

In the example above, I already have libsodium 1.06 and vc14 installed, but now it wants to switch to. . . libsodium1.06 with vc14.  That's what's already installed!  Why does it need to make any change?

What I want is to be able to install any package without worrying about which channel it came from, and have that install or upgrade any *needed* dependencies, while not changing anything that doesn't need to be changed.  I don't want every package installation to keep shuffling things between defaults and conda-forge, especially when it's not actually changing any versions.

**Comment by michaelaye** [comment] 2018-12-28 00:19
I didn't say to use it at all, but ppl in general recommend to not mix them. You could have an env based on the defaults channel, sure.
But I know for a fact when I mix packages regarding the gdal package, that things break due to the different ways the gdal package is organized in the defaults and `conda-forge` channel.

I believe your requirement on things working exactly the same for different channels is too high. Channels are and always be organized by very different people with different ideas of packaging, a complicated fact of the Python world.
Anaconda,Inc. controls only the `defaults` channel, while `conda-forge` is a self-organized independent group (but I don't know if they have a charta or rules book).
And there are many other channels created by other entities, like NASA or USGS, providing conda packages.

I believe, conda is not able to distinguish between the different build identifiers used in the `defaults` channel and the `conda-forge` channel, creating these superfluous changes. My above described methods ensure that things are more stable, I leave it to Anaconda employees to explain why/how things work/do not work. Note that I'm just a conda "power"-user that often has a hard time explaining to colleagues the miraculous ways of Python packages. 
Amazingly, despite all its pitfalls, I have not found a better Python package handler than `conda`. There is no faster way than using conda for the complete wiping and reinstallation of **ALL** my Python environments, using a few simple scripts that combine the required commands.

**Comment by BrenBarn** [comment] 2021-11-21 04:40
The issue is not resolved.  The same procedure I described three years ago still doesn't do the right thing.  To clarify:

Step 1: `conda create -n testdeps python=3.6`
Step 2: `conda activate testdeps`
Step 3: `conda install jupyter`
Step 4: `conda install -c conda-forge jupyter_contrib_nbextensions`

Result: a gazillion "upgrades" switching to the same versions of already-installed packages, but now getting them from `conda-forge`.

Expected behavior: conda should *never* switch a package to the same version on a different channel.  conda should *never* switch a package to a different channel at all, unless either the user explicitly asks for that specific package to be taken from that channel, or no version of the package satisfying dependencies of packages the user explicitly asked for exists on the already-used channel.  Or, in short, channels should not be part of what the user needs to think about to suss out dependencies.  If you have PackageX version a.b.c it should not matter what channel is from; that version of that package should satisfy any dependency of any package on any channel as long as PackageX version a.b.c satisifies the dependency.

**Comment by kenodegard** [comment] 2021-11-22 22:45
@BrenBarn for your example you can get around this by specifying the channel for the package itself:

```bash
conda install conda-forge::jupyter_contrib_nbextensions
```

**Comment by kenodegard** [comment] 2022-03-24 17:24
The behavior described here is expected behavior for `conda`. When adding a new channel to search (e.g. `conda install -c conda-forge ...`) it's appropriate for the solver to prioritize packages from that channel even if the dependency is already installed. This is due to the assumption and understanding that the package from one channel **is not and should not** be treated the same as the same-named package from another channel (since they could've been packaged differently in incompatible ways). This is simply how `conda` was and has been envisioned from the start.

If you do wish to circumvent this default behavior you can explicitly specify the channel for the package itself using the `<channel>::<package>` syntax:

```bash
$ conda create -n testdeps python=3.6
$ conda activate testdeps
$ conda install jupyter conda-forge::jupyter_contrib_nbextensions
```

Or as one command:

```bash
$ conda create -n testdeps python=3.6 jupyter conda-forge::jupyter_contrib_nbextensions
$ conda activate testdeps
```

**Closed by kenodegard** 2022-03-24 17:24 UTC
Labels: type::feature, solver, source::community, pending::discussion
