### ISSUE TITLE
traceback error when listing packages

### ISSUE THREAD

**Issue by emilyhoughkovacs** [conda/conda#2122] opened 2016-02-23 16:55 UTC
<p>I think this problem may be due to multiple installations of pip on my machine.</p>
===

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 3.19.3
  conda-build version : 1.14.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/emilyhoughkovacs/anaconda  (writable)
  default environment : /Users/emilyhoughkovacs/anaconda
     envs directories : /Users/emilyhoughkovacs/anaconda/envs

====
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/emilyhoughkovacs/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 254, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/Users/emilyhoughkovacs/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Users/emilyhoughkovacs/anaconda/bin/python', '/Users/emilyhoughkovacs/anaconda/bin/pip', '-V']' returned non-zero exit status 1

**Comment by jakirkham** [comment] 2016-02-27 20:23
Well, that's fun. Any chance I could convince you to reinstall from scratch and see if the issue persists?

**Comment by kalefranz** [comment] 2016-03-10 21:17
What is the output of this command for you?

    /Users/emilyhoughkovacs/anaconda/bin/python /Users/emilyhoughkovacs/anaconda/bin/pip -V

**Comment by kalefranz** [comment] 2016-03-11 23:40
I'm guessing this is a duplicate of #2245.  @emilyhoughkovacs can you confirm?  If it's a different issue, I'll re-open it.

**Closed by kalefranz** 2016-03-11 23:40 UTC
