### ISSUE TITLE
channel_alias inconsistent docs; requires terminating `/` for windows

### ISSUE THREAD

**Issue by sandhujasmine** [conda/conda#3877] opened 2016-11-14 19:51 UTC
When pointing conda to an internal repository, the `.condarc` contains `channel_alias` key. This is inconsistently documented:
[channel_alias: https://your.repo/](http://conda.pydata.org/docs/config.html#set-a-channel-alias-channel-alias)
[channel_alias: https://your.repo/conda](http://conda.pydata.org/docs/install/central.html#channel-alias-channel-alias)

For this to work consistently with windows, it should be: `channel_alias: https://your.repo/conda/`
Below is the error we get because of the missing trailing `/`

```
>cat .condarc
channels:
  - anaconda
  - r-channel

channel_alias: https://ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com:8443/conda
ssl_verify: False

>conda update anaconda-navigator
Fetching package metadata .....CondaHTTPError: HTTP Error: Could not find URL: https://xxx-xxx-xxx-xxx.compute-1.amazonaws.com:8443/conda\anaconda/win-64/
```

conda likely does an os.path.join so it is platform specific, it ends up looking for incorrect URL:
`https://xxx-xxx-xxx-xxx.compute-1.amazonaws.com:8443/conda\anaconda/win-64/`

**Comment by kalefranz** [comment] 2016-11-14 20:04
It shouldn't. May be a bug though. 

What is the output of your `conda info`?

**Comment by electronwill** [comment] 2016-11-18 23:07
@sandhujasmine and @kalefranz it sounds like the expected behavior is that all three of https://your.repo/conda and https://your.repo/conda/ and https://your.repo/ will work, and the actual behavior is that only https://your.repo/conda/ works, possibly due to a bug. If no one objects, next week I will edit the docs to use https://your.repo/conda/ in all cases.

**Comment by kalefranz** [comment] 2016-11-22 23:08
Oh, I just saw this

> `https://xxx-xxx-xxx-xxx.compute-1.amazonaws.com:8443/conda\anaconda/win-64/`

Definitely a bug for conda on Windows.

**Comment by kalefranz** [comment] 2016-11-22 23:10
Somewhere I'm using `os.path.join()` when I should be using `conda.common.url.join()`.

**Comment by kerrywatson1** [comment] 2017-01-03 22:04
On the following pages which reference "channel alias":

http://conda.pydata.org/docs/config.html#set-a-channel-alias-channel-alias
http://conda.pydata.org/docs/install/central.html#channel-alias-channel-alias
http://conda-test.pydata.org/docs/config.html

Can we append this note:

NOTE: For Windows users, the slash (/) at the end of a URL is required. Example ``https://your.repo/conda/ ``

**Comment by kerrywatson1** [comment] 2017-01-17 17:48
https://github.com/conda/conda-docs/pull/403

**Comment by kerrywatson1** [comment] 2017-01-17 17:53
@electronwill please review and merge if okay, thanks.

**Comment by kalefranz** [comment] 2017-01-17 18:01
This looks like a bug to me.

**Comment by kalefranz** [comment] 2017-01-17 18:03
Oh. It is.  That's why there's history here.  I can fit it all in my brain 😜

**Comment by kalefranz** [comment] 2017-01-17 18:07
I'm seeing tests that should cover this, and those tests are passing.  Can we confirm that I haven't already fixed this in `4.2.15` and `4.3.4`?

**Comment by kerrywatson1** [comment] 2017-01-17 18:09
Feel free to close this if it's been fixed.



_______________________________

Kerry Watson
Documentation manager

[image: Continuum Analytics] <http://continuum.io>

**Comment by kalefranz** [comment] 2017-01-17 18:14
I'd like independent confirmation first.  Or I guess we can close and reopen.

**Closed by kalefranz** 2017-01-17 18:14 UTC
Labels: bug, cio
