### ISSUE TITLE
Error running "conda env remove" command

### ISSUE THREAD

**Issue by KBoehme** [conda/conda#2719] opened 2016-06-16 15:25 UTC
Getting the following issue when trying to remove any conda environment on my machine.

kevin@kevin-linux:~$ conda env remove --name flask
Fetching package metadata ...........

`Traceback (most recent call last):
  File "/home/kevin/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/home/kevin/miniconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/kevin/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/home/kevin/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: module 'conda.plan' has no attribute 'PREFIX'

kevin@kevin-linux:~$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.0
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/kevin/miniconda3  (writable)
  default environment : /home/kevin/miniconda3
     envs directories : /home/kevin/miniconda3/envs
        package cache : /home/kevin/miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
          config file : /home/kevin/.condarc
    is foreign system : False`

**Comment by mcg1969** [comment] 2016-06-16 15:36
Duplicate of https://github.com/conda/conda-env/issues/248; fixes already built! Thanks for the report!

**Closed by mcg1969** 2016-06-16 15:36 UTC
