### ISSUE TITLE
error happens when using conda install and conda create

### ISSUE THREAD

**Issue by serenanio** [conda/conda#6165] opened 2017-10-14 02:49 UTC
error happens like this ...do anyone know how to fix this problem?  I have tried to reinstall anaconda  but the problem still exists....  really appreciate it if you can tell me how to solve it !!! it has botherd me for a long time ....(crying)

(L:\Anaconda3) C:\Users\asus>conda create -n chloe python=3.5
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : L:\Anaconda3  (writable)
    default environment : L:\Anaconda3
       envs directories : L:\Anaconda3\envs
                          C:\Users\asus\AppData\Local\conda\conda\envs
                          C:\Users\asus\.conda\envs
          package cache : L:\Anaconda3\pkgs
                          C:\Users\asus\AppData\Local\conda\conda\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\asus\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False

`$ L:\Anaconda3\Scripts\conda-script.py create -n chloe python=3.5`

    Traceback (most recent call last):
      File "L:\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "L:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "L:\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "L:\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "L:\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "L:\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "L:\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "L:\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "L:\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "L:\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
        timeout=timeout
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

(root) C:\Users\asus>conda install tensorflow
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : L:\Anaconda3  (writable)
    default environment : L:\Anaconda3
       envs directories : L:\Anaconda3\envs
                          C:\Users\asus\AppData\Local\conda\conda\envs
                          C:\Users\asus\.conda\envs
          package cache : L:\Anaconda3\pkgs
                          C:\Users\asus\AppData\Local\conda\conda\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\asus\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False

`$ L:\Anaconda3\Scripts\conda-script.py install tensorflow`

    Traceback (most recent call last):
      File "L:\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "L:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "L:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "L:\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "L:\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "L:\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "L:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "L:\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "L:\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "L:\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "L:\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
        timeout=timeout
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "L:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kalefranz** [comment] 2017-10-14 03:37
Can you please provide details of your proxy configuration?  Do you have a `%HOME%\.netrc` file?  Do you have any `*_PROXY` environment variables set?  Do you have other proxies configured?

**Comment by serenanio** [comment] 2017-10-14 04:17
I have a file named:netrc.py in the path:Anaconda3\lib

(L:\Anaconda3) C:\Users\asus>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/msys2: https://repo.continuum.io/
  L:/Anaconda3/conda-bld: file:///
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro", "https://repo.continuum.io/pkgs/msys2"]
  local: ["file:///L:/Anaconda3/conda-bld"]
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
envs_dirs:
  - L:\Anaconda3\envs
  - C:\Users\asus\AppData\Local\conda\conda\envs
  - C:\Users\asus\.conda\envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - L:\Anaconda3\pkgs
  - C:\Users\asus\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: True
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0

**Comment by kalefranz** [comment] 2017-10-14 04:38
To my knowledge, the only way this triggers is for misconfigurations and typos set for proxy servers. Conda just uses requests here, and requests picks up proxy configuration from all over the place, including I think out the the registry on windows. Keep digging I guess. There are plenty of similar issues in our tracker and probably also exposed by google if you look.

**Comment by serenanio** [comment] 2017-10-14 13:15
wow I finally solved it!!! thanks a lot!!!! 👍 : )

**Comment by kalefranz** [comment] 2017-10-20 19:44
@serenanio How did you solve it?  Could you please provide the details here for the benefit of other users?

**Comment by kalefranz** [comment] 2017-10-20 19:57
Related to or duplicate of #3962.  Please move further discussion to that issue.

**Closed by kalefranz** 2017-10-20 19:57 UTC

**Comment by serenanio** [comment] 2017-10-21 05:14
oh.. it was my proxy configuration problem ....maybe because I set a wrong proxy server address before ?not sure about that .. But I set my LAN setting to be ''automatic detection settings''  and it works.  : )
