### ISSUE TITLE
errors in upgrading pkg 

### ISSUE THREAD

**Issue by ShouYuqing** [conda/conda#5958] opened 2017-09-13 02:58 UTC
the errors' descriptions are as follow:
`Traceback (most recent call last):
      File "D:\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "D:\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "D:\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "D:\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "D:\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "D:\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "D:\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
        self._prepare_proxy(conn)
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
        conn.connect()
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 66, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'
`

**Comment by kalefranz** [comment] 2017-09-21 02:35
Please provide the output of `conda info` and all details necessary to reproduce your error.

**Comment by kalefranz** [comment] 2017-10-05 18:25
Related to or duplicate of #3962.

**Comment by kalefranz** [comment] 2017-10-05 18:28
Please move future discussion to #3962.

**Closed by kalefranz** 2017-10-05 18:28 UTC
