### ISSUE TITLE
conda update error

### ISSUE THREAD

**Issue by lee19840806** [conda/conda#6136] opened 2017-10-10 00:07 UTC
Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /home/lee1984/anaconda3  (writable)
    default environment : /home/lee1984/anaconda3
       envs directories : /home/lee1984/anaconda3/envs
                          /home/lee1984/.conda/envs
          package cache : /home/lee1984/anaconda3/pkgs
                          /home/lee1984/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Linux/4.10.0-35-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/lee1984/anaconda3/bin/conda update --all`

    Traceback (most recent call last):
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/lee1984/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080114.791 for timestamp

**Comment by lee19840806** [comment] 2017-10-10 00:08
run the command "conda update --all" and I got the error Invalid value 1506080114.791 for timestamp

**Comment by SenWang** [comment] 2017-10-10 02:37
I have the same issue. 
Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Users\sense\Anaconda3  (writable)
    default environment : C:\Users\sense\Anaconda3
       envs directories : C:\Users\sense\Anaconda3\envs
                          C:\Users\sense\AppData\Local\conda\conda\envs
                          C:\Users\sense\.conda\envs
          package cache : C:\Users\sense\Anaconda3\pkgs
                          C:\Users\sense\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Users\sense\Anaconda3\Scripts\conda update conda`




    Traceback (most recent call last):
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\cli\install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "C:\Users\sense\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506081103.986 for timestamp

**Comment by macnc** [comment] 2017-10-10 02:42
I have the same issue with anaconda3.
Command 'conda update anaconda' or 'conda update --all', I got the same result.

**Comment by PerryZh** [comment] 2017-10-10 03:26
I have same issue

Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /Users/Perry/anaconda  (writable)
    default environment : /Users/Perry/anaconda
       envs directories : /Users/Perry/anaconda/envs
                          /Users/Perry/.conda/envs
          package cache : /Users/Perry/anaconda/pkgs
                          /Users/Perry/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/Perry/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Darwin/14.5.0 OSX/10.10.5    
                UID:GID : 501:20

`$ /Users/Perry/anaconda/bin/conda update --all`




    Traceback (most recent call last):
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/Perry/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080276.026 for timestamp

**Comment by nehaljwani** [comment] 2017-10-10 06:16
Closing as duplicate of #6096 

Basically, we need to fix the json files in conda-meta with timestamp values in floating point.

@lee19840806 Try:
```
sed -i -E 's|("timestamp": [0-9]+)\.|\1|' /home/lee1984/anaconda3/conda-meta/*.json
```
@PerryZh Try:
```
sed -i '' -E 's|("timestamp": [0-9]+)\.|\1|' /Users/Perry/anaconda/conda-meta/*.json
```

@SenWang To find out the files with timestamp in floating point, type:
```
findstr /s /m /i /r /c:"timestamp\": [0-9]*\." C:\Users\sense\Anaconda3\conda-meta\*.json
```
... and use del <path-to-file> to delete those files only.

**Closed by nehaljwani** 2017-10-10 06:16 UTC
