### ISSUE TITLE
Wrong update plan despite "channel_priority: false"

### ISSUE THREAD

**Issue by pitrou** [conda/conda#3986] opened 2016-12-01 16:08 UTC
```
$ conda update --all
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/antoine/miniconda3/envs/dask35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    snappy-1.1.3               |                0         214 KB
    pyzmq-16.0.2               |           py35_0         923 KB
    requests-2.12.1            |           py35_0         788 KB
    cffi-1.9.1                 |           py35_0         338 KB
    cryptography-1.6           |           py35_0         831 KB
    hdfs3-0.1.2                |           py35_0          27 KB
    ipykernel-4.5.1            |           py35_0         128 KB
    ------------------------------------------------------------
                                           Total:         3.2 MB

The following packages will be UPDATED:

    cffi:         1.8.3-py35_0                  --> 1.9.1-py35_0     
    cryptography: 1.5.3-py35_0                  --> 1.6-py35_0       
    hdfs3:        0.1.2-py35_0      conda-forge --> 0.1.2-py35_0     
    ipykernel:    4.5.0-py35_0                  --> 4.5.1-py35_0     
    pyzmq:        16.0.1-py35_0                 --> 16.0.2-py35_0    
    requests:     2.12.0-py35_0                 --> 2.12.1-py35_0    

The following packages will be SUPERCEDED by a higher-priority channel:

    h5py:         2.6.0-np111py35_7 conda-forge --> 2.6.0-np111py35_2
    snappy:       1.1.3-2           conda-forge --> 1.1.3-0          

```

```
$ cat /home/antoine/.condarc
# This is a sample .condarc file

# channel locations. These override conda defaults, i.e., conda will
# search *only* the channels listed here, in the order given. Use "defaults" to
# automatically include all default channels. Non-url channels will be
# interpreted as binstar usernames (this can be changed by modifying the
# channel_alias key; see below).
channels:
  - defaults
  - numba
  - antoine
#  - http://some.custom/channel
#  - file:///some/local/directory

channel_priority: false
add_pip_as_python_dependency: false
```

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.11
         python version : 3.4.5.final.0
       requests version : 2.12.1
       root environment : /home/antoine/miniconda3  (writable)
    default environment : /home/antoine/miniconda3/envs/dask35
       envs directories : /home/antoine/miniconda3/envs
          package cache : /home/antoine/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/numba/linux-64
                          https://conda.anaconda.org/numba/noarch
                          https://conda.anaconda.org/antoine/linux-64
                          https://conda.anaconda.org/antoine/noarch
            config file : /home/antoine/.condarc
           offline mode : False

```

**Comment by pitrou** [comment] 2016-12-28 09:57
Ping? I still encounter variants of this issue on a regular occurrence. @mcg1969

**Comment by mcg1969** [comment] 2016-12-28 13:09
What do you think it should be doing?

**Comment by pitrou** [comment] 2016-12-28 13:11
Well, it should keep the higher-versioned package that's already installed (i.e. `2.6.0-np111py35_7` instead of replacing it with `2.6.0-np111py35_2`). Since I purposedly disabled the `channel_priority` option as advised, that's what I was expecting.

**Comment by mcg1969** [comment] 2016-12-28 13:12
Ah, I remember now. Don't confuse the explanation of the plan with the plan itself. Do you see any problem with the package choice? I don't. The explanations are constructed after the fact. I agree that part should be fixed.

**Comment by pitrou** [comment] 2016-12-28 13:17
Well, that would depend what the exact dependencies of those two versions of `h5py` are.

**Comment by pitrou** [comment] 2016-12-28 13:17
Is there an easy way to inspect that?

**Comment by mcg1969** [comment] 2016-12-28 13:21
Actually, we do not have any notion of per package channel pinning. Packages that are from channels not in the channel list have lowest priority, and even with channel priority set to false, version ties are broken by channel priority. So this is expected behavior. Perhaps not desirable, but not a bug. We are talking about how to tell the solver to preserve the channel a particular package came from.

**Comment by mcg1969** [comment] 2016-12-28 13:26
I believe Will recently improved the documentation around channel priority. But he may not have incorporated the nuance about channels that are not in your channel list.

What you really need, it sounds to me, is the ability to tell the system two in one or more packages to a specific channel.

**Comment by mcg1969** [comment] 2016-12-28 13:28
Sorry, voice dictation fail. That is: the ability to tell the system to pin one or more packages to a specific channel.

**Comment by pitrou** [comment] 2016-12-28 13:37
> That is: the ability to tell the system to pin one or more packages to a specific channel.

Yes, it's probably that in the end. There are some packages that have specific patches in conda-forge and don't in Anaconda.

**Comment by dhirschfeld** [comment] 2017-01-04 00:00
I think I'm having a similar issue. I have `channel_priority` set to `false` because when I update I want the latest version of a package irrespective of whichever channel in my channel list it comes from i.e. I should never see the message:
> The following packages will be SUPERCEDED by a higher-priority channel:

It might be possible to see that message if it was swapping the package for the exact same version (i.e. not downgrading) from the "higher priority" channel, but that would be somewhat redundant and contrary to my expectation that channel priority means treat all channels the same.

In my case whenever I do an `update --all` it wants to *downgrade* freetype:
```
The following packages will be UPDATED:

    beautifulsoup4: 4.5.1-py35_0              --> 4.5.3-py35_0
    conda-build:    2.0.12-py35_0             --> 2.1.0-py35_0
    pyflakes:       1.3.0-py35_0              --> 1.4.0-py35_0
    pymc3:          3.0rc4-py35_0 conda-forge --> 3.0rc6-py35_0 conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    freetype:       2.7-vc14_0    conda-forge [vc14] --> 2.5.5-vc14_1              [vc14]
```
...however upgrading freetype after the fact works fine:
```
λ conda update --force freetype
Fetching package metadata .........................
Solving package specifications: ..........

Package plan for installation in environment C:\Python:

The following packages will be UPDATED:

    freetype: 2.5.5-vc14_1 [vc14] --> 2.7-vc14_0 conda-forge [vc14]

Proceed ([y]/n)? y

Pruning extracted packages from the cache ...
[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
```

Note: I *think* this may be due to a mis-specified dependency somewhere in which case the behaviour is correct but the message is misleading - i.e. the message should specify that it is being downgraded due to version conflicts rather than channel priority (which should never happen)

**Comment by dhirschfeld** [comment] 2017-01-07 03:14
Seems related to #3377

**Comment by kalefranz** [comment] 2017-05-12 22:59
Ultimately, this ticket ended up being a feature request for per-channel package pinning.  That should be coming in conda 4.4.  Tracked in plenty of other open tickets.

**Closed by kalefranz** 2017-05-12 22:59 UTC
Labels: source:cio, type:feature
