### ISSUE TITLE
Conda create --name <> --clone <> returns unexpected error

### ISSUE THREAD

**Issue by k-dinesh** [conda/conda#2192] opened 2016-03-07 23:15 UTC
Traceback (most recent call last):
  File "/Users/Palace/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/misc.py", line 243, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/resolve.py", line 716, in dependency_sort
    for key, value in iteritems(must_have):
  File "/Users/Palace/anaconda/lib/python3.5/site-packages/conda/compat.py", line 157, in iteritems
    return iter(getattr(d, _iteritems)())
AttributeError: 'list' object has no attribute 'items'

**conda --info**
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.1
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/Palace/anaconda  (writable)
  default environment : /Users/Palace/anaconda
     envs directories : /Users/Palace/anaconda/envs
        package cache : /Users/Palace/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by mcg1969** [comment] 2016-03-07 23:58
Duplicate of https://github.com/conda/conda/issues/2178. I've got a fix in preparation.

**Comment by mcg1969** [comment] 2016-03-08 00:15
Fix here: https://github.com/conda/conda/pull/2193

**Comment by kalefranz** [comment] 2016-03-08 20:02
Should be fixed with today's `4.0.2` release.

**Closed by kalefranz** 2016-03-08 20:02 UTC
