### ISSUE TITLE
MD5 Sum mismatch during conda update conda

### ISSUE THREAD

**Issue by MSeifert04** [conda/conda#2235] opened 2016-03-11 00:27 UTC
I'm not sure if this is a problem with ``conda`` but I found it rather strange:

```
[Anaconda] C:\Users\--->conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
.Solving package specifications: ..........

Package plan for installation in environment C:\Programming\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.0.4                |           py35_0         232 KB

The following packages will be UPDATED:

    conda: 4.0.3-py35_0 --> 4.0.4-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-4.0.4-py 100% |###############################| Time: 0:00:00  15.19 MB/s
conda-4.0.4-py 100% |###############################| Time: 0:00:00   0.00  B/s
conda-4.0.4-py 100% |###############################| Time: 0:00:00  15.18 MB/s
conda-4.0.4-py 100% |###############################| Time: 0:00:00  15.16 MB/s
Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/win-64/conda-4.0.4-py35_0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != c451b400b5d9488ae0877e24eb41c8f9)
```

any idea what may be causing this or how to bypass it?

**Comment by msarahan** [comment] 2016-03-11 00:32
Duplicate of #2232 - please see that post for solution.

**Closed** 2016-03-11 00:32 UTC

**Comment by kalefranz** [comment] 2016-03-11 01:07
@MSeifert04 Backing out of this isn't all that easy unfortunately.  You actually need to back up to your previous version of conda, and then you can update to 4.0.4.

The output of

    ls $(/conda/bin/conda info | grep cache | cut -d: -f2) | grep -E "^conda-\d"

should show you the version number.  Then from there, for example if `3.19.3` was the version number indicated

    conda install conda=3.19.3

Sorry for the trouble.

**Comment by MSeifert04** [comment] 2016-03-11 01:08
Thank you for the answers after downgrading the update worked correctly. :+1:
