### ISSUE TITLE
For conda envs lacking an interpreter `conda activate` uses system python whereas `conda run` uses the base python

### ISSUE THREAD

**Issue by karrtikr** [conda/conda#11211] opened 2022-02-11 16:37 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Hi Python extension VSCode dev here 👋

Create a conda environment without a python interpreter using `conda create -n hello`. Run the following set of commands in anaconda prompt:
### Scenario 1:
```
conda activate hello
python -c"import sys;print(sys.executable)"
```
Outputs system python: like `~\AppData\Local\Programs\Python\Python39\python.exe`

### Scenario 2:
```
conda run -n hello python -c"import sys;print(sys.executable)"
```
Outputs base conda python: like `~\Miniconda3\python.exe`

**Expected behavior:** Both of them should use the base conda python.

### Conda info

```shell
active environment : None
    shell level : 0
user config file : ~\.condarc
populated config files : ~\.condarc
  conda version : 4.11.0
conda-build version : not installed
  python version : 3.8.3.final.0
virtual packages : __cuda=11.5=0
                  __win=0=0
                  __archspec=1=x86_64
base environment : ~\Miniconda3  (writable)
conda av data dir : ~\Miniconda3\etc\conda
conda av metadata url : None
    channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                  https://repo.anaconda.com/pkgs/main/noarch
                  https://repo.anaconda.com/pkgs/r/win-64
                  https://repo.anaconda.com/pkgs/r/noarch
                  https://repo.anaconda.com/pkgs/msys2/win-64
                  https://repo.anaconda.com/pkgs/msys2/noarch
                  https://conda.anaconda.org/conda-forge/win-64
                  https://conda.anaconda.org/conda-forge/noarch
  package cache : ~\Miniconda3\pkgs
                  ~\.conda\pkgs
                  ~\AppData\Local\conda\conda\pkgs
envs directories : ~\Miniconda3\envs
                  ~\.conda\envs
                  ~\AppData\Local\conda\conda\envs
        platform : win-64
      user-agent : conda/4.11.0 requests/2.25.1 CPython/3.8.3 Windows/10 Windows/10.0.22518
  administrator : False
      netrc file : None
    offline mode : False
```

### Conda config

```shell
==> ~\.condarc <==
channels:
  - defaults
  - conda-forge
```

### Conda list

```shell
# packages in environment at C:\Users\karraj\Miniconda3:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
astroid                   2.9.3                    pypi_0    pypi
attrs                     21.4.0             pyhd3eb1b0_0    defaults
autopep8                  1.6.0                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports-entry-points-selectable 1.1.0                    pypi_0    pypi
black                     22.1.0                   pypi_0    pypi
brotlipy                  0.7.0           py38h2bbff1b_1003    defaults
ca-certificates           2021.10.26           haa95532_4    defaults
certifi                   2021.10.8        py38haa95532_2    defaults
cffi                      1.15.0           py38h2bbff1b_1    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.3              pyhd3eb1b0_0    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
conda                     4.11.0           py38haa95532_0    defaults
conda-package-handling    1.7.3            py38h8cc25b3_1    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              36.0.0           py38h21b164f_0    defaults
debugpy                   1.5.1            py38hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
distlib                   0.3.3                    pypi_0    pypi
entrypoints               0.3                      py38_0    defaults
filelock                  3.1.0                    pypi_0    pypi
idna                      3.3                pyhd3eb1b0_0    defaults
ipykernel                 6.4.1            py38h595d716_0    conda-forge
ipython                   7.29.0           py38hd4e2768_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
jedi                      0.18.0           py38haa95532_1    defaults
jupyter_client            7.1.2              pyhd3eb1b0_0    defaults
jupyter_core              4.9.1            py38haa95532_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
menuinst                  1.4.16           py38he774522_0    defaults
mypy_extensions           0.4.3            py38haa95532_1    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
openssl                   1.1.1m               h2bbff1b_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pathspec                  0.9.0                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pip                       21.2.2           py38haa95532_0    defaults
platformdirs              2.4.1                    pypi_0    pypi
powershell_shortcut       0.0.1                         3    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
pycodestyle               2.8.0                    pypi_0    pypi
pycosat                   0.6.3            py38h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pylint                    2.12.2                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0    defaults
pytest                    6.2.4                    pypi_0    pypi
python                    3.8.3                he1778fa_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python_abi                3.8                      2_cp38    conda-forge
pywin32                   302              py38h827c3e9_1    defaults
pyzmq                     22.3.0           py38hd77b12b_2    defaults
regex                     2021.8.3         py38h2bbff1b_0    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py38h2bbff1b_0    defaults
setuptools                58.0.4           py38haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.37.0               h2bbff1b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.1              py38h2bbff1b_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
typed-ast                 1.4.3            py38h2bbff1b_1    defaults
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
urllib3                   1.26.8             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
virtualenv                20.8.1                   pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
win_inet_pton             1.1.0            py38haa95532_0    defaults
wincertstore              0.2              py38haa95532_2    defaults
yaml                      0.2.5                he774522_0    defaults
```

**Comment by jaimergp** [comment] 2022-02-15 21:22
Would [this](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#nested-activation) help?

**Comment by beeankha** [comment] 2022-02-21 20:58
Closing this issue since this is a duplicate of https://github.com/conda/conda/issues/11174; @karrtikr, please feel free to add any additional discussion items to that issue directly.

**Closed by beeankha** 2022-02-21 20:58 UTC
Labels: type::bug, source::community, duplicate
