### ISSUE TITLE
Unsatisfiable deps error when building a package that has features

### ISSUE THREAD

**Issue by akale2408** [conda/conda#1820] opened 2015-11-13 19:14 UTC
When building a package that both has features and has tests (run_test.sh or run_test.py exists in the recipe dir), conda fails to correctly bootstrap the test environment, reporting unsatisfied dependencies. The following script will reproduce the problem:

``` bash
mkdir fail

cat > fail/meta.yaml << EOF
package:
  name: fail
  version: 1

requirements:
  build:
    - python

  run:
    - python

build:
  features:
    - debug

EOF

touch fail/build.sh
touch fail/run_test.sh

conda build fail
```

If the `touch fail/run_test.sh` line is removed, or the debug feature is removed, the build runs successfully

I'm running conda 3.18.5 and conda-build 1.18.1

I am able to workaround the issue by adding the following line to my ".condarc":

``` yaml
track_features: debug
```

**Comment by rainman110** [comment] 2016-08-08 20:15
I can confirm this issue. This issue started for since the upgrade to conda 4.*.*.

The svn package from conda-recipes contains both features (vc9, vc10, vc14) and tests. It fails at the testing stage due to unresolvable package specifications.

**Comment by tyler-thetyrant** [comment] 2017-05-02 03:56
Closing outdated.

**Closed by tyler-thetyrant** 2017-05-02 03:56 UTC
