### ISSUE TITLE
clear command doesn't work with OS X 10.10.3: "unknown terminal type"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1368] opened 2015-06-09 13:28 UTC
I have a brand new Mac Book Pro with very little customization.  I have Anaconda 2.2.0 and `conda info -a` reports:

```
             platform : osx-64
        conda version : 3.13.0
  conda-build version : 1.11.0
       python version : 2.7.10.final.0
```

The `clear` command does not work properly for me:

```
petawawa:tmp ijstokes$ clear
'xterm-256color': unknown terminal type.

petawawa:tmp ijstokes$ which clear
/Users/ijstokes/anaconda/bin/clear

petawawa:tmp ijstokes$ ls -Fla `which clear`
-rwxr-xr-x  2 ijstokes  staff  8644 Oct 21  2014 /Users/ijstokes/anaconda/bin/clear*
```

I am about to rename it so I get my system clear back, but I thought I would report this behavior first.

**Comment by asmeurer** [comment] 2015-06-09 16:11
Looks like an issue with my ncurses package.

**Comment by asmeurer** [comment] 2015-06-09 16:37
This should be fixed. `conda update ncurses`.

**Closed by asmeurer** 2015-06-09 16:37 UTC

**Comment by mtbirdsall** [comment] 2016-01-27 18:07
I am trying to use `clear` with a fresh install of anaconda2 on XOS. The issue is that I can't clear the terminal screen. Not a problem I can get by without it.  I installed `ncurses` and that didn't seem to change my plight.  This the stout from `clear`:
```
-bash: /Users/user/anaconda2/bin/clear: No such file or directory
```
FYI  - 
I am new to using terminal as consistently as I have over the last 3 months (i.e. I am sure that I can update a $PATH but I am not sure exactly how I would, should do it, or if I can fix this using another method like updating).

**Comment by mtbirdsall** [comment] 2016-01-27 18:12
`Kenobi-Wan:~ mbirdsall$ conda info -a`
```
             platform : osx-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/mbirdsall/anaconda2  (writable)
  default environment : /Users/mbirdsall/anaconda2
     envs directories : /Users/mbirdsall/anaconda2/envs
        package cache : /Users/mbirdsall/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```
`Kenobi-Wan:~ mbirdsall$ which clear`
```
/usr/bin/clear
```
`Kenobi-Wan:~ mbirdsall$ ls -Fla 'which clear'`
```
ls: which clear: No such file or directory
```

**Comment by gawbul** [comment] 2016-12-08 14:12
I'm having the same issue on a fresh install of Miniconda2 - has the ncurses bug resurfaced?

cc @blink1073 re https://github.com/ContinuumIO/anaconda-issues/issues/331

**Comment by gawbul** [comment] 2016-12-08 14:32
Doing the following fixed for me, so definitely something with the ncurses package again.

```
$ conda remove ncurses 
Fetching package metadata .............
Solving package specifications: ..........

Package plan for package removal in environment /home/gawbul/miniconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fastx_toolkit-0.0.14       |                0         496 KB  bioconda

The following packages will be REMOVED:

    gnuplot:       5.0.4-ncurses5.9_0 bioconda
    ncurses:       5.9-8              r       

The following packages will be DOWNGRADED due to dependency conflicts:

    fastx_toolkit: 0.0.14-2           bioconda --> 0.0.14-0 bioconda

Proceed ([y]/n)? 
```

**Comment by chenqifengfree** [comment] 2017-12-12 06:45
Terminal.app is setting the TERM environment variable according to the menu entry, so exporting it does not address the problem. (Setting TERM has no effect on the behavior of Terminal.app, but that is a different mattern).

OSX (and most Unix-like) systems use terminfo for finding terminal information. If the environment variable TERMINFO is set, the ncurses library uses that path in preference to the compiled-in location (which is supposed to match the installed-location).

Your shell may have set the TERMINFO variable (for instance, by copying settings from another machine). Removing it from the shell initialization (such as ~/.profile or ~/.bashrc) is a way to fix that.

Alternatively, you may (as in tput: unknown terminal “xterm-256color”) have installed some not-mentioned package which conflicts with the ncurses libraries on the system. In that discussion, it seems that someone built ncurses libraries which had compiled-in default for TERMINFO to a non-existent location. For that case, I pointed out that the OP could set TERMINFO to tell the broken libraries where to find the terminal database. That is,

`export TERMINFO=/usr/share/terminfo`
would be a first step.

**Comment by PKHG** [comment] 2019-04-03 13:19
macbook clear works again after adding below in .bash_profile
export TERMINFO=/usr/share/terminfo

Finally  ;-)

**Comment by NLeRoy917** [comment] 2020-04-06 15:18
I ran into this today on OSX's Z Shell (ZSh). (I've had so many issues with Zshell since upgrading to Catalina). Setting TERMINFO as an environment variable

`export TERMINFO=/usr/share/terminfo`

works, but obviously is only temporary - as @PKHG suggested, adding to your ~/.profile makes the fix permanent - but for Z shell, instead of the `~/.bash_profile` you should use `~/.zshrc`.
