### ISSUE TITLE
I can't activate environments in centrally administered install

### ISSUE THREAD

**Issue by davidslac** [conda/conda#2869] opened 2016-06-26 03:05 UTC
I am getting this message

Cannot activate environment bash.
User does not have write access for conda symlinks.

when I activate an environment created in a shared account. 

Doing something like, from the administrator account,

conda create -n boostenv boost python=2.7

and then from a user account, doing

source activate boostenv

leads to that message. This is a very recent version of conda, 4.1.3 I think. This kind of thing was working with 4.0.3. Are we no longer able to make environments centrally for users, unless they can all write to the central location? That doesn't seem right - note, the filesystems may be different enough between the user home directory and the central location that a hard link is not supported, only soft links will work. I am on linux - rhel7.

**Comment by frol** [comment] 2016-06-26 18:54
It seems to be a duplicate of #2681.

**Comment by kalefranz** [comment] 2016-06-30 04:39
Thanks @frol.  Yes I think a duplicate.  And SHOULD be fixed in `4.1.5`.

**Closed by kalefranz** 2016-06-30 04:39 UTC
Labels: bug

**Comment by davidslac** [comment] 2016-07-01 20:02
I was able to create an environment from the administrator account and 
activate in a user account, thanks for fixing this! At first I tried to 
just update conda but I still got the problem, I re-installed from 
scratch, updated conda, conda-env and conda-build to the latest 
versions, and then it worked.

best,

David

**Comment by mjgar** [comment] 2017-10-04 19:37
I am still seeing the broken behavior with conda 4.3.27 and conda-env 2.6.0.

On a fresh install of Anaconda2-5.0.0.1 in /usr/anaconda
I clone the root environment: `conda create -n test --clone root`
The environment is cloned, but when I try to activate it as a regular user, I see an error.

```
source /usr/anaconda/bin/activate test
CondaEnvironmentError: Cannot activate environment bash.
User does not have write access for conda symlinks.
```

**Comment by ithh** [comment] 2017-10-04 19:49
I saw that the code is commented out in the latest version of this file, so I just did so as well on my copy of it. Hopefully it's fixed in the next version of conda.

**Comment by edwardreed81** [comment] 2017-11-28 15:42
I am seeing this behavior using conda 4.3.30 and conda-env 2.6.0 and trying to activate an environment as a user in a bash shell (`source activate <env_name>`). Activating from a fish shell works (`conda activate <env_name>`).
