### ISSUE TITLE
FileNotFoundError - Filename or extension too long

### ISSUE THREAD

**Issue by attibalazs** [conda/conda#7376] opened 2018-06-04 08:44 UTC
I was unable to install nodejs from the conde-forge channel:

```
(base) c:\>conda install -c conda-forge nodejs
Solving environment: done

## Package Plan ##

  environment location: C:\Users\me\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - nodejs


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nodejs-9.11.1              |                0        12.6 MB  conda-forge

The following NEW packages will be INSTALLED:

    nodejs:          9.11.1-0          conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0                  --> 2018.4.16-0      conda-forge
    certifi:         2018.4.16-py36_0              --> 2018.4.16-py36_0 conda-forge
    conda:           4.5.4-py36_0                  --> 4.5.4-py36_0     conda-forge
    openssl:         1.0.2o-h8ea7d77_0             --> 1.0.2o-vc14_0    conda-forge [vc14]

Proceed ([y]/n)? y


Downloading and Extracting Packages
nodejs-9.11.1        | 12.6 MB | #########################################################################2                        |  76%

FileNotFoundError(2, 'The filename or extension is too long')

```

**Comment by kalefranz** [comment] 2018-06-04 16:11
Duplicate of https://github.com/conda/conda/issues/7203

**Closed by kalefranz** 2018-06-04 16:11 UTC
