### ISSUE TITLE
Activating conda env crashes/closes Windows Anaconda prompt

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#8337] opened 2019-02-25 19:48 UTC
After successfully creating a conda env from an `environment.yml` file, activating the resulting env with `conda activate` crashes (or at least closes) the Anaconda prompt window in Windows 10.  Unfortunately, the window closes so quickly, I cannot read what is printed to standard out prior to close.

Using conda 4.6.7.

Here are the contents of `environment.yml`:

```
name: dev

channels:
 - conda-forge
 
dependencies:
- python=3.7
- altair
- arrow
- basemap
- blaze
- bokeh
- cython
- dask
- engarde
- conda-forge::geopandas
- ibis-framework
- ipython
- jupyter
- notebook
- ipyparallel
- ipywidgets
- joblib
- jupyter_client
- jupyter_core
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- jupyterlab
- line_profiler
- mkl-service
- numexpr
- numba
- numpy
- openpyxl
- pandas
- pandas-gbq
- patsy
- pillow
- pip
- pylint
- rpy2
- scikit-learn
- scipy
- seaborn
- snakeviz
- sympy
- theano
- xlrd
- pip:
  - tf-nightly
  - tfp-nightly
  - google-cloud-bigquery
  - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3
```

**Comment by msarahan** [comment] 2019-02-25 19:53
Thanks for the report and the env spec.  I suspect an errant exit code, but we'll need to reproduce it to make sure.

**Comment by msarahan** [comment] 2019-02-25 20:06
Unfortunately, I can't immediately reproduce this on a win-64 machine.  The activation works OK for me.  There may be more state involved here.

**Comment by msarahan** [comment] 2019-02-25 20:14
The activation scripts in play here are at https://gist.github.com/msarahan/966d118f4a2390d7522cd6d57613cf35

It seems to me that if you don't have VS2015, that script may error out.  Do you have VS2015 installed on the system?

Regardless, we should handle the error condition here more gracefully.

**Comment by fonnesbeck** [comment] 2019-02-27 19:08
Right, I do not have VS2015 installed, and I'd prefer not to. Should I edit the bat files in conda?

**Comment by msarahan** [comment] 2019-02-27 19:25
It's probably better to identify what's bringing in that compiler dependency and maybe try to fix that package so that it doesn't bring in the compiler dependency.  As a hack, yeah, just straight up removing that script from activate.d will do the trick.

**Comment by fonnesbeck** [comment] 2019-02-28 04:51
I've installed VS2017, and it still crashes. Why would it be pinned to VS2015?

**Comment by msarahan** [comment] 2019-02-28 14:26
That is the nature of compiler packages.  They don't say "you need any of a range of compilers."  They say "You need this compiler."  That makes a lot of sense at build time, where you want to control compatibility more tightly.  It makes less sense with compilers at runtime.  At runtime, they need only be compatible with whatever else is in the environment.  Unfortunately, we don't have very good ways to express that right now.  There needs to be some way to express that Theano needs some compiler that is capable of generating code that is compatible within certain bounds.  For Python 3.5+, those bounds are the new UCRT/VC 14 runtimes.

But I digress.  The problem you have is that the constraint on VS2015 comes from one or more of the packages you're installing.  Theano is almost certainly one of them.  Your options are:

* manually remove that vs2015 file from etc/conda/activate.d
* fork the conda-forge theano recipe and build it yourself with vs2017 in a c_compiler field in conda_build_config.yaml
* use theano from defaults, which is set up to use the m2w64 toolchain instead of MSVC

**Comment by dhirschfeld** [comment] 2019-03-12 03:13
I'm running into this same problem when trying to install on a machine that doesn't have Visual Studio installed.

It looks like the offending package is `vs2015_win-64`:
```
~\envs\dev\etc\conda\activate.d> dir

   Volume in drive C has no label.
   Volume Serial Number is 94F7-A1ED
  
   Directory of ~\envs\dev\etc\conda\activate.d
  
  12/03/2019  11:54 AM    <DIR>          .
  12/03/2019  11:54 AM    <DIR>          ..
  16/01/2018  12:14 PM             2,456 vs2015_compiler_vars.bat
                 1 File(s)          2,456 bytes
                 2 Dir(s)  383,204,581,376 bytes free

~\envs\dev\etc\conda\activate.d> fsutil hardlink list vs2015_compiler_vars.bat

  \Miniconda3\pkgs\vs2015_win-64-14.0.25123-h17c34da_3\etc\conda\activate.d\vs2015_compiler_vars.bat
  ~\envs\dev\etc\conda\activate.d\vs2015_compiler_vars.bat

~\envs\dev\etc\conda\activate.d>
```

**Comment by dhirschfeld** [comment] 2019-03-12 03:37
`exit 1` is clearly the wrong thing to do however I'm not sure where to open an issue as I can't find the repo for the `vs2015_win-64` package

**Comment by dhirschfeld** [comment] 2019-03-12 03:54
It looks like it's `theano` which includes this dep:
```python
In [22]: record
Out[22]: 
{'arch': 'x86_64',
 'build': 'py37h6538335_1000',
 'build_number': 1000,
 'channel': 'https://conda.anaconda.org/conda-forge/win-64',
 'constrains': [],
 'depends': ['numpy >=1.9.1',
  'pygpu >=0.7.0,<0.8',
  'python >=3.7,<3.8.0a0',
  'scipy >=0.14',
  'setuptools',
  'six >=1.9.0',
  'vc 14.*',
  'vs2015_win-64'],
 'features': '',
 'fn': 'theano-1.0.4-py37h6538335_1000.tar.bz2',
 'license': 'BSD 3-Clause',
 'md5': '89158713b2423a1dc8bbfe5c344a4a01',
 'name': 'theano',
 'platform': 'win32',
 'size': 3862421,
 'subdir': 'win-64',
 'timestamp': 1547665296934,
 'track_features': '',
 'url': 'https://conda.anaconda.org/conda-forge/win-64/theano-1.0.4-py37h6538335_1000.tar.bz2',
 'version': '1.0.4'}
```

**Comment by wochner** [comment] 2019-05-09 16:32
We have the same issue. It does seem to crash after a line that reads `do SET "VSINSTALLDIR=%B"`

Attached a screenshot we managed to capture:

[crash_screenshot.pdf](https://github.com/conda/conda/files/3163107/crash_screenshot.pdf)

**Comment by DeanLa** [comment] 2019-05-29 11:14
Are there any workarounds for now?
I have intalled PyMC3 on its own env, but now even my base conda env crashes.

**Comment by dhirschfeld** [comment] 2019-05-29 11:48
> *Are there any workarounds for now?*

Delete the `vs2015_compiler_vars.bat` file. YMMV.

**Comment by wochner** [comment] 2019-06-13 15:07
In which version of theano was this introduced? Can we just fix theano to a specific version before the vs dependancy was introduced as a workaround until this is solved?

**Comment by dhirschfeld** [comment] 2019-06-13 23:24
The `vs2015_win-64` dependency was fixed in https://github.com/AnacondaRecipes/aggregate/pull/153 so this should no longer be a problem.

As such this issue can probably be closed since a `conda update vs2015_win-64` *should* fix it.

**Comment by agressorbro** [comment] 2019-06-30 18:27
I updated conda, conda-env and conda-build packages via Anaconda Navigator which fixed the issue for me.
Anaconda prompt which was crashing before starting working post that.
then I did conda update anaconda to bring things to latest version.

**Closed** 2020-04-28 15:46 UTC
Labels: source-community, type-packaging
