### ISSUE TITLE
QuTip installation problems

### ISSUE THREAD

**Issue by mredell** [conda/conda#6107] opened 2017-10-08 13:20 UTC
I tried installing Qutip using: 

`conda install qutip`

and received the following:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 1.18.1
         python version : 3.5.1.final.0
       requests version : 2.13.0
       root environment : /Users/mredell/anaconda  (writable)
    default environment : /Users/mredell/anaconda
       envs directories : /Users/mredell/anaconda/envs
                          /Users/mredell/.conda/envs
          package cache : /Users/mredell/anaconda/pkgs
                          /Users/mredell/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/mredell/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.13.0 CPython/3.5.1 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /Users/mredell/anaconda/bin/conda install qutip`

    Traceback (most recent call last):
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/mredell/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1505178619.367 for timestamp

Any help with correcting this would be greatly appreciated! I ensured that all of the packages required for QuTip (found at http://qutip.org/docs/4.0.2/installation.html) were already installed or updated to compatible versions.

Thanks!

**Comment by msarahan** [comment] 2017-10-08 15:52
Duplicate of #6096. closing to consolidate discussion.

**Closed by msarahan** 2017-10-08 15:52 UTC
