### ISSUE TITLE
env creation eooro

### ISSUE THREAD

**Issue by harica** [conda/conda#4136] opened 2016-12-24 15:14 UTC
(C:\Users\Hari\Anaconda3) C:\Users\Hari\Anaconda3\CarND-TensorFlow-Lab>conda env create -f CarND-TensorFlow-Lab/environment.yml > error.txt
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\Hari\Anaconda3  (writable)
    default environment : C:\Users\Hari\Anaconda3
       envs directories : C:\Users\Hari\Anaconda3\envs
          package cache : C:\Users\Hari\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\Hari\Anaconda3\Scripts\conda-env-script.py create -f CarND-TensorFlow-Lab/environment.yml`

    Traceback (most recent call last):
      File "C:\Users\Hari\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Hari\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 81, in execute
        directory=os.getcwd())
      File "C:\Users\Hari\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: CarND-TensorFlow-Lab/environment.yml file not found
    There is no requirements.txt

(C:\Users\Hari\Anaconda3) C:\Users\Hari\Anaconda3\CarND-TensorFlow-Lab>

**Comment by kalefranz** [comment] 2017-05-09 03:57
Duplicate of #3689

**Closed by kalefranz** 2017-05-09 03:57 UTC
