### ISSUE TITLE
failed to conda update pysam

### ISSUE THREAD

**Issue by jmh010** [conda/conda#3940] opened 2016-11-23 05:59 UTC
```
Current conda install:

             platform : osx-64
        conda version : 4.2.13
     conda is private : False
    conda-env version : 4.2.13
  conda-build version : 1.18.2
       python version : 2.7.12.final.0
     requests version : 2.12.1
     root environment : /Users/josmh/anaconda  (writable)
  default environment : /Users/josmh/anaconda
     envs directories : /Users/josmh/anaconda/envs
        package cache : /Users/josmh/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                        https://repo.continuum.io/pkgs/free/noarch
                        https://repo.continuum.io/pkgs/pro/osx-64
                        https://repo.continuum.io/pkgs/pro/noarch
          config file : None
         offline mode : False



`$ /Users/josmh/anaconda/bin/conda update pysam`




  Traceback (most recent call last):
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
      return_value = func(*args, **kwargs)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
      exit_code = args.func(args, p)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
      install(args, parser, 'update')
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
      prefix=prefix)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
      index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
      for url in urls]
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
      res = f(*args, **kwargs)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
      timeout=(6.1, 60))
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
      return self.request('GET', url, **kwargs)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
      resp = self.send(prep, **send_kwargs)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
      r = adapter.send(request, **kwargs)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
      timeout=timeout
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
      chunked=chunked)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
      self._validate_conn(conn)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
      conn.connect()
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
      cert = self.sock.getpeercert()
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
      'subjectAltName': get_subj_alt_name(x509)
    File "/Users/josmh/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
      ext = cert.extensions.get_extension_for_class(
  AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
```

**Comment by kalefranz** [comment] 2016-11-23 22:29
Duplicate of #3898, #3918, #3929, #3934, #3935 and #3938. Honestly not sure where this came from all the sudden. We definitely need to limit dependencies somewhere.

In general pyopenssl and cryptography are out of sync.

    CONDA_VERIFY_SSL=false conda update pyopenssl

should fix your problem

**Closed by kalefranz** 2016-11-23 22:29 UTC
