### ISSUE TITLE
conda update conda

### ISSUE THREAD

**Issue by mahimanzum** [conda/conda#6310] opened 2017-11-15 12:42 UTC
conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.11.1
       root environment : /home/mahim/anaconda3  (writable)
    default environment : /home/mahim/anaconda3
       envs directories : /home/mahim/anaconda3/envs
                          /home/mahim/.conda/envs
          package cache : /home/mahim/anaconda3/pkgs
                          /home/mahim/.conda/pkgs
           channel URLs : https://conda.anaconda.org/soumith/linux-64
                          https://conda.anaconda.org/soumith/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/mahim/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.11.1 CPython/3.6.2 Linux/4.13.0-16-generic debian/stretch/sid glibc/2.26    
                UID:GID : 1000:1000

`$ /home/mahim/anaconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/mahim/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1502004065.769 for timestamp

**Comment by nasedil** [comment] 2017-11-16 12:08
Have you tried this:
https://github.com/conda/conda/issues/6096

**Comment by kalefranz** [comment] 2018-01-12 23:24
Duplicate of #6096.

**Closed by kalefranz** 2018-01-12 23:24 UTC
