### ISSUE TITLE
Installing for a tar.bz2 file should warn about missing dependencies.

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#3179] opened 2016-07-28 10:42 UTC
We ran into this recently. It would be a friendly feature to tell the user what they need to install.

**Comment by jakirkham** [comment] 2016-08-27 23:50
Yeah, this would be pretty amazing. 👍

Here's an [example]( https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.6250/job/smf34l63qhqcd6q8#L592 ) of the current behavior. While I'm sure it is some dependency that I'm missing (probably due to an unrelated issue), I cannot seem to determine what it is.

**Comment by kalefranz** [comment] 2018-03-02 10:43
This is a duplicate of https://github.com/conda/conda/issues/6147. Let's track with that issue.

**Closed by kalefranz** 2018-03-02 10:43 UTC
Labels: source:core, type:feature
