### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by PachiCartelle** [conda/conda#4024] opened 2016-12-09 00:02 UTC
Traceback (most recent call last):
  File "/Users/pachicartelle/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/pachicartelle/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/Users/pachicartelle/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/pachicartelle/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/pachicartelle/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 413, in get_info
    args.func(args, p)
  File "/Users/pachicartelle/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 156, in execute
    from conda.api import get_index
  File "/Users/pachicartelle/anaconda/lib/python2.7/site-packages/conda/api.py", line 7, in <module>
    from .fetch import fetch_index
  File "/Users/pachicartelle/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 20, in <module>
    from requests.packages.urllib3.connectionpool import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning

**Comment by kalefranz** [comment] 2017-05-01 21:52
duplicate of #4803

**Closed by kalefranz** 2017-05-01 21:52 UTC
