### ISSUE TITLE
An unexpected error has occurred when trying to install_tensorflow() on windows 10 / RStudio

### ISSUE THREAD

**Issue by anneg1000** [conda/conda#5635] opened 2017-07-04 08:07 UTC
> install_tensorflow()
Creating r-tensorflow conda environment for TensorFlow installation...
Fetching package metadata ...**An unexpected error has occurred.**
Please consider posting the following information to the
conda GitHub issue tracker at:

    **https://github.com/conda/conda/issues**

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\PROGRA~3\ANACON~1  (writable)
    default environment : C:\PROGRA~3\ANACON~1
       envs directories : C:\PROGRA~3\ANACON~1\envs
          package cache : C:\PROGRA~3\ANACON~1\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\PROGRA~3\ANACON~1\Scripts\conda-script.py create --yes --name r-tensorflow python=3.6`

    Traceback (most recent call last):
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\PROGRA~3\ANACON~1\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\PROGRA~3\\ANACON~1\\pkgs\\cache\\2116b818.json'

Error: Error 1 occurred creating conda environment r-tensorflow
In addition: Warning message:
running command '"C:\PROGRA~3\ANACON~1\Scripts\conda.exe" "create" "--yes" "--name" "r-tensorflow" "python=3.6"' had status 1

**Comment by nehaljwani** [comment] 2017-07-05 06:43
Closing as duplicate of #4743

**Closed by nehaljwani** 2017-07-05 06:43 UTC
