### ISSUE TITLE
error when conda update anaconda

### ISSUE THREAD

**Issue by clausTue** [conda/conda#1778] opened 2015-11-04 07:17 UTC
Hello, 
I tried to update anaconda, when the error below occurred and I was asked to submit the issue here. I'd appreciate any pointers for resolving this issue.

Thanks.

conda update anaconda
Fetching package metadata: ......
Solving package specifications: .....................................................................................................................An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/carlos/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 1057, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 819, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/Users/carlos/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 624, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: beautifulsoup4-4.4.1-py27_0.tar.bz2 MatchSpec(u'html5lib')
u-198-c178: carlos$conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.3
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /Users/carlos/anaconda  (writable)
  default environment : /Users/carlos/anaconda
     envs directories : /Users/carlos/anaconda/envs
        package cache : /Users/carlos/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/ioos/osx-64/
                        https://conda.anaconda.org/ioos/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/carlos/.condarc
    is foreign system : False

u-198-c178: carlos$

**Comment by BjornFJohansson** [comment] 2015-11-04 13:47
Hi, same here:

    Traceback (most recent call last):
      File "/home/bjorn/anaconda/envs/bjorn/bin/conda", line 5, in <module>
        sys.exit(main())
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
        args_func(args, p)
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
        args.func(args, p)
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
        install.install(args, parser, 'update')
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 333, in install
        update_deps=args.update_deps)
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/plan.py", line 411, in install_actions
        update_deps=update_deps):
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 1057, in solve
        installed, minimal_hint=minimal_hint, update_deps=update_deps)
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 819, in solve2
        clauses = set(self.gen_clauses(v, dists, specs, features))
      File "/home/bjorn/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 624, in gen_clauses
        assert len(clause) > 1, '%s %r' % (fn1, ms)
    AssertionError: tornado-4.2-py27_0.tar.bz2 MatchSpec(u'backports.ssl_match_hostname')
    (bjorn)bjorn@bjorn-ThinkPad-T450s:~$ 


my system:

    (bjorn)bjorn@bjorn-ThinkPad-T450s:~$ conda info --json
    {
      "channels": [
        "https://conda.anaconda.org/t/<TOKEN>/BjornFJohansson/linux-64/", 
        "https://conda.anaconda.org/t/<TOKEN>/BjornFJohansson/noarch/", 
        "https://repo.continuum.io/pkgs/free/linux-64/", 
        "https://repo.continuum.io/pkgs/free/noarch/", 
        "https://repo.continuum.io/pkgs/pro/linux-64/", 
        "https://repo.continuum.io/pkgs/pro/noarch/"
      ], 
      "conda_build_version": "1.18.0", 
      "conda_version": "3.18.3", 
      "default_prefix": "/home/bjorn/anaconda/envs/bjorn", 
      "envs": [
        "/home/bjorn/anaconda/envs/_app_own_environment_ypkpathway", 
        "/home/bjorn/anaconda/envs/_test", 
        "/home/bjorn/anaconda/envs/bjorn", 
        "/home/bjorn/anaconda/envs/jup", 
        "/home/bjorn/anaconda/envs/seguid", 
        "/home/bjorn/anaconda/envs/wp", 
        "/home/bjorn/anaconda/envs/wp2"
      ], 
      "envs_dirs": [
        "/home/bjorn/anaconda/envs"
      ], 
      "is_foreign": false, 
      "pkgs_dirs": [
        "/home/bjorn/anaconda/pkgs"
      ], 
      "platform": "linux-64", 
      "python_version": "2.7.10.final.0", 
      "rc_path": "/home/bjorn/.condarc", 
      "requests_version": "2.8.1", 
      "root_prefix": "/home/bjorn/anaconda", 
      "root_writable": true, 
      "sys_rc_path": "/home/bjorn/anaconda/.condarc", 
      "user_rc_path": "/home/bjorn/.condarc"
    }
    (bjorn)bjorn@bjorn-ThinkPad-T450s:~$

**Comment by marscher** [comment] 2015-11-04 17:38
This seems to be a really serious bug! Same here.

**Comment by ijstokes** [comment] 2015-11-04 19:28
We're working on an update to conda to resolve this issue (in fact, I think the fix has been completed and we're just waiting for conda 3.18.4 package to be released).  In the mean time you *may* be able to fix things by reverting to an earlier version of conda, e.g. by doing:

```bash
conda install conda=3.17
```

I just had a similar problem that I got around by reverting to an earlier conda version.

**Comment by mcg1969** [comment] 2015-11-04 23:52
This is a frustrating issue indeed, not just because of the trouble it's causing y'all, but because we're having a dickens of a time reproducing it. If anyone can come up with a `conda install` string that consistently reproduces this particular issue, it would be greatly appreciated.

**Comment by mcg1969** [comment] 2015-11-04 23:58
OK, I am now reasonably certain that the issue is due to conflicts between the multiple repos. 

@clausTue, `beautifulsoup4-4.4.1-py27_0.tar.bz2` exists both in the `ioos` repo and in the master repo. The problem is that the `ioos` version has different dependencies.

@BjornFJohansson, do you have a tornado package in your personal repos?

**Comment by mcg1969** [comment] 2015-11-05 00:01
Here's a single-line conda command to exercise the error: `conda create -n test1 -c ioos anaconda`

**Comment by mcg1969** [comment] 2015-11-05 00:27
I just discovered that if I apply https://github.com/conda/conda/pull/1766 the problem goes away. This PR has already been merged into master, but hasn't been pushed out in an official release yet. It's coming, but I do not know when.

**Comment by BjornFJohansson** [comment] 2015-11-05 05:50
@mcg1969 I do have tornado 4.2 

https://anaconda.org/bjornfjohansson/tornado

**Comment by mcg1969** [comment] 2015-11-10 02:19
conda 3.18.4 has been released, which includes the required fixes.

**Closed** 2015-11-10 02:37 UTC
