### ISSUE TITLE
spacebar not recognized in python shell (no problem with compiled from source) 

### ISSUE THREAD

**Issue by amanzotti** [conda/conda#939] opened 2014-10-08 21:26 UTC
My problem is that when I run a python version obtained through Miniconda from the bash the spacebar is not recognized in the python shell. When I press the spacebar I just hear the beep sound.

Using different shell does not seem to solve the problem.

This does NOT happen when I compile Python from source or when I used the python already installed in the system. I am running OSX 10.9.5. I compiled different python version and they work fine so it does not seem to be related to the version of python I am using.

And it happen only with python/ipython I have never seen this problem with other application or in my bash.

It seems to be something related to how  Miniconda python is compiled (maybe some libreadline issue?). 

Some possible info are:

Tha miniconda version has the problem
```
    otool -L ~/miniconda/bin/python2.7
/Users/alessandromanzotti/miniconda/bin/python2.7:
    @loader_path/../lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.0.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

```
As well as the macport python
```
otool -L /opt/local/bin/python
/opt/local/bin/python:
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

otool -L /opt/local/bin/python3.3
/opt/local/bin/python3.3:
    /opt/local/Library/Frameworks/Python.framework/Versions/3.3/Python (compatibility version 3.3.0, current version 3.3.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

```
The osx python installed with the systems works
```
otool -L /usr/bin/python
/usr/bin/python:
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.14.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
As well as the 2 version I compiled

otool -L /Users/alessandromanzotti/Python2.7.8/bin/python2.7 
/Users/alessandromanzotti/Python2.7.8/bin/python2.7:
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.17.0)
    /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)

```

**Comment by soapy1** [comment] 2016-10-13 18:35
I can't reproduce this issue on the newest version of conda. Closing the issue; if this is still a problem for you after updating conda, please reopen the issue.

**Closed by soapy1** 2016-10-13 18:35 UTC
