### ISSUE TITLE
[CI] Study the use `paths-ignore` to prevent some runs

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#12053] opened 2022-11-03 10:11 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

We can improve the GHA workflows so they use [`paths-ignore`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) to prevent some jobs from being triggered if the push event only contains certain file types that should not have an effect at all on the results of the tests.

For example, in the `ci.yml`, we could add the following filters to prevent PRs from being triggered when a push event only contains the news file (quite common), or documentation changes:

```yaml
name: CI tests

on:
  # NOTE: github.event context is push payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
  push:
    branches:
      - main

  # NOTE: github.event context is pull_request payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
  pull_request:
    paths-ignore:
      - `news/`
      - `docs/` # maybe?
```

### Why is this needed?

To save some precious natural resources, guilt and time.

### What should happen?

If this works, the CI should not run when a push event **only** contains changes in e.g. `news/`.

**Comment by kenodegard** [comment] 2022-12-19 16:03
Duplicate of https://github.com/conda/conda/issues/12133

**Closed by kenodegard** 2022-12-19 16:03 UTC
Labels: type::feature, duplicate
