### ISSUE TITLE
Issue trying to update 

### ISSUE THREAD

**Issue by CamiloAlvarezU** [conda/conda#3952] opened 2016-11-27 03:04 UTC
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.2
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : /Users/Camilo/anaconda  (writable)
    default environment : /Users/Camilo/anaconda
       envs directories : /Users/Camilo/anaconda/envs
          package cache : /Users/Camilo/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/Camilo/anaconda/bin/conda update anaconda`

    Traceback (most recent call last):
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/Camilo/anaconda/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/Users/Camilo/anaconda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/Users/Camilo/anaconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Users/Camilo/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by Sardtok** [comment] 2016-11-27 16:36
Same error on Python 2.7. Both for updating Anaconda or setting up new environments.

**Comment by kalefranz** [comment] 2017-05-01 19:56
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:56 UTC
