### ISSUE TITLE
conda install something.bz2 makes weird file: directory

### ISSUE THREAD

**Issue by rcthomas** [conda/conda#3911] opened 2016-11-17 22:47 UTC
To reproduce:

    mkdir qqq && cd qqq
    wget https://repo.continuum.io/miniconda/Miniconda2-4.2.12-Linux-x86_64.sh
    bash Miniconda2-4.2.12-Linux-x86_64.sh -b -p $(pwd)/env
    export PATH=$(pwd)/env/bin:$PATH
    conda install astropy
    mv env/pkgs/*.bz2 .
    conda uninstall mkl
    conda install *.bz2
    ls
    (see file: directory with strange stuff in it)

The resulting conda info:

conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /global/homes/r/rthomas/qqq/env  (writable)
    default environment : /global/homes/r/rthomas/qqq/env
       envs directories : /global/homes/r/rthomas/qqq/env/envs
          package cache : /global/homes/r/rthomas/qqq/env/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /global/homes/r/rthomas/.condarc
           offline mode : False

**Comment by hainm** [comment] 2016-11-18 00:04
related #https://github.com/conda/conda/issues/3801

**Comment by kalefranz** [comment] 2016-11-18 00:56
Yeah I think it's fixed. We need a patch release. I'll make it happen soon. Have been heads down getting 4.3 ready :)

**Comment by jhunkeler** [comment] 2016-11-18 02:51
@kalefranz Just to confirm what we're seeing here, the problem is in `conda/install.py::try_hard_link()`

Using current master 1f94336c3254e2d85405073f5ebfb4d6c8b2769d (installing via `--file URL`):
```
(Pdb) l
568  	    dst = join(prefix, '.tmp-%s' % dist)
569  	    assert isfile(src), src
570  	    assert not isfile(dst), dst
571  	    try:
572  	        if not isdir(prefix):
573  ->	            os.makedirs(prefix)
574  	        _link(src, dst, LINK_HARD)
575  	        # Some file systems (at least BeeGFS) do not support hard-links
576  	        # between files in different directories. Depending on the
577  	        # file system configuration, a symbolic link may be created
578  	        # instead. If a symbolic link is created instead of a hard link,
(Pdb) n
> /home/jhunk/miniconda3/lib/python3.5/site-packages/conda/install.py(574)try_hard_link()
-> _link(src, dst, LINK_HARD)
(Pdb) display prefix
display prefix: 'http://ssb.stsci.edu/conda-dev::'
(Pdb) display dst
display dst: 'http://ssb.stsci.edu/conda-dev::/.tmp-appdirs-1.4.0-py27_0'
```

Generates and leaves behind this directory structure:

```
$ ls -l
total 4
drwxrwxr-x. 3 jhunk jhunk   60 Nov 17 21:39 http:
```

```
$ find http\:/
http:/
http:/ssb.stsci.edu
http:/ssb.stsci.edu/conda-dev::
```

**Comment by kalefranz** [comment] 2017-05-05 18:22
Definitely fixed now.

**Closed by kalefranz** 2017-05-05 18:22 UTC
Labels: type:bug
