### ISSUE TITLE
BlockingIOError

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda#6468] opened 2017-12-15 16:50 UTC
I got the following with the latest conda (4.3.30 py36h5d9f9f4_0) on [travis](https://travis-ci.org/diffpy/sampledb/jobs/316701556) during `conda create --yes -n testenv python=3.6 pytest codecov coverage xlrd xlsxwriter pymongo flake8 pandas jsonschema -c conda-forge`

Any idea what could be going wrong?

```python
--- Logging error ---
Traceback (most recent call last):
  File "/home/travis/mc/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "/home/travis/mc/lib/python3.6/site-packages/conda/cli/install.py", line 326, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/plan.py", line 828, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
    cmd(state, arg)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/home/travis/mc/lib/python3.6/site-packages/conda/core/package_cache.py", line 492, in execute
    self._execute_action(action)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/core/package_cache.py", line 513, in _execute_action
    raise CondaMultiError(exceptions)
conda.CondaMultiError: BlockingIOError(11, 'write could not complete without blocking', 4048)
BlockingIOError(11, 'write could not complete without blocking', 4048)
BlockingIOError(11, 'write could not complete without blocking', 8192)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/mc/lib/python3.6/logging/__init__.py", line 996, in emit
    self.flush()
  File "/home/travis/mc/lib/python3.6/logging/__init__.py", line 976, in flush
    self.stream.flush()
BlockingIOError: [Errno 11] write could not complete without blocking
Call stack:
  File "/home/travis/mc/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/home/travis/mc/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/exceptions.py", line 631, in handle_exception
    print_conda_exception(e)
  File "/home/travis/mc/lib/python3.6/site-packages/conda/exceptions.py", line 567, in print_conda_exception
    stderrlogger.info("\n%r", exception)
Message: '\n%r'
Arguments: (CondaError: BlockingIOError(11, 'write could not complete without blocking', 4048)
CondaError: BlockingIOError(11, 'write could not complete without blocking', 4048)
CondaError: BlockingIOError(11, 'write could not complete without blocking', 8192)
,)
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking
```

**Comment by anjos** [comment] 2017-12-17 20:37
This problems seems related to the verbosity of conda installs - maybe some terminal incompatibility? Using `--quiet` at conda operations that make extensive use of terminal control (e.g. `conda create`) mitigates the problems for me.

**Comment by kalefranz** [comment] 2018-01-05 17:15
Duplicate of https://github.com/conda/conda/issues/6473.  There's more discussion there, so will close this issue.

**Closed** 2018-01-05 17:16 UTC
