### ISSUE TITLE
Cannot use Conda - unexpected error when checking conda --version

### ISSUE THREAD

**Issue by Liurika** [conda/conda#4174] opened 2017-01-04 15:38 UTC
C:\WINDOWS\system32>conda --version
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Program Files\Miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\exceptions.py", line 413, in get_info
    args.func(args, p)
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\cli\main_info.py", line 156, in execute
    from conda.api import get_index
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\fetch.py", line 29, in <module>
    from .connection import CondaSession, RETRIES
  File "C:\Program Files\Miniconda2\lib\site-packages\conda\connection.py", line 60, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1458, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1420, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.12 |Continuum Analytics, Inc.| (default, Jun 29 2016, 11:42:13) [MSC v.1500 32 bit (Intel)]'

**Comment by kalefranz** [comment] 2017-05-05 00:23
Duplicate of #3606

**Closed by kalefranz** 2017-05-05 00:23 UTC
