### ISSUE TITLE
request: conda "rename" (or conda "move") for changing name of an environment

### ISSUE THREAD

**Issue by TomLav** [conda/conda#3097] opened 2016-07-17 06:11 UTC
All is in the title :)

Today I wanted to rename my historic "dev" environment to "devel".

This did the trick:

`conda create --name devel --clone dev`
`conda remove --name dev --all`

This however seemed to (temporarily) duplicate disk usage. And maybe a specific command could do something smarter than "copy + remove", I do not know.

T.

**Comment by eduartua** [comment] 2016-11-20 05:28
Any advancement with this?

**Comment by wandonye** [comment] 2017-01-13 07:34
Is it ok to just change the name of the folder under env?

**Comment by kaumaron** [comment] 2017-01-18 14:25
I just tried your suggestion wandonye and it seems to be working so far.

**Comment by H0R5E** [comment] 2017-03-13 09:39
+1

**Comment by shachar-i** [comment] 2017-03-22 09:01
+1

**Comment by ashander** [comment] 2017-03-31 17:12
Yes this would be great. Not only does the work around posted above temporarily duplicate disk usage but it hits remote repos and uses network

**Comment by dlime** [comment] 2017-04-11 11:37
+1 :)

**Comment by DheerajAgarwal** [comment] 2017-04-25 13:54
+1

**Comment by braham-snyder** [comment] 2017-04-25 19:47
Though I too would like to see this feature implemented, "+1" posts send every subscriber a useless notification--I (and I suspect many other subscribers) would greatly appreciate it if you instead gave the OP a thumbs up (by clicking the smiley face in its top right corner).

(In case you didn't notice, GitHub's issue tracker can sort issues by the numbers of reactions they've garnered--ideally, IMO, we'd have explicit issue voting with votes displayed next to the number of comments as in https://github.com/isaacs/github/issues/9 or, e.g., GitLab, but that doesn't look like it will happen in the near future.)

**Comment by ijstokes** [comment] 2017-05-30 19:58
@kalefranz I'd like to suggest that this is a duplicate of #1845

**Comment by sebma** [comment] 2017-06-15 16:55
Hi,
I tried renaming my environment directory name in the filesystem from `test` to `test3` and inside `$HOME/.conda/environments.txt` file but it does not seem enough : 
```
$ source activate test2
$ ipython -V
-bash: /usr/local/miniconda3/envs/test3/bin/ipython: /usr/local/miniconda3/envs/test/bin/python: bad interpreter: No such file or directory
```

Any idea ?

**Comment by sebma** [comment] 2017-06-15 17:16
I found why : 

I seems the path to environment is included in the shebang of the scripts in the environment bin directory and also in other files.

Therefore unless script a recursive search'n'replace, rename the environment directory is a VERY BAD IDEA.

I won't do it next time, I promise :) !

**Comment by sebma** [comment] 2017-06-15 17:32
Until this feature request is implemented, I will use a little bash function I just created.
If anyone is interested, here is the code :) 

```
function condaRename {
    oldName=$1
    newName=$2
    test $# = 2 && {
        conda create --name $newName --clone $oldName
        conda remove --name $oldName --all
    }
}
```

**Comment by mat2py** [comment] 2017-06-30 23:37
Any progress with this?

**Comment by KelSolaar** [comment] 2017-07-10 21:08
Hi,

I wanted to add some information to that thread: I'm on Windows and have a conda environment with **pyinstaller** pip installed into it.

I used the above command to rename that environment, e.g.

``` bash
conda create --name python-2.7 --clone platform-windows
```

In the new *python-2.7* environment it turns out that the *pyinstaller.exe* executable was erroring:

```
Fatal error in launcher: Unable to create process using '"'
```

After hexadecimal inspection, it turns out that the executable embeds absolute path to the Python interpreter and it does not get updated when cloning the environment:

![image](https://user-images.githubusercontent.com/99779/28039954-34d0505c-6618-11e7-8433-d20c850730ea.png)

cheers,

Thomas

**Comment by cham11ng** [comment] 2017-07-11 18:13
I just renamed my old environment directory and it worked.

    mv ~/anaconda3/envs/old_name ~/anaconda3/envs/new_name

**Comment by pirtim** [comment] 2017-07-14 00:22
@ashander you can use `--offline` flag to disable hitting a network. Conda will just copy existing files from other envs.

**Comment by sebma** [comment] 2017-07-14 08:22
@cham11ng Oh that's strange. Can you please type these 2 commands and give us the result of the second one?
```
source activate new_name
which python python2 python3
```

**Comment by sebma** [comment] 2017-07-14 08:25
@pirtim Thanks for the tip :)

**Comment by cham11ng** [comment] 2017-07-14 17:34
it gives the path of environment's python location.

**Comment by sebma** [comment] 2017-07-15 09:09
@cham11ng Can you please be more precise and give the output of the `which python python2 python3` ?

**Comment by moble** [comment] 2017-07-24 17:43
@sebma I tried @cham11ng's approach, and it correctly gave me
```
> which python python2 python3
/Users/me/anaconda3/envs/out_of_core_fft/bin/python
/usr/local/bin/python2
/Users/me/anaconda3/envs/out_of_core_fft/bin/python3
```
However, the problem is that other scripts don't typically work.  For example `ipython` still fails, as you said above, because things like `ipython` don't get the message that the directory has changed.

Another (less-than-ideal) solution is to simply symbolically link the old directory to the new directory, rather than moving it.  Then, `ipython` still finds the right (old) directory, even though you're using the new name.  The only problem is that the old name still exists, and occupies that name's place.

**Comment by sebma** [comment] 2017-07-27 15:58
@moble Can you check ipython path with this command `which ipython ipython2 ipython3` ?

**Comment by moble** [comment] 2017-07-27 16:18
Same things, but with `i`s.  But now they work because they're just symbolic links to the originals, which point to other things in the original directory — which still exists.

**Comment by speleo3** [comment] 2017-10-06 06:36
(Cross posting this from [my post to the anaconda@continuum.io list](https://groups.google.com/a/continuum.io/d/msg/anaconda/tiTwrmjbp1E/e3DHVPg2AQAJ))

I've had sufficient success in creating a portable bundle based on Anaconda. I wrote [a shell script](https://anaconda.org/schrodinger/makeportable) that patches a couple of files and gets python scripts (shebang), PyQt and ssl working, independent of the absolute path of the bundle. This also works with renamed environments.

```
mv old_name new_name
conda install -y -n new_name -c schrodinger makeportable
bash new_name/make-portable.sh
```

**Comment by nnn144** [comment] 2018-02-05 14:30
It is bad to do like this:
`mv ~/anaconda3/envs/old_name ~/anaconda3/envs/new_name`

Because some executables in this environment have the environment path hardcoded. As far as I know, jupyter / Ipython does that. And this affect me a lot. Now my jupyter is messed up the packages and environment and I still have no idea how to fix my jupyter.

**Comment by velconia** [comment] 2018-05-16 06:14
Is there any progress with this Now?

**Comment by millett** [comment] 2018-07-11 21:22
Bump!

**Comment by chesucr** [comment] 2018-08-07 19:43
The equivalent on virtualenv would be [this](https://virtualenv.pypa.io/en/stable/userguide/#making-environments-relocatable)

    virtualenv --relocatable env_folder

But it is a experimental feature

**Comment by assafbental** [comment] 2018-08-30 14:08
Definitely a basic, needed feature, plus 1 and a bump.  Thanks

**Comment by assafbental** [comment] 2018-08-30 14:13
Definitely a basic, needed feature, plus 1 and a bump.  Thanks

**Comment by assaf-b** [comment] 2018-08-30 14:15
Definitely a basic, needed feature, +1 and a bump.  Thanks

**Comment by mingwandroid** [comment] 2018-08-30 15:08
This workaround may be useful?

```
conda activate OLD_NAME
conda env export > env.yaml
conda activate base
conda env create -n NEW_NAME -f env.yaml
rm -rf $CONDA_PREFIX/envs/OLD_NAME
```

**Comment by mingwandroid** [comment] 2018-08-30 15:08
And while moving an env may appear basic, it is far from it.

**Comment by TD22057** [comment] 2018-08-30 15:41
> And while moving an env may appear basic, it is far from it.

Agreed.  We have fairly complicated C++/python build/install system that uses conda.  As far as I can see, the only real way to handle this is to add a new script hook to the system to relocate a package.  The existing post install scripts assume they're starting from the original, unpackaged files and won't work on previously installed scripts (the fact that some package scripts may work has nothing to do with - it's not required and not every package behaves the same way).  Adding a new system to support a relocate script and then adding it to all the packages that need it seems like a lot of work when you can just reinstall in the new location.

**Comment by assaf-b** [comment] 2018-08-30 16:33
By basic, I didn't mean that it's simple, just that it is a useful primitive.  I obviously accept that Conda is a complicated feat, with inherent endless cases.

But why relocation is needed in the first place?  From what you guys say, I understand that conda does not use some intermediary env reference symbol in its metadata?

Let's see if I understand, take this unrelated example - someone coded a piece of "make" dev-ops system with direct references to some objects instead of using some global symbol, (for simplicity, say some "const myType& myRef=..." is missing from the metadata), now when he tries to change something, the metadata has to be scrutinized, instead of just changing the myRef line in it.  So *if relocation is necessary*, then it sounds like the metadata of the environment works like physical referencing, with no intermediate symbols in the metadata?

Obviously adding references across the metadata engine is a big task, that is why I am just adding my vote, for the powers that be to consider if the need is worth it.  But if referencing is redone then it eliminates the need for *relocation*.  I've seen it done in huge source control dev-op systems and in complicated "make" systems, and the bonus is significant and it alleviates so many end cases.

So if I'm wrong and the metadata already has a single reference to physical names and locations, then I would be interested in what is the real reason environment relocation is needed?
Thanks!

**Comment by mingwandroid** [comment] 2018-08-31 01:35
> But why relocation is needed in the first place? From what you guys say, I understand that conda does not use some intermediary env reference symbol in its metadata?

Relocation has little to do with metadata just that the information about what text and binary files need to be relocated is stored in each package's metadata.

The need for relocation is demonstrated very easily with this pseudo-C code:
```
static char config_file[] = PREFIX ## "/share/config";
void main() {
  fopen(install_prefix);
}
```

Here .PREFIX was passed in as the folder in which the software was configured to live in, so this software does no relocate itself. We need to actually patch these binaries with their actual installed location instead (or better, patch the upstream software to support relocation). Doing this is tricky, esp with C++11 and beyond.

We also relocate text files, but this is safer and easier.

**Comment by mingwandroid** [comment] 2018-08-31 21:10
I'm not sure what you mean. This had nothing to do with Python not pip. I have you a simple c example that illustrates the problem.

These subsequent questions suggest you didn't read or else didn't understand my example.

Since SSO (small string optimization) and in general with std::string there's a stored length variable to contend with and that requires some assumptions about the memory layout. Currently we do not attempt to detect and patch such strings, we pretend they are normal c strings instead.

**Comment by assaf-b** [comment] 2018-08-31 21:39
When an explanation I make doesn't go through, I check where I can fix the explanation, not attack the "explainee".  For instance, your example contained install_prefix, which doesn't seem to relate to either the PREFIX you concatenated, nor the config_file you defined, not syntactically and not semantically, at least for someone who doesn't already know conda's arch.  So for me, even for pseudo code this did not "compile" (pun intended), and therefore I filled out the blanks with what I knew from build systems I had to work with in the past.

As for C++11, I didn't expect the reason to be the usage of STL containers due to their extremely high performance drain (move semantics from C++11 just fixed a small part of their cost), interesting to know it's used, but now that's beside the point.

You have a right to be impatient, you volunteer your time to answer, having said that, with the tone where it is, perhaps we should end it here, I appreciate your time.

**Comment by H0R5E** [comment] 2018-08-31 22:10
Why not put the environments somewhere else (less obvious) and use symbolic links in the envs folder? Then renaming the environment would be a matter of regenerating the symbolic link and menu items for Windows, I guess.

I know this is a large structural change but it would decouple the name of an environment from its physical location.

Just a thought, you know, given the thread is on 🔥 right now.

**Comment by mingwandroid** [comment] 2018-08-31 22:26
This issue also nothing to do with the STL.

**Comment by mingwandroid** [comment] 2018-08-31 22:28
Conda cannot use symlinks because they are too opaque. To be explicit, software installed in a path where a folder conversations a symlink will behave differently should said software call readlink() on said path for any reason.

**Comment by H0R5E** [comment] 2018-08-31 22:32
Ok, does the name of an environment have to be the same as the folder which contains it? Is the issue about the use of conda or where it places stuff on disk?

**Comment by assaf-b** [comment] 2018-08-31 22:38
*You* mentioned std::string, it's an STL container with all the performance diseases that come with such containers to this day, hence I was surprised it's in use in conda.

**Comment by assaf-b** [comment] 2018-08-31 22:43
H0R5E, the response was not to you, it was to ming

**Comment by kalefranz** [comment] 2018-08-31 22:43
I think there's some misunderstanding and misinterpretation here.  Conda has no knowledge of `std::string`.

**Comment by assaf-b** [comment] 2018-08-31 22:44
Please see above comment by mingwandroid at https://github.com/conda/conda/issues/3097#issuecomment-417790065  it is his statement, not mine

**Comment by huanli2012** [comment] 2020-06-18 07:57
> Is it ok to just change the name of the folder under env?

That would result in error ` bad interpreter: anaconda3/envs/myenv/bin/python: no such file or directory` in my case if you `pip freeze | grep` some package.

**Comment by ahmedkhalf** [comment] 2020-07-03 12:09
+1

**Comment by simozanin** [comment] 2020-07-14 05:25
bump

**Comment by sathishkumark27** [comment] 2020-08-05 14:49
+1

**Comment by shailensobhee** [comment] 2020-10-01 22:30
Important basic feature that's missing since 4 years (and counting)! 
+1

**Comment by rumble-up** [comment] 2020-10-13 01:27
+1 
conda is great, thanks for all the hard work :) 
adding this feature would be a huge help

**Comment by wogong** [comment] 2020-11-15 13:28
+1

**Comment by CamiloMartinezM** [comment] 2021-01-07 07:15
+1

**Comment by dfucci** [comment] 2021-02-05 13:34
+1

**Comment by rohetoric** [comment] 2021-03-16 06:14
Any updates on how we can do this? This is really needed :zap:

**Comment by H0R5E** [comment] 2021-03-19 13:05
@rohetoric, I think the clone and remove approach [in the thread you listed](https://stackoverflow.com/a/42231765), is the best way of doing this, still.

The problem is [not trivial](https://github.com/conda/conda/issues/3097#issuecomment-417366027), because the name of the environment is it's path, and a number of packages are not portable to another path. This is why trying to simply rename the folder breaks things.

I guess conda could consider creating a shortcut called rename to do the clone and remove, but people might wonder why it's so involved.

**Comment by brando90** [comment] 2021-03-27 01:00
progress?

https://stackoverflow.com/questions/42231764/how-can-i-rename-a-conda-environment

**Comment by Lovkush-A** [comment] 2021-08-18 08:42
Can somebody from the conda team explain why this issue has not been resolved? Is it quite complex to change the name of an environment? Are there always more urgent issues?

(Tone is hard to convey in writing, I am genuinely asking out of curiosity, rather than rhetorically)

**Comment by Y-H-Joe** [comment] 2021-11-18 22:25
+1

**Comment by nikhilweee** [comment] 2021-12-07 08:52
@jezdez I see that the popular_feature tag was removed from the issue. I'm curious to know, is this request not popular anymore?

**Comment by H0R5E** [comment] 2021-12-07 09:47
@nikhilweee, it looks like that label no longer exists (for all issues).

**Comment by jezdez** [comment] 2021-12-07 13:32
> @jezdez I see that the popular_feature tag was removed from the issue. I'm curious to know, is this request not popular anymore?

Oh yikes, yeah, that's not what this was about. We recently started to redo our [ticket triaging process](https://github.com/orgs/conda/projects/4) and part of that was reviewing existing labels and streamlining it.

**Comment by MrPeterLee** [comment] 2022-04-04 02:39
+1

**Comment by kevinsuedmersen** [comment] 2022-04-29 13:13
I am constantly running into this use case and would really like to use the renaming feature

**Closed** 2022-07-16 20:35 UTC
Labels: type::feature, source::community, severity::4, sprint
