### ISSUE TITLE
env create failure on fresh Mac OS X install ("no requirements.txt")

### ISSUE THREAD

**Issue by mahmoud** [conda/conda#4073] opened 2016-12-14 21:46 UTC
On a fresh, CLI-based, 64-bit install of Anaconda, conda (v4.2.9) throws the following error when I run `~/anaconda2/bin/conda env create -n env`:

```
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/mahmoud/anaconda2  (writable)
    default environment : /Users/mahmoud/anaconda2
       envs directories : /Users/mahmoud/anaconda2/envs
          package cache : /Users/mahmoud/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /Users/mahmoud/anaconda2/bin/conda-env create -n env`




    Traceback (most recent call last):
      File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    SpecNotFound: Runtime error: Invalid name, try the format: user/package
    env does not exist or can't be accessed
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt
```

I'm pretty sure this worked before, so I'm not sure what, if anything, has changed.

**Comment by kalefranz** [comment] 2016-12-14 22:39
4.2.9 is probably what shipped with the last Anaconda Distribution installer.  Can you update to the latest 4.2 (I think 4.2.13) and make sure we haven't already fixed it?  This seems familiar and I think we might have squashed it already.

**Comment by mahmoud** [comment] 2016-12-14 22:55
Ah! Of course. Upgraded to 4.2.13 and I was so psyched, but alas:

```
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/mahmoud/anaconda2  (writable)
    default environment : /Users/mahmoud/anaconda2
       envs directories : /Users/mahmoud/anaconda2/envs
          package cache : /Users/mahmoud/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /Users/mahmoud/anaconda2/bin/conda-env create -n env`




    Traceback (most recent call last):
      File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    SpecNotFound: Runtime error: Invalid name, try the format: user/package
    env does not exist or can't be accessed
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

```

**Comment by kalefranz** [comment] 2016-12-14 23:29
Ok. Just released 4.3.0 into the conda-canary channel today. It'll be GA in a couple weeks. I might have stuck the fix in there. I'll look into it and backport to 4.2.x.

**Comment by mahmoud** [comment] 2016-12-14 23:36
Great, thanks!

**Comment by kalefranz** [comment] 2016-12-17 06:35
Hey Mahmoud.  I actually don't use the `conda env` commands much, and they haven't gotten much attention over this last year.  Hopefully I'll have time to swing through a lot of those in 2017.

I perfectly reproduced your stack trace on both 4.2.x and 4.3.x, but only when there wasn't an `environment.yml` file in my current working directory.  When I put an `environment.yml` file there, both branches seemed to work just fine.  Just used the simple `environment.yml` file [here](http://conda.pydata.org/docs/using/envs.html#create-environment-file-by-hand) to test.

I also tested by invoking `python -m conda env create -n env1`, but I don't think that would make a difference.

So are you sure you had an `environment.yml` file to start with?

If you were trying to just create a new, empty environment, use `conda create -n env`.  I know, it's all horribly confusing.  I'm not a fan some some of the UX.

**Comment by kalefranz** [comment] 2017-05-09 03:57
Duplicate of #3689

**Closed by kalefranz** 2017-05-09 03:57 UTC
