### ISSUE TITLE
503 errors when running conda update

### ISSUE THREAD

**Issue by desilinguist** [conda/conda#2561] opened 2016-05-27 11:36 UTC
All my CI builds have been failing since last night at midnight giving the 503 error about backend server being at full capacity.

**Comment by desilinguist** [comment] 2016-05-27 11:38
https://circleci.com/gh/EducationalTestingService/rsmtool/66

**Comment by freeman-lab** [comment] 2016-05-27 12:26
Seeing the same thing on TravisCI, for example:

https://travis-ci.org/thunder-project/thunder-extraction/jobs/133365621

**Comment by freeman-lab** [comment] 2016-05-27 12:39
Update: seems to be working again.

**Comment by desilinguist** [comment] 2016-05-27 13:09
Nope, now I am getting a timeout error instead (https://circleci.com/gh/EducationalTestingService/rsmtool/67)

**Comment by desilinguist** [comment] 2016-05-27 14:08
okay, my build seems to be passing again.

**Comment by kalefranz** [comment] 2016-05-27 14:50
Aware of the issue. Trying to figure out the cause now.

**Comment by kalefranz** [comment] 2016-05-27 15:38
We've added extra servers to repo.continuum.io.  Still investigating root cause.  Being tracked in other places though, so closing issue.

**Closed by kalefranz** 2016-05-27 15:38 UTC
