### ISSUE TITLE
MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content

### ISSUE THREAD

**Issue by goelakash** [conda/conda#8721] opened 2019-05-24 17:47 UTC
## Current Behavior

```
MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/ninja-1.9.0-py37h04f5b5a_0.tar.bz2'.
  download saved to: /Users/goelakas/miniconda3/pkgs/ninja-1.9.0-py37h04f5b5a_0.tar.bz2
  expected md5 sum: fe1108e627cb2da502035cc7fcbaa057
  actual md5 sum: 7ce56cb2933037d9bdfabcc9806b80bf

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/cffi-1.12.3-py37hb5b8e2f_0.tar.bz2'.
  download saved to: /Users/goelakas/miniconda3/pkgs/cffi-1.12.3-py37hb5b8e2f_0.tar.bz2
  expected md5 sum: 2c2eee77ea4c9d706c859019770b7975
  actual md5 sum: 7765ac64cccd111178448c35020e63b7

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/olefile-0.46-py37_0.tar.bz2'.
  download saved to: /Users/goelakas/miniconda3/pkgs/olefile-0.46-py37_0.tar.bz2
  expected md5 sum: fc596f43287f133029fc9dae9c270ff5
  actual md5 sum: 8ccdf16277b606cebea5461777ba3787

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/pillow-6.0.0-py37hb68e598_0.tar.bz2'.
  download saved to: /Users/goelakas/miniconda3/pkgs/pillow-6.0.0-py37hb68e598_0.tar.bz2
  expected md5 sum: b9b4ca4bb9ea9322463dbe00b46d53ff
  actual md5 sum: 24a39c468a818532e72ce6d4b1c70143

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.tar.bz2'.
  download saved to: /Users/goelakas/miniconda3/pkgs/libpng-1.6.37-ha441bb4_0.tar.bz2
  expected md5 sum: d69245a20ec59d8dc534c65308607129
  actual md5 sum: 256b1d19857d350dc549c64d6857c9a9
```

### Steps to Reproduce

Any install command
```
conda install pytorch torchvision -c pytorch
conda install -c auto epydoc
```

## Expected Behavior

The packages should be downloaded and installed

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : goelakas
    active env location : /Users/goelakas/miniconda3/envs/goelakas
            shell level : 2
       user config file : /Users/goelakas/.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /Users/goelakas/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/goelakas/miniconda3/pkgs
                          /Users/goelakas/.conda/pkgs
       envs directories : /Users/goelakas/miniconda3/envs
                          /Users/goelakas/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 2085706504:1896053708
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

Empty
```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/goelakas/miniconda3/envs/goelakas:
#
# Name                    Version                   Build  Channel
astroid                   2.2.5                    py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.0.2                    py37_0    defaults
bokeh                     0.13.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
decorator                 4.3.0                    py37_0    defaults
defusedxml                0.5.0                    py37_1    defaults
entrypoints               0.2.3                    py37_2    defaults
intel-openmp              2019.0                      118    defaults
ipython_genutils          0.2.0                    py37_0    defaults
isort                     4.3.18                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jsonschema                2.6.0                    py37_0    defaults
jupyter_client            5.2.3                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
lazy-object-proxy         1.4.0            py37h1de35cc_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
markupsafe                1.0              py37h1de35cc_1    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.6            py37hb8a8100_0    defaults
mkl_random                1.0.1            py37h5d10147_1    defaults
nbconvert                 5.4.0                    py37_1    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_0    defaults
numpy                     1.15.2           py37h6a91979_1    defaults
numpy-base                1.15.2           py37h8a80b8c_1    defaults
openssl                   1.1.1b               h1de35cc_1    defaults
packaging                 18.0                     py37_0    defaults
pandas                    0.23.4           py37h6440ff4_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2                    py37_1    defaults
pip                       10.0.1                   py37_0    defaults
pygments                  2.2.0                    py37_0    defaults
pylint                    2.3.1                    py37_0    defaults
pyparsing                 2.2.2                    py37_0    defaults
python                    3.7.1                haf84260_3    defaults
python-dateutil           2.7.3                    py37_0    defaults
pytz                      2018.5                   py37_0    defaults
pyyaml                    3.13             py37h1de35cc_0    defaults
pyzmq                     17.1.2           py37h1de35cc_0    defaults
readline                  7.0                  h1de35cc_5    defaults
setuptools                40.4.3                   py37_0    defaults
six                       1.11.0                   py37_1    defaults
sqlite                    3.25.2               ha441bb4_0    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tornado                   5.1.1            py37h1de35cc_0    defaults
traitlets                 4.3.2                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.32.1                   py37_0    defaults
wrapt                     1.11.1           py37h1de35cc_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h0a44026_1    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

**Comment by goelakash** [comment] 2019-05-24 17:48
I see other issues where edge-cache was causing the problems.
E.g.: https://github.com/conda/conda/issues/6121

**Comment by msarahan** [comment] 2019-05-24 17:51
yes, duplicate of #8720 - please see that issue.  This should be resolved, but you might need to ``conda clean -iy`` to clean out your local cached index.

**Closed by msarahan** 2019-05-24 17:51 UTC

**Comment by petguy** [comment] 2019-05-24 17:55
Having similar/same issue using $conda udpate conda
Also ran $conda clean -iy and still get same error
Note: this is a new installation of anaconda, so I was surprised that it even told me there was an update. The same error occurs when trying $conda install any modules for me (and this is after the $conda clean -iy)

$ conda update conda
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /anaconda2

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.6.14               |           py27_0         1.9 MB
    ------------------------------------------------------------
                                           Total:         1.9 MB

The following packages will be UPDATED:

  conda                                       4.6.11-py27_0 --> 4.6.14-py27_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.6.14         | 1.9 MB    | ###########################7          |  75% 

CondaMultiError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/conda-4.6.14-py27_0.tar.bz2'.
  download saved to: /anaconda2/pkgs/conda-4.6.14-py27_0.tar.bz2
  expected md5 sum: 25e78605b04f86b2b8a5faee3c080101
  actual md5 sum: c2db5f750725ea6647cadf61f35d5071

**Comment by jmoober** [comment] 2019-05-24 18:07
Seeing same behavior as @petguy.

**Comment by laiviet** [comment] 2019-05-24 18:07
I had a similar issue.  Anyone got it fixed?

**Comment by GandalfSaxe** [comment] 2019-05-24 19:11
Same issue with command `conda create -n myenv python=2.7`

**Comment by msarahan** [comment] 2019-05-24 19:20
https://github.com/conda/conda/issues/8720#issuecomment-495756977

**Comment by msarahan** [comment] 2019-05-24 19:27
reverted repodata is in place. If the problem persists, try ``conda clean -iy`` - if that still doesn't work, let us know.

**Comment by lmeyerov** [comment] 2019-09-30 06:26
@msarahan Hitting this now..

**Comment by lmeyerov** [comment] 2019-09-30 06:47
In particular:
```
amazon-ebs: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
    amazon-ebs: for url 'https://conda.anaconda.org/rapidsai/label/xgboost/noarch/dask-xgboost-0.2.0.dev28-cuda10.0py37_0.tar.bz2'.
    amazon-ebs:   download saved to: /opt/conda/pkgs/dask-xgboost-0.2.0.dev28-cuda10.0py37_0.tar.bz2
    amazon-ebs:   expected md5 sum: 2454fb1a643b01a1150078f3e428cc40
    amazon-ebs:   actual md5 sum: 509cf7f8d660763ad73cf0ebc2ebccc3
    ama
```

**Comment by lmeyerov** [comment] 2019-10-02 00:07
Worked around on our side: we had to change repo order in `conda install -c repo1 -c repo2 ...`. Something still smells wrong where an error reports the same repo has mismatching checksums, however.

**Comment by forrestwaters** [comment] 2019-10-02 00:17
@lmeyerov the original problem in this issue was temporary due to bad repodata and is no longer a problem. If you are seeing the above consistently, can you please open a new issue with all the details filled out (steps to reproduce, etc.)? Thanks!

**Comment by msarahan** [comment] 2019-10-02 01:04
Note that incomplete or corrupted downloads are generally the cause of this problem, and a retry is the best remedy.  Debugging random corruption not a productive use of anyone's time - it just has way too many hard-to-reproduce potential causes.  As @forrestwaters mentioned, your problem appears different from the original issue here.

**Comment by lmeyerov** [comment] 2019-10-02 01:15
cc @mike-wendt in case this recurs on your end. (I assume nvidia testing included xgboost so a partial download is surprising, but who knows!)

**Comment by lmeyerov** [comment] 2019-10-02 01:18
For historic purposes, here is the repeatable bug:

1. Fails w/ md5checksum condaforge issue:

`Dockerfile`:
```
FROM rapidsai/rapidsai:0.9-cuda10.0-base-ubuntu18.04

ENV DEBIAN_FRONTEND noninteractive

RUN echo "start" \
  && conda clean -ayqv \
  && conda env list \
  && source activate rapids \
  && conda env list \
  && mkdir /blazingsql \
  && conda install -y \
    -c blazingsql/label/cuda10.0 \
    -c blazingsql \
    -c rapidsai \
    -c nvidia \
    -c conda-forge \
    -c defaults \
    blazingsql-calcite \
    blazingsql-orchestrator \
    blazingsql-ral \
    blazingsql-python

RUN pip install flatbuffers
```

`docker build .`

2. Succeeds (adds missing repo):
```
FROM rapidsai/rapidsai:0.9-cuda10.0-base-ubuntu18.04

ENV DEBIAN_FRONTEND noninteractive

RUN echo "start" \
  && conda clean -ayqv \
  && conda env list \
  && source activate rapids \
  && conda env list \
  && mkdir /blazingsql \
  && conda install -y \
    -c blazingsql/label/cuda10.0 \
    -c blazingsql \
    -c rapidsai/label/xgboost \
    -c rapidsai \
    -c nvidia \
    -c conda-forge \
    -c defaults \
    blazingsql-calcite \
    blazingsql-orchestrator \
    blazingsql-ral \
    blazingsql-python

RUN pip install flatbuffers
```

**Comment by msarahan** [comment] 2019-10-02 01:24
One thing we see now and again is a race condition with packages uploaded to anaconda.org.  There may be a package that has duplicate records with different hashes, and we can investigate and clean that up.  CC @soapy1
