### ISSUE TITLE
conda exits .bat script prematurely

### ISSUE THREAD

**Issue by fredrikaverpil** [conda/conda#7139] opened 2018-04-09 10:06 UTC
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

When running the .bat file below, the second command never gets executed, as conda exits the script prematurely even if the command was successfully executed without any errors.

```
# envinstall.bat
conda create --yes --mkdir -p C:\Users\fredrik\customenvs\envone python=2.7
conda create --yes --mkdir -p C:\Users\fredrik\customenvs\envtwo python=3.5 pyside2
```

### Steps to Reproduce

Just run the bat script above on Windows 10 (with admin privileges).

## Expected Behavior

The first conda command should run, then the next one.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\iruser\.condarc
 populated config files : C:\Users\iruser\.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\iruser\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\iruser\AppData\Local\conda\conda\envs
                          C:\Users\iruser\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\iruser\.condarc <==
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\ProgramData\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.11.4           py36hfa6e2cd_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
conda                     4.5.0                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.1.4            py36he1d7878_0    defaults
idna                      2.6              py36h148d497_1    defaults
menuinst                  1.4.11           py36hfa6e2cd_0    defaults
openssl                   1.0.2o               h8ea7d77_0    defaults
pip                       9.0.1            py36h226ae91_4    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
python                    3.6.4                h6538335_1    defaults
pywin32                   222              py36hfa6e2cd_0    defaults
requests                  2.18.4           py36h4371aae_1    defaults
ruamel_yaml               0.15.35          py36hfa6e2cd_1    defaults
setuptools                38.4.0                   py36_0    defaults
six                       1.11.0           py36h4db2310_1    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2015_runtime            14.0.25123                    3    defaults
wheel                     0.30.0           py36h6c3ec14_1    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
```
</p></details>

**Comment by kalefranz** [comment] 2018-04-09 11:03
The first `conda` on `PATH` is now `conda.bat` as of conda 4.4.0.  That means you need to either change your `envinstall.bat` script to

```
# envinstall.bat
CALL conda create --yes --mkdir -p C:\Users\fredrik\customenvs\envone python=2.7
CALL conda create --yes --mkdir -p C:\Users\fredrik\customenvs\envtwo python=3.5 pyside2
```

or

```
# envinstall.bat
conda.exe create --yes --mkdir -p C:\Users\fredrik\customenvs\envone python=2.7
conda.exe create --yes --mkdir -p C:\Users\fredrik\customenvs\envtwo python=3.5 pyside2
```

In the future, we'll be encouraging the *correct* way to do this under the 'Anaconda Prompt' as

```
# envinstall.bat
"%CONDA_EXE%" create --yes --mkdir -p C:\Users\fredrik\customenvs\envone python=2.7
"%CONDA_EXE%" create --yes --mkdir -p C:\Users\fredrik\customenvs\envtwo python=3.5 pyside2
```

although that will only apply for conda 4.6 and onward.

**Comment by fredrikaverpil** [comment] 2018-04-09 13:12
Ah, excellent. Thank you!
Should I/we close this issue?

**Comment by kalefranz** [comment] 2018-04-13 05:26
This issue is being left open as a reminder to ensure we have `CONDA_EXE` exported as an environment variable with each individual shell wrapper.

**Comment by kalefranz** [comment] 2018-04-24 12:33
Last note indicates this is now a duplicate of #7126.

**Closed by kalefranz** 2018-04-24 12:33 UTC
