### ISSUE TITLE
conda run python in it's own activated environment not using proper python

### ISSUE THREAD

**Issue by paw-lu** [conda/conda#9571] opened 2020-01-08 18:00 UTC
## Current Behavior

In conda 4.8.1 and 4.8.0, when using `conda run` from inside its own activated environment, it does not use the specified environment.

### Steps to Reproduce

With the file `script.py`

```python
import sys

print(sys.path)
```

```shell
base ❯ conda run -n env_name python script.py 
['/Users/pcosta/miniconda3/envs/env_name/lib/python37.zip', '/Users/pcosta/miniconda3/envs/env_name/lib/python3.7', '/Users/pcosta/miniconda3/envs/env_name/lib/python3.7/lib-dynload', '/Users/pcosta/miniconda3/envs/env_name/lib/python3.7/site-packages']

base ❯ conda activate env_name

env_name ❯ python script.py
['/Users/pcosta/miniconda3/envs/env_name/lib/python37.zip', '/Users/pcosta/miniconda3/envs/env_name/lib/python3.7', '/Users/pcosta/miniconda3/envs/env_name/lib/python3.7/lib-dynload', '/Users/pcosta/miniconda3/envs/env_name/lib/python3.7/site-packages']

env_name ❯ conda run -n env_name python script.py
['/Users/pcosta/miniconda3/lib/python37.zip', '/Users/pcosta/miniconda3/lib/python3.7', '/Users/pcosta/miniconda3/lib/python3.7/lib-dynload', '/Users/pcosta/miniconda3/lib/python3.7/site-packages']
```

## Expected Behavior

`conda run` should always use Python environment specified in argument.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : env_name
    active env location : /Users/pcosta/miniconda3/envs/env_name
            shell level : 2
       user config file : /Users/pcosta/.condarc
 populated config files : /Users/pcosta/.condarc
          conda version : 4.8.1
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __osx=10.14.4
       base environment : /Users/pcosta/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/plotly/osx-64
                          https://conda.anaconda.org/plotly/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/pcosta/miniconda3/pkgs
                          /Users/pcosta/.conda/pkgs
       envs directories : /Users/pcosta/miniconda3/envs
                          /Users/pcosta/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.3 Darwin/18.5.0 OSX/10.14.4
                UID:GID : 1058790558:1165330761
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/pcosta/.condarc <==
auto_activate_base: False
ssl_verify: False
proxy_servers:
  http: {my_address}
  https: {my_address}
channels:
  - plotly
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/pcosta/miniconda3/envs/env_name:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0    anaconda
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0                 py37_1000    conda-forge
asn1crypto                0.24.0                   py37_0    anaconda
astor                     0.7.1                      py_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
azure-common              1.1.23                   pypi_0    pypi
azure-storage-blob        2.1.0                    pypi_0    pypi
azure-storage-common      2.1.0                    pypi_0    pypi
babel                     2.7.0                      py_0    anaconda
backcall                  0.1.0                      py_0    conda-forge
black                     19.3b0                     py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boto3                     1.9.249                  pypi_0    pypi
botocore                  1.12.249                 pypi_0    pypi
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.12.3           py37hb5b8e2f_0    anaconda
chardet                   3.0.4                 py37_1003    anaconda
click                     7.0                        py_0    conda-forge
commonmark                0.9.0                      py_0    conda-forge
cryptography              2.7              py37ha12b0ac_0    anaconda
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
doc8                      0.8.0                      py_2    conda-forge
docutils                  0.15.2                   py37_0    anaconda
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
flake8                    3.7.8                    py37_1    conda-forge
flake8-bugbear            19.8.0                     py_0    conda-forge
flake8-docstrings         1.5.0                    pypi_0    pypi
flake8-mypy               17.8.0                   pypi_0    pypi
freetds                   1.1rc3               h6ad6909_1    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
future                    0.17.1                py37_1000    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                      py37_0    anaconda
ijson                     2.5.1                    pypi_0    pypi
imagesize                 1.1.0                    py37_0    anaconda
importlib_metadata        0.22                     py37_0    conda-forge
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                    pypi_0    pypi
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.2                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.1.0            py37ha1b3eb9_0    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcxx                    9.0.0                h89e68fa_1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h4bb4525_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h11da6c2_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h1de35cc_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
mypy                      0.720                    pypi_0    pypi
mypy-extensions           0.4.1                    pypi_0    pypi
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
numpy                     1.17.2           py37h6b0580a_0    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.25.1           py37h86efe34_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pbr                       5.4.2                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pendulum                  2.0.5                    py37_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.2.3                   py37_0    conda-forge
plotly                    4.1.1                      py_0    plotly
pluggy                    0.13.0                   py37_0    conda-forge
pockets                   0.7.2                      py_0    conda-forge
pony                      0.7.10                   pypi_0    pypi
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyarrow                   0.15.0                   pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py37_0    anaconda
pycryptodomex             3.9.0                    pypi_0    pypi
pydocstyle                4.0.1                    pypi_0    pypi
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyjwt                     1.7.1                    pypi_0    pypi
pyodbc                    4.0.27           py37h6de7cb9_0    conda-forge
pyopenssl                 19.0.0                   py37_0    anaconda
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_4    conda-forge
pyrsistent                0.15.4           py37h01d97ff_0    conda-forge
pysocks                   1.7.0                    py37_0    anaconda
pytest                    5.1.2                    py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pytzdata                  2019.3                     py_0    conda-forge
pyyaml                    5.1.2                    pypi_0    pypi
pyzmq                     18.1.0           py37hee98d25_0    conda-forge
qt                        5.9.7                h8cf7e54_3    conda-forge
qtconsole                 4.5.5                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
recommonmark              0.6.0                      py_0    conda-forge
requests                  2.22.0                   py37_0    anaconda
restructuredtext_lint     1.3.0                      py_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
s3transfer                0.2.1                    pypi_0    pypi
scipy                     1.3.2            py37h82752d6_0    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
sip                       4.19.8          py37h0a44026_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.9.0                      py_0    anaconda
snowflake-connector-python 2.0.1                    pypi_0    pypi
sphinx                    2.1.2                      py_0    anaconda
sphinx-theme-material     1.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                      py_0    anaconda
sphinxcontrib-devhelp     1.0.1                      py_0    anaconda
sphinxcontrib-htmlhelp    1.0.2                      py_0    anaconda
sphinxcontrib-jsmath      1.0.1                      py_0    anaconda
sphinxcontrib-napoleon    0.7                        py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    anaconda
sphinxcontrib-serializinghtml 1.1.3                      py_0    anaconda
sqlite                    3.29.0               hb7d70f7_1    conda-forge
statsmodels               0.10.1           py37h3b54f70_2    conda-forge
stevedore                 1.30.1                     py_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h01d97ff_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
typed-ast                 1.4.0                    pypi_0    pypi
typing-extensions         3.7.4                    pypi_0    pypi
unixodbc                  2.3.7                h1de35cc_0    anaconda
urllib3                   1.24.2                   py37_0    anaconda
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge
```
</p></details>

**Comment by nfearnley** [comment] 2020-01-10 21:30
This seems to be the same issue as #9587 9587

**Comment by kenodegard** [comment] 2022-03-10 19:26
Duplicate of https://github.com/conda/conda/issues/11174

**Closed by kenodegard** 2022-03-10 19:26 UTC
Labels: type::bug, source::community, plugins::run, duplicate
