### ISSUE TITLE
Latest conda spews massive amounts of debug info?

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#3205] opened 2016-08-01 23:38 UTC
e.g.
```
λ conda install --force widgetsnbextension
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...INFO:stdoutlog:Fetching package metadata ...
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
.INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x0000000005724860>}
.DEBUG:dotupdate:fetching repodata: args ('https://conda.anaconda.org/t/dh-c16df99b-6f5f-4a0f-beab-a481db490556/conda-forge/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x000000000572B780>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/win-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x00000000057244E0>}
.DEBUG:dotupdate:fetching repodata: args ('https://conda.anaconda.org/t/dh-c16df99b-6f5f-4a0f-beab-a481db490556/dhirschfeld/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x0000000005702E48>}
.DEBUG:dotupdate:fetching repodata: args ('https://conda.anaconda.org/t/dh-c16df99b-6f5f-4a0f-beab-a481db490556/dhirschfeld/win-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x00000000056FAB70>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x00000000056FAB00>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/msys2/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x0000000005724FD0>}
.DEBUG:dotupdate:fetching repodata: args ('https://conda.anaconda.org/t/dh-c16df99b-6f5f-4a0f-beab-a481db490556/conda-forge/win-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x000000000572B3C8>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/msys2/win-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x0000000005724C18>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/win-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x0000000005707780>}

INFO:stdoutlog:

Solving package specifications: INFO:stdoutlog:Solving package specifications:
.DEBUG:dotupdate:Solving for [MatchSpec('widgetsnbextension'), MatchSpec('python 3.5* (target=python-3.5.2-0.tar.bz2)'), MatchSpec('conda >=4.1.11'), MatchSpec('conda-env'), MatchSpec('pip (target=pip-8.1.2-py35_0.tar.bz2)'), MatchSpec('pycosat (target=pycosat-0.6.1-py35_1.tar.bz2)'), MatchSpec('scikit-image (target=scikit-image-0.12.3-np111py35_1.tar.bz2)'), MatchSpec('pywin32 (target=pywin32-220-py35_1.tar.bz2)'), MatchSpec('comtypes (target=comtypes-1.1.2-py35_0.tar.bz2)'), MatchSpec('sqlalchemy (target=sqlalchemy-1.0.13-py35_0.tar.bz2)'), MatchSpec('entrypoints (target=entrypoints-0.2.2-py35_0.tar.bz2)'), MatchSpec('pycparser (target=pycparser-2.14-py35_1.tar.bz2)'), MatchSpec('bzip2 (target=bzip2-1.0.6-vc14_3.tar.bz2)'), MatchSpec('pytest (target=pytest-2.9.2-py35_0.tar.bz2)'), MatchSpec('gevent (target=gevent-1.1.2-py35_0.tar.bz2)'), MatchSpec('markupsafe (target=markupsafe-0.23-py35_2.tar.bz2)'), MatchSpec('r-irdisplay (target=mro::r-irdisplay-0.3-r3.2._0a.tar.bz2)'), MatchSpec('beautifulsoup4 (target=beautifulsoup4-4.4.1-py35_0.tar.bz2)'), MatchSpec('boto (target=boto-2.40.0-py35_0.tar.bz2)'), MatchSpec('console_shortcut (target=console_shortcut-0.1.1-py35_1.tar.bz2)'), MatchSpec('r-xts (target=mro::r-xts-0.9_7-r3.2._0a.tar.bz2)'), MatchSpec('mkl-service (target=mkl-service-1.1.2-py35_2.tar.bz2)'), MatchSpec('r-reshape2 (target=mro::r-reshape2-1.4.1-r3.2._1a.tar.bz2)'), MatchSpec('r-chron (target=mro::r-chron-2.3_47-r3.2._0a.tar.bz2)'), MatchSpec('pylint (target=pylint-1.5.4-py35_0.tar.bz2)'), MatchSpec('backports.shutil_get_terminal_size (target=conda-forge::backports.shutil_get_terminal_size-1.0.0-py35_0.tar.bz2)'), MatchSpec('jupyter_console (target=jupyter_console-5.0.0-py35_0.tar.bz2)'), MatchSpec('scipy (target=scipy-0.17.1-np111py35_1.tar.bz2)'), MatchSpec('imagesize (target=imagesize-0.7.1-py35_0.tar.bz2)'), MatchSpec('r-rjsonio (target=mro::r-rjsonio-1.3_0-r3.2._1a.tar.bz2)'), MatchSpec('logilab-common (target=logilab-common-1.0.2-py35_0.tar.bz2)'), MatchSpec('jdcal (target=jdcal-1.2-py35_1.tar.bz2)'), MatchSpec('pyzmq (target=pyzmq-15.3.0-py35_0.tar.bz2)'), MatchSpec('r-digest (target=mro::r-digest-0.6.8-r3.2._2a.tar.bz2)'), MatchSpec('colorama (target=colorama-0.3.7-py35_0.tar.bz2)'), MatchSpec('ipython-qtconsole (target=ipython-qtconsole-4.0.1-py35_4.tar.bz2)'), MatchSpec('mpmath (target=mpmath-0.19-py35_1.tar.bz2)'), MatchSpec('ipykernel (target=ipykernel-4.3.1-py35_0.tar.bz2)'), MatchSpec('qgrid (target=qgrid-0.3.1-py35_0.tar.bz2)'), MatchSpec('pyqt (target=pyqt-4.11.4-py35_7.tar.bz2)'), MatchSpec('r-knitr (target=mro::r-knitr-1.11-r3.2._0a.tar.bz2)'), MatchSpec('wrapt (target=wrapt-1.10.6-py35_0.tar.bz2)'), MatchSpec('numpydoc (target=numpydoc-0.5-py35_1.tar.bz2)'), MatchSpec('r-plyr (target=mro::r-plyr-1.8.3-r3.2._0a.tar.bz2)'), MatchSpec('pyasn1 (target=pyasn1-0.1.9-py35_0.tar.bz2)'), MatchSpec('cython (target=cython-0.24.1-py35_0.tar.bz2)'), MatchSpec('r-repr (target=mro::r-repr-0.3-r3.2._0a.tar.bz2)'), MatchSpec('r-rzmq (target=mro::r-rzmq-0.7.7-r3.2._1a.tar.bz2)'), MatchSpec('flask (target=flask-0.11.1-py35_0.tar.bz2)'), MatchSpec('futures (target=futures-3.0.3-py35_0.tar.bz2)'), MatchSpec('anaconda-navigator (target=anaconda-navigator-1.2.2-py35_0.tar.bz2)'), MatchSpec('r-scales (target=mro::r-scales-0.3.0-r3.2._0a.tar.bz2)'), MatchSpec('r-nloptr (target=mro::r-nloptr-1.0.4-r3.2._1a.tar.bz2)'), MatchSpec('r-highr (target=mro::r-highr-0.5.1-r3.2._0a.tar.bz2)'), MatchSpec('qtconsole (target=qtconsole-4.2.1-py35_0.tar.bz2)'), MatchSpec('tornado (target=tornado-4.4.1-py35_0.tar.bz2)'), MatchSpec('setuptools_scm (target=conda-forge::setuptools_scm-1.11.1-py35_0.tar.bz2)'), MatchSpec('msgpack-python (target=msgpack-python-0.4.7-py35_0.tar.bz2)'), MatchSpec('r-data.table (target=mro::r-data.table-1.9.6-r3.2._0a.tar.bz2)'), MatchSpec('r-randomforest (target=mro::r-randomforest-4.6_12-r3.2._0a.tar.bz2)'), MatchSpec('mingw (target=mingw-4.7-1.tar.bz2)'), MatchSpec('seaborn (target=seaborn-0.7.0-py35_0.tar.bz2)'), MatchSpec('r-sparsem (target=mro::r-sparsem-1.7-r3.2._0a.tar.bz2)'), MatchSpec('setuptools (target=setuptools-23.0.0-py35_0.tar.bz2)'), MatchSpec('path.py (target=path.py-8.2.1-py35_0.tar.bz2)'), MatchSpec('r-glmnet (target=mro::r-glmnet-2.0_2-r3.2._0a.tar.bz2)'), MatchSpec('cycler (target=cycler-0.10.0-py35_0.tar.bz2)'), MatchSpec('tk (target=conda-forge::tk-8.5.19-vc14_0.tar.bz2)'), MatchSpec('cytoolz (target=cytoolz-0.8.0-py35_0.tar.bz2)'), MatchSpec('pyopenssl (target=pyopenssl-16.0.0-py35_0.tar.bz2)'), MatchSpec('libsodium (target=libsodium-1.0.3-0.tar.bz2)'), MatchSpec('msvc_runtime (target=msvc_runtime-1.0.1-vc14_0.tar.bz2)'), MatchSpec('r-assertthat (target=mro::r-assertthat-0.1-r3.2._1a.tar.bz2)'), MatchSpec('pyflakes (target=pyflakes-1.2.3-py35_0.tar.bz2)'), MatchSpec('scikit-learn (target=scikit-learn-0.17.1-np111py35_1.tar.bz2)'), MatchSpec('dask (target=conda-forge::dask-0.10.2-py35_0.tar.bz2)'), MatchSpec('pickleshare (target=pickleshare-0.7.3-py35_0.tar.bz2)'), MatchSpec('h5py (target=h5py-2.6.0-np111py35_0.tar.bz2)'), MatchSpec('xlwings (target=xlwings-0.7.2-py35_0.tar.bz2)'), MatchSpec('pyodbc (target=pyodbc-3.0.10-py35_0.tar.bz2)'), MatchSpec('sockjs-tornado (target=sockjs-tornado-1.0.3-py35_0.tar.bz2)'), MatchSpec('pillow (target=pillow-3.2.0-py35_1.tar.bz2)'), MatchSpec('pytables (target=pytables-3.2.2-np111py35_4.tar.bz2)'), MatchSpec('r-quantmod (target=mro::r-quantmod-0.4_5-r3.2._0a.tar.bz2)'), MatchSpec('r-tidyr (target=mro::r-tidyr-0.3.1-r3.2._0a.tar.bz2)'), MatchSpec('node-webkit (target=node-webkit-0.10.1-0.tar.bz2)'), MatchSpec('r-quantreg (target=mro::r-quantreg-5.19-r3.2._0a.tar.bz2)'), MatchSpec('numexpr (target=numexpr-2.6.1-np111py35_0.tar.bz2)'), MatchSpec('r-proto (target=mro::r-proto-0.3_10-r3.2._1a.tar.bz2)'), MatchSpec('cryptography (target=cryptography-1.4-py35_0.tar.bz2)'), MatchSpec('nbformat (target=nbformat-4.0.1-py35_0.tar.bz2)'), MatchSpec('r-rcpp (target=mro::r-rcpp-0.12.2-r3.2._0a.tar.bz2)'), MatchSpec('alabaster (target=conda-forge::alabaster-0.7.9-py35_0.tar.bz2)'), MatchSpec('pyreadline (target=pyreadline-2.1-py35_0.tar.bz2)'), MatchSpec('r-catools (target=mro::r-catools-1.17.1-r3.2._2a.tar.bz2)'), MatchSpec('r-httpuv (target=mro::r-httpuv-1.3.3-r3.2._0a.tar.bz2)'), MatchSpec('r-htmltools (target=mro::r-htmltools-0.2.6-r3.2._2a.tar.bz2)'), MatchSpec('r-lme4 (target=mro::r-lme4-1.1_10-r3.2._0a.tar.bz2)'), MatchSpec('r-r6 (target=mro::r-r6-2.1.1-r3.2._0a.tar.bz2)'), MatchSpec('conda-build (target=conda-forge::conda-build-1.21.9-py35_0.tar.bz2)'), MatchSpec('ipython_genutils (target=ipython_genutils-0.1.0-py35_0.tar.bz2)'), MatchSpec('r-ttr (target=mro::r-ttr-0.23_0-r3.2._0a.tar.bz2)'), MatchSpec('boto3 (target=boto3-1.3.1-py35_0.tar.bz2)'), MatchSpec('feather-format (target=dhirschfeld::feather-format-0.2.0.post007+g36c328e-py35_0.tar.bz2)'), MatchSpec('r-matrixmodels (target=mro::r-matrixmodels-0.4_1-r3.2._0a.tar.bz2)'), MatchSpec('libdynd (target=libdynd-0.7.2-0.tar.bz2)'), MatchSpec('r-formatr (target=mro::r-formatr-1.2.1-r3.2._0a.tar.bz2)'), MatchSpec('fastcache (target=fastcache-1.0.2-py35_1.tar.bz2)'), MatchSpec('r-irkernel (target=mro::r-irkernel-0.5-r3.2._1a.tar.bz2)'), MatchSpec('astropy (target=astropy-1.2.1-np111py35_0.tar.bz2)'), MatchSpec('traitlets (target=traitlets-4.2.2-py35_0.tar.bz2)'), MatchSpec('unicodecsv (target=unicodecsv-0.14.1-py35_0.tar.bz2)'), MatchSpec('cffi (target=cffi-1.6.0-py35_0.tar.bz2)'), MatchSpec('r-munsell (target=mro::r-munsell-0.4.2-r3.2._1a.tar.bz2)'), MatchSpec('openpyxl (target=openpyxl-2.3.2-py35_0.tar.bz2)'), MatchSpec('r-mime (target=mro::r-mime-0.4-r3.2._0a.tar.bz2)'), MatchSpec('wcwidth (target=wcwidth-0.1.7-py35_0.tar.bz2)'), MatchSpec('flask-cors (target=flask-cors-2.1.2-py35_0.tar.bz2)'), MatchSpec('botocore (target=conda-forge::botocore-1.4.41-py35_0.tar.bz2)'), MatchSpec('launcher (target=launcher-1.0.0-4.tar.bz2)'), MatchSpec('r-rbokeh (target=mro::r-rbokeh-0.2.2-r3.2._0a.tar.bz2)'), MatchSpec('xlwt (target=xlwt-1.1.2-py35_0.tar.bz2)'), MatchSpec('configobj (target=configobj-5.0.6-py35_0.tar.bz2)'), MatchSpec('openssl (target=openssl-1.0.2h-vc14_0.tar.bz2)'), MatchSpec('freetype (target=freetype-2.5.5-vc14_1.tar.bz2)'), MatchSpec('locket (target=locket-0.2.0-py35_1.tar.bz2)'), MatchSpec('snowballstemmer (target=snowballstemmer-1.2.1-py35_0.tar.bz2)'), MatchSpec('html5lib (target=html5lib-0.999-py35_0.tar.bz2)'), MatchSpec('line_profiler (target=line_profiler-1.0-py35_1.tar.bz2)'), MatchSpec('pyyaml (target=pyyaml-3.11-py35_4.tar.bz2)'), MatchSpec('r-shiny (target=mro::r-shiny-0.12.2-r3.2._0a.tar.bz2)'), MatchSpec('pygments (target=pygments-2.1.3-py35_0.tar.bz2)'), MatchSpec('nose (target=nose-1.3.7-py35_1.tar.bz2)'), MatchSpec('r-maps (target=mro::r-maps-3.0.0_2-r3.2._0a.tar.bz2)'), MatchSpec('sphinx_rtd_theme (target=sphinx_rtd_theme-0.1.9-py35_0.tar.bz2)'), MatchSpec('bokeh (target=bokeh-0.12.1-py35_0.tar.bz2)'), MatchSpec('vega (target=conda-forge::vega-0.4.1-py35_2.tar.bz2)'), MatchSpec('bottleneck (target=bottleneck-1.1.0-np111py35_0.tar.bz2)'), MatchSpec('pandas (target=pandas-0.18.1-np111py35_0.tar.bz2)'), MatchSpec('r-rmarkdown (target=mro::r-rmarkdown-0.8.1-r3.2._0a.tar.bz2)'), MatchSpec('click (target=click-6.6-py35_0.tar.bz2)'), MatchSpec('r-uuid (target=mro::r-uuid-0.1_2-r3.2._0a.tar.bz2)'), MatchSpec('cloudpickle (target=cloudpickle-0.2.1-py35_0.tar.bz2)'), MatchSpec('backports (target=backports-1.0-py35_0.tar.bz2)'), MatchSpec('greenlet (target=greenlet-0.4.10-py35_0.tar.bz2)'), MatchSpec('menuinst (target=menuinst-1.4.1-py35_0.tar.bz2)'), MatchSpec('r-jsonlite (target=mro::r-jsonlite-0.9.17-r3.2._0a.tar.bz2)'), MatchSpec('spyder (target=spyder-2.3.8-py35_1.tar.bz2)'), MatchSpec('lazy-object-proxy (target=lazy-object-proxy-1.2.1-py35_0.tar.bz2)'), MatchSpec('py (target=py-1.4.31-py35_0.tar.bz2)'), MatchSpec('argcomplete (target=argcomplete-1.0.0-py35_1.tar.bz2)'), MatchSpec('jupyter (target=jupyter-1.0.0-py35_3.tar.bz2)'), MatchSpec('execnet (target=execnet-1.3.0-py35_1.tar.bz2)'), MatchSpec('prompt_toolkit (target=prompt_toolkit-1.0.3-py35_0.tar.bz2)'), MatchSpec('win_unicode_console (target=win_unicode_console-0.5-py35_0.tar.bz2)'), MatchSpec('sympy (target=sympy-1.0-py35_0.tar.bz2)'), MatchSpec('ipywidgets (target=conda-forge::ipywidgets-5.2.2-py35_0.tar.bz2)'), MatchSpec('chest (target=chest-0.2.3-py35_0.tar.bz2)'), MatchSpec('r (target=mro::r-3.2.3-0.tar.bz2)'), MatchSpec('nltk (target=nltk-3.2.1-py35_0.tar.bz2)'), MatchSpec('statsmodels (target=statsmodels-0.6.1-np111py35_1.tar.bz2)'), MatchSpec('zlib (target=zlib-1.2.8-vc14_3.tar.bz2)'), MatchSpec('r-pbkrtest (target=mro::r-pbkrtest-0.4_2-r3.2._2a.tar.bz2)'), MatchSpec('werkzeug (target=werkzeug-0.11.10-py35_0.tar.bz2)'), MatchSpec('sip (target=sip-4.18-py35_0.tar.bz2)'), MatchSpec('r-magrittr (target=mro::r-magrittr-1.5-r3.2._1a.tar.bz2)'), MatchSpec('qtpy (target=conda-forge::qtpy-1.1.1-py35_0.tar.bz2)'), MatchSpec('r-yaml (target=mro::r-yaml-2.1.13-r3.2._1a.tar.bz2)'), MatchSpec('pycrypto (target=pycrypto-2.6.1-py35_4.tar.bz2)'), MatchSpec('conda-manager (target=conda-manager-0.4.0-py35_0.tar.bz2)'), MatchSpec('ply (target=ply-3.8-py35_0.tar.bz2)'), MatchSpec('distributed (target=conda-forge::distributed-1.11.3-py35_0.tar.bz2)'), MatchSpec('r-essentials (target=mro::r-essentials-1.1-r3.2._0a.tar.bz2)'), MatchSpec('docutils (target=docutils-0.12-py35_2.tar.bz2)'), MatchSpec('heapdict (target=heapdict-1.0.0-py35_1.tar.bz2)'), MatchSpec('numpy (target=numpy-1.11.1-py35_0.tar.bz2)'), MatchSpec('notebook (target=notebook-4.2.1-py35_0.tar.bz2)'), MatchSpec('r-dbi (target=mro::r-dbi-0.3.1-r3.2._2a.tar.bz2)'), MatchSpec('vs2015_runtime (target=conda-forge::vs2015_runtime-14.0.25420-0.tar.bz2)'), MatchSpec('networkx (target=networkx-1.11-py35_0.tar.bz2)'), MatchSpec('pep8 (target=pep8-1.7.0-py35_0.tar.bz2)'), MatchSpec('r-hexbin (target=mro::r-hexbin-1.27.1-r3.2._0a.tar.bz2)'), MatchSpec('ruamel_yaml (target=ruamel_yaml-0.11.14-py35_0.tar.bz2)'), MatchSpec('r-rcolorbrewer (target=mro::r-rcolorbrewer-1.1_2-r3.2._2a.tar.bz2)'), MatchSpec('algopy (target=dhirschfeld::algopy-0.5.3-py35_0.tar.bz2)'), MatchSpec('multipledispatch (target=multipledispatch-0.4.8-py35_0.tar.bz2)'), MatchSpec('pydot (target=dhirschfeld::pydot-1.2.2-py35_0.tar.bz2)'), MatchSpec('psutil (target=psutil-4.3.0-py35_0.tar.bz2)'), MatchSpec('toolz (target=toolz-0.8.0-py35_0.tar.bz2)'), MatchSpec('packaging (target=conda-forge::packaging-16.7-py35_0.tar.bz2)'), MatchSpec('hypothesis (target=conda-forge::hypothesis-3.4.2-py35_0.tar.bz2)'), MatchSpec('r-base64enc (target=mro::r-base64enc-0.1_3-r3.2._0a.tar.bz2)'), MatchSpec('r-gtable (target=mro::r-gtable-0.1.2-r3.2._2a.tar.bz2)'), MatchSpec('ipython-notebook (target=ipython-notebook-4.0.4-py35_3.tar.bz2)'), MatchSpec('et_xmlfile (target=et_xmlfile-1.0.1-py35_0.tar.bz2)'), MatchSpec('r-rcppeigen (target=mro::r-rcppeigen-0.3.2.5.1-r3.2._0a.tar.bz2)'), MatchSpec('r-iterators (target=mro::r-iterators-1.0.8-r3.2._0a.tar.bz2)'), MatchSpec('singledispatch (target=singledispatch-3.4.0.3-py35_0.tar.bz2)'), MatchSpec('xlsxwriter (target=xlsxwriter-0.9.2-py35_0.tar.bz2)'), MatchSpec('r-colorspace (target=mro::r-colorspace-1.2_6-r3.2._0a.tar.bz2)'), MatchSpec('babel (target=conda-forge::babel-2.3.4-py35_0.tar.bz2)'), MatchSpec('r-bitops (target=mro::r-bitops-1.0_6-r3.2._1a.tar.bz2)'), MatchSpec('pytz (target=pytz-2016.6.1-py35_0.tar.bz2)'), MatchSpec('jedi (target=jedi-0.9.0-py35_1.tar.bz2)'), MatchSpec('r-foreach (target=mro::r-foreach-1.4.3-r3.2._0a.tar.bz2)'), MatchSpec('jsonschema (target=jsonschema-2.5.1-py35_0.tar.bz2)'), MatchSpec('r-evaluate (target=mro::r-evaluate-0.8-r3.2._0a.tar.bz2)'), MatchSpec('r-labeling (target=mro::r-labeling-0.3-r3.2._1a.tar.bz2)'), MatchSpec('r-caret (target=mro::r-caret-6.0_62-r3.2._0a.tar.bz2)'), MatchSpec('requests (target=requests-2.10.0-py35_0.tar.bz2)'), MatchSpec('astroid (target=astroid-1.4.4-py35_0.tar.bz2)'), MatchSpec('nb_config_manager (target=nb_config_manager-0.1.3-py35_0.tar.bz2)'), MatchSpec('llvmlite (target=llvmlite-0.12.1-py35_0.tar.bz2)'), MatchSpec('spyder-app (target=spyder-app-2.3.8-py35_0.tar.bz2)'), MatchSpec('jupyter_core (target=jupyter_core-4.1.0-py35_0.tar.bz2)'), MatchSpec('mkl (target=mkl-11.3.3-1.tar.bz2)'), MatchSpec('r-bh (target=mro::r-bh-1.58.0_1-r3.2._0a.tar.bz2)'), MatchSpec('clyent (target=clyent-1.2.2-py35_0.tar.bz2)'), MatchSpec('sphinx (target=sphinx-1.4.1-py35_0.tar.bz2)'), MatchSpec('patsy (target=patsy-0.4.1-py35_0.tar.bz2)'), MatchSpec('wheel (target=wheel-0.29.0-py35_0.tar.bz2)'), MatchSpec('simplegeneric (target=simplegeneric-0.8.1-py35_1.tar.bz2)'), MatchSpec('bitarray (target=bitarray-0.8.1-py35_1.tar.bz2)'), MatchSpec('r-dichromat (target=mro::r-dichromat-2.0_0-r3.2._2a.tar.bz2)'), MatchSpec('itsdangerous (target=itsdangerous-0.24-py35_0.tar.bz2)'), MatchSpec('numba (target=numba-0.27.0-np111py35_0.tar.bz2)'), MatchSpec('r-minqa (target=mro::r-minqa-1.2.4-r3.2._1a.tar.bz2)'), MatchSpec('nbconvert (target=nbconvert-4.2.0-py35_0.tar.bz2)'), MatchSpec('xlrd (target=xlrd-1.0.0-py35_0.tar.bz2)'), MatchSpec('partd (target=conda-forge::partd-0.3.5-py35_0.tar.bz2)'), MatchSpec('r-dplyr (target=mro::r-dplyr-0.4.3-r3.2._0a.tar.bz2)'), MatchSpec('cx_oracle (target=dhirschfeld::cx_oracle-5.2.1-oracle11g_py35.tar.bz2)'), MatchSpec('libtiff (target=libtiff-4.0.6-vc14_2.tar.bz2)'), MatchSpec('r-zoo (target=mro::r-zoo-1.7_12-r3.2._1a.tar.bz2)'), MatchSpec('mistune (target=conda-forge::mistune-0.7.3-py35_0.tar.bz2)'), MatchSpec('pyparsing (target=pyparsing-2.1.4-py35_0.tar.bz2)'), MatchSpec('patch (target=patch-2.5.9-1.tar.bz2)'), MatchSpec('rope (target=rope-0.9.4-py35_1.tar.bz2)'), MatchSpec('r-markdown (target=mro::r-markdown-0.7.7-r3.2._1a.tar.bz2)'), MatchSpec('r-stringr (target=mro::r-stringr-1.0.0-r3.2._0a.tar.bz2)'), MatchSpec('pytest-xdist (target=dhirschfeld::pytest-xdist-1.14-py35_0.tar.bz2)'), MatchSpec('anaconda-client (target=conda-forge::anaconda-client-1.5.0-py35_0.tar.bz2)'), MatchSpec('decorator (target=decorator-4.0.10-py35_0.tar.bz2)'), MatchSpec('r-car (target=mro::r-car-2.1_0-r3.2._0a.tar.bz2)'), MatchSpec('jmespath (target=jmespath-0.9.0-py35_0.tar.bz2)'), MatchSpec('lxml (target=lxml-3.6.1-py35_0.tar.bz2)'), MatchSpec('get_terminal_size (target=get_terminal_size-1.0.0-py35_0.tar.bz2)'), MatchSpec('jupyter_client (target=jupyter_client-4.3.0-py35_0.tar.bz2)'), MatchSpec('r-ggplot2 (target=mro::r-ggplot2-1.0.1-r3.2._0a.tar.bz2)'), MatchSpec('qt (target=qt-4.8.7-vc14_9.tar.bz2)'), MatchSpec('qtawesome (target=qtawesome-0.3.3-py35_0.tar.bz2)'), MatchSpec('tblib (target=tblib-1.3.0-py35_0.tar.bz2)'), MatchSpec('blosc (target=blosc-1.7.0-vc14_2.tar.bz2)'), MatchSpec('s3fs (target=s3fs-0.0.6-py35_0.tar.bz2)'), MatchSpec('dynd-python (target=dynd-python-0.7.2-py35_0.tar.bz2)'), MatchSpec('curl (target=curl-7.49.0-vc14_0.tar.bz2)'), MatchSpec('idna (target=idna-2.1-py35_0.tar.bz2)'), MatchSpec('ipython (target=ipython-5.0.0-py35_0.tar.bz2)'), MatchSpec('jinja2 (target=jinja2-2.8-py35_1.tar.bz2)'), MatchSpec('r-lazyeval (target=mro::r-lazyeval-0.1.10-r3.2._2a.tar.bz2)'), MatchSpec('pyscaffold (target=conda-forge::pyscaffold-2.5.6-py35_0.tar.bz2)'), MatchSpec('six (target=six-1.10.0-py35_0.tar.bz2)'), MatchSpec('r-xtable (target=mro::r-xtable-1.8_0-r3.2._0a.tar.bz2)'), MatchSpec('dill (target=dill-0.2.5-py35_0.tar.bz2)'), MatchSpec('r-stringi (target=mro::r-stringi-1.0_1-r3.2._0a.tar.bz2)'), MatchSpec('matplotlib (target=matplotlib-1.5.1-np111py35_0.tar.bz2)'), MatchSpec('numdifftools (target=dhirschfeld::numdifftools-0.9.11.post093+gd22e9fa-py35_0.tar.bz2)'), MatchSpec('sortedcontainers (target=conda-forge::sortedcontainers-1.5.3-py35_0.tar.bz2)'), MatchSpec('hdf5 (target=hdf5-1.8.15.1-vc14_4.tar.bz2)'), MatchSpec('libpng (target=conda-forge::libpng-1.6.23-vc14_0.tar.bz2)'), MatchSpec('pbr (target=pbr-1.10.0-py35_0.tar.bz2)'), MatchSpec('python-dateutil (target=python-dateutil-2.5.3-py35_0.tar.bz2)'), MatchSpec('jpeg (target=jpeg-8d-vc14_0.tar.bz2)'), MatchSpec('altair (target=conda-forge::altair-1.0.0-py35_0.tar.bz2)'), MatchSpec('r-htmlwidgets (target=mro::r-htmlwidgets-0.5-r3.2._0a.tar.bz2)')]
.DEBUG:dotupdate:Checking satisfiability
.DEBUG:dotupdate:Package removal metric: 0
.DEBUG:dotupdate:Initial package version/build metrics: 0/0
.DEBUG:dotupdate:Track feature count: 1
.DEBUG:dotupdate:Package feature count: 15
.DEBUG:dotupdate:Dependency update count: 0
.DEBUG:dotupdate:Additional package version/build metrics: 0/0
.DEBUG:dotupdate:Weak dependency count: 0
.DEBUG:dotupdate:Looking for alternate solutions

INFO:stdoutlog:


Package plan for installation in environment C:\Python:

The following NEW packages will be INSTALLED:

    widgetsnbextension: 1.2.6-py35_3 conda-forge

Proceed ([y]/n)? y
```

**Comment by dhirschfeld** [comment] 2016-08-01 23:39
Any to turn this down/off?

**Comment by HugoTian** [comment] 2016-08-02 13:57
Could you please show the output of conda info ?

Thanks

**Comment by kalefranz** [comment] 2016-08-02 15:44
I think the issue is actually conda-build changed the root logger behavior. We'll fix this for conda master branch and 4.2 for sure. I think @msarahan has released a conda-build that reverts previous behavior for now.

**Comment by msarahan** [comment] 2016-08-02 16:04
Confirming that this is an issue with conda-build 1.21.8.  Should be better in 1.21.9 - but may still have some messages that I missed.  Longer-term, we will be working to separate logger behavior between conda and conda-build better.

**Comment by msarahan** [comment] 2016-08-02 20:54
Sorry, this is fixed in https://github.com/conda/conda-build/pull/1166 - will be part of conda-build 1.21.10 later today.  I recommend manually installing conda-build 1.21.7 if this is bothering you too much.

**Comment by dhirschfeld** [comment] 2016-08-04 02:51
Thanks, it's not *too* much of a bother so I'll just update when 1.21.10 is realeased...

**Closed** 2016-08-04 03:07 UTC
