### ISSUE TITLE
conda update --all failing

### ISSUE THREAD

**Issue by partha1968** [conda/conda#6146] opened 2017-10-11 12:17 UTC
I tried to update conda using
conda update --all --yes

I got the following error

(C:\Users\Quant\Anaconda3) C:\Users\Quant\Documents>conda update --all --yes
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Users\Quant\Anaconda3  (writable)
    default environment : C:\Users\Quant\Anaconda3
       envs directories : C:\Users\Quant\Anaconda3\envs
                          C:\Users\Quant\AppData\Local\conda\conda\envs
                          C:\Users\Quant\.conda\envs
          package cache : C:\Users\Quant\Anaconda3\pkgs
                          C:\Users\Quant\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Quant\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/7 W
indows/6.1.7601
          administrator : False

`$ C:\Users\Quant\Anaconda3\Scripts\conda update --all --yes`

    Traceback (most recent call last):
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\cli\main.py", line
140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\cli\main_update.py"
, line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 160, in install
        linked_dists = install_linked(prefix)
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\core\linked_data.py
", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\core\linked_data.py
", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\core\linked_data.py
", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\_vendor\auxlib\enti
ty.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\_vendor\auxlib\enti
ty.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\_vendor\auxlib\enti
ty.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance
, val))
      File "C:\Users\Quant\Anaconda3\lib\site-packages\conda\_vendor\auxlib\enti
ty.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506372959.50
3 for timestamp

(C:\Users\Quant\Anaconda3) C:\Users\Quant\Documents>

**Comment by kalefranz** [comment] 2017-10-11 18:47
Duplicate of #6096. Solution given in that issue.

**Closed by kalefranz** 2017-10-11 18:47 UTC
