### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by ice1x** [conda/conda#12440] opened 2023-03-04 09:44 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Support Python 3.11

**Comment by johnnynunez** [comment] 2023-03-06 12:09
https://github.com/conda/conda/issues/11170

**Comment by kenodegard** [comment] 2023-03-06 14:48
Closing as duplicate of #11170

**Closed by kenodegard** 2023-03-06 14:48 UTC
Labels: type::feature, duplicate
