### ISSUE TITLE
specifying envs_dirs behavior change in 4.2.9

### ISSUE THREAD

**Issue by jerowe** [conda/conda#3906] opened 2016-11-17 09:22 UTC
Hello,

pinging @kalefranz 

I finally upgraded from 4.1.11, and it broke my multiuser environment setup.

Using 4.2.9, it sees that the root environment is read only, but for whatever reason still appends it to the package cache and envs dirs.

ETA - More specifically, we saw this issue here:

https://github.com/conda/conda/issues/3469

We also ran into issues creating environments, if it saw a package in the root environment it would try to decompress it, but would obviously run into write issues.

### Conda Version 4.2.9

```
[jdr400@login-0-4 ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0  (read only)
    default environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0
       envs directories : /scratch/jdr400/.conda
                          /home/jdr400/.conda/envs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/envs
          package cache : /scratch/jdr400/.conda/.pkgs
                          /home/jdr400/.conda/envs/.pkgs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/pkgs
           channel URLs : https://conda.anaconda.org/r/linux-64/
                          https://conda.anaconda.org/r/noarch/
                          https://conda.anaconda.org/conda-forge/linux-64/
...
            config file : /home/jdr400/.condarc
           offline mode : False
```

### Conda Version 4.1.11

In 4.1.11, the behavior is as expected.

```
[jdr400@login-0-4 ~]$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 1.4.1
  conda-build version : 2.0.2
       python version : 2.7.12.final.0
     requests version : 2.11.1
     root environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0  (read only)
  default environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0
     envs directories : /scratch/jdr400/.conda
        package cache : /scratch/jdr400/.conda/.pkgs
         channel URLs : https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/jdr400/.condarc
         offline mode : False
    is foreign system : False
```

**Comment by jerowe** [comment] 2016-11-17 09:29
The behavior is here:

https://github.com/conda/conda/blob/master/conda/base/context.py#L228

```
conda.base.context
```
```
    @property
    def envs_dirs(self):
        return tuple(abspath(expanduser(p))
                     for p in concatv(self._envs_dirs,
                                      (join(self.root_dir, 'envs'), )
                                      if self.root_writable
                                      else ('~/.conda/envs', join(self.root_dir, 'envs'))))
```

it should be

```
    @property
    def envs_dirs(self):
        return tuple(abspath(expanduser(p))
                     for p in concatv(self._envs_dirs,
                                      if self.root_writable:
                                              (join(self.root_dir, 'envs'), )
                                      else:
                                          #~/.conda.envs should only be appended if the user has not specified a envs_dirs in ~/.condarc
                                         ('~/.conda/envs', join(self.root_dir, 'envs'))))
```

**Comment by jerowe** [comment] 2016-11-17 10:24
Commenting again

IMO, the logic should be

if in conda.base.context.Context

```
@property
def envs_dirs(self):
envs_dirs = []

if self.root_dir_writable:
      envs_dirs.append(join(self.root_dir, 'envs')
else:
        if  not self._envs_dirs:
           envs_dirs.append('~/.conda/envs')

for p in self._envs_dirs:
    envs_dirs.append(p)

return envs_dirs
```

**Comment by kalefranz** [comment] 2016-11-17 15:12
Still reading through this, but any reason to not upgrade to 4.2.12 instead of 4.2.9?  In 4.2.11, there was this PR https://github.com/conda/conda/pull/3685

**Comment by jerowe** [comment] 2016-11-17 15:19
I wasn't aware there was a 4.2.12. I just ran a conda install -c conda conda, and that's what I got. I assumed ti was the most recent version, but clearly I assumed wrong!

**Comment by jerowe** [comment] 2016-11-17 15:23
Alright, I upgraded to 4.2.12.

## Conda Info

```
[jdr400@login-0-3 ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.20.0
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda/2-4.0.0  (read only)
    default environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda/2-4.0.0
       envs directories : /scratch/jdr400/.conda/envs
                          /home/jdr400/.conda/envs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda/2-4.0.0/envs
          package cache : /scratch/jdr400/.conda/envs/.pkgs
                          /home/jdr400/.conda/envs/.pkgs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda/2-4.0.0/pkgs
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jdr400/.condarc
           offline mode : False
```

## Conda Create

```
[jdr400@login-0-3 ~]$ conda create -p /scratch/jdr400/software/tmp
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /scratch/jdr400/software/tmp:

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.9.26-0      conda-forge (copy)
    certifi:         2016.9.26-py27_0 conda-forge (copy)
    ncurses:         5.9-9            conda-forge (copy)
    openssl:         1.0.2h-2         conda-forge (copy)
    pip:             9.0.1-py27_0     conda-forge (copy)
    python:          2.7.12-1         conda-forge (copy)
    readline:        6.2-0            conda-forge (copy)
    setuptools:      28.8.0-py27_0    conda-forge (copy)
    sqlite:          3.13.0-1         conda-forge (copy)
    tk:              8.5.19-0         conda-forge (copy)
    wheel:           0.29.0-py27_0    conda-forge (copy)
    zlib:            1.2.8-3          conda-forge (copy)

Proceed ([y]/n)? y

Linking packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
```

**Comment by kalefranz** [comment] 2016-11-17 15:41
The logic for `envs_dirs` in 4.2 is *intended* to exactly duplicate the logics for `envs_dirs` in previous versions.  Previous versions had the logic in `conda/config.py`, and that file routinely twists my brain in knots.  Your comparison output made it clear that I got it wrong.

Could you try using this code here for me:

```
    @property
    def envs_dirs(self):

        def _default_envs_dirs():
            if self.root_writable:
                return join(self.root_dir, 'envs'),
            else:
                # ~/envs for backwards compatibility
                return '~/.conda/envs', '~/envs', join(self.root_dir, 'envs')

        return tuple(abspath(expanduser(p)) for p in self._envs_dirs or _default_envs_dirs())
```

See if it gives you the result you're looking for in https://github.com/conda/conda/pull/3908 and also gives you back the 4.1.x behavior...

**Comment by kalefranz** [comment] 2016-11-17 15:42
The big difference here is the `or` in the last line.  I thought all of these sources were being concat'd together before.  They're not.

**Comment by jerowe** [comment] 2016-11-17 15:54
Tbh I didn't poke around the 4.1.11 code to see the difference.  

Also,  I suppose it is a design choice,  but I don't think the home/.conda/envs should be added if the user defines envs_dur either in the config or a variable.

**Comment by jerowe** [comment] 2016-11-17 15:56
I will get back to you by the end of today on the code you proposed. I'm away from my computer right now.  ;)

**Comment by jerowe** [comment] 2016-11-17 16:02
I don't like to be pushy,  but do you have a time frame for when this will be fixed? This is a critical bug for my users.  It renders versions > 4.1.11 unusable for us,  since our setup specifically requires multiple user support.

**Comment by jerowe** [comment] 2016-11-17 17:17
## Conda info with 4.1.11 envs_dir 

## With envs_dirs in ~/.condarc

```
[jdr400@login-0-4 ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.12.dev527+f339ca8
       conda is private : False
      conda-env version : 4.2.12.dev527+f339ca8
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0  (read only)
    default environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0
       envs directories : /scratch/jdr400/.conda/envs
          package cache : /scratch/jdr400/.conda/envs/.pkgs
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jdr400/.condarc
           offline mode : False
             user-agent : conda/4.2.12.dev527+f339ca8 requests/2.11.1 CPython/2.7.12 Linux/3.10.0-327.36.3.el7.x86_64 CentOS Linux/7.2.1511 glibc/2.17
                UID:GID : 1700454:100
```

## Without envs_dirs in ~/.condarc

```
[jdr400@login-0-4 ~]$ conda info                                                                                                                                                                             
Current conda install:

               platform : linux-64
          conda version : 4.2.12.dev527+f339ca8
       conda is private : False
      conda-env version : 4.2.12.dev527+f339ca8
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0  (read only)
    default environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0
       envs directories : /home/jdr400/.conda/envs
                          /home/jdr400/envs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/envs
          package cache : /home/jdr400/.conda/envs/.pkgs
                          /home/jdr400/envs/.pkgs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/pkgs
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jdr400/.condarc
           offline mode : False
             user-agent : conda/4.2.12.dev527+f339ca8 requests/2.11.1 CPython/2.7.12 Linux/3.10.0-327.36.3.el7.x86_64 CentOS Linux/7.2.1511 glibc/2.17
                UID:GID : 1700454:100
```

I guess I never noticed this before because I always define my envs_dirs, but the second is, imo, a design flaw.

```
return '~/.conda/envs', '~/envs', join(self.root_dir, 'envs')
```

Should be

```
return '~/.conda/envs', '~/envs'
```

**Comment by jerowe** [comment] 2016-11-17 17:24
### Conda Create Log with envs_dir from 4.1.11

```
conda create -p /scratch/jdr400/software/tmp
Fetching packages ...
ca-certificate 100% |#############################################################################################################################################################| Time: 0:00:04  38.79 kB/s
ncurses-5.9-9. 100% |#############################################################################################################################################################| Time: 0:00:04 225.66 kB/s
sqlite-3.13.0- 100% |#############################################################################################################################################################| Time: 0:00:15 329.92 kB/s
tk-8.5.19-0.ta 100% |#############################################################################################################################################################| Time: 0:00:05 380.84 kB/s
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
`$ /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/bin/conda create -p /scratch/jdr400/software/tmp`




    Traceback (most recent call last):
      File "/scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/lib/python2.7/site-packages/conda/exceptions.py", line 504, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/lib/python2.7/site-packages/conda/cli/install.py", line 390, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/pkgs/zlib-1.2.8-3.tar.bz2.part' for writing ([Errno 13] Permission denied: u'/scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/pkgs/zlib-1.2.8-3.tar.bz2.part').
```

**Comment by kalefranz** [comment] 2016-11-17 17:25
> but do you have a time frame for when this will be fixed? This is a critical bug for my users.

Yes, we will back-port the fix to the `4.2.x` branch and include it in the next `4.2.x` patch release.  We can probably do that within the next week.

**Comment by kalefranz** [comment] 2016-11-17 17:26
> Having a dir that is read only is pkgs or envs will create permissions difficulties

Yes, it's a long-standing issue.  That's exactly one of the high-priority targets for the `4.4` feature release--which I'm committed to making happen within 2016.

**Comment by jerowe** [comment] 2016-11-17 17:27
Why 4.4, if you don't mind my asking? It looks like a simple enough change.

**Comment by jerowe** [comment] 2016-11-17 17:30
### Conda default_envs_dirs  - don't append root_dir

```
[jdr400@login-0-4 ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.12.dev528+0d50ff6
       conda is private : False
      conda-env version : 4.2.12.dev528+0d50ff6
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0  (read only)
    default environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0
       envs directories : /home/jdr400/.conda/envs
                          /home/jdr400/envs
          package cache : /home/jdr400/.conda/envs/.pkgs
                          /home/jdr400/envs/.pkgs
``

**Comment by kalefranz** [comment] 2016-11-17 17:30
> Why 4.4, if you don't mind my asking? It looks like a simple enough change.

When I do change this, I want to make sure it's all correct and working seamlessly.  There's a lot of related threads and interconnected code here.  Changing this *will* just push bugs to other places in the code.  So we basically duplicate the error reports, with now bug reports that look different, but really have the same root cause.

**Comment by jerowe** [comment] 2016-11-17 17:32
Gotcha. Conda is a very involved project. Btw, I tell everyone all the time just how awesome it is. ;-)

**Comment by jerowe** [comment] 2016-11-17 17:35
But, if you decide to change

`return '~/.conda/envs', '~/envs', join(self.root_dir, 'envs')` to `return '~/.conda/envs', '~/envs'`, I will totally keep it a secret. ;-)

**Comment by kalefranz** [comment] 2016-11-17 17:40
> I will totally keep it a secret

`4.4.x` will be out before you know it :)

**Comment by jerowe** [comment] 2016-12-29 16:03
@kalefranz , any updates on this?

**Comment by jerowe** [comment] 2017-01-13 04:41
@kalefranz , I see there is lots of work being done on conda. Exciting stuff! Will any of the new versions include the fix for the env_dir/root_dir ?

**Comment by jerowe** [comment] 2017-01-18 00:26
@kalefranz , it looks like this behavior was fixed?

https://github.com/conda/conda/blob/f1d2674c75bcfc22c9bee73ef696261d4cc6c646/conda/base/context.py#L259

**Comment by jerowe** [comment] 2017-02-01 07:12
Can confirm this is fixed.

**Read Only**
```
[jdr400@login-0-3 RNAseqAlignment]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0  (read only)
    default environment : /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0
       envs directories : /home/jdr400/.conda/envs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/envs
          package cache : /home/jdr400/.conda/envs/.pkgs
                          /scratch/gencore/.local/easybuild/software/gencore_anaconda2/4.2.0/pkgs
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jdr400/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.12 Linux/3.10.0-327.36.3.el7.x86_64 CentOS Linux/7.2.1511 glibc/2.17
                UID:GID : 1700454:100
```

Installing works also.

**Closed** 2017-05-10 02:45 UTC
