### ISSUE TITLE
conda updating anaconda failure

### ISSUE THREAD

**Issue by javierj** [conda/conda#3918] opened 2016-11-19 11:54 UTC
After

>  conda update conda

I tried to update Anaconda too. this is the result:

>conda update anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.18.2
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : C:\code\apps\Anaconda3  (writable)
    default environment : C:\code\apps\Anaconda3
       envs directories : C:\code\apps\Anaconda3\envs
          package cache : C:\code\apps\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\code\apps\Anaconda3\Scripts\conda-script.py update anaconda`

    Traceback (most recent call last):
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\fetch.py", line 310, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\code\apps\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\code\apps\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\code\apps\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "C:\code\apps\Anaconda3\lib\site-packages\conda\fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\code\apps\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

I have the same error if I try to update conda itself

**Comment by OliverChow** [comment] 2016-11-20 05:41
I also came across this problem, exactly the same as you, I have reinstalled my ubuntu system for at least 5 times, but it just didn't work, I am so depressed now.....

**Comment by kalefranz** [comment] 2016-11-22 22:33
Duplicate of #3929, #3935, and #3934.  Honestly not sure where this came from all the sudden.  We definitely need to limit dependencies somewhere.

In general `pyopenssl` and `cryptography` are out of sync.

    CONDA_VERIFY_SSL=false conda update pyopenssl

should fix your problem

**Closed by kalefranz** 2016-11-22 22:33 UTC

**Comment by iranmatlab** [comment] 2017-09-23 19:16
Hello Friends
I have solved the problem.

This error cause because of different version of python in anaconda and installed python on your system.

when you upgrade anaconda to new version, It has been written in newest version on pyhton (3.6 for me) but i have installed lower version (3.5 for me) of python in my system, so it cause fail in run.

so download newest version of python and install it, then 
**rename** folder of last python to a different name such as "pythoonn"

then conda command will works.
