### ISSUE TITLE
Please use Semantic Versioning to signal backward incompatible changes.

### ISSUE THREAD

**Issue by nicolaasuni** [conda/conda#6606] opened 2017-12-29 11:23 UTC
The Conda version 4.4.0 (https://github.com/conda/conda/releases/tag/4.4.0) introduces backward-incompatible changes that breaks existing configurations.

To allow automatic Conda updates while avoid breaking changes, Conda should follow the Semantic Versioning convention:

Given a version number MAJOR.MINOR.PATCH, increment the:

* MAJOR version when you make incompatible changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

For more information:
https://semver.org/

**Comment by kalefranz** [comment] 2017-12-29 14:31
Can you clarify what you're experiencing as backward-incompatible? Perhaps we missed something.

We use semver for conda viewed as an application, i.e. the command-line API.  Not necessarily for conda viewed as a library, i.e. `import conda` from python.

**Comment by nicolaasuni** [comment] 2017-12-29 14:57
The page https://github.com/conda/conda/releases/tag/4.4.0 lists some breaking changes.
For example: "the conda 'root' environment is now generally referred to as the 'base' environment".

I believe there should not be a "breaking changes" section in a non-major release.

In my specific case I had some orchestration scripts installing Miniconda3-4.3.31. Conda was automatically updating to 4.4.0 version and the change listed above was breaking the setup. As a temporary solution I had to pin the conda version to 4.3.31 in conda-meta/pinned.

In order to upgrade to Conda 4.4 I will have to change the orchestration/setup/config scripts to account for the breaking change.

**Comment by kalefranz** [comment] 2017-12-29 15:02
That was implemented in what was hoped to be a backward-compatible way.  For example

    conda update -n root conda

and

    conda update -n base conda

do exactly the same thing.  From the CLI perspective, `root` is aliased to `base` still for backward compatibility.

It's possible we missed something still in the implementation.  Where are your scripts getting tripped up?

**Comment by levy5674** [comment] 2018-01-03 22:46
This change from `root` to `base` has broken apps I've built on top of the `miniconda3:4.2.27` docker image.  The key thing seems to be that `environment.yml` installs a pip dependency, and `Dockerfile` installs into the root environment. 

Here's a toy `environment.yml`

```
name: conda6606
dependencies:
- tqdm
- pip:
  - bumpversion
```

A `Dockerfile` that fails

```
FROM continuumio/miniconda3:4.3.27

WORKDIR /app
COPY environment.yml /app/environment.yml
RUN conda env update -n root
```

and a `Dockerfile` that's ok

```
FROM continuumio/miniconda3:4.3.27

WORKDIR /app
COPY environment.yml /app/environment.yml
RUN conda env update -n base
```

Here is the traceback from the failure:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    original data Length: %(original_data_length)d
  File "/opt/conda/lib/python3.6/site-packages/conda_env/cli/main_update.py", line 106, in execute
    installer = get_installer(installer_type)
  File "/opt/conda/lib/python3.6/site-packages/conda_env/installers/pip.py", line 40, in _pip_install_via_requirements
    args, pip_version = pip_args(prefix)
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-env", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_env/cli/main.py", line 76, in main

  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    'path': path,
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    def __init__(self, path, placeholder, new_prefix, original_data_length, new_data_length):
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 595, in print_unexpected_error_message

  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
    from .common import print_envs_list, stdout_json
ImportError: cannot import name 'print_envs_list'
```

**Comment by mbargull** [comment] 2018-01-03 23:38
@levy5674: your issue is unrelated and (I think) due to a resolved bug in `4.3.27`.
Try to use `RUN conda update conda` before running `conda env update`.

**Comment by patricksnape** [comment] 2018-01-04 08:52
I am seeing exactly the same issue as @levy5674 - pip installed dependencies from a environment.yml seem to be failing to install.

**Comment by patricksnape** [comment] 2018-01-04 08:58
It looks to me like the update command is also updating conda despite it not being listed in the set of requirements?

**Comment by kalefranz** [comment] 2018-01-05 18:02
Conda 4.3.x doesn't know anything about `base`.  In 4.3.x it's `root`.  In conda 4.4.x it's `base`, but conda 4.4.x also treats `root` as an alias of `base` for backward compatibility.

So `RUN conda env update -n base` will NOT work for conda 4.3.x, while `RUN conda env update -n root` will work for both, and work in the same way for both.

**Comment by mbargull** [comment] 2018-01-05 22:39
For clarification: on 4.3.x `conda env update -n base` won't update the root env but create a new one named `base`. Hence it will succeed, but it doesn't do want you intended to do.

I have to correct myself though: The issue seen by @levy5674 and @patricksnape is not resolved in `conda 4.3.30` but actually a bug in `conda-env`, present in 4.3.x and 4.4.x likewise, see: #6672.

All of that is still unrelated to the original isuue, though, so @kalefranz's question to @nicolaasuni:
>  Where are your scripts getting tripped up?

remains open.

**Comment by kalefranz** [comment] 2018-01-24 18:55
I think we can close this issue.  It's mostly devolved to a discussion of bugs at this point.  New bug reports should have individual issues filed (after making sure the bug isn't already fixed in an up-to-date version of conda).

**Closed by kalefranz** 2018-01-24 18:55 UTC

**Comment by MattF-NSIDC** [comment] 2018-10-24 20:29
@kalefranz I feel there's value to the discussion here that is _not_ related to bugs but instead related to deliberate changes (such as the one referenced by #4448) which seem to work as intended but change the public API in backwards-incompatible ways in conda minor/patch versions. 

So I'm confused about `conda`'s policy towards semantic versioning. Is conda committed to using semver, or some subset of semver? It appears that conda team defines conda's public API as the CLI based on the quote above: "We use semver for conda viewed as an application, i.e. the command-line API."

I ran in to the breaking change #4448 this week with an automated build tool at my organization, and I have to say it was frustrating for this to happen in a minor version. I set up my project's dependencies to avoid exactly this problem (`conda<5.0.0`) but that only works if the project uses semver. Note that this tool is parsing the CLI output, and not using conda as a library.

I also consider renaming the root environment to "base" and displaying that name in the output of `conda env list` to be a breaking change to the public API. Any tool which parses that output expecting the formerly-canonical root environment will now fail. This could have been avoided by retaining the "root" environment name and making "base" the alias or by bumping to the next major version with this change.

Since the change re:#4448, and in my opinion the rename of the "root" environment to "base", introduce breaking public API changes to the portion of `conda` which is supposed to be under semver, is there going to be a new minor version which restores backwards compatibility as prescribed by semver? https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version

Conda provides a lot of value to my organization (I believe we use it across >100 projects), and I feel the one change that would improve our experience most dramatically is strict adherence to semantic versioning. Thanks for your time!
