### ISSUE TITLE
Updating conda causing command line prompt issues

### ISSUE THREAD

**Issue by mitchelldehaven** [conda/conda#11942] opened 2022-10-06 18:39 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I recently updated my Miniconda setup from 4.8 (I think) to the current version and my command prompt seems to be having issues. My prompt used to be fairly standard:
```
(<active_conda_env>) <username>@<hostname> <dirname> $ 
```
However, now it just shows the conda environment name, with no additional info:
```
(<active_conda_env>)
e.g.
(base)
```

I added `export PS1=$PS1'\u@\h \W $ '` to my `~/.bashrc`, which solves the problem when a terminal is created, but as soon as a I active a different env, the same problem shows up. I tried doing a simple fix by adding the same command to files under `etc/profiles.d` in my conda directory, but that doesn't seem to help. Any help in restoring my prompt back to isn't original state would be appreciated.

**Comment by ebebpl** [comment] 2022-10-07 15:44
I have the exact same issue after updating conda using $conda update conda . My directory display in prompt vanished and I only see (base) in terminal. How can I revert back to standard prompt like:  (<active_conda_env>) <username>@<hostname> <dirname> $ 


(base) conda list conda
# packages in environment at /opt/anaconda3:
# Name                    Version                   Build  Channel
anaconda                  2022.05                  py39_0
anaconda-client       1.9.0            py39h06a4308_0
conda                        22.9.0           py39h06a4308_0

**Comment by kenodegard** [comment] 2022-10-07 17:44
@mitchelldehaven Thanks for reporting, closing this since it's a duplicate of #11885.

**Closed by kenodegard** 2022-10-07 17:44 UTC
Labels: type::bug, duplicate
