### ISSUE TITLE
conda 4.6.x and conda 4.7.x not able to resolve identical package in different subdirectories

### ISSUE THREAD

**Issue by jeremyjliu** [conda/conda#9116] opened 2019-08-16 18:22 UTC
Current Behavior

The following happens:
```
[root@596ad8f0842a /]# conda create -n conda-env --dry-run -- test-package
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package pandas conflicts for:
test-package -> pandas
Package typing conflicts for:
test-package -> typing
Package libffi conflicts for:
test-package -> libffi[version='>=3.2.1,<4.0a0']
Package pyyaml conflicts for:
test-package -> pyyaml
Package six conflicts for:
test-package -> six[version='>=1.12.0']
Package py4j conflicts for:
test-package -> py4j
Package icu conflicts for:
test-package -> icu
Package wrapt conflicts for:
test-package -> wrapt
Package pytz conflicts for:
test-package -> pytz
Package python conflicts for:
test-package -> python[version='>=2.7.14']
Package pyarrow conflicts for:
test-package -> pyarrow
Package matplotlib conflicts for:
test-package -> matplotlib[version='>=2.0.2,<2.3.0']
```
Also observed on conda 4.6.14

### Steps to Reproduce

1. Create a conda repository `test-channel` with the following set up
2. In /linux-64/repodata.json
```
{
  "info": {
    "subdir": "linux-64"
  },
  "packages": {
    "test-package-4.2.1-py_0.tar.bz2": {
      "build": "py_0",
      "build_number": 0,
      "depends": [
        "icu",
        "libffi >=3.2.1,<4.0a0",
        "matplotlib >=2.0.2,<2.3.0",
        "pandas",
        "py4j",
        "pyarrow",
        "python >=2.7.14",
        "pytz",
        "pyyaml",
        "six >=1.12.0",
        "typing",
        "wrapt"
      ],
      "md5": "1512a7e9a56ecb8523475c891bfa6657",
      "name": "test-package",
      "noarch": "python",
      "sha256": "3c02f947500c13ceb8e8aa38db2af43e9017c4948905d0cbd1610185318fe7d9",
      "size": 30098,
      "subdir": "noarch",
      "timestamp": 1565634321434,
      "version": "4.2.1"
    }
  },
  "removed": [],
  "repodata_version": 1
}
```
3. In /noarch/repodata.json
```
{
  "info": {
    "subdir": "noarch"
  },
  "packages": {
    "test-package-4.2.1-py_0.tar.bz2": {
      "build": "py_0",
      "build_number": 0,
      "depends": [
        "icu",
        "libffi >=3.2.1,<4.0a0",
        "matplotlib >=2.0.2,<2.3.0",
        "pandas",
        "py4j",
        "pyarrow",
        "python >=2.7.14",
        "pytz",
        "pyyaml",
        "six >=1.12.0",
        "typing",
        "wrapt"
      ],
      "md5": "1512a7e9a56ecb8523475c891bfa6657",
      "name": "test-package",
      "noarch": "python",
      "sha256": "3c02f947500c13ceb8e8aa38db2af43e9017c4948905d0cbd1610185318fe7d9",
      "size": 30098,
      "subdir": "noarch",
      "timestamp": 1565634321434,
      "version": "4.2.1"
    }
  },
  "removed": [],
  "repodata_version": 1
}
```
3. Set up conda to only point to the test-channel, note I see this error on `--dry-run` so I did not populate the test-channel with the actual packages.
4. Run `conda create -n conda-env --dry-run -- test-package`

## Expected Behavior

Previously, in conda 4.5.x, there was no issue with resolving packages like this.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
[root@596ad8f0842a /]# conda info

     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
                          /condarc
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /miniconda  (writable)
           channel URLs : file://test-channel/asset/conda/linux-64
                          file://test-channel/asset/conda/noarch
          package cache : /miniconda/pkgs
                          /root/.conda/pkgs
       envs directories : /miniconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.9.184-linuxkit centos/6.10 glibc/2.12
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
[root@596ad8f0842a /]# conda config --show-sources
==> /root/.condarc <==
channel_priority: disabled
channels:
  - file://test-channel/asset/conda/
repodata_fns:
  - repodata.json
use_only_tar_bz2: False

==> /condarc <==
channels: []
default_channels: []
```
</p></details>
Note I attempted to remove current_repodata.json from being considered, but this is 4.7.10 before the config value is apparently respected.

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
[root@596ad8f0842a /]# conda list --show-channel-urls
# packages in environment at /miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://repo.anaconda.com/pkgs/main
asn1crypto                0.24.0                   py37_0    https://repo.anaconda.com/pkgs/main
bzip2                     1.0.8                h7b6447c_0    https://repo.anaconda.com/pkgs/main
ca-certificates           2019.5.15                     0    https://repo.anaconda.com/pkgs/main
certifi                   2019.6.16                py37_0    https://repo.anaconda.com/pkgs/main
cffi                      1.12.3           py37h2e261b9_0    https://repo.anaconda.com/pkgs/main
chardet                   3.0.4                    py37_1    https://repo.anaconda.com/pkgs/main
conda                     4.7.10                   py37_0    https://repo.anaconda.com/pkgs/main
conda-package-handling    1.3.11                   py37_0    https://repo.anaconda.com/pkgs/main
cryptography              2.7              py37h1ba5d50_0    https://repo.anaconda.com/pkgs/main
idna                      2.8                      py37_0    https://repo.anaconda.com/pkgs/main
libarchive                3.3.3                h5d8350f_5    https://repo.anaconda.com/pkgs/main
libedit                   3.1.20181209         hc058e9b_0    https://repo.anaconda.com/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://repo.anaconda.com/pkgs/main
libgcc-ng                 9.1.0                hdf63c60_0    https://repo.anaconda.com/pkgs/main
libstdcxx-ng              9.1.0                hdf63c60_0    https://repo.anaconda.com/pkgs/main
libxml2                   2.9.9                hea5a465_1    https://repo.anaconda.com/pkgs/main
lz4-c                     1.8.1.2              h14c3975_0    https://repo.anaconda.com/pkgs/main
lzo                       2.10                 h49e0be7_2    https://repo.anaconda.com/pkgs/main
ncurses                   6.1                  he6710b0_1    https://repo.anaconda.com/pkgs/main
openssl                   1.1.1c               h7b6447c_1    https://repo.anaconda.com/pkgs/main
pip                       19.1.1                   py37_0    https://repo.anaconda.com/pkgs/main
pycosat                   0.6.3            py37h14c3975_0    https://repo.anaconda.com/pkgs/main
pycparser                 2.19                     py37_0    https://repo.anaconda.com/pkgs/main
pyopenssl                 19.0.0                   py37_0    https://repo.anaconda.com/pkgs/main
pysocks                   1.7.0                    py37_0    https://repo.anaconda.com/pkgs/main
python                    3.7.3                h0371630_0    https://repo.anaconda.com/pkgs/main
python-libarchive-c       2.8                     py37_11    https://repo.anaconda.com/pkgs/main
readline                  7.0                  h7b6447c_5    https://repo.anaconda.com/pkgs/main
requests                  2.22.0                   py37_0    https://repo.anaconda.com/pkgs/main
ruamel_yaml               0.15.46          py37h14c3975_0    https://repo.anaconda.com/pkgs/main
setuptools                41.0.1                   py37_0    https://repo.anaconda.com/pkgs/main
six                       1.12.0                   py37_0    https://repo.anaconda.com/pkgs/main
sqlite                    3.29.0               h7b6447c_0    https://repo.anaconda.com/pkgs/main
tk                        8.6.8                hbc83047_0    https://repo.anaconda.com/pkgs/main
tqdm                      4.32.1                     py_0    https://repo.anaconda.com/pkgs/main
urllib3                   1.24.2                   py37_0    https://repo.anaconda.com/pkgs/main
wheel                     0.33.4                   py37_0    https://repo.anaconda.com/pkgs/main
xz                        5.2.4                h14c3975_4    https://repo.anaconda.com/pkgs/main
yaml                      0.1.7                had09818_2    https://repo.anaconda.com/pkgs/main
zlib                      1.2.11               h7b6447c_3    https://repo.anaconda.com/pkgs/main
zstd                      1.3.7                h0b5b093_0    https://repo.anaconda.com/pkgs/main
```
</p></details>

**Comment by jeremyjliu** [comment] 2019-08-16 18:23
Key question: is this expected behavior for packages that have an identical noarch and linux-64 builds?

**Comment by jeremyjliu** [comment] 2019-08-16 18:55
Additional note: if I remove the repodata entry for either `linux-64` or `noarch` subdir, but not the other, then the command succeeds

**Comment by jjhelmus** [comment] 2019-08-21 14:38
This is likely similar to #8302 which was partially fixed in #8938.  Packages from different subdirs with the same name will also have the same channel which causes conda to consider than as the same package.  

For the time being it is best to not have packages with identical names in `noarch` and another subdir.  This is not the intended behavior, the solver should treat these are two separate packages.

**Comment by jeremyjliu** [comment] 2019-08-22 15:16
To add a data point, I'm seeing this on another `conda create` but this time it doesn't seem to be an issue with any packages that I can control, but somewhere in public channels. Is there a suggested way to narrow down where this is coming from?

**Comment by jeremyjliu** [comment] 2019-09-11 17:29
@jjhelmus do you have any initial thoughts on how to fix the issue within conda? Happy to take a stab at contributing and testing a patch for this edge case.

**Comment by jjhelmus** [comment] 2019-09-27 17:06
@jeremyjliu The solver uses the PackageRecords [dist_str method](https://github.com/conda/conda/blob/4.7.12/conda/resolve.py#L805-L813) when translating a package into a SAT model.  The [dist_str method is defined in models/records.py](https://github.com/conda/conda/blob/4.7.12/conda/models/records.py#L283-L284) and does not include the subdir.  If that string included the subdir that may be sufficient, although last time I tried to modify the method it had a chain of knock on effects that needed to be addressed.  

The other method to keep in mind are [__hash__ and in turn _pkey ](https://github.com/conda/conda/blob/4.7.12/conda/models/records.py#L258-L278).  These establish package equality as discussed in #8302.

**Comment by jeremyjliu** [comment] 2019-10-01 17:38
Thanks @jjhelmus! I ended up doing the former that you mentioned.

**Closed** 2019-11-27 17:48 UTC
Labels: tag-solver, type-bug
