### ISSUE TITLE
conda update conda not working (valueError could not be decoded)

### ISSUE THREAD

**Issue by mukolx** [conda/conda#1400] opened 2015-06-27 13:37 UTC
_Trying to run_  __conda update conda__ _I get the following error_

micah@:~
16:27:35  $ conda update conda
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/micah/.anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 261, in install
    for dist in linked]
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/install.py", line 488, in is_linked
    return json.load(fi)
  File "/home/micah/.anaconda/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/home/micah/.anaconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/home/micah/.anaconda/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/micah/.anaconda/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded

-------------
_results of _ __conda info__ _is as follows_

micah@:~
16:34:37  $ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.10.2
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/micah/.anaconda  (writable)
  default environment : /home/micah/.anaconda
     envs directories : /home/micah/.anaconda/envs
        package cache : /home/micah/.anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ilanschnell** [comment] 2015-06-29 19:55
I cannot reproduce the error.  Can you try running the command again.  It looks like the error is either with the online repository data, or a download error of that repo data occurred.

**Comment by mukolx** [comment] 2015-07-01 07:07
Dear Ilan Schnell,

_The problem still persists_
---------------------------------------------------------------------------------------------------
micah@:~
10:02:42  $ conda update conda
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/micah/.anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 261, in install
    for dist in linked]
  File "/home/micah/.anaconda/lib/python2.7/site-packages/conda/install.py", line 488, in is_linked
    return json.load(fi)
  File "/home/micah/.anaconda/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/home/micah/.anaconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/home/micah/.anaconda/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/micah/.anaconda/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

---------------------------------------------------------------------------------------------------
   __conda info output__
------------------------------------

micah@:~
10:03:15  $ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.10.2
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/micah/.anaconda  (writable)
  default environment : /home/micah/.anaconda
     envs directories : /home/micah/.anaconda/envs
        package cache : /home/micah/.anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by agude** [comment] 2016-04-09 15:34
Did this ever get resolved @mukolx ? I get the same error, but I suspect it might be a remote server issue (in which case I would expect it to fix itself when the server comes back).

Perhaps it is because the JSON files at https://repo.continuum.io/pkgs/pro/noarch/ are all empty?

https://repo.continuum.io/pkgs/pro/noarch/index.json:
```{}```

https://repo.continuum.io/pkgs/pro/noarch/repodata.json:
```{
  "info": {},
  "packages": {}
}```

## Conda Info

```
Current conda install:

             platform : linux-64
        conda version : 3.18.5
  conda-build version : 1.11.0
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : $HOME/bin/anaconda  (writable)
  default environment : $HOME/bin/anaconda
     envs directories : $HOME/bin/anaconda/envs
        package cache : $HOME/bin/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False```

**Comment by agude** [comment] 2016-04-11 16:24
Some additional debugging: If I move my anaconda directory over (via rsync for example) to a new computer, it does reproduce the error, suggesting some local configuration has gotten mangled, although I'm not sure how that would have happened.

If I have time this evening I'll try bisecting my backups and figure out at what point the mangling happened .

**Comment by soapy1** [comment] 2016-10-25 14:52
@mukolx @agude is this still an issue for you?

**Comment by agude** [comment] 2016-10-25 16:14
@soapy1 Fortunately (or maybe, unfortunately) not. I was never able to debug it, so I blew away the install and started from scratch. I have not encountered the problem again though.

**Comment by soapy1** [comment] 2016-10-25 16:38
Cool, I'm going to close this issue then. If it comes up again it can be reopened or a new issue can be filed 😸

**Closed by soapy1** 2016-10-25 16:38 UTC
