### ISSUE TITLE
Error: ERROR: placeholder...

### ISSUE THREAD

**Issue by necrolyte2** [conda/conda#2353] opened 2016-04-13 16:52 UTC
```
Linking packages ...
Error: ERROR: placeholder '/root/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placehold_p' too short in: ncurses-5.9-4
```

```
$ miniconda/bin/conda info
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /media/People/tyghe.vallard/Projects/GithubRelease/Software/ngs_mapper-latest/miniconda  (writable)
  default environment : /media/People/tyghe.vallard/Projects/GithubRelease/Software/ngs_mapper-latest/miniconda
     envs directories : /media/People/tyghe.vallard/Projects/GithubRelease/Software/ngs_mapper-latest/miniconda/envs
        package cache : /media/People/tyghe.vallard/Projects/GithubRelease/Software/ngs_mapper-latest/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/BioBuilds/linux-64/
                        https://conda.anaconda.org/BioBuilds/noarch/
                        https://conda.anaconda.org/vdbwrair/linux-64/
                        https://conda.anaconda.org/vdbwrair/noarch/
                        https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /media/People/tyghe.vallard/.condarc
    is foreign system : False
```

**Comment by msarahan** [comment] 2016-04-13 17:05
Duplicate of https://github.com/conda/conda-build/pull/877 - please discuss there.

**Closed by msarahan** 2016-04-13 17:05 UTC

**Comment by nsoranzo** [comment] 2016-06-16 19:53
@msarahan From conda/conda-build#877 I get that you fixed a problem in conda-build, but how can users workaround the above error when using "conda create" in the mean time?

**Comment by msarahan** [comment] 2016-06-16 20:06
The only workaround right now is to get a shorter working path however you can.  This merge is very disruptive - it will effectively require the rebuild of any package with an embedded PATH.  That's going to end up being a large job.  We put this change off until the 2.0 release - which will be after the Anaconda 4.1 release at the end of the month.

Once that has been released, we'll need to start rebuilding packages with conda build 2.0.  Once all the packages you use have been rebuilt, this PR will have its full positive effect.

**Comment by nsoranzo** [comment] 2016-06-17 09:54
@msarahan Thanks for the info. One thing I don't understand is why this seems to happen only for some unlucky users but not to everybody, any clue?
