### ISSUE TITLE
Use conda to check for the installation integrity

### ISSUE THREAD

**Issue by duytrung** [conda/conda#5721] opened 2017-07-25 03:08 UTC
Hi everybody,

I have a question. I installed anaconda to my laptop but for some unexpected reason, the computer restarted when the installation was running. I wonder if any tool to check for the package installation integrity when such incident happen. Reinstallation seems reasonable but I'm after an automated tool because I have installed additional packages so it took time.

Thanks for your suggestions.

Regards

**Comment by kalefranz** [comment] 2018-02-22 12:47
In effect a duplicate of https://github.com/conda/conda/issues/474

**Closed** 2018-02-22 12:47 UTC
Labels: source:community, type:feature
