### ISSUE TITLE
multi-user conda: no write permissions to pkgs/cache/

### ISSUE THREAD

**Issue by nick-youngblut** [conda/conda#6378] opened 2017-11-30 12:17 UTC
I'm using `conda 4.3.29` on `Ubuntu 16.04.3` and am getting the following error when running `conda install -n MY_CONDA_ENV MY_NEW_PACKAGE`:

```
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.13.0
       root environment : /ebio/abt3_projects/software/miniconda3  (writable)
    default environment : /ebio/abt3_projects/software/miniconda3
       envs directories : /ebio/abt3_projects/software/miniconda3/envs
                          /ebio/abt3/nyoungblut/.conda/envs
          package cache : /ebio/abt3_projects/software/miniconda3/pkgs
                          /ebio/abt3/nyoungblut/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/qiime2/linux-64
                          https://conda.anaconda.org/qiime2/noarch
            config file : /ebio/abt3/nyoungblut/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.13.0 CPython/3.6.3 Linux/4.4.67 debian/stretch/sid glibc/2.23
                UID:GID : 6354:350

`$ /ebio/abt3_projects/software/miniconda3/bin/conda install -n py3_physeq r-dplyr r-tidyr r-ggplot2`


    Traceback (most recent call last):
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/ebio/abt3_projects/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/ebio/abt3_projects/software/miniconda3/pkgs/cache/ffeee55f.json'
```

I checked the permissions of `./pkgs/cache/`, and the directory (or sub-directories) do not have write permissions for the user group. Thus, can don't have permissions to write to ./pkgs/cache/`.

I've created this issue based on the instructions listed in [Issue 4644](https://github.com/conda/conda/issues/4644)

**Comment by nick-youngblut** [comment] 2018-02-04 07:45
Myself and other members of my lab are still constantly running into this permissions issue. We always have to wait for the current owner of `./pkgs/cache/` to change permissions. I'm just wondering if there's been any progress on this issue or maybe there's a good work-around (at least for now).

**Comment by kalefranz** [comment] 2018-02-24 11:06
I think the root cause here is probably tracked in a couple other issues.

https://github.com/conda/conda/issues/6610
https://github.com/conda/conda/issues/6576

As in #6576, we're trying to make progress.  Obviously need some further work still though.

Closing this issue in lieu of the others.

**Closed by kalefranz** 2018-02-24 11:06 UTC

**Comment by daveuu** [comment] 2019-08-05 15:47
See [here](https://github.com/conda/conda/issues/7227#issuecomment-518289063) for a solution
