### ISSUE TITLE
conda unconditionally attempts to chown .conda/environments.txt even when it is not necessary

### ISSUE THREAD

**Issue by ezyang** [conda/conda#6576] opened 2017-12-25 21:01 UTC
Steps to reproduce:

1. Delete `.conda/environments.txt`, confirm that `.conda` is correctly permissioned.
2. Run `conda install` with a recent Conda (I'm running 4.4.4-py27_0) from a user that does not have `chown` rights (for example, by default a user in a Docker environment will not have the ability to chown)

Expected result: It works

Actual result: conda attempts to chown the file (which already has the right ownership) and fails

Here is a real transaction which failed:

```

root@a110994e25e1:/# cd /tmp
root@a110994e25e1:/tmp# mkdir /opt/conda
root@a110994e25e1:/tmp# chown jenkins:jenkins /opt/conda
root@a110994e25e1:/tmp# wget -q https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
root@a110994e25e1:/tmp# sudo -H -u jenkins ./Miniconda2-latest-Linux-x86_64.sh -b -f -p /opt/conda
sudo: ./Miniconda2-latest-Linux-x86_64.sh: command not found
root@a110994e25e1:/tmp# chmod +x Miniconda2-latest-Linux-x86_64.sh
root@a110994e25e1:/tmp# sudo -H -u jenkins ./Miniconda2-latest-Linux-x86_64.sh -b -f -p /opt/conda
PREFIX=/opt/conda
installing: python-2.7.14-h1571d57_29 ...
Python 2.7.14 :: Anaconda, Inc.
installing: ca-certificates-2017.08.26-h1d4fec5_0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: libgcc-ng-7.2.0-h7cc24e2_2 ...
installing: libstdcxx-ng-7.2.0-h7a57d05_2 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.0-h9df7e31_2 ...
installing: openssl-1.0.2n-hb7f436b_0 ...
installing: tk-8.6.7-hc745277_3 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1-heed3624_0 ...
installing: readline-7.0-ha6073c6_4 ...
installing: sqlite-3.20.1-hb898158_2 ...
installing: asn1crypto-0.23.0-py27h7b0c810_0 ...
installing: certifi-2017.11.5-py27h71e7faf_0 ...
installing: chardet-3.0.4-py27hfa10054_1 ...
installing: enum34-1.1.6-py27h99a27e9_1 ...
installing: idna-2.6-py27h5722d68_1 ...
installing: ipaddress-1.0.18-py27h337fd85_0 ...
installing: pycosat-0.6.3-py27ha4109ae_0 ...
installing: pycparser-2.18-py27hefa08c5_1 ...
installing: pysocks-1.6.7-py27he2db6d2_1 ...
installing: ruamel_yaml-0.11.14-py27h672d447_2 ...
installing: six-1.11.0-py27h5f960f1_1 ...
installing: cffi-1.11.2-py27ha7929c6_0 ...
installing: setuptools-36.5.0-py27h68b189e_0 ...
installing: cryptography-2.1.4-py27h6697b16_0 ...
installing: wheel-0.30.0-py27h2bc6bb2_1 ...
installing: pip-9.0.1-py27ha730c48_4 ...
installing: pyopenssl-17.5.0-py27hcee3be0_0 ...
installing: urllib3-1.22-py27ha55213b_0 ...
installing: requests-2.18.4-py27hc5b0589_1 ...
installing: conda-4.3.31-py27_0 ...
installation finished.
root@a110994e25e1:/tmp# sudo -H -u jenkins /opt/conda/bin/conda install -q -y mkl numpy pyyaml


Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    futures:      3.2.0-py27h7b459c0_0 
    intel-openmp: 2018.0.0-hc7b2577_8  
    mkl:          2018.0.1-h19d6760_4  
    numpy:        1.13.3-py27hbcc08e0_0
    pyyaml:       3.12-py27h2d70dd7_1  

The following packages will be UPDATED:

    conda:        4.3.31-py27_0         --> 4.4.4-py27_0

root@a110994e25e1:/tmp# sudo -H -u jenkins /opt/conda/bin/conda install -q -y nnpack -c killeent
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - nnpack


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nnpack-0.0.1               |       h310ec7a_1         1.1 MB  killeent

The following NEW packages will be INSTALLED:

    nnpack: 0.0.1-h310ec7a_1 killeent

Preparing transaction: ...working... done
Verifying transaction: ...working... failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /var/lib/jenkins/.conda/environments.txt
  uid: 1014
  gid: 1014

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 1014:1014 /var/lib/jenkins/.conda/environments.txt

In general, it's not advisable to use 'sudo conda'.

```

Interestingly, running the command again works. Looking at the strace makes it clear what's happening:

```
lstat("/var/lib/jenkins/.conda/environments.txt", 0x7ffd44341090) = -1 ENOENT (No such file or directory)
stat("/var/lib/jenkins/.conda", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/lib/jenkins/.conda", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/var/lib/jenkins/.conda/environments.txt", O_WRONLY|O_CREAT|O_APPEND, 0666) = 6
chown("/var/lib/jenkins/.conda/environments.txt", 0, 0) = -1 EPERM (Operation not permitted)
failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /var/lib/jenkins/.conda/environments.txt
  uid: 1014
  gid: 1014

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 1014:1014 /var/lib/jenkins/.conda/environments.txt

In general, it's not advisable to use 'sudo conda'.

```

It is successfully making the file, but then failing on chown. Second time around, it notices the file exists with correct permissions, and does not bother chowning again.

**Comment by kalefranz** [comment] 2017-12-25 21:15
Does https://github.com/conda/conda/pull/6570 help with this at all?

**Comment by ezyang** [comment] 2017-12-25 21:32
Hi @kalefranz, I am not familiar with the conda development process, and when I attempted to use the instructions in README to install a development version of conda, it broke my conda executable:

```
jenkins@1c5b427a5ee1:~$ git clone https://github.com/kalefranz/conda/
Cloning into 'conda'...
remote: Counting objects: 57193, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 57193 (delta 15), reused 25 (delta 13), pack-reused 57154
Receiving objects: 100% (57193/57193), 17.63 MiB | 0 bytes/s, done.
Resolving deltas: 100% (42002/42002), done.
Checking connectivity... done.
jenkins@1c5b427a5ee1:~$ cd conda
jenkins@1c5b427a5ee1:~/conda$ git checkout fix-6569-writing-to-HOME
Branch fix-6569-writing-to-HOME set up to track remote branch fix-6569-writing-to-HOME from origin.
Switched to a new branch 'fix-6569-writing-to-HOME'
jenkins@1c5b427a5ee1:~/conda$ /opt/conda/
bin/                         envs/                        lib/                         ssl/                         
compiler_compat/             etc/                         pkgs/                        x86_64-conda_cos6-linux-gnu/ 
conda-meta/                  include/                     share/                       
jenkins@1c5b427a5ee1:~/conda$ source /opt/conda/bin/activate 
(base) jenkins@1c5b427a5ee1:~/conda$ cd conda^C
(base) jenkins@1c5b427a5ee1:~/conda$ ls
CHANGELOG.md  MANIFEST.in  README.rst	 circle.yml  conda.recipe  conftest.py	setup.py  utils
LICENSE.txt   Makefile	   appveyor.yml  conda	     conda_env	   setup.cfg	tests
(base) jenkins@1c5b427a5ee1:~/conda$ which python
/opt/conda/bin/python
(base) jenkins@1c5b427a5ee1:~/conda$ python setup.py develop

WARNING: Your current install method for conda only supports conda
as a python library.  You are not installing a conda executable command
or activate/deactivate commands.  If your intention is to install conda
as a standalone application, currently supported install methods include
the Anaconda installer and the miniconda installer.  If you'd still like
for setup.py to create entry points for you, use `utils/setup-testing.py`.

--- >8 snip >8 ---

Using /opt/conda/lib/python2.7/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /opt/conda/bin

Using /opt/conda/lib/python2.7/site-packages
Finished processing dependencies for conda==4.3.19.post1658+43f8531
(base) jenkins@1c5b427a5ee1:~/conda$ conda --version
Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 11, in <module>
    load_entry_point('conda', 'console_scripts', 'conda')()
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2750, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'conda') not found
```

**Comment by danielkza** [comment] 2018-01-04 17:06
I believe I've found the root cause of the issue, and it is not simply trying to write to the home dir. That is actually a pretty reasonable expectation for most programs.

Instead, the code of [mkdir_p_sudo_safe](https://github.com/conda/conda/blob/c72c237a354c3fd9629d800311ba6a2b8a95d1d1/conda/gateways/disk/__init__.py#L69) makes the bad assumption that any use of `sudo` with Anaconda is a user mistake, and that it should just write files as the original user instead (from the `SUDO_UID` env var). 

In my case using sudo is correct and intended. I'm automating the installation of JupyterHub using Ansible, and I *want* to drop from root to an unprivileged user to create a virtual environment that can be read by that user. I do not want any files to be created as root, and the home directory is correctly set by Ansible.

**Comment by ezyang** [comment] 2018-02-24 02:06
Thank you for the analysis @danielkza. A recent conda update broke our old workaround, so we're using this workaround now:

```
  as_jenkins() {
    # NB: unsetting the environment variables works around a conda bug
    # https://github.com/conda/conda/issues/6576
    sudo -H -u jenkins env -u SUDO_UID -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER $*
  }
```

**Comment by elelayan** [comment] 2018-03-27 15:42
Thanks @ezyang for the workaround. I've instead done it to my install script:
```
unset SUDO_UID SUDO_GID SUDO_COMMAND SUDO_USER
```

**Comment by kalefranz** [comment] 2018-04-27 05:06
A fix for this is in the master branch, which is currently the release branch for 4.6.0.  A 4.6.0a1 build exists that you can test in the `conda-canary` channel.

**Closed by kalefranz** 2018-04-27 05:06 UTC
Labels: s:2, source:community, type:bug

**Comment by tdhopper** [comment] 2021-07-29 15:50
@hhuuggoo Did you ever find a solution for that in jupyterhub?
