### ISSUE TITLE
Regression in conda 4.3.33 regarding build features

### ISSUE THREAD

**Issue by SylvainCorlay** [conda/conda#6833] opened 2018-02-02 14:20 UTC
It seems that `conda 4.3.33` installs packages that have a build feature when installing any package that has the same build feature.

From a fresh miniconda, with conda pinned at `4.3.32`:

```sh
scorlay@mbp ~]$ conda install cryptopp -c QuantStack -c conda-forge
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/scorlay/miniconda3:

The following NEW packages will be INSTALLED:

    cling-patches: 1-0           QuantStack
    cryptopp:      5.6.5-cling_0 QuantStack [cling]
```

With `conda 4.3.33`

```sh
[scorlay@mbp ~]$ conda install cryptopp -c QuantStack -c conda-forge
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/scorlay/miniconda3:

The following NEW packages will be INSTALLED:

    clangdev:      5.0.0-cling_1 QuantStack  [cling]
    cling-patches: 1-0           QuantStack 
    cryptopp:      5.6.5-cling_0 QuantStack  [cling]
    icu:           58.2-0        conda-forge
    libiconv:      1.15-0        conda-forge
    libxml2:       2.9.7-0       conda-forge
    llvmdev:       5.0.0-cling_1 QuantStack  [cling]
```

The only package tracking the `cling` build feature is `cling-patches`.

Notice in the second case that `clangdev` gets installed while it is not a dependency.

**Comment by SylvainCorlay** [comment] 2018-02-02 14:23
As per @jjhelmus 's comment, this might be due to #6766. @mcg1969 .

**Comment by mbargull** [comment] 2018-02-02 14:37
Cannot reproduce thiswith a fresh `Miniconda3-4.3.31-Linux-x86_64.sh` installation updated to `conda 4.3.32`:
```bash
$ conda --version
conda 4.3.32
$ conda create -qnx --dry-run -c QuantStack -c conda-forge cryptopp cling@


Package plan for installation in environment /home/maba/code/conda/mc4332/envs/x:

The following NEW packages will be INSTALLED:

    cling-patches: 1-0           QuantStack
    cryptopp:      5.6.5-cling_0 QuantStack [cling]
    libgcc-7:      7.2.0-0       QuantStack

$ conda install -qy conda=4.3.33


Package plan for installation in environment /home/maba/code/conda/mc4332:

The following packages will be UPDATED:

    conda: 4.3.32-py36_0 --> 4.3.33-py36_0

$ conda create -qnx --dry-run -c QuantStack -c conda-forge cryptopp cling@


Package plan for installation in environment /home/maba/code/conda/mc4332/envs/x:

The following NEW packages will be INSTALLED:

    cling-patches: 1-0           QuantStack
    cryptopp:      5.6.5-cling_0 QuantStack [cling]
    libgcc-7:      7.2.0-0       QuantStack
```
Can you give more information on your environment? (E.g., fill out the issue template.)

**Comment by SylvainCorlay** [comment] 2018-02-02 14:37
This is something I am seeing on OS X.

**Comment by mcg1969** [comment] 2018-02-02 14:41
Features need to die a fiery death. They simply are not SAT representable as conceived :-(

I will see what I can do.

**Comment by SylvainCorlay** [comment] 2018-02-02 15:00
> Features need to die a fiery death. They simply are not SAT representable as conceived :-(
> I will see what I can do.

What should I used instead.

**Comment by mcg1969** [comment] 2018-02-02 15:02
@SylvainCorlay can we get a `conda create` recipe from you that can reproduce the problem, so that it can be reliably reproduced?

**Comment by mcg1969** [comment] 2018-02-02 15:02
> What should I used instead.

It depends exactly what you are trying to do.

**Comment by SylvainCorlay** [comment] 2018-02-02 15:12
> @SylvainCorlay can we get a conda create recipe from you that can reproduce the problem, so that it can be reliably reproduced?

I don't understand what you would like here.

**Comment by mcg1969** [comment] 2018-02-02 16:03
Your examples involve `conda install` commands --- I wonder if you can give us a `conda create` command instead that reveals the issue. With `conda install`, it assumes an existing envrionment with a set of packages that might be influencing the solution.

**Comment by SylvainCorlay** [comment] 2018-02-02 17:21
ok will do. FYI, I produced this from the root environment of a newly installed miniconda.

**Comment by SylvainCorlay** [comment] 2018-02-06 22:47
Note: I am not reproducing with `conda create`. Only `conda install`.

**Comment by mbargull** [comment] 2018-02-06 23:03
`conda create` reproducer:
```
|$ conda --version
conda 4.3.32
|$ CONDA_SUBDIR=osx-64 conda create -qnx --dry-run -c QuantStack -c conda-forge cryptopp icu


Package plan for installation in environment /home/maba/code/conda/conda-4.3/envs/x:

The following NEW packages will be INSTALLED:

    cling-patches: 1-0           QuantStack 
    cryptopp:      5.6.5-cling_0 QuantStack  [cling]
    icu:           58.2-0        conda-forge

|$ conda install -qy conda=4.3.33


Package plan for installation in environment /home/maba/code/conda/conda-4.3:

The following packages will be UPDATED:

    conda: 4.3.32-py36_0 --> 4.3.33-py36_0

|$ CONDA_SUBDIR=osx-64 conda create -qnx --dry-run -c QuantStack -c conda-forge cryptopp icu


Package plan for installation in environment /home/maba/code/conda/conda-4.3/envs/x:

The following NEW packages will be INSTALLED:

    clangdev:      5.0.0-cling_1 QuantStack  [cling]
    cling-patches: 1-0           QuantStack 
    cryptopp:      5.6.5-cling_0 QuantStack  [cling]
    icu:           58.2-0        conda-forge
    libiconv:      1.15-0        conda-forge
    libxml2:       2.9.7-0       conda-forge
    llvmdev:       5.0.0-cling_1 QuantStack  [cling]
    xz:            5.2.3-0       conda-forge
    zlib:          1.2.11-0      conda-forge
```
(uses `CONDA_SUBDIR=osx-64` as I'm on Linux).
To reproduce it, all parts of `-c QuantStack -c conda-forge cryptopp icu` are needed.

**Comment by kalefranz** [comment] 2018-02-07 08:09
@mcg1969 has told me that he probably supports reverting #6766 in a conda 4.3.34 release.  Do you agree @mbargull?

**Comment by mbargull** [comment] 2018-02-07 13:04
That breaks my heart 😢. That PR improved the situation on previously failing cases a lot.
Reverting that #6766 would mean we are back to square one for https://github.com/conda/conda/issues/6269#issuecomment-344077631.
I still agree with
https://github.com/conda/conda/issues/6833#issuecomment-362604480:
> Features need to die a fiery death. They simply are not SAT representable as conceived :-(

https://github.com/conda/conda/pull/6296#issuecomment-347257443:
> We have discussed this at length internally. @mcg1969 is very hesitant to change anything about how features work. There's a lot of pain there, and his opinion is that it's very hard to anticipate any potential breakage from this PR.

But still, I had hoped those latest changes were to stay 😞.

**Comment by mcg1969** [comment] 2018-02-07 13:10
Well, for a short time, people who experienced regressions can pin conda to an earlier version. But we need to figure something out soon.

**Comment by mcg1969** [comment] 2018-02-07 13:20
We did just discover something useful that may help us form a solution. It turns out that just using a `track_feature` _with no corresponding `feature` packages_ has a useful interpretation for establishing preferences. I'm trying to see if we can reproduce that useful quality.

**Comment by SylvainCorlay** [comment] 2018-02-07 13:32
conda-forge relies a lot on build featutes for MSVC flavors. We do a lot at QuantStack for flavors of builds of llvm (for cling which requires patches).

In another case, we have used it to overcome problems with channel priorities not being respected, ehich appears to have been solved since but a lot of our builds still have the features.

**Comment by kalefranz** [comment] 2018-02-07 14:02
Maybe a compromise would be to revert it in 4.3 but leave it in 4.4? Idk.

**Comment by SylvainCorlay** [comment] 2018-02-07 14:04
May be @conda-forge/core would have an opinion on this. If it is a backward incompatible change, it would probably deserve a `5.0`.

Is there a good alternative to build features at the moment?

**Comment by mbargull** [comment] 2018-02-07 14:38
> Maybe a compromise would be to revert it in 4.3 but leave it in 4.4? Idk.

`conda-forge` and `bioconda` both benefit from `4.3.33` in some cases (and still need some time to update to 4.4)...

> If it is a backward incompatible change, it would probably deserve a `5.0`.

In regards to solver logic, there were already some changes in 4.x (channel priority, timestamps) -- so it's not the case that 4.x was stable in that regard anyway... (That's just mean as an objective and *not* suggestive comment.)
@SylvainCorlay, I haven't yet completely assessed the severity of the issue `4.3.33` introduced for you. Would that be a workflow-breaking change or could it be (in a broader sense) seen as an "inconvenience". I know that the introduction of additional packages (esp. during build) is undesirable, but the question is if that is workflow breaking or not.
This is not to downplay the issue, just to put it into perspective to the issues #6766 helped with (some of them were workflow-breaking), so we can decide, based on severity, what we should do.

**Comment by mcg1969** [comment] 2018-02-07 16:48
I know that some of the larger package sets are relying on features---indeed Anaconda does too, although less so now than it used to. I also know that I've seen multiple instances of packages that use features _incorrectly_, or at least, in a way contrary to advice I have repeatedly given in the past. 

In particular, it is generally bad practice for package A to _depend_ on a package B that has a `track_feature`. This _forces_ package B, and its `track_feature`, to be brought into an environment when package A is installed. And one of the key aspects of features is that they aren't brought in unless specifically requested, not accidentally or indirectly. To be clear, I don't know to what degree that is happening in the packages causing problems here.

The problem with features is that people are relying on behavior that, to be frank, is not fully understood---by anyone, including me. I mean, I have an _idea_ about how I want them to behave, but again, that behavior is _not representable by SAT logic_, so the best we can do is a heuristic. And so when we try to make corrections for clearly bad behavior, we are sometimes breaking others.

So I really, really, really want to avoid this kind of mistake again.

That said: I have an idea for another approach to the `generate_feature_metric` method; @mbargull you may want to try this. The idea is this. Right now the two feature optimization passes are:

1. Minimize the number of active features activated.
2. Maximize the number of packages installed that contain an active feature.

The problem has been with step 2 there, and how it has been implemented. Indeed, as I've stated it here, it's quite obvious why it's causing the problems @SylvainCorlay is seeing now. But I think a better metric is this:

2. Minimize the number of packages installed with _feature mismatch_. That is: the package _has_ a featured alternative, but it was not installed for other reasons (say, dependency conflicts).

Here is the code I've written to generate this optimization metric. @mbargull it doesn't break the test I created for PR #6766. And I _believe_ this will resolve the behavior we're seeing here, because it's not doing anything to _favor_ the installation of a package you didn't ask for.

```
    def generate_feature_metric(self, C):
        eq = {}  # a C.minimize() objective: Dict[varname, coeff]
        # Given a pair (dist, feature), assign a "1" score IF:
        # - The dist is installed
        # - The dist does NOT require the feature
        # - At least one package in the group DOES require the feature
        # - A package that tracks the feature is installed
        for name, group in iteritems(self.groups):
            dist_feats = {dist.full_name: self.features(dist) for dist in group}
            active_feats = set.union(*dist_feats.values()).intersection(self.trackers)
            for feat in active_feats:
                feat_spec = self.push_MatchSpec(C, '@' + feat)
                for dist, features in dist_feats.items():
                    if feat not in features:
                        mname = '{}/{} mismatch'.format(feat, dist)
                        C.name_var(C.And(dist, feat_spec), mname)
                        eq[mname] = 1
        return eq
```

**Comment by mcg1969** [comment] 2018-02-07 16:51
I'm still tweaking on that code, BTW, so don't assume this is what I'd ultimately want to see.

**Comment by mcg1969** [comment] 2018-02-07 17:02
However, this metric _does_ give me the desired result for
```
CONDA_SUBDIR=osx-64 conda create -qnx --dry-run -c QuantStack -c conda-forge cryptopp icu
```

**Comment by mcg1969** [comment] 2018-02-07 17:06
For anyone interested, check the `featmetric` branch.

**Comment by SylvainCorlay** [comment] 2018-02-07 18:45
So the reason why the installation of extra packages at build time is problematic for us is that the package in question is a compiler. Cling requires patched versions of clang and llvm at runtime.

The only package tracking the cling feature is the `cling-patches` empty package so we are following best practices on that front.

Now another requirement of the cling interpreter is that we have very strict requirements in terms of binary compatibility. For example the interpreted c++ must use the same STL that was used to *build* clang. So on linux it would be that of gcc-7, which we ship as a conda package on our channel. For similar reasons we need our own builds of other dependencies such as cryptopp, zeromq, which must also be built with gcc-7 on linux, or whichever host compiler we decide for on other platforms. We have been using build features to make sure that our version was picked up, versus the same package on default or conda forge.

Now to build these things, we must be careful about the version of clang used to build things (the conda package or the host version). The ultimate solution in the future for OS X will be to build clang with itself to prevent this mismatch between the host compiler and the version of clang used at runtime.

**Comment by SylvainCorlay** [comment] 2018-02-07 18:53
Quick note: this need for a completely bootstrapped distribution from the compiler to the top really makes me think that in order for this to work in the long run, miniconda / anaconda will need to have named versions like a linux distribution, and a different set of channels at each new major release of the disttibution.

For example miniconda-bald-eagle would be a gcc-7 bootstrapped disttibution which would pick pacjages on a bald-eagle default channel where everything is built with gcc-7 (on linux).

**Comment by mingwandroid** [comment] 2018-02-07 18:58
Anaconda is already completely bootstrapped with GCC 7, and has been since 5.0.0.

On Linux at least there's no need to avoid mixing GCC 7 and GCC 8 (for example) packages since the compiler runtimes are backwards compatible and we list the correct >= constraints for them when they appear in run dependencies.

Or am I missing something here? Are you talking about cling-based things only? I am confused by this comment.

**Comment by SylvainCorlay** [comment] 2018-02-07 19:09
Yeah, I am aware of anaconda 5, and it is great news.
Cling has tighter requirements that the usual libc binary dependency ones with the libc. It basically needs to be the same...
Also the bootstrapping on OS X would mean that the OS X conda package for clang would be built with itself.

**Comment by mingwandroid** [comment] 2018-02-07 19:46
OK, so you *are* just talking about cling.

> in order for this to work in the long run, miniconda / anaconda will need to have named versions like a linux distribution

Well, I don't think cling's very peculiar, tight binary compatibility problems are anything for AD to fret about (but yes, conda needs to do the right thing for you).

**Comment by johanneskoester** [comment] 2018-02-07 20:58
@SylvainCorlay does the featmetric branch solve the problem for you?

**Comment by mbargull** [comment] 2018-02-08 01:17
Just reviewed #6853. Those changes look great and I believe they should satisfy everyone's need on the matter!

**Comment by SylvainCorlay** [comment] 2018-02-08 08:44
@johanneskoester I confirm that the `featmetric` branch appears to be working correctly!

(I applied the patch on the top of 4.3.33 to be accurate.)

**Comment by kalefranz** [comment] 2018-02-08 14:04
My day is pretty packed, but I’ll try to get this merged and released.

**Closed** 2018-02-09 21:24 UTC
Labels: s:2, source:community, type:bug

**Comment by SylvainCorlay** [comment] 2018-02-09 21:27
Woot!

**Comment by kalefranz** [comment] 2018-02-09 21:56
Conda 4.3.34 has been uploaded to the `conda-canary` channel.

    conda config --add channels conda-canary
    conda install conda=4.3.34

Note it's not just `conda update conda` because there are a bunch of 4.4 releases in front of it.
