### ISSUE TITLE
Attempting to create an env from invalid file produces vague error

### ISSUE THREAD

**Issue by petebachant** [conda/conda#6319] opened 2017-11-17 19:05 UTC
I didn't nest pip dependencies properly under the conda dependencies in my `environment.yml` file, e.g.,

```yaml
dependencies:
  - numpy
pip:
  - something
```

and got this error

```
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Can't process without a name
```

when running

    conda env create

Perhaps invalid top level keys in environment files should be ignored or throw exceptions.

**Comment by kalefranz** [comment] 2018-01-25 00:12
Duplicate of https://github.com/conda/conda/issues/5681

**Closed by kalefranz** 2018-01-25 00:12 UTC
