### ISSUE TITLE
`conda init bash` writes to my bashrc

### ISSUE THREAD

**Issue by matthiasbeyer** [conda/conda#10297] opened 2020-10-20 08:20 UTC
## Current Behavior

```bash
$ sha1sum ~/.bashrc
f92d96590f161b3bf0048c81eefec34016d37044  [...]
$ conda init bash
[...]
$ sha1sum ~/.bashrc
967c823332fbc6d2a1d01ad588afd80a3e0c3d36  [...]
```

`conda init bash` touches my bashrc. I consider that a bug. Why does it do that? This is not necessary! This should _NEVER_ be done.

### Steps to Reproduce

Execute the commands from above.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : None
       user config file : $HOME/.condarc
 populated config files : $HOME/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __cuda=9.1
                          __glibc=2.17
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/3.10.0-1127.19.1.el7.x86_64 centos/7.8.2003 glibc/2.17
                UID:GID : 1955:999
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by wolfv** [comment] 2020-10-20 11:00
It's very much necessary. Why do you think it's not necessary? You can check the modifications in your bashrc file to figure out why it's done.

**Comment by christophprokop** [comment] 2020-10-20 11:16
Software can write into ~/.config/ or in ~/.${Softwarename} but why would i want another package *write* into one of the config files of another software.

**Comment by matthiasbeyer** [comment] 2020-10-20 11:17
It sources code from a tool that downloads binaries and code from the internet. What could possibly go wrong?

The stuff that is happening could easily be put into a command that one has to execute when working on something conda-related, which might simply spawn a customized subshell.

Right now, this executes arbitrary code from the internet (from a users perspective) upon shell initialization with user rights. This is a security concern IMO.

**Comment by wolfv** [comment] 2020-10-20 11:24
no-one forces you to run `conda init`. you can run conda by giving the absolute path to the conda binary and it should be fine.
If you're concerned about security, maybe run conda in a container? Conda anyways installs arbitrary packages on your computer. If you install a package with pip, you also execute arbitrary code from the internet ... there is no real difference here.

**Comment by wolfv** [comment] 2020-10-20 11:25
also bashrc is not really a config file of another software. it is a user-customizable init file for the bash shell. it's only purpose is to contain what the user wants.

If the user wants conda in that file (by running `conda init`) then it's totally fine to edit the bashrc file.

**Comment by matthiasbeyer** [comment] 2020-10-20 11:31
> If you install a package with pip, you also execute arbitrary code from the internet ... there is no real difference here.

The difference is that conda _always_ runs arbitrary code when I spawn a new shell!

> you can run conda by giving the absolute path to the conda binary and it should be fine.

If that would be the only concern here, you would only alter `$PATH` in the snippet - but conda adds much more to the `bashrc` file than just a simple `export PATH+=:...`.

**Comment by wolfv** [comment] 2020-10-20 11:43
yeah the one important piece it adds is the ability to run `conda activate ...` which in turn _executes more arbitrary_ code and adds more variables to $PATH ... depending on which environment you activate. 
If you have a good idea how to do that without essentially source'ing (or eval'ing) in the context of the currently running bash shell, then I would be interested to hear that. 

If you want to add a mechanism that writes out the necessary files and then spwan a new shell, I think that could be an interesting addition, but few people care greatly about that. Definitely not such a smooth usage.

You can get the contents you need to eval (for bash) with `conda shell.bash activate`

**Comment by matthiasbeyer** [comment] 2020-10-21 14:49
> yeah the one important piece it adds is the ability to run conda activate ... which in turn executes more arbitrary code and adds more variables to $PATH ... depending on which environment you activate.

Sounds like you want me to open more bug reports here, seriously!

> If you have a good idea how to do that without essentially source'ing (or eval'ing) in the context of the currently running bash shell, then I would be interested to hear that.

Open subshells and give them the environment they need. But never mess with the current shell. Especially because this hurts reproducability if cleanup isn't done right (and be assured: it is _never_ done correctly. There are _always_ things that slip through - but not with subshells!)

> If you want to add a mechanism that writes out the necessary files and then spwan a new shell, I think that could be an interesting addition

No need to write files, are there? Inheriting environment into the new shell is a perfectly fine way to configure environments!

**Comment by wolfv** [comment] 2020-10-21 15:02
Cool! I am sure you can write a simple script to do that. Would be great if you can share that here!

**Comment by wolfv** [comment] 2020-10-21 15:06
ie. this would probably do it:

```
$ conda shell.bash activate > /tmp/init.sh
$ bash --init-file /tmp/init.sh 
```

and can probably be further improved.

**Comment by matthiasbeyer** [comment] 2020-10-21 15:12
And why not `conda activate` and that starts a shell for me where I can develop in? Why do I have to work around your bugs?

**Comment by mcg1969** [comment] 2020-10-21 16:10
Given that this was a deliberate design decision made by the conda development team, and it is accomplishing exactly the task it is created to do, and behaving in the manner the team intended it to behave, it is by definition not a bug.

You've made it quite clear that it is behavior _you do not like_, but that doesn't make it a bug.

What you're asking for—to start a new shell with the desired environment—sounds very similar to what is done on Windows with the Command Line and Powershell menu items. And so it absolutely has merit. But the overwhelming majority of conda users are best served by the design as is.

**Comment by wolfv** [comment] 2020-10-21 17:41
@matthiasbeyer I think your tone is a little "off". It's definitely not a bug and works fantastically well for thousands of users.

**Comment by christophprokop** [comment] 2020-10-21 18:46
Call it a bug or something else. It's an open issue here on the github repo that contains some feedback. Things like "sudo curl $URI | sh" work "fantastically well for thousands of users" and are "smooth usage" - that does not make it better in any way. I don't understand why you defend the current way it works as if it was either the only way to go or in any way "elegant" or brilliant. It's a pretty straight forward approach that makes it work as intended ("deliberate design decision"? for a decision you need alternatives - right?). Now you have some feedback that it might have some flaws. Maybe discuss a bit and hear a few more people about it? So if the main problem is it that calling it a "bug", then please do rename it and let's discuss a little more...

**Comment by mcg1969** [comment] 2020-10-21 18:51
@christophprokop, we always welcome reasoned, constructive, and collaborative feedback like yours. In fact, the `conda init` behavior arose not out of a vacuum, but it evolved over years of interaction with the community. And we _have_ received and considered objections from people who disagree with the design choice. That said, I agree with @wolfv that the tone of this thread is "off" and is not productive, and will be closing the issue an disabling further comments.

**Closed by mcg1969** 2020-10-21 18:51 UTC
Labels: reso-wontfix
