### ISSUE TITLE
cairo is not supported in conda R 3.3.1

### ISSUE THREAD

**Issue by dyusuf** [conda/conda#3868] opened 2016-11-13 13:25 UTC
Hi,

There is no cairo in conda R 3.3.1 even it was built with cairo as one dependency according to the r channel recipe.

>capabilities('cairo')
cairo 
FALSE

Then I tried to separately install r-cario, here is the output,
$ conda install r-cairo

The following packages will be UPDATED:

r-cairo:       1.5_9-r3.3.1_0   r --> 1.5_9-r3.2.2_0a   r
r-class:       7.3_14-r3.3.1_0  r --> 7.3_14-r3.2.2_0a  r
r-codetools:   0.2_14-r3.3.1_0  r --> 0.2_14-r3.2.2_0a  r
r-foreign:     0.8_66-r3.3.1_0  r --> 0.8_66-r3.2.2_0a  r
r-kernsmooth:  2.23_15-r3.3.1_0 r --> 2.23_15-r3.2.2_0a r
r-lattice:     0.20_33-r3.3.1_0 r --> 0.20_33-r3.2.2_0a r
r-mass:        7.3_45-r3.3.1_0  r --> 7.3_45-r3.2.2_0a  r
r-rpart:       4.1_10-r3.3.1_0  r --> 4.1_10-r3.2.2_0a  r
r-spatial:     7.3_11-r3.3.1_0  r --> 7.3_11-r3.2.2_0a  r

The following packages will be DOWNGRADED due to dependency conflicts:

r:             3.3.1-r3.3.1_0   r --> 3.2.2-0           r
r-base:        3.3.1-3          r --> 3.2.2-0           r
r-boot:        1.3_18-r3.3.1_0  r --> 1.3_17-r3.2.2_0a  r
r-cluster:     2.0.4-r3.3.1_0   r --> 2.0.3-r3.2.2_0a   r
r-matrix:      1.2_6-r3.3.1_0   r --> 1.2_2-r3.2.2_0a   r
r-mgcv:        1.8_12-r3.3.1_0  r --> 1.8_9-r3.2.2_0a   r
r-nlme:        3.1_128-r3.3.1_0 r --> 3.1_122-r3.2.2_0a r
r-nnet:        7.3_12-r3.3.1_0  r --> 7.3_11-r3.2.2_0a  r
r-recommended: 3.3.1-r3.3.1_0   r --> 3.2.2-r3.2.2_0    r
r-survival:    2.39_4-r3.3.1_0  r --> 2.38_3-r3.2.2_0a  r

R 3.3.1 was automatically downgraded to R 3.2.2, then,

capabilities('cairo')
cairo 
TRUE

**Here is something wrong with cario in conda R 3.3.1.**

**Comment by mingwandroid** [comment] 2016-12-02 11:43
Closing as a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1239

**Closed by mingwandroid** 2016-12-02 11:43 UTC
