### ISSUE TITLE
 Error when using a conda environment file containing packages sourced from non-default channels

### ISSUE THREAD

**Issue by tomkinsc** [conda/conda#2800] opened 2016-06-21 18:27 UTC
I've been following the [documentation page](http://conda.pydata.org/docs/using/envs.html) on exporting and using an environment file and have run into a problem. I have an active conda environment with dependencies from the [bioconda channel](https://anaconda.org/bioconda), the default conda channel, as well as pip dependencies, and I'm trying to create a conda environment file that encapsulates all installed packages, both pip and (bio)conda. Exporting an environment file lists everything I have installed. 

When I try to create a new environment from the environment file, I receive an error that the bioconda-sourced packages are missing. Are environment files not intended to install packages from other channels? I assumed because of the bioconda-prefix "namespace notation" that the packages would be sourced from the appropriate channel.

A bit more about what I did:

An environment file was exported via `conda env export > environment.yml`.

The file looks like this (prefix changed for this example):

```
name: project-test-env
channels: !!python/object/new:ruamel_yaml.comments.CommentedSeq
  listitems:
  - bioconda
  - defaults
  state:
    _yaml_format: !!python/object:ruamel_yaml.comments.Format
      _flow_style: false
    _yaml_line_col: !!python/object:ruamel_yaml.comments.LineCol
      col: 2
      data:
        0:
        - 1
        - 4
        1:
        - 2
        - 4
      line: 1
dependencies:
- bioconda::bcftools=1.3.1=0
- bioconda::curl=7.45.0=1
- bioconda::htslib=1.3.1=0
- bioconda::peewee=2.8.0=py35_1
- bioconda::pysam=0.9.1=py35_0
- bioconda::python-dateutil=2.3=py35_0
- bioconda::samtools=1.3.1=1
- bioconda::selscan=1.1.0b=0
- biopython=1.67=np111py35_0
- ecdsa=0.13=py35_0
- libgcc=4.8.5=1
- mkl=11.3.3=0
- ncurses=5.9=0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- paramiko=1.16.0=py35_0
- pip=8.1.2=py35_0
- pycrypto=2.6.1=py35_4
- python=3.5.1=0
- pytz=2016.4=py35_0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - apipkg==1.4
  - boltons==16.4.1
  - coverage==4.1
  - coveralls==1.1
  - docopt==0.6.2
  - execnet==1.4.1
  - flake8==2.6.0
  - mccabe==0.5.0
  - mock==2.0.0
  - pbr==1.10.0
  - peewee==2.8.0
  - py==1.4.31
  - pycodestyle==2.0.0
  - pyflakes==1.2.3
  - pysam==0.9.1
  - pytest==2.9.2
  - pytest-cov==2.2.1
  - pytest-xdist==1.14
  - python-dateutil==2.3
  - requests==2.10.0
prefix: /path/to/my-env
```

Next I tried to use the environment file to setup a new environment:
`conda env create -f=environment.yml -n duplicate-env`

```
I receive the following error:
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
Error: Packages missing in current osx-64 channels:
  - bioconda::bcftools 1.3.1 0
  - bioconda::curl 7.45.0 1
  - bioconda::htslib 1.3.1 0
  - bioconda::peewee 2.8.0 py35_1
  - bioconda::pysam 0.9.1 py35_0
  - bioconda::python-dateutil 2.3 py35_0
  - bioconda::samtools 1.3.1 1
  - bioconda::selscan 1.1.0b 0
```

In the environment file, the "missing" packages specify the channel they should be coming from, so is it expected behavior that they are not being found? I'm not sure if it makes a difference, but I did place bioconda among the channels in my global config via "conda config --add channels bioconda" (before doing any of the above).

Here is the output from "conda info" (Miniconda3 install):

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:


             platform : osx-64
        conda version : 4.1.2
  conda-build version : 1.21.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/tomkinsc/miniconda3  (writable)
  default environment : /Users/tomkinsc/miniconda3
     envs directories : /Users/tomkinsc/miniconda3/envs
        package cache : /Users/tomkinsc/miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/bioconda/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/bioconda/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/tomkinsc/.condarc
    is foreign system : False
```

Thank you to any who can help shed some light on whether this is an internal conda issue, or whether I've made incorrect assumptions about how environment files are intended to work.

Thanks,
Chris

**Comment by tomkinsc** [comment] 2016-06-21 18:28
This issue follows a thread on the [conda Google group](https://groups.google.com/a/continuum.io/forum/#!topic/conda/j61cGzaHQS0).

**Comment by tomkinsc** [comment] 2016-06-21 18:42
Following advice from @ijstokes, I've confirmed that for my install of conda removing the channel prefixes from the environment file allows me to install the packages. Ideally in the future the channel namespaces would be honored to allow conda to disambiguate package origins.

**Comment by stevenengler** [comment] 2016-06-21 23:05
I have run into this same issue today as well. Removing the channel from the prefix is not enough to fix the error for me. I also have to add the following lines to the yaml file:

```
channels:
- channel_name
```

This can be seen in the [`from_yaml()`](https://github.com/conda/conda-env/blob/33c4e74f5cf6d4998e9aca1ddf26b3ce11f1df95/conda_env/env.py#L65) function.

I don't know enough about the conda source to make any edits myself, but following the source code (starting from the conda-env [`from_file()`](https://github.com/conda/conda-env/blob/33c4e74f5cf6d4998e9aca1ddf26b3ce11f1df95/conda_env/env.py#L68)), the line from the yaml is sent to [`conda.cli.common.spec_from_line()`](https://github.com/conda/conda/blob/master/conda/cli/common.py#L509), where it is parsed by the [regexp](https://github.com/conda/conda/blob/master/conda/cli/common.py#L495) above. It parses the name as "channel::package" which is obviously incorrect (same reason why `conda install channel::package` fails with the same error). I'm not sure if the name should be parsed properly here, or parsed properly further down the chain nearer to where it is actually loaded.

The easiest fix from my perspective would be to loop through all of the parsed dependencies in the [`Environment` constructor](https://github.com/conda/conda-env/blob/33c4e74f5cf6d4998e9aca1ddf26b3ce11f1df95/conda_env/env.py#L132), find which ones have the `::`, and remove the channel from the package name string. The channel could then be added to the Environment using the [add_channels()](https://github.com/conda/conda-env/blob/33c4e74f5cf6d4998e9aca1ddf26b3ce11f1df95/conda_env/env.py#L138) method.

The problem with this method is that I'm guessing it will automatically attempt to load the package from the standard Anaconda channel before loading it from the proper channel. Anyways I'll leave this to people who know what they're doing.

**Comment by jseabold** [comment] 2016-06-22 23:25
I just ran into a similar issue after upgrading to 4.1.2. from 4.0.x. Is it possible to export and then create an environment when non-default channels are in your `.condarc` in this version?

**Comment by kalefranz** [comment] 2016-06-23 01:07
I think the issue is that we need to make conda-env aware of ruamel_yaml and not let it use pyyaml.  Should be an easy PR if someone wants to go for it...

**Comment by mcg1969** [comment] 2016-06-23 03:03
I'm afraid it's more complex than that, @kalefranz. This is another casualty of the senseless separation of `conda-env` and `conda` into two projects. I think the right thing it do is exactly what @stevenengler is mentioning above

**Comment by mcg1969** [comment] 2016-06-23 03:03
But keep in mind this isn't an exact fix in that it can't guarantee that precisely the same packages will be selected from the same channels. For that a `conda list --explicit` output is going to do the trick.

**Comment by jseabold** [comment] 2016-07-12 14:26
See https://github.com/conda/conda-env/pull/261

**Comment by jseabold** [comment] 2016-07-12 14:53
This is probably a band-aid given the deeper issues noted in this issue but it would be great to get environments working again for even basic use cases.

**Comment by jseabold** [comment] 2016-07-12 15:33
Connecting all of the conversations I'm having with myself. It doesn't look like ruamel_yaml round-trips out of the box. Just using ruamel_yaml barfs on the thing output from conda.

```
In [10]: from conda.config import rc

In [11]: import ruamel_yaml

In [12]: rc['channels']
Out[12]: ['conda-forge', 'defaults']

In [13]: type(rc['channels'])
Out[13]: ruamel_yaml.comments.CommentedSeq

In [14]: ruamel_yaml.load(ruamel_yaml.dump(rc['channels']))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-b24e563cee49> in <module>()
----> 1 ruamel_yaml.load(ruamel_yaml.dump(rc['channels']))

/Users/civisemployee/.miniconda3/lib/python3.4/site-packages/ruamel_yaml/main.py in load(stream, Loader, version)
     73     loader = Loader(stream, version)
     74     try:
---> 75         return loader.get_single_data()
     76     finally:
     77         loader.dispose()

/Users/civisemployee/.miniconda3/lib/python3.4/site-packages/ruamel_yaml/constructor.py in get_single_data(self)
     59         node = self.get_single_node()
     60         if node is not None:
---> 61             return self.construct_document(node)
     62         return None
     63

/Users/civisemployee/.miniconda3/lib/python3.4/site-packages/ruamel_yaml/constructor.py in construct_document(self, node)
     63
     64     def construct_document(self, node):
---> 65         data = self.construct_object(node)
     66         while self.state_generators:
     67             state_generators = self.state_generators

/Users/civisemployee/.miniconda3/lib/python3.4/site-packages/ruamel_yaml/constructor.py in construct_object(self, node, deep)
    114             data = constructor(self, node)
    115         else:
--> 116             data = constructor(self, tag_suffix, node)
    117         if isinstance(data, types.GeneratorType):
    118             generator = data

/Users/civisemployee/.miniconda3/lib/python3.4/site-packages/ruamel_yaml/constructor.py in construct_python_object_new(self, suffix, node)
    745
    746     def construct_python_object_new(self, suffix, node):
--> 747         return self.construct_python_object_apply(suffix, node, newobj=True)
    748
    749 Constructor.add_constructor(

/Users/civisemployee/.miniconda3/lib/python3.4/site-packages/ruamel_yaml/constructor.py in construct_python_object_apply(self, suffix, node, newobj)
    736         instance = self.make_python_instance(suffix, node, args, kwds, newobj)
    737         if state:
--> 738             self.set_python_instance_state(instance, state)
    739         if listitems:
    740             instance.extend(listitems)

/Users/civisemployee/.miniconda3/lib/python3.4/site-packages/ruamel_yaml/constructor.py in set_python_instance_state(self, instance, state)
    698                 slotstate.update(state)
    699             for key, value in slotstate.items():
--> 700                 setattr(object, key, value)
    701
    702     def construct_python_object(self, suffix, node):

TypeError: can't set attributes of built-in/extension type 'object'
```

**Comment by kalefranz** [comment] 2016-07-13 02:45
> ruamel_yaml.load(ruamel_yaml.dump(rc['channels']))

The problem here, I think, is that `rc['channels']` is a list.  And you can't dump a list to yaml, only a dict/map.

Still looking into this though.

**Comment by jseabold** [comment] 2016-07-13 03:15
See above for the type of `rc['channels']` at least for me. In conda-env it ends up being a mixture of things because only `rc['channels']` is a ruamel_yaml type. That's why I coerce it to a list in that PR. I couldn't figure out what to do with it otherwise (or why I care for anything other than what's supported by pyyaml, but I don't understand why the other yaml library is necessary).

**Comment by jseabold** [comment] 2016-07-13 03:20
That definitely needs a regression test though. I started on one today but didn't arrive at one I was happy with and didn't circle back.

**Comment by kalefranz** [comment] 2016-07-13 14:37
I don't want to close this ticket quite yet, despite https://github.com/conda/conda-env/pull/261.  The *correct* solution here is to use ruamel_yaml or ruamel.yaml for conda-env instead of pyyaml.

**Comment by stevenengler** [comment] 2016-07-13 14:59
I'm not familiar with ruamel_yaml, but how does it handle the `::` syntax differently than pyyaml?

**Comment by jseabold** [comment] 2016-07-13 15:58
I think there are two issues being conflated here. 

One is related to the `channels` section in the above example. That is fixed by avoiding the ruamel_yaml types or otherwise handling them correctly. 

The other issue is the `channel::package` syntax. The `::` syntax necessitates fixing the regex in conda, no? I haven't seen that syntax in my environments and don't know how it gets produced. I just always prefer the first place a package is found as defined by the order of the channels.

**Comment by stevenengler** [comment] 2016-07-13 17:07
Ah sorry, I completely missed the weird `channels` formatting in the yaml in the OP. I have a feeling that these changes won't be quite enough to fix the issue I was having, so I think once ruamel_yaml and the regexp are fixed, this can be closed (since it should solve the OP), and any remaining issues can be brought up in new issues.

Personally I like the idea of having the channel name with the package name so that you are 100% sure that the environment yaml represents your environment. For example `conda env export > environment.yml` and `conda env create -f environment.yml` should create an environment exactly the same as the original (the process should be reversible). By having the channels separately at the top, you aren't guaranteed that the environment will be the same.

**Comment by jseabold** [comment] 2016-07-15 13:48
Thinking a bit more. Is the environment specification format written down
anywhere? That would make things much easier.

I can't be the only one who bristled at the kapsel announcement. By my
count, we now have 5 ways of making an environment in flight.

**Comment by jseabold** [comment] 2016-07-18 20:15
Ok, now I'm seeing the channels as part of the packages in my exported environment.yml files. I guess this was from a conda update? The intersection of where things come from is pretty difficult to follow (`conda create` vs `conda env create`). I guess I'll try to hunt this one down.

**Comment by jseabold** [comment] 2016-07-18 21:18
So does anyone have any idea how to solve this? Are there any hooks for installing at the package level from a channel rather than just adding the channels to the environment? 

As pointed out, this won't necessarily result in a reproducible environment. Since I have my `condarc` setup in order, it won't much matter from me if we strip the channel information. It looks like it's partially supported in `conda.resolve` but I'm going to have to spend more time than I care with this to fix it the right way. Stripping the channel information seems like the simplest solution to me to get back to something that at least kind of works.

**Comment by stevenengler** [comment] 2016-07-19 14:47
I think the answer at the moment is no, there are no hooks for installing at the package level from a channel when importing an environment. This would need to be developed, but I'm not sure what the best way is. Specifying channels and packages separately seems to be the approach taken by kapsel.

For the moment, there seems to be no real roadmap for conda env, which is demonstrated by Continuum Analytics' conda kapsel announcement, so I'm going to leave conda env alone until higher powers agree on standardizing something. Especially since conda env was just moved back to the conda repo. It seems like a bit of a throw-it-at-the-wall-and-see-what-sticks type of situation.

For whoever hasn't seen it, kapsel uses a similar [yaml structure](http://conda.pydata.org/docs/kapsel/config.html#environments-and-channels) to conda env, but it seems to be an entirely new code base (afaict). For example, the environment structure in kapsel is [here](https://github.com/conda/kapsel/blob/ccee786b33be2ec267efa0c16ba4163e60f1c5d8/conda_kapsel/env_spec.py). And [here](https://github.com/conda/kapsel#if-youve-been-using-conda-env-and-environmentyml)'s a short paragraph for the difference between kapsel and conda env.

**Comment by jseabold** [comment] 2016-07-19 15:06
Yeah, unfortunately, I think there are a lot of projects that have been built around conda environments, and I've also written a lot of code that came to rely on them. 

I wonder if the changes that export the channel in the package name shouldn't be reverted given that they don't get handled. What was the motivation for this given that the information doesn't appear to be able to be used? I feel like I'm just missing something.

**Comment by jseabold** [comment] 2016-07-19 16:17
I added a flag `--skip-channel-prefix` to at least workaround the problem. Can someone in this issue can do code review? Can discuss open questions on the PR.

**Comment by stevenengler** [comment] 2016-07-19 16:18
I have summarized the issues here. Hopefully I didn't miss anything or say anything incorrectly.

### Problem 1:

I'm not sure if you fixed this, and I don't have this problem so I can't comment. There was a channel formatting problem in the OP that looked like the following:

```
channels: !!python/object/new:ruamel_yaml.comments.CommentedSeq
  listitems:
  - bioconda
  - defaults
  state:
    _yaml_format: !!python/object:ruamel_yaml.comments.Format
      _flow_style: false
    _yaml_line_col: !!python/object:ruamel_yaml.comments.LineCol
      col: 2
      data:
        0:
        - 1
        - 4
        1:
        - 2
        - 4
      line: 1
```
### Problem 2:

I don't add any channels to conda explicitly (I have no `condarc`). When I add a package from a different channel, I use for example `conda install -c pandas bottleneck`. This installs only that specific package from that specific channel.

Because of this, I do not have a `channel` field in my exported environment yaml since my environment does not have any specific channels (the [`Environment.channels`](https://github.com/conda/conda/blob/master/conda-env/conda_env/env.py#L136) field is empty). This explains why the channels are not listed for me in my environment yaml. The solution to this depends on the approach taken for problem 3.

### Problem 3:

When exporting an environment as yaml, for packages from other channels, they are listed in the format `channel::package=num=num`. When importing this environment yaml, it throws an exception due to the `::` formatting. It doesn't know to parse the channel and package separately, and instead tries to install the package named `channel::package`. Therefore, importing the environment yaml throws the same exception as if you tried the command `conda install channel::package`.

------------

Problems 2 and 3 are related. There are two approaches to solving these problems.

### Approach 1 (Change output/yaml formatting):

The problem of the channel in the package name is caused by [`Environment.to_dict()`](https://github.com/conda/conda/blob/master/conda-env/conda_env/env.py#L144). It simply takes the [raw](https://github.com/conda/conda/blob/master/conda-env/conda_env/env.py#L149) text package names and writes them to the yaml. Instead, it should parse them, maybe using [`common.arg2spec`](https://github.com/conda/conda/blob/fe411835e4c02c7e6c69421d7cf5f9fe79d39379/conda/cli/common.py#L470), and then remove the channel name before converting them back to text. When it removes the channel name, it then needs to be added to [`Environment.channels`](https://github.com/conda/conda/blob/master/conda-env/conda_env/env.py#L136) if it does not already exist in order for it to be written to the `channels` field in the yaml.

This leaves the problem that the import/export process is not reversible. If a package is installed with `conda install -c pandas bottleneck`, that channel should be used for that package only and not for all packages, but this approach does not do that.

### Approach 2 (Change input/yaml parsing):

The approach will let you keep the conda environment file as-is, and will also let you have package-specific channels for packages installed with `conda install -c pandas bottleneck`. I'm not sure if the parsing should be fixed around the regexp ([`arg2spec`](https://github.com/conda/conda/blob/fe411835e4c02c7e6c69421d7cf5f9fe79d39379/conda/cli/common.py#L470)) or somewhere else.

I think an even better solution might be to allow the conda package installer to accept package names in the format `channel::package`. This would be a simple solution (I think), and would be backwards-compatible. I'm not sure specifically where to change this.

-------

I cannot get the conda setup.py develop to work (throws exception) so I cannot work on this. But anyways, good luck!

**Comment by jseabold** [comment] 2016-07-19 16:43
Problem #1 was fixed in latest release. It's technically a workaround, but I don't know what problem using `ruamel_yaml` solves, so I just ignore it.

I hadn't thought about the no channels in `.condarc` issue, so thanks for pointing that out. Approach 1 seemed easier to me having spent some time digging through how installs actually happen and is basically what I do here, except I didn't go back and add the channels that are parsed out. The problem with this approach is as you point out. That's undesirable, but I wonder if we can get around this with documentation? Was this basically the status quo before the recent changes? If so, I'd like to at least move back to something that works but is sub-optimal and documenting what's actually going on here.

Approach 2 definitely sounds like The Right Way to get working and reproducible environments, but it's going to require more knowledge than I have about the various places metadata are stored and what's there and what it's used for. I don't have the bandwidth to dig in here and figure this out.

**Comment by kalefranz** [comment] 2017-05-10 09:21
Regarding the original issue, I think we've solved this with ruamel_yaml.  It's been out for a while now, although I think we just recently wired it into conda-env (guess we missed it before).

**Comment by kalefranz** [comment] 2017-05-12 19:34
I think this issue can now be closed, no?

**Closed by kalefranz** 2017-05-12 19:34 UTC

**Comment by darkdreamingdan** [comment] 2017-08-06 09:56
I don't think this issue can be closed.  The `channel::package` functionality still isn't implemented correctly.  Internally this syntax seems to just be a way to add a channel to the environment file (just like adding to the `channels` section in the yml), rather than instruct the package to come from a specific channel.

**Comment by zpincus** [comment] 2017-11-17 18:48
I agree that this should not be closed. There really needs to be a mechanism to specify the channel in an environment file *per dependency*. See for example [this user's very valid issues with channels](http://vincebuffalo.org/notes/2017/08/28/notes-on-anaconda.html), which would be addressed with a proper per-dependency channel specification mechanism. I have also had recent problems in the same vein.

**Comment by sudarshan85** [comment] 2018-05-03 18:48
Is the ability to specify the channel per dependency added? Or is it in development?

**Comment by jaib1** [comment] 2019-08-21 00:49
>There really needs to be a mechanism to specify the channel in an environment file per 
dependency.

>Is the ability to specify the channel per dependency added?

Is there a way to do this?
