### ISSUE TITLE
"conda update conda" error

### ISSUE THREAD

**Issue by dineshbvadhia** [conda/conda#1206] opened 2015-03-19 19:54 UTC
Conda Info at bottom.

C:\>conda update conda

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 253, in instal
l
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 528, in get_ind
ex_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 79, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 247, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 400, in
 result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 359, in
 __get_result
    reraise(self._exception, self._traceback)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_compat.py", line 107,
in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 61, in
 run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 64, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 99, in fetch_repodat
a
    verify=config.ssl_verify)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 464, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 762, in _validate_conn
    conn.connect()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py",
line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenss
l.py", line 251, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenss
l.py", line 152, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in
 __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in
 valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in
 __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in
 valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComp
onentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in get
PositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) n
ot found

C:\>conda info
Current conda install:

             platform : win-32
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.8.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by white-c** [comment] 2015-03-27 17:04
I have gotten the same error.

```
Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.7.final.0
     requests version : 2.6.0
     root environment : C:\Users\white\AppData\Local\Continuum\Anaconda  (writable)
  default environment : C:\Users\white\AppData\Local\Continuum\Anaconda
     envs directories : C:\Users\white\AppData\Local\Continuum\Anaconda\envs
        package cache : C:\Users\white\AppData\Local\Continuum\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by asmeurer** [comment] 2015-05-28 20:43
Try `conda update requests`

**Comment by asmeurer** [comment] 2015-05-28 20:45
Closing as duplicate of https://github.com/conda/conda/issues/1261

**Closed by asmeurer** 2015-05-28 20:45 UTC
