### ISSUE TITLE
graphviz executables missing

### ISSUE THREAD

**Issue by eliot1785** [conda/conda#5465] opened 2017-06-01 18:52 UTC
I have tried finding the answer on my own but it's quite confusing, apologies in advance if I did something boneheaded.

I can't seem to run graphviz in Jupyter Notebook. I get the error message "make sure the Graphviz executables are on your systems' PATH"

I have run both of the following:
pip install graphviz
conda install graphviz

Additionally, I downloaded and ran the Windows MSI installer from the graphviz website.
Finally, I added C:\Program Files (x86)\Graphviz2.38\bin to both the system PATH and my user PATH, restarted my Jupyter Python3 kernel, etc.

After each of these steps I reran my graphviz python commands but got the same error.

A few questions:
1. What am I missing? 
2. Was it necessary to install it 3 different ways or did I end up getting multiple copies of graphviz on my computer?
3. I've noticed that some graphviz executable names conflict with Anaconda executable names. For example both of these exist:
C:\Program Files (x86)\Graphviz2.38\bin\dot.exe
C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\Library\bin\dot.bat

Wouldn't that tend to cause problems? This is only related to this issue in the sense that I needed to add the first PATH entry to try to resolve this issue.

**Comment by kalefranz** [comment] 2017-06-02 00:22
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1666.  Plenty of discussion there.

**Closed by kalefranz** 2017-06-02 00:22 UTC
