### ISSUE TITLE
erreur installation package

### ISSUE THREAD

**Issue by sahikatia** [conda/conda#6868] opened 2018-02-12 15:53 UTC
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/main/win-64/repodata.json.bz2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005200E48>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))",),)

**Comment by kalefranz** [comment] 2018-02-12 16:11
Please use the issue template, and fill in all sections.  It's there for a reason.

I'm going to assume this is a duplicate of https://github.com/conda/conda/issues/6837.  Closing.

**Closed by kalefranz** 2018-02-12 16:11 UTC
