### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by rachamaduguravi** [conda/conda#5668] opened 2017-07-10 02:39 UTC
Getting the above error after fresh install of Anaconda, also pasted the %path%

Q) At what point is it stuck? During install or after install when trying to use it?
A) After install when trying to use it

Q) How did you install it? All Users or Just Me? 
A) All users

Q) Did you elect to allow the installer to modify your PATH or not?
A)  I elected to modify PATH

Q) If it got stuck after install when trying to use it, how did you launch the console? A normal cmd.exe prompt or using the Anaconda Prompt?
A) Anaconda prompt

Q) What is the content of %path%
A) 

C:\Users\rrachama>echo %path%

C:\Anaconda3;C:\Anaconda3\Library\mingw-w64\bin;C:\Anaconda3\Library\usr\bin;C:\
Anaconda3\Library\bin;C:\Anaconda3\Scripts;C:\Program Files\ImageMagick-7.0.4-Q1
6;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\
System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)
\QuickTime\QTSystem\;C:\Program Files\CapgeminiScripts\Support Tools\;C:\Program
 Files (x86)\Common Files\Lenovo;C:\Program Files (x86)\Calibre2\;D:\Projects\To
ols\Git\cmd;D:\Projects\Tools\nodejs\;C:\Users\rrachama\AppData\Roaming\npm;D:\P
rojects\Tools\shell.w32-ix86;C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\bin;D:\Projects\Tools\Microsoft VS Code\bin

``
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
                          C:\Users\rrachama\AppData\Local\conda\conda\envs
                          C:\Users\rrachama\.conda\envs
          package cache : C:\Anaconda3\pkgs
                          C:\Users\rrachama\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/7 W
indows/6.1.7601
          administrator : True

`$ C:\Anaconda3\Scripts\conda-script.py ..checkenv cmd.exe C:\Anaconda3`

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 167, in main

        import conda.cli.activate as activate
      File "C:\Anaconda3\lib\site-packages\conda\cli\activate.py", line 12, in <
module>
        from ..utils import shells
      File "C:\Anaconda3\lib\site-packages\conda\utils.py", line 13, in <module>

        from .gateways.disk.read import compute_md5sum
      File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 22
, in <module>
        from ...models.channel import Channel
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 9, in
<module>
        from ..base.context import context
      File "C:\Anaconda3\lib\site-packages\conda\base\context.py", line 18, in <
module>
        from .._vendor.auxlib.path import expand
      File "C:\Anaconda3\lib\site-packages\conda\_vendor\auxlib\path.py", line 8
, in <module>
        import pkg_resources
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked

      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatib
le
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resou
rces\__init__.py", line 2985, in <module>
        @_call_aside
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resou
rces\__init__.py", line 2971, in _call_aside
        f(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resou
rces\__init__.py", line 3013, in _initialize_master_working_set
        dist.activate(replace=False)
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resou
rces\__init__.py", line 2544, in activate
        declare_namespace(pkg)
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resou
rces\__init__.py", line 2118, in declare_namespace
        _handle_ns(packageName, path_item)
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resou
rces\__init__.py", line 2058, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resou
rces\__init__.py", line 2087, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

**Comment by kalefranz** [comment] 2017-08-15 11:00
Duplicate of #5483 and #5500. Fixed with #5496 in conda 4.3.22.

**Closed by kalefranz** 2017-08-15 11:00 UTC
Labels: reso:duplicate, source:community, type:bug
