### ISSUE TITLE
Cannot create conda environment from file under windows.

### ISSUE THREAD

**Issue by soerendip** [conda/conda#8209] opened 2019-02-01 23:46 UTC
From the Anaconda prompt under W7, I use  `conda env create -f requirements.txt`.
With `requirements.txt` containing:

```
name: miiit
channels:
  - conda-forge
  - defaults
dependencies:
  - appmode=0.5.0
  - jupyter=1.0.0
  - pandas=0.24.0
  - pip=18.1
  - tqdm=4.29.1
  - lxml=4.3.0
  - pip:
    - pyteomics==4.0.1
prefix: /home/.../miniconda3/envs/miiit
```
I receive a message that `Solving environment failed.

```
ResolvePackageNotFound: 
  - expat=2.2.6
  - libedit=3.1.20181209
  - libuuid=1.0.3
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - libgfortran-ng=7.3.0
  - gst-plugins-base=1.14.0
  - readline=7.0
  - ptyprocess=0.6.0
  - dbus=1.13.6
  - gstreamer=1.14.0
  - libgcc-ng=8.2.0
  - gmp=6.1.2
```
The content of the file was extracted from a file that was exported with `conda env export` under linux. I also tried to remove all the version specifications.
Conda version 4.6.2

**Comment by msarahan** [comment] 2019-02-01 23:54
duplicate of #8203

**Closed by msarahan** 2019-02-01 23:54 UTC

**Comment by soerendip** [comment] 2019-02-01 23:56
Never mind. I was actually using `-n` instead of `-f`.
