### ISSUE TITLE
Feature proposal: Add package blacklist

### ISSUE THREAD

**Issue by cel4** [conda/conda#2410] opened 2016-04-28 04:41 UTC
Would it be possible to add a blacklist to conda in which individual packages can be excluded from the resolver? 

Sometimes a channel provides a broken or misconfigured version of package. It would be very helpful to have a simple way to tell the resolver to ignore it.

E.g. A blacklisting section in `.condarc` would do:

```
blacklist:
  - channel/my-pkg
  - channel/my-pkg-1.0.0
  - channel/my-pkg-1.*
```

**Comment by jakirkham** [comment] 2016-05-25 06:11
cc @janschulz

**Comment by janschulz** [comment] 2016-05-25 12:30
See also https://github.com/conda/conda/issues/2067 which can be considered a duplicate of this

**Comment by mcg1969** [comment] 2016-05-25 13:30
Definitely a good idea.

**Comment by kalefranz** [comment] 2016-05-25 14:37
We are right now working through details of making channel a first-class-citizen in a package's identity. The first step is recognizing channel priority, which will be a conda 4.1 feature. We are also revisiting conda's configuration code in 4.2. With those two elements in place, we can think through how best to specify and implement blacklist functionality.

**Comment by cel4** [comment] 2016-05-29 15:33
Making channels a first-class-citizen could also clear the way to introduce blockers in conda recipes. This also could be a very helpful feature to guide the solver to find the right dependencies.

**Comment by dhirschfeld** [comment] 2016-06-14 05:16
My usecase is that I have installed bokeh from source (`setup.py develop`) in an environment but `conda update --all` wants to install bokeh. I guess conda can't tell its already installed?

It seems this could be worked around if there were an option
```
conda update --all --exclude bokeh
```

**Comment by jakirkham** [comment] 2016-06-14 05:45
A related use case would be potentially exclude a rc/dev channel. Though I'm not sure the dynamics would be the same when doing `conda update --all`. Would need some option to potentially avoid downgrades caused by an rc/dev package missing a channel.

**Comment by dhirschfeld** [comment] 2016-07-05 01:09
Ping! Just wanted to +1 this again as I've come across another situation where I need this functionality.

In this instance I *don't* want to install Python from `conda-forge` so would like to be able to exclude it from my `update --all` whilst still pulling in the latest packages from any of my configured channels.

This could also be resolved by allowing packages to be pinned to a specific channel(s). I didn't see an issue for this so I opened #2978. I think the functionality requested there is complementary to this and that both would be very useful to have.

**Comment by croth1** [comment] 2016-10-21 20:01
Any progress here?

**Comment by dhirschfeld** [comment] 2017-06-12 04:59
Just hit this one again...

I have ipywidgets installed from pip because the pre-release isn't available on conda-forge. Unfortuantely every time I try to update it tries to install ipywidgets even though it's already installed (by pip)

Having a `conda update --all --exclude ipywidgets` would allow be to work around this.

Alternatively if conda could be made to recognise pip installed packages this would solve my immediate problem though I still think there's a usecase for an `--exclude` flag

**Comment by kalefranz** [comment] 2018-02-24 00:19
Done and working again with https://github.com/conda/conda/pull/6932 in conda 4.5.

**Closed by kalefranz** 2018-02-24 00:19 UTC
Labels: type:feature
