### ISSUE TITLE
failed to parse sys.version

### ISSUE THREAD

**Issue by paul908** [conda/conda#5413] opened 2017-05-24 07:44 UTC
conda update --all
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "c:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "c:\Anaconda2\lib\site-packages\conda\cli\main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "c:\Anaconda2\lib\site-packages\conda\exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "c:\Anaconda2\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "c:\Anaconda2\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "c:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "c:\Anaconda2\lib\site-packages\conda\connection.py", line 55, in <module>
    python=platform.python_implementation(),
  File "c:\Anaconda2\lib\platform.py", line 1460, in python_implementation
    return _sys_version()[0]
  File "c:\Anaconda2\lib\platform.py", line 1422, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 |Anaconda custom (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)]'

**Comment by kalefranz** [comment] 2017-05-25 06:16
Duplicate of #3606, https://github.com/conda/conda/issues/4901

For help, see https://github.com/conda/conda/issues/4901#issuecomment-287868746

**Closed by kalefranz** 2017-05-25 06:16 UTC
