### ISSUE TITLE
Support proxy_servers in conda config

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#546] opened 2014-01-31 17:32 UTC
proxy_servers is not support in conda config because it's a dictionary, but it currently only supports list or boolean keys.

**Comment by jasongrout** [comment] 2015-08-13 20:30
@asmeurer - it seems like this works now, right?

**Comment by jasongrout** [comment] 2015-08-13 21:04
Oh, never mind.  I see what you're saying.  You can't set proxy servers from the `conda config` command line script.

**Comment by kalefranz** [comment] 2017-05-09 08:41
Duplicate of #4302

**Closed by kalefranz** 2017-05-09 08:41 UTC
Labels: 1 - Backlog/long term, type:feature
