### ISSUE TITLE
Error when installing r-essential on windows 7

### ISSUE THREAD

**Issue by tkandl** [conda/conda#4757] opened 2017-02-28 16:11 UTC
When I try to install the r-essentials, I get the following error:

 $ C:\ProgramData\Anaconda3\Scripts\conda-script.py install -c r r-essentials=1.5.2 

Traceback (most recent call last):
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
 return_value = func(*args, **kwargs)
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
 exit_code = args.func(args, p)
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
 install(args, parser, 'install')
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 118, in install
 context.validate_configuration()
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 830, in validate_configuration
 raise_errors(tuple(chain.from_iterable((errors, post_errors))))
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 828, in 
 for name in self.parameter_names)
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 821, in _collect_validation_error
 func(*args, **kwargs)
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 446, in get
 result = typify_data_structure(self._merge(matches) if matches else self.default,
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 662, in _merge
 for match in relevant_matches)
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 662, in 
 for match in relevant_matches)
 File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\compat.py", line 72, in iteritems
 return iter(d.items(**kw))
 AttributeError: 'NoneType' object has no attribute 'items'

Current conda install:

platform : win-64
 conda version : 4.3.8
 conda is private : False
 conda-env version : 4.3.8
 conda-build version : not installed
 python version : 3.6.0.final.0
 requests version : 2.12.4
 root environment : C:\ProgramData\Anaconda3 (writable)
 default environment : C:\ProgramData\Anaconda3
 envs directories : C:\ProgramData\Anaconda3\envs
 package cache : C:\ProgramData\Anaconda3\pkgs
 channel URLs : https://conda.anaconda.org/r/win-64
                         https://conda.anaconda.org/r/noarch
                         https://repo.continuum.io/pkgs/free/win-64
                         https://repo.continuum.io/pkgs/free/noarch
                         https://repo.continuum.io/pkgs/r/win-64
                         https://repo.continuum.io/pkgs/r/noarch
                         https://repo.continuum.io/pkgs/pro/win-64
                         https://repo.continuum.io/pkgs/pro/noarch
                         https://repo.continuum.io/pkgs/msys2/win-64
                         https://repo.continuum.io/pkgs/msys2/noarch
 config file : C:\Users\xxx.condarc
 offline mode : False
 user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601

If somebody could help me with this, that would be great.
Thanks

**Comment by kalefranz** [comment] 2017-02-28 19:04
Latest conda version is 4.3.13.  `conda update conda`

**Comment by tkandl** [comment] 2017-03-01 12:58
Thanks.
I tried this and got exactly the same error.

I also installed Miniconda3 with conda 4.3.11 and tried "conda update conda" and got the same error.

**Comment by kalefranz** [comment] 2017-03-01 15:23
Oh yeah.  Syntax errors in yaml files

**Comment by kalefranz** [comment] 2017-03-01 15:24
Oh yeah.  Syntax errors in yaml configuration files don't go through conda's normal error handler because it hasn't been initialized yet.

Can you give me what you actually had as contents for the bad condarc file?  I'll write a regression test for it...

**Comment by tkandl** [comment] 2017-03-02 14:14
I didn't have the spaces before the proxy server entries:

proxy_servers:
http: xxx.xxx.xxx.xxx:80
https: xxx.xxx.xxx.xxx:80

**Comment by kalefranz** [comment] 2017-03-02 15:06
cool thanks

**Comment by kalefranz** [comment] 2017-05-04 20:58
This was fixed in 4.3.17.

**Closed by kalefranz** 2017-05-04 20:58 UTC
