### ISSUE TITLE
"conda update -n base -c conda-forge conda" breaks conda

### ISSUE THREAD

**Issue by jwhite007** [conda/conda#12064] opened 2022-11-05 17:20 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Notice that I am using an env prompt and that activating after update does not return the whole prompt as follows in "expected activation behavior".
```
$ conda update -n base -c conda-forge conda
$ conda activate <some conda env>
(cenv_aide)
```
expected activation behavior:
```
$ conda activate <some conda env>
(cenv_aide)
$ 
```
deactivation behavior after update (hangs and have to kill tty from other session)
```
$ conda activate /toolbox/bioinformatics/conda/envs/test/cenv_aide
(cenv_aide)conda deactivate
```
expected deactivation behavior:
```
$ conda activate <some conda env>
(cenv_aide)
$ conda deactivate
$
```

### Conda Info

```shell
After update:
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/linuxbrew/.condarc
 populated config files : /home/linuxbrew/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest  (writable)
      conda av data dir : /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest/etc/conda
  conda av metadata url : None
           channel URLs : file:///toolbox/bioinformatics/conda/channel/linux-64
                          file:///toolbox/bioinformatics/conda/channel/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /toolbox/bioinformatics/conda/pkgs
       envs directories : /toolbox/bioinformatics/conda/envs/prod
                          /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest/envs
                          /home/linuxbrew/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/4.18.0-372.26.1.el8_6.x86_64 rhel/8.6 glibc/2.28
                UID:GID : 63393591:1955
             netrc file : None
           offline mode : False

After rollback:
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/linuxbrew/.condarc
 populated config files : /home/linuxbrew/.condarc
          conda version : 4.14.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest  (writable)
      conda av data dir : /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest/etc/conda
  conda av metadata url : None
           channel URLs : file:///toolbox/bioinformatics/conda/channel/linux-64
                          file:///toolbox/bioinformatics/conda/channel/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /toolbox/bioinformatics/conda/pkgs
       envs directories : /toolbox/bioinformatics/conda/envs/prod
                          /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest/envs
                          /home/linuxbrew/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.9.13 Linux/4.18.0-372.26.1.el8_6.x86_64 rhel/8.6 glibc/2.28
                UID:GID : 63393591:1955
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
$ conda config --show-sources
==> /home/linuxbrew/.condarc <==
auto_activate_base: False
changeps1: True
env_prompt: ({name})
envs_dirs:
  - /toolbox/bioinformatics/conda/envs/prod
pkgs_dirs:
  - /toolbox/bioinformatics/conda/pkgs
channel_priority: strict
channels:
  - file:///toolbox/bioinformatics/conda/channel
  - conda-forge
  - bioconda
  - r
  - defaults
restore_free_channel: True
```

### Conda list

```shell
After update:
$ conda list --show-channel-urls
# packages in environment at /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39he91dace_2    conda-forge
chardet                   5.0.0            py39hf3d152e_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.9.0           py39hf3d152e_2    conda-forge
conda-build               3.22.0           py39hf3d152e_2    conda-forge
conda-package-handling    1.9.0            py39hb9d737c_1    conda-forge
cryptography              38.0.3           py39h3ccb8fc_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libarchive                3.6.1                h648a969_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblief                   0.12.3               h27087fc_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1            py39hb9d737c_2    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.7                h166bdaf_0    conda-forge
patch                     2.7.6             h7f98852_1002    conda-forge
patchelf                  0.16.1               h58526e2_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
psutil                    5.9.3            py39hb9d737c_1    conda-forge
py-lief                   0.12.3           py39h5a03fae_0    conda-forge
pycosat                   0.6.4            py39hb9d737c_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.13          h2660328_0_cpython    conda-forge
python-libarchive-c       4.0              py39hf3d152e_2    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb9d737c_5    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ripgrep                   13.0.0               h2f28480_2    conda-forge
ruamel_yaml               0.15.80         py39hb9d737c_1008    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.39.4               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
tzdata                    2022f                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.38.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge

After rollback:
$ conda list --show-channel-urls
# packages in environment at /toolbox/bioinformatics/.pyenv/versions/miniconda3-latest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15          pyhd8ed1ab_1    conda-forge
cffi                      1.15.1           py39he91dace_0    conda-forge
chardet                   5.0.0            py39hf3d152e_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     4.14.0           py39hf3d152e_0    conda-forge
conda-build               3.22.0           py39hf3d152e_2    conda-forge
conda-package-handling    1.8.1            py39hb9d737c_1    conda-forge
cryptography              37.0.4           py39hd97740a_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libarchive                3.5.2                hb890918_3    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.12.1               h27087fc_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1            py39hb9d737c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
patch                     2.7.6             h7f98852_1002    conda-forge
patchelf                  0.15.0               h58526e2_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
psutil                    5.9.1            py39hb9d737c_0    conda-forge
py-lief                   0.12.1           py39h5a03fae_0    conda-forge
pycosat                   0.6.3           py39hb9d737c_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-libarchive-c       4.0              py39hf3d152e_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb9d737c_4    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ripgrep                   13.0.0               h2f28480_2    conda-forge
ruamel_yaml               0.15.80         py39hb9d737c_1007    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.39.2               h4ff8645_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

**Comment by kenodegard** [comment] 2022-11-05 17:41
Duplicate of #11885

**Closed** 2022-11-05 17:41 UTC
Labels: type::bug, duplicate

**Comment by jwhite007** [comment] 2022-11-06 01:47
@kenodegard, apologies. I searched for similar issues; however, I guess my search wasn't thorough enough.
