### ISSUE TITLE
Setting and activating environment for Python from .YAML file

### ISSUE THREAD

**Issue by andresmdiaz** [conda/conda#4364] opened 2017-01-18 19:28 UTC
I have a .yaml file from instructor with the created environment I need. Do I have to save this in a specific place in my computer in order for Python to find it? All I was instructed to do was to download the file, then use the code: **conda env create -f dand-env-win.yaml** and finally **activate DAND** 

I tried that and this is the message I got:

Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\Andres Diaz\Anaconda3  (writable)
    default environment : C:\Users\Andres Diaz\Anaconda3
       envs directories : C:\Users\Andres Diaz\Anaconda3\envs
          package cache : C:\Users\Andres Diaz\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\Andres Diaz\Anaconda3\Scripts\conda-env-script.py create -f dand-env-win.yaml`

    Traceback (most recent call last):
      File "C:\Users\Andres Diaz\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Andres Diaz\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 82, in execute
        directory=os.getcwd())
      File "C:\Users\Andres Diaz\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: dand-env-win.yaml file not found
    There is no requirements.txt

(C:\Users\Andres Diaz\Anaconda3) C:\Users\Andres Diaz>

**Comment by nehaljwani** [comment] 2017-01-19 04:28
Seems like a duplicate of https://github.com/conda/conda/issues/4328

**Comment by kalefranz** [comment] 2017-05-09 03:51
Indeed a duplicate of #4328.  But we should really fix conda-env here to `os.path.join(os.getcwd(), args.file)` or whatever the equivalent is.

**Comment by kalefranz** [comment] 2017-05-09 03:51
I've seen at least half a dozen bug reports of the same issue it feels like.

**Comment by kalefranz** [comment] 2017-05-09 03:54
duplicate of #4342

**Comment by kalefranz** [comment] 2017-05-09 03:58
Duplicate of #3689

**Closed by kalefranz** 2017-05-09 03:58 UTC
Labels: source:community, tag:conda-env, type:bug
