### ISSUE TITLE
java jdk

### ISSUE THREAD

**Issue by xweipbcsf** [conda/conda#6101] opened 2017-10-07 16:10 UTC
Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : /Users/xingkong/anaconda  (writable)
    default environment : /Users/xingkong/anaconda
       envs directories : /Users/xingkong/anaconda/envs
                          /Users/xingkong/.conda/envs
          package cache : /Users/xingkong/anaconda/pkgs
                          /Users/xingkong/.conda/pkgs
           channel URLs : https://conda.anaconda.org/cyclus/osx-64
                          https://conda.anaconda.org/cyclus/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/xingkong/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/3.6.2 Darwin/17.0.0 OSX/10.13    
                UID:GID : 501:20

`$ /Users/xingkong/anaconda/bin/conda install -c cyclus java-jdk`

    Traceback (most recent call last):
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506044346.682 for timestamp

**Comment by nehaljwani** [comment] 2017-10-08 16:49
Closing as duplicate of #6096

**Closed by nehaljwani** 2017-10-08 16:49 UTC
