### ISSUE TITLE
channel UNC path encoding errors on windows

### ISSUE THREAD

**Issue by gregfreeman** [conda/conda#3779] opened 2016-11-01 12:11 UTC
I have some channel specifications for UNC file paths on windows that stopped working in conda 4.2.11, but did work in 4.2.9 and earlier

The conda command with channel specification followed this style
conda install -c file://\\machine\shared_folder\path\conda  my_package

Channels specified in condarc were also affected and caused a bug when parsing the condarc file (via calling a conda command).

Is there another preferred style for UNC paths on windows?

I see some new channel decoding code in the channel model that is likely the culprit.  
if value.startswith('file:') and on_win:	
	value = value.replace('\\', '/')	
        return Channel.from_url(value)

**Comment by gregfreeman** [comment] 2016-12-19 00:50
It looks like there was a encoding error in the issue report.   
The previously working command was:
conda install -c file://\\machine\shared_folder\path\conda my_package

**Comment by kalefranz** [comment] 2016-12-19 01:08
hey @gregfreeman does 

    conda install -c file:///machine/shared_folder/path/conda my_package

work?

Also I think you did find a bug here.  It probably should be `value = value.replace('\\', '/')`

**Comment by kalefranz** [comment] 2016-12-19 15:05
@gregfreeman Can you confirm that this is or is not fixed in 4.2.13?  I can't find any instances of `.replace('\', '/')` in the code base.

If the issue is still there, can you provide more information?  The stack trace--or whatever other behavior you're seeing--when it "doesn't work."

**Comment by gregfreeman** [comment] 2016-12-19 16:46
Github changes the encoding: 
conda install -c file://\\\\machine\shared_folder\path\conda my_package

**Comment by gregfreeman** [comment] 2016-12-19 16:51
The alternative command with file:///machine/shared_folder  does not work.  It gives a CondaHTTPError. HTTP 404 None for url <None>

Its failing on windows 7 with python 2.7 root environment.

**Comment by kalefranz** [comment] 2016-12-19 22:05
Hey @gregfreeman, I've written some additional tests [here](https://github.com/conda/conda/pull/4112), and I haven't found a smoking gun yet.

Is it possible that this actually doesn't have anything to do with unc paths?

Can you give me the output of

    conda install -c file://\machine\shared_folder\path\conda my_package --debug

**Comment by kalefranz** [comment] 2016-12-19 22:06
Also the output of `conda info`.

**Comment by gomyhr** [comment] 2017-01-05 10:17
I have written a proposed fix. The examples that @kalefranz came up with do not work, though, as they are not valid URLs for UNCs. Valid commands IMHO are:

    # File URL (note only to slashes between : and machine):
    conda install -c file://machine/shared_folder/path/conda my_package
    # UNC:
    conda install -c \\machine\shared_folder\path\conda my_package
   # Python open()
    conda install -c //machine/shared_folder/path/conda my_package

All those examples should work with my fix. I hope I did not break anything else...

**Comment by bklaas** [comment] 2017-01-05 17:08
@gomyhr Thanks for you efforts on this. I've been working for the past few days to encapsulate the nature of the issue with conda >=4.2.11 and UNC paths, as we've been experiencing the same issues here.

One note: of the three UNCs listed above, none of them follow the exact syntax of what was previously working for us:

    conda install -c file://\\machine\shared_folder\path\conda my_package

Will that syntax be supported with the code change as well? Specifically, we need this to work in the channels section of environment yaml spec files, e.g.,

    channels:
        - file://\\machine\shared_folder\path\conda
        - defaults
    dependencies:
        - my_package=1.2.3
        - pandas=0.19.1

I'm sure that's the same code pathway, but thought I'd mention the use case.

Cheers for your efforts!
-Ben

**Comment by kalefranz** [comment] 2017-01-05 17:55
Hey everyone,

Please review the tests around https://github.com/conda/conda/pull/4190/files#diff-511832f80cfd3343dcdda4fde410b3aeR10.  If there's something wrong in those tests, there's going to be something wrong in the end result.  If there are tests we should add, please also propose those :)

**Comment by bklaas** [comment] 2017-01-05 18:06
To my eye the tests looks good and would exercise the UNC syntax I listed in my previous comment.

**Closed** 2017-01-05 18:42 UTC
Labels: bug
