### ISSUE TITLE
msvc_runtime unsatisfiable dependencies on new installation of miniconda

### ISSUE THREAD

**Issue by j9ac9k** [conda/conda#1779] opened 2015-11-04 16:30 UTC
I just installed a miniconda, and proceeded to run 

```
~ $ conda update --all
Fetching package metadata: ..............
Solving package specifications: ..................
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: 'msvc_runtime' has unsatisfiable dependencies (see 'conda info msvc_runtim
e')

Note that the following features are enabled:
  - vc9
  - vc10
  - vc14
```

I updated msvc_runtime, along with openssl and certifi, but I still get that error.

Suggestions?

**Comment by groutr** [comment] 2015-11-04 20:56
Can you please post the output of `conda info` and `conda list`?

**Comment by j9ac9k** [comment] 2015-11-04 21:19
Here you go.

```
~ $ conda update --all
Fetching package metadata: ..............
Solving package specifications: ................
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: 'msvc_runtime' has unsatisfiable dependencies (see 'conda info msvc_runtim
e')

Note that the following features are enabled:
  - vc10
  - vc14
  - vc9

~ $ conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : not installed
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Users\omoore\AppData\Local\Continuum\Miniconda3  (wri
table)
  default environment : C:\Users\omoore\AppData\Local\Continuum\Miniconda3
     envs directories : C:\Users\omoore\AppData\Local\Continuum\Miniconda3\envs
        package cache : C:\Users\omoore\AppData\Local\Continuum\Miniconda3\pkgs
         channel URLs : https://conda.anaconda.org/salilab/win-64/
                        https://conda.anaconda.org/salilab/noarch/
                        https://conda.anaconda.org/juhasch/win-64/
                        https://conda.anaconda.org/juhasch/noarch/
                        https://conda.anaconda.org/pyzo/win-64/
                        https://conda.anaconda.org/pyzo/noarch/
                        https://conda.anaconda.org/pydy/win-64/
                        https://conda.anaconda.org/pydy/noarch/
                        https://conda.anaconda.org/r/win-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\omoore\.condarc
    is foreign system : False

~ $ conda list
# packages in environment at C:\Users\omoore\AppData\Local\Continuum\Miniconda3:

#
conda                     3.18.3                   py35_0
conda-env                 2.4.4                    py35_0
menuinst                  1.2.1                    py35_0
msvc_runtime              1.0.0                    vc14_0  [vc14]
pycosat                   0.6.1                    py35_0
pycrypto                  2.6.1                    py35_3
python                    3.5.0                         2
pyyaml                    3.11                     py35_2
requests                  2.8.1                    py35_0
~ $
```

**Comment by j9ac9k** [comment] 2015-11-04 21:20
Huh, I just noticed it's using an older .conrarc file from before, I renamed it to .condarc.old and reran conda info and conda list

```
~ $ conda list
# packages in environment at C:\Users\omoore\AppData\Local\Continuum\Miniconda3:

#
conda                     3.18.3                   py35_0
conda-env                 2.4.4                    py35_0
menuinst                  1.2.1                    py35_0
msvc_runtime              1.0.0                    vc14_0  [vc14]
pycosat                   0.6.1                    py35_0
pycrypto                  2.6.1                    py35_3
python                    3.5.0                         2
pyyaml                    3.11                     py35_2
requests                  2.8.1                    py35_0
~ $ conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : not installed
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Users\omoore\AppData\Local\Continuum\Miniconda3  (wri
table)
  default environment : C:\Users\omoore\AppData\Local\Continuum\Miniconda3
     envs directories : C:\Users\omoore\AppData\Local\Continuum\Miniconda3\envs
        package cache : C:\Users\omoore\AppData\Local\Continuum\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

~ $
```

**Comment by chadkennedyonline** [comment] 2015-11-05 15:24
Can you try running "conda update --all" multiple times, and check if it's always the same package that's reported? (Please see #1783) This might help narrow down the issue.

**Comment by j9ac9k** [comment] 2015-11-05 15:26
I always get the same package (msvc_runtime) as having unsatisfiable dependencies, however if you look at my conda list output above, that is the only package that has the [vc14] next to it, in your issue #1783 you will notice that you're getting that error for all packages dependent on the msvc_runtime.

**Comment by chadkennedyonline** [comment] 2015-11-05 18:01
Not sure how to interpret this, but I have a bit more info by running "conda update --dry-run --alt-hint --all":

    The following set of clauses is unsatisfiable:

    msvc_runtime-1.0.0-vc10_0 => not msvc_runtime-1.0.1-vc14_0
    msvc_runtime-1.0.0-vc10_0 or msvc_runtime-1.0.1-vc10_0
    msvc_runtime-1.0.1-vc14_0 or msvc_runtime-1.0.0-vc14_0
    msvc_runtime-1.0.1-vc10_0 => not msvc_runtime-1.0.1-vc14_0
    msvc_runtime-1.0.0-vc10_0 => not msvc_runtime-1.0.0-vc14_0
    msvc_runtime-1.0.0-vc14_0 => not msvc_runtime-1.0.1-vc10_0

**Comment by j9ac9k** [comment] 2015-11-05 18:13
Hmmm...should look up reverse dependencies for msvc_runtime-1.0.0-vc10_0 ...there was a way to do that, but I can't remember how.

**Comment by chadkennedyonline** [comment] 2015-11-05 18:15
Dropped back to 2.2.0 distribution. Updated conda and confirmed same result. Simply did "conda remove msvc_runtime" and then "conda update --dry-run --all" runs without issue. Not sure if that will work with 2.4.0.

**Comment by chadkennedyonline** [comment] 2015-11-05 21:03
This all seems to have to do with conflicting/confused "features" (aka vc9, vc10, vc14). A new, similar message for the openssl package:

    openssl-1.0.2d-vc10_0
    openssl-1.0.2d-vc9_0
    openssl-1.0.2d-vc10_0 => not openssl-1.0.2d-vc9_0

Yet, I don't have any vc9 packages on my system. I'm beginning to think either conda or the online package repo is borked. Do I really have something that requires openssl-1.0.2d-vc9_0? How can I tell? Searching the json files in conda-meta doesn't turn up any dependencies for anything vc9.

**Comment by ijstokes** [comment] 2015-11-06 14:11
@msarahan can you take a quick look at this and provide your thoughts/insights into what might be the cause and what might be i) a short term work-around; and ii) a longer term fix?

**Comment by ukoethe** [comment] 2015-11-06 15:30
I have seen similar error messages on other recipes (unrelated to this issue) and found that it helped to add a `track_features` directive to the package in question. That is, `msvc_runtime/meta.yaml` should contain something like:
```yaml
package:
  name: msvc_runtime
  version: 1.0.0

build:
  features:
    - vc9
  track_features:
    - vc9
  ...
```
(likewise for the other variants of that package). To test if this helps, it might be possible to edit `<conda-root>\pkgs\msvc_runtime-1.0.0-vc9_0\info\index.json` etc. and add the line:
```json
  "track_features": "vc9", 
```
(hoping that conda won't overwrite the change with the package's original content). If this indeed resolves the issue, upstream must fix their recipes and create new packages.

Moreover, I don't quite understand why all `msvc_runtime` variants have version numbers `1.0.0` or `1.0.1`. It would be much more logical to match the package version to the compiler version, i.e. `msvc_runtime-9.0` for vc9. Then one could also enforce a particular msvc version by calling `conda install msvc_runtime=9.0`. The present design that distinuishes variants only by build string may also relate this issue to the version resolution bug described in https://github.com/conda/conda/issues/1589.

**Comment by chadkennedyonline** [comment] 2015-11-06 15:52
@ukoethe Tried your suggestion:

I start from a state where I get the error: 

    C:\Users\Chad\Anaconda3>conda update --alt-hint --all
    Fetching package metadata: ....
    Solving package specifications: ...............................................
    Error: Unsatisfiable package specifications.
    Generating minimal hint:
    [      COMPLETE      ]|##################################################| 100%
    
    The following set of clauses is unsatisfiable:
    
    openssl-1.0.2d-vc10_0 => not openssl-1.0.2d-vc9_0
    openssl-1.0.2d-vc10_0
    openssl-1.0.2d-vc9_0

I confirm the feature of the openssl package:

    C:\Users\Chad\Anaconda3>conda list openssl
    # packages in environment at C:\Users\Chad\Anaconda3:
    #
    openssl                   1.0.2d                   vc10_0  [vc10]
    pyopenssl                 0.15.1                   py34_1

Then, following your suggestion, I added the line 

      "track_features": "vc10",

to the file C:\Users\Chad\Anaconda3\pkgs\openssl-1.0.2d-vc10_0\info\index.json. The error remained unchanged, I also tried 

      "track_features": "vc9",

instead, but to no avail. Error message remained unchanged. Here is info on my install:

    C:\Users\Chad\Anaconda3>conda info
    Current conda install:
    
                 platform : win-64
            conda version : 3.18.3
      conda-build version : 1.18.1
           python version : 3.4.3.final.0
         requests version : 2.8.1
         root environment : C:\Users\Chad\Anaconda3  (writable)
      default environment : C:\Users\Chad\Anaconda3
         envs directories : C:\Users\Chad\Anaconda3\envs
            package cache : C:\Users\Chad\Anaconda3\pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/win-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : D:\Chad\.condarc
        is foreign system : False

**Comment by msarahan** [comment] 2015-11-06 19:51
@ukoethe some background info:

> I don't quite understand why all msvc_runtime variants have version numbers 1.0.0 or 1.0.1

Because it's a single package that bundles different DLLs based on the VC version used to build the recipe.  Splitting it into separate recipes is certainly an option, especially if it smooths out these dependency resolution issues.  However, it introduces pinning issues that might be annoying.  Any library needs both features, and now more conditional code for which msvc_runtime package it should depend on.  Your jinja2 stuff would make this much nicer, but we have a lot of work to do internally to modernize recipes to use jinja2.  That's probably the long-term fix.

In the current system, track-features lives in Python - nowhere else.  Python 2.7 tracks vc9; Python 3.4 tracks vc10, Python 3.5 tracks vc14.  This metadata ends up in repodata.json ( http://repo.continuum.io/pkgs/free/win-32/repodata.json or http://repo.continuum.io/pkgs/free/win-64/repodata.json)

Both of these look consistent - all the vc versions match Python versions.

msvc_runtime has no dependencies whatsoever.  I am lost on this.  Pinging @mcg1969, our solver expert.

**Comment by groutr** [comment] 2015-11-06 19:53
If I understand features correctly, only the package at the bottom of the stack needs track features (ie, in a python environment, only python would have track_features).  Then the environment would know to only install packages with a certain feature if its available.

**Comment by groutr** [comment] 2015-11-06 21:02
Can anyone with this issue try updating again?  Please post here if you get another unsatisifiable dependency.

**Comment by j9ac9k** [comment] 2015-11-06 21:04
Still getting the issue:

```
~ $ conda update --all
Fetching package metadata: ....
Solving package specifications: ....................
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: 'msvc_runtime' has unsatisfiable dependencies (see 'conda info msvc_runtim
e')

Note that the following features are enabled:
  - vc14
  - vc10
  - vc9

~ $ conda list
# packages in environment at C:\Users\omoore\AppData\Local\Continuum\Miniconda3:

#
conda                     3.18.3                   py35_0
conda-env                 2.4.4                    py35_0
menuinst                  1.2.1                    py35_0
msvc_runtime              1.0.1                    vc14_0  [vc14]
pip                       7.1.2                    py35_0
pycosat                   0.6.1                    py35_0
pycrypto                  2.6.1                    py35_3
python                    3.5.0                         2
pyyaml                    3.11                     py35_2
requests                  2.8.1                    py35_0
setuptools                18.4                     py35_0
wheel                     0.26.0                   py35_1
~ $ conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : not installed
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Users\omoore\AppData\Local\Continuum\Miniconda3  (wri
table)
  default environment : C:\Users\omoore\AppData\Local\Continuum\Miniconda3
     envs directories : C:\Users\omoore\AppData\Local\Continuum\Miniconda3\envs
        package cache : C:\Users\omoore\AppData\Local\Continuum\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

~ $
```

**Comment by ukoethe** [comment] 2015-11-06 21:47
> @groutr: If I understand features correctly, only the package at the bottom of the stack needs track features.

In practice it seems to be more complicated than that. I can reproduce an "unsatisfiable dependencies" error with the following minimal example:
```yaml
# track_feat/meta.yaml
package:
  name:  track_feat
  version: "1.0"

build:
  features:
    - feat
  track_features:
    - feat
```
```yaml
# feat/meta.yaml
package:
  name:  feat
  version: "1.0"

build:
  features:
    - feat

requirements:
  build:
    - track_feat
  run:
    - track_feat
```
Then on the command line:
```sh
>> conda build  track_feat     # works
>> conda build  feat           # works
>> conda create --use-local -n feat  feat  # fails: 'feat' has unsatisfiable dependencies
```
According to my understanding of the documentation, this is supposed to work. 
There are two possibilities to fix the example:
1. Add a `track_features: feat` directive to `feat/meta.yaml`.
2. Install `track_feat` separately:
```sh
>> conda create --use-local -n feat  track_feat
>> activate feat
>> conda install --use-local feat
```

**Comment by ukoethe** [comment] 2015-11-06 22:35
In [response](https://github.com/conda/conda/issues/1779#issuecomment-154514729) to @msarahan: 
> Because it's a single package that bundles different DLLs based on the VC version used to build the recipe.

I still don't understand. According to @chadkennedyonline's [debug output](https://github.com/conda/conda/issues/1779#issuecomment-154138975) above, there are several packages named `msvc_runtime-1.0.0` which are differentiated by their build strings. Where does the "single package" fit in here? 

In any case, while fixing conda's version comparison code a few weeks ago, I got the strong impression that build string comparison is very much ad hoc, and one should not base significant version resolution decisions on build strings in their current form. That's one rationale behind my suggestion to add suffixes to version numbers, like `1.2.3.vc11`.

>  However, it introduces pinning issues that might be annoying.

Which pinning issues?

> Any library needs both features.

In fact, I believe that any compiled Python module that #includes numpy headers needs at least three features: the compiler version, the Python version, and the numpy version. The ABIs of these packages differ between versions, and any mismatched installation *will* crash sooner or later.

> In the current system, track-features lives in Python - nowhere else.

Since you already introduced `msvc_runtime` packages, they should track the appropriate `vc?` as well because this feature is also relevant (in fact, required) in pure C-packages like libtiff that don't depend on Python at all.

>  Python 2.7 tracks vc9

True, but we needed a Python 2.7 that tracks vc11 because vc9 is too old to compile our C++ packages, and we cannot yet switch to Python 3. Since we couldn't find recipes with that property, we created them from scratch (by now about 130, see https://github.com/ilastik/ilastik-build-conda/tree/toolset-config).

> Your jinja2 stuff would make this much nicer, but we have a lot of work to do internally to modernize recipes to use jinja2. That's probably the long-term fix.

The recipes linked above already contain a full implementation of a (preliminary) variant of the jinja2 stuff for Windows. We would like to finalize this design and extend it to the other platforms as soon as possible, but work is effectively stalled due to https://github.com/conda/conda/pull/1727, https://github.com/conda/conda-build/pull/662, https://github.com/conda/conda-build/pull/664, https://github.com/conda/conda-build/pull/666, https://github.com/conda/conda-build/pull/667. Once we have finished, you are welcome to use our recipes as a starting point.

**Comment by msarahan** [comment] 2015-11-07 16:27
> Where does the "single package" fit in here

I misspoke.  It is a single recipe that generates multiple packages.  I tried this morning to change it to 3 separate recipes, each named msvc_runtime, but with different versions.  I tried this two different ways:

  1. Individual folders, msvc_runtime-9.0.???? and so on.  Our build system gets confused by multiple packages named msvc_runtime.  Needs work.
  2. Adding selectors to version field of package metadata in meta.yaml, in single recipe.  Selectors don't seem to be supported in that field, unfortunately.

I am leaving it as is for the time being, but noting that this issue is something that needs urgent work in our build system, and potentially also with conda-build to add support for selectors everywhere in meta.yaml.  Templating with jinja2 might be a better way to do this, but the build system does not cache generated jinja2 output, so the metadata to populate the index currently has to come from static, non-templated files.

> In fact, I believe that any compiled Python module that #includes numpy headers needs at least three features: the compiler version, the Python version, and the numpy version.

I agree with you in principal, but the compiler version is somewhat implicit in the Python version.  We are not going to support using compilers other than the ones officially used to build Python.  Thus, Python2.7 specifies MSVC 2008 for ALL packages for Python 2.7, and so on.  I see from your later point that you build Python 2.7 with MSVC 2012.  That's a compelling point that we should make the compiler version explicit rather than implicit through python version.  I think it won't hurt us (we will probably build only the standard configuration), but it will help you.  Our recipes will only ever have features like: 

        - vc9  [win and py27]
        - vc10  [win and py34]
        - vc14  [win and py35]

but that should not preclude you from setting different features in your personal recipes.  The thing I don't know would be how you would force installation of your vc11-built Python in the first place, such that only those featured packages would get installed.

> Which pinning issues?

Right now, a package can simply depend on msvc_runtime, and the feature stuff should get it the right version.  If we depend on versions instead, then we need to add sections like:

requirements:
    run:
        - msvc_runtime  9.*  [win and py27]
        - msvc_runtime  10.*  [win and py34]
        - msvc_runtime  14.*  [win and py35]

Or else, I think your earlier point about version matching getting mixed up with feature matching remains an open issue, and essentially all installations with try to install the latest version of msvc_runtime, rather than the correct one for the given platform.

> True, but we needed a Python 2.7 that tracks vc11 because vc9 is too old to compile our C++ packages, and we cannot yet switch to Python 3.

This is a really hard problem.  I think you've found a good solution to it, but that's not really one that we can support.  In the name of compatibility, we need to stick with the mainstream version.  I feel your pain, though, and I hope we can find a way to at least not conflict with what you're trying to do.  FWIW, the Kitware folks often build and link Python and libraries statically in this situation: http://www.kitware.com/blog/home/post/742

> The recipes linked above already contain a full implementation of a (preliminary) variant of the jinja2 stuff for Windows.

Thanks.  These will be tremendously helpful.  Unfortunately, the problem is not just updating recipes.  We also have to update our internal build system to populate package metadata from templates in very different ways.  It currently can only draw from static meta.yaml files, which is why adoption of jinja2 stuff internally has been slow.  This build system is totally separate from conda-build, but can use conda-build and conda-recipes.  For our next release, we will be working towards converting all of our recipes to conda recipes, and consolidating the build system.

**Comment by mcg1969** [comment] 2015-11-07 16:53
Thanks for pinging me @msarahan but I'm afraid this is outside my scope of knowledge of the system. It sounds like you have a good handle on it. It does seem clear to me that we have to pick one version of a compiler and stick with it, and yet I also agree that some of these proposed improvements will be helpful for people who truly _need_ to build non-standard packages.

C++ is really the problem here, but Python really cares only about the C linkage. It seems like there _ought_ to be a way for people to compile code with a more modern C++ compiler but still be able to connect that code to VC9-compiled Python. I know this is a hard problem but if anyone can crack it we should clearly document it for the benefit of our users.

**Comment by nicoddemus** [comment] 2015-11-07 18:05
@ukoethe 

> True, but we needed a Python 2.7 that tracks vc11 because vc9 is too old to compile our C++ packages, and we cannot yet switch to Python 3. 

@msarahan

> Thus, Python2.7 specifies MSVC 2008 for ALL packages for Python 2.7, and so on. I see from your later point that you build Python 2.7 with MSVC 2012. That's a compelling point that we should make the compiler version explicit rather than implicit through python version. I think it won't hurt us (we will probably build only the standard configuration), but it will help you.

I second that, but we build Python 2.7 with MSVC 2010, so we've been struggling with the same situation.

**Comment by msarahan** [comment] 2015-11-08 20:56
I don't understand why conda is giving these unsatisfiable dependencies.  I have found that if I:

```conda update msvc_runtime```

Then the latest (fixed) version of conda-env, python, and msvc_runtime are pulled in.  That should happen with conda update conda, but it does not seem to.  Moreover, once that update completes, I am in no better of a situation: ```conda update --all``` still gives this unsatisfiable dependency problem.

Version 1.0.0 and 1.0.1 of msvc_runtime differ only in that 1.0.1 copies the runtime DLLs not only into Library/bin, but also into PREFIX.  It does so because the installers were failing to find these DLLs, despite the fact that we set the PATH for the installer processes to include Library/bin.

I am going to try rebuilding the anaconda-bundled packages, in the hopes that they will get re-connected with a single msvc_runtime package.

**Comment by j9ac9k** [comment] 2015-11-09 16:27
Implemented #1792, however still getting these unsatisfiable dependencies errors.  I currently have msvc_runtime 1.0.1 installed.  Not sure that helps here.

**Comment by coobas** [comment] 2015-11-09 20:07
@j9ac9k I'm still getting Unsatisfiable package specifications even after updating 
```
    conda-env:    2.4.4-py35_0 defaults --> 2.4.4-py35_2      defaults
    msvc_runtime: 1.0.0-vc14_0 defaults [vc14] --> 1.0.1-vc14_0      defaults [vc14]
    python:       3.5.0-2      defaults --> 3.5.0-3           defaults
    menuinst: 1.2.1-py35_0 defaults --> 1.2.2-py35_0 defaults
```

**Comment by j9ac9k** [comment] 2015-11-10 18:29
Yup, issue still is not resolved yet; they're working on it.

**Comment by chadkennedyonline** [comment] 2015-11-11 13:18
Not sure if this helps or not, but I came across this article that seemed highly relevant to the current issue(s): http://stevedower.id.au/blog/building-for-python-3-5-part-two/

**Comment by j9ac9k** [comment] 2015-11-13 06:08
saw conda 3.18.5 get pushed out, I updated to it, but still got msvc_runtime dependency issues, however once I reinstalled the newest version of miniconda, and updated conda, I was then able to proceed to install all packages without an issue.

In the coming day or so I'll be doing more testing, but at this point I think the issue can be closed (although I'm not sure how current users can maintain their existing distributions (not that I would be the person to know)).

**Comment by Korijn** [comment] 2015-12-01 20:27
Also having this issue... with a fresh install of `Miniconda3-3.16.0-Windows-x86_64.exe`

**Comment by msarahan** [comment] 2015-12-01 20:32
This is due to a bug in conda.  It was fixed in 3.18.5.  You need to

```conda update conda``` 

before doing anything else.  Let us know if that does not work.

**Comment by Korijn** [comment] 2015-12-02 07:07
I updated to 3.18.6 before the error occurred.

**Comment by msarahan** [comment] 2015-12-04 14:56
Pinging @ilanschnell on this - I'm lost on why this might be happening with current conda.

**Comment by Korijn** [comment] 2015-12-04 15:07
Also see: https://github.com/conda/conda-build/pull/520#issuecomment-161949463

**Comment by Korijn** [comment] 2016-01-25 16:40
We faced this issue recently and after some digging around in the source I was able to figure what caused the unsatisfiability the following part of resolve.py at the end of `gen_clauses`

```python
            # Don't install any package that has a feature that wasn't requested.
            for fn in self.find_matches(ms):
                if fn in dists and self.features(fn) - features:
                    yield (-v[fn],)

            # finally, ensure a matching package itself is installed
            # numpy-1.7-py27 OR numpy-1.7-py26 OR numpy-1.7-py33 OR
            # numpy-1.7-py27[mkl] OR ...
            clause = [v[fn] for fn in self.find_matches(ms)
                      if fn in dists]
            assert len(clause) >= 1, ms
            yield tuple(clause)
```

generated 

* `mypkg_py35[vc14] or mypkg_py34[vc10] or mypkg_py27[vc9]`
* `not mypkg_py35[vc14]`
* `not mypkg_py34[vc10]`
* `not mypkg_py27[vc9]`

(As displayed by `--alt-hint`)

This package only came in those three flavours, no other versions or builds available. The only build and runtime dependency was `python`, and the error was caused by running `conda install -n myenv python mypkg`.

I hope his info might be of some use to whoever is assigned to this. We can't reproduce anymore since we resolved by removing the packages and removing the features from the recipe and just adding `msvc_runtime` to the runtime dependencies, while we wait for a fix from you guys.

**Comment by msarahan** [comment] 2016-01-25 17:23
Pinging @ilanschnell @mcg1969

**Comment by mcg1969** [comment] 2016-01-25 18:11
Very helpful, thanks, I'll look at this.

**Comment by mcg1969** [comment] 2016-01-25 18:18
Alas, since I can't reproduce this, I can only guess. But it looks like the `features` list provided at that point does not include whichever VC feature is currently installed. The problem is that I don't know why that's happening. Can anyone help us identify an easy way to reproduce this?

**Comment by msarahan** [comment] 2016-01-25 18:21
This might be related to the frequently recurring issue that if Python
version is not explicitly passed, then its associated features do not get
activated.

**Comment by mcg1969** [comment] 2016-01-25 18:23
I tried downloading Miniconda3 3.16, installing, and doing a `conda update --all`, and all is well.

**Comment by Korijn** [comment] 2016-01-25 18:35
@msarahan that is exactly the pattern we've seen.

I'll reproduce with a minimal package tomorrow.

**Comment by mcg1969** [comment] 2016-01-25 19:02
That's great, I appreciate it. I'm confident I can develop a solution if I can reproduce it reliably.

**Comment by mcg1969** [comment] 2016-01-25 19:17
Ah, well, I do see something. 

First of all, here's the output of `conda list` after installing Miniconda 3.16. Why isn't `msvc_runtime` in there? It is a dependency, after all.

```
C:\Users\mcg_000>conda list
# packages in environment at C:\Users\mcg_000\Miniconda3:
#
conda                     3.16.0                   py34_0
conda-env                 2.4.2                    py34_0
menuinst                  1.0.4                    py34_0
pycosat                   0.6.1                    py34_0
pycrypto                  2.6.1                    py34_3
python                    3.4.3                         0
pyyaml                    3.11                     py34_1
requests                  2.7.0                    py34_0
```
In fact, if I do `conda update conda`, one of the things it installs is `msvc_runtime`. Of course, it _was_ installed, right? But the metadata was not. So that's an issue, as far as I can tell.

Now, if I do `conda update --all`, again with version 3.16 of conda, I get a features list of `('vc10','vc9','vc14')`. That's not good: only one of these features should be active. That's why [these lines](https://github.com/conda/conda/blob/master/conda/resolve.py#L1041-L1042) were added to `resolve.py`. But this just prevents conda from even _seeing_ which feature is installed. So that change is not fixing the problem, it's just covering it up a little bit.

**Comment by msarahan** [comment] 2016-01-25 19:23
Part of this observation is that msvc_runtime is a semi-recent addition.  It may not be part of the miniconda that you are starting with.  I think it came in with Miniconda 3.18.x.  Bear in mind that the assumption is that only Python is activating the vc feature.  The appropriate one should get selected when the Python package is updated.

**Comment by mcg1969** [comment] 2016-01-25 19:27
Indeed, I just looked at `conda info "python 3.4.3"`, and I see that build 0 does not include msvc_runtime as a dependency, and build 1 does.

It's not clear to me what the wisdom is for using features to differentiate between different builds of `msvc_runtime`. I don't think conda's current solver is equipped to handle features in the manner necessary to do this right. Why not just offer different _versions_ of `msvc_runtime`, with version numbers that at least roughly parallel VC's own; e.g., 9, 10, 14?

**Comment by mcg1969** [comment] 2016-01-25 19:31
Hold on: the metadata for `python-3.4.3-0.tar.bz2` says it's tracking `vc10`, but it doesn't have an `msvc_runtime` dependency. That's definitely not right.

**Comment by msarahan** [comment] 2016-01-25 20:33
See also https://github.com/conda/conda/issues/1932#issuecomment-168598451 for easy reproduction of the issue.

**Comment by mcg1969** [comment] 2016-01-25 20:52
When I execute `conda create -n python` using conda 3.16 (before the two-line fix above), it installs `python 3.5.0 1`, which tracks the `vc14` feature but does not depend on or install the corresponding runtime. I assume that the runtime is provided in the package itself. 

However, what I do know is that conda _doesn't know_ `vc14` was installed. So what that means is that if I tried to install another package that depended on that feature, it would fail.

**Comment by mcg1969** [comment] 2016-01-25 21:14
OK, I managed to reproduce the issue:

Conda 3.16, `conda create -n test35` ...

- `python matplotlib`: python 3.4.3, matplotlib 1.4.3, no msvc_runtime, vc10 feature.
- `python=3.5 matplotlib`: python 3.5.1, matplotlib 1.5.1, msvc_runtime, vc14 feature.
- `python=3.5 matplotlib=1.5.1`: same as before
- `python matplotlib=1.5.1`: unsatisfiable dependencies

With the above fix, `conda create -n test35`:

- `python matplotlib`: python 3.4.4, matplotlib 1.4.3, msvc_runtime, vc10 feature.
- `python=3.5 matplotlib`: python 3.5.1, matplotlib 1.5.1, msvc_runtime, vc14 feature
- `python=3.5 matplotlib=1.5.1`: same as before
- `python matplotlib=1.5.1`:  unsatisfiable dependencies

**Comment by Korijn** [comment] 2016-01-25 21:36
FYI: It's easy to isolate the issue with a package that doesn't have any old builds/versions *without* features.

**Comment by Korijn** [comment] 2016-01-26 16:16
As promised: https://github.com/Korijn/condabug

**Comment by mcg1969** [comment] 2016-01-26 18:27
This is great. Thanks for all the hard work.

**Comment by Korijn** [comment] 2016-01-26 20:38
Well, considering most of our codebase relies on conda, I'd say we have enough justification to help sort this out. :)

**Comment by Korijn** [comment] 2016-03-13 16:31
With the new conda 4.0 solver, these reproduction steps no longer lead to the incorrect behavior. In other words, the bug appears to be fixed!

```
> conda create -n condabug --alt-hint --use-local python hw                         
Using Anaconda Cloud api site https://api.anaconda.org                              
Fetching package metadata: ........                                                 
Solving package specifications: ...........                                         
                                                                                    
Package plan for installation in environment C:\Users\korij\Miniconda3\envs\condabug
                                                                                    
The following NEW packages will be INSTALLED:                                       
                                                                                    
    hw:           1.0.0-py35_vc14_0 [vc14]                                          
    msvc_runtime: 1.0.1-vc14_0      [vc14]                                          
    pip:          8.1.0-py35_0                                                      
    python:       3.5.1-2                                                           
    setuptools:   20.2.2-py35_0                                                     
    wheel:        0.29.0-py35_0                                                     
                                                                                    
Proceed ([y]/n)?                                                                    
                                                                                    
Linking packages ...                                                                
[      COMPLETE      ]|##################################################| 100%     
#                                                                                   
# To activate this environment, use:                                                
# > activate condabug                                                               
#                                                                                   
```

**Comment by msarahan** [comment] 2016-03-13 16:56
Thanks @korijn. Nice work @mcg1969! Closing.

**Closed by msarahan** 2016-03-13 16:56 UTC
Labels: bug, high priority

**Comment by mcg1969** [comment] 2016-03-13 17:04
Whew! What a relief. Thanks to everyone for their help.
