### ISSUE TITLE
Feature discussion: environment hierarchy

### ISSUE THREAD

**Issue by jni** [conda/conda#1209] opened 2015-03-20 05:55 UTC
I like to use separate environments for my various projects, and various *branches* of various projects. However, I also like to keep my environments updated (except for the odd testing against older dependency versions). Currently, if e.g. scikit-image gets a new version, I have to go into each environment and `conda update scikit-image`. It would be cool if I could define environments hierarchically. Example:

- I have my py3 root env (python==3.4 + anaconda),
- then I clone that to projA (python==3.4 + anaconda + projA-master + projA-requirements.txt),
- then I clone that environment to projA-branch1 (python==3.4 + anaconda + projA-branch1 + projA-branch1-requirements.txt)

when I update scikit-image in the root, that update gets propagated down the hierarchy. (but the other direction doesn't.)

This is something I've wished for quite a few times but might be difficult / rife with problems / undesirable for some reason I haven't considered. Have the conda devs considered this design and if so is there any chance of it being implemented?

Feel free to just close this if it doesn't make sense — I'd just like to know what you guys think of it.

Thanks!

**Comment by asmeurer** [comment] 2015-03-20 16:55
It makes sense. It might be a better feature request for conda-env.

**Comment by jni** [comment] 2015-03-22 02:02
@asmeurer Ah, I didn't realise that was a separate repo! Would you like me to move the issue there? I still manage my envs with conda...

**Comment by asmeurer** [comment] 2015-03-23 16:30
Yeah, I would open the issue there.

**Comment by tswicegood** [comment] 2015-04-13 19:45
Closing as a duplicate of https://github.com/conda/conda-env/issues/65.

**Closed by tswicegood** 2015-04-13 19:45 UTC

**Comment by jpoeppel** [comment] 2017-01-19 15:54
Since conda-env was migrated into conda and I cannot find either the old issue nor any documentation about this feature I thought I'd just ask if this was implemented/works (if so how?) or if this was declined? Thanks a lot!
