### ISSUE TITLE
Jupyter Notebook can't open automatically after updating Mac OS Sierra to version 10.12.5 (16F73)

### ISSUE THREAD

**Issue by kiwiweiji** [conda/conda#5408] opened 2017-05-23 13:47 UTC
I have recently started learning python and before downloading Anaconda I was using generic python 3.6.0 IDE. When I installed Anaconda the python installed  with it was 3.5.2, so I I thought I should update it to 3.6.0 but I am getting an error when I try to update it in Anaconda Navigator.

The error shows like following:

Last login: Tue May 23 06:45:35 on ttys000
WEIs-MacBook-Pro:~ weiji$ jupyter notebook
[I 06:46:25.397 NotebookApp] Serving notebooks from local directory: /Users/weiji
[I 06:46:25.397 NotebookApp] 0 active kernels
[I 06:46:25.397 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=96aa6c753255973c9698935e03bc648517ecc5c72efb837a
[I 06:46:25.397 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 06:46:25.398 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=96aa6c753255973c9698935e03bc648517ecc5c72efb837a
0:97: execution error: "http://localhost:8888/tree?token=0afbfff9ff08fc344ab3e7b24ec91fad183801d979d3f061" doesn’t understand the “open location” message. (-1708)

**Comment by chizhang529** [comment] 2017-05-24 22:10
I have the same issue here. Seems that you have to copy and paste the link manually to your browser to start it

**Comment by kalefranz** [comment] 2017-05-25 06:18
duplicate of https://github.com/jupyter/notebook/issues/2438

**Closed by kalefranz** 2017-05-25 06:18 UTC

**Comment by luolingqi** [comment] 2017-06-08 18:31
Still no solution yet!? Same here

**Comment by jezzthez** [comment] 2017-06-12 14:40
same problem here!

**Comment by ChongLu121** [comment] 2017-06-12 15:58
I have the same probelm. Even changing the setting of jupter_notebook_config.py file didn't work on my computer!!!

**Comment by musketeer191** [comment] 2017-06-16 02:09
same problem, just updated macOS to 10.12.5 :(

**Comment by sebastianmng** [comment] 2017-06-18 20:40
same problem here. Using macOS 10.12.5

**Comment by silenceOM** [comment] 2017-06-19 01:44
same problem here, just updated macOS to 10.12.5...

**Comment by yxtay** [comment] 2017-06-19 06:56
Issue has been raised here:
https://github.com/jupyter/notebook/issues/2438

There are some suggested interim solutions in that issue.

**Comment by ghao2** [comment] 2017-06-19 22:19
i'm Python 2.7.  I got this error:

[I 17:09:46.971 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 17:09:46.971 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
0:42: execution error: "http://localhost:8888/tree" doesn’t understand the “open location” message. (-1708)

But when I copy and paste http://localhost:8888/tree into browser, it works fine.

**Comment by meli-lewis** [comment] 2017-06-23 23:04
Folks posting after this issue was closed -- please note https://github.com/conda/conda/issues/5408#issuecomment-303866137

**Comment by alfonsostg** [comment] 2017-07-12 11:25
Yup, same for me.

**Comment by beaunorgeot** [comment] 2017-07-12 18:27
Summary from: #2438 

Most straightforward, browser agnostic solution posted by @lmarti:

I have just found out that if you set the BROWSER variable to open as:

export BROWSER=open

it automatically detects your default browser when you run jupyter notebook

**Comment by emudria** [comment] 2017-07-19 12:02
and how and where do I set export BROWSER = Open

**Comment by beaunorgeot** [comment] 2017-07-19 15:08
@emudria you will set the export in your bash_profile or bash_rc (depending on your system). 
It probably lives here: 
~/.bash_rc

Alternatively, starting your notebook with: 
jupyter notebook --browser=Chrome

then navigating to: 
http://localhost:8888/  (assuming only 1 notebook is open)

Also works fine

**Comment by perrydc** [comment] 2017-07-24 15:30
My fix was:

nano ~/.bash_profile

add these lines:
export BROWSER=open
alias j="~/anaconda/bin/jupyter_mac.command ; exit;"

control-X to save, then restart terminal

et voila!  now you can just open terminal and type j to open jupyter in your browser

**Comment by sanpietro** [comment] 2017-07-24 23:00
Thanks @perrydc for the fix! One thing to note is that many of us are using anaconda2, so just need to make sure that we change it to: alias j="~/anaconda**2**/bin/jupyter_mac.command ; exit;"

**Comment by lis07** [comment] 2017-07-27 16:17
@perrydc thank you so much! It worked perfect for me!

**Comment by Clara-YR** [comment] 2017-08-18 10:06
open terminal in Mac
type `jupyter notebook --generate-config`
the output is `Writing default config to: /Users/User_name/.jupyter/jupyter_notebook_config.py`
then type `open /Users/User_name/.jupyter/jupyter_notebook_config.py` to open the python file
find `#c.NotebookApp.browser = u' '` 
and change it to `c.NotebookApp.browser = u'Chrome '`

**Comment by fatma95** [comment] 2017-09-30 16:58
Thank youu @perrydc
