### ISSUE TITLE
conda-forge::perl installation error

### ISSUE THREAD

**Issue by aschuerch** [conda/conda#4819] opened 2017-03-07 14:08 UTC
I get this error when trying to install packages with perl dependencies or perl itself (conda 4.3.14 on linux) :

`conda create -n perltest perl`

> Fetching package metadata .................
> Solving package specifications: .
> 
> Package plan for installation in environment /hpc/local/CentOS7/dla_mm/tools/miniconda2/envs/perltest:
> 
> The following NEW packages will be INSTALLED:
> 
>   perl: 5.22.2.1-0 conda-forge
> 
> Proceed ([y]/n)? y
> 
> 
> ERROR
>
> conda.core.link:_execute_actions(335): An error occurred while installing package 'conda-forge::perl-5.22.2.1-0'.
> OSError(22, 'Invalid argument')
> Attempting to roll back.`
>
> OSError(22, 'Invalid argument')

Any ideas how to solve this?

**Comment by kalefranz** [comment] 2017-03-07 16:30
Can you attach the log.txt file created from

    conda create -n perltest perl -vvv | tee log.txt

I don't yet understand what's going on, but I'd really like to.

**Comment by aschuerch** [comment] 2017-03-07 18:51
I guess you would want the whole output so I did
`conda create -n perltest perl -vvv 2>&1 | tee log.txt`

[log.txt](https://github.com/conda/conda/files/825434/log.txt)

**Comment by nehaljwani** [comment] 2017-03-12 18:23
@aschuerch Is `/hpc` a special filesystem? Could you please share the output for the command: `mount`

**Comment by aschuerch** [comment] 2017-03-13 06:22
```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=65863524k,nr_inodes=16465881,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mapper/vg0-root on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime,seclabel)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
/dev/sda1 on /boot type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg0-var on /var type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
/dev/mapper/vg0-tmp on /tmp type xfs (rw,relatime,seclabel,attr2,inode64,usrquota)
isilon.storage.hpc:/ifs/data/group_space/dbg_gen on /hpc/dbg_gen type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.30,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.30)
isilon.storage.hpc:/ifs/data/group_space/dla_ao on /hpc/dla_ao type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.27,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.27)
isilon.storage.hpc:/ifs/data/group_space/hub_kind on /hpc/hub_kind type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.35,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.35)
isilon.storage.hpc:/ifs/data/group_space/dla_mm on /hpc/dla_mm type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.20,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.20)
isilon.storage.hpc:/ifs/data/group_space/uu_csb on /hpc/uu_csb type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.11,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.11)
isilon.storage.hpc:/ifs/data/group_space/hub_creyghton on /hpc/hub_creyghton type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.40,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.40)
isilon.storage.hpc:/ifs/data/group_space/uu_pmi on /hpc/uu_pmi type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.28,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.28)
isilon.storage.hpc:/ifs/data/group_space/hub_scs on /hpc/hub_scs type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.18,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.18)
isilon.storage.hpc:/ifs/data/group_space/hub_clevers on /hpc/hub_clevers type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.17,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.17)
isilon.storage.hpc:/ifs/data/group_space/uu_ics_vht on /hpc/uu_ics_vht type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.33,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.33)
isilon.storage.hpc:/ifs/data/tmp on /hpc/tmp type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.16,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.16)
isilon.storage.hpc:/ifs/data/local on /hpc/local type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.38,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.38)
isilon.storage.hpc:/ifs/data/group_space/dhl_ec on /hpc/dhl_ec type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.10,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.10)
isilon.storage.hpc:/ifs/data/group_space/hers_en on /hpc/hers_en type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.32,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.32)
isilon.storage.hpc:/ifs/data/home on /home type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.19,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.19)
isilon.storage.hpc:/ifs/data/group_space/cog_gonl on /hpc/cog_gonl type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.37,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.37)
isilon.storage.hpc:/ifs/data/group_space/imaging_mrstat on /hpc/imaging_mrstat type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.14,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.14)
isilon.storage.hpc:/ifs/data/group_space/digd_rr on /hpc/digd_rr type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.36,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.36)
isilon.storage.hpc:/ifs/data/group_space/uu_bio_fg on /hpc/uu_bio_fg type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.22,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.22)
isilon.storage.hpc:/ifs/data/group_space/hub_oudenaarden on /hpc/hub_oudenaarden type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.15,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.15)
isilon.storage.hpc:/ifs/data/group_space/dbg_mz on /hpc/dbg_mz type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.25,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.25)
isilon.storage.hpc:/ifs/data/sge on /opt/sge type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.13,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.13)
isilon.storage.hpc:/ifs/data/group_space/uu_cryoem on /hpc/uu_cryoem type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.29,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.29)
isilon.storage.hpc:/ifs/data/group_space/dla_lti on /hpc/dla_lti type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.24,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.24)
isilon.storage.hpc:/ifs/data/group_space/cog_bioinf on /hpc/cog_bioinf type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.39,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.39)
isilon.storage.hpc:/ifs/data/shared on /hpc/shared type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.34,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.34)
143.121.12.176:/ifs/provider/op/groups on /data/isi type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=143.121.243.143,local_lock=none,addr=143.121.12.176)
tmpfs on /run/user/10195 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10195,gid=532)
tmpfs on /run/user/10862 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10862,gid=10044)
tmpfs on /run/user/11421 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11421,gid=10044)
tmpfs on /run/user/11305 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11305,gid=532)
tmpfs on /run/user/60165 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=60165,gid=532)
tmpfs on /run/user/7015 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=7015,gid=10044)
tmpfs on /run/user/11213 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11213,gid=10044)
tmpfs on /run/user/11391 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11391,gid=532)
isilon.storage.hpc:/ifs/data/group_space/julius_me on /hpc/julius_me type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.37,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.37)
isilon.storage.hpc:/ifs/data/group_space/uu_bio_mgx on /hpc/uu_bio_mgx type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.34,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.34)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /run/user/11039 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11039,gid=10595)
tmpfs on /run/user/11237 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11237,gid=532)
tmpfs on /run/user/10796 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10796,gid=11248)
tmpfs on /run/user/11453 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11453,gid=11248)
tmpfs on /run/user/11559 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11559,gid=532)
tmpfs on /run/user/10991 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10991,gid=500)
tmpfs on /run/user/10655 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10655,gid=532)
tmpfs on /run/user/10680 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10680,gid=10595)
tmpfs on /run/user/10101 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10101,gid=532)
tmpfs on /run/user/11262 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11262,gid=532)
tmpfs on /run/user/11068 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11068,gid=11066)
tmpfs on /run/user/10935 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10935,gid=666)
tmpfs on /run/user/11069 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11069,gid=10044)
tmpfs on /run/user/10957 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10957,gid=10308)
tmpfs on /run/user/10327 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10327,gid=10326)
tmpfs on /run/user/11030 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11030,gid=10932)
tmpfs on /run/user/11322 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11322,gid=10308)
tmpfs on /run/user/10708 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10708,gid=10595)
tmpfs on /run/user/10794 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10794,gid=10308)
isilon.storage.hpc:/ifs/data/gnu on /gnu type nfs (rw,relatime,vers=3,rsize=131072,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.5.32,mountvers=3,mountport=300,mountproto=udp,local_lock=none,addr=10.100.5.32)
tmpfs on /run/user/733 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=733,gid=532)
tmpfs on /run/user/10619 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=10619,gid=532)
tmpfs on /run/user/11463 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=13174936k,mode=700,uid=11463,gid=10571)
```

**Comment by nehaljwani** [comment] 2017-03-13 10:12
@aschuerch Would it be possible to share the output for:
```bash
cd /hpc/local/CentOS7/dla_mm/tools/miniconda2/
touch 'App::Cpan.3'
ln 'App::Cpan.3' 'App2::Cpan.3'
```

**Comment by aschuerch** [comment] 2017-03-13 10:21
```
ln:` failed to create hard link ‘App2::Cpan.3’ => ‘App::Cpan.3’: Invalid argument
```

Are you sure about the location?

**Comment by nehaljwani** [comment] 2017-03-13 10:24
It is weird that your isilon mount allows you to create a file with the name '::' in it, but is not able to create a hard link. Does this succeed:
```bash
cd /hpc/local/CentOS7/dla_mm/tools/miniconda2/
touch 'App::Cpan.3'
ln 'App::Cpan.3' 'AppCpan.3'
```

**Comment by aschuerch** [comment] 2017-03-13 10:27
yes

**Comment by nehaljwani** [comment] 2017-03-13 10:30
Which flavour of Linux are you using? Is it CentOS 7? Does the `touch` and subsequent `ln` command with '::' in the filenames succeed in a directory which is _not_ an isilon mount?  Which version of isilon are you using?

**Comment by nehaljwani** [comment] 2017-03-13 10:41
Temporarily, your woes might be sorted out by using the following commands instead:
```bash
cond env remove -yn perltest
conda create -n perltest perl --copy
```

**Comment by aschuerch** [comment] 2017-03-13 10:54
It is CentOS7. I am not the sysadmin so I don't know about the isilon mount but I can't seem to find any other mounts that I could write to. On my other computer, running conda 4.3.13, everything seems to be fine though.

And 

`conda create -n perltest perl --copy`

works, thank you. I'll be using that for the moment.

Thank you very much for your help!

**Comment by lpagie** [comment] 2017-03-21 09:55
Not sure if I should comment on this thread or start a new one:
I tried installing tophat, which chocked on installing perl with a near identical error msg as above (sorry; history is lost): 
```
conda.core.link:_execute_actions(335): An error occurred while installing package 'conda-forge::perl-5.22.2.1-0'.
OSError(22, 'Invalid argument')
Attempting to roll back.

OSError(22, 'Invalid argument')
````
Except it tried to install perl-5.22.0.1-0

Googling let me here and I at some point installed perl using:
```
conda install perl --copy -vvv
```
which worked out ok.
Next I installed tophat with:
```
conda install tophat
```
which now also worked.

Note; I'm new to conda, so bear with me in case I did something stupid.
If you want me to test something let me know.
grts, Ludo

**Comment by nehaljwani** [comment] 2017-03-22 03:10
@lpagie Could you please:

- Attach the log.txt file created from: `conda create -n perltest perl -vvv | tee log.txt`
- Share with use the name of the filesystem on which you were trying to create the environment?

**Comment by greggjm** [comment] 2017-04-13 22:41
@nehaljwani I was led here with the same issue, though it didn't resolve itself like @lpagie.

I'm using ubuntu 16.04 via WSL and running into this problem continually when trying to install the necessary tools for tophat, hisat2, etc.

Not sure if this is identical to the issue in this thread, but since I'm on WSL I can start a new thread if needed. I've alluded to this issue [here](https://github.com/conda/conda/issues/4827) and am just trying to follow up on it for a fix since I'd like to include these packages in an automatic installation script for other beginners like myself.
[perltest_fail.txt](https://github.com/conda/conda/files/921041/perltest_fail.txt)

Any insight would be appreciated.

**Comment by nehaljwani** [comment] 2017-04-14 08:29
@greggjm I went through the debug output to find that error occurs when trying to extract a file with '::' in the filename.

```bash
OSError: [Errno 22] Invalid argument: '/root/unix/bin/miniconda3/pkgs/perl-5.22.2.1-0/man/man3/Encode::Config.3'
```

Now, I may be wrong, but according to [Windows docs](https://support.microsoft.com/en-in/help/905231/information-about-the-characters-that-you-cannot-use-in-site-names,-folder-names,-and-file-names-in-sharepoint), a file cannot have any of the following characters in it's name:
```
 \, /, :, *, ?, "", <, >, |.
```

Even thought that might be the case, I went ahead and tried installing `perl` from the `conda-forge` channel on `WSL`. And it succeeded for me. When I looked at the particular file at which the extraction for you was failing, I noticed that Windows stored the character ':' as '#003A' [(the utf-8 value)](http://www.htmlescape.net/00/character_colon_003a.html) but the Linux Subsystem automatically understands this and interprets it as ':' (I don't know how). They probably do this by [intercepting](https://blogs.msdn.microsoft.com/wsl/2016/06/08/wsl-system-calls/) the open() syscall.
![screenshot from 2017-04-14 12-52-55](https://cloud.githubusercontent.com/assets/1779189/25037812/d6d71f56-2118-11e7-9974-8aea56219b5f.png)

That being said, could you please try updating Windows? There was a discussion related to this in one of the GitHub issues on WSL at https://github.com/Microsoft/BashOnWindows/issues/1514 and it seems to have been fixed in a newer version. This worked for me on `Windows 10 Home v1607 Build: 14393.0`

**Comment by greggjm** [comment] 2017-04-14 12:21
@nehaljwani Thanks for the help. 

I thought it might have been a bug with one of the earlier versions of WSL so I updated Windows on April 11th to the creators build as it was released. I was using Windows 10 v 1607 build 14393 for the first thread #4827 , but as of posting in this thread I've been using Windows 10 v 1703 build 15063.168.

**Comment by nehaljwani** [comment] 2017-04-14 13:01
@greggjm Is it the case that you have created any mount point or symbolic link to a destination which is not present inside linux subsystem at `%localappdata%\lxss`? Do you face the same issue when you try to use miniconda inside, let's say `/home/miniconda2`? To confirm my suspicion, could you please share the output for:
```bash
sudo touch /root/unix/bin/miniconda3/pkgs/a:b
sudo touch /root/a:b
touch /home/$whatever-username-you-created/a:b
```

**Comment by greggjm** [comment] 2017-04-14 18:22
@nehaljwani You're spot-on, that fixed it. 

The output of the commands are as follows:
`sudo touch /root/unix/bin/miniconda3/pkgs/a:b`
touch: setting times of '/root/unix/bin/miniconda3/pkgs/a:b': No such file or directory
`sudo touch /root/a:b`
makes a:b in ~/
`touch /home/$whatever-username-you-created/a:c`
creates file a:c in /home/$user/

The larger problem I had was many packages that I tried installing using conda failed upon attempting to extract perl. Installing miniconda to a destination in the linux subsystem solved the issue.

I'll provide a little more background in case google directs anybody else here with my issue.

The linux subsystem is present in the local appdata folder. To make things a bit more convenient for downloading files in windows and making them available for use in linux, I symbolically linked a folder on my desktop (named unix) to my home directory. 

During installation, I installed miniconda to a folder within the unix folder on my desktop. I ran into the problem with perl as files with the character ':' were being extracted outside of the linux subsystem. 

Thanks again.

**Closed** 2017-05-01 20:20 UTC

**Comment by lpagie** [comment] 2017-05-30 07:59
@greggjm I ran into the same problem again. I can probably work around it again but I thought trying to add to your findings above.
I also work on an Isilon file system. I do have access to a std ext4 linux file system as well.
I can confirm that creating hard links to files containing ':' does work on the linux filesystem but not on the Isilon filesystem. I can create ':' files on Isilon, and also soft links, and copies, but not hard links.

I attempted to downgrade perl. I ran the following and attached the output:
`conda install perl=5.22.0.1-0 -vvv &> /tmp/tt`
[tt.gz](https://github.com/conda/conda/files/1037557/tt.gz)

I can provide the following info regarding filesystems:
`
df -h $HOME /tmp
Filesystem                                Size  Used Avail Use% Mounted on
nfs.isi-hpc01.nki.nl:/ifs/data/nfs/users  379T  336T   38T  90% /home/NFS/users
/dev/sdb1                                  30G   19G  9.4G  67% /
`
where `nfs.isi-hpc01.nki.nl` is the nfs mounted Isilon storage, and /dev/sdb1 is ext4 filesystem.

Creating and linking ':' files:
```
cd /tmp/; df -h .; touch tt::tt; ln tt::tt tt::hardlink; ln -s tt::tt tt::softlink; cp tt::tt tt::copy; ls -l *tt\:*
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1        30G   19G  9.4G  67% /
-rw-r--r-- 1 l.pagie domain users 0 May 30 09:51 tt::copy
-rw-r--r-- 2 l.pagie domain users 0 May 30 09:51 tt::hardlink
lrwxrwxrwx 1 l.pagie domain users 6 May 30 09:51 tt::softlink -> tt::tt
-rw-r--r-- 2 l.pagie domain users 0 May 30 09:51 tt::tt


cd $HOME/tmp/; df -h .; touch tt::tt; ln tt::tt tt::hardlink; ln -s tt::tt tt::softlink; cp tt::tt tt::copy; ls -l *tt\:*
Filesystem                                Size  Used Avail Use% Mounted on
nfs.isi-hpc01.nki.nl:/ifs/data/nfs/users  379T  336T   38T  90% /home/NFS/users
ln: failed to create hard link 'tt::hardlink' => 'tt::tt': Invalid argument
-rw-r--r-- 1 l.pagie domain users 0 May 30 09:52 tt::copy
lrwxrwxrwx 1 l.pagie domain users 6 May 30 09:52 tt::softlink -> tt::tt
-rw-r--r-- 1 l.pagie domain users 0 May 30 09:52 tt::tt
```

Is there anything else I can do to help you finding a general solution?

cheers

**Comment by nehaljwani** [comment] 2017-06-04 07:16
@lpagie As a workaround, You can use the `--copy` flag as I have mentioned at https://github.com/conda/conda/issues/4819#issuecomment-286072345

I may be wrong, but it might be the case that this could have been fixed in a newer version of Isilon, since I wasn't able to reproduce this on the [isolon simulator v8.1](https://www.emc.com/products-solutions/trial-software-download/isilon.htm)
