### ISSUE TITLE
Conda update error

### ISSUE THREAD

**Issue by naseer786** [conda/conda#7295] opened 2018-05-16 03:57 UTC
In my windows10 environment I am unable to upgrade conda using following command

>>conda update conda

**My anaconda and python version**

    (base) C:\Users\naseer>conda --version
    conda 4.5.3
    
    (base) C:\Users\naseer>python --version
    Python 3.6.4 :: Anaconda, Inc.

**following is my error log** 

(base) C:\Users\naseer>conda update conda
Solving environment: failed

'>>>>>>>>>>>>>>>>Error Report>>>>>>>>>>>>>>>>>>>

`$ C:\Users\naseer\Anaconda3\Scripts\conda update conda`

  environment variables:
                 CCHZPATH=C:\CTEX\CTeX\cct\fonts
                 CCPKPATH=C:\CTEX\CTeX\fonts\pk\modeless\cct\dpi$d
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\naseer\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\naseer\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\naseer\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\naseer\Anaconda3
              CONDA_SHLVL=1
             GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
                 HOMEPATH=\Users\naseer
             INTELOCLPATH=C:\Intel\OpenCL\sdk\bin\x64;C:\Intel\OpenCL\sdk\bin\x86
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\intel64_win_mic
                     PATH=C:\Users\naseer\Anaconda3;C:\Users\naseer\Anaconda3\Library\mingw-w64\
                          bin;C:\Users\naseer\Anaconda3\Library\usr\bin;C:\Users\naseer\Anaconda
                          3\Library\bin;C:\Users\naseer\Anaconda3\Scripts;C:\Users\naseer\Anacon
                          da3\bin;C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_20
                          18.0.124\windows\mpi\intel64\bin;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files
                          (x86)\Common Files\Intel\Shared
                          Libraries\redist\ia32_win\mpirt;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program
                          Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compil
                          er;C:\Intel\OpenCL\sdk\bin\x64;C:\Intel\OpenCL\sdk\bin\x86;C:\Intel\Op
                          enCL\sdk\bin\Pin;C:\Intel\OpenCL\sdk\bin\GTPin;C:\Program
                          Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
                          tem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files\dotnet\;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\CTE
                          X\UserData\miktex\bin;C:\CTEX\MiKTeX\miktex\bin;C:\CTEX\CTeX\ctex\bin;
                          C:\CTEX\CTeX\cct\bin;C:\CTEX\CTeX\ty\bin;C:\CTEX\Ghostscript\gs9.05\bi
                          n;C:\CTEX\GSview\gsview;C:\CTEX\WinEdt;C:\Program
                          Files\MATLAB\R2018a\runtime\win64;C:\Program
                          Files\MATLAB\R2018a\bin;C:\Program
                          Files\MATLAB\R2016b\runtime\win64;C:\Program
                          Files\MATLAB\R2016b\bin;C:\Program
                          Files\MATLAB\R2016b\polyspace\bin;C:\Program Files\Git\cmd;C:\Program
                          Files\Microsoft VS
                          Code\bin;C:\Users\naseer\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program
                          Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program
                          Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files
                          (x86)\Microsoft SDKs\Azure\PowerShell\Storage\
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\naseer\Anaconda3
            shell level : 1
       user config file : C:\Users\naseer\.condarc
 populated config files : C:\Users\naseer\.condarc
          conda version : 4.5.3
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Users\naseer\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/noarch/win-64
                          https://conda.anaconda.org/noarch/noarch
                          https://github.com/manuel-calzolari/sklearn-genetic.git/win-64
                          https://github.com/manuel-calzolari/sklearn-genetic.git/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\naseer\Anaconda3\pkgs
                          C:\Users\naseer\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\naseer\Anaconda3\envs
                          C:\Users\naseer\AppData\Local\conda\conda\envs
                          C:\Users\naseer\.conda\envs
               platform : win-64
             user-agent : conda/4.5.3 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False

V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
CondaHTTPError: HTTP 404 NOT FOUND for url <https://github.com/manuel-calzolari/sklearn-genetic.git/noarch/repodata.json>
Elapsed: 00:01.876498
The remote server could not find the noarch directory for the
requested channel with url: https://github.com/manuel-calzolari/sklearn-genetic.git

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

A reportable application error has occurred. Conda has prepared the above report.
Upload successful.

(base) C:\Users\naseer>

**My conda channel list**

    (base) C:\Users\naseer>type C:\Users\naseer\.condarc
    channels:
      - https://github.com/manuel-calzolari/sklearn-genetic.git
      - defaults
    report_errors: true
    ssl_verify: true

**My Effort so far**

So reading error message it shows that as per the new conda version I need to create some specific files in a channel So I added those files using following commands (As I am not able to install any package so I could not install bzip2 also)

**I first created necessary directories and files as told** 

    (base) C:\Users\naseer>mkdir noarch
    
    (base) C:\Users\naseer>echo '{}' > noarch/repodata.json
    
    (base) C:\Users\naseer>echo  > noarch/repodata.json.bz2
    
    (base) C:\Users\naseer>

**then I added this new channel noarch**

    (base) C:\Users\naseer>conda config --add channels noarch

**Output from my condarc file**

    (base) C:\Users\naseer>type C:\Users\naseer\.condarc
    channels:
      - noarch
      - https://github.com/manuel-calzolari/sklearn-genetic.git
      - defaults
    report_errors: true
    ssl_verify: true

Again I tried to update conda but still got the same long error?

**Comment by rubennj** [comment] 2018-05-17 21:53
Similar problem here:
```
>conda update conda
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.3
  latest version: 4.5.4

Please update conda by running

    $ conda update -n base conda

# All requested packages already installed.

>conda update -n base conda
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.3
  latest version: 4.5.4

Please update conda by running

    $ conda update -n base conda

# All requested packages already installed.
```
It never gets updated, I think is since version 4.5.3
```
python version : 3.6.5.final.0
platform : win-64
user-agent : conda/4.5.3 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.16299
administrator : False
netrc file : None
offline mode : False
```

**Comment by kalefranz** [comment] 2018-05-17 22:35
@rubennj your issue is a duplicate of #7165.  Fixed with #7289 + #7303 in conda 4.5.5.

**Comment by kalefranz** [comment] 2018-05-17 22:36
@naseer786 neither `noarch` nor `https://github.com/manuel-calzolari/sklearn-genetic.git` are valid conda channels.  Remove those lines from your `.condarc` file.

**Closed by kalefranz** 2018-05-17 22:36 UTC

**Comment by naseer786** [comment] 2018-05-18 02:41
@kalefranz  Yes I figured it out . The reason was those incorrect channels so I removed them froma .condarc file. Now everything is perfectly fine!
