### ISSUE TITLE
conda install from GH sub-tree

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#677] opened 2014-04-16 20:05 UTC
E.g. Imagine the `usermgmt` directory (and its sub-content) in our original Wakari repo contained everything required for a conda package.  It would be great to be able to do:

``` bash
conda install https://github.com/ContinuumIO/wakari/tree/master/usermgmt
```

Nothing specific to an "app" in there, just need conda install to know how to handle URLs to GH, and act on a directory sub-tree instead of a repo.

**Comment by kalefranz** [comment] 2017-05-08 15:55
duplicate of https://github.com/conda/conda/issues/306

**Closed by kalefranz** 2017-05-08 15:55 UTC
