### ISSUE TITLE
safety check of total dependencies at the end of an install

### ISSUE THREAD

**Issue by cjw296** [conda/conda#1268] opened 2015-04-11 21:31 UTC
Of course, having proper, full, dependency resolution before the "install" of a package or set of packages commits to being completed would be what we should aim for, in the meantime:

once any install operation completes, do a check of the installed packaged and make sure none of their dependency version specifications have been violated and whine loudly if they have!

(another one for @tswicegood )

**Comment by asmeurer** [comment] 2015-04-11 21:56
I'm not sure I follow. conda *does* check for dependency consistency when you install (or rather, it's impossible for the solver to generate a package installation solution that is inconsistent).

**Comment by cjw296** [comment] 2015-04-11 22:00
Does it do that for *all* packages in the environment, whether installed by pip or conda?
(not just the dependencies of what was installed...)

**Comment by tswicegood** [comment] 2015-04-13 19:36
@asmeurer try this test case:

* `conda create --yes -n test python=3.4*`
* `source activate test`
* `conda install flask --yes`
* `conda install python=2.7* --yes`

At this point, all of the Flask code that was installed is installed with the py34 builds.

What @cjw296 is after here is to revisit the dependencies within an environment prior to allowing the install.  For example, the Flask dependencies for py34 require python3.4*.  At some point during that `python=2.7*` install something should complain.

My preference for this is to see what has a dependency on the package, then see if there's another build that meets the correct dependency and tell the user they have to install that to continue, then fail if it can't be found.

**Comment by cjw296** [comment] 2015-04-13 20:36
Right, as a minimum, after any package install is finished, running a check on all packages installed in an environment and making sure they don't have incompatible dependencies installed and whining with an error if they do, would be what I would have expected.

**Comment by asmeurer** [comment] 2015-04-13 20:58
I see. This is somewhat a duplicate of https://github.com/conda/conda/issues/454. Checking an installation independently is possible, although, I'm not sure what the value would be. It would be very difficult to give a reasonable error message when it isn't satisfiable. I can think of some partial "solutions" to this problem, but the user experience would only be optimal with #454, I think. Otherwise it's really on the user to really make sure that things are "correct".

Also worth point out that there is already sort of a way to achieve this. `conda update --all` is equivalent to `conda install A B C ...` for all the all the packages installed in the environment. This will generate a consistant installation if it can, for the reason I noted [above](https://github.com/conda/conda/issues/1268#issuecomment-91933348). This in general updates everything because conda updates packages when you install them. But you can keep packages downgraded by pinning them (http://continuum.io/blog/advanced-conda-part-1#pinning-packages). 

Checking pip packages is outside the scope of conda.

**Comment by cjw296** [comment] 2015-04-13 21:15
Yep #454 looks related.

`conda update --all` is a hacky work around for the lack of what should be there ;-)

conda understands pip metadata so why is ensuring the sum total of packages installed by conda and pip into an environment fulfil the metadata-stated dependency requirements of the installed packages not an aim of conda?

pinning feels like we now have several places to achieve the same thing :-(
(I'd just prefer environment.yml to be the "one true source" of conda package requirements)

**Comment by asmeurer** [comment] 2015-04-13 21:22
conda doesn't really read pip metadata. `conda list` shells out to `pip list` and formats the result. That's the entirety of conda's interaction with pip. 

If you're using environment.yml, I'd say your workflow should be to edit that file and rerun `conda env` whenever you want to install a new package (or I think there might be a `conda env` command that does these both at once). Installing packages manually strictly speaking always puts the environment out of sync with the environment.yml (even if the environment itself is still self consistent).

**Comment by cjw296** [comment] 2015-04-13 21:28
I must be missing something: how does `pip install` find packages installed by conda?

**Comment by asmeurer** [comment] 2015-04-13 21:57
conda packages include the pip metadata (the egg-info file), which is installed by distutils when the conda package is made.

**Comment by kalefranz** [comment] 2017-05-08 16:20
Outdated after all the solver work in 4.0.

**Closed by kalefranz** 2017-05-08 16:20 UTC
Labels: type:bug
