### ISSUE TITLE
neither `conda activate` nor `conda deactivate` are described in `conda --help`

### ISSUE THREAD

**Issue by poshul** [conda/conda#10953] opened 2021-09-30 10:16 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

`activate` and `deactivate` commands are not described in `conda --help`

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /home/samuel/miniconda3
            shell level : 1
       user config file : /home/samuel/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.10.43.3=0
                          __glibc=2.32=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/samuel/miniconda3  (writable)
      conda av data dir : /home/samuel/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/samuel/miniconda3/pkgs
                          /home/samuel/.conda/pkgs
       envs directories : /home/samuel/miniconda3/envs
                          /home/samuel/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/5.10.43.3-microsoft-standard-WSL2 ubuntu/18.04.4 glibc/2.32
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /home/samuel/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
argon2-cffi               20.1.0           py39h27cfd23_1    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
biopython                 1.78             py39h7f8727e_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.0.0              pyhd3eb1b0_0    defaults
bottleneck                1.3.2            py39hdd57654_1    defaults
brotli                    1.0.9                he6710b0_2    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2021.7.5             h06a4308_1    defaults
certifi                   2021.5.30        py39h06a4308_0    defaults
cffi                      1.14.6           py39h400218f_0    defaults
chardet                   4.0.0           py39h06a4308_1003    defaults
conda                     4.10.3           py39h06a4308_0    defaults
conda-package-handling    1.7.3            py39h27cfd23_1    defaults
cryptography              3.4.7            py39hd23ed53_0    defaults
cycler                    0.10.0           py39h06a4308_0    defaults
dbus                      1.13.18              hb2f20db_0    defaults
debugpy                   1.4.1            py39h295c915_0    defaults
decorator                 5.0.9              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
entrypoints               0.3              py39h06a4308_0    defaults
expat                     2.4.1                h2531618_2    defaults
fontconfig                2.13.1               h6c09931_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.10.4               h5ab3b9f_0    defaults
glib                      2.69.1               h5202010_0    defaults
gst-plugins-base          1.14.0               h8213a91_2    defaults
gstreamer                 1.14.0               h28cd5cc_2    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
importlib-metadata        4.8.1            py39h06a4308_0    defaults
importlib_metadata        4.8.1                hd3eb1b0_0    defaults
intel-openmp              2021.3.0          h06a4308_3350    defaults
ipykernel                 6.2.0            py39h06a4308_1    defaults
ipython                   7.27.0           py39hb070fc8_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.4              pyhd3eb1b0_0    defaults
jedi                      0.18.0           py39h06a4308_1    defaults
jinja2                    3.0.1              pyhd3eb1b0_0    defaults
jpeg                      9d                   h7f8727e_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter_client            7.0.1              pyhd3eb1b0_0    defaults
jupyter_console           6.4.0              pyhd3eb1b0_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
kiwisolver                1.3.1            py39h2531618_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgfortran-ng            7.5.0               ha8ba4b0_17    defaults
libgfortran4              7.5.0               ha8ba4b0_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.12               h03d6c58_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
markupsafe                2.0.1            py39h27cfd23_0    defaults
matplotlib                3.4.2            py39h06a4308_0    defaults
matplotlib-base           3.4.2            py39hab158f2_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mistune                   0.8.4           py39h27cfd23_1000    defaults
mkl                       2021.3.0           h06a4308_520    defaults
mkl-service               2.4.0            py39h7f8727e_0    defaults
mkl_fft                   1.3.0            py39h42c9631_2    defaults
mkl_random                1.2.2            py39h51133e4_0    defaults
munkres                   1.1.4                      py_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.1.0            py39h06a4308_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
notebook                  6.4.4              pyha770c72_0    conda-forge
numexpr                   2.7.3            py39h22e1b3c_1    defaults
numpy                     1.20.3           py39hf144106_0    defaults
numpy-base                1.20.3           py39h74d4b33_0    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
openjpeg                  2.4.0                h3ad879b_0    defaults
openssl                   1.1.1l               h7f8727e_0    defaults
packaging                 21.0               pyhd3eb1b0_0    defaults
pandas                    1.3.3            py39h8c16a72_0    defaults
pandocfilters             1.4.3            py39h06a4308_1    defaults
parso                     0.8.2              pyhd3eb1b0_0    defaults
pcre                      8.45                 h295c915_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.3.1            py39h2c7a002_0    defaults
pip                       21.1.3           py39h06a4308_0    defaults
prometheus_client         0.11.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.17             pyhca03da5_0    defaults
prompt_toolkit            3.0.17               hd3eb1b0_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.20                       py_2    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py39h2531618_6    defaults
pyrsistent                0.18.0           py39h7f8727e_0    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.5                h12debd9_4    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1             pyhd3eb1b0_0    defaults
pyzmq                     22.2.1           py39h295c915_1    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 5.1.1              pyhd3eb1b0_0    defaults
qtpy                      1.10.0             pyhd3eb1b0_0    defaults
readline                  8.1                  h27cfd23_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
scipy                     1.7.1            py39h292c36d_2    defaults
seaborn                   0.11.2             pyhd3eb1b0_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                52.0.0           py39h06a4308_0    defaults
sip                       4.19.13          py39h2531618_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
terminado                 0.9.4            py39h06a4308_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tornado                   6.1              py39h27cfd23_0    defaults
tqdm                      4.61.2             pyhd3eb1b0_1    defaults
traitlets                 5.1.0              pyhd3eb1b0_0    defaults
tzdata                    2021a                h52ac0ba_0    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1            py39h06a4308_1    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1            py39h06a4308_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zeromq                    4.3.4                h2531618_0    defaults
zipp                      3.5.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.9                haebb681_0    defaults
```

</details>

**Comment by kenodegard** [comment] 2022-03-09 20:41
Duplicate of https://github.com/conda/conda/issues/6353

**Closed by kenodegard** 2022-03-09 20:41 UTC
Labels: source::community, type::documentation, duplicate
