### ISSUE TITLE
Wrong hostname in prompt after activating root environment

### ISSUE THREAD

**Issue by TTTPOB** [conda/conda#8008] opened 2018-12-03 11:57 UTC
I am using miniconda 3, latest version on a centos 6 x64 machine(cluster).
normally, prompt in terminal displays correctly like 
![image](https://user-images.githubusercontent.com/19909103/49372489-ced20d80-f735-11e8-99bb-ed9543504f26.png)

or
![image](https://user-images.githubusercontent.com/19909103/49372263-0b513980-f735-11e8-94ac-bea9e99ce9b7.png)
but if I activate the root environment using conda activate, I would get
![image](https://user-images.githubusercontent.com/19909103/49372320-2cb22580-f735-11e8-9011-3b3820efec66.png)
which makes me unable to find out which node in the cluster I am on.
but in bash it looks ok as I expected
![image](https://user-images.githubusercontent.com/19909103/49372427-903c5300-f735-11e8-919d-b9d649200f3f.png)
activating the non-root environment won't cause that problem in both bash (figure not shown) and zsh.
![image](https://user-images.githubusercontent.com/19909103/49520789-04662a80-f8df-11e8-8348-3df23d28ba60.png)
(I do changed zsh theme but it doesn't matter)

zsh: 5.5.1
bash: 4.1.2(2)
conda: 4.5.11
being inside or outside tmux does not make any difference.

**Comment by nehaljwani** [comment] 2018-12-10 11:53
Closing as duplicate of https://github.com/conda/conda/issues/7031

**Closed by nehaljwani** 2018-12-10 11:53 UTC
