### ISSUE TITLE
"Unexpected Error" when updating anaconda packages with "conda update --all"

### ISSUE THREAD

**Issue by CYUlysses** [conda/conda#6862] opened 2018-02-10 23:06 UTC
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

Error message followed by abortion of update process.

### Steps to Reproduce

Started the terminal with admin access, activated the correct environment, and used
"conda update -all -v"

## Expected Behavior
Packages updated nicely.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3\envs\spacy2
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\cydru\AppData\Local\conda\conda\envs
                          C:\Users\cydru\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\cydru\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\cydru\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.16299
          administrator : True
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\cydru\.condarc <==
ssl_verify: True
channels:
  - conda-forge
  - anaconda-fusion
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\ProgramData\Anaconda3\envs\spacy2:
#
alabaster                 0.7.10                   py36_1    conda-forge
asn1crypto                0.23.0           py36h546eea3_0    defaults
astroid                   1.5.3                    py36_0    conda-forge
astropy                   2.0.2               np113py36_1    conda-forge
attrs                     17.4.0                     py_0    conda-forge
babel                     2.5.0            py36h35444c1_0    defaults
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
blinker                   1.4                      py36_0    conda-forge
bokeh                     0.12.13                  py36_0    conda-forge
boto                      2.48.0                   py36_0    defaults
bz2file                   0.98                     py36_0    defaults
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
chardet                   3.0.4                     <pip>
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.2                      py_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cymem                     1.31.2                    <pip>
cytoolz                   0.8.2                     <pip>
dask                      0.16.1                     py_0    conda-forge
dask-core                 0.16.1                     py_0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
dill                      0.2.7.1                   <pip>
dill                      0.2.7.1                  py36_0    conda-forge
distributed               1.20.2                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
en-core-web-sm            2.0.0                     <pip>
entrypoints               0.2.3                    py36_1    conda-forge
es-core-news-sm           2.0.0                     <pip>
freetype                  2.7                      vc14_1  [vc14]  conda-forge
ftfy                      4.4.3                     <pip>
gensim                    3.0.1               py36_vc14_0  [vc14]  conda-forge
glue-core                 0.12.0                   py36_0    conda-forge
glue-vispy-viewers        0.9                      py36_0    conda-forge
glueviz                   0.12.0                        0    conda-forge
google-api-python-client  1.6.5                     <pip>
h5py                      2.7.1                    py36_2    conda-forge
hdf5                      1.10.1                   vc14_1  [vc14]  conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
httplib2                  0.10.3                    <pip>
icu                       58.1                     vc14_1  [vc14]  conda-forge
idna                      2.6                      py36_1    conda-forge
idna                      2.6                       <pip>
imageio                   2.2.0                    py36_0    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
isort                     4.2.15                   py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                       vc14_1  [vc14]  conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter_client            5.2.2                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
langdetect                1.0.7                      py_0    conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.28                   vc14_0  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_0  [vc14]  conda-forge
libxslt                   1.1.29                   vc14_5  [vc14]  conda-forge
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.1.0                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.0                    py36_0    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
mkl                       2017.0.3                      0    defaults
msgpack-numpy             0.4.1                     <pip>
msgpack-python            0.4.8                     <pip>
msgpack-python            0.5.1                    py36_0    conda-forge
murmurhash                0.28.0                    <pip>
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
networkx                  2.0                      py36_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
notebook                  5.4.0                    py36_0    conda-forge
numpy                     1.13.3                    <pip>
numpy                     1.13.1                   py36_0    defaults
numpydoc                  0.7.0                    py36_0    conda-forge
oauth2client              4.1.2                     <pip>
oauthlib                  2.0.6                      py_0    conda-forge
olefile                   0.44                     py36_0    conda-forge
openssl                   1.0.2l                   vc14_0  [vc14]  conda-forge
pandas                    0.20.3                   py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
pathlib                   1.0.1                     <pip>
pdfminer.six              20170720                 py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
plac                      0.9.6                     <pip>
plotly                    2.2.3                    py36_0    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
preshed                   1.0.0                     <pip>
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.0                    py36_0    conda-forge
py                        1.5.2                      py_0    conda-forge
pyasn1                    0.4.2                     <pip>
pyasn1-modules            0.2.1                     <pip>
pycodestyle               2.3.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyjwt                     1.5.3                      py_0    conda-forge
pylint                    1.8.1                    py36_0    conda-forge
pyopengl                  3.1.1a1                  py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyreadline                2.1              py36h094d952_1    defaults
pyreadline                2.1                       <pip>
pysocks                   1.6.7                    py36_0    conda-forge
pytest                    3.4.0                    py36_0    conda-forge
python                    3.6.3                         0    conda-forge
python-crfsuite           0.9.2               py36_vc14_0  [vc14]  conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pywavelets                0.5.2                    py36_1    conda-forge
pywinpty                  0.5                      py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.3.1                    py36_0    conda-forge
regex                     2017.04.05                <pip>
requests                  2.18.4                   py36_1    conda-forge
requests                  2.18.4                    <pip>
requests-oauthlib         0.8.0                    py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
rsa                       3.4.2                     <pip>
scikit-image              0.13.1                   py36_0    conda-forge
scikit-learn              0.19.0              np113py36_0    defaults
scipy                     0.19.1              np113py36_0    defaults
send2trash                1.4.2                      py_0    conda-forge
setuptools                36.6.0                   py36_1    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                    <pip>
six                       1.11.0                   py36_1    conda-forge
smart_open                1.5.3                    py36_0    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sortedcontainers          1.5.7                    py36_0    conda-forge
spacy                     2.0.2                     <pip>
sphinx                    1.6.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.6                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
thinc                     6.10.0                    <pip>
toolz                     0.8.2                      py_2    conda-forge
toolz                     0.8.2                     <pip>
tornado                   4.5.2                    py36_0    conda-forge
tqdm                      4.19.4                    <pip>
traitlets                 4.3.2                    py36_0    conda-forge
twython                   3.6.0                    py36_0    conda-forge
typing                    3.6.2                    py36_0    conda-forge
ujson                     1.35                      <pip>
uritemplate               3.0.0                     <pip>
urllib3                   1.22                     py36_0    conda-forge
urllib3                   1.22                      <pip>
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                     <pip>
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
webencodings              0.5.1                     <pip>
wheel                     0.30.0                     py_1    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
wincertstore              0.2                      py36_0    conda-forge
winpty                    0.4.3                    vc14_2  [vc14]  conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
wrapt                     1.10.11                   <pip>
xlrd                      1.1.0                      py_2    conda-forge
xlsxwriter                1.0.2                      py_0    conda-forge
xx-ent-wiki-sm            2.0.0                     <pip>
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
```
</p></details>

## Error output:
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3\envs\spacy2
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\cydru\AppData\Local\conda\conda\envs
                          C:\Users\cydru\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\cydru\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\cydru\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.16299
          administrator : True

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py update --all -v`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/d', '/c', 'C:\\ProgramData\\Anaconda3\\envs\\spacy2\\Scripts\\.ipykernel-post-link.bat']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package conda-forge::ipykernel-4.8.1-py36_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProgramData\Anaconda3\envs\spacy2\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 281, in execute
        pkg_data, actions)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package conda-forge::ipykernel-4.8.1-py36_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProgramData\Anaconda3\envs\spacy2\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package conda-forge::ipykernel-4.8.1-py36_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProgramData\Anaconda3\envs\spacy2\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

**Comment by nehaljwani** [comment] 2018-02-11 07:42
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/8087

**Closed by nehaljwani** 2018-02-11 07:42 UTC
