### ISSUE TITLE
`python-dateutil 2.9.0post0` is actually 2.8.2

### ISSUE THREAD

**Issue by sam-s** [conda/conda#13933] opened 2024-05-22 14:31 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Conda reports `dateutil` as 2.9 while 2.8 is actually installed:
```
$ conda list --show-channel-urls dateutil
# packages in environment at .../miniconda3/envs/c312:
#
# Name                    Version                   Build  Channel
python-dateutil           2.9.0post0      py312haa95532_0
```
but
```
$ python -c 'import dateutil; print(dateutil.__version__); print(dateutil.__path__)'
2.8.2
['.../miniconda3/envs/c312/Lib/site-packages/dateutil']
```
and
```
cat $(python -c 'import dateutil; print(dateutil.__path__[0])')/_version.py
# file generated by setuptools_scm
# don't change, don't track in version control
...
__version__ = version = '2.8.2'
__version_tuple__ = version_tuple = (2, 8, 2)
```

[Judging by](https://github.com/dateutil/dateutil/issues/1314)

> .../miniconda3/envs/c312/Lib/site-packages/dateutil/tz/tz.py: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated...

the actually used code is 2.8.2.

(I replaced backslashes in paths with normal slashes by hand to protect my eyes).

[Original report](https://stackoverflow.com/q/78514084/850781).

### Conda Info

```shell
active environment : c312
    active env location : C:\Users\ssteingold\AppData\Local\miniconda3\envs\c312
            shell level : 2
       user config file : C:\Users\ssteingold\.condarc
 populated config files : C:\Users\ssteingold\.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.11.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.5.0=0
                          __cuda=11.4=0
                          __win=0=0
       base environment : C:\Users\ssteingold\AppData\Local\miniconda3  (writable)
      conda av data dir : C:\Users\ssteingold\AppData\Local\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda/win-64
                          https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda/noarch
                          https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/win-64
                          https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/noarch
                          https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo/win-64
                          https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo/noarch
                          https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev/win-64
                          https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\ssteingold\AppData\Local\miniconda3\pkgs
                          C:\Users\ssteingold\.conda\pkgs
                          C:\Users\ssteingold\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ssteingold\AppData\Local\miniconda3\envs
                          C:\Users\ssteingold\.conda\envs
                          C:\Users\ssteingold\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.5.0 requests/2.32.1 CPython/3.11.6 Windows/10 Windows/10.0.19045
solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\ssteingold\.condarc <==
ssl_verify: False
...
channel_priority: flexible
channels:
  - https://artprod.dev.bloomberg.com/artifactory/api/conda/bb-conda
  - https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge
  - https://artprod.dev.bloomberg.com/artifactory/bb-bqnt/conda-repo
  - https://artprod.dev.bloomberg.com/artifactory/bqnt-conda-dev
  - conda-forge
  - defaults
report_errors: False
```

### Conda list

```shell
far too long
```

**Comment by kenodegard** [comment] 2024-05-22 14:59
@sam-s thanks for reporting, the appropriate team has been notified and will be rebuilding the `python-dateutil 2.9.0post0` package

closing this ticket since the issue is not pertaining to conda itself

**Closed by kenodegard** 2024-05-22 14:59 UTC
Labels: off-topic

**Comment by kenodegard** [comment] 2024-05-22 20:06
@sam-s the ticket is unfortunately internal but you can follow along with the work here https://github.com/AnacondaRecipes/python-dateutil-feedstock/pull/6

in the future please report any issue with the packages themselves to https://github.com/ContinuumIO/anaconda-issues, thanks!

**Comment by JeanChristopheMorinPerso** [comment] 2024-05-24 00:27
This is now fixed.

**Comment by sam-s** [comment] 2024-10-29 17:31
I still observe the same problem after `conda install --force-reinstall python-dateutil`: files stamped with `2024-05-07`, `conda list python-dateutil` reports `2.9.0post0` while  `_version.py` has `2.8.2`

**Comment by sam-s** [comment] 2024-10-29 18:49
> [@sam-s](https://github.com/sam-s) the ticket is unfortunately internal but you can follow along with the work here [AnacondaRecipes/python-dateutil-feedstock#6](https://github.com/AnacondaRecipes/python-dateutil-feedstock/pull/6)
> 
> in the future please report any issue with the packages themselves to https://github.com/ContinuumIO/anaconda-issues, thanks!

https://github.com/ContinuumIO/anaconda-issues/issues/13435
