### ISSUE TITLE
Update environment variables when running "conda env update"

### ISSUE THREAD

**Issue by geoffdavey** [conda/conda#10725] opened 2021-06-15 13:47 UTC
It seems that environment variables are not updated when running "conda env update" (see example below).

Proposal: either enable it or mention in the documentation that environment variables won't be updated.

```
(base) [plaid@machine env-test]$ conda create --clone base --name test
Source:      /mnt/appdata/plaid/test/anaconda-2021.05
Destination: /mnt/appdata/plaid/test/anaconda-2021.05/envs/test
The following packages cannot be cloned out of the root environment:
 - defaults/linux-64::conda-env-2.6.0-1
 - defaults/linux-64::conda-4.10.1-py38h06a4308_1
 - defaults/noarch::conda-token-0.3.0-pyhd3eb1b0_0
 - defaults/linux-64::anaconda-navigator-2.0.3-py38_0
 - defaults/linux-64::conda-build-3.21.4-py38h06a4308_0
Packages: 339
Files: 0
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [plaid@machine env-test]$ cat environment.yaml
channels:
  - defaults
variables:
  MY_ENV_VAR: 1

(base) [plaid@machine env-test]$ conda env update --file environment.yaml --name test
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [plaid@machine env-test]$ conda activate test
(test) [plaid@machine env-test]$ echo MY_ENV_VAR=$MY_ENV_VAR
MY_ENV_VAR=
(test) [plaid@machine env-test]$
```

**Comment by jezdez** [comment] 2021-06-16 12:53
Duplicate of #10652.

**Closed by jezdez** 2021-06-16 12:53 UTC
