### ISSUE TITLE
Taking long time to install any package.

### ISSUE THREAD

**Issue by SoumanPaul** [conda/conda#7839] opened 2018-10-08 17:48 UTC
Whenever i try to install any package in conda environment it takes long time to complete process. 
please make it more faster.

Thank you.

**Comment by ThirstyGeo** [comment] 2018-10-16 02:12
You are right, but this is already discussed here:
https://github.com/conda/conda/issues/7239

**Comment by lonelykid** [comment] 2018-10-28 13:31
> You are right, but this is already discussed here:
> #7239

Hi @ThirstyGeo , is the problem solved? Could you give me a reference link to the solution?

**Comment by msarahan** [comment] 2018-10-28 13:41
closing as duplicate of #7239

**Closed by msarahan** 2018-10-28 13:41 UTC
