### ISSUE TITLE
Conda create --no-deps not working as expected

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda#2327] opened 2016-04-04 15:28 UTC
Using  `--no-deps` will correctly not install dependencies but inexplicably requires them to be in-place.

Using conda to make a staging area to deploy packages. It should be possible to place all conda packages in a sub directory, index it with `conda index` and proceed with a `conda create`. 
conda is forcing me to place packages that I don’t wish to deploy.

Summary: If you use `--no-deps` it should not require dependencies to be available if its not going to install them.

**Comment by mcg1969** [comment] 2016-04-04 15:29
conda 4.0 has a rule: dependencies must be satisfied unless you use '--force'. '--force' is the only way to willingly break an environment. Can you ask him to try '--force --no-deps' and see what happens?

**Comment by JeremyEnns** [comment] 2016-04-04 21:08
No luck with `--force`, note that without --force, it will install without the dependency (with --no-deps ). But only if it has access to the dependency. 

Tried with conda 4.0 / 3.19.1 / 3.12

**Comment by mcg1969** [comment] 2016-04-05 13:23
OK, I understand better now, but I'm pretty sure this has been a long-standing behavior. (Whether it should or not.) I seem to recall telling someone else about this. I *think* the solution is to feed the full filename to `conda` on the command line instead of a URL.

**Comment by ilanschnell** [comment] 2016-04-06 05:14
My understanding (and that used to be the behavior a long time ago) of `--no-deps` is that this dependencies are ignored (as if the package had no dependencies, maybe Python was handled special).
This is in contrast with `--force`, which does not ignore dependencies.

**Comment by mcg1969** [comment] 2016-04-06 14:24
Per our previous conversation @ilanschnell I'm all for getting this nailed down and implemented.

**Comment by JeremyEnns** [comment] 2016-05-20 17:32
https://github.com/conda/conda/issues/2035 also relevant to this.

**Comment by kalefranz** [comment] 2016-06-10 03:02
@mcg1969 Let's write a regression/integration test for this use case now.

**Comment by mcg1969** [comment] 2016-06-10 12:16
We still need to settle on what it is _supposed_ to do in the first place.

As Ilan says, his understanding is that dependencies are ignored. That means, apparently, that it is just going to pick the latest version of the package and install it. Of course, there's no guarantee that this package will _work_ in this manner. I think we all acknowledge this. 

But in my view it's worse than that. Suppose there is a package that is built separately for Python 2 and Python 3, and you have Python 3 installed. They have different dependencies, but because you're using this flag, conda is supposed to ignore them. That means it's entirely _arbitrary_ which version of the package is picked. If conda _happens_ to install the Python 3 version, then it will work; if it _happens_ to install the Python 2 version, it will not. This means that no-deps has the potential to install the wrong package _even if installing the right package is possible_. What am I missing?

If I'm not missing anything, then the solution is simple: use an explicit spec. But we support that now, already, don't we?

So if someone can explain _exactly_ how `--no-deps` is/was supposed to work, in all scenarios, then I think we can implement it. Whether or not it can actually be done by 4.1 I do not know.

**Comment by mcg1969** [comment] 2016-06-10 12:30
https://github.com/conda/conda/blob/18af6e354bd1c180aac4fba06e2b68ab5e7042ac/conda/cli/install.py#L199-L219

This is conda 3.18.0. If I understand this correctly, then --no-deps works in two different ways:

- When the specs are all .tar.bz2 files, then this older version of conda would install them all, determine their their dependencies, and install those. If --no-deps is supplied, it would skip this last step. The problem I'm seeing here, as it relates to conda 4.x: what if the tar files are installed, and then conda discovers that it *can't* determine a set of dependencies that will make everything work? It has _already installed_ the tar files at this point, so it can't go back.

- For normal sets of specs, --no-deps performs the full solve, including the dependencies, and _then_ drops the dependencies after the fact. I'm pretty sure we still do that, but because conda 4.x does a better solve, it's likely producing undesirable results for people.

My feeling here is that --no-deps is fundamentally problematic, and we need to find a way to address some specific uses cases and let the rest of them go. So for instance, if you have a list of .tar.bz2 files, we should certainly allow you to create an environment that contains just them, with no dependencies.

**Comment by mcg1969** [comment] 2016-06-10 20:16
I think I've found the commit where `--no-deps` behavior was changed:

https://github.com/conda/conda/commit/5effd9ec727b935f5e1794e6fba64541d82e3544#diff-34bb8d01f991a5ffabae5e80b987c83fL45

@ilanschnell, it looks like this is your change, and it's not clear what the motivation is for this. But what seems to have happened is that 2 out of the 3 times where `no_deps` is actually referenced, the behavior was effectively changed to `no_deps=True` always.

Apparently, in the past, `install_tar` and `install_local_packages` would assemble a list of dependencies for the newly installed packages; and if `no_deps=False`, these dependencies would be passed along to the standard install logic in a second installation step.

**Comment by mcg1969** [comment] 2016-06-10 20:23
To be perfectly fair, I actually think this is the right thing to do. If you're installing tarballs, it ought to just be a straight `--force` install with no further analysis. I'm not inclined to roll this back.

But we still have to address the @JeremyEnns scenario. What do to with a staging area of local packages? I say the mistake is turning the local packages into a channel with `conda index` and `conda create`.  I think instead we should be working to make sure that explicit channel lists work properly.

What do you think, Jeremy?

**Comment by kalefranz** [comment] 2016-06-20 18:52
There's a lot of unspecified behavior here that I think we need to spend more time on, and now appears to be out of scope for 4.1.x.  Bumping the issue to 4.2.x.

**Comment by kalefranz** [comment] 2016-07-11 18:26
Input here has slowed, and the 4.2 canary release is hitting Thursday.  Bumping to 4.3.

**Comment by kalefranz** [comment] 2017-05-02 01:19
@JeremyEnns can you revisit this issue in the context of 4.3?  Have we fixed the problems you were seeing?

**Comment by kalefranz** [comment] 2017-05-04 18:14
@JeremyEnns please re-open if this is still a problem.

**Closed by kalefranz** 2017-05-04 18:14 UTC
Labels: priority:high, type:bug
