### ISSUE TITLE
Error when cloning an environment

### ISSUE THREAD

**Issue by malev** [conda/conda#2633] opened 2016-06-09 15:21 UTC
I'm using `conda create --clone` to create a new environment and it's failing big time!

```
[root@hostname ~]# /opt/wakari/anaconda/bin/conda create -p ~/new-env --clone /opt/wakari/anaconda/
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
src_prefix: '/opt/wakari/anaconda'
dst_prefix: '/root/new-env'
Packages: 313
Files: 47057
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'r-zoo-1.7_12-r3.2.2_1a.tar.bz2'
[root@hostname ~]#
```

**Comment by mcg1969** [comment] 2016-06-09 18:11
@malev can you give me a raw `conda create` command that produces an environment that breaks cloning?

**Comment by mcg1969** [comment] 2016-06-09 18:13
I suspect we've fixed this in master, because among other things we've cleaned up this output:
```
src_prefix: '/opt/wakari/anaconda'
dst_prefix: '/root/new-env'
```
It would now be
```
Source:      /opt/wakari/anaconda
Destination: /root/new-env
```

**Comment by mcg1969** [comment] 2016-06-09 18:14
Actually, scratch that, your Flowdock chat suggests even rc3, which has the new output format, is broken. Again, I'll be happy to work on this ASAP if you can give me an offending environment to work with. Thanks!

**Comment by mcg1969** [comment] 2016-06-09 20:06
Here's what I've found. 

Environments created with older versions of `conda` don't have the `url` field included in their `conda-meta` metadata. This prevents `conda` from determining what channel it came from, and therefore whether the packages in the package cache represent the proper version of the package to clone.

The good news is this: environments created with `conda 4.0.8` or later include this `url` field, which allows cloning to proceed normally. So if you were to re-create this environment again using the later version of conda, all would be well. Furthermore, `conda 4.1.x` will do one better, and support fully offline cloning as long as all of the correct packages are in the cache. Previous versions of conda would still try and query Anaconda Cloud.

The bad news: we can't clone these older environments with 4.1, it seems, because we don't know where the packages came from. This can be fixed, by basically searching the users' channel lists in priority order for the requested package dist, and accepting the first match. But let me suggest we do this in 4.1.1. 

@malev, is that going to throw things off for you? Would it be possible to re-create the base Wakari environment using 4.0.8 or later? And if that is the case, @kalefranz is this timeline acceptable?

**Comment by grlee77** [comment] 2016-06-09 21:10
Good to hear this is being addressed.  I believe all of the following are the same or similar issue: #2539, #2536, #2510, #2404, #2351, #2315, #2278

**Comment by mcg1969** [comment] 2016-06-10 00:15
Yep. There are quite a few of these indeed.

**Comment by zym1010** [comment] 2016-07-05 01:38
I tried removing everything about `miniconda`, installed a conda with version `4.0.10`, created an environment with packages from `conda-forge`, and still ran into this problem (see <https://travis-ci.org/leelabcnbc/DevOps/builds/142343218>). I checked that environment `conda-meta` does have `url` for packages... So maybe this is not an issue with `url` only?

**Comment by malev** [comment] 2016-07-11 19:34
@mcg1969 @kalefranz the problem is still happening in `4.1.6`:

```
[root@marcos-conda-clone ~]# /opt/wakari/anaconda/bin/conda --version
conda 4.1.6
[root@marcos-conda-clone ~]# /opt/wakari/anaconda/bin/conda create -p ~/new-env --clone /opt/wakari/anaconda/ --offline
Source:      /opt/wakari/anaconda
Destination: /root/new-env
The following packages cannot be cloned out of the root environment:
 - <unknown>::conda-4.1.6-py27_0
 - <unknown>::conda-build-1.20.3-py27_0
 - <unknown>::conda_analysis_package-0.2.1-py27_0_g9faaee8
Fetching package metadata ...
Error: Packages  missing in current linux-64 channels: - py-1.4.31-py27_0.tar.bz2
 - pip-8.1.2-py27_0.tar.bz2
 - sip-4.16.9-py27_0.tar.bz2
 - r-evaluate-0.8-r3.2.2_0a.tar.bz2
```

Talking with @mcg1969 he asked me to have an environment where you folks can reproduce the problem. I have created the environment, just contact me to get the credentials.

Related to https://github.com/ContinuumIO/aen-issues/issues/395

**Comment by kalefranz** [comment] 2016-07-11 19:41
@malev public key at `curl https://api.github.com/users/kalefranz/keys`

This isn't prioritized right now.  However, if you can give me a step-by-step simple way to reproduce the problem (i.e. isolated reproducibility) so that I can write a regression test out of your instructions, recent history has shown that it will get fixed pretty quickly.

**Comment by malev** [comment] 2016-07-11 19:46
@kalefranz how to reproduce:

```
[root@marcos-conda-clone ~]# /opt/wakari/anaconda/bin/conda --version
conda 4.1.6
[root@marcos-conda-clone ~]# /opt/wakari/anaconda/bin/conda create -p ~/new-env --clone /opt/wakari/anaconda/ --offline
```

**Comment by kalefranz** [comment] 2016-07-13 15:57
> This isn't prioritized right now.

I actually misspoke.  I intend to tackle it on (or before if it can be easily reproduced) in 4.3 or soon after.  A "root cause" fix goes along with cleaning up the package cache.

**Comment by malev** [comment] 2016-07-19 15:39
FWI, I've tested the new conda `4.1.8` and still not working

**Comment by dorzel** [comment] 2016-07-20 16:41
Yes it seems that the problem is due to this environment being created with an older version of conda, as the metadata is missing more than a few fields that are expected in more recent versions. Doing the clone in --offline mode means it doesn't have the data it needs.

A temporary fix (this was on @malev 's environment) was to add the "defaults" and "r" channels to .condarc, and do the clone without "--offline". This fixed it for most packages, all but 3:


```
[root@marcos-conda-clone conda-meta]# /opt/wakari/anaconda/bin/conda create -p ~/new-env --clone /opt/wakari/anaconda/
Source:      /opt/wakari/anaconda
Destination: /root/new-env
The following packages cannot be cloned out of the root environment:
 - conda-4.1.8-py27_0
 - <unknown>::conda-build-1.20.3-py27_0
 - <unknown>::conda_analysis_package-0.2.1-py27_0_g9faaee8
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Error: Packages  missing in current linux-64 channels: - ipython-we-4.2-py27_28_g2d95eab.tar.bz2
 - pandoc-1.12.3-3.tar.bz2
 - wakari-client-1.0.2-py27_37.tar.bz2
```

An alternative is to force update the packages to their same version, which applies the correct metadata. However, trying to use that on the few that were left over:

```
[root@marcos-conda-clone conda-meta]# /opt/wakari/anaconda/bin/conda update -f ipython-we
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........
Warning: cannot lookup MD5 of: <unknown>::ipython-we-4.2-py27_28_g2d95eab.tar.bz2
Package plan for installation in environment /opt/wakari/anaconda:

The following NEW packages will be INSTALLED:

    ipython-we: 4.2-py27_28_g2d95eab <unknown>

Proceed ([y]/n)? y

Extracting packages ...
An unexpected error has occurred, please consider sending the                                                    |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/install.py", line 848, in extract
    url = rec['urls'][0]
IndexError: list index out of range
```

Looking into ways to solve this.

**Comment by damianavila** [comment] 2016-07-20 22:24
@dorzel just to let you know the `--offline` is a must for us. The resolution can not depend on getting online data (unless you are suggesting an online "fix" pre-step to solve the issue about the metadata and then we can use the clone command offline as we expect to... I mean, in a `offline` setup).

**Comment by dorzel** [comment] 2016-07-21 14:46
@damianavila Indeed the online fix would only have to happen once, or if you could recreate the environment from scratch with the latest conda it would no longer have to go online to get the metadata as everything would be in place.

**Comment by kalefranz** [comment] 2016-07-28 20:29
Just want to update this ticket.  We're still working on a definite, final, awesome solution.  @dorzel's analysis should be helpful.  @mcg1969 or @HugoTian should have time to iterate further in the next couple days.

**Comment by damianavila** [comment] 2016-07-28 23:23
Thanks for the update @kalefranz

**Comment by mcg1969** [comment] 2016-07-31 22:08
I SSH'ed into the test machine. One obvious issue I found is that `/opt/wakari/anaconda/pkgs` had none of the packages required to reproduce the environment. Conda will never be able to clone without either the tarballs or the extracted packages residing in that directory. We do not just copy the package files from the original environment---they are re-linked _from the package cache_.

However, @dorzel is basically correct. `/opt/wakari/anaconda` cannot be cloned offline with 4.1.11, because it was constructed with an older version of `conda`, and that version of conda did not embed the necessary metadata in the environment to complete the cloning. I _am_, however, able to do an offline clone of a _clone_ of that environment. That is, I can do this:

1. Update conda to 4.1.11
2. `conda create -c wakari -p ~/new_env --clone /opt/wakari/anaconda`
3. `conda create -p ~/new_env2 --clone ~/new_env`

Note that the second, offline clone does not require `-c wakari`.

My recommendation is that `/opt/wakari/anaconda` be recreated using the latest 4.1.x version of conda, so that the necessary package metadata is in place to do the cloning. 

I did come up with a couple of fixes that would make it possible to clone the existing `/opt/wakari/anaconda` environment offline. It basically involves allowing offline mode to use the _cached_ metadata for the channels. Whether we want to do this now for 4.1.x, include those changes in 4.2.x or later, I leave up to @kalefranz.

However, in either case, the package cache _must_ be filled. There is absolutely no way to accomplish an offline clone with `/opt/wakari/anaconda`  in the state that I found it in.

**Comment by damianavila** [comment] 2016-08-01 15:30
Nice info, thanks @mcg1969.

**Comment by kalefranz** [comment] 2016-08-02 18:27
I think we have a resolution here now. The plan is for AEN to start using constructor rather than cas-installer, and that should resolve the root cause of the issue.

**Comment by damianavila** [comment] 2016-08-02 22:11
>I think we have a resolution here now. The plan is for AEN to start using constructor rather than cas-installer, and that should resolve the root cause of the issue.

@kalefranz well... AEN can not use constructor in replacement of cas-installer, but I agree this issue can be closed (see https://github.com/ContinuumIO/aen-issues/issues/455 for more details).

**Comment by kalefranz** [comment] 2016-08-03 14:36
@damianavila I got something wrong then. And I don't want to close the issue until I make sure I've done everything possible to help you guys.  Going to re-open, and schedule a call with you.

**Closed** 2016-09-01 15:47 UTC
Labels: bug, cio, ent
