### ISSUE TITLE
Stacking conda env is not working as expected

### ISSUE THREAD

**Issue by hkjoo13** [conda/conda#9597] opened 2020-01-13 22:36 UTC
I'm trying to stack two conda environments, **env_A** (say, includes numpy) and **env_B** (say, does NOT include numpy).

By activating **env_A** first, then stacking **env_B**, 'll be in **env_B** but backed by **env_A**.
So my expectation is that numpy is still importable as it is in env_A.

## Current Behavior
```
conda activate env_A
conda activate --stack env_B
python -c 'import sys; print(sys.path)'
```

This returns
```
[
 '', 
 '/home/hkjoo/projects/envs/env_B/lib/python36.zip', 
 '/home/hkjoo/projects/envs/env_B/lib/python3.6', 
 '/home/hkjoo/projects/envs/env_B/lib/python3.6/lib-dynload', 
 '/home/hkjoo/projects/envs/env_B/lib/python3.6/site-packages'
]
```

env_A is not part of sys.path, hence numpy **could not** be imported.

## Questions

With a little bit of debugging, I've learned that **sys.path** gets populated from PYTHONPATH (which is empty for me) and installation-dependent defaults from **site.py** during python initialization.

site.py looks for '\site-pacakges' path for only two prefixes which are **sys.prefix** and **sys.exec_prefix**, which are the first element in the PATH (**env_B** in this case).

And I think updated PATH variable and/or CONDA_PREFIX_1, etc (which are modified by doing `conda activate --stack`) are not actually reflected.

**Hence my question, does `conda activate --stack` really work in ipython and/or python?**

**Comment by hkjoo13** [comment] 2020-01-13 22:47
@nh3, @mfansler, @kalefranz Appreciate if you have any advises & comments! :)

**Comment by sdebionne** [comment] 2020-01-14 10:28
I believe this a duplicate of #9578.

**Comment by hkjoo13** [comment] 2020-01-14 11:06
> I believe this might be related to #9578.

Thank you @sdebionne. I went through the link, feel my issue is more on python initialization step (as conda commands edit PATH as expected).

Once you stack, and start Python, does **sys.path** get populated correctly for you?

**Comment by sdebionne** [comment] 2020-01-14 12:43
> Once you stack, and start Python, does sys.path get populated correctly for you?

In my case, I get Python from the `base` environment instead of the `env_A`. Are you running Linux or Windows?

**Comment by hkjoo13** [comment] 2020-01-14 12:48
> > Once you stack, and start Python, does sys.path get populated correctly for you?
> 
> In my case, I get Python from the `base` environment instead of the `env_A` (my `env_B` does not have python). Are you running Linux or Windows?

I'm running in Linux.

**Comment by sdebionne** [comment] 2020-01-14 12:53
Does your `env_B` have Python installed? If yes, I guess it's hidding the python (and all the packages such as numpy) in `env_A`.

**Comment by forrestwaters** [comment] 2020-01-14 14:13
Stacking environments does not currently modify PYTHONPATH; only path. If python is installed in env_B, it will not be able to import python packages from env_A and that is currently working as intended.

**Comment by hkjoo13** [comment] 2020-01-14 14:18
> Stacking environments does not currently modify PYTHONPATH; only path. If python is installed in env_B, it will not be able to import python packages from env_A and that is currently working as intended.

Thank you @forrestwaters. Agree that conda only modify PATH, not PYTHONPATH.

Regarding your second point, why 'not able to import packages from env_A' is expected when:
```
conda activate env_A
conda activate --stack env_B
```

If numpy is in **envA** and not in **env_B**, shouldn't we be able to import numpy by stacking?

**Comment by forrestwaters** [comment] 2020-01-14 14:26
The stacked environment is placed higher on PATH. So if python gets installed into env_B, you'll be using the python from that environment (which also inherits it's PYTHONPATH). The only time you'd be able to import packages from env_A is if python is installed **only** in env_A

**Comment by hkjoo13** [comment] 2020-01-14 14:36
This is a good point. I've removed python from env_B and did the same:
```
conda activate env_A
conda activate --stack env_B

python -c "import sys; print(sys.path)"
```
However now this returns below, no /site-packages folder of **env_A** is in sys.path.
[
 '', 
 '/home/hkjoo/projects/envs/env_A/lib/python36.zip', 
 '/home/hkjoo/projects/envs/env_A/lib/python3.6', 
 '/home/hkjoo/projects/envs/env_A/lib/python3.6/lib-dynload', 
 '/home/hkjoo/projects/envs/env_A/lib/python3.6/site-packages'
]

Did it work to you @forrestwaters ?

**Comment by hkjoo13** [comment] 2020-01-14 17:34
> The stacked environment is placed higher on PATH. So if python gets installed into env_B, you'll be using the python from that environment (which also inherits it's PYTHONPATH). The only time you'd be able to import packages from env_A is if python is installed **only** in env_A


I've done a little bit more research, and I think it is not possible to create a conda env without python (unless creating a completely empty one).

As soon as I install package that has python as part of requirement, it gets installed. 

That being said.. I wonder what is the truely expected behavior when one stacks envs?

**Comment by mingwandroid** [comment] 2020-01-14 20:29
We do not attempt to merge the python path from stacked environments. The only thing stacked is PATH itself.

It is not possible in general to stack python path safely (pyc file format is different as is syntax) and even if we were to slow it when the version match exactly it would represent a huge change of behavior for python. Stacked envs are for specific use cases where attacking of executables found on PATH is the goal.

Perhaps our docs should make this clear?

**Comment by sdebionne** [comment] 2020-01-15 08:09
It is definitely possible to create env without python. I do mostly C++ dev and do that all the time.

The expected behavior when envs are stacks is that the stacked env (`env_B`) is searched first for executable/scripts then the base one (`env_A`). Quoting @forrestwaters above:

> The stacked environment is placed higher on `PATH`.

**Comment by mfansler** [comment] 2020-01-15 14:02
> It is definitely possible to create env without python. I do mostly C++ dev and do that all the time.

Yes, but creating an env without Python but still with Python packages seems to be what OP is asking. This would require force installing packages, i.e. circumventing Conda's dependency management. Generally, it's not practical and would require manual curation to ensure the package builds match the Python version of the other env.

**Comment by hkjoo13** [comment] 2020-01-15 14:32
> We do not attempt to merge the python path from stacked environments. The only thing stacked is PATH itself.
> 
> It is not possible in general to stack python path safely (pyc file format is different as is syntax) and even if we were to allow it when the versions match exactly it would represent a huge change of behavior for python. Stacked envs are for specific use cases where stacking of executables found on PATH is the goal.
> 
> Perhaps our docs should make this clear?

Thanks @mingwandroid this made me clear.

**Comment by forrestwaters** [comment] 2020-01-15 18:35
Closing as this seems to be cleared up now.

**Closed by forrestwaters** 2020-01-15 18:35 UTC
