### ISSUE TITLE
By downgrading conda 4.5.0 to 4.4.7 "ONDA_EXE*" appear at the end of downgrading process.

### ISSUE THREAD

**Issue by Usama23** [conda/conda#6999] opened 2018-03-07 13:47 UTC
Miniconda2/3- 4.5.0
Conda 4.5.0

**Steps to Reproduce:**

1: Download and install miniconda.
2: From prompt downgrade conda version from 4.5.0 to 4.4.7.

**Actual Result:**

At the end of the downgrading process "ONDA_EXE*" appear and run itself which is not recognized in result.
```

(base) C:\Users\tester>conda install conda=4.4.7
Solving environment: done

## Package Plan ##

  environment location: C:\Users\tester\Miniconda2

  added / updated specs:
    - conda=4.4.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.4.7                |           py27_0         953 KB

The following packages will be DOWNGRADED:

    conda: 4.5.0rc0-py27_0 --> 4.4.7-py27_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda 4.4.7: ########################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\tester>ONDA_EXE*
'ONDA_EXE*' is not recognized as an internal or external command,
operable program or batch file.
```
![screenshot_944](https://user-images.githubusercontent.com/21064099/37094696-829a77f2-2235-11e8-835f-5931c573db17.png)

**Comment by kalefranz** [comment] 2018-03-07 17:42
I'll bet this issue has the same root cause as https://github.com/conda/conda/issues/6968. I still don't understand it though.

**Comment by mbargull** [comment] 2018-03-13 10:17
Yes, it's the same issue, let's track it there. Duplicate of #6968.

**Closed by mbargull** 2018-03-13 10:17 UTC
