### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by addyblanch** [conda/conda#3165] opened 2016-07-27 14:28 UTC
Hi, I was trying to install QIIME in a conda environment on Ubuntu 14.04 LTS and getting the following:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/adam/Software/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/adam/Software/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/adam/Software/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/adam/Software/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/home/adam/Software/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 431, in install
    print_activate(args.name if args.name else prefix)
  File "/home/adam/Software/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 100, in print_activate
    shell = find_parent_shell(path=False)
  File "/home/adam/Software/miniconda2/lib/python2.7/site-packages/conda/utils.py", line 259, in find_parent_shell
    process = psutil.Process()
TypeError: __init__() takes exactly 2 arguments (1 given)

The output from "conda info" is:

Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.1
  conda-build version : not installed
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /home/adam/Software/miniconda2  (writable)
  default environment : /home/adam/Software/miniconda2
     envs directories : /home/adam/Software/miniconda2/envs
        package cache : /home/adam/Software/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

Any help appreciated

**Comment by HugoTian** [comment] 2016-07-27 15:10
@addyblanch , please try to update psutil. Please run 'conda update psutils'. I think you may be running psutil 1.2.1, and this got updated to 4.3.0

**Comment by addyblanch** [comment] 2016-07-27 15:15
Hi @HugoTian, it is already 4.3.0

Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /home/adam/Software/miniconda2:
#
psutil                    4.3.0                    py27_0

**Comment by HugoTian** [comment] 2016-07-27 16:44
@addyblanch , that's wired, I looked in to the init of Process, and seems process() will work for initialisation. I will try to reproduce this, and fix this one asap

**Comment by HugoTian** [comment] 2016-07-28 15:40
@addyblanch  I tried this on ubuntu VM, and it works fine.

I guess , the problem is related to environment. As you said, "Hi, I was trying to install QIIME in a conda environment on Ubuntu 14.04 L". So I guess this environment is a new env, instead of root conda environment. 

So, just make sure psutil library is 4.3.0 in your environment,(after activate that environment, and run "conda install psutil"). If you still have problem, please let me know

Thanks

**Comment by HugoTian** [comment] 2016-07-28 15:44
Just for reference, below is documentation for psutil 1.2

https://code.google.com/archive/p/psutil/wikis/Documentation.wiki

    psutil.Process(pid)
    A class which represents an OS process. Raises NoSuchProcess if pid does not exist.

Unlike 4.3.0, it will raise a error if you initialize by p = psutil.Process().

That is why I think you are in old version somehow.

Thanks

**Comment by HugoTian** [comment] 2016-07-28 16:16
Actually, we have the psutil issue several times, I think we can change the code to psutil.Process(os.getpid()). In this way, it will work with both version

I will close this issue, and if you still have this problem, please reopen this issue and @ me

**Closed by HugoTian** 2016-07-28 16:16 UTC
