### ISSUE TITLE
Do not modify prompt by default

### ISSUE THREAD

**Issue by olets** [conda/conda#10928] opened 2021-09-19 23:10 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Don't automatically change the terminal prompt on installation.

### Why is this needed

On installing conda, the user's prompt is appended with `(base)\n`.

There is no warning that this will happen, no guarantee that the user (depending on what else they change in their environment) will identify it as a conda-generated change, and no good path to identifying the source (no change to the shell config file, no `~/.condarc` file for those who might think to look for one).

Packages should not modify the user's prompt without consent. Granted I am not in the data science field, maybe it's different in your sphere, but there is no precedent in my experience for a package modifying the prompt.

### What should happen?

From my perspective, needing to know the conda environment at all times is a niche need. It should be offered as a poweruser feature, not a default behavior.

### Additional Context

Related to #8606 but in my opinion even non-default environments should not be added to the prompt by default. Including the option of modifying the prompt may be a nice a feature for some Conda users, but it should be opt-in.

**Comment by ctrueden** [comment] 2021-09-23 18:45
@olets You can disable the prompt changes via:
```
conda config --set changeps1 false
```
And it will add the line:
```
changeps1: false
```
to your `~/.condarc`.

But of course that doesn't address the question of whether the prompt-changing behavior should be enabled versus disabled by default.

**Comment by beeankha** [comment] 2022-08-31 21:04
Changing the prompt to show `(base)` post `conda`/`miniconda` installation is expected behavior; however, I have filed a [new issue](https://github.com/conda/constructor/issues/562) in the `conda/constructor` repository to request the addition of more information regarding this change in the terminal prompt. 

(closing this issue due to the other ticket getting filed)

**Closed by beeankha** 2022-08-31 21:04 UTC
Labels: type::feature, source::community

**Comment by olets** [comment] 2022-09-01 00:59
Out of interest, is this a common behavior in data science tools? I'm used to the model that users who want environment information in their prompt use something like Spaceship Prompt / Starship / powerlevel10k. Not pushing back on your decision just intrigued!

**Comment by kenodegard** [comment] 2022-09-01 02:03
It is expected that the average user of conda does not modify their prompt via spaceship/starship/etc. so the defaults need to be designed to work out of the box on a barebones setup. This is especially true of datacenter & cloud users who may not even have the ability to make significant (permanent) modifications to their shell/prompt.

That being said, this information is very easy to disable either via `changeps1: false` or `auto_activate_base: false`. Since these options are already available it would be straightforward to add prompts/configuration options to the installer that would immediately configure this for the user.
