### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 9: ordinal not in range(128)

### ISSUE THREAD

**Issue by noeliecherrier** [conda/conda#1631] opened 2015-09-21 10:33 UTC
Hello !

I tried to install naima and gammapy using : 
conda config --add channels astropy --add channels sherpa
conda install gammapy naima

Traceback (most recent call last):
  File "C:\Users\NoÙlie\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
    args.func(args, p)
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\cli\install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\plan.py", line 427, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\plan.py", line 242, in ensure_linked_actions
    if install.is_linked(prefix, dist):
  File "C:\Users\NoÙlie\Anaconda\lib\site-packages\conda\install.py", line 492, in is_linked
    meta_path = join(prefix, 'conda-meta', dist + '.json')
  File "C:\Users\NoÙlie\Anaconda\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path

Thanks !

**Comment by asmeurer** [comment] 2015-09-21 19:05
Are you using Python 2 or Python 3? Using conda with Python 2 with non-ASCII characters in your install path is basically not supported (see https://github.com/conda/conda/issues/1180).  You'll either need to change your username, choose a different install location without non-ASCII characters, or install Anaconda3. 

If you are using Python 3 though this is a bug that should be fixed.

**Comment by noeliecherrier** [comment] 2015-09-21 19:22
Thank you very much, i am using Python 2 and my username (Noëlie) raises indeed problem because of the ¨. 

Problem solved, thanks a lot ! 


De: "Aaron Meurer" <notifications@github.com> 
À: "conda/conda" <conda@noreply.github.com> 
Cc: "noeliecherrier" <noelie.cherrier@mines-paristech.fr> 
Envoyé: Lundi 21 Septembre 2015 21:05:35 
Objet: Re: [conda] UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 9: ordinal not in range(128) (#1631) 



Are you using Python 2 or Python 3? Using conda with Python 2 with non-ASCII characters in your install path is basically not supported (see #1180 ). You'll either need to change your username, choose a different install location without non-ASCII characters, or install Anaconda3. 

If you are using Python 3 though this is a bug that should be fixed.

**Comment by asmeurer** [comment] 2015-09-21 19:59
I'm going to close this as a duplicate of #1180.

**Closed by asmeurer** 2015-09-21 19:59 UTC
