### ISSUE TITLE
tensorflow installattion error on conda

### ISSUE THREAD

**Issue by rukshanb4a** [conda/conda#10163] opened 2020-08-15 23:42 UTC
I tried to install TensorFlow in anaconda and this is what happens. What should I do?

<!Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tensorflow -> python[version='3.5.*|3.6.*|3.7.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

**Comment by quantisedboy** [comment] 2020-08-16 22:25
I faced this very issue today, Tensorflow supports python version 3.5,3.6,3.7, you have 3.8 ! 
1. Create a virtual environment with python 3.5 or 3.6 or 3.7, and install tensorflow on it.(I did this and it works)
2. I was reading there's a way to install other versions of python using conda install python (version), you can try that also.
3. Uninstall conda and reinstall a conda version that comes with Python 3.5,3.6 or 3.7. (2019 versions maybe)

**Comment by angloyna** [comment] 2020-08-17 14:14
@quantisedboy good catch, it is an issue with his version of python. We've got plans to work on the messaging of these types of conflicts so that the problem is a little more clear. 

You shouldn't have to go to too much trouble to get to a compatible version of python with our most recent Tensorflow package.

You can run `conda install python=3.7` in the same environment you're attempting to install tensorflow.
If you want to create a new environment with a particular python installed, run `conda create -n new_env python=3.7`

We should have a version of tensorflow for windows using python 3.8 soon as we're planning to build and publish the latest version (v2.3) soon.

**Comment by quantisedboy** [comment] 2020-08-18 06:11
@angloyna Yes, I spent a whole evening trying to find a solution for this and one another problem, the thing is even though TensorFlow installs well in the new environment, matplotlib and seaborn refuses to do so. Always throws an error, some 'conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0',  also I get the same kind of error trying to clone the conda base environment.

**Comment by rukshanb4a** [comment] 2020-08-18 09:14
@quantisedboy Thanks for the clarification and possible options. I really loved to stay with the conda and tried installing previous version but couldn't get it to work.
@angloyna, Thank you that really helped I have successfully installed python 3.7 and then installed TensorFlow without any problem.

**Comment by angloyna** [comment] 2020-08-18 14:20
@quantisedboy is that the other issue you opened this week? we can definitely dig into that there.

For this issue, the solver conflict messaging often isn't clear enough to figure out package is getting pruned to 0 available package versions. It's a very awkward solution, but I usually run `conda install <pkg_name> -vvv` and search the console output for ` -> 0`. This corresponds to a pruning log where conda couldn't find any package versions that satisfy the constraints. We're looking to improve the messaging, but I hope this help you debug if you run into this in the meantime. 

I'll close this ticket but leave the other ticket open so we can debug your second issue when we get a chance, @quantisedboy

**Closed by angloyna** 2020-08-18 14:20 UTC
Labels: source-community, tag-solver_messaging, type-support, waiting-OP_response
