### ISSUE TITLE
when i use the command "conda update anaconda",there is a exception.

### ISSUE THREAD

**Issue by GuanglinZhou** [conda/conda#6114] opened 2017-10-09 01:38 UTC
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/guanglinzhou/anaconda  (writable)
    default environment : /Users/guanglinzhou/anaconda
       envs directories : /Users/guanglinzhou/anaconda/envs
          package cache : /Users/guanglinzhou/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/guanglinzhou/anaconda/bin/conda update anaconda`

    Traceback (most recent call last):
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/guanglinzhou/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 137, in fetch_repodata
        .format(url, filename, e))
    CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2: Failed to parse: :::8787

**Comment by joshij1979** [comment] 2017-10-09 05:05
Error on updating conda 

conda update --all

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /home/joshij/anaconda3  (writable)
    default environment : /home/joshij/anaconda3
       envs directories : /home/joshij/anaconda3/envs
                          /home/joshij/.conda/envs
          package cache : /home/joshij/anaconda3/pkgs
                          /home/joshij/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Linux/4.4.0-96-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/joshij/anaconda3/bin/conda update pandas`




    Traceback (most recent call last):
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/joshij/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080114.791 for timestamp

**Comment by nehaljwani** [comment] 2017-10-09 05:07
@joshij1979 Your issue is related to #6096 . For you, the solution is to find out the files with timestamp in decimals and delete them:
```
grep -l '"timestamp": [0-9]\+\.'  /home/joshij/anaconda3/conda-meta/*.json | xargs rm -f
```

**Comment by joshij1979** [comment] 2017-10-09 05:14
Hello Nehal,

Thanks a ton !! it worked. Just out of curiosity could you please help me
understanding why was it throwing the error.

**Comment by nehaljwani** [comment] 2017-10-09 06:31
@joshij1979 Those files were created by conda 4.3.28, which has a bug in division operator.

**Comment by msarahan** [comment] 2017-10-09 13:11
Closing as duplicate of #6096

**Closed by msarahan** 2017-10-09 13:11 UTC
