### ISSUE TITLE
Cannot "conda update anaconda"

### ISSUE THREAD

**Issue by chipaudette** [conda/conda#1511] opened 2015-08-10 02:18 UTC
I use conda via the anaconda distribution.  After doing a full `conda update anaconda` from my win7 command line, I issued the command again to confirm that everything was up to date.  When I issued `conda update anaconda`, I got the error below.  Note that I get the same error if I just do a `conda update conda`.

```
Fetching package metadata: ...An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 255, in install
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 256, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 397, in result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 356, in __get_result
    raise self._exception
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found
```

This error suggests that I include `conda info`, so here is its output:

```
Current conda install:

             platform : win-64
        conda version : 3.15.1
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Am I stuck with an un-upgradeable conda/anaconda forever?

**Comment by asmeurer** [comment] 2015-08-10 19:43
Run `conda update requests`. 

Closing as a duplicate of https://github.com/conda/conda/issues/1261.

**Closed by asmeurer** 2015-08-10 19:43 UTC
