### ISSUE TITLE
Include deactivate option into --help command

### ISSUE THREAD

**Issue by santiagotoscanini** [conda/conda#10801] opened 2021-07-19 15:46 UTC
Conda version: `4.9.2`
Running `conda --help` shows:
```
usage: conda [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    clean        Remove unused packages and caches.
    compare      Compare packages between conda environments.
    config       Modify configuration values in .condarc. This is modeled after the git config command. Writes to the user .condarc file (/Users/stoscanini/.condarc) by default.
    create       Create a new conda environment from a list of specified packages.
    help         Displays a list of available conda commands and their help strings.
    info         Display information about current conda install.
    init         Initialize conda for shell interaction. [Experimental]
    install      Installs a list of packages into a specified conda environment.
    list         List linked packages in a conda environment.
    package      Low-level conda package utility. (EXPERIMENTAL)
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove.
    run          Run an executable in a conda environment. [Experimental]
    search       Search for packages and display associated information. The input is a MatchSpec, a query language for conda packages. See examples below.
    update       Updates conda packages to the latest compatible version.
    upgrade      Alias for conda update.

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.

conda commands available from other packages:
  env
```

There's no clue that `conda deactivate` deactivate the active environment.

**Comment by kenodegard** [comment] 2022-03-10 20:40
Duplicate of https://github.com/conda/conda/issues/6353

**Closed by kenodegard** 2022-03-10 20:40 UTC
Labels: duplicate
