### ISSUE TITLE
Incomplete package installation with 4.3.x

### ISSUE THREAD

**Issue by msarahan** [conda/conda#4374] opened 2017-01-19 02:03 UTC
Originally posted at https://github.com/ContinuumIO/anaconda-issues/issues/1372

This is with conda 4.3.x current branch. This installation works with current 4.2.x branch.

```
 msarahan@0109-msarahan-2  ~  conda update numpy
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/msarahan/miniconda2:

The following packages will be UPDATED:

    mkl:   11.3.3-0      --> 2017.0.1-0
    numpy: 1.11.1-py27_0 --> 1.11.3-py27_0

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'defaults::mkl-2017.0.1-0'.
CondaError: Cannot link a source that does not exist. /Users/msarahan/miniconda2/pkgs/mkl-2017.0.1-0/lib/libmkl_core.dylib

Attempting to roll back.



CondaError: Cannot link a source that does not exist. /Users/msarahan/miniconda2/pkgs/mkl-2017.0.1-0/lib/libmkl_core.dylib
```

**Comment by msarahan** [comment] 2017-01-19 02:05
And of course, this works for me now...  I guess let's leave this open for a little while to see if anyone else runs across this issue.

**Comment by kalefranz** [comment] 2017-01-19 06:58
That's frustrating.  Yeah let's leave it open for a while.

**Comment by BeniaminK** [comment] 2017-01-19 23:41
Same problem here. I removed the mkl package and tried to install it again, but it fails to install now.

**Comment by willigott** [comment] 2017-01-21 00:21
I run into the same issue; I use Anaconda2-4.2.0-Linux-x86_64.sh

I receive the error:

```
conda install -c bgoli cbmpy
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment path/to/anaconda2:

The following NEW packages will be INSTALLED:

    cbmpy: 0.7.10-py27_1 bgoli
    suds:  0.4-py27_0    bgoli

Proceed ([y]/n)? 

cbmpy-0.7.10-p 100% |######################################################################################################| Time: 0:00:01   1.46 MB/s
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'bgoli::cbmpy-0.7.10-py27_1'.
CondaError: Cannot link a source that does not exist. path/to/anaconda2/pkgs/cbmpy-0.7.10-py27_1/Lib/site-packages/cbmpy-0.7.10.r547-py2.7.egg-info

Attempting to roll back.

CondaError: Cannot link a source that does not exist. path/to/anaconda2/pkgs/cbmpy-0.7.10-py27_1/Lib/site-packages/cbmpy-0.7.10.r547-py2.7.egg-info
```

How could this be fixed? Deleting the temporary files in the folder `pkgs` folder did not help.

**Comment by kalefranz** [comment] 2017-01-24 08:54
@willigott Did you get your problem resolved?

I checked the package at https://anaconda.org/bgoli/cbmpy/0.7.10/download/win-64/cbmpy-0.7.10-py27_1.tar.bz2, and it looks ok.

What looks weird to me in that output is `path/to/anaconda2`.  Did you actually create an environment with that?

If you need further help, let's start with the output of `conda info --all` for you.

**Comment by willigott** [comment] 2017-01-24 14:27
@kalefranz Thanks for your reply!

The `path/to/anaconda2` part was changed by me; the actual one is the typical `/home/willi/...`.

No, the problem is not resolved. It actually became even worse. On another computer (where I used `Anaconda-2.2.0-Linux-x86_64.sh`), I just tried to update cbmpy (the installation itself which I did a few weeks ago worked perfectly) using

`conda update -c bgoli cbmpy`

That yields the following output:

```
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/willi/anaconda:

The following packages will be UPDATED:

    cbmpy: 0.7.10-py27_1 bgoli --> 0.7.11-py27_1 bgoli
    conda: 4.3.5-py27_0        --> 4.3.7-py27_0       

Proceed ([y]/n)? 

conda-4.3.7-py 100% |################################| Time: 0:00:00  13.18 MB/s
cbmpy-0.7.11-p 100% |################################| Time: 0:00:02 813.25 kB/s
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'bgoli::cbmpy-0.7.11-py27_1'.
CondaError: Cannot link a source that does not exist. /home/willi/anaconda/pkgs/cbmpy-0.7.11-py27_1/Lib/site-packages/cbmpy-0.7.11-py2.7.egg-info

Attempting to roll back.



CondaError: Cannot link a source that does not exist. /home/willi/anaconda/pkgs/cbmpy-0.7.11-py27_1/Lib/site-packages/cbmpy-0.7.11-py2.7.egg-info
```
The command 
`conda info --all`

gives the following output:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : 1.11.0
         python version : 2.7.11.final.0
       requests version : 2.12.4
       root environment : /home/willi/anaconda  (writable)
    default environment : /home/willi/anaconda
       envs directories : /home/willi/anaconda/envs
          package cache : /home/willi/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/2.7.11 Linux/3.16.0-70-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000

# conda environments:
#
root                  *  /home/willi/anaconda

sys.version: 2.7.11 |Anaconda 2.2.0 (64-bit)| (defaul...
sys.prefix: /home/willi/anaconda
sys.executable: /home/willi/anaconda/bin/python
conda location: /home/willi/anaconda/lib/python2.7/site-packages/conda
conda-build: /home/willi/anaconda/bin/conda-build
conda-convert: /home/willi/anaconda/bin/conda-convert
conda-develop: /home/willi/anaconda/bin/conda-develop
conda-env: /home/willi/anaconda/bin/conda-env
conda-index: /home/willi/anaconda/bin/conda-index
conda-inspect: /home/willi/anaconda/bin/conda-inspect
conda-metapackage: /home/willi/anaconda/bin/conda-metapackage
conda-pipbuild: /home/willi/anaconda/bin/conda-pipbuild
conda-server: /home/willi/anaconda/bin/conda-server
conda-skeleton: /home/willi/anaconda/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: /opt/gurobi605/linux64/lib:/opt/gurobi605/linux64/lib
PATH: /home/willi/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/gurobi605/linux64/bin
PYTHONHOME: <not set>
PYTHONPATH: /opt/ibm/ILOG/CPLEX_Studio126/cplex/python/x86-64_linux:

License directories:
    /home/willi/.continuum
    /home/willi/anaconda/licenses
License files (license*.txt):
Package/feature end dates:
```
Any ideas what is going on?

**Comment by kalefranz** [comment] 2017-01-24 15:57
The package is at:
https://anaconda.org/bgoli/cbmpy/0.7.11/download/linux-64/cbmpy-0.7.11-py27_1.tar.bz2
or
https://conda.anaconda.org/bgoli/linux-64/cbmpy-0.7.11-py27_1.tar.bz2

The path being complained about is:

    /home/willi/anaconda/pkgs/cbmpy-0.7.11-py27_1/Lib/site-packages/cbmpy-0.7.11-py2.7.egg-info

After conda downloads and unpackages the file, you'll find it in your cache at 

    /home/willi/anaconda/pkgs/cbmpy-0.7.11-py27_1/lib/python2.7/site-packages/cbmpy-0.7.11-py2.7.egg-info

The reason conda thinks the file is at

    Lib/site-packages/cbmpy-0.7.11-py2.7.egg-info

instead of 

    lib/python2.7/site-packages/cbmpy-0.7.11-py2.7.egg-info

is because of what's listed in the `info/paths.json` file.  Note that this *doesn't* match what's in the `info/files` file, which is the older version of the package manifest.

So the package as it exists right now has problems.  It's possible that if you rebuild it with conda-build 2.1.2 (it was built with conda-build 2.1.1), that we've already fixed the bug and it will work fine.

If 2.1.2 fixes it, that's great and I can move on.  If it doesn't, then this is a serious bug (unfortunately in conda-build) that we need to fix quickly.

If 2.1.2 doesn't fix the problem, can you give some additional information on how you're building the package?  What OS are you running during the package build?  etc

**Comment by mingwandroid** [comment] 2017-01-24 16:04
The difference between those paths is that one is a Windows path and the other a Unix path, so that points to `conda convert` doesn't it?

**Comment by dkoppstein** [comment] 2017-01-24 17:40
I ran into a similar error with another package on conda 4.3.7:

```
ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'conda-forge::widgetsnbextension-1.2.6-py34_3'.
LinkError: Link error: Error: post-link failed for: conda-forge::widgetsnbextension-1.2.6-py34_3

Attempting to roll back.



LinkError: Link error: Error: post-link failed for: conda-forge::widgetsnbextension-1.2.6-py34_3
```

Rolling back to conda 4.0.5 fixed it for me; that's the last stable release that consistently works in my hands (since I have been limited by #4346 which was only fixed in 4.3.7).

**Comment by willigott** [comment] 2017-01-24 20:40
@kalefranz Thanks again for your detailed reply.

The errors I reported are from Ubuntu 16.04 and 14.04, respectively.

I now removed anaconda completely and installed it again using `Anaconda2-4.2.0-Linux-x86_64.sh` which I just downloaded. For some reason, the installation now works as expected. When I run 

`conda install -c bgoli -c sbmlteam cbmpy`

I now get the following output:

```
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/willi/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    python-libsbml-5.13.0      |           py27_0        21.8 MB  sbmlteam
    requests-2.12.4            |           py27_0         762 KB
    suds-0.4                   |           py27_0         344 KB  bgoli
    wxpython-3.0.0.0           |           py27_2        31.6 MB
    biopython-1.68             |      np111py27_0         2.2 MB
    pyopenssl-16.2.0           |           py27_0          68 KB
    conda-4.3.7                |           py27_0         468 KB
    cbmpy-0.7.11               |           py27_1         1.8 MB  bgoli
    ------------------------------------------------------------
                                           Total:        59.0 MB

The following NEW packages will be INSTALLED:

    biopython:      1.68-np111py27_0         
    cbmpy:          0.7.11-py27_1    bgoli   
    conda-env:      2.6.0-0                  
    python-libsbml: 5.13.0-py27_0    sbmlteam
    suds:           0.4-py27_0       bgoli   
    wxpython:       3.0.0.0-py27_2           

The following packages will be UPDATED:

    conda:          4.2.9-py27_0              --> 4.3.7-py27_0 
    pyopenssl:      16.0.0-py27_0             --> 16.2.0-py27_0
    requests:       2.11.1-py27_0             --> 2.12.4-py27_0

Proceed ([y]/n)? 

Fetching packages ...
conda-env-2.6. 100% |######################################################################################################| Time: 0:00:00 256.52 kB/s
python-libsbml 100% |######################################################################################################| Time: 0:00:22   1.00 MB/s
requests-2.12. 100% |######################################################################################################| Time: 0:00:00   2.65 MB/s
suds-0.4-py27_ 100% |######################################################################################################| Time: 0:00:00 573.32 kB/s
wxpython-3.0.0 100% |######################################################################################################| Time: 0:00:13   2.37 MB/s
biopython-1.68 100% |######################################################################################################| Time: 0:00:01   2.08 MB/s
pyopenssl-16.2 100% |######################################################################################################| Time: 0:00:00   2.15 MB/s
conda-4.3.7-py 100% |######################################################################################################| Time: 0:00:00   2.80 MB/s
cbmpy-0.7.11-p 100% |######################################################################################################| Time: 0:00:01   1.12 MB/s
Extracting packages ...
[      COMPLETE      ]|#########################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#########################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#########################################################################################################################| 100%
```

I have no idea why it now works and failed yesterday; all I did was to remove anaconda and reinstalled it. But yesterday it would have installed 

`cbmpy: 0.7.10-py27_1 bgoli`

while today the version is 

`cbmpy:          0.7.11-py27_1    bgoli `

So something could have changed in the package itself.

I will try tomorrow on the ubuntu 14.04 machine and check whether it works there as well now; I will then check the things you suggested above.

**Comment by kalefranz** [comment] 2017-01-24 21:30
Thanks for the extra info @willigott.  Keep us updated :)

**Comment by kalefranz** [comment] 2017-01-24 21:34
@dkoppstein Your issues is different than what was originally filed.  If we need to discuss further, please file a new report.

The https://conda.anaconda.org/conda-forge/linux-64/widgetsnbextension-1.2.6-py34_3.tar.bz2 contains a post-link script that is exiting with a non-zero return code.  There is no messaging output given by the script.  It is an issue you should consider filing with conda-forge.

Conda 4.0 continued with certain failure conditions, even though it's unsafe to do so.  When unspecified failures occur in conda 4.3, such as something with a post-link script, we roll back to the previous state so that we don't mess up your environment in unpredictable ways.

**Comment by dkoppstein** [comment] 2017-01-24 22:44
@kalefranz thanks for the clarification, I've lodged a separate issue with conda-forge as you suggested.

**Comment by bgoli** [comment] 2017-01-24 22:59
Hi I'm the cbmpy developer, thanks for all the effort wrt to this problem.

The cbmpy version that  @willigott was trying to install was built on win-64 after which I did a "convert" for the cross-platform builds. 

What I have subsequently done is tried to build (using 2.1.1) on both win-64 (cbmpy-0.7.11-py27_5.tar.bz)" and linux-64 (cbmpy-0.7.11-py27_6.tar.bz2) run convert and and looked at the paths.json produced for both win-64 and linux-64 targets:

**win-64 build --> linux-64 target** 
    {
      "_path": "Lib/site-packages/cbmpy-0.7.11-py2.7.egg-info",
    },

**linux-64 build --> linux-64 target** 
    {
      "_path": "lib/python2.7/site-packages/cbmpy-0.7.11-py2.7.egg-info",
    },

**win-64 build --> win-64 target**
    {
      "_path": "Lib/site-packages/cbmpy-0.7.11-py2.7.egg-info",
    },

**linux-64 build -->win-64 target** 
    {
      "_path": "lib/python2.7/site-packages/cbmpy-0.7.11-py2.7.egg-info",
    },

In both cases the "cross-compiled" paths in path.json are not converted to the target OS, is this expected behaviour? What is interesting is that in all cases the "info/files" has the corrected "target" paths.

**Comment by kalefranz** [comment] 2017-01-24 23:32
We just have a bug in `conda convert` where we need to add extra logic to support the new paths.json file. I'm on a cell phone right now or I'd create a conda-build rocket to track it.

**Comment by msarahan** [comment] 2017-01-25 01:37
There is already an issue for ``conda convert`` at https://github.com/conda/conda-build/issues/1678

**Comment by kalefranz** [comment] 2017-04-21 16:29
This has been fixed via #4789 and/or #5098.

**Closed by kalefranz** 2017-04-21 16:29 UTC
Labels: source:core, type:bug

**Comment by megamindbrian** [comment] 2017-07-21 19:24
Still not fixed:
```
(py36) C:\Users\brian.cullinan\Documents\jupytangular2>conda install -f -c conda-forge jupyterlab
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\ProgramData\Anaconda3\envs\py36:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jupyterlab-0.25.2          |           py36_0         3.2 MB  conda-forge

The following NEW packages will be INSTALLED:

    jupyterlab: 0.25.2-py36_0 conda-forge

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
jupyterlab-0.2 100% |###############################| Time: 0:00:01   3.11 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[jupyterlab          ]|                                                  |   0%

LinkError: Link error: Error: post-link failed for: conda-forge::jupyterlab-0.25.2-py36_0

```

**Comment by denfromufa** [comment] 2017-10-22 20:07
I'm getting this issue on Windows 10 with nbgrader installation:
 
```
C:\Users\denis>conda install -c conda-forge nbgrader
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Python\Anaconda3_64b:

The following NEW packages will be INSTALLED:

    alembic:       0.9.6-py_0            conda-forge
    mako:          1.0.7-py35_0          conda-forge
    nbgrader:      0.5.3-py35_0          conda-forge
    python-editor: 1.0.3-py35_0          conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:         4.3.30-py35hec795fb_0             --> 4.3.29-py35_0 conda-forge

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::alembic-0.9.6-py_0'.
CondaError: Cannot link a source that does not exist. C:\Python\Anaconda3_64b\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.


CondaError: Cannot link a source that does not exist. C:\Python\Anaconda3_64b\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.

```


```
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 2.0.2
         python version : 3.5.3.final.0
       requests version : 2.12.4
       root environment : C:\Python\Anaconda3_64b  (writable)
    default environment : C:\Python\Anaconda3_64b
       envs directories : C:\Python\Anaconda3_64b\envs
                          C:\Users\denis\AppData\Local\conda\conda\envs
                          C:\Users\denis\.conda\envs
          package cache : C:\Python\Anaconda3_64b\pkgs
                          C:\Users\denis\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.12.4 CPython/3.5.3 Windows/10 Windows/10.0.16299
          administrator : False
```

**Comment by SylvainCorlay** [comment] 2018-01-29 15:56
It does not seem to be fixed. I am getting this error as well with the latest miniconda.

**Comment by SylvainCorlay** [comment] 2018-01-29 16:03
It seems to be an issue with noarch package. Updating conda to 4.4 fixes the issue.

**Comment by OnlyBelter** [comment] 2018-02-23 06:35
Updating conda to 4.3.34 fixed this problem, see here https://github.com/jupyterhub/jupyterhub-tutorial/issues/21
