### ISSUE TITLE
Conda doesn't show progress bar and text (copy)

### ISSUE THREAD

**Issue by AndreWin** [conda/conda#4938] opened 2017-03-25 07:30 UTC
Hello!

I have conda 4.3.15 on Windows 8.1x64 (Russian interface). I have installed miniconda recently, then have added conda-canary channel and have updated conda.

When I create new environment with conda, for example:

```
conda create -p E:\Jupyter\dist\pyenv3.6-win64 --copy python=3 numpy scipy matplotlib jupyter
```

I don't see text `(copy)` in list of packages that will be installed. So I'm not sure if I will get copy of packages unstead of shortcuts.  Also I see only progressbar of packages downloading. But when packages are installing I see nothing.

Is there any fix or workarrond?

Best regards, Andrey.

**Comment by kalefranz** [comment] 2017-05-08 15:17
Duplicate of #5242

**Closed by kalefranz** 2017-05-08 15:17 UTC
