### ISSUE TITLE
conda fails to create env using local file channel, maximum recursion depth exceeded

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#2371] opened 2016-04-18 19:12 UTC
I need to configure conda to run with a local channel only.  No Anaconda Repo channels.
Our JPM client requires the default install to only point to a local repo.
conda fails to create envs with the local repo channel.

**Steps to reproduce:**

1. Install Anaconda
1. Copy pkgs/*.bz2 files to a directory - /tmp/localrepo/osx-64
1. Index the repo directory - conda index /tmp/localrepo/osx-64
1. Add the local repo channel to conda config 
1. Try to create an env (see error message below).

**conda info**
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /tmp/anaconda  (writable)
  default environment : /tmp/anaconda
     envs directories : /tmp/anaconda/envs
        package cache : /tmp/anaconda/pkgs
         channel URLs : file:///tmp/localrepo/osx-64/
                        file:///tmp/localrepo/noarch/
          config file : /Users/jhull/.condarc
    is foreign system : False

**~/.condarc**
cat ~/.condarc
channels:
  - file:///tmp/localrepo

**Create env command**
conda create -n test python pip

**Error message**
 File "/tmp/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 287, in v_
    return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fn_(spec)
  File "/tmp/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 290, in v_ms_
    return ms.optional or any(v_fn_(fn) for fn in self.find_matches(ms))
  File "/tmp/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 554, in find_matches
    res = self.find_matches_.get(ms, None)
  File "/tmp/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 151, in __eq__
    return type(other) is MatchSpec and self.spec == other.spec
RuntimeError: **maximum recursion depth exceeded **while calling a Python object

**Comment by kalefranz** [comment] 2016-04-18 19:48
Confirm I am able to reproduce.  Here's the debug output

    kfranz@0283:~/continuum/conda *4.0.x ❯ conda --debug create -n test5 python
    DEBUG:binstar:Found login token: /Users/kfranz/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token
    DEBUG:conda.fetch:channel_urls=('file:///tmp/localrepo/osx-64/', 'file:///tmp/localrepo/noarch/')
    Fetching package metadata: INFO:stdoutlog:Fetching package metadata:
    DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
    .DEBUG:dotupdate:fetching repodata: args ('file:///tmp/localrepo/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1041e1b10>}
    .DEBUG:dotupdate:fetching repodata: args ('file:///tmp/localrepo/osx-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1041e1b10>}

    INFO:stdoutlog:

    DEBUG:conda.plan:Pinned specs=[]
    DEBUG:conda.plan:H0 specs=['python']
    DEBUG:conda.plan:H2 python False
    DEBUG:conda.plan:H2 lua False
    DEBUG:conda.plan:H2A lua
    DEBUG:conda.plan:HF specs=['python', 'python 2.7*']
    DEBUG:conda.resolve:Checking satisfiability of current install
    DEBUG:conda.resolve:Checking if the current environment is consistent
    Solving package specifications: INFO:stdoutlog:Solving package specifications:
    .DEBUG:dotupdate:Solving for [MatchSpec('python'), MatchSpec('python 2.7*')]
    DEBUG:conda.resolve:Retrieving packages for: [MatchSpec('python'), MatchSpec('python 2.7*')]

    INFO:stdoutlog:

    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda/issues

    Include the output of the command 'conda info' in your report.


    Traceback (most recent call last):
      File "/conda/bin/conda", line 6, in <module>
        sys.exit(main())
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/cli/main.py", line 139, in main
        args_func(args, p)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/cli/main.py", line 146, in args_func
        args.func(args, p)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/cli/main_create.py", line 49, in execute
        install.install(args, parser, 'create')
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/cli/install.py", line 334, in install
        update_deps=args.update_deps)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/plan.py", line 413, in install_actions
        pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 875, in install
        pkgs = self.solve(specs, len0=len0, returnall=returnall)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 909, in solve
        dists, new_specs = self.get_dists(specs)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 399, in get_dists
        specs, removes, optional, features = self.verify_specs(specs)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 391, in verify_specs
        bad_deps.extend(self.invalid_chains(ms, filter))
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 359, in invalid_chains
        return chains_(spec)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 357, in chains_
        notfound.update(chains_(m2))
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 357, in chains_
        notfound.update(chains_(m2))
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 357, in chains_
        notfound.update(chains_(m2))
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 357, in chains_
        notfound.update(chains_(m2))

    ...

      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 351, in chains_
        if spec.name == top or self.valid(spec, filter):
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 299, in valid
        return v_(spec)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 287, in v_
        return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fn_(spec)
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 290, in v_ms_
        return ms.optional or any(v_fn_(fn) for fn in self.find_matches(ms))
      File "/conda/lib/python2.7/site-packages/conda-4.0.5.dev6+ga66597c-py2.7.egg/conda/resolve.py", line 554, in find_matches
        res = self.find_matches_.get(ms, None)
    RuntimeError: maximum recursion depth exceeded

**Comment by kalefranz** [comment] 2016-04-18 19:58
@mcg1969 will be digging in soon...

**Comment by mcg1969** [comment] 2016-04-18 20:44
Quick fix: change line 357 of conda/resolve.py from
```
                    notfound.update(chains_(m2))
```
to
```
                    notfound.update(chains_(m2, top or spec.name))
```
However, when I do `conda create -n testA python pip` I get this:
```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..
Solving package specifications: .
Error:  Dependencies missing in current osx-64 channels: 
  - python -> openssl 1.0.2d
  - python -> pip -> wheel
  - python -> pip -> setuptools
  - pip -> python 2.7* -> openssl 1.0.2d
  - pip -> python 3.4* -> openssl 1.0.2d
  - pip -> wheel -> python 3.4* -> openssl 1.0.2d
  - pip -> setuptools -> python 3.4* -> openssl 1.0.2d
  - pip -> setuptools -> python 2.7* -> openssl 1.0.2d
  - pip -> wheel -> python 2.7* -> openssl 1.0.2d
  - python 2.7* -> openssl 1.0.2d
  - python 2.7* -> pip -> wheel
  - python 2.7* -> pip -> setuptools

Did you mean one of these?

    wheel

Did you mean one of these?

    setuptools

You can search for this package on anaconda.org with

    anaconda search -t conda setuptools

 (and similarly for the other packages)
```
So for some reason it doesn't think I have a valid set of packages in the repo. I'll investigate.

**Comment by mcg1969** [comment] 2016-04-18 20:55
OK, here's the problem I'm seeing. According to the `conda index` output in repodata.json, python depends on `openssl 1.0.2d`. However, according to the `repodata.json` file hosted on repo.continuum.io, it now depends on `openssl 1.0.2g`. This is a "hot fix" that has been inserted into the repodata without rebuilding the packages.

The problem, of course, is that `conda index` doesn't know that the hosted repodata has been changed, so it is using the old version: and the package cache does not contain the packages needed.

**Comment by mcg1969** [comment] 2016-04-18 21:04
@joelhullcio, even with the recursion bug fixed, you're not going to be able to build a local repository in the manner you're seeking. This is because you need the updated package metadata that exists on repo.continuum.io; the data contained in the `.tar.bz2` files themselves is out of date. We've been making adjustments to the metadata like this for some time, and it certainly is nice not having to rebuild packages just to make changes to the metadata; but this is an instance where it causes a failure.

What I think we would need to do is instead of doing `conda index`, we build a short script that pulls down the `repodata.json` file from continuum.io, filter out those packages that are present in the local cache, and write out that filtered version of `repodata.json`. Arguably, this capability could and should be built into `conda index`.

**Comment by kalefranz** [comment] 2016-04-18 21:07
@csoja Can you add a discussion item for our next Thursday weekly about this issue and `conda index`?

**Comment by mcg1969** [comment] 2016-04-18 21:12
@kalefranz I'll leave it to you to decide whether this is worth the hotfix on 4.0.x. That one line above will do it, even though it results in messy-looking hints.

**Comment by joelhullcio** [comment] 2016-04-18 21:14
@mcg1969 thanks for finding the issue quickly!  Is there a way we can resolve this without requiring a trip to the Internet (repo.continuum.io).  The JPM requirement is for the Anaconda installer to be stand-alone and not require an external repo (breach the firewall).  Perhaps this could be resolved during the installer build process in constructor?  Could constructor add the extra meta data needed in the installer for conda index to find locally?  Would it help if I downgrade openssl to 1.0.2d in the installer?

**Comment by mcg1969** [comment] 2016-04-18 21:37
Yes, if your objective is to build a standalone installer, that's what you should do, and this is not the way to do it... our constructor project is the best start.

**Comment by mcg1969** [comment] 2016-04-18 21:38
Of course, if constructor is part of the problem here, you should file an issue over there. But I'm thinking that it ought to be using the latest metadata when building the installer. Whether it does or not I'm not sure.

**Comment by joelhullcio** [comment] 2016-04-18 21:50
Because I am using a hybrid of Anaconda 2.5 and Anaconda 4.0 packages in my custom installer I was able to downgrade the openssl package to version 1.0.2d in the installer and now conda is happy.  No more recursion error!!  This gives me a path forward until conda index can be updated to use the latest version of openssl.  Thanks guys!!

**Comment by kalefranz** [comment] 2016-04-19 03:30
@joelhullcio You've exposed an issue here with `conda index` that I don't think we were aware of before.  It may be some time before we come up with a solution, but I've added it to our agenda to discuss at our weekly Thursday meeting.

**Comment by kalefranz** [comment] 2016-04-19 04:09
I'm going to close this issue, because I don't think it's exactly a bug with `conda index`.  Like I said though, it'll be discussed on Thursday.

**Closed by kalefranz** 2016-04-19 04:09 UTC
