### ISSUE TITLE
Requests throwing InsecurePlatformWarning

### ISSUE THREAD

**Issue by H0R5E** [conda/conda#1204] opened 2015-03-18 09:45 UTC
Hi,

I recently updated conda and now I am getting a warning that I don't understand like this:

```
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79:
InsecurePlatformWarning: A true SSLContext object is not available.
This prevents urllib3 from configuring SSL appropriately and may
cause certain SSL connections to fail. For more information, see
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

This is conda info:

```
Current conda install:

             platform : win-32
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.7.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://conda.binstar.org/topper/win-32/
                        https://conda.binstar.org/topper/noarch/
                        https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : D:\Users\108630\.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment] 2015-03-18 17:07
What version of Windows is this?

**Comment by asmeurer** [comment] 2015-03-18 17:09
Never mind, I can reproduce this. It comes from having a Python version lower than 2.7.9.

**Comment by rbuckley-nv** [comment] 2015-03-18 17:09
Windows 7

Sent from my iPhone

On 18 Mar 2015, at 17:08, Aaron Meurer <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of Windows is this?

-
Reply to this email directly or view it on GitHub<https://github.com/conda/conda/issues/1204#issuecomment-83059736>.

-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Comment by asmeurer** [comment] 2015-03-18 17:10
@ilanschnell what do you think we should do about this? See https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning for more information.

**Comment by ilanschnell** [comment] 2015-03-18 17:16
I think we should make 'http://repo.continuum.io/' the default channels again.  There have just been too many problems with https.

**Comment by asmeurer** [comment] 2015-03-18 17:17
I can confirm that installing the three packages suggested at https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl makes the warnings go away (I had to build ndg-httpsclient). I would suggest making the Python 2 version of requests depend on these libraries on Windows.

**Comment by asmeurer** [comment] 2015-03-18 17:17
> I think we should make 'http://repo.continuum.io/' the default channels again. There have just been too many problems with https.

-1

**Comment by ThomasLecocq** [comment] 2015-03-20 10:53
Well, part of the problem comes that ``conda update python``  on windows doesn't up to 2.7.9 ...

**Comment by asmeurer** [comment] 2015-03-20 16:56
That's true. If we can get https://github.com/conda/conda/pull/1133 working, this would become a non-issue.

**Comment by adamklein** [comment] 2015-03-25 16:29
I am also bitten by `conda update python` not bringing 2.7.8 up to 2.7.9. :/

**Comment by babykiss4ever** [comment] 2015-03-30 17:08
@asmeurer 
Thanks for your advice. It resolves the problem by using easy_install to install those packages.

PIP WON'T WORK because my username is not an ASCII string.

**Comment by asmeurer** [comment] 2015-03-30 20:05
If your username is not ASCII, I really recommend just using Python 3.

**Comment by stefangeorge** [comment] 2015-03-31 13:06
so how does one update python to 2.7.9 in anaconda?
or should i also install active state python??

**Comment by asmeurer** [comment] 2015-03-31 15:17
We are working on a way to update Python on the root environment. For now, the only way is to create a new environment with conda, or else reinstall Anaconda (Anaconda 2.2, which will be released later this week, will have 2.7.9).

**Comment by Fast4ea** [comment] 2015-07-26 13:01
Sorry if this has already been covered, but I'm getting "insecure platform warning" on every module installing via command "conda update anaconda."  

I have my install directory in a different directory than C: I assume that's no issue?  

My Python version is 2.7.8. Should I just wipe Anaconda and reinstall to update Python, or would "conda update python" fix this? Thanks in advance.

**Comment by asmeurer** [comment] 2015-07-27 18:16
I guess the answer to this wasn't posted here. The solution is to `conda install ndg-httpsclient`. Reinstalling Anaconda would also fix it (although not an ideal solution for many people). A future version of conda will let you update Python, which would also fix this, but it won't work just yet.

**Closed by asmeurer** 2015-07-27 18:16 UTC
