### ISSUE TITLE
Conda update conda : Failure

### ISSUE THREAD

**Issue by paulamma** [conda/conda#4496] opened 2017-02-01 17:45 UTC
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.2
         python version : 3.5.2.final.0
       requests version : 2.12.3
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Anaconda3\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _mai
n
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, i
n execute
        install(args, parser, 'update')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in i
nstall
        prefix=prefix)
      File "C:\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_i
ndex
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listco
mp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_re
sult
        raise self._exception
      File "C:\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_r
epodata
        timeout=(6.1, 60))
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in g
et
        return self.request('GET', url, **kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in r
equest
        resp = self.send(prep, **send_kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in s
end
        r = adapter.send(request, **kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in s
end
        timeout=timeout
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionp
ool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionp
ool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionp
ool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.
py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyo
penssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyo
penssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_clas
s'

(C:\Anaconda3) D:\Users\Administrateur>

**Comment by jakirkham** [comment] 2017-02-25 21:50
Duplicate of issue ( https://github.com/conda/conda/issues/4495 ).

**Comment by kalefranz** [comment] 2017-03-01 22:13
This is a dependency conflict between requests and its sub-dependencies.  Easiest solution is

    conda config --set ssl_verify false
    conda update conda
    conda config --remove-key ssl_verify

**Closed by kalefranz** 2017-03-01 22:13 UTC

**Comment by paulamma** [comment] 2017-03-02 09:24
Thank you for pointing out it was duplicate issue,

kalefranz: Thanks for your advice :)

Have a nice day to all.
