### ISSUE TITLE
Wrong package plan on `conda update --all`

### ISSUE THREAD

**Issue by pitrou** [conda/conda#2713] opened 2016-06-16 09:40 UTC
`conda update --all` proposes unexpected installs and downgrades:
```
$ conda update --all
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications .............

Package plan for installation in environment /home/antoine/35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-7.0            |                1       190.8 MB  numba
    pydbg-1.0                  |                0          676 B  antoine
    xz-5.2.2                   |                0         644 KB
    heapdict-1.0.0             |           py35_1           5 KB
    pip-0.0.1                  |           py35_0          779 B  antoine
    pyyaml-3.11                |           py35_4         326 KB
    toolz-0.8.0                |           py35_0          80 KB
    numexpr-2.6.0              |      np111py35_0         357 KB
    qt-4.8.7                   |                3        34.1 MB
    botocore-1.4.26            |           py35_0         1.8 MB
    pyqt-4.11.4                |           py35_3         3.4 MB
    dask-0.10.0                |           py35_0         552 KB
    ------------------------------------------------------------
                                           Total:       232.0 MB

The following NEW packages will be INSTALLED:

    pydbg:         1.0-0             antoine

The following packages will be UPDATED:

    botocore:      1.4.19-py35_0             --> 1.4.26-py35_0            
    dask:          0.9.0-py35_0              --> 0.10.0-py35_0            
    decorator:     4.0.9-py35_0              --> 4.0.10-py35_0            
    freetype:      2.5.5-0                   --> 2.5.5-1                  
    heapdict:      1.0.0-py35_0              --> 1.0.0-py35_1             
    numexpr:       2.5.2-np111py35_1         --> 2.6.0-np111py35_0        
    openblas:      0.2.14-0                  --> 0.2.14-4                 
    openssl:       1.0.2h-0                  --> 1.0.2h-1                 
    pickleshare:   0.5-py35_0                --> 0.7.2-py35_0             
    ptyprocess:    0.5-py35_0                --> 0.5.1-py35_0             
    pycparser:     2.14-py35_0               --> 2.14-py35_1              
    pyqt:          4.11.4-py35_1             --> 4.11.4-py35_3            
    pyyaml:        3.11-py35_1               --> 3.11-py35_4              
    qt:            4.8.7-1                   --> 4.8.7-3                  
    setuptools:    21.2.1-py35_0             --> 23.0.0-py35_0            
    simplegeneric: 0.8.1-py35_0              --> 0.8.1-py35_1             
    toolz:         0.7.4-py35_0              --> 0.8.0-py35_0             
    xz:            5.0.5-1                   --> 5.2.2-0                  

The following packages will be DOWNGRADED:

    cudatoolkit:   7.5-0                     --> 7.0-1             numba  
    pip:           8.1.1-py35_1              --> 0.0.1-py35_0      antoine
    python:        3.5.1-0                   --> 3.5.0-4_dbg       antoine [pydbg]

Proceed ([y]/n)? n

```

**Comment by pitrou** [comment] 2016-06-16 09:40
This is with conda 4.1.0. conda 4.0.8 is fine.

**Comment by mcg1969** [comment] 2016-06-16 12:09
I will investigate. Can you do `conda list --explicit` for me?

**Comment by mcg1969** [comment] 2016-06-16 12:10
Regardless can you please offer the output of `conda info` as well.

**Comment by mcg1969** [comment] 2016-06-16 12:11
Sorry for the barrage of questions. But why do you have `pip 0.0.1` in your channel?

**Comment by pitrou** [comment] 2016-06-16 12:12
Of course:
```
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/linux-64/backports-1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/bokeh-0.11.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/boto3-1.3.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/botocore-1.4.19-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cffi-1.6.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/chest-0.2.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/click-6.6-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cloudpickle-0.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cudatoolkit-7.5-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cycler-0.10.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cython-0.24-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/dask-0.9.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/decorator-4.0.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/distributed-1.10.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/docutils-0.12-py35_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/fontconfig-2.11.1-5.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/freetype-2.5.5-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/futures-3.0.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/get_terminal_size-1.0.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/heapdict-1.0.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipython-4.2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipython_genutils-0.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jinja2-2.8-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jmespath-0.9.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libffi-3.2.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgfortran-3.0.0-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libpng-1.6.17-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libxml2-2.9.2-0.tar.bz2
https://conda.anaconda.org/numba/linux-64/llvmdev-3.7.1-4.tar.bz2
https://conda.anaconda.org/numba/linux-64/llvmlite-0.11.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/locket-0.2.0-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/markupsafe-0.23-py35_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/matplotlib-1.5.1-np111py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mkl-11.3.3-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/msgpack-python-0.4.6-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/nose-1.3.7-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numexpr-2.5.2-np111py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numpy-1.11.0-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openblas-0.2.14-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.2h-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pandas-0.18.1-np111py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/partd-0.3.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/path.py-8.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pexpect-4.0.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pickleshare-0.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pip-8.1.1-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/psutil-4.2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ptyprocess-0.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pycparser-2.14-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyparsing-2.1.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyqt-4.11.4-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-3.5.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-dateutil-2.5.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pytz-2016.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyyaml-3.11-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/qt-4.8.7-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/readline-6.2-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/requests-2.10.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/s3fs-0.0.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/scipy-0.17.1-np111py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/setuptools-21.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/simplegeneric-0.8.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/singledispatch-3.4.0.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sip-4.16.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/six-1.10.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sqlite-3.13.0-0.tar.bz2
https://conda.anaconda.org/numba/linux-64/system-5.8-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tblib-1.3.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/toolz-0.7.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tornado-4.3-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/traitlets-4.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wheel-0.29.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xz-5.0.5-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/yaml-0.1.6-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.8-3.tar.bz2
```

Also:
```
$ conda config --get channels
--add channels 'defaults'
--add channels 'antoine'
--add channels 'numba'
```

and:
```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.1.0
  conda-build version : 1.21.0
       python version : 3.4.4.final.0
     requests version : 2.10.0
     root environment : /home/antoine/miniconda3  (writable)
  default environment : /home/antoine/35
     envs directories : /home/antoine/miniconda3/envs
        package cache : /home/antoine/miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/numba/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/numba/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/antoine/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/antoine/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/antoine/.condarc
    is foreign system : False
```

**Comment by pitrou** [comment] 2016-06-16 12:14
> Sorry for the barrage of questions. But why do you have pip 0.0.1 in your channel?

That was suggested as a workaround for this issue: https://github.com/conda/conda/issues/1365

**Comment by pitrou** [comment] 2016-06-16 12:16
> What happens if you rearrange your channel list so that antoine is at the end instead of the beginning?

Then the plan is slightly saner, but still proposes a `cudatoolkit` downgrade:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-7.0            |                1       190.8 MB  numba
    heapdict-1.0.0             |           py35_1           5 KB
    pyyaml-3.11                |           py35_4         326 KB
    toolz-0.8.0                |           py35_0          80 KB
    numexpr-2.6.0              |      np111py35_0         357 KB
    qt-4.8.7                   |                3        34.1 MB
    botocore-1.4.26            |           py35_0         1.8 MB
    pyqt-4.11.4                |           py35_3         3.4 MB
    dask-0.10.0                |           py35_0         552 KB
    ------------------------------------------------------------
                                           Total:       231.4 MB

The following packages will be UPDATED:

    botocore:      1.4.19-py35_0     --> 1.4.26-py35_0          
    dask:          0.9.0-py35_0      --> 0.10.0-py35_0          
    decorator:     4.0.9-py35_0      --> 4.0.10-py35_0          
    freetype:      2.5.5-0           --> 2.5.5-1                
    heapdict:      1.0.0-py35_0      --> 1.0.0-py35_1           
    numexpr:       2.5.2-np111py35_1 --> 2.6.0-np111py35_0      
    openblas:      0.2.14-0          --> 0.2.14-4               
    openssl:       1.0.2h-0          --> 1.0.2h-1               
    pickleshare:   0.5-py35_0        --> 0.7.2-py35_0           
    pip:           8.1.1-py35_1      --> 8.1.2-py35_0           
    ptyprocess:    0.5-py35_0        --> 0.5.1-py35_0           
    pycparser:     2.14-py35_0       --> 2.14-py35_1            
    pyqt:          4.11.4-py35_1     --> 4.11.4-py35_3          
    pyyaml:        3.11-py35_1       --> 3.11-py35_4            
    qt:            4.8.7-1           --> 4.8.7-3                
    setuptools:    21.2.1-py35_0     --> 23.0.0-py35_0          
    simplegeneric: 0.8.1-py35_0      --> 0.8.1-py35_1           
    toolz:         0.7.4-py35_0      --> 0.8.0-py35_0           

The following packages will be DOWNGRADED:

    cudatoolkit:   7.5-0             --> 7.0-1             numba
```

**Comment by pitrou** [comment] 2016-06-16 12:30
Note that with `channels_priority: false`, I get a different downgrade:

```
$ conda config --get channels
--add channels 'defaults'
--add channels 'numba'
--add channels 'antoine'
$ conda update --all
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications .............

Package plan for installation in environment /home/antoine/35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    llvmdev-3.7.1              |                2        70.6 MB  antoine
    heapdict-1.0.0             |           py35_1           5 KB
    pyyaml-3.11                |           py35_4         326 KB
    toolz-0.8.0                |           py35_0          80 KB
    numexpr-2.6.0              |      np111py35_0         357 KB
    qt-4.8.7                   |                3        34.1 MB
    botocore-1.4.26            |           py35_0         1.8 MB
    pyqt-4.11.4                |           py35_3         3.4 MB
    dask-0.10.0                |           py35_0         552 KB
    ------------------------------------------------------------
                                           Total:       111.1 MB

The following packages will be UPDATED:

    botocore:      1.4.19-py35_0           --> 1.4.26-py35_0            
    dask:          0.9.0-py35_0            --> 0.10.0-py35_0            
    decorator:     4.0.9-py35_0            --> 4.0.10-py35_0            
    freetype:      2.5.5-0                 --> 2.5.5-1                  
    heapdict:      1.0.0-py35_0            --> 1.0.0-py35_1             
    numexpr:       2.5.2-np111py35_1       --> 2.6.0-np111py35_0        
    openblas:      0.2.14-0                --> 0.2.14-4                 
    openssl:       1.0.2h-0                --> 1.0.2h-1                 
    pickleshare:   0.5-py35_0              --> 0.7.2-py35_0             
    pip:           8.1.1-py35_1            --> 8.1.2-py35_0             
    ptyprocess:    0.5-py35_0              --> 0.5.1-py35_0             
    pycparser:     2.14-py35_0             --> 2.14-py35_1              
    pyqt:          4.11.4-py35_1           --> 4.11.4-py35_3            
    pyyaml:        3.11-py35_1             --> 3.11-py35_4              
    qt:            4.8.7-1                 --> 4.8.7-3                  
    setuptools:    21.2.1-py35_0           --> 23.0.0-py35_0            
    simplegeneric: 0.8.1-py35_0            --> 0.8.1-py35_1             
    toolz:         0.7.4-py35_0            --> 0.8.0-py35_0             

The following packages will be DOWNGRADED:

    llvmdev:       3.7.1-4           numba --> 3.7.1-2           antoine

Proceed ([y]/n)? n
```

**Comment by mcg1969** [comment] 2016-06-16 12:34
OK, these last two "solutions" look sane to me. I'm guessing that there is some sort of severe version/build pinning going on. Yes, downgrades are penalized, but given how many upgrades their are, we'd have to penalize them *a lot* to prevent even one downgrade like that.

Also it looks like there is some serious version/build restriction going on here. Why would `llvmdev-3.7.1-4` not be compatible with the packages installed, but `llvmdev-3.7.1-2` is? Can you look at the dependency information in those two packages and tell me the difference?

**Comment by mcg1969** [comment] 2016-06-16 12:34
Likewise for `cudatoolkit`. What are the differences in the dependencies between 7.5-0 and 7.0-1?

**Comment by mcg1969** [comment] 2016-06-16 12:36
Regarding #1365, that issue is well before the 4.x solver fix. We should probably close that.

**Comment by pitrou** [comment] 2016-06-16 12:36
Here are the requirements for llvmdev:
```
requirements:
  build:
    - cmake
    - system           [linux and not armv7l]
  run:
    - system           [linux and not armv7l]
```

I don't think `cudatoolkit` has any particular dependencies, it just bundles proprietary software from NVidia.

**Comment by mcg1969** [comment] 2016-06-16 12:38
Can you past the text of your `.condarc` for these last two cases?

**Comment by pitrou** [comment] 2016-06-16 12:39
Expanded information about `llvmdev` (from `conda info`):

```
llvmdev 3.7.1 2
---------------
file name   : antoine::llvmdev-3.7.1-2.tar.bz2
name        : llvmdev
version     : 3.7.1
build number: 2
build string: 2
channel     : antoine/linux-64
size        : 70.6 MB
arch        : x86_64
binstar     : {'owner_id': '53f3b8f25e7683090df1f2fd', 'channel': 'main', 'package_id': '545b5c985e768304c69ad130'}
fn          : llvmdev-3.7.1-2.tar.bz2
license     : Open Source (http://llvm.org/releases/3.7.0/LICENSE.TXT)
machine     : x86_64
md5         : 3160d70a68ff8ef4453405686504d4a0
operatingsystem: linux
platform    : linux
priority    : 1
schannel    : antoine
subdir      : linux-64
target-triplet: x86_64-any-linux
url         : https://conda.anaconda.org/t/an-62662a71-8243-492b-bc05-6c11381f00f8/antoine/linux-64/llvmdev-3.7.1-2.tar.bz2
dependencies:
    system

[...]
llvmdev 3.7.1 4
---------------
file name   : numba::llvmdev-3.7.1-4.tar.bz2
name        : llvmdev
version     : 3.7.1
build number: 4
build string: 4
channel     : numba/linux-64
size        : 70.4 MB
arch        : x86_64
binstar     : {'owner_id': '545ba7365e768304c818edde', 'channel': 'main', 'package_id': '546bd9755e76831cc7f8c082'}
fn          : llvmdev-3.7.1-4.tar.bz2
license     : Open Source (http://llvm.org/releases/3.7.0/LICENSE.TXT)
machine     : x86_64
md5         : 17613e6ecfd667a971cf13a3933049e4
operatingsystem: linux
platform    : linux
priority    : 2
schannel    : numba
subdir      : linux-64
target-triplet: x86_64-any-linux
url         : https://conda.anaconda.org/t/an-62662a71-8243-492b-bc05-6c11381f00f8/numba/linux-64/llvmdev-3.7.1-4.tar.bz2
dependencies:
    system
```

**Comment by pitrou** [comment] 2016-06-16 12:39
```
$ cat ~/.condarc 
# This is a sample .condarc file

# channel locations. These override conda defaults, i.e., conda will
# search *only* the channels listed here, in the order given. Use "defaults" to
# automatically include all default channels. Non-url channels will be
# interpreted as binstar usernames (this can be changed by modifying the
# channel_alias key; see below).
channels:
  - antoine
  - numba
#  - http://some.custom/channel
#  - file:///some/local/directory
  - defaults

channel_priority: false
```

**Comment by mcg1969** [comment] 2016-06-16 12:40
OK, I'll check this out. It looks like `channel_priority: false` is not being fully honored here.

**Comment by mcg1969** [comment] 2016-06-16 12:47
Actually, llvmdev looks right. When `channel_priority` is `false`, it prioritizes version first, _then_ channel priority, _then_ build. That's because build numbers can't be compared across channels.

**Comment by pitrou** [comment] 2016-06-16 12:51
> That's because build numbers can't be compared across channels.

In this case, they can, since the same recipe has been used first for the `antoine` upload, then later for the `numba` upload ;-)

**Comment by mcg1969** [comment] 2016-06-16 13:18
That's the exception, I'm afraid, and conda can't traffic in exceptions. Still, channel pinning will help settle these cases.

**Comment by mcg1969** [comment] 2016-06-16 14:59
OK, let's tackle these in reverse order.

In the last case, I can confirm that what is happening is that it is preferring the higher-priority `antoine` channel over the lower-priority `numba` channel. Even though the build number is lower, it's not considered a downgrade because, again, we cannot depend on build numbers being sortable across channels. I'm actually going to submit a patch that adds a new list of "channel crossgrades" to conda's output so that this is made more clear; for instance:
```
The following packages will be UPDATED from a higher-priority channel:

    llvmdev:       3.7.1-4           numba    --> 3.7.1-2           antoine
```
Now to look at the second case.

**Comment by mcg1969** [comment] 2016-06-16 15:03
The `cudatoolkit` case is the same. If I set `channel_priority: true` and move `antoine` to third position in the channel order, then we get this:
```
The following packages will be UPDATED from a higher-priority channel:

    cudatoolkit:   7.5-0             defaults --> 7.0-1             numba
```
I would recommend the `numba` channel either remove `cudatoolkit` or at least keep version parity with defaults.

**Comment by pitrou** [comment] 2016-06-16 15:13
In other words, per-package channel pinning will really be the answer to all this, right?

**Comment by mcg1969** [comment] 2016-06-16 15:13
Finally, in the case offered at the top of the issue, we have this:
```
The following packages will be SUPERCEDED by a higher-priority channel:

    cudatoolkit:   7.5-0             defaults --> 7.0-1             numba
    llvmdev:       3.7.1-4           numba    --> 3.7.1-2           antoine
    llvmlite:      0.11.0-py35_0     numba    --> 0.8.0.dev-py35_11 antoine
    pip:           8.1.1-py35_1      defaults --> 0.0.1-py35_0      antoine
    python:        3.5.1-0           defaults --> 3.5.0-4_dbg       antoine  [pydbg]
```
(you'll note I tweaked the language further).

So why did it select the debug build? Well, the first priority conda has is to obtain the latest version and build of the packages on the command line. That's `3.5.0-4` in the case of Python. _Then_ it determines the minimum number of features required to support that package. Unfortunately, you have _only_ a debug version in your channel, so it has no choice but to select it.

What would be the solution here? Well, turning off `channel_priority` is one. Hosting a non-debug build of Python for every debug build that you have is another.

**Comment by mcg1969** [comment] 2016-06-16 15:14
Yes, I think per-channel pinning is going to be really useful now!

**Comment by kalefranz** [comment] 2016-06-16 17:05
I'm going go ahead and close this issue now.  But I think we're aware of everything.  Have #2718 as a response. Plus we'll make per-package channel pinning a HIGH priority.

**Closed by kalefranz** 2016-06-16 17:05 UTC
