### ISSUE TITLE
`using Conda; Conda.update()` causes "An unexpected error has occurred."

### ISSUE THREAD

**Issue by StrangeRay** [conda/conda#6113] opened 2017-10-08 22:01 UTC
The cell output window reads:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /Users/StrangeHeim/.julia/v0.6/Conda/deps/usr  (writable)
    default environment : /Users/StrangeHeim/.julia/v0.6/Conda/deps/usr
       envs directories : /Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/envs
                          /Users/StrangeHeim/.conda/envs
          package cache : /Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/pkgs
                          /Users/StrangeHeim/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/condarc-julia.yml
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.14 Darwin/17.0.0 OSX/10.13    
                UID:GID : 501:20

`$ /Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/bin/conda update -y --all`




    Traceback (most recent call last):
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Invalid value 1505178119.19 for timestamp

failed process: Process(setenv(`/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/bin/conda update -y --all`,String["CLICOLOR=1", "LSCOLORS=ExFxBxDxCxegedabagacad", "PATH=/Applications/Julia-0.6.app/Contents/Resources/julia/bin:/Applications/Julia-0.6.app/Contents/Resources/julia/bin:/Users/StrangeHeim/anaconda3/bin:/Users/StrangeHeim/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/usr/local/git/bin", "XPC_FLAGS=0x0", "PWD=/Users/StrangeHeim/Experiments/Julia/Newton's_Cannonball", "DISPLAY=/private/tmp/com.apple.launchd.JnTgCI26QC/org.macosforge.xquartz:0", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=Apple_Terminal", "JUPYTER=/Users/StrangeHeim/anaconda3/bin/jupyter", "COLUMNS=80", "SHELL=/bin/bash", "__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0", "JPY_PARENT_PID=983", "TMPDIR=/var/folders/33/6n9mv33s6q1_ftqytshwt2f00000gn/T/", "TK_LIBRARY=/System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Scripts", "CONDARC=/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr/condarc-julia.yml", "FONTCONFIG_PATH=/Applications/Julia-0.6.app/Contents/Resources/julia/etc/fonts", "LANG=en_US.UTF-8", "PS1=\\[\\033[36m\\]\\u\\[\\033[m\\]@\\[\\033[32m\\]\\h:\\[\\033[33;1m\\]\\w\\[\\033[m\\]\$ ", "SHLVL=1", "LOGNAME=StrangeHeim", "DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.m44fcKk8z5/unix_domain_listener", "CONDA_PREFIX=/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr", "TERM_SESSION_ID=3150AC32-3281-49DA-84C0-168FAFCE816D", "SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.AKAaxnw7QA/Listeners", "_=/Users/StrangeHeim/anaconda3/bin/jupyter", "CONDA_DEFAULT_ENV=/Users/StrangeHeim/.julia/v0.6/Conda/deps/usr", "Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.OcB3iwsurM/Render", "LINES=30", "USER=StrangeHeim", "SECURITYSESSIONID=186a8", "TERM=xterm-256color", "HOME=/Users/StrangeHeim", "TERM_PROGRAM_VERSION=400", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] update() at /Users/StrangeHeim/.julia/v0.6/Conda/src/Conda.jl:219
 [4] include_string(::String, ::String) at ./loading.jl:515

In [ ]:

1
​
```

**Comment by thomasernste** [comment] 2017-10-08 23:33
Same issue for me here when I try to do anything with anaconda/jupyter notebook.

**Comment by fsoustra** [comment] 2017-10-08 23:40
Same issue here: 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\opt\anaconda3  (writable)
    default environment : C:\opt\anaconda3
       envs directories : C:\opt\anaconda3\envs
                          C:\Users\fredb\AppData\Local\conda\conda\envs
                          C:\Users\fredb\.conda\envs
          package cache : C:\opt\anaconda3\pkgs
                          C:\Users\fredb\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\fredb\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\opt\anaconda3\scripts\conda update -y --all`




    Traceback (most recent call last):
      File "C:\opt\anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\opt\anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\opt\anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\opt\anaconda3\lib\site-packages\conda\cli\install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "C:\opt\anaconda3\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\opt\anaconda3\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\opt\anaconda3\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "C:\opt\anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\opt\anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\opt\anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "C:\opt\anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506621463.269 for timestamp

**Comment by nehaljwani** [comment] 2017-10-09 04:52
Closing as duplicate of #6096 

Solution is to find out files with timestamp in decimal, and delete them:
```
findstr /s /m /i /r /c:"timestamp\": [0-9]*\." C:\opt\anaconda3\conda-meta\*.json
```

**Closed by nehaljwani** 2017-10-09 04:52 UTC
