### ISSUE TITLE
conda update conda-build broke (master)

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2559] opened 2016-05-26 19:57 UTC
```
$ conda update conda-build
...
Traceback (most recent call last):
  File "/Users/ilan/python/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/ilan/conda/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/ilan/conda/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/ilan/conda/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "/Users/ilan/conda/conda/cli/install.py", line 381, in install
    plan.display_actions(actions, index, show_channel_urls=args.show_channel_urls)
  File "/Users/ilan/conda/conda/plan.py", line 66, in display_actions
    info = index[dist + '.tar.bz2']
KeyError: u'anaconda-2.4.0-np110py27_0.tar.bz2[m.tar.bz2'
```
CC @kalefranz @mcg1969

**Comment by mcg1969** [comment] 2016-05-26 20:25
I'm sure this is related to my efforts to smash these `dist`-manipulation bugs once and for all. I will fix this, and I'll add the tests as well

**Comment by mcg1969** [comment] 2016-05-26 20:27
This looks like an interaction with the `with_features_depends` implementation (the `[m` is the giveaway)

**Comment by mcg1969** [comment] 2016-05-27 00:56
@ilanschnell I am having difficulty reproducing this. Can you repeat with the `--debug` flag? Thanks.

**Comment by mcg1969** [comment] 2016-05-27 16:28
I did manage to reproduce this. Interesting bug caused by the way I process the index data in the `Resolve` class. If multiple `Resolve` objects are built from the same `index` data, it is important to do some of this preprocessing only once. I had a safeguard in place to prevent repeated preprocessing, but that safeguard was not perfect. I'm building a patch now.

**Comment by mcg1969** [comment] 2016-05-27 22:54
Since this is a two-liner I went ahead and merged it.

**Closed** 2016-05-27 22:54 UTC
Labels: bug
