### ISSUE TITLE
Error on conda install odo

### ISSUE THREAD

**Issue by jrellis** [conda/conda#1694] opened 2015-10-09 14:32 UTC
I'm getting an error when upgrading odo with conda install odo. I'm getting a similar error with bokeh. Possibly from the numpy version?

numpy                     1.10.0                   py27_0

```
conda install odo
Fetching package metadata: \\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
..\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "\\susq\eot\eot_sata3\scratch\miniconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
    args.func(args, p)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\plan.py", line 427, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\plan.py", line 247, in ensure_linked_actions
    if install.try_hard_link(extracted_in, prefix, dist):
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\install.py", line 407, in try_hard_link
    assert not isfile(dst), dst
AssertionError: \\susq\eot\eot_sata3\scratch\miniconda\envs\base\.tmp-numpy-1.9.3-py27_0
```

```
conda install bokeh
Fetching package metadata: \\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
..\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "\\susq\eot\eot_sata3\scratch\miniconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
    args.func(args, p)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\cli\install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\plan.py", line 427, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\plan.py", line 247, in ensure_linked_actions
    if install.try_hard_link(extracted_in, prefix, dist):
  File "\\susq\eot\eot_sata3\scratch\miniconda\lib\site-packages\conda\install.py", line 407, in try_hard_link
    assert not isfile(dst), dst
AssertionError: \\susq\eot\eot_sata3\scratch\miniconda\envs\base\.tmp-numpy-1.9.3-py27_0
```

```
conda info
Current conda install:

             platform : win-64
        conda version : 3.14.1
  conda-build version : not installed
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : \\susq\eot\eot_sata3\scratch\miniconda  (writable)
  default environment : \\susq\eot\eot_sata3\scratch\miniconda\envs\base
     envs directories : \\susq\eot\eot_sata3\scratch\miniconda\envs
        package cache : \\susq\eot\eot_sata3\scratch\miniconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        http://conda.binstar.org/ellis/win-64/
                        http://conda.binstar.org/ellis/noarch/
          config file : C:\Users\ellis\.condarc
    is foreign system : False
```

**Comment by soapy1** [comment] 2016-11-07 20:01
I can't reproduce this on the newest version of conda so I'm going to close this issue. If this is still an issue for you please `conda update conda` and try again. If the problem persists, please reopen the issue.

**Closed by soapy1** 2016-11-07 20:01 UTC
