### ISSUE TITLE
conda create -h blows  up if envs directory is missing

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda#1446] opened 2015-07-21 19:57 UTC
if a sysadmin makes a system install, and the ~/.conda/envs and ~/envs directories are missing

conda create works, but for some reason conda create -h does not work

(in fact, if the envs directory in the root sysadmin install is missing, conda create -h will never work)

This is only an issue with conda create -h (the help)  the rest of the command appears fine

**Comment by soapy1** [comment] 2016-10-25 22:45
I can't reproduce this on the newest version of conda, so I'm closing the issue. Please reopen if the problem persists

**Closed by soapy1** 2016-10-25 22:45 UTC
