### ISSUE TITLE
Unexpected error updating anaconda 4.3.27 on mac

### ISSUE THREAD

**Issue by KirkLab** [conda/conda#6111] opened 2017-10-08 19:07 UTC
When attempting to update anaconda and its packages, the following error occurred.  

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 3.5.4.final.0
       requests version : 2.18.4
       root environment : /Users/Username/anaconda  (writable)
    default environment : /Users/Username/anaconda
       envs directories : /Users/Username/anaconda/envs
                          /Users/Username/.conda/envs
          package cache : /Users/Username/anaconda/pkgs
                          /Users/Username/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/Username/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.5.4 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /Users/Username/anaconda/bin/conda update --all`

    Traceback (most recent call last):
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/Username/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080228.419 for timestamp

**Comment by nehaljwani** [comment] 2017-10-08 19:38
Closing as duplicate of https://github.com/conda/conda/issues/6096

**Closed** 2017-10-08 19:38 UTC
