### ISSUE TITLE
error when creating a new enviroment

### ISSUE THREAD

**Issue by HugoSiles** [conda/conda#4075] opened 2016-12-15 00:28 UTC
I need help with this error:
C:\Users\Usuario>conda create -n oldqt python=3.4 anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 2.7.10.final.0
       requests version : 2.12.4
       root environment : C:\Users\Usuario\Anaconda  (writable)
    default environment : C:\Users\Usuario\Anaconda
       envs directories : C:\Users\Usuario\Anaconda\envs
          package cache : C:\Users\Usuario\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\Usuario\Anaconda\Scripts\conda-script.py create -n oldqt python=3.4
anaconda`

    Traceback (most recent call last):
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\exceptions.py", l
ne 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\main.py", lin
 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\main_create.p
", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\install.py",
ine 238, in install
        prefix=prefix)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\api.py", line 24,
in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\fetch.py", line 2
5, in fetch_index
        for url in urls]
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\fetch.py", line 7
, in func
        res = f(*args, **kwargs)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\fetch.py", line 1
7, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\sessions.py",
ine 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\sessions.py",
ine 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\sessions.py",
ine 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\adapters.py",
ine 423, in send
        timeout=timeout
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\packages\urlli
3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\packages\urlli
3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\packages\urlli
3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\packages\urlli
3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\packages\urlli
3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Users\Usuario\Anaconda\lib\site-packages\requests\packages\urlli
3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_cla
s'

**Comment by kalefranz** [comment] 2017-05-09 04:38
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-09 04:38 UTC
