### ISSUE TITLE
`conda create --experimental-solver=libmamba` hangs after caching indices

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11223] opened 2022-02-15 17:17 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Installed `conda-libmamba-solver` in my `base` env as well as in a standalone `libmamba` env:

```
$ conda activate base
(base) $ conda install \
    --override-channels \
    -c conda-canary/label/conda-conda-pr-11193 \
    -c conda-canary/label/conda-libmamba-solver-pr-3 \
    -c conda-forge \
    -c defaults \
    conda \
    conda-libmamba-solver
(base) $ conda create \
    -n mamba-py27 \
    --dry-run \
    --experimental-solver=libmamba \
    python=2.7 \
    anaconda
```

```
$ conda create \
    -n libmamba \
    --override-channels \
    -c conda-canary/label/conda-conda-pr-11193 \
    -c conda-canary/label/conda-libmamba-solver-pr-3 \
    -c conda-forge \
    -c defaults \
    conda \
    conda-libmamba-solver
$ conda activate libmamba
(libmamba) $ $CONDA_PREFIX/bin/conda create \
    -n mamba-py27 \
    --dry-run \
    --experimental-solver=libmamba \
    python=2.7 \
    anaconda
```

In both cases the `conda create` with the libmamba solver hangs after caching the repo indices.

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /Users/kodegard/anaconda/current
            shell level : 1
       user config file : /Users/kodegard/.condarc
 populated config files : /Users/kodegard/.condarc
          conda version : 4.11.0.73_gb1ea4be80
    conda-build version : 3.21.7
         python version : 3.9.7.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/kodegard/anaconda/current  (writable)
      conda av data dir : /Users/kodegard/anaconda/current/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/kodegard/anaconda/current/pkgs
                          /Users/kodegard/.conda/pkgs
       envs directories : /Users/kodegard/anaconda/current/envs
                          /Users/kodegard/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0.73_gb1ea4be80 requests/2.26.0 CPython/3.9.7 Darwin/20.6.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

</details>

### Conda config

```shell
==> /Users/kodegard/.condarc <==
auto_update_conda: False
channels:
  - defaults
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/kodegard/anaconda/current:
#
# Name                    Version                   Build  Channel
anaconda-client           1.8.0            py39hecd8cb5_0    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
beautifulsoup4            4.10.0             pyh06a4308_0    defaults
brotlipy                  0.7.0           py39h9ed2024_1003    defaults
bs4                       4.10.0               hd3eb1b0_0    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py39h6e9494a_1    conda-forge
cffi                      1.14.6           py39h2125817_0    defaults
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
chardet                   4.0.0           py39hecd8cb5_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
clyent                    1.2.2            py39hecd8cb5_1    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
commonmark                0.9.1              pyhd3eb1b0_0    defaults
conda                     4.11.0.73_gb1ea4be80          py39_0    conda-canary/label/conda-conda-pr-11193
conda-build               3.21.7           py39hecd8cb5_0    defaults
conda-libmamba-solver     22.2.0.25_gaaa86a9            py_0    conda-canary/label/conda-libmamba-solver-pr-3
conda-package-handling    1.7.3            py39h9ed2024_1    defaults
coverage                  5.5              py39h9ed2024_2    defaults
cryptography              35.0.0           py39h2fd3fbb_0    defaults
distlib                   0.3.2              pyhd3eb1b0_0    defaults
editdistance-s            1.0.0            py39hf018cea_1    conda-forge
filelock                  3.0.12             pyhd3eb1b0_1    defaults
flaky                     3.7.0                      py_0    defaults
future                    0.18.2           py39hecd8cb5_1    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 h0a44026_3    defaults
identify                  2.2.15             pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd3eb1b0_0    defaults
importlib-metadata        4.8.2            py39hecd8cb5_0    defaults
importlib_metadata        4.8.2                hd3eb1b0_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter_core              4.9.1            py39hecd8cb5_0    defaults
krb5                      1.19.2               hcfbf3a7_3    conda-forge
libarchive                3.5.2                h2b60450_1    conda-forge
libcurl                   7.81.0               hf45b732_0    conda-forge
libcxx                    12.0.0               h2f01273_0    defaults
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  hb1e8313_2    defaults
libiconv                  1.16                 h1de35cc_0    defaults
liblief                   0.10.1               h23ab428_1    defaults
libmamba                  0.21.2               h9ce2d19_0    conda-forge
libmambapy                0.21.2           py39h2c464dc_0    conda-forge
libnghttp2                1.46.0               h6f36284_0    conda-forge
libsolv                   0.7.19               hcf210ce_5    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libxml2                   2.9.12               hcdb78fc_0    defaults
libzlib                   1.2.11            h9173be1_1013    conda-forge
lz4-c                     1.9.3                h23ab428_1    defaults
lzo                       2.10              haf1e3a3_1000    conda-forge
markupsafe                2.0.1            py39h9ed2024_0    defaults
mock                      4.0.3              pyhd3eb1b0_0    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.3                  hca72f7f_2    defaults
nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0    defaults
pip                       21.2.4           py39hecd8cb5_0    defaults
pkginfo                   1.7.1            py39hecd8cb5_0    defaults
pluggy                    0.13.1           py39hecd8cb5_0    defaults
pre-commit                2.15.0           py39h6e9494a_0    conda-forge
psutil                    5.8.0            py39h9ed2024_1    defaults
py                        1.10.0             pyhd3eb1b0_0    defaults
py-lief                   0.10.1           py39h23ab428_1    defaults
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3            py39h9ed2024_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyopenssl                 21.0.0             pyhd3eb1b0_1    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyrsistent                0.18.0           py39hca72f7f_0    defaults
pysocks                   1.7.1            py39hecd8cb5_0    defaults
pytest                    6.2.4            py39hecd8cb5_2    defaults
pytest-cov                2.12.1             pyhd3eb1b0_0    defaults
pytest-mock               3.6.1              pyhd3eb1b0_0    defaults
python                    3.9.7                h88f2d9e_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python.app                3                py39h9ed2024_0    defaults
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0    defaults
pyyaml                    6.0              py39hca72f7f_1    defaults
readline                  8.1                  h9ed2024_0    defaults
reproc                    14.2.3               h0d85af4_0    conda-forge
reproc-cpp                14.2.3               he49afe7_0    conda-forge
requests                  2.26.0             pyhd3eb1b0_0    defaults
rich                      10.11.0          py39h6e9494a_0    conda-forge
ripgrep                   12.1.1                        0    defaults
ruamel_yaml               0.15.100         py39h9ed2024_0    defaults
setuptools                58.0.4           py39hecd8cb5_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hce871da_0    defaults
textual                   0.1.12           py39h6e9494a_0    conda-forge
tk                        8.6.11               h7bc2e8c_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
tzdata                    2021e                hda174b7_0    defaults
urllib3                   1.26.7             pyhd3eb1b0_0    defaults
virtualenv                20.4.6           py39hecd8cb5_1    defaults
wheel                     0.37.0             pyhd3eb1b0_1    defaults
xz                        5.2.5                h1de35cc_0    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
yaml-cpp                  0.6.3                hb1e8313_4    conda-forge
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```

</details>

**Comment by jaimergp** [comment] 2022-02-15 18:13
Hm, I have seen this on Windows today, but not on Linux... so I am guessing this has to do with a new libmamba release? But downgrading didn't help. We need to disable the stderr captures, as discussed [here](https://github.com/conda-incubator/conda-libmamba-solver/pull/8).

**Comment by jaimergp** [comment] 2022-02-15 18:16
Can you reproduce the error if you set an environment variable `CI=1`?

**Comment by jaimergp** [comment] 2022-02-15 19:36
I can't reproduce this on Linux :(

**Comment by kenodegard** [comment] 2022-02-15 19:58
I've only tried this on macOS.

Tried with `CI=1` in both envs and it still hangs. Only this time it doesn't print out the progress bars/caching messages for the indices.

The log files are also empty.

**Comment by jaimergp** [comment] 2022-02-15 19:59
Ok, noted! I'll try to get an Intel Mac this week. Or maybe we can get arm64 builds before that :D

**Comment by jaimergp** [comment] 2022-02-15 20:07
Hm, in the meantime, can you try with this version?

https://github.com/conda/conda/issues/11222#issuecomment-1040704404

**Comment by kenodegard** [comment] 2022-02-15 20:11
Still hangs 😞

**Comment by jaimergp** [comment] 2022-02-16 13:18
Let's see if this one works:

```
conda install https://anaconda.org/conda-canary/conda-libmamba-solver/22.2.0.11_g432a93e/download/noarch/conda-libmamba-solver-22.2.0.11_g432a93e-py_0.tar.bz2
```

**Comment by kenodegard** [comment] 2022-02-16 15:54
@jaimergp woohoo! it works now in both my `base` and `libmamba` envs!

**Comment by jezdez** [comment] 2022-02-18 21:32
Closing this, since we found the problem around logging and [fixed it in the recent canary build](https://github.com/conda-incubator/conda-libmamba-solver/pull/8). Thank you for filing the bug @kenodegard!

**Closed by jezdez** 2022-02-18 21:32 UTC
Labels: type::bug, source::anaconda, type::poc, solver::libmamba
