### ISSUE TITLE
conda update error on windows

### ISSUE THREAD

**Issue by complexly** [conda/conda#1274] opened 2015-04-13 10:11 UTC
**when using "conda update conda", output is:**

C:\ANACONDA\lib\site-packages\binstar_client\utils\__init__.py:43: UserWarning:
Module argparse was already imported from C:\ANACONDA\lib\argparse.pyc, but c:\a
naconda\lib\site-packages is being added to sys.path
  from pkg_resources import parse_version as pv
Fetching package metadata: ...An unexpected error has occurred, please consider
sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\ANACONDA\SCRIPTS\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\ANACONDA\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\ANACONDA\lib\site-packages\conda\cli\main.py", line 207, in args_func

    args.func(args, p)
  File "C:\ANACONDA\lib\site-packages\conda\cli\main_update.py", line 40, in exe
cute
    install.install(args, parser, 'update')
  File "C:\ANACONDA\lib\site-packages\conda\cli\install.py", line 253, in instal
l
    offline=args.offline)
  File "C:\ANACONDA\lib\site-packages\conda\cli\common.py", line 531, in get_ind
ex_trap
    return get_index(*args, **kwargs)
  File "C:\ANACONDA\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\ANACONDA\lib\site-packages\conda\utils.py", line 86, in __call__
    value = self.func(*args, **kw)
  File "C:\ANACONDA\lib\site-packages\conda\fetch.py", line 250, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\ANACONDA\lib\site-packages\concurrent\futures\_base.py", line 400, in
 result
    return self.__get_result()
  File "C:\ANACONDA\lib\site-packages\concurrent\futures\_base.py", line 359, in
 __get_result
    reraise(self._exception, self._traceback)
  File "C:\ANACONDA\lib\site-packages\concurrent\futures\_compat.py", line 107,
in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\ANACONDA\lib\site-packages\concurrent\futures\thread.py", line 61, in
 run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\ANACONDA\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\ANACONDA\lib\site-packages\conda\fetch.py", line 100, in fetch_repoda
ta
    verify=config.ssl_verify)
  File "C:\ANACONDA\lib\site-packages\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\ANACONDA\lib\site-packages\requests\sessions.py", line 464, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\ANACONDA\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\ANACONDA\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\ANACONDA\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 544, in urlopen
    body=body, headers=headers)
  File "C:\ANACONDA\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\ANACONDA\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 762, in _validate_conn
    conn.connect()
  File "C:\ANACONDA\lib\site-packages\requests\packages\urllib3\connection.py",
line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\ANACONDA\lib\site-packages\requests\packages\urllib3\contrib\pyopenss
l.py", line 251, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\ANACONDA\lib\site-packages\requests\packages\urllib3\contrib\pyopenss
l.py", line 152, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\ANACONDA\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in
 __call__
    stGetValueDecoder, self, substrateFun
  File "C:\ANACONDA\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in
 valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\ANACONDA\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in
 __call__
    stGetValueDecoder, self, substrateFun
  File "C:\ANACONDA\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in
 valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\ANACONDA\lib\site-packages\pyasn1\type\univ.py", line 874, in setComp
onentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\ANACONDA\lib\site-packages\pyasn1\type\namedtype.py", line 68, in get
PositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) n
ot found

**The output of "conda info":**
C:\ANACONDA\lib\site-packages\binstar_client\utils\__init__.py:43: UserWarning:
Module argparse was already imported from C:\ANACONDA\lib\argparse.pyc, but c:\a
naconda\lib\site-packages is being added to sys.path
  from pkg_resources import parse_version as pv
Current conda install:

             platform : win-64
        conda version : 3.10.1
  conda-build version : not installed
       python version : 2.7.5.final.0
     requests version : 2.6.0
     root environment : C:\ANACONDA  (writable)
  default environment : C:\ANACONDA
     envs directories : C:\ANACONDA\envs
        package cache : C:\ANACONDA\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ymost** [comment] 2015-04-21 15:15
+1

**Comment by sanand0** [comment] 2015-04-28 02:19
I faced the same issue just now.

    Current conda install:

                 platform : linux-64
            conda version : 3.10.1
      conda-build version : 1.3.5
           python version : 2.7.9.final.0
         requests version : 2.6.0
         root environment : /home/ec2-user/gvkdrive2/anaconda  (writable)
      default environment : /home/ec2-user/gvkdrive2/anaconda
         envs directories : /home/ec2-user/gvkdrive2/anaconda/envs
            package cache : /home/ec2-user/gvkdrive2/anaconda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/linux-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

**Comment by lmillefiori** [comment] 2015-04-28 18:06
Same issue here.

```
Current conda install:

             platform : win-64
        conda version : 3.11.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by jorisvandenbossche** [comment] 2015-05-01 12:24
I saw this here: https://github.com/nose-devs/nose/issues/622 (if you are using python 2.7 or >= 3.2, you argparse is included in the stdlib, and this warning is caused by also having the separate lib installed)

Doing a `pip uninstall argparse` did solve the problem for me.

**Comment by asmeurer** [comment] 2015-05-01 20:09
@jorisvandenbossche the PyAsn1Error error was caused by argparse?

**Comment by jorisvandenbossche** [comment] 2015-05-01 20:26
Whoops, sorry, only looked at the first part of the issue report above. So no, I was speaking about the warning "UserWarning: Module argparse was already imported from C:\ANACONDA\lib\argparse.pyc, but c:\anaconda\lib\site-packages is being added to sys.path", not about the error on the line below that ...

**Comment by asmeurer** [comment] 2015-05-01 20:40
Everyone here seems to be running requests 2.6.0. The latest version is 2.6.2. Maybe `conda update requests` will fix this.

**Comment by asmeurer** [comment] 2015-05-28 20:45
Closing as duplicate of https://github.com/conda/conda/issues/1261

**Closed by asmeurer** 2015-05-28 20:45 UTC
