### ISSUE TITLE
Env Create Warning Message

### ISSUE THREAD

**Issue by 1dmesh** [conda/conda#13600] opened 2024-02-16 04:29 UTC
### What is the idea?

I believe a warning message to be necessary for this command.

```
conda env create -n env_name
```

It gives this error:

```
EnvironmentFileNotFound: './environment.yml' file not found
```

### Why is this needed?

I am a beginner user of anaconda. I urge you to google "conda env create --name environmentfilenotfound" (or any variation of the error to try to find the problem) and tell me it's not difficult to actually find how to fix this issue. My brain remembered `conda env list` as I just used it moments ago, so it stands to reason `conda env create -n` was an acceptable command. If it's not, I think the error should at least be easy to google (or visually see what's wrong) for people that don't know what they're doing. Even in the issues of this repo, the actual fix was hard to find. 

To answer "why did you just not use -h", please see:

```
> conda env create -h

Examples::

    conda env create
    conda env create -n envname
    conda env create folder/envname
    conda env create -f /path/to/environment.yml
    conda env create -f /path/to/requirements.txt -n envname
    conda env create -f /path/to/requirements.txt -p /home/user/envname
```

**Edit:** My ape brain really only looked at the usage examples, and not the description. Which is my fault, but once I made the assumption it was the correct command it was downhill! Maybe I am just dense, and that's okay!

### What should happen?

If the usage does not mach, it would be nice if it gave an error instead, or something similar:
```
EnvironmentFileNotFound: './environment.yml' file not found. If you intended to make an environment without an environment.yml, please use 'conda create -n` instead.
```

### Additional Context

Issue discussed below as far as documentation / usage change. If this is not going to happen, a user warning would be nice.

See: https://github.com/conda/conda/issues/3859

**Comment by ForgottenProgramme** [comment] 2024-02-18 16:21
Hey, @1dmesh
Thank you for opening this issue. This is a reasonable ask. I will be bringing this up with my team. 
Meanwhile, I encourage you to follow the larger conversation around collapsing `conda env` into `conda` [here](https://github.com/conda/conda/issues/11633).

**Comment by kenodegard** [comment] 2024-03-11 13:46
Duplicate of https://github.com/conda/conda/issues/13015

**Closed** 2024-03-11 13:46 UTC
Labels: type::feature, source::community, plugins::env, duplicate
