### ISSUE TITLE
conda --debug and it shows: "an unexpected error has occurred"

### ISSUE THREAD

**Issue by franklinqin7** [conda/conda#2864] opened 2016-06-25 00:59 UTC
I run conda --debug and it shows: "An unexpected error has occurred". I wonder why this happens?

This is the result of "conda info":
Current conda install:

             platform : win-64
        conda version : 4.1.3
    conda-env version : 2.5.0
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\Ziyuan Qin\Anaconda3  (writable)
  default environment : C:\Users\Ziyuan Qin\Anaconda3
     envs directories : C:\Users\Ziyuan Qin\Anaconda3\envs
        package cache : C:\Users\Ziyuan Qin\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment] 2016-06-25 01:16
`conda --debug` isn't a complete command.  The behavior is expected.

Is there a tutorial or instruction somewhere that told you to use this command?

**Comment by mcg1969** [comment] 2016-06-27 14:33
Kale is correct, of course, but in my view every unexpected traceback is a bug. We should be catching this incorrect usage.

However, I notice you're running `conda-env 2.5.0`. @franklinqin7 can you please try doing `conda update conda-env` and see if this fixes the problem?

**Comment by mcg1969** [comment] 2016-06-27 14:35
(To be honest, I don't know why the conda-env version would cause this bug, but I can't reproduce it.)

**Comment by mcg1969** [comment] 2016-06-27 14:37
Aha! I can indeed reproduce it.

**Comment by mcg1969** [comment] 2016-06-27 14:44
I think it's due to behavioral differences in `argparse` with Windows vs. other platforms, or perhaps Python 2 vs. Python 3. I just reproduced it on `conda 4.0.5` using Python 3 on Windows, and I think that `argparse` isn't correctly concluding that there's a missing `command` argument.

**Comment by mcg1969** [comment] 2016-06-27 14:45
http://stackoverflow.com/questions/18282403/argparse-with-required-subcommands

**Comment by franklinqin7** [comment] 2016-06-27 20:36
Thanks to both of you! @kalefranz @mcg1969 
Clearly I am learning data structures and objected oriented programming so I currently do not understand parsing. 
@kalefranz I typed `conda --debug` because `conda --h` told me to do so.
Sorry for the late message.

**Comment by mcg1969** [comment] 2016-06-28 18:05
I'm going to go ahead and close this since 1) I'm certain we fixed it in versions to come and 2) it's not an issue with normal usage.

**Closed by mcg1969** 2016-06-28 18:05 UTC
