### ISSUE TITLE
conda update conda failed on RHEL7 x86_64

### ISSUE THREAD

**Issue by prjemian** [conda/conda#3966] opened 2016-11-29 16:29 UTC
Here is the console session with the exception trace:

    jemian@gov .../eclipse/punx $ conda update conda
    Fetching package metadata .../local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.anaconda.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
      SubjectAltNameWarning
    /local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.anaconda.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
      SubjectAltNameWarning
    ..An unexpected error has occurred.
    Please consider posting the following information to the
    conda GitHub issue tracker at:

    	https://github.com/conda/conda/issues

    Current conda install:

    		   platform : linux-64
    	      conda version : 4.2.12
    	   conda is private : False
    	  conda-env version : 4.2.12
    	conda-build version : 1.20.3
    	     python version : 2.7.10.final.0
    	   requests version : 2.12.1
    	   root environment : /local/Apps/anaconda  (writable)
    	default environment : /local/Apps/anaconda
    	   envs directories : /local/Apps/anaconda/envs
    	      package cache : /local/Apps/anaconda/pkgs
    	       channel URLs : http://conda.anaconda.org/psi4/linux-64
    			      http://conda.anaconda.org/psi4/noarch
    			      https://repo.continuum.io/pkgs/free/linux-64
    			      https://repo.continuum.io/pkgs/free/noarch
    			      https://repo.continuum.io/pkgs/pro/linux-64
    			      https://repo.continuum.io/pkgs/pro/noarch
    		config file : /home/oxygen/JEMIAN/.condarc
    	       offline mode : False

    `$ /home/oxygen/JEMIAN/Apps/anaconda/bin/conda update conda`

    	Traceback (most recent call last):
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
    	    return_value = func(*args, **kwargs)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
    	    exit_code = args.func(args, p)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
    	    install(args, parser, 'update')
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
    	    prefix=prefix)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
    	    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 310, in fetch_index
    	    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 396, in result
    	    return self.__get_result()
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    	    result = self.fn(*self.args, **self.kwargs)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
    	    res = f(*args, **kwargs)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 116, in fetch_repodata
    	    timeout=(3.05, 60))
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    	    return self.request('GET', url, **kwargs)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    	    resp = self.send(prep, **send_kwargs)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    	    r = adapter.send(request, **kwargs)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    	    timeout=timeout
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    	    chunked=chunked)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    	    self._validate_conn(conn)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    	    conn.connect()
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    	    cert = self.sock.getpeercert()
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    	    'subjectAltName': get_subj_alt_name(x509)
    	  File "/local/Apps/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    	    ext = cert.extensions.get_extension_for_class(
    	AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by prjemian** [comment] 2016-11-29 16:41
With this ref: https://github.com/shazow/urllib3/issues/497#issuecomment-150210488

To follow up, this is the "fix" that has worked for me

  pip install requests==2.7.0
  conda install -y requests=2.7.0

It downgrades the requests package.

Note that the error is produced when running the "conda" command,  I found empirically that conda won't do anything as long as the requests package is broken in this way.  By using "pip" first, the broken package can be downgraded.  Then, the "conda" command is run to ensure that the downgrade is complete.  Tedious but it works.

After this, conda is working again.

**Comment by kalefranz** [comment] 2017-05-01 19:56
Duplicate of #3898, #3918, #3929, #3934, and #3935.

**Closed by kalefranz** 2017-05-01 19:56 UTC
