### ISSUE TITLE
conda envs directories and package cache reversed from previous version causing errors

### ISSUE THREAD

**Issue by dmarkwat** [conda/conda#4621] opened 2017-02-13 22:05 UTC
Hello!  Apologies in advance for the lengthy issue.  I am doing some regression testing of conda installs and noticed issues as I installed a test env using conda 4.3.11.  All my work with 4.3.9 has worked until this point; and I was hoping to keep on top of a regular conda refresh on the many machines I work on.

The install (some info omitted):
```
Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /usr/platform/miniconda2  (read only)
    default environment : /usr/platform/miniconda2
       envs directories : /usr/platform/miniconda2/envs
                          /home/userid/.conda/envs
          package cache : /usr/platform/miniconda2/pkgs
                          /home/userid/.conda/pkgs
           channel URLs : <private>
            config file : /usr/platform/miniconda2/.condarc
           offline mode : False
```

I was attempting `/usr/platform/miniconda2/bin/conda create -n foobah python=3`, but was greeted with the error:
```
Traceback (most recent call last):
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'/usr/platform/miniconda2/pkgs/cache/82c9030b.json'
```

Upon some investigation of 4.3.9 vs 4.3.11 I noticed the resolution of package caches and envs dirs might be reversed from their defaults in 4.3.9 which would appear to have resulted in the above error.  Is this expected?  Were these reversed by-design in an intermediate release?

4.3.9 conda info snippet: 
```
envs directories : /home/userid/.conda/envs
                            /usr/platform/miniconda2/envs
package cache : /home/userid/.conda/envs/.pkgs
                          /usr/platform/miniconda2/pkgs
```
4.3.11 conda info snippet:
```
envs directories : /usr/platform/miniconda2/envs
                            /home/userid/.conda/envs
package cache : /usr/platform/miniconda2/pkgs
                          /home/userid/.conda/pkgs
```

For additional context: /usr/platform/miniconda2/envs is root-writable only, and we would like to keep it that way for many reasons.

Adding to that, I had a thought: the shared cache - while very helpful at dedup-ing packages on a single machine - is making it very difficult to create reproducible environments at scale due to some of the (implied?) strictness of the way caches and envs are resolved.  Would it be possible to do any or all of the following:
- introduce a new configuration in condarc that explicitly disables usage of the shared cache for users?
- break out the caches from the envs dirs in condarc?
- make conda look more closely at package caches and envs dirs - checking them for writable behavior, e.g. - before assuming they are OK to use?  OR simply make conda more passive - if one cache fails, silently ignore and attempt the next until all are exhausted?

I suggest the last of those because it appears a writability check could have salvaged the install by skipping to my home dir cache and would make the cache and envs dirs resolution order less relevant, allowing for an accepted "default" to be adhered to while allowing for users to proceed.

I'd love to hear suggestions on how to handle this or if any of the above are possible, as any or all of these would help greatly with platform management and might help prevent me from pulling the python install out from under the users' environments when we roll upgrades.

**Comment by kalefranz** [comment] 2017-02-14 05:40
duplicate of #4593

The order flip was unintentional.  This is a big F-up on my part.  Biggest apologies.
Fix is here https://github.com/conda/conda/pull/4626
and will be deployed ASAP.

It will have to go through canary first.  I'll let you know when there's a canary version posted so you can test it.

**Comment by kalefranz** [comment] 2017-02-14 05:42
> introduce a new configuration in condarc that explicitly disables usage of the shared cache for users?

The reason this code was touched at all in 4.3.10/4.3.11 was to add an additional configuration and decouple environment directory configuration from package cache configuration.  To wit, you can now configure `pkgs_dirs` in a condarc file and/or set a comma-delimited `CONDA_PKGS_DIRS` environment variable.

**Comment by kalefranz** [comment] 2017-02-14 05:46
Oh, and I guess for the writability check, we weren't actually doing it, but we are now:
https://github.com/conda/conda/pull/4626/files#diff-5c11c4ae01650e54b3d5807b2c1cd8f5R589

**Comment by dmarkwat** [comment] 2017-02-14 14:36
Thanks for the prompt response!  But boy do I look silly; if I dug 5 more mins into this...alas, end of day struggles!  Well the imminent and coming changes look to be exactly like what I was looking for all around so that's awesome to see!

> The order flip was unintentional. This is a big F-up on my part. Biggest apologies.

Absolutely no worries at all :)  Knowing the little bit that I do about how the config is handled, the order on the print-out seemed all too tell-tale so figured that must have been it.

Re `pkgs_dirs`: I didn't see this out on the doc site but that will be a huge win for the way we are distributing to the users.  I should have looked a little more closely at release notes/PRs being as close to the latest release as possible.

And I totally feel the pain on not having a good framework for testing file permissions.  I also saw more than a few issues on here where you've mentioned as much :).  But despite that it looks like you're all doing great keeping on top of conda.  Much appreciated, too, btw!

**Comment by kalefranz** [comment] 2017-02-14 18:30
Ok, I have an update.  The fix will be https://github.com/conda/conda/pull/4626.  I'm going to have to leave the default order of pkgs_dirs inverted.  That's because of assumptions that are hard-coded in conda-build tests that can't be changed without a new conda-build release.  (Definite pain point that conda and conda-build aren't versioned and shipped together.)

However the fix *should* correctly look at the package cache to determine if it's user-writable or not.  To make this determination, we look specifically at the `urls.txt` file within the package cache, since it always exists for any versions of conda in at least the last year.  If the user can open that file for writing, then we infer that the package cache is writable.

I think this at least makes progress for us.  I'll have a path release into the conda-canary channel either today or tomorrow for you to test.

**Comment by kalefranz** [comment] 2017-02-15 04:35
Conda 4.3.12 that includes a patch for this issue has been released to conda canary.  Feel free to test.

    conda config --add channels conda-canary
    conda update conda

**Closed by kalefranz** 2017-02-15 04:35 UTC
Labels: bug, high priority

**Comment by dmarkwat** [comment] 2017-02-15 14:29
I am testing conda 4.3.12 from canary but running into some issues.  Notably, any time it tries to reference a cache directory and it doesn't exist, conda fails.  This happens both in conda clean and conda create that I've noticed so far.

Config:
```
pkgs_dirs:
  - ~/.conda/envs/pkgs
```

```
`$ /usr/platform/miniconda2/bin/conda clean -y --all`




    Traceback (most recent call last):
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/cli/main_clean.py", line 297, in execute
        pkgs_dirs, totalsize = find_tarballs()
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/cli/main_clean.py", line 84, in find_tarballs
        for package_cache in PackageCache.all_writable(context.pkgs_dirs):
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 176, in all_writable
        (PackageCache(pd) for pd in pkgs_dirs)))
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 175, in <lambda>
        writable_caches = tuple(filter(lambda c: c.is_writable,
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 295, in is_writable
        self._is_writable = create_package_cache_directory(self.pkgs_dir)
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/create.py", line 303, in create_package_cache_directory
        touch(join(pkgs_dir, 'urls'))
      File "/usr/platform/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/update.py", line 67, in touch
        assert isdir(dirname(path))
    AssertionError

Error doing: 
```

```
$ /usr/platform/miniconda2/bin/conda create -n pootoo python=3
Fetching package metadata ...

CondaError: No writable package cache directories found in
(u'~/.conda/envs/pkgs',)
```

On a cold run on an empty machine, I would expect both of these to succeed by simply ignoring in the case of clean (a warning used to be displayed in previous version) or initializing the cache dir in the case of create.  Is that what you would expect too, @kalefranz?

**Comment by davidfokkema** [comment] 2017-02-16 14:01
While provisioning my VM, I get the AssertionError as well.
