### ISSUE TITLE
Permissions error on conda create and others on Windows

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda/conda#1986] opened 2016-01-22 17:48 UTC
I installed Miniconda for a specific user on Windows.  When running as that user, I did this command:

```
conda create --copy -n anaocnda-builder chalmers
```

It looked okay until `Extracting Packages`, then I get:

```
Extracting packages ...
An unexpected error has occurred, please consider sending the            |  10%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\anaconda\Miniconda\Scripts\conda-script.py", line 4, in <module
>
    sys.exit(main())
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\cli\main.py", line 1
95, in main
    args_func(args, p)
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\cli\main.py", line 2
02, in args_func
    args.func(args, p)
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\cli\main_create.py",
 line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\cli\install.py", lin
e 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\plan.py", line 537,
in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\instructions.py", li
ne 148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\instructions.py", li
ne 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Users\anaconda\Miniconda\lib\site-packages\conda\install.py", line 48
5, in extract
    t.extractall(path=path)
  File "C:\Users\anaconda\Miniconda\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\Users\anaconda\Miniconda\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Users\anaconda\Miniconda\lib\tarfile.py", line 2191, in _extract_memb
er
    self.makefile(tarinfo, targetpath)
  File "C:\Users\anaconda\Miniconda\lib\tarfile.py", line 2231, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Users\\anaconda\\Miniconda\\pkgs\\p
ython-2.7.11-1\\DLLs\\_ctypes.pyd'
```

It seems like there is a permissions or lock issue that doesn't allow touching the current python package dir?

**Comment by msarahan** [comment] 2016-01-22 18:39
I think this is a duplicate of #1961 - my suggestion remains the same: run your long-running processes with a separate Miniconda installation.  You will never be able to update files on Windows when they are in use.

**Comment by msarahan** [comment] 2016-01-22 18:43
Your main alternative here, if separate installations are not an option, is to do much more explicit updates (list all packages), and limit dependencies to those that are not in use.

**Comment by PeterDSteinberg** [comment] 2016-01-22 18:46
@srossross does the windows deployment with 2 Miniconda installations make sense to you?

**Closed** 2017-05-01 21:13 UTC
