### ISSUE TITLE
conda update [anything] not working (as well as a number of other commands)

### ISSUE THREAD

**Issue by MattJEM** [conda/conda#6767] opened 2018-01-23 05:29 UTC
Submitting a bug report. Running conda 4.4.7, conda-build 3.2.2, python 2.7. I'm getting error reports with `conda update`, `conda info`, `conda config [anything]`, and so on. Here's the results for the requested info--all produce error reports.

<details open><summary><code>`conda update [foo]`</code></summary><p>

```

 >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 225, in __init__
        argparse_args=argparse_args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/collections.py", line 69, in __init__
        self.__update(*args, **kwds)
      File "/home/abc/anaconda2/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/loader.py", line 63, in __init__
        RoundTripConstructor.__init__(self, preserve_quotes=preserve_quotes, loader=self)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 66, in __init__
        self.allow_duplicate_keys = version_tnf((0, 15, 1), (0, 16))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/compat.py", line 200, in version_tnf
        from ruamel_yaml import version_info  # NOQA
    ImportError: cannot import name version_info

`$ /home/abc/anaconda2/bin/conda update --all`

  environment variables:
                 CIO_TEST=<not set>
          COMPIZ_BIN_PATH=/usr/bin/
               CONDA_ROOT=/home/abc/anaconda2
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/abc/anaconda2/bin:/home/abc/bin:/home/abc/.local/bin:/usr/local/
                          sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loca
                          l/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : None
       user config file : /home/abc/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : 3.2.2
         python version : 2.7.14.final.0
       base environment : /home/abc/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/abc/anaconda2/pkgs
                          /home/abc/.conda/pkgs
       envs directories : /home/abc/anaconda2/envs
                          /home/abc/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/2.7.14 Linux/4.13.0-26-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

</p></details>

<details open><summary><code>`conda info`</code></summary><p>

```
 
>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 225, in __init__
        argparse_args=argparse_args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/collections.py", line 69, in __init__
        self.__update(*args, **kwds)
      File "/home/abc/anaconda2/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/loader.py", line 63, in __init__
        RoundTripConstructor.__init__(self, preserve_quotes=preserve_quotes, loader=self)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 66, in __init__
        self.allow_duplicate_keys = version_tnf((0, 15, 1), (0, 16))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/compat.py", line 200, in version_tnf
        from ruamel_yaml import version_info  # NOQA
    ImportError: cannot import name version_info

`$ /home/abc/anaconda2/bin/conda info`
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 225, in __init__
        argparse_args=argparse_args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/collections.py", line 69, in __init__
        self.__update(*args, **kwds)
      File "/home/abc/anaconda2/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/loader.py", line 63, in __init__
        RoundTripConstructor.__init__(self, preserve_quotes=preserve_quotes, loader=self)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 66, in __init__
        self.allow_duplicate_keys = version_tnf((0, 15, 1), (0, 16))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/compat.py", line 200, in version_tnf
        from ruamel_yaml import version_info  # NOQA
    ImportError: cannot import name version_info

`$ /home/abc/anaconda2/bin/conda config --show-sources`

  environment variables:
                 CIO_TEST=<not set>
          COMPIZ_BIN_PATH=/usr/bin/
               CONDA_ROOT=/home/abc/anaconda2
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/abc/anaconda2/bin:/home/abc/bin:/home/abc/.local/bin:/usr/local/
                          sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loca
                          l/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : None
       user config file : /home/abc/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : 3.2.2
         python version : 2.7.14.final.0
       base environment : /home/abc/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/abc/anaconda2/pkgs
                          /home/abc/.conda/pkgs
       envs directories : /home/abc/anaconda2/envs
                          /home/abc/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/2.7.14 Linux/4.13.0-26-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

 >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 225, in __init__
        argparse_args=argparse_args)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/collections.py", line 69, in __init__
        self.__update(*args, **kwds)
      File "/home/abc/anaconda2/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/conda/common/serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/loader.py", line 63, in __init__
        RoundTripConstructor.__init__(self, preserve_quotes=preserve_quotes, loader=self)
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 66, in __init__
        self.allow_duplicate_keys = version_tnf((0, 15, 1), (0, 16))
      File "/home/abc/anaconda2/lib/python2.7/site-packages/ruamel_yaml/compat.py", line 200, in version_tnf
        from ruamel_yaml import version_info  # NOQA
    ImportError: cannot import name version_info

`$ /home/abc/anaconda2/bin/conda list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
          COMPIZ_BIN_PATH=/usr/bin/
               CONDA_ROOT=/home/abc/anaconda2
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/abc/anaconda2/bin:/home/abc/bin:/home/abc/.local/bin:/usr/local/
                          sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loca
                          l/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : None
       user config file : /home/abc/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : 3.2.2
         python version : 2.7.14.final.0
       base environment : /home/abc/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/abc/anaconda2/pkgs
                          /home/abc/.conda/pkgs
       envs directories : /home/abc/anaconda2/envs
                          /home/abc/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/2.7.14 Linux/4.13.0-26-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

```
</p></details>


Thank you!

Addendum: I CAN run programs. They may produce errors before launching, but they run normally. These are all on $PATH though--no `conda [whatever]` to run them.

**Comment by kalefranz** [comment] 2018-01-23 16:05
This is a duplicate of #6755. See that issue for solution.

**Closed by kalefranz** 2018-01-23 16:05 UTC
