### ISSUE TITLE
Timestamp appears lower in priority than number of pkgs criterion

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5882] opened 2017-08-25 00:53 UTC
Title is my theory more than anything.  With my new MKL packages, I have 5 builds so far:

```
conda search --override-channels -c msarahan mkl
Loading channels: done
Name                       Version                   Build  Channel
mkl                        2018.0.0             h1bd1d16_4  msarahan
mkl                        2018.0.0             h47df402_4  msarahan
mkl                        2018.0.0             h5077ac0_4  msarahan
mkl                        2018.0.0             h5f440b7_0  msarahan
mkl                        2018.0.0             hb1dadce_4  msarahan
```

h5077ac0_4 is the most recent.  If I run a test creation command, I get an older version:

```
conda create -n mkltest -c msarahan mkl

Solving environment: done

## Package Plan ##

  environment location: /Users/msarahan/miniconda3/envs/mkltest

  added / updated specs:
    - mkl


The following NEW packages will be INSTALLED:

    icc_rt: 16.0.3-h28e9f76_4   msarahan
    mkl:    2018.0.0-h1bd1d16_4 msarahan

Proceed ([y]/n)? n
```

However, when an exact spec is provided for the latest version, we can actually install it:

```
conda create -n mkltest -c msarahan mkl=2018.0.0=h5077ac0_4
Solving environment: done

## Package Plan ##

  environment location: /Users/msarahan/miniconda3/envs/mkltest

  added / updated specs:
    - mkl==2018.0.0=h5077ac0_4


The following NEW packages will be INSTALLED:

    icc_rt:       16.0.3-h28e9f76_4   msarahan
    intel-openmp: 2018.0.0-h28e9f76_4 msarahan
    mkl:          2018.0.0-h5077ac0_4 msarahan

Proceed ([y]/n)? n
```

The repodata entry for the h1bd1d16_4 build is here.  It has one dependency.

```
"mkl-2018.0.0-h1bd1d16_4.tar.bz2":{"timestamp":1502815658750,
"depends":["icc_rt"],"arch":"x86_64","operatingsystem":"darwin","target-triplet":"x86_64-any-darwin","size":155074161,"build_number":4,"name":"mkl","license":"proprietary - Intel","has_prefix":false,"license_family":"Proprietary","machine":"x86_64","platform":"osx","version":"2018.0.0","build":"h1bd1d16_4","binstar":{"package_id":"5993244f07006a12ce26bd22","channel":"main","owner_id":"55fac6e4d3234d09d295156c"},"md5":"3fa955642b0bc1873e3b407f2b5ee58b","requires":[],"subdir":"osx-64"}
```

The repodata for the current build, h5077ac0_4 is here.  It has two dependencies.

```
"mkl-2018.0.0-h5077ac0_4.tar.bz2":{"timestamp":1503615970929,
"depends":["icc_rt","intel-openmp"],
"arch":"x86_64","operatingsystem":"darwin","target-triplet":"x86_64-any-darwin","size":155039165,"build_number":4,"name":"mkl","license":"proprietary - Intel","has_prefix":false,"license_family":"Proprietary","machine":"x86_64","platform":"osx","version":"2018.0.0","build":"h5077ac0_4","binstar":{"package_id":"5993244f07006a12ce26bd22","channel":"main","owner_id":"55fac6e4d3234d09d295156c"},"md5":"6340dd0e05d8955c6b958df97e27733b","requires":[],"subdir":"osx-64"}
```

The newer package has one more dependency - the old build was wrong in omitting it.  I believe this is finally perhaps a smoking gun of sorts in timestamps not being respected.

CC @mcg1969 @kalefranz

**Comment by mcg1969** [comment] 2017-08-25 01:44
Is it possible that this is simply a matter of ordering? Should we be negating the timestamp in the version key? It seems like we should

**Comment by msarahan** [comment] 2017-08-25 02:02
I'm very confused.  I thought the timestamp was already something that came after the version key.  First package name, then version, finally timestamp, and then lexicographic build string.  Is there something else I'm missing?

**Comment by msarahan** [comment] 2017-08-25 02:12
Scratch that, I think you might be right.  I think the fix in 4.3.x has not been ported to 4.4.x.

```
 msarahan@0109-msarahan-2  ~/code/conda   4.3.x  conda create -n mkltest -c msarahan mkl
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /Users/msarahan/miniconda3/envs/mkltest:

The following NEW packages will be INSTALLED:

    icc_rt:       16.0.3-h28e9f76_4   msarahan
    intel-openmp: 2018.0.0-h28e9f76_4 msarahan
    mkl:          2018.0.0-h5077ac0_4 msarahan

Proceed ([y]/n)? n

Exiting

 ✘ msarahan@0109-msarahan-2  ~/code/conda   4.3.x  git checkout 4.4.x
Switched to branch '4.4.x'
Your branch is up-to-date with 'origin/4.4.x'.
 msarahan@0109-msarahan-2  ~/code/conda   4.4.x  conda create -n mkltest -c msarahan mkl
Solving environment: done

## Package Plan ##

  environment location: /Users/msarahan/miniconda3/envs/mkltest

  added / updated specs:
    - mkl


The following NEW packages will be INSTALLED:

    icc_rt: 16.0.3-h28e9f76_4   msarahan
    mkl:    2018.0.0-h1bd1d16_4 msarahan

Proceed ([y]/n)? n
```

**Comment by mcg1969** [comment] 2017-08-25 21:13
> I'm very confused. I thought the timestamp was already something that came after the version key. First package name, then version, finally timestamp, and then lexicographic build string. Is there something else I'm missing?

What I'm referring to is the _sign_ of the timestamp. The version key should be sorting the packages in order of priority, with highest priority first. But if the timestamps are increasing, that will put the newer packages later in the list, right?

[This](https://github.com/conda/conda/blob/master/conda/resolve.py#L412-L415) is what I'm referring to. Note that channel priority is negated. But timestamp never has been, since it was first [committed](https://github.com/conda/conda/blob/84a9bae3ae78c8fa6afe09d37dcdbbe70b1f976d/conda/resolve.py#L536-L537).

**Comment by kalefranz** [comment] 2017-10-10 21:31
I believe we now have this solved.  I've also seen places where I've reproduced this type of behavior with older versions of conda, and it's fixed in newer versions of conda.  I'm going to close this issue.  If anyway disagrees, we can reopen it.

**Closed by kalefranz** 2017-10-10 21:31 UTC
Labels: source:core, type:bug
