### ISSUE TITLE
[Bug] conda removes folders from working directory when they share name with environment

### ISSUE THREAD

**Issue by Korijn** [conda/conda#3383] opened 2016-09-06 06:19 UTC
conda removes folders from working directory when they share their name with the environment that you want to delete. You can find a minimal reproduction at the tagged commit linked here:

https://github.com/Korijn/condabug/tree/conda-env-remove
# Steps to reproduce

Run the following command from the root of the repository:

``` batch
> conda env create
> conda remove -n hw --all -y
```

_Conda has now deleted not only the `hw` environment but also the `hw` source folder!_

Since `conda env remove`'s behavior was redirect to the same code in a fairly recent release, you can also reproduce the bug like this:

``` batch
> conda env create
> conda env remove -n hw -y
```

You can even cause the behavior after the environment has already been deleted.
# conda info

``` batch
> conda info                                                                        
Current conda install:                                                              

             platform : win-64                                                      
        conda version : 4.1.11                                                      
    conda-env version : 2.5.2                                                       
  conda-build version : 2.0.0                                                       
       python version : 3.5.1.final.0                                               
     requests version : 2.9.1                                                       
     root environment : C:\Users\korij\Miniconda3  (writable)                       
  default environment : C:\Users\korij\Miniconda3                                   
     envs directories : C:\Users\korij\Miniconda3\envs                              
        package cache : C:\Users\korij\Miniconda3\pkgs                              
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/win-64/    
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/    
                        https://repo.continuum.io/pkgs/free/win-64/                 
                        https://repo.continuum.io/pkgs/free/noarch/                 
                        https://repo.continuum.io/pkgs/pro/win-64/                  
                        https://repo.continuum.io/pkgs/pro/noarch/                  
                        https://repo.continuum.io/pkgs/msys2/win-64/                
                        https://repo.continuum.io/pkgs/msys2/noarch/                
          config file : C:\Users\korij\.condarc                                     
         offline mode : False                                                       
    is foreign system : False                                                       
```

**Comment by Korijn** [comment] 2016-09-16 08:36
@msarahan this needs a bug label or something :)

**Comment by dmopalmer** [comment] 2016-10-06 23:28
This bug bites even if there never was an environment with the name.

Very extremely bad.

**Comment by Korijn** [comment] 2016-10-07 05:44
@msarahan @kalefranz this needs a bug label!

**Comment by Korijn** [comment] 2016-11-16 09:27
This appears to have been fixed in some version of conda, but I can't tell where it happened.

I can at least confirm it's fixed on 4.2.12

**Comment by Korijn** [comment] 2017-09-14 08:58
I was finally able to reproduce this on latest conda, see PR #5965

**Comment by ijstokes** [comment] 2017-10-23 20:12
I believe #5867 is a duplicate of this.  Someone on the Anaconda ML also reported that

```
conda remove -p /some/typo/path --all
```

deleted the mis-typed path `/some/typo/path` (in the case of that person it was their home directory, I think).

Seems like conda should do some kind of sanity check to make sure it is actually a conda environment that lives in that location (path or name).

**Comment by elehcim** [comment] 2017-10-26 11:30
I just hit this bug. I sweated heavily when I saw the folder disappear and I didn't understand why. Luckily I was able to recover the folder. This is extremely dangerous.

**Comment by kalefranz** [comment] 2018-01-26 07:14
Fixed now in latest I think.

```
kfranz@0283:~/continuum/conda fix-insecure-flag ❯ ls -al
total 1272
drwxr-xr-x  32 kfranz  staff   1.0K Jan 26 00:29 ./
drwxr-xr-x  84 kfranz  staff   2.6K Dec 23 11:35 ../
-rw-r--r--@  1 kfranz  staff   6.0K Jun 13  2017 .DS_Store
drwxr-xr-x   3 kfranz  staff    96B Jan 25 17:17 .cache/
-rw-r--r--   1 kfranz  staff   365B Jan 24 11:39 .codecov.yml
-rw-r--r--   1 kfranz  staff    39K Jan 24 11:32 .coverage
drwxr-xr-x  18 kfranz  staff   576B Jan 26 01:13 .git/
drwxr-xr-x   3 kfranz  staff    96B Jan 25 18:19 .github/
-rw-r--r--   1 kfranz  staff   258B Jan 24 11:39 .gitignore
drwxr-xr-x  12 kfranz  staff   384B Jan 26 00:42 .idea/
drwxr-xr-x   3 kfranz  staff    96B Dec  6  2016 .vagrant/
-rw-r--r--   1 kfranz  staff   112K Jan 26 00:29 CHANGELOG.md
-rw-r--r--   1 kfranz  staff   1.7K Jan 24 11:39 LICENSE.txt
-rw-r--r--   1 kfranz  staff   167B Jan 24 04:10 MANIFEST.in
-rw-r--r--   1 kfranz  staff   2.5K Jan 24 11:39 Makefile
-rw-r--r--   1 kfranz  staff   6.8K Jan 24 11:39 README.rst
-rw-r--r--   1 kfranz  staff   902B Dec  6  2016 Vagrantfile
drwxr-xr-x   4 kfranz  staff   128B Jan 25 18:41 __pycache__/
-rw-r--r--   1 kfranz  staff   3.2K Jan 24 11:39 appveyor.yml
-rw-r--r--   1 kfranz  staff   8.5K Jan 24 11:39 circle.yml
drwxr-xr-x  39 kfranz  staff   1.2K Jan 26 00:29 conda/
drwxr-xr-x   6 kfranz  staff   192B Jan 24 11:39 conda.recipe/
drwxr-xr-x  16 kfranz  staff   512B Jan 25 19:41 conda_env/
-rw-r--r--   1 kfranz  staff   773B Jan 24 11:40 conftest.py
-rw-r--r--   1 kfranz  staff   413K Jan 24 11:32 coverage.xml
drwxr-xr-x   5 kfranz  staff   160B Dec  7 16:01 docs/
drwxr-xr-x  11 kfranz  staff   352B Oct  2 12:54 env/
drwxr-xr-x   2 kfranz  staff    64B Dec 19 17:36 rust/
-rw-r--r--   1 kfranz  staff   1.7K Jan 24 11:40 setup.cfg
-rw-r--r--   1 kfranz  staff   3.9K Jan 24 11:40 setup.py
drwxr-xr-x  44 kfranz  staff   1.4K Jan 26 00:31 tests/
drwxr-xr-x  14 kfranz  staff   448B Jan 24 12:15 utils/
kfranz@0283:~/continuum/conda fix-insecure-flag ❯ python -m conda_env remove -n utils

EnvironmentLocationNotFound: Not a conda environment: /usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/envs/utils

(1)kfranz@0283:~/continuum/conda fix-insecure-flag ❯ python -m conda_env remove -n utils -y

EnvironmentLocationNotFound: Not a conda environment: /usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/envs/utils

```

**Closed by kalefranz** 2018-01-26 07:14 UTC

**Comment by Korijn** [comment] 2018-01-26 07:53
Is it also covered by a test case now?
