### ISSUE TITLE
Support nested boolean expressions for version range definitions in environment.yml

### ISSUE THREAD

**Issue by ArneBachmannDLR** [conda/conda#11122] opened 2022-01-03 12:00 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

I'd like to express different versions ranges for Python package dependencies, but constrained by the Python version used.

Somewhat working example from `Lib\site-packages\mypackage-version.dist-info\METADATA`:
```
Requires-Dist: ruamel.yaml (>=0.17.17) ; python_version >= "3.10"
Requires-Dist: ruamel.yaml (>=0.16.13,<0.17) ; python_version < "3.10"
```

There is, however, no way to specify combinations of AND and OR version expressions in the environment definition YAML file, and putting the expressions on two lines fails as well. I tried many combinations of `,`, `;`, spacing and escaping, to no avail.

Is conda able, at all, to parse and understand above definitions?

### Why is this needed

To allow specific version ranges for different Python versions or architectures.

### What should happen?

The version range must be a fully parsed tree of AND and OR expressions.

**Comment by kenodegard** [comment] 2022-01-13 00:44
no we do not support selectors in the `environment.yml` files at this time

this is a duplicate of #8089

**Closed by kenodegard** 2022-01-13 00:44 UTC
Labels: type::feature, source::community, plugins::env, duplicate
