### ISSUE TITLE
Automatically set PKG_CONFIG_PATH when activating an environment

### ISSUE THREAD

**Issue by multimeric** [conda/conda#13691] opened 2024-03-14 05:20 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Activating a conda environment should expose the `pkg-config` inside the environment to current shell. 

### Why is this needed?

Currently, activating a conda environment updates the `PATH` to add executables to the calling shell, but doesn't do anything to expose libraries in the same way. Adding this mechanism would allow for users to compile software using conda packages, but without forcing the software to also live in the conda environment.

### What should happen?

`conda activate` should set `PKG_CONFIG_PATH=$CONDA_PREFIX/lib/pkg-config` as part of the activate script. 
Because this change would potentially break existing compilation workflows, I'm imagining it would have to be hidden behind a flag, for example: `conda activate --pkg-config my_env`.

### Additional Context

A similar issue has been discussed in terms of setting the `LD_LIBRARY_PATH` on activate. This proposal has been rejected because of potential linking errors this might cause. However I believe the `pkg-config` mechanism is safe from such issues

**Comment by travishathaway** [comment] 2024-03-15 10:11
Hi @multimeric,

Thanks for this feature request. I think to get this conversation started, it would help if you could site a specific example of what this would allow you to do. I'm really curious about the specific use case you have where you would need to compile with software residing outside the conda environment.

**Comment by multimeric** [comment] 2024-03-15 10:47
I support the use of an HPC cluster. Frequently our users need to use or compile software that has library dependencies, but they can't use a system package manager because they don't have root. In theory, conda solves this quite well because it provides pre-compiled packages that install very quickly when using mamba. conda is also preferred to other package managers because the bioconda channel has made conda a very well known package manger in bioinformatics circles.

There are a few reasons why the software our users want to install (the end user software) can't "live" inside a conda environment, where it would automatically be able to access that environment's libraries.

One reason is because it's an R or Python package that needs to live in the user's local library alongside their other packages. You might argue that having a local library at all is a poor practise, and I agree in many situations. However, it's a necessity at my workplace because:
* Lack of storage space disincentives per-project virtual environments and conda environments due to package duplication 
* There is a tradition of installing packages in this way, and users are unlikely to want to migrate an entire project and all its dependencies into a conda environment when earlier work didn't require this.
* We encourage the use of R and Python binaries provided by the module system. These are optimised for the HPC and sometimes have site-specific tweaks. If a project were to fully embrace conda, that would mean using conda's Python or R rather than the HPC's Python or R.

Another, possibly more important use case is software that isn't packaged at all, so it can't be neatly installed into a prefix.  Instead it might be a repository with a Makefile that compiles some software in the current directory, but requires some native libraries to do so. This is very common in bioinformatics. Ideally all software would be packaged in conda to avoid this issue, but this is not the reality.

In both of these scenarios, a conda environment that lives alongside the end-user software that provides the native libraries would offer a neat, simple solution.

**Comment by rgommers** [comment] 2024-03-20 16:34
> A similar issue has been discussed in terms of setting the `LD_LIBRARY_PATH` on activate. This proposal has been rejected because of potential linking errors this might cause. However I believe the `pkg-config` mechanism is safe from such issues

Doing this will not be free of issues or foot guns I think. One that come to mind: if a library is installed in both a system directory (e.g., `/usr/lib/`) and in a conda env's libdir, this would change what library gets picked depending on whether `pkg-config` itself is installed in the conda env yes or no. It goes from doing the right thing to always preferring the library in the conda env, so it potentially breaks things for users who don't want to depend on the conda library (can get a changed library version, or a broken application if the conda env gets removed or updated).

> Another, possibly more important use case is software that isn't packaged at all, so it can't be neatly installed into a prefix. Instead it might be a repository with a Makefile that compiles some software in the current directory, but requires some native libraries to do so

These use cases are valid and interesting, but it's a simple one-liner for the user to either set `PKG_CONFIG_PATH` themselves or to install `pkg-config` into the conda env. So I don't quite see what's being gained here if this proposal would be accepted and implemented. If HPC cluster users _intentionally_ want to mix system and conda libraries, they shouldn't have an issue with understanding the one-liner. And if it's more _accidental_ mixing that you want to promote, that is probably not a desirable outcome.

**Comment by multimeric** [comment] 2024-03-23 11:51
Consider though that just by updating the `PATH`, the exact same thing can happen. If you have `gcc` in the environment, your library search path will update (`gcc -print-search-dirs`), and the same goes for `pkg-config`. Which begs the question why I can't use that mechanism, and the answer is I probably can. It seems that `pkg-config` is not a dependency of most packages so it has to be manually installed in the environment, but once it is, everything seems to work automatically

**Comment by rgommers** [comment] 2024-03-23 16:22
I'm not 100% sure what you're saying here, or if you're proposing to still make a change. `PATH` isn't relevant I think. `pkg-config` in an activated env knows where to look:
```
$ pkg-config --variable pc_path pkg-config
/path/to/env/lib/pkgconfig:/path/to/env/share/pkgconfig
```
and the library search path is handled for compilers is handled in compiler activation by setting `LDFLAGS`:
```
$ echo $LDFLAGS
-Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/path/to/env/lib -L/path/to/env/lib
```

**Comment by multimeric** [comment] 2024-03-24 00:08
Okay so your concern with updating `PKG_CONFIG_PATH` was that it would affect unrelated compilations, correct? My argument was that this *already* happens, because certain build tools from the environment such as `pkg-config` will get added to your `PATH` and therefore affect these compilations anyway. I also noted that I could use this mechanism deliberately, and specifically install the `pkg-config` package to add it to my PATH and more or less get the behaviour I want.

**Comment by rgommers** [comment] 2024-03-24 09:32
Sure, if you take the action of installing `pkg-config` inside the env and activate it, then it's on the path and will take precedence over a `pkg-config` in `/usr/bin/` or elsewhere. That is things working as designed.

For more context: conda envs set a number of environment variables on environment activation with compilers installed. This is necessary to make things work, but _should be kept to an absolute minimum_. Each unnecessary addition to for example `CFLAGS`/`LDFLAGS` causes a problem somewhere else. What is added now is already too much. Proposals to add more, like this one, should be rejected unless absolutely necessary.

Since you have now figured out how to make things work by installing `pkg-config` (or setting `PKG_CONFIG_PATH`), can you please close this issue?

**Closed** 2024-03-24 09:42 UTC
Labels: type::feature, source::community
