### ISSUE TITLE
MD5MismatchError and line 376: INST_OPT: unbound variable error

### ISSUE THREAD

**Issue by qiaoqiaozhu** [conda/conda#8720] opened 2019-05-24 17:03 UTC
## Current Behavior

I was having trouble installing chromedriver, then I decided to delete the old installation and did a reinstall from fresh. However, I had problem with the latest installer. I'm on a mac os 10.14.5

First, with graphic installer, I run into the following whenever I run conda update, or for most of the conda install:

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/certifi-2019.3.9-py37_0.tar.bz2'.
  download saved to: /Users/qiaoqiaozhu/anaconda3/pkgs/certifi-2019.3.9-py37_0.tar.bz2
  expected md5 sum: addbd3c2a740fb8e1af9027fb65a600c
  actual md5 sum: 6068906673260f66506c4f3f4d597a87

Then I tried the commend line installation, and run into this:
Anaconda3-2019.03-MacOSX-x86_64.sh: line 376: INST_OPT: unbound variable

**Comment by engalexm** [comment] 2019-05-24 17:29
I am also having mismatch errors on the latest Mac OS

**Comment by msarahan** [comment] 2019-05-24 17:35
The index has been reverted. You may need to run

conda clean -iy

to clean out the index cache.

**Comment by ahpd** [comment] 2019-05-24 17:55
Having a similar issue setting up a new conda env:
```
➜  ~ conda create -y -n bob python==3.6.5
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/bob

  added / updated specs:
    - python==3.6.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.3.9           |           py36_0         152 KB
    openssl-1.0.2r             |       h1de35cc_0         1.9 MB
    setuptools-41.0.1          |           py36_0         506 KB
    wheel-0.33.4               |           py36_0          41 KB
    ------------------------------------------------------------
                                           Total:         2.6 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/osx-64::certifi-2019.3.9-py36_0
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.0.2r-h1de35cc_0
  pip                pkgs/main/osx-64::pip-19.1.1-py36_0
  python             pkgs/main/osx-64::python-3.6.5-hc167b69_1
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-41.0.1-py36_0
  sqlite             pkgs/main/osx-64::sqlite-3.28.0-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.33.4-py36_0
  xz                 pkgs/main/osx-64::xz-5.2.4-h1de35cc_4
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3



Downloading and Extracting Packages
setuptools-41.0.1    | 506 KB    | ###########################################################################################################################################################2                                                    |  75%
certifi-2019.3.9     | 152 KB    | ###########################################################################################################################################################2                                                    |  75%
openssl-1.0.2r       | 1.9 MB    | ###########################################################################################################################################################2                                                    |  75%
wheel-0.33.4         | 41 KB     | ###########################################################################################################################################################2                                                    |  75%

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/setuptools-41.0.1-py36_0.tar.bz2'.
  download saved to: /anaconda3/pkgs/setuptools-41.0.1-py36_0.tar.bz2
  expected md5 sum: e92e5f9e9ca806f56ce27c0a143c9532
  actual md5 sum: 38316060f5d85f7028bb5cdc3e21bb4f

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/certifi-2019.3.9-py36_0.tar.bz2'.
  download saved to: /anaconda3/pkgs/certifi-2019.3.9-py36_0.tar.bz2
  expected md5 sum: f943a2dffa0a03192d740d890be71799
  actual md5 sum: d96de1e011d41f9a004f6f488aeec85c

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.0.2r-h1de35cc_0.tar.bz2'.
  download saved to: /anaconda3/pkgs/openssl-1.0.2r-h1de35cc_0.tar.bz2
  expected md5 sum: 5ab29116447945a2ef1669e878e43fda
  actual md5 sum: 6db1ff746c7cce337a69fb44fae3424e

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/wheel-0.33.4-py36_0.tar.bz2'.
  download saved to: /anaconda3/pkgs/wheel-0.33.4-py36_0.tar.bz2
  expected md5 sum: 0ce21499e39329a9c8701e18beb713d2
  actual md5 sum: 2da70e49e3cb8c89666ac4260616ff07
```

**Comment by qiaoqiaozhu** [comment] 2019-05-24 17:57
I run "conda clean -iy", it doesn't solve the problem.

**Comment by war5** [comment] 2019-05-24 18:11
im having the same issue on mac os x im trying to update conda and it gives me 
`MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/conda-4.6.14-py37_0.tar.bz2'.
  download saved to: /usr/local/anaconda3/pkgs/conda-4.6.14-py37_0.tar.bz2
  expected md5 sum: fa49d46d833a333ce023775bbac99215
  actual md5 sum: efdbcc39ce8a6455706b65c2a2d30b87`

I tried "conda clean -iy" and it doesnt solve the problem. my expected md5 sum is still the same as before i ran the clean command.

**Comment by laiviet** [comment] 2019-05-24 18:14
Anyone sees the progress bar, it shows 75% downloaded not 100%?

**Comment by thv92** [comment] 2019-05-24 18:18
@laiviet I'm also getting that same issue when creating an environment for python 2.7.16

**Comment by hponde** [comment] 2019-05-24 18:19
I did run `conda clean -iy` but it didn't fix the problem:

```
>>> conda create -n tests python=3.6
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/hponde/anaconda3/envs/tests

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-19.1.1                 |           py36_0         1.6 MB
    setuptools-41.0.1          |           py36_0         506 KB
    wheel-0.33.4               |           py36_0          41 KB
    ------------------------------------------------------------
                                           Total:         2.2 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/osx-64::certifi-2019.3.9-py36_0
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1b-h1de35cc_1
  pip                pkgs/main/osx-64::pip-19.1.1-py36_0
  python             pkgs/main/osx-64::python-3.6.8-haf84260_0
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-41.0.1-py36_0
  sqlite             pkgs/main/osx-64::sqlite-3.28.0-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.33.4-py36_0
  xz                 pkgs/main/osx-64::xz-5.2.4-h1de35cc_4
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-19.1.1           | 1.6 MB    | #############################################################################################                                |  75%
setuptools-41.0.1    | 506 KB    | #############################################################################################                                |  75%
wheel-0.33.4         | 41 KB     | #############################################################################################                                |  75%

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/pip-19.1.1-py36_0.tar.bz2'.
  download saved to: /Users/hponde/anaconda3/pkgs/pip-19.1.1-py36_0.tar.bz2
  expected md5 sum: 42e597a30bae316bea673e9eb8b8a6dc
  actual md5 sum: 9af4eb5f07d44157fa8d6518319c6249

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/setuptools-41.0.1-py36_0.tar.bz2'.
  download saved to: /Users/hponde/anaconda3/pkgs/setuptools-41.0.1-py36_0.tar.bz2
  expected md5 sum: e92e5f9e9ca806f56ce27c0a143c9532
  actual md5 sum: 38316060f5d85f7028bb5cdc3e21bb4f

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/wheel-0.33.4-py36_0.tar.bz2'.
  download saved to: /Users/hponde/anaconda3/pkgs/wheel-0.33.4-py36_0.tar.bz2
  expected md5 sum: 0ce21499e39329a9c8701e18beb713d2
  actual md5 sum: 2da70e49e3cb8c89666ac4260616ff07
```

**Comment by christopherpetrino** [comment] 2019-05-24 18:21
```
Collecting package metadata: done
Solving environment: done

Downloading and Extracting Packages
pytest-4.5.0         | 355 KB    | ##################################################################                       |  75%
more-itertools-7.0.0 | 93 KB     | ##################################################################                       |  75%

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/pytest-4.5.0-py37_0.tar.bz2'.
  download saved to: /anaconda3/pkgs/pytest-4.5.0-py37_0.tar.bz2
  expected md5 sum: 388570599d003c0ceb69ba80994f163d
  actual md5 sum: 9936da04df763e7c77fc26ad65f1f275

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/more-itertools-7.0.0-py37_0.tar.bz2'.
  download saved to: /anaconda3/pkgs/more-itertools-7.0.0-py37_0.tar.bz2
  expected md5 sum: d273fd6ad3631c85b4ffc75fc9e48104
  actual md5 sum: 00e0f7b9559144fb8086d2f8875d451c
```

**Comment by hponde** [comment] 2019-05-24 18:21
I can also confirm that `conda create -n tests python=2.7` and `conda create -n tests python=3.6` fail but `conda create -n tests python=3.7` succeeds!

**Comment by laiviet** [comment] 2019-05-24 18:24
@hponde Which conda version are you using?
I failed with miniconda 4.4.10

**Comment by hponde** [comment] 2019-05-24 18:26
My conda version is `conda 4.6.14`

**Comment by laiviet** [comment] 2019-05-24 18:31
```
conda clean -iy
conda create -n py37 python=3.7
```
Does not work with 4.6.14 on MacOS

**Comment by tveldhui** [comment] 2019-05-24 18:35
I'm also having this problem, Julia 1.1 and MacOS 10.12.6.

```
│ MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
│ for url 'https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.16.3-py37h6575580_0.tar.bz2'.
│   download saved to: /Users/tveldhui/.julia/conda/3/pkgs/numpy-base-1.16.3-py37h6575580_0.tar.bz2
│   expected md5 sum: f7f43aa5c4df4c5c1f5ba8484150dfce
│   actual md5 sum: 230eefd691f74ec074cc95ec1681baf5
│ 
│ MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
│ for url 'https://repo.anaconda.com/pkgs/main/osx-64/mkl_fft-1.0.12-py37h5e564d8_0.tar.bz2'.
│   download saved to: /Users/tveldhui/.julia/conda/3/pkgs/mkl_fft-1.0.12-py37h5e564d8_0.tar.bz2
│   expected md5 sum: 0702dfcae21520ceaa5a26a41e0d1752
│   actual md5 sum: fc0fc362086fef7227b963ef70d04b3f
│ ...
```

**Comment by hponde** [comment] 2019-05-24 18:39
@laiviet in my setup (`conda 4.6.14`) this did work:

```
conda clean -iy
conda create -n py37 python=3.7
```

And in fact `3.7` for me is the only version that works, `3.6` and `2.7` does not work

**Comment by tonyabracadabra** [comment] 2019-05-24 18:42
I did run conda clean -iy but it didn't fix the problem, I think this is a problem that occurs to many of us. 
 Not sure if it is caused by anaconda's server or the version I am using?

**Comment by msarahan** [comment] 2019-05-24 19:05
It's caused by bad data in repodata.json.bz2, which conda prefers to repodata.json.

We are reverting it, and things should be back to normal in a few minutes.

**Comment by glaserL** [comment] 2019-05-24 19:13
Version 4.6.11

I experienced similar issues. I tried `conda clean -iy` and even `conda clean -a`. Also recreating an environment does not help completely.

I was able to install numpy, tensorflow, keras and tqdm in a newly created environment, however adding pygame with `conda install -c cogsci pygame` caused the issues mentioned above. Also I can't update conda with `conda update -n base -c defaults conda`

and @laiviet I also see that it fails, when any download stops at 75%.

Hope anyone can help with this?

**Comment by msarahan** [comment] 2019-05-24 19:14
It's not going to work until repodata.json.bz2 is fixed.  It's being uploaded now.  Please try again in a few minutes.

**Comment by glaserL** [comment] 2019-05-24 19:15
should've refreshed before posting, thanks!

**Comment by msarahan** [comment] 2019-05-24 19:27
reverted repodata is in place.  If the problem persists, try ``conda clean -iy`` - if that still doesn't work, let us know.

**Comment by laiviet** [comment] 2019-05-24 19:28
work for ```conda 4.4.10``` on MacOS

**Comment by thv92** [comment] 2019-05-24 19:29
works for 4.6.14 on MacOS! Thanks!

**Comment by tveldhui** [comment] 2019-05-24 19:30
Working for me now.  Thanks also!

**Comment by hponde** [comment] 2019-05-24 19:32
Works for me as well. And for python versions `3.7`, `3.6` and `2.7`. Thanks!

**Comment by ahpd** [comment] 2019-05-24 19:33
Works on macos, thanks!

**Comment by msarahan** [comment] 2019-05-24 19:36
Sounds like we're back to normal. Thanks for the feedback. Closing the issue.

**Closed by msarahan** 2019-05-24 19:36 UTC
