### ISSUE TITLE
Issue when creating environment on ubuntu 64bit with dand-env-mac.yaml

### ISSUE THREAD

**Issue by wuming79** [conda/conda#6454] opened 2017-12-14 08:08 UTC
Hi,

Saw the msg to consider posting the following here. dand-env-mac.yaml is from the site "https://classroom.udacity.com/courses/ud170/lessons/5430778793/concepts/54140889150923"

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.1.3
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/osboxes/anaconda3  (writable)
    default environment : /home/osboxes/anaconda3
       envs directories : /home/osboxes/anaconda3/envs
                          /home/osboxes/.conda/envs
          package cache : /home/osboxes/anaconda3/pkgs
                          /home/osboxes/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.8.0-59-generic debian/stretch/sid glibc/2.24    
                UID:GID : 1000:1000

`$ /home/osboxes/anaconda3/bin/conda-env create -f dand-env-mac.yaml`

    Traceback (most recent call last):
      File "/home/osboxes/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/osboxes/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/osboxes/anaconda3/lib/python3.6/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
    TypeError: can only concatenate list (not "NoneType") to list

**Comment by kalefranz** [comment] 2018-01-24 23:12
Duplicate of https://github.com/conda/conda/issues/6454

**Closed by kalefranz** 2018-01-24 23:12 UTC
