### ISSUE TITLE
how to create environment

### ISSUE THREAD

**Issue by phani99** [conda/conda#5067] opened 2017-04-18 12:11 UTC
(C:\Users\phani bhushan\Anaconda3) C:\Users>conda env create -f aind-environment-windows.yml
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : C:\Users\phani bhushan\Anaconda3  (writable)
    default environment : C:\Users\phani bhushan\Anaconda3
       envs directories : C:\Users\phani bhushan\Anaconda3\envs
                          C:\Users\phani bhushan\AppData\Local\conda\conda\envs
                          C:\Users\phani bhushan\.conda\envs
          package cache : C:\Users\phani bhushan\Anaconda3\pkgs
                          C:\Users\phani bhushan\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.6.1 Windows/10 Windows/10.0.14393

`$ C:\Users\phani bhushan\Anaconda3\Scripts\conda-env-script.py create -f aind-environment-windows.yml`

    Traceback (most recent call last):
      File "C:\Users\phani bhushan\Anaconda3\lib\site-packages\conda\exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\phani bhushan\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Users\phani bhushan\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: aind-environment-windows.yml file not found
    There is no requirements.txt

**Comment by nehaljwani** [comment] 2017-04-19 19:12
Duplicate of #4328

**Closed** 2017-04-19 19:26 UTC
