### ISSUE TITLE
Fetching package metadata ...An unexpected error has occurred (  TypeError: 'NoneType' object does not support item assignment)

### ISSUE THREAD

**Issue by AbNeil** [conda/conda#7896] opened 2018-10-23 08:04 UTC
Hello,
While trying to install any package I get the following error. Tried installing in env also but nothing is working. 
conda install -c anaconda tensorflow-gpu 

Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.19
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/xmn/anaconda3  (writable)
    default environment : /home/xmn/anaconda3/envs/tensorflow
       envs directories : /home/xmn/anaconda3/envs
                          /home/xmn/.conda/envs
          package cache : /home/xmn/anaconda3/pkgs
                          /home/xmn/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/menpo/linux-64
                          https://conda.anaconda.org/menpo/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/xmn/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-96-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/xmn/anaconda3/envs/tensorflow/bin/conda install -c anaconda tensorflow-gpu`

    Traceback (most recent call last):
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 456, in fetch_repodata
        mod_etag_headers.get('_etag'), mod_etag_headers.get('_mod'))
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 388, in read_local_repodata
        process_repodata(local_repodata, channel_url, schannel, priority)
      File "/home/xmn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 412, in process_repodata
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

Any help will be much appreciated.

**Comment by sremm** [comment] 2018-10-26 12:42
Same issue here when trying "conda install -c anaconda tensorflow-gpu"

**Comment by msarahan** [comment] 2018-10-26 12:59
duplicate of #7870, closing

**Closed by msarahan** 2018-10-26 12:59 UTC
