### ISSUE TITLE
Whitespace in path to tmp requirements.txt

### ISSUE THREAD

**Issue by quartox** [conda/conda#8308] opened 2019-02-19 21:31 UTC
## Current Behavior

`conda env update -f conda-env.yaml` with conda-env.yaml containing a pip dependency on linux with whitespace in the directory name.

### Steps to Reproduce

```
conda env update -f conda-env.yaml
```

## Expected Behavior

Put slashes before the whitespace in the command.

I believe the relevant line is here (requirements.name specifically): https://github.com/conda/conda/blob/master/conda_env/installers/pip.py#L51 but I do not know the preferred method of handling whitespace in paths within the code base.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /nas/isg_prodops_work/openhands/anaconda
            shell level : 1
       user config file : /nas/hrthome/axrbohsf/.condarc
 populated config files : /nas/hrthome/axrbohsf/.condarc
          conda version : 4.6.4
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       base environment : /nas/isg_prodops_work/openhands/anaconda  (writable)
           channel URLs : defaults
                               conda-forge
          package cache : /nas/isg_prodops_work/openhands/anaconda/pkgs
                          /nas/hrthome/axrbohsf/.conda/pkgs
       envs directories : /nas/isg_prodops_work/openhands/local/envs
                          /nas/isg_prodops_work/openhands/anaconda/envs
                          /nas/hrthome/axrbohsf/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/3.7.2 Linux/3.10.0-957.5.1.el7.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 35595:5429
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /nas/hrthome/axrbohsf/.condarc <==
envs_dirs:
  - /nas/isg_prodops_work/openhands/local/envs
ssl_verify: False
channels:
  - defaults
  - conda-forge
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

The channel urls are internal mirrors to defaults and conda-forge.

</p></details>

**Comment by csevast** [comment] 2019-02-23 18:38
I am using YML files for the updating and creation of CONDA environments, and I found out that the PIP dependencies are not installed because of potential empty spaces in CONDA produced temporary files which raises the following error:

(base) G:\My Drive\software\ericIDE>C:\dev\Miniconda3\python.exe C:\dev\Miniconda3\Scripts\pip-script.py --disable-pip-version-check install -r G:\My Drive\software\ericIDE\condaenv.c12vw9ri.requirements.txt
Invalid requirement: 'Drive\software\ericIDE\condaenv.c12vw9ri.requirements.txt'
It looks like a path. File 'Drive\software\ericIDE\condaenv.c12vw9ri.requirements.txt' does not exist.

**Comment by jjhelmus** [comment] 2019-03-02 19:52
@quartox Could you share the contents of the `conda-env.yaml` where you see this issue.  I'm having a hard time reproducing this.

**Comment by jjhelmus** [comment] 2019-03-02 19:57
#8532 looks to be a report of the same issue with #8352 fixing the issue.  I'm going to close this as a duplicate report.  @quartox If you feel like the issue here is different than #8532 please re-open this issue.

**Closed by jjhelmus** 2019-03-02 19:57 UTC

**Comment by quartox** [comment] 2019-03-02 22:48
Looks good, they identified the same line, I think that will solve it.
