### ISSUE TITLE
Bug in conda dependency solver

### ISSUE THREAD

**Issue by lparsons** [conda/conda#6269] opened 2017-11-06 22:13 UTC
Attempting to install `trinity==2.4.0` results in `bowtie=2.2.5=0` being installed. This is not the lastest bowtie2 build (there is a build 2) and it doesn't work. Also, attempting to install `bowtie==2.2.5` results in the broken build 0 install. However, first installing `bowtie=2.2.5_py36_2` does work and subsequently installing `trinity==2.4.0` into that envrionment results in `bowtie2 2.3.3.1-py36pl5.22.0_0` being installed. Then everything works.

From a discussion on Gitter with @mbargull :
> Sounds like Conda's solver didn't prioritize its objectives (maximize req. pkg. version, maximize req. pkg. build number, minimize number of packages) correctly. The cause seems to be the dependency on pythonfor the newer builds which requires more packages to be installed. If you explicitly add python to the list of packages of your conda install/create command, you'll see it will then pick up the newer build. Interestingly conda 4.4.0rc1 behaves correctly.

**Comment by mbargull** [comment] 2017-11-06 23:18
This is about the `bowtie2=2.2.5` package from the `bioconda` channel.
The difference between `bowtie2=2.2.5=0` and `bowtie2=2.2.5=2` are mainly the added dependencies, notably `python`.

See the following logs which show the described behavior:
<details><summary><code>
(ins)(root) [miniconda3]$ cat .condarc
</code></summary><p>

```
default_channels:
  - https://repo.continuum.io/pkgs/free
```
</p></details>

<details><summary><code>
(ins)(root) [miniconda3]$ conda info
</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.19
         python version : 3.5.4.final.0
       requests version : 2.14.2
       root environment : /home/maba/code/miniconda3  (writable)
    default environment : /home/maba/code/miniconda3
       envs directories : /home/maba/code/miniconda3/envs
                          /home/maba/.conda/envs
          package cache : /home/maba/code/miniconda3/pkgs
                          /home/maba/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
            config file : /home/maba/code/miniconda3/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.5.4 Linux/4.13.10-1-MANJARO / glibc/2.26    
                UID:GID : 1000:1000
```
</p></details>

<details><summary><code>
(ins)(root) [miniconda3]$ conda create --dry-run -n x -c bioconda bowtie2=2.2.5
</code></summary><p>

```
Fetching package metadata .......
Solving package specifications: .

Package plan for installation in environment /home/maba/code/miniconda3/envs/x:

The following NEW packages will be INSTALLED:

    bowtie2: 2.2.5-0 bioconda

```
</p></details>

<details><summary><code>
(ins)(root) [miniconda3]$ conda create --dry-run -n x -c bioconda bowtie2=2.2.5 python
</code></summary><p>

```
Fetching package metadata .......
Solving package specifications: .

Package plan for installation in environment /home/maba/code/miniconda3/envs/x:

The following NEW packages will be INSTALLED:

    bowtie2:       2.2.5-py36_2     bioconda
    certifi:       2016.2.28-py36_0         
    libgcc:        5.2.0-0                  
    openssl:       1.0.2l-0                 
    perl-threaded: 5.22.0-10        bioconda
    pip:           9.0.1-py36_1             
    python:        3.6.2-0                  
    readline:      6.2-2                    
    setuptools:    36.4.0-py36_1            
    sqlite:        3.13.0-0                 
    tk:            8.5.18-0                 
    wheel:         0.29.0-py36_0            
    xz:            5.2.3-0                  
    zlib:          1.2.11-0                 
```
</p></details>

<details><summary><code>
(ins)(root) [miniconda3-canary]$ cat .condarc 
</code></summary><p>

```
channels:
  - conda-canary
  - defaults
```
</p></details>

<details><summary><code>
(ins)(root) [miniconda3-canary]$ conda info
</code></summary><p>

```

     active environment : base
    active env location : /home/maba/code/miniconda3-canary
       user config file : /home/maba/.condarc
 populated config files : /home/maba/code/miniconda3-canary/.condarc
          conda version : 4.4.0rc1
    conda-build version : 3.0.1
         python version : 3.5.4.final.0
       base environment : /home/maba/code/miniconda3-canary  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/maba/code/miniconda3-canary/pkgs
                          /home/maba/.conda/pkgs
       envs directories : /home/maba/code/miniconda3-canary/envs
                          /home/maba/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.0rc1 requests/2.14.2 CPython/3.5.4 Linux/4.13.10-1-MANJARO manjaro/17.1-dev glibc/2.26
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details><summary><code>
(ins)(root) [miniconda3-canary]$ conda create --dry-run -n x -c bioconda bowtie2=2.2.5
</code></summary><p>

```
Solving environment: done

## Package Plan ##

  environment location: /home/maba/code/miniconda3-canary/envs/x

  added / updated specs: 
    - bowtie2=2.2.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2016.2.28          |           py36_0         216 KB
    setuptools-36.4.0          |           py36_1         563 KB
    python-3.6.2               |                0        16.5 MB
    bowtie2-2.2.5              |           py36_2        10.1 MB  bioconda
    libgcc-5.2.0               |                0         1.1 MB
    perl-threaded-5.22.0       |               10        11.2 MB  bioconda
    ------------------------------------------------------------
                                           Total:        39.6 MB

The following NEW packages will be INSTALLED:

    bowtie2:       2.2.5-py36_2     bioconda
    certifi:       2016.2.28-py36_0         
    libgcc:        5.2.0-0                  
    openssl:       1.0.2l-0                 
    perl-threaded: 5.22.0-10        bioconda
    pip:           9.0.1-py36_1             
    python:        3.6.2-0                  
    readline:      6.2-2                    
    setuptools:    36.4.0-py36_1            
    sqlite:        3.13.0-0                 
    tk:            8.5.18-0                 
    wheel:         0.29.0-py36_0            
    xz:            5.2.3-0                  
    zlib:          1.2.11-0                 
```
</p></details>

**Comment by mbargull** [comment] 2017-11-06 23:31
In case someone is interested in the context regarding the `trinity` install:
<details><summary><code>
(ins)(root) [miniconda3]$ conda create --dry-run -n x -c bioconda trinity
</code></summary><p>

```
Fetching package metadata .......
Solving package specifications: .

Package plan for installation in environment /home/maba/code/miniconda3/envs/x:

The following NEW packages will be INSTALLED:

    bowtie:              1.0.0-1       bioconda
    bowtie2:             2.2.5-0       bioconda
    bzip2:               1.0.6-3               
    collectl:            4.0.4-1       bioconda
    curl:                7.54.1-0              
    fastool:             0.1.4-1       bioconda
    jellyfish:           2.2.6-0       bioconda
    krb5:                1.13.2-0              
    libgcc:              5.2.0-0               
    libssh2:             1.8.0-0               
    openjdk:             8.0.121-1             
    openssl:             1.0.2l-0              
    parafly:             r2013_01_21-0 bioconda
    perl-app-cpanminus:  1.7039-2      bioconda
    perl-file-find-rule: 0.34-1        bioconda
    perl-module-build:   0.4214-2      bioconda
    perl-number-compare: 0.03-0        bioconda
    perl-text-glob:      0.09-0        bioconda
    perl-threaded:       5.22.0-10     bioconda
    samtools:            1.6-0         bioconda
    slclust:             02022010-1    bioconda
    trimmomatic:         0.36-5        bioconda
    trinity:             2.4.0-3       bioconda
    xz:                  5.2.3-0               
    zlib:                1.2.8-3               
```
</p></details>

<details><summary><code>
(ins)(root) [miniconda3]$ conda create --dry-run -n x -c bioconda trinity python
</code></summary><p>

```
Fetching package metadata .......
Solving package specifications: .

Package plan for installation in environment /home/maba/code/miniconda3/envs/x:

The following NEW packages will be INSTALLED:

    bowtie:             1.2.0-py36_0     bioconda
    bowtie2:            2.3.0-py36_1     bioconda
    bzip2:              1.0.6-3                  
    certifi:            2016.2.28-py36_0         
    collectl:           4.0.4-1          bioconda
    curl:               7.54.1-0                 
    fastool:            0.1.4-1          bioconda
    jellyfish:          2.2.6-0          bioconda
    krb5:               1.13.2-0                 
    libgcc:             5.2.0-0                  
    libssh2:            1.8.0-0                  
    openjdk:            8.0.121-1                
    openssl:            1.0.2l-0                 
    parafly:            r2013_01_21-0    bioconda
    perl-app-cpanminus: 1.7039-2         bioconda
    perl-module-build:  0.4214-2         bioconda
    perl-threaded:      5.22.0-10        bioconda
    pip:                9.0.1-py36_1             
    python:             3.6.2-0                  
    readline:           6.2-2                    
    samtools:           1.6-0            bioconda
    setuptools:         36.4.0-py36_1            
    slclust:            02022010-1       bioconda
    sqlite:             3.13.0-0                 
    tbb:                4.4_20150728-0   bioconda
    tk:                 8.5.18-0                 
    trimmomatic:        0.36-5           bioconda
    trinity:            2.4.0-5          bioconda
    wheel:              0.29.0-py36_0            
    xz:                 5.2.3-0                  
    zlib:               1.2.8-3                  
```
</p></details>

Those logs essentially show the same behavior, i.e, the core problem here is `bowtie2=2.2.5=0` being picked up unless `python` is also explicitly installed.

**Comment by mbargull** [comment] 2017-11-07 22:31
For anyone who tries to reproduce this: The `bowtie2=2.2.5-0` build is now labeled `broken` in the Bioconda channel. Hence instead of `-c bioconda` use `-c bioconda -c bioconda/label/broken`.

**Comment by mbargull** [comment] 2017-11-07 23:14
For the `trinity` package in `bioconda` there is even a difference if Miniconda2 or Miniconda3 is used. See the progress in https://github.com/bioconda/bioconda-recipes/issues/6637

**Comment by mbargull** [comment] 2017-11-10 15:30
@kalefranz: Any ideas how we could approach this issue? If you want, I can provide some additional `conda create -vvv` logs or whatever you deem helpful.

(cc @johanneskoester)

**Comment by johanneskoester** [comment] 2017-11-13 10:14
So, if I get this right, the fix is in conda 4.4? @kalefranz when can we expect a release, or will there be a backport of solver fixes?

**Comment by mbargull** [comment] 2017-11-13 22:17
Did some intensive digging into this issue:
It boils down to prioritization of features in the solver logic. The specific catch for this issue: None of the packages actually use features 😵! Well, except for some old Python debug builds in `https://repo.continuum.io/pkgs/free/linux-64`:
```
python: 2.7.9-d1    [debug]
python: 2.7.9-d2    [debug]
python: 2.7.10-d0   [debug]
python: 2.7.11-d0   [debug]
```
Of course none of those will ever be installed, especially for Python 3 environments.
`conda 4.4.0rc1` actually only succeeded coincidentally as those Python builds only specify their required feature but have no dependency on the package which provides that feature (also named `debug`). For some reason `conda 4.4.0rc1` will only behave like `conda 4.3.30` if they would correctly specify their dependency -- for now I couldn't pin down the cause of that behavioral difference since the feature support code changed a bit from `4.3.x` to `4.4.x`...
Nonetheless, I think those builds can be classified as broken nonetheless:
```
(ins)(root) [miniconda3]$  conda create --dry-run -n x python=2.7.9=d1
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7.9 d1
Use "conda info <package>" to see the dependencies for each package.
```
```
(ins)(root) [miniconda3]$  conda create --dry-run -n x python=2.7.9=d1 debug
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/maba/code/miniconda3/envs/x:

The following NEW packages will be INSTALLED:

    certifi:    2016.2.28-py27_0
    debug:      1.0-0           
    openssl:    1.0.1k-1        
    pip:        9.0.1-py27_1    
    python:     2.7.9-d1         [debug]
    readline:   6.2-2           
    setuptools: 36.4.0-py27_1   
    sqlite:     3.13.0-0        
    system:     5.8-2           
    tk:         8.5.18-0        
    wheel:      0.29.0-py27_0   
    zlib:       1.2.11-0        
```
 Hence, a quick fix without making changes to `conda` itself is just to pull those debug builds from the repository.
I'll submit a PR to postpone the prioritization of features and give some condensed test cases.

**Comment by mbargull** [comment] 2017-11-16 20:04
That bug caused some trouble elsewhere: https://github.com/galaxyproject/tools-iuc/pull/1578
There the problem is a transitive dependency on `r-base` -> `gsl` where some (but not all) builds of `gsl` require the `blas_openblas` feature. Hence, due to the present bug, Conda tries to avoid using any `gsl` builds no matter if they require a feature or not, resulting in the installation of the requested package's older build.

**Comment by johanneskoester** [comment] 2017-11-23 09:16
xref: #6296

**Comment by mcg1969** [comment] 2017-11-30 14:22
I studied conda-forge’s feature use too and it is non-ideal as well. We’ll work with them to hammer it out.

**Comment by mbargull** [comment] 2017-11-30 14:46
@mcg1969: I was already wondering what your take on that will be. Thanks for looking into that!

**Closed** 2018-02-24 09:18 UTC
Labels: source:community, tag:solver, type:discussion
