### ISSUE TITLE
Lock Environments

### ISSUE THREAD

**Issue by JucaVaz** [conda/conda#12138] opened 2022-12-01 10:21 UTC
### What is the idea?

What if there was a way to "lock" specific conda environments and don't let any packages be installed/updated? For example, lock the base environment, so in case I forgot to activate my conda environment it would avoid me from polluting the base environment with packages unless I disable that specific feature. Throwing at me some kind of error? Looks like would be a nice feature to have, instead of doing `conda install --revision` every time I mess up a package installation.

**Comment by travishathaway** [comment] 2022-12-15 15:20
Hi @JucaVaz,

Thanks for this feature request. This is a very sensible idea for a new ability in conda, but is unlikely to actually be added to the core of conda. Fortunately, this is a great for a plugin. I want to keep this open to highlight a potential use case for a future plugin.

As it stands, we currently do not have the appropriate plugin hook to make this work, but in a future release, it is likely that we will add a plugin hook that allow plugin authors to run code before a command runs. After adding this hook, writing a plugin for this type of locking behavior would actually be relatively simple.

I am going to add our plugin label to this issue so that we can keep track of it.

Thank you very much for this idea.

--
conda team ✌️ 🐍

**Comment by bernt-matthias** [comment] 2023-04-01 08:41
Has there been any progress on this? I just recently tried to (re)create all my environments in a parallel way and failed horribly (with lots of broken packages). 

Also we are using conda environment more and more in multi-user setups .. where it would be nice if they would be able to use a shared package cache.

**Comment by bernt-matthias** [comment] 2023-04-02 09:21
Maybe a duplicate of https://github.com/conda/conda/issues/6742

**Comment by travishathaway** [comment] 2023-05-24 04:46
Hi @bernt-matthias,

So, this feature request doesn't mean locking like in the context of parallel computing, rather it means locking an environment so that you can no longer make changes to it.

This is essentially how it would work:

```
conda envlock -n base
Successfully locked based
```

and then, if I tried to install something to base:

```
conda install -n base python=3.11
Cannot install to environment "base" because it is currently locked
```

I hope that makes a little more sense now 😅.

**Comment by bernt-matthias** [comment] 2023-05-24 07:45
Thanks for the explanation @travishathaway . This sounds super useful as well :). Actually for my environments I always `chmod -R ugo-w ENVDIR` to have a similar behavior (wo a pretty error message).

But you are right, I was looking for the wrong thing in this issue.

**Comment by travishathaway** [comment] 2023-07-28 06:27
@JucaVaz,

I'm happy to report that I have released a plugin that essentially does what you want. Please check out the README on this repository to learn more: https://github.com/travishathaway/conda-guard

To install, run this command:

```
conda install thath::conda-guard
```

For anyone else visiting this issue, please create a new issue at the repository above to leave feedback or report a bug.

Thanks ✌️

**Comment by travishathaway** [comment] 2024-05-21 11:08
I'm going to close this issue for now, especially considering conda-protect is seeing more usage and has been officially adopted as a conda-incubator project. Please report any issues with that tool there and not here.

**Closed by travishathaway** 2024-05-21 11:08 UTC
Labels: type::feature, source::anaconda, plugins, backlog
