### ISSUE TITLE
BUG: conda command fails when conda-forge channel is present

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#2897] opened 2016-06-28 15:01 UTC
This is a new issue with conda 4.1.4 (was not present with 4.1.3).

If I set up an environment using the following minimal example on Travis: [.travis.yml](https://github.com/astrofrog/travis-conda/blob/e0ce58f984ae473bc59f59926faa69dd8963c6c2/.travis.yml)

I get a weird error at the end:

```
$ $CONDA_INSTALL glueviz
/home/travis/build.sh: line 45: conda install  python=2.7: command not found
```

Full log [here](https://travis-ci.org/astrofrog/travis-conda/builds/140824926)

Now if I remove the line containing conda-forge: [.travis.yml](https://github.com/astrofrog/travis-conda/blob/06fe95202cb3c00e736ddd7f7c9af4ad6a8901e9/.travis.yml) then it all works fine - see [full log](https://travis-ci.org/astrofrog/travis-conda/builds/140825878) (Travis fails because I forgot to redefine ``script``, but the install works)

cc @bsipocz

**Comment by astrofrog** [comment] 2016-06-28 15:09
The issue seems to be related to the use of ``$CONDA_INSTALL`` - but I don't understand what's changed in conda 4.1.4 that would cause this to change. Basically, doing:

```
  - export CONDA_INSTALL='conda install  python=2.7'
  - $CONDA_INSTALL glueviz
```

doesn't work but

```
  - conda install python=2.7 glueviz
```

works. However, this is only an issue if the ``conda-forge`` channel is added. 😕

**Comment by jakirkham** [comment] 2016-06-28 15:13
Could you please explain why keeping `python=2.7` is needed? 😕

**Comment by astrofrog** [comment] 2016-06-28 15:18
@jakirkham - because we are in a CI environment and we want to make sure that installing certain packages doesn't accidentally update the python or numpy version, so we normally do e.g.:

```
export CONDA_INSTALL='conda install python=2.7 numpy=1.10'
```

If we don't do that, Numpy can get accidentally upgraded. I know that Python won't normally get upgraded, but it's for future proof-ness :)

Anyway, this is a red herring :fish: - the install fails if we do:

```
  - export CONDA_INSTALL='conda install'
  - $CONDA_INSTALL glueviz
```

**Comment by jakirkham** [comment] 2016-06-28 15:27
Just for fun, could you please try changing `$CONDA_INSTALL glueviz` -> `eval $CONDA_INSTALL glueviz`?

**Comment by kalefranz** [comment] 2016-06-28 15:30
Yeah I'm confused here so far too.

**Comment by jakirkham** [comment] 2016-06-28 15:32
FWIW, when I have a similar issue and want to pin a few things, normally I add a `pinned` file to `$PREFIX/conda-meta` that specifies what versions I want. Maybe this works for you? Here are the [docs]( http://conda.pydata.org/docs/faq.html#pinning-packages ) on it if you would like to get more familiar.

**Comment by astrofrog** [comment] 2016-06-28 15:39
Using ``eval`` works - however this is not the real solution here - something happened in conda v4.1.4 that broke the (otherwise valid) way to do it that we are using.

We do use the pinned file for other dependencies, and I agree that in the future we could use it for python and numpy too.

The reason why these options don't solve the issue is that we are setting up ``$CONDA_INSTALL`` inside the ``ci-helpers`` package, and many packages are now potentially using the ``$CONDA_INSTALL`` variable inside their own Travis files, so we need to get this working as it did before, otherwise we face the prospect of updating quite a few .travis.yml files.

For now, we are pinning conda to 4.1.3.

**Comment by bsipocz** [comment] 2016-06-28 15:39
@jakirkham - We use the pinning, and will probably pin the conda version, too to have a better control over situations like this. 

However I think it would be quite useful to get a clear understanding why this is happening, which change between v4.1.3 and v4.1.4 causes this bug, and then add it to the regression tests.

**Comment by jakirkham** [comment] 2016-06-28 15:58
Of course, just trying to provide options and understand the scope.

**Comment by mcg1969** [comment] 2016-06-28 15:59
This one is throwing me. But I have to be honest I'm still not convinced that it's conda's issue. Yes, I fully understand that this worked in 4.1.3. But doesn't the [log output](https://travis-ci.org/astrofrog/travis-conda/builds/140824926) suggest that the error occurs _at the shell level_ and not the python level? It suggests that under certain circumstances, Bash itself is not parsing the environment variable before execution:
```
0203-mgrant:~ mgrant$ 'conda install'
-bash: conda install: command not found
```

**Comment by astrofrog** [comment] 2016-06-28 16:01
@mcg1969 - indeed the error happens at the shell level, but why should the behavior be different when conda is upgraded from 4.1.3 to 4.1.4? Does conda maybe set/modify any environment variables that could have an impact on the shell?

**Comment by mcg1969** [comment] 2016-06-28 16:02
That's certainly possible, and helps narrow down the search for an offending commit. But does out there know what might cause BASH to parse an environment variable differently?

**Comment by jakirkham** [comment] 2016-06-28 16:03
So, one thing that might help narrow this down (if people have time) is trying to reproduce this locally (perhaps in a docker container, but not required) and run `git bisect`. There are only a [handful of commits]( https://github.com/conda/conda/compare/4.1.3...4.1.4 ) between these releases.

**Comment by astrofrog** [comment] 2016-06-28 16:03
What's the recommended way to install a developer version of conda into a conda environment? I could try bisecting to find the offending commit?

**Comment by jakirkham** [comment] 2016-06-28 16:04
So, I think we just `pip install` from the repo on top of the existing `conda`. Does that sound correct, @msarahan, or is there a better way?

**Comment by astrofrog** [comment] 2016-06-28 16:40
@mcg1969 @jakirkham @msarahan the problematic commit is https://github.com/conda/conda/commit/804955d57510142ca7ece2387f8dc55edc01ec64

See the following list of builds! https://travis-ci.org/astrofrog/travis-conda/builds/140852439

**Comment by mcg1969** [comment] 2016-06-28 16:41
Excellent detective work. @msarahan, this is a weird one! I see nothing in there that would explain why this is happening. Any ideas?

**Comment by jakirkham** [comment] 2016-06-28 16:43
I like your testing strategy, @astrofrog. 😄

**Comment by mcg1969** [comment] 2016-06-28 16:44
@kalefranz, check out what @astrofrog did above to bisect this conda bug. (see his travis link)

**Comment by astrofrog** [comment] 2016-06-28 16:45
Just for completeness, here's the value of the two environment variables that are mentioned in the commit:

```
$ echo $CONDA_DEFAULT_ENV
test
$ echo $CONDA_PREFIX
/home/travis/miniconda/envs/test
```

**Comment by mcg1969** [comment] 2016-06-28 16:46
Ah, so some sort of relative vs. absolute path issue, perhaps

**Comment by msarahan** [comment] 2016-06-28 17:13
I don't think so @mcg1969 - those variables are not (visibly) involved in his bash commands.

I wonder why you're using a string, though.  This is a situation where I think an array would be better.  Even just leaving the string unquoted when setting CONDA_INSTALL would work (works for me, anyway).  I have been able to replicate both the working behavior (with bash only), and the non-working behavior (in zsh, and with an activated bash shell).

I'm sorry to say that although I'm curious how that seemingly unrelated change introduced this breakage, the workaround is so trivial that I would ask you to change your scripts (either use an array, or don't quote your string when setting CONDA_INSTALL)

**Comment by msarahan** [comment] 2016-06-28 17:19
cf: http://superuser.com/a/360986/184799

**Comment by mingwandroid** [comment] 2016-06-28 17:20
This https://github.com/astrofrog/travis-conda/commit/71b52e136d5fef8ad95cbb4b4f34529b6ee735b7 is brilliant.

**Comment by mcg1969** [comment] 2016-06-28 17:22
This may be a more relevant article: http://unix.stackexchange.com/questions/38440/why-does-bash-variable-expansion-retain-quotes

**Comment by mcg1969** [comment] 2016-06-28 17:24
I still don't understand why the identified commit would break things. But I see this as an argument for fixing your build script, not reverting that commit.

**Comment by astrofrog** [comment] 2016-06-28 17:26
It's also nuts that this only happens if the conda-forge channel is added. I guess this will remain one of the mysteries of the modern world!

We'll report back on fixing the environment variable.

**Comment by astrofrog** [comment] 2016-06-28 17:30
@msarahan - I don't think removing the quotes will work:

```
$ export CONDA_INSTALL=conda install
$ echo $CONDA_INSTALL
conda
```

but we'll look into it a bit.

**Comment by msarahan** [comment] 2016-06-28 17:31
Might have been a zsh-ism.  Ignore it - I think the array is the right way to go.

**Comment by astrofrog** [comment] 2016-06-28 17:36
@msarahan - sadly, an array won't work for us either because then the environment variable can't be used as before:

```
$ VAR=(echo "hi")
$ $VAR

$
```

One has to then do ``"${VAR[@]}"`` (but then we are back to having to change all the scripts that may use that variable). We're going to investigate pinning the versions via the pin file and setting ``CONDA_INSTALL`` to the one-word ``conda`` command.

**Comment by kalefranz** [comment] 2016-06-28 19:58
Actually, I'm having trouble reproducing this on OS X.  Is it a Linux-only thing? Or something with the bash version?

    kfranz@0283:~/continuum/conda *4.1.x ❯ conda info
    Using Anaconda Cloud api site https://api.anaconda.org
    Current conda install:

                 platform : osx-64
            conda version : 4.1.4
        conda-env version : 2.5.1
      conda-build version : 2.0.0beta+40.g38c9be5
           python version : 2.7.11.final.0
         requests version : 2.9.1
         root environment : /conda  (writable)
      default environment : /conda
         envs directories : /conda/envs
            package cache : /conda/pkgs
             channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/
                            https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                            https://repo.continuum.io/pkgs/free/osx-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/osx-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : /Users/kfranz/.condarc
             offline mode : False
        is foreign system : False

    kfranz@0283:~/continuum/conda *4.1.x ❯ export CONDA_INSTALL='conda install'
    kfranz@0283:~/continuum/conda *4.1.x ❯ $CONDA_INSTALL glueviz
    Using Anaconda Cloud api site https://api.anaconda.org
    Fetching package metadata .........
    Solving package specifications: ..........

    Package plan for installation in environment /conda:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        glueviz-0.8.1              |           py27_1         1.1 MB  conda-forge

    The following NEW packages will be INSTALLED:

        glueviz: 0.8.1-py27_1 conda-forge

    Proceed ([y]/n)? n

**Comment by astrofrog** [comment] 2016-06-28 21:33
@kalefranz - I haven't tried reproducing it on MacOS X

**Comment by mcg1969** [comment] 2016-06-28 21:46
I have, and I've been unable to do so.

**Comment by kalefranz** [comment] 2016-06-28 22:51
I also cannot reproduce this on CentOS 5

    root@default:~ # conda info
    Current conda install:

                 platform : linux-64
            conda version : 4.1.4
        conda-env version : 2.5.1
      conda-build version : 1.21.0
           python version : 2.7.11.final.0
         requests version : 2.9.1
         root environment : /usr/local  (writable)
      default environment : /usr/local
         envs directories : /usr/local/envs
            package cache : /usr/local/pkgs
             channel URLs : https://conda.anaconda.org/t/<TOKEN>/kalefranz/linux-64/
                            https://conda.anaconda.org/t/<TOKEN>/kalefranz/noarch/
                            https://repo.continuum.io/pkgs/free/linux-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/linux-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : /root/.condarc
             offline mode : False
        is foreign system : False

    root@default:~ # export CONDA_INSTALL='conda install'
    root@default:~ # $CONDA_INSTALL glueviz
    Fetching package metadata .........
    Solving package specifications: ..........

    Package plan for installation in environment /usr/local:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        libgfortran-3.0.0          |                1         281 KB
        libsodium-1.0.10           |                0         1.2 MB
        mkl-11.3.3                 |                0       122.1 MB
        pixman-0.32.6              |                0         2.4 MB
        hdf5-1.8.16                |                0         1.9 MB
        libpng-1.6.22              |                0         214 KB
        zeromq-4.1.4               |                0         4.1 MB
        freetype-2.5.5             |                1         2.5 MB
        backports-1.0              |           py27_0           1 KB
        backports_abc-0.4          |           py27_0           5 KB
        ...
        ...
        ssl_match_hostname: 3.4.0.2-py27_1
        tornado:            4.3-py27_1
        traitlets:          4.2.1-py27_0
        xlrd:               1.0.0-py27_0
        zeromq:             4.1.4-0

    Proceed ([y]/n)?

**Comment by bsipocz** [comment] 2016-06-29 16:51
@kalefranz - I try to check the osx behaviour, but travis is down atm.
Anyway, it looks like you didn't add ``conda-forge`` to the list of channels for your test?

**Comment by kalefranz** [comment] 2016-06-29 19:26
You're right @bsipocz, I hadn't.  But adding it, I get the same result on CentOS 5.

    root@default:~ # conda config --add channels conda-forge
    root@default:~ # conda info
    Current conda install:

                 platform : linux-64
            conda version : 4.1.4
        conda-env version : 2.5.1
      conda-build version : 1.21.0
           python version : 2.7.11.final.0
         requests version : 2.9.1
         root environment : /usr/local  (writable)
      default environment : /usr/local
         envs directories : /usr/local/envs
            package cache : /usr/local/pkgs
             channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/linux-64/
                            https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                            https://repo.continuum.io/pkgs/free/linux-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/linux-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : /root/.condarc
             offline mode : False
        is foreign system : False

    root@default:~ # export CONDA_INSTALL='conda install'
    root@default:~ # $CONDA_INSTALL glueviz
    Fetching package metadata ...........
    Solving package specifications: ..........

    Package plan for installation in environment /usr/local:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        jpeg-9b                    |                0         918 KB  conda-forge
        libgfortran-3.0.0          |                1         281 KB
        libiconv-1.14              |                2         1.3 MB  conda-forge
        libsodium-1.0.10           |                0         1.5 MB  conda-forge
        mkl-11.3.3                 |                0       122.1 MB
        hdf5-1.8.17                |                2         3.3 MB  conda-forge
        libpng-1.6.23              |                0         296 KB  conda-forge
        libtiff-4.0.6              |                5         507 KB  conda-forge
        zeromq-4.1.5               |                0         5.0 MB  conda-forge
        freetype-2.6.3             |                1         2.8 MB  conda-forge
        backports.shutil_get_terminal_size-1.0.0|           py27_0           5 KB  conda-forge
        certifi-2016.2.28          |           py27_0         210 KB  conda-forge
        decorator-4.0.10           |           py27_0          12 KB
        fontconfig-2.11.1          |                3         874 KB  conda-forge
        functools32-3.2.3.2        |           py27_1          16 KB  conda-forge
        ipython_genutils-0.1.0     |           py27_0          32 KB
        numpy-1.11.1               |           py27_0         6.2 MB
        pillow-3.2.0               |           py27_2         880 KB  conda-forge
        ptyprocess-0.5.1           |           py27_0          19 KB  conda-forge
        pygments-1.6               |           py27_0         865 KB  conda-forge
        pyparsing-2.1.1            |           py27_0          67 KB  conda-forge
        python-decorator-4.0.10    |           py27_0          12 KB  conda-forge
        python-simplegeneric-0.8.1 |           py27_0           7 KB  conda-forge
        pyzmq-14.7.0               |           py27_0         669 KB  conda-forge
        sip-4.18                   |           py27_0         263 KB  conda-forge
        ssl_match_hostname-3.5.0.1 |           py27_0           6 KB  conda-forge
        xlrd-1.0.0                 |           py27_0         181 KB
        astropy-1.2.1              |      np111py27_0         8.4 MB
        cycler-0.10.0              |           py27_0          13 KB  conda-forge
        h5py-2.6.0                 |      np111py27_4         2.6 MB  conda-forge
        networkx-1.11              |           py27_0         1.1 MB
        pexpect-4.1.0              |           py27_0          65 KB  conda-forge
        python-pathlib2-2.1.0      |           py27_0          26 KB  conda-forge
        qt-4.8.7                   |                3        34.1 MB
        scipy-0.17.1               |      np111py27_1        30.1 MB
        tornado-4.2.1              |           py27_0         522 KB  conda-forge
        traitlets-4.2.1            |           py27_0         108 KB  conda-forge
        jupyter_core-4.1.0         |           py27_0          51 KB  conda-forge
        pandas-0.18.1              |      np111py27_0        14.2 MB  conda-forge
        pickleshare-0.7.2          |           py27_0           8 KB  conda-forge
        pyqt-4.11.4                |           py27_3         3.4 MB
        ipython-4.2.0              |           py27_2         975 KB  conda-forge
        jupyter_client-4.2.2       |           py27_0          95 KB  conda-forge
        matplotlib-1.5.1           |      np111py27_4         6.7 MB  conda-forge
        ipykernel-4.3.1            |           py27_0         117 KB
        scikit-image-0.12.3        |      np111py27_0        27.3 MB  conda-forge
        qtconsole-4.2.1            |           py27_0         132 KB  conda-forge
        glueviz-0.8.1              |           py27_1         1.2 MB  conda-forge
        ------------------------------------------------------------
                                               Total:       279.1 MB

    The following NEW packages will be INSTALLED:

        astropy:                            1.2.1-np111py27_0
        backports.shutil_get_terminal_size: 1.0.0-py27_0       conda-forge
        certifi:                            2016.2.28-py27_0   conda-forge
        cycler:                             0.10.0-py27_0      conda-forge
        decorator:                          4.0.10-py27_0
        fontconfig:                         2.11.1-3           conda-forge
        freetype:                           2.6.3-1            conda-forge
        functools32:                        3.2.3.2-py27_1     conda-forge
        glueviz:                            0.8.1-py27_1       conda-forge
        h5py:                               2.6.0-np111py27_4  conda-forge
        hdf5:                               1.8.17-2           conda-forge
        ipykernel:                          4.3.1-py27_0
        ipython:                            4.2.0-py27_2       conda-forge
        ipython_genutils:                   0.1.0-py27_0
        jpeg:                               9b-0               conda-forge
        jupyter_client:                     4.2.2-py27_0       conda-forge
        jupyter_core:                       4.1.0-py27_0       conda-forge
        libgfortran:                        3.0.0-1
        libiconv:                           1.14-2             conda-forge
        libpng:                             1.6.23-0           conda-forge
        libsodium:                          1.0.10-0           conda-forge
        libtiff:                            4.0.6-5            conda-forge
        matplotlib:                         1.5.1-np111py27_4  conda-forge
        mkl:                                11.3.3-0
        networkx:                           1.11-py27_0
        numpy:                              1.11.1-py27_0
        pandas:                             0.18.1-np111py27_0 conda-forge
        pexpect:                            4.1.0-py27_0       conda-forge
        pickleshare:                        0.7.2-py27_0       conda-forge
        pillow:                             3.2.0-py27_2       conda-forge
        ptyprocess:                         0.5.1-py27_0       conda-forge
        pygments:                           1.6-py27_0         conda-forge
        pyparsing:                          2.1.1-py27_0       conda-forge
        pyqt:                               4.11.4-py27_3
        python-decorator:                   4.0.10-py27_0      conda-forge
        python-pathlib2:                    2.1.0-py27_0       conda-forge
        python-simplegeneric:               0.8.1-py27_0       conda-forge
        pyzmq:                              14.7.0-py27_0      conda-forge
        qt:                                 4.8.7-3
        qtconsole:                          4.2.1-py27_0       conda-forge
        scikit-image:                       0.12.3-np111py27_0 conda-forge
        scipy:                              0.17.1-np111py27_1
        sip:                                4.18-py27_0        conda-forge
        ssl_match_hostname:                 3.5.0.1-py27_0     conda-forge
        tornado:                            4.2.1-py27_0       conda-forge
        traitlets:                          4.2.1-py27_0       conda-forge
        xlrd:                               1.0.0-py27_0
        zeromq:                             4.1.5-0            conda-forge

    Proceed ([y]/n)? n

**Comment by kalefranz** [comment] 2016-10-24 04:02
Closing the issue. I'm guessing it's resolved by now given no additional comment?

**Closed by kalefranz** 2016-10-24 04:02 UTC
Labels: bug

**Comment by bsipocz** [comment] 2016-10-24 07:33
@kalefranz -  I'm not sure whether the original problem was solved or not. We've ended up pinning the conda version to 4.1.3 and hasn't been tested the new releases since.

**Comment by HarveySummers** [comment] 2018-07-17 19:39
note: opened new issue https://github.com/conda/conda/issues/7550
