### ISSUE TITLE
VersionOrder __lt__() gives incorrect results

### ISSUE THREAD

**Issue by vyasr** [conda/conda#8194] opened 2019-01-31 02:26 UTC
## Current Behavior
Attempting to rerender feedstocks using conda-smithy results in a RuntimeError indicating that my conda-smithy version is out of date, because it thinks that v3.2.11<3.2.11. I am using conda version 4.6.2, conda-smithy version v3.2.11. I then attempted to rerender a feedstock using `conda smithy rererender`. The result is a RuntimeError with traceback

### Steps to Reproduce

```
$ conda activate
$ conda --version
conda 4.6.2
$ conda install -c conda-forge conda-smithy
$ conda smithy --version
v3.2.11
$ # Should cd into feedstock, but not necessary to reproduce since the failure occurs early.
$ conda smithy rerender
Traceback (most recent call last):
  File "/Users/vramasub/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 424, in main
    args.subcommand_func(args)
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 292, in __call__
    exclusive_config_file=args.exclusive_config_file,
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1304, in main
    check_version_uptodate(r, "conda-smithy", __version__, error_on_warn)
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1228, in check_version_uptodate
    raise RuntimeError("{} Exiting.".format(msg))
RuntimeError: conda-smithy version in root env (v3.2.11) is out-of-date (3.2.11). Exiting.
```

## Expected Behavior
The versions should be correctly detected as up-to-date. The issue appears to be in VersionOrder.__lt__(), conda/models/version.py, which defines strings to always compare as less than integers. The issue appears related to Issue #1590, but that fix does not appear to have addressed this problem.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /Users/vramasub/miniconda3
            shell level : 1
       user config file : /Users/vramasub/.condarc
 populated config files : /Users/vramasub/.condarc
          conda version : 4.6.2
    conda-build version : 3.15.1
         python version : 3.6.8.final.0
       base environment : /Users/vramasub/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/vramasub/miniconda3/pkgs
                          /Users/vramasub/.conda/pkgs
       envs directories : /Users/vramasub/miniconda3/envs
                          /Users/vramasub/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.2 requests/2.18.4 CPython/3.6.8 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 99459853:65537
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/vramasub/.condarc <==
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/vramasub/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.23.0           py36h782d450_0    defaults
beautifulsoup4            4.7.1                 py36_1001    conda-forge
blinker                   1.4                        py_1    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.2           py36hd3e6348_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
conda                     4.6.2                    py36_0    conda-forge
conda-build               3.15.1                   py36_0    conda-forge
conda-env                 2.6.0                h36134e3_0    defaults
conda-forge-pinning       2019.01.29                    0    conda-forge
conda-smithy              3.2.11                     py_0    conda-forge
cryptography              2.4.2            py36ha12b0ac_0    defaults
deprecated                1.2.4                      py_0    conda-forge
expat                     2.2.6                h0a44026_0    defaults
filelock                  3.0.10                     py_0    conda-forge
git                       2.19.1          pl526h6951d83_0    defaults
gitdb2                    2.0.5                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
glob2                     0.6                        py_0    conda-forge
idna                      2.6              py36h8628d0a_1    defaults
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.10                       py_1    conda-forge
libcurl                   7.62.0               h051b688_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1                h475c297_4    defaults
libiconv                  1.15              h1de35cc_1004    conda-forge
libssh2                   1.8.0                         1    conda-forge
markupsafe                1.1.0           py36h1de35cc_1000    conda-forge
msrest                    0.6.2                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
openssl                   1.1.1a            h1de35cc_1000    conda-forge
perl                      5.26.2            h79c3c89_1001    conda-forge
pip                       9.0.1            py36h1555ced_4    defaults
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.4.8           py36h1de35cc_1000    conda-forge
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1           py36h1de35cc_1002    conda-forge
pygithub                  1.43.4                   py36_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
python                    3.6.8                haf84260_0    defaults
python.app                2                py36h54569d5_7    defaults
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py36h1de35cc_1001    conda-forge
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
requests-oauthlib         1.0.0                      py_1    conda-forge
ruamel.yaml               0.15.87          py36h1de35cc_0    conda-forge
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
setuptools                36.5.0           py36h2134326_0    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
smmap2                    2.0.5                      py_0    conda-forge
soupsieve                 1.7.1                 py36_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
tqdm                      4.29.1                     py_0    conda-forge
urllib3                   1.22             py36h68b9469_0    defaults
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.30.0           py36h5eb2c71_1    defaults
wrapt                     1.11.1           py36h1de35cc_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

**Comment by kalefranz** [comment] 2019-01-31 02:44
I don’t think this is a new issue in conda with 4.6 (though I haven’t confirmed myself yet).

Conda makes the assumption that versioning is consistent across releases with the same package name. We also are not able to assume anything special about the `v` character. `u3 < v3 < w3 < 2 < 3`

More details in https://github.com/conda/conda/issues/2071

**Comment by msarahan** [comment] 2019-01-31 02:52
I think this might be new because 4.6 does more to understand dev versions that may be installed.  v3.2.11 is not a valid conda-smithy version.  It may be a tag, but that's not the same thing as a version.  However, tools like versioneer or setuptools_scm relate to tags, and that's probably showing up here.

Either that, or conda-smithy was released with a bug.  The leading v is definitely NOT part of a normal version.

**Comment by vyasr** [comment] 2019-01-31 18:02
It could be that conda-smithy was released with a bug. The leading v is clearly not supported by this comparator, but I'm not sure if that's because conda didn't know to support this versioning scheme, or because conda-smithy used a version tag that conda should treat as invalid.

**Comment by msarahan** [comment] 2019-01-31 18:06
It's not accurate to say that the leading v is not supported.  It is being considered, and it's behaving as it should: letters are lower than numbers.  The problem is that the version numbering in this line of versions is inconsistent - some have a leading v, others do not.  The ones with a leading v will be "lower" than the ones without.

**Closed** 2019-01-31 18:07 UTC

**Comment by vyasr** [comment] 2019-01-31 18:16
Fair enough, you are correct that what is unsupported is mixing and matching versions with and without the leading v. Since you closed the issue I assume that you don't think this is something that conda should be addressing intrinsically; do you view this as a bug in conda-smithy's versioning scheme, then? Should this be raised with them?
