### ISSUE TITLE
conda create fails with a lock file permission error

### ISSUE THREAD

**Issue by bow** [conda/conda#2778] opened 2016-06-20 11:53 UTC
Hi Conda developers,

I've been trying create a local conda environment from a YAML file containing the package list. During the download, everything works fine. It's not until it tries to install the first package that I get this error:

```
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/opt/anaconda/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/opt/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 105, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/opt/anaconda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 20, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python3.5/site-packages/conda/plan.py", line 589, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "/opt/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 80, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/opt/anaconda/lib/python3.5/site-packages/conda/install.py", line 1059, in link
    with Locked(prefix), Locked(pkgs_dir):
  File "/opt/anaconda/lib/python3.5/site-packages/conda/lock.py", line 60, in __enter__
    os.makedirs(self.lock_path)
  File "/opt/anaconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/anaconda/pkgs/.conda_lock-5633'
```

I can't see the lock file afterwards (it seems to have been deleted). The `/opt/anaconda/` is where my Anaconda installation is and it's owned by root only.

For context, I'm on Archlinux using the Anaconda installed from AUR (https://aur.archlinux.org/packages/anaconda/) and this is my `conda info` output:

```
             platform : linux-64
        conda version : 4.1.2
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /opt/anaconda  (read only)
  default environment : /opt/anaconda
     envs directories : /home/bow/.conda/envs
                        /home/bow/envs
                        /opt/anaconda/envs
        package cache : /home/bow/.conda/envs/.pkgs
                        /home/bow/envs/.pkgs
                        /opt/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/bow/.condarc
    is foreign system : False
```

Thanks in advance for looking into this :).

**Comment by baudilio** [comment] 2016-06-20 15:11
I've just had the same error. I was able to reproduce it when creating a new environment and also when activating a existing one.
My current conda info follows:
Current conda install:

             platform : linux-64
        conda version : 4.1.2
  conda-build version : 1.20.3
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /opt/anaconda2  (read only)
  default environment : /opt/anaconda2
     envs directories : /home/baudilio/.conda/envs
                        /home/baudilio/envs
                        /opt/anaconda2/envs
        package cache : /home/baudilio/.conda/envs/.pkgs
                        /home/baudilio/envs/.pkgs
                        /opt/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by bow** [comment] 2016-06-21 07:49
Some additional info that I thought may be useful:

I installed the Anaconda package initially via my distro package manager, and it was version 4.0.5. I remembered that at some point conda updated itself to version 4.1.2 (the one shown in my `conda info` output above. For a temporary fix, I decided to downgrade (i.e. reinstall) the version available in my package manager.

This seems to fix the problem for now; I can create environments as usual again and I don't see the permission errors anymore.

Still, I think this should not be the behavior (i.e. conda should still work even after it updates itself).

Thanks again for looking into this.

**Comment by Bklyn** [comment] 2016-06-22 13:14
Seeing this same issue with conda=4.1.2 and conda-env=2.5.0

**Comment by ThereAreThoseWhoCallMeTim** [comment] 2016-06-24 20:28
I've ran into this issue as well. The bug does not appear in 4.0.[56789], but using anything 4.1.0+ introduces this problem. I also tried updating just conda to 4.1.3, and leaving conda-env at 2.4.5, but that solved nothing. Even if a solution isn't available right now, do we know what could be causing it?

**Comment by Bklyn** [comment] 2016-06-24 20:37
This commit looks like the start of the troubles:

https://github.com/conda/conda/commit/c3d7056e31aa404f7749db5d0cbcb902a0ecbee4

This adds locking of the package directory as part of installing packages.  Presumably this prevents simultaneous "conda clean" and "conda install" processes from interfering with one another.

**Comment by kalefranz** [comment] 2016-06-24 21:42
The 21fc7b8 isn't where that lock was introduced.  Actually far before that.  21fc7b8 was reverting to a previous state.  There's a PR coming soon to get rid of this directory locking, but it'l probably be in 4.2.  I'd definitely like to track down where this is coming from.

**Comment by kalefranz** [comment] 2016-06-24 21:47
Here's the PR to loosen up that directory lock: https://github.com/conda/conda/pull/2858/files

**Comment by Bklyn** [comment] 2016-06-27 16:36
@kalefranz this won't change anything AFAICT.  The problem is that the package directory may not be writeable by a user running "conda create", and the `os.path.makedirs` call in `Locked.__enter__` is not guarded with a try block.  So I believe the application will bail out with a stack trace even with this change.

**Comment by kalefranz** [comment] 2016-06-27 16:53
We'll probably fix this for sure with 4.2.0. @HugoTian is working on locks now.

**Comment by Bklyn** [comment] 2016-06-27 16:57
"Probably fix this for sure" fills me with unbridled optimism :)

**Comment by kalefranz** [comment] 2016-06-27 17:04
Oh we will **definitely** fix this for sure!  Probably won't get back ported to 4.1.x but go out in 4.2.0. That's the *probably*.

**Comment by kalefranz** [comment] 2016-06-28 16:07
Ok, so this is a permissions issue.  You don't have write access as the current user to `/opt/anaconda`.  It's a multi-user support problem, and it's on our roadmap to fix.

**Comment by Bklyn** [comment] 2016-06-28 16:16
So now this won't make it into 4.1.x or 4.2?  I'd consider this a regression and a bug since this used to work in 4.0.x.

**Comment by gruel** [comment] 2016-06-29 08:23
I had the same problem and I basically downgrade miniconda to get the expected behavior. Perhaps I am wrong but If the problem is a permission issue it should work as sudo and, in my case, it was not the case. I got the same error as regular user and as sudo.

**Comment by kalefranz** [comment] 2016-06-29 19:17
This morning I realized how #2320 actually caused this issue.  My apologies for not recognizing it sooner.  The revert commit will be in `4.1.5` to be released today.

**Closed by kalefranz** 2016-06-29 19:17 UTC
Labels: bug, ent
