### ISSUE TITLE
Problem installing pillow package

### ISSUE THREAD

**Issue by Xiddler** [conda/conda#1046] opened 2014-12-14 18:13 UTC
The conda info is at the bottom. The traceback is at the top

Traceback (most recent call last):
  File "C:\Users\user\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\cli\install.py", line 210, in install
    verbose=not args.quiet)
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\misc.py", line 213, in install_local_packages
    execute_actions(actions, verbose=verbose)
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\plan.py", line 563, in execute_plan
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Users\user\Anaconda\Lib\site-packages\conda\install.py", line 434, in extract
    t.extractall(path=path)
  File "C:\Users\user\Anaconda\lib\tarfile.py", line 2051, in extractall
    self.extract(tarinfo, path)
  File "C:\Users\user\Anaconda\lib\tarfile.py", line 2088, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Users\user\Anaconda\lib\tarfile.py", line 2164, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\user\Anaconda\lib\tarfile.py", line 2204, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: 'C:\\Users\\user\\Anaconda\\pkgs\\pillow-2.5.1-py27_1\\Lib\\site-packages\\PIL\\_imaging.pyd'

conda info →
Current conda install:

             platform : win-64
        conda version : 3.7.3
  conda-build version : 1.3.5
       python version : 2.7.7.final.0
     requests version : 2.4.1
     root environment : C:\Users\user\Anaconda  (writable)
  default environment : C:\Users\user\Anaconda
     envs directories : C:\Users\user\Anaconda\envs
        package cache : C:\Users\user\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment] 2016-10-13 19:37
I can't reproduce this issue on the newest version of conda. Closing the issue; if this is still a problem for you after updating conda, please reopen the issue.

**Closed by soapy1** 2016-10-13 19:37 UTC
