### ISSUE TITLE
(SOLVED) can not install conda-build version .  

### ISSUE THREAD

**Issue by Atropos123** [conda/conda#5520] opened 2017-06-13 13:26 UTC
Hello the info is below.  i have not been able to get the navigator or spyder to open.  I see i do not have a conda-build installed and i don't know why.  i have done spyder reset i have tried conda update conda then update anaconda.  i have uninstalled anaconda and python and reinstalled both to no affect.  any help is appreciated.  thanks

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.17.3
       root environment : C:\Users\TurnerJ\Anaconda3  (writable)
    default environment : C:\Users\TurnerJ\Anaconda3
       envs directories : C:\Users\TurnerJ\Anaconda3\envs
                          C:\Users\TurnerJ\AppData\Local\conda\conda\envs
                          C:\Users\TurnerJ\.conda\envs
          package cache : C:\Users\TurnerJ\Anaconda3\pkgs
                          C:\Users\TurnerJ\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.17.3 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Users\TurnerJ\Anaconda3\Scripts\conda-script.py ..checkenv cmd.exe C:\Users\TurnerJ\Anaconda3`

    Traceback (most recent call last):
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\conda\cli\main.py", line 167, in main
        import conda.cli.activate as activate
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\conda\cli\activate.py", line 12, in <module>
        from ..utils import shells
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\conda\utils.py", line 13, in <module>
        from .gateways.disk.read import compute_md5sum
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 22, in <module>
        from ...models.channel import Channel
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\conda\models\channel.py", line 9, in <module>
        from ..base.context import context
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\conda\base\context.py", line 18, in <module>
        from .._vendor.auxlib.path import expand
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\conda\_vendor\auxlib\path.py", line 8, in <module>
        import pkg_resources
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
        @_call_aside
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
        f(*args, **kwargs)
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
        dist.activate(replace=False)
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
        declare_namespace(pkg)
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
        _handle_ns(packageName, path_item)
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "C:\Users\TurnerJ\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

C:\Users\TurnerJ>

**Comment by mandeep** [comment] 2017-06-13 14:10
Hi @Atropos123, conda-build is not installed with Anaconda so it's okay that you did not have it installed. Your issue looks to be a pkg_resources issue so you may want to try `conda update setuptools`. If that doesn't work, please open an issue on the Anaconda issue tracker found here: https://github.com/ContinuumIO/anaconda-issues/issues

**Comment by Atropos123** [comment] 2017-06-13 15:20
that did not work will post to link you stated thanks.

**Comment by kalefranz** [comment] 2017-06-15 07:56
duplicate of #5500 
fixed with #5496 in conda 4.3.22, which is currently in canary

**Closed by kalefranz** 2017-06-15 07:56 UTC
