### ISSUE TITLE
Error with environment.yml and pip format

### ISSUE THREAD

**Issue by alanhdu** [conda/conda#2237] opened 2016-03-11 06:36 UTC
With the following two `environment.yml` files:

```
name: test
dependencies:
- python=3.5
- pip:
    - https://github.com/mitsuhiko/flask/archive/master.zip
```

```
name: test
dependencies:
- python=3.5
- pip:
    - git+https://github.com/mitsuhiko/flask@master
```

On Windows (and not on Linux), I get this error when trying to run `conda env create`:

```powershell
PS C:\Users\End User\workspace\test> conda info
Current conda install:
             platform : win-64
        conda version : 4.0.4
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\End User\Miniconda3  (writable)
  default environment : C:\Users\End User\Miniconda3
     envs directories : C:\Users\End User\Miniconda3\envs
        package cache : C:\Users\End User\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False  
PS C:\Users\End User\workspace\test> conda env create
...
Traceback (most recent call last):
  File "C:\Users\End User\Miniconda3\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda_env\cli\main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda_env\installers\pip.py", line 8, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

If I downgrade conda to v3.19.3, the error disappears and everything works, so I assume this is a conda error. Let me know if I should refile with conda env instead.

**Comment by alanhdu** [comment] 2016-03-11 06:46
Update: Everything works with conda 4.0.2, but not with 4.0.4, so this must have been introduced pretty recently.

**Comment by kalefranz** [comment] 2016-03-11 23:33
Duplicate of https://github.com/conda/conda-env/issues/232

**Comment by kalefranz** [comment] 2016-03-11 23:34
This issue was moved to conda/conda-env#233

**Closed by kalefranz** 2016-03-11 23:34 UTC
