### ISSUE TITLE
Conda connection fails, install, search,update all fail

### ISSUE THREAD

**Issue by EatElephant** [conda/conda#5944] opened 2017-09-10 14:26 UTC
Window10 Anaconda 64bit, conda connection fails. All command needs connection fail such as install, update, search.

I tried uninstall and reinstall anaconda but this doesn't fix the problem.

Below is the console information.

Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

`$ D:\Anaconda3\Scripts\conda-script.py create -n py2 python=2 anaconda`

    Traceback (most recent call last):
      File "D:\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "D:\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "D:\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "D:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "D:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "D:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "D:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "D:\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
        timeout=timeout
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "D:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kalefranz** [comment] 2017-10-02 21:50
What is the output of `conda info` and `conda config --show-sources`?

**Comment by kalefranz** [comment] 2017-10-03 02:29
And also output of `env | sort` ?

**Comment by kalefranz** [comment] 2017-10-05 18:25
Related to or duplicate of #3962.

**Comment by kalefranz** [comment] 2017-10-05 18:28
Please move future discussion to #3962.

**Closed by kalefranz** 2017-10-05 18:28 UTC
