### ISSUE TITLE
conda install never returns

### ISSUE THREAD

**Issue by lxkain** [conda/conda#8543] opened 2019-04-10 20:46 UTC
Hello,

using conda 4.6.11 on MacOS, when I issue

`conda install -c conda-forge kivy` the command "never" returns (where never means at least 30 minutes spent at the "Solving environment" step, before cancelling).

**Comment by msarahan** [comment] 2019-04-10 20:50
duplicate of https://github.com/conda/conda/issues/8197

**Closed by msarahan** 2019-04-10 20:50 UTC
