### ISSUE TITLE
conda update --all --dry-run throws and error

### ISSUE THREAD

**Issue by akapocsi** [conda/conda#3475] opened 2016-09-20 15:12 UTC
Here it is:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 2.0.1
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Anaconda3\Scripts\conda-script.py update --all --dry-run`

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 398, in install
        common.confirm_yn(args)
      File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 433, in confirm_yn
        raise DryRunExit
    TypeError: __init__() missing 1 required positional argument: 'message'

**Comment by kalefranz** [comment] 2016-09-20 15:17
Duplicate of #3455.  Thanks for the report!

**Closed by kalefranz** 2016-09-20 15:17 UTC
