### ISSUE TITLE
unexpected error: pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

### ISSUE THREAD

**Issue by drandreaskrueger** [conda/conda#1301] opened 2015-04-27 13:21 UTC
C:\Windows\system32>conda update anaconda
Fetching package metadata: ...An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 255, in install
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 546, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 120, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 250, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    verify=config.ssl_verify)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 234, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 135, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in getPositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

conda info

C:\Windows\system32>conda info
Current conda install:

             platform : win-64
        conda version : 3.11.0
  conda-build version : not installed
       python version : 2.7.5.final.0
     requests version : 2.6.2
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment] 2015-05-28 20:42
Try `conda update requests`

**Comment by asmeurer** [comment] 2015-05-28 20:44
Closing as duplicate of https://github.com/conda/conda/issues/1261

**Closed by asmeurer** 2015-05-28 20:44 UTC

**Comment by drandreaskrueger** [comment] 2015-06-22 13:30
Thanks! Will try that next time. 

This time, I reinstalled the whole environment. That worked, too ;-)
