### ISSUE TITLE
TypeError: LoadLibrary() argument 1 must be str, not Non

### ISSUE THREAD

**Issue by tochenan** [conda/conda#8865] opened 2019-07-03 10:24 UTC
## Current Behavior
hello, when I tried to update conda using my cmd or just create an environment, the following error popped up.

C:\Users\analysis\DeepLabCut\conda-environments>conda update conda
Traceback (most recent call last):
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\analysis\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 8, in <module>
    from .install import install
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\analysis\Anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

And I feel really confused about it.
```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

when I ran this command in my cmd, I got nothing from it.

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

Traceback (most recent call last):
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\analysis\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 24, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 17, in <module>
    import conda_package_handling.api
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\analysis\Anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\analysis\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\analysis\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
</p></details>

OMG everything looks really broken

**Comment by Okroshiashvili** [comment] 2019-07-03 10:55
I have the same problem and still did not find a solution. Here is the [link](https://github.com/conda/conda/issues/8835)

**Comment by mingwandroid** [comment] 2019-07-03 11:42
If you run conda.bat explicitly from the condabin folder these problems will go away.

**Comment by Okroshiashvili** [comment] 2019-07-03 13:31
@mingwandroid  still does not work. Gives the same error

**Comment by msarahan** [comment] 2019-07-05 21:27
That error is happening because libarchive is failing to load.  The error indicates that it isn't being found.  I uploaded a new build of python-libarchive-c that might do a tiny bit better, but Ray's advice should really be adequate.  Can you list commands that you try running?  The one that we think should really work is:

```
call C:\path\to\miniconda\Scripts\activate
```

which should get you working conda, and then

```
conda init cmd.exe
```

which should keep it working in the future.

**Comment by Okroshiashvili** [comment] 2019-07-08 10:29
@msarahan I did what you suggested me but does not work. Still getting the same error. I don't know what to do. I tried every possible solution. Conda does not work at all. Running any command gives the same error as above.

Spyder and Jupyter work perfectly, but conda and anaconda-navigator do not.

**Comment by kunshouout** [comment] 2019-07-08 15:39
Had the same problem. 
"conda init cmd.exe" worked for me

**Comment by kunshouout** [comment] 2019-07-08 16:26
Had the same problem. 
After running "conda init cmd.exe", "conda list" works well. However, when I open a new cmd.exe and run python, it warns me that conda has not been activated. This problem goes away if i run "conda activate" before python, but do I have to run "conda activate" every time? How can I fix this? @msarahan

**Comment by msarahan** [comment] 2019-07-08 16:30
use "anaconda prompt"

If you don't have it, you can get it with ``conda install console_shortcut powershell_shortcut``

**Comment by Okroshiashvili** [comment] 2019-07-11 13:38
Nothing works! I don't know what else can I do.

**Comment by msarahan** [comment] 2019-07-11 13:56
Try just starting fresh.  Keep your old installation around, but install miniconda to a new folder.  Does this installation work?  If so, you can use it to fix your other installation.

**Comment by retsyo** [comment] 2019-07-20 13:33
I met the same problem on win7 64bits
1. I just downloaded and installed `Python 3.7 version 64-Bit Graphical Installer (662 MB)` from https://www.anaconda.com/distribution/, which is actually `Anaconda3-2019.03-Windows-x86_64.exe`
2. I just downloaded and installed `Win64 OpenSSL v1.1.1c Light` from https://slproweb.com/products/Win32OpenSSL.html
3. 
```
E:\prg\py\Anaconda3_64\Scripts>conda update matplotlib
Traceback (most recent call last):
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 1062, in
__call__
    return func(*args, **kwargs)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\cli\main.py", line 84, in _mai
n
    exit_code = do_call(args, p)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\cli\conda_argparse.py", line 8
0, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "E:\prg\py\Anaconda3_64\lib\importlib\__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\cli\main_update.py", line 8, i
n <module>
    from .install import install
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\cli\install.py", line 19, in <
module>
    from ..core.index import calculate_channel_urls, get_index
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\core\index.py", line 9, in <mo
dule>
    from .package_cache_data import PackageCacheData
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\core\package_cache_data.py", l
ine 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda_package_handling\api.py", line
 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "E:\prg\py\Anaconda3_64\lib\site-packages\libarchive\__init__.py", line 1, in
<module>
    from .entry import ArchiveEntry
  File "E:\prg\py\Anaconda3_64\lib\site-packages\libarchive\entry.py", line 6, in <mo
dule>
    from . import ffi
  File "E:\prg\py\Anaconda3_64\lib\site-packages\libarchive\ffi.py", line 27, in <mod
ule>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "E:\prg\py\Anaconda3_64\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "E:\prg\py\Anaconda3_64\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\prg\py\Anaconda3_64\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\cli\main.py", line 150, in mai
n
    return conda_exception_handler(_main, *args, **kwargs)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 1354, in
conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 1065, in
__call__
    return self.handle_exception(exc_val, exc_tb)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 1109, in
handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 1120, in
handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 1190, in
print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\cli\main_info.py", line 19, in
 <module>
    from ..core.index import _supplement_index_with_system
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\core\index.py", line 9, in <mo
dule>
    from .package_cache_data import PackageCacheData
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda\core\package_cache_data.py", l
ine 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda_package_handling\api.py", line
 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "E:\prg\py\Anaconda3_64\lib\site-packages\conda_package_handling\tarball.py",
line 7, in <module>
    import libarchive
  File "E:\prg\py\Anaconda3_64\lib\site-packages\libarchive\__init__.py", line 1, in
<module>
    from .entry import ArchiveEntry
  File "E:\prg\py\Anaconda3_64\lib\site-packages\libarchive\entry.py", line 6, in <mo
dule>
    from . import ffi
  File "E:\prg\py\Anaconda3_64\lib\site-packages\libarchive\ffi.py", line 27, in <mod
ule>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "E:\prg\py\Anaconda3_64\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "E:\prg\py\Anaconda3_64\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
```

**Comment by hameerabbasi** [comment] 2019-07-22 19:34
I am able to reproduce this problem to some extent on CI.

- CI Build logs: https://dev.azure.com/Quansight-Labs/uarray/_build/results?buildId=270&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=0f0b056b-e9f7-5ce7-8817-a8ca2fd77699&lineStart=221&lineEnd=221&colStart=1&colEnd=58
- Azure Pipelines YAML: https://raw.githubusercontent.com/Quansight-Labs/uarray/730aea6963dbb13d27ab91950b2dab955d697f0b/azure-pipelines.yml
- Environment YAML: https://raw.githubusercontent.com/Quansight-Labs/uarray/730aea6963dbb13d27ab91950b2dab955d697f0b/.conda/environment3.5.yml
- Azure Steps YAML: https://raw.githubusercontent.com/Quansight-Labs/uarray/730aea6963dbb13d27ab91950b2dab955d697f0b/ci/azure-steps-windows.yml

**Comment by dariuskay** [comment] 2019-07-27 20:28
This is a awkward bug. I think it lies within the Windows installer... Does the new stable release address this??

**Comment by msarahan** [comment] 2019-07-27 21:15
It takes some steps to avoid it, yes, but there are still ways that it can fail.  It is fundamentally a problem with how Windows searches for libraries, and the difficulty of managing a software collection that needs to have its libraries in a place other that immediately alongside the executables.

If you use Anaconda Prompt or otherwise ensure that you are activating your environment, there should be no issue.

**Comment by hameerabbasi** [comment] 2019-07-28 05:01
Is there a way to use Anaconda prompt on CI?

**Comment by hameerabbasi** [comment] 2019-07-28 06:43
It seems that this bug, in combination with microsoft/azure-pipelines-tasks#11016 means it's impossible to use a recent `conda` version on Azure Pipelines, AFAICT.

**Comment by chenqing** [comment] 2019-07-30 16:11
in windows 10  use `_conda` instead `conda`

**Comment by LaurentRDC** [comment] 2019-07-31 13:22
For those wondering a temporary fix in CI, you can pin your conda version to 4.6.14.

**Comment by ankitmathur45** [comment] 2019-08-05 08:39
Solved by doing 'conda init cmd.exe' and then 'conda list' works perfectly

**Comment by msarahan** [comment] 2019-08-07 00:14
This should be fixed by updating python-libarchive-c to build number 12 or higher.  These builds have a patch that helps python find libarchive and load it correctly.

Closing, but happy to reopen if that python-libarchive-c package doesn't fix things for you.

**Closed by msarahan** 2019-08-07 00:14 UTC

**Comment by stev-0** [comment] 2019-08-08 11:45
@msarahan how is this done exactly? `conda updatte python-libarchive-c` doesn't seem to install anything new, but I can see https://repo.anaconda.com/pkgs/main/win-64/python-libarchive-c-2.8-py37_13.tar.bz2.  `conda install python-libarchive-c=2.8-py37_13` also doesn't work, nor does `conda update python-libarchive-c=2.8-py37_13`. I have googled but to no avail - is it a manual thing?

**Comment by stev-0** [comment] 2019-08-08 11:59
@msarahan Solved using `conda install python-libarchive-c=2.8=py37_13`.

**Comment by simonm3** [comment] 2019-08-30 16:10
I have same error on brand new install of anaconda. Have tried all the above and nothing works.

**Comment by kuriakinzeng** [comment] 2019-09-07 01:27
I had the same problem. Adding <path-to-Anaconda>/Library/bin to PATH works for me.

**Comment by yunhua-deng** [comment] 2019-09-10 02:58
> use "anaconda prompt"
> 
> If you don't have it, you can get it with `conda install console_shortcut powershell_shortcut`

This works for me!

Windows 10, conda 4.7, python 3.7

**Comment by Duke-LeTran** [comment] 2019-09-10 17:50
> use "anaconda prompt"
> 

This worked, but I also had to open it using "Run as Administrator." Perhaps bc I had installed Anaconda as windows sudoer (heh)?

**Comment by gkamtzir** [comment] 2019-09-23 17:38
> I had the same problem. Adding `<path-to-Anaconda>/Library/bin` to PATH works for me.

That did the trick!

**Comment by msarahan** [comment] 2019-09-23 18:01
conda-package-handling 1.6.0 includes a new statically-linked libarchive library.  These problems should no longer be an issue with that update.
