### ISSUE TITLE
boost 1.60.0-py27-0 linked against icu 56 but conda installs icu 54 - cannot use boost_regex

### ISSUE THREAD

**Issue by dctrud** [conda/conda#3320] opened 2016-08-18 21:29 UTC
Going through the process of making a conda recipe for software that uses boost_regex I found any attempt to use boost_regex from the 1.60.0 conda package fails. By creating a fresh conda environment with only boost it's clear there is a mismatch in the boost and icu versions:

```
04:20 PM $ conda create -n boost boost
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home2/dtrudgian/.conda/envs/boost:

The following NEW packages will be INSTALLED:

    boost:      1.60.0-py27_0
    icu:        54.1-0       
    openssl:    1.0.2h-1     
    pip:        8.1.2-py27_0 
    python:     2.7.12-1     
    readline:   6.2-2        
    setuptools: 25.1.6-py27_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3      
```

The libboost_regex.so provided by `boost 1.60.0-py27-0` wants to link to .so.56 versions:

```
04:21 PM $ ldd ~/.conda/envs/boost/lib/libboost_regex.so
	linux-vdso.so.1 =>  (0x00007ffff7ffe000)
	libicudata.so.56 => not found
	libicui18n.so.56 => not found
	libicuuc.so.56 => not found
```

However the installed `icu 54.1-0` provides so.54 versions:

```
16:31 $ ls  ~/.conda/envs/boost/lib/libicu*
/home2/dtrudgian/.conda/envs/boost/lib/libicudata.so
/home2/dtrudgian/.conda/envs/boost/lib/libicudata.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libicudata.so.54.1
/home2/dtrudgian/.conda/envs/boost/lib/libicui18n.so
/home2/dtrudgian/.conda/envs/boost/lib/libicui18n.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libicui18n.so.54.1
/home2/dtrudgian/.conda/envs/boost/lib/libicuio.so
/home2/dtrudgian/.conda/envs/boost/lib/libicuio.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libicuio.so.54.1
/home2/dtrudgian/.conda/envs/boost/lib/libicule.so
/home2/dtrudgian/.conda/envs/boost/lib/libicule.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libicule.so.54.1
/home2/dtrudgian/.conda/envs/boost/lib/libiculx.so
/home2/dtrudgian/.conda/envs/boost/lib/libiculx.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libiculx.so.54.1
/home2/dtrudgian/.conda/envs/boost/lib/libicutest.so
/home2/dtrudgian/.conda/envs/boost/lib/libicutest.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libicutest.so.54.1
/home2/dtrudgian/.conda/envs/boost/lib/libicutu.so
/home2/dtrudgian/.conda/envs/boost/lib/libicutu.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libicutu.so.54.1
/home2/dtrudgian/.conda/envs/boost/lib/libicuuc.so
/home2/dtrudgian/.conda/envs/boost/lib/libicuuc.so.54
/home2/dtrudgian/.conda/envs/boost/lib/libicuuc.so.54.1
```

**Comment by ccordoba12** [comment] 2016-08-19 00:24
This is a duplicate of ContinuumIO/anaconda-issues#700

**Closed by ccordoba12** 2016-08-19 00:24 UTC
