### ISSUE TITLE
CondaHTTPError: 404 None

### ISSUE THREAD

**Issue by gnarlie** [conda/conda#5076] opened 2017-04-19 17:09 UTC
On a brand new installation (conda 4.2.13) when using "--use-local" I'm getting the error `CondaHTTPError: 404 None`

```
(empty) [12:02][badams@wud-badams01 ~/dev] $ 1 conda install --use-local anything
Fetching package metadata ....................

CondaHTTPError: HTTP 404 None
for url <None>

The remote server could not find the channel you requested.

You will need to adjust your conda configuration to proceed.
Use `conda config --show` to view your configuration's current state.
Further configuration help can be found at <http://conda.pydata.org/docs/config.html>.



(empty) [12:02][badams@wud-badams01 ~/dev] $ 1 conda --version
conda 4.2.13
```

**Comment by tyler-thetyrant** [comment] 2017-04-19 17:29
Can you try again after running `conda update conda`? We are currently on 4.3.16

**Comment by kalefranz** [comment] 2017-04-21 05:29
I can't reproduce this in the conda 4.3 feature branch, so I think it's been resolved. Going to close the issue.

**Closed by kalefranz** 2017-04-21 05:29 UTC
Labels: source:community, type:bug
