### ISSUE TITLE
Error with conda install (ValidationError: Invalid value 1505136837.5 for timestamp)

### ISSUE THREAD

**Issue by kostaconda** [conda/conda#6108] opened 2017-10-08 16:06 UTC
Hello I was hoping to obtain some help with an issue I am having when trying to use conda install. Every time I run conda install for any package I get the following error message. It was just working before but now I keep running into this issue. Thanks in advance for the help

Current conda install:

               platform : linux-32
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 1.19.0
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /home/kosta/anaconda2  (writable)
    default environment : /home/kosta/anaconda2
       envs directories : /home/kosta/anaconda2/envs
                          /home/kosta/.conda/envs
          package cache : /home/kosta/anaconda2/pkgs
                          /home/kosta/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda/linux-32
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.continuum.io/pkgs/main/linux-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-32
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Linux/4.10.0-35-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/kosta/anaconda2/bin/conda install -c anaconda libgfortran`

    Traceback (most recent call last):
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/kosta/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Invalid value 1505136837.5 for timestamp

**Comment by nehaljwani** [comment] 2017-10-08 16:47
Closing as duplicate of  #6096

**Closed by nehaljwani** 2017-10-08 16:47 UTC
