### ISSUE TITLE
"An unexpected error has occurred" when installing flask

### ISSUE THREAD

**Issue by tpudlik** [conda/conda#1036] opened 2014-12-08 03:00 UTC
Upon running `conda install flask`, I received the following traceback:

    Traceback (most recent call last):
      File "/home/ted/anaconda/bin/conda", line 5, in <module>
        sys.exit(main())
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
        args.func(args, p)
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
        install.install(args, parser, 'install')
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 184, in install
        unknown=args.unknown)
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/api.py", line 40, in get_index
        unknown=unknown)
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/utils.py", line 77, in __call__
        value = self.func(*args, **kw)
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 163, in fetch_index
        use_cache=use_cache, session=session)), reversed(channel_urls))
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 163, in <lambda>
        use_cache=use_cache, session=session)), reversed(channel_urls))
      File "/home/ted/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 82, in fetch_repodata
        cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
    IOError: invalid data stream

Here's the output of `conda info`:

               platform : linux-32
          conda version : 3.5.5
         python version : 2.7.7.final.0
       root environment : /home/ted/anaconda  (writable)
    default environment : /home/ted/anaconda
       envs directories : /home/ted/anaconda/envs
          package cache : /home/ted/anaconda/pkgs
           channel URLs : http://repo.continuum.io/pkgs/free/linux-32/
                          http://repo.continuum.io/pkgs/pro/linux-32/
            config file : None
      is foreign system : False

Let me know if any additional information would be helpful!

I was able to work around this by running `conda remove flask` and then `pip install flask`.

**Comment by ijstokes** [comment] 2016-04-20 21:04
I'm having this issue as well.

```python
$ /opt/wakari/miniconda/bin/conda install -p /opt/wakari/wakari-server django
Fetching package metadata: ....An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 239, in install
    offline=args.offline)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 264, in fetch_index
    reversed(channel_urls))
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 263, in <lambda>
    use_cache=use_cache, session=session)),
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 103, in fetch_repodata
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
IOError: invalid data stream
```

**Comment by ijstokes** [comment] 2016-04-20 21:53
My instance of this may be related to #1189, since I get this error with one user, but not with another.

User with problem (exception above):

```
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.0
     root environment : /opt/wakari/miniconda  (writable)
  default environment : /opt/wakari/miniconda
     envs directories : /opt/wakari/miniconda/envs
        package cache : /opt/wakari/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/noarch/
                        http://localhost:8080/conda/anaconda/linux-64/
                        http://localhost:8080/conda/anaconda/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /opt/wakari/.condarc
    is foreign system : False
```

and the associated `.condarc`:

```
channels:
  - https://conda.anaconda.org/t/TOKEN/anaconda-nb-extensions
  - http://localhost:8080/conda/anaconda
  - defaults
```

`TOKEN` is the actual token, and I've confirmed that I can get a real JSON file by going to 
https://conda.anaconda.org/t/TOKEN/anaconda-nb-extensions/linux-64/repodata.json

User with no problem:

```
$ /opt/wakari/miniconda/bin/conda info
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.0
     root environment : /opt/wakari/miniconda  (writable)
  default environment : /opt/wakari/miniconda
     envs directories : /opt/wakari/miniconda/envs
        package cache : /opt/wakari/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/wakari/linux-64/
                        https://conda.anaconda.org/wakari/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /opt/wakari/miniconda/.condarc
    is foreign system : False
```

And their `.condarc`:

```
channels:
  - https://conda.anaconda.org/wakari
  - defaults

create_default_packages:
  - anaconda-client
  - python
  - ipython-we
  - pip
```

**Comment by soapy1** [comment] 2016-10-13 19:52
I can't reproduce this issue on the newest version of conda. Closing the issue; if this is still a problem for you after updating conda, please reopen the issue.

**Closed by soapy1** 2016-10-13 19:52 UTC
