### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by jesuneken** [conda/conda#4697] opened 2017-02-21 11:34 UTC
c:\Users\Usuario>conda env create -f environment.yml
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (read only)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\Usuario\AppData\Local\conda\conda\envs
                          C:\Users\Usuario\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\Usuario\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601

`$ C:\ProgramData\Miniconda3\Scripts\conda-env-script.py create -f environment.y
ml`

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", li
ne 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\cli\main_creat
e.py", line 82, in execute
        directory=os.getcwd())
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\specs\__init__
.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a na
me
    Please install nbformat:
        conda install nbformat
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

c:\Users\Usuario>

**Comment by kalefranz** [comment] 2017-05-09 03:58
Duplicate of #3689

**Closed by kalefranz** 2017-05-09 03:58 UTC
Labels: source:community, tag:conda-env, type:bug
