### ISSUE TITLE
installed miniconda in order to install climada, having this issue RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by kenny070287** [conda/conda#12217] opened 2023-01-05 15:30 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

had conda 4.2.7 installed, but when trying to install climada related stuff `conda env create -n climada_env -f climada_python/requirements/env_climada.yml`, had the error `CommandNotFoundError: Command Error: error with command 'env'. Command not found: 'env'. Error: Could not locate 'conda-env' env Error: Could not locate 'conda-env'`.

when trying to run conda install conda, got the following error: 

`An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.8.6.final.0
       requests version : 2.28.1
       root environment : c:\users\kenny\desktop\climada\climada_python\env  (writable)
    default environment : c:\users\kenny\desktop\climada\climada_python\env
       envs directories : c:\users\kenny\desktop\climada\climada_python\env\envs
          package cache : c:\users\kenny\desktop\climada\climada_python\env\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ c:\users\kenny\desktop\climada\climada_python\env\Scripts\conda install conda`

    Traceback (most recent call last):
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\install.py", line 201, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\kenny\\desktop\\climada\\climada_python\\env\\pkgs\\menuinst-1.4.7-py36_0\\info\\has_prefix'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\install.py", line 209, in yield_lines
        raise StopIteration
    StopIteration

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\install.py", line 943, in link
        has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\install.py", line 248, in read_has_prefix
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\install.py", line 248, in <dictcomp>
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\install.py", line 247, in <genexpr>
        parsed_lines = (parse_line(line) for line in yield_lines(path))
    RuntimeError: generator raised StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "c:\users\kenny\desktop\climada\climada_python\env\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration`

### Conda Info

```shell
platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.8.6.final.0
       requests version : 2.28.1
       root environment : c:\users\kenny\desktop\climada\climada_python\env  (writable)
    default environment : c:\users\kenny\desktop\climada\climada_python\env
       envs directories : c:\users\kenny\desktop\climada\climada_python\env\envs
          package cache : c:\users\kenny\desktop\climada\climada_python\env\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False
```

### Conda Config

```shell
no output
```

### Conda list

```shell
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
```

### Additional Context

only has miniconda installed

**Comment by travishathaway** [comment] 2023-01-23 16:13
Hi @kenny070287,

I would suggest install a newer miniconda version. It appears you have gotten your hands a relatively old version, which may be the cause of your error.

Here are the latest downloads for miniconda:

- https://docs.conda.io/en/latest/miniconda.html

The latest versions come bundled with the `conda env` commands.

I will close this issue for now, but please feel free to reopen if your issues persist.

**Closed by travishathaway** 2023-01-23 16:13 UTC
Labels: type::support
