### ISSUE TITLE
conda.exceptions.UnsatisfiableError: " TypeError: sequence item 0: expected str instance, MultiChannel found"  when trying to install anything that has conflicts

### ISSUE THREAD

**Issue by makpcheng** [conda/conda#9855] opened 2020-04-17 15:49 UTC
I'm getting conda.exceptions.UnsatisfiableError "TypeError: sequence item 0: expected str instance, MultiChannel found", anytime I'm installing anything that has a conflict.  This is a new install on Ubuntu 18.04.

## Current Behavior
When installing a package that has a conflict it fails with the following error:
```
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed           
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError: 
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.
    
    conda config --set unsatisfiable_hints True
                
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "/home/makkari/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, MultiChannel found
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=facegpu
                CONDA_EXE=/home/makkari/anaconda3/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/home/makkari/anaconda3/envs/facegpu
           CONDA_PREFIX_1=/home/makkari/anaconda3
           CONDA_PREFIX_2=/home/makkari/anaconda3/envs/faced
    CONDA_PROMPT_MODIFIER=(facegpu)
         CONDA_PYTHON_EXE=/home/makkari/anaconda3/bin/python
               CONDA_ROOT=/home/makkari/anaconda3
              CONDA_SHLVL=3
                     PATH=/home/makkari/anaconda3/bin:/home/makkari/anaconda3/envs/facegpu/bin:/
                          home/makkari/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sb
                          in:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin
                          :/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=1

     active environment : facegpu
    active env location : /home/makkari/anaconda3/envs/facegpu
            shell level : 3
       user config file : /home/makkari/.condarc
 populated config files : /home/makkari/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=9.1
                          __glibc=2.27
       base environment : /home/makkari/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/makkari/anaconda3/pkgs
                          /home/makkari/.conda/pkgs
       envs directories : /home/makkari/anaconda3/envs
                          /home/makkari/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/5.3.0-46-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
### Steps to Reproduce
Installed any package that would cause conflicts such as...
```
conda install tensorflow-gpu=1.12.0
```

## Expected Behavior
It should resolve those conflicts

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
 active environment : facegpu
    active env location : /home/makkari/anaconda3/envs/facegpu
            shell level : 3
       user config file : /home/makkari/.condarc
 populated config files : /home/makkari/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=9.1
                          __glibc=2.27
       base environment : /home/makkari/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/makkari/anaconda3/pkgs
                          /home/makkari/.conda/pkgs
       envs directories : /home/makkari/anaconda3/envs
                          /home/makkari/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/5.3.0-46-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/makkari/.condarc <==
report_errors: False
unsatisfiable_hints: True

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/makkari/anaconda3/envs/facegpu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.9.0                    py36_0    defaults
asn1crypto                1.3.0                    py36_0    defaults
astor                     0.8.0                    py36_0    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h7b6447c_1001    defaults
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2020.4.5.1       py36h9f0ad1d_0    conda-forge
cffi                      1.14.0           py36h2e261b9_0    defaults
chardet                   3.0.4                 py36_1003    defaults
click                     7.1.1                    pypi_0    pypi
conda-package-handling    1.6.0            py36h7b6447c_0    defaults
cryptography              2.8              py36h1ba5d50_0    defaults
cycler                    0.10.0                   py36_0    defaults
dbus                      1.13.12              h746ee38_0    defaults
dlib                      19.19.99                 pypi_0    pypi
expat                     2.2.6                he6710b0_0    defaults
face-recognition          1.3.0                    pypi_0    pypi
face-recognition-models   0.3.0                    pypi_0    pypi
ffmpeg                    4.1.3                h167e202_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.9.1                h8a8886c_1    defaults
gast                      0.3.3                      py_0    defaults
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.63.1               h5a9c865_0    defaults
gmp                       6.2.0                he1b5a44_2    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
grpcio                    1.27.2           py36hf8bcb03_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.10.0           py36h7918eee_0    defaults
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.4               hb1b8bf9_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.9                        py_1    defaults
imageai                   2.1.5                    pypi_0    pypi
imutils                   0.5.3                    pypi_0    pypi
intel-openmp              2020.0                      166    defaults
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
keras                     2.2.4                         0    defaults
keras-applications        1.0.8                      py_0    defaults
keras-base                2.2.4                    py36_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
kiwisolver                1.1.0            py36he6710b0_0    defaults
lame                      3.100             h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
liblapacke                3.8.0                    15_mkl    conda-forge
libpng                    1.6.37               hbc83047_0    defaults
libprotobuf               3.11.4               hd408876_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
markdown                  3.1.1                    py36_0    defaults
matplotlib                3.1.3                    py36_0    defaults
matplotlib-base           3.1.3            py36hef1b27d_0    defaults
mkl                       2020.0                      166    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.0.15           py36ha843d7b_0    defaults
mkl_random                1.1.0            py36hd6b4f25_0    defaults
ncurses                   6.2                  he6710b0_0    defaults
nettle                    3.4.1             h1bed415_1002    conda-forge
numpy                     1.18.1           py36h4f9e942_0    defaults
numpy-base                1.18.1           py36hde5b4d6_1    defaults
olefile                   0.46                     py36_0    defaults
opencv                    4.1.0            py36h5517eff_4    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1f               h516909a_0    conda-forge
pcre                      8.43                 he6710b0_0    defaults
pillow                    7.0.0            py36hb39fc2d_0    defaults
pip                       20.0.2                   py36_1    defaults
pixman                    0.38.0            h516909a_1003    conda-forge
protobuf                  3.11.4           py36he6710b0_0    defaults
pycosat                   0.6.3            py36h7b6447c_0    defaults
pycparser                 2.20                       py_0    defaults
pyopenssl                 19.1.0                   py36_0    defaults
pyparsing                 2.4.6                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
pysocks                   1.7.1                    py36_0    defaults
python                    3.6.10               hcf32534_1    defaults
python-dateutil           2.8.1                      py_0    defaults
python_abi                3.6                     1_cp36m    conda-forge
pyyaml                    5.3.1            py36h7b6447c_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  8.0                  h7b6447c_0    defaults
requests                  2.23.0                   py36_0    defaults
ruamel_yaml               0.15.87          py36h7b6447c_0    defaults
scipy                     1.4.1            py36h0b6359f_0    defaults
setuptools                46.1.3                   py36_0    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.14.0                   py36_0    defaults
sqlite                    3.31.1               h7b6447c_0    defaults
tensorboard               1.12.2           py36he6710b0_0    defaults
tensorflow                1.12.0          mkl_py36h69b6ba0_0    defaults
tensorflow-base           1.12.0          mkl_py36h3c3e929_0    defaults
termcolor                 1.1.0                    py36_1    defaults
tk                        8.6.8                hbc83047_0    defaults
tornado                   6.0.4            py36h7b6447c_1    defaults
tqdm                      4.44.1                     py_0    defaults
urllib3                   1.25.8                   py36_0    defaults
werkzeug                  1.0.1                      py_0    defaults
wheel                     0.34.2                   py36_0    defaults
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

```
</p></details>

**Comment by kenodegard** [comment] 2022-06-16 21:09
Duplicate of #9681

**Closed by kenodegard** 2022-06-16 21:09 UTC
Labels: duplicate
