### ISSUE TITLE
no-arch install with conda-forge

### ISSUE THREAD

**Issue by jreback** [conda/conda#5761] opened 2017-08-01 12:21 UTC
see end of: https://travis-ci.org/pandas-dev/pandas/jobs/259724201

Travis CI started failing yesterday when pulling packages from conda-forge

```
Current conda install:
               platform : linux-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/travis/miniconda3  (writable)
    default environment : /home/travis/miniconda3
       envs directories : /home/travis/miniconda3/envs
                          /home/travis/.conda/envs
          package cache : /home/travis/miniconda3/pkgs
                          /home/travis/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/travis/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.14.2 CPython/3.6.1 Linux/4.11.6-041106-generic debian/jessie/sid glibc/2.19    
                UID:GID : 2000:2000
# conda environments:
#
root                  *  /home/travis/miniconda3
```

At the end of the logs
```
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-forge
It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.
If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.......
PackageNotFoundError: Packages missing in current channels:
            
  - feather-format
We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

**Comment by jreback** [comment] 2017-08-01 12:21
cc @kalefranz

**Comment by jreback** [comment] 2017-08-01 12:22
note that nothing that changed in pandas in last 2 days, nor Travis AFAICT.

**Comment by jreback** [comment] 2017-08-01 12:23
cc @ocefpaf

**Comment by ocefpaf** [comment] 2017-08-01 12:42
Bring @jjhelmus, @mingwandroid, and @msarahan here to help.

PS: did you try pinning to an older `conda` version?

**Comment by jreback** [comment] 2017-08-01 12:57
its the *same* conda version :<  4.3.23 (e.g working from a day ago: https://travis-ci.org/pandas-dev/pandas/jobs/259194863)

**Comment by ocefpaf** [comment] 2017-08-01 13:05
That is quite odd. Conda should not crash b/c the `noarch` directory is missing. Although it is not, we can access it [here](https://conda.anaconda.org/conda-forge/noarch), and the requested file [here](https://conda.anaconda.org/conda-forge/noarch/repodata.json). I believe you are not the first one to report this. Let me try to find the other issues and xref them here.

**Comment by ocefpaf** [comment] 2017-08-01 13:06
xref: https://github.com/conda-forge/conda-forge.github.io/issues/419

**Comment by jjhelmus** [comment] 2017-08-01 13:08
Is this error repeatable?  I tried to reproduce the error locally in a docker image and was not successful.  Perhaps Travis CI had a network error that made conda.anaconda.org inaccessible for a short time?

**Comment by jreback** [comment] 2017-08-01 13:08
also seems conda removed some older packages (e.g. xlsxwriter 0.4.6, bottleneck 0.8.0) from defaults, no big deal (https://github.com/pandas-dev/pandas/pull/17142)

**Comment by jreback** [comment] 2017-08-01 13:09
see https://travis-ci.org/pandas-dev/pandas/pull_requests

worked 1 day ago, failing last 12 hours AFAICT.

**Comment by Lnaden** [comment] 2017-08-01 13:20
I can also confirm this is repeatable on [Travis-CI](https://travis-ci.org/choderalab/yank/jobs/259747263#L575-L634), but it appears to be a problem when searching the channels missing  noarch directory for packages since conda packages are still installable in general, but none from conda-forge or others are found.

Example: [build from yesterday](https://travis-ci.org/choderalab/yank/jobs/259431184#L501-L521) correctly pulls the packages from the higher priority conda-forge channel, but [fails this morning and falls back to default channel](https://travis-ci.org/choderalab/yank/jobs/259747263#L501-L544). Comparison is on same Travis-build version and same base conda install version, so there should not be any difference.

When it tries to find a package on channels without a `noarch` directory, it [appears to fail](https://travis-ci.org/choderalab/yank/jobs/259747263#L575-L634). In this case there should be a `nose-timer` on `conda-forge` and the `omnia` channel, but neither are fetched and the install fails since it does not exist on `default`. Since the package `nose-timer` *should* exist on two channels in the search, it should find at least one of them, but does not.

**Comment by jjhelmus** [comment] 2017-08-01 13:21
From the log is does not seem like any channels hosted on conda.anaconda.org are being detected.  Specifically the initial environment creation is only installing packages from `defaults` despite `conda-forge` having higher precedence: https://travis-ci.org/pandas-dev/pandas/jobs/259601225#L656-L733.

**Comment by glemaitre** [comment] 2017-08-01 13:46
The same issue in pydicom to install a conda-forge package:
https://travis-ci.org/glemaitre/pydicom/jobs/259710021#L942

**Comment by jakirkham** [comment] 2017-08-01 14:17
I don't think the cause of this issue is `conda`. Saying this because things worked fine earlier yesterday with `conda` 4.3.23 and stopped working a few hours later, but still had the same `conda` version.

Working: https://travis-ci.org/dask-image/dask-ndmeasure/builds/259373631
Failing: https://travis-ci.org/dask-image/dask-ndmeasure/builds/259469273

**Comment by jjhelmus** [comment] 2017-08-01 14:23
> I don't think the cause of this issue is conda

I agree.  I made a [repository](https://github.com/jjhelmus/bug-free-disco) where I've been debugging this issue I regardless of the conda version I have not been able to get conda to install anything from the `conda-forge` channel.

* conda 4.3.23 : https://travis-ci.org/jjhelmus/bug-free-disco/builds/259789276
* conda 4.3.16 : https://travis-ci.org/jjhelmus/bug-free-disco/builds/259791028

Notice that all the packages in the test environment are from `defaults`.

**Comment by glemaitre** [comment] 2017-08-01 14:32
We are building our doc in Circle CI and in this case the install is working as well.
The problem seems to be with Travis.

**Comment by jjhelmus** [comment] 2017-08-01 14:57
Attempting to fetch repodata.json from conda.anaconda.org on Travis CI fails with a 403 Forbidden.  This happens from [within conda](https://travis-ci.org/jjhelmus/bug-free-disco/builds/259803623#L593-L612) or if the same file is downloaded [using wget](https://travis-ci.org/jjhelmus/bug-free-disco/builds/259806247#L548-L553).

```
$ wget https://conda.anaconda.org/jjhelmus/linux-64/repodata.json -O repodata.json
--2017-08-01 14:54:21--  https://conda.anaconda.org/jjhelmus/linux-64/repodata.json
Resolving conda.anaconda.org (conda.anaconda.org)... 104.16.193.233, 104.16.192.233, 2400:cb00:2048:1::6810:c0e9, ...
Connecting to conda.anaconda.org (conda.anaconda.org)|104.16.193.233|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-08-01 14:54:21 ERROR 403: Forbidden.
```

**Comment by jakirkham** [comment] 2017-08-01 15:14
Have you tried with `wget` using verbose mode? Not sure if it will give us anything useful, but maybe.

**Comment by jjhelmus** [comment] 2017-08-01 15:18
> Have you tried with wget using verbose mode?

Yes!  Looks as if the Travis CI IP address is being blocked by conda.anaconda.org, https://travis-ci.org/jjhelmus/bug-free-disco/builds/259810868#L424-L540.  I'm working with Continuum folks to figure out the details.

**Comment by jakirkham** [comment] 2017-08-01 15:19
Thanks @jjhelmus!

**Comment by jjhelmus** [comment] 2017-08-01 15:41
The Travis CI IP address has been unblocked and should be once again working.  Sorry all the troubles this caused.

**Comment by Lnaden** [comment] 2017-08-01 15:47
Huzzah! Confirming up and running here

**Comment by jakirkham** [comment] 2017-08-01 15:54
Also appears to be working for me as well. Thanks for resolving this.

**Closed** 2017-08-01 17:32 UTC

**Comment by jreback** [comment] 2017-08-01 18:27
thanks everyone for the fast action!
