### ISSUE TITLE
Cannot update conda

### ISSUE THREAD

**Issue by GeoWicks** [conda/conda#3979] opened 2016-12-01 00:23 UTC
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/gwicks/anaconda2/bin/conda", line 5, in <module>
    
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    p = sub_parsers.add_parser(
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    add_unlink(actions, dist)
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    commands = {
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    symlink_conda(state['prefix'], arg)
  File "/home/gwicks/anaconda2/lib/python2.7/site-packages/conda/install.py", line 616, in link
    else:
  File "/home/gwicks/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/gwicks/anaconda2/lib/python2.7/site-packages/pip/_vendor/html5lib/_trie'

[gwicks@localhost ~]$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.2
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /home/gwicks/anaconda2  (writable)
    default environment : /home/gwicks/anaconda2
       envs directories : /home/gwicks/anaconda2/envs
          package cache : /home/gwicks/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

[gwicks@localhost ~]$

**Comment by worry1613** [comment] 2016-12-04 13:22
root@feb1d0de1508:/opt/conda/bin# conda install jupyter -y --quiet
Fetching package metadata ....Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
....
Solving package specifications: ..........

Package plan for installation in environment /opt/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    conda-4.2.13               |           py35_0         402 KB
    ------------------------------------------------------------
                                           Total:         402 KB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

The following packages will be UPDATED:

    conda:     4.2.9-py35_0 --> 4.2.13-py35_0

Could not connect to https://repo.continuum.io/pkgs/free/linux-64/conda-4.2.13-py35_0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /opt/conda/bin/conda install jupyter -y --quiet`




    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "/opt/conda/lib/python3.5/ssl.py", line 377, in wrap_socket
        _context=self)
      File "/opt/conda/lib/python3.5/ssl.py", line 752, in __init__
        self.do_handshake()
      File "/opt/conda/lib/python3.5/ssl.py", line 988, in do_handshake
        self._sslobj.do_handshake()
      File "/opt/conda/lib/python3.5/ssl.py", line 633, in do_handshake
        self._sslobj.do_handshake()
    socket.timeout: _ssl.c:629: The handshake operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 355, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 315, in _raise_timeout
        raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/conda-4.2.13-py35_0.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 377, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3.05, 27))
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/conda-4.2.13-py35_0.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/conda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 403, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/conda-4.2.13-py35_0.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/linux-64/conda-4.2.13-py35_0.tar.bz2


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/opt/conda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/conda-4.2.13-py35_0.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/linux-64/conda-4.2.13-py35_0.tar.bz2

**Comment by kalefranz** [comment] 2017-05-01 19:35
The permissions stack trace got fixed in 4.3.   The other error is an intermittent http issue.

**Closed by kalefranz** 2017-05-01 19:35 UTC
