### ISSUE TITLE
Conda activate does not activate environment

### ISSUE THREAD

**Issue by domoritz** [conda/conda#7968] opened 2018-11-16 06:09 UTC
When I activate an env, it is not activated. I have not yet installed anything.

## Current Behavior

```
$ which python
~/anaconda3/bin/python
```

### Steps to Reproduce

```
$ conda create --name foo
$ conda activate foo
```

## Expected Behavior

```
$ which python
~/anaconda3/envs/foo/bin/python
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : foo
    active env location : /homes/gws/domoritz/anaconda3/envs/foo
            shell level : 1
       user config file : /homes/gws/domoritz/.condarc
 populated config files : /homes/gws/domoritz/.condarc
          conda version : 4.5.11
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /homes/gws/domoritz/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /homes/gws/domoritz/anaconda3/pkgs
                          /homes/gws/domoritz/.conda/pkgs
       envs directories : /homes/gws/domoritz/anaconda3/envs
                          /homes/gws/domoritz/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Linux/4.9.115-1.el7.retpoline.x86_64 centos/7 glibc/2.17
                UID:GID : 26909:6201
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /homes/gws/domoritz/.condarc <==
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /homes/gws/domoritz/anaconda3/envs/foo:
#
# Name                    Version                   Build  Channel
```
</p></details>

**Comment by nehaljwani** [comment] 2018-11-24 08:05
1. Creating an environment should not add anything in it, so the expected behaviour of having `~/anaconda3/envs/foo/bin/python` as the output for `which python` is wrong.
2. You see that ~/anaconda3/bin is still in PATH because conda stacks environment by default (this is going to change with 4.6.x). To avoid this, you can do: `conda config --set max_shlvl 1`

Assuming that you actually were referring to 2, I am going to go ahead and close this as duplicate of https://github.com/conda/conda/issues/7933 . Feel free to re-open if that's not the case.

**Closed by nehaljwani** 2018-11-24 08:05 UTC

**Comment by domoritz** [comment] 2018-11-24 08:08
> Creating an environment should not add anything in it, so the expected behaviour of having ~/anaconda3/envs/foo/bin/python as the output for which python is wrong.

Interesting. I get `~/anaconda3/envs/foo/bin/python` for an environment that I created earlier. I guess something went wrong then.
