### ISSUE TITLE
Add conda fetch or download command

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1150] opened 2015-02-13 01:52 UTC
As part of the work of creating offline environments I need a reliable way to retrieve a package and write it to another location.  The proposal is to add a `conda fetch` or `conda download` command.
## Proposed Interface

Note, `conda fetch` is used here, but it could be `conda fetch` or `conda download`

Here's an example that would simply download the packages and place the tarballs in the package cache.

``` bash
$ conda fetch ipython-notebook
```

Here's an example that would download the packages but write them to another directory:

``` bash
$ conda fetch ipython-notebook --directory=/path/to/dir
# or
$ conda fetch ipython-notebook -d /path/to/dir
```
## Proposed Implementation

This should work through the same mechanism as `conda install`.  It should build the index and determine what package to fetch / use.  If a local tarball is available in the package cache, fetch should not re-retrieve the file from the index.  If a local file is available and `-d|--directory` was used it should use that tarball when writing to disk.

**Comment by tswicegood** [comment] 2015-02-13 16:30
@epl-ca -- this is the issue we talked about you working on.  Let me know if you have any questions.  I'm sure @ilanschnell and @asmeurer can answer them too.

**Comment by ilanschnell** [comment] 2015-02-13 16:43
I assume, `conda fetch` should download the latest version of the package.  What about different builds of the same package (e.g. Python 2.7, 3.3, 3.4 or MKL vs. non-MKL linked)?  Which of these should the command download?  Also, should dependencies also be downloaded?

**Comment by tswicegood** [comment] 2015-02-13 16:44
@ilanschnell all dependencies.  My thought is that it would act just like `conda install`, but give you the tarballs the instructions would install so you can wrote those to disk elsewhere.

**Comment by ilanschnell** [comment] 2015-02-13 16:55
`conda install` looks at the active environment and then chooses packages according to Python version and features.  To do the same for `conda fetch`, it would also have to look at the active environment.  So, yes, basically it does what `conda install` doesm without extracting and linking the packages.

**Comment by tswicegood** [comment] 2015-02-13 19:26
@ilanschnell is there a way to look at that information and fetch any packages that aren't in the package cache and then return the list of those packages?

**Comment by asmeurer** [comment] 2015-02-13 19:47
Regarding the name, I think it should just be a flag to `install`, like `conda install --download-only`.

**Comment by ilanschnell** [comment] 2015-02-13 19:51
I was thinking the same, because the code path is so similar.

**Comment by tswicegood** [comment] 2015-02-13 21:14
I'm -0 on it.  Don't really care, but it always feel weird to type `pip install --download` and know that it's not actually going to install.  `conda fetch` came to mind because of git.  Most people use `git pull`, but under the cover it's `git fetch && git merge`.  In terms of mapping conda's actions to the actual things, I was thinking of `conda fetch && conda link` or some such as how it would map (yes, I know `conda link` doesn't exist).

At any rate, I just need a command (or command plus options) that allows me to take a package, download it if necessary, and output it to another directory.

**Comment by mnazbro** [comment] 2015-09-18 21:36
I'm very interested in a download functionality. However, I'm particularly interested in downloading for a specific architecture or Python version. I often run into the situation where I'm developing on a Mac computer but need to deploy a product offline on a Linux computer. Could we make sure that there is a way to download the dependencies offline for a different architecture?

It looks like `conda.api.app_info_packages` could easily be modified to take an optional platform to make this easy to do even if the command line version doesn't exist.

**Comment by greyltc** [comment] 2016-12-11 15:58
+1 for making sure this can be done across platforms (so that I could fetch packages for 32bit Windows XP from Linux for example). 

I think that feature might be hard though. Every time `conda install` would have inspected the system to help it decide what to download, `conda fetch` would then need a flag to override the result of that inspection. And packages should it assume are already installed on the target system? 0_o

Also, it would be helpful if the tool had the option putting multiple packages it might fetch into one .tar file.

**Comment by y2kbugger** [comment] 2016-12-19 05:14
Another +1 for cross platform flags. I also agree about the tar as well.

One assumption would be to be able to choose a miniconda or full anaconda or no assumptions (updating all packages) to be already installed.

**Comment by nouiz** [comment] 2017-09-20 15:05
Note, I have this need to download only (without the cross platform need).

The way I work around it not available is by making an env and downloading stuff there. This env is only for download, so then it will work later offline in my real env.

Just in case this work around help someone.

**Comment by jkmacc-LANL** [comment] 2017-09-20 15:27
@nouiz I've looked at doing this, but I think all packages for all environments land in the same place, `$ANACONDAHOME/pkgs`, which makes it a pain to collect the ones for a specific environment.  Did you have another way to do this?

**Comment by kalefranz** [comment] 2017-09-20 16:29
Guess https://github.com/conda/conda/issues/5983 is a dupe of this ticket.

**Comment by nouiz** [comment] 2017-09-20 16:58
@jkmacc-LANL I never read conda code. From what I know, you are right, all packages end up installed in the same directory and the env symlink link to them. As "conda install" compute the dependency itself for a specific env, he is able to get the information you want.

Why not have "conda fetch" call internally a "conda install --download-only"? This would reuse much of the code while still having the not strange user interface? (This can be hard or relatively easy depending of the code, can't guess as I didn't try it).

@jkmacc-LANL My work around is pretty simple:
- conda create -n myenv_cloned --clone myenv
- source activate myenv_cloned
- conda install THE_PACKAGE_YOU_WANT

Personally, for the last line, I use "conda update --all", so having "conda fetch --update-all" would be what I would need. Which wasn't the exact same request from the original description.

**Comment by jkmacc-LANL** [comment] 2017-09-20 17:10
I'd just like a way to collect everything in my environment into a bz2 file, like `conda env export -n my_env --bz2 -f my_env.tar.bz2`, where `--bz2` is for a bz2 output.

**Comment by kalefranz** [comment] 2018-03-02 10:25
Conda 4.4 has added a `--download-only` flag.

**Closed by kalefranz** 2018-03-02 10:25 UTC
Labels: type:feature
