### ISSUE TITLE
conda install from file doesn't respect channels in .condarc

### ISSUE THREAD

**Issue by talumbau** [conda/conda#1340] opened 2015-05-20 13:30 UTC
A file named 'conda-requirements.txt` has the following contents:

```
packageA
packageB
packageC
```

A .condarc file in the user's path exists as follows:

```
channels:
  - https://conda.binstar.org/some_organization
  - defaults
```

The binstar channel for `some_organization` contains the packages for `packageB`. Executing:

```
conda install --file conda-requirements.txt
```

Results in:

```
Error: No packages found in current osx-64 channels matching: packageB
```

A manual installation:

```
conda install -c some_organization packageB
```

is successful.

Seems like a bug.

**Comment by openvest** [comment] 2015-05-20 15:21
Does ~/.condarc say anything about "channel_alias"  ?

**Comment by talumbau** [comment] 2015-05-20 16:47
no. I have shown the entire contents of the .condarc

**Comment by asmeurer** [comment] 2015-05-20 16:49
Can you tell me specifically what `some_organization` and `packageB` are?

**Comment by talumbau** [comment] 2015-05-20 17:07
Sure. `some_organization`=`ospc`. `packageB`=`taxcalc`

**Comment by asmeurer** [comment] 2015-05-20 17:18
I can't reproduce this. If you can show me the machine where this is happening I can take a closer look.

**Comment by talumbau** [comment] 2015-05-20 17:24
it appears that `conda install packagename` will look in the .condarc in the current directory. As far as I can see, `conda install --file filename` will not look for a .condarc in the directory, but rather only ~/.condarc. Can you confirm this?

**Comment by kalefranz** [comment] 2017-05-09 03:56
Outdated. Closing.  If there are ongoing related issues, can always re-open.

**Closed by kalefranz** 2017-05-09 03:56 UTC
