### ISSUE TITLE
conda update ignores pinning

### ISSUE THREAD

**Issue by eli-osherovich** [conda/conda#9995] opened 2020-06-10 09:11 UTC
## Current Behavior

`conda update` ignores pinning: it tries to install packages that violate pinning rules.

### Steps to Reproduce

```
conda create --name test
conda activate test
echo -n 'blas[build=*mkl]' > $CONDA_PREFIX/conda-meta/pinned
conda install blas # it installs correct (MKL) blas
conda update --all # it tries to install openblas
```

## Expected Behavior

conda should respect pinning and use MKL blas

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

    active environment : test
    active env location : /home/eli/virtenvs/test
            shell level : 1
       user config file : /home/eli/.condarc
 populated config files : /home/eli/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.30
       base environment : /home/eli/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/eli/miniconda3/pkgs
                          /home/eli/.conda/pkgs
       envs directories : /home/eli/virtenvs
                          /home/eli/miniconda3/envs
                          /home/eli/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/5.6.0-2-amd64 debian/testing glibc/2.30
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
auto_activate_base: False
env_prompt: ({name})
pip_interop_enabled: True
envs_dirs:
  - ~/virtenvs
channels:
  - conda-forge
  - pytorch
  - intel
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/eli/virtenvs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
blas                      2.15                        mkl    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
liblapacke                3.8.0                    15_mkl    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
mkl                       2020.1                      219    conda-forge

```
</p></details>

**Comment by eli-osherovich** [comment] 2020-06-12 06:46
This issue is probably related to #9981

**Comment by jeanmonet** [comment] 2020-06-20 09:53
Quick side question related to the location of the `pinned` file - hope it's not inappropriate to ask this here.

The documentation refers to: `~/anaconda/conda-meta/pinned`

But can it be located in: `~/anaconda/envs/myenv/conda-meta/pinned` ?
Does the latter have any effect?

**Comment by eli-osherovich** [comment] 2020-06-29 07:44
Any reaction from the authors?

**Comment by endolith** [comment] 2021-07-06 14:59
Yeah I pinned `python 3.8.*` and `scikit-learn ==0.24.1` because 0.24.2 consistently fails to install on Windows 7, and 3.9 is no longer supported, but when I `conda update --all` it tries to install 

    scikit-learn                        0.24.1-py38hf11a4ad_0 --> 0.24.2-py38hf11a4ad_1

anyway, which fails.

**Comment by randolf-scholz** [comment] 2021-09-07 13:12
Having the same issue. Oddly enough, mamba detects and uses the `pinned` file just fine.

**Comment by jezdez** [comment] 2021-09-17 19:45
Closing as duplicate of #9016.

**Closed by jezdez** 2021-09-17 19:45 UTC
