### ISSUE TITLE
BlockingIOError(11, 'write could not complete without blocking', 4048) on Travis

### ISSUE THREAD

**Issue by j3mdamas** [conda/conda#6481] opened 2017-12-17 22:36 UTC
Hi Conda team,

We've been facing issues on Travis machines, and it's been hard to solve them. Currently we have `conda install` commands that are failing on those machines with the error in title (more logging below). The command works fine locally. The failures do not occur always at the same package. I tried googl'ing the error and conda or travis, but I couldn't find any information. I also saw this ticket (https://github.com/conda/conda/issues/6473), so maybe there is something general going in Travis machines regarding IO. Is there anything that could help track down this problem? Thank you!

```
[0K$ conda install --file package/htmd-deps/DEPENDENCIES -y
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/travis/miniconda/envs/travis-env:

The following NEW packages will be INSTALLED:

    acecloud-client:    1.0.42-py36_1              acellera
    acemd:              2017.11.30-h1254938_0      acellera
    acemd-examples:     2016.5.12-1                acellera
    ambermini:          16.16.0-7                  acellera
    attrs:              17.3.0-py36h5ab58ff_0              
    bhmm:               0.6.1-np112py36_0          acellera
    bleach:             2.1.1-py36hd521086_0               
    boost:              1.63.0-py36h415b752_1      acellera
    boto3:              1.4.8-py36h0bb4d74_0               
    botocore:           1.8.5-py36hac303ac_0               
    bzip2:              1.0.6-h6d464ef_2                   
    cairo:              1.14.10-hdf128ce_6                 
    chemps2:            1.8.3-5                    psi4    
    cloog:              0.18.0-0                           
    coverage:           4.4.2-py36hca7c4c5_0               
    cycler:             0.10.0-py36h93f1223_0              
    cython:             0.27.3-py36h1860423_0              
    dbus:               1.10.22-h3b5a359_0                 
    dftd3:              3.2.0-7                    psi4    
    dkh:                1.2-0                      psi4    
    docutils:           0.14-py36hb0f60f5_0                
    entrypoints:        0.2.3-py36h1aec115_2               
    erd:                3.0.6-0                    psi4    
    et_xmlfile:         1.0.1-py36hd6bccc3_0               
    expat:              2.2.5-he0dffb1_0                   
    fftw3f:             3.3.4-2                    acellera
    fontconfig:         2.12.4-h88586e7_1                  
    freetype:           2.8-hab7d2ae_1                     
    gcc-5:              5.2.0-1                    psi4    
    gcc-5-mp:           5.2.0-0                    psi4    
    gdma:               2.2.6-2                    psi4    
    glib:               2.53.6-h5d9569c_2                  
    gmp:                6.1.2-h6c8ec71_1                   
    gst-plugins-base:   1.12.2-he3457e5_0                  
    gstreamer:          1.12.2-h4f93127_0                  
    hdf5:               1.8.17-2                           
    htmd-data:          0.0.45-py_0                acellera
    htmd-pdb2pqr:       2.1.1+htmd.3-pyh13f2e89_0  acellera
    html5lib:           1.0.1-py36h2f9c1c0_0               
    hypothesis:         3.38.5-py36h196a6cc_0              
    icu:                58.2-h9c2bf20_1                    
    intel-openmp:       2018.0.0-hc7b2577_8                
    ipykernel:          4.7.0-py36h2f9c1c0_0               
    ipyparallel:        6.0.2-py36_0                       
    ipython:            6.2.1-py36h88c514a_1               
    ipywidgets:         7.0.5-py36h31d6531_0               
    isl:                0.12.2-0                           
    jdcal:              1.3-py36h4c697fb_0                 
    jedi:               0.11.0-py36_2                      
    jinja2:             2.10-py36ha16c418_0                
    jmespath:           0.9.3-py36hd3948f9_0               
    joblib:             0.11-py36_0                        
    jpeg:               9b-h024ee3a_2                      
    jupyter_client:     5.1.0-py36h614e9ea_0               
    jupyter_console:    5.2.0-py36he59e554_1               
    libefp:             1.4.2-0                    psi4    
    libgcc:             7.2.0-h69d50b8_2                   
    libgfortran-ng:     7.2.0-h9f7466a_2                   
    libint:             1.2.1-0                    psi4    
    libpng:             1.6.32-hbd3595f_4                  
    libsodium:          1.0.15-hf101ebd_0                  
    libtiff:            4.0.9-h28f6b97_0                   
    libxc:              3.0.0-3                    psi4    
    libxcb:             1.12-hcd93eb1_4                    
    libxml2:            2.9.4-h2e8b1d7_6                   
    llvmlite:           0.21.0-py36ha241eea_0              
    markupsafe:         1.0-py36hd9260cd_1                 
    match:              0.0.6-h2c94f36_0           acellera
    matplotlib:         2.1.1-py36ha26af80_0               
    mdtraj:             1.9.1-py36_0               acellera
    mistune:            0.8.1-py36h3d5977c_0               
    mkl:                2018.0.1-h19d6760_4                
    mock:               2.0.0-py36h3c5bf6c_0               
    mpc:                1.0.1-0                            
    mpfr:               3.1.2-0                            
    msmtools:           1.2.1-np112py36_0          acellera
    natsort:            5.1.0-py36_0                       
    nbconvert:          5.3.1-py36hb41ffb7_0               
    networkx:           2.0-py36h7e96fb8_0                 
    nglview:            1.0-py36_1                 acellera
    nlopt:              2.4.2-py36_2               acellera
    notebook:           5.2.2-py36h40a37e6_0               
    numba:              0.36.1-np112py36hf993da8_0         
    numexpr:            2.6.4-py36hc4a3f9a_0               
    numpy:              1.12.1-py36he24570b_1              
    olefile:            0.44-py36h79f9f78_0                
    openbabel:          2.4.1-py36_3               acellera
    openmm:             7.1.1-py36_0               acellera
    openpyxl:           2.4.9-py36hb5dfbf6_0               
    pandas:             0.21.1-py36h20b78c2_0              
    pandoc:             1.19.2.1-hea2e7c5_1                
    pandocfilters:      1.4.2-py36ha6701b7_1               
    parmed:             2.7.3-py36_1               acellera
    parso:              0.1.1-py36h35f843b_0               
    pbr:                3.1.1-py36hb5f6b33_0               
    pcmsolver:          1.1.10-py36_0              psi4    
    pcre:               8.41-hc27e229_1                    
    periodictable:      1.5.0-py36_0               acellera
    pexpect:            4.3.0-py36h673ed17_0               
    pickleshare:        0.7.4-py36h63277f8_0               
    pillow:             4.3.0-py36h6f462bf_1               
    pint:               0.7.2-py36_0               acellera
    pixman:             0.34.0-hceecf20_3                  
    pluggy:             0.6.0-py36hb689045_0               
    plumed1:            1.3.2-0                    acellera
    plumed2:            2.3.3+htmd.4-4             acellera
    progress_reporter:  1.4-py_0                   acellera
    prompt_toolkit:     1.0.15-py36h17d85b1_0              
    propka:             3.1.8-py_0                 acellera
    protocolinterface:  0.1.6-py_0                 acellera
    psfgen:             1.6.9-0                    acellera
    psi4:               1.1+add49b9-py36_0         psi4    
    psi4-lt-mp:         1.1-py36_0                 psi4    
    psutil:             5.4.1-py36hecd8e42_0               
    ptyprocess:         0.5.2-py36h69acd42_0               
    py:                 1.5.2-py36h29bf505_0               
    pyemma:             2.4-np112py36_1            acellera
    pygments:           2.2.0-py36h0d3125c_0               
    pympler:            0.5-py36h6b12e4d_0                 
    pyparsing:          2.2.0-py36hee85983_1               
    pyqt:               5.6.0-py36h0386399_5               
    pytables:           3.4.2-np112py36_0                  
    pytest:             3.3.0-py36h23ce9bc_0               
    pyzmq:              16.0.3-py36he2533c7_0              
    qt:                 5.6.2-h974d657_12                  
    rdkit:              2017.09.2.0-py36hf4eed20_1 acellera
    s3transfer:         0.1.11-py36haba1813_1              
    scikit-learn:       0.19.1-py36h7aa7ec6_0              
    scipy:              1.0.0-py36hbf646e7_0               
    simint:             0.7-0                      psi4    
    simplegeneric:      0.8.1-py36h2cb9092_0               
    sip:                4.18.1-py36h51ed4ed_2              
    terminado:          0.6-py36ha25a19f_0                 
    testpath:           0.3.1-py36h8cadb63_0               
    thermotools:        0.2.6-np112py36_1          acellera
    tornado:            4.5.2-py36h1283b2a_0               
    tqdm:               4.19.4-py36ha5a5176_0              
    vina:               1.1.101-0                  acellera
    wcwidth:            0.1.7-py36hdf4376a_0               
    webencodings:       0.5.1-py36h800622e_1               
    widgetsnbextension: 3.0.8-py36h25a1d49_0               
    zeromq:             4.2.2-hbedb6e5_2                   
    zope:               1.0-py36_0                         
    zope.interface:     4.4.3-py36h0ccbf34_0               

acemd-examples   0% |                              | ETA:  --:--:--   0.00  B/s
<progress bars snipped>
acemd-2017.11.  31% |#########                  
CondaError: BlockingIOError(11, 'write could not complete without blocking', 4096)
CondaError: BlockingIOError(11, 'write could not complete without blocking', 4048)
CondaError: BlockingIOError(11, 'write could not complete without blocking', 4048)


--- Logging error ---
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/install.py", line 326, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/plan.py", line 828, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
    cmd(state, arg)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 492, in execute
    self._execute_action(action)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 513, in _execute_action
    raise CondaMultiError(exceptions)
conda.CondaMultiError: BlockingIOError(11, 'write could not complete without blocking', 4096)
BlockingIOError(11, 'write could not complete without blocking', 4048)
BlockingIOError(11, 'write could not complete without blocking', 4048)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.6/logging/__init__.py", line 996, in emit
    self.flush()
  File "/home/travis/miniconda/lib/python3.6/logging/__init__.py", line 976, in flush
    self.stream.flush()
BlockingIOError: [Errno 11] write could not complete without blocking
Call stack:
  File "/home/travis/miniconda/envs/travis-env/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 631, in handle_exception
    print_conda_exception(e)
  File "/home/travis/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 567, in print_conda_exception
    stderrlogger.info("\n%r", exception)
Message: '\n%r'
Arguments: (CondaError: BlockingIOError(11, 'write could not complete without blocking', 4096)
CondaError: BlockingIOError(11, 'write could not complete without blocking', 4048)
CondaError: BlockingIOError(11, 'write could not complete without blocking', 4048)
,)
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking

travis_time:end:071b4426:start=1513549351591698550,finish=1513549376966459059,duration=25374760509
[0K
[31;1mThe command "conda install --file package/htmd-deps/DEPENDENCIES -y" failed and exited with 120 during .[0m
```

**Comment by kalefranz** [comment] 2018-01-05 17:14
Duplicate of https://github.com/conda/conda/issues/6468 and https://github.com/conda/conda/issues/6473.

**Closed by kalefranz** 2018-01-05 17:14 UTC

**Comment by j3mdamas** [comment] 2018-01-10 17:22
Just commenting: https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959 fixed this for me.
