### ISSUE TITLE
PermissionError: [WinError 5]  Acess denied - Creating new environment

### ISSUE THREAD

**Issue by JuantLB** [conda/conda#2742] opened 2016-06-17 15:14 UTC
Traceback (most recent call last):
  File "C:\Users\mm\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\mm\Anaconda3\lib\site-packages\conda\install.py", line 828, in extract
    os.rename(temp_path, path)
PermissionError: [WinError 5] Acesso negado: 'C:\\Users\\mm\\Anaconda3\\pkgs\\menuinst-1.3.2-py27_0.tmp' -> 'C:\\Users\\mm\\Anaconda3\\pkgs\\menuinst-1.3.2-py27_0'

**Comment by knorthover** [comment] 2016-06-17 15:38
Similar problem with a package install after updating conda this morning.  Log and conda info in attached.

[conda_install_issue.txt](https://github.com/conda/conda/files/320801/conda_install_issue.txt)

**Comment by kalefranz** [comment] 2016-06-17 16:30
Pretty sure this is a duplicate of #2687 and #2697, with a fix coming in a few hours with 4.1.2.

**Closed by kalefranz** 2016-06-17 16:30 UTC
