### ISSUE TITLE
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content

### ISSUE THREAD

**Issue by aminrd** [conda/conda#10849] opened 2021-08-09 23:36 UTC
Doing the following scenario: 

```bash
conda create -n env_name
conda activate env_name
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
```

 I interfered the following error on downloading the package which apparently after downloading when checking the checksum, it sees a mismatch. I also tried removing those *.bz2 files just in case if there is a pre-downloaded file, it didn't work.

```bash
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/pytorch/linux-64/torchaudio-0.9.0-py39.tar.bz2'.
  download saved to: /home/amin/anaconda3/pkgs/torchaudio-0.9.0-py39.tar.bz2
  expected md5: 7224453f68125005e034cb6646f2f0a3
  actual md5: 6bbb8056603453427bbe4cca4b033361

ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/pytorch/linux-64/torchvision-0.10.0-py39_cu111.tar.bz2'.
  download saved to: /home/amin/anaconda3/pkgs/torchvision-0.10.0-py39_cu111.tar.bz2
  expected md5: 78b4c927e54b06d7a6d18eec8b3f2d18
  actual md5: 69dd8411c573903db293535017742bd9
```

My system information:
```
Linux SPOT-Server 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

My `conda --version` is also `4.8.2`. I also should add that I have same issue on Windows having `conda --version` equal to `4.10.1`.

I also downloaded the links manually using `wget` and calculated the checksums manually using `md5sum` and in both cases, the computed checksum was equal to the `expected md5` mentioned in the `CheckSum` error.

**Comment by Javier-Jimenez99** [comment] 2021-08-10 10:34
I have the same error with pytorch.

**Comment by jezdez** [comment] 2021-08-10 12:37
This is a duplicate of #10848, please open a ticket in the Pytorch issue tracker.

**Closed by jezdez** 2021-08-10 12:37 UTC
