### ISSUE TITLE
Not able to activate new environment with conda

### ISSUE THREAD

**Issue by mdivk** [conda/conda#7845] opened 2018-10-10 18:31 UTC
I am using Anaconda 4.4.10
I created env as below, using the following two methods mentioned in the official document:
https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands

`conda create --name myenv`
and
`conda env create -f environment.yml`

Now I have two new env: py36 and rxie-env

> $ conda env list
> py36 /home/hadoopuser/.conda/envs/py36
> rxie-env /home/hadoopuser/.conda/envs/rxie-env
> base * /opt/cloudera/parcels/Anaconda
> 
> I am not able to activate either of them, below is the detail:
> CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
> If your shell is Bash or a Bourne variant, enable conda for the current user with
> 
> $ echo ". /opt/cloudera/parcels/Anaconda/etc/profile.d/conda.sh" >> ~/.bashrc
> or, for all users, enable conda with
> 
> $ sudo ln -s /opt/cloudera/parcels/Anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
> The options above will permanently enable the 'conda' command, but they do NOT
> put conda's base (root) environment on PATH. To do so, run
> 
> $ conda activate
> in your terminal, or to put the base environment on PATH permanently, run
> 
> $ echo "conda activate" >> ~/.bashrc
> Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
> your ~/.bashrc file. You should manually remove the line that looks like
> ...........
> export PATH="/opt/cloudera/parcels/Anaconda/bin:$PATH"
> ^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^

I already tried:
1. echo "conda activate" >> ~/.bashrc
2. source ~/.bashrc: not mentioned in the prompt but I think it is needed
3. remove export PATH="/opt/cloudera/parcels/Anaconda/bin:$PATH"

I got new error prompted in the output below:

> -bash: /home/jhelmus/workspace/misc/cdh_parcel/anaconda/scripts/parcel/tmp/Anaconda-5.1.0/bin/conda: No such file or directory

So what it the secret command to activate an environment?
Thank you very much.

**Comment by nehaljwani** [comment] 2018-10-14 05:28
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/10179

**Closed by nehaljwani** 2018-10-14 05:28 UTC
